envoyproxy/envoy

test/common/buffer/BUILD
test/common/buffer/buffer_speed_test.cc

Description: Convert buffer_speed_test to benchmark cc binary and test framework
Testing: n/a

[test] Convert buffer_speed_test to benchmark cc binary and test framework

---

source/common/network/dns_impl.cc

Description: Fixes comments in dns comments in that refers to old code
Testing: N/A

network: fix dns impl comments

---

docs/root/configuration/observability/access_log.rst
include/envoy/stream_info/stream_info.h
source/server/connection_handler_impl.cc
test/config/utility.cc
test/config/utility.h
test/extensions/filters/network/direct_response/direct_response_integration_test.cc
test/integration/BUILD
test/integration/filter_manager_integration_test.cc
test/integration/http_integration.cc
test/integration/http_integration.h
test/integration/integration.cc
test/integration/integration.h

Description:
- add filter chain not found response code details
- test response flag and details for filter chain not found
- test direct response details
Testing: done
Docs Changes: done

access log: tests for response code details

---

source/common/buffer/buffer_impl.cc

Description: Add static_cast<size_t> to code that constructs RawSlice from BufferImpl Slices to fix 32-bit Envoy build broken by #10381.  This should be a no-op for 64-bit platforms where both uint64_t and size_t are 64-bit unsigned types.  It is safe in 32-bit platforms because the value being cast is a size of a contiguous buffer and is therefore guaranteed to fit in size_t.
Testing: n/a

[buffer] Add temporary static_cast<size_t> when constructing RawSlices in Buffer::OwnedImpl to fix 32-bit Envoy mobile builds.

---

docs/root/intro/deprecated.rst
include/envoy/http/codec.h
include/envoy/http/filter.h
include/envoy/http/header_map.h
include/envoy/server/admin.h
source/common/http/codec_wrappers.h
source/common/http/conn_manager_impl.h
source/common/http/headers.h
source/common/http/http1/codec_impl.cc
source/common/http/http1/codec_impl.h
source/common/http/http2/codec_impl.h
source/extensions/quic_listeners/quiche/envoy_quic_client_stream.h
source/extensions/quic_listeners/quiche/envoy_quic_server_stream.h
source/extensions/stat_sinks/hystrix/hystrix.cc
source/extensions/stat_sinks/hystrix/hystrix.h
source/server/http/BUILD
source/server/http/admin.cc
source/server/http/admin.h
test/common/http/http2/codec_impl_test.cc
test/extensions/quic_listeners/quiche/envoy_quic_client_stream_test.cc
test/extensions/quic_listeners/quiche/envoy_quic_server_stream_test.cc
test/extensions/stats_sinks/hystrix/BUILD
test/extensions/stats_sinks/hystrix/hystrix_integration_test.cc
test/extensions/stats_sinks/hystrix/hystrix_test.cc
test/integration/fake_upstream.h
test/integration/integration_test.cc
test/mocks/http/mocks.h
test/mocks/http/stream_encoder.cc
test/mocks/http/stream_encoder.h
test/mocks/server/mocks.h

Fixes https://github.com/envoyproxy/envoy/issues/9749
Testing: Modified test and new Hystrix integration test

http: remove magic :no-chunks header

---

source/extensions/filters/http/aws_lambda/aws_lambda_filter.cc
test/extensions/filters/http/aws_lambda/BUILD
test/extensions/filters/http/aws_lambda/aws_lambda_filter_integration_test.cc
test/extensions/filters/http/aws_lambda/aws_lambda_filter_test.cc

Description:
Fix Lambda integration test.
Testing: unit/integration tests

AWS Lambda integration test fix

---

source/common/common/utility.cc

Description:
Fix flaky h1_capture_persistent_fuzz_test at my branch
Testing:
Docs Changes:
Release Notes:

getDefaultDateFormat static init pattern

---

tools/api_proto_plugin/traverse.py
tools/api_proto_plugin/type_context.py
tools/type_whisperer/type_whisperer.py
tools/type_whisperer/typedb_gen.py
tools/type_whisperer/types.proto

Reverts envoyproxy/envoy#10571 which broke format check on master (and affect PRs)

Revert "tools: enhance type DB to span frozen/active major versions."

---

tools/gen_compilation_database.py

compdb: add missed query

---

api/envoy/api/v2/core/config_source.proto
api/envoy/config/core/v3/config_source.proto
docs/root/configuration/security/secret.rst
docs/root/intro/arch_overview/security/ssl.rst
docs/root/intro/version_history.rst
generated_api_shadow/envoy/api/v2/core/config_source.proto
generated_api_shadow/envoy/config/core/v3/config_source.proto

Adds documentation for #10163.
Signed-off-by: Tero Saarni <tero.saarni@est.tech>

doc: certificate hot-reload for xDS gRPC connection

---

test/extensions/common/proxy_protocol/proxy_protocol_regression_test.cc

build: fix merge conflict with addAcceptFilter().

---

docs/root/intro/version_history.rst
source/server/server.cc

This shouldn't be a warning as it confuses operators.
Testing: None

server: downgrade SIGUSR1 log message into info and clarify

---

api/envoy/api/v2/core/protocol.proto
api/envoy/config/core/v3/protocol.proto
generated_api_shadow/envoy/api/v2/core/protocol.proto
generated_api_shadow/envoy/config/core/v3/protocol.proto

Description: fixes idle timeout docs
Testing: N/A

docs:  correct idle timeout docs

---

windows/.bazelrc

ci: try fix windows oom

---

docs/root/configuration/http/http_filters/grpc_web_filter.rst

Description: fix broken link in grpc-web filter docs
Testing: built docs locally
Docs Changes: update broken link

docs: fix broken link

---

.azure-pipelines/bazel.yml
.azure-pipelines/pipelines.yml
ci/do_ci.sh

ci: unblock

---

.azure-pipelines/bazel.yml
.azure-pipelines/cleanup.sh

ci: remove tools from agent for disk

---

tools/protoxform/protoxform_test_helper.py

Description: remove duplicate test run of `protoxform`

protoxform: remove duplicate test run

---

test/mocks/http/stream_decoder.cc
test/mocks/http/stream_encoder.cc

Causes minor issues in google build.

test: Use gtest ASSERT_NE in test code

---

docs/requirements.txt
tools/deprecate_version/requirements.txt

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fixed #10786 

Changed gitpython version to 3.1.1

---

.circleci/config.yml
ci/do_circle_ci.sh
test/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter_integration_test.cc
test/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter_test.cc

ci: fix coverage

---

docs/root/_static/css/envoy.css

Breaking long word to stop content overflow.

---

.azure-pipelines/cleanup.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: update before purge in cleanup

---

docs/root/configuration/http/http_filters/lua_filter.rst

docs: fix lua typo, missing quote in example

---

bazel/foreign_cc/BUILD
bazel/foreign_cc/zlib.patch
bazel/repositories.bzl

build: fix zlib build for crosscompiling

---

repokitteh.star

repokitteh: allow envoyproxy/api-watchers to monitor API changes.

---

docs/root/version_history/current.rst

Commit Message: add missing release note. 
Testing: n/a
Docs Changes: release note added

Add release note for #10884

---

bazel/repositories.bzl
bazel/repository_locations.bzl

Add NIST CPE IDs to Envoy dependencies.
Risk Level: Low (build flags only)

build: Add NIST CPE IDs of envoy dependencies

---

docs/root/faq/api/control_plane.rst
docs/root/faq/api/control_plane_version_support.rst
docs/root/faq/api/why_versioning.rst
docs/root/faq/overview.rst

* Elaborate on what we gained from v3.
* Explain how to rollout control plane changes.

docs: some additional v3 FAQ entries.

---

.azure-pipelines/cleanup.sh

ci: no upgrade in cleanup script

---

bazel/repository_locations.bzl

ci: add envoy-build-tools sha256sum

---

bazel/repositories.bzl
bazel/repository_locations.bzl

build: enforce non-empty SHA256 for dependency pinning.

---

docs/root/faq/load_balancing/disable_circuit_breaking.rst
docs/root/faq/overview.rst
docs/root/faq/performance/how_fast_is_envoy.rst
docs/root/faq/performance/how_to_benchmark_envoy.rst

docs: FAQ on benchmarking best practices.

---

SECURITY.md

docs: update to security process for low severity bugfixes

---

docs/root/intro/arch_overview/http/upgrades.rst

docs: fix file path

---

source/common/http/http1/BUILD
source/common/http/http1/codec_impl.cc
source/common/http/http1/codec_impl.h

This reverts commit 3550a7a7b0b858f4c2ac505efa6c71c2610f2666. (#11101)
Not to be merged until #10878 actions are complete.

Revert "[http] Remove exceptions from HTTP/1 codec callbacks (#11101)"

---

.bazelci/presubmit.yml

bazelci: add coverage

---

bazel/repository_locations.bzl

build: update envoy-build-tools

---

bazel/repository_locations.bzl

tls: update BoringSSL to 107c03cf (4103).

---

PULL_REQUESTS.md
docs/root/start/sandboxes/fault_injection.rst

Commit Message: Fixing breaking link issues and typos
Testing: format and integration
Docs Changes:Yes
Release Notes:
[Optional Fixes #11215 

fixing typos and breaking link issues

---

test/integration/protocol_integration_test.cc

http: testing 304-with-body behavior

---

CONTRIBUTING.md
docs/root/version_history/current.rst
tools/code_format/check_format.py
tools/testdata/check_format/version_history/current.rst

This attempts to make it easier when upgrading to understand the
changes in the release and how they will affect a given deployment.
Related: #11211

docs: break release notes into categories

---

.bazelci/presubmit.yml

bazelci: no rbe for coverage

---

docs/root/configuration/upstream/cluster_manager/cluster_stats.rst

Commit Message: clarify upstream_rq_pending_failure_eject stat 
Additional Description: Refer https://github.com/envoyproxy/envoy/issues/11237
Testing: N/a
Fixes #11237

docs: clarify upstream_rq_pending_failure_eject stat 

---

test/common/config/subscription_factory_impl_test.cc

test: fix merge race in #11223.

---

test/common/upstream/health_checker_impl_test.cc

Added allocHealthChecker and addCompletionCallback method  in TestHttpHealthCheckerImpl, TestProdHttpHealthchecker, TcpHealthCheckerImpl and TestGrpcHealthCheckerImpl.  
Risk Level:
Testing:
Docs Changes:
Release Notes:
includes partial fix to  #11109

health: Refactored health_checker tests.

---

.azure-pipelines/linux.yml
bazel/README.md
tools/bazel.rc

- Fixes latest coverage report location too

tech-debt: delete unused files

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/setup.sh
tools/vscode/refresh_compdb.sh

devex: several fix for devcontainer

---

docs/root/intro/arch_overview/security/google_vrp.rst

docs: clarify VRP starts at 1.15.0.

---

api/envoy/extensions/compression/gzip/decompressor/v3/gzip.proto
generated_api_shadow/envoy/extensions/compression/gzip/decompressor/v3/gzip.proto
source/extensions/filters/http/decompressor/decompressor_filter.cc

Commit Message: decompressor - fix logs and docs
Additional Description: noticed a couple stale things that got merged in #11172.
Docs Changes: updated

decompressor: fix logs and docs

---

bazel/README.md

docs: fixing broken link

---

docs/root/intro/arch_overview/upstream/circuit_breaking.rst
docs/root/intro/arch_overview/upstream/connection_pooling.rst

I've has a few questions on how this works and how active connection
limits and stats relate. After doing some spelunking this seems to be
the story.

docs: clarify circuit breaker and H2 conn pool behavior.

---

ci/mac_ci_setup.sh

ci: fix mac bazelisk

---

ci/mac_ci_setup.sh

ci: fix mac bazelisk (#11444)

---

docs/root/version_history/v1.12.4.rst
docs/root/version_history/v1.13.2.rst
docs/root/version_history/v1.14.2.rst
docs/root/version_history/version_history.rst

docs: add 1.12.4, 1.13.2 and 1.14.2 release notes.

---

test/common/upstream/eds_speed_test.cc

This shows that the EDS onConfigUpdate() is 2-3x slower when working
with v2 config and doing version conversion with original version
recovery. Followup PRs will optimize.
Relates to #11362 and #10875.
Testing: Ran benchmark with -c opt binary.

eds_speed_test: support v2/v3 variants of config.

---

ci/run_envoy_docker.sh

Commit Message: feat(ci): add NO_PROXY and BAZELISK_BASE_URL env in ci/run_envoy_docker.sh
Testing:
Docs Changes:
Release Notes:

feat(ci): add NO_PROXY and BAZELISK_BASE_URL env in ci/run_envoy_docker.sh

---

ci/do_ci.sh

Signed-off-by: Ranjith Kumar <ranjith.dakshana2015@gmail.com>
Commit Message: ci: fix collect_build_profile to copy gzipped file
Testing:
Docs Changes:
Release Notes:

ci: fix collect_build_profile

---

include/envoy/http/filter.h
source/common/upstream/health_checker_impl.h
source/extensions/filters/common/rbac/matchers.h
source/server/listener_impl.h
source/server/server.h

style: fix Doxygen style

---

bazel/dependency_imports.bzl
bazel/repository_locations.bzl

build: update several go dependencies

---

source/server/listener_manager_impl.cc

Commit Message: listener manager: fix typo
Testing:
Docs Changes:
Release Notes:

listener manager: fix typo

---

docs/root/configuration/http/http_filters/lua_filter.rst

Commit Message: correct dynamicMetadata example
Risk Level:
Testing:
Docs Changes: correct dynamicMetadata example
Release Notes:

docs: correct dynamicMetadata example

---

include/envoy/common/BUILD
include/envoy/common/conn_pool.h
include/envoy/http/conn_pool.h
include/envoy/tcp/conn_pool.h

conn_pool: unifying drain interfaces

---

docs/root/faq/debugging/why_is_envoy_404ing_connect_requests.rst
docs/root/faq/overview.rst

Risk Level: n/a (docs)
Testing: n/a (docs)
Fixes #11552

docs: adding a connect matcher faq

---

source/docs/flow_control.md

Commit Message:  fix description of flow control
Docs Changes: This pull request fixes typos and the descriptions about calling readDisable on high/low watermarks.

docs: fix description of flow control

---

.devcontainer/devcontainer.json

Commit Message: devex: add Python settings
Testing: Low
Docs Changes: Low
Release Notes: Low

devex: add Python settings

---

bazel/EXTERNAL_DEPS.md

Commit Message: docs: fix link in external dependency documentation
Testing: N/A

docs: fix link in external dependency documentation

---

api/envoy/service/status/v3/csds.proto
api/envoy/service/status/v4alpha/csds.proto
generated_api_shadow/envoy/service/status/v3/csds.proto
generated_api_shadow/envoy/service/status/v4alpha/csds.proto

add EDS config to csds proto.
EDS config has been added to [config_dump](https://github.com/envoyproxy/envoy/blob/master/api/envoy/admin/v3/config_dump.proto#L355) in #11425  and implemented in #11577 .
Testing: N/A
Signed-off-by: Yutong Li <yutongli@google.com>
/cc @fuqianggao @alexburnos

api: add eds config to csds proto

---

test/common/event/dispatcher_impl_test.cc

Commit Message: dispatcher: Tests to capture low-level timer behavior
Risk Level: n/a test only changes
Testing: unit

[dispatcher] Tests to capture low-level timer behavior

---

test/mocks/event/mocks.cc
test/mocks/router/mocks.cc

Add required using declarations for testing::DoAll to avoid relying on ADL
Risk Level: Low (test only)

test: Add required using declarations for testing::DoAll

---

bazel/repository_locations.bzl

Risk Level:
Testing:
Docs Changes:
Release Notes:

bump re2 for wasm build

---

test/integration/integration.cc
test/integration/integration.h

test: cleaning up teardown

---

include/envoy/router/router.h
source/common/router/upstream_request.cc
source/common/router/upstream_request.h
source/extensions/upstreams/http/http/upstream_request.cc
source/extensions/upstreams/http/http/upstream_request.h
source/extensions/upstreams/http/tcp/upstream_request.cc
source/extensions/upstreams/http/tcp/upstream_request.h
test/extensions/upstreams/http/tcp/upstream_request_test.cc
test/mocks/router/mocks.cc
test/mocks/router/mocks.h

Risk Level: Low (API change)
Testing: n/a

upstream: cleaning up APIs

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Commit Message: devex: set CLANG_FORMAT
Testing: N/A

devex: set CLANG_FORMAT

---

.devcontainer/devcontainer.json

Commit Message: devex: fix Python settings
Additional Description: It needs `--` to work correctly
Testing: N/A

devex: fix Python settings

---

tools/code_format/check_format.py

Commit Message: format: compile regexs
Testing: N/A

format: compile regexs

---

api/envoy/config/filter/network/client_ssl_auth/v2/client_ssl_auth.proto
api/envoy/extensions/filters/network/client_ssl_auth/v3/client_ssl_auth.proto
docs/root/configuration/listeners/network_filters/client_ssl_auth_filter.rst
docs/root/version_history/current.rst
generated_api_shadow/envoy/config/filter/network/client_ssl_auth/v2/client_ssl_auth.proto
generated_api_shadow/envoy/extensions/filters/network/client_ssl_auth/v3/client_ssl_auth.proto
source/common/network/BUILD
source/common/network/cidr_range.cc
source/common/network/cidr_range.h
source/extensions/filters/network/client_ssl_auth/client_ssl_auth.cc
source/extensions/filters/network/client_ssl_auth/client_ssl_auth.h
test/common/network/BUILD
test/common/network/cidr_range_test.cc
test/common/stats/tag_extractor_impl_test.cc
test/extensions/filters/network/client_ssl_auth/client_ssl_auth_test.cc
test/extensions/filters/network/ratelimit/config_test.cc

Also clean up some dead code.
Part of https://github.com/envoyproxy/envoy/issues/11596
Testing: Existing/modified tests

client_ssl_auth: update to use inclusive language

---

docs/root/configuration/http/http_filters/compressor_filter.rst

Commit Message: fix http filter compressor name in example
Additional Description: fix example
Testing: n/a
Docs Changes: example change

docs: fix http filter compressor name in example

---

source/common/upstream/upstream_impl.cc
source/common/upstream/upstream_impl.h

This was a leftover of #11086.

upstream: remove unused code

---

include/envoy/http/header_map.h
test/common/http/header_map_impl_test.cc

test: add explicit test for custom registered headers

---

api/envoy/config/cluster/redis/redis_cluster.proto
api/envoy/config/filter/network/redis_proxy/v2/redis_proxy.proto
api/envoy/extensions/clusters/redis/v3/redis_cluster.proto
api/envoy/extensions/filters/network/redis_proxy/v3/redis_proxy.proto
docs/root/intro/arch_overview/intro/threading_model.rst
docs/root/intro/arch_overview/other_protocols/redis.rst
generated_api_shadow/envoy/config/cluster/redis/redis_cluster.proto
generated_api_shadow/envoy/config/filter/network/redis_proxy/v2/redis_proxy.proto
generated_api_shadow/envoy/extensions/clusters/redis/v3/redis_cluster.proto
generated_api_shadow/envoy/extensions/filters/network/redis_proxy/v3/redis_proxy.proto
source/extensions/clusters/redis/redis_cluster.cc
source/extensions/clusters/redis/redis_cluster.h
source/extensions/clusters/redis/redis_cluster_lb.cc
source/extensions/clusters/redis/redis_cluster_lb.h
source/extensions/filters/network/common/redis/client.h
source/extensions/filters/network/common/redis/client_impl.cc
source/extensions/health_checkers/redis/redis.h
test/extensions/clusters/redis/redis_cluster_integration_test.cc
test/extensions/clusters/redis/redis_cluster_lb_test.cc
test/extensions/clusters/redis/redis_cluster_test.cc
test/extensions/filters/network/common/redis/client_impl_test.cc
test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc

Part of https://github.com/envoyproxy/envoy/issues/11596

redis: update to use inclusive language

---

test/common/router/config_impl_test.cc

Signed-off-by: knight42 <anonymousknight96@gmail.com>
Commit Message: fix PathRedirectQueryNotPreserved test
Additional Description: fix the PathRedirectQueryNotPreserved test introduced in #11493. I forgot to push local changes. I am really sorry about that 😭
Risk Level:
Docs Changes:
Release Notes:

test(router): fix PathRedirectQueryNotPreserved test

---

test/integration/cx_limit_integration_test.cc

Should fix the asan failure in https://github.com/envoyproxy/envoy/issues/11841#issuecomment-652467061
Testing: n/a
Helps one failure on #11841

test: fixing an integration test flake

---

test/integration/http2_integration_test.cc
test/integration/integration.cc
test/integration/integration.h

Part of https://github.com/envoyproxy/envoy/issues/11801
Testing: Fixed test

test: fix http2_integration_test flake

---

test/integration/cx_limit_integration_test.cc

Pulling out a 5s wait in many runs.
Testing: n/a

test: speeding up a test from 80s to 3s

---

.bazelci/presubmit.yml

Testing: https://buildkite.com/bazel/envoy/builds/1213
Fixes #11400

bazelci: fix bazel CI with coverage

---

test/integration/filter_manager_integration_test.cc

test: deflaking filter manager integration test

---

test/common/stats/BUILD
test/common/stats/thread_local_store_speed_test.cc
test/extensions/filters/http/common/compressor/BUILD
test/extensions/filters/http/common/compressor/compressor_filter_speed_test.cc

Commit Message: test: Convert compressor_filter_speed_test and thread_local_store_speed_test to benchmark cc binary and test framework
Risk Level: n/a, test only
Testing: new benchmark tests

test: Convert compressor_filter_speed_test and thread_local_store_speed_test to benchmark cc binary and test framework

---

include/envoy/router/route_config_update_receiver.h

Fix incorrect reference to v2 RouteConfiguration

---

bazel/repository_locations.bzl

Risk Level:
Testing:
Docs Changes:
Release Notes:

re2: bump 2020-07-06

---

RELEASES.md

While there, update details for v1.15.x releases.

docs: Yuchen Dai to manage stable releases in 2020 Q3.

---

tools/deprecate_version/deprecate_version.py

Fixing the check for preexisting bugs.
Risk Level: n/a (tooling)

tooling: fixing bug tracker

---

test/common/network/BUILD
test/common/router/BUILD
test/common/upstream/BUILD
test/extensions/common/aws/BUILD
test/extensions/filters/http/cors/BUILD
test/extensions/filters/http/router/BUILD
test/extensions/filters/network/rbac/BUILD
test/extensions/transport_sockets/alts/BUILD
test/integration/BUILD
test/server/BUILD

Hopefully getting the windows CI to be more green while we sort out operation system differences
cc @sunjayBhatia

test: rollback #11741

---

test/integration/run_envoy_test.sh
test/integration/test_utility.sh

Additional Description: This is a noop change for the most part, mostly a clean-up making internal import saner.

test: fix path quotes

---

source/common/common/random_generator.h

Adds an include guard.
Signed-off-by: Otto van der Schaaf <oschaaf@we-amp.com>

Add pragma once to random_generator.h

---

GOVERNANCE.md

docs: updating rotation calendar links

---

.bazelrc
test/integration/BUILD
test/per_file_coverage.sh

ci: temproray disable vhds_integration_test in TSAN

---

.bazelrc
.circleci/config.yml
.devcontainer/Dockerfile
bazel/repository_locations.bzl

* Updated envoy-build-ubuntu image tag
* Updated envoy-build-tools
Signed-off-by: Dmitri Dolguikh <ddolguik@redhat.com>
Testing: N/A

Updated envoy-build-ubuntu image tag

---

.azure-pipelines/pipelines.yml

ci: toplevel download on macOS

---

test/common/tcp_proxy/tcp_proxy_test.cc
test/common/upstream/cluster_manager_impl_test.cc
test/common/upstream/utility.h
test/server/configuration_impl_test.cc
test/test_common/utility.h

Commit Message: V2 to V3 changes for parseFoofromV2json 
Risk Level: NA
Testing: unit and format
Release Notes:
Optional Fixes #10843 

V2 v3 changes for parse foo from v2 json

---

docs/root/install/sandboxes/local_docker_build.rst

Corrected the command to build an envoy docker image from source.
Signed-off-by: Yosry Ahmed <yosryahmed@google.com>
Testing: N/A
Docs Changes: Building an Envoy Docker image - Updated step 2 

Docs: corrected outdated command

---

include/envoy/filesystem/filesystem.h
include/envoy/thread/thread.h
source/exe/platform_impl.h

Commit Message: format: use type alias
Testing: N/A
Part of #11634

format: use type alias

---

source/common/upstream/eds.cc

Commit Message: change eds cluster factory comments
Testing: N/A

eds: change eds cluster factory comments

---

test/integration/hds_integration_test.cc

Part of https://github.com/envoyproxy/envoy/issues/12184
Testing: N/A

hds: fix integration test flakes

---

test/per_file_coverage.sh

Risk Level: Medium build breakage risk (coverage changes with every merge)
Testing: local

test: extending directory coverage checks to core code.

---

test/extensions/filters/http/aws_request_signing/aws_request_signing_filter_test.cc
test/per_file_coverage.sh

aws_request_signing: fix coverage

---

test/server/config_validation/BUILD

Until https://github.com/envoyproxy/envoy/issues/12258 is fixed.

test: disable xds_fuzz

---

.azure-pipelines/bazel.yml
.bazelrc
ci/build_setup.sh
ci/do_ci.sh
ci/do_circle_ci.sh

ci: clear some CircleCI tech debts, collect more profile

---

docs/root/configuration/http/http_filters/lua_filter.rst

Commit Message: fix lua type in typed_config in examples
Testing: N/a
Release Notes: N/a

lua: fix type in lua examples

---

test/integration/protocol_integration_test.cc

test: regression testing handling of out of bounds response codes

---

test/integration/integration_test.cc
test/integration/server.h
test/integration/server_stats.h

Fixes https://github.com/envoyproxy/envoy/issues/12325

test: fix PerWorkerStatsAndBalancingFlake

---

test/extensions/filters/network/rbac/integration_test.cc

The write can see disconnect upon completion.
Fixes https://github.com/envoyproxy/envoy/issues/12294
Testing: Existing test

test: fix rbac flake

---

api/envoy/service/extension/v3/config_discovery.proto
generated_api_shadow/envoy/service/extension/v3/config_discovery.proto

proto: workaround for ECDS to be included in api/BUILD

---

source/common/http/conn_manager_impl.cc

Commit Message: Fix merge issue

fix main branch merge snafu

---

docs/root/install/building.rst
docs/root/version_history/current.rst

Follow up to https://github.com/envoyproxy/envoy/pull/11813/files

docs: add more docs on ARM images

---

ci/do_circle_ci.sh

ci: fix adding extra params for CircleCI.

---

test/server/listener_manager_impl_test.cc

build: fix main branch merge issue

---

docs/root/configuration/upstream/cluster_manager/cluster_circuit_breakers.rst

Commit Message: Fix broken yaml indentation
Testing: Compare this <https://github.com/ujihisa/envoy/blob/c687265807990f61572a769ccb9776c0d34d97d3/docs/root/configuration/upstream/cluster_manager/cluster_circuit_breakers.rst> with this <https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_circuit_breakers>
Docs Changes: Fix broken yaml indentation

docs: Fix broken yaml indentation

---

bazel/envoy_build_system.bzl
bazel/envoy_library.bzl

Workaround for #12444, while we figure out a permanent solution.

Make extensions public visible

---

source/extensions/filters/network/rocketmq_proxy/conn_manager.h

rocketmq: small grammar fix

---

test/integration/integration_test.cc

Fixes https://github.com/envoyproxy/envoy/issues/12459

test: fix Response204WithBody flake

---

source/common/upstream/static_cluster.h
source/extensions/stat_sinks/statsd/config.h

Commit Message: add a couple static registration macros
Additional Description: needed for registration in static library environments. 
Testing: local

extensions: add a couple static registration macros

---

include/envoy/http/BUILD
include/envoy/ssl/connection.h
source/common/http/BUILD
source/common/protobuf/well_known.h
source/extensions/common/wasm/BUILD
source/extensions/common/wasm/wasm_vm_base.h
source/extensions/filters/http/dynamo/config.h
source/extensions/filters/http/on_demand/config.h
source/extensions/filters/network/kafka/BUILD
source/extensions/health_checkers/redis/BUILD
source/extensions/quic_listeners/quiche/platform/spdy_string_utils_impl.h

tidy: fix all clang-diagnostic-errors on master

---

source/common/common/basic_resource_impl.h
source/common/filesystem/posix/directory_iterator_impl.cc
source/common/protobuf/utility.cc
source/common/stats/symbol_table_impl.h
source/extensions/filters/network/kafka/serialization.h
source/extensions/quic_listeners/quiche/platform/quic_mem_slice_span_impl.h
test/common/http/conn_manager_impl_test.cc
test/extensions/filters/common/lua/lua_wrappers.h
test/integration/http_subset_lb_integration_test.cc
test/integration/transport_socket_match_integration_test.cc

From: https://dev.azure.com/cncf/envoy/_build/results?buildId=47396&view=results

tidy: fix auto fixable errors

---

bazel/foreign_cc/BUILD
bazel/foreign_cc/luajit.patch
bazel/foreign_cc/moonjit.patch
source/common/network/address_impl.cc
source/common/network/utility.cc
source/extensions/filters/udp/dns_filter/dns_parser.cc
source/extensions/tracers/xray/xray_configuration.h
test/exe/main_common_test.cc
test/extensions/filters/network/postgres_proxy/postgres_decoder_test.cc

There's still a few left (some from curl, some due to lua).

build: fix several use of unintialized value detect by MSAN

---

source/server/admin/admin.cc
source/server/connection_handler_impl.cc
source/server/filter_chain_manager_impl.cc
source/server/listener_manager_impl.cc

Some code optimization:
1. Reduce code repetition:
* In 'admin.cc': There are many times of  ```get()``` from ```absl::optional``` for the same value. Similar for ```host->address()->asString()```. So I merged them together to avoid multiple calls for the same value.
*  Similar problem inside "connection_handler_impl.cc"
2. Adopt pair binding feature in C++ 17. 

Code Optimization

---

include/envoy/stats/stats.h

Commit Message: cleanup: remove unused forward declaration
Testing: bazel test //test/...

cleanup: remove unused forward declaration

---

source/common/http/async_client_utility.cc
source/common/network/filter_matcher.cc
source/common/signal/BUILD
source/common/signal/fatal_error_handler.cc

Commit Message: Add some missing #includes
Signed-off-by: Elisha Ziskind <eziskind@google.com>

Add some missing #includes

---

bazel/foreign_cc/BUILD
bazel/repositories.bzl
bazel/repository_locations.bzl

build: use bazel native yaml-cpp

---

test/integration/http_timeout_integration_test.cc

Fixes https://github.com/envoyproxy/envoy/issues/12653
Testing: 1000 runs clean

test: fix http_timeout_integration_test flake

---

test/integration/protocol_integration_test.cc

Fixes https://github.com/envoyproxy/envoy/issues/12484

test: fix ProtocolIntegrationTest.LargeRequestMethod flake

---

source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc

It is very helpful for debugging.
Signed-off-by: DongRyeol Cha <dr83.cha@samsung.com>
Testing: bazel test

udp: Add some log when session is deleted

---

ci/docker_ci.sh

Testing: Locally with custom prefix, tag and master.

ci: fix docker tag push

---

source/common/upstream/cds_api_impl.cc

Commit Message: cleanup: use structured binding
Testing: bazel test //test/common/upstream/...

cleanup: use structured binding

---

.azure-pipelines/cleanup.sh
.azure-pipelines/pipelines.yml

ci: save more space on azp

---

source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc
source/extensions/filters/listener/proxy_protocol/proxy_protocol.h
test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc

proxy protocol: remove dependency on ioctl and raw fds

---

bazel/repository_locations.bzl

tls: update BoringSSL to 597b8103 (4183).

---

include/envoy/network/io_handle.h
source/common/network/io_socket_handle_impl.h
source/common/network/socket_interface_impl.cc
source/extensions/quic_listeners/quiche/active_quic_listener.cc
source/extensions/quic_listeners/quiche/quic_io_handle_wrapper.h
source/extensions/quic_listeners/quiche/udp_gso_batch_writer.cc
source/extensions/transport_sockets/tls/ssl_socket.cc
source/server/hot_restarting_parent.cc
test/common/network/udp_listener_impl_test.cc
test/extensions/quic_listeners/quiche/quic_io_handle_wrapper_test.cc
test/mocks/network/io_handle.h

- rename fd accessor
- cleaned up udp listener test

network: rename io handle fd accessor

---

restarter/hot-restarter.py
source/server/hot_restarting_parent.cc

Signed-off-by: panzhongxian <panzhongxian0532@gmail.com>
Commit Message: Fix a typo in comment.
Testing: None
Docs Changes: Fix a typo in comment.

Fix a typo in comment.

---

test/integration/tcp_proxy_integration_test.cc

Testing: deflake runs cleanly
Fixes https://github.com/envoyproxy/envoy/issues/12413

test: deflaking tcp proxy integration test

---

api/envoy/api/v2/route/route_components.proto
api/envoy/config/route/v3/route_components.proto
api/envoy/config/route/v4alpha/route_components.proto
generated_api_shadow/envoy/api/v2/route/route_components.proto
generated_api_shadow/envoy/config/route/v3/route_components.proto
generated_api_shadow/envoy/config/route/v4alpha/route_components.proto

route: fix comments

---

source/common/router/rds_impl.cc
test/common/router/rds_impl_test.cc

fix https://github.com/envoyproxy/envoy/issues/12683 , 

fix VHDS not work when vhds config set in first rds update both

---

ci/flaky_test/process_xml.py

Commit Message: Flaky test job fix
Fixes: https://github.com/envoyproxy/envoy/issues/12896
Tested: https://github.com/envoyproxy/envoy/pull/12900
Release job failed (https://dev.azure.com/cncf/envoy/_build/results?buildId=49957&view=logs&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8) and then fixed (https://dev.azure.com/cncf/envoy/_build/results?buildId=50001&view=logs&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8&t=86512d3a-caa5-5e3f-9bce-4070faa3b830) by this

[ci] fix ci build failure

---

source/common/common/backoff_strategy.cc
source/common/common/backoff_strategy.h
source/common/router/retry_state_impl.cc
test/common/common/backoff_strategy_test.cc
test/common/router/retry_state_impl_test.cc

Commit Message: common: handle divide by zero in backoff strategy
Testing: Additional unit tests.

common: handle divide by zero in backoff strategy

---

CONTRIBUTING.md
source/docs/repokitteh.md

Thanks for adding `retest` for non-maintainers :). 
Commit Message: Updated docs regarding retest and retest-circle.
Testing: n/a

[docs]: updated docs regarding retest and retest-circle.

---

test/server/BUILD

Risk Level: Low - bazel-only change
Testing:
Docs Changes:
Release Notes:

fix build from uncaught merge conflict in #12811

---

source/extensions/filters/http/ext_authz/ext_authz.h

Commit Message: cleanup: remove unused enum
Testing: bazel test //test/extensions/filters/http/ext_authz/... , //test/extensions/filters/common/...

cleanup: remove unused enum

---

api/envoy/config/cluster/v3/cluster.proto
api/envoy/config/cluster/v4alpha/cluster.proto
generated_api_shadow/envoy/config/cluster/v3/cluster.proto
generated_api_shadow/envoy/config/cluster/v4alpha/cluster.proto

* grammar fix
* small style fix splitting sentence up

api: fix comment for PrefetchPolicy

---

test/extensions/filters/http/dynamic_forward_proxy/BUILD
test/extensions/filters/http/dynamic_forward_proxy/config_test.cc
test/per_file_coverage.sh

Commit Message: increase dynamic forward proxy coverage.
Additional Description: deletes the per file coverage bar
Testing: added tests

coverage: increase dynamic forward proxy filter coverage

---

bazel/repository_locations.bzl
repokitteh.star

repokitteh: tag envoyproxy/dependency-watchers on relevant files.

---

docs/root/_static/searchtools.js

Commit Message: This imports searchtools.js from https://raw.githubusercontent.com/sphinx-doc/sphinx/3.x/sphinx/themes/basic/static/searchtools.js.
Additional Description: https://github.com/envoyproxy/envoy/pull/13005#discussion_r484918969
Testing: CI docs build
Release Notes:  N/A
Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

docs: Import searchtools.js

---

api/envoy/config/route/v3/route_components.proto
api/envoy/config/route/v4alpha/route_components.proto
api/envoy/extensions/filters/http/adaptive_concurrency/v3/adaptive_concurrency.proto
generated_api_shadow/envoy/config/route/v3/route_components.proto
generated_api_shadow/envoy/config/route/v4alpha/route_components.proto
generated_api_shadow/envoy/extensions/filters/http/adaptive_concurrency/v3/adaptive_concurrency.proto
test/common/router/route_corpus/Response_headers_to_remove
test/common/router/route_corpus/clusterfuzz-testcase-route_fuzz_test-5671270751141888
test/extensions/filters/http/adaptive_concurrency/adaptive_concurrency_filter_test.cc
test/extensions/filters/http/common/fuzz/filter_corpus/clusterfuzz-testcase-filter_fuzz_test-5728684315770880

Commit Message: Added validations for WeightedCluster and AdaptiveConcurrency
Testing: N/A

[fuzz] Added validations for WeightedCluster and AdaptiveConcurrency

---

test/per_file_coverage.sh

Commit Message: Fix source/server coverage, low on main branch.

[ci] lower server coverage

---

test/common/upstream/load_balancer_benchmark.cc

Commit Message: test: skip expensive load balancer benchmarks when running in test mode.
Additional Description: benchmark test under tsan now runs in 36sec, down from 481sec
Risk Level: n/a (test-only changes)
Testing: n/a
Fixes #13099

test: skip expensive load balancer benchmarks when running in test mode.

---

source/extensions/filters/common/lua/wrappers.cc
test/extensions/filters/http/lua/lua_filter_test.cc
test/per_file_coverage.sh

  test: improving lua coverage

---

test/common/event/dispatcher_impl_test.cc
test/common/memory/heap_shrinker_test.cc
test/extensions/filters/http/adaptive_concurrency/controller/gradient_controller_test.cc
test/extensions/filters/network/common/fuzz/uber_readfilter.cc
test/extensions/filters/network/common/fuzz/uber_writefilter.cc
test/extensions/quic_listeners/quiche/active_quic_listener_test.cc
test/extensions/quic_listeners/quiche/envoy_quic_alarm_test.cc
test/extensions/quic_listeners/quiche/envoy_quic_dispatcher_test.cc
test/extensions/quic_listeners/quiche/envoy_quic_server_session_test.cc
test/server/server_test.cc
test/test_common/BUILD
test/test_common/simulated_time_system.cc
test/test_common/simulated_time_system_test.cc
test/test_common/test_time_system.h

Commit Message: test: replace advanceTimeAsync with advanceTimeAndRun
Following up from https://github.com/envoyproxy/envoy/pull/12609#discussion_r476623905
Risk Level: n/a, test only changes
Testing: n/a test API changes
/cc @mattklein123

test: replace advanceTimeAsync with advanceTimeAndRun

---

source/extensions/filters/http/buffer/config.h

Commit Message: buffer filter - add static declaration macro
Additional Description: needed for static libraries using envoy.
Testing: n/a

buffer filter: add static declaration macro

---

test/common/router/corpus_from_config_impl.sh
test/common/runtime/filesystem_setup.sh
test/config/integration/certs/certs.sh
test/exe/build_id_test.sh
test/exe/envoy_static_test.sh
test/exe/pie_test.sh
test/exe/version_out_test.sh
test/extensions/filters/network/thrift_proxy/driver/generate_bindings.sh
test/extensions/filters/network/thrift_proxy/driver/generate_fixture.sh
test/extensions/transport_sockets/tls/ocsp/gen_unittest_ocsp_data.sh
test/extensions/transport_sockets/tls/test_data/certs.sh
test/integration/hotrestart_test.sh
test/integration/run_envoy_test.sh
test/integration/test_utility.sh
test/per_file_coverage.sh
test/run_envoy_bazel_coverage.sh
test/tools/router_check/test/route_tests.sh
tools/code_format/check_shellcheck_format.sh

Commit Message: Shellcheck test/
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Partial fix for #7793 

Shellcheck: test/

---

test/common/event/dispatcher_impl_test.cc

Commit Message: test: fix comments in dispatcher_impl_test
Testing: n/a

test: fix comments in dispatcher_impl_test

---

ci/build_setup.sh
ci/do_ci.sh
ci/do_circle_ci.sh
ci/docker-entrypoint.sh
ci/docker_ci.sh
ci/docker_rebuild_google-vrp.sh
ci/envoy_build_sha.sh
ci/filter_example_setup.sh
ci/flaky_test/run_process_xml.sh
ci/mac_ci_steps.sh
ci/run_clang_tidy.sh
ci/run_envoy_docker.sh
ci/run_envoy_docker_windows.sh
ci/setup_cache.sh
ci/upload_gcs_artifact.sh
ci/windows_ci_steps.sh
tools/code_format/check_shellcheck_format.sh

Commit Message: Shellcheck: ci/
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Partial fix for #7793 

Shellcheck: ci/

---

OWNERS.md

maintainers: welcome Antonio!

---

source/common/event/dispatcher_impl.cc

Commit Message: Fixed yoda style code.
Testing:

yoda style code fix.

---

GOVERNANCE.md

Commit Message: Update the spelling of external on the governance readme.
Testing: None
Docs Changes: This is a doc change and not anything to do with the code itself.

docs: minor spelling update to GOVERNANCE.md

---

.bazelci/presubmit.yml

bazelci: remove gcc job

---

source/extensions/filters/http/oauth2/filter.cc

Commit Message: oauth: fix typos in response code details

oauth: fix typos in response code details

---

api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
api/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto
docs/root/configuration/overview/extension.rst
generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto

Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: minor edits in extension config section

---

.gitignore

Commit Message: git: Add *~ to gitignore
be nice to emacs users 8)
Testing: n/a
Release Notes:

git: Add *~ to gitignore

---

source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc

Commit Message: ext_authz: optimize header traversal in http client
Additional Description: Use the new HeaderMap::getAll() instead of HeaderMap::iterate() to avoid O(n) traversal of all the headers.
Testing: All existing tests passing. The case of multiple entries for the same header key is covered in existing tests.

ext_authz: optimize header traversal in http client

---

docs/root/configuration/observability/access_log/usage.rst
docs/root/version_history/current.rst

Commit Message: follow-up to https://github.com/envoyproxy/envoy/pull/13156
Risk Level:
Testing:
Docs Changes:

docs: add note for CONNECTION_ID

---

source/extensions/retry/priority/previous_priorities/previous_priorities.cc

Fix missing case of -Wrange-loop-analysis

---

docs/root/about_docs.rst
docs/root/index.rst

docs: move version history to last

---

docs/root/configuration/http/http_conn_man/stats.rst

Fixes #3077.
Commit Message: docs: update conn mgr stats
Testing: n/a

docs: update conn mgr stats

---

source/common/upstream/resource_manager_impl.h

Commit Message: update comment to reflect the correct base class
Testing: n/a

update comment to reflect the correct base class

---

.azure-pipelines/pipelines.yml
ci/flaky_test/run_process_xml.sh
ci/flaky_test/run_process_xml_mac.sh
ci/mac_ci_setup.sh

ci: use same flaky test process script on macOS

---

README.md

Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
Commit Message: build: update ppc64le CI build status shield
Testing: N/A

build: update ppc64le CI build status shield

---

include/envoy/common/conn_pool.h
source/common/conn_pool/conn_pool_base.cc
source/common/conn_pool/conn_pool_base.h

Risk Level: n/a (comment + rename)
Testing: n/a
Fixes #13369

conn_pool: fixing comments

---

ci/mac_ci_setup.sh

ci: workaround for actions/virtual-environments#1811

---

OWNERS.md

Many dependency bumps later :)

owners: add @moderation as a Friend of Envoy.

---

examples/wasm/BUILD

wasm: fix building Wasm example.

---

.bazelrc
ci/do_ci.sh
test/common/network/connection_impl_test.cc

remove asan workaround

---

docs/root/intro/arch_overview/http/upgrades.rst

docs: updating config links

---

.bazelrc

bazel: add --config=remote-asan with vptr checks.

---

ci/do_ci.sh
ci/repokitteh/modules/azure_pipelines.star

use `secret_headers` for creds
Commit Message: repokitteh: Secure azure creds
Risk Level:
Testing:
Docs Changes:
Release Notes:

repokitteh: Secure azure creds

---

.bazelrc

asan: fix copt

---

docs/root/configuration/http/http_filters/grpc_stats_filter.rst

Commit Message: document filter state format
Testing: none

grpc_stats: update docs

---

docs/root/configuration/http/http_filters/tap_filter.rst

Part of https://github.com/envoyproxy/envoy/issues/6387

docs: add docs around UDS issues for admin taps

---

.azure-pipelines/pipelines.yml
configs/BUILD

Commit Message: configs: Add more validation
some configs in the `configs/` dir had escaped validation, and some new ones have been added. This PR should catch them
Risk Level:
Testing:
Docs Changes:
Release Notes:

configs: Add more validation

---

source/common/runtime/runtime_impl.cc
source/common/runtime/runtime_impl.h
test/common/runtime/runtime_impl_test.cc

Signed-off-by: Jingwei Hao <jingwei.hao@gmail.com>
Commit Message: make rtds honor the resource removal
Related pr: https://github.com/envoyproxy/envoy/pull/13201

rtds: make rtds to honor resource removal

---

ci/do_ci.sh
tools/code_format/check_shellcheck_format.sh

Commit Message: ci: Improve shellcheck fail output
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fix #13709 

ci: Improve shellcheck fail output

---

docs/build.sh

Commit Message: docs: Cleanup duplicated/merged function
When #13728 and #13622 got merged a function got duplicated, this removes it
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Cleanup duplicated/merged function

---

tools/vscode/README.md

Signed-off-by: Tong Cai <caitong93@gmail.com>
docs: fix typos in tools/vscode
Testing:
Docs Changes:
Release Notes:

docs: fix typos in tools/vscode

---

configs/envoyproxy_io_proxy.yaml

Commit Message: configs: Small fix for default container config
small fix for typo in default container config
Risk Level:
Testing:
Docs Changes:
Release Notes:

configs: Small fix for default container config

---

ci/repokitteh/modules/azure_pipelines.star

- use subcheck IDs (which is required check)
- retrying partially failed pipelines
Fixes #13725

rk: improve azp retry

---

source/common/runtime/runtime_impl.cc
source/common/runtime/runtime_impl.h
test/integration/rtds_integration_test.cc

Testing: Added IT assertions
Fixes #13762

rtds: properly scope rtds stats

---

test/integration/tcp_tunneling_integration_test.cc

test: adding a test for CONNECT to an IP address

---

api/envoy/service/discovery/v3/discovery.proto
api/envoy/service/discovery/v4alpha/discovery.proto
generated_api_shadow/envoy/service/discovery/v3/discovery.proto
generated_api_shadow/envoy/service/discovery/v4alpha/discovery.proto

docs: remove spurious comment marker

---

docs/root/start/sandboxes/dynamic-configuration-filesystem.rst
examples/dynamic-config-fs/Dockerfile-proxy
examples/dynamic-config-fs/docker-compose.yaml

Commit Message: docs/examples: Update dynamic fs sandbox
Follow up from #13854 
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs/examples: Update dynamic fs sandbox

---

CODEOWNERS

codeowners: adding ggreenway to some extensions

---

.bazelrc
.devcontainer/Dockerfile
examples/wasm-cc/docker-compose-wasm.yaml

Commit Message: ci: Update build hashes
includes `expect` in build image
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Update build hashes

---

docs/root/configuration/http/http_filters/lua_filter.rst

Commit Message: lua: update config examples to use typed_pre_filter_config
Additional Description: related issue: https://github.com/envoyproxy/envoy/issues/13899

lua: update config examples to use typed_pre_filter_config

---

ci/run_envoy_docker.sh

1.15: fix CI script

---

test/extensions/filters/http/grpc_web/grpc_web_filter_integration_test.cc

Adding a test which apparently doesn't repro #13831

grpc: upstream disconnect test

---

.azure-pipelines/pipelines.yml

Commit Message: docs/ci: Publish master docs after docker
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fix #13778 

docs/ci: Publish master docs after docker

---

bazel/README.md

Signed-off-by: Yitao Hu <harmonyharmo@users.noreply.github.com>

Minor update of bazel doc

---

source/common/event/scaled_range_timer_manager_impl.cc

Signed-off-by: Louis Opter <louis@dropbox.com>
Commit Message: event: reduce log level for min timer complete message
Testing: existing CI
Release Notes: event: reduce log level for min timer complete message

event: reduce log level for min timer complete message

---

.bazelci/presubmit.yml

bazelci: exclude wasm

---

api/envoy/config/common/matcher/v3/matcher.proto
api/envoy/config/common/matcher/v4alpha/matcher.proto
generated_api_shadow/envoy/config/common/matcher/v3/matcher.proto
generated_api_shadow/envoy/config/common/matcher/v4alpha/matcher.proto

api: mark matching API as WIP

---

docs/root/start/quick-start/configuration-static.rst

Commit Message: docs: Minor cleanup of config render
cleanup from #13993 
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Minor cleanup of config render

---

bazel/repository_locations.bzl

wasm: fix CPE for Wasmtime.

---

source/extensions/transport_sockets/tls/context_impl.cc
test/server/listener_manager_impl_test.cc

log the internal error message from *SSL when the cert and private key doesn't match

---

.devcontainer/devcontainer.json
ci/run_clang_tidy.sh
ci/run_envoy_docker.sh

tidy: use last_github_commit script instead of target branch

---

docs/root/start/sandboxes/dynamic-configuration-filesystem.rst
docs/root/start/sandboxes/load_reporting_service.rst
docs/root/start/sandboxes/mysql.rst

Signed-off-by: 杨阳 10014842 <yangyang1@zte.com.cn>
Risk Level: n/a (docs only)

docs: Fix sandboxes doc

---

include/envoy/network/io_handle.h

Risk Level: n/a comments only
Testing: n/a

comments: clarify comment for IoHandle::write

---

test/integration/sds_dynamic_key_rotation_setup.sh

fix sds_dynamic_key_rotation_setup.sh running from other repos

---

bazel/repository_locations.bzl

tls: update BoringSSL to 1ce6682c (4280).

---

examples/skywalking-tracing/docker-compose.yaml

Commit Message: examples: update skywalking tracer version.

examples: update skywalking tracer version.

---

PULL_REQUESTS.md
STYLE.md

Commit Message: Updated link of "life of a request" in `STYLE.md`
Additional Description: Updated link of "life of a request" in `STYLE.md`. Currently redirecting to 404. 
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes #13397

Update link of "life of a request"

---

source/common/signal/fatal_action.h
source/common/signal/fatal_error_handler.cc
source/common/signal/signal_action.cc
test/common/signal/fatal_action_test.cc

Commit Message: Fixed typo.
Testing: N/A
Platform Specific Features:N/A

Fixed typo.

---

.bazelci/presubmit.yml
.bazelrc

bazelci: add fuzz coverage

---

tools/protodoc/protodoc.py

Commit Message: Add label for field in protobuf.
Additional Description: Add label for the field in protobuf. See #3458  
Risk Level: High
Testing: format
Fixes #3458

protodoc: Add label for field.

---

source/common/network/utility.cc
source/common/network/utility.h
source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc
source/extensions/filters/listener/proxy_protocol/proxy_protocol.h

Commit Message: replace exceptions with enum state|bool|optional (as appropriate) in proxy protocol listener extension.  
Testing: pre-existing unit and integration tests
Fixes: https://github.com/envoyproxy/envoy/issues/11044
@asraa Can you please take a look when you get a chance?

Clean up exceptions in proxy protocol listener

---

tools/stack_decode.py

This can be a problem when setting logging level to trace mode.

stack_decode: ignore decoding errors

---

test/integration/BUILD

test: disable flaky xds_integration_test.

---

.github/workflows/stale.yml

1) Every 4 hours
2) Up operationsd per run to 100
3) Ascending search to hit old issues first

stale: more changes

---

.github/workflows/stale.yml

stale: more allowed ops

---

source/common/event/dispatcher_impl.cc
test/common/event/dispatcher_impl_test.cc

event: touch watchdog before execution of each post callback and before deferred deletion
To avoid spurious watchdog miss events in cases where the dispatcher is churning along through a long backlog of post callbacks or deferred deletion (which includes deferred tasks)
Testing: extended dispatcher unit tests

event: touch watchdog before execution of each post callback and before deferred deletion

---

source/extensions/filters/http/squash/squash_filter.cc
test/extensions/filters/http/squash/squash_filter_test.cc

squash: check for cluster that does not exist

---

api/API_VERSIONING.md

Also, update other cases for when breaking changes are permitted.

api: define an API breaking change grace period.

---

CODEOWNERS

wasm: add mathetake to CODEOWNERS

---

test/integration/integration_tcp_client.cc
test/integration/tcp_proxy_integration_test.cc

Not sure how those extra semicolons got in.

Follow-up to #14424

---

OWNERS.md

owners: Change dio email address

---

docs/root/configuration/other_features/other_features.rst
docs/root/configuration/other_features/wasm.rst
docs/root/configuration/other_features/wasm_service.rst

Commit Message: Add initial stat docs for Wasm. I have tried to add more stats but the code is hard to understand with all the callbacks between multiple repos.
Risk Level:
Testing:
Release Notes:

wasm: basic stats

---

test/integration/protocol_integration_test.cc

ci: fix osx build

---

api/envoy/extensions/filters/http/ext_proc/v3alpha/ext_proc.proto
generated_api_shadow/envoy/extensions/filters/http/ext_proc/v3alpha/ext_proc.proto

Addresses https://github.com/envoyproxy/envoy/issues/14631
Signed-off-by: Gregory Brail <gregbrail@google.com>

Update ext_proc docs to reflect implementation status

---

source/extensions/transport_sockets/tls/ssl_socket.cc

Commit Message: fix empty connection debug  logs
Testing: N/A
Fixes https://github.com/envoyproxy/envoy/issues/14661

fix empty connection debug logs

---

.azure-pipelines/pipelines.yml

ci: fix docs tag build

---

test/extensions/filters/http/dynamic_forward_proxy/BUILD

Signed-off-by: Randy Miller <rmiller14@gmail.com>
Commit Message: Remove flaky_on_windows tag from proxy_filter_integration_test
Testing: Ran proxy_filter_integration_test thousands of times

Remove flaky_on_windows tag from proxy_filter_integration_test

---

bazel/repository_locations.bzl

wasm: update V8 to v8.9.255.6.

---

bazel/repository_locations.bzl

tls: update BoringSSL to fbbf8781 (4324).

---

test/integration/integration_test.cc

test: clean up some string checks

---

.azure-pipelines/pipelines.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

backport 1.17: ci: fix docs tag build

---

source/extensions/transport_sockets/tls/context_impl.cc
test/extensions/transport_sockets/tls/context_impl_test.cc
tools/spelling/spelling_dictionary.txt

[tls] add missing built in cipher stat names (#14676)

---

.azure-pipelines/pipelines.yml
bazel/repository_locations.bzl
ci/filter_example_setup.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

backport 1.15: ci: fix docs tag build

---

.azure-pipelines/pipelines.yml
bazel/repository_locations.bzl
ci/filter_example_setup.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

backport 1.14: ci: fix docs tag build

---

docs/root/configuration/http/http_filters/router_filter.rst

Risk Level:
Testing:
Docs Changes: docs/root/configuration/http/http_filters/router_filter.rst
Release Notes:

doc: fix typo

---

source/common/router/config_utility.cc

Signed-off-by: Alan Chiu <achiu@lyft.com>
Commit Message: android: fix unsigned int and signed int comparison 
Testing: unit

android: fix unsigned int and signed int comparison

---

docs/root/version_history/current.rst

Commit Message: Add release notes for #14799
Add missing release notes for PR #14799
Testing: n/a
Docs Changes: added release notes

docs: add release notes for #14799

---

test/integration/protocol_integration_test.cc
test/integration/protocol_integration_test.h

Enforcing that tests which do a full upstream H1/H2 and downstream H1/H2/H3 mesh actually use upstream connections.
Testing: tests pass

test: moving some tests around

---

SECURITY.md

security: add Microsoft to distributor list.

---

docs/generate_extension_db.py
source/extensions/access_loggers/file/BUILD

Commit Message: extensions: Improve error handling for missing extension category
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fix #15081

extensions: Improve error handling for missing extension category

---

source/common/config/utility.h

Bumped into reading translateToFactoryConfig()'s doc while working on
#14855.

config/utility: fix comment

---

docs/root/version_history/current.rst
source/common/upstream/health_discovery_service.cc
test/common/upstream/hds_test.cc
test/integration/hds_integration_test.cc

Commit Message: hds: support custom health check port
Additional Description: This is an supplement for this issue https://github.com/envoyproxy/envoy/issues/439

hds: support custom health check port

---

.github/workflows/stale.yml

I don't think the latest delta is working.  hoping a revert fixes and it's not a wider github infra issue.

process: reverting stalebot fixes

---

source/common/config/grpc_subscription_impl.cc
test/common/config/grpc_subscription_test_harness.h
test/common/config/subscription_impl_test.cc

Commit Message: Fixes init fetch timeout stat increment
Additional Description: fix init fetch timeout stat increment which is not incrementing correctly now
Testing: Updated
Fixes https://github.com/envoyproxy/envoy/issues/15085

xds: fix init fetch timeout stat

---

docs/root/configuration/listeners/udp_filters/_include/udp-proxy.yaml

Commit Message: Fix broken udp proxy yaml
Testing: n/a
Docs Changes: fix broken udp proxy yaml - `listener_filters` accepts lists of filters

docs: Fix broken udp proxy yaml

---

.bazelrc
.devcontainer/Dockerfile
examples/wasm-cc/docker-compose-wasm.yaml

Commit Message: build: Bump build image hash to d9b1f1cbb24b2cecca768feaa9fa3c6e6660a948
Risk Level:
Testing:
Docs Changes:
Release Notes:

build: Bump build image hash to d9b1f1cbb24b2cecca768feaa9fa3c6e6660a948

---

test/common/network/io_socket_handle_impl_integration_test.cc

Add comments in io_socket_handle_impl_integration_test

---

CODEOWNERS
OWNERS.md

Remove myself from non-Wasm responsibilities.

---

docs/root/configuration/http/http_filters/lua_filter.rst

fix tlsVersion()
Risk Level:
Testing:
Docs Changes:
Release Notes:

doc: fix typo in lua doc

---

test/integration/protocol_integration_test.cc

AFIK another issue with the two PRs merged this morning (masked by the deterministic failure)

quic: disabling one more flake

---

ci/mac_ci_setup.sh

Commit Message: ci: Fix macosx install flake
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Fix macosx install flake

---

bazel/external/su-exec.BUILD
bazel/repositories.bzl
bazel/repository_locations.bzl
ci/Dockerfile-envoy
ci/do_ci.sh

Relates to https://github.com/envoyproxy/envoy/issues/14454
Signed-off-by: Arko Dasgupta <arko@tetrate.io>
Testing: Manual + CI

[build] Bazel build for su-exec

---

OWNERS.md

Also prune stale other friends. :(

owners: add Dmitry Rozhkov to friends of Envoy

---

docs/build.sh
tools/extensions/generate_extension_rst.py

1) Run generate extension db always so there isn't stale data.
2) Check for errors and fast fail so it's obvious if env vars, etc.
aren't set.

docs: fix local iterative doc builds

---

api/envoy/extensions/filters/http/kill_request/v3/kill_request.proto
api/envoy/service/status/v3/csds.proto
generated_api_shadow/envoy/extensions/filters/http/kill_request/v3/kill_request.proto
generated_api_shadow/envoy/service/status/v3/csds.proto

Commit Message: protos: Cleanup unused imports
another attempt at removing redundant imports and reducing build noise
Risk Level:
Testing:
Docs Changes:
Release Notes:

protos: Cleanup unused imports

---

CODEOWNERS
OWNERS.md

owners: update htuch@ areas of ownership/expertise.

---

source/server/worker_impl.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

fix an UD about parameters eval order

---

docs/root/start/sandboxes/double-proxy.rst
docs/root/start/sandboxes/dynamic-configuration-filesystem.rst

Commit Message: typos in sandbox docs
Risk Level:
Testing:
Release Notes:
part of #11027

fixing typos in sandboxes docs

---

.github/ISSUE_TEMPLATE/feature_request.md
bazel/README.md
docs/root/configuration/operations/runtime.rst
source/common/stats/tag_extractor_impl.cc
test/common/config/grpc_mux_impl_test.cc
test/extensions/filters/http/cache/cache_filter_test.cc
test/integration/http2_flood_integration_test.cc

Removed dups from docs.

---

test/extensions/transport_sockets/tls/context_impl_test.cc
test/extensions/transport_sockets/tls/ssl_socket_test.cc
test/integration/base_integration_test.cc
test/test_common/environment.cc
test/test_common/environment.h

Testing:  n/a
Docs Changes: n./a

test: consolidating file logic

---

api/bazel/repository_locations.bzl
generated_api_shadow/bazel/repository_locations.bzl

build: migrate from cncf/udpa to cncf/xds.

---

docs/root/configuration/listeners/stats.rst
docs/root/configuration/listeners/udp_filters/udp_proxy.rst
docs/root/version_history/current.rst
include/envoy/network/listener.h
source/common/network/udp_listener_impl.h
source/common/network/utility.cc
source/common/network/utility.h
source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h
source/extensions/quic_listeners/quiche/envoy_quic_client_connection.h
source/server/active_udp_listener.cc
source/server/active_udp_listener.h
test/common/network/udp_listener_impl_test.cc
test/extensions/filters/udp/udp_proxy/udp_proxy_integration_test.cc
test/mocks/network/mocks.h
test/server/listener_manager_impl_quic_only_test.cc
test/server/utility.h
test/test_common/network_utility.cc

udp: add stats for downstream and upstream drops

---

docs/root/start/quick-start/run-envoy.rst

Commit Message: ref issue in doc
Additional Description: Note Section in https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/run-envoy#override-the-default-configuration
Testing:
Docs Changes:Yes
Release Notes:
part of #11027

fix ref issue in quick start doc

---

docs/root/start/quick-start/configuration-dynamic-control-plane.rst

Improved docs.

---

docs/root/version_history/current.rst
include/envoy/stream_info/stream_info.h
source/common/stream_info/utility.cc
source/extensions/access_loggers/grpc/grpc_access_log_utils.cc
test/common/access_log/access_log_impl_test.cc
test/common/stream_info/utility_test.cc

Fixed an error bit - string mapping bug introduced in #15431
Update the release notes to highlight the minor behavior change. 
As per https://github.com/envoyproxy/envoy/pull/15431#discussion_r595336633
Risk Level:
Testing:
Docs Changes:
Release Notes:

error flag NC, cont

---

docs/root/start/quick-start/configuration-static.rst

Commit Message: ref glitch in configuration doc
Risk Level:LOW
Testing: 
Release Notes:
part of #11027

ref glitch in configuration doc

---

docs/README.md
docs/build.sh

Commit Message: Updated docs/build.sh to fix local build.
Additional Description: Please see https://github.com/envoyproxy/envoy/issues/15536#issuecomment-801166225
Testing: n/a

docs: Fixed local build.

---

docs/root/configuration/upstream/health_checkers/redis.rst

Fixed typed_config. See #15571
Fixes #15571

redis: Fixed typed_config.

---

tools/api_proto_plugin/annotations.py
tools/api_proto_plugin/plugin.py
tools/api_proto_plugin/traverse.py
tools/api_proto_plugin/type_context.py
tools/api_proto_plugin/utils.py
tools/api_versioning/generate_api_version_header.py
tools/code_format/format_python_tools.py
tools/config_validation/validate_fragment.py
tools/dependency/cve_scan.py
tools/deprecate_version/deprecate_version.py
tools/envoy_collect/envoy_collect.py
tools/envoy_headersplit/headersplit.py
tools/envoy_headersplit/replace_includes.py
tools/proto_format/proto_sync.py
tools/protodoc/protodoc.py
tools/protoxform/migrate.py
tools/protoxform/options.py
tools/protoxform/protoprint.py
tools/protoxform/protoxform.py
tools/protoxform/protoxform_test_helper.py
tools/type_whisperer/type_whisperer.py
tools/type_whisperer/typedb_gen.py

Commit Message: python: Fix docstring formatting
Risk Level:
Testing:
Docs Changes:
Release Notes:

python: Fix docstring formatting

---

test/server/BUILD

test: Remove unused dependency

---

source/docs/h2_metadata.md

Risk Level:
Testing:
Docs Changes:
Release Notes:

doc: fix typo in h2 metadata

---

api/envoy/config/listener/v3/quic_config.proto
api/envoy/config/listener/v3/udp_listener_config.proto
api/envoy/config/listener/v4alpha/quic_config.proto
api/envoy/config/listener/v4alpha/udp_listener_config.proto
api/envoy/extensions/access_loggers/stderror/v3/stderror.proto
api/envoy/extensions/access_loggers/stderror/v4alpha/stderror.proto
api/envoy/extensions/access_loggers/stdoutput/v3/stdoutput.proto
api/envoy/extensions/access_loggers/stdoutput/v4alpha/stdoutput.proto
api/envoy/extensions/filters/udp/udp_proxy/v3/udp_proxy.proto
api/envoy/extensions/matching/input_matchers/consistent_hashing/v3/consistent_hashing.proto
api/envoy/type/http/v3/path_transformation.proto
generated_api_shadow/envoy/config/listener/v3/quic_config.proto
generated_api_shadow/envoy/config/listener/v3/udp_listener_config.proto
generated_api_shadow/envoy/config/listener/v4alpha/quic_config.proto
generated_api_shadow/envoy/config/listener/v4alpha/udp_listener_config.proto
generated_api_shadow/envoy/extensions/access_loggers/stderror/v3/stderror.proto
generated_api_shadow/envoy/extensions/access_loggers/stderror/v4alpha/stderror.proto
generated_api_shadow/envoy/extensions/access_loggers/stdoutput/v3/stdoutput.proto
generated_api_shadow/envoy/extensions/access_loggers/stdoutput/v4alpha/stdoutput.proto
generated_api_shadow/envoy/extensions/filters/udp/udp_proxy/v3/udp_proxy.proto
generated_api_shadow/envoy/extensions/matching/input_matchers/consistent_hashing/v3/consistent_hashing.proto
generated_api_shadow/envoy/type/http/v3/path_transformation.proto

Commit Message: protos: Cleanup redundant imports
Risk Level:
Testing:
Docs Changes:
Release Notes:

protos: Cleanup redundant imports

---

.azure-pipelines/pipelines.yml
configs/configgen.py
docs/_ext/validating_code_block.py
tools/api/generate_go_protobuf.py
tools/api_proto_plugin/annotations.py
tools/api_proto_plugin/type_context.py
tools/code_format/flake8.conf
tools/config_validation/validate_fragment.py
tools/dependency/utils.py
tools/deprecate_version/deprecate_version.py
tools/envoy_headersplit/headersplit.py
tools/envoy_headersplit/headersplit_test.py
tools/extensions/generate_extension_db.py
tools/extensions/generate_extension_rst.py
tools/gen_compilation_database.py
tools/print_dependencies.py
tools/proto_format/proto_sync.py
tools/protodoc/protodoc.py
tools/protoxform/protoxform_test_helper.py
tools/protoxform/utils.py
tools/socket_passing.py
tools/stack_decode.py
tools/type_whisperer/proto_build_targets_gen.py

Commit Message: python: Cleanup redundant imports
Risk Level:
Testing:
Docs Changes:
Release Notes:

python: Cleanup redundant imports

---

tools/protodoc/BUILD

For detail, please refer to https://envoyproxy.slack.com/archives/C78HA81DH/p1616479414057200

doc: add Jinja2 requirement for protodoc target

---

bazel/repository_locations.bzl

wasm: update V8 to v9.0.257.13.

---

test/extensions/filters/http/gzip/BUILD
test/extensions/filters/http/gzip/gzip_filter_test.cc

This test was pulling in the JSON parsing lib for no reason.
Testing: n/a

gzip: remove test dependency on json_loader_lib

---

source/server/BUILD

I'd like to land this asap, but @lizan can you suggest a CI to run with  --//bazel:http3=False for a follow-up PR?

build: fix ~quic build

---

api/envoy/api/v2/core/address.proto
api/envoy/config/core/v3/address.proto
api/envoy/config/core/v4alpha/address.proto
generated_api_shadow/envoy/api/v2/core/address.proto
generated_api_shadow/envoy/config/core/v3/address.proto
generated_api_shadow/envoy/config/core/v4alpha/address.proto
test/common/network/cidr_range_test.cc

Fixes #15579
Risk Level: n/a (no functional change)
Testing: Unit test to verify case added to docs
Docs Changes: Added definition of default value

api: Document default CidrRange prefix_len

---

source/common/http/conn_pool_base.cc

Risk Level: n/a (comment only change)
part of #14829

quic: updating a TODO

---

source/common/conn_pool/conn_pool_base.cc

Commit Message: conn_pool_base: minor fix for warnings building on android-x86
Testing: Local and CI
Signed-off-by: Mike Schore <mike.schore@gmail.com>

conn_pool_base: minor fix for warnings building on android-x86

---

docs/root/intro/arch_overview/http/upgrades.rst

connect: adding docs to address CONNECT+TLS

---

test/per_file_coverage.sh

Bumping coverage numbers up.
Testing: CI passes

test: ratcheting coverage

---

docs/root/intro/arch_overview/http/upgrades.rst

The buffer filter breaks web socket upgrades, so add a note about
this.

docs: add note about the buffer filter & upgrades

---

source/common/upstream/BUILD
source/common/upstream/cds_api_helper.cc
source/common/upstream/cds_api_helper.h
source/common/upstream/cds_api_impl.cc
source/common/upstream/cds_api_impl.h

We plan to add an OdCdsApiImpl class next to CdsApiImpl. It's config
updated callback functionality would be similar to CdsApiImpl's, but
with some extra code. To avoid the duplication of code, we move it to
a helper class that will be used by both OdCdsApiImpl and CdsApiImpl.
This is split out from https://github.com/envoyproxy/envoy/pull/15523 to ease the review. It has no functional changes.
Risk Level:
Low.
Testing:
Tested as a part of https://github.com/envoyproxy/envoy/pull/15523.
Docs Changes:
Added API docs for the newly added CdsApiHelper class.
Release Notes:
None needed.
None.

CDS: Factor out some functionality of CDS into a helper class

---

bazel/README.md
docs/root/start/building.rst

Signed-off-by: Sotiris Nanopoulos <sonanopo@microsoft.com>
Add Windows section in `building.rst`

Add Windows section in `building.rst`

---

bazel/BUILD
bazel/envoy_select.bzl

When this was added originally this skylib helper didn't exist.

bazel: Simplify select alias configuration

---

source/extensions/filters/http/ext_proc/BUILD
source/extensions/filters/http/ext_proc/ext_proc.cc
source/extensions/filters/http/ext_proc/ext_proc.h
source/extensions/filters/http/ext_proc/processor_state.cc
source/extensions/filters/http/ext_proc/processor_state.h

Commit message: Reorganize some of the logic from the core filter into a set of
classes. This eliminates some duplicate logic, and it also
will make it easier to implement some up coming features without
so much code duplication.
Testing: Existing unit and integration tests
Signed-off-by: Gregory Brail <gregbrail@google.com>

ext_proc: Refactor state processing

---

source/extensions/transport_sockets/alts/BUILD
source/extensions/transport_sockets/alts/tsi_socket.cc
source/extensions/transport_sockets/alts/tsi_socket.h
test/extensions/transport_sockets/alts/tsi_socket_test.cc

This PR resolves the second issue described in #15296.

alts: Fix TsiSocket doRead to obey read limits

---

bazel/envoy_internal.bzl

Will tag lizan/avd once I make sure Ci is happy
Futureproofing the one-off in https://github.com/envoyproxy/envoy/pull/15858
Testing: n/a

build: adding -Wreturn-type

---

support/bootstrap
support/hooks/pre-push
support/hooks/prepare-commit-msg
tools/code_format/check_shellcheck_format.sh

Commit Message: shellcheck: Enable for more files and fix
Risk Level:
Testing:
Docs Changes:
Release Notes:

shellcheck: Enable for more files and fix

---

SECURITY.md

security: clarify policy on early patch access to reporters.

---

CODEOWNERS
docs/root/configuration/http/http_conn_man/headers.rst
docs/root/intro/arch_overview/observability/tracing.rst
source/extensions/tracers/xray/BUILD

Signed-off-by: Sunil Narasimhamurthy <sunnrs@amazon.com>
Commit Message: update envoy docs to contain information related to AWS X-Ray extension and update codeowners for the same extension
Testing: N/A
Docs Changes: The PR updates the envoy documentation to reference X-Ray as a tracing extension that is supported by envoy and also gives reference towards the specific http header that is provided by this extension.

docs: update docs for the AWS X-Ray tracer

---

test/common/common/regex_test.cc

route: adding tests

---

bazel/repository_locations.bzl

wasm: update V8 to v9.0.257.17.

---

CODEOWNERS

Signed-off-by: Tony Allen <tony@allen.gg>

owners: Add tonya11en@ to various AWS-related extension owner lists

---

api/envoy/config/listener/v3/listener.proto
api/envoy/config/listener/v4alpha/listener.proto
docs/root/configuration/listeners/stats.rst
docs/root/version_history/current.rst
generated_api_shadow/envoy/config/listener/v3/listener.proto
generated_api_shadow/envoy/config/listener/v4alpha/listener.proto
source/server/listener_impl.cc
test/server/listener_manager_impl_test.cc

Testing: Added unit test
Docs Changes: added

listener: add optional stat_prefix to use instead of listener address

---

docs/root/start/quick-start/configuration-dynamic-control-plane.rst
docs/root/start/quick-start/configuration-dynamic-filesystem.rst

Commit Message: docs: Fix emphasize lines in literalincludes
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Fix emphasize lines in literalincludes

---

.bazelrc
.devcontainer/Dockerfile
examples/wasm-cc/docker-compose-wasm.yaml

Commit Message: build: Bump build image to 3d0491e2
Risk Level:
Testing:
Docs Changes:
Release Notes:

build: Bump build image to 3d0491e2

---

test/config_test/BUILD

Hopefully reducing tsan failures

tagging example config test as large

---

tools/base/checker.py
tools/base/tests/test_checker.py
tools/code_format/python_check.py
tools/code_format/tests/test_python_check.py
tools/testing/plugin.py
tools/testing/tests/test_python_coverage.py
tools/testing/tests/test_python_pytest.py

Commit Message: python: Add main test fixture and consolidate checker/runner mains
Risk Level:
Testing:
Docs Changes:
Release Notes:

python: Add main test fixture and consolidate checker/runner mains

---

OWNERS.md

owners: add @wrowe as a maintainer.

---

docs/root/faq/configuration/timeouts.rst

Commit Message: fix underscore lost in field name idle_timeout
Additional Description: fix doc
Testing: N/A
Docs Changes: docs/root/faq/configuration/timeouts.rst

docs: fix field name: idle_timeout field name lost underscore

---

api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
api/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto
generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto

Reserve field ID for an upcoming patch

---

docs/requirements.txt
examples/grpc-bridge/client/requirements.txt
tools/code_format/requirements.txt

Commit Message: dependabot: Aggregate updates
Risk Level:
Testing:
Docs Changes:
Release Notes:

dependabot: Aggregate updates

---

docs/root/configuration/http/http_filters/wasm_filter.rst

Commit Message: docs: add a missing word to WASM filter doc
Testing: N/A
Docs Changes: Adding a missing word to the Wasm filter doc
Release Notes:

docs: add a missing word to WASM filter doc

---

docs/root/api/client_features.rst
docs/root/configuration/http/http_conn_man/stats.rst
docs/root/configuration/http/http_filters/aws_lambda_filter.rst
docs/root/configuration/http/http_filters/fault_filter.rst
docs/root/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter.rst
docs/root/configuration/listeners/udp_filters/dns_filter.rst
docs/root/configuration/observability/access_log/overview.rst
docs/root/configuration/operations/tools/router_check.rst
docs/root/configuration/overview/versioning.rst
docs/root/configuration/overview/xds_api.rst
docs/root/intro/arch_overview/advanced/attributes.rst
docs/root/intro/arch_overview/http/http_routing.rst
docs/root/intro/arch_overview/upstream/load_balancing/excluded.rst
docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
docs/root/operations/certificates.rst
docs/root/operations/tools/config_generator.rst
docs/root/operations/tools/route_table_check_tool.rst

Commit Message: docs: Update refs: v2 -> v3
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Update refs: v2 -> v3

---

docs/root/configuration/listeners/network_filters/_include/zookeeper-filter-proxy.yaml
docs/root/configuration/listeners/network_filters/zookeeper_proxy_filter.rst

Signed-off-by: JaredTan95 <jian.tan@daocloud.io>
Commit Message: update zk proxy configuration yaml.
Additional Description: update zk proxy configuration yaml.
Testing: N/A
Docs Changes:  update zk proxy configuration yaml.

docs: update zookeeper filter proxy configuration yaml.

---

docs/BUILD

Commit Message: configs: Validate dynamic xds config
Risk Level:
Testing:
Docs Changes:
Release Notes:

configs: Validate dynamic xds config

---

docs/root/version_history/current.rst
source/common/http/header_map_impl.cc
source/common/runtime/runtime_features.cc
test/common/http/header_map_impl_test.cc

Testing: n/a
Fixes https://github.com/envoyproxy/envoy/issues/16018

http: removing envoy.reloadable_features.http_set_copy_replace_all_heders

---

OWNERS.md

owners: add @phlax as maintainer.

---

bazel/external/wee8.BUILD
bazel/external/wee8.genrule_cmd
bazel/repository_locations.bzl

wasm: update V8 to v9.1.269.18.

---

source/common/quic/active_quic_listener.cc

Adding an informative log since I ended up confused when trying to sort out https://github.com/envoyproxy/envoy/issues/15845 and needed to fix https://github.com/envoyproxy/envoy/pull/15926 accordingly.
Risk Level: n/a (adding info log)

udp: log when BPF is not attempted

---

test/integration/multiplexed_integration_test.cc

Part of https://github.com/envoyproxy/envoy/issues/16335

test: disabling flaky test

---

.bazelrc

bazel: add --config=docker-asan and --config=remote-tsan.

---

include/envoy/http/codec.h
source/common/http/conn_manager_impl.cc
source/common/http/conn_manager_impl.h
source/common/http/filter_manager.cc
source/common/http/filter_manager.h
source/common/http/http1/codec_impl.cc
test/common/http/http1/codec_impl_test.cc
test/integration/fake_upstream.h
test/mocks/http/mocks.h
test/mocks/http/stream_decoder.h

Risk Level: low (removing unused args)
Testing: n/a

http: cleaning up obsolete grpc args

---

docs/root/version_history/current.rst
source/common/runtime/runtime_features.cc

Risk Level: High (new tcp pool, lots of smoke testing)
Testing: integration tests, unit tests, production validation by Pinterest

tcp: switching to the new pool

---

SECURITY.md

security: add Square to distributor list.

---

security/email-templates.md

security: add template for security advisory

---

configs/Dockerfile

Commit Message: docker: Remove unused Dockerfile
Risk Level:
Testing:
Docs Changes:
Release Notes:

docker: Remove unused Dockerfile

---

.github/dependabot.yml

Commit Message: dependabot: Add Dockerfile checks
Risk Level:
Testing:
Docs Changes:
Release Notes:

dependabot: Add Dockerfile checks

---

SECURITY.md

security: add Apple to the distributor list

---

docs/root/faq/configuration/timeouts.rst

Signed-off-by: Keerthan Ekbote <saiskee@gmail.com>
Commit Message: Add scaled timeout docs.
Additional Description: Adds section about scaled timeout to FAQ docs.
Testing: --
Docs Changes: Timeout FAQs - scaled timeouts
Release Notes: --
Platform Specific Features: --

add scaled timeout docs faq

---

docs/root/start/sandboxes/gzip.rst
docs/root/start/sandboxes/index.rst
examples/gzip/Dockerfile-gzip
examples/gzip/Dockerfile-service
examples/gzip/README.md
examples/gzip/docker-compose.yaml
examples/gzip/gzip-envoy.yaml
examples/gzip/service.py
examples/gzip/verify.sh

Signed-off-by: Long Dai <long0dai@foxmail.com>
Commit Message: Add gzip example.
Some [discuess](https://envoyproxy.slack.com/archives/C78HA81DH/p1619508864486000) in slack.
Testing:
Docs Changes:
Release Notes:

examples: add gzip

---

tools/dependency/release_dates.sh

Commit Message: dependencies: Fix script imports
#16767 broke the release dates script despite passing CI - this should fix the problem for now
Risk Level:
Testing:
Docs Changes:
Release Notes:

dependencies: Fix script imports

---

.github/actions/pr_notifier/pr_notifier.py

Fixing an early return for multiple maintainers
Adding stale notifications to oncall

tools: bugfix and stale PR update

---

.github/actions/pr_notifier/pr_notifier.py

pr notifier: treat waiting.any as waiting label

---

test/common/http/conn_manager_impl_test.cc

Signed-off-by: Renjie Tang <renjietang@google.com>
Commit Message: Fix ci build failure introduced by https://github.com/envoyproxy/envoy/pull/16797

ci: fix ci build by specifying an unsigned number in test.

---

test/common/quic/client_connection_factory_impl_test.cc

test: fixing a v6 only test failure

---

.azure-pipelines/bazel.yml
.azure-pipelines/cve_scan.yml
.azure-pipelines/pipelines.yml
.bazelci/presubmit.yml
.github/ISSUE_TEMPLATE/config.yml
.github/dependabot.yml
.github/workflows/codeql-daily.yml
.github/workflows/codeql-push.yml
.github/workflows/pr_notifier.yml
.github/workflows/stale.yml
.zuul/playbooks/envoy-build/run.yaml

Commit Message: yaml: Lint CI and repo configs
this is another breakout pr from #15726
see #16841 for further explanation
Risk Level:
Testing:
Docs Changes:
Release Notes:

yaml: Lint CI and repo configs

---

docs/root/intro/arch_overview/other_protocols/redis.rst

Signed-off-by: agrawalnishant <root.nishi@gmail.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: fix word repetition and grammar.

---

source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.h

Commit Message: remove unused code in json transcoder filter
Testing: N/A

json transcoder: remove dead code

---

tools/proto_format/proto_format.sh
tools/proto_format/proto_sync.py

Removed user input from proto_sync.py.
Fixes #16835

ci: Removed user input from proto_sync.py

---

configs/encapsulate_in_http1_connect.yaml
configs/encapsulate_in_http2_connect.yaml
configs/encapsulate_in_http2_post.yaml
configs/envoyproxy_io_proxy_http3_downstream.yaml
configs/freebind/freebind.yaml
configs/google-vrp/envoy-edge.yaml
configs/google-vrp/envoy-origin.yaml
configs/proxy_connect.yaml
configs/terminate_http1_connect.yaml
configs/terminate_http2_connect.yaml
configs/terminate_http2_post.yaml

Commit Message: yaml: Lint configs yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:

yaml: Lint configs yaml

---

OWNERS.md

Risk Level:
Testing:
Docs Changes:
Release Notes:

owners: fix small typo

---

api/envoy/extensions/filters/http/squash/v3/BUILD
generated_api_shadow/envoy/extensions/filters/http/squash/v3/BUILD
tools/proto_format/proto_sync.py

Commit Message: protos: v2 squash.proto removal
Fork of #16336 with a fix and readd of previous_message_type info
Risk Level:
Testing:
Docs Changes:
Release Notes:

protos: v2 squash.proto removal

---

source/server/listener_manager_impl.cc

Commit Message: listener: remove the todo about the draining race problem
The todo comment describes the draining flow as below:
1. main thread: calling drainListener
2. work thread: deferred delete the active connection
3. work thread: post to main that the drain is done
4. main thread: erase the listener
5. worker thread: execute destroying connection when the shared listener config is
destroyed at step 4 (could be worse such as access the connection because the connection is
not yet started to deleted).
But actually, step 5 should happen before #4.
Although the ActiveTcpSocket and ActiveTcpConnection will be deferred deleted:
https://github.com/envoyproxy/envoy/blob/123e81813a2003de07c8e3400c090bb755676a63/source/server/active_tcp_listener.cc#L53 …

listener: remove the todo about the draining race problem

---

docs/root/start/sandboxes/brotli.rst
docs/root/start/sandboxes/index.rst
examples/brotli/Dockerfile-brotli
examples/brotli/Dockerfile-service
examples/brotli/README.md
examples/brotli/brotli-envoy.yaml
examples/brotli/docker-compose.yaml
examples/brotli/service.py
examples/brotli/verify.sh

Signed-off-by: Long Dai <long0dai@foxmail.com>
Add brotli example.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fixes #16747

examples: add brotli

---

source/extensions/filters/network/dubbo_proxy/BUILD
source/extensions/filters/network/dubbo_proxy/config.cc
source/extensions/filters/network/dubbo_proxy/filters/BUILD
source/extensions/filters/network/dubbo_proxy/router/BUILD
source/extensions/filters/network/dubbo_proxy/router/config.h
test/extensions/filters/network/dubbo_proxy/BUILD
test/extensions/filters/network/dubbo_proxy/router_filter_config_test.cc

Signed-off-by: Long Dai <long0dai@foxmail.com>
Testing: functional
Docs Changes:
Release Notes:

dubbo_proxy: remove well_known_names

---

docs/BUILD
docs/build.sh
tools/docs/BUILD

Commit Message: docs: Consolidate rst genrules
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Consolidate rst genrules

---

api/envoy/config/rbac/v3/rbac.proto
api/envoy/config/rbac/v4alpha/rbac.proto
generated_api_shadow/envoy/config/rbac/v3/rbac.proto
generated_api_shadow/envoy/config/rbac/v4alpha/rbac.proto

Signed-off-by: Yangmin Zhu <ymzhu@google.com>
Commit Message: Update the RBAC API documentation to match the implemented behavior about policy evaluation order.
Risk Level: N/A, only small doc update
Testing: N/A
Optional Fixes https://github.com/envoyproxy/envoy/issues/16152

rbac: update documentation about policy evaluation order

---

source/extensions/stat_sinks/metrics_service/grpc_metrics_service_impl.h

Allows code that want to reuse the metrics service to specify the metrics flusher to use for the service, allowing
them to override the predicate to use.
Testing: n/a

metrics service: allow passing flusher as ctor arg

---

source/server/options_impl.h
test/integration/server.cc
test/server/options_impl_test.cc

Fix typo in source/server/options_impl.h
setAllowUnkownFields->setAllowUnknownFields

Fix typo in options_impl.h

---

ci/format_pre.sh
tools/code_format/glint.sh

Commit Message: ci: Add glint fix-your-editor message
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fix #17008 

ci: Add glint fix-your-editor message

---

DEVELOPER.md

Commit Message: Fixed link redirection.
Additional Description: Links given in docs are redirected to **repository** rather than `README`.

docs: Fixed link redirection.

---

tools/proto_format/proto_format.sh

Commit Message: ci: Speedup format job
While debugging i found a potential (large) speedup for the format job by passing through the bazel args correctly
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Speedup format job

---

docs/root/configuration/listeners/network_filters/rocketmq_proxy_filter.rst

Added v3 API reference in [rocketmq_proxy_filter](https://github.com/envoyproxy/envoy/blob/main/docs/root/configuration/listeners/network_filters/rocketmq_proxy_filter.rst) docs.

docs: Added v3 API reference.

---

ci/do_ci.sh

Commit Message: ci: Speedup deps precheck
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Speedup deps precheck

---

.github/actions/pr_notifier/requirements.txt
tools/deprecate_version/requirements.txt
tools/docs/requirements.txt

Commit Message: dependabot: Updates
Risk Level:
Testing:
Docs Changes:
Release Notes:

dependabot: Updates

---

ci/repokitteh/modules/newcontributor.star

changes didn't work.  Will sync with itay

repokitteh rollback

---

tools/code_format/check_format_test_helper.py

Commit Message: format: Update clang-format default in check_format_test
Risk Level:
Testing:
Docs Changes:
Release Notes:

format: Update clang-format default in check_format_test

---

bazel/repositories.bzl
bazel/repository_locations.bzl
docs/BUILD

Commit Message: bazel: Add rules_pkg
Risk Level:
Testing:
Docs Changes:
Release Notes:

bazel: Add rules_pkg

---

api/envoy/config/cluster/v3/cluster.proto
api/envoy/config/cluster/v4alpha/cluster.proto
api/envoy/config/listener/v3/listener_components.proto
api/envoy/config/listener/v4alpha/listener_components.proto
generated_api_shadow/envoy/config/cluster/v3/cluster.proto
generated_api_shadow/envoy/config/cluster/v4alpha/cluster.proto
generated_api_shadow/envoy/config/listener/v3/listener_components.proto
generated_api_shadow/envoy/config/listener/v4alpha/listener_components.proto

Commit Message: Expected transport_socket_name for TLS: envoy.transport_sockets.tls
Testing: N/A
Docs Changes: 

Expected transport_socket_name for TLS: envoy.transport_sockets.tls

---

docs/root/intro/arch_overview/advanced/attributes.rst

Signed-off-by: Mandar U Jog <mjog@google.com>

Doc: Clarify request/response attributes are http-only

---

CODEOWNERS

owners: add owners for kafka network filter

---

docs/root/configuration/http/http_filters/rate_limit_filter.rst

Commit Message:  Fix reference link to MetadataKey..
Additional Description: None.
Testing: Manual verification. Docs CI check.
Docs Changes: Fixing ref link.
Platform Specific Features: None.

docs: fix reference link to MetadataKey.

---

tools/base/checker.py
tools/base/tests/test_checker.py
tools/testing/BUILD
tools/testing/requirements.txt

Commit Message: tools: Add AsyncChecker
Allows use of asyncio for checkers
Risk Level:
Testing:
Docs Changes:
Release Notes:

tools: Add AsyncChecker

---

source/server/listener_hooks.h
source/server/server.cc
source/server/server.h
test/integration/server.h

server: removing unused onRuntimeCreated hooks

---

.github/actions/pr_notifier/pr_notifier.py
OWNERS.md

:tada: thank you @davinci26 for all your work!

owners: add Sotiris

---

docs/build.sh

Commit Message:  bazel: Adjust docs build strategy
use rbe for all parts of docs build where available
Risk Level:
Testing:
Docs Changes:
Release Notes:

bazel: Adjust docs build strategy

---

docs/root/configuration/best_practices/_include/edge.yaml

I copy pasted this today to try something out and it took me a while
to notice that there was no router filter configured.

docs: fix edge example

---

docs/root/version_history/current.rst
source/common/conn_pool/conn_pool_base.cc
source/common/runtime/runtime_features.cc
test/common/http/http2/conn_pool_test.cc

Testing: n/a
Fixes https://github.com/envoyproxy/envoy/issues/17323

runtime: removing envoy.reloadable_features.allow_preconnect

---

.github/dependabot.yml
docs/conf.py
tools/docs/requirements.txt

Fixes https://github.com/envoyproxy/envoy/issues/17312

docs: fix bullet lists

---

ci/mac_ci_steps.sh

This should give very basic sanity coverage.

ci: speed up OSX CI

---

ci/repokitteh/modules/newcontributor.star

repokitteh: file copy

---

RELEASES.md

add mathetake as Q3 stable maintainer

---

tools/base/checker.py
tools/base/runner.py
tools/base/tests/test_checker.py

Commit Message: tooling: Misc log/proc improvements
Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Misc log/proc improvements

---

docs/root/intro/arch_overview/upstream/dns_resolution.rst
source/common/network/apple_dns_impl.cc
source/common/network/apple_dns_impl.h
test/common/network/apple_dns_impl_test.cc

Commit Message: apple dns: add more details on DNS failure
Risk Level: low, new telemetry
Testing: added tests

apple dns: add more details on DNS failure

---

tools/distribution/BUILD
tools/distribution/sign.py
tools/distribution/tests/test_sign.py
tools/gpg/identity.py
tools/gpg/tests/test_identity.py

Commit Message: dist: Add signing util
Risk Level:
Testing:
Docs Changes:
Release Notes:

dist: Add package signing util

---

test/run_envoy_bazel_coverage.sh

ci: set --flaky_test_attempts=2 for coverage.

---

source/server/api_listener_impl.cc

follow-up on https://github.com/envoyproxy/envoy/pull/17407
Testing: existing test passes
fixes https://github.com/envoyproxy/envoy/issues/17434

envoy-mobile-hcm: removing an unnecessary try/catch

---

api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto

Signed-off-by: Kateryna Nezdolii <nezdolik@spotify.com>
Additional Description: Name is required field for `original_ip_detection_extensions`, pasting example as it is fails in proto validation step.
Testing:
Docs Changes:
Release Notes:

Fix yaml example in api

---

source/server/BUILD
source/server/server.cc
test/server/server_test.cc

v2: removing bootstrap

---

source/extensions/stat_sinks/metrics_service/BUILD
source/extensions/stat_sinks/metrics_service/grpc_metrics_proto_descriptors.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

v2: final source removal

---

envoy/stream_info/stream_info.h
source/common/router/router.cc
source/common/stream_info/stream_info_impl.h
source/common/tcp_proxy/tcp_proxy.cc
test/common/router/router_test.cc
test/common/router/router_test_base.cc
test/common/stream_info/test_util.h
test/common/tcp_proxy/tcp_proxy_test.cc
test/mocks/stream_info/mocks.cc
test/mocks/stream_info/mocks.h

Commit Message: stream info - add attempt count for HTTP requests and TCP proxy
Testing: UT

stream info: add attempt count for HTTP requests and TCP proxy

---

tools/base/envoy_python.bzl

this allows external tools that depend on envoy tooling to make use of the `pytest_my_tool` setup etc
Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Add `@envoy` prefix in `envoy_py_` macros

---

tools/dependency/validate.py

tools: fix missing format strings

---

tools/base/runner.py
tools/base/tests/test_runner.py
tools/distribution/tests/test_sign.py
tools/docs/sphinx_runner.py
tools/docs/tests/test_sphinx_runner.py

Commit Message: tooling: Move tempdir/cleanup to base runner class
this pattern is repeated increasingly frequently, moving it to the base class saves a load of boilerplate and testing
Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Move tempdir/cleanup to base runner class

---

tools/dependency/validate.py

tools: simplify bazel deps query

---

REPO_LAYOUT.md
source/common/network/connection_impl.cc

Signed-off-by: qinggniq <livewithblank@gmail.com>
Fix an outdated link and uniform the link format.
Commit Message: REPO_LAYOUT.md: fix outdated link
Risk Level:
Testing:
Docs Changes:
Release Notes:

REPO_LAYOUT.md: fix outdated link

---

source/common/config/utility.cc
test/README.md
test/common/config/BUILD
test/common/config/delta_subscription_impl_test.cc
test/common/config/delta_subscription_state_test.cc
test/common/config/delta_subscription_test_harness.h
test/common/config/grpc_mux_impl_test.cc
test/common/config/grpc_stream_test.cc
test/common/config/grpc_subscription_impl_test.cc
test/common/config/grpc_subscription_test_harness.h
test/common/config/http_subscription_impl_test.cc
test/common/config/http_subscription_test_harness.h
test/common/config/new_grpc_mux_impl_test.cc
test/common/config/opaque_resource_decoder_impl_test.cc
test/common/config/subscription_factory_impl_test.cc
test/common/config/subscription_impl_test.cc
test/common/config/utility_test.cc
test/common/upstream/cds_api_impl_test.cc
test/common/upstream/cluster_manager_impl_test.cc
test/common/upstream/eds_test.cc
test/integration/BUILD
test/integration/README.md
test/integration/integration_test.cc

Cleaning up more v2 usage in tests
Testing: n/a

config: v2 test cleanup

---

.github/actions/pr_notifier/pr_notifier.py

Risk Level: n/a (tooling)
Testing: n/a

tools: adding @rojkov to pr notifier

---

source/server/config_validation/server.cc
source/server/config_validation/server.h
test/extensions/filters/http/ext_authz/BUILD
test/extensions/filters/http/ext_authz/ext_authz.yaml
test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc

Signed-off-by: qinggniq <livewithblank@gmail.com>
(cherry picked from commit 0bd670a2c0851cb5d0a21acbb89501afe976f455, PR #17499)
Risk Level:
Testing:
Docs Changes:
Release Notes:

bug fix: return bootstrap when validating config

---

test/integration/proxy_proto_integration_test.cc
test/integration/proxy_proto_integration_test.h

Risk Level: 
Testing:
Docs Changes:
Release Notes:

Fix flaky test ProxyProtoFilterChainMatchIntegrationTest

---

source/common/config/type_to_endpoint.cc
test/common/config/type_to_endpoint_test.cc
test/common/upstream/cluster_manager_impl_test.cc

Risk Level: Medium 
Testing: fixed up sneaky v2 tests

config: removing v2 mappings

---

source/extensions/extensions_metadata.yaml

resolves https://github.com/envoyproxy/envoy/issues/17511.
cc @lizan @azdagron @evan2645
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

doc: promote SPIFFE Cert Validator to alpha, set security_posture.

---

test/mocks/stats/mocks.h

Remove members that shadow members of the base class

---

OWNERS.md

cc @tonya11en @dmitri-d @yanavlasov

docs: updates to envoy security team

---

STYLE.md

fix: typo in STYLE.md from handing to handling

---

source/common/matcher/exact_map_matcher.h
source/common/matcher/field_matcher.h

Commit Message: Change log level from debug to trace.
Additional Description: Current logs are pretty verbose in `debug`. Changing to `trace` to make `debug` cleaner. 
Testing: N/A 
Docs Changes: N/A 

matching api: change log level from debug to trace

---

tools/api/generate_go_protobuf.py

Signed-off-by: Yangmin Zhu <ymzhu@google.com>
Commit Message: update generate_go_protobuf.py to include api/contrib
Testing: Tested locally by running the generate_go_protobuf.py, confirmed the api/contrib is now included in the go-control-plane

tools: update generate_go_protobuf.py to include api/contrib

---

docs/root/intro/arch_overview/operations/draining.rst

docs: clarify graceful drain

---

source/common/conn_pool/conn_pool_base.cc

Commit Message: conn pool - add logging to closing idle client

conn pool: add logging to closing idle client

---

source/common/quic/envoy_quic_client_stream.cc
source/common/quic/envoy_quic_server_stream.cc
source/common/quic/envoy_quic_server_stream.h
source/common/quic/envoy_quic_utils.h
test/common/quic/envoy_quic_utils_test.cc

Follow up from #17520 to make the rst codes more accurate

http3: fixing rst codes

---

.azure-pipelines/cve_scan.yml
tools/dependency/cve_scan.py

Commit Message: tooling: Fix cve scan script
this is not a perfect solution, but it should at least get the scanner working again
Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Fix cve scan script

---

source/server/filter_chain_manager_impl.cc
source/server/filter_chain_manager_impl.h
test/integration/server.h
test/integration/server_stats.h
test/integration/xds_integration_test.cc
test/test_common/utility.cc
test/test_common/utility.h

Crash is reported. 
Risk Level: LOW. Stats may leak and no worse than a week back.
Testing:
Docs Changes:
Release Notes:

Revert "listener: create per network filter chain stats scope (#17931)"

---

.azure-pipelines/cve_scan.yml

Commit Message: ci: Fix cve scan schedule
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Fix cve scan schedule

---

envoy/server/overload/overload_manager.h

Commit Message: FIx a typo
Risk Level:
Testing:
Docs Changes:
Release Notes:

Fix a typo that prevents the spell checker from passing 

---

ci/Dockerfile-envoy-alpine
ci/Dockerfile-envoy-distroless

Commit Message: Update base Alpine and Distroless container images
Signed-off-by: Michael Payne <michael@sooper.org>

CI: Update base Alpine and Distroless container images

---

contrib/kafka/filters/network/test/mesh/integration_test/BUILD

Commit Message: deps: Fix for kafka requirement
Fixes a merging error
Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Fix for kafka requirement

---

test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc

test: fix build

---

tools/docs/rst_check.py
tools/docs/tests/test_rst_check.py

tools: Improve the error message in tools/docs/rst_check.py for invalid backticks
Testing: None

tools: Improve the error message in tools/docs/rst_check.py for invalid backticks

---

tools/dependency/validate.py

Commit Message: tooling: Validation tool cleanup
This is a minor/cleanup PR to fix the docstrings in the dependency validation tool
I have separated these changes here as i have another PR to work on this file, and the cleanups were making that PR hard to review.
Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Validation tool cleanup

---

ci/do_ci.sh
tools/api_proto_breaking_change_detector/BUILD
tools/api_proto_breaking_change_detector/buf_utils.py
tools/api_proto_breaking_change_detector/detector.py
tools/api_proto_breaking_change_detector/detector_ci.py
tools/api_proto_breaking_change_detector/detector_ci.sh
tools/api_proto_breaking_change_detector/detector_test.py

Commit Message: tooling: Shift `api_proto_breaking_change_detector` to bazel
Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Shift `api_proto_breaking_change_detector` to bazel

---

docs/root/start/install.rst

Following the comment: https://github.com/envoyproxy/envoy/issues/17047#issuecomment-878375242
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

doc: add note about rate limit on Docker Hub.

---

.azure-pipelines/pipelines.yml
ci/upload_gcs_artifact.sh
docs/build.sh
docs/publish.sh

Commit Message: docs: Publish rst to storage
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Publish rst to storage

---

test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc

apparently it didn't like 0.0.0.0 for loopback.
Testing: yes

windows: fixing caching test on windows

---

source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc

dns cache: upgrade log to log event

---

source/extensions/filters/listener/original_dst/original_dst.cc
source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc

Signed-off-by: YaoZengzeng <yaozengzeng@huawei.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:

log: make log of listener filters consistent.

---

test/common/shared_pool/shared_pool_test.cc

Commit Message: resolves a tsan race in shared_pool test between the test thread and the main thrad
Risk Level: very low -- only a test change
Testing: just this one test
Docs Changes:
Release Notes:

test: resolve race in test/common/shared_pool:shared_pool_test

---

source/extensions/filters/network/ratelimit/BUILD
source/extensions/stat_sinks/statsd/BUILD
test/common/network/BUILD
test/common/network/filter_manager_impl_test.cc
test/extensions/filters/network/ratelimit/BUILD
test/extensions/filters/network/ratelimit/ratelimit_test.cc

Commit Message: n/a (test only)
Testing: n/a
Part of #9953

test: resolving statsd and ratelimit test locations

---

contrib/cryptomb/private_key_providers/source/BUILD

Additional Description: main branch build broken

fix main branch build

---

PULL_REQUESTS.md
PULL_REQUEST_TEMPLATE.md

Update PR template to include the "Fixes commit" message when reverting or fixing bad commits

---

test/common/http/BUILD
test/extensions/key_value/file_based/BUILD

Additional Description: fixes broken internal build

test: Add missing dependencies

---

contrib/sip_proxy/filters/network/test/conn_manager_test.cc

Commit Message: SIPProxy BUGFIX UT failure for fastbuild/debug
Additional Description:  fix the issue from https://github.com/envoyproxy/envoy/pull/18039
Risk Level:
Testing:
Docs Changes:
Release Notes:

SIPProxy BUGFIX UT failure for fastbuild/debug

---

docs/root/configuration/http/http_filters/cors_filter.rst

Commit Message: Typo Corrections
Additional Description: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/cors_filter
Testing: Unit
Release Notes:

typo corrections

---

source/common/network/cidr_range.cc
source/common/network/cidr_range.h

remove an unused function along with small optimization.
Risk Level:
Testing:
Docs Changes:
Release Notes:

coverage: improve source/source/network

---

source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc

dns cache: upgrade resolve timeout log to log event

---

tools/dependency/cve_scan.py

Commit Message: cvescan: Fix/workaround kafka false +ve
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Workaround for #18354

cvescan: Fix/workaround kafka false +ve

---

api/bazel/repository_locations.bzl

bazel: update xds to include go_package annotations

---

api/envoy/extensions/filters/http/ratelimit/v3/rate_limit.proto
api/envoy/service/auth/v3/external_auth.proto
api/envoy/type/matcher/v3/regex.proto

Commit Message: protos: Remove unused protos
Risk Level:
Testing:
Docs Changes:
Release Notes:

protos: Remove unused protos

---

tools/deprecate_version/BUILD
tools/deprecate_version/deprecate_version.py

Commit Message: tooling: Fix deprecate_version PATH
Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Fix deprecate_version PATH

---

source/common/common/BUILD
source/common/common/dns_utils.cc
source/common/common/dns_utils.h
source/common/upstream/BUILD
source/extensions/clusters/dynamic_forward_proxy/BUILD
source/extensions/common/dynamic_forward_proxy/BUILD
source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc

Risk Level: n/a (moving code)
Testing: n/a

dns: moving code to dns utils

---

source/common/runtime/runtime_features.cc
test/common/protobuf/utility_test.cc
test/config/utility.cc
test/config/utility.h
test/server/test_data/server/zipkin_tracing_deprecated_config.yaml

test: cleaning up deprecated flag

---

source/extensions/filters/common/rbac/matchers/upstream_ip_port.h
test/extensions/filters/http/rbac/rbac_filter_integration_test.cc

Fixing extension name in multiple places to  match the extension metadata.
Testing: Existing unit, integration testing
Signed-off-by: Jojy George Varghese <jojy_varghese@apple.com>

[rbac]: Fix extension name.

---

test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc

dfp: fixing test for systems without v4 support

---

docs/root/configuration/observability/access_log/usage.rst

Signed-off-by: Peter Jausovec <peter.jausovec@gmail.com>
Commit Message: Remove an extra word (typo)
Docs Changes: Remove an extra word (typo)

Remove an extra word (typo)

---

bazel/repository_locations.bzl

Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fix #18839

deps: Bump `build_bazel_rules_apple` -> 0.32.0

---

test/extensions/filters/http/lua/lua_filter_test.cc

Commit Message: Add test for lua FilterConfigPerRoute dtor called on worker thread.
There is a conditional block in `~FilterConfigPerRoute`.
Only the testcase `LuaIntegrationTest.RdsTestOfLuaPerRoute` generates coverage there but even that depends on scheduling:
Every thread has a shared pointer to the route config including the per route lua script.
When the RDS updates the routing, all threads assign the new value to the shared pointer.
It is not predictable which will do the last assignment and actually call the destructor of the previous pointed route config.
If last one is worker thread the block is covered if not it is not covered.
(For validation, some delay in the lamda at the beginning of `Envoy::Router::RdsRouteConfigProviderImpl::onConfigUpdate()` like …

test: stabilize coverage for lua filter.

---

contrib/rocketmq_proxy/filters/network/source/conn_manager.cc

Signed-off-by: theidexisted <invalid_ms_user@live.com>
Commit Message: rocketmq_proxy: Improvement for map find
Additional Description: With my change(
heterogeneous lookup), we avoid constructing temporary string objects, save us from memory allocation and deallocation
Risk Level: Very Low
Testing: N/A
Docs Changes:  N/A

rocketmq_proxy: Improvement for map find

---

bazel/envoy_test.bzl

Commit Message: This allows the usage of this rule from other repositories.
Testing: na/

bazel: add repository arg to benchmark_test

---

test/integration/scoped_rds_integration_test.cc

Modify the `InlineScopedRoutesIntegrationTest` to accept the IP version as a parameter.
Risk: N/A. This is a test only change.

test: parameterize 'InlineScopedRoutesIntegrationTest' with IP versions.

---

tools/base/requirements.txt

Risk Level:
Testing:
Docs Changes:
Release Notes:

dependabot: Python (docs) updates

---

test/server/BUILD

test: Remove unused dependencies

---

docs/root/configuration/http/http_filters/_include/grpc-transcoder-filter.yaml

Commit Message: web links in yaml yields "page not found"  
Additional Description: see path https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter#sample-envoy-configuration
Testing: 

broken link path fix for items http_filters/grpc_json_transcoder_filter

---

test/extensions/transport_sockets/starttls/starttls_integration_test.cc

changes from failing 16:200 to passing 100%
Testing: yep
Co-authored-by: Alyssa Wilk <alyssar@chromium.org>
(cherry picked from commit 7136c3ade0a8366a86621a1a3a63993af5573486)
Risk Level:
Testing:
Docs Changes:
Release Notes:

test: deflaking starttls test (#18977)

---

docs/root/version_history/current.rst
source/common/conn_pool/conn_pool_base.cc
source/common/http/conn_pool_base.cc
source/common/http/conn_pool_base.h
test/common/http/http2/conn_pool_test.cc
tools/spelling/spelling_dictionary.txt

Commit Message: remove negative_capacity_ to make the code easier to understand
Additional Description: fixes part I of #18880
Testing: unit

http2: remove unnecessary negative_capacity_

---

api/envoy/extensions/filters/network/meta_protocol_proxy/matcher/action/v3/action.proto
api/envoy/extensions/filters/network/meta_protocol_proxy/matcher/v3/matcher.proto
api/envoy/extensions/filters/network/meta_protocol_proxy/v3/meta_protocol_proxy.proto
api/envoy/extensions/filters/network/meta_protocol_proxy/v3/route.proto

This was caused by a merge race

protos: add more go_package annotations

---

.bazelci/presubmit.yml

Signed-off-by: Yun Peng pcloudy@google.com
Commit Message: Install additional dependencies on Bazel CI
Fixes https://github.com/envoyproxy/envoy/issues/19196

Update presubmit.yml for Bazel CI

---

source/extensions/filters/listener/original_dst/BUILD
test/integration/BUILD

test: cleaning up original dst visibility

---

OWNERS.md

Removing myself from the list of maintainers.
Additional Description: As I mentioned on the Slack channel, I will step down for the time being as I won't have the time needed to support the project. I will support all of you from the sidelines.
Thanks a lot for everything, it has been an amazing journey working with all of you. You are all incredible.
Testing: N/A
Signed-off-by: Sotiris Nanopoulso <sotirisnan@gmail.com>

Step-down: Sotiris

---

envoy/stream_info/stream_info.h
source/common/http/codec_client.cc
source/common/router/upstream_request.cc
source/common/stream_info/stream_info_impl.h
test/integration/BUILD
test/integration/filters/stream_info_to_headers_filter.cc
test/integration/http_integration.cc
test/integration/multiplexed_upstream_integration_test.cc

http: track how many streams are on a connection

---

api/envoy/service/discovery/v2/ads.proto
api/envoy/service/discovery/v3/ads.proto
bazel/foreign_cc/BUILD
bazel/repository_locations.bzl
docs/root/version_history/v1.8.0.rst
envoy/common/platform.h

docs: replace old Lyft URLs (NFC)

---

api/envoy/type/matcher/v3/regex.proto

Commit Message: Refer #18633. discussion with @rojkov, adding Note Section in Matcher doc for better clarity of "`max_program_size`" uses
part of #18633

To Add Note Section in Matcher

---

source/common/network/utility.cc
test/common/network/utility_test.cc

Commit Message: network utility -- fix bug with ip version filtering in getLocalAddress
Testing: added testing
Fixes #19231

network utility: fix bug with ip version filtering in getLocalAddress

---

RELEASES.md

Fixes https://github.com/envoyproxy/envoy/issues/19228

governance: shifting release dates

---

source/common/network/connection_impl.cc

connection: update connecting log line to log event

---

envoy/tracing/BUILD
envoy/tracing/custom_tag.h
envoy/tracing/trace_config.h
envoy/tracing/trace_driver.h
source/common/router/BUILD
source/common/router/config_impl.cc
source/common/tracing/BUILD
source/common/tracing/custom_tag_impl.cc
source/common/tracing/custom_tag_impl.h
source/common/tracing/http_tracer_impl.cc
source/common/tracing/http_tracer_impl.h
source/extensions/filters/network/http_connection_manager/config.cc
test/common/http/BUILD
test/common/http/conn_manager_impl_test_base.h
test/common/tracing/http_tracer_impl_test.cc

Commit Message: tracing: separate custom tag interface from trace driver
Additional Description: This is part of https://github.com/envoyproxy/envoy/pull/18955.
Testing:
Docs Changes:
Release Notes:

tracing: separate custom tag interface from trace driver

---

.github/actions/pr_notifier/pr_notifier.py
.github/workflows/pr_notifier.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling:allow pr_notifier to be run manually more easily.

---

api/envoy/config/core/v3/protocol.proto

Risk Level: n/a (docs only)
Testing: n/a
Fixes: #19302

docs: attempting clarity

---

docs/root/intro/life_of_a_request.rst

doc: fix a dead link

---

docs/root/version_history/v1.16.0.rst

doc: fix dead BUILD link

---

test/integration/protocol_integration_test.cc

Part of https://github.com/envoyproxy/envoy/issues/19430

test: adding debug info

---

source/common/runtime/runtime_features.cc
test/integration/BUILD

Risk Level:
Testing:
Docs Changes:
Release Notes:

defering inline write flip to post-release

---

docs/root/configuration/best_practices/_include/edge.yaml

Fixes https://github.com/envoyproxy/envoy/issues/19451
co-authored-by: @jiangdongzi

docs: fix up h2 example config

---

test/integration/BUILD
test/run_envoy_bazel_coverage.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

test: get better logs

---

docs/root/version_history/current.rst
source/common/network/connection_impl.cc
source/common/network/connection_impl.h
test/common/network/connection_impl_test.cc

Trying to avoid double error messages: see https://github.com/envoyproxy/envoy/issues/19443
Testing: no

connect: hopefully address envoy bug

---

docs/BUILD
tools/dependency/BUILD
tools/dependency/cve_scan.py
tools/dependency/exports.py
tools/dependency/utils.py
tools/docs/BUILD
tools/docs/generate_external_deps_rst.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Use bazel repository_locations metadata

---

test/extensions/filters/http/kill_request/kill_request_filter_integration_test.cc
test/per_file_coverage.sh

test: disabling a flaky test

---

.github/actions/pr_notifier/pr_notifier.py
CODEOWNERS
OWNERS.md
tools/code_format/check_format.py

@asraa sorry to see you go - thanks so much for all of your help on Envoy!
@KBaichoo @adisuissa welcome aboard!

maintainers: additions and subtractions

---

api/bazel/repository_locations.bzl

Gets rid of a few more build warnings

xds: bumping deps

---

test/integration/protocol_integration_test.cc

Testing: yes
Part of https://github.com/envoyproxy/envoy/issues/19430

test: adding debug info for windows flake

---

OWNERS.md

owners: add Trail of Bits to PST for current contract.

---

bazel/envoy_select.bzl
bazel/wasm/wasm.bzl
test/tools/wee8_compile/wee8_compile.cc

wasm: precompile for V8 only when testing V8 runtime.

---

test/extensions/filters/http/stateful_session/stateful_session_integration_test.cc

Signed-off-by: wbpcode <wbphub@live.com>
Commit Message: fix stateful session test flakes
Address #19540 cc @alyssawilk 
Testing: N/A.

fix stateful session test flakes

---

source/extensions/BUILD
tools/base/envoy_python.bzl
tools/extensions/BUILD
tools/extensions/extensions_check.py
tools/extensions/tests/test_extensions_check.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Use bazel json data for extensions check

---

docs/root/version_history/current.rst
source/common/router/router.cc
source/common/router/router.h
source/common/runtime/runtime_features.cc
source/common/upstream/health_checker_impl.cc
test/common/router/router_test.cc
test/common/upstream/health_checker_impl_test.cc

Testing: n/a
Fixes https://github.com/envoyproxy/envoy/issues/18441

runtime: remove envoy.reloadable_features.preserve_downstream_scheme

---

docs/root/configuration/http/http_filters/stateful_session_filter.rst

Signed-off-by: John Howard <howardjohn@google.com>
Commit Message: docs: fix stateful_session_filter config
Testing: None
Docs Changes: This is a doc change
Release Notes:

docs: fix stateful_session_filter config

---

source/common/http/codec_client.cc
source/common/http/conn_pool_base.cc
source/common/http/http1/legacy_parser_impl.cc
source/common/json/json_internal.cc
source/common/json/json_internal_legacy.cc
source/common/network/cidr_range.cc
source/common/network/utility.cc
source/common/protobuf/utility.cc
source/common/quic/codec_impl.h
source/common/quic/envoy_quic_client_session.cc
source/common/quic/envoy_quic_proof_verifier_base.cc
source/common/quic/quic_filter_manager_connection_impl.h
source/common/quic/quic_transport_socket_factory.h
source/common/runtime/runtime_impl.cc
source/common/stats/tag_extractor_impl.cc
source/common/stats/timespan_impl.cc
source/common/tracing/custom_tag_impl.cc
source/common/upstream/cluster_manager_impl.cc
source/common/upstream/outlier_detection_impl.cc
source/common/upstream/subset_lb.cc
test/per_file_coverage.sh

part of https://github.com/envoyproxy/envoy/issues/19172

removing more gcovr macros

---

test/integration/multiplexed_integration_test.cc

part of https://github.com/envoyproxy/envoy/issues/19595

test: hopefully deflaking slow coverage test by lowering logging

---

docs/root/configuration/http/http_filters/grpc_http1_bridge_filter.rst
docs/root/version_history/current.rst
source/common/runtime/runtime_features.cc
source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.cc
source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.h
test/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter_test.cc

Signed-off-by: changran <changran.wang@intel.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes https://github.com/envoyproxy/envoy/issues/19503

grpc_bridge_filter: envoy.reloadable_features.grpc_bridge_stats_disabled deprecation

---

bazel/repository_locations.bzl

wasm: update V8 to v9.9.115.3.

---

docs/root/intro/arch_overview/intro/threading_model.rst

Commit Message: docs: fix spelling
Testing: None
Docs Changes: Spelling

docs: fix spelling

---

docs/root/configuration/http/http_filters/_include/stateful-cookie-session.yaml
docs/root/configuration/http/http_filters/http_filters.rst
docs/root/configuration/http/http_filters/stateful_session_filter.rst
docs/root/configuration/http/http_filters/wasm_filter.rst

Follow up from https://github.com/envoyproxy/envoy/pull/19653/files#r789890154
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Shift stateful session config example to yaml

---

source/common/router/router.cc

Fixes https://github.com/envoyproxy/envoy/issues/19682

router: improving trace logs for internal redirects

---

bazel/repository_locations.bzl

Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes commit #PR or SHA] Fix #19674

deps: Bump `rules_fuzzing` -> 0.3.1

---

bazel/repository_locations.bzl

Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fix #19675

deps: Bump `rules_pkg` -> 0.6.0

---

.azure-pipelines/pipelines.yml

ci: explicit windows version

---

bazel/repository_locations.bzl
source/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator.cc
test/per_file_coverage.sh

tls: update BoringSSL to 5416e4f1 (4844).

---

.github/workflows/check-deps.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/deps: Add `--fix` flag for release issues

---

ci/README.md

Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #19729

build: enable code coverage for contrib extension

---

source/common/router/config_impl.cc

Modify the condition for logging

---

bazel/repository_locations.bzl

Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fix #19658

deps: Bump `rules_apple` -> 0.33.0

---

source/extensions/filters/common/fault/fault_config.cc
source/extensions/filters/common/rbac/engine_impl.cc
source/extensions/filters/common/rbac/matchers.cc
source/extensions/filters/http/admission_control/config.cc
source/extensions/filters/http/aws_lambda/config.cc
source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc
source/extensions/filters/http/ext_authz/ext_authz.cc
source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc
source/extensions/filters/http/header_to_metadata/header_to_metadata_filter.cc
source/extensions/filters/http/ip_tagging/ip_tagging_filter.h
source/extensions/filters/http/jwt_authn/filter_config.cc
source/extensions/filters/http/jwt_authn/jwks_cache.cc
source/extensions/filters/http/jwt_authn/matcher.cc
source/extensions/filters/http/jwt_authn/verifier.cc
source/extensions/filters/http/ratelimit/ratelimit.cc
source/extensions/filters/listener/http_inspector/http_inspector.cc
source/extensions/filters/listener/tls_inspector/tls_inspector.cc
source/extensions/filters/network/common/redis/fault_impl.cc
source/extensions/filters/network/dubbo_proxy/router/router_impl.cc
source/extensions/filters/network/thrift_proxy/router/upstream_request.cc
source/extensions/filters/network/thrift_proxy/thrift.h
source/extensions/filters/udp/udp_proxy/hash_policy_impl.cc
source/extensions/network/dns_resolver/apple/apple_dns_impl.cc
source/extensions/transport_sockets/tls/context_config_impl.cc
test/extensions/filters/udp/udp_proxy/hash_policy_impl_test.cc
test/per_file_coverage.sh

Part of https://github.com/envoyproxy/envoy/issues/19172

source: more GCOVR removals

---

.azure-pipelines/pipelines.yml

Commit Message: CI: Increase docker multiarch timeout.
Additional Description: See related issue
Testing:
Fixes #19958

CI: Increase docker multiarch timeout.

---

source/server/admin/admin.cc
source/server/admin/admin_filter.cc

Commit Message: Demotes an info log to a debug log, and removes some spurious comments
Testing: //test/server/admin/...

admin: cleanup spurious comments and info log.

---

tools/gen_compilation_database.py

Signed-off-by: Lucas Lu <lucasludev@gmail.com>
Commit Message: Currently this script has options for external, headers, and generated files. I would like to make development/testing slightly easier by adding an include_all argument to this script
Testing: N/A
Release Notes:

Update gen_compilation_database.py in tools folder with include_all argument

---

contrib/sip_proxy/filters/network/source/conn_manager.cc
contrib/sip_proxy/filters/network/source/decoder.cc
contrib/sip_proxy/filters/network/source/router/router_impl.cc
source/common/common/assert.h
source/extensions/common/matcher/matcher.cc
source/extensions/common/tap/admin.cc
source/extensions/common/tap/extension_config_base.cc
source/extensions/common/tap/tap_config_base.cc
source/extensions/common/wasm/context.cc
source/extensions/filters/common/lua/wrappers.cc
source/extensions/health_checkers/redis/redis.cc
source/extensions/stat_sinks/common/statsd/statsd.cc
source/extensions/stat_sinks/graphite_statsd/config.cc
source/extensions/stat_sinks/statsd/config.cc
source/server/admin/profiling_handler.cc
source/server/admin/utils.cc
source/server/config_validation/api.cc
source/server/connection_handler_impl.cc
source/server/listener_impl.cc
source/server/overload_manager_impl.cc
test/per_file_coverage.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes https://github.com/envoyproxy/envoy/issues/19172

Last gcovr

---

.github/workflows/check-deps.yml
.github/workflows/codeql-daily.yml
.github/workflows/codeql-push.yml

Follow up from https://github.com/envoyproxy/envoy/pull/19914#discussion_r804918163
Risk Level:
Testing:
Docs Changes:
Release Notes:

repo: Remove ~redundant version comments in gh actions

---

source/server/listener_impl.h

Commit Message: Listener: remove unused member from ListenerImpl
Testing: n/a

Listener: remove unused member from ListenerImpl

---

BUILD
test/tools/schema_validator/BUILD

Required to verify nested type configs
Risk Level: Low, link change to test tool
Testing: Manual. Will circle back with actual tests for this thing.

tools: link all extensions into schema validator

---

docs/root/version_history/v1.18.6.rst
docs/root/version_history/v1.19.3.rst
docs/root/version_history/v1.20.2.rst
docs/root/version_history/v1.21.1.rst
docs/root/version_history/version_history.rst

Update version history to reflect recent security release

---

docs/root/version_history/current.rst

Follow up to https://github.com/envoyproxy/envoy/pull/20004 and
https://github.com/envoyproxy/envoy/pull/20048.

docs: add missing rel note for tools image and schema validator

---

source/server/admin/logs_handler.cc
test/server/admin/logs_handler_test.cc

Signed-off-by: Tianpeng Wang <tpwang@alauda.io>
Commit Message: admin: improve logs handler test coverage
Additional Description: This is a follow-up of #19868, in this PR which should increase coverage to  100%

admin: improve logs handler test coverage

---

tools/base/requirements.txt
tools/base/requirements_win.in

Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Aggregate dependabot updates

---

docs/root/configuration/listeners/udp_filters/udp_proxy.rst

Signed-off-by: changran <changran.wang@intel.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: fix small typo

---

bazel/README.md

Signed-off-by: HaoTu haotu@alauda.io
Commit Message: add "trouble shooting" for macOS
Risk Level: 
Testing: 
Docs Changes: https://github.com/envoyproxy/envoy/blob/main/bazel/README.md
[Optional Fixes #Issue] Fixes #20046

docs: add "troubleshooting" for macOS

---

api/STYLE.md

Signed-off-by: Tianyu Xia [tyxia@google.com](mailto:tyxia@google.com)

docs: clarify the workflow to ensure the changes are effective 

---

examples/verify-common.sh
support/bootstrap
test/extensions/transport_sockets/tls/ocsp/test_data/certs.sh
test/extensions/transport_sockets/tls/test_data/certs.sh
tools/shell_utils.sh

Partial fix for #20199 
Risk Level:
Testing:
Docs Changes:
Release Notes:

repo: Fix shellcheck errors (in newer version)

---

api/bazel/repositories.bzl
api/bazel/repository_locations.bzl

Fix #19918
Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Remove `com_github_bazel_buildtools`

---

bazel/README.md

Add more comments for clang-format
Signed-off-by: bozhang <bozhang@ebay.com>
Refe to https://github.com/envoyproxy/envoy/pull/20175

Add more comments for clang-format

---

envoy/matcher/matcher.h
source/common/matcher/matcher.h
source/extensions/common/matcher/trie_matcher.h
test/extensions/common/matcher/trie_matcher_test.cc

Commit Message: matchers: implement on_no_match for custom matchers
Risk Level: low (new feature)
Testing: unit
Release Notes:

matchers: implement on_no_match for custom matchers

---

source/common/upstream/upstream_impl.cc
source/server/listener_manager_impl.cc

prefer ref and move to copy
Testing:
Docs Changes:
Release Notes:

perf: config message tiny optimization

---

OWNERS.md

setec: adding folks

---

source/common/network/cidr_range.cc
source/common/network/utility.cc
source/extensions/filters/udp/dns_filter/dns_parser.cc
source/extensions/transport_sockets/tls/utility.cc
test/common/network/address_impl_speed_test.cc
test/common/network/address_impl_test.cc
test/extensions/network/dns_resolver/apple/apple_dns_impl_test.cc

Commit Message: cleanup: zero out sockaddr_in/sockaddr_in6
Testing: n/a

cleanup: zero out sockaddr_in/sockaddr_in6

---

bazel/README.md

Risk Level:
Testing:
Docs Changes:
Release Notes:

bazel: Small cleanup to README

---

test/config_test/config_test.cc
test/config_test/config_test.h

Testing:
Docs Changes:
Release Notes:

test: remove dead code in config_test.cc

---

test/integration/stats_integration_test.cc

Fixes https://github.com/envoyproxy/envoy/issues/20331 for now

test: silence flake

---

.github/workflows/codeql-push.yml

Signed-off-by: LL <loong.dai@intel.com>
Refer to https://github.com/github/codeql-action/issues/416#issuecomment-810982080
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes commit #PR or SHA] Fix #20329

CI: codeql ignore check PRs from dependabot

---

bazel/boringssl_static.patch
bazel/repository_locations.bzl

tls: update BoringSSL to cacb5526 (4896).

---

CODEOWNERS

pradeepcrao and chaoqin-li1123 will be working on and reviewing changes to the ext_proc.
Testing: N/A

Add pradeepcrao and chaoqin-li1123 as ext_proc owners

---

OWNERS.md

owners: move junr03 to emeritus

---

source/extensions/tracers/skywalking/skywalking_tracer_impl.cc
test/extensions/tracers/skywalking/skywalking_tracer_impl_test.cc

Signed-off-by: wbpcode <wbphub@live.com>
Commit Message: fix error instance name of skywalking
Fix #20288 
Testing: Updated.

fix error instance name of skywalking

---

examples/cache/service.py
examples/dynamic-config-cp/Dockerfile-control-plane

Fix #20360
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] 

v1.18 fix examples

---

CODEOWNERS

Risk Level:
Testing:
Docs Changes:
Release Notes:

Add weisisea as redis extension owner

---

docs/root/intro/arch_overview/operations/draining.rst

draining: document thrift support

---

api/envoy/extensions/common/dynamic_forward_proxy/v3/dns_cache.proto
docs/root/version_history/current.rst
source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc
source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h
test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc

dns cache: add dns_min_refresh_rate configuration

---

NOTICE

Per https://github.com/cncf/foundation/blob/main/copyright-notices.md#copyright-notices

notice: fix to remove dates

---

.github/actions/pr_notifier/pr_notifier.py
OWNERS.md

maintainers: add wbpcode

---

source/extensions/filters/http/jwt_authn/authenticator.cc
source/extensions/filters/http/jwt_authn/filter.cc
source/extensions/filters/http/jwt_authn/filter_config.h
source/extensions/filters/http/jwt_authn/filter_factory.cc
source/extensions/filters/http/jwt_authn/jwks_cache.cc
source/extensions/filters/http/jwt_authn/jwks_cache.h
source/extensions/filters/http/jwt_authn/jwt_cache.cc
source/extensions/filters/http/jwt_authn/verifier.cc

Flush the non functional changes while I am waiting for the feedback at api 
includes the changes regarding binding, const, header including and typo fix
Docs Changes:
Release Notes:

jwt_auth: better engineering

---

source/extensions/tracers/skywalking/skywalking_tracer_impl.cc
source/extensions/tracers/skywalking/tracer.cc
source/extensions/tracers/skywalking/tracer.h
test/extensions/tracers/skywalking/tracer_test.cc

Commit Message: skywalking: simplify span interface
Testing: N/A
Docs Changes:
Release Notes:

skywalking: simplify span interface

---

test/integration/buffer_accounting_integration_test.cc

Commit Message: Test cleanup: Remove excess parameterization
Additional Description:  was already occurring via HTTPProtocolTestParam
With change:
```
took: //test/integration:buffer_accounting_integration_test           (cached) PASSED in 31.7s
Stats over 4 runs: max = 31.7s, min = 10.8s, avg = 21.2s, dev = 10.4s
```
Without change:
```
INFO: Build completed successfully, 7 total actions
//test/integration:buffer_accounting_integration_test                    PASSED in 62.7s
Stats over 4 runs: max = 62.7s, min = 21.0s, avg = 41.8s, dev = 20.9s
```
Testing: Ran test …

Test cleanup: Remove excess parameterization

---

OWNERS.md

Move dio to emeritus

---

docs/root/operations/tools/route_table_check_tool.rst
test/tools/router_check/BUILD
test/tools/router_check/router.cc
test/tools/router_check/router.h
test/tools/router_check/router_check.cc
test/tools/router_check/test/BUILD
test/tools/router_check/test/router_test.cc
test/tools/router_check/validation.proto
tools/code_format/check_format.py

Signed-off-by: Zurab Svianadze <zurab@google.com>
Commit Message: router check tool: add an option to write test results to a file.
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes #20064

router check tool: add an option to write test results to a file.

---

OWNERS.md

Welcome and thank you so much!!!

owners: add Keith Smiley

---

ci/format_pre.sh

Fix #20459 
Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Yapf fix diff

---

source/extensions/access_loggers/file/BUILD
source/extensions/filters/http/buffer/BUILD
source/extensions/filters/network/common/BUILD

Risk Level: n/a (visibility only)
part of https://github.com/envoyproxy/envoy/issues/9953

builld: tweaking visibility rules

---

docs/root/start/quick-start/configuration-dynamic-filesystem.rst
docs/root/start/quick-start/run-envoy.rst

Commit Message: add one line note in the start docs about the ipv6
Try to reduce questions like in #20542.
Risk Level: N/A.
Testing: N/A.
Docs Changes: Docs Only.

add some more note about ipv6 support of docker networking in the start docs

---

test/common/http/filter_manager_test.cc

Commit Message: increasing filter_manager coverage
Additional Description: Added a call to the `addStreamEncoderFilter` method.
Risk Level: Low (tests only)
Testing: N/A

test: increasing filter_manager coverage

---

bazel/repository_locations.bzl

Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fix #20502

deps: Bump `build_bazel_rules_apple` -> 0.34.0

---

.azure-pipelines/pipelines.yml

as space appears to be running out for this job
Risk Level:
Testing:
Docs Changes:
Release Notes:

repo: Add cleanup.sh for x64 release job

---

test/extensions/transport_sockets/tls/integration/BUILD
test/extensions/transport_sockets/tls/integration/sni_to_header_filter.cc
test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc
test/extensions/transport_sockets/tls/ssl_socket_test.cc
tools/code_format/check_format.py

Add tests for Ssl::ConnectionInfo::sni

---

examples/local_ratelimit/ratelimit-envoy.yaml

Risk Level:
Testing:
Docs Changes:
Release Notes:

examples: fix merge race

---

docs/root/start/sandboxes/gzip.rst
examples/gzip/gzip-envoy.yaml
examples/gzip/service.py
examples/gzip/verify.sh

Commit Message: add gzip decompression example
Risk Level:
Testing:
Docs Changes:
Release Notes:

examples: add gzip decompression

---

.azure-pipelines/pipelines.yml

prevent future (branch) CI from breaking
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Pin macos-latest VM version

---

ci/Dockerfile-envoy

Risk Level:
Testing:
Docs Changes:
Release Notes:

build: Pin distroless base image with sha

---

STYLE.md

docs: updating exception policy

---

examples/local_ratelimit/ratelimit-envoy.yaml
examples/local_ratelimit/verify.sh

Enlarge refresh time to make token refill as expected.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes commit #PR or SHA] Fix #20712

examples: fix flaky example

---

source/common/http/alternate_protocols_cache_impl.cc
source/common/http/alternate_protocols_cache_impl.h
test/common/http/alternate_protocols_cache_impl_test.cc

Part of https://github.com/envoyproxy/envoy/issues/20696

http3: allowing caching srtt without alt-svc

---

.azure-pipelines/pipelines.yml
ci/docker_ci.sh
ci/mac_ci_steps.sh
examples/cache/service.py

- partial fix for macOS (VM)
- fix for windows VM
- fix cache verify example
- fix VRP verify example
Risk Level:
Testing:
Docs Changes:
Release Notes:

[backport/v1.19] ci: Fix broken tests

---

test/integration/multiplexed_integration_test.cc

fixes https://github.com/envoyproxy/envoy/issues/20585

test: deflaking AdjustUpstreamSettingsMaxStreams

---

docs/root/configuration/http/http_filters/oauth2_filter.rst
docs/root/configuration/http/http_filters/original_src_filter.rst
docs/root/configuration/listeners/listener_filters/http_inspector.rst
docs/root/configuration/overview/examples.rst
docs/root/intro/arch_overview/http/http_connection_management.rst
docs/root/intro/arch_overview/other_features/ip_transparency.rst
docs/root/operations/traffic_tapping.rst

Commit Message: Fix more examples (all router and raw_buffer plus some more I found). Convert some examples to use validated code blocks.
Testing: none

docs: fix more examples to use type URL

---

.azure-pipelines/pipelines.yml
ci/docker_ci.sh
examples/cache/service.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

[backport/v1.21] ci: Fix tests

---

.azure-pipelines/pipelines.yml
ci/docker_ci.sh
examples/cache/service.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

[backport/v1.20] ci: Fix tests

---

docs/root/configuration/listeners/listener_filters/original_src_filter.rst

Commit Message: doc: add note for original source listener filter required CAP_NET_ADMIN
Avoid the question like #20776
Testing: n/a
Fixes #20776

doc: add note for original source listener filter required CAP_NET_ADMIN

---

api/envoy/config/cluster/v3/cluster.proto
docs/root/intro/arch_overview/upstream/connection_pooling.rst

docs: Add an overview of Happy Eyeballs Support
Testing: N/A
Docs Changes: Add an overview of Happy Eyeballs Support

docs: Add an overview of Happy Eyeballs Support

---

api/envoy/extensions/filters/http/composite/v3/composite.proto

Commit Message: docs only: fix doc link for composite filter
Additional Description: An occasionally discovery.
Risk Level: None.
Testing: N/A.

docs only: fix doc link for composite filter

---

source/common/upstream/load_balancer_impl.cc

Commit Message: upstream lb: Improve config check.
Prevent illegal config value for aggression_runtime to set
aggression_ to nan.
Testing: n/a

upstream lb: Improve config check.

---

source/common/conn_pool/conn_pool_base.cc
source/common/http/conn_pool_base.cc

conn pool: enhance debug logging

---

docs/root/configuration/operations/overload_manager/overload_manager.rst

Commit Message: Docs: Fix math comment.
Additional Description: Need to escape % in math.
Risk Level: NA
Testing: played around in https://livesphinx.herokuapp.com/
Docs Changes: incld

Docs: Fix math comment.

---

GOVERNANCE.md
docs/README.md
docs/publish.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

website: Rename repo `envoyproxy.github.io` -> `envoy-website`

---

test/integration/filters/encoder_decoder_buffer_filter.cc
test/integration/filters/modify_buffer_filter.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

test: fix typos

---

ci/repokitteh/modules/docs.star
repokitteh.star

- in response to /docs command
- for any PR that has a prefix of `docs:`
Risk Level:
Testing:
Docs Changes:
Release Notes:

repokitteh: Print docs link

---

docs/conf.py
docs/root/version_history/v1.20.0.rst

Minor cleanup to ensure version history links are correct
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Fix mappings for version history links

---

.github/dependabot.yml

- Included dependabot for gomod.
- https://github.com/envoyproxy/envoy/pull/20930#issuecomment-1106126126
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

Included dependabot for gomod

---

source/extensions/filters/network/common/BUILD

Commit Message: This allows out-or-repo filters to use it.
Docs Changes:
Release Notes:

build: make factory_base_lib visibility public

---

.github/actions/pr_notifier/pr_notifier.py
CODEOWNERS
OWNERS.md

1) Remove Dmitry
2) Add Kuat
Also other CODEOWNERS cleanups.

owners: maintainer updates

---

.bazelrc

The absl flagsaver logs every time it restores flags and this is the best way I can find to silence it
https://github.com/abseil/abseil-cpp/blob/master/absl/base/internal/raw_logging.cc#L147

build: silencing absl logspam

---

test/integration/multiplexed_integration_test.cc
test/integration/protocol_integration_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

test: deflaking settings test more

---

bazel/dependency_imports.bzl

bazel: add arm64 iOS simulator rust support

---

test/extensions/filters/network/thrift_proxy/integration_test.cc
test/extensions/filters/network/thrift_proxy/translation_integration_test.cc
test/integration/base_integration_test.h
test/integration/http2_flood_integration_test.cc
test/integration/quic_http_integration_test.cc

Part of https://github.com/envoyproxy/envoy/issues/21017 and https://github.com/envoyproxy/envoy/issues/21019

tests: disabling flaky tests

---

test/extensions/filters/network/thrift_proxy/config_test.cc

Commit Message: thrift proxy: fix function spelling in the tests of thrift proxy
Simple name spelling fix.
Risk Level: None.
Testing: N/A.

thrift proxy: fix function spelling in the tests of thrift proxy

---

tools/spelling/check_spelling_pedantic.py

spelling: remove redundant checking for third_party

---

source/extensions/filters/http/file_system_buffer/filter.cc
source/extensions/filters/http/file_system_buffer/filter.h
test/extensions/filters/http/file_system_buffer/BUILD
test/extensions/filters/http/file_system_buffer/filter_test.cc

Commit Message: Add implementation for file_system_buffer filter
Additional Description: Integration test follows in the next PR.
Risk Level: None, not yet used.
Testing: 100% coverage.

Add implementation for file_system_buffer filter

---

ci/README.md
ci/run_envoy_docker.sh

Signed-off-by: HaoTu <haotu@alauda.io>
#21098

support go_proxy to replace default GOPROXY in run_envoy_docker.sh

---

LICENSE

Commit Message: update license file to match Apache official file
The LICENSE file had a minor change (additional '.') compared to the Apache official LICENSE file.
Executed: `wget https://www.apache.org/licenses/LICENSE-2.0.txt -O LICENSE` to match the license file.
Testing: N/A.

license: update license file to match Apache official file

---

source/extensions/filters/http/file_system_buffer/filter.cc
source/extensions/filters/http/file_system_buffer/fragment.h
test/extensions/filters/http/file_system_buffer/BUILD
test/extensions/filters/http/file_system_buffer/filter_integration_test.cc
test/extensions/filters/http/file_system_buffer/filter_test.cc

Commit Message: Add integration test to file_system_buffer filter
Risk Level: None, test-only
Testing: Yes

Add integration test to file_system_buffer filter

---

configs/proxy_connect.yaml

config: fixing example config

---

changelogs/1.7.1.yaml

Small cleanup to add (the only) missing changelog
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Add missing changelog (1.7.1)

---

docs/root/operations/admin.rst

Commit Message: fix admin docs
Testing:
Docs Changes:
Release Notes:

docs: fix reference in admin docs

---

CODEOWNERS

@mattklein123 as promised (a bit later due to vacation), here's the PR to add myself to the code owners for tracing extensions.
Signed-off-by: Bas van Beek <bas@tobin.nl>
Risk Level:
Testing:
Docs Changes:
Release Notes:

Update CODEOWNERS for tracing extensions

---

api/contrib/envoy/extensions/filters/network/sip_proxy/v3alpha/sip_proxy.proto
contrib/sip_proxy/filters/network/source/BUILD
contrib/sip_proxy/filters/network/source/app_exception_impl.cc
contrib/sip_proxy/filters/network/source/conn_manager.cc
contrib/sip_proxy/filters/network/source/conn_manager.h
contrib/sip_proxy/filters/network/source/decoder.cc
contrib/sip_proxy/filters/network/source/decoder.h
contrib/sip_proxy/filters/network/source/filters/BUILD
contrib/sip_proxy/filters/network/source/filters/filter.h
contrib/sip_proxy/filters/network/source/metadata.cc
contrib/sip_proxy/filters/network/source/metadata.h
contrib/sip_proxy/filters/network/source/router/router_impl.cc
contrib/sip_proxy/filters/network/source/router/router_impl.h
contrib/sip_proxy/filters/network/source/sip.h
contrib/sip_proxy/filters/network/source/stats.h
contrib/sip_proxy/filters/network/source/utility.cc
contrib/sip_proxy/filters/network/source/utility.h
contrib/sip_proxy/filters/network/test/decoder_test.cc
contrib/sip_proxy/filters/network/test/mocks.cc
contrib/sip_proxy/filters/network/test/mocks.h
contrib/sip_proxy/filters/network/test/router_test.cc
contrib/sip_proxy/filters/network/test/tra_test.cc

Commit Message: sip-proxy: add local cache limitation and refactor affinity handler
Testing: Ut/Mt
Docs Changes:
Release Notes:

sip-proxy: add local cache limitation and refactor affinity handler

---

api/envoy/extensions/access_loggers/grpc/v3/als.proto

Commit Message:fix docs in retry policy
Testing: N/a
Docs Changes:N/A
Release Notes:N/A

accesslog: fix docs in retry policy

---

changelogs/1.10.0.yaml
changelogs/1.16.0.yaml
changelogs/1.16.5.yaml
changelogs/1.17.4.yaml
changelogs/1.18.4.yaml
changelogs/1.19.1.yaml
changelogs/1.7.0.yaml
changelogs/1.8.0.yaml
changelogs/1.9.0.yaml
changelogs/1.9.1.yaml
changelogs/sections.yaml

Backtick cleanup found from fixing the tooling
Date format is made consistent with other changelogs
Risk Level:
Testing:
Docs Changes:
Release Notes:

changelogs: Minor cleanups

---

docs/BUILD
tools/base/requirements.in
tools/base/requirements.txt
tools/docs/BUILD
tools/docs/generate_version_histories.py
tools/docs/versions_check.py

and add required fixes
Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Bump `envoy.base.utils`

---

docs/root/configuration/http/http_filters/_include/admission-control-filter.yaml
docs/root/configuration/http/http_filters/admission_control_filter.rst

Commit Message: docs: fix admission control sample usage
Docs Changes: Please see [discussion in Issue here](https://github.com/envoyproxy/envoy/issues/21221)

docs: fix admission control sample usage

---

test/fuzz/common.proto

Commit Message: fuzz test: Add protobuf validate expression.
Add a validate expression to test specific protobuf files fixing an
assert.
Testing: n/a
API Considerations: Just add a validate expression, to prevent fuzzer (and users checking their configuration) to use illegal characters in header-value like options.

fuzz test: Add protobuf validate expression.

---

source/common/upstream/cluster_manager_impl.cc

alpn: disabling an envoy_bug while 21345 is investigated

---

test/common/router/corpus_from_config_impl.sh
test/common/router/router_fuzz.proto

Testing: manual - logs dump though sans newlines

router: only dumping router fuzz logs to stdout if build fails

---

.azure-pipelines/pipelines.yml
bazel/wasm/wasm.bzl
ci/do_ci.sh
source/common/io/io_uring_impl.h
source/common/network/io_socket_handle_impl.cc
test/common/buffer/watermark_buffer_test.cc
test/common/signal/signals_test.cc
test/mocks/router/mocks.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: enable MSAN except extensions

---

tools/protodoc/protodoc.py

These were added to balance the fact that the previously search-engine-indexed v2 api was removed and the links were redirected to v3 equivalents - so it provided a way back
I think we can now remove as we have removed the redirects, and the update/removal has been well notified
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Remove v2 API links

---

source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.cc
source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.h

Commit Message: Change to unsigned, added wrap-around, more comments.
Testing: regression testing

local rate limit: follow up to #21327

---

contrib/kafka/filters/network/test/kafka_response_parser_test.cc

Commit Message: tests: make kafka parser test a bit more restrictive
Additional Description: as found during https://github.com/envoyproxy/envoy/pull/21055 , the test was passing but wasn't strict enough - proper checks for exception's message have been added
Testing: N/A

tests: make kafka parser test a bit more restrictive

---

.gitignore
tools/base/requirements.in
tools/base/requirements.txt
tools/docs/generate_version_histories.py

Fix #20211
Also updates `envoy.base.utils` to use async changelog data, hence hacks on version_history code
Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Updates (including new check for `RUNTIME_GUARDS`)

---

changelogs/current.yaml

Risk Level:
Testing:
Docs Changes:
Release Notes:

changelogs: Fix `RUNTIME_GUARDS` format

---

source/extensions/filters/network/thrift_proxy/conn_manager.cc

thrift: ensure an RPC isn't removed more than once

---

ci/do_ci.sh
ci/format_pre.sh
tools/base/requirements.in
tools/base/requirements.txt

Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Quieten checkers

---

docs/root/configuration/http/http_filters/_include/http-cache-configuration.yaml
docs/root/configuration/http/http_filters/cache_filter.rst
docs/root/configuration/http/http_filters/http_filters.rst
docs/root/start/sandboxes/cache.rst

Signed-off-by: Povilas Versockas <p.versockas@gmail.com>
Commit Message: add http cache documentation
Additional Description: Envoy seems to be missing HTTP Cache filter documentations
Testing:  local
Docs Changes: HTTP Cache
Release Notes:

docs: add http cache documentation

---

bazel/repository_locations.bzl

Fix #21122
Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Bump `rules_apple` -> 0.34.2

---

bazel/emsdk.patch
bazel/repositories.bzl

wasm: disable npm install

---

DEPENDENCY_POLICY.md

Risk Level:
Testing:
Docs Changes:
Release Notes:

readme: Add info about dependency issue tracker to DEPENDENCY_POLICY.md

---

docs/root/configuration/other_features/internal_listener.rst

Signed-off-by: Hu Shuai <hus.fnst@fujitsu.com>
Commit Message: Fix a small typo
Additional Description: acomplished --> accomplished
Docs Changes: docs/root/configuration/other_features/internal_listener.rst

Fix a small typo

---

ci/Dockerfile-envoy-distroless

Risk Level:
Testing:
Docs Changes:
Release Notes:

[backport/v1.20] docker: Update distroless image -> `d65ac1a`

---

tools/base/requirements.in
tools/base/requirements.txt
tools/extensions/BUILD
tools/extensions/extensions_schema.yaml

and update `extensions_schema.yaml`
Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Bump `envoy.code.check` -> 0.2.1

---

docs/root/api-docs/xds_protocol.rst

Signed-off-by: Mark D. Roth <roth@google.com>
Commit Message: xds spec: add section about PGV annotations
Additional Description: Describe use of PGV annotations in xDS.
Testing: N/A
CC @htuch

xds spec: add section about PGV annotations

---

ci/Dockerfile-envoy-distroless

Risk Level:
Testing:
Docs Changes:
Release Notes:

[backport/v1.19] docker: Update distroless image -> `d65ac1a`

---

api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
api/envoy/extensions/http/header_validators/envoy_default/v3/header_validator.proto

Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: updating rfc link

---

tools/protodoc/BUILD
tools/protodoc/generate_empty.py
tools/protodoc/protodoc.py
tools/protodoc/rst_filters.py
tools/protodoc/templates/empty.rst.tpl
tools/protodoc/templates/extension.rst.tpl
tools/protodoc/templates/extension_category.rst.tpl

Risk Level:
Testing:
Docs Changes:
Release Notes:

protodoc: Use prebuilt jinja env

---

docs/BUILD
docs/_ext/powershell_lexer.py
docs/build.sh
docs/conf.py
tools/base/requirements.in
tools/base/requirements.txt

- Quieten docs build
- Run sphinx multi core
Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Update `envoy.docs.sphinx_runner`

---

test/per_file_coverage.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

coverage: Adjust broken oauth coverage for CI

---

examples/local_ratelimit/README.md

Commit Message: fix local_ratelimit example readme doc
Testing: N/A

fix local_ratelimit example readme doc

---

tools/protodoc/BUILD
tools/protodoc/protodoc.py
tools/protodoc/templates/extension.rst.tpl

Risk Level:
Testing:
Docs Changes:
Release Notes:

protodoc: Integrate artefact data

---

examples/verify-common.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

examples: Improve debugging output

---

test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc

dns: adding double test with no cache

---

contrib/sip_proxy/filters/network/source/conn_manager.cc
contrib/sip_proxy/filters/network/source/conn_manager.h
contrib/sip_proxy/filters/network/source/router/router_impl.cc
contrib/sip_proxy/filters/network/test/conn_manager_test.cc
contrib/sip_proxy/filters/network/test/tra_test.cc

Commit Message: throw exception when stop loadbalance to return 503
Testing: Done

throw exception when stop loadbalance to return 503

---

OWNERS.md

Commit Message: Grant boteng and tyxia @google access to setec for reviewing oss-fuzz PRs
Additional Description: Google is leading oss-fuzz effort to address fuzzing backlogs and improve fuzz coverage with the help of X41 security analysts. As part of this engagement, Envoy team in Google would like to review the PRs raised in setec.

Grant boteng and tyxia access to setec for reviewing oss-fuzz PRs

---

CODEOWNERS

Commit Message: n/a
Testing: n/a

codeowners: calling attention to newly underowned extensions

---

api/envoy/extensions/http/header_validators/envoy_default/v3/header_validator.proto
api/envoy/extensions/load_balancing_policies/round_robin/v3/round_robin.proto

cc @phlax these showed up when I ran one of the check_format scripts - I wonder if we could make it fail

proto: fixing a few more warnings

---

tools/proto_format/proto_format.sh
tools/protoxform/BUILD
tools/protoxform/protoxform.bzl

Risk Level:
Testing:
Docs Changes:
Release Notes:

protoxform: Add aspect rule

---

api/bazel/BUILD
tools/proto_format/BUILD
tools/proto_format/proto_format.sh
tools/proto_format/proto_sync.py

This doesnt resolve the performance issues with proto_format/sync but is the first step, bringing these into bazel will allow performance to be addressed subsequently.
Risk Level:
Testing:
Docs Changes:
Release Notes:

proto_format: Shift `proto_sync` to bazel

---

CODEOWNERS

owners: updating thrift

---

source/extensions/filters/network/dubbo_proxy/router/router_impl.cc
test/extensions/filters/network/dubbo_proxy/router_test.cc

Commit Message:fix dubbo outlier detection due to not considering LocalConnectionFailure
Testing: N/A

fix dubbo outlier detection due to not considering LocalConnectionFailure

---

contrib/sip_proxy/filters/network/source/decoder.cc
contrib/sip_proxy/filters/network/source/metadata.h
contrib/sip_proxy/filters/network/source/router/router_impl.cc

1.  when response with p-cookie-ip-map, will do retrieveTRA, then do                                                                                                                                                                                                updateTRA, but retrieveTRA doesn't work here now because it depends on                                                                                                                                                                                          metadata's affinity info which only exist in request. …

contrib-sipproxy: fix sip reg affinity issue

---

.azure-pipelines/pipelines.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

[backport/1.20] release: Fix diskspace issue (1.20.6)

---

test/integration/overload_integration_test.cc

Commit Message: The stat can increment and the event loop stop before the client gets the
goAway. Add an additional wait step to ensure it arrives before the check.
Testing: test-only
Docs Changes:
Release Notes:
Fixes #14366

test: fix flake in overload_integration_test

---

bazel/dependency_imports.bzl
bazel/repository_locations.bzl

Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fix #20501

deps: Bump `bazel_gazelle` -> v0.25.0

---

test/extensions/filters/http/file_system_buffer/filter_test.cc

Commit Message: Remove accidental debug prints in test
Testing: n/a

remove debug prints

---

.azure-pipelines/pipelines.yml

- Fix cache key for `proto_format` job
- Add cache for `dependencies` job
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Cache fixes/cleanups

---

ci/run_envoy_docker.sh

While working on example verification (#21939 #21935 ) i have been looking to move the verification into bazel and into the build container
As this uses the docker engine on the host, it needs a shared path that can be sent to docker (avoiding mangling the paths before doing so)
Risk Level:
Testing:
Docs Changes:
Release Notes:

docker/build: Add shared temp directory

---

source/extensions/filters/network/dubbo_proxy/active_message.cc
source/extensions/filters/network/dubbo_proxy/decoder_event_handler.h

Signed-off-by: zhaohuabing <zhaohuabing@gmail.com>
Commit Message: remove unused "retry" status
Testing: yes

remove unused "retry" status

---

support/README.md

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: update support README

---

.bazelignore

Risk Level:
Testing:
Docs Changes:
Release Notes:

bazel: Ignore emacs temp files

---

tools/config_validation/BUILD
tools/config_validation/validate_fragment.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

config_validation: Remove runfiles and cleanup args

---

tools/protoxform/protoxform.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

protoxform: Dont copy the file proto in visitor

---

docs/BUILD
tools/docs/generate_version_histories.py
tools/proto_format/BUILD
tools/proto_format/format_api.py
tools/protoprint/BUILD
tools/protoxform/BUILD

Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Compress remaining tarballs in pipelines

---

docs/BUILD

Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Improve file collection/handling in build

---

BACKPORTS.md
RELEASES.md

docs: putting backports docs in the repo

---

tools/api_proto_plugin/BUILD
tools/api_proto_plugin/constants.py
tools/protodoc/protodoc.py
tools/protoprint/protoprint.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

api_proto_plugin: Add `constants.py`

---

tools/base/requirements.in
tools/base/requirements.txt

Partial fix for #22023
Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Bump `envoy.dependency.check` -> 0.1.3

---

source/common/upstream/cluster_manager_impl.cc
test/integration/fake_upstream.cc
test/integration/fake_upstream.h
test/integration/uds_integration_test.cc
test/integration/uds_integration_test.h

Testing: new UDS TLS test
Release Notes:
Fixes https://github.com/envoyproxy/envoy/pull/21356 (because we can never take out the optional check)

uds: fixing a regression with tls uds upstreams

---

ci/format_pre.sh
tools/proto_format/proto_format.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Shift buf job out of format_pre

---

ci/format_pre.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

format_pre: Only run test for format check in CI

---

source/extensions/filters/network/http_connection_manager/config.cc

Fixing a cosmetic clangTidy issue
Risk Level:
Testing:
Docs Changes:
Release Notes:

Fixing a cosmetic clangTidy issue

---

.github/workflows/check-deps.yml
ci/do_ci.sh
tools/base/requirements.in
tools/base/requirements.txt
tools/dependency/BUILD

Fix #22100
Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: Preload CVE data for `dependency.check`

---

docs/root/configuration/http/http_filters/composite_filter.rst

docs: Fix the sample description for the composite filter

---

docs/root/_static/css/envoy.css
docs/root/configuration/http/http_conn_man/local_reply.rst
docs/root/configuration/http/http_filters/aws_lambda_filter.rst
docs/root/configuration/http/http_filters/language_filter.rst
tools/protodoc/protodoc.py

and some small cleanups for naked code blocks
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Force json markup for pseudo json code

---

tools/docs/generate_version_histories.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

changelogs: Fix sorting

---

docs/root/configuration/listeners/udp_filters/udp_proxy.rst
docs/root/start/quick-start/configuration-dynamic-control-plane.rst
docs/root/start/quick-start/configuration-dynamic-filesystem.rst
docs/root/start/quick-start/configuration-static.rst
docs/root/start/quick-start/run-envoy.rst
docs/root/start/quick-start/securing.rst
docs/root/start/sandboxes/dynamic-configuration-control-plane.rst

Fix #22167
also adds some downloads/captions
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Fix wonky line selection/highlights

---

docs/root/_static/css/envoy.css
docs/root/_static/searchtools.js
docs/root/api-v3/config/contrib/cryptomb/cryptomb.rst
docs/root/api-v3/config/contrib/hyperscan/hyperscan.rst
docs/root/api-v3/config/contrib/sip/sip.rst
docs/root/api-v3/config/rbac/matchers.rst
docs/root/api-v3/config/rbac/matchers/matchers.rst
tools/docs/generate_extensions_security_rst.py
tools/docs/generate_external_deps_rst.py
tools/protodoc/protodoc.py

Fix #22151 
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Cleanup titles and search

---

bazel/v8.patch

wasm: fix V8 build on older versions of Linux.

---

ci/flaky_test/BUILD

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Remove unused flakey test dep that is breaking on win

---

test/config/utility.cc
test/config/utility.h
test/integration/base_integration_test.cc
test/integration/listener_lds_integration_test.cc
test/integration/quic_http_integration_test.cc

Commit Message: multiple addresses: add integration tests
Part of https://github.com/envoyproxy/envoy/issues/11184

multiple addresses: add integration tests

---

tools/code_format/check_format.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

check_format: Fix regexes

---

bazel/repository_locations.bzl

Fix #21866
Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Bump `build_bazel_rules_apple` -> 1.0.1

---

ci/README.md

Signed-off-by: Ikko Ashimine <eltociear@gmail.com>
Commit Message: defualt -> default
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: fix typo in README.md

---

OWNERS.md

Risk Level: negative
Testing: trial by fire
Docs Changes: many, over time thank you phlax

owners: bumping phlax and RyanTheOptimist to senior maintainers

---

source/common/http/BUILD
source/common/http/dependency_manager.cc
source/common/http/dependency_manager.h
source/common/http/filter_chain_helper.cc
source/common/http/filter_chain_helper.h
source/extensions/filters/network/http_connection_manager/BUILD
source/extensions/filters/network/http_connection_manager/config.cc
source/extensions/filters/network/http_connection_manager/config.h
test/common/http/BUILD
test/common/http/dependency_manager_test.cc
test/extensions/filters/network/http_connection_manager/BUILD
test/extensions/filters/network/http_connection_manager/config_test.cc

Risk Level: low (code refactor)
Testing: n/a
part of https://github.com/envoyproxy/envoy/issues/10455

hcm: factoring out filter chain creation code

---

source/common/router/upstream_request.cc

Signed-off-by: zhao nan <zhaonan06@corp.netease.com>
Commit Message: remove duplicate code 
Additional Description:  we have used this code in initialization
Testing: N/A

remove duplicate code

---

ci/build_setup.sh

Commit Message: build: simple build setup script updates
Address suggestion from @phlax  in the #22355
Testing: n/a.

build: simple build setup script format updates

---

test/extensions/transport_sockets/http_11_proxy/connect_integration_test.cc
test/integration/fake_upstream.cc

Fixes https://github.com/envoyproxy/envoy/issues/22324

test: fixing a flake

---

changelogs/1.23.0.yaml
changelogs/current.yaml

Commit Message: move misplaced logs to current.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:

changelog: fix misplaced log

---

distribution/debian/packages.bzl
distribution/distros.yaml

ci: remove ubuntu impish build

---

.azure-pipelines/cleanup.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Free more diskspace for failing CI

---

contrib/sip_proxy/filters/network/source/conn_manager.cc
contrib/sip_proxy/filters/network/source/conn_manager.h
contrib/sip_proxy/filters/network/source/metadata.cc
contrib/sip_proxy/filters/network/source/sip.h
contrib/sip_proxy/filters/network/source/tra/tra_impl.cc
contrib/sip_proxy/filters/network/source/tra/tra_impl.h
contrib/sip_proxy/filters/network/test/decoder_test.cc

1. Fix issue 22306
2. Fix issue of mismatched tra context
Testing: UT
Docs Changes:
Release Notes:
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/22306

contrib-sip-proxy: Fix Issues of request_active_ counter and mismatched tra context

---

source/common/quic/client_connection_factory_impl.cc
test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc

test: changing an 8s timeout to 2s

---

docs/root/api-docs/xds_protocol.rst

Risk Level:
Testing:
Docs Changes:
Release Notes:

[backport/v1.23] url glitch in PGV annotation

---

source/common/protobuf/utility.cc

Fix code for C++20 compliance

---

docs/root/start/sandboxes/lua.rst
examples/lua/envoy.yaml
examples/lua/verify.sh

Commit Message: lua: update example to verify the multiple lua filter can be configured simultaneously
Simple example updates.
Testing: n/a.

lua: update example to verify the multiple lua filter can be configured simultaneously

---

.azure-pipelines/bazel.yml
.azure-pipelines/pipelines.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Timeout test result publishing if agent is hung

---

CONTRIBUTING.md

Fix typo stratch to scratch in CONTRIBUTING.md
Signed-off-by: Ruslan Mstoi <ruslan.mstoi@intel.com>
Commit Message: Fix typo stratch to scratch in CONTRIBUTING.md
Risk Level:
Testing:
Docs Changes:
Release Notes:

doc: CONTRIBUTING.md: typo fix

---

test/common/http/http1/codec_impl_test.cc

Tighten up test expectations for
Http1ServerConnectionImplTest.LargeRequestHeadersRejected and
Http1ServerConnectionImplTest.LargeRequestHeadersRejectedBeyondMaxConfig.
Re-enable
Http1ServerConnectionImplTest.Http11InvalidRequest,
Http1ServerConnectionImplTest.RequestWithTrailersKept, and
Http1ServerConnectionImplTest.ManyTrailersRejected for BalsaParser.
These could have been re-enabled earlier, but I missed them as #22039
was originally prepared before some other PRs that actually made the
tests pass got merged.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional …

[balsa] Tighten up some tests; re-enable some tests.

---

bazel/repository_locations.bzl

Fix #22497
Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Bump `com_github_nlohmann_json` -> 3.11.1

---

bazel/repository_locations.bzl
tools/base/requirements.in
tools/base/requirements.txt

Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Fix dependency checker (return code) + date fixes

---

docs/root/configuration/http/http_filters/sxg_filter.rst
docs/root/configuration/other_features/vcl.rst

Add note section about "not support".
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes commit #PR or SHA] #22443

docs: add note for sgx&vcl

---

api/envoy/config/cluster/v3/cluster.proto
docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst

Clarify Maglev docs that it aims for minimal disruption and point to table_size to control the behaviour.
Commit Message: clarify maglev docs
Testing: N/A

clarify maglev docs

---

source/extensions/filters/http/common/factory_base.h
test/extensions/filters/http/common/empty_http_filter_config.h
test/integration/filters/add_body_filter.cc
test/integration/filters/add_invalid_data_filter.cc
test/integration/filters/add_trailers_filter.cc
test/integration/filters/buffer_continue_filter.cc
test/integration/filters/call_decodedata_once_filter.cc
test/integration/filters/common.h
test/integration/filters/continue_headers_only_inject_body_filter.cc
test/integration/filters/crash_filter.cc
test/integration/filters/decode_headers_return_stop_all_filter.cc
test/integration/filters/encode_headers_return_stop_all_filter.cc
test/integration/filters/encoder_decoder_buffer_filter.cc
test/integration/filters/invalid_header_filter.cc
test/integration/filters/local_reply_during_encoding_data_filter.cc
test/integration/filters/local_reply_during_encoding_filter.cc
test/integration/filters/local_reply_with_metadata_filter.cc
test/integration/filters/on_local_reply_filter.cc
test/integration/filters/passthrough_filter.cc
test/integration/filters/remove_response_headers.cc
test/integration/filters/stop_iteration_headers_inject_body_filter.cc
test/integration/filters/wait_for_whole_request_and_response.cc

Testing: n/a
part of https://github.com/envoyproxy/envoy/issues/10455

test: allowing many test filters to be upstream filters

---

examples/wasm-cc/docker-compose.yaml

Signed-off-by: jespersoderlund <jesper.soderlund@gmail.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes #22589

sandbox: fixing wasm example making port config explict to match envoy config

---

CODEOWNERS

Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: updating ownership

---

source/common/stats/allocator_impl.h
source/extensions/filters/udp/dns_filter/dns_parser.h
test/integration/fake_resource_monitor.cc
test/integration/fake_resource_monitor.h
test/mocks/stream_info/mocks.h

Fix msan errors

---

source/extensions/common/wasm/context.cc
test/extensions/filters/http/wasm/wasm_filter_test.cc

Commit Message: fix wasm callouts with xff
Testing: ut

wasm: fix wasm callouts with xff

---

ci/do_ci.sh

Mitigate #22646
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Dont check release issues in PR CIs

---

envoy/http/filter.h
envoy/router/router.h
source/common/http/async_client_impl.h
source/common/http/filter_manager.cc
source/common/http/filter_manager.h
source/common/router/router.cc
source/common/router/router.h
source/common/router/upstream_request.cc
source/common/router/upstream_request.h
source/extensions/common/wasm/context.cc
source/extensions/filters/http/lua/lua_filter.h
source/extensions/upstreams/http/tcp/upstream_request.cc
test/common/router/router_test_base.cc
test/extensions/filters/common/ext_authz/check_request_utils_test.cc
test/extensions/filters/http/common/fuzz/uber_per_filter.cc
test/extensions/filters/http/ext_authz/config_test.cc
test/extensions/filters/http/ext_authz/ext_authz_fuzz_test.cc
test/extensions/filters/http/ext_authz/ext_authz_test.cc
test/extensions/filters/http/lua/lua_filter_test.cc
test/extensions/filters/http/rbac/rbac_filter_test.cc
test/extensions/filters/http/wasm/wasm_filter_test.cc
test/extensions/stats_sinks/hystrix/hystrix_test.cc
test/integration/filters/pause_filter.cc
test/integration/filters/pause_filter_for_quic.cc
test/integration/filters/random_pause_filter.cc
test/mocks/http/mocks.h
test/mocks/router/mocks.h
test/mocks/router/router_filter_interface.cc

part of https://github.com/envoyproxy/envoy/issues/10455

http: changing some Connection* interfaces to be OptRef

---

bazel/repository_locations.bzl

Fix #22692
Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Bump `com_github_nlohmann_json` -> 3.11.2

---

changelogs/current.yaml
source/server/connection_handler_impl.cc
test/server/connection_handler_test.cc

Commit Message: connection handler: correct the handling of listener update
This is cherry-pick from https://github.com/envoyproxy/envoy/pull/22622
Testing: unittest added
Release Notes: an item for bug fixes added.
Fixes https://github.com/envoyproxy/envoy/issues/22449

[backport][release/v1.23] connection handler: correct the handling of listener update 

---

.github/workflows/check-deps.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Fix python version

---

.azure-pipelines/pipelines.yml
ci/do_ci.sh
tools/base/requirements.in
tools/base/requirements.txt
tools/project/BUILD

Risk Level:
Testing:
Docs Changes:
Release Notes:

[backport/v1.23] repo: Add automated tagging/publishing (#22578)

---

source/common/router/upstream_request.cc
source/common/router/upstream_request.h
test/common/router/upstream_request_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

http: fix bad merge

---

test/extensions/transport_sockets/tls/test_data/certs.sh

Commit Message: minor update: remove unnecessary intermediate files for refresh certs
Simple minor update to the tool script to clear some unnecessary intermediate files.
Check this discussion for context https://github.com/envoyproxy/envoy/pull/22792#discussion_r951388769
Testing: n/a.

minor update: remove unnecessary intermediate files for refresh certs

---

source/common/upstream/edf_scheduler.h

Checking and then using std::weak_ptr::expired() is inherently thread-unsafe:
https://en.cppreference.com/w/cpp/memory/weak_ptr/expired
Signed-off-by: Eugene Chan <eugenechan@google.com>
Commit Message: upstream: Use std::weak_ptr::lock() to construct shared pointers in EdfScheduler
Risk Level: low (should be no-op)
Testing: existing CI

upstream: Use std::weak_ptr::lock() to construct shared pointers in EdfScheduler

---

test/common/config/config_provider_impl_test.cc

Use dedicated methods to clear proto values

---

test/common/matcher/matcher_test.cc
test/common/matcher/test_utility.h

The existing test is using `NeverMatch` matcher which always return false for match() method. So, we didn't really test the matching behavior for custom_match field/mechanism. In this PR:
- Implement a new custom_matcher and factory to do simple string comparison matching.
- Test custom_match with this newly added custom matcher/factory for the expected matching result that `result.on_match_.has_value()` is true

custom_matcher: Test the custom_match effectively

---

STYLE.md

Documentation changes as per [https://github.com/envoyproxy/envoy/pull/22829](https://github.com/envoyproxy/envoy/pull/22829)

Updated documentation for previous ENVOY_BUG changes

---

source/common/protobuf/visitor.cc
test/benchmark/main.cc
test/extensions/common/async_files/async_file_manager_thread_pool_test.cc
test/extensions/transport_sockets/internal_upstream/internal_upstream_test.cc

Small code cleanups from linters

---

bazel/README.md
tools/BUILD

This is handy if you want to hermetically run a test with stack decoding.
Risk Level:
Testing:
Docs Changes:
Release Notes:

tools: add a stack_decode target

---

source/extensions/clusters/redis/redis_cluster.cc

Commit Message: enhance redis cluster logs
Additional Description: enhance redis cluster logs to include additional debug information
Testing: N/A

redis: enhance redis cluster debug logs

---

api/STYLE.md

docs: Add a note about the wip extension status

---

source/extensions/clusters/redis/redis_cluster.cc
source/extensions/clusters/redis/redis_cluster.h

Commit Message: add more logs and enable stats for cluster slot command
Testing: N/A

redis: add more logs and enable stats for cluster slot command
