source/common/common/utility.cc
No need to run costly find when we can do linear comparison.
=> use strncmp instead of find.

source/common/http/codec_client.h, source/common/http/conn_manager_impl.h
=> Fix definitions of ActiveRequest & ActiveStream.

source/common/common/utility.h, source/common/runtime/runtime_impl.h
Make seed for random to be current time in nano ^ current thread id.
=> Better seeding of RNG.

source/exe/hot_restart.h
Signed-off-by: David Mackey <tdmackey@booleanhaiku.com>
=> hot restart: fix assert side effect

docs/configuration/cluster_manager/cluster_manager.rst, docs/configuration/cluster_manager/cluster_runtime.rst, docs/configuration/cluster_manager/cluster_stats.rst, docs/intro/arch_overview/load_balancing.rst
=> Follow up on zone routing docs.

source/common/http/http1/codec_impl.cc, test/common/http/http1/codec_impl_test.cc
=> http/1: fix codec crash from too small buffer reservation

source/common/tracing/http_tracer_impl.cc
Regression from header map rewrite.
=> tracing: fix sending wrong x-request-id tag

include/envoy/upstream/host_description.h, include/envoy/upstream/outlier_detection.h, include/envoy/upstream/upstream.h, source/common/upstream/cluster_manager_impl.cc, source/common/upstream/logical_dns_cluster.h, source/common/upstream/outlier_detection_impl.cc, source/common/upstream/outlier_detection_impl.h, source/common/upstream/upstream_impl.cc, source/common/upstream/upstream_impl.h, test/common/upstream/outlier_detection_impl_test.cc, test/common/upstream/upstream_impl_test.cc, test/mocks/upstream/host.h, test/mocks/upstream/mocks.cc
=> namespace outlier detection code

docs/configuration/http_conn_man/route_config/route.rst, docs/configuration/http_conn_man/route_config/route_config.rst, docs/configuration/http_conn_man/route_config/route_matching.rst, docs/configuration/http_conn_man/route_config/traffic_shifting.rst, docs/configuration/http_conn_man/route_config/vhost.rst, docs/intro/arch_overview/http_routing.rst
@lyft/network-team 
fixes https://github.com/lyft/envoy/issues/194
=> Traffic shifting docs

docs/configuration/cluster_manager/cluster_stats.rst, include/envoy/upstream/upstream.h, source/common/upstream/upstream_impl.cc, test/common/upstream/sds_test.cc, test/common/upstream/upstream_impl_test.cc
Adds a healthy gauge which is inclusive of both health checking and
outlier detection.
=> add cluster overall healthy stat

source/common/router/router.cc, test/common/http/async_client_impl_test.cc, test/common/router/router_test.cc
regression from https://github.com/lyft/envoy/pull/279
=> router: fix pool failure crash

source/common/ssl/context_impl.cc
Both Envoy and libevent must be linked against BoringSSL. Additionally,
libevent must include a fix (commit 6702da1 from 2016-10-15), otherwise
it's going to crash.
=> Make it work with BoringSSL.

.idea/vcs.xml, test/common/upstream/sds_test.cc, test/common/upstream/test_data/sds_response.json
Cover two important cases with max_host_weight.
=> Make 100% test coverage for upstream_impl.cc

test/common/upstream/load_balancer_impl_test.cc
Fixed ZoneAwareRoutingNotHealthy as that was not properly working.
Covered local cluster missing test.
=> Tech debt: make 100% coverage on load_balancer_impl.cc

source/common/common/base64.cc, test/CMakeLists.txt, test/common/common/base64_test.cc
=> Implement base64 encode

include/envoy/json/json_object.h, source/common/json/json_loader.cc, test/common/json/json_loader_test.cc
=> json: add hash function

source/common/upstream/outlier_detection_impl.cc, test/common/upstream/outlier_detection_impl_test.cc
This is a little complicated, see the comment in the commit. Needed for
dynamic cluster removal.
=> outlier: handle cross thread destroy

test/common/filter/auth/client_ssl_test.cc, test/common/grpc/rpc_channel_impl_test.cc, test/common/router/router_test.cc, test/common/router/shadow_writer_impl_test.cc, test/common/tracing/http_tracer_impl_test.cc, test/common/upstream/sds_test.cc, test/mocks/buffer/mocks.h, test/mocks/upstream/mocks.h, test/server/http/admin_test.cc, test/server/http/health_check_test.cc
Faster re-building tests when changing async_client_impl.h :)
=> Remove async_client_impl from upstream/mocks.h

ci/build_container/build_container.sh, docs/install/requirements.rst, thirdparty.cmake
cc: @lyft/network-team @PiotrSikora
=> Replace openssl with boringssl as the official ssl provider

source/common/stats/stats_scope_impl.h
Regresion from #334. I'm in the process of rewriting all of the scope stuff
currently so I'm not going to bother with tests. I will add tests in the real
change.
=> stats: fix scope timer prefix

docs/configuration/http_conn_man/access_log.rst, include/envoy/http/access_log.h, source/common/http/access_log/access_log_formatter.cc, source/common/http/access_log/access_log_formatter.h, source/common/http/filter/ratelimit.cc, test/common/http/access_log/access_log_formatter_test.cc, test/common/http/filter/ratelimit_test.cc
Added new access log response flag and log the response flag from the rate limit filter.
=> Log rate limited requests with new response flag.

docs/configuration/network_filters/client_ssl_auth_filter.rst, include/envoy/http/message.h, source/common/CMakeLists.txt, source/common/filter/auth/client_ssl.cc, source/common/filter/auth/client_ssl.h, source/common/http/message_impl.cc, source/common/http/message_impl.h, source/common/http/rest_api_fetcher.cc, source/common/http/rest_api_fetcher.h, source/common/upstream/sds.cc, source/common/upstream/sds.h, source/server/config/network/client_ssl_auth.cc, test/common/filter/auth/client_ssl_test.cc
We now do periodic fetching of a REST API in multiple places so this
commit adds a base class to help with the common logic.
=> implement REST API fetcher base class

source/common/ssl/openssl.cc, source/common/ssl/openssl.h
boringssl has internal support for threading.
=> ssl: remove openssl threading code if using boringssl

configs/envoy_double_proxy.template.json, configs/envoy_front_proxy.template.json, configs/envoy_service_to_service.template.json
@lyft/network-team 
cc: @moderation
=> Fix lightstep collector link in Envoy example configs

docs/configuration/listeners/listeners.rst, source/common/json/config_schemas.cc, test/server/configuration_impl_test.cc
=> JSON Schema: Allow empty filters in listeners

docs/configuration/http_conn_man/route_config/route.rst, source/common/json/config_schemas.cc, source/common/json/config_schemas.h, source/common/router/config_impl.cc, source/common/router/router_ratelimit.cc, source/server/config/network/http_connection_manager.cc, source/server/config/network/http_connection_manager.h, test/common/router/config_impl_test.cc, test/mocks/server/mocks.cc, test/server/config/network/config_test.cc
Provides schema validation for HTTP Connection Manager Filter.
Next PR will extend coverage for access log and HTTP Filters.
=> JSON Schema: HTTP Connection Manager Filter

docs/configuration/http_conn_man/route_config/route.rst, docs/configuration/http_filters/router_filter.rst, include/envoy/http/filter.h, include/envoy/router/router.h, source/common/grpc/http1_bridge_filter.cc, source/common/http/async_client_impl.cc, source/common/http/async_client_impl.h, source/common/http/conn_manager_impl.cc, source/common/http/conn_manager_impl.h, source/common/http/filter/fault_filter.cc, source/common/http/filter/ratelimit.cc, source/common/http/filter/ratelimit.h, source/common/json/config_schemas.cc, source/common/router/config_impl.cc, source/common/router/config_impl.h, source/common/router/router.cc, source/common/router/router.h, test/common/grpc/http1_bridge_filter_test.cc, test/common/http/conn_manager_impl_test.cc, test/common/http/filter/fault_filter_test.cc, test/common/http/filter/ratelimit_test.cc, test/common/router/config_impl_test.cc, test/common/router/router_test.cc, test/mocks/http/mocks.cc, test/mocks/http/mocks.h, test/mocks/router/mocks.cc, test/mocks/router/mocks.h, test/mocks/upstream/mocks.cc
fixes https://github.com/lyft/envoy/issues/308
=> router: add ability to select cluster via request header

docs/configuration/configuration.rst, docs/configuration/overview/overview.rst, source/common/json/config_schemas.cc, source/common/json/config_schemas.h, source/common/upstream/cds_api_impl.cc, source/common/upstream/sds.cc, test/common/upstream/cds_api_impl_test.cc, test/common/upstream/sds_test.cc
-Updates documentation to refer to schema validation
-Adds schema support for SDS and CDS.
=> JSON Schema: Provide support for discovery service

source/common/http/http2/codec_impl.cc, source/common/http/http2/codec_impl.h, test/common/http/http2/codec_impl_test.cc
fixes https://github.com/lyft/envoy/issues/410
See the issue and the PR code comments for more information.
=> http/2: better deferred reset handling

docs/configuration/http_conn_man/route_config/route.rst, docs/intro/arch_overview/arch_overview.rst, docs/intro/arch_overview/dynamic_configuration.rst, docs/intro/arch_overview/grpc.rst, docs/intro/arch_overview/http_connection_management.rst, docs/intro/arch_overview/http_routing.rst, docs/intro/arch_overview/ssl.rst, docs/intro/version_history.rst, docs/intro/what_is_envoy.rst
fixes https://github.com/lyft/envoy/issues/468
=> docs: dynamic config overview

ci/README.md, ci/docker_push.sh
@lyft/network-team tag before push.
=> ci: tag envoy latest with travis commit

docs/intro/arch_overview/outlier.rst, include/envoy/upstream/outlier_detection.h, source/common/upstream/outlier_detection_impl.cc, source/common/upstream/outlier_detection_impl.h, test/common/upstream/outlier_detection_impl_test.cc, test/mocks/upstream/host.h
=> outlier: add secs since last action field to log

docs/README.md
@lyft/network-team docs update explaining the automatic doc push process and security.
=> docs: update readme

.travis.yml
=> ci: push builds only on master

source/common/common/thread.cc, source/common/common/thread.h, source/common/runtime/runtime_impl.h, test/common/common/utility_test.cc, test/common/http/utility_test.cc, test/common/runtime/runtime_impl_test.cc, test/common/upstream/cluster_manager_impl_test.cc, test/common/upstream/logical_dns_cluster_test.cc, test/common/upstream/upstream_impl_test.cc, test/integration/fake_upstream.h, test/integration/server.h, test/mocks/upstream/cluster_info.h, test/mocks/upstream/mocks.cc, test/server/config/network/config_test.cc, test/test_common/utility.cc, test/test_common/utility.h
Also, add some random coverage for a few things that I missed in
the past.
=> perf: do not generate random number in runtime if not needed

include/envoy/event/dispatcher.h, include/envoy/event/file_event.h, source/common/event/dispatcher_impl.cc, source/common/event/dispatcher_impl.h, source/common/event/file_event_impl.cc, source/common/event/file_event_impl.h, source/common/filesystem/watcher_impl.cc, source/common/network/connection_impl.cc, source/common/network/dns_impl.cc, source/common/network/proxy_protocol.cc, source/exe/hot_restart.cc, test/common/event/file_event_impl_test.cc, test/mocks/event/mocks.h
note: existing tests cover this case well.
fixes https://github.com/lyft/envoy/issues/391
=> network connection: apply real back pressure during read disable

source/common/upstream/cds_api_impl.cc
fixes https://github.com/lyft/envoy/issues/549
=> cds: make log output more clear

ci/build_container/Dockerfile, ci/build_container/build_container.sh
This is in support of Bazelifying the build (#415).
=> Upgrade Docker image to Ubuntu 16.04 LTS, add bazel and deps.

ci/do_ci.sh
This bit rot crept in during in b8b1563.
=> Fix ordering of NUM_CPUS echo.

ci/Dockerfile-envoy-image
regression from https://github.com/lyft/envoy/commit/504913a753ff8b66d9f5b846157ea4ddc8636eb8
=> build: fix docker image push

ci/ci_steps.sh, source/common/tracing/http_tracer_impl.cc, source/common/tracing/http_tracer_impl.h, test/common/tracing/http_tracer_impl_test.cc
=> Update code to reflect changes in LightStep 0.36 library

docs/configuration/overview/runtime.rst, docs/operations/runtime.rst
fixes https://github.com/lyft/envoy/issues/612
=> docs: more runtime details

source/common/tracing/http_tracer_impl.cc, test/common/tracing/http_tracer_impl_test.cc, test/mocks/http/mocks.cc, test/mocks/http/mocks.h, test/mocks/tracing/mocks.cc, test/mocks/tracing/mocks.h
=> Tracing: Make span name to be egress host_header, e.g., egress api

bazel/envoy_build_system.bzl, source/common/json/json_loader.cc, source/common/router/config_impl.cc, source/server/server.cc, test/common/http/access_log/access_log_impl_test.cc, test/mocks/event/mocks.cc
These are sufficient to build Envoy with clang (r299268).
=> build: clang build fixes.

CMakeLists.txt, tools/check_format.py
Automagically enforce the BUILD style guide.
=> tools: add buildifier to check_format/fix_format flows (#415).

ci/do_ci.sh
This now works reliably after #647.
=> ci: enable testing in bazel.debug.

test/common/upstream/outlier_detection_impl_test.cc
=> outlier: fix missing expectation

docs/configuration/cluster_manager/cluster.rst, docs/configuration/cluster_manager/cluster_runtime.rst, source/common/upstream/outlier_detection_impl.cc, source/common/upstream/outlier_detection_impl.h, test/common/upstream/outlier_detection_impl_test.cc
=> outlier: stdev factor runtime controllable

ci/build_amazon_linux/build_amazon_linux.sh, ci/build_container/build_recipes/boringssl.sh, docs/install/requirements.rst, thirdparty.cmake
Do we want to track Chrome build (2987) or milestone (m57) in the commit message?
=> ssl: update BoringSSL to be873e9f (2987).

docs/configuration/http_conn_man/route_config/vhost.rst, source/common/router/config_impl.cc, source/common/router/config_impl.h, test/common/router/config_impl_test.cc
@htuch @dnoe 
Ok, take two where hopefully I'll not hose my git repo this time. Addressed comments from PR 735.
Fixes https://github.com/lyft/envoy/issues/519
=> Support wildcard domains other than '*'

source/common/http/access_log/access_log_formatter.cc, source/common/http/access_log/access_log_impl.cc, source/common/mongo/bson_impl.cc, source/common/router/config_impl.cc, source/server/config/network/http_connection_manager.cc, test/mocks/redis/mocks.cc
Fixes https://github.com/lyft/envoy/issues/590
=> swap NOT_IMPLEMENTED for NOT_REACHED where appropriate

docs/intro/arch_overview/cluster_manager.rst
=> Minor grammar correction

docs/configuration/cluster_manager/cluster_ssl.rst, docs/configuration/listeners/ssl.rst, include/envoy/ssl/context_config.h, source/common/json/config_schemas.cc, source/common/ssl/context_config_impl.cc, source/common/ssl/context_config_impl.h, source/common/ssl/context_impl.cc
While there, change default from "P-256" to "X25519:P-256".
=> ssl: add ability to configure ECDH curves.

CONTRIBUTING.md, OWNERS.md, STYLE.md
Fixes https://github.com/lyft/envoy/issues/625
=> docs: refresh contributing guide

docs/configuration/network_filters/mongo_proxy_filter.rst, source/common/mongo/proxy.cc, source/common/mongo/proxy.h, source/common/mongo/utility.cc, source/common/mongo/utility.h, test/common/mongo/proxy_test.cc, test/common/mongo/utility_test.cc
=> mongo: count queries without maxTimeMS

ci/ci_steps.sh
To e685bf07124b1aba3e6ce8efcce6a87dd7bff24f
=> ci: update image

test/common/http/async_client_impl_test.cc
Fixes https://github.com/lyft/envoy/issues/845
=> test: fix http async client test flake

docs/conf.py, docs/requirements.txt
This still unfortunately does not fix
https://github.com/rtfd/sphinx_rtd_theme/issues/397
Also switch copyright to 2016-2017.
=> docs: upgrade sphinx and theme

docs/extending/extending.rst
=> docs: add reference to envoy-filter-example.

ci/ci_steps.sh
To 22c55f8ec756c5ddeb26c3424e128a91aec23116
=> ci: update build image

ci/build_setup.sh, source/common/network/address_impl.cc, source/common/network/utility.cc, test/common/network/address_impl_test.cc, test/common/network/utility_test.cc, test/config/integration/server.json, test/integration/BUILD, test/integration/hotrestart_test.sh, test/integration/http2_integration_test.h, test/integration/http2_upstream_integration_test.h, test/integration/integration.cc, test/integration/integration.h, test/integration/integration_admin_test.cc, test/integration/integration_test.cc, test/integration/integration_test.h, test/integration/proxy_proto_integration_test.h, test/integration/server.cc, test/integration/ssl_integration_test.cc, test/integration/ssl_integration_test.h, test/integration/uds_integration_test.h, test/integration/utility.cc, test/integration/utility.h, test/test_common/BUILD, test/test_common/environment.cc, test/test_common/environment.h, test/test_common/network_utility.cc, test/test_common/network_utility.h
=> Revert "test: add IPv6 testing to IntegrationTest.Echo"

configs/configgen.py, configs/envoy_front_proxy.template.json, configs/envoy_router.template.json, configs/envoy_service_to_service.template.json, configs/routing_helper.template.json, docs/install/ref_configs.rst
Fixes #394 
Add sample for 
* RDS
* CDS
* Outlier Detection
* Remote Address rate limiting in Envoy Front Proxy template
=> Update envoy config samples

source/common/grpc/common.cc, source/common/mongo/bson_impl.cc, test/common/network/dns_impl_test.cc, tools/bazel.rc
=> bazel: enable -fsanitize=alignment in ASan builds.

test/integration/integration.cc, test/integration/integration.h
needed for transcoding integration test.
=> Allow integration client to send arbitrary data

ci/README.md, ci/run_envoy_docker.sh, docs/install/sandboxes.rst
Mac users require running the docker command with root permission.
=> Fix scripts for docker build on mac

configs/configgen.py, configs/envoy_service_to_service.template.json
Fixing s2s template to use actions that replaced "service_to_service".
=> Update S2S template to use correct action

source/common/grpc/codec.cc, test/common/grpc/codec_test.cc
=> grpc: fix decoder to decode empty frame

source/common/grpc/grpc_web_filter.cc, test/common/grpc/grpc_web_filter_test.cc
Encodes response trailers for gRPC-Web when text based response being asked.
=> Encodes response trailers for gRPC-Web when text based response being asked.

CONTRIBUTING.md, DEPRECATED.md
@htuch some updates on deprecation policy and currently deprecated features.
=> Update deprecation policy related docs (deprecated/contributing).

test/common/network/connection_impl_test.cc
Parameterize IPv4/IPv6 testing for connection_impl_test
=> test: add connection impl IPv6 tests

CONTRIBUTING.md
fixes https://github.com/lyft/envoy/issues/1012
=> docs: update contribution guide for deprecation policy

docs/configuration/http_conn_man/route_config/route.rst
=> docs: fix case_sensitive type

ci/build_setup.sh, source/common/dynamo/dynamo_filter.cc, source/common/dynamo/dynamo_filter.h, source/common/filter/auth/client_ssl.cc, source/common/filter/auth/client_ssl.h, source/common/filter/ratelimit.cc, source/common/filter/ratelimit.h, source/common/filter/tcp_proxy.cc, source/common/filter/tcp_proxy.h, source/common/http/codes.cc, source/common/http/codes.h, source/common/http/conn_manager_impl.cc, source/common/http/conn_manager_impl.h, source/common/http/filter/buffer_filter.cc, source/common/http/filter/buffer_filter.h, source/common/http/filter/fault_filter.cc, source/common/http/filter/fault_filter.h, source/common/http/filter/ratelimit.cc, source/common/http/filter/ratelimit.h, source/common/http/http2/codec_impl.cc, source/common/http/http2/codec_impl.h, source/common/http/user_agent.cc, source/common/http/user_agent.h, source/common/mongo/proxy.cc, source/common/mongo/proxy.h, source/common/router/router.cc, source/common/router/router.h
Cleanups from https://github.com/lyft/envoy/pull/1083. Rename
some variables and repoint to filter example master. No logic
changes.
=> cleanup: variable renames

source/common/upstream/BUILD, source/common/upstream/upstream_impl.cc, test/common/http/conn_manager_impl_test.cc, test/common/network/address_impl_test.cc, test/common/router/config_impl_test.cc, test/common/tracing/http_tracer_impl_test.cc, test/common/upstream/cluster_manager_impl_test.cc, test/mocks/event/mocks.h, test/server/config/network/BUILD, test/server/config/network/http_connection_manager_test.cc, test/server/http/admin_test.cc, test/server/options_impl_test.cc
And one small impl leak cleanup (needed to add coverage anyway).
=> test: add some misc missing coverage

tools/stack_decode.py
The [backtrace] search regexes required updating.
=> Fix stack_decode.py post #1068.

docs/intro/arch_overview/cluster_manager.rst
There can only be a single SDS management server
=> docs: Clarify cluster configuration

test/common/http/filter/BUILD, test/common/http/filter/ip_tagging_filter_test.cc
=> ip tagging: coverage

test/common/network/dns_impl_test.cc
=> test: add error message to dns impl test

source/common/http/http1/codec_impl.cc, source/common/http/http1/codec_impl.h, source/common/http/http2/codec_impl.cc, test/integration/http2_integration_test.cc, test/integration/integration.cc, test/integration/integration.h, test/integration/integration_test.cc
This reverts commit b643ac8d5c4cbb9f8996701cecb5512596de68d0.
=> Revert "http: adding content length validation (#1121)"

ci/build_container/build_recipes/cares.sh, ci/build_container/build_recipes/http-parser.sh, ci/build_container/build_recipes/protobuf.sh, docs/install/requirements.rst
Upgrade to latest versions of http-parser and protobuf.
=> Upgrade http-parser to 2.7.1 and protobuf to 3.3.0.

tools/check_format.py
=> tools: add argsparse to check format. Allow additional excluded prefixes

source/server/BUILD, source/server/init_manager_impl.cc, source/server/init_manager_impl.h, source/server/server.cc, source/server/server.h
Needed for LDS. No actual logic changes just code movement.
=> init: move init manager code

test/common/network/cidr_range_test.cc
Add unit tests for unexercised cidr range code.
=> test: add coverage for unexercised cidr_range code

bazel/repositories.bzl, test/common/config/grpc_subscription_test_harness.h, test/common/config/http_subscription_test_harness.h
As per https://github.com/lyft/envoy-api/pull/96.
=> config: remove cc_generic_services dependency.

docs/configuration/http_conn_man/http_conn_man.rst, docs/configuration/http_conn_man/route_config/route_config.rst, source/common/json/config_schemas.cc, source/common/router/config_impl.cc, source/common/router/config_impl.h, test/common/router/config_impl_test.cc
fixes https://github.com/lyft/envoy/issues/1197
=> router config: add configuration option for cluster validation

include/envoy/server/worker.h, source/server/worker_impl.cc, source/server/worker_impl.h, test/mocks/server/mocks.cc, test/mocks/server/mocks.h, test/server/BUILD, test/server/listener_manager_impl_test.cc, test/server/worker_impl_test.cc
Not currently used but will be used in LDS.
=> worker: add ability to stop and remove a listener

OWNERS.md
Welcome Dan Noé to the wonderful world of OSS management. Enjoy. ;-)
=> owners: Dan Noé

bazel/repositories.bzl, source/common/grpc/json_transcoder_filter.cc, source/common/grpc/json_transcoder_filter.h, source/server/config/http/grpc_json_transcoder.cc, test/common/grpc/json_transcoder_filter_test.cc, test/integration/grpc_json_transcoder_integration_test.cc
- Use PathMatcherUtility to build
- Increase test coverage for GrpcJsonTranscoderConfig
- Rename typedef
#1192
=> Update gRPC-JSON library

source/common/buffer/zero_copy_input_stream_impl.h, source/common/config/http_subscription_impl.h, source/common/protobuf/protobuf.h, source/common/upstream/eds.cc
With this, I can do a Google import minus gRPC transcoding (where we need to do similar transforms
on the dependent library) and lightstep.
=> protobuf: some ProtobufTypes stragglers.

test/tools/schema_validator/BUILD, test/tools/schema_validator/schema_validator.cc, test/tools/schema_validator/validator.cc, test/tools/schema_validator/validator.h
Test tool to validate schemas for route configs. Further applications of this tool will validate Cluster and Listener JSON.
=> Schema validator tool

.travis.yml
@lyft/network-team Travis suggested changing to language: minimal to save more space.
=> build: change to language minimal

docs/configuration/http_filters/grpc_json_transcoder_filter.rst
sorry, left a broken link in the docs.
this may not worth another commit ,so maybe @lizan can cherry-pick it for me.
=> docs: fix JsonPrintOptions link

docs/configuration/listeners/ssl.rst, include/envoy/ssl/context_config.h, include/envoy/ssl/context_manager.h, source/common/json/config_schemas.cc, source/common/ssl/context_config_impl.cc, source/common/ssl/context_config_impl.h, source/common/ssl/context_impl.cc, source/common/ssl/context_impl.h, source/common/ssl/context_manager_impl.cc, source/common/ssl/context_manager_impl.h, source/server/listener_manager_impl.cc, test/common/ssl/connection_impl_test.cc, test/integration/ssl_integration_test.cc, test/integration/xfcc_integration_test.cc, test/mocks/ssl/mocks.h
=> ssl: require client certificate.

source/common/config/utility.cc, source/common/config/utility.h, source/common/router/BUILD, source/common/router/rds_impl.cc, source/common/stats/BUILD, source/common/stats/statsd.cc, source/common/stats/statsd.h, source/common/upstream/BUILD, source/common/upstream/cds_api_impl.cc, source/server/BUILD, source/server/lds_api.cc, test/server/lds_api_test.cc
Check that the lds cluster exists and local info is available.
Fixes https://github.com/lyft/envoy/issues/1264
=> lds api: more error handling

include/envoy/upstream/upstream.h, source/common/upstream/cluster_manager_impl.cc
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
=> upstream: Fix typos.

ci/coverage_publish.sh
@lyft/network-team @mkercher s3 encryption at rest per https://github.com/lyft/ops/blob/master/docs/s3/encryption_at_rest.md
=> security: s3 encrytion at rest

test/integration/tcp_proxy_integration_test.cc
using decl 'AnyNumber' is unused
=> format: clang tidy fix

source/common/protobuf/utility.cc
=> protobuf: update protobuf string wrapper

include/envoy/json/json_object.h, source/common/common/utility.cc, source/common/common/utility.h, source/common/config/BUILD, source/common/config/tls_context_json.cc, source/common/config/tls_context_json.h, source/common/http/utility.cc, source/common/json/json_loader.cc, source/common/protobuf/protobuf.h, source/common/protobuf/utility.h, source/common/ssl/BUILD, source/common/ssl/context_config_impl.cc, source/common/ssl/context_config_impl.h, source/common/upstream/BUILD, source/common/upstream/upstream_impl.cc, test/common/json/json_loader_test.cc
This is an incremental step towards CDS v2 protos replacing JSON.
=> config: convert TLS context JSON handling to protobuf.

source/common/event/dispatcher_impl.cc, source/common/event/dispatcher_impl.h, source/common/filesystem/filesystem_impl.cc, source/common/filesystem/filesystem_impl.h
Fixes https://github.com/lyft/envoy/issues/1294
=> dispatcher: fix createTimer() assert

source/common/network/BUILD, source/common/network/utility.cc, source/common/upstream/BUILD, source/common/upstream/logical_dns_cluster.cc, source/common/upstream/upstream_impl.cc
@htuch These are the calls I mentioned.
=> Wrap protobuf string values passed to fmt::Format in ProtobufTypes::FromString calls.

bazel/README.md
=> bazel: fix the nonexistent target

docs/configuration/http_conn_man/http_conn_man.rst, docs/intro/arch_overview/http_routing.rst, include/envoy/http/codec.h, source/common/http/http1/codec_impl.cc, source/common/http/http1/codec_impl.h, source/common/http/utility.cc, source/common/http/utility.h, source/common/json/config_schemas.cc, source/server/config/network/http_connection_manager.cc, source/server/config/network/http_connection_manager.h, source/server/http/admin.cc, test/common/http/conn_manager_utility_test.cc, test/common/http/http1/codec_impl_test.cc, test/config/integration/server.json, test/integration/fake_upstream.cc, test/integration/integration.cc, test/integration/integration.h, test/integration/integration_test.cc, test/integration/integration_test.h
Add forward proxy support 
#1214
=> Forward proxy support

test/integration/integration.cc
=> Fix a missing-field-initializers error.

test/test_common/environment.cc
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
=> test: fix implicit fallthrough

bazel/repositories.bzl, docs/configuration/http_conn_man/route_config/route.rst, include/envoy/json/json_object.h, source/common/common/utility.cc, source/common/common/utility.h, source/common/config/BUILD, source/common/config/base_json.cc, source/common/config/base_json.h, source/common/config/json_utility.h, source/common/config/metadata.h, source/common/config/rds_json.cc, source/common/config/rds_json.h, source/common/json/json_loader.cc, source/common/router/BUILD, source/common/router/config_impl.cc, source/common/router/config_impl.h, source/common/router/config_utility.cc, source/common/router/config_utility.h, source/common/router/rds_impl.cc, source/common/router/router_ratelimit.cc, source/common/router/router_ratelimit.h, test/common/common/utility_test.cc, test/common/json/json_loader_test.cc, test/common/router/BUILD, test/common/router/config_impl_test.cc, test/common/router/router_ratelimit_test.cc, test/tools/router_check/BUILD, test/tools/router_check/router.cc, test/tools/schema_validator/BUILD, test/tools/schema_validator/validator.cc
One from column A, one from column B...
=> config: complete RDS v1 JSON -> proto translation.

bazel/README.md
I think this is the information necessary to get it going for other folks.
=> bazel: update README for OS X

include/envoy/http/filter.h, source/common/grpc/json_transcoder_filter.cc, source/common/http/async_client_impl.h, source/common/http/conn_manager_impl.cc, source/common/http/conn_manager_impl.h, test/common/grpc/json_transcoder_filter_test.cc, test/common/http/conn_manager_impl_test.cc, test/config/integration/server_grpc_json_transcoder.json, test/mocks/http/mocks.h
=> grpc-json: clear route cache

source/common/config/filesystem_subscription_impl.h, source/common/config/filter_json.cc, source/common/config/grpc_subscription_impl.h, source/common/config/http_subscription_impl.h, source/common/grpc/json_transcoder_filter.cc, source/common/network/utility.cc, source/common/protobuf/protobuf.h, source/common/protobuf/utility.cc, source/common/protobuf/utility.h, source/common/router/rds_impl.cc, source/common/ssl/context_config_impl.cc, source/common/upstream/eds.cc, source/common/upstream/logical_dns_cluster.cc, source/common/upstream/upstream_impl.cc, source/server/config/network/http_connection_manager.cc
They are no longer necessary for import.
=> Removed FromString and ToString proto conversion functions

docs/configuration/http_conn_man/stats.rst, source/common/http/conn_manager_impl.h, source/common/http/conn_manager_utility.cc, test/common/http/conn_manager_impl_test.cc, test/common/http/conn_manager_utility_test.cc, test/mocks/runtime/mocks.cc, test/mocks/runtime/mocks.h
=> perf: UUID generation can no longer fail.

source/common/router/config_impl.cc, source/common/router/rds_impl.cc, source/common/upstream/eds.cc, source/server/config/network/http_connection_manager.cc, source/server/listener_manager_impl.cc
This is helpful for Google import and shouldn't affect anybody else.
=> config: few changes to help with protobuf string type mismatch.

docs/configuration/overview/overview.rst, docs/intro/arch_overview/dynamic_configuration.rst
Fixes https://github.com/lyft/envoy/issues/1468
=> docs: fix missing docs for top level LDS config

source/common/http/codec_helper.h, source/common/http/http2/codec_impl.cc, source/common/http/http2/codec_impl.h, test/common/http/http2/codec_impl_test.cc, test/integration/http2_upstream_integration_test.cc
=> Making sure stream callbacks are not called after stream end

bazel/target_recipes.bzl, ci/build_container/build_recipes/yaml-cpp.sh, ci/prebuilt/BUILD, docs/install/requirements.rst
Needed for YAML ingestion support.
=> build: add yaml-cpp to external deps.

include/envoy/server/BUILD, include/envoy/server/filter_config.h, source/common/config/filter_json.cc, source/common/config/lds_json.cc, source/server/config/network/http_connection_manager.cc, source/server/listener_manager_impl.cc, test/config/integration/server_xds.cds.yaml, test/config/integration/server_xds.eds.yaml, test/config/integration/server_xds.lds.yaml, test/config/integration/server_xds.rds.yaml
Despite printing snake field names as camel, protobuf accepts the snake case variants. These are closer to the proto and just look better.
=> config: switch YAML integration test configs to snake case.

include/envoy/http/access_log.h, source/common/http/access_log/access_log_formatter.cc, source/common/http/access_log/request_info_impl.h, source/common/router/router.cc, test/common/http/access_log/access_log_formatter_test.cc, test/common/http/access_log/access_log_impl_test.cc, test/mocks/http/mocks.cc, test/mocks/http/mocks.h
This reverts commit 23716e0ea8292163514f71c229a66177b3102ba5.
=> Revert "Added request and response times to RequestInfo (#1464) (#1510)"

configs/envoy_service_to_service.template.json, configs/routing_helper.template.json, docs/configuration/cluster_manager/cluster.rst, docs/configuration/http_conn_man/http_conn_man.rst, docs/configuration/overview/overview.rst, source/common/config/cds_json.cc, source/common/config/filter_json.cc, source/common/config/protocol_json.cc, source/common/config/protocol_json.h, source/common/json/config_schemas.cc, test/common/http/utility_test.cc, test/common/json/config_schemas_test_data/test_cluster_schema.py, test/common/upstream/upstream_impl_test.cc
=> part 2 of 1.4.0 deprecations

test/common/network/connection_impl_test.cc
The order of the listener's `onNewConnection` callback and the client's `onEvent(ConnectionEvent::Connected)` callback is not deterministic on OS X.
When BindTest connects and then immediately attempts to look at `server_connection_` it is often still nullptr.
Fixed this by keeping track of the two events in `ConnectImplTest::connect()` -- my initial instinct was to call `dispatcher_->exit()` from each expectation and run the dispatcher loop twice. Turns out that exit does not terminate the run loop immediately after the event completes, it continues processing until it runs out of events and then exits. This result is that both exit calls can happen during one call to `dispacher_->run()` and then the second call to run hangs.
I believe it's safe to use a plain int (as opposed …
=> test/common/network: fix flakey test on Mac OS

OWNERS.md
=> owners: add Alyssa Wilk

source/common/upstream/upstream_impl.cc, test/common/upstream/upstream_impl_test.cc
=> Using the source address from cluster config

source/common/router/config_impl.cc, source/common/router/config_impl.h
Fixes https://github.com/lyft/envoy/issues/1577
=> route config: add more comments on ownership safety

docs/configuration/http_conn_man/headers.rst
=> docs: Fix minor typo

test/config/BUILD, test/config/utility.cc, test/config/utility.h, test/integration/BUILD, test/integration/integration.cc, test/integration/integration.h, test/integration/proto_integration_test.cc
=> Adding a config util for bootstrap config

source/common/common/BUILD, source/common/common/macros.h, source/common/common/version.cc, source/common/grpc/BUILD, source/common/grpc/common.cc, source/common/redis/BUILD, source/common/redis/supported_commands.h, source/common/router/rds_impl.h, source/common/tracing/zipkin/span_context.cc, source/server/http/BUILD, source/server/http/admin.h, test/common/http/BUILD, test/common/http/conn_manager_impl_test.cc, test/test_common/BUILD, test/test_common/environment.cc, test/tools/router_check/json/BUILD, test/tools/router_check/json/tool_config_schemas.cc
Implements https://isocpp.org/wiki/faq/ctors#static-init-order-on-first-use in macro form. I decided to try and take a more general approach than implement `SINGLETON_STRING` only. Could be convinced otherwise.
=> macro for "construct on first use"

docs/configuration/http_conn_man/route_config/route.rst
Fixes https://github.com/lyft/envoy/issues/1553
=> docs: clarify how to route on HTTP method

GOVERNANCE.md, OWNERS.md
Fixes https://github.com/envoyproxy/envoy/issues/1665
=> docs: create GOVERNANCE.md

README.md
This is a requirement for graduation.
=> Update README to mention CNCF

CODE_OF_CONDUCT.md
https://github.com/cncf/foundation/blob/master/code-of-conduct.md
=> Update to CNCF Code of Conduct

CONTRIBUTING.md
https://developercertificate.org/
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Update CONTRIBUTING.md for DCO

ci/docker_push.sh
=> ci: one more try at pushing docker images

source/common/http/filter/buffer_filter.cc, source/common/http/filter/buffer_filter.h, source/common/http/filter/fault_filter.cc, source/common/http/filter/fault_filter.h, source/common/http/http2/codec_impl.cc, source/common/http/utility.cc, source/common/json/json_loader.cc, test/common/http/filter/buffer_filter_test.cc, test/common/http/filter/fault_filter_test.cc, test/integration/ssl_integration_test.cc, test/tools/router_check/router_check.cc
1) Remove stale TODOs
2) Use sendLocalReply in buffer/fault filter
=> misc cleanups

README.md, docs/intro/getting_help.rst, docs/requirements.txt
=> docs: contact updates

OWNERS.md
=> owners: add Daniel Hochman

README.md
Fixes https://github.com/envoyproxy/envoy/issues/1664
=> readme: badges

source/common/router/router.cc
=> router: fix temp reference issue

test/integration/integration_test.cc
true == true
"true" == true
false == false
"false" == true
:)
=> Fix implicit string -> bool conversion

test/integration/ads_integration_test.cc
=> test: fix merge race in ads_integration_test.

ci/build_container/build_recipes/googletest.sh, docs/install/requirements.rst
@jmillikin-stripe like so?
Part of #1695
=> Moving to a newer version of googletest

.circleci/config.yml
=> ci: dummy CircleCI config

docs/configuration/listeners/lds.rst
=> docs: fix lds docs

docs/configuration/http_filters/cors_filter.rst
Fixed some mistake in the docs.
=> Fix CORS documentation

docs/configuration/http_conn_man/route_config/route.rst, include/envoy/http/access_log.h, include/envoy/router/router.h, source/common/http/access_log/request_info_impl.h, source/common/http/async_client_impl.h, source/common/http/conn_manager_impl.cc, source/common/http/conn_manager_impl.h, source/common/http/websocket/ws_handler_impl.cc, source/common/http/websocket/ws_handler_impl.h, source/common/router/BUILD, source/common/router/config_impl.cc, source/common/router/config_impl.h, source/common/router/req_header_formatter.cc, source/common/router/req_header_formatter.h, source/common/router/router.cc, test/common/http/access_log/access_log_impl_test.cc, test/common/http/conn_manager_impl_test.cc, test/common/router/BUILD, test/common/router/config_impl_test.cc, test/common/router/req_header_formatter_test.cc, test/mocks/http/mocks.h, test/mocks/router/mocks.h, test/tools/router_check/json/tool_config_schemas.cc, test/tools/router_check/router.cc, test/tools/router_check/router.h, test/tools/router_check/test/config/TestRoutes.golden.json, test/tools/router_check/test/config/TestRoutes.json
Fixes #1016 
Signed-off-by: Kunal Gandhi <kugandhi@ebay.com>
=> http:support for adding dynamic request headers to the upstream requests

README.md
http://envoyslack.cncf.io
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add information about Slack

.circleci/config.yml
=> docs: add SSH keys to push job

ci/build_container/docker_push.sh, ci/do_ci.sh, ci/docker_push.sh
=> ci: push images

ci/README.md, ci/build_container/docker_build.sh, ci/build_container/docker_push.sh, ci/docker_push.sh
=> ci: fix build container push

ci/ci_steps.sh, ci/coverage_publish.sh, ci/do_ci.sh, ci/do_circle_ci.sh
=> ci: fixes for pushing coverage and images

ci/build_container/build_recipes/tclap.sh
=> thirdparty: pull TCLAP from GitHub

ci/coverage_publish.sh, ci/do_ci.sh, ci/docker_push.sh
=> ci: more fixes

.circleci/config.yml, ci/build_container/README.md, ci/envoy_build_sha.sh
=> ci: update build image SHA to 7480d2a53726b6389380d741f8a7e7b74a990133

docs/operations/cli.rst, include/envoy/filesystem/filesystem.h, include/envoy/server/options.h, source/common/common/BUILD, source/common/common/logger.cc, source/common/common/logger.h, source/common/filesystem/filesystem_impl.cc, source/common/filesystem/filesystem_impl.h, source/exe/main_common.cc, source/server/options_impl.cc, source/server/options_impl.h, source/server/server.cc, test/common/filesystem/filesystem_impl_test.cc, test/integration/server.h, test/mocks/filesystem/mocks.h, test/mocks/server/mocks.cc, test/mocks/server/mocks.h, test/server/options_impl_test.cc, test/server/server_test.cc
The file will be re-opened by SIGUSR1 just like access logs.
=> Optionally log to a file instead of stderr.

.circleci/config.yml
=> ci: disable OSX due to needing to sort out Circle config issues

source/common/router/config_impl.cc, source/common/router/config_impl.h, test/common/router/config_impl_test.cc
=> Support multiple hash policies for HTTP routing

docs/intro/arch_overview/websocket.rst
Signed-off-by: Gabriel Rosenhouse <grosenhouse@pivotal.io>
=> docs: fix up language in websocket arch overview

include/envoy/server/hot_restart.h
Signed-off-by: Gabriel Rosenhouse <grosenhouse@pivotal.io>
=> Fix up doc comments in hot_restart.h

ci/build_container/build_container_ubuntu.sh
=> Whitespace addition to kick new build

.circleci/config.yml, ci/docker_push.sh, ci/docker_tag.sh
Old PR: https://github.com/envoyproxy/envoy/pull/1743
Signed-off-by: bndw <benjamindwoodward@gmail.com>
=> CI: Publish tags to Dockerhub

test/common/filesystem/filesystem_impl_test.cc
=> Fix race condition in TEST(FileSystemImpl, flushToLogFileOnDemand)

.circleci/config.yml, bazel/README.md, ci/coverage_publish.sh
=> ci: upload coverage artifact on every build

include/envoy/api/os_sys_calls.h, source/common/api/os_sys_calls_impl.cc, source/common/api/os_sys_calls_impl.h, source/server/hot_restart_impl.cc, source/server/hot_restart_impl.h, test/mocks/api/mocks.h, test/server/hot_restart_impl_test.cc
This is needed for Lyft's test environment.
=> hot restart test: also mock out bind call

source/exe/main.cc
=> Fix mac build

ci/build_container/build_container_ubuntu.sh
=> Update expected Ubuntu compiler version.

README.md
https://goo.gl/5Cergb
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add community meeting information

.circleci/config.yml, ci/mac_ci_setup.sh
I'll keep an eye on the pull request CI.
=> mac: re-enable macOS ci

docs/operations/admin.rst, source/server/http/admin.cc, test/integration/integration_admin_test.cc
Signed-off-by: jmphilli <jphillips@lyft.com>
=> Admin:  added `added_via_api` flag to `/clusters` endpoint

docs/configuration/http_conn_man/stats.rst
Signed-off-by: Constance Caramanolis <ccaramanolis@lyft.com>
=> Docs: Fix indentation for per listener stats documentation.

docs/requirements.txt
=> docs: update theme to fix sidebar issue

ci/build_container/docker_push.sh
Signed-off-by: John Millikin <jmillikin@stripe.com>
(trying to create this PR again because Github wasn't picking up changed tip in the other one)
=> Push new Docker images if anything under bazel/ changes.

ci/build_container/docker_build.sh
=> Allow specifying the entire image name in docker_build.sh

ci/build_setup.sh
=> Allow specifying extra build options via BAZEL_EXTRA_OPTIONS

docs/configuration/http_conn_man/http_conn_man.rst
=> docs: fix indent

bazel/external/lightstep.BUILD, bazel/genrule_repository.bzl
This is another attempt to prevent build failures when using non-sandbox
mode. Instead of trying to find things under `src/c++11/` second, we just
drop that entire directory from the search path.
This fixes `/usr/bin/ld: unrecognized option '--push-state'` errors
caused when older versions of G++ use gold-specific options to GNU LD.
=> Lightstep includes and gold

include/envoy/http/filter.h, source/common/http/conn_manager_impl.cc, test/common/http/conn_manager_impl_test.cc
=> http: allow add*Data() to be called from *Data() filter callbacks

test/integration/tcp_proxy_integration_test.cc
=> adding a TCP test for upstream writing first

bazel/target_recipes.bzl, ci/build_container/build_recipes/luajit.sh, ci/prebuilt/BUILD, docs/install/requirements.rst
=> thirdparty: add luajit

.circleci/config.yml
=> circleci: bump hashes to match #1915.

docs/publish.sh
=> docs: push to primary docs repo

docs/publish.sh
=> docs: fix publish take 2

ci/envoy_build_sha.sh
=> ci: single source of truth for Envoy Docker base image.

source/common/config/utility.cc
Signed-off-by: Reuven Lazarus <rzl@google.com>
=> Add a missing #include.

WORKSPACE, bazel/repositories.bzl
=> Add rules_go bazel dependency

README.md
=> readme: add dashboards blog

source/common/upstream/eds.cc, source/common/upstream/upstream_impl.cc, source/common/upstream/upstream_impl.h, test/common/upstream/sds_test.cc
See code comment for more information.
=> eds: block health check recalculations during initialization

ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
*Description* : Provides a template for PR and Issues in Github. 
*Fixes* : #1432 
Signed-off-by: Constance Caramanolis <ccaramanolis@lyft.com>
=> Templates: Add PR and Issue template

README.md
=> readme: add contributing section

ci/prebuilt/BUILD, source/common/common/logger.h, source/common/http/filter/lua/BUILD, source/common/http/filter/lua/wrappers.cc, source/common/http/filter/lua/wrappers.h, source/common/lua/BUILD, source/common/lua/lua.h, source/common/lua/wrappers.cc, source/common/lua/wrappers.h, test/common/http/filter/lua/BUILD, test/common/http/filter/lua/wrappers_test.cc, test/common/lua/BUILD, test/common/lua/wrappers_test.cc, test/test_common/BUILD, test/test_common/lua_wrappers.h
*Description*:
Adds base and http object wrappers needed for the HTTP filter.
*Testing*: Unit
=> lua: base and http wrappers

source/common/config/address_json.cc, source/common/network/utility.cc, source/common/network/utility.h, test/common/config/utility_test.cc
*title*: cds: better error message for uds + strict_dns cluster
*Description*:
More descriptive error messages for URL parsing errors while translating JSON.
#1961 
*Testing*:
UT included.
=> Better error message for UDS + strict_dns cluster

source/common/config/BUILD, source/common/config/filter_json.cc, source/common/config/filter_json.h, source/common/http/filter/BUILD, source/common/http/filter/fault_filter.cc, source/common/http/filter/fault_filter.h, source/server/config/http/BUILD, source/server/config/http/fault.cc, source/server/config/http/fault.h, test/common/http/filter/BUILD, test/common/http/filter/fault_filter_test.cc, test/server/config/http/config_test.cc
Signed-off-by: Shriram Rajagopalan <shriram@us.ibm.com>
*v2 api: adding fault filter*
*Description*: Adding support for V2 API for fault filter
*Testing*: unit tests
=> fault filter using v2 API

ci/build_container/docker_build.sh
=> ci: fix build image push

.circleci/config.yml, ci/ci_steps.sh, ci/envoy_build_sha.sh, docs/install/sandboxes/local_docker_build.rst
=> ci: update to new docker hub org

test/config/utility.h
*title*: test: fix missing include header
*Description*:
Test utility failed to compile using gcc 7.2.
Fixes: https://groups.google.com/forum/#!topic/envoy-dev/tqTExh5E8qI
=> test: fix missing include header

docs/configuration/network_filters/redis_proxy_filter.rst, source/common/redis/BUILD, source/common/redis/proxy_filter.cc, source/common/redis/proxy_filter.h, source/server/config/network/redis_proxy.cc, test/common/redis/proxy_filter_test.cc
=> redis: implement drain close functionality

bazel/repositories.bzl, docs/configuration/listeners/listeners.rst, docs/intro/arch_overview/arch_overview.rst, docs/intro/arch_overview/draining.rst, docs/intro/arch_overview/health_checking.rst, include/envoy/server/listener_manager.h, source/common/config/lds_json.cc, source/common/json/config_schemas.cc, source/exe/main_common.cc, source/server/config_validation/server.h, source/server/drain_manager_impl.cc, source/server/drain_manager_impl.h, source/server/listener_manager_impl.cc, source/server/listener_manager_impl.h, test/mocks/server/mocks.h, test/server/drain_manager_impl_test.cc, test/server/listener_manager_impl_test.cc, test/server/utility.h
*API Changes*: https://github.com/envoyproxy/data-plane-api/pull/227
*Testing*: UT only
=> listeners: implement drain_type option

bazel/external/jinja.BUILD, bazel/external/markupsafe.BUILD, bazel/repositories.bzl, bazel/repository_locations.bzl
Fixes https://github.com/envoyproxy/envoy/issues/2041
Signed-off-by: John Millikin <jmillikin@stripe.com>
=> Move all repository locations to `repository_locations.bzl`.

.circleci/config.yml, ci/do_ci.sh, docs/README.md, docs/publish.sh
Fixes https://github.com/envoyproxy/envoy/issues/1290
=> docs: push on tags only

bazel/repository_locations.bzl
=> data-plane-api: bump sha

bazel/repository_locations.bzl
Signed-off-by: John Millikin <jmillikin@stripe.com>
=> Update protobuf dependency to 3.5.0.

bazel/README.md
Signed-off-by: Louis Taylor <louis@kragniz.eu>
=> docs: add fedora build deps to copy+paste

test/common/grpc/codec_test.cc
Signed-off-by: Louis Taylor <louis@kragniz.eu>
=> test: improve coverage of grpc/codec

OWNERS.md
Congrats and thanks for all your hard work!
=> owners: add Stephan as maintainer

bazel/repository_locations.bzl, source/common/access_log/access_log_impl.cc, source/common/access_log/access_log_impl.h, source/common/config/filter_json.cc, source/common/config/filter_json.h, source/common/filter/tcp_proxy.cc, source/server/config/network/file_access_log.cc, test/common/access_log/access_log_impl_test.cc, test/common/filter/tcp_proxy_test.cc, test/common/router/router_upstream_log_test.cc, test/server/config/network/config_test.cc
=> envoy-api: update SHA and fix namespaces

include/envoy/upstream/upstream.h, source/common/config/cds_json.cc, source/common/config/cds_json.h, source/common/json/config_schemas.cc, source/common/upstream/cluster_manager_impl.cc, source/common/upstream/ring_hash_lb.cc, source/common/upstream/ring_hash_lb.h, source/common/upstream/subset_lb.cc, source/common/upstream/subset_lb.h, source/common/upstream/upstream_impl.cc, source/common/upstream/upstream_impl.h, test/common/upstream/BUILD, test/common/upstream/cluster_manager_impl_test.cc, test/common/upstream/ring_hash_lb_test.cc, test/common/upstream/subset_lb_test.cc, test/mocks/upstream/cluster_info.cc, test/mocks/upstream/cluster_info.h
**Description**
Adds `minimum_ring_size` and `use_std_hash`. Fixes https://github.com/envoyproxy/envoy/issues/2021.
**TODO**
**API Changes**
Completes https://github.com/envoyproxy/data-plane-api/pull/202.
**Risk Level**
Low
**Testing**
UT
=> ring_hash_lb: wire up ring size and hash fn config

OWNERS.md
Congrats Greg and thanks for all your hard work!
=> owners: add Greg Greenway

bazel/README.md
docs: Updated bazel readme to include installing the latest version of bazel.
Unfortunately I missed the "developer" section of the readme when I submitted my previous PR.  Sorry about that.
Risk: Low
Signed-off-by: Nicholas J <nicholas.a.johns5@gmail.com>
=> Docs: Updated bazel readme to include latest bazel.

PULL_REQUEST_TEMPLATE.md
pr template: add docs changes optional link, misc enhancements
*Description*: added an optional link to docs changes. Moved the optional fields after the required ones.
*Testing*: docs changes. No testing needed.
=> pr template: add docs changes optional link, misc enhancements

source/common/grpc/async_client_impl.h, source/common/tracing/http_tracer_impl.h, test/common/grpc/async_client_impl_test.cc
Signed-off-by: Gary Brown <gary@brownuk.com>
=> tracing: Remove duplicate 'upstream cluster' tag

bazel/repositories.bzl, bazel/repository_locations.bzl, source/server/BUILD, source/server/config/stats/BUILD, source/server/configuration_impl.cc, source/server/configuration_impl.h
*Description*:
Envoy side changes for https://github.com/envoyproxy/data-plane-api/pull/342.
Also this includes a follow-up commit "Specify correct external_deps" for https://github.com/envoyproxy/envoy/pull/2158.
*Testing*:
Automated tests should cover this.
https://github.com/envoyproxy/data-plane-api/pull/342.
N/A
=> data-plane-api: extract trace protos

tools/path_fix.sh
=> path fix: gracefully handle errors

source/common/config/cds_json.cc, source/common/config/tls_context_json.cc, source/common/ssl/context_config_impl.cc, source/server/config_validation/server.cc, source/server/server.cc, source/server/server.h, test/config_test/config_test.cc
We were not validating bootstrap in the v1 to v2 conversion case.
Fix that. Also use shared code across main server, validation server,
and config test to make sure we don't miss changes in the future.
*Testing*: Existing tests now actually catch stuff. ;)
Fixes https://github.com/envoyproxy/envoy/issues/2219
=> bootstrap: validate in all cases

test/common/event/dispatcher_impl_test.cc
*Description*:
The dispatcher has no real unit testing of documented functionality.  As components that are linked into Envoy start to take advantage of the dispatcher, this functionality should have unit tests that clearly show that the methods work as desired.
*Testing*: Added new tests.
=> dispatcher: add simple unit tests

source/common/http/conn_manager_utility.cc, test/common/http/conn_manager_utility_test.cc
Follow up to https://github.com/envoyproxy/envoy/pull/2232.
=> conn manager utility: comment cleanups

source/exe/BUILD
*Testing*: All targets build. All tests pass.
=> build: Move DynamoDB into the non-core protocols library

DEPRECATED.md, RAW_RELEASE_NOTES.md, SECURITY_RELEASE_PROCESS.md, bazel/README.md, configs/original-dst-cluster/README.md, source/docs/flow_control.md, test/config/integration/certs/README.md
*Description*:
Fixes a few typos in the documentation.
=> docs: fix typos

CONTRIBUTING.md
=> contributing: DCO fixup best practice.

bazel/README.md
=> bazel: fix links to requirements docs.

ci/build_container/build_container_centos.sh, ci/build_container/docker_push.sh
Install cmake 3 from EPEL, enable centos build image (disabled in #2233)
=> ci build image: enable centos

support/hooks/pre-push
=> support: do not check DCO on merge commits

CONTRIBUTING.md, support/README.md
Signed-off-by: Brian Pane <bpane@pinterest.com>
=> Add some documentation on the format fix script.

bazel/repository_locations.bzl
=> tracing: Update lightstep to 0.6.1.

bazel/repository_locations.bzl, source/server/config/access_log/grpc_access_log.cc, test/integration/access_log_integration_test.cc, test/server/config/access_log/config_test.cc
=> access log: update to use GrpcCluster

source/common/access_log/grpc_access_log_impl.h, source/common/config/grpc_mux_impl.h, source/common/filter/tcp_proxy.h, source/common/upstream/subset_lb.h, source/server/lds_api.cc, test/common/upstream/ring_hash_lb_test.cc, test/integration/xfcc_integration_test.cc
Signed-off-by: James Synge <jamessynge@google.com>
=> Add missing includes of <unordered_map>

source/server/config/network/http_connection_manager.cc, source/server/listener_manager_impl.cc
Logging filter configuration makes debugging easier.
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
=> server: Log filter configuration.

bazel/repository_locations.bzl, source/common/config/subscription_factory.h, source/common/config/utility.cc, source/common/router/rds_impl.cc, source/common/router/rds_subscription.cc, source/common/upstream/cds_subscription.cc, source/common/upstream/cluster_manager_impl.cc, source/common/upstream/sds_subscription.cc, source/server/config/access_log/grpc_access_log.cc, source/server/lds_subscription.cc, test/common/config/subscription_factory_test.cc, test/common/config/utility_test.cc, test/common/upstream/eds_test.cc, test/common/upstream/sds_test.cc, test/integration/access_log_integration_test.cc, test/integration/ads_integration_test.cc, test/integration/header_integration_test.cc, test/integration/load_stats_integration_test.cc, test/server/config/access_log/config_test.cc
Since there was some renaming and refactoring of messages in b796da4, there's some code churn here.
=> build: update data-plane-api to b796da4.

test/integration/access_log_integration_test.cc
*Testing*: Test fix
Fixes https://github.com/envoyproxy/envoy/issues/2327
=> access log: fix integration test flake

bazel/repository_locations.bzl
Signed-off-by: Kyle Myerson <kmyerson@google.com>
=> build: update data-plane-api to 90698c6

bazel/repository_locations.bzl
Signed-off-by: Kyle Myerson <kmyerson@google.com>
=> build: update data-plane-api to f268484

OWNERS.md
=> owners: promote Alyssa to senior maintainer

source/server/config/http/lightstep_http_tracer.cc
Regression from https://github.com/envoyproxy/envoy/pull/2368
*Testing*: Covered by existing tests (why ASAN does not catch I don't know)
=> lightstep: fix string temporary issue

test/common/grpc/BUILD, test/common/grpc/grpc_client_integration.h, test/common/grpc/grpc_client_integration_test.cc, test/integration/BUILD, test/integration/access_log_integration_test.cc, test/integration/ads_integration_test.cc, test/integration/metrics_service_integration_test.cc, test/integration/ratelimit_integration_test.cc, test/integration/utility.cc
Testing: New parameterized integration tests.
=> grpc: parameterize integration tests by gRPC client type.

DEPRECATED.md
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
=> DEPRECATED.md: Fix typo.

test/integration/ratelimit_integration_test.cc, test/integration/server.h
=> test: fix ratelimit_integration_test flake introduced in #2434.

OWNERS.md
*Risk Level*: n/a.
*Testing*: n/a
=> Adding jmarantz as an area expert for abseil and performance work

test/integration/access_log_integration_test.cc
Failed to update the stats check for this test in #2481.
In general, we should get better at abstracting away these gRPC client type dependent stats in
integration tests, but we should merge this PR to reduce CI flakes first.
Testing: 100 runs of the test with -c dbg.
=> test: fix flake in access_log_integration_test.

test/common/ssl/ssl_socket_test.cc
Adding "" to the tests to fix a bad merge.
*Testing*: yep
=> Unbreaking build

test/common/grpc/common_test.cc
=> Improve Grpc::Common test coverage

test/common/http/filter/cors_filter_test.cc, test/common/http/filter/squash_filter_test.cc, test/server/config/http/BUILD, test/server/config/http/config_test.cc
*Risk Level*: n/a (test only)
*Testing*: test-only :-)
=> Improving filter test coverage

RAW_RELEASE_NOTES.md, include/envoy/registry/registry.h, source/common/router/config_impl.h, source/common/upstream/upstream_impl.cc, test/common/access_log/grpc_access_log_impl_test.cc, test/common/filter/auth/client_ssl_test.cc, test/common/filter/tcp_proxy_test.cc, test/common/mongo/proxy_test.cc, test/common/network/address_impl_test.cc, test/common/redis/conn_pool_impl_test.cc, test/common/redis/proxy_filter_test.cc, test/common/router/config_impl_test.cc, test/common/stats/statsd_test.cc, test/common/tracing/http_tracer_impl_test.cc, test/common/upstream/cluster_manager_impl_test.cc, test/common/upstream/health_checker_impl_test.cc, test/common/upstream/logical_dns_cluster_test.cc, test/mocks/redis/mocks.h, test/server/http/admin_test.cc, test/server/http/health_check_test.cc, test/server/listener_manager_impl_test.cc
Also fix a bug on exposing decorator to weighted routes.
*Testing*: Existing and new UT
=> misc coverage

ci/build_container/build_container_ubuntu.sh
=> ci: rebuild Docker image for Bazel 0.10.0.

test/common/protobuf/BUILD, test/common/protobuf/descriptor_test.cc
Part of https://github.com/envoyproxy/envoy/issues/2471.
*Testing*: New test
=> test: add proto descriptor back compat test

source/common/router/config_utility.cc, test/common/router/config_impl_test.cc, test/integration/http2_integration_test.cc, test/integration/http2_upstream_integration_test.cc, test/integration/http_integration.cc, test/integration/http_integration.h, test/integration/integration_test.cc
Signed-off-by: Brian Pane <bpane@pinterest.com>
=> add more test coverage for health check filter (and fix a bug it found)

ci/do_circle_ci.sh
=> build: updating stale comment

test/mocks/router/mocks.cc, test/mocks/router/mocks.h
*Description*: Add mock support for recently added RouteEntry related methods and classes.
*Testing*: N/A - this adds mock classes.
=> rds: add mocks for a recently added classes and methods

ci/build_container/Makefile
=> build: avoid spurious rebuilds of external deps.

bazel/repository_locations.bzl, source/common/grpc/BUILD, source/common/grpc/google_async_client_impl.cc, source/common/grpc/google_async_client_impl.h, source/common/grpc/google_async_client_site.cc
We need to do some Google specific channel creation logic, so introducing a generic mechanism for
site-specifics.
Testing: Existing tests.
=> grpc: site specific customizations for Google gRPC.

RAW_RELEASE_NOTES.md, bazel/repository_locations.bzl, include/envoy/upstream/load_balancer_type.h, source/common/upstream/BUILD, source/common/upstream/cluster_manager_impl.cc, source/common/upstream/maglev_lb.cc, source/common/upstream/maglev_lb.h, source/common/upstream/ring_hash_lb.cc, source/common/upstream/ring_hash_lb.h, source/common/upstream/subset_lb.cc, source/common/upstream/thread_aware_lb_impl.cc, source/common/upstream/thread_aware_lb_impl.h, source/common/upstream/upstream_impl.cc, test/common/upstream/BUILD, test/common/upstream/cluster_manager_impl_test.cc, test/common/upstream/load_balancer_benchmark.cc, test/common/upstream/maglev_lb_test.cc, test/common/upstream/subset_lb_test.cc, test/common/upstream/upstream_impl_test.cc
Refactor RingHash into a common base class. The amount of new code needed
for Maglev is tiny.
*Testing*: Unit
*Docs Changes*: https://github.com/envoyproxy/data-plane-api/pull/487
*API Changes*: https://github.com/envoyproxy/data-plane-api/pull/487
*Release Notes*: Added
Fixes https://github.com/envoyproxy/envoy/issues/2267
=> load balancer: add Maglev

source/common/http/filter/gzip_filter.cc, source/common/http/filter/gzip_filter.h
gzip: just one tiny more reference to std::string
*Description*:
I has a sad because I missed the header and upstream is happy with String = std::string but missed it for Google internal.
*Testing*: Ran all the tests
=> String is still not string

source/common/redis/conn_pool_impl.cc, test/common/redis/conn_pool_impl_test.cc
**Description**
We were missing some Redis stats at the host level.
**Risk Level**
Low
**Testing**
Unit
N/A
N/A
=> redis: attribute stats to hosts

GOVERNANCE.md
=> docs: updating docs for oncall rotation

ci/build_container/build_container_centos.sh
This is needed by the coverage build.
Fixes #2731
=> centos image: yum install bc

examples/front-proxy/README.md, examples/grpc-bridge/README.md, examples/jaeger-tracing/README.md, examples/zipkin-tracing/README.md
Signed-off-by: Daniel Hochman <danielhochman@users.noreply.github.com>
Fixes #2748
=> docs: fix broken example links

source/common/router/router.cc, test/common/router/router_upstream_log_test.cc
*Description*:
As part of the changes in #2660 the timing of upstream requests was dropped and upstream logs that use `%DURATION%` no longer report timings. This change reinstates recording of upstream request timings and adds an explicit unit test.
*Testing*: Unit test
Signed-off-by: Stephan Zuercher <stephan@turbinelabs.io>
=> router: bring back upstream request timings

GOVERNANCE.md, bazel/repository_locations.bzl
Also add docs on how to cut a release.
=> data-plane-api: update for release

bazel/repository_locations.bzl
=> version: bump to 1.7.0-dev

test/common/http/codec_client_test.cc, test/common/http/common.h, test/integration/http2_integration_test.cc, test/mocks/upstream/cluster_info.cc
Fixes few nits noted in this PR https://github.com/envoyproxy/envoy/pull/2714
Description: Fixes few nits noted in this PR https://github.com/envoyproxy/envoy/pull/2714. More of cosmetic changes. No functional change.
Risk Level: Low. More of formatting related changes.
Testing: Automated tests
Docs Changes:  NA
=> http: idle timeout cleanup

source/extensions/filters/network/redis_proxy/codec.h
=> redis_proxy: fix comment

source/common/config/well_known_names.h
=> config: fix comment

source/common/config/BUILD, source/common/config/utility.h, source/common/config/well_known_names.h, test/common/http/filter/gzip_filter_test.cc, test/common/protobuf/utility_test.cc, test/common/router/config_impl_test.cc, test/common/stats/stats_impl_test.cc, test/extensions/filters/http/lua/lua_filter_test.cc
=> test: misc coverage increases

configs/BUILD, test/config_test/BUILD, test/config_test/config_test.cc, test/config_test/example_configs_test.cc
=> config: validate freebind and original-dst-cluster example configs.

source/extensions/tracers/common/ot/opentracing_driver_impl.h
Signed-off-by: Wuliang <wu.liang30@zte.com.cn>
*title*: *modify note*
>Title can be a one or two words to describe the subsystem or the aspect
this PR applies to. Title and description must be lower case. For example:
* ci: update build image to 44d539cb
* docs: fix indent, buffer: add copyOut() method
* router:add x-envoy-overloaded header
* tls: add support for specifying TLS session ticket keys
*Description*:
>modify one note. one word is error.
*Risk Level*: Low | Medium | High
>Low: Small bug fix or small optional feature.
*Testing*:
[Optional *API Changes*:]
>Link to [Data Plane PR](https://github.com/envoyproxy/data-plane-api/pulls)]
>Description of what is deprecated.
=> Modify the explanatory note

source/common/runtime/uuid_util.h
Signed-off-by: pandaamanda <xiong.zhongliang@zte.com.cn>
*title*: *annotation*
=> A simple annotation error

source/exe/BUILD, source/extensions/extensions_build_config.bzl, source/extensions/filters/http/health_check/BUILD, source/extensions/filters/http/health_check/config.cc, source/extensions/filters/http/health_check/config.h, source/extensions/filters/http/health_check/health_check.cc, source/extensions/filters/http/health_check/health_check.h, source/server/http/BUILD, test/extensions/filters/http/health_check/BUILD, test/extensions/filters/http/health_check/config_test.cc, test/extensions/filters/http/health_check/health_check_test.cc, test/extensions/filters/network/hcm/BUILD, test/integration/BUILD, test/server/BUILD, test/server/config/http/BUILD, test/server/config/http/config_test.cc, test/server/http/BUILD
=> repo reorg: move health check filter

STYLE.md
Signed-off-by: Raul Gutierrez S <rgs@pinterest.com>
=> style: fix grammar error

source/common/ssl/context_impl.cc, source/common/ssl/ssl_socket.cc
=> tls: use ranged for loops.

.circleci/config.yml
=> ci: some more CircleCI debug.

api/CONTRIBUTING.md, ci/api_mirror.sh
=> api: trivial change to test data-plane-api mirroring.

ci/api_mirror.sh
=> api: fix api_mirror.sh CHECKOUT_DIR dependency.

ci/api_mirror.sh
=> ci: another api_mirror.sh fixup.

api/envoy/admin/v2/config_dump.proto, ci/api_mirror.sh
Validated the full push-to-master to data-plane-api, so this time it should work.
=> ci: another fixup round for api_mirror.sh.

ci/build_container/Dockerfile-centos, ci/build_container/Dockerfile-ubuntu, ci/build_container/docker_build.sh
=> ci: fix build_image build.

CONTRIBUTING.md, api/README.md, ci/api_mirror.sh
=> api: some fixups post repo merge.

.circleci/config.yml, ci/filter_example_mirror.sh
=> ci: bump envoy-filter-example SHA on master merge.

docs/root/configuration/http_filters/lua_filter.rst
=> docs: remove Lua experimental tag

source/common/upstream/health_checker_impl.cc, test/common/upstream/health_checker_impl_test.cc
This replays https://github.com/envoyproxy/envoy/pull/3113 from brian-pane@,
separate PR due to ongoing DCO technical difficulties.
=> build: fix FALLTHRU related build breakage.

source/extensions/extensions_build_config.bzl, test/extensions/health_checkers/redis/BUILD
This was missing from the previous commit.
=> redis hc: set up build configuration

test/fuzz/README.md
=> fuzz: docs for local Docker workflow.

source/extensions/filters/network/redis_proxy/codec_impl.h, source/extensions/filters/network/redis_proxy/command_splitter_impl.h, source/extensions/filters/network/redis_proxy/conn_pool_impl.h, source/extensions/filters/network/redis_proxy/proxy_filter.h, test/extensions/filters/network/redis_proxy/codec_impl_test.cc, test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc, test/extensions/filters/network/redis_proxy/proxy_filter_test.cc
=> redis_proxy: update comments

source/common/upstream/cluster_manager_impl.cc, test/common/upstream/cluster_manager_impl_test.cc, test/server/server_corpus/clusterfuzz-testcase-server_fuzz_test-5704964522377216
This was found via proto fuzzing the server config.
Testing: Added cluster_manager_impl_test.
=> upstream: remove incorrect ASSERT regarding consistent hash + subset LB

api/envoy/service/metrics/v2/metrics_service.proto
*Description*: Drop draft status for metrics service
*Testing*: NA
*Docs Changes*: NA
*Release Notes*: NA
=> api: drop draft status for metrics service

source/common/upstream/subset_lb.cc, source/common/upstream/subset_lb.h, test/common/upstream/subset_lb_test.cc, test/server/server_corpus/clusterfuzz-testcase-server_fuzz_test-5705154446753792
This was found via proto fuzzing the server config.
Testing: subset_lb_test regression.
=> subset_lb: fix heap-use-after-free bug.

tools/run-valgrind.sh, tools/valgrind-suppressions.txt
*Description*:
>Adds a script to help with running bazel tests under valgrind.
*Testing*: lots of tests run under valgrind, several fail, but that shouldn't block this PR.
=> tools: Add infrastructure to make it easier to run valgrind

ci/build_container/build_recipes/nghttp2.sh
=> build: update nghttp2 to v1.32.0.

api/envoy/type/percent.proto
Signed-off-by: Daniel Hochman <danielhochman@users.noreply.github.com>
=> build: remove unused import in percent.proto

PULL_REQUEST_TEMPLATE.md
Fixes https://github.com/envoyproxy/envoy/issues/2925
=> docs: clarify release notes are required for API changes

source/common/config/well_known_names.h
Fixes https://github.com/envoyproxy/envoy/issues/2716
=> stats: fix typo

api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto, docs/root/configuration/tools/router_check.rst
*title*: Minor documentation fixes
Removed a stray line that was out of place, and fixed the JSON syntax for the route table example test.
=> Minor documentation fixes

docs/root/configuration/access_log.rst, docs/root/configuration/http_conn_man/headers.rst, source/common/access_log/access_log_formatter.cc, source/common/router/header_formatter.cc, test/common/access_log/access_log_formatter_test.cc, test/common/router/config_impl_test.cc, test/common/router/header_formatter_test.cc, test/config/integration/tcp_proxy.json, test/extensions/filters/network/tcp_proxy/tcp_proxy_test.cc, test/integration/tcp_proxy_integration_test.cc, test/tools/router_check/test/config/TestRoutes.json
Fixes https://github.com/envoyproxy/envoy/issues/2900
*Testing*: Fixed existing tests
=> deprecations: remove DOWNSTREAM_ADDRESS and CLIENT_IP formatters

source/extensions/filters/network/client_ssl_auth/BUILD, source/extensions/filters/network/client_ssl_auth/config.cc, source/extensions/filters/network/client_ssl_auth/config.h, source/extensions/filters/network/common/BUILD, source/extensions/filters/network/common/factory_base.h, source/extensions/filters/network/ext_authz/BUILD, source/extensions/filters/network/ext_authz/config.cc, source/extensions/filters/network/ext_authz/config.h, source/extensions/filters/network/http_connection_manager/BUILD, source/extensions/filters/network/http_connection_manager/config.cc, source/extensions/filters/network/http_connection_manager/config.h, source/extensions/filters/network/mongo_proxy/BUILD, source/extensions/filters/network/mongo_proxy/config.cc, source/extensions/filters/network/mongo_proxy/config.h, source/extensions/filters/network/ratelimit/BUILD, source/extensions/filters/network/ratelimit/config.cc, source/extensions/filters/network/ratelimit/config.h, source/extensions/filters/network/redis_proxy/BUILD, source/extensions/filters/network/redis_proxy/config.cc, source/extensions/filters/network/redis_proxy/config.h, source/extensions/filters/network/redis_proxy/conn_pool_impl.h, source/extensions/filters/network/tcp_proxy/BUILD, source/extensions/filters/network/tcp_proxy/config.cc, source/extensions/filters/network/tcp_proxy/config.h, test/extensions/filters/network/ext_authz/config_test.cc, test/extensions/filters/network/http_connection_manager/config_test.cc, test/extensions/filters/network/mongo_proxy/config_test.cc, test/extensions/filters/network/ratelimit/config_test.cc, test/extensions/filters/network/redis_proxy/config_test.cc
Similar to the one previously done for HTTP.
Fixes https://github.com/envoyproxy/envoy/issues/2911
=> network filters: add factory base to reduce boilerplate

docs/root/configuration/listener_filters/tls_inspector.rst, include/envoy/network/listen_socket.h, source/common/network/listen_socket_impl.h, source/extensions/filters/listener/tls_inspector/tls_inspector.cc, source/extensions/filters/listener/tls_inspector/tls_inspector.h, test/extensions/filters/listener/tls_inspector/tls_inspector_benchmark.cc, test/extensions/filters/listener/tls_inspector/tls_inspector_test.cc, test/mocks/network/mocks.h, test/test_common/tls_utility.cc, test/test_common/tls_utility.h
*Docs Changes*: Minor
For #3397.
=> listener: teach TLS Inspector about ALPN.

source/extensions/filters/network/ext_authz/config.h, source/extensions/filters/network/http_connection_manager/config.h, source/extensions/filters/network/mongo_proxy/config.h, source/extensions/filters/network/ratelimit/config.h, source/extensions/filters/network/redis_proxy/config.h
=> network filters: some missing validation includes in #3393.

docs/root/faq/sni.rst, source/server/listener_manager_impl.cc, test/server/listener_manager_impl_test.cc
=> listener: automatically inject TLS Inspector when needed.

test/server/http/admin_test.cc
Redo of https://github.com/envoyproxy/envoy/pull/2875/files.
=> test: fix expectation

docs/root/operations/admin.rst, include/envoy/stats/stats.h, source/common/stats/thread_local_store.cc, source/common/stats/thread_local_store.h, source/server/http/admin.cc, source/server/http/admin.h, test/integration/integration_admin_test.cc, test/integration/integration_admin_test.h, test/mocks/stats/mocks.h, test/server/http/admin_test.cc
*Description*:
Consistence in stats output formats as discussed in https://github.com/envoyproxy/envoy/issues/3210#issuecomment-389230233
*Testing*: Automated tests as well as Manual testing.
*Docs Changes*: Added docs to admin.rst
Fixes https://github.com/envoyproxy/envoy/issues/3210
=> stats: consistent output in stats endpoints

api/envoy/api/v2/listener/listener.proto, docs/root/configuration/listener_filters/tls_inspector.rst, docs/root/intro/version_history.rst, source/server/listener_manager_impl.cc, source/server/listener_manager_impl.h, test/server/listener_manager_impl_test.cc
*Docs Changes*: Added
*Release Notes*: Added
Fixes #3397.
=> listener: add support for filter chain selection based on ALPN.

source/extensions/filters/network/mongo_proxy/bson_impl.cc, test/extensions/filters/network/mongo_proxy/bson_impl_test.cc
=> mongo: add adding missing BSON decoding error checking

docs/root/configuration/http_filters/grpc_json_transcoder_filter.rst
#3456 
*Description*:
*Risk Level*: Low (docs only)
*Testing*: N/A
=> docs: transocder route config

api/envoy/api/v2/listener/listener.proto, source/server/listener_manager_impl.cc, test/server/listener_manager_impl_test.cc
=> listener: perform server name match against all wildcard domains.

source/common/stats/thread_local_store.cc, source/common/stats/thread_local_store.h, source/common/thread_local/thread_local_impl.cc, source/server/http/admin.cc, test/common/stats/thread_local_store_test.cc, test/common/thread_local/thread_local_impl_test.cc, test/integration/integration_admin_test.cc, test/integration/integration_admin_test.h
*Description*:
Handle main thread in merge, runOnAllthreads does not call it on main thread.
*Testing*: Automated
*Docs Changes*:NA
*Release Notes*:NA
=> stats:handle main thread in merge

api/envoy/api/v2/BUILD, api/envoy/api/v2/auth/BUILD, api/envoy/api/v2/cluster/BUILD, api/envoy/api/v2/core/BUILD, api/envoy/api/v2/endpoint/BUILD, api/envoy/api/v2/listener/BUILD, api/envoy/api/v2/ratelimit/BUILD, api/envoy/api/v2/route/BUILD, api/envoy/config/bootstrap/v2/BUILD, api/envoy/config/filter/accesslog/v2/BUILD, api/envoy/config/filter/http/health_check/v2/BUILD, api/envoy/config/filter/network/http_connection_manager/v2/BUILD, api/envoy/config/metrics/v2/BUILD, api/envoy/config/ratelimit/v2/BUILD, api/envoy/config/rbac/v2alpha/BUILD, api/envoy/config/trace/v2/BUILD, api/envoy/service/accesslog/v2/BUILD, api/envoy/service/auth/v2alpha/BUILD, api/envoy/service/discovery/v2/BUILD, api/envoy/service/load_stats/v2/BUILD, api/envoy/service/metrics/v2/BUILD, api/envoy/service/ratelimit/v2/BUILD, api/envoy/service/trace/v2/BUILD, api/envoy/type/BUILD, include/envoy/common/BUILD, test/config/BUILD, test/integration/BUILD, test/proto/BUILD, test/test_common/BUILD
=> build: sort load() arguments.

api/envoy/api/v2/auth/cert.proto
No functional changes, only API update.
=> secret: add CertificateValidationContext as a possible Secret.

api/envoy/config/grpc_credentials/v2alpha/file_based_metadata.proto
*Description*:
ran `tools/check_format.py fix` on master
*Testing*: existing tests / CI
=> fix proto format

OWNERS.md
*Testing*: via Prior PRs ;-)
*Docs Changes*: yep
=> owners: adding Lizan as an Envoy maintainer

api/envoy/api/v2/route/route.proto, include/envoy/router/router.h, source/common/http/utility.cc, source/common/http/utility.h, source/common/router/config_impl.cc, source/common/router/router.h, test/common/http/utility_test.cc, test/common/router/config_impl_test.cc, test/common/router/router_test.cc, test/integration/http2_integration_test.cc
*Testing*: new unit tests
*Docs Changes*:  config documented inline.
*Release Notes*: added in #3462
Fixed #3532
=> http: making routing cookies HttpOnly, allowing configured paths

include/envoy/network/address.h
*title*: Update Network::Address documentation to match implementations.
*Testing*: N/A
*Docs Changes*: Updated Network::Address documentation to indicate that the error details are returned in a platform specific manner.
*Release Notes*: N/!
>If this change is user impacting OR extension developer impacting (filter API, etc.) you **must**
>add a release note to [version_history.rst](docs/root/intro/version_history.rst). Please include
>any relevant links. Each release note should be prefixed with the relevant subsystem in
>alphabetical order (see existing examples as a guide) and include links to relevant parts of the
>documentation. Thank you! Please write in N/A if there are no release notes.
Fixes #3500.
=> Update Network::Address documentation to match implementations.

api/envoy/api/v2/auth/cert.proto, docs/root/intro/version_history.rst, source/common/ssl/context_impl.cc, source/common/ssl/context_impl.h, test/common/ssl/ssl_socket_test.cc
=> tls: allow verify_certificate_{spki,hash} without trusted_ca.

ci/build_setup.sh, ci/do_ci.sh
*Description*:
>In some environments, it doesn't work to try to pull from the network from docker. So don't try to do that in do_ci.sh during formatting.
*Testing*: check_format ...
=> util: No checkout code for format

api/envoy/config/grpc_credential/v2alpha/BUILD, ci/build_container/build_container_common.sh
*Description*:
Also ran `tool/check_format.py fix` to fix existing files.
*Testing*: existing tests / CI
=> format: update buildifier

test/server/options_impl_test.cc
Signed-off-by: Elisha Ziskind <eziskind@google.com>
=> Improve test coverage for server/options_impl.cc

source/common/grpc/google_async_client_impl.cc
This showed up in some internal tests.
=> grpc: fix TSAN race introduced in #3545.

source/common/event/dispatcher_impl.cc, test/common/event/dispatcher_impl_test.cc
Fixes #3644
*Testing*: New unit test.
=> event: fix deadlock around post()

docs/root/intro/version_history.rst
*Testing*: n/a
*Docs Changes*: release notes cleaned up.
=> docs: release note cleanup for 1.7

tools/deprecate_version/deprecate_version.py
=> tools: updating instructions for deprecation script

source/extensions/tracers/common/ot/opentracing_driver_impl.cc, test/extensions/tracers/common/ot/opentracing_driver_impl_test.cc
Signed-off-by: Gary Brown <gary@brownuk.com>
Resolves #3435 
*Description*:
Uses the config "operation name" (Egress/Ingress) to determine whether the OpenTracing span should have the `span.kind` tag of `server` or `client`.
The zipkin tracer has this logic, although it represents the span kind using CLIENT_SEND/RECV and SERVER_SEND/RECV annotations. This PR is just making the OpenTracing tracers have the same level of information, but using the OpenTracing standard `span.kind` tag.
*Testing*:
Additional unit tests have been provided.
@mburn Could you take a look at this, to make sure you are ok with the impact on LightStep and dynamic OT impl?
=> tracing: Set span.kind tag when creating client/server spans

ci/build_container/build_container_ubuntu.sh
It appears ubuntu updated gcc again
*Testing*: manual
*Release Notes*: n.an
=> ci: updating EXPECTED_CXX_VERSION

README.md
Fix #3762 Change unofficial Chinese doc link with the docs from https://github.com/servicemesher/envoy
@lizan @mattklein123
=> change unofficial Chinese doc with ServiceMesher

.github/stale.yml
=> Add new issue label "no stalebot" to be ignored by stalebot.

.gitattributes
See http://krlmlr.github.io/using-gitattributes-to-avoid-merge-conflicts/
*Risk Level*: Extra-low
*Testing*: Manually tested a conflicting merge
=> Auto-merge the version-history file.

source/extensions/filters/network/thrift_proxy/transport_impl.cc
*Description*: Add empty details to missed one in #3842 
*Testing*: `bazel test //test/...`
=> build: fix RELEASE_ASSERT missed in #3842

test/integration/ads_integration_test.cc, test/integration/http_integration.cc, test/integration/integration_test.cc
Fixing a whole bunch more flakes in integration_test, ads_integration_test and http2_integration_test.  Explanations inline in tests.
protip: if you run with 
bazel test [test] --jobs 60 --local_resources 100000000000,100000000000,10000000 --runs_per_test=1000 you can do a good job reproducing issues on the overloaded ipv6 and macos CI machines.
*Risk Level*: Low (test only)
*Testing*: Lots of  --runs_per_test=1000
=> test: fixing yet more flakes

test/server/listener_manager_impl_test.cc
*Description*: Follow-up #3968 fix typos
*Testing*: Autoamted
=> listener: fix typos

source/common/ssl/BUILD, source/common/ssl/context_impl.cc, test/common/ssl/context_impl_test.cc
*Testing*: Unit test modified
*Docs Changes*: None
*Release Notes*: None
=> Add more information to errors about rejected cipher suite configuration.

OWNERS.md
=> owners: add Dhi as maintainer

.github/stale.yml
*Description*:
*Testing*: no code change
=> bot: exempt label "no stalebot" for PRs

docs/root/configuration/cluster_manager/cluster_stats.rst, docs/root/configuration/http_conn_man/stats.rst, docs/root/intro/version_history.rst, include/envoy/upstream/upstream.h, source/common/http/codes.cc, source/common/http/conn_manager_config.h, source/common/http/conn_manager_impl.cc, test/common/http/codes_test.cc, test/common/http/conn_manager_impl_test.cc
*Description*: add counters for total completed requests regardless of status code
*Testing*: added relevant in unit tests
*Docs Changes*: none
*Release Notes*: added one
cc @btc
=> HttpConnectionManager and upstream counters for total completed requests

test/common/access_log/BUILD, test/common/access_log/access_log_formatter_corpus/response_code, test/common/access_log/access_log_formatter_fuzz.proto, test/common/access_log/test_util.h, test/common/router/BUILD, test/common/router/header_parser_corpus/address_0, test/common/router/header_parser_corpus/address_1, test/common/router/header_parser_corpus/address_2, test/common/router/header_parser_corpus/compound_headers, test/common/router/header_parser_corpus/invalid_0, test/common/router/header_parser_corpus/invalid_1, test/common/router/header_parser_corpus/invalid_2, test/common/router/header_parser_corpus/invalid_3, test/common/router/header_parser_corpus/invalid_4, test/common/router/header_parser_corpus/invalid_5, test/common/router/header_parser_corpus/invalid_6, test/common/router/header_parser_corpus/invalid_7, test/common/router/header_parser_corpus/invalid_8, test/common/router/header_parser_corpus/protocol, test/common/router/header_parser_corpus/start_time, test/common/router/header_parser_corpus/upstream_metadata_0, test/common/router/header_parser_corpus/upstream_metadata_1, test/common/router/header_parser_fuzz.proto, test/common/router/header_parser_fuzz_test.cc, test/fuzz/BUILD, test/fuzz/common.proto, test/fuzz/utility.h
Testing: corpus has 82.3% test coverage for header_formatter.cc and 82.5% for header_parser.cc
=> fuzz: router header formatter/parser fuzz test.

bazel/repositories.bzl, configs/envoy_front_proxy_v2.template.yaml, configs/envoy_service_to_service_v2.template.yaml
Fixes example_configs_test by updating example configs to match
latest API changes.
*Testing*: unit tests
*Docs Changes*: examples themsleves are now correct
Signed-off-by: Stephan Zuercher <stephan@turbinelabs.io>
=> configs: match latest API changes

source/server/configuration_impl.cc
=> config: print "loading XXX cluster(s)" during initialization.

bazel/repository_locations.bzl
This gives us working --test_filter and general improvements.
=> build: bump googletest version.

api/envoy/api/v2/route/route.proto
Signed-off-by: Daniel Hochman <danielhochman@users.noreply.github.com>
=> docs: remove reference to deprecated value field

bazel/repository_locations.bzl
=> tls: update BoringSSL to ab36a84b (3497).

docs/root/intro/arch_overview/websocket.rst
=> docs: fix links in websocket documentation.

restarter/hot-restarter.py
*Description*: 2020 is just around the corner!  This adds python3 support for `hot-restarter.py` without removing python2 support.
*Risk Level*: Low, mostly just syntax changes and appeasing a linter.
*Testing*: Ran both python2 and python3 invocations of the hot-restarted, issued some `kill -SIGHUP` and watched no change in behaviour.
=> hot-restarter.py: python3 support

.circleci/config.yml, ci/build_setup.sh, tools/bazel.rc
*Description*:
Use lld in clang builds (ASAN/TSAN) #4170 
*Risk Level*: Low (not in release)
*Testing*: ci
=> ci: use lld in clang builds

source/common/upstream/eds.cc
*Description*: Updates an incorrect comment
*Testing*: n/a
=> upstream: update incorrect comment

docs/root/configuration/overview/v2_overview.rst
*Description*: Fixes minor config in overview examples
*Testing*: N/A
=> docs: fix config in overview example

DEVELOPER.md, test/README.md
*Description*: Adds test/README.md, with a description of matchers.
*Risk Level*: Low (docs only)
*Testing*: n/a (docs only)
*Docs Changes*: Adds test/README.md, with a description of matchers.
Fixes #4389
=> docs: Write a test README to describe matchers.

CODEOWNERS, OWNERS.md
*Description*:
*Risk Level*:
*Testing*: N/A
=> Update contact and CODEOWNERS

docs/root/intro/version_history.rst
*Description*: Minor link issue in version history
*Testing*: Low
=> docs: fix sds link in version history

docs/root/configuration/overview/v2_overview.rst
=> fix dead link

DEPRECATED.md, api/envoy/api/v2/core/BUILD, api/envoy/api/v2/core/base.proto, api/envoy/api/v2/route/route.proto, source/common/access_log/access_log_impl.cc, source/common/protobuf/utility.cc, source/common/protobuf/utility.h, source/common/router/config_impl.cc, source/common/router/config_impl.h, source/extensions/filters/http/fault/fault_filter.cc, source/extensions/filters/network/mongo_proxy/proxy.cc, test/common/router/config_impl_test.cc
This patch reintroduces PR #4217.
=> route match: Add runtime_fraction field for more granular routing

docs/root/configuration/http_filters/router_filter.rst
Noted while skimming through #4536.
=> docs: Fix typo

ci/build_container/build_container_ubuntu.sh
*Description*:
Needed by #4666
*Testing*: CI
=> ci: install clang-tidy in build image

source/common/network/connection_impl.h, test/integration/BUILD, test/integration/filters/BUILD, test/integration/filters/pause_filter.cc, test/integration/filters/random_pause_filter.cc, test/integration/http2_upstream_integration_test.cc
*Risk Level*: n/a (test only)
*Testing*: 5k runs cleanly
=> test: adding one more watermark test

test/common/http/conn_manager_impl_test.cc
Signed-off-by: Auni Ahsan <auni@google.com>
*Description*: bring into compliance with english language
*Risk Level*: low risk
=> conn man test: Correct typo in sendReqestHeadersAndData

bazel/README.md
Signed-off-by: Elisha Ziskind <eziskind@google.com>
=> doc: add comment about getting symbolized asan backtraces

DEVELOPER.md
Signed-off-by: tianqian.zyf <tianqian.zyf@alibaba-inc.com>
*Description*: fix dead link
*Testing*: N/A
*Docs Changes*: y
=> docs: fix dead link

source/common/upstream/outlier_detection_impl.cc, test/common/upstream/outlier_detection_impl_test.cc, test/server/server_corpus/clusterfuzz-testcase-minimized-server_fuzz_test-5690948441341952
Fixes oss-fuzz issue https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10812.
Testing: Unit test and corpus entry added.
=> outlier_detection: fix divide-by-zero in success rate processing.

bazel/repository_locations.bzl
=> tls: update BoringSSL to 060e9a58 (3538).

source/extensions/extensions_build_config.bzl, source/extensions/filters/network/dubbo_proxy/BUILD, source/extensions/filters/network/dubbo_proxy/dubbo_protocol_impl.cc, source/extensions/filters/network/dubbo_proxy/dubbo_protocol_impl.h, source/extensions/filters/network/dubbo_proxy/protocol.h, test/extensions/filters/network/dubbo_proxy/BUILD, test/extensions/filters/network/dubbo_proxy/dubbo_protocol_impl_test.cc, test/extensions/filters/network/dubbo_proxy/mocks.cc, test/extensions/filters/network/dubbo_proxy/mocks.h, test/extensions/filters/network/dubbo_proxy/utility.h
Signed-off-by: tianqian.zyf <tianqian.zyf@alibaba-inc.com>
*Description*: Add decoder for dubbo protocol
*Testing*: unittests
[Optional Fixes #Issue] #3998 #4200 
=> dubbo_proxy: Add decoder for dubbo protocol

CONTRIBUTING.md, api/STYLE.md
=> api: clarify feature deprecation and replacement policy for protos.

DEVELOPER.md, STYLE.md, ci/README.md, ci/build_container/docker_push.sh, ci/coverage_publish.sh, ci/docker_push.sh, ci/docker_tag.sh
=> ci/docs: update references to travis to CircleCI

test/config/utility.cc, test/config/utility.h, test/integration/ssl_utility.cc
Moving ssl initialization to a test util
*Risk Level*: low (test only refactor)
*Testing*: existing tests pass
=> test: minor test cleanup

docs/requirements.txt, docs/root/intro/arch_overview/websocket.rst
=> docs: upgrade sphinx/theme and small nesting fix

repokitteh.sky
*Description*: 
Brings in repokitteh's assign module. This allows organization members to assign and unassign issues and PRs by using comments.
Examples:
```
/assign @htuch 
/unassign @mattklein123
/assign
/unassign
```
*Risk Level*:
Low.
*Testing*:
Tested on envoybot, see https://github.com/envoyproxy/envoybot/pull/3.
Please advise regarding developer documentation. 
*Release Notes*: 
None.
=> bring in repokitteh's assign module

tools/check_format.py
*Description*:
Before this change, `check_format.py fix` was crashing infinitely
when external tools like clang-format-7 or buildifier were not
available. After this change, the script looks up for those tools
and shows an error if they are unavailable. Error messages contain
instructions how to use CLANG_FORMAT and BUILDIFIER_BIN env
variables and how to install buildifier.
*Testing*: n/a
*Fixes*: #4786
Signed-off-by: Michal Rostecki <mrostecki@suse.de>
=> tools: Check for external tools needed in check_format.py

test/test_common/simulated_time_system.cc
*Description*:
Found by clang-tidy.
*Testing*: CI
=> tidy: fix ASSERT with side-effect

PULL_REQUEST_TEMPLATE.md
*Description*: Link to [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md) in the pull request template for easier discoverability.
*Testing*: N/A
=> docs: link to the pull request rules in the pull request template

repokitteh.sky
*Description*:
Bring in the review module, allows to:
```
/review @htuch 
/unreview @htuch
/unreview
```
*Risk Level*:
Low
*Testing*:
See below in this PR (how cool is that?!)
Docs to be added soon.
None
=> repokitteh: bring in review module

tools/check_format_test_helper.py
*Description*:
Add a test which temporarily changes PATH to get an error about
clang-format-7 being not available, then expects that error.
This is a followup to #4788.
*Testing*: new checker test
Signed-off-by: Michal Rostecki <mrostecki@suse.de>
=> tools: Test for external tools in check_format_test_helper.py

test/common/stats/thread_local_store_test.cc
Signed-off-by: Joshua Marantz <jmarantz@google.com>
*Description*: By default ThreadLocalStore creates a tag producer that does not have any tag-patterns, so we weren't computing any tags. This updates the memory tests so tag extraction is measured.
*Testing*: just this test
=> stats Initialize the tag producer so we count tag extraction in the stats memory unit test

source/docs/repokitteh.md
*Description*:
Add documentation for RepoKitteh functionality.
*Risk Level*:
None.
*Testing*:
None.
This file.
None.
=> repokitteh documentation

tools/find_related_envoy_files.py
*Description*: there are a few patterns of related files previously missed by this script, such as test utility helper classes, and their headers and tests.
*Testing*: manually tested with simulated_time_system .cc .h _test.cc and some integration test infra
=> util: Capture a few extra patterns of related files seen in test directories.

source/common/config/grpc_mux_impl.cc, test/common/config/grpc_mux_impl_test.cc
=> config: fix minor typo in error message

repokitteh.star, source/docs/repokitteh.md
*Description*:
Bring in `/wait' command - see inside for doc changes.
*Risk Level*:
None.
*Testing*:
See this PR.
See inside.
None
=> reokitteh: bring in wait module

.gitignore, docs/build.sh, tools/deprecate_version/deprecate_version.sh, tools/shell_utils.sh
*Description*: Add a check for existing active virtualenvs to shell scripts. This allows for users to create their own workspace for us to utilize.
*Testing*: Manual runs
=> add check for active venv to shell scripts

source/common/router/router.cc, source/common/router/router.h
=> router: cleanup unused variable

source/extensions/filters/network/thrift_proxy/twitter_protocol_impl.cc
*Description*: Minor nit found with cppcheck.
*Testing*: N/A
=> lint: use initializer list for constructor

source/extensions/tracers/zipkin/zipkin_core_constants.h, source/extensions/tracers/zipkin/zipkin_tracer_impl.cc, test/extensions/tracers/zipkin/zipkin_tracer_impl_test.cc
Signed-off-by: tianqian.zyf <tianqian.zyf@alibaba-inc.com>
*Description*: b3 headers are duplicated
*Risk Level*: lower
*Testing*: Manual testing
[Optional Fixes #Issue] #5017
=> tracing: Fix duplicated x-b3-* header

repokitteh.star
*Description*:
Bring in repokitteh's circleci module. This will allow people to `/retest` their change in CI.
*Risk Level*:
Low.
*Testing*:
See this PR.
Upcoming PR.
None.
=> bring in circleci module

repokitteh.star, source/docs/repokitteh.md
*Description*:
Documentation for `/retest` and a demo PR.
*Risk Level*:
None.
*Testing*:
None.
Repokitteh documentation.
None
=> repokitteh: document retest

test/exe/main_common_test.cc
Signed-off-by: Takanori Ishibashi <takanori.1112@gmail.com>
*Description*: Ensurees -> Ensure
=> main_common_test.cc: fix typo 

source/exe/main_common.cc
Signed-off-by: Takanori Ishibashi <takanori.1112@gmail.com>
*Description*: remove unreachable code
=> remove unreachable code

source/extensions/retry/priority/previous_priorities/previous_priorities.cc
Signed-off-by: Takanori Ishibashi <takanori.1112@gmail.com>
*Description*: priorites -> priorities 
=> previous_priorities.cc: fix typo 

source/common/common/block_memory_hash_set.h
Signed-off-by: Takanori Ishibashi <takanori.1112@gmail.com>
*Description*: comtrolling -> controlling
=> block_memory_hash_set.h: fix typo

docs/root/configuration/listener_filters/proxy_protocol.rst, docs/root/configuration/listener_filters/tls_inspector.rst, docs/root/configuration/thrift_filters/rate_limit_filter.rst, docs/root/configuration/thrift_filters/router_filter.rst
*Description*: Add thrift filter names in the docs.
*Testing*: N/A
=> docs: add thrift filter names

test/integration/integration_test.cc
*Risk Level*: n/a (test only)
*Testing*: now testing 100 continue with via
=> test: fixing a test bug

OWNERS.md
*Description*:
I've switched projects at Lyft and no longer have the bandwidth to maintain Envoy. It has been quite the ride(or check ins you could say :) ).
*Risk Level*: N/A
*Testing*: N/A
=> Graduating to Emeritus

test/common/ssl/ssl_socket_test.cc, test/config/integration/certs/BUILD
=> test: some fixes for Google import.

docs/root/intro/version_history.rst
=> tls: add support for client-side session resumption (relnotes).

test/server/listener_manager_impl_test.cc
Merge of stale #4682 caused this.
=> build: fix broken master.

api/envoy/api/v2/cds.proto
*Description*: Update merge window docs to indicate that it is enabled by default.
*Testing*: N/A
=> docs: fix merge window docs

docs/root/start/sandboxes/front_proxy.rst
*Description*: Fix step numbers in the front proxy sandbox docs
*Testing*: N/A
*Docs Changes*: Fix step numbers in the front proxy sandbox docs
=> docs: fix step numbers in front proxy sandbox

OWNERS.md
Hurray! @jmarantz has agreed to join us as a maintainer! :tada: 
@envoyproxy/maintainers
=> owners: add jmarantz

docs/root/intro/arch_overview/circuit_breaking.rst
*Description*: Specifies the stat that is incremented when connection circuit breaker overflows.
=> docs: minor circuit breaker doc improvements

bazel/repository_locations.bzl
=> tls: update BoringSSL to 77e47de9 (3578).

docs/root/configuration/http_conn_man/headers.rst
*Description*: Fixes a broken link in header docs
=> docs: fix link http header docs

source/common/upstream/cluster_manager_impl.cc, source/common/upstream/eds.cc
*Description*: While debugging #5168 , added some additional debug info in logs locally. Thought would be generally useful so adding that PR.
*Testing*: N/A
=> upstream: add debug logs

OWNERS.md
Update my email address in OWNERS.md
Signed-off-by: Stephan Zuercher <szuercher@slack-corp.com>
=> owners: fix email

test/common/grpc/grpc_client_integration_test_harness.h
=> test: fix build with google_grpc=disabled.

WORKSPACE, ci/WORKSPACE, tools/check_format.py
=> format: run buildifier on WORKSPACE files.

ci/run_clang_tidy.sh
*Description*:
Try to figure out what is the cause for #5144.
*Testing*: CI
=> ci: debug clang-tidy runs

docs/root/faq/overview.rst, docs/root/faq/rolling_upgrades.rst
*Description*: Added a FAQ entry on how to configure Envoy for rolling upgrade scenarios.
*Testing*: N/A
=> docs: rolling upgrade faq

.circleci/config.yml, source/extensions/filters/common/lua/lua.h
=> build: fix lua compile and switch to 2.1 in CI

docs/root/faq/overview.rst, docs/root/faq/transient_failures.rst
*Description*: Address review comments in #5252 
*Testing*: N/A
=> docs: address review comments

api/envoy/config/filter/network/dubbo_proxy/v2alpha1/dubbo_proxy.proto
*Description*: Fix typo in dubbo proxy proto comment.
*Testing*: N/A
Signed-off-by: Dhi Aurrahman <dio@tetrate.io>
=> Fix typo: Dubbo instead of Thrift

ci/build_container/build_container_ubuntu.sh
=> ci: update expectd g++ version

docs/root/configuration/listeners/stats.rst, docs/root/intro/version_history.rst, source/common/ssl/context_impl.cc, test/common/ssl/ssl_socket_test.cc
=> tls: add ssl.curves and ssl.sigalgs to tracked TLS stats.

.circleci/config.yml, ci/README.md, ci/do_ci.sh
*Testing*: Ran this build with a source change that broke the non-grpc build; verified build failed.
=> Add CI variant to test the build with various compile-time flags toggled

bazel/BUILD
=> ci: fix build with BoringSSL FIPS.

docs/root/intro/version_history.rst, source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.cc, test/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter_test.cc
Fixes #5328 
*Testing*: unit test
=> grpc_http1_bridge: support content-type application/grpc+proto

include/envoy/http/filter.h
*Description*: Updates filter docs with additional return value from decodeHeaders
*Testing*: None
*Docs Changes*: doc comments in filter.h
*Release Notes*: Update filter docs with additional return value from decodeHeaders
=> Include StopIterationAndWatermark in StreamDecoderFilterCallbacks doc

include/envoy/stream_info/stream_info.h
Signed-off-by: Dhi Aurrahman <dio@tetrate.io>
*Testing*: N/A
=> Fix typo s/bye/byte

source/extensions/filters/network/dubbo_proxy/BUILD, source/extensions/filters/network/dubbo_proxy/deserializer.h, source/extensions/filters/network/dubbo_proxy/filter.cc, source/extensions/filters/network/dubbo_proxy/filter.h, source/extensions/filters/network/dubbo_proxy/hessian_deserializer_impl.cc, source/extensions/filters/network/dubbo_proxy/hessian_deserializer_impl.h, source/extensions/filters/network/dubbo_proxy/message.h, source/extensions/filters/network/dubbo_proxy/protocol.h, test/extensions/filters/network/dubbo_proxy/hessian_deserializer_impl_test.cc
*Description*: Add NamedDeserializerConfigFactory definition
*Testing*: unit test
this is only part of the code for DubboProxy, the rest of the code hasn't been committed yet, complete implementation: https://github.com/gengleilei/envoy/tree/feature-dubbo-router-develop/source/extensions/filters/network/dubbo_proxy
=> dubbo_proxy : Add NamedDeserializerConfigFactory definition

docs/root/configuration/listener_filters/proxy_protocol.rst
*Description*: Proxy protocol stats are not documented. This PR adds that documentation
*Testing*: N/A
=> docs: proxy protocol stats docs

docs/root/configuration/http_filters/rate_limit_filter.rst, docs/root/configuration/listener_filters/tls_inspector.rst
*Description*: Fixes minor doc issues
*Testing*: N/A
=> docs: minor doc corrections

GOVERNANCE.md
*Testing*: n/a
*Docs Changes*: yep
=> docs: extending release instructions

bazel/external/BUILD, bazel/external/apache_thrift.BUILD, bazel/external/backward.BUILD, bazel/external/boringssl_fips.BUILD, bazel/external/fmtlib.BUILD, bazel/external/gcovr.BUILD, bazel/external/http-parser.BUILD, bazel/external/jinja.BUILD, bazel/external/libcircllhist.BUILD, bazel/external/libprotobuf_mutator.BUILD, bazel/external/markupsafe.BUILD, bazel/external/rapidjson.BUILD, bazel/external/spdlog.BUILD, bazel/external/tclap.BUILD, bazel/external/twitter_common_finagle_thrift.BUILD, bazel/external/twitter_common_lang.BUILD, bazel/external/twitter_common_rpc.BUILD, bazel/external/xxhash.BUILD, tools/check_format.py, tools/envoy_build_fixer.py
=> format: run buildifier on BUILD files for external deps.

tools/check_format.py
=> format: add newline before printing command to execute.

CONTRIBUTING.md
=> Contributing: document hosting requirements for design docs

examples/cors/backend/Dockerfile-service, examples/cors/frontend/Dockerfile-service, examples/front-proxy/Dockerfile-service
Signed-off-by: Derek Schaller <dschaller@lyft.com>
*Description*: Remove unnecessary layer from dockerfile that print docker and pip version.
*Testing*: Manually built & started container.
=> examples: remove unnecessary docker layer from examples

docs/root/start/start.rst, examples/redis/Dockerfile-proxy, examples/redis/Dockerfile-redis, examples/redis/README.md, examples/redis/docker-compose.yaml, examples/redis/envoy.yaml
*Description*: Adds an example on how to configure redis filter
*Testing*: N/A
Fixes #5276
=> examples: add redis example

examples/cors/backend/front-envoy.yaml
Signed-off-by: Derek Schaller <dschaller@lyft.com>
*Description*: Update CORS examples for new enabled and shadow enabled fields.
*Testing*: Manually tested the sandbox
=> examples: udpate CORS for enabled/shadow enabled fields

OWNERS.md, api/XDS_PROTOCOL.md, bazel/BUILD, bazel/README.md, bazel/envoy_build_system.bzl, ci/README.md, ci/build_container/build_recipes/cares.sh, ci/mac_ci_setup.sh, source/common/common/thread_annotations.h, source/common/network/connection_impl.cc, source/common/network/socket_option_impl.h, source/common/network/utility.cc, test/common/network/connection_impl_test.cc, test/common/ssl/test_data/README.md, test/common/ssl/test_data/certs.sh, test/common/stream_info/test_util.h, test/config_test/example_configs_test.cc, test/fuzz/utility.h, test/integration/echo_integration_test.cc, test/integration/http_integration.cc, test/integration/ssl_integration_test.cc, test/test_common/utility.h
=> It's macOS.

.circleci/config.yml, bazel/external/apache_thrift.BUILD, bazel/external/http-parser.BUILD, bazel/external/libcircllhist.BUILD, bazel/external/libprotobuf_mutator.BUILD, bazel/external/twitter_common_rpc.BUILD, ci/build_setup.sh
=> build: fix clang-tidy with Bazel-0.21.

test/exe/BUILD, test/exe/version_out_test.sh
=> test: more strict test for the --version output.

test/test_common/environment.cc
=> test: fix nullptr dereference.

test/exe/main_common_test.cc
=> test: properly name the new Death Test.

ci/build_container/build_container_ubuntu.sh
=> ci: install libc++ in the Ubuntu build image.

docs/root/operations/cli.rst
*Description*: Add pointer to valid arguments to `--component-log-level` in docs
*Risk Level*:  Minimal
*Testing*: None
*Docs Changes*: See description
=> docs: add pointer to valid components in docs

bazel/envoy_build_system.bzl, test/exe/BUILD, test/exe/build_id_test.sh, test/exe/envoy_static_test.sh, test/exe/version_out_test.sh
=> test: respect $TEST_RUNDIR in test/exe tests.

docs/root/intro/arch_overview/health_checking.rst
*Risk Level*: Low, docs only
*Testing*: n/a
=> docs: fix references in health checking docs

docs/conf.py
=> docs: fix copyright current year

ci/run_envoy_docker.sh
*Description*:
Fix of #5572 that breaks people.
*Risk Level*: 
*Testing*: local (this time for sure...)
=> fix ci/run_envoy_docker.sh

.bazelrc
*Description*:
Options to run ASAN/UBSAN on macOS.
https://github.com/envoyproxy/envoy/issues/5551#issuecomment-452896953
*Testing*: local
=> build: add macos-asan in .bazelrc

bazel/README.md
Signed-off-by: zyfjeff <tianqian.zyf@alibaba-inc.com>
*Description*: fix spelling mistakes
*Testing*: N/A
*Docs Changes*: fix spelling mistakes
=> doc: Fix spelling mistakes

ci/build_container/build_container_ubuntu.sh
As suggested at https://github.com/envoyproxy/envoy/pull/5636#issuecomment-455290284  @lizan What other modifications are required to complete stage 1?
*Description*:
*Risk Level*:
*Testing*:
=> Add Python 3 and pip3 to build_container_ubuntu.sh

.circleci/config.yml, tools/check_format.py, tools/check_format_test_helper.py, tools/format_python_tools.py, tools/format_python_tools.sh
This reverts commit 5a7bf7c3d7fc8d0af017e78c6ed81cb1481ce763.
=> Revert "CI: Run remaining format tests on Python 3 (#5714)"

tools/format_python_tools.sh
Fixes https://github.com/envoyproxy/envoy/issues/5726
=> tools: always use venv for python format check

docs/root/configuration/cluster_manager/cluster_manager.rst, docs/root/configuration/cluster_manager/overview.rst, docs/root/configuration/http_conn_man/http_conn_man.rst, docs/root/configuration/http_conn_man/overview.rst, docs/root/configuration/listeners/listeners.rst, docs/root/configuration/listeners/overview.rst, docs/root/install/ref_configs.rst, docs/root/intro/version_history.rst
A few misc doc fixes. The main thing I did here is remove hidden toctrees, because personally I think it makes the docs more confusing to view if reading in order and without the sidebar.
=> docs: misc fixes

bazel/repository_locations.bzl
=> tls: update BoringSSL to a7d9ef75 (3626).

source/server/config_validation/server.h, source/server/server.h, test/server/server_corpus/clusterfuzz-testcase-minimized-config_fuzz_test-5762646786179072
Same issue as in #4940, but on the config_validation side.
Testing: corpus entry added.
=> config_validation: fix heap-use-after-free.

bazel/PPROF.md
*Description*: Updated profiling docs with instructions for profiling tests
*Testing*:
=> Updated memory profiling docs with instructions for tests

source/server/overload_manager_impl.cc
a tiny change: concat statsname with a constant dot.
and fix some typo errors
=> small change: refactor StatsName

tools/check_spelling_pedantic.py
tool -> tools and adding the dictionary file since we have two
*Risk Level*: n/a (tools only)
*Testing*: manual
=> tools: tweaking the failure message in check_spelling_pedantic

.bazelrc, ci/build_setup.sh, docs/root/intro/version_history.rst
*Description*:
Fixes #4170 
*Testing*: CI
*Release Notes*: Added
=> ci: use lld for release

test/mocks/upstream/mocks.h, tools/spelling_dictionary.txt
=> fix master format check

docs/root/configuration/overview/v2_overview.rst
Although it is spelling mistakes, it might make an affects while reading.
*Description*: Fix some minor typos
*Testing*: N/A
*Docs Changes*: updated v2_overview.rst
=> Trivial Fix: Fix some typos

docs/root/intro/version_history.rst
*Description*: Minor reorder of version history
*Testing*: N/A
=> docs: reorder version history

GOVERNANCE.md
*Testing*: manual testing
*Docs Changes*: yep!
*Release Notes*: nope.
=> governance: moving from pagerduty to opsgenie

test/fuzz/BUILD, test/fuzz/fuzz_runner.cc
=> fuzz: don't spam with nghttp2 tracing when non-opt.

api/XDS_PROTOCOL.md, bazel/README.md, docs/root/configuration/secret.rst, docs/root/intro/arch_overview/load_balancing/locality_weight.rst, docs/root/intro/arch_overview/load_balancing/overview.rst, docs/root/intro/arch_overview/load_balancing/panic_threshold.rst, source/docs/stats.md
Corect some words for reading more easily
Signed-off-by: Nguyen Quang Huy <huynq0911@gmail.com>
*Description*: Fix some minor typos
*Risk Level*:  Low
*Testing*: N/A
*Docs Changes*: 
- api/XDS_PROTOCOL.md
- bazel/README.md
- docs/root/configuration/secret.rst
- docs/root/intro/arch_overview/load_balancing/locality_weight.rst
- docs/root/intro/arch_overview/load_balancing/overview.rst
- docs/root/intro/arch_overview/load_balancing/panic_threshold.rst
- source/docs/stats.md
=> Fix some typos

ci/mac_ci_steps.sh
*Description*:
*Risk Level*:
*Testing*:
=> mac: collect disk space information during ci

source/docs/stats.md
*Description*: replace `binary` with `binary program`
*Risk Level*:
*Testing*:
=> replace `binary` with `binary program`

bazel/DEVELOPER.md
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
*Description*:
*Risk Level*:
*Testing*:
=> trivial fix typo

test/test_runner.h
This commit aims to update the deprecated link to the working one.
Co-Authored-By: Nguyen Phuong An <AnNP@vn.fujitsu.com>
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
*Description*: Update deprecated link
*Risk Level*: LOW
*Testing*: N/A
=> Update deprecated link

docs/root/configuration/cluster_manager/cds.rst, docs/root/configuration/listeners/lds.rst, docs/root/configuration/overview/v2_overview.rst, docs/root/configuration/secret.rst, docs/root/intro/arch_overview/load_balancing/locality_weight.rst, docs/root/intro/arch_overview/load_balancing/original_dst.rst, docs/root/intro/arch_overview/load_balancing/overview.rst, docs/root/intro/arch_overview/load_balancing/panic_threshold.rst, docs/root/intro/arch_overview/websocket.rst, docs/root/intro/version_history.rst, docs/root/operations/admin.rst
This PR fixes many typos in docs.
=> Fixing many typos in docs

CONTRIBUTING.md, README.md, api/CONTRIBUTING.md, docs/root/configuration/access_log.rst, docs/root/configuration/http_filters/lua_filter.rst, docs/root/configuration/listener_filters/proxy_protocol.rst, docs/root/install/ref_configs.rst, docs/root/intro/arch_overview/grpc.rst, docs/root/intro/arch_overview/load_balancing/load_balancers.rst, docs/root/intro/arch_overview/tracing.rst, docs/root/intro/comparison.rst, docs/root/intro/what_is_envoy.rst, docs/root/start/sandboxes/cors.rst, docs/root/start/sandboxes/jaeger_native_tracing.rst, docs/root/start/sandboxes/jaeger_tracing.rst, docs/root/start/sandboxes/zipkin_tracing.rst
*Description*:  Fix http link to https link for secure.
*Testing*:
=> Change http to https for security links

api/envoy/api/v2/auth/cert.proto
Co-Authored-By: Nguyen Phuong An <AnNP@vn.fujitsu.com>
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
*Description*: Fix a wrong URL
*Risk Level*: LOW
*Testing*: N/A
=> Fix a wrong URL

test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc, test/extensions/filters/network/mysql_proxy/mysql_test_config.yaml
*Risk Level*: n/a (test only)
*Testing*: 1k runs pass cleanly
Fixes #6051
=> test: deflaking mysql_integration_test

api/envoy/api/v2/route/route.proto, api/envoy/config/filter/http/ext_authz/v2/ext_authz.proto, source/common/buffer/buffer_impl.cc, source/common/stats/symbol_table_impl.cc, source/extensions/filters/http/squash/squash_filter.h, test/test_common/global.h, test/test_common/simulated_time_system.h
*Description*:  Correct spelling for code comment.
*Testing*:  N/A
- api/envoy/api/v2/route/route.proto
- api/envoy/config/filter/http/ext_authz/v2/ext_authz.proto
- source/common/buffer/buffer_impl.cc
- source/common/stats/symbol_table_impl.cc
- source/extensions/filters/http/squash/squash_filter.h
- test/test_common/global.h
- test/test_common/simulated_time_system.h
*Release Notes*:  N/A
Co-Authored-By: Nguyen Van Trung [trungnvfet@outlook.com](mailto:trungnvfet@outlook.com)
Signed-off-by: Nguyen Quang Huy [huynq0911@gmail.com](mailto:huynq0911@gmail.com)
=> Remove some duplicated words

.gitignore
Ignore folder .idea/ when open project Envoy with
IntelliJ IDEA.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
*Description*:
*Risk Level*:
*Testing*:
=> Insert .idea/ in file .gitignore

PULL_REQUEST_TEMPLATE.md
Removing the rich formatting because it's annoying for maintainers to clean up before merge.
=> docs: updating the pull request template

api/envoy/admin/v2alpha/memory.proto, api/envoy/api/v2/route/route.proto, api/envoy/config/trace/v2/trace.proto, api/envoy/type/http_status.proto, api/envoy/type/matcher/string.proto, bazel/README.md, bazel/envoy_build_system.bzl, bazel/external/boringssl_fips.genrule_cmd, tools/protodoc/protodoc.py
This PR replaces deprecated HTTP links by HTTPS links for security and consistency.
=> Update deprecated links

bazel/external/quiche.BUILD, source/extensions/quic_listeners/quiche/platform/BUILD, source/extensions/quic_listeners/quiche/platform/quic_singleton_impl.h
Description: Add QuicSingletonImpl.
Risk Level:
Testing: import external test quic_singleton_test.cc into @com_googlesource_quiche//:quic_platform_test and tested it with --test_output=all --define quiche=enabled --experimental_remap_main_repo.
Part of #2557
=> Implement QuicSingleton

docs/root/faq/configure_flow_control.rst, docs/root/faq/overview.rst, source/docs/flow_control.md
=> docs: improving flow control docs

ci/do_coverity_local.sh
The link in do_coverity_local.sh is not correct so I fix it.
=> Update link in do_coverity_local.sh

bazel/README.md
=> bazel: add note about running sanitizers on os x

api/envoy/data/tap/v2alpha/http.proto, api/envoy/data/tap/v2alpha/transport.proto, api/envoy/data/tap/v2alpha/wrapper.proto, docs/root/operations/traffic_tapping.rst, source/extensions/common/tap/tap_config_base.cc, source/extensions/transport_sockets/tap/tap_config.h, source/extensions/transport_sockets/tap/tap_config_impl.cc, source/extensions/transport_sockets/tap/tap_config_impl.h, test/extensions/common/tap/BUILD, test/extensions/common/tap/common.cc, test/extensions/common/tap/common.h, test/extensions/common/tap/tap_config_base_test.cc, test/extensions/filters/http/tap/tap_config_impl_test.cc, test/extensions/transport_sockets/tap/BUILD, test/extensions/transport_sockets/tap/tap_config_impl_test.cc, test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc
Risk Level: Medium for existing tap transport users, none for anyone else
Testing: New UTs
Fixes #6127
=> tap: implement streaming tap for the transport socket

tools/print_dependencies.py
Description:
Allows you to print the external dependencies for a bazel target
Risk Level: 
Low
Testing:
Ran the following bash script
```bash
./tools/print_deps_for_target.sh //source/exe:envoy
```
=> Update script to print external dependencies for a target

source/common/runtime/runtime_impl.cc, test/common/config/grpc_mux_impl_test.cc, test/common/runtime/runtime_impl_test.cc, test/server/guarddog_impl_test.cc
This PR fixes various typos in test code.
=> test: fix typos in test code

ci/build_container/Dockerfile-centos, ci/build_container/build_container_centos.sh, ci/build_container/docker_push.sh, ci/build_setup.sh
*Description*:
For #5742 
*Risk Level*:
*Testing*:
=> build: CentOS build image

ci/build_container/Dockerfile-centos
Description:
Fixes merge race with #6049.
Testing:
Docs Changes:
Release Notes:
=> fix CentOS image build

source/extensions/filters/network/common/redis/BUILD, source/extensions/filters/network/common/redis/codec.h, source/extensions/filters/network/common/redis/codec_impl.cc, source/extensions/filters/network/common/redis/codec_impl.h, source/extensions/filters/network/common/redis/supported_commands.h, source/extensions/filters/network/redis_proxy/BUILD, source/extensions/filters/network/redis_proxy/command_splitter.h, source/extensions/filters/network/redis_proxy/command_splitter_impl.cc, source/extensions/filters/network/redis_proxy/command_splitter_impl.h, source/extensions/filters/network/redis_proxy/config.cc, source/extensions/filters/network/redis_proxy/conn_pool.h, source/extensions/filters/network/redis_proxy/conn_pool_impl.cc, source/extensions/filters/network/redis_proxy/conn_pool_impl.h, source/extensions/filters/network/redis_proxy/proxy_filter.cc, source/extensions/filters/network/redis_proxy/proxy_filter.h, source/extensions/health_checkers/redis/redis.cc, source/extensions/health_checkers/redis/redis.h, test/extensions/filters/network/common/redis/BUILD, test/extensions/filters/network/common/redis/codec_impl_test.cc, test/extensions/filters/network/common/redis/mocks.cc, test/extensions/filters/network/common/redis/mocks.h, test/extensions/filters/network/redis_proxy/BUILD, test/extensions/filters/network/redis_proxy/command_lookup_speed_test.cc, test/extensions/filters/network/redis_proxy/command_splitter_impl_test.cc, test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc, test/extensions/filters/network/redis_proxy/mocks.cc, test/extensions/filters/network/redis_proxy/mocks.h, test/extensions/filters/network/redis_proxy/proxy_filter_test.cc, test/extensions/health_checkers/redis/redis_test.cc
Simpler version of https://github.com/envoyproxy/envoy/pull/6055. Will amend description/close other PR if this one passes coverage test without a strange bison/flex error.
=> Refactor Redis commands and connection pool

bazel/README.md, tools/print_dependencies.py
Description:
Follow up of #6168.
Testing:
Docs Changes:
Release Notes:
=> remove envoy_deps completely

test/server/options_impl_test.cc
Description:
Fix test build on macOS caused by #5975.
Testing: CI, mac local
Docs Changes:
Release Notes:
=> fix mac test build

.gitignore
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
Description:  add generated CLion files to gitignore
Testing: N/A
=> git: add generated CLion files to gitignore

docs/root/start/start.rst, examples/mysql/Dockerfile-mysql, examples/mysql/Dockerfile-proxy, examples/mysql/README.md, examples/mysql/docker-compose.yaml, examples/mysql/envoy.yaml
Add an example of how to use Envoy's MySQL network filter.
Signed-off-by: Nick Travers <n.e.travers@gmail.com>
Testing: n/a
=> Add a MySQL filter example

include/envoy/network/listener.h, source/server/connection_handler_impl.cc
Description: fix inconsistent comment
Testing: Test in Prod 
Docs Changes: Please suggest
=> listener: fix comment of onAccept

api/envoy/config/bootstrap/v2/bootstrap.proto, api/envoy/config/filter/http/buffer/v2/buffer.proto, api/envoy/config/filter/http/ip_tagging/v2/ip_tagging.proto, api/envoy/config/filter/http/jwt_authn/v2alpha/config.proto
Signed-off-by: Rama Chavali <rama.rao@salesforce.com>
Description: Forgot to remove this unused import when I removed the deprecated rate limiting from bootstrap.
Docs Changes: N./A
=> config: remove unused import

test/extensions/filters/network/http_connection_manager/BUILD, test/extensions/filters/network/http_connection_manager/config_test.cc
Description: convert v1 JSON to v2 YAML for HttpConnectionManager unit tests
Risk Level: Low (no functional change)
Testing:
=> test: convert HCM test configs to v2 YAML

docs/build.sh, docs/conf.py, docs/root/start/sandboxes/fault_injection.rst, docs/root/start/sandboxes/lua.rst, docs/root/start/sandboxes/mysql.rst, docs/root/start/sandboxes/redis.rst, docs/root/start/start.rst, tools/protodoc/protodoc.py
Part of https://github.com/envoyproxy/envoy/issues/6361
=> docs: start the work of snapping docs to the repo/docker

api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto
=> api: reserve HCM field for pending security fix.

test/common/router/BUILD, test/common/router/router_ratelimit_test.cc
_Description:_ Another PR towards https://github.com/envoyproxy/envoy/issues/6362
_Risk Level:_ Low - no functional change
_Docs Changes:_ N/A
_Release Notes:_ N/A
=> test: convert ratelimit test configs to v2 YAML

examples/grpc-bridge/service/script/gen
Signed-off-by: neilhong <neilhong1206@gmail.com>
Description: fix the outdate gen script of grpc-bridge example
Testing: n/a
=> Examples: Update gen script of grpc example service

SECURITY_RELEASE_PROCESS.md
This will reduce one of the manual steps we keep repeating.
=> security: update distributor application example to include e-mail.

ci/README.md
Signed-off-by: Derek Schaller <dschaller@lyft.com>
Description: Update clang version in CI format target docs
Testing: N/A
=> docs: update clang format version in CI format targets

ci/build_container/build_container_centos.sh, ci/build_container/build_container_ubuntu.sh
Description:
Install LLVM-8 to build image
Testing: CI
Docs Changes:
Release Notes:
=> build_image: install clang-8

support/bootstrap, tools/format_python_tools.sh
=> tools: allow hooks/format to be run from owning directory

source/common/http/async_client_impl.h, source/common/tracing/http_tracer_impl.h
Description:
Fixes #6584 
Testing: CI
Docs Changes:
Release Notes:
=> build: initialize const vector explicitly

support/hooks/pre-push
=> tools: check spelling in pre-push hook

README.md
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
Description: add ppc64le badge that links to Jenkins build server
Risk Level: Low - Docs only
Testing: Viewed in browser and through GH markdown viewer
Release Notes: support ppc64le CPU architecture
Fixes: #5196
=> build: add ppc build badge to README

test/integration/echo_integration_test.cc, test/server/BUILD, test/server/listener_manager_impl_test.cc, test/server/utility.h, test/test_common/environment.cc
Description: Inching closer to deleting v1 code. For #6362.
Testing: Included
=> [test] convert listener test stubs to v2 API

test/common/config/rds_json_test.cc
Add test of parsing weighted_cluster route configuration to improve test coverage of the RdsJson::translateWeightedCluster() method.
Description: Add test of parsing weighted_cluster route configuration to improve test coverage of the RdsJson::translateWeightedCluster() method.
=> config: improve RdsJson::translateRoute test coverage

bazel/repository_locations.bzl
=> tls: update BoringSSL to 8cb07520 (3729).

SECURITY_RELEASE_PROCESS.md
=> security: clarify security release window from fix patch availability.

tools/check_format.py
Description: Small oversight from the clang-8 upgrade
Risk Level: N/A (doc change)
Testing: N/A (doc change)
=> [tools] fix clang-8 reference

ci/do_ci.sh, tools/check_format.py, tools/header_order.py
For the purpose of reuse in Nighthawk.
Testing: check_format_test and NH manual tests.
=> check_format: parameterize namespace and header ordering checks.

docs/root/intro/arch_overview/load_balancing/load_balancers.rst
Signed-off-by: Rama Chavali <rama.rao@salesforce.com>
Description: Minor doc fix.
Testing: N/A
=> docs: minor fix maglev docs

README.md
Description: adds an Azure Pipelines badge to the readme
Testing: n/a
=> add Azure Pipelines badge to README

.circleci/config.yml
=> ci: removing broken opsgenie integration

include/envoy/stream_info/stream_info.h, source/extensions/filters/http/ext_authz/ext_authz.cc, source/extensions/filters/http/fault/fault_filter.cc, source/extensions/filters/http/ratelimit/ratelimit.cc, test/extensions/filters/http/ext_authz/ext_authz_test.cc, test/extensions/filters/http/fault/fault_filter_test.cc, test/extensions/filters/http/ratelimit/ratelimit_test.cc
=> http: adding more rc details

source/common/config/BUILD, source/common/config/delta_subscription_impl.cc, source/common/config/delta_subscription_impl.h, source/common/config/filesystem_subscription_impl.cc, source/common/config/filesystem_subscription_impl.h, source/common/config/grpc_mux_subscription_impl.cc, source/common/config/grpc_mux_subscription_impl.h, source/common/config/http_subscription_impl.cc, source/common/config/http_subscription_impl.h
Followup of #6391
Risk Level: none, cleanup only
=> config: Split detemplatized classes into cc and h

SECURITY_RELEASE_PROCESS.md
=> security: add Aspen Mesh to private distributor list.

include/envoy/router/BUILD, include/envoy/router/rds.h, include/envoy/router/route_config_update_receiver.h, include/envoy/router/router.h, source/common/config/resources.h, source/common/http/async_client_impl.h, source/common/router/BUILD, source/common/router/config_impl.cc, source/common/router/config_impl.h, source/common/router/rds_impl.cc, source/common/router/rds_impl.h, source/common/router/route_config_update_receiver_impl.cc, source/common/router/route_config_update_receiver_impl.h, source/common/router/vhds.cc, source/common/router/vhds.h, source/server/http/admin.h, test/common/http/conn_manager_impl_fuzz_test.cc, test/common/http/conn_manager_impl_test.cc, test/common/router/BUILD, test/common/router/vhds_test.cc, test/integration/BUILD, test/integration/http_integration.cc, test/integration/http_integration.h, test/integration/integration.cc, test/integration/integration.h, test/integration/vhds_integration_test.cc, test/mocks/router/mocks.cc, test/mocks/router/mocks.h
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Base VHDS implementation

source/server/listener_manager_impl.cc, test/server/listener_manager_impl_test.cc
This is an alternative to #6022.
Fixes #6905.
=> listener: detect filter chains with overlapping matching rules.

source/common/config/delta_subscription_state.cc, test/common/config/delta_subscription_state_test.cc
Testing: added to delta_subscription_state_test.cc
=> config: DeltaSubscriptionState now fails on duplicate names

source/common/upstream/health_checker_impl.cc, source/common/upstream/health_checker_impl.h
This is a follow-up to #6942. This makes it a bit more readable. We
spent some time debugging this too, so it would be nice to ensure
it's readable next time we bump into something around this code
surface :-)
=> Make close condition more readable

api/API_OVERVIEW.md, api/README.md
Description: just fixing a link
Testing: checked the preview
=> api: Fix link to xDS proto overview in api docs

SECURITY_RELEASE_PROCESS.md
Description: Add VMware to the security members list
Testing: N/A
/cc @htuch
=> Add VMware to the security members list

source/exe/process_wide.cc, source/extensions/access_loggers/http_grpc/BUILD, source/extensions/access_loggers/http_grpc/config.cc, source/extensions/access_loggers/http_grpc/grpc_access_log_proto_descriptors.cc, source/extensions/access_loggers/http_grpc/grpc_access_log_proto_descriptors.h, source/extensions/filters/network/ratelimit/config.cc, source/extensions/filters/network/ratelimit/config.h, source/extensions/stat_sinks/metrics_service/BUILD, source/extensions/stat_sinks/metrics_service/config.cc, source/extensions/stat_sinks/metrics_service/grpc_metrics_proto_descriptors.cc, source/extensions/stat_sinks/metrics_service/grpc_metrics_proto_descriptors.h, source/server/BUILD, source/server/proto_descriptors.cc, source/server/proto_descriptors.h, test/extensions/filters/http/header_to_metadata/header_to_metadata_filter_test.cc, test/extensions/filters/http/health_check/health_check_test.cc, test/server/options_impl_test.cc
=> coverage: fix some misc coverage

test/extensions/filters/http/grpc_http1_reverse_bridge/reverse_bridge_test.cc
Description: Fix common typo: grcp -> grpc
Testing: N/A
=> Fix common typo: grcp -> grpc

docs/root/configuration/listener_filters/original_dst_filter.rst
docs: fix error link of ListenerFilter
Docs Changes: fix error link of ListenerFilter
=> docs: fix error link of ListenerFilter

api/envoy/config/bootstrap/v2/bootstrap.proto, api/envoy/service/discovery/v2/BUILD, api/envoy/service/discovery/v2/tds.proto, api/test/build/BUILD, api/test/build/build_test.cc, source/server/BUILD, source/server/proto_descriptors.cc
This PR provides the TDS API config. The implementation and docs will be
added in a followup, the idea is to unblock some projects that depend on
the details here.
Testing: @envoy_api build
Part of #6708
=> tds: bootstrap and API configuration protos.

api/envoy/api/v2/eds.proto, api/envoy/api/v2/lds.proto, api/envoy/service/discovery/v2/sds.proto, source/server/BUILD, source/server/proto_descriptors.cc
Delta services other than DeltaClusters were missing. Also added those services to proto_descriptors.cc. Also added some other things that proto_descriptors.cc was missing. #4991 
=> server: add more delta service definitions, update proto_descriptors

source/common/upstream/eds.cc, test/common/upstream/eds_test.cc
=> config: fix EDS for empty update

bazel/repository_locations.bzl
=> tls: update BoringSSL to e534d74f (3770).

test/extensions/filters/network/client_ssl_auth/client_ssl_auth_test.cc
Description: For issue #6362 
Testing: N/A
=> [test] convert ClientSSLAuth stubs to v2

test/common/access_log/access_log_impl_test.cc
Description: For issue #6362 
Testing: included
=> [test] convert AccessLogFilter stubs to v2

docs/root/configuration/http_conn_man/headers.rst
Description: Updating documentation example to be accurate.
Fixes #6457
=> #6457 docs: update example to accurately reflect description

test/common/config/rds_json_test.cc
Description: Added coverage of methods translateVirtualCluster and translateCors to RdsJson class
Part of #1963
Signed-off-by: Andrzej Wawrzyniak <andrzejwaw@gmail.com>
=> Added coverage of methods translateVirtualCluster and translateCors to RdsJson class

test/config_test/config_test.cc
This prevents default failure when a feature has not been failed by default yet.
Risk Level: None, test only.
Testing: Existing tests.
=> config test: use real deprecated feature list

test/integration/integration_admin_test.cc
TBD (someone else) why the two don't play well together - I've done my debug duty for the week :-)
#7215
=> test: deflake admin test by not using LDS

tools/check_format_test_helper.py
=> format: fix the ability to find buildifier in non-standard path.

source/common/upstream/subset_lb.h
Signed-off-by: Kateryna Nezdolii <nezdolik@spotify.com>
Sync comment with implementation (optional wrapper was dropped)
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> subsets fix comment

docs/build.sh, tools/protodoc/protodoc.bzl
Description:
Testing: local
Docs Changes:
Release Notes:
=> ci: make protodoc.bzl ready for Bazel 0.27

ci/mac_ci_steps.sh, test/extensions/filters/network/thrift_proxy/driver/BUILD
Description:
Testing: CI
Docs Changes:
Release Notes:
=> Fix macOS CI with Bazel 0.27

source/extensions/filters/http/fault/fault_filter.cc, source/extensions/filters/http/fault/fault_filter.h, test/extensions/filters/http/fault/fault_filter_test.cc
Probably related to https://github.com/envoyproxy/envoy/issues/7179
Testing: New UT
=> fault: destroy rate limiter during reset

.bazelrc
https://github.com/bazelbuild/bazel/issues/8626
=> bazel: Force python 2 for host tools

api/envoy/admin/v2alpha/clusters.proto, docs/root/intro/version_history.rst, source/server/http/admin.cc, test/server/http/admin_test.cc
Part of https://github.com/envoyproxy/envoy/issues/1606
Testing: Modified UT
=> admin: show hostname in clusters output

test/integration/server.h, test/test_common/utility.cc, test/test_common/utility.h
Description: Refactor some test methods
Testing: N/A
=> server: refactor test methods

.azure-pipelines/linux.yml, ci/build_setup.sh
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: use ci script and remote cache in Azure for Linux

source/common/grpc/google_grpc_utils.cc
Description:
Simplifying GoogleGrpcUtils::makeBufferInstance by leveraging ref count of grpc_slice.
Docs Changes:
Release Notes:
Fixes #7266.
=> grpc: simplify GoogleGrpcUtils::makeBufferInstance

source/extensions/filters/network/zookeeper_proxy/utils.cc, source/extensions/filters/network/zookeeper_proxy/utils.h
Spotted these while working on part 2 of the filter, but
sending them out now to keep nits separate.
=> zookeeper: more constness

source/common/protobuf/utility.cc
Description: This fixes the deprecation warning by adding a missing space character.
Testing: Waiting on CI
=> log: fix deprecation warning

docs/root/configuration/tools/router_check.rst
Signed-off-by: Jyoti Mahapatra <jmahapatra@lyft.com>
Description: Correcting documentation of router check tookl
=> Adding missing description of the runtime field in router check config

test/server/BUILD, test/server/filter_chain_benchmark_test.cc
Description:
Run by
`TEST_SRCDIR=$(pwd) TEST_WORKSPACE=./ TEST_RUNDIR=$(pwd)  bazel run -c opt test/server:filter_chain_benchmark_test`
=> filterchainmanager: add benchmark

docs/root/intro/arch_overview/security/jwt_authn_filter.rst, docs/root/intro/arch_overview/security/security.rst
Signed-off-by: Yangmin Zhu <ymzhu@google.com>
Description:
Testing: N/A
Docs Changes: Added JWT Authentication to arch overview
Optional Fixes https://github.com/envoyproxy/envoy/issues/7285
cc @qiwzhang @lizan @mattklein123
=> add JWT authentication to arch overview

docs/root/intro/version_history.rst
Testing: n/a
Docs Changes: relnote cleanup
=> docs: cleanup for 1.11 release

source/extensions/filters/network/dubbo_proxy/decoder.cc, source/extensions/filters/network/dubbo_proxy/decoder.h
Description:
Merge race of #7118 and #7447 
Testing:
Docs Changes:
Release Notes:
=> dubbo: tidy fix

ci/setup_cache.sh
Reverts envoyproxy/envoy#7563
Blocked on https://github.com/bazelbuild/bazel/issues/8508#issuecomment-509755175
=> Revert "ci: Enable bazel limited download flags"

source/common/http/header_utility.cc, source/common/http/header_utility.h, test/common/http/BUILD, test/common/http/header_map_impl_test.cc, test/common/http/header_utility_test.cc, test/common/router/header_formatter_test.cc, test/integration/protocol_integration_test.cc
Yay, we're doing it right!
Testing: yes
#7488
=> test: adding tests for set-cookie being handled correctly

source/common/event/dispatcher_impl.h
Description:
PR #7330 forgot to update a comment. Fix it to match the current behavior.
Testing: N/A
=> dispatcher: fix a comment.

bazel/foreign_cc/BUILD, bazel/repository_locations.bzl
This has now been fixed upstream
=> build: remove ranlib workaround

.azure-pipelines/linux.yml, ci/WORKSPACE.filter.example, ci/run_envoy_docker.sh
Part from #7625.
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: full IPv6 tests in Azure pipelines

test/coverage/gen_build.sh, test/run_envoy_bazel_coverage.sh
Description:
Testing:
Docs Changes:
Release Notes:
=> coverage: shard coverage tests

source/server/server.cc
=> More constness in server.cc

source/extensions/filters/listener/http_inspector/http_inspector.cc, test/extensions/filters/listener/http_inspector/http_inspector_config_test.cc, test/extensions/filters/listener/http_inspector/http_inspector_test.cc
Bumped into these non consts while fetching  #7559 for our repo.
=> More constness for http_inspector

test/extensions/clusters/redis/redis_cluster_integration_test.cc
Description:
CONFIG/CONFIG_WITH_AUTH initialization order is undefined. Causes ASAN timeout.
Testing: test fix
Docs Changes:
Release Notes:
=> redis_cluster: fix static initialization fiasco

bazel/BUILD, source/common/api/BUILD, source/server/BUILD
Description: Add support for mips64.
Testing: N/A
Fixes: #7689 
Signed-off-by: zqzzq <zhengqianglc@inspur.com>
=> Add support for mips64

.circleci/config.yml, ci/build_container/docker_push.sh
Description:
Needed for RBE. Fixes #7613
Testing: build_image if we have build_container change during the PR. some part are not testable though.
Docs Changes:
Release Notes:
=> ci: push build image to gcr.io

ci/build_container/docker_push.sh
Description:
Follow up of #7740, also fixes format.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: add missed gcloud command

bazel/repository_locations.bzl
=> tls: update BoringSSL to 87d1c8f2 (3809).

SECURITY.md
=> security: add IBM to distributors, clarify policy.

api/envoy/service/discovery/v2/rtds.proto, api/xds_protocol.rst, docs/root/configuration/runtime.rst, docs/root/intro/version_history.rst
Description: see title
Testing: local build
Docs Changes: fix only
Signed-off-by: Daniel Hochman <danielhochman@users.noreply.github.com>
=> docs: fix missing ref in xDS docs and runTime case

source/extensions/filters/network/dubbo_proxy/active_message.cc, source/extensions/filters/network/dubbo_proxy/active_message.h, source/extensions/filters/network/dubbo_proxy/conn_manager.h, source/extensions/filters/network/dubbo_proxy/message.h, test/extensions/filters/network/dubbo_proxy/conn_manager_test.cc, test/extensions/filters/network/dubbo_proxy/decoder_test.cc, test/extensions/filters/network/dubbo_proxy/dubbo_protocol_impl_test.cc, test/extensions/filters/network/dubbo_proxy/mocks.cc, test/extensions/filters/network/dubbo_proxy/mocks.h
Description: Improve dubbo_proxy code coverage
Signed-off-by: leilei.gll <leilei.gll@alibaba-inc.com>
=> dubbo_proxy: Improved code coverage

OWNERS.md
=> security: add @yanavlasov to Envoy security team.

.azure-pipelines/linux.yml, .circleci/config.yml, bazel/toolchains/configs/clang/bazel_0.28.1/config/BUILD, bazel/toolchains/configs/clang_libcxx/bazel_0.28.1/config/BUILD, bazel/toolchains/configs/gcc/bazel_0.28.1/config/BUILD, bazel/toolchains/configs/versions.bzl, bazel/toolchains/rbe_toolchains_config.bzl
Description: Fixes post submit issue from #7786 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: roll forward build image

source/extensions/filters/network/zookeeper_proxy/decoder.cc
=> Fix comment

source/extensions/filters/network/well_known_names.h
Description: self-explanatory
Risk Level: N.A
Testing: N/A
Signed-off-by: Derek Argueta <darguetap@gmail.com>
=> docs: fix incorrect comment

SECURITY.md
=> security: update Istio contact e-mail.

source/extensions/filters/http/jwt_authn/authenticator.cc, source/extensions/filters/http/jwt_authn/extractor.cc, source/extensions/filters/http/jwt_authn/matcher.cc, test/extensions/filters/http/jwt_authn/extractor_test.cc, test/extensions/filters/http/jwt_authn/filter_config_test.cc, test/extensions/filters/http/jwt_authn/filter_factory_test.cc, test/extensions/filters/http/jwt_authn/matcher_test.cc
Description: Some "using" are not used any more.  This change clean them out
Testing: unit-test
Release Notes:  None
=> jwt_authn: clean not-used using

source/extensions/filters/http/ip_tagging/ip_tagging_filter.h
Description: Clears a TODO left by @ccaraman to reduce copies in `IpTaggingFilterConfig` constructor to construct the LC-trie. The optimization opportunities I found were
1) pre-reserve `std::vector`s since size is known beforehand
2) `std::move` into `emplace_back` for `Network::Address::CidrRange` to avoid copy constructor (can't use in-place construction since we check `isValid()` after construction)
3) use in-place construction for `std::pair<std::string, std::vector<Network::Address::CidrRange>>` into `emplace_back` by perfect forwarding the constructor arguments
This isn't an online path (only called for config construction) so I think this suffices for optimizations here.
Signed-off-by: Derek Argueta …
=> ip tagging: fix old perf TODO in config constructor

source/extensions/filters/network/kafka/protocol/generator.py
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
Description: cleanup message in comment, make it more understandable.
Testing: no need testing :)
=> cleanup: generator.py words correction.

source/common/config/watch_map.cc
Spotted iterators that could be const, when incorporating #7108 
into our repo.
=> Make iterators const

SECURITY.md, test/server/server_test.cc
These came up in the last set of CVEs.
=> security: some intra-entity and 3rd party embargo clarifications.

source/common/protobuf/message_validator_impl.cc, source/common/protobuf/message_validator_impl.h
Include What You Use fix for source/common/protobuf/message_validator_impl.h. 
Testing: No new tests added.
=> protobuf: IWYU

docs/root/_static/css/envoy.css
#7992 
Signed-off-by: Manish Kumar <manishjpiet@gmail.com>
=> Content in envoy docs does not cover whole page

docs/root/intro/version_history.rst
=> Fix version history

source/common/upstream/BUILD, source/extensions/tracers/opencensus/BUILD
=> build: some missing dep fixups for Google import.

test/test_runner.h
=> build: missing regex include.

bazel/external/quiche.BUILD, bazel/repository_locations.bzl, source/extensions/quic_listeners/quiche/BUILD, source/extensions/quic_listeners/quiche/platform/BUILD, source/extensions/quic_listeners/quiche/platform/flags_list.h, source/extensions/quic_listeners/quiche/platform/quic_mem_slice_storage_impl.h, source/extensions/quic_listeners/quiche/platform/quic_text_utils_impl.h, source/extensions/quic_listeners/quiche/platform/spdy_containers_impl.h, source/extensions/quic_listeners/quiche/platform/spdy_map_util_impl.h, test/extensions/quic_listeners/quiche/BUILD, test/extensions/quic_listeners/quiche/platform/BUILD
Update QUICHE tar ball to 4abb566fbbc63df8fe7c1ac30b21632b9eb18d0c.
Add some new impl's for newly added api.
Testing: using quiche build in tests.
Part of #2557
=> quiche: Update QUICHE dep

docs/build.sh, tools/protodoc/BUILD, tools/protodoc/protodoc.py
Testing: Rebuilt docs, manual inspection of some example generated files.
=> protodoc: upgrade to Python 3.

bazel/repository_locations.bzl
Signed-off-by: Pengyuan Bian <bianpengyuan@google.com>
cc @g-easy 
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Update io_opencensus_cpp SHA

docs/root/intro/version_history.rst, include/envoy/buffer/buffer.h, source/common/buffer/buffer_impl.cc, source/common/buffer/buffer_impl.h, source/common/http/conn_manager_utility.cc, test/common/buffer/buffer_fuzz.cc, test/common/buffer/buffer_speed_test.cc, test/common/buffer/owned_impl_test.cc, test/common/buffer/watermark_buffer_test.cc, test/common/http/conn_manager_utility_test.cc
Testing: added test case
Release Notes: updated
Fixes: #8229
=> http: only accept HTTP client magic at the start of buffer

api/envoy/admin/v2alpha/metrics.proto, api/envoy/admin/v2alpha/server_info.proto, api/envoy/api/v2/cds.proto, api/envoy/api/v2/core/base.proto, api/envoy/api/v2/route/route.proto, api/envoy/config/filter/accesslog/v2/accesslog.proto, api/envoy/config/filter/http/gzip/v2/gzip.proto, api/envoy/data/accesslog/v2/accesslog.proto, api/envoy/data/core/v2alpha/health_check_event.proto, tools/protoxform/protoxform.py
=> protoxform: remove blank line spacing in any enum with no comments.

api/envoy/api/v2/cds.proto
#8309 and #8100 collided
Risk Level: Low (cleanup)
Testing: n/a
=> api: fixing format build

tools/check_format.py, tools/check_format_test_helper.py, tools/testdata/check_format/api/go_package.proto, tools/testdata/check_format/api/java_options.proto, tools/testdata/check_format/api/java_options.proto.gold
This has been subsumed into protoxform.
Risk level: Low (developer formatting tool)
Testing: check/fix_format.
=> check_format: remove proto options handling.

ci/run_fuzzit.sh
This is a fix for https://github.com/envoyproxy/envoy/pull/7509#issuecomment-534384231
@lizan @htuch
=> update fuzzit CLI to v2.4.57

.azure-pipelines/linux.yml, .circleci/config.yml
=> ci: move format check to azp

source/extensions/filters/http/squash/squash_filter.h, test/extensions/filters/http/squash/squash_filter_test.cc
Description: Part of issue #6362
Testing: included
=> test: update squash filter test stubs to v2

.azure-pipelines/linux.yml, .circleci/config.yml
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: run asan in Azure RBE

ci/do_ci.sh
Description:
:pray: this doesn't flake.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: fix tcpdump not found 

test/common/access_log/BUILD, test/common/access_log/access_log_impl_test.cc
Description: part of issue #6362 
=> test: migrate AccessLog test configurations to v2

test/extensions/filters/http/fault/BUILD, test/extensions/filters/http/fault/fault_filter_test.cc
Description: part of issue #6362 
=> test: migrate fault filter test configurations to v2

README.md
Description: Adds OSS-Fuzz fuzzing badge, see https://google.github.io/oss-fuzz/getting-started/new-project-guide/#status-badge
Risk Level:
Testing: NA
Docs Changes: Adds OSS-Fuzz fuzzing badge
Signed-off-by: Abhishek Arya <inferno@chromium.org>
=> Add OSS-Fuzz fuzzing badge.

test/common/router/BUILD, test/common/router/rds_impl_test.cc
Description: part of issue #6362 
=> test: migrate HTTP Connection Manager to v2

include/envoy/stats/stats_macros.h
=> stats: Remove extraneous include

.bazelrc, .circleci/config.yml, bazel/README.md, bazel/repository_locations.bzl, ci/build_setup.sh, ci/run_clang_tidy.sh, tools/check_format.py, tools/check_format_test_helper.py
Description:
Risk Level: Med
Testing: CI
=> build: use clang-9

tools/gen_compilation_database.py
=> build: make compilation database generation faster

api/envoy/config/filter/http/dynamic_forward_proxy/v2alpha/dynamic_forward_proxy.proto, api/envoy/config/filter/http/dynamic_forward_proxy/v3alpha/dynamic_forward_proxy.proto, docs/root/configuration/http/http_filters/dynamic_forward_proxy_filter.rst, docs/root/intro/version_history.rst, include/envoy/router/router.h, source/extensions/filters/http/buffer/buffer_filter.cc, source/extensions/filters/http/dynamic_forward_proxy/BUILD, source/extensions/filters/http/dynamic_forward_proxy/config.cc, source/extensions/filters/http/dynamic_forward_proxy/config.h, source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc, source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.h, source/extensions/filters/http/fault/fault_filter.cc, source/extensions/filters/http/rbac/rbac_filter.cc, test/extensions/filters/http/dynamic_forward_proxy/BUILD, test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_test.cc
This enables us to support host rewrites.
Fixes: #8607
=> dynamic forward proxy: implement per filter config

repokitteh.star
Description:
Configure ownerscheck to work with labels.
Risk Level:
Low.
Testing:
In this PR.
Docs Changes:
None
Release Notes:
None
=> ownerscheck with labels

api/envoy/api/v2/core/health_check.proto, api/envoy/api/v2/route/route.proto, api/envoy/api/v3alpha/core/health_check.proto, api/envoy/api/v3alpha/route/route.proto, source/common/config/api_type_db.generated.pb_text
=> build: run tools/proto_format.sh on master to fix build

include/envoy/server/filter_config.h, source/common/upstream/upstream_impl.cc, source/server/server.h
Description:
I planned another bigger change on TransportSocketFactory but I don't have the bandwidth to complete.
This one is killing a small tech debt. 
Done is better than perfect I guess.
I will pick up the bigger refactor in the future.
=> filter: delete messageValidationVisitor from serverfactorycontext

.bazelrc, ci/do_ci.sh, test/extensions/filters/network/redis_proxy/proxy_filter_test.cc
Testing: CI
Docs Changes:
Release Notes:
=> ci: sanitize vptr and function

docs/build.sh, tools/proto_format.sh
Description:
Testing:
Docs Changes:
Release Notes:
=> build: remove unnecessary spawn_strategy

test/tools/router_check/test/route_tests.sh
Signed-off-by: Derek Schaller <d_a_schaller@yahoo.com>
Description: Remove dead line in router check tests.
Testing: Existing tests to ensure this doesn't introduce regressions.
=> router check tests: remove unnecessary line

.azure-pipelines/linux.yml, ci/docker_push.sh, ci/docker_tag.sh
Description:
Testing: Tested in security release repo
Fixes #6596
=> Enable tag release from azp

api/envoy/api/v2/cluster/circuit_breaker.proto, api/envoy/api/v2/route/route.proto, api/envoy/api/v3alpha/cluster/circuit_breaker.proto, api/envoy/api/v3alpha/route/route.proto, api/envoy/config/filter/network/dubbo_proxy/v2alpha1/route.proto, api/envoy/config/filter/network/dubbo_proxy/v3alpha/route.proto, api/envoy/config/filter/network/tcp_proxy/v3alpha/tcp_proxy.proto, api/envoy/data/accesslog/v2/accesslog.proto, api/envoy/data/accesslog/v3alpha/accesslog.proto, source/common/common/regex.cc, source/common/protobuf/utility.h, source/common/upstream/upstream_impl.cc
Signed-off-by: Michael Payne <michael@sooper.org>
Description: Fix PGV location references and TODOs. Remove some unused imports.
Risk Level: Low (locations in comments and simple TODOs as outlined by @htuch)
Testing: `bazel build @envoy_api//envoy/...`, `bazel test //test/...`
Docs Changes: None required
Release Notes: None required
=> Fix PGV location references and TODOs.

docs/root/configuration/other_protocols/thrift_filters/rate_limit_filter.rst, docs/root/configuration/other_protocols/thrift_filters/router_filter.rst
Caught while setting up configs for these filters.
=> thrift: fix filter names in docs

docs/root/configuration/other_protocols/dubbo_filters/router_filter.rst
=> dubbo: fix router doc

bazel/README.md
Description: Fix Document issue #8549
Testing: 
Release Notes:
[Optional Fixes #Issue]  Document issue #8549
=> document change

test/server/listener_manager_impl_test.cc
Description:
Testing: test only
Docs Changes:
Release Notes:
=> test: increase coverage of listener_manager_impl.cc

include/envoy/stats/stats.h, source/common/stats/allocator_impl.h, source/common/stats/metric_impl.cc, source/common/stats/metric_impl.h, source/common/stats/symbol_table_impl.cc, source/common/stats/symbol_table_impl.h, test/common/stats/isolated_store_impl_test.cc, test/common/stats/symbol_table_impl_test.cc, test/common/stats/thread_local_store_test.cc, test/mocks/stats/mocks.h, tools/spelling_dictionary.txt
Description: a few methods here and there that were untested. Either remove them or add unit tests.
Testing: //test/common/stats/...
=> stats: Improve test coverage

README.md
=> misc: fix azp badge

source/extensions/clusters/dynamic_forward_proxy/cluster.cc, source/extensions/clusters/dynamic_forward_proxy/cluster.h, source/extensions/common/dynamic_forward_proxy/dns_cache.h, source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc, source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h, test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc, test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc, test/extensions/common/dynamic_forward_proxy/mocks.h, test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
Fixes https://github.com/envoyproxy/envoy/issues/8343
Testing: Unit/integration
=> forward proxy: handle cache reattach

.bazelci/presubmit.yml
=> bazelci: macos and rbe

include/envoy/upstream/cluster_manager.h, source/common/upstream/cluster_manager_impl.h, source/extensions/quic_listeners/quiche/active_quic_listener.cc, source/extensions/quic_listeners/quiche/active_quic_listener.h, source/server/connection_handler_impl.cc, source/server/connection_handler_impl.h, test/extensions/quic_listeners/quiche/active_quic_listener_test.cc, test/mocks/upstream/mocks.h
And some other misc cleanup.
Prep for finishing basic UDP proxying.
=> connection handler: remove dynamic casts

docs/root/configuration/other_protocols/thrift_filters/rate_limit_filter.rst
Discussion: https://envoyproxy.slack.com/archives/C78HA81DH/p1572312694107700
=> Fix Thrift rate limit filter name

source/extensions/common/wasm/null/null_vm.cc, source/extensions/common/wasm/null/null_vm.h, source/extensions/common/wasm/wasm_vm.h, test/extensions/common/wasm/wasm_vm_test.cc
Remove code that is no longer needed. For details, see:
- https://github.com/envoyproxy/envoy-wasm/pull/276
- https://github.com/envoyproxy/envoy-wasm/pull/282                                                                           
=> wasm: sync WasmVm interface with upstream.

source/common/http/http1/codec_impl.cc
Removes the dependency on `fmt::format` in H1 codec. Eliminates the use of `fmt::format` to format HTTP requests. Instead uses `absl::StrCat`, which can handle hex values with `absl::Hex`. 
=> [codec] remove uses of fmt::format, move to absl::StrCat

source/common/network/address_impl.cc, tools/spelling_dictionary.txt
=> fix format on master

source/extensions/filters/network/common/redis/BUILD, source/extensions/filters/network/common/redis/codec.h, source/extensions/filters/network/common/redis/codec_impl.cc, source/extensions/filters/network/common/redis/codec_impl.h, source/extensions/filters/network/redis_proxy/command_splitter_impl.cc, test/extensions/filters/network/common/redis/codec_impl_test.cc
Description: Add CompositeArray Redis RespValue as part of the #8780 PR
Testing: Added unit tests
=> Composite array

.azure-pipelines/linux.yml, api/envoy/api/v3alpha/core/base.proto, ci/check_and_fix_format.sh
Description:
Risk Level:
Testing: testing CI
Docs Changes:
Release Notes:
Fixes #8636
=> ci: try fix format in CI

source/common/grpc/codec.cc, source/common/grpc/codec.h, source/extensions/filters/http/grpc_stats/grpc_stats_filter.cc, test/common/grpc/codec_test.cc
Description: apply visitor pattern to reduce code duplication in gRPC parsing
Risk Level: medium (protocol parsing)
Testing: existing unit tests
=> grpc: merge the inspector with the decoder

.bazelrc, docs/build.sh, tools/proto_format.sh
=> bazel: update command line flags for RBE

OWNERS.md
Thanks for all your hard work on Envoy and welcome to the senior maintainer group!
=> owners: bumping Snow to senior maintainer!

.bazelrc, .circleci/config.yml, ci/envoy_build_sha.sh
Description:
Risk Level:
Testing: v1.12.0 tag in azp https://dev.azure.com/cncf/envoy/_build/results?buildId=17571
Docs Changes:
Release Notes:
=> ci: remove release jobs from circle

bazel/repository_locations.bzl
Signed-off-by: Pengyuan Bian <bianpengyuan@google.com>
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Update opencensus sha

bazel/external/wee8.genrule_cmd, bazel/setup_clang.sh
=> wasm: fix V8 running under UBSan with vptr checks.

source/extensions/all_extensions.bzl, source/extensions/extensions_build_config.bzl
Testing:
Docs Changes:
Release Notes:
Fixes #8928
=> build: make crypto utility as required extension

api/envoy/api/v2/route/route.proto, api/envoy/api/v3alpha/route/route.proto, api/envoy/config/bootstrap/v2/bootstrap.proto, api/envoy/config/bootstrap/v3alpha/bootstrap.proto, api/envoy/config/filter/network/thrift_proxy/v2alpha1/route.proto, api/envoy/config/filter/network/thrift_proxy/v3alpha/route.proto
Description: Fix badly formatted links in .proto files
Testing: N/A
Docs Changes: cross links in docs generated out of .proto files
=> docs: fix badly formatted links in .proto files

ci/build_setup.sh, ci/run_envoy_docker.sh
=> ci: use test cache in PR runs

test/common/config/BUILD, test/common/crypto/BUILD
This fixes some crypto dependent tests.
/cc @lizan
=> tests: enable crypto dependent tests

docs/root/configuration/http/http_conn_man/header_sanitizing.rst
Testing: n/a
Docs Changes: updated
Release Note: n/a
Fixes: #8971
=> docs: note internal_address_config setting in header sanitization docs

test/extensions/clusters/redis/redis_cluster_integration_test.cc, test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc, test/integration/integration.cc, test/integration/integration.h, test/integration/server.cc, test/integration/server.h
Description: I cannot locally repro the failed test locally, but looking at the code this is where the likely failure might be.
Testing: Integration test updated.
Fixes #8917
=> fix flaky tests in redis integration test

docs/root/intro/version_history.rst, source/common/grpc/common.cc, source/common/grpc/common.h, source/common/upstream/health_checker_impl.cc, test/common/upstream/health_checker_impl_test.cc
Copy of https://github.com/envoyproxy/envoy/pull/8254 with test added
=> health check: Set grpc timeout for gRPC health checks (copy of #8254)

api/xds_protocol.rst
Description: Clarify semantics of resource_names field in xDS API.
Testing: N/A
Docs Changes: Included in this PR.
As discussed with @htuch.
=> api: Clarify that clients will ignore unrequested resources.

source/common/json/json_loader.cc, source/common/json/json_loader.h, test/common/json/json_loader_test.cc
=> remove Json::Factory::listAsJsonString

tools/envoy_build_fixer.py
=> format: allow envoy bazel prefix to be overriden in BUILD fixer

bazel/external/wee8.genrule_cmd, bazel/setup_clang.sh
=> wasm: fix V8 running under ASan without setup_clang.

docs/root/intro/version_history.rst, source/common/router/router.cc, test/common/router/router_test.cc
=> Add Location header only when required

source/extensions/tracers/xray/BUILD, source/extensions/tracers/xray/config.cc, source/extensions/tracers/xray/localized_sampling.cc, source/extensions/tracers/xray/localized_sampling.h, source/extensions/tracers/xray/reservoir.h, source/extensions/tracers/xray/sampling_strategy.h, source/extensions/tracers/xray/tracer.cc, source/extensions/tracers/xray/tracer.h, source/extensions/tracers/xray/xray_configuration.h, source/extensions/tracers/xray/xray_tracer_impl.cc, source/extensions/tracers/xray/xray_tracer_impl.h, test/extensions/tracers/xray/BUILD, test/extensions/tracers/xray/localized_sampling_test.cc, test/extensions/tracers/xray/xray_tracer_impl_test.cc
Description: Localized sampling strategy for X-Ray (1/2). This creates the spans but does not (yet)
send them to the daemon.
Signed-off-by: Marco Magdy <mmagdy@gmail.com>
=> AWS X-Ray Localized Sampling (1/2)

include/envoy/buffer/buffer.h, source/common/event/libevent.h, source/extensions/quic_listeners/quiche/platform/quic_mem_slice_storage_impl.cc
=> buffer: misc missed evbuffer references

docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
Description: Trivial doc update.
Risk Level: Negative.
Docs Changes: Addressing old feedback from https://github.com/envoyproxy/data-plane-api/pull/529
@htuch apologies, I shut off mail from github a while ago and totally missed your
feedback.  This addresses it!
=> docs: Attribute least request from N random load balancing link.

test/common/network/listener_impl_test.cc
The DisableAndEnableListener test creates a real listener and client
connection to test listener enable/disable functionality. Prior to
was not accepted by a disabled listener within 2 seconds. After #7165,
the timer and sleep execute against an `Event::SimulatedTimeSystem`
(e.g. the sleep call increments simulated time and the timer fires
almost immediately). The timer event closes the client connection. If
that occurs before the listener has a pending connection, the
subsequent `listener.enable()` call does not trigger
`listener.onAccept` and the test times out. This seems to happen
primarily on macOS, though in principal the race exists on Linux as
well. However, it may be that in practice localhost connections in
Linux are rarely or never deferred.
Testing: 1000x …
=> test: fix flakey listener_impl_test

test/extensions/filters/udp/udp_proxy/udp_proxy_integration_test.cc
=> udp proxy: fix test flake

bazel/repository_locations.bzl
Description: update CEL runtime. Improves activation interface, fixes string_view from null violation, includes a new (and not used here) parser.
Testing:
Docs Changes:
Release Notes:
=> cel: update runtime

source/extensions/filters/network/dubbo_proxy/router/route_matcher.cc, source/extensions/filters/network/dubbo_proxy/router/route_matcher.h, test/extensions/filters/network/dubbo_proxy/route_matcher_test.cc
Signle -> Single
Testing: N/A
Signed-off-by: JUN JIE NAN <nanjunjie@gmail.com>
=> Fixed typo mistake

source/common/upstream/maglev_lb.h
Description: "listening 1" -> "listing 1"
Testing: N/A
=> lb: fix docstring typo

ci/envoy_build_sha.sh
=> build: fix envoy_build_sha.sh error message

source/common/grpc/context_impl.cc, test/common/grpc/context_impl_test.cc
Description: fixes https://github.com/envoyproxy/envoy/issues/9173
Testing: unit
=> grpc: strip query params from stats

OWNERS.md
Welcome!
While editing OWNERS, as a bonus I disclaimed knowledge on some items.
=> owners: add asraa@ as maintainer.

source/extensions/filters/common/rbac/matchers.cc, test/extensions/filters/common/rbac/matchers_test.cc
Fixes principal  match condition in RBAC as discussed  her ihttps://github.com/envoyproxy/envoy/pull/9237#discussion_r355154509
Testing: Added
=> rbac: fix rbac principal match condition

api/envoy/api/v3alpha/route/route.proto, source/extensions/filters/http/dynamic_forward_proxy/BUILD
Apply from CI run: https://dev.azure.com/cncf/envoy/_build/results?buildId=22372&view=logs&jobId=9fd74226-df5b-5f29-39da-76fc341cc763
=> fix merge race

docs/root/configuration/http/http_filters/grpc_http1_reverse_bridge_filter.rst
Risk Level: low, docs only
Testing: n/a
Doc Changes: inline
=> docs: fix v2 api ref for grpc_http1_reverse_bridge_filter

test/extensions/transport_sockets/tls/BUILD, test/extensions/transport_sockets/tls/integration/BUILD, test/extensions/transport_sockets/tls/ssl_socket_test.cc, test/integration/BUILD, test/server/BUILD, test/server/filter_chain_manager_impl_test.cc
=> Cleanup: Remove unused dependencies

api/xds_protocol.rst
Description: Clarify xDS protocol semantics for resources that do not exist.
Testing: N/A
Docs Changes: Included in PR.
CC @htuch
=> docs: Clarify xDS semantics for resources that do not exist.

docs/root/faq/load_balancing/region_failover.rst, docs/root/faq/overview.rst
=> docs: add faq entry about region failovers

tools/testdata/protoxform/envoy/v2/sample.proto.v2.gold, tools/testdata/protoxform/envoy/v2/sample.proto.v3alpha.gold
=> build: fix merge race between #9241 and #9413.

docs/root/operations/admin.rst
Description: Fix config dump query param docs introduced in #9100 
Testing: N/A
=> docs: fix config dump docs

docs/root/intro/version_history.rst
Description: Couple of minor version history updates
Testing: N/A
=> docs: minor version history updates

tools/clang_tools/api_booster/main.cc, tools/spelling_dictionary.txt
Description: Fix spelling errors and add code snippets from comments to dictionary
Testing: N/A
=> Fix spelling errors and add to spelling dictionary

source/common/protobuf/utility.h, test/test_common/utility.h
=> protobuf: trivial utility header cleanups.

generated_api_shadow/envoy/api/v2/core/grpc_service.proto, generated_api_shadow/envoy/api/v3alpha/core/grpc_service.proto
Description: https://github.com/envoyproxy/envoy/pull/9486 crossed paths with #9429. This PR fixes the format CI run.
Testing: local format scripts.
=> fmt: fix master

OWNERS.md
=> owners: change snowp email address

docs/root/configuration/best_practices/edge.rst, docs/root/configuration/http/http_filters/adaptive_concurrency_filter.rst, docs/root/configuration/http/http_filters/dynamic_forward_proxy_filter.rst, docs/root/configuration/http/http_filters/ext_authz_filter.rst, docs/root/configuration/http/http_filters/fault_filter.rst, docs/root/configuration/http/http_filters/grpc_http1_reverse_bridge_filter.rst, docs/root/configuration/http/http_filters/grpc_json_transcoder_filter.rst, docs/root/configuration/http/http_filters/header_to_metadata_filter.rst, docs/root/configuration/http/http_filters/original_src_filter.rst, docs/root/configuration/http/http_filters/tap_filter.rst, docs/root/configuration/listeners/listener_filters/original_src_filter.rst, docs/root/configuration/listeners/network_filters/dubbo_proxy_filter.rst, docs/root/configuration/listeners/network_filters/ext_authz_filter.rst, docs/root/configuration/listeners/network_filters/zookeeper_proxy_filter.rst, docs/root/configuration/operations/overload_manager/overload_manager.rst, docs/root/faq/configuration/flow_control.rst, docs/root/intro/arch_overview/http/http_connection_management.rst, docs/root/operations/traffic_tapping.rst
Testing: N/A
Part of Fixing #5558
=> docs: Replace use of Struct with Any

source/server/server.cc
Description: When Envoy shuts down it sends lifecycle notifications to registered callbacks. Some of these callbacks take a completion callback which gets invoked to exit the main dispatcher after all registered callbacks have finished their work. This is implemented by wrapping the completion callback in a shared_ptr so that it gets called as part of the custom destructor of the shared_ptr. Registered callbacks typically involve calling runOnAllThreads on a TLS object and there is a race condition here that can result in the wrapped completion cb being destroyed on a worker thread which triggers the assert that we're on the main thread. To fix this, I'm removing the assert and posting the completion cb to the main dispatcher so that it gets executed on the right thread. This is similar …
=> server: fix race condition during server shutdown lifecycle notification

api/STYLE.md
=> doc: add v3 package structure

tools/check_format.py
=> tools: update list of maintainers in check_format.py

configs/envoy_double_proxy_v2.template.yaml, configs/envoy_front_proxy_v2.template.yaml, configs/envoy_service_to_service_v2.template.yaml, configs/original-dst-cluster/proxy_config.yaml, examples/cors/backend/front-envoy.yaml, examples/grpc-bridge/client/envoy-proxy.yaml, examples/jaeger-native-tracing/front-envoy-jaeger.yaml, examples/jaeger-native-tracing/service1-envoy-jaeger.yaml, examples/jaeger-native-tracing/service2-envoy-jaeger.yaml, examples/jaeger-tracing/front-envoy-jaeger.yaml, examples/jaeger-tracing/service1-envoy-jaeger.yaml, examples/jaeger-tracing/service2-envoy-jaeger.yaml, examples/zipkin-tracing/front-envoy-zipkin.yaml, examples/zipkin-tracing/service1-envoy-zipkin.yaml, examples/zipkin-tracing/service2-envoy-zipkin.yaml, test/config_test/example_configs_test.cc
From the lamentably dead flip PR, replacement in progress
Testing: yes
=> test: updating example configs for upcoming disallowed by default features

bazel/repository_locations.bzl
Description: routine upgrade of abseil, last update was in July.
=> deps: upgrade abseil

bazel/repository_locations.bzl
=> wasm: update V8 to v8.0.426.12.

source/server/listener_manager_impl.cc, test/server/listener_manager_impl_test.cc, test/server/listener_manager_impl_test.h
Description: Fixes the workers started log line
Testing: N/A
=> server: fix workers log messages

docs/root/configuration/http/http_filters/dynamic_forward_proxy_filter.rst
=> docs: fix filter type url

api/STYLE.md, tools/proto_sync.py
Avoid deleting files without prompting, link back to the recommended extension API flow.
Fixes #9610
=> tools: improve proto_sync.py UX.

OWNERS.md
=> owners: add yavlasov@ as maintainer.

SECURITY.md
=> docs: adding dropbox to cncf-envoy-distributors-announce

tools/proto_sync.py
Run patch directly when there's nothing to delete.
cc: @htuch 
=> Fix for #9699

docs/root/configuration/http/http_filters/on_demand_updates_filter.rst, source/extensions/filters/http/well_known_names.h, test/integration/vhds_integration_test.cc
This is a brand new filter which no one is likely using yet so
I think it's OK to fix this.
=> vhds: fix filter name to conform to new style

test/mocks/config/mocks.h, test/mocks/network/connection.h, test/mocks/server/mocks.h, test/mocks/ssl/mocks.h, test/mocks/upstream/mocks.h
Follow-up to https://github.com/envoyproxy/envoy/pull/9741
=> test: batch 2/4 of updating MOCK_METHOD to new style

docs/root/intro/arch_overview/operations/draining.rst
Description: Fixes draining docs in arch overview.
Testing: N/A
Fixes https://github.com/envoyproxy/envoy/issues/9761
=> docs: fix draining docs

source/docs/stats.md
Signed-off-by: Snow Pettersen <aickck@gmail.com>
Testing: n/a
=> docs: fix typo in stats docs

source/server/http/admin.cc
Description: as title saysg
Related to issue #6953 cc @dichen16 
=> admin: replace time(nullptr) with timesource's SystemTime

SECURITY.md
=> docs: adding stripe to cncf-envoy-distributors-announce

source/common/network/connection_impl.cc, test/common/network/connection_impl_test.cc, test/extensions/transport_sockets/tls/ssl_socket_test.cc
Risk Level: Medium (changes the connection class)
=> network: draining the buffer on close

source/extensions/tracers/zipkin/config.cc
Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>
Description: Correct Typo
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tracers: fix typo s/lightstep/Zipkin/

test/integration/idle_timeout_integration_test.cc
=> test: Fix CRLF in Request-Line

docs/root/configuration/http/http_filters/aws_request_signing_filter.rst
=> docs: fix aws_request_signing's config example

bazel/repository_locations.bzl
=> tls: update BoringSSL to 08a0b210 (3987).

source/common/network/transport_socket_options_impl.cc, test/common/upstream/cluster_manager_impl_test.cc
=> transport socket: hash SAN transport socket options

docs/root/configuration/other_protocols/thrift_filters/router_filter.rst, docs/root/intro/version_history.rst
=> thrift_proxy: add stats docs for the router filter

include/envoy/secret/secret_manager.h, source/common/secret/secret_manager_impl.cc
Signed-off-by: bennettdong <xiangfeid@gmail.com>
Description: remove unnecessary code introduced by https://github.com/envoyproxy/envoy/pull/9858
=> cleanup: remove unnecessary code introduced by 9858

test/extensions/common/redis/cluster_refresh_manager_test.cc
Description: Fix a race condition in the cluster refresh manager test
Testing: ran the test 100 times and verify fix
Fixes: #9583
=> Fix refresh manager test

api/envoy/api/v2/auth/cert.proto, api/envoy/extensions/transport_sockets/tls/v3/cert.proto, generated_api_shadow/envoy/api/v2/auth/cert.proto, generated_api_shadow/envoy/extensions/transport_sockets/tls/v3/cert.proto
Description: Fixes doc indentation
Testing: N/a
Release Notes: N/a
=> docs:fix yaml indentation

tools/stack_decode.py
Signed-off-by: John Plevyak <jplevyak@gmail.com>
=> Add parsing for ASAN error stack output.

test/coverage/gen_build.sh, test/run_envoy_bazel_coverage.sh
=> ci: mark coverage flaky and multiple attempts in CI

tools/code_format/check_format.py
Enables @yanavlasov to be listed as a directory owner in CODEOWNERS
=> tools: add @yavlasov to maintainers in check_format.py for owned directories

api/envoy/admin/v2alpha/clusters.proto, api/envoy/admin/v3/clusters.proto, generated_api_shadow/envoy/admin/v2alpha/clusters.proto, generated_api_shadow/envoy/admin/v3/clusters.proto, source/server/http/admin.cc, test/server/http/admin_test.cc
Signed-off-by: Xin Zhuang <stevenzzz@google.com>
Description: export host locality in host_status of Admin cluster/ 
Risk Level: LOW (new admin info dump)
Testing: unit test updated.
Fixes #10106
=> export locality to host_status in Admin/ cluster dump

source/common/stats/thread_local_store.cc, source/common/stats/thread_local_store.h
Signed-off-by: Snow Pettersen <aickck@gmail.com>
Description:
Testing: n/a
=> stats: remove comments/dead code related to name truncation

api/envoy/api/v2/route/route_components.proto, api/envoy/config/route/v3/route_components.proto, generated_api_shadow/envoy/api/v2/route/route_components.proto, generated_api_shadow/envoy/config/route/v3/route_components.proto
Description: Fixes a small typo in route components proto
Testing: N/a
=> router: fix typo in route components proto

ci/do_ci.sh
=> [1.12] bazel: build tests only in sanitizer runs (#8878)

docs/root/faq/configuration/flow_control.rst
=> docs: fix config example in flow control faq

ci/docker_build.sh, ci/docker_push.sh
=> docker: push SHA tag for release branch too

ci/docker_build.sh, ci/docker_push.sh
=> [1.13] docker: push SHA tag for release branch too (#10214)

ci/docker_build.sh, ci/docker_push.sh
=> [1.12] docker: push SHA tag for release branch too (#10214)

source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc
Description: I forgot I wanted to add these log lines in #10200. This PR adds them.
Risk Level: low, debug log lines.
=> dns cache: add missing logs

ci/docker_push.sh
=> docker: fix typo in docker push script

source/common/router/BUILD, source/common/router/router.cc, source/common/router/router.h, source/common/router/upstream_request.cc, source/common/router/upstream_request.h
Risk Level: Low (moving classes around) 
Testing: n/a
Cleanup for #1630
=> router: moving upstream to a new file

test/extensions/filters/http/common/fuzz/filter_fuzz_test.cc
=> fuzz: Fix conditional expression

OWNERS.md
Hurray!
Also fix up the security team list.
=> maintainers: add Greg back!

test/common/common/base64_fuzz_test.cc
Signed-off-by: Lin Lin <linlineric@google.com>
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Add more fuzz tests for base64 functions

source/server/server.cc, source/server/server.h, test/config_test/config_test.cc
Signed-off-by: Snow Pettersen <kpettersen@netflix.com>
Testing: n/a
=> server: remove references to v1/2 from loadBootstrapConfig

bazel/repository_locations.bzl, source/extensions/quic_listeners/quiche/codec_impl.cc, source/extensions/quic_listeners/quiche/envoy_quic_server_session.cc, source/extensions/quic_listeners/quiche/envoy_quic_server_session.h, source/extensions/quic_listeners/quiche/platform/flags_list.h, test/extensions/quic_listeners/quiche/envoy_quic_client_session_test.cc, test/extensions/quic_listeners/quiche/envoy_quic_client_stream_test.cc, test/extensions/quic_listeners/quiche/envoy_quic_server_session_test.cc, test/extensions/quic_listeners/quiche/envoy_quic_server_stream_test.cc, test/extensions/quic_listeners/quiche/test_utils.h
Update QUICHE to commit 4f6ba16cf16505f12dc8d2f23cfc6e13c1aa5806
Testing: existing test
=> quiche: update tar

bazel/repository_locations.bzl
Signed-off-by: Ryan Burn <ryan.burn@gmail.com>
Updates the lightstep dependency to fix issue on aarch64
=> tracing: Fix issue on aarch64

docs/root/configuration/http/http_filters/fault_filter.rst
Signed-off-by: Rafal Augustyniak <raugustyniak@lyft.com>
Description: Fixing a typo in docs
Testing: None
Release Notes: Docs change
=> Fix typo in docs

api/envoy/api/v2/route/route_components.proto, api/envoy/config/route/v3/route_components.proto, generated_api_shadow/envoy/api/v2/route/route_components.proto, generated_api_shadow/envoy/config/route/v3/route_components.proto
Signed-off-by: Yan Xue <yxyan@google.com>
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> update retry_policy_typed_config field

test/integration/protocol_integration_test.cc
Fixes the test flake, tested 10k times by both me and yavlasov@ 
Fixes https://github.com/envoyproxy/envoy/issues/10180
=> [test] fix protocol integration test flake

docs/root/intro/version_history.rst
=> docs: merge 1.13.1 and 1.12.3 release note to master
