envoyproxy/envoy

tools/base/BUILD, tools/base/bazel_query.py
Commit Message: bazel: Add implementation of ABazelQuery
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel: Add implementation of ABazelQuery

docs/root/version_history/current.rst
While working on a feature and adding release notes for it, I noticed that there is a duplicate entry and also some minor typos here and there. This is a small clean-up PR to remove the duplicate entry and correct the typos.
**Commit Message:** de-dupe current version history entries and address some minor typos.
**Additional Description:** De-dupes the duplicate entires in the current version's history file and also address some minor typos/issues.
**Risk Level:** None
**Docs Changes:** De-duped the duplicate entries and fixed typos etc.
**Release Notes:** Fixed
**Signed-off-by:** Rohit Agrawal <rohit.agrawal@databricks.com>
=> fix: De-dupe current version history entries and address some minor typos

configs/encapsulate_in_http1_connect.yaml, configs/encapsulate_in_http2_connect.yaml, configs/encapsulate_in_http2_post.yaml
curl somehow accepts `--x` while specifying proxy. 
It attempts to use proxy once and then not using proxy.
curl version: 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0
tl;dr 2 request are initiated
* Rebuilt URL to: 127.0.0.1:10000/
* Rebuilt URL to: http://hey/
```
$ curl -vvv --x 127.0.0.1:10000  http://hey
* Rebuilt URL to: 127.0.0.1:10000/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 10000 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:10000
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-type: text/plan
< Date: Fri, 17 Sep 2021 04:54:08 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
Hello Node JS Server Response
* Connection #0 to host 127.0.0.1 left intact
* Rebuilt URL to: …
```
=> doc: fix curl command in http connect tunnel example

docs/root/intro/deployment_types/double_proxy.rst, docs/root/intro/deployment_types/front_proxy.rst
Commit Message: in docs urls are pointing back to originals page for below mentioned deployments.(for text "**See **here** for more information.**")
Front_Proxy - https://www.envoyproxy.io/docs/envoy/latest/intro/deployment_types/front_proxy#configuration-template and
Double_Proxy - https://www.envoyproxy.io/docs/envoy/latest/intro/deployment_types/double_proxy#configuration-template
Additional Description: the changes done after release v1.16.0
Testing: Local
Release Notes:
=> correcting urls in deployment types docs

source/extensions/filters/http/grpc_stats/grpc_stats_filter.cc
This makes a tiny change by removing wrong comment for closing brace.
It is not namespace's closing brace but class's.
Testing: n/a
=> Fix wrong comment for closing brace

source/server/server.cc
Signed-off-by: Pradeep Rao <pcrao@google.com>
Defensively keep RefCountPtrs to stats around during the flush, guarding against stat deletions on the worker thread. Stats allocated with ThreadLocalStore are always deleted on the main thread after being cleared from the TLS caches, so this is not a problem in practice, but it does make sense to hold onto a shared-ptr in the sink.
Note that this is a transient state -- in a future PR the intermediate vectors can be dropped and lambda functions can be used to process all the sinked stats.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
=> Keep snapped stats in MetricSnapshotImpl.

test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
Testing the first-resolve-fail case to make sure it fails cleanly (until-if we clean up DFP cache)
Risk Level: n/a 
Testing: ues
cc @mattklein123 @conqerAtapple
=> dfp: adding failed resolution test

tools/protodoc/protodoc.bzl
Commit Message: docs: Small optimization for protodoc
this is a small optimization that removes non-envoy rst files from the output depset of protodoc
this makes the api tarball smaller and allows the downstream code to not have to filter these out
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: Small optimization for protodoc

docs/root/version_history/current.rst, source/extensions/filters/network/client_ssl_auth/client_ssl_auth.cc, test/extensions/filters/network/client_ssl_auth/client_ssl_auth_test.cc
Currently, `client_ssl_auth` does not set any response flags or any other additional details while terminating the condition due to `auth_digest_no_match` error which occurs when the SSL certificate coming from the client is not in the allowed-list of principals.
**Motivation:** [See This](https://github.com/envoyproxy/envoy/issues/17847)
This PR adds the response flag of `UAEX` and also sets `auth_digest_no_match` in the additional response details when the above mentioned conditions occur. 
---
**Commit Message:** set additional termination details and response flag for auth_digest_no_match in client_ssl_auth
**Additional Description:** See Background Section.
**Testing:** Unit Tests …
=> filter: set additional termination details and response flag for auth_digest_no_match in client_ssl_auth

ci/upload_gcs_artifact.sh, docs/build.sh
Commit Message: docs: Fix build rst/html script
fix the docs build script to only build html *or* rst, by default
also fixes the commit sha so that the docs are pushed with the correct tag
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: Fix build rst/html script

ci/do_ci.sh
Commit Message: ci: fixing api_compat post-job cache issue
Fixing the api_compat CI post-job cache failure (example: https://dev.azure.com/cncf/envoy/_build/results?buildId=89129&view=logs&j=34589ac8-7a1a-5ab1-7ee8-e202f4bf08f2&t=ac8660cc-f6a7-43c2-8464-358529887f90&l=65)
Risk Level: Low - CI only.
Testing: None.
Docs Changes: None.
Platform Specific Features: None.
Partially fixes: #18211
=> ci: fixing api_compat post-job cache issue

source/common/common/thread.cc, source/common/common/thread.h, source/common/network/address_impl.cc, test/common/thread_local/thread_local_impl_test.cc
https://github.com/envoyproxy/envoy/pull/16122 added asserts to utilities to make sure they were called from the correct thread.
Over on the Envoy mobile side when we do QUIC we're doing it from the main thread, and failing some of the assert checks.
I think the right thing to do here is just remove the assert
This is the only use of isWorkerThread()  so I'm inclined to just remove it.
cc @goaway 
Testing: n/a
Docs Changes:  n/a
=> network: remove an assert

api/envoy/extensions/upstreams/http/v3/http_protocol_options.proto, source/common/http/conn_pool_grid.cc, source/common/upstream/cluster_manager_impl.cc, source/extensions/upstreams/http/config.cc, test/common/http/conn_pool_grid_test.cc, test/common/upstream/upstream_impl_test.cc, test/extensions/upstreams/http/config_test.cc, test/integration/multiplexed_upstream_integration_test.cc, test/integration/multiplexed_upstream_integration_test.h
upstream: Make the Alt-Svc cache configuration required if HTTP/3 is enabled with AutoHttpConfig.
=> upstream: Make the Alt-Svc cache configuration required if HTTP/3 is enabled with AutoHttpConfig.

ci/do_ci.sh
Commit Message: bazel: Add build options for su-exec
When checking that bazel commands had been added correctly in ci, i noticed that this build command is missing build options
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel: Add build options for su-exec

ci/Dockerfile-envoy-windows
Signed-off-by: Sotiris Nanopoulos <sonanopo@microsoft.com>
Windows sets an expiration date on password of users even
when the password is empty. This prevents running the container
as EnvoyUser after the expiration.
Risk Level: Low, this only affects unpublished images
=> Fix issue where EnvoyUsers password expires

source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc
Signed-off-by: James Heppenstall <james.heppenstall@mongodb.com>
**Commit Message:** proxy_protocol: fix IOCallResult error checks
**Additional Description:** There are two redundant `result.ok()` checks in `Envoy::Extensions::ListenerFilters::ProxyProtocol::readProxyHeader`. It appears that these are typos and the checks should instead be `read_result.ok()`.
**Testing:** Manual
=> proxy_protocol: fix IOCallResult error checks

source/extensions/common/dynamic_forward_proxy/dns_cache.h, source/extensions/common/dynamic_forward_proxy/dns_cache_manager_impl.cc, source/extensions/common/dynamic_forward_proxy/dns_cache_manager_impl.h, test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc, test/extensions/common/dynamic_forward_proxy/mocks.h
Commit Message: dns cache manager - lookup cache by name
Additional Description: the existing lookup function, which requires a config object, is not ergonomic in places where synthesizing such a config is convoluted.
Risk Level: low - new API
Co-Authored-By: Mike Schore <mike.schore@gmail.com>
=> dns cache manager: lookup cache by name

tools/protoxform/protoprint.py
On OSX with `clang-format` 12.0.1 and `clang-format-11` installed elsewhere with `CLANG_FORMAT=/usr/local/opt/llvm@11/bin/clang-format`, I noticed that `tools/proto_format/proto_format.sh fix` produced an odd diff on `api/envoy/extensions/filters/http/jwt_authn/v3/config.proto`.
After some digging, I found that protoprint.py was invoking clang-format directly instead of consulting `CLANG_FORMAT`. This PR fixes that behavior, taking precedent from `tools/code_format/check_format.py`
Commit Message: tools: fix protoprint to respect CLANG_FORMAT env var
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tools: fix protoprint to respect CLANG_FORMAT env var

envoy/network/socket.h
Commit Message: Remove useless comment for ConnectionInfoProvider
Already finished the rename task, so remove that comment.
Testing: N/A
=> Remove useless comment for ConnectionInfoProvider

BUILD, bazel/README.md
This is a minor quality of life improvement to just be able to run
`bazel build envoy`
=> bazel: add root `envoy` alias

source/common/quic/codec_impl.cc, source/common/quic/codec_impl.h, test/integration/multiplexed_integration_test.cc, test/integration/protocol_integration_test.cc
Fixing client side goaways to send (in opt mode) rather than crash.
In debug mode, this unfortunately still crashes due to an upstream quiche perspective check, so commenting that out and adding a TODO.
Fixes https://github.com/envoyproxy/envoy/issues/12930
=> http3: sending goaways

source/extensions/filters/common/ratelimit/ratelimit_impl.cc, source/extensions/filters/http/ratelimit/ratelimit.cc
Commit Message: add ratelimt log
add some log to help debug ratelimt filter, in following cases specially:
- ratelimt Status Error due when timeout was set to small, refer to [istio PR](https://github.com/istio/istio/pull/33937)
- call grpc server onFailure
Testing: manual testing
Docs Changes: 
Release Notes:
=> filter: add ratelimit log

source/common/network/connection_impl.cc, test/common/network/connection_impl_test.cc
=> network: set failure reason for transport socket connect timeout

source/common/upstream/thread_aware_lb_impl.cc, source/common/upstream/thread_aware_lb_impl.h, test/common/upstream/maglev_lb_test.cc, test/common/upstream/ring_hash_lb_test.cc, test/config/utility.cc, test/config/utility.h, test/integration/cds_integration_test.cc
Commit Message: fix possible use-after-free introduced by the cross-priority host map updates in the thread aware lb
Fixes commit #17848
Fix #18250.
=> fix possible use-after-free introduced by the cross-priority host map updates in the thread aware lb

test/server/guarddog_impl_test.cc
This is a clone of https://github.com/envoyproxy/envoy/pull/18252 but with the formatting fixed.
Risk Level: None - test only
Testing: N/A
=> coverage: exclude a guarddog test from coverage

source/common/config/subscription_factory_impl.cc, source/common/config/type_to_endpoint.cc, source/common/config/type_to_endpoint.h, test/common/config/type_to_endpoint_test.cc
=> subscription: cleaning up unused argument

source/common/signal/signal_action.cc, tools/spelling/spelling_dictionary.txt
According to https://reviews.llvm.org/D28265 using `sigaltstack` with
`backtrace()` (which absiel uses internally to get stack trace info) is
not compatible. Using them together results in crashes in tests not
printing backtraces only on macOS
https://github.com/envoyproxy/envoy-mobile/issues/1827
=> Disable sigaltstack on Apple platforms

bazel/repository_locations.bzl
Commit Message: bazel: Fix rules_go release date
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel: Fix rules_go release date

source/common/protobuf/utility.cc, test/common/protobuf/utility_test.cc, test/proto/sensitive.proto
Signed-off-by: Paul Gallagher <pgal@google.com>
Commit Message: proto: handle maps correctly in `redact`.
Additional Description: Currently, when a map is marked as sensitive, `redact` will turn every key into the string "[redacted]", thereby invalidating the map. This change causes the map to only have values converted to "[redacted]".
Testing: unit tested.
Docs Changes:
Release Notes:
=> proto: Handle maps correctly in `redact`.

bazel/README.md
Commit Message: doc: adjust the order of paths in the env variable %PATH% for windows
Ensure the bazel reference the correct command from the path.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> doc: adjust the order of paths in the env variable %PATH% for windows

source/common/http/BUILD, source/common/http/alternate_protocols_cache_impl.cc, source/common/http/alternate_protocols_cache_impl.h, source/common/http/alternate_protocols_cache_manager_impl.cc, test/common/http/alternate_protocols_cache_impl_test.cc, test/common/http/conn_pool_grid_test.cc
alternate_protocols_cache: Impose a max size limit on the alternate protocols cache
Implement a very basic MRU map in AlternateProtocolsCacheImpl.
=> alternate_protocols_cache: Impose a max size limit on the alternate protocols cache

source/extensions/filters/http/grpc_http1_bridge/BUILD, test/extensions/filters/http/grpc_http1_bridge/BUILD, test/extensions/filters/http/grpc_http1_bridge/grpc_http1_bridge_integration_test.cc, test/integration/BUILD, test/integration/integration_test.cc
Commit Message: n/a
Testing: n/a
Part of #9953
=> test: moving grpc bridge tests out of core directory

test/integration/multiplexed_integration_test.cc
Commit Message: [test] Fixing integration test to cleanup cleanly
Fixing the DownstreamSendingEmptyMetadata integration test to cleanup cleanly by closing the upstream connection before closing the client.
Risk Level: Low - tests only.
Testing: Fixed a current test.
Part of the fix of #18290.
=> [test] Fixing integration test to cleanup cleanly

source/common/signal/signal_action.cc, source/common/signal/signal_action.h
Commit Message: signal action - fully disable sigaltstack on Apple
Additional Description: follow up from #18251 
Risk Level: low - follow up on previous PR
Platform Specific Features: only affects apple platforms
=> signal action: fully disable sigaltstack on Apple

source/extensions/common/dynamic_forward_proxy/dns_cache_manager_impl.cc
Commit Message: dns cache: remove assert at this layer
Additional Description: Envoy Mobile has logic that executes on the main thread but may not have the necessary state to pass this assertion. This change maintains the existing convention that callers of the DNS cache manager should validate their thread context independently.
Testing: Local & CI
Signed-off-by: Mike Schore <mike.schore@gmail.com>
=> dns cache: remove main thread assert in cache lookup

source/common/router/scoped_rds.cc, source/common/upstream/conn_pool_map.h, source/common/upstream/conn_pool_map_impl.h, source/extensions/access_loggers/common/grpc_access_logger.h
Return bool type on empty() function per  https://github.com/envoyproxy/envoy/pull/18057#discussion_r708253723
With the stacked clean up.
Docs Changes:
Release Notes:
=> cleanup: various tiny cleanup

source/common/quic/codec_impl.cc
Upstream merge made goaways work in debug mode as well.
Testing: yes
=> quic: updating goaway code

.github/workflows/check-deps.yml, tools/dependency/release_dates.py, tools/dependency/release_dates.sh, tools/shell_utils.sh
Commit Message: added action to take a closer look of deps release
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> create issue via github action for stale deps #16705

test/test_common/environment.cc
absl implements this for apple platforms as well, it's just a no-op.
=> Remove unnecessary #ifdef

source/common/config/delta_subscription_state.cc, source/common/config/xds_mux/delta_subscription_state.cc, test/common/config/delta_subscription_state_test.cc
Signed-off-by: Xin Zhuang <stevenzzz@google.com>
Commit Message: Only track a resource in delta subscriptionState when there are subscriptions interested in it.
Risk Level: LOW ( the extra tracked resources will be removed, but they are "invisible" to non-wildcard xDSes anyway.
Testing: unit tests added.
Docs Changes:
Release Notes:
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/18292
=> Only track subscribed resources in Delta subscription state

envoy/singleton/manager.h, test/common/singleton/manager_impl_test.cc
Commit Message: singleton manager - overload getTyped with non-constructing version
Additional Description: allows uses of the singleton manager where constructing is not viable, but using an existing singleton is
Risk Level: low. new api
=> singleton manager: overload getTyped with non-constructing version

bazel/envoy_internal.bzl
With `--config=linux` we enable `per_object_debug_info`, which passes
this flag, so we don't also need to pass it here, otherwise you cannot
build without split debug info.
I verified with aquery that this arg is still passed, just only once now
=> bazel: remove duplicate -gsplit-dwarf argument

bazel/foreign_cc/BUILD
On macOS the value of `CMAKE_AR` is actually `libtool` which has an
entirely different interface. This works with rules_foreign_cc because
it takes the correct flags from the cc toolchain for `libtool` and tells
cmake to use those.
When using `CMAKE_TRY_COMPILE_TARGET_TYPE` cmake does a test of
compiling a file where it respects `CMAKE_AR`, but doesn't respect
`CMAKE_C_ARCHIVE_CREATE` which is what rules_foreign_cc uses to override
the args. This resulted in a argument mismatch where `ar` args would be
passed to `libtool`, and if we set `CMAKE_AR` back to `/usr/bin/ar`,
when the actual build happened, not just this test, it would be passed
`libtool` args instead.
I don't think removing this should cause problems, since it's just an
early warning sign in the build.
Signed-off-by: Keith …
=> bazel: Remove CMAKE_TRY_COMPILE_TARGET_TYPE from libsxg

bazel/envoy_internal.bzl, source/extensions/common/dynamic_forward_proxy/BUILD, source/extensions/common/dynamic_forward_proxy/dns_cache_manager_impl.cc, source/extensions/common/dynamic_forward_proxy/dns_cache_manager_impl.h, source/server/factory_context_base_impl.h, test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc
Make sure the DNS code can handle the creating factory (and context) being destroyed before the DNS cache.
=> dns: fix lifetime issue with local context

.azure-pipelines/pipelines.yml
Unfortunately, a change in the flags or behavior of the bazel 4.2.1
release has caused a regression in the ability to compile grpc under clang-cl.
The primary output of envoy-static.exe is generated by MSVC, the clang-cl
alternative is an observation point to see what the MS compiler might be
doing wrong based on our general clang compiler development strategy.
At the moment, it is a blocker.
This patch should be reverted once we've uncovered what's changed with
bazel 4.2.1; this isn't entirely on the compiler, the same error occurs on 
clang-cl versions 11 and 12, not on msvc, and does not occur in clang for linux.
See issue https://github.com/envoyproxy/envoy/issues/18407
Signed-off-by: William A Rowe Jr <wrowe@vmware.com>
Risk Level:
Testing: …
=> Drop clang-cl compilation target for the time being

bazel/repository_locations.bzl
Update ipp-crypto to 2021.4 release.
Testing: Ran the code + basic perf tests on Xeon Scalable Gen 3.
Fixes #18384
=> Update ipp-crypto to 2021.4 release.

tools/dependency/release_dates.py
Signed-off-by: Tarun Sharma <starun.1998@gmail.com>
Following up for the https://github.com/envoyproxy/envoy/pull/17876#issuecomment-931047255
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Create Issue with more clear title and body

tools/gen_compilation_database.py
This ensures that the compdb treats Envoy source code as C++ in case it is pulled in as an external repo, allowing this code
to be reused by repos that depend on Envoy. This also conveniently match envoy-mobile. 
Testing: Manual testing
=> tools: improve support for using compdb script from subrepos 

bazel/repository_locations.bzl
Commit Message: deps: Bump `com_github_nlohmann_json` -> 3.10.2
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fix #18330
=> deps: Bump `com_github_nlohmann_json` -> 3.10.2

bazel/repository_locations.bzl
Commit Message: deps: Bump `com_github_google_flatbuffers` -> 2.0.0
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fix #18324
=> deps: Bump `com_github_google_flatbuffers` -> 2.0.0

source/common/common/fancy_logger.cc, source/common/common/logger.cc, source/common/common/logger.h, test/common/common/logger_test.cc
This adds support for specifying a SinkDelegate that should be active
only on the current thread. This allows for per thread overrides of the
logging context, which opens up for overriding the logger for the
duration of a dispatcher event as well as overriding the logger for
specific function calls.
Testing: New UTs, benchmarks
=> common: add support for thread local sink overrides

docs/root/configuration/observability/application_logging.rst
According to GKE's fluent-bit config, logs should be of the format `^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source_file>[^ \]]+)\:(?<source_line>\d+)\]\s(?<message>.*)$`. (I found it by running `kubectl describe cm fluentbit-gke-config-v1.0.6 -n kube-system` on my GKE cluster.)
The example in doc lacks `\:(?<source_line>\d+)` part, so I added it.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Fix --log-format example to conform to glog format

api/envoy/extensions/formatter/metadata/v3/metadata.proto, docs/root/configuration/observability/access_log/usage.rst
Signed-off-by: Peter Jausovec <peter.jausovec@gmail.com>
Commit Message: Fix typo (remove extra word)
Additional Description: Removes an extra word in the docs
Docs Changes: Removes an extra word
=> Fix typo (remove extra word)

envoy/network/socket.h
Commit Message: The copy assignment operator is being invoked for `SocketOptionName` implicitly. Explicitly request it.
Testing: NA
It seems to be breaking for Clang 14. See:
```
Step #3 - "compile-afl-address-x86_64": [1m./envoy/network/socket.h:26:3: [0m[0;1;31merror: [0m[1mdefinition of implicit copy assignment operator for 'SocketOptionName' is deprecated because it has a user-declared copy constructor …
```
=> Minor: Request copy assignment operator.

.bazelrc, docs/root/version_history/current.rst
gperftools_tcmalloc is not compatible with macOS 12, resulting in a
crash on startup. The crash happens very early, before CLI args are
parsed.
Fixes #17535
(cherry picked from commit b9939c6f8045b12b98933ffdf3d9f2eacd9cf38e)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Fix crash-on-startup on macOS 12 (#18779)

configs/encapsulate_in_http2_connect.yaml, docs/root/version_history/current.rst, source/common/tcp_proxy/upstream.cc, source/common/tcp_proxy/upstream.h, test/common/tcp_proxy/upstream_test.cc, test/extensions/upstreams/tcp/generic/config_test.cc, test/integration/tcp_tunneling_integration_test.cc
This allows to generate tcp proxy's upstream CONNECT header values using downstream info.
Examples include modifying the host/:authority headers
Or emulate the proxy protocol via CONNECT as in the test cases.
Use with caution: a RFC in-compliant upstream header can be introduced because stream info may carry arbitrary bytes. 
Risk Level: LOW 
Testing:
Docs Changes:
Release Notes:
Fixes #18128
=> tcp_proxy: add support to evaluate downstream info at tunnel setting

OWNERS.md, RELEASES.md
=> docs: updating backports docs to reflect recent process and new setec folks

test/integration/BUILD, test/integration/multiplexed_integration_test.cc
See https://github.com/envoyproxy/envoy/issues/18881.
temporarily disable until i figure out a fix
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [ci] disable multplexed integration test for coverage temporarily

docs/root/version_history/current.rst, source/common/config/grpc_stream.h, test/common/config/grpc_stream_test.cc
config: adjust "gRPC config stream closed" log message (#18533)
backport of c35ff419e3b4fe3f7e6deae08e6e329cf91ba5b5
Signed-off-by: Taylor Barrella <tabarr@google.com>
Testing: Unit
=> [v1.20 backport] config: adjust "gRPC config stream closed" log message

contrib/rocketmq_proxy/filters/network/source/protocol.h
Commit Message: rocketmq_proxy: Simplify the conversion for absl::string_view
Testing: N/A
=> Simlify convertion from absl string_view

source/common/common/logger.cc, source/common/common/logger.h, source/common/common/logger_delegates.cc, source/common/common/logger_delegates.h, test/common/common/logger_test.cc, test/test_common/logging.cc, test/test_common/logging.h
Commit Message: This allows sinks to inspect the log line details without parsing the formatted message.
Testing: New UTs
=> logging: include spdlog log_msg in log to SinkDelegate

source/common/http/http3/conn_pool.cc, source/common/quic/quic_transport_socket_factory.h, test/common/http/http3/conn_pool_test.cc
Commit Message: quic: test fast-fail if secrets not loaded when create quic connection  
Testing:  N/A
=> quic: test fast-fail if secrets not loaded when create quic connection

source/common/quic/envoy_quic_client_session.cc
moving to an accessor now that it exists.
Testing: n/a (existing tests apply)
=> quic: post-import TODO cleanup

source/common/grpc/typed_async_client.h
Commit Message: The copy assignment operator is being invoked for `AsyncStream` implicitly. Explicitly request it.
Detected due to a fuzz build failure when using clang 14.
Testing: N/A.
Platform Specific Features: N/A. 
=> Minor: adding copy assignment operator for AsyncStream

bazel/external/wee8.genrule_cmd
I'm not sure what changed here but it seems chromium attempts to use lld
on macOS even though it doesn't ship with Xcode. This could be
intentional on their part if they require folks to use an llvm toolchain
instead, but this likely isn't the right move for envoy unless we vendor
that toolchain ourselves. For now we can safely disable this.
https://github.com/envoyproxy/envoy/issues/16482#issuecomment-962372629
=> bazel: disable lld on macOS

bazel/external/wee8.genrule_cmd
I don't know gn well enough to know how this is used, but it seems like
both macOS architectures should point to this.
=> bazel: use mac ninja on arm64

docs/root/version_history/current.rst, source/common/runtime/runtime_features.cc, test/common/json/BUILD, test/common/json/json_fuzz_test.cc, test/common/router/header_formatter_test.cc, test/per_file_coverage.sh
We added the code to switch json libraries over in https://github.com/envoyproxy/envoy/pull/14467
The removal is tracked by https://github.com/envoyproxy/envoy/issues/4705 and smoke tested (https://github.com/envoyproxy/envoy/issues/18451)
Risk Level: Medium for folks using json
Testing: n/a
Fixes https://github.com/envoyproxy/envoy/issues/18451
=> runtime: flipping envoy.reloadable_features.remove_legacy_json

source/extensions/network/dns_resolver/cares/dns_impl.cc
Additional Description: it would be useful to see c-ares status when the callback is called.
Risk Level: low - debug log
=> c-ares dns: add log on failure

source/common/conn_pool/conn_pool_base.cc, source/common/http/http3/conn_pool.cc, source/common/quic/codec_impl.h, source/common/quic/envoy_quic_client_session.cc, test/common/conn_pool/conn_pool_base_test.cc, test/integration/BUILD, test/integration/fake_upstream.cc, test/integration/fake_upstream.h, test/integration/quic_http_integration_test.cc
Risk Level: Medium (conn pool refactors)
Testing: unit, integration
=> quic: supporting connections with zero initial available streams

api/envoy/service/discovery/v2/ads.proto, api/envoy/service/discovery/v3/ads.proto, api/envoy/service/endpoint/v3/leds.proto
Commit Message: remove unnecessary file level 'not unimplemented hide' annotation
Remove the unnecessary file level 'not-implemented-hide' annotation. I found these annotations during the development of PR #18923 . But it seems that they should not have this annotation.
If this is a misunderstanding on my part, please close this PR.
Risk Level: Doc Only.
Testing: N/A.
=> remove unnecessary file level not unimplemented hide annotation

tools/dependency/BUILD, tools/dependency/cve.yaml, tools/dependency/cve_scan.py
This moves the ignore and configuration data to a separate yaml file, which will make it easier to push the cve scanner to a library
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> cvescan: Move cvescan data to yaml

source/common/grpc/BUILD, source/common/grpc/async_client_manager_impl.cc, source/common/grpc/async_client_manager_impl.h, test/common/grpc/BUILD, test/common/grpc/async_client_manager_impl_test.cc
Commit Message: As we are migrating to cache raw async grpc client, it is necessary to evict unused client to prevent the size of the cache to grow infinitely.
Testing: Some test to verify the behavior.
Docs Changes:NA
Release Notes:NA
Platform Specific Features:NA
=> grpc: Use lru cache for grpc raw async client

test/extensions/transport_sockets/starttls/starttls_integration_test.cc
I don't _think_ this test server assert adds value, and it's flaking horribly on CI today.
changes from failing 16:200 to passing 100%
Testing: yep
=> test: deflaking starttls test

test/common/http/http2/http2_frame.cc, test/common/http/http2/http2_frame.h
Signed-off-by: Dianna Hu <diannahu@google.com>
Commit Message: Fix test-only Http2Frame to send the ":authority" pseudoheader instead of "host" for requests.
Additional Description: This change enables tests using Http2Frame to comply with the "SHOULD" suggestion of the HTTP/2 specification: https://httpwg.org/specs/rfc7540.html#HttpRequest.
Testing: //test/integration:http2_flood_integration_test //test/integration:h2_capture_fuzz_test //test/integration:h2_capture_persistent_fuzz_test //test/integration:h2_capture_direct_response_fuzz_test //test/integration:h2_capture_direct_response_persistent_fuzz_test
Docs Changes:
Release Notes: …
=> Fix test-only Http2Frame: host -> :authority.

source/common/http/http1/codec_impl.cc, test/integration/http_protocol_integration.cc, test/integration/protocol_integration_test.cc
Commit Message: Fix H1 byte counting due to not correctly moving the bytes meter to the stream when the stream starts.
Additional Description: We ended up invoking the copy constructor and not the move constructor => the connection level byte meter sticks before stream starts ends up accumulating bytes
Testing: integration tests using multiple req / response
=> H1: Byte Counting Fix

.bazelrc
Commit Message: Use `--experimental_allow_tags_propagation` with bazel.
Additional Description: This allows tags to influence execution requirements. There is already one use of `no-remote` in this repo, but this is also needed by envoy-mobile, so I thought it was best to add here.
Testing: Local builds.
=> bazel: Use `--experimental_allow_tags_propagation`

test/integration/quic_http_integration_test.cc
quic: Disable flaky test QuicHttpIntegrationTest.AdminDrainDrainsListeners while we work on a fix to the underlying issue.
Testing: N/A
=> quic: Disable QuicHttpIntegrationTest.AdminDrainDrainsListeners

bazel/external/wee8.genrule_cmd, bazel/external/wee8.patch, bazel/repository_locations.bzl
=> wasm: update V8 to v9.6.180.12.

contrib/vcl/source/vcl_event.cc
=> vcl: remove extraneous cb call in event activate

docs/root/operations/admin.rst
Signed-off-by: Peter Jausovec <peter.jausovec@gmail.com>
Commit Message: Fix a typo in admin interface documentation
=> Fix a typo in admin interface documentation

test/integration/integration_test.cc, test/integration/protocol_integration_test.cc
Commit Message: Cleanup: remove unnecessary newlines in useAccessLog.
Additional Description: `BaseIntegrationTest::waitForAccessLog` expects one newline per access log so if the 2nd entry was waited for with an access log string ending in "\n" it'd return earlier than expected.
Testing: Ran tests
Release Notes:NA
=> Cleanup: remove unnecessary newlines in useAccessLog strings.

docs/root/intro/arch_overview/other_protocols/redis.rst
Known large scale production use.
Testing: N/A
Docs Changes: Doc only
=> redis cluster: remove experimental from docs

source/common/formatter/substitution_formatter.cc, source/common/protobuf/utility.cc, source/common/protobuf/utility.h, test/common/protobuf/utility_test.cc
Commit Message: Currently FilterStateFormatter::formatValue is converting ProtobufTypes::Message to ProtobufWkt::Value through intermediate json string format, which is not efficient and may throw exception in data plane. Add serializeAsProtoValue virtual method to do the conversion directly.
Additional Description: NA
Testing: NA
=> [filter state]: make jsonConvert no throw

test/common/access_log/access_log_impl_test.cc, test/common/formatter/substitution_formatter_fuzz_test.cc, test/common/formatter/substitution_formatter_speed_test.cc, test/common/router/header_parser_fuzz_test.cc, test/common/stream_info/test_util.h, test/extensions/access_loggers/open_telemetry/substitution_formatter_speed_test.cc, test/extensions/filters/common/expr/evaluator_fuzz_test.cc, test/extensions/filters/network/mongo_proxy/proxy_test.cc, test/fuzz/utility.h
Every update to the stream into interface requires updates to the impl, the mocks, and the test class. Making the test class inherit from the impl to reduce churn.
Risk Level: n/a  (test only)
Testing: n/a
Clean up for https://github.com/envoyproxy/envoy-mobile/issues/1520
=> stream_info: removing redundant test code.

docs/root/faq/extensions/contract.rst
=> docs: update contract reference

api/envoy/extensions/filters/http/aws_request_signing/v3/BUILD, api/envoy/extensions/filters/http/aws_request_signing/v3/aws_request_signing.proto, docs/root/configuration/http/http_filters/aws_request_signing_filter.rst, docs/root/version_history/current.rst, source/extensions/common/aws/BUILD, source/extensions/common/aws/signer_impl.cc, source/extensions/common/aws/signer_impl.h, source/extensions/common/aws/utility.cc, source/extensions/common/aws/utility.h, source/extensions/filters/http/aws_lambda/config.cc, source/extensions/filters/http/aws_request_signing/BUILD, source/extensions/filters/http/aws_request_signing/config.cc, source/extensions/grpc_credentials/aws_iam/config.cc, test/extensions/common/aws/signer_impl_test.cc, test/extensions/common/aws/utility_test.cc, test/extensions/filters/http/aws_request_signing/config_test.cc
This change extends the [AWS Request Signing filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/aws_request_signing_filter) with an optional list of header exclusions (implemented as a list of StringMatchers) named `match_excluded_headers`. This allows configuring certain headers to not be signed and addresses the issue in https://github.com/envoyproxy/envoy/issues/18695.
I also took the opportunity to move the existing hard-coded rules for skipping certain header signings from the signing method itself to the initialization of a signer.
Testing: Updated unit test cases
Docs Changes: Added description of the new field and updated the example filter configuration with the new field.
Release Notes: …
=> aws_request_signing: extend api to allow excluding headers from signing

source/common/conn_pool/conn_pool_base.cc, source/common/http/conn_pool_base.cc, test/common/http/http2/conn_pool_test.cc
Commit Message: http2: transist READY client to busy when SETTING decreases the capacity
Additional Description:  fixes part I of #18880
Risk Level:  low
Testing: unit
=> http2: transist READY client to busy when SETTING decreases the capacity

docs/root/version_history/current.rst, envoy/http/codec.h, source/common/http/header_utility.cc, source/common/http/http1/codec_impl.cc, source/common/http/http2/codec_impl.cc, source/common/router/router.cc, source/common/runtime/runtime_features.cc, test/common/http/http1/codec_impl_test.cc, test/common/http/http2/codec_impl_test.cc, test/common/quic/envoy_quic_client_stream_test.cc, test/integration/http_integration.cc, test/integration/http_integration.h, test/integration/integration_stream_decoder.cc, test/integration/integration_stream_decoder.h, test/integration/multiplexed_integration_test.cc, test/integration/protocol_integration_test.cc
Proxying 102s from upstream
Risk Level: Low (minor refactor)
Runtime guard: envoy.reloadable_features.proxy_102
Fixes https://github.com/envoyproxy/envoy/issues/18844
=> http: proxying 102s.

source/server/admin/prometheus_stats.cc, test/server/admin/prometheus_stats_test.cc
Commit Message: stats(prometheus): escape problematic chars in text serialization
This PR attempts to address https://github.com/envoyproxy/envoy/issues/18589 and https://github.com/istio/istio/issues/35575 by adding escaping logic to the prometheus stats code. An attempt was made to mirror the logic in the prometheus common golang code for text serialization.
Testing: Unit
Fixes #18589
Signed-off-by: Douglas Reid <douglas-reid@users.noreply.github.com>
=> stats(prometheus): escape problematic chars in text serialization

test/integration/multiplexed_integration_test.cc
Commit Message: ci: disable multplexed integration test for coverage temporarily
IpVersions/Http2MetadataIntegrationTest.ProxyInvalidMetadata/IPv4_Http2Downstream_Http2UpstreamWrappedHttp2 test fails often in coverage and compile_time_options builds.
Disable it for now.
Testing: run the failing test manually
Details in #19040
=> ci: disable multplexed integration test for coverage temporarily

test/extensions/filters/http/grpc_http1_reverse_bridge/reverse_bridge_integration_test.cc
the base class teardown has the order of destruction set up correctly to avoid crashes. Fixes a 6/5000 flake I'm seeing way more often on CI.
Testing: many runs
=> test: fixing a reverse bridge teardown flake

api/envoy/config/core/v3/protocol.proto, docs/root/version_history/current.rst, source/common/http/http2/codec_impl.cc, source/common/http/http2/codec_impl.h, source/common/runtime/runtime_features.cc, test/integration/http2_flood_integration_test.cc, tools/code_format/check_format.py
Remove envoy.reloadable_features.upstream_http2_flood_checks runtime override and legacy code paths.
Docs Changes: proto comments updated
Fixes #18449
=> Remove envoy.reloadable_features.upstream_http2_flood_checks and legacy code paths

docs/root/configuration/http/http_conn_man/headers.rst, docs/root/version_history/current.rst, source/common/router/header_formatter.cc, test/common/router/header_formatter_test.cc
This PR adds a new command operator in the header formatter called `%REQUESTED_SERVER_NAME%` which can be used to extract the SNI information from the stream and set it as a custom header. 
**Commit Message:** Added support for `%REQUESTED_SERVER_NAME%` to extract the SNI as a custom header.
**Additional Description:** Adds a new command operator called `%REQUESTED_SERVER_NAME%` in the http header formatter which can be used to extract the SNI information from the stream and set it as a custom header.
**Testing:** Unit Tests
**Docs Changes:** Added description on `%REQUESTED_SERVER_NAME%` in the docs.
**Signed-off-by:** Rohit Agrawal <rohit.agrawal@databricks.com>
=> http: added support for %REQUESTED_SERVER_NAME% to extract SNI as a custom header (Fixes #19024)

source/common/common/base64.cc, source/common/common/base64.h, source/common/config/grpc_mux_impl.cc, source/common/config/grpc_mux_impl.h
Signed-off-by: Tarun Sharma <starun.1998@gmail.com>
Commit Message:  replace std:string to absl::string
Additional Description: #11318
Testing: N/A
[Optional Fixes #Issue] N/A
[Optional Fixes commit #PR or SHA] N/A
[Optional Deprecated:] N/A
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):] N/A
=> replace std:string to absl::string

source/common/http/http1/codec_impl.cc, source/common/http/http1/codec_impl.h, test/common/http/codec_impl_fuzz_test.cc, test/common/http/http1/codec_impl_test.cc, test/integration/fake_upstream.cc
Commit Message: Refactor HTTP1 Active Request to be defer deletable
Additional Description: This will be helpful to enable us to safely remove the `ActiveStream` from being subscribed to the response encoder of the codec level stream. See https://github.com/envoyproxy/envoy/pull/18895#discussion_r752652736 for context.
Risk Level: low (refactor)
Testing: Ran tests
=> HTTP1: Refactor HTTP1 Active Request to be defer deletable.

envoy/stream_info/stream_info.h, source/common/stream_info/stream_info_impl.h, test/common/access_log/access_log_impl_test.cc, test/common/stream_info/stream_info_impl_test.cc, test/common/stream_info/test_util.h, test/fuzz/utility.h, test/mocks/stream_info/mocks.h
Refactoring upstream stream info into a shared pointer owned struct.
Testing: n/a
Refactors for https://github.com/envoyproxy/envoy-mobile/issues/1520
=> stream_info: reworking upstream data

api/envoy/extensions/filters/udp/udp_proxy/v3/udp_proxy.proto, docs/root/configuration/listeners/udp_filters/udp_proxy.rst, docs/root/version_history/current.rst, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h, test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc, tools/spelling/spelling_dictionary.txt
Signed-off-by: Michał Mąka <m.maka@partner.samsung.com>
Commit Message: udp_proxy: added per packet load balancing possibility which can be enabled via specifying 'use_per_packet_load_balancing' field
This feature adds possibility to have per packet load balancing in UDP proxy. Currently, there is kind of `sticky session`, which means that once data was forwarded to specific upstream host, the host is also used for subsequent messages if timeout does not occur.
By default, current behavior is used, but if `use_per_packet_load_balancing` configuration flag is set to true, on each data receival, new upstream host is selected and receives that data.
Testing: unit test, manual testing
Docs Changes: Introduced description of the feature and a way it …
=> udp_proxy: added per packet load balancing possibility

source/common/upstream/load_balancer_impl.cc
Signed-off-by: Hu Shuai <hus.fnst@fujitsu.com>
Commit Message: Fix a small typo
Additional Description: agression --> aggression
=> Fix a small typo

docs/root/configuration/http/http_filters/lua_filter.rst
Signed-off-by: Peter Jausovec <peter.jausovec@gmail.com>
Commit Message: Fix a broken example in Lua filter docs
Additional Description: Setting values in Lua is done using `=`, not `:`
Docs Changes: Fix the broken example
=> Fix a broken example in Lua filter docs

source/common/quic/envoy_quic_client_connection.cc
Commit Message: hard code prefer_gro to false. The performance of GRO hasn't been evaluated yet, so it shouldn't be default on.
=> quic: turn off GRO in client connection

source/common/stream_info/stream_info_impl.h
Commit Message: Remove requested_server_name field for StreamInfo
Since the requested_server_name was moved to ConnectionInfoProvider, this field is useless now.
Testing: n/a
=> Remove requested_server_name field for StreamInfo

bazel/repositories.bzl, bazel/repository_locations.bzl
Commit Message: Remove dependency - six
Additional Description: An internal 3pp scan reports that six version is older and a newer version is available. However as six is no longer used, attempting to remove the same
Testing: local build and pre checks done
=> dep: Remove dependency - six

tools/dependency/release_dates.py
Recently the kafka upstream dep released a new version for an older minor release (1.6.2)
This has caused a few problems with the release dates checker
This PR should fix an issue where it was falling back to using the commit date  rather than the release date
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tools: Fix dependency checker release dates bug

tools/dependency/release_dates.py
Commit Message: dep: Fix verify_and_print_latest_release logic
Additional Description: Fixes #19109 Fix #19136
Testing: local testing of the script done
=> dep: Fix verify_and_print_latest_release logic

docs/root/configuration/http/http_filters/lua_filter.rst, source/extensions/filters/common/lua/wrappers.cc, source/extensions/filters/common/lua/wrappers.h, source/extensions/filters/http/lua/lua_filter.cc, source/extensions/filters/http/lua/lua_filter.h, test/extensions/filters/common/lua/wrappers_test.cc, test/extensions/filters/http/lua/lua_integration_test.cc
Commit Message: This patch modifies body setBytes API to make the header content length can be set automatically, which can avoid error when you forget set header content length in lua script and make the setBytes API more convenient for users.
Testing: ut, integration
=> lua: support body setBytes with header content length set automatically

docs/root/version_history/current.rst, source/extensions/filters/http/ext_authz/ext_authz.cc, test/extensions/filters/http/ext_authz/ext_authz_test.cc
This fixes a bug in which the UAEX flag is not set prior to calling
`callback->sendLocalReply(...)`.
Commit Message: ext-authz: fix missing UAEX flag on Denied CheckResponse
Additional Description: See #18964
Release Notes: ext-authz: fix missing UAEX flag on Denied CheckResponse
Fixes #18964
=> ext-authz: fix missing UAEX flag on Denied CheckResponse

api/envoy/extensions/http/header_formatters/preserve_case/v3/preserve_case.proto, docs/root/version_history/current.rst, envoy/http/header_formatter.h, source/common/http/http1/codec_impl.cc, source/common/http/http1/codec_impl.h, source/common/http/http1/legacy_parser_impl.cc, source/common/http/http1/parser.h, source/extensions/http/header_formatters/preserve_case/preserve_case_formatter.cc, source/extensions/http/header_formatters/preserve_case/preserve_case_formatter.h, test/extensions/http/header_formatters/preserve_case/BUILD, test/extensions/http/header_formatters/preserve_case/preserve_case_formatter_reason_phrase_integration_test.cc, test/extensions/http/header_formatters/preserve_case/preserve_case_formatter_test.cc
Commit Message: http: extend StatefulHeaderFormatter to allow forwarding HTTP1 reason phrase
Additional Description: In some cases the upstream can produce a non-default reason phrase when using HTTP1. For example AWS S3 can return `503 Slow Down` in certain cases. StatefuleHeaderFormatter can now take an optional flag to enable forwarding non-default HTTP1 reason phrases.
Testing: unit testing, integration testing
Docs Changes: release notes
Release Notes: http: added support for forwarding HTTP1 reason phrase
=> Extend StatefulHeaderFormatter to allow forwarding HTTP1 reason phrase

bazel/repository_locations.bzl
Fixes #18816
Commit Message: Update boringssl version
As per the comment in #18816, grabbing BoringSSL version from Chromium 94.0.4606.81 should fix the build issue reported. I tried to pick the latest version as per https://omahaproxy.appspot.com/, and https://chromium.googlesource.com/chromium/src/+/refs/tags/98.0.4710.4/DEPS, however this revision of boring_ssl brings in a breaking change that needs some refactoring in SPIFFEValidator::doVerifyCertChain in envoy. Hence moved back to 94.0.4606.81 to align to the solution provided in the GitHub issue
Testing: Local build tested
=> Update boringssl version

docs/root/version_history/current.rst, source/server/listener_manager_impl.cc, test/server/listener_manager_impl_test.cc
This bug existed previously, but with the recent reuse port
as the default change is now more obvious. Previously, we would
allow multiple listeners to listen on the same port, which is
obviously very wrong. This change blocks that at config load time.
Fixes https://github.com/envoyproxy/envoy/issues/19099
Testing: New UT, the port 0 case is covered by integration tests
=> listener: disallow duplicate port specification

docs/root/version_history/current.rst, docs/root/version_history/v1.20.1.rst, docs/root/version_history/version_history.rst
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: Add 1.20.1 release notes to main

test/extensions/filters/http/cache/simple_http_cache/simple_http_cache_test.cc, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/utils.cc, test/extensions/filters/http/ext_proc/utils.h, test/test_common/utility.cc
Signed-off-by: Saidi Tang tangsaidi@google.com
Description: The `headerMapEqualIgnoreOrder` function didn't check the outcome of the `iterate` method. We are passing a few tests in `cache` and `ext_proc` with incorrect expected values. I fixed the comparison utility and updated the tests accordingly.
Commit Message: Added a flag variable to check whether the iterate function returned after a value mismatch for a key
Risk Level: Low, it's part of the test utility
Testing: Does not apply
=> test: fix headerMapEqualIgnoreOrder utility missing a check

test/integration/BUILD, test/integration/buffer_accounting_integration_test.cc, test/integration/filters/test_socket_interface.cc, test/integration/filters/test_socket_interface.h, test/integration/http2_flood_integration_test.cc, test/integration/protocol_integration_test.cc, test/integration/socket_interface_swap.cc, test/integration/socket_interface_swap.h
Extending the socket override framework to work for HTTP/3 and using it in the failed write test.
Testing: yep
=> test: adding HTTP/3 fail socket write test

bazel/repositories.bzl, bazel/rules_fuzzing.patch
@adisuissa 
Commit Message: Try fix for OSS-Fuzz build failure (see https://github.com/bazelbuild/rules_fuzzing/issues/185)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [fuzz] try fix for oss-fuzz build

source/extensions/common/wasm/context.cc
Signed-off-by: Scott LaVigne <lavignes@amazon.com>
Commit Message: Fix potential segfault when reading filter_state
Additional Description: Adding a needed null-check when reading the `filter_state` property from a WASM filter.
Testing: I have a repro for the crash and tested the fix via: https://github.com/lavignes/proxy-wasm-crash-example
I was experimenting with a WASM network filter and ran into a case where my WASM plugin was crashing Envoy. Here's a minimal repro: https://github.com/lavignes/proxy-wasm-crash-example. I also got confirmation by @PiotrSikora that it would be safe to just open a PR publicly.
=> wasm: Fix potential segfault when reading filter_state

test/common/buffer/BUILD, test/common/buffer/buffer_speed_test.cc
Simple benchmark to compare OwnedImpl::add to WatermarkBuffer::add
Also, benchmark to cover buffer account use.
Risk Level: n/a (benchmark, test-only changes)
Testing: test-only changes
=> Simple benchmark to compare OwnedImpl::add to WatermarkBuffer::add

CONTRIBUTING.md
Commit Message: doc: fix incorrect link
Testing: n/a
Docs Changes: link fix
=> doc: fix incorrect link

docs/root/version_history/current.rst, source/common/router/router.cc, source/common/router/router.h, source/common/runtime/runtime_features.cc, test/common/router/router_test.cc
Take the time elapsed since the downstream request was completed into account when setting the ``x-envoy-expected-rq-timeout-ms`` header on retries.
Previously the header value from the first request would be used for retries, but this meant expected timeouts could be sent that were longer than the remaining time until the global timeout expired.
Runtime Guard: ``envoy.reloadable_features.update_expected_rq_timeout_on_retry``
Fixes: #13196
=> router: update expected timeout header on retry

test/common/http/conn_pool_grid_test.cc
Commit Message: adjust EXPECT_CALL on setsockopt() in ConnectionCloseDuringCreation test  to work with possibly pre-bind socket options. The fix is needed to make the test pass under Google internal gtest suite.
Testing: n/a
=> quic: fix conn pool grid test

envoy/stream_info/stream_info.h, source/common/common/utility.cc, source/common/common/utility.h, source/common/http/conn_manager_impl.cc, source/common/http/filter_manager.cc, source/common/router/router.cc, source/common/router/upstream_request.cc, source/common/stream_info/stream_info_impl.h, source/extensions/common/wasm/context.cc, source/extensions/filters/common/rbac/utility.cc, source/extensions/filters/http/admission_control/admission_control.cc, source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc, source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc, source/extensions/filters/http/jwt_authn/filter.cc, test/common/common/utility_test.cc, test/common/router/router_2_test.cc, test/common/router/router_test.cc, test/common/stream_info/stream_info_impl_test.cc, test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_test.cc, test/extensions/filters/http/ext_proc/filter_test.cc, test/integration/filters/invalid_header_filter.cc, test/integration/filters/listener_typed_metadata_filter.cc, test/integration/filters/local_reply_with_metadata_filter.cc, test/integration/protocol_integration_test.cc
Commit Message: minor perf: no empty space chars' replace in the set response code details method
To prevent the response code details from breaking the access log format, we replace all whitespace chars of detail string in the `setResponseCodeDetails` method. Related issue: #13423.
However, **most code details do not contain whitespace chars, and it is unnecessary to make every setResponseCodeDetails call perform an additional absl::StrReplaceAll.**
We just need to require that the caller of `setResponseCodeDetails` must ensure that the detail string does not contain whitespace chars.
Testing: Partial
=> minor perf: no empty space chars' replace in the set response code details method

envoy/network/dns.h, source/common/common/dns_utils.cc, source/common/upstream/logical_dns_cluster.cc, source/common/upstream/strict_dns_cluster.cc, source/extensions/clusters/redis/redis_cluster.cc, source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc, source/extensions/common/wasm/context.cc, source/extensions/filters/udp/dns_filter/dns_filter_resolver.cc, source/extensions/network/dns_resolver/apple/apple_dns_impl.cc, source/extensions/network/dns_resolver/cares/dns_impl.cc, source/extensions/network/dns_resolver/cares/dns_impl.h, test/common/http/header_map_impl_test.cc, test/extensions/network/dns_resolver/apple/apple_dns_impl_test.cc, test/extensions/network/dns_resolver/cares/dns_impl_test.cc
Commit Message: dns: abstraction c-ares pending resolution
Additional Description: The purpose of this abstraction is to make the resolution process as common as possible when adding support for SRV query lookup in c-ares. With this abstraction, starting a pending resolution is as simple as calling `startResolution()`. The introduction of this function is the core of this refactor, and the implementation of `startResolution()` in the pending resolution object for SRV queries also simplifies the process of `DnsResolverImpl::resolve()`. Also, the DNS Response structure is abstracted by one level, and it can store the resolution of A/AAAA/SRV queries.
Testing: N/A
Docs Changes:
Release Notes:
[Optional …
=> dns: abstraction c-ares pending resolution

test/common/config/subscription_factory_impl_test.cc, test/common/protobuf/utility_test.cc, test/server/admin/config_dump_handler_test.cc
Upcoming updates to proto library use different whitespace between name and value pairs.This change preemptively modifies tests to use matchers that work with both new and old versions on proto library.
=> test: Update tests that use proto DebugString

api/envoy/config/core/v3/protocol.proto
Commit Message: just a cosmatic fix while reading protocol.proto doc
Additional Description:  bit different as compare to other similar text in same page. 
```
allow_chunked_length
(bool) Allows Envoy to process requests/responses with both Content-Length and Transfer-Encoding headers set. By default such messages are rejected, but if option is enabled - Envoy will remove Content-Length header and process message. See **RFC7230, sec. 3.3.3 <https://tools.ietf.org/html/rfc7230#section-3.3.3>** for details.
Risk Level:
```
Testing:
Docs Changes:
=> fix url glitch

source/extensions/access_loggers/grpc/http_config.cc, source/extensions/access_loggers/grpc/tcp_config.cc, test/extensions/access_loggers/grpc/http_config_test.cc, test/extensions/access_loggers/grpc/tcp_config_test.cc
Commit Message: remove grpc als static cluster check
Additional Description: This PR remove static cluster check in GRPC ALS, make behavior consistent with the OpenTelemetry ALS
Testing: unittests / integration tests
Docs Changes: TBD
Release Notes: TBD
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/19001
=> remove grpc als static cluster check

test/integration/multiplexed_upstream_integration_test.cc
Signed-off-by: YaoZengzeng <yaozengzeng@huawei.com>
Commit Message: the value of header `NO_END_STREAM` should not be empty, otherwise it won't take effect
Additional Description: ref: https://github.com/envoyproxy/envoy/blob/main/test/test_common/utility.h#L944 
Testing: N/A
=> test: use NO_END_STREAM of AutonomousStream correctly

tools/dependency/release_dates.py
=> dep: dependency checker should ignore pre-releases

.bazelci/presubmit.yml
Commit Message: Use ubuntu2004 on Bazel CI
gcc version is too old on ubuntu1804, which caused envoyproxy/envoy#19196
=> Use ubuntu2004 on Bazel CI

docs/root/version_history/current.rst, source/extensions/transport_sockets/common/passthrough.h, source/extensions/transport_sockets/proxy_protocol/proxy_protocol.cc, source/extensions/transport_sockets/proxy_protocol/proxy_protocol.h, source/extensions/transport_sockets/tap/tap.cc, source/extensions/transport_sockets/tap/tap.h, source/extensions/transport_sockets/tcp_stats/config.cc, source/extensions/transport_sockets/tcp_stats/config.h, test/extensions/transport_sockets/common/passthrough_test.cc
Creating a passthrough factory for consistent handling of wrapped characteristics for proxy_proto, tap, and tcp_stats socket factories.
Testing: new unit testing
Part of https://github.com/envoyproxy/envoy/issues/19149
=> transport_sockets: fixing alpn for wrapped sockets

docs/root/version_history/current.rst, envoy/stream_info/stream_info.h
Signed-off-by: wbpcode <wbphub@live.com>
Commit Message: supplement release note for PR #19114
Supplement to #19114.
Testing: N/A.
=> docs: supplement release note for PR #19114

source/common/common/assert.cc
Commit Message: static member vars in the implementation of ENVOY_BUG could cause an init-order fiasco if someone calls ENVOY_BUG during static init. For bad things to happen there would need to be another place with a static-init fiasco and a call to ENVOY_BUG, but it's easier to just to avoid fiascos as a rule.
Testing: //test/...
Fixes: #19264
=> assert: Avoid static-init-order fiasco for ENVOY_BUG macro impl

docs/root/version_history/current.rst, envoy/upstream/host_description.h, source/common/runtime/runtime_features.cc, source/common/upstream/transport_socket_match_impl.h, source/common/upstream/upstream_impl.cc, test/common/upstream/transport_socket_matcher_test.cc, test/common/upstream/upstream_impl_test.cc, test/mocks/upstream/transport_socket_match.h
Making sure that socket matchers on alpn-required clusters support ALPN.
Runtime guard: envoy.reloadable_features.correctly_validate_alpn
Part of https://github.com/envoyproxy/envoy/issues/19149
=> alpn: fixing config validation for socket matchers

tools/dependency/release_dates.py
A backup logic in dependency-checker for projects that do not have releases, is generating
warnings for all the tag versions greater than the current version. A sample output is given below, and the current 
patch tries to fix this.
github_release:  GitHubRelease(organization='emscripten-core', project='emsdk', version='2.0.8', tagged=True)
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.9@<2020-11-16 22:58:38>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.10@<2020-12-04 16:53:37>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.11@<2020-12-17 22:47:38>
*WARNING* emsdk has a newer release than 2.0.8@<2020-10-24 17:42:23>: 2.0.12@<2021-01-09 15:25:52>
*WARNING* emsdk …
=> dep: Dependency checker should give warning for only the latest tag

bazel/external/wee8.patch, bazel/repository_locations.bzl
While there, fix build with MSan (broken in #18621).
=> wasm: update V8 to v9.7.106.17.

bazel/repository_locations.bzl, docs/BUILD
Bumps the version and fixes paths for `rules_pkg` 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> deps: Bump `rules_pkg` and fix paths

test/common/json/json_loader_test.cc
Improving test line coverage for json tests
Signed-off-by: Tom Hadlaw <tomhadlaw@gmail.com>
Additional Description: Adding more tests to increase line coverage for json package. Adding coverage for missing code paths by testing various loadFromString inputs.
Testing: Added tests to json_loader_test
This PR seeks to improve this issue: https://github.com/envoyproxy/envoy/issues/1963
=> Add test coverage for json package

.github/dependabot.yml, bazel/repositories_extra.bzl, tools/base/requirements.in, tools/base/requirements.txt, tools/dev/BUILD, tools/dev/requirements.txt
This allows requirements without hashes - ie using `-e` to be used in development
They can either point to a git/hub requirement for testing in CI, or a local filesystem requirement for development of pytooling packages.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tooling: Add dev requirements setup

test/extensions/network/dns_resolver/cares/dns_impl_test.cc
Commit Message: dns: refactor parsing dns bytes stream in TestDnsServer
Additional Description: This refactor alleviates the cost of adding the process of parsing SRV query requests in TestDnsServerQuery.
Testing:
Docs Changes:
Release Notes:
=> dns: refactor parsing dns bytes stream in TestDnsServer

.azure-pipelines/pipelines.yml
CI is failing on https://github.com/envoyproxy/envoy/pull/19275 due to running out of diskpace during the docker build
This PR should free up ~1GB of extra space
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docker: Delete CI build artefacts after loading

bazel/external/quiche.patch, bazel/repositories.bzl
=> quiche: patch for MacOS build

api/envoy/config/filter/http/transcoder/v2/transcoder.proto, api/envoy/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto
The documentation for `convert_grpc_status` had two leading spaces in the text following a code block, causing the text to be rendered as part of the code block.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: fix whitespace typo in transcoder documentation.

source/extensions/filters/http/cache/cache_headers_utils.cc
Commit Message: During compilation of Envoy this warning was found:
```
source/extensions/filters/http/cache/cache_headers_utils.cc: In function 'Envoy::SystemTime Envoy::Extensions::HttpFilters::Cache::CacheHeadersUtils::httpTime(const Envoy::Http::HeaderEntry*)':
source/extensions/filters/http/cache/cache_headers_utils.cc:144:27: error: loop variable 'format' of type 'const string&' {aka 'const std::__cxx11::basic_string<char>&'} binds to a temporary constructed from type 'const char*' [-Werror=range-loop-construct]
144 |   for (const std::string& format : rfc7231_date_formats) {
|                           ^~~~~~
source/extensions/filters/http/cache/cache_headers_utils.cc:144:27: note: use non-reference type 'const string' {aka 'const std::__cxx11::basic_string<char>'} to make the copy …
```
=> cache: clean up string-array declaration to avoid temp std::string conversion during lookup, and eliminate warning

docs/root/configuration/best_practices/edge.rst
Commit Message: Missing url in best practices doc for RFC3986.
Additional Description: url path https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge
=> To fix missing url in best practices doc for RFC3986

source/common/buffer/buffer_impl.h
minor fix to the  extra symbols in comments
=> fix: remove extra symbols in comments

envoy/network/socket.h, source/common/grpc/typed_async_client.h
This PR fixes two compilation error that are happening in the oss-fuzz build of Envoy. Note that the latest oss-fuzz build errors out with only the [ error related to `AsyncStream`](https://oss-fuzz-build-logs.storage.googleapis.com/log-917e4a97-e528-4cce-b749-9187973dd9ed.txt) but AFAIR when it is fixed, a different compilation error has to be fixed which I fixed in the first commit that changes the socket.h file.
=> Fix oss-fuzz build compilation errors

test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc
Fixing the alt-svc test to make sure it uses the HTTP/3 connection, where before it simply attempted to establish one.
Also adding some comments since these tests are complicated.
Testing: yes
=> http3: test fix

api/envoy/extensions/filters/http/decompressor/v3/decompressor.proto, docs/root/configuration/http/http_filters/decompressor_filter.rst, docs/root/version_history/current.rst, source/extensions/filters/http/decompressor/decompressor_filter.cc, source/extensions/filters/http/decompressor/decompressor_filter.h, test/extensions/filters/http/decompressor/decompressor_filter_test.cc
Commit Message: Add config flag to decompress even when no-transform is specified
Additional Description: This allows matching the more lenient behavior of other client-side networking libraries such as OkHttp or URLSession, especially in cases where the remote server is not under the client developer's control.
Risk Level: Low, defaults are unaffected, change is opt-in.
Testing: Added unit tests for existing `no-transform` behavior (there was none) and a new test validating the new configuration flag.
Docs Changes: Updated.
=> decompressor: add config flag to ignore no-transform

source/extensions/filters/http/cache/config.cc, source/extensions/filters/http/cache/http_cache.h, source/extensions/filters/http/cache/simple_http_cache/simple_http_cache.cc, test/extensions/filters/http/cache/simple_http_cache/BUILD, test/extensions/filters/http/cache/simple_http_cache/simple_http_cache_test.cc
Commit Message: Add factory context arg to http cache factory
Additional Description: Http Cache factory needs access to factory context to bootstrap async clients, and child stats scopes.
Risk Level: L
Testing: N/A
=> Add factory context arg to http cache factory

source/common/router/header_formatter.cc, test/common/router/header_formatter_test.cc, test/common/router/route_corpus/non_parsable_metadata
Commit Message: route: graceful handling of non-object header formatter metadata parsing
Fixing a crash due to a control-plane invalid metadata header format, where the format string doesn't include an object.
In this PR the output from the json converter is validated, and an EnvoyException is thrown in case it is incorrect.
Testing: Added unit test + fuzz test
Fixes fuzz isse: 42385
=> route: graceful handling of non-object header formatter metadata parsing

source/common/html/utility.cc, source/common/html/utility.h, source/common/stats/allocator_impl.cc, test/server/admin/stats_handler_test.cc
Commit Message: Text-readout stats were not setting their 'Used' bit, so `?usedonly` omitted all text-readouts. This PR sets the bit and adds a unit test for that. It also switches an html util that previously took a `const std::string&` to take an `absl::string_view` intead.
Testing: Just the new test, plus //test/common/html/...
=> stats: set used-only bit and when updating text-readouts, and test it.

tools/base/requirements.in, tools/base/requirements.txt
This bumps `pygments` beyond `2.11.1` which was causing the docs build to fail
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> deps: Bump `envoy.docs.sphinx-runner` -> 0.0.6

source/extensions/filters/http/cache/http_cache.cc, source/extensions/filters/http/cache/key.proto, test/extensions/filters/http/cache/http_cache_test.cc
Signed-off-by: Edin Kadric <edin@google.com>
Commit Message: Add scheme field to Envoy.Extensions.HttpFilters.Cache.Key and deprecate clear_http. The current state is confusing because the clear_http field is not marked "optional", so it doesn't have a "has" presence test, which means that if protocol information is ignored and the field isn't set, users of the proto will interpret clear_http=false as SSL=true.
Additional Description: An alternative would be to just add "optional" to the field, but the field is also confusing because "clear_http" sounds like an action where we "clear" an HTTP field. Also, adding presence tracking to an existing field may not be safe: If the field is set to its default value and passes through an old binary, the field will be dropped and any newer binaries …
=> filter: Add scheme field to cache keys and deprecate clear_http

api/envoy/extensions/filters/http/grpc_http1_bridge/v3/config.proto, docs/root/configuration/http/http_filters/grpc_http1_bridge_filter.rst, docs/root/version_history/current.rst, source/common/grpc/common.cc, source/common/grpc/common.h, source/extensions/filters/http/grpc_http1_bridge/BUILD, source/extensions/filters/http/grpc_http1_bridge/config.cc, source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.cc, source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.h, test/common/grpc/common_test.cc, test/common/http/header_map_impl_test.cc, test/extensions/filters/http/grpc_http1_bridge/BUILD, test/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter_test.cc
This is an implementation based on the discussion in #19198.
When application/x-protobuf is used the filter will prepend the payload with the gRPC header, as defined by the wire format. Before returning the response the frame is also trimmed. This functionality is behind a configuration setting.
Docs Changes: WIP
Fixes #19198
=> grpc_http1_bridge: support for prepending and trimming the grpc frame header

test/extensions/filters/http/ext_proc/BUILD, test/extensions/filters/http/ext_proc/ext_proc_grpc_fuzz.cc, test/extensions/filters/http/ext_proc/ext_proc_grpc_fuzz.proto
Commit Message: fuzz: Fixing ext_proc_grpc fuzzer to pass clusterfuzz check_build.
Currently the fuzzer is not passing the `check_build` step of OSS-fuzz when running with empty input,
because it doesn't cover any code. This PR modifies the input from arbitrary buffer that is divided to 2 internal inputs,
into a proto-based input that has 2 `bytes` entries.
Risk Level: Low - fuzzer only
Testing: N/A.
=> [fuzz] Fixing ext_proc_grpc fuzzer to pass clusterfuzz check_build

test/common/http/path_utility_fuzz_test.cc
Commit Message: fuzz: Fixing path_utility fuzzer to pass clusterfuzz check_build.
Currently the fuzzer is not passing the check_build step of OSS-fuzz when running with empty input,
because it doesn't cover any code. This PR adds an output to the log that is covers some of the Envoy code, and makes that step happy.
Risk Level: Low - fuzz code only
Testing: N/A.
=> [fuzz] Fixing path_utility fuzzer to pass clusterfuzz check_build

docs/root/configuration/http/http_filters/ext_authz_filter.rst, docs/root/version_history/current.rst, envoy/http/async_client.h, source/common/http/async_client_impl.cc, source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc, test/common/http/async_client_impl_test.cc, test/common/router/router_test.cc
Commit Message: async_client: add the option to keep parent sampling status for child spans
Additional Description: ext authz requests always get traced, regardless of parent sampling status; this happens because the HTTP async client (used by ext authz) overrides the span's sampling status with `true`.
Testing: added a test case for keeping the parent's sampling status; built envoy and ran it with a config, confirming that authz spans keep the parent sampling status.
Fixes #17085
Signed-off-by: Caroline Stere <stere@adobe.com>
=> async_client: add the option to keep parent sampling status for child spans

tools/base/entry_point.py, tools/base/envoy_python.bzl
This extends the `rules_python` `entry_point` to allow data to be
added to the sandbox, and args to pass the data to the tool.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel: Add python `envoy_entry_point`

source/extensions/access_loggers/common/grpc_access_logger.h, source/extensions/access_loggers/grpc/grpc_access_log_impl.cc, test/extensions/access_loggers/common/grpc_access_logger_test.cc
Previously we always created the proto and so always created the retry config
Risk Level: low (bugfix)
h/t Raven who caught and root caused this.
=> access logger: don't always create retry config.

bazel/external/wee8.genrule_cmd
Fixes https://github.com/envoyproxy/envoy/issues/19379
=> wasm: pass -Wno-invalid-offsetof when building V8.

bazel/repository_locations.bzl
=> Update com_github_nlohmann_json: v3.10.5 (current: v3.10.4)

contrib/sip_proxy/filters/network/source/router/router_impl.h
Change the catching to references to fix compilation failed because Envoy::EnvoyException values were caught by value
The error message was this:
```
./contrib/sip_proxy/filters/network/source/router/router_impl.h:244:19: error: catching polymorphic type 'class std::out_of_range' by value [-Werror=catch-value=]
244 |     } catch (std::out_of_range) {
|                   ^~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/re …
=> sip_proxy: fix EnvoyException caught by value

docs/root/version_history/current.rst, source/common/http/http1/codec_impl.cc, source/common/http/http1/codec_impl.h, source/common/runtime/runtime_features.cc, test/common/http/http1/codec_impl_test.cc
http: clean up *_1xx_and_204_response_headers guards
Signed-off-by: Taylor Barrella <tbarrella@gmail.com>
Testing: Unit
Runtime guard: Removes `require_strict_1xx_and_204_response_headers` and `send_strict_1xx_and_204_response_headers`
Fixes #19509 #19510
=> http: clean up *_1xx_and_204_response_headers guards

source/common/quic/BUILD, source/common/quic/envoy_quic_client_stream.cc, source/common/quic/envoy_quic_stream.h, test/integration/multiplexed_integration_test.cc, test/integration/protocol_integration_test.cc, test/integration/quic_http_integration_test.cc
Commit Message: switch to use `http2::adapter::HeaderValidator` from QUICHE to validate request/response header names and values. This library validate both header name and value to protect against header smuggling attack.
Additional Description: this change also fix a bug where `override_stream_error_on_invalid_http_message` didn't take effect on invalid headers rejected by EnvoyQuicStream::validateHeader() .
Testing: added integration tests
=> quic: use oghttp2 header validator to validate request/response headers

test/integration/protocol_integration_test.cc
fixing one more tsan shutdown race, where the test upstream was reading/writing packets during singleton shutdown.
=> test: fixing one more flake

.bazelrc, test/integration/filters/add_body_filter.proto, test/integration/filters/crash_filter.proto, test/integration/filters/set_is_terminal_filter_config.proto, test/integration/filters/stop_and_continue_filter_config.proto
Also removing a couple of unnecessary validate.proto files.
This removes several thousands of lines worth of warnings from our build logs.
=> tools: not warning about deprecated declarations

source/common/upstream/upstream_impl.cc, test/common/upstream/upstream_impl_test.cc
Signed-off-by: Kateryna Nezdolii <nezdolik@spotify.com>
Commit Message: The change fixes slow config not being propagated for Round Robin Load balancer case. Currently, slow start mode does not work in RR (only works in LR).
Testing: Done
Docs Changes:
Release Notes: TBD
Fixes #19437
=> Fix slow start for round robin LB

source/extensions/filters/network/dubbo_proxy/dubbo_protocol_impl.cc, test/extensions/filters/network/dubbo_proxy/dubbo_protocol_impl_test.cc
Commit Message: fix decoding of provider error response
There is no response type in the non `Ok` dubbo response. So we should not try to decode response type from non `Ok` dubbo response to avoid the `Cannot parse RpcResult type from buffer` exception. 
=> fix decoding of provider error response

test/exe/BUILD
All other tests that depend on //source/exe:envoy-static are already
excluded from the coverage. Also, those tests run only on win32, but
its dependencies are build on all platforms leading to the increased
build times and other issues.
=> coverage: exclude win32 tests from coverage.

docs/root/version_history/current.rst, source/common/runtime/runtime_features.cc
This largely fixes issues with HTTP/3, iff there's a upstream write error under the stack of reading.
Risk Level: Medium (data plane refactor)
Testing: yes
[Optional Runtime guard:] envoy.reloadable_features.allow_upstream_inline_write
=> data plane: allowing upstream inline writes

api/envoy/api/v2/auth/common.proto, api/envoy/extensions/transport_sockets/tls/v3/common.proto, docs/root/version_history/current.rst, source/extensions/transport_sockets/tls/context_config_impl.cc, test/extensions/transport_sockets/tls/ssl_socket_test.cc
Commit Message: Remove TLS 1.0 and 1.1 from the default server TLS versions. Users can still explicitly opt-in to 1.0 and 1.1 using tls_minimum_protocol_version.
Docs Changes: updated
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/5398 and checks off one box for https://github.com/envoyproxy/envoy/issues/5401
=> tls: set TLS v1.2 as the default minimal version for servers

test/run_envoy_bazel_coverage.sh
tested locally - this is what we need for multiplexed integration test logs
=> test: bumping logs file larger

source/common/grpc/context_impl.cc, source/common/stats/utility.cc, source/common/stats/utility.h, test/common/grpc/context_impl_test.cc, test/common/stats/utility_test.cc
Fixes #16715
The service/method attributes might be changed due to the routing config.
It looks safer to preserve them to be able able to get the
correct statistics once the request is over.
Signed-off-by: Mikhail Galanin <mikhail.galanin@team.bumble.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> grpc stat: copy request path attributes instead of keeping them as a reference

source/server/admin/stats_handler.cc
Commit Message: minor update to avoid temp string allocation
Try to reduce unnecessary string allocation by the new `addFragments` api.
Testing: N/A.
=> minor update to avoid temp string allocation

api/envoy/config/cluster/v3/cluster.proto, docs/root/configuration/observability/access_log/usage.rst, docs/root/version_history/current.rst, source/common/formatter/substitution_formatter.cc, source/common/runtime/runtime_features.cc, test/common/formatter/substitution_formatter_test.cc, test/common/tcp_proxy/tcp_proxy_test.cc
#15139 ([cluster] Use alt_stat_name for general observability purposes (access log, tracing, admin)) introduced a runtime guarded feature, which has been 6 months since the new code has been exercised by default, so remove the old code path.
Testing:
Docs Changes:
Release Notes: Deprecate envoy.reloadable_features.use_observable_cluster_name.
[Optional Fixes #Issue] #18447
=> envoy.reloadable_features.use_observable_cluster_name deprecation

test/integration/multiplexed_upstream_integration_test.cc
This small testing change improves header test robustness by ensuring
that multiple headers are (as intended) counted distinctly.
The intention of
MultiplexedUpstreamIntegrationTest.TestManyResponseHeadersRejected is to
verify that a response with over 100 headers is rejected.
Based on https://httpwg.org/specs/rfc7230.html#field.order, "[a] sender
MUST NOT generate multiple header fields with the same field name in a
message unless either the entire field value for that header field is
defined as a comma-separated list [i.e., #(values)] or the header field
is a well-known exception [...]" and "[a] recipient MAY combine multiple
header fields with the same field name into one "field-name:
field-value" pair, without changing the semantics of the message [...]"
By changing the test to use …
=> test: Improve headers test robustness.

tools/base/BUILD, tools/base/entry_point.py, tools/base/envoy_python.bzl, tools/distribution/BUILD, tools/docs/BUILD
This is a follow up to use the macro added in #19450 for existing entry_points
Also contains a fix to use a template to create the py_binary main to ensure the py_binary retains the path to the entry point
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tooling: Use `envoy_entry_point`

docs/root/version_history/current.rst, source/common/router/router.cc, source/common/runtime/runtime_features.cc
Commit Message: envoy.reloadable_features.http_transport_failure_reason_in_body deprecation
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #16008
=> http: envoy.reloadable_features.http_transport_failure_reason_in_body deprecation

docs/root/configuration/operations/overload_manager/overload_manager.rst
Commit Message:  Clarify docs for Overload Manager disable_keep_alive action.
Looking at the code: https://github.com/envoyproxy/envoy/blob/0a4e3d990ae865c6753432322e9b2eaec8057548/source/common/http/conn_manager_impl.cc#L1382-L1401 
We seem to use GoAways for H2/H3 and a drain timer for H/1 which will close the connection if it has no stream and nothing to write when the timer fires.
Risk Level: NA
Testing: NA
Docs Changes: Included
=> Docs: Clarify docs for Overload Manager disable_keep_alive action.

ci/do_ci.sh, tools/dependency/BUILD, tools/dependency/validate.py, tools/dependency/validate_test.py
this is a reopening of #18085 partly for the purposes of testing
im not sure whether it would be best to shift this tool to bazel first and then to `envoy.dependency.check` or just to the check tool directly
either way i need to figure out separating the data
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel: Shift dependency validate tool to bazel

test/extensions/filters/http/ext_proc/BUILD, test/extensions/filters/http/ext_proc/ext_proc_benchmark_test.cc, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Commit Message: Add a benchmark test for ext_proc and improve coverage of empty HTTP bodies
Additional Description: Add a test that uses performance annotation counters to measure performance of ext_proc, including the gRPC calls that it makes.
Risk Level: Low -- just tests.
Testing: A new test suite and one new test case added
=> ext_proc: Add a benchmark test and otherwise improve coverage

docs/root/configuration/http/http_filters/grpc_json_transcoder_filter.rst
Previously, the `protoc` command used `-I$(GOOGLEAPIS_DIR)`, which
attempts to run the `GOOGLEAPIS_DIR` as a command in a subshell.
This commit replaces `-I$(GOOGLEAPIS_DIR)` with`-I${GOOGLEAPIS_DIR}`,
which correctly dereferences the env variable.
Signed-off-by: Henry Qin <root@hq6.me>
=> Update incorrect docs for gRPC-JSON transcoder.

test/common/quic/platform/quic_platform_test.cc
Commit Message: QuicThread test fails under TSAN because of racing between vtable pointer change and calling into its virtual method. Fix it by waiting till the virtual method finishes before destruction.
This is a test setup issue.
Testing: N/A
=> quic: fix quic platform test TSAN failure

bazel/BUILD, bazel/envoy_select.bzl, test/extensions/access_loggers/wasm/config_test.cc, test/extensions/bootstrap/wasm/config_test.cc, test/extensions/bootstrap/wasm/wasm_integration_test.cc, test/extensions/bootstrap/wasm/wasm_test.cc, test/extensions/common/wasm/wasm_runtime.cc, test/extensions/common/wasm/wasm_test.cc, test/extensions/filters/http/wasm/config_test.cc, test/extensions/filters/network/wasm/config_test.cc, test/extensions/stats_sinks/wasm/config_test.cc, test/extensions/stats_sinks/wasm/wasm_stat_sink_test.cc
=> wasm: exclude C++ tests on all unsupported platforms.

test/extensions/filters/http/wasm/wasm_filter_test.cc
The default stack size in WAMR has been increased since those tests
were disabled, and they work fine now.
Missed in #19404.
=> wasm: re-enable gRPC tests when using WAMR.

test/common/network/io_socket_handle_impl_test.cc
Commit Message: test: allow disabling IP versions in iohandle test
Additional Description: The test case "IoSocketHandleImplTest" attempts to open a TCP socket listening on the loopback interface, parameterized over both IPv4 and IPv6.  This does not respect configuration in the environment variable
`ENVOY_IP_TEST_VERSIONS`.  As a result, test cases run with `ENVOY_IP_TEST_VERSIONS=v4only` still attempt to open a TCP socket with a link-local IPv6 address, failing in IPv4-only environments.
It seems like the canonical way to parameterize the IP versions is to simply use the output of `TestEnvironment::getIpVersionsForTest()` as the test parameter set.  After applying this patch, an IPv4-only environment used for development begins to pass tests on v1.21.0.
Testing: This …
=> test: allow disabling IP versions in iohandle test

source/common/http/conn_pool_grid.cc, source/common/http/conn_pool_grid.h, source/common/http/http3/conn_pool.cc, source/common/http/http3/conn_pool.h, source/common/quic/envoy_quic_client_session.cc, source/common/upstream/cluster_manager_impl.cc, test/common/http/conn_pool_grid_test.cc, test/common/http/http3/conn_pool_test.cc
Commit Message: mark h3 conn pool Confirmed via a new callback interface PoolConnectResultCallback instead of `WrapperCallbacks::onConnectionAttemptReady()`. The new interface is called from h3 pool based on handshake result. 
Moving marking Confirmed logic out of `onConnectionAttemptReady()` is needed to support 0-RTT handshakes. This is because if a connection is using 0-RTT credentials, onPoolReady() doesn't necessarily means the handshake succeeds. And it will also be used to notify conn pool grid about 0-RTT handshake failure when h3 conn pool starts sending 0-RTT requests.
Risk Level: low, conn pool grid change
Testing: added unit tests
Part of #19593 #18715
=> quic: mark http3 confirmed from H3 conn pool

docs/root/version_history/current.rst, source/common/http/conn_manager_impl.cc, test/integration/protocol_integration_test.cc
Commit Message: http: envoy.reloadable_features.allow_response_for_timeout deprecation
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #16005
=> http: envoy.reloadable_features.allow_response_for_timeout deprecation

docs/root/configuration/http/http_conn_man/headers.rst, docs/root/configuration/observability/access_log/usage.rst, source/common/formatter/substitution_formatter.cc, source/common/router/header_formatter.cc, test/common/formatter/substitution_formatter_test.cc, test/common/router/header_formatter_test.cc, test/extensions/access_loggers/grpc/http_grpc_access_log_impl_test.cc, test/mocks/stream_info/mocks.cc
The substitution_formatter & header_formatter formatters do not cover
all 15 combinations of address & output type, so make it more
consistent.
Output formats:
- _ADDRESS
- _ADDRESS_WITHOUT_PORT
- _PORT
For each each address in the set:
- UPSTREAM_LOCAL_
- UPSTREAM_REMOTE_
- DOWNSTREAM_LOCAL_
- DOWNSTREAM_REMOTE_
- DOWNSTREAM_DIRECT_REMOTE_
Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>
Signed-off-by: Robin H. Johnson <rjohnson@digitalocean.com>
Testing: unit tests added & passed for all inputs
Docs Changes: Adds format specifiers
Release Notes: router: add upstream/downstream local/remote format specifiers; formatter: add upstream/downstream local/remote format specifiers
=> router, formatter: make address formats consistent in substitution_formatter & header_formatter

source/common/config/BUILD, source/common/config/utility.h
Commit Message: config: update xDS V2 deprecation error
Additional Description: Fixes broken link and updates error message to note that xDS V2 support has been removed. The current link is [only applicable up through v1.17 docs](https://www.envoyproxy.io/docs/envoy/v1.17.4/faq/api/transition). A similar fix should likely be applied to the [`release/v1.18`](https://github.com/envoyproxy/envoy/tree/release/v1.18) branch too.
_Edit: rebased to add DCO sign-off, missed that the first time_
=> config: update xDS V2 deprecation error

docs/root/version_history/current.rst, source/common/runtime/runtime_features.cc, source/common/upstream/health_checker_impl.cc, test/common/upstream/health_checker_impl_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #18438
=> health_check: envoy.reloadable_features.health_check.graceful_goaway_handling deprecation

docs/root/version_history/current.rst, source/common/formatter/substitution_formatter.cc, source/common/runtime/runtime_features.cc, test/common/formatter/substitution_formatter_test.cc
Signed-off-by: changran <changran.wang@intel.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> access_log: envoy.reloadable_features.unquote_log_string_values deprecation

source/common/network/addr_family_aware_socket_option_impl.h, test/common/network/addr_family_aware_socket_option_impl_test.cc
Commit Message: socket options - re-add support for directly setting options
Additional Description: originally added in https://github.com/envoyproxy/envoy/pull/18769 and removed in https://github.com/envoyproxy/envoy/pull/19684 due to missing coverage. Added here with coverage.
Testing: added UT
=> socket options: re-add support for directly setting options

test/integration/multiplexed_upstream_integration_test.cc
Commit Message: Restore ManyLargeSimultaneousRequestWithRandomBackup test.
Additional Description: Seems to have been dropped by mistake when adding pause-filter tests that support QUIC.
Originally added here: https://github.com/envoyproxy/envoy/pull/4675/files#diff-ca12a5f228df0c283c4135e6a49ce6eb90d719eb0b26b48565765fef1db38aa5R285
Replaced with pause-filter here: https://github.com/envoyproxy/envoy/pull/15841/files#diff-f87cd0fb4494001b7c81830045c827969604aa1d2c5ab405ea3fa45248cf46b3R328
Testing: ran tests
Docs Changes:NA
Platform Specific Features:NA
=> Restore ManyLargeSimultaneousRequestWithRandomBackup test.

docs/root/version_history/current.rst, source/common/http/http2/codec_impl.cc, source/common/runtime/runtime_features.cc, test/common/http/http2/codec_impl_test.cc
Commit Message: http: envoy.reloadable_features.http2_consume_stream_refused_errors deprecation
Fixes  #19505
=> http: envoy.reloadable_features.http2_consume_stream_refused_errors deprecation

CODEOWNERS, docs/root/version_history/current.rst, source/extensions/tracers/xray/xray_configuration.h, test/extensions/tracers/xray/xray_tracer_impl_test.cc
Signed-off-by: Sunil Narasimhamurthy <13044744+suniltheta@users.noreply.github.com>
Commit Message: xray: make Unknown as the default SamplingDecision
**Additional Description:** Earlier the default value in `enum SamplingDecision` is `Sampled`. This will cause a bug in AWS X-Ray extension where if a request with header: `x-amzn-trace-id` is supplied without `"sampled="` key then it ends up considering the request as sampled. All the requests originating from Amazon Load Balancer has header `x-amzn-trace-id` without sampling decision set. This forces envoy to sample 100% of the request without any regard for the sampling rate set in the envoy.
Release Notes: Include bug fix description on version history
=> xray: make Unknown as the default SamplingDecision

bazel/envoy_test.bzl
Commit Message: [bazel] allow specifying `exec_properties` in `envoy_cc_test`
Additional Description: In order to pass properties such as `sandboxNetwork` as we are trying to do in Envoy Mobile here: https://github.com/envoyproxy/envoy-mobile/pull/2022
=> [bazel] allow specifying `exec_properties` in `envoy_cc_test`

docs/root/version_history/current.rst
PR#19613 missed the release note addition, which is added in this PR.
Risk Level: Zero
Testing: N/A. Documentation.
Docs Changes: Release notes
Release Notes: this change
Signed-off-by: Robin H. Johnson <rjohnson@digitalocean.com>
Fixes: https://github.com/envoyproxy/envoy/pull/19613
Reference: https://github.com/envoyproxy/envoy/pull/19613#issuecomment-1021403630
=> router, formatter: release notes for address formats in substitution_formatter & header_formatter

bazel/README.md
Commit Message: docs: recommend clang-format 12.0.1
Recommend clang-format 12.0.1 because 11.* known to fail:
```sh
❯ /opt/local/bin/clang-format-mp-11 --version
clang-format version 11.1.0
❯ /opt/local/bin/clang-format-mp-11 -n ./test/common/http/header_map_impl_test.cc
./test/common/http/header_map_impl_test.cc:425:4: warning: code should be clang-formatted [-Wclang-format-violations]
{
^
./test/common/http/header_map_impl_test.cc:427:4: warning: code should be clang-formatted [-Wclang-format-violations]
}
^
```
Also use fix directory name to match https://github.com/llvm/llvm-project/releases/tag/llvmorg-12.0.1
Risk Level:  n/a
Testing: n/a
Docs Changes: recommend clang-format 12.0.1
=> docs: recommend clang-format 12.0.1

test/test_common/environment.cc
Commit Message: Windows: fix the invalid tmp directory path
Some of test failed on windows due to create the tmp directory.  So build the tmp dir path by the env variable instead of own-build one.
```
Executing tests from //test/integration:quic_protocol_integration_test
-----------------------------------------------------------------------------
[2022-01-27 04:33:09.036][20216][critical][assert] [test/test_common/environment.cc:48] assert failure: dirname != nullptr. Details: failed to create tempdir from template:  :\Windows\TEMP\envoy_test_uds.z20216 The system cannot move the file to a different disk drive.
```
Testing: n/a
Platform Specific Features: windows
=> Windows: fix the invalid tmp directory path

source/common/router/router.cc
Signed-off-by: Eugene Chan <eugenechan@google.com>
Commit Message: Clarify a log line that claims no cluster match when no route was found
Testing: n/a
Release Notes: changes a debug log line
=> Clarify a log line that claims no cluster match when no route was found

test/common/network/resolver_impl_test.cc, test/common/tracing/http_tracer_manager_impl_test.cc, test/server/api_listener_test.cc
Problem description:
Having the unit tests bound to the existing format is fragile. 
Solution:
This PR decouple the unit tests with the existing format.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Decouple unit tests with the existing Protobuf DebugString format

.python-version
This should fix problems - as seen here:
https://github.com/envoyproxy/envoy/pull/19722/files#diff-bb622deaf176384b0aeb5bf4f767ea4ac5d71a1f371100ce2c46813564cb936fL409
...where dependabot is trying to uninstall libs that are required for 3.8 and 3.9, but not for 3.10
(officially/in ci we use 3.8, i tend to test locally with 3.9)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> repo: Set python version (for dependabot)

test/extensions/filters/http/ext_authz/ext_authz_fuzz.proto
Fuzz inputs to ext authz extension hit ASSERT because of unhandled value of result field. Add validation rules in ext authz fuzz proto to only allow enum defined values for result field. 
Signed-off-by: Kirtimaan <krajshiva@google.com>
Commit Message: Only allow valid fuzz inputs for result field in ext_authz_fuzz.proto for fuzz test to not Assert.
Additional Description: ext_authz_fuzz_test hits ASSERT due to invalid values for result field. ext authz result field will always be from defined enums as it is set internally in the code. Adding validation rules to only allow defined enum values will prevent fuzz test to ASSERT prematurely.
Risk Level:Low
Testing: $ bazel test ext_authz_fuzz_test --config=remote
INFO: Invocation ID: f3bf6669-a44d-4f77-8904-0b79ee6c86d3
INFO: Build options …
=> Only allow valid fuzz inputs for result field in ext_authz_fuzz.proto.

source/common/quic/envoy_quic_client_stream.cc, source/common/quic/envoy_quic_client_stream.h, source/common/quic/envoy_quic_server_stream.cc, source/common/quic/envoy_quic_server_stream.h, source/common/quic/envoy_quic_stream.h, test/common/quic/envoy_quic_client_stream_test.cc, test/common/quic/envoy_quic_server_stream_test.cc, test/integration/http_protocol_integration.cc, test/integration/http_protocol_integration.h, test/integration/protocol_integration_test.cc, test/integration/redirect_integration_test.cc
Use byteMeter in QUIC client and server streams
Fixes #19051
Testing: Unit
=> Use byteMeter in QUIC streams

source/common/common/logger.h, source/extensions/filters/http/ext_proc/client_impl.h, source/extensions/filters/http/ext_proc/ext_proc.h, source/extensions/filters/http/ext_proc/mutation_utils.h, source/extensions/filters/http/ext_proc/processor_state.h
Commit Message: Create an "ext_proc" logger ID, like other filters have. 
Additional Description: Previously, ext_proc was using the generic "filter" ID.
Docs Changes:
Release Notes:
=> ext_proc: Add an explicit logger ID

CODEOWNERS
Signed-off-by: Pradeep Rao <pcrao@google.com>
Adding Yanjun Xiang to CODEOWNERS for the DNS Filter, as an active contributor, as part of the steps required to move the extension from alpha to stable status.
Testing: N/A
=> Add Yanjun Xiang to owners list for Dns Filter Extension.

source/common/runtime/runtime_features.cc
See https://github.com/envoyproxy/envoy/issues/19761
Fixes commit #19614
=> runtime: flipping http2_new_codec_wrapper false

api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
Commit Message: Clean up errors in the ext_proc configuration proto
* Fix comments regarding what is and isn't implemented.
* Indicate that "stat_prefix" really is implemented, because it is.
* Re-name two misnamed (but as yet unimplemented) fields in per-route
configuration.
Testing: Existing integration and unit tests
Docs Changes:
Release Notes:
=> ext_proc: Clean up errors in configuration proto

test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc, test/integration/filters/stream_info_to_headers_filter.cc, test/integration/multiplexed_upstream_integration_test.cc, tools/base/envoy_python.bzl
Part of https://github.com/envoyproxy/envoy-mobile/issues/1520
=> dfp: adding connection timing test

test/integration/http_integration.cc, test/integration/multiplexed_integration_test.cc
addressing https://github.com/envoyproxy/envoy/issues/19595 more systematically.
=> test: more logs deflaking

bazel/external/wee8.genrule_cmd
New features in V8 severely limited the maximum number of WasmVMs
that can be created in a single process, so disable them for now.
See: https://bugs.chromium.org/p/v8/issues/detail?id=12592
This increases the maximum number of WasmVMs from 268 to 6,479.
Fixes #19720.
=> wasm: increase the maximum number of WasmVMs when using V8.

test/config/utility.cc, test/integration/integration_test.cc, test/integration/multiplexed_integration_test.cc, test/integration/protocol_integration_test.cc
As detailed in the linked issue, the lack of delay-close in integration tests was causing windows to react to FINs before reading error bodies, so turning up delay close.
Fixes https://github.com/envoyproxy/envoy/issues/19430
=> test: deflaking yet another test

source/extensions/transport_sockets/tcp_stats/tcp_stats.cc, test/extensions/transport_sockets/tcp_stats/tcp_stats_test.cc
See
https://github.com/envoyproxy/envoy/issues/19535#issuecomment-1022977011
This allows using othe compiler toolchains that are not literally in
/usr/include but are still present. I don't think this should impact
standard clang builds at all.
Signed-off-by: John Howard <howardjohn@google.com>
Commit Message: tcp_stats: use relative import
See
https://github.com/envoyproxy/envoy/issues/19535#issuecomment-1022977011
This allows using othe compiler toolchains that are not literally in
/usr/include but are still present. I don't think this should impact
standard clang builds at all.
Testing: existing tests ensure it builds still
Docs Changes:
Release Notes:
[Optional Fixes …
=> tcp_stats: use relative import

docs/root/version_history/current.rst, envoy/filesystem/filesystem.h, source/common/filesystem/BUILD, source/common/filesystem/posix/filesystem_impl.cc, source/common/filesystem/win32/filesystem_impl.cc, source/common/filesystem/win32/filesystem_impl.h, source/common/runtime/runtime_features.cc, test/common/filesystem/filesystem_impl_test.cc, test/test_common/environment.cc, test/test_common/environment.h
Right now Envoy has 2 calls to file based writing, access logs (which append) and the key value store (which is buggy for short writes).  We could wire a truncate flag through for k-v store, but I assert most folks want to either append or write-and-truncate, and we can add an InlineWrite flag if folks want !truncate behavior.
[Optional Runtime guard:] yes
=> file: truncating files which are not opened with append

source/common/conn_pool/conn_pool_base.cc, test/integration/cds_integration_test.cc, tools/base/envoy_python.bzl
Fixing a bug where the connection pool attempts to establish new connections while draining.
=> conn pool: fixing overly aggressive connect 

examples/front-proxy/Dockerfile-jaeger-service, examples/front-proxy/Dockerfile-service
Part of #19781 
Testing: local
=> ci: not using alpine image in examples

security/email-templates.md
security: Update the 'Candidate release patches' email template to reflect recent format.
Testing: N/A
=> security: Update the 'Candidate release patches' email template

docs/root/version_history/current.rst, source/extensions/transport_sockets/tls/utility.cc, source/extensions/transport_sockets/tls/utility.h, test/extensions/transport_sockets/tls/utility_test.cc
Signed-off-by: Sunil Narasimhamurthy <13044744+suniltheta@users.noreply.github.com>
Commit Message: tls: SAN with wildcard after string match dns name
Testing: Updated unit testing
Release Notes: Included bug fix description
[Optional Fixes #Issue] #18235
=> tls: SAN with wildcard after string match dns name

bazel/envoy_binary.bzl
This is the default on apple platforms and is also ignored and produces
a warning:
```
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
```
=> bazel: remove -pie on apple platforms

source/common/common/dns_utils.cc, source/common/common/matchers.cc, source/common/common/matchers.h, source/common/common/utility.h, source/common/conn_pool/conn_pool_base.cc, source/common/filesystem/file_shared_impl.h, source/common/router/config_impl.cc, source/common/router/config_utility.cc, source/common/router/header_parser.cc, source/common/router/rds_impl.cc, source/common/router/reset_header_parser.cc, source/common/router/router.cc, source/common/router/router_ratelimit.cc, source/common/router/scoped_config_impl.cc, source/common/router/scoped_rds.cc, source/common/router/scoped_rds.h, source/extensions/network/dns_resolver/cares/dns_impl.cc, test/per_file_coverage.sh
part of https://github.com/envoyproxy/envoy/issues/19172
=> source: more GCOVR removal

api/envoy/service/ext_proc/v3/external_processor.proto
Signed-off-by: Chet Nichols III chet@apple.com
Commit Message: api docs: improve wording of ext_proc ImmediateResponse.Details field
Addition Details: I had been trying to figure out a good way to provide more internally-derived feedback from an *ext_proc* implementation to *envoy* (without needing to do things like set response headers or rely on a separate log file), and was led to the discovery that the `ImmediateResponse.Details` field actually populates `%RESPONSE_CODE_DETAILS%` for use in access logging.
Due to how much better this discovery made my life, I am hoping it will make other people's lives better as well.
Testing: Leveraged existing unit tests
=> api docs: improve wording of ext_proc ImmediateResponse.Details field

bazel/foreign_cc/luajit.patch, bazel/foreign_cc/moonjit.patch
This prevents target LDFLAGS from affecting host tools,
and it matches the existing behavior of CFLAGS.
=> lua: clear LDFLAGS for host tools.

ci/docker_ci.sh
No doc for `docker buildx` that `TYPE` is useful.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: remove useless assign

docs/root/version_history/v1.14.0.rst, docs/root/version_history/v1.8.0.rst
It is a historical issue indeed, not sure it is the best way to fix it.
Commit Message: fix RBAC proto links.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> doc: fix rbac proto links

ci/Dockerfile-envoy, ci/docker_ci.sh
Part of #19781
Commit Message: do not build for alpine anymore.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docker: remove alpine build

docs/root/version_history/v1.11.0.rst
Commit Message: Fix dead links.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #19840
=> doc: fix dead links

ci/docker_ci.sh
The script doesn't load image to docker daemon anymore on Linux so no need to `docker tag`.
Testing: local
=> ci: fix docker push

bazel/foreign_cc/luajit.patch, bazel/foreign_cc/moonjit.patch
=> lua: don't strip the binary.

api/envoy/api/v2/cluster/circuit_breaker.proto, api/envoy/api/v2/cluster/filter.proto, api/envoy/api/v2/cluster/outlier_detection.proto, api/envoy/api/v2/listener/listener.proto, api/envoy/api/v2/listener/listener_components.proto, api/envoy/api/v2/listener/quic_config.proto, api/envoy/api/v2/listener/udp_listener_config.proto, tools/protoxform/protoprint.py
fixes us generating an invalid ruby_package for protobuf.
Signed-off-by: Cynthia <cynthia@coan.dev>
We should probably talk about back-porting as right now generating any packages with ruby is broken.
Risk Level: Should be none, this only changes `ruby_package` which was broken before.
Testing:
- Generated the protobufs with the changed package names, and validated that generation succeeds.
Release Notes: Pending backport discussions.
Fixes #19814
=> fix invalid ruby_package gen from protoxform

source/common/grpc/BUILD, source/common/grpc/buffered_async_client.h, source/common/grpc/buffered_message_ttl_manager.h, test/common/grpc/BUILD, test/common/grpc/buffered_async_client_test.cc, test/common/grpc/buffered_message_ttl_manager_test.cc
Commit Message: grpc: implement TTL manager to re-buffer pending messages for bidirectional gRPC 
Additional Description: Related with #17486. This PR provides the TTL manager for buffered bidirectional gRPC messages.
Testing: Unit
=> grpc: implement TTL manager to re-buffer pending messages for bidirectional gRPC

.bazelrc
Commit Message: include contrib source coverage
Additional Description: fix the issue that bazel coverage doesn't do coverage of source code in contrib
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/19729
=> Contrib coverage

.azure-pipelines/bazel.yml, .azure-pipelines/cleanup.sh, .azure-pipelines/pipelines.yml
This reverts commit e330009658366a518c54ee747caca0a5dae6abe9.
I added this previously as it was slowing down ci and it didnt seem necessary - but for #19275 i think we need to revert
i have some additional space saving that we could do, but tbh this is probably enough
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Revert "ci: Dont remove packages in ci jobs (#17146)"

source/common/network/utility.cc, source/common/network/utility.h, source/server/connection_handler_impl.cc, test/server/connection_handler_test.cc
Commit Message: Fix ConnectionHandlerImpl matching correct any address
* Fix https://github.com/envoyproxy/envoy/pull/19362 using the `Network::Utility::getIpv4AnyAddress` with wrong way. `Utility::getIpv4AnyAddress` returns a singleton of any address instance, it won't work with port parameter. This also leads to istio integration test failed https://github.com/istio/istio/pull/37004
* Add more checks for avoid return shutdown listener when redirect.
* Add assertion ensure the redirect won't consider non-ip address.
Risk Level:low
Co-authored-by: Yuchen Dai <silentdai@gmail.com>
=> Fix ConnectionHandlerImpl matching correct any address

source/common/buffer/buffer_impl.cc, source/common/buffer/buffer_impl.h
=> buffer: add explicit cast to remove narrowing warning

docs/root/start/install.rst
Part of #19781
Commit Message: remove alpine image info.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> doc: remove alpine info

.github/workflows/codeql-daily.yml, .github/workflows/codeql-push.yml
Fix errors from CodeQL about codeql-action being out-of-date.
=> codeql: upgrade codeql-action to 1.0.32.

OWNERS.md
There is consensus amongst @envoyproxy/senior-maintainers  around Yan
joining us. Welcome!
Risk level: Very low
Testing: Many years of Envoy contribution and maintainer efforts.
=> owners: promote Yan to senior maintainer.

test/run_envoy_bazel_coverage.sh
We're on the border of 24% and a recent merge has caused this to drop to
23.9%. Until we have a systematic plan to boost fuzz coverage (something
the Google Envoy team is working on), dropping this to 23.75% to prevent
further flakes.
Cheers,
Harvey
=> test: drop fuzz coverage.

source/extensions/filters/http/jwt_authn/extractor.cc, test/extensions/filters/http/jwt_authn/extractor_test.cc
To fix https://github.com/envoyproxy/envoy/issues/19772
Even if "from_cookie" is specified, the current code is still trying to find JWT token from the default location.
Testing: unit-test
=> jwt_authn: not use default locations if from_cookie is used

docs/root/version_history/current.rst, source/common/http/conn_manager_impl.cc, source/common/http/conn_manager_impl.h, source/common/http/filter_manager.cc, source/common/http/filter_manager.h, source/common/router/router.cc, source/common/router/router.h, source/common/runtime/runtime_features.cc, test/common/router/router_test.cc, test/mocks/http/mocks.h
Commit Message: http: envoy.reloadable_features.internal_redirects_with_body deprecation
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #19506
=> http: envoy.reloadable_features.internal_redirects_with_body deprecation

test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
Problem description:
Envoy CONNECT message handling can terminate the CONNECT message and send the payload upstream as raw TCP data.  
This PR is to add a integration test for it.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Adding an integration test to verify CONNECT termination works with DFP config

configs/envoyproxy_io_proxy_http3_downstream.yaml, configs/original-dst-cluster/README.md
Signed-off-by: Sunil Narasimhamurthy <sunnrs@amazon.com>
**Commit Message:** docs: Fix few typos in a README and a yaml
Additional Description: The new config file name is [proxy_config.yaml](https://github.com/envoyproxy/envoy/blob/main/configs/original-dst-cluster/proxy_config.yaml) where README refers to them as json file. Also another small typo.
Testing: NA
=> docs: Fix few typos in a README and a yaml

source/server/admin/admin_filter.cc
Commit Message: Reduce logging severity from error to info in admin filter
Additional Description: Nighthawk is reliant on no error logs to determine successful runs. Logging this message as an error causes nighthawk tests to fail. 
Testing: unit testing.
Signed-off-by: tomjzzhang <4367421+tomjzzhang@users.noreply.github.com>
=> admin:reduce logging severity in filter from error to info

test/integration/integration_test.cc
Commit Message: Disable IpVersions/IntegrationTest.AllWorkersAreHandlingLoad for OSX due to flakes.
Risk Level: 
Testing: 
Docs Changes:NA
Platform Specific Features: 
Related Issue: #19807
=> Disable IpVersions/IntegrationTest.AllWorkersAreHandlingLoad for OSX.

docs/root/version_history/current.rst, source/common/common/regex.cc, source/common/common/regex.h, source/common/runtime/runtime_features.cc, test/common/common/regex_test.cc
Testing: n/a
Part of https://github.com/envoyproxy/envoy/issues/19847
=> re: removing histograms, tweaking runtime access

source/common/http/conn_manager_impl.cc, source/common/runtime/runtime_features.cc
envoy.reloadable_features.allow_response_for_timeout is supposed to be removed but there is something left.
kill it with fire
Testing:
Docs Changes:
Release Notes:
Fixes #16005
=> hcm: remove allow_response_for_timeout, cont

envoy/network/connection_handler.h, source/common/quic/active_quic_listener.cc, source/common/quic/active_quic_listener.h, source/server/active_raw_udp_listener_config.cc, source/server/active_raw_udp_listener_config.h, source/server/connection_handler_impl.cc, test/common/quic/active_quic_listener_test.cc
part of https://github.com/envoyproxy/envoy/issues/19847
=> quic: using real runtime, not runtime singleton

support/hooks/pre-push
Does not seem to be running in CI right now.
=> hooks: disable pedantic spelling in pre-push hook

test/extensions/key_value/file_based/key_value_store_test.cc
Path `/foo` might be writable so the flush actually works therefore the
test fails. Replacing it with a path that's more likely to fail upon an
attempt to write works better.
Signed-off-by: Jonh Wendell <jonh.wendell@redhat.com>
=> test: harden key/value test

ci/filter_example_setup.sh
This file needs to be copied otherwise bazelisk picks whichever current
version is out there which could break with any release
=> bazel: copy .bazelversion for envoy filter examples (#18730)

contrib/kafka/filters/network/source/protocol/generator.py, contrib/kafka/filters/network/source/serialization.h, docs/root/configuration/listeners/network_filters/kafka_broker_filter.rst
Commit Message: kafka: handle all request types (requires handling of int64_t)
Additional Description: add the remaining request types there were missed over the most recent updates.
Testing: integration tests; manual tests (new APIs)
=> kafka: handle all request types (requires handling of int64_t)

envoy/network/connection.h, envoy/network/transport_socket.h, source/common/network/connection_impl.cc, source/common/network/connection_impl.h, source/common/network/happy_eyeballs_connection_impl.h, source/common/network/raw_buffer_socket.h, source/common/quic/quic_filter_manager_connection_impl.cc, source/common/quic/quic_filter_manager_connection_impl.h, source/extensions/transport_sockets/alts/tsi_socket.h, source/extensions/transport_sockets/common/passthrough.cc, source/extensions/transport_sockets/common/passthrough.h, source/extensions/transport_sockets/starttls/starttls_socket.h, source/extensions/transport_sockets/tls/ssl_socket.cc, source/extensions/transport_sockets/tls/ssl_socket.h, source/server/api_listener_impl.h, test/extensions/transport_sockets/common/passthrough_test.cc, test/extensions/transport_sockets/starttls/starttls_socket_test.cc, test/extensions/transport_sockets/tls/ssl_socket_test.cc, test/mocks/network/connection.h, test/mocks/network/transport_socket.h, test/server/api_listener_test.cc, tools/spelling/spelling_dictionary.txt
Add a configureInitialCongestionWindow method to Envoy::Network::Connection to set the initial congestion window.
QUIC connections will use QuicConnection::AdjustNetworkParameters to set
the congestion window.
TCP connections will delegate to the TransportSocket, which is a no-op
by default because there is no portable api to set TCP congestion
window. An application can use a custom TransportSocket and override the
method to set the congestion window in a proprietary way.
Signed-off-by: Bin Wu <wub@google.com>
Commit Message: Add a configureInitialCongestionWindow method to Envoy::Network::Connection to set the initial congestion window.
Testing: None, just adding an interface that is not used in OSS envoy. I'll test it in my application tests.
=> Add a configureInitialCongestionWindow method to Envoy::Network::Connection

examples/brotli/Dockerfile-service, examples/cache/Dockerfile-service, examples/cors/backend/Dockerfile-service, examples/cors/frontend/Dockerfile-service, examples/csrf/crosssite/Dockerfile-service, examples/csrf/samesite/Dockerfile-service, examples/double-proxy/Dockerfile-app, examples/ext_authz/upstream/service/Dockerfile, examples/front-proxy/Dockerfile-jaeger-service, examples/front-proxy/Dockerfile-service, examples/gzip/Dockerfile-service, examples/load-reporting-service/Dockerfile-http-server, examples/locality-load-balancing/Dockerfile-server, examples/win32-front-proxy/Dockerfile-service
Currently verify_examples is failing due to a problem with flask dependencies
I tested this with various versions of flask and all below v2 seem to have the problem - i have therefore updated all the examples to current latest 2.0.3
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fix #20037
=> examples: Fix flask import

test/benchmark/main.cc
Commit Message: currently running a benchmark binary with `--help` just shows the help for the TCLAP options: `--runtime_feature`, `--skip_expensive_benchmark`, and `--version`, but doesn't tell you about any of the google benchmark library options, such as filtering for which tests to run, or adding a repeat-count with statistical analysis.
This change emits the benchmark help after the tclap help when the user specifies --help.
Testing: just ran a perf test with --help and without
Fixes: #15076
=> perf: show benchmark library help in addition to tclap when --help is specfied

api/envoy/config/listener/v3/listener_components.proto
Problem description:
Add API definition for ECDS listerner filter support. This is to add API change for issue: https://github.com/envoyproxy/envoy/issues/20049.
Build:
passed
Testing:
passed
Release Notes:
N/A
Issues: ecds: add support for listener filters #20049
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Add API definition for ECDS listerner filter support

docs/root/configuration/operations/tools/router_check.rst, test/tools/router_check/coverage.cc, test/tools/router_check/coverage.h, test/tools/router_check/router.cc, test/tools/router_check/router.h, test/tools/router_check/test/config/DirectResponse.golden.proto.json, test/tools/router_check/test/config/Redirect4.golden.proto.json, test/tools/router_check/test/config/Redirect4.yaml, test/tools/router_check/test/route_tests.sh, test/tools/router_check/validation.proto
Signed-off-by: Zurab Svianadze <zurab@google.com>
Commit Message: A new validation has been added to the router check tool that allows to write tests with redirect response code assertions.
Testing:
Docs Changes:
Release Notes:
=> Router check tool: add redirect response code validation

tools/code_format/check_format.py, tools/code_format/check_format_test_helper.py
Commit Message: tools: Improve check_format error message for CondVar::waitFor().
Additional Description: This check can have false positives if a TimeSystem variable has a name the linter doesn't expect, so clarify that.
Testing: tools/code_format/check_format.py check (saw only clang-format errors); ./ci/run_envoy_docker.sh './ci/do_ci.sh tooling'
=> tools: Improve check_format error message for CondVar::waitFor().

source/common/http/filter_manager.cc, source/common/http/filter_manager.h
Commit Message: http: fix typo in filter manager
Additional Description: the method name has1xxheaders does not comply with the camel case naming convention and should be has1xxHeaders like the following method do1xxHeaders
Testing: N/A
=> http: fix typo in filter manager

source/common/upstream/outlier_detection_impl.cc, test/common/upstream/outlier_detection_impl_test.cc
Commit Message: Reset Consecutive Local Origin Failure counter when unejecting a host
to ensure that the host will be re-ejected when envoy experiences
local origin failure for the host.
this commit fixes #18950
Testing: Verfied that I can no longer reproduce the bug with the fix
Docs Changes:
Release Notes:
=> Reset Consecutive Local Origin Failure counter

source/common/upstream/outlier_detection_impl.cc, test/common/upstream/outlier_detection_impl_test.cc
This reverts commit f3f58333f161199946522e4dcdb0c4048e1848e8 (#19205)
as it breaks CI.
Commit Message: Revert "Reset Consecutive Local Origin Failure counter (#19205)"
=> Revert "Reset Consecutive Local Origin Failure counter (#19205)"

source/server/server.cc
Commit Message: listener: listener: add note for the reuse port old default value compatible code
according the discussion https://github.com/envoyproxy/envoy/pull/19977#discussion_r812126652
Testing: n/a
=> listener: add note for the reuse port old default value compatible code

source/extensions/transport_sockets/tls/ocsp/ocsp.cc, test/extensions/transport_sockets/tls/ocsp/asn1_utility_test.cc, test/extensions/transport_sockets/tls/ocsp/ocsp_test.cc
PR #12307 added a handrolled OCSP parser, but handled the version field incorrectly.
ASN.1 tags are more than just a number. They also have a class (universal, context-specific, application, or private). Class zero is "universal", which is for the built-in types like INTEGER or SEQUENCE.
A tag written like [1] is not universal but "context-specific". That means one needs to write `CBS_ASN1_CONTEXT_SPECIFIC | 1`, not plain 1. Plain 1 is BOOLEAN. ASN.1 TLVs additionally are either constructed
or primitive. Explicitly-tagged types are always constructed (they contain other TLVs). The constructed bit is encoded alongside the tag, so CBS/CBB treat it as part of the tag.
See https://letsencrypt.org/docs/a-warm-welcome-to-asn1-and-der/ for further background. BoringSSL's CBS/CBB …
=> tls: Fix OCSP version tag handling

docs/root/intro/life_of_a_request.rst
`UpstreamRequest::encoderHeaders()` should be [UpstreamRequest::encodeHeaders](https://github.com/envoyproxy/envoy/blob/dffddfad2db79ed01d9985da2e0de181aedfb865/source/common/router/upstream_request.cc#L244).
=> docs: fix a typo

source/extensions/network/dns_resolver/cares/dns_impl.cc, source/extensions/network/dns_resolver/cares/dns_impl.h, test/common/http/header_map_impl_test.cc, test/extensions/network/dns_resolver/cares/dns_impl_test.cc
Commit Message: c-ares - change from assert to logging for failure in getifaddrs
Additional Description: this assert crashes Envoy in situations where maintaining existing, non filtering behavior is more desirable.
Signed-off-by: José Ulises Niño Rivera <junr03@users.noreply.github.com>
=> c-ares: change from assert to logging for failure in getifaddrs

docs/root/intro/arch_overview/advanced/attributes.rst, source/extensions/filters/common/expr/context.cc, source/extensions/filters/common/expr/context.h, test/extensions/filters/common/expr/context_test.cc
Commit Message: Add ability to get request query from the URL without any decoding as an attribute.
Risk Level: low (new attribute)
Testing: unit
Release Notes:
Fixes: https://github.com/envoyproxy/envoy/issues/19724
=> attributes: add request.query

test/fuzz/README.md
Commit Message: doc: fix the command to run fuzzing test
The command is missing a space. lead to unknow param as below
```
ERROR: --test/common/common/base64_corpus :: Unrecognized option: --test/common/common/base64_corpus
```
Testing: n/a
Docs Changes: doc fix
=> doc: fix the command to run fuzzing test

source/extensions/access_loggers/common/BUILD, source/extensions/access_loggers/common/grpc_access_logger.h, source/extensions/access_loggers/common/grpc_access_logger_utils.cc, source/extensions/access_loggers/common/grpc_access_logger_utils.h, source/extensions/access_loggers/grpc/grpc_access_log_impl.cc, source/extensions/access_loggers/grpc/grpc_access_log_impl.h, source/extensions/access_loggers/open_telemetry/grpc_access_log_impl.cc, source/extensions/access_loggers/open_telemetry/grpc_access_log_impl.h, test/extensions/access_loggers/common/grpc_access_logger_test.cc, test/extensions/access_loggers/grpc/grpc_access_log_impl_test.cc, test/extensions/access_loggers/open_telemetry/grpc_access_log_impl_test.cc
Commit Message: access log: cleanup arguments in gRPC access log
Additional Description: This refactor is needed to draw proto config around the various classes in access log. 
Testing: N/A
Docs Changes:
Release Notes:
=> access log: cleanup arguments in gRPC access log

tools/code_format/check_format.py
**Commit Message:** This change fixes an issue in the code formatter where explicitly
excluded paths are incorrectly matched when the script is provided
arguments that do not start with './' or that end with a trailing
slash.
To address this issue this change normalizes paths before checking
if the path is excluded.
**Additional Description:** I think the core issue here is the use of direct string matching for excluded files. Refactoring to address the root cause is out of scope for this change, but will likely need to be done in the future.
**Risk Level:** low
**Testing:** Ran code format with arguments of the form 'path/to/dir' and './path/to/dir/', verifying that excluded files are not formatted as expected.
**Docs Changes:** n/a
**Release Notes:** n/a
**Platform Specific Features:** …
=> code_format: fix path matching

.github/workflows/codeql-push.yml
Instead of showing ".github/workflows/codeql-push.yml" for the CodeQL workflow it will now say "CodeQL"
=> build: Add a name to the CodeQL workflow

bazel/repositories.bzl, source/common/common/BUILD, source/common/common/key_value_store_base.cc, source/common/http/alternate_protocols_cache_impl.cc, source/common/http/alternate_protocols_cache_impl.h, test/common/http/alternate_protocols_cache_impl_test.cc, test/extensions/key_value/file_based/key_value_store_test.cc
Was brought up to Envoy Security team.
Commit Message:  Alt srv-cache no longer modifies the keystore while iterating.
Additional Description: modifications to keystore during iterate can cause us to rehash but we have no iterator stability => sad times.
=> Alt Service Cache: Alt srv-cache no longer modifies the keystore while iterating.

source/server/listener_impl.cc, test/server/listener_manager_impl_test.cc
Commit Message: listener: ensure Ipv6 any address is valid on ipv4_compat set
The Ipv6 address is valid when ipv4_compat set. This check is missing https://github.com/envoyproxy/envoy/pull/19716
=> listener: ensure Ipv6 any address is valid on ipv4_compat set

source/common/formatter/substitution_formatter.cc, test/common/formatter/substitution_formatter_test.cc
This is a continuation of #19383 
Add a case in the SubstitutionFormatter to replace '%%' with '%'.
This allows users to escape % in their configurations, fixing https://github.com/envoyproxy/envoy/issues/15159.
Signed-off-by: Aidan Hahn [aidanhahn@datawire.io](mailto:aidanhahn@datawire.io)
Commit Message: formatter: escape percent sign in response format
Docs Changes:
Release Notes:
Fixes: https://github.com/envoyproxy/envoy/issues/15159
=> formatter: escape percent sign in response format

contrib/sip_proxy/filters/network/source/BUILD, contrib/sip_proxy/filters/network/source/conn_manager.cc, contrib/sip_proxy/filters/network/source/conn_manager.h, contrib/sip_proxy/filters/network/source/decoder.h, contrib/sip_proxy/filters/network/source/router/BUILD, contrib/sip_proxy/filters/network/source/router/router_impl.cc, contrib/sip_proxy/filters/network/source/router/router_impl.h, contrib/sip_proxy/filters/network/source/utility.h, contrib/sip_proxy/filters/network/test/conn_manager_test.cc, contrib/sip_proxy/filters/network/test/mocks.cc, contrib/sip_proxy/filters/network/test/mocks.h
Commit Message: sip-proxy: get load address from context localInfo
Additional Description: Use the unique service ip from localinfo instead of connection info
Testing: Ut/Mt
=> sip-proxy: get load address from context localInfo

source/common/conn_pool/conn_pool_base.cc, source/common/conn_pool/conn_pool_base.h, source/common/http/http3/conn_pool.h, source/common/tcp/conn_pool.h, test/common/conn_pool/conn_pool_base_test.cc
Commit Message: refactor decr|incrConnectingAndConnectedStreamCapacity() to take into consideration whether the client is connecting or not while updating cluster and conn pool connecting stream capacity.
Additional Description: also replace some call sites of effectiveConcurrentStreamLimit() with currentUnusedCapacity() where the client is connecting because that's when these two are the same.
This change is preparing for upcoming 0-RTT support in https://github.com/envoyproxy/envoy/pull/20167 which allows connecting client to open new streams and transit to other non-CONNECTING state.
Risk Level: low, no behavior change
Part of #18715
=> conn pool: refactor connecting capacity accounting

source/common/network/address_impl.cc
Commit Message: address: reuse InitHelper for Ipv6Instance
Testing: n/a
=> address: reuse InitHelper for Ipv6Instance

test/extensions/filters/http/csrf/BUILD
Commit Message: CI: Increase shard count since CSRF times out under TSAN.
Testing: ran under tsan with additional sharding:
`Stats over 20 runs: max = 126.8s, min = 123.8s, avg = 125.5s, dev = 0.7s`
=> CI: Increase shard count since CSRF times out under TSAN.

distribution/BUILD, distribution/debian/BUILD, distribution/debian/copyright, distribution/debian/packages.bzl, distribution/debian/postinst, distribution/debian/preinst, distribution/distros.yaml, distribution/distrotest.sh, distribution/packages.bzl, tools/distribution/BUILD
breakout pr from #17979 containing only the bazel rules (and no ci changes)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel: Add rules for debian packaging

test/integration/http_integration.h
Commit Message: remove dead code. 
Original PR is here: https://github.com/envoyproxy/envoy/pull/5228/files#diff-8e768fa8b2a194d09414fa6572b201d58caf7e973c5535b0fc35c2304ca9198cR368-R373
Was moved in Moved into https://github.com/envoyproxy/envoy/pull/5941/files#diff-478cdae3dba52e78ed6d1a2e4e4eb4a1aba3e80178b6c8d14707501fc1fb2ddbR56-R62
but method declaration was missed
Testing: na
=> Cleanup: Remove dead code.

docs/root/version_history/current.rst, source/common/runtime/runtime_features.cc
Part of https://github.com/envoyproxy/envoy/issues/20254
=> undeprecating used re2 knobs

source/extensions/filters/network/dubbo_proxy/config.cc, source/extensions/filters/network/http_connection_manager/config.cc, test/common/upstream/subset_lb_test.cc, test/extensions/filters/listener/tls_inspector/tls_inspector_test.cc, test/integration/extension_discovery_integration_test.cc, test/integration/listener_lds_integration_test.cc
The multi line json config is annoying because it doesn't contain timestamp and occupy a large screen space.
Note that this log behavior in HCM aligns was done in network filter at listener and cluster. 
Also degrade some obvious non-error logs.
Testing:
Docs Changes:
Release Notes:
=> log: log each http filter config in single line

bazel/v8.patch
I've submitted this upstream as well, but this unblocks us temporarily.
Fixes https://github.com/envoyproxy/envoy/issues/19916
=> bazel: Patch m1 support for v8

test/common/router/config_impl_test.cc
Fix ahead to accommodate future changes in absl::Status which include stack trace in error strings.
=> Use regex to match exception message from absl::Status

source/extensions/filters/http/local_ratelimit/local_ratelimit.cc, source/extensions/filters/http/local_ratelimit/local_ratelimit.h
Signed-off-by: hejianpeng <hejianpeng2@huawei.com>
Commit Message: add ratelimit populate descriptors log to help debug
Testing:
Docs Changes:
Release Notes:
=> add ratelimit populate descriptors log

STYLE.md, source/common/common/thread.cc
GUARDED_BY is deprecated and replaced with ABSL_GUARDED_BY
=> Fix deprecated GUARDED_BY macro and update doc

source/common/common/key_value_store_base.cc
This is not a strictly valid C++ and stricter configured internal compiler complains.
=> Fully qualify template parameters in variable definition

source/common/stats/thread_local_store.cc, source/common/stats/thread_local_store.h
Commit Message: remove never used allocator instance in the thread local store
Additional Description: simple cleanup.
Testing: N/A.
=> remove never used allocator instance in the thread local store

docs/root/start/sandboxes/dynamic-configuration-filesystem.rst
Commit Message: doc: fix wrong emphasize line number in cds demo config
Additional Description: The [official doc](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/dynamic-configuration-filesystem) emphasized a wrong line.
Testing: n/a
Docs Changes: doc fix
Release Notes:  n/a
Signed-off-by: YuanYingdong <1975643103@qq.com>
=> doc: fix wrong emphasize line in cds demo config

test/integration/listener_lds_integration_test.cc
=> Fix IgnoreUnknownOptionalHttpFilter test to work in IPv6 only environment

test/common/matcher/BUILD
=> Add missing dependency for //test/common/matcher:matcher_test

envoy/stream_info/filter_state.h, source/common/stream_info/filter_state_impl.cc, source/common/stream_info/filter_state_impl.h, test/common/stream_info/filter_state_impl_test.cc
Commit Message: Allow access to mutable filter state objects via shared pointer. This allows copying objects to different streams (e.g. from downstream to upstream filter state, or from downstream to another internal downstream filter state). Read-only objects are locked to the stream to avoid mutation via another stream.
Testing: unit
=> filter_state: add shared pointer accessor

api/API_VERSIONING.md
Signed-off-by: Mark D. Roth <roth@google.com>
Commit Message: API versioning policy: remove incorrect exception for not-implemented-hide
Testing: N/A
=> API versioning policy: remove incorrect exception for not-implemented-hide

docs/root/version_history/current.rst, source/extensions/tracers/xray/daemon.proto, source/extensions/tracers/xray/tracer.cc, source/extensions/tracers/xray/tracer.h, test/extensions/tracers/xray/tracer_test.cc, tools/spelling/spelling_dictionary.txt
In Xray tracing, there is the concept of an xray segment and each segment can contain subsegments. The segment and subsegment maps to Envoy's parent and child spans. In the existing xray extension implementation, each span is emitted independently without the distinction whether the span is a child or not, so Xray treats each span as its own segment. 
Whereas in fact, the Xray extension should annotate child spans as subsegments by setting a key value pair "type=subsegment" in the segment payload: https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-subsegments. This PR is to perform this annotation so Xray subsegments are correctly related to their parent segment. 
Testing: unit …
=> xray tracer: correctly annotate child spans as xray subsegments

source/server/server.cc, test/integration/multi_envoy_test.cc
the envoy bug stats are global and complicated, and I think we can just skip them for multi-envoy rather than switch to getpid() and hash maps.
=> multi-envoy: fixing shutdown ordering bugs

source/extensions/filters/network/dubbo_proxy/dubbo_hessian2_serializer_impl.cc, test/extensions/filters/network/dubbo_proxy/dubbo_hessian2_serializer_impl_test.cc
Commit Message: dubbo: fix unexpected exception for null but with attachments response type
When dubbo providers response null value but with attachments, the error body length check will result in an unexpected exception.
And this PR fix it.
**This bug is reported by the @zhnxin in the #19635. But @zhnxin is unresponsive, so I pick this up to complete this fix.
Thanks a lot to the @zhnxin. 🌷 **
=> dubbo: fix unexpected exception for null but with attachments response type

source/common/conn_pool/conn_pool_base.cc, source/common/conn_pool/conn_pool_base.h, source/common/http/conn_pool_base.cc, source/common/http/http3/conn_pool.cc, source/common/http/mixed_conn_pool.cc, source/common/tcp/conn_pool.cc, test/common/conn_pool/conn_pool_base_test.cc, test/common/http/http2/conn_pool_test.cc, test/common/http/http3/conn_pool_test.cc, test/common/tcp/conn_pool_test.cc
Commit Message: change ConnectionPool::ActiveClient::State enum values to Camel casing according to Envoy style guide. All the enum values are single word right now, so upper casing isn't blowing up the format check, but once there is state value represented by more than one word, it's gonna cause format check to fail.
Risk Level: low, refactoring only
=> conn pool: fix ActiveClient::State enum format

OWNERS.md
X41 team is working on fixing OSS-Fuzz bugs and need access to the `setec` repo for PRs that may be a security vulnerability.
Testing: N/A
=> Add X41 team to the setec ACL

tools/code_format/check_format.py
Commit Message: Update check_format.py to clang-format-12
Testing: Tool-only
=> Update check_format.py to clang-format-12

source/extensions/filters/http/ext_proc/BUILD, source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, test/common/grpc/grpc_client_integration.h, test/extensions/filters/http/ext_proc/BUILD, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/ordering_test.cc, test/extensions/filters/http/ext_proc/streaming_integration_test.cc, test/extensions/filters/http/grpc_json_transcoder/grpc_json_transcoder_integration_test.cc
This reverts commit 3b75d302bb67cc2b2594c81b7695626c8e96462d.
This commit was causing CI flakes. See example [here](https://github.com/envoyproxy/envoy/pull/20244#issuecomment-1071538849)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Revert "Defer Processing: Parameterize test for filters to avoid bit rot (#20244)"

api/envoy/config/route/v3/route_components.proto, docs/root/version_history/current.rst, source/common/router/router_ratelimit.cc, source/common/router/router_ratelimit.h, test/common/router/router_ratelimit_test.cc
Signed-off-by: hejianpeng <hejianpeng2@huawei.com>
before:
```yaml
- header_value_match:
descriptor_value: "svc1"
expect_match: true
headers:
- name: :path
prefix_match: /svc1
```
```console
[2022-03-14 13:45:02.793][3414241][debug][filter] [external/envoy/source/extensions/filters/http/local_ratelimit/local_ratelimit.cc:120] populate descriptors: key=request_method value=GET
[2022-03-14 13:45:02.793][3414241][debug][filter] [external/envoy/source/extensions/filters/http/local_ratelimit/local_ratelimit.cc:120] populate descriptors: key=header_match value=svc1
```
after:
```
- header_value_match:
descriptor_key: path_match
descriptor_value: "svc1"
expect_match: true
headers:
- name: :path
prefix_match: /svc1
```
```console
[2022-03-14 13:45:35.923][3414669][debug][filter] …
```
=> HeaderValueMatch support custom descriptor key

contrib/cryptomb/private_key_providers/source/cryptomb_private_key_provider.cc, contrib/cryptomb/private_key_providers/test/ops_test.cc, docs/root/version_history/current.rst
cryptomb: drop RSA signing PKCS1 v1.5 padding support.
Drop RSA signing PKCS1 v1.5 padding support (which wasn't functional). Only keep the RSA-PSS for now. If someone needs PKCS1 v1.5, we can re-add it properly later.
Testing: unit tests, manual testing
Platform Specific Features: CryptoMB extension works on 3rd Gen Intel Xeon Scalable processors.
=> cryptomb: remove PKCS1_5 padding support.

source/extensions/filters/http/ext_proc/BUILD, source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, test/common/grpc/grpc_client_integration.h, test/extensions/filters/http/ext_proc/BUILD, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/ordering_test.cc, test/extensions/filters/http/ext_proc/streaming_integration_test.cc, test/extensions/filters/http/grpc_json_transcoder/grpc_json_transcoder_integration_test.cc
Commit Message: Defer Processing: Parameterize test for filters to avoid bit rot.
Additional Description: This is simply https://github.com/envoyproxy/envoy/pull/20244 which was reverted due to merge fails from https://github.com/envoyproxy/envoy/commit/1a1373f31e4d3854ac09451b057270d2b97ef0b2. No longer use the Runtime singleton which was removed. [This is the only real change from 20244](https://github.com/envoyproxy/envoy/pull/20405/files#diff-1f838ae62058b3d3f17be73d5e0a141598f3be9f2b8ad304ac65001490b08a94R924-R925)
Risk Level: Med
Testing: Parameterized test to work with deferred processing
[Optional [API …
=> Defer Processing: Parameterize test for filters to avoid bit rot

docs/root/version_history/current.rst, source/common/router/router.cc, test/common/router/router_test.cc
Previously in the case that the default was 0, the fractional
percent variant of runtime lookup was not used. This uses that
variant in all cases while retaining default behavior. This leads
to the expected behavior.
Testing: Fixed tests
=> router: fix mirror policy runtime_fraction runtime lookup

test/common/http/conn_pool_grid_test.cc, test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc, test/extensions/filters/http/on_demand/on_demand_integration_test.cc, test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc, test/integration/http_integration.cc, test/integration/http_integration.h, test/integration/multiplexed_upstream_integration_test.cc, test/integration/protocol_integration_test.cc, test/integration/sds_dynamic_integration_test.cc, test/integration/vhds.h, test/integration/vhds_integration_test.cc, test/mocks/ssl/mocks.h
Upcoming https://github.com/envoyproxy/envoy/pull/20436 fixes QUIC to use auto_sni when it's configured.
The Envoy integration tests use auto_sni by default, but this causes problems for HTTP/3 which validates that the sni hostname (currently "host" for most test) matches the certificate (*.lyft.com for most tests).
Changing the tests independently of the fix PR per request.
=> test: fixing up hostnames

test/extensions/filters/http/kill_request/BUILD
coverage.
Commit Message: Increase crash integration test sharding as it takes a long time under coverage.
Additional Description: Ironically, I think automatic deflaking kept this one hidden from us as it'd occasionally pass from those retired attempts.
Testing: ran
Fixes #20444
=> Increase crash integration test sharding as it takes a long time under

test/common/access_log/access_log_manager_impl_test.cc
Signed-off-by: Guang Yang <pyrl247@gmail.com>
Fixes https://github.com/envoyproxy/envoy/issues/20084
Fix resource Competition in access_log_manager_impl_test.
"filesystem.write_total_buffered" sub in another thread after file_lock_ unlock, so we need to wait it.
Testing:
Docs Changes:
Release Notes:
=> [test case fix]: fix resource competition in access_log_manager_impl_test.

test/integration/tcp_tunneling_integration_test.cc
we had a connect test which was doing sendRawHttpAndWaitForResponse, which generally waits for a completely framed response, and the while point of CONNECT proxying is the "body" isn't ever complete.  Setting disconnect_after_headers_complete = true means the test finishes up after the headers are sent rather than waiting for a body which will never arrive.
=> test: fixing timeout

.github/workflows/check-deps.yml, .github/workflows/codeql-daily.yml, .github/workflows/codeql-push.yml, .github/workflows/pr_notifier.yml, .github/workflows/stale.yml
- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
Also, dependabot supports upgrading based on SHA.
- Also included permissions for actions to reduce the attack …
=> Pin actions to a full length commit SHA

docs/root/version_history/current.rst, source/common/router/router.cc, test/integration/header_integration_test.cc
Commit Message: ensure via_upstream is populated in RESPONSE_CODE_DETAILS for response headers
Testing: Manual testing
[Optional Fixes #Issue] Fixes #20413
=> ensure via_upstream is populated in RESPONSE_CODE_DETAILS for response headers

source/common/router/config_impl.cc, source/common/router/router.cc, test/common/router/router_test.cc, test/mocks/router/mocks.h
https://github.com/envoyproxy/envoy/pull/20424 had a regression
when runtimey key was not set but the default was set to not zero.
This change further cleans up the logic to make it more clear
as well as fixes the regression. Tests now use more of the
production code to protect against future regressions.
Testing: Updated tests
=> router: fix default mirror when runtime key not specified

docs/root/version_history/current.rst, source/extensions/tracers/xray/tracer.cc, source/extensions/tracers/xray/tracer.h, source/extensions/tracers/xray/xray_tracer_impl.cc, test/extensions/tracers/xray/tracer_test.cc, test/extensions/tracers/xray/xray_tracer_impl_test.cc
Commit Message: xray: use HTTP X-Forwarded-For header value inside xray span
Fixes: https://github.com/aws/aws-app-mesh-roadmap/issues/395
=> xray: use HTTP X-Forwarded-For header value inside xray span

bazel/README.md
As of Go 1.17 , installing packages with go get is deprecated
See https://go.dev/doc/go-get-install-deprecation
Signed-off-by: Toma Petkov <tpetkov@vmware.com>
Commit Message: bazel: Update buildifier/buildozer instructions
Additional Description: As of Go 1.17 , installing packages with go get is deprecated. See https://go.dev/doc/go-get-install-deprecation
Testing:
```sh
go install github.com/bazelbuild/buildtools/buildifier@latest
go install github.com/bazelbuild/buildtools/buildozer@latest
```
Docs Changes: Changed instructions for buildifier/buildozer
=> Update buildifier/buildozer instructions

api/envoy/config/route/v3/route.proto
Signed-off-by: Doug Fawley <dfawley@google.com>
Commit Message: route.proto: add is_optional field to ClusterSpecifierPlugin
When deploying a new cluster specifier plugin, it is often necessary to add it to the configuration before all clients can be updated to support it, with routing rules configured to prevent clients without support from selecting any routes referencing the plugin.  This field will allow those clients to suppress the default behavior of NACKing any resource containing the unknown plugin.
Testing: None
@markdroth @ejona86
=> route.proto: add is_optional field to ClusterSpecifierPlugin

docs/root/start/quick-start/run-envoy.rst
Listen to `127.0.0.1` will cause a `ERR_EMPTY_RESPONSE` when use docker, which will interrupt one's start process. It should be changed to `0.0.0.0` 😃
=> docs: quick start docker socket address to 0.0.0.0

docs/root/version_history/current.rst
Not sure why CI is not picking these up - i thought we added something previously
This PR just cleans up the current backtick issues in version history - i will investigate further why they are being missed
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: Cleanup backticks in version_history

source/common/router/router.cc, source/common/router/upstream_request.cc, test/common/router/router_2_test.cc, test/common/router/router_test.cc
Commit Message: router: inject tracing context in the upstream request
Move tracing context injecting to upstream request. We can reduce some unnecessary injectings by this way. And in the future, we can provide some more upstream infos (for example, upstream host) to `injectContext` call.
Testing: Unit.
=> router: inject tracing context in the upstream request

source/extensions/network/dns_resolver/cares/dns_impl.cc, source/extensions/network/dns_resolver/cares/dns_impl.h, test/extensions/network/dns_resolver/cares/dns_impl_test.cc
The code was not accounting for parallel queries in this path. Also
add more assertions to make similar issues easier to understand in
the future.
Risk Level: Medium (code is very tricky, hard to understand all implications of the change, and per TODO test coverage is missing on some clearly critical paths).
Testing: New failing test prior to fix
=> cares: fix bad cleanup of parallel All query during destroy

docs/root/api-docs/xds_protocol.rst
Commit Message: clarify xds docs on resource deletion
Additional Description: Resource deletion for non wildcard resource types like eds and rds will only happen on parent resource deletion for both Sotw and Incremental variants. This PR clarifies it in doc.
Testing: N/A
Release Notes:N/A
=> clarify xds docs on resource deletion

api/envoy/extensions/transport_sockets/tls/v3/tls.proto, test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc
Commit Message: remove useless comment for tls key log
Additional Description: [This comment](https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/transport_sockets/tls/v3/tls.proto#L134) is useless now. It should be [useful during this commit](https://github.com/envoyproxy/envoy/pull/19182/commits/d70fcc4aef9df89bcd1b83c84576796272731f67#r791849206), and [should be remove after this discussion](https://github.com/envoyproxy/envoy/pull/19182/commits/7d806e0c9ecfde5db69be6bbc3e81d121cfcbaf6#r818131121).
Testing: Testing with neither `local_address_range` nor `remote_address_range`
=> chore: remove useless comment for tls key log

test/extensions/filters/http/ext_proc/filter_test.cc
The addDefaultHeaders function takes a bool as its second argument.
If we want to set the method, we need to do that on the requestHeaders
object itself.
This seems to have been forgotten in
82b1f66df20d9577a24ea632f149481ba2f99edd.
Signed-off-by: Justin Mazzola Paluska <justinmp@google.com>
Testing: bazel test //test/extensions/filters/http/ext_proc:filter_test
=> Update OutOfOrder test to use new addDefaultHeaders interface

ci/build_setup.sh
The last consumer of this was removed in the linked commit
=> ci: remove unused variable (NFC)

contrib/sip_proxy/filters/network/source/tra/tra.h, contrib/sip_proxy/filters/network/source/tra/tra_impl.cc, contrib/sip_proxy/filters/network/source/tra/tra_impl.h, contrib/sip_proxy/filters/network/test/BUILD, contrib/sip_proxy/filters/network/test/app_exception_impl_test.cc, contrib/sip_proxy/filters/network/test/mocks.cc, contrib/sip_proxy/filters/network/test/mocks.h, contrib/sip_proxy/filters/network/test/tra_test.cc
Commit Message: Fix TRA Ut
Testing: Ut
Docs Changes:
Release Notes:
=> contrib-sipproxy: Fix TRA Ut

source/extensions/filters/listener/tls_inspector/tls_inspector.h
Commit Message: listener: fix tls inspector's maxReadBytes() return type
Testing: n/a
=> listener: fix tls inspector's maxReadBytes() return type

test/config/utility.cc, test/config/utility.h, test/extensions/access_loggers/grpc/http_grpc_access_log_integration_test.cc, test/extensions/filters/network/direct_response/direct_response_integration_test.cc, test/extensions/filters/network/echo/echo_integration_test.cc, test/extensions/stats_sinks/hystrix/hystrix_integration_test.cc, test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc, test/integration/base_integration_test.cc, test/integration/command_formatter_extension_integration_test.cc, test/integration/http_timeout_integration_test.cc, test/integration/idle_timeout_integration_test.cc, test/integration/integration_test.cc, test/integration/multiplexed_integration_test.cc, test/integration/original_ip_detection_integration_test.cc, test/integration/protocol_integration_test.cc, test/integration/socket_interface_integration_test.cc, test/integration/utility.cc, test/integration/utility.h, test/integration/xds_integration_test.cc
Follow up on https://github.com/envoyproxy/envoy/pull/20468 to future-proof against slow tests, by adding a default timeout to the raw connection driver
This caught a whole bunch of tests which were waiting 15s for delay close.
Testing: CI
=> test: switching one more wait to not infinitely time out for failures

api/envoy/type/matcher/v3/regex.proto
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: Clarify that RegexMatcher uses a full regex match

test/extensions/filters/listener/tls_inspector/BUILD, test/extensions/filters/listener/tls_inspector/tls_inspector_integration_test.cc, test/integration/BUILD
Part of https://github.com/envoyproxy/envoy/issues/9953
=> test: moving the tls inspector test to the extension directory

api/envoy/config/cluster/v3/cluster.proto, configs/encapsulate_in_http1_connect.yaml, configs/terminate_http1_connect.yaml, docs/root/version_history/current.rst, source/common/upstream/original_dst_cluster.cc, source/common/upstream/original_dst_cluster.h, test/common/upstream/original_dst_cluster_test.cc
Add an option in OriginalDstCluster type to override the original dst address by 
host header in load downstream load balance context.
Note that the :authority header is offered in HTTP CONNECT request. 
For example, if a HTTP request is `CONNECT 127.0.0.1:443 HTTP/1.1`
Envoy HTTP conn manager sets :authority to `127.0.0.1:443`. A TCP connection will
be established to this address via an original_dst cluster setting `use_http_authority`.
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]  part of #16503
[Optional [API …
=> cluster: add new config to restore original dst address from :authority header

envoy/config/extension_config_provider.h, source/common/filter/config_discovery_impl.h
Commit Message: upate filter config provider to return reference wrapper of filter factory cb
In the previous ecds implementation, we will always create a temp copy of `FactoryCb` which results in uncessary memory allocations and atomic operations (copy and destroy shared pointer in the `FactoryCb`).
Testing: N/A.
=> upate filter config provider to return reference wrapper of filter factory cb

source/extensions/filters/network/mongo_proxy/codec_impl.cc, test/extensions/filters/network/common/fuzz/network_writefilter_corpus/mongodb_proxy_2
Commit Message: mongodb_proxy: Enhance sanity check before accessing message header.
Fuzz tests showed an issue where bytes are read beyond the message end. This patch adds a corpus showing an assert because of the issue and a patch to fix it. Please comment, whether the log-message and return is appropriate here or if an exception should be thrown.
Testing: n/a
=> Check msg length in mongo proxy

docs/root/api-docs/xds_protocol.rst
Reverts envoyproxy/envoy#20523.
The change made in that PR was incorrect.  The incremental protocol variant does explicitly delete resources of all types, not just LDS and CDS.
=> Revert "clarify xds docs on resource deletion"

.bazelrc, bazel/external/googleurl.patch, bazel/repository_locations.bzl, source/common/http/BUILD
A newer version of googleurl also supports building without ICU, so we
can remove the patch that created an Envoy-specific build target.
Signed-off-by: Victor Vasiliev <vasilvv@google.com>
Testing: Dependency change; should be covered by existing tests.
Fixes #14743
=> Update googleurl to the latest version.

test/server/config_validation/config_fuzz_test.cc
Commit Message: Limit the number of endpoints in config_fuzz_test.
A config_fuzz_test having more than 10 endpoints configured takes a
significant amount of time to run, which leads to a timeout in when
more then 1 minute is needed. Limiting the number of endpoints to 10
still allows the fuzzer to generate a sufficiently complex config.
Testing: n/a
=> Limit num endpoints in config fuzz test

contrib/sip_proxy/filters/network/test/mocks.h, test/extensions/filters/network/thrift_proxy/mocks.h
`resetUpstreamConnection` should be a removed method of `DecoderFilter`.
=> filter: remove legacy mock function for DecoderFilter

bazel/external/googleurl.patch
The [recent update](https://github.com/envoyproxy/envoy/commit/74a32f3aa0a5b7ba118ba99cb0a3d61a24a900b2) broke Android builds because the clang shipped with the NDK version we use doesn't support these attributes.
I've submitted this upstream as well https://quiche-review.googlesource.com/c/googleurl/+/10961
=> bazel: Add googleurl patch for android

CODEOWNERS
Commit Message: delete useless section in CODEOWNERS
Additional Description: the section is useless since compression part has moved in this commit: https://github.com/envoyproxy/envoy/commit/fa385b2e9e8b269ad2a1c4723da9aac6b4bd4866#diff-fcf14c4b7b34fe7a11916195871ae66a59be87a395f28db73e345ebdc828085bR194
Risk Level: n/a (docs)
Testing: n/a
=> docs: delete useless section in CODEOWNERS

test/extensions/tracers/xray/fuzz_test.cc
Commit Message: Limit xray-fuzz input to reasonable size.
The fuzzer's input size is now limited to 4k to prevent timeouts
due to asan overhead.
Testing: n/a
=> Limit xray-fuzz input to reasonable size.

bazel/dependency_imports.bzl
This is required to support rust analyzer for IDEs
=> bazel: Add rustc source files

test/test_common/BUILD, test/test_common/status_utility.h, test/test_common/status_utility_test.cc
Commit Message: Add EXPECT_OK and IsOk to test_common/status_utility.h
Additional Description: Test helper functions.
Risk Level: None, just test helper functions.
Testing: Included tests for the tests.
=> Add EXPECT_OK and IsOk to test_common/status_utility.h

test/extensions/filters/http/common/fuzz/filter_fuzz_test.cc
Signed-off-by: Pradeep Rao <pcrao@google.com>
Disable failing filters in filter_fuzz_test as a temporary fix for #20737
Testing:
=> Disable test for failing filters in filter_fuzz_test

ci/README.md, ci/do_ci.sh
Now only `bazel.release` cover contrib, add this target will help developers.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: add contrib target

ci/build_setup.sh, ci/mac_ci_steps.sh, ci/windows_ci_steps.sh
This flag was removed from newer versions of bazel and apparently hasn't
done anything since 2019
https://github.com/bazelbuild/bazel/commit/2e48994ab8202796324df3c93ff9441a44b5ba4d
=> ci: remove no-op bazel option

docs/root/version_history/current.rst, source/common/config/new_delta_subscription_state.cc, source/common/config/xds_mux/delta_subscription_state.cc, test/common/config/delta_subscription_state_test.cc
Commit Message: delta-xds fix wildcard resource versions
Additional Description: Fixing a bug in delta-xDS where the versions of the wildcard resources are not updated, and may result in wasted passing of resources, and usage of stale resources.
Testing: Added a unit test.
Release Notes:
Fixes #Issue: #20699
=> delta-xds: fix wildcard resource versions

source/extensions/filters/network/thrift_proxy/router/router_impl.h
The is a followup from https://github.com/envoyproxy/envoy/pull/20577#discussion_r842221602
`return parent_->ClusterHeader()` hints we might have a header to honor, which is not true.
=> thrift: Explicitly express no cluster header for weighted clusters

contrib/sip_proxy/filters/network/source/conn_manager.cc, contrib/sip_proxy/filters/network/source/conn_manager.h, contrib/sip_proxy/filters/network/source/router/router_impl.cc, contrib/sip_proxy/filters/network/source/tra/BUILD, contrib/sip_proxy/filters/network/source/tra/tra.h, contrib/sip_proxy/filters/network/source/tra/tra_impl.cc, contrib/sip_proxy/filters/network/source/tra/tra_impl.h, contrib/sip_proxy/filters/network/test/mocks.cc, contrib/sip_proxy/filters/network/test/mocks.h, contrib/sip_proxy/filters/network/test/router_test.cc, contrib/sip_proxy/filters/network/test/tra_test.cc
When their are more than one TRA subscribe actions, stream_ maybe
overwrited which cause the last connection can't be resetted gracefully.
so introduce a list of stream_callbacks and request_callbacks.
Commit Message: contrib-sipproxy: Fix the coredump when teardown
Additional Description: When their are more than one TRA subscribe actions, stream_ maybe                                                                                                                               overwrited which cause the last connection can't be resetted gracefully.                                                                                                                        so introduce a list of stream_callbacks and request_callbacks to fix it.  
Risk …
=> contrib-sipproxy: Fix the issue when teardown

docs/root/configuration/http/http_filters/adaptive_concurrency_filter.rst, docs/root/configuration/http/http_filters/admission_control_filter.rst, source/extensions/extensions_metadata.yaml
No longer in development and should be prod ready.
Testing: N/A
=> adaptive concurrency / admission control: mark non-alpha

source/server/admin/BUILD, source/server/admin/stats_render.cc, source/server/admin/stats_render.h, test/common/http/header_map_impl_test.cc
Commit Message: Uses the new Json::sanitizer from #20637 to generate counters, gauges, and text-readouts in response to admin endpoint `/stats?format=json`, resulting in a 5.6x speedup for AllCountersJson, and making JSON output only around 10% slower than text output.
Before:
```
------------------------------------------------------------------
Benchmark                        Time             CPU   Iterations
------------------------------------------------------------------
BM_AllCountersText             454 ms          453 ms            2
BM_UsedCountersText           35.8 ms         35.8 ms           20
BM_FilteredCountersText       1806 ms         1805 ms            1
BM_AllCountersJson            2824 ms         2823 ms            1
BM_UsedCountersJson …
```
=> switch to using json sanitizer for admin counters, gauges, and text-readouts

envoy/router/router.h, source/common/http/async_client_impl.cc, source/common/http/async_client_impl.h, source/common/router/config_impl.h, source/common/router/delegating_route_impl.cc, source/common/router/delegating_route_impl.h, test/common/http/async_client_impl_test.cc, test/common/http/conn_manager_impl_test.cc, test/common/router/config_impl_test.cc, test/mocks/router/mocks.cc, test/mocks/router/mocks.h
Commit Message: Revert "router: Remove PathMatchType and PathMatchCriterion #20469"
This reverts commit [7014ce6fd31ef7a2f6a2083d99d4b85bbe55b6c6](https://github.com/envoyproxy/envoy/commit/7014ce6fd31ef7a2f6a2083d99d4b85bbe55b6c6).
The object is used by extensions to gather more information about route matching (see: #2531).
Added additional comment to `PathMatchCriterion` that explains this.
Testing: N/A.
=> Revert "router: Remove PathMatchType and PathMatchCriterion (#20649)"

.azure-pipelines/pipelines.yml, ci/docker_ci.sh, ci/mac_ci_steps.sh, examples/cache/service.py
- partial fix for macOS (VM)
- fix for windows VM
- fix cache verify example
- fix VRP verify example
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [backport/v1.18] ci: Fix broken tests

docs/root/configuration/observability/access_log/usage.rst, docs/root/version_history/current.rst, source/common/formatter/substitution_formatter.cc, source/common/formatter/substitution_formatter.h, test/common/access_log/access_log_impl_test.cc, test/common/formatter/substitution_formatter_test.cc
Similar to https://github.com/envoyproxy/envoy/issues/9352 but number format. Useful because `grpc-status` may appear in either the headers or in the trailers and there's no alternative to coalesce the value into a single access log field.
Appreciate feedback regarding C++ and testing. The change is simple enough, but I'm not particularly familiar with C++.
Docs Changes: Required
Release Notes: Required
=> access log: add GRPC_STATUS_NUMBER format operator

test/extensions/filters/network/local_ratelimit/local_ratelimit_corpus/clusterfuzz-testcase-minimized-local_ratelimit_fuzz_test-5036107325112320, test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test.cc
Commit Message: fuzz test: Validate fuzzed input to local rate limit
Input to the local_ratelimit_fuzz_test must not accept fill_intervals
less than 50ms. Added better checking of input.
Testing: n/a
=> fuzz test: Validate fuzz input to local rate limit

source/common/io/io_uring_impl.cc, source/common/io/io_uring_impl.h, test/common/io/io_uring_impl_test.cc, test/per_file_coverage.sh
Commit Message: io_uring: skip tests if unsupported
Testing: run unittests on machines where io_uring supported and not (MS WSL).
Platform Specific Features: no features added
Fixes #20763
=> io_uring: skip tests if unsupported

source/common/http/filter_manager.cc, test/common/http/conn_manager_impl_test_2.cc
The following sequence lead to trailers being continued twice:
1) Filter 1 stops iteration in headers
2) Filter 1 continues iteration on data with end stream true
3) Filter 2 continues iteration in headers
4) filter 2 continued iteration in data, but adds trailers
Previously trailers were continued twice, now they are continued
once.
Testing: New UT
=> http filter manager: handle trailers added during continuation

contrib/vcl/source/vcl_io_handle.cc
Commit Message: stop reading from vcl if previous read did not fill current slice
Testing: n/a
=> vcl: stop readv if slice not full after read

source/common/http/conn_pool_base.cc, source/common/http/conn_pool_base.h, source/common/http/mixed_conn_pool.cc, source/common/runtime/runtime_features.cc, test/common/http/mixed_conn_pool_test.cc, test/integration/alpn_integration_test.cc, test/integration/base_integration_test.cc
Risk Level: low (off by default)
Testing: unit + integration
Runtime guard: envoy.reloadable_features.allow_concurrency_for_alpn_pool
Part of https://github.com/envoyproxy/envoy/issues/20696 part of https://github.com/envoyproxy/envoy/issues/15947
=> http: the first step towards alpn having intelligent initial streams.

test/common/http/BUILD, test/common/http/codec_impl_fuzz_test.cc
Signed-off-by: Dianna Hu <diannahu@google.com>
Commit Message: This PR updates codec_impl_fuzz_test.cc's HttpVersion to include oghttp2 and wrapped-nghttp2, then enables the appropriate runtime config in testing.
Additional Description: Other examples of the three HTTP/2 codec variations and associated runtime config enablement can be found at https://github.com/envoyproxy/envoy/search?q=setupHttp2Overrides. However, I chose not to use a dedicated method here because setup occurs at only one place. This PR is an identical respin of envoyproxy#20811, except that the unrelated commits are removed.
Testing: bazel test //test/common/http:codec_impl_fuzz_test --config=libc++
[Optional …
=> test: Add oghttp2 and wrapped-nghttp2 coverage to codec_impl_fuzz_test.cc

source/extensions/filters/http/gcp_authn/gcp_authn_filter.cc, source/extensions/filters/http/gcp_authn/gcp_authn_filter.h, test/extensions/filters/http/gcp_authn/gcp_authn_filter_integration_test.cc
- Implement the response path
On the response path, once the token is returned from authentication server,  we need to include it  in an `Authorization: Bearer ID_TOKEN` header and add the header into the request which is sent from calling service to the receiving service.
- Add the test coverage in integration test to verify the request header modification mentioned above 
Signed-off-by: Tianyu Xia [tyxia@google.com](mailto:tyxia@google.com)
=> GCP Authentication Filter: Implement response path

bazel/repositories.bzl, bazel/rules_rust.patch
This enables building rust that targets android devices until the
upstream PR is released. It shouldn't affect any other configuration
since it's scoped to the triple.
=> bazel: add temporary rules_rust patch

bazel/dependency_imports.bzl
This is preliminary work for getting rust working in envoy mobile. This
should be minimal overhead in the case you're not actually building rust
for mobile. If it becomes an issue we can inject this from the consumers
of `envoy_dependency_imports`.
=> bazel: add mobile rust toolchains

test/common/event/dispatcher_impl_test.cc
Replaced hard coded "127.0.0.1" by getLoopbackAddressUrlString 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> test: allow dispatcher test cases running on ipv6 only env

bazel/BUILD, bazel/envoy_internal.bzl, ci/do_ci.sh
This config setting enables Universal Header Validator and disables HTTP header compliance checks in codecs.
This setting is temporary to transition header validation into UHV without impacting production builds of Envoy.
This setting is enabled for the bazel.compile_time_options CI target.
Risk Level: Low, build options for compile_time_options CI target
Part of #20261
=> build: Add bazel option for enabling Universal Header Validator

.bazelrc
This fixes an issue where the PATH wasn't actually set to what we tried
to force as the default on macOS. I'm not sure if this is a bazel bug or
not, but either way it's surprising behavior.
https://github.com/bazelbuild/bazel/issues/15270
=> bazel: move shared action_env above enable_platform_specific_config

api/envoy/config/accesslog/v3/accesslog.proto
Commit Message: api: Add validate to required member.
ComparisonFilter's value now marked as required in validate to ensure valid
input to fuzz tests.
Testing: n/a
API Considerations: Add a validate rule to the value a binary operation compares against. Not ensuring that the value exists without giving a reasonable default is questionable. Therefore this patch adds a validate rule to at least flag the missing value.
=> api: Add validate to required member.

.bazelrc, bazel/README.md, bazel/dependency_imports.bzl, bazel/setup_clang.sh
This makes it so you don't have to have cmake, make, or ninja installed,
or worry about version issues between them.
Since 0.1.0 rules_foreign_cc has supported vendoring these tools https://github.com/bazelbuild/rules_foreign_cc/releases/tag/0.1.0 and it builds them with cross platform scripts for bootstrapping.
=> bazel: enable rules_foreign_cc vendored tools

.bazelrc, bazel/README.md, bazel/dependency_imports.bzl, bazel/setup_clang.sh
Reverts envoyproxy/envoy#20517
one of the tools depends on python2 which macOS no longer ships.
=> Revert "bazel: enable rules_foreign_cc vendored tools"

.bazelrc
On M1 macs this fails with a linker error that I'm attempting to fix
here https://chromium-review.googlesource.com/c/v8/v8/+/3589296
We could also take that as a patch but it would probably be nice to get
input upstream on the fix first.
=> bazel: disable wasm on macOS for now

bazel/README.md, external
Commit Message: docs: add WASM runtime build instructions
Additional Description: This adds the specific language for enabling an optional WASM runtime for envoy to the bazel build instructions
Testing: n/a
Docs Changes: this is only a change to docs
=> docs: add WASM runtime build instructions

api/envoy/extensions/filters/network/thrift_proxy/v3/route.proto
Commit Message: thrift proxy: minor api docs update for new trds feature
Additional Description: Asynchronous route discovery was supported but the comment of `name` field in the thrift `RouteConfiguration` havn't updated.
I dicovered this minor issue occationally when I was trying to implement dubbo rds. So I created this minor PR.
Risk Level: None. Docs only update.
Testing: N/A.
=> thrift proxy: minor api docs update for new trds feature

api/envoy/extensions/rbac/matchers/upstream_ip_port/v3/upstream_ip_port_matcher.proto
Commit Message: docs: fix wrong link in RBAC upstream IP and port matcher
Additional Description: the link of proxy_filter.cc contains an extra space in [RBAC upstream IP and port matcher plugin](https://www.envoyproxy.io/docs/envoy/v1.22.0/api-v3/extensions/rbac/matchers/upstream_ip_port/v3/upstream_ip_port_matcher.proto.html). The address has been interpreted as .../v1.22.0/%20source/extensions/...
Testing: N/A
Docs Changes: API
=> docs: fix wrong link in RBAC upstream IP and port matcher

envoy/stats/scope.h, tools/code_format/check_format.py, tools/code_format/check_format_test_helper.py, tools/testdata/check_format/code_conventions.cc, tools/testdata/check_format/code_conventions.cc.gold
Commit Message: Prevent further in-repo uses of Stats::ScopePtr with a lint error. Attempt to discourage out-of-repo uses of Stats::ScopePtr with a `deprecated` flag, though that doesn't seem to cause any warning in *our* build  or clang-tidy when I change a reference in the code. See #19468 for the change to suppress deprecation warnings. 
Testing: //test/common/stats/...
=> stats: add lint error for using Stats::ScopePtr, and mark that nickname as deprecated

source/server/server.cc, source/server/server.h
Accessing destroyed class member causing MemorySanitizer: use-of-uninitialized-value issue
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> MemorySanitizer: use-of-uninitialized-value issue due to accessing destroyed class member

envoy/stats/scope.h
Commit Message: Adds a reference to the issue for removing Stats::ScopePtr once all external refs are cleaned
Testing: none
=> stats: update comment and add reference to issue for removing Stats::ScopePtr

bazel/BUILD, bazel/platform_mappings
This allows us to build envoy mobile for the M1 simulator architecture,
and get the correct apple conditionals
=> bazel: add ios_sim_arm64 CPU

source/common/http/http2/codec_impl.cc, test/common/http/http2/codec_impl_test.cc
Commit Message: HTTP2: Only schedule deferred processing if data is pending.
Additional Description: Still need to implement chunking
Risk Level:  low (off by default due to release guard)
Docs Changes: NA (until more fleshed out)
Release Notes: NA (until feature fully implemented)
Related Issue #19127
=> HTTP2: Only schedule deferred processing if data is pending.

bazel/foreign_cc/BUILD
When compile envoy on RedHat based OS like Fedra, zstd will compile error with complaining: external/envoy/bazel/foreign_cc/BUILD:551:12: output 'external/envoy/bazel/foreign_cc/zstd/lib/libzstd.a' was not created
This is because on RedHat based OS, CMAKE_INSTALL_LIBDIR default is set to lib64, so it will generate object in external/envoy/bazel/foreign_cc/zstd/lib64/libzstd.a
Add the cmake compile flag `CMAKE_INSTALL_LIBDIR: lib` to fix this.
Commit Message: fix zstd compile error
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
=> fix zstd compile error

test/extensions/common/async_files/BUILD, test/extensions/common/async_files/mocks.cc, test/extensions/common/async_files/mocks.h
Commit Message: Add mocks for AsyncFiles to facilitate testing clients
Additional Description: Mocks for AsyncFileManager and its surrounding classes make unit testing dependent classes much simpler, allowing the test full control over when callbacks from another thread are triggered.
Risk Level: None, test-only
Testing: None, test-only changes
=> Add mocks for AsyncFiles to facilitate testing clients

test/extensions/filters/network/common/fuzz/uber_per_readfilter.cc
Commit Message: fuzz test: Prevent use of negative durations.
In network_readfilter_fuzz_test ensure that timeout and intervall of
http2_protocol_options.connection_keepalive are
both positive.
Testing: n/a
=> fuzz test: Prevent use of negative durations.

source/extensions/clusters/dynamic_forward_proxy/cluster.h, source/extensions/common/dynamic_forward_proxy/dns_cache.h, source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc, source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h, test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc, test/extensions/common/dynamic_forward_proxy/mocks.h
This can be used by Envoy Mobile after cache flush to
drain cluster connections if desired.
Testing: Modified existing tests
=> dns cache: add callback for all resolutions

docs/conf.py, docs/root/version_history/v1.19.3.rst, docs/root/version_history/v1.20.0.rst, docs/root/version_history/v1.20.1.rst, docs/root/version_history/v1.20.2.rst, docs/root/version_history/v1.21.0.rst, docs/root/version_history/v1.21.1.rst, docs/root/version_history/v1.22.0.rst
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fix #20963
=> docs: Cleanup version histories

bazel/external/quiche.BUILD, source/common/quic/platform/BUILD, source/common/quic/platform/quiche_lower_case_string_impl.h
Add a build target for platform/api/quiche_header_policy.h, and another
one for the default implementation bundled in QUICHE.
Add a build target for platform/api/quiche_lower_case_string.h, and add
an implementation that defines it as an alias to Http::LowerCaseString.
Commit Message: Add two QUICHE platform APIs.
Additional Description: Add some unused build targets.
Testing: These APIs are part of the QUICHE third party library and do not have tests.
=> Add two QUICHE platform APIs.

test/integration/multiplexed_upstream_integration_test.cc
Commit Message: the test closes the upstream connection between two requests to test upstream caches 0-RTT keys. But because the upstream connection is closed by the fake upstream, there is a race in Envoy between closing the corresponding upstream connection and picking an existing upstream connection for the 2nd request. If the latter wins the race, the 2nd request will reuse the old upstream connection and then fail. This change fixes the race by checking cluster stats `upstream_cx_destroy` in Envoy before sending the 2nd request to ensure the Envoy also has closed the upstream connection.
Testing: the test is no longer flaky
=> test: deflake MultiplexedUpstreamIntegrationTest.UpstreamCachesZeroRttKeys

contrib/cryptomb/private_key_providers/source/cryptomb_private_key_provider.cc, contrib/cryptomb/private_key_providers/test/ops_test.cc, docs/root/version_history/current.rst
Backport: cryptomb: remove PKCS1_5 padding support (https://github.com/envoyproxy/envoy/pull/20408)
Additional Description: Drop RSA signing PKCS1 v1.5 padding support (which wasn't functional).
Platform Specific Features: CryptoMB extension works on 3rd Gen Intel Xeon Scalable processors.
=> [1.21] Backport #20408 cryptomb: remove PKCS1_5 padding support.

envoy/http/http_server_properties_cache.h, source/common/http/conn_pool_grid.cc, source/common/http/http_server_properties_cache_impl.cc, source/common/http/http_server_properties_cache_impl.h, test/common/http/conn_pool_grid_test.cc, test/common/http/http_server_properties_cache_impl_test.cc, test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc, test/mocks/http/http_server_properties_cache.h
Testing: new unit testing
Part of https://github.com/envoyproxy/envoy/issues/20696
=> server properties: tracking concurrent streams (not used yet)

test/integration/fake_upstream.cc, test/integration/http_integration.cc, test/integration/http_integration.h, test/integration/http_protocol_integration.h, test/integration/multiplexed_integration_test.cc
Commit Message: some tests with giant request/response payload in multiplex_integration_tests.cc have been flaky at FakeHttpConnection::waitForNewStream() under TSAN because of the contention between the main test thread and the fake upstream thread. This contention exists in all tests that uses non-autonomous fake upstream, but more severe in tests with large payload because their clients have more IO events to handle while holding the mutex.
This change modifies two things to mitigate the synchronization cost:
1. Change large payload tests to use autonomous fake upstream, so that the synchronization between the main test thread and the fake upstream thread can be eliminated.
2. Adjust the timeout of waitForWithDispatcherRun() to respect …
=> test: deflake TSAN test failure with giant payload in multiplex_integration_test

test/common/upstream/least_request_load_balancer_fuzz_test.cc
Commit Message: lb fuzz test: Limit choice_count.
Limit the choice_count to a reasonable number. Allowing any number has
no added value.
Testing: n/a
=> lb fuzz test: Limit choice_count.

test/integration/listener_lds_integration_test.cc
Commit Message: listener: add integration test for in-place update listener filters order
Test the case of only the listener filters order was updated, then the envoy will do a in-place update for this case.
Part of Fixes #20100
=> listener: add integration test for in-place update listener filters order

docs/root/configuration/observability/access_log/usage.rst, docs/root/version_history/current.rst, envoy/stream_info/stream_info.h, source/common/formatter/substitution_formatter.cc, source/common/formatter/substitution_formatter.h, source/common/router/upstream_request.cc, source/common/stream_info/stream_info_impl.h, test/common/formatter/substitution_formatter_test.cc
Commit Message: access_log: Added new command operators to retrieve upstream connection information
Additional Description: Need to add information upstream (protocol and TLS info) information in access log (using it in the context of "dynamic forward proxy" but is also usable generally).  So added following command operators
```
%UPSTREAM_PROTOCOL%           get upstream protocol
%UPSTREAM_PEER_SUBJECT%       upstream TLS subject
%UPSTREAM_PEER_ISSUER%        upstream TLS certificate issuer
%UPSTREAM_TLS_SESSION_ID%     upstream TLS session ID
%UPSTREAM_TLS_CIPHER%         upstream TLS cipher
%UPSTREAM_TLS_VERSION%        upstream TLS version
%UPSTREAM_PEER_CERT_V_START%  upstream TLS cert validation start date
%UPSTREAM_PEER_CERT_V_END%    upstream TLS cert validation end/expiry date …
```
=> access_log: Added new command operators to retrieve upstream information

api/STYLE.md
Commit Message: Update STYLE.md with instructions that actually work
Additional Description: While trying to send a pull request for an extension I was baffled multiple times by poor error messages and surprising behaviors. The alterations here each derive from a confusing thing that mostly also didn't get any clear "someone understood it better" signs from the dev slack channel.
First surprise, if you use `option (udpa.annotations.file_status).work_in_progress = true;` like the doc suggested, proto_format.sh would remove it. Suggestion from the slack channel was to use `xds.annotations.v3.file_status` instead, which this updates STYLE.md to reflect. ([related slack thread](https://envoyproxy.slack.com/archives/C78HA81DH/p1649780849908359 …
=> Update STYLE.md with instructions that actually work

test/common/buffer/buffer_corpus/clusterfuzz-testcase-minimized-buffer_fuzz_test-5605149941301248, test/common/buffer/buffer_fuzz.cc
Commit Message: fuzz test: Fix fuzzer tracking of allocs.
Fix tracking the reserved size for the (fuzzer's shadow) StringBuffer
when reserveCommitting a slice larger than 16kB.
Testing: n/a
=> fuzz test: Fix fuzzer tracking of allocs.

test/server/server_fuzz_test.cc
Commit Message: fuzz test: Force server_fuzz_test to end event loop.
When a fuzz input does not produce any events in the main event loop,
server_fuzz_test will run forever. Enforce an event (closing event loop)
after 5 seconds.
Testing: n/a
=> fuzz test: Force server_fuzz_test to end event loop.

test/extensions/filters/http/compressor/BUILD, test/extensions/filters/http/compressor/compressor_filter_speed_test.cc
Commit Message: support zstd benchmark
```
2022-04-24T13:45:31+08:00
Running ./bazel-bin/test/extensions/filters/http/compressor/compressor_filter_speed_test
Run on (112 X 3500.57 MHz CPU s)
CPU Caches:
L1 Data 48 KiB (x56)
L1 Instruction 32 KiB (x56)
L2 Unified 1280 KiB (x56)
L3 Unified 43008 KiB (x2)
Load Average: 10.64, 5.78, 5.70
***WARNING*** Library was built as DEBUG. Timings may be affected.
-------------------------------------------------------------------------------------
Benchmark                                           Time             CPU   Iterations
-------------------------------------------------------------------------------------
...
compressFullWithZstd/0/manual_time               2.62 ms         3.18 ms          272 …
```
=> compressor filter: support zstd benchmark

test/common/json/json_fuzz_test.cc
Commit Message: fuzz test: Limit the size of json input.
There is no added benefit in allowing the fuzzer to generate arbitrary
big json input for the configuration.
Testing: n/a
=> fuzz test: Limit the size of json input.

source/server/filter_chain_manager_impl.cc, test/test_common/status_utility_test.cc, test/tools/router_check/coverage.cc
Small clean-ups for clang-tidy complaints and prep for upgrade of absl and protobuf
=> test: Fix clang-tidy and pre for upgrade of absl and protobuf

contrib/kafka/filters/network/test/kafka_response_parser_test.cc
header_len was never read here. The newer LLVM versions warn on this
now.
=> tests: remove unused variable

envoy/network/transport_socket.h, source/common/http/BUILD, source/common/http/conn_pool_grid.cc, source/common/http/mixed_conn_pool.cc, source/common/http/mixed_conn_pool.h, source/common/network/raw_buffer_socket.h, source/common/quic/quic_transport_socket_factory.h, source/common/upstream/cluster_manager_impl.cc, source/extensions/transport_sockets/alts/tsi_socket.h, source/extensions/transport_sockets/common/passthrough.h, source/extensions/transport_sockets/starttls/starttls_socket.h, source/extensions/transport_sockets/tls/ssl_socket.h, test/common/http/BUILD, test/common/http/mixed_conn_pool_test.cc, test/common/upstream/transport_socket_matcher_test.cc, test/integration/alpn_integration_test.cc, test/integration/fake_upstream.h, test/mocks/network/transport_socket.h
Commit Message: having the ALPN pool cache initial muxed stream limits
Risk Level: low (off by default)
Testing: new unit, integration tests
Part of https://github.com/envoyproxy/envoy/issues/20696
=> alpn: latching h2 streams (off by default)

.bazelrc
To be reverted if it makes CI debug harder, but in the interim makes CI logs and build logs MUCH easier to read.
=> build: silencing info logspam.

test/integration/protocol_integration_test.cc
Commit Message: TrailersWireBytesCountUpstream test is flaky because of header compression. The fix changes the workflow of the test a bit to mitigate the racing between sending trailers and sync'ing compression instruction tables.
Risk Level: n/a, test only
=> http trailers: fix flaky byte accounting trailers test caused by nondeterministic header compression

envoy/upstream/cluster_manager.h, source/common/upstream/cluster_manager_impl.cc, source/common/upstream/cluster_manager_impl.h, test/common/upstream/cluster_manager_impl_test.cc, test/integration/http_conn_pool_integration_test.cc, test/mocks/upstream/cluster_manager.h
This will allow EM to selectively drain connections based on hostname(),
for example.
Testing: New integration test
=> cluster manager: add optional host predicate to drainConnections()

api/envoy/config/core/v3/socket_option.proto
Commit Message: docs: add an example with TCP Keep-alive for socket_option
Additional Description: Add docs for https://github.com/envoyproxy/envoy/issues/21042
Testing: N/A
Docs Changes: Yes, for socket option
=> docs: add an example with TCP Keep-alive for socket_option

.bazelrc, ci/build_setup.sh
Locally seeing bazel info lines can be helpful for things like
`--announce_rc`. This should disable for CI only. Except
for jobs that set `NO_BUILD_SETUP` which isn't many.
=> ci: move info filter to ci config

source/extensions/filters/http/cache/config.cc
Commit Message: Make cache filter not re-fetch the cache for each connection
Additional Description: While in the case of SimpleHttpCache this re-fetching operation is inexpensive, for another cache implementation it could potentially be a significant amount of config parsing, which is best avoided on a per-connection basis. (And there is no downside to avoiding it here.)
Risk Level: Very low, filter is tagged WIP and getCache should be idempotent.
Testing: Existing tests should already cover as the expected behavior is the same. Tests still pass.
=> Make cache filter not re-fetch the cache for each connection

BUILD
This mirrors the envoy alias at the top level, since this is the
recommendation for release builds this allows people to easily build
this version a well.
This came up in https://github.com/envoyproxy/envoy/issues/21060
=> bazel: add root envoy.stripped alias

test/common/router/route_fuzz_test.cc
Commit Message: fuzz test: Prevent fuzzing of unimplemented router configs.
- Add router config option non_forwarding_action marked not-implemented to
the filter loop to prevent fuzzing them.
- In VirtualHost config the retry_policy_typed_config is flagged as not
implemented. Prevent the fuzzer from wasting time and space fuzzing it.
Testing: n/a
=> fuzz test: Prevent fuzzing of unimplemented router configs.

api/envoy/extensions/filters/http/stateful_session/v3/stateful_session.proto, source/extensions/filters/http/stateful_session/config.cc, source/extensions/filters/http/stateful_session/stateful_session.cc, source/extensions/filters/http/stateful_session/stateful_session.h, test/extensions/filters/http/stateful_session/config_test.cc, test/extensions/filters/http/stateful_session/stateful_session_test.cc
Commit Message: stateful session: allow empty filter config
Now, empty filter config is not allowed for the stateful session filter. However, some users may like to enable stateful session in only specific routes. For example, #20658.
This PR will loosen restrictions on proto API of stateful session.
Testing: Unit. Added.
=> stateful session: allow empty filter config

source/common/config/grpc_mux_impl.cc, source/common/config/watch_map.cc
Commit Message: Updating grpc mux code to use a base type to avoid cast
As noted in #21060, building with gcc in "opt" mode results in a compilation error:
```
ERROR: /workspaces/envoy/source/common/config/BUILD:414:17: Compiling source/common/config/watch_map.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 154 arguments skipped)
Use --sandbox_debug to see verbose messages from the sandbox
source/common/config/watch_map.cc: In member function 'virtual void Envoy::Config::WatchMap::onConfigUpdate(const …
```
=> mux: using base type to avoid cast

source/exe/process_wide.cc
2 racing callers can leave 1 caller thinking things are
initialized while the other caller is still initializing.
This change uses a mutex to fix that race.
=> process wide: fix concurrent callers

envoy/http/filter.h, envoy/network/filter.h, source/common/network/matching/inputs.cc, source/common/network/matching/inputs.h
This changes how we do generics for the different inputs slightly differently: instead of having the initial template
specify the behavior for the most common type and then override it for UdpMatchingData, instead we make all
inputs type conform to the same shape and use only a single template for these types.
Risk Level: Low, refactor
=> matching: avoid template specialization in favor of uniform types

.github/workflows/check-deps.yml, .github/workflows/depsreview.yml, .github/workflows/pr_notifier.yml
also consistently using the same envoyproxy/envoy checks across the workflow files.
=> tools: limiting dependency reviews to envoyproxy/envoy

source/common/common/regex.cc, source/common/runtime/runtime_features.cc, source/common/runtime/runtime_features.h, source/common/runtime/runtime_impl.cc, test/integration/stats_integration_test.cc
Fixes an issue where a runtime value was applied before it was set.
Re-introduces an issue where that runtime guard may never actually be applied.
Part of https://github.com/envoyproxy/envoy/issues/21056
=> regex: restoring regex behavior prior to runtime load

api/envoy/config/core/v3/substitution_format_string.proto, test/extensions/filters/network/common/fuzz/network_readfilter_corpus/oss-fuzz-26856-network_readfilter_fuzz_test-5364876991791104
Commit Message: fuzz test: Ensure content type is valid.
In http_connection_manager check that the content-type in a
local_reply_config contains only allowed characters.
Signed-off-by: Andre Vehreschild [vehre@x41-dsec.de](mailto:vehre@x41-dsec.de)
Testing: n/a
API Considerations: Added validator to existing option enabling automatic checking for legal content-type.
=> fuzz test: Ensure content type is valid.

test/integration/README.md
Commit Message: Add mention of `stress` to deflaking integration tests doc
Additional Description: stress tool helps repro difficult flakes
Risk Level: None, doc only
Testing: n/a
Docs Changes: Yes it is
=> Add mention of `stress` to deflaking integration tests doc

source/common/tracing/common_values.h, source/common/tracing/http_tracer_impl.cc, source/extensions/tracers/skywalking/tracer.cc, test/common/http/async_client_impl_test.cc, test/common/router/router_2_test.cc, test/common/tracing/http_tracer_impl_test.cc, test/extensions/tracers/skywalking/tracer_test.cc
Commit Message: skywalking: set peer with tag value of peer.address
Peer is a important attribution of skywalking span. But in the previous skywalking tracer's implementation, it never be set correctly. This PR will set peer of skywalking span with that tag value of `peer.address`.
This PR consist of two part:
1. Set `peer.address` tag when we calling the `finalizeUpstreamSpan`.
2. Set peer of skywalking span base on the value of `peer.address` tag.
Testing: Added
=> skywalking: set peer with tag value of peer.address

api/envoy/config/route/v3/route_components.proto, changelogs/1.23.0.yaml, source/common/router/BUILD, source/common/router/router_ratelimit.cc, source/common/router/router_ratelimit.h, test/common/router/router_ratelimit_test.cc
Signed-off-by: hejianpeng <hejianpeng2@huawei.com>
make `RemoteAddressAction` support prefix len`
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/20433
=> remote address action support prefix len

source/common/common/regex.cc, source/common/runtime/runtime_features.cc, source/common/runtime/runtime_features.h, source/common/runtime/runtime_impl.cc, test/integration/stats_integration_test.cc
Backport #21069 to 1.22
Testing: New integration test
=> [Backport 1.22] regex: restoring regex behavior prior to runtime load (#21069)

test/extensions/filters/http/common/fuzz/filter_corpus/clusterfuzz-testcase-minimized-filter_fuzz_test-4845350742523904, test/extensions/filters/http/common/fuzz/uber_filter.h, test/extensions/filters/http/common/fuzz/uber_per_filter.cc
Commit Message: fuzz test: Allow aws signing filter to run.
- Provide decoding_buffer_ to aws signing filter, allowing it to run
further.
Testing: n/a
=> fuzz test: Allow aws signing filter to run. 

test/extensions/filters/udp/dns_filter/dns_filter_fuzz_test.cc
* In this PR, [#20744](https://github.com/envoyproxy/envoy/pull/20744) the answer message is disabled. 
* Remove separate fuzzing of the parseDnsQueryRecord as it is tested as part of the parseDnsObject method.
* Remove fuzz_function randomization and only test the parseDnsObject method as it is used in the filter implementation.
Commit Message: simplify dns filter fuzz tests
Testing: fuzz test
Docs Changes:
Release Notes:
=> dns_filter: simpilfy dns filter fuzz tests

CODEOWNERS
Update CODEOWNERS with additional Intel folks for Intel supported contrib
extensions. Also drop non-existing modules.
Signed-off-by: Dmitry Rozhkov <dmitry.rozhkov@intel.com>
=> codeowners: fix up ownership and drop non-existing modules

envoy/tcp/upstream.h, source/common/formatter/substitution_formatter.cc, source/common/router/upstream_request.cc, source/common/tcp_proxy/tcp_proxy.cc, source/common/tcp_proxy/tcp_proxy.h, source/common/tcp_proxy/upstream.cc, source/common/tcp_proxy/upstream.h, test/common/formatter/substitution_formatter_test.cc, test/common/tcp_proxy/tcp_proxy_test.cc, test/common/tcp_proxy/tcp_proxy_test_base.h, test/integration/tcp_proxy_integration_test.cc
Description:
Currently the access log tag `UPSTREAM_TRANSPORT_FAILURE_REASON` does not work as intended. The
failure string is not propagated all the way to the logs. This change fixes the issue.
Testing: Unit tests, manual tests
=> access_logs: propagate UPSTREAM_TRANSPORT_FAILURE_REASON

envoy/server/admin.h, source/server/admin/stats_request.cc, source/server/admin/stats_request.h, test/server/admin/admin_test.cc, test/server/admin/stats_request_test.cc
Commit Message: The Admin infrastructure's nextChunk() contract does not require its caller to drain the buffer on each call. This fixes the logic in StatsRequest::nextChunk to append up to N *additional* bytes on each call, and adds tests in both stats_request_test.cc and in admin_test.cc that repro'd the problem and verifies that it is fixed.
This problem did *not* affect the admin HTTP port because when admin_filter.cc calls nextChunk(), since it drains the response buffer and sends it to the network.
Testing: //test/server/admin/...
=> admin: fix problem with large /stats requests via adminRequest API

source/extensions/clusters/dynamic_forward_proxy/cluster.cc, test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc
Commit Message: dynamic_forward_proxy: add outlier detection support
Additional Description: Currently dfp doesn't honor host ejections, continuous to use ejected
hosts. This adds support for honoring ejections/de-ejections.
Testing: Unit and manual testing
=> dynamic_forward_proxy: add outlier detection support

test/common/http/codec_impl_corpus/oss-fuzz-45481-codec_impl_fuzz_test-4765897875652608, test/common/http/codec_impl_fuzz_test.cc
Commit Message: fuzz test: Prevent endless loop by checking for progress.
In codec_impl_fuzz_test a client_server_buffer_drain could get caught
into a loop where readDisabled(true) was set and the buffer wouldn't get
drained. Break that loop by checking that the buffer length changes.
Testing: n/a
=> fuzz test: Prevent endless loop by checking for progress.

changelogs/current.yaml, source/extensions/tracers/skywalking/skywalking_tracer_impl.cc, source/extensions/tracers/skywalking/tracer.cc, source/extensions/tracers/skywalking/tracer.h, test/extensions/tracers/skywalking/skywalking_tracer_impl_test.cc, test/extensions/tracers/skywalking/tracer_test.cc
Commit Message: skywalking: use request path as operation name
To pick up #20452 .
=> skywalking: use request path as operation name

SECURITY.md
docs: Add a link to the Fix Lead Checklist from SECURITY.md
Testing: N/A
Docs Changes: SECURITY.md
=> docs: Add a link to the Fix Lead Checklist from SECURITY.md

source/extensions/common/async_files/async_file_manager_thread_pool.cc, source/extensions/common/async_files/async_file_manager_thread_pool.h
Commit Message: Disable O_TMPFILE branch when O_TMPFILE is not defined
Additional Description: Behavior should be near-indistinguishable. Will not compile on Mac when O_TMPFILE is used. Addresses issue #21217.
Risk Level: Very low, filter is WIP.
Testing: Existing tests essentially cover it.
=> Disable O_TMPFILE branch when O_TMPFILE is not defined

changelogs/current.yaml, source/common/runtime/runtime_features.cc, source/server/config_validation/server.cc, source/server/server.cc, test/integration/multi_envoy_test.cc, test/integration/protocol_integration_test.cc, test/test_common/test_runtime.h
The runtime guard for using runtime singleton was inverted, as debugged in envoy-mobile with multi-engine tests not working.
Risk Level: high (removing runtime singleton)
Testing: yes
Release Notes: updated
=> runtime: fix borked runtime guard, removing runtime singleton

source/common/http/http1/codec_impl.cc, source/common/http/http1/legacy_parser_impl.cc, source/common/http/http1/legacy_parser_impl.h, source/common/http/http1/parser.h
The motivation is to not expose integer error codes internal to
http-parser.  This will make it easier to add another Parser
implementation based on a different library.
LegacyHttpParserImpl::execute() returns HTTP_PARSER_ERRNO.  This serves
two purposes at the sole call site in ConnectionImpl::dispatchSlice():
first, it is converted to a ParserStatus and compared to Success and
Pause.  This PR calls getStatus() directly instead.  Then the errno is
fed back to LegacyHttpParserImpl::errnoName(), which converts it to a
string.  This PR removes the errnoName() argument and makes this method
call HTTP_PARSER_ERRNO instead (via Impl::getErrno()).  This allows the
error code to be removed from the return struct of Parser::execute()
altogether.
Also, errnoName() is renamed to the more generic …
=> Simplify Parser::execute() and Parser::errnoName().

source/common/config/xds_mux/sotw_subscription_state.cc, test/common/config/sotw_subscription_state_test.cc
Commit Message: unified_mux: Keeping version_info in SotW reconnect
The SotW unified mux currently resets the version_info when a reconnect event occurs.
This PR changes the behavior so Envoy keeps the last valid version_info it has, and sends that upon reconnect.
Risk Level: Low - unified_mux is currently runtime guarded
=> unified_mux: Keeping version_info in SotW reconnect

api/envoy/extensions/transport_sockets/tls/v3/common.proto
Related PR: https://github.com/envoyproxy/envoy/pull/20643
Signed-off-by: derekguo001 <dong.guo@intel.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> doc: Remove SHA-1 cipher suites from the defaults on the server-side

test/common/http/codec_impl_corpus/oss-fuzz-46020-codec_impl_fuzz_test-6259213749321728, test/common/http/codec_impl_fuzz_test.cc
Commit Message: fuzz test: Check status before encoding headers.
Headers encoding throws on illegal status value, which is not desired.
Testing: n/a
=> fuzz test: Check status before encoding headers.

test/extensions/filters/network/common/fuzz/network_readfilter_corpus/clusterfuzz-testcase-minimized-network_readfilter_fuzz_test-4766957658832896, test/extensions/filters/network/common/fuzz/uber_readfilter.cc
Commit Message: fuzz test: Continue processing only on open conn. 
Continue processing of corpus file only while the connection is still
open. Reset the fuzzer and terminate the loop else.
Testing: n/a
=> fuzz test: Continue processing only on open conn. 

tools/vscode/refresh_compdb.sh
Running tools/vscode/refresh_compdb.py to generate the code completion symbols for VSCode produces an error because the .bazelversion in Envoy may not be available in certain environments.  The recommendation is to use `bazelisk`, but the compilation database script defaults to using `bazel`.  This change enables the VSCode compilation database generation script to use `bazelisk` if it is available on the system; if not, it will use `bazel`.
Testing: local
=> tools: Enable the VSCode completion db to use bazelisk if available

api/envoy/config/listener/v3/listener.proto, test/tools/schema_validator/test/config/lds_pgv_fail.yaml, test/tools/schema_validator/test/schema_validator_test.cc
Signed-off-by: Mark D. Roth <roth@google.com>
Commit Message: xds: Listener.address field is not required when api_listener is populated
Additional Description: This removes the overly restrictive PGV annotation that the address field is required, since there are cases where it does not need to be populated.
Testing: N/A
The right long-term solution is to use a oneof for the different types of listeners, as described in #15372.  But in the interim, it should not be necessary to populate the address field for non-socket listeners.
CC @costinm
=> xds: Listener.address field is not required when api_listener is populated

contrib/cryptomb/private_key_providers/source/cryptomb_private_key_provider.cc, contrib/cryptomb/private_key_providers/test/fake_factory.cc, contrib/cryptomb/private_key_providers/test/ops_test.cc
cryptomb: add support for PKCS #1 1.5 RSA padding.
Add support for PKCS #1 1.5 RSA padding to cryptomb according to RFC 8017. Also add some tests for both PKCS #1 1.5 and RSA-PSS padding schemes.
Testing: Unit tests, also tests in https://github.com/envoyproxy/envoy/issues/21198
Platform Specific Features: Requires Intel 3rd generation Xeon Scalable server processor for the AVX-512 IFMA instruction set.
Fixes #21198
=> cryptomb: add support for PKCS #1 1.5 RSA padding.

source/extensions/transport_sockets/tls/ssl_socket.cc
When we migrate the current traffic from others to envoy, we always found that TLS errors because of the TLS version/cipher mismatch. But current log did not tell us the client IP. This PR can help find the client IPs which have issues so that we can change the TLS configuration for the clients. 
Testing:
Release Notes:
=> Add remote address into debug log for TLS error

source/common/http/http1/codec_impl.cc, source/common/http/http1/codec_impl.h, source/common/http/http1/legacy_parser_impl.cc, source/common/http/http1/legacy_parser_impl.h, source/common/http/http1/parser.h
The motivation is that the int errno is implementation-specific (in this
case defined by http-parser).  Removing this method from the abstract
Parser interface and changing
ParserCallbacks::setAndCheckCallbackStatus* methods to return
ParserStatus instead of this implementation-specific int will make it
simpler to add another Parser implementation, one not based on
http-parser.
Instead of applying statusToInt() within setAndCheckCallbackStatus() and
setAndCheckCallbackStatusOr() before returning in ConnectionImpl, return
ParserStatus, and apply statusToInt() within LegacyHttpParserImpl.  This
allows statusToInt() to be moved to legacy_parser_impl.cc anonymous
namespace, right next to its counterpart intToStatus().
Commit …
=> Remove Parser::statusToInt().

docs/root/configuration/http/http_filters/ext_proc_filter.rst
Signed-off-by: Tony Tang <tsukiy0@users.noreply.github.com>
Commit Message: update extproc stats
Additional Description: added missing `message_timeouts` and `rejected_header_mutations` stats to ext_proc docs
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: update extproc stats

test/proto/helloworld.proto
Commit Message: Removing license comment in test proto
The original test file `test/proto/helloworld.proto`, which probably came from [gRPC](https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto), is using BSD license, whereas the rest of the project is using Apache 2.0.
I've removed the LICENSE comment from the file. This matches both the Envoy license, and the gRPC updated license.
Testing: N/A
=> test: Removing license comment in test proto

source/common/http/matching/inputs.h, test/common/http/matching/inputs_test.cc
Commit Message: matching: fix unmatched response trailers input
Additional Description: the patch fixes unmatched response trailers input and proto in its factory, and also adds tests for all HTTP matching inputs.
Testing: Unit
=> matching: fix unmatched response trailers input

source/common/filter/config_discovery_impl.cc, source/common/filter/config_discovery_impl.h
The type_url filed in any.proto is type: absl::string_view.
Receiving it with std::string is causing compiling issues in some systems. Change it to absl::string_view.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Fixing comipling issue related to any.proto type_url.

source/extensions/http/header_formatters/preserve_case/config.h
Commit Message: Declare `PreserveCaseFormatterFactoryConfig` factory
Additional Description: So it can be force-registered in Envoy Mobile.
Testing: Envoy Mobile CI (https://github.com/envoyproxy/envoy-mobile/pull/2279)
=> Declare `PreserveCaseFormatterFactoryConfig` factory

test/integration/alpn_integration_test.cc
Snagging the mutex meant there was still outstanding connections happening to the autonomous upstream on destruction which doesn't work well.
instead simply tearing things down while there's no outstanding work.
=> test: deflaking alpn test

source/common/upstream/cluster_manager_impl.cc
Commit Message: Move ENVOY_BUG into the runtime-guarded block it was supposed to be in
Additional Description: This looks like a merge slip in PR #21228 that put the ENVOY_BUG in the wrong place, which can trigger surprising crashes in debug builds (found in end to end testing).
Risk Level: Less than introducing the change was. :)
Testing: n/a
=> Move ENVOY_BUG into the runtime-guarded block it was supposed to be in

bazel/dependency_imports.bzl, bazel/repository_locations.bzl, docs/BUILD
Fix #20731
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> deps: Bump `rules_pkg` -> 0.7.0

docs/root/intro/arch_overview/upstream/connection_pooling.rst
Commit Message: Docs: Fix sphinx link syntax in connection pool documentation.
Risk Level: na
Testing: played around in https://livesphinx.herokuapp.com/
=> Docs: Fix sphinx link syntax in connection pool documentation.

test/extensions/filters/network/thrift_proxy/BUILD
While testing python-toolchains the windows run of this test reliably fails
Trying to debug this, i noticed that it occasionally fails on other CI runs
Increasing the shards here, makes my PR work (or at least fail later after passing flakily)
Im guessing that increasing this would reduce windows flakes in CI more generally
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> thrift: Increase test shard count (for windows)

test/server/config_validation/config_fuzz_test.cc
Commit Message: fuzz test: Use in-memory files to prevent conflicts.
The config_fuzz_test creates a file and failed some times, because a path was not create- or write-able. In-memory files prevent this issue.
Testing: n/a
=> fuzz test: Use in-memory files to prevent conflicts.

test/common/http/codec_impl_corpus/oom_due_to_leaky_expectation, test/common/http/codec_impl_fuzz_test.cc
Commit Message: Fix OOM that can occur in codec_impl_fuzz_test.
Additional Description: See below
My analysis is as follows:
1. Looking at the massif-out in visualizers, so the image below I see that we end up having allocating a lot of memory in directionAction via
a buffer ctor that takes a string view.
I took this hint to then annotate the pending send buffer, as I though the slice which originally was allocated from directionalAction ends up in another buffer.
We can see:
```
[2022-05-17 23:58:43.204][1592727][debug][http2] [source/common/http/http2/codec_impl.cc:804] [C8] Stream 1 has 2776084051 in pending_send_data
[2022-05-17 …
```
=> Fuzzer: Fix OOM that can occur in codec_impl_fuzz_test.

tools/protodoc/BUILD, tools/protodoc/protodoc.py
This makes use of the newly ~fixed RST backticks checker, and applies it to API docs as they are being built (by protodoc)
This just throws a warning for now, we can make it an error once these are cleaned up
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: Add WARNING for single backticks in API docs

changelogs/current.yaml, source/common/network/utility.cc, source/common/network/utility.h, source/common/upstream/logical_dns_cluster.cc, source/common/upstream/logical_dns_cluster.h, source/common/upstream/strict_dns_cluster.cc, source/common/upstream/strict_dns_cluster.h, test/common/network/utility_test.cc, test/integration/protocol_integration_test.cc
Fixing a bug where Envoy would not start with logical or strict DNS clusters with IPv6 addresses.
Testing: added integration tests actually using these clusters
=> upstream: fixing logical/strict DNS clusters for IPv6

WORKSPACE, bazel/python_dependencies.bzl, bazel/repositories_extra.bzl, ci/WORKSPACE.filter.example
Also bumps `rules_python` -> 0.8.0 (Fix #20431 ) 
In order to get this to work and to accommodate the 3 stages of loading required (register toolchains, register pipsets, install pipsets) i have had to move things around a little and add a `python_dependencies.bzl` file
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> repo: Use python toolchains

source/common/http/http2/codec_impl.cc, source/common/http/http2/codec_impl.h, test/common/http/codec_impl_corpus/clusterfuzz-testcase-minimized-codec_impl_fuzz_test-4785896639037440.fuzz
Commit Message: nghttp2: Prevent assert in getStream.
getStream() in error conditions can return a nullptr, which is valid and
treated correctly on call site. Introducing an unchecked version of
getStream without assert.
Testing: n/a
=> nghttp2: Prevent assert in getStream.

api/envoy/extensions/filters/http/stateful_session/v3/stateful_session.proto, source/extensions/filters/http/stateful_session/config.cc, source/extensions/filters/http/stateful_session/stateful_session.cc, source/extensions/filters/http/stateful_session/stateful_session.h, test/extensions/filters/http/stateful_session/config_test.cc, test/extensions/filters/http/stateful_session/stateful_session_test.cc
Backport https://github.com/envoyproxy/envoy/pull/20960 to 1.22. Check https://github.com/envoyproxy/envoy/pull/20960#issuecomment-1134572736 for some more context.
Additional Description: n/a.
Testing: n/a.
=> [Backport 1.22] stateful session: allow empty filter config (#20960)

source/common/http/http3/conn_pool.cc, source/common/quic/client_connection_factory_impl.cc, source/common/quic/client_connection_factory_impl.h, source/common/quic/envoy_quic_client_session.cc, source/common/quic/envoy_quic_client_session.h, test/common/http/http3/conn_pool_test.cc, test/common/quic/client_connection_factory_impl_test.cc, test/common/quic/envoy_quic_client_session_test.cc, test/common/quic/test_utils.h, test/integration/http_integration.cc, test/integration/quic_http_integration_test.cc, test/integration/utility.cc
Commit Message: pass 2 cluster config knobs socket options and transport socket options to EnvoyQuicClientSession and EnvoyQuicClientConnection.
=> h3 pool: quic connection honors socket options

source/common/common/logger.cc
`current_context` can be `nullptr` at beginning 
`static Context* current_context = nullptr;`
Commit Message: logger: avoid nullptr err in enableFancyLogger
Docs Changes:
Release Notes:
=> logger: avoid nullptr err in enableFancyLogger

bazel/BUILD
This is usable in selects for any android target.
=> bazel: add config_setting for android

ci/Dockerfile-envoy
Fix #21353
From https://console.cloud.google.com/gcr/images/distroless/global/base-debian11@sha256:d65ac1a65a4d82a48ebd0a22aea2acdd95d7abeeda245dfee932ec0018c781f4/details
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docker: Update distroless image -> `d65ac1a`

.bazelrc
We're seeing OOMs on the arm CI builds, this might fix that.
=> bazel: bump host jvm size

source/extensions/filters/common/lua/lua.cc, test/extensions/filters/common/lua/lua_test.cc
Commit Message: lua extension: handle empty lua errors
Additional Description: Calling "error()" in a lua script would result in a NULL pointer for the
lua string. This commit handles this case.
This is a revival of https://github.com/envoyproxy/envoy/pull/15471 with the missing test.
=> lua extension: handle empty lua errors

bazel/repositories.bzl
Commit Message: [cleanup] Remove quiche_spdy_platform which points at a nonentity
Additional Description: There is no target "spdy_platform" in quiche now, neither in the original nor the replacement build file.
Testing: n/a
=> [cleanup] Remove quiche_spdy_platform which points at a nonentity

source/common/quic/envoy_quic_dispatcher.cc, source/common/quic/platform/BUILD, source/common/quic/platform/quiche_flags_impl.cc
quiche: Move the code which sets FLAGS_quic_buffered_data_threshold from EnvoyQuicDispatcher to quiche_flag_impl.h
Testing: N/A
=> quiche: Move the code which sets FLAGS_quic_buffered_data_threshold 

source/common/http/http1/codec_impl.cc, source/common/http/http1/legacy_parser_impl.cc, source/common/http/http1/legacy_parser_impl.h, source/common/http/http1/parser.h
Replace Parser::httpMajor() and httpMinor() with a single isHttp11()
method, as that is the only thing ConnectionImpl cares about.  Note that
Protocol struct does not define HTTP/0.9 (in envoy/http/protocol.h)
anyway.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Simplify Parser HTTP version calls.

source/common/quic/platform/quiche_flags_impl.cc, source/common/quic/platform/quiche_flags_impl.h, test/common/quic/platform/quic_platform_test.cc, test/common/runtime/runtime_impl_test.cc
quiche: Make QUICHE reloadable flag behavior match runtime guard behavior
Currently QUICHE reloadable flags have curious behavior. When reloading a new snapshot, any reloadable flags which are not present in the snapshot have their values reverted to their default values. However, runtime guards which are not present in the snapshot do not have their values changed. This PR changes QUICHE reloadable flag behavior to match 
Testing: New unit tests
=> quiche: Make QUICHE reloadable flag behavior match runtime guard behavior

.bazelrc
Previously on CI there are so many tests that you have to scroll past
many successful test lines to find the last error. Now only the failing
tests are printed in the summary.
=> bazel: decrease size of test summary

test/extensions/filters/http/common/fuzz/filter_corpus/oss-fuzz-46967-filter_fuzz_test-6312516046684160, test/extensions/filters/http/common/fuzz/uber_per_filter.cc
Commit Message: fuzz test: Prevent illegal config for tap.
No longer cause abort due to illegal fuzzed configuration in the
filter_fuzz_test.
Testing: n/a
=> fuzz test: Prevent illegal config for tap.

ci/Dockerfile-envoy
Fix #21353
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [backport/v1.22] docker: Update distroless image -> `d65ac1a` (#21474)

ci/Dockerfile-envoy-distroless
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [backport/v1.21] docker: Update distroless image -> `d65ac1a`

test/extensions/filters/listener/common/fuzz/listener_filter_fuzzer.cc, test/extensions/filters/listener/common/fuzz/listener_filter_fuzzer.h, test/extensions/filters/listener/tls_inspector/tls_inspector_corpus/oss-fuzz-46844-tls_inspector_fuzz_test-5401720986927104
Commit Message: fuzz test: Close only open connections.
- In tls_inspector_fuzz_test an event-loop could block due to getting no
signal.
- Use a flag to indicate, that a connection has been opened and close it
only, when the flag has been set ensuring a close event can be received.
Testing: n/a
=> fuzz test: Close only open connections.

source/extensions/transport_sockets/tls/cert_validator/cert_validator.h, source/extensions/transport_sockets/tls/cert_validator/default_validator.cc, source/extensions/transport_sockets/tls/cert_validator/default_validator.h, source/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator.cc, source/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator.h, source/extensions/transport_sockets/tls/context_impl.cc, test/common/quic/envoy_quic_server_stream_test.cc, test/extensions/transport_sockets/tls/cert_validator/default_validator_test.cc, test/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator_test.cc
Commit Message: rename it to doSynchronousVerifyCertChain() to make its behavior difference more obvious from the the new interface in https://github.com/envoyproxy/envoy/pull/21417.
Risk Level: low, no behavior change
=> cert validator: rename CertValidator::doVerifyCertChain()

envoy/ssl/handshaker.h, source/extensions/transport_sockets/tls/context_config_impl.cc, source/extensions/transport_sockets/tls/context_config_impl.h, source/extensions/transport_sockets/tls/ssl_handshaker.h, test/mocks/server/transport_socket_factory_context.cc, test/mocks/server/transport_socket_factory_context.h
Commit Message: tls/handshaker: extend HandshakerFactoryContext with singletonManager
Additional Description: Allow Handshaker extension to access singleton manager
Risk Level: No Risk
Testing: No tests added, existing mock updated
Sometimes it is required to have access to some sort of "global cache" from TLS handshaker extension. So extending `HandshakerFactoryContext` with singletonManager property.
=> tls/handshaker: extend HandshakerFactoryContext with singletonManager

test/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter_test.cc
This change brings `absl::string_view` inline with `std::string_view`. Where the latter disallows passing `null` to its constructor.
=> Remove absl::string_view(nullptr) use as it is deprecated

bazel/dependency_imports.bzl, tools/base/envoy_python.bzl
Allows for easy merging/mangling of yaml and json data
Adds `yq` to allow dumping yaml to json
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tooling: Add  `genjson` macro

test/extensions/filters/http/common/fuzz/filter_corpus/clusterfuzz-testcase-minimized-filter_fuzz_test-6004616048803840, test/extensions/filters/http/common/fuzz/filter_fuzz_test.cc
Commit Message: fuzz test: Filter ext_authz plugin.
Filter ext_authz extension from being tested in the general
filter_fuzz_test, because it has a dedicated test and needs some
additional setup to work.
Testing: n/a
=> fuzz test: Filter ext_authz plugin.

test/extensions/filters/http/common/fuzz/BUILD, test/extensions/filters/http/common/fuzz/filter_corpus/oss-fuzz-47373-filter_fuzz_test-5658415797501952, test/extensions/filters/http/common/fuzz/uber_per_filter.cc
Commit Message: fuzz test: Limit number of threads for async file.
Limit the number of threads created for FileSystemBuffer.thread_pool()
to reduce the load in the test.
Testing: n/a
=> fuzz test: Limit number of threads for async file.

tools/api_proto_plugin/plugin.bzl, tools/api_proto_plugin/plugin.py
Filter non-interesting protos earlier.
- less descriptors to iterate
- avoids creating empty files
not sure how many this filters out in reality but may/not be many (google primitive protos i guess)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tooling: Micro-optimization for `api_proto_plugin`

tools/base/envoy_python.bzl, tools/protodoc/BUILD, tools/protodoc/protodoc.py
For optimized preloading of data
This macro takes a yaml or json data source, creates a python data pickle from it and exposes a python lib containing the `data`
If we load all of protodoc's data this way (and do any other validation/cleanup/mangling beforehand) we should be able to reduce overheads
in this initial pr the data artefacts required by protodoc are imported individually - in a followup i will merge the data to a single artefact
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/revi …
=> tooling: Add python data macro

api/STYLE.md
Commit Message: Add some examples and adjust the development flow to make it clear.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: update API STYLE.md

bazel/repository_locations.bzl
Commit Message: tls: update BoringSSL to 227ff6e6 (5060).
Additional Description: Updating BoringSSL to its latest revision.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tls: update BoringSSL to 227ff6e6 (5060).

bazel/foreign_cc/BUILD
Signed-off-by: Felix Du <felix.du@nokia-sbell.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/21497
=> contrib: std::exception can't be catched correctly with libc++

changelogs/current.yaml, docs/root/configuration/http/http_filters/lua_filter.rst, source/extensions/filters/http/lua/lua_filter.cc, source/extensions/filters/http/lua/lua_filter.h, source/extensions/filters/http/lua/wrappers.h, test/extensions/filters/http/lua/lua_filter_test.cc
Added microsecond resolution in lua timestamp function.
Timestamp function now returns a string representing the integer value of the selected resolution since epoch time.
N/A
Testing:
New unit test of lua timestamp function added. It checks the valid return of a microsecond resolution timestamp.
Slight modification of relevant millisecond unit test.
Docs Changes:
Added info in lua timestamp documentation. It clarifies that the return value is a string representing the integer value of the selected resolution.
Release Notes:
Added a relevant release note.
Platform Specific Features: 
N/A
[Optional Fixes #Issue] N/A
[Optional Fixes commit #PR or SHA] N/A
[Optional Deprecated:] N/A
[Optional [API …
=> lua: microseconds accuracy in timestamp

source/extensions/tracers/skywalking/skywalking_tracer_impl.cc, test/extensions/tracers/skywalking/skywalking_tracer_impl_test.cc
Commit Message: skywalking: fix to avoid tracing all requests
Current skywalking tracer will tracing all the requests by default and igore the sampling decision of Envoy. 
But in fact, if there is no downstream tracing context (propagation header) is provided and samping decision of Envoy is false, the tracer should do nothing.
Testing: Updated.
=> skywalking: fix to avoid tracing all requests

api/envoy/config/core/v3/protocol.proto, changelogs/current.yaml, envoy/http/codec.h, source/common/http/http1/codec_impl.cc, source/common/http/http1/codec_impl.h, source/common/http/http1/settings.cc, test/common/http/http1/codec_impl_test.cc, test/integration/integration_test.cc
Risk Level: low (and config guarded)
Testing: new unit, integration tests
Docs Changes: in with APIs
part of https://github.com/envoyproxy/envoy-mobile/issues/1622
=> http1: allowing for upstream absolutele URIs

bazel/foreign_cc/BUILD
When compile envoy on RedHat based OS like Fedra, zstd will compile error with complaining: external/envoy/bazel/foreign_cc/BUILD:551:12: output 'external/envoy/bazel/foreign_cc/zstd/lib/libzstd.a' was not created
This is because on RedHat based OS, CMAKE_INSTALL_LIBDIR default is set to lib64, so it will generate object in external/envoy/bazel/foreign_cc/zstd/lib64/libzstd.a
Add the cmake compile flag `CMAKE_INSTALL_LIBDIR: lib` to fix this.
Cherrypick of https://github.com/envoyproxy/envoy/pull/20918
=> [backport/v1.22] fix zstd compile error (#20918)

contrib/sip_proxy/filters/network/source/conn_manager.cc, contrib/sip_proxy/filters/network/source/decoder.cc, contrib/sip_proxy/filters/network/source/decoder.h, contrib/sip_proxy/filters/network/source/metadata.cc, contrib/sip_proxy/filters/network/source/metadata.h, contrib/sip_proxy/filters/network/source/router/router_impl.cc
all sip message in single connection share the same connection manager,
so share the same decoder, the bug is that only the first record-route
will be setted ep, the first-record-route flag should be reset at decode
complete.
Signed-off-by: Felix Du <felix.du@nokia-sbell.com>
Commit Message: sip-proxy: fix only first record-route add ep
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> contrib-sip-proxy: fix only first record-route add ep

envoy/router/router.h, source/common/router/router.h, source/common/router/upstream_request.cc, source/common/router/upstream_request.h, source/extensions/upstreams/http/tcp/upstream_request.cc, test/extensions/upstreams/http/tcp/upstream_request_test.cc, test/mocks/router/mocks.h, test/mocks/router/router_filter_interface.cc, test/mocks/router/router_filter_interface.h
Commit Message: router: update method of 'UpstreamToDownstream' to return 'Route'
Some important methods were moved from `RouteEntry` to `Route` in the #17359. This change make it impossible to access `metadata`/`typed metadata` in the custom `GenericConnPool` implementations.
This PR update method of `UpstreamToDownstream` to provide `Route` rather than provide `RouteEntry`.
=> router: update method of 'UpstreamToDownstream' to return 'Route'

test/extensions/access_loggers/open_telemetry/substitution_formatter_test.cc, test/extensions/filters/http/alternate_protocols_cache/filter_test.cc, test/mocks/stream_info/BUILD, test/mocks/stream_info/mocks.cc, test/mocks/stream_info/mocks.h
While working on access log formatter for upstream host metadata, I could not simulate error conditions because mock 
for UpstreamInfo was missing.
Added MockUpstreamInfo implementation and linked it to MockStreamInfo.
Testing: All existing unit tests are passing.
Release Notes: No 
=> test: added MockUpstreamInfo

.azure-pipelines/pipelines.yml, ci/do_ci.sh
This job was added mostly to accomodate python tests which have now moved to pytooling, so it makes more sense to just test the remaining tools where they are used and cut CI time
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: Remove tooling job

envoy/http/async_client.h, test/common/grpc/async_client_impl_test.cc
Commit Message: Async call API does not enforce that parent context is always set. When not set, `stream_info` is accessed as a raw pointer, which eventually leads to the following UB:
```
source/common/router/header_formatter.cc:289:24: runtime error: member call on address 0x7fff213f83a0 which does not point to an object of type 'Envoy::StreamInfo::StreamInfo'
0x7fff213f83a0: note: object has a possibly invalid vptr: abs(offset to top) too big
20 00 00 00  b0 47 19 00 20 60 00 00  02 00 00 00 00 00 00 00  f0 03 91 07 00 00 00 00  a0 85 3f 21
^~~~~~~~~~~~~~~~~~~~~~~
possibly invalid vptr
```
The fix is to initialize the field to `nullptr`.
Risk Level: low, internal API
Testing: added regression test
=> async: fix UB with uninitialized parent context

test/extensions/filters/http/common/fuzz/uber_filter.cc
Commit Message: fuzz test: Fix clearing decoding_buffer and stats.
In filter_fuzz_test a pointer to a buffer was stored, that could have
been freed between two fuzzer runs. Furthermore are stats reset, that
should be zero for each fuzzer run.
Testing: n/a
=> fuzz test: Fix clearing buffers

source/server/active_stream_listener_base.h, source/server/configuration_impl.cc, source/server/configuration_impl.h, source/server/listener_impl.cc, source/server/listener_impl.h
Commit Message: Listener ECDS: reject the connection directly when missing config
Testing: the existing integration test covered
Fixes #21427
=> Listener ECDS: reject the connection directly when missing config

test/common/router/route_corpus/clusterfuzz-testcase-minimized-route_fuzz_test-4870627644801024, test/common/router/route_fuzz_test.cc
Commit Message: fuzz test: Improve on_no_match validation. 
When fuzzing a routeaction with on_no_match, reject a configuration, if some fields are unset.
Testing: n/a
=> fuzz test: Improve on no match validation

api/envoy/config/route/v3/route.proto, changelogs/current.yaml, source/common/router/config_impl.cc, source/common/router/config_impl.h, test/common/router/config_impl_test.cc
Commit Message: Add an option in RouteConfiguration, if enabled, ignore path-parameters (RFC1808) in path matching.
Risk Level: LOW(default false).
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #21590
=> [router] Ignore path parameters when RouteConfiguration is configured

docs/BUILD, tools/protodoc/BUILD, tools/protodoc/protodoc.bzl
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> protodoc: Fix aspect and speedup api/rst build

changelogs/current.yaml, docs/root/operations/cli.rst, source/common/common/logger.cc, test/common/common/logger_test.cc
Commit Message: Fix `--log-format-escaped` to only log one newline per log line
Previously, when a log line contained multiple trailing newline characters, it would result in creating multiple empty lines in the log output. 
For example, `ENVOY_LOG(debug, "message\n message \n\n")` is translated to log line `message\n message \n\n\n`. With `--log-format-escaped` enabled, this is logged as:
```
message\n message
```
Because **all trailing whitespace characters** would not be escaped under the previous implementation. The correct behavior is for all `\n` to be escaped **except** the last one:
```
message\n message\n\n
```
Testing: Unit tests, including platform specific ones
Docs Changes: Updated wording in flag documentation
Release Notes: …
=> Fix `--log-format-escaped` to only log one newline per log line

test/common/http/http1/codec_impl_test.cc
Simplify Http1ServerConnectionImplTest::expect400() and tighten up tests using it.
Arguments `Protocol p` and `bool allow_absolute_url` had the same value
at all call sites.  Remove these arguments and hardcode the value in
function body.
Provide expected `responseDetails` value for one test that did not have
it, and remove default value.
Add expectation for `status.message()` in all four tests.
This is related to #21245.  Tighter tests will make changing parsers
safer.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
=> Tighten up four :codec_impl_tests.

changelogs/current.yaml, source/common/config/well_known_names.cc, source/common/config/well_known_names.h, test/common/stats/tag_extractor_impl_test.cc, test/extensions/filters/network/thrift_proxy/integration.h
Fixes issue #20201 by adding tag extraction for thrift proxy filter.
`curl 0.0.0.0:9901/stats/prometheus | grep this_is_a_thrift_tag`
```
envoy_thrift_cx_destroy_local_with_active_rq{envoy_thrift_prefix="this_is_a_thrift_tag"} 0
envoy_thrift_cx_destroy_remote_with_active_rq{envoy_thrift_prefix="this_is_a_thrift_tag"} 0
envoy_thrift_downstream_cx_max_requests{envoy_thrift_prefix="this_is_a_thrift_tag"} 0
envoy_thrift_downstream_response_drain_close{envoy_thrift_prefix="this_is_a_thrift_tag"} 0
envoy_thrift_no_healthy_upstream{envoy_thrift_prefix="this_is_a_thrift_tag"} 0
envoy_thrift_request{envoy_thrift_prefix="this_is_a_thrift_tag"} 0
envoy_thrift_request_call{envoy_thrift_prefix="this_is_a_thrift_tag"} 0
envoy_thrift_request_decoding_error{envoy_thrift_prefix="this_is_a_t …
```
=> Thrift Proxy: Fix tag extraction to work with filter stat_prefix

bazel/README.md
Commit Message: Fix a typo.
Testing:
Docs Changes:
Release Notes:
=> bazel/README.md: fix a typo

bazel/BUILD, bazel/envoy_binary.bzl, bazel/envoy_internal.bzl, bazel/envoy_test.bzl
This is a linker optimization that trades link time for binary size.
This change enables -no_deduplicate for dbg and fastbuild, which on my
M1 Max mbp takes link time of the main envoy binary from 60s to 12s on
macOS.
=> bazel: add -no_deduplicate for dbg builds on darwin

.azure-pipelines/bazel.yml
currently all check jobs run as "Run CI script" and there is no
way to differentiate them in azp analytics. This should resolve that.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: Differentiate check jobs (for azp analytics)

source/common/http/header_utility.cc, source/common/http/http1/codec_impl.cc, source/common/http/utility.cc, source/common/http/utility.h, source/common/quic/envoy_quic_client_stream.cc, source/common/router/retry_state_impl.cc, source/extensions/filters/http/gcp_authn/gcp_authn_impl.cc, test/common/http/codec_impl_fuzz_test.cc, test/common/http/utility_test.cc, test/common/router/retry_state_impl_test.cc, test/extensions/filters/http/common/fuzz/http_filter_fuzzer.h
Removing the http status code check which throws an exception. By default status will now ENVOY_BUG and return 0 if the status header is not present.
May break downstream unit tests which relied on the throw (as I had to refactor envoy unit tests accordingly)
=> http: removing throw

docs/root/configuration/upstream/clusters.rst, docs/root/configuration/upstream/upstream.rst, docs/root/intro/arch_overview/upstream/upstream.rst
Commit Message: There was no easy-to-find link to the cluster configuration docs from the main configuration reference.
Testing: docs-only
Docs Changes:
Release Notes:
=> docs: add configuration reference links for clusters

bazel/README.md, tools/proto_format/proto_format.sh
the flag is no longer experimental, and the default is what we
are setting it to.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tooling: Remove (default) `remote_download_outputs` flags

test/integration/listener_extension_discovery_integration_test.cc
Adding listener ECDS integration test to cover the case that two dynamic listener filters with different names and two config provider resources.
This is a follow up commit for https://github.com/envoyproxy/envoy/pull/21133.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Adding listener ECDS integration test case with two resources

.bazelrc
Since adding BES streaming/resultstore some jobs can timeout or take a very long time in CI
It doesnt happen all the time and is seemingly a bit random, although  it does appear to happen after jobs that invoke aspects so my suspicion is that it is uploading all the info for each aspect job despite not publishing any URL anywhere for them (i havent been able to confirm this, but it seems correct)
I have found a couple of jobs in resultstore where this has happened that show as ~"tool broken"~ "tool failed"
I tried setting the timeout very low, in the hope that it would just raise a warning and move on, but it errors - so i have instead set it to 5s (the `--bes_best_effort` flag might've help here but is deprecated).
If this breaks anything we can …
=> ci: Set timeout for BES/resultstore streaming

ci/build_setup.sh, tools/code_format/check_format_test_helper.py, tools/protoxform/protoprint.py
Currently the clang-format version is hardcoded to clang-format-11 if it doesnt find the one in env - this is wrong, so this PR fixes that.
Also, this currently works because whenever `CLANG_FORMAT` is required to be read from env it is running in a bazel `run` job so it can see the env var - this breaks if you try to run those jobs in a `build` job. This PR fixes that by adding `CLANG_FORMAT` as an `action_env` var
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: Fix `CLANG_FORMAT` version

test/common/http/BUILD, test/common/http/codec_impl_fuzz_test.cc
This allows the fuzzer to focus on the individual protocols better and allows us to categorize failures by protocol.
Commit Message: Split codec_impl_fuzz_test targets out by protocol.
Testing: built and ran target
=> Split codec_impl_fuzz_test targets out by protocol

contrib/sip_proxy/filters/network/source/router/router_impl.cc
If header of customized_affinity entities is `Route` and there is no
`Route` header in sip message, use `TOP-URI` instead
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [contrib-sipproxy] fix the issue of top-uri

.azure-pipelines/pipelines.yml, ci/check_and_fix_format.sh, ci/do_ci.sh, ci/format_pre.sh
Now that the format_pre jobs are much faster, i think it makes sense to put the format jobs together, with a view to integrating them longer term
currently, the proto_format job takes a lot longer than everyting else - im working to optimize this separately, but i think for now lets keep this separate and run concurrently
this PR also makes a slight change to the check_format run in that it just runs `fix` immediately rather than running `check` and conditionally running `fix`
the current behaviour with proto_format and check_format grouped together means that if either fails both are run twice - so this at least resolves that (proto_format still runs twice if it fails - but we can address that as part of optimization)
Risk Level:
Testing:
Docs …
=> ci: Re-organize format jobs

bazel/protobuf.patch, bazel/repository_locations.bzl
Following up offline conversation, a couple of cleanups for precompiled protoc:
- remove all but supported build architectures from protoc deps
- ensure canonical protobuf version
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> protoc: Version/dependency cleanups

source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc, test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
Fixes a bug in https://github.com/envoyproxy/envoy/pull/19588 (and previously) where after DNS resolutoin fail, subsequent requests weren't blackholed by the filter.
Testing: fixed integration tests
Fixes https://github.com/envoyproxy/envoy/issues/21410
=> dfp: consistent behavior on DNS resolution failure

bazel/repositories.bzl
this make it easier to use the api version in python jobs
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel: Add `API_VERSION` to `@envoy_repo` repository rule

test/extensions/access_loggers/open_telemetry/grpc_access_log_impl_test.cc
Signed-off-by: Alex Ellis <ellisonjtk@gmail.com>
Commit Message: Fix broken test after OpenTelemetry Tracer PR merge
Additional Description: As part of OpenTelemetry Tracer PR, I upgraded the OTLP proto library version. This included a breaking change to the OpenTelemetry Log proto, where the `logs` field in instrumentation_library_logs was renamed to `log_records`. Earlier today, a new test was added with `logs` in the yaml, and when my PR was merged in, this caused the new test to fail:
```
unknown file: Failure
C++ exception with description "Protobuf message (type opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest reason INVALID_ARGUMENT:(resource_logs.instrumentation_library_logs[0]) logs: Cannot find field.) has unknown fields" thrown in the test body. …
```
=> extensions: fix log_records entry in OTEL access logger test

tools/base/requirements.in, tools/base/requirements.txt
Adds a workaround to prevent dependency issues being raised for
release binary deps
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> deps: Bump py `envoy.dependency.check` -> 0.1.2

test/common/http/conn_manager_impl_corpus/oss-fuzz-48096-conn_manager_impl_fuzz_test-4884773308334080, test/common/http/conn_manager_impl_fuzz_test.cc
Commit Message: fuzz test: Sanitize status header before use, part 2.
In conn_manager_impl_fuzz_test the:status header needs to be sanitized
before use, too, due to the change having the getResponseHeader() no
longer throw but bug.
Testing: n/a
=> fuzz test: Sanitize status header before use, part 2.

bazel/BUILD, bazel/README.md, bazel/envoy_build_system.bzl, bazel/envoy_internal.bzl, bazel/envoy_select.bzl, changelogs/current.yaml, ci/do_ci.sh, source/server/admin/BUILD, source/server/admin/admin.cc, source/server/admin/admin_html.cc, source/server/admin/admin_no_html.cc, test/common/http/header_map_impl_test.cc, test/integration/integration_admin_test.cc, test/server/admin/BUILD, test/server/admin/admin_html_test.cc, test/server/admin/admin_test.cc
Commit Message: Make the HTML view for stats a compile-time option, defaulting to on. This PR doesn't change any code-paths, but it moves the HTML support into a separate file, compiled into //source/server/admin:admin_lib. In the future, and admin_html_lib will be added, built only when admin-html is not disabled. That will allow https://github.com/envoyproxy/envoy/pull/19546 and ultimately https://github.com/envoyproxy/envoy/pull/18670 to proceed.
To disable, compile with `--define=admin_html=disabled`, in which case the admin `"/"` endpoint will just print that the thml mode was disabled.
Additional Description: This PR is a step toward solving https://github.com/envoyproxy/envoy/issues/18675
Risk Level: low -- this just moves code around and doesn't change it at all.
Testing: …
=> admin: make admin HTML a compile-time option

api/buf.lock, api/buf.yaml, api/envoy/config/trace/v3/opentelemetry.proto, ci/format_pre.sh
initially this will only check for "unused imports" but we can expand as other linting rules are met.
in order to get this to work i had to fix the buf deps which were currently failing
i have also switched the buf version to v1 which provides the unused import test
...and fixed failing protos
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> api: Add `buf` linting

test/extensions/clusters/redis/redis_cluster_integration_test.cc
Test is now passing with https://github.com/envoyproxy/envoy/pull/21785
Signed-off-by: Sotiris Nanopoulos <sotiris.nanopoulos@reddit.com>
=> Remove `skip_tag_extraction_rule_check_` from RedisClusterTest

test/extensions/common/async_files/async_file_handle_thread_pool_test.cc
Commit Message: Fix flaky async_file_manager test
Additional Description: A race in the test destructor, fixed by explicitly deleting the things that have to go first in TearDown. Fixes issue #[21854](https://github.com/envoyproxy/envoy/issues/21854)
=> Fix flaky async_file_manager test

api/envoy/config/endpoint/v3/endpoint_components.proto
Signed-off-by: Mark D. Roth <roth@google.com>
Commit Message: xds: clarify endpoint weight default behavior
Additional Description: Updates the comment to reflect the underlying behavior.  The previous comment was misleading, because if some endpoints in a locality had weights but others did not, not all endpoints were given equal weight.  The actual behavior is that [we use a weight of 1](https://github.com/envoyproxy/envoy/blob/17d7d7908507888617824d73bc5904a3d79d1d17/source/common/upstream/upstream_impl.cc#L367) whenever the weight is unset.
Testing: N/A
[Optional [API …
=> xds: clarify endpoint weight default behavior

source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, source/extensions/filters/http/ext_proc/processor_state.cc, source/extensions/filters/http/ext_proc/processor_state.h, test/extensions/filters/http/ext_proc/ordering_test.cc
Commit Message: Move setCallbackState and startTimer or disableTimer into the same function call because callback_state and timer have the same lifetime. This will make the state machine management more consistent and easier to reason about.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [ext_proc]: Refactor ext proc timeout handling

source/extensions/tracers/opentelemetry/tracer.cc, source/extensions/tracers/opentelemetry/tracer.h, test/extensions/tracers/opentelemetry/opentelemetry_tracer_impl_test.cc
Signed-off-by: Alex Ellis <ellisonjtk@gmail.com>
Commit Message:  Add Span::setTag for setting attributes in OTLP Tracer
Additional Description: Adding attributes to the OTLP traces generated in the OTLP tracer (see https://github.com/envoyproxy/envoy/issues/9958). 
Here's a sampling of the attributes Envoy creates in a basic test setup (Envoy making a child span for its call to the Nighthawk test server) by just adding this method:
Testing: Added a unit test (with fleshed out proto expectations)
Part of #9958
=> extension: Add Span::setTag for setting attributes in OTLP Tracer

source/extensions/filters/http/file_system_buffer/filter.cc
Commit Message: Fix race in file_system_buffer filter (destroy filter vs open file)
Additional Description: If a filter is destroyed while asynchronously opening a file (too late to cancel but before the callback) it did not close the file, leading to an assertion in debug builds (file handle destroyed but not closed) or an open file descriptor leak in other builds. This change makes the callback close the file if the filter was destroyed. Fixes #21856.
Risk Level: Very Low (experimental filter, change only fixes unintentional behavior)
Testing: Test that was about 3% flaky passed with runs_per_test=200.
=> Fix race in file_system_buffer filter (destroy filter vs open file)

tools/testdata/protoxform/envoy/v2/BUILD
I believe this target currently works as whatever calls it provides required dependencies.
if you try to build it directly, or to include it in a `proto_descriptor_set` then it fails without the addition of these deps.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> cleanup: Fix `protoprint` test data

test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc, test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc, test/extensions/filters/http/router/auto_sni_integration_test.cc, test/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter_integration_test.cc, test/integration/base_integration_test.cc, test/integration/base_integration_test.h, test/integration/hds_integration_test.cc, test/integration/sds_dynamic_integration_test.cc, test/integration/sds_static_integration_test.cc, test/integration/xfcc_integration_test.cc
Previously, the BaseIntegrationTest::addFakeUpstream() function would only create a FakeUpstream, not taking
BaseIntegrationTest::autonomous_upstream_ into account.  This could lead to confusing integration test behavior.
With this change, the addFakeUpstream() function takes a required autonomous_upstream parameter that
indicates whether an AutonomousUpstream should be created instead of a FakeUpstream. 
=> test: Enable addFakeUpstream() to create AutonomousUpstreams

test/common/router/route_corpus/clusterfuzz-testcase-minimized-route_fuzz_test-5167783282868224, test/common/router/route_fuzz_test.cc
Commit Message: fuzz test: Include on_no_match.matcher into validation.
In an on_no_match not only an action can be set, but also a matcher.
This is now included into checks for valid configuration.
Corpus added.
Testing: n/a
=> fuzz test: Include on_no_match.matcher into validation.

source/common/network/io_socket_handle_impl.cc, source/common/network/io_socket_handle_impl.h, source/common/network/socket_interface_impl.cc, source/common/runtime/runtime_features.cc
We suspect that under some conditions, non-Android platforms (i.e. iOS) also would benefit from forcibly using IPv6 sockets, so to validate this this change adds a new runtime feature generalizing the one added for Android.
Risk Level: Low, runtime guard defaults to false.
Testing: Tested on an iPhone 13 Pro via Envoy Mobile, confirmed that an IPv4 address was being mapped to an IPv6 one.
Platform Specific Features: Not platform specific, but intended to be used on Apple platforms.
Runtime guard: `envoy.reloadable_features.always_use_v6` (default false)
=> network: allow Apple platforms to force IPv6 sockets

tools/protodoc/BUILD
the python libs are not required as the descriptor file should have the required data, and for the manifest proto we only need a python proto lib - so rather use `py_proto_library` directly
also, `manifest_to_json` directly imports from google.protoobuf so should have an explicit dep
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> protodoc: Small cleanup/optimization

docs/root/intro/arch_overview/upstream/connection_pooling.rst
Wasn't updated when https://github.com/envoyproxy/envoy/blob/main/source/common/runtime/runtime_features.cc#L35 was defaulted true
=> docs: update flag status

changelogs/current.yaml, source/extensions/tracers/opencensus/opencensus_tracer_impl.cc, test/extensions/tracers/opencensus/tracer_test.cc
tracing: remove unnecessary "spawnChild" annotations in OpenCensus tracer
This might be a left-over debug annotation from when the tracer was implemented. The annotations add no value and make traces harder to read. e.g.
Testing: None
Signed-off-by: nareddyt <tejunareddy@gmail.com>
=> tracing: remove unnecessary "spawnChild" annotations in OpenCensus tracer

tools/gen_compilation_database.py, tools/vscode/refresh_compdb.sh
The contrib directory sometimes doesn't build and prevents the VSCode code completion script
(tools/vscode/refresh_compdb.sh) from generating the symbols database.  This change overrides
the default directories built for the VSCode script by removing contrib and only building source,
test, and tools by default.
To allow including the contrib directories in the VSCode completion database, remove the 
`--exclude_contrib` flag from refresh_compdb.sh.
=> tools: Remove contrib from the VSCode code completion db

tools/api_proto_plugin/plugin.bzl
My understanding is that this parses args lazily, saves mem and optimizes aspects
Probs the args could be optimized further - this at least switches to using `ctx.actions.args`
More context here: https://docs.bazel.build/versions/main/skylark/performance.html#use-ctxactionsargs-for-command-lines
reading that page, i think there are a few more optis to be had around our handling of deps in rules
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> api_proto_plugin: Use `ctx.actions.args`

source/extensions/common/async_files/async_file_context_base.cc, source/extensions/common/async_files/async_file_context_base.h, source/extensions/common/async_files/async_file_context_thread_pool.h, source/extensions/common/async_files/async_file_manager.cc, source/extensions/common/async_files/async_file_manager_thread_pool.cc, source/extensions/common/async_files/async_file_manager_thread_pool.h
Commit Message: [async_files] Make cancel callbacks more consistent.
Additional Description: CancelFunction was defined to make the intent of returned callbacks in async_files more clear, but it was only partially applied. This change increases the usage.
Risk Level: None, no practical change.
Testing: Existing test coverage.
=> Make cancel callbacks more consistent

ci/do_ci.sh, tools/api_proto_plugin/plugin.bzl, tools/api_proto_plugin/plugin.py, tools/proto_format/BUILD, tools/proto_format/format_api.py, tools/proto_format/proto_sync.py, tools/protoprint/BUILD, tools/protoprint/protoprint.bzl, tools/protoprint/protoprint.py, tools/protoprint/protoprint_test.py, tools/protoxform/BUILD
This switches from calling protoprint in scripts with python multiproc to using a bazel aspect
Both the `proto_format.sh` job and the `protoprint_test` are switched to using a prebuilt protoprinted version of the api/test protos
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> proto_format: Use aspect to protoprint formatted api

ci/Dockerfile-envoy
following up on https://github.com/envoyproxy/envoy/issues/21899
switching the `COPY --chown` from `root` -> `0` resolved the following error i hit locally:
```console
unable to convert uid/gid chown string to host mapping: can't find uid for user root: open /var/lib/docker/overlay2/cd074b39f9fa59a8731b1b92200dfa7c652dd32739edaa52d595d75f0184c91d/merged/etc/passwd: no such file or directory             
```
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> dockerfile: Add default platform and use 0 for uid/gid

source/common/http/codec_client.cc
Commit Message: http: Skip useless check when get Connected event in CodecClient::onEvent
When reviewing the HTTP code, I think we can just `return` when getting a  `Network::ConnectionEvent::Connected` event to skip the unnecessary checks.
Testing: Waiting.
=> http: Skip useless check when get Connected event in CodecClient::onEvent

bazel/README.md
As a beginner I've had a tough time getting around Envoy. One of the things that got me scratching my head for a while was "how to run Envoy directly from the CLI?".
Although testing Envoy with bazel is magnificently documented (10/10 to whoever wrote it), I couldn't find much information on how to run Envoy from the CLI.
I believe this small section will be of great use for beginners, although I'm not convinced if this doc is the right one for the "Running envoy via CLI" section. What do you thing? 
> PS, in case there is already information on this topic, maybe we should make it more visible or easy to find.
Signed-off-by: Lucas Martinez <57833320+martinezlucas98@users.noreply.github.com>
=> docs: add section for running Envoy via CLI

source/extensions/io_socket/user_space/io_handle.h, source/extensions/io_socket/user_space/io_handle_impl.cc, test/extensions/transport_sockets/internal_upstream/internal_upstream_integration_test.cc
Commit Message: Fix assertion in internal listener user space socket. The assertion would fail if internal upstream transport socket is not used, but it is not necessary.
Additional Description: Added an integration test as well (apparently there was none before without internal upstream transport)
Testing: yes
=> internal listener: fix assertion in passthrough state

source/extensions/filters/network/dubbo_proxy/active_message.cc, source/extensions/filters/network/dubbo_proxy/decoder_event_handler.h, source/extensions/filters/network/dubbo_proxy/router/router_impl.cc, test/extensions/filters/network/dubbo_proxy/conn_manager_test.cc, test/extensions/filters/network/dubbo_proxy/router_test.cc
The meaning of the StopIteration status is ambiguous: it is used in two scenarios now:
* Pause the current iteration of the l7 filter chain and the execution of the filter chain will be resumed later.  In this case, the current implementation is fine.
* Abort the iteration of the l7 filter chain. In this case, the current implementation results in memory leak since the active message will not be deleted from the connection manager until the downstream connection is closed.
This PR solves this issue by splitting StopIteration into two unambiguous statuses: PauseIteration and AbortIteration
* PauseIteration: the filter iteration is paused and will be resumed later, for e.g, waiting for an available connection. The corresponding message remains in the connection manager.
* AbortIteration: …
=> Split StopIteration into two statuses

envoy/network/dns_resolver.h, source/common/config/utility.h, source/common/network/dns_resolver/dns_factory_util.cc, source/exe/BUILD, source/exe/process_wide.cc, source/extensions/network/dns_resolver/cares/dns_impl.cc
Only call ares_library_init()/cleanup() routines in process_wide() if ares extension is used in DNS resolving.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Only call ares_library_init()/cleanup() routines in process_wide() if ares extension used in DNS resolving.

docs/BUILD, docs/build.sh, tools/base/requirements.in, tools/base/requirements.txt, tools/docs/generate_api_rst.py, tools/docs/generate_extensions_security_rst.py, tools/docs/generate_external_deps_rst.py, tools/protodoc/generate_empty.py
This significantly speeds up RBE docs build
for non-RBE it may very slightly slower, but at least uses less diskspace and may be faster from less io
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: Compress files in build pipeline

api/bazel/api_build_system.bzl, tools/protoshared/BUILD, tools/protoshared/protoshared.bzl
This cycles proto deps and creates a descriptor file from them - but only for dependencies, not targets - thereby creating a descriptor of all envoy's proto deps.
This will allow other proto plugins to call protoc with the descriptor
file and just their `direct_sources` and not all of the `transitive_sources`
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> api_proto_plugin: Add `protoshared` aspect

changelogs/current.yaml, source/extensions/filters/network/thrift_proxy/BUILD, source/extensions/filters/network/thrift_proxy/router/upstream_request.cc, source/extensions/filters/network/thrift_proxy/router/upstream_request.h, source/extensions/filters/network/thrift_proxy/thrift.h, test/extensions/filters/network/thrift_proxy/conn_manager_test.cc, test/extensions/filters/network/thrift_proxy/router_test.cc
serviceA --> envoyA --> envoyB --> serviceB
When envoyB sends drain header to envoyA, envoyA will close its upstream connection.
However, the local connection failure event in envoyA triggers the downstream disconnection, which should be prevented.
Otherwise, serviceA could keep sending request which will be failed by connection error.
Upstream request keeps a state {request_complete,  response_started, draining, response_complete} and try not to 
close downstream connection if the response is complete or in draining stage.
Docs Changes: current.yaml
Release Notes:
=> Thrift: Keep downstream connection if response is complete without underflow

tools/api_proto_plugin/plugin.bzl, tools/proto_format/BUILD, tools/proto_format/format_api.py, tools/proto_format/proto_sync.py, tools/protoprint/BUILD, tools/protoprint/protoprint.bzl, tools/protoprint/protoprint.py
- dont wait on protoxform
- improve handling of pybin args
- add `extra_inputs` to `api_proto_plugin`
- remove runfiles from `protoprint` (and sys.path hack)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> protoprint: Cleanups/fixes

source/common/network/utility.cc, test/common/network/utility_test.cc
Commit Message: Fix crash in config_dump when using internal address.
Testing: yes
=> internal address: fix assertion in config_dump?include_eds

envoy/stream_info/stream_info.h, source/common/router/router.cc, test/config/utility.cc, test/integration/http_timeout_integration_test.cc
Per https://github.com/envoyproxy/envoy/issues/13068 the upstream_response_timeout can occur before an upstream has been assigned.  Renaming for clarity.
Release Notes:
[Optional Runtime guard:
=> http: updating response code details

changelogs/current.yaml, source/extensions/filters/http/aws_lambda/aws_lambda_filter.cc, source/extensions/filters/http/aws_lambda/aws_lambda_filter.h, test/extensions/filters/http/aws_lambda/aws_lambda_filter_test.cc
Signed-off-by: Vaibhav Dhage <vddhage@amazon.com>
- Allow cross account lambda function invocation by setting the path in header with complete Lambda ARN instead of the function name.
- Without this change, lambda filter always calls the lambda function in the AWS account where envoy runs and fails if it can't find the function in that account with the same name.
Risk Level:
- Low
Testing:
- Unit Test
- Integration Test
- Manual testing in AWS cross account setup to make sure function invocation works for both in account and cross account.
Docs Changes:
Release Notes:
[Optional [API …
=> aws_lambda: allow cross account lambda function invocation

test/server/connection_handler_test.cc
Commit Message: bug fix: fix connection handler test bug. 
Additional Description: It returned a reference to a shared pointer on the stack that gets deleted after returning from the call.
Testing: ran with asan, msan
=> Bug fix: fix connection handler test bug. 

api/contrib/envoy/extensions/filters/network/sip_proxy/v3alpha/sip_proxy.proto, tools/api_proto_plugin/annotations.py, tools/api_proto_plugin/type_context.py, tools/protodoc/protodoc.py, tools/protoprint/protoprint.py, tools/protoprint/protoprint_test.py
This is a general cleanup to shift responsibility for normalizing comment strings in `type_context`
This will make it easier to shift protodoc to templates, and also will enforce comments have a preceding space - ie `// comment` not `//comment` and prevent bugs as can be seen here https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/sip_proxy/v3alpha/sip_proxy.proto.html?highlight=sip_proxy#extensions-filters-network-sip-proxy-v3alpha-localservice
it also shifts some v inefficient closures
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional …
=> api_proto_plugin: Normalize `SourceCodeInfo.comments` in `type_context`

tools/base/requirements.in, tools/base/requirements.txt, tools/dependency/BUILD
this reduces the deps of the core package/s and therefore reduces the deps required to run many of the py tooling packages
the deps are the same overall, but just much less deps are required for most of the packages
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tooling: Reduce transient py deps

api/envoy/extensions/filters/network/redis_proxy/v3/BUILD, api/envoy/extensions/filters/network/redis_proxy/v3/redis_proxy.proto, changelogs/current.yaml, source/extensions/filters/network/redis_proxy/proxy_filter.cc, source/extensions/filters/network/redis_proxy/proxy_filter.h, test/common/network/multi_connection_base_impl_test.cc, test/extensions/filters/network/redis_proxy/proxy_filter_test.cc, test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc
Commit Message: redis_proxy: support multiple passwords
Additional Description: When rotating passwords, we need to support multiple passwords for graceful deployment/rollout. This change adds support for multiple passwords in AUTH, for both old auth and new ACL based one.
Testing: Integration and unit tests
Signed-off-by: Suresh Kumar <sureshkumar.pp@gmail.com>
Signed-off-by: Suresh Kumar <suresh.ponnusamy@freshworks.com>
=> redis_proxy: support multiple passwords

changelogs/current.yaml, source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc, source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.h, test/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter_test.cc
To fix https://github.com/envoyproxy/envoy/issues/21490
grpc response transcoder will fail with error if the proto message is too deep (>64),  but grpc_transcoder filter encodeData() function did not check the error status.  This pr adds code to check the error status and adds a test.
Risk Level:  Low
Testing:  Unit-test
=> grpc_transcoder: check response transcoder error

source/common/http/http1/balsa_parser.cc, test/common/http/http1/codec_impl_test.cc
This fixes Http1ServerConnectionImplTest.RejectInvalidMethod, and also
tightens up the test by adding one expectation.
Tested by patching in #22039 and running
bazel test //test/common/http/http1:codec_impl_test
--test_arg=--runtime-feature-override-for-tests=envoy.reloadable_features.http1_use_balsa_parser
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [balsa] Verify method.

tools/api_proto_plugin/plugin.py
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> api_proto_plugin: Remove debugging code

bazel/BUILD, bazel/volatile_env.sh, docs/BUILD, docs/build.sh, tools/base/requirements.in, tools/base/requirements.txt
This speeds up building docs when switching branches by not automatically expiring caches on the git sha
It also pushes responsibility script -> bazel for determining the build env
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: Use stamping for deriving git sha

api/contrib/envoy/extensions/filters/network/sip_proxy/tra/v3alpha/tra.proto, api/contrib/envoy/extensions/filters/network/sip_proxy/v3alpha/sip_proxy.proto, contrib/sip_proxy/filters/network/source/conn_manager.cc, contrib/sip_proxy/filters/network/source/conn_manager.h, contrib/sip_proxy/filters/network/source/decoder.cc, contrib/sip_proxy/filters/network/source/metadata.h, contrib/sip_proxy/filters/network/source/router/router_impl.cc, contrib/sip_proxy/filters/network/source/tra/tra.h, contrib/sip_proxy/filters/network/source/tra/tra_impl.cc, contrib/sip_proxy/filters/network/source/tra/tra_impl.h, contrib/sip_proxy/filters/network/source/utility.h, contrib/sip_proxy/filters/network/test/decoder_test.cc, contrib/sip_proxy/filters/network/test/mocks.cc, contrib/sip_proxy/filters/network/test/mocks.h, contrib/sip_proxy/filters/network/test/router_test.cc, contrib/sip_proxy/filters/network/test/tra_test.cc
Commit Message: SIP Proxy extension TRA API updated to send additional SIP context.
Co-authored-by: Jonah Murphy <jonamurp@cisco.com>
Additional Description: This PR contains the following changes:
1. SIP Proxy extension TRA API updated to send additional SIP context (method type and from header), so TRA service can use this information for customized affinity management.
2. Fix an error with decoding of SIP headers with a valid format causing Envoy proxy to crash in case of empty header fields.
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/re …
=> sip_proxy: add SIP context to TRA requests

docs/root/intro/arch_overview/advanced/attributes.rst, source/extensions/filters/common/expr/context.cc, source/extensions/filters/common/expr/context.h, test/extensions/filters/common/expr/context_test.cc
Commit Message: Add SHA256 digest to Cel/Wasm context
Testing: unit 
Docs Changes: yes 
Fixes: https://github.com/envoyproxy/envoy/issues/14229
=> expr: add SHA256 certificate digest

bazel/README.md, ci/README.md
docs: new parameter name for the bazel remote cache
The bazel parameter '--remote_http_cache' has been renamed to
'--remote_cache'. Use the new name.
=> docs: new parameter name for the bazel remote cache

docs/root/start/sandboxes/brotli.rst, docs/root/start/sandboxes/cache.rst, docs/root/start/sandboxes/double-proxy.rst, docs/root/start/sandboxes/dynamic-configuration-control-plane.rst, docs/root/start/sandboxes/dynamic-configuration-filesystem.rst, docs/root/start/sandboxes/front_proxy.rst, docs/root/start/sandboxes/gzip.rst, docs/root/start/sandboxes/local_ratelimit.rst, docs/root/start/sandboxes/tls-sni.rst, docs/root/start/sandboxes/wasm-cc.rst, docs/root/start/sandboxes/zstd.rst
Follow on fix for #20915
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: Fix example composition build instructions

api/envoy/extensions/filters/http/lua/v3/BUILD, api/envoy/extensions/filters/http/lua/v3/lua.proto, changelogs/current.yaml, docs/root/configuration/http/http_filters/lua_filter.rst, examples/lua/envoy.yaml, source/extensions/filters/http/lua/lua_filter.cc, source/extensions/filters/http/lua/lua_filter.h, test/extensions/filters/http/lua/config_test.cc, test/extensions/filters/http/lua/lua_filter_test.cc, test/extensions/filters/http/lua/lua_integration_test.cc
Commit Message: lua: deprecate inline_code and use default_source_code
Lua source codes map and per route inline source code are supported after #11235 and #12516. However, the `inline_code` field is still necessary for the proto validation.
For users who needn't global/default script, they always need to set a `inline_code` with meaningless code (#14030). This PR will fix this problem.
**This PR will make the `inline_code` optional (remove the `string.min_len` validation) and deprecate it. The  `default_source_code`(of type  `core.v3.DataSource`) will be used to set default/global script.**
Testing: Updated.
Docs Changes: Updated.
=> lua: deprecate inline_code and use default_source_code

docs/BUILD, docs/conf.py, docs/root/_pygments/style.py
Fix #22050 
This PR links docs builds with a selection of pygments themes for code-block highlighting
We can adapt a chosen theme, but the less we have to do so the better
Some changes are easier than others - for example changing the background
I think that a few of the themes might work better if they didnt have a white background
Risk Level:
Testing:
Docs Changes:
Release Notes:
https://dt.iki.fi/pygments-gallery
- start/quick-start/run-envoy.html
- start/sandboxes/ext_authz.html
- start/sandboxes/wasm-cc.html …
=> docs: Improve code-block highlighting

source/common/network/io_socket_handle_impl.cc, source/common/network/utility.cc, source/extensions/network/dns_resolver/cares/dns_impl.cc, test/extensions/network/dns_resolver/cares/dns_impl_test.cc
Additional Description: Only some error messages are affected.
=> spelling: Replace 'getiffaddrs' with 'getifaddrs'

contrib/sip_proxy/filters/network/source/conn_manager.cc, contrib/sip_proxy/filters/network/source/conn_manager.h, contrib/sip_proxy/filters/network/source/router/router_impl.h, contrib/sip_proxy/filters/network/source/tra/tra_impl.cc, contrib/sip_proxy/filters/network/source/tra/tra_impl.h, source/common/grpc/typed_async_client.h
Commit Message: fix the coredump when stream is nullptr, then return directly instead of still sendMessage
Testing: MT
=> fix coredump

ci/Dockerfile-envoy-distroless
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [backport/v1.21] docker: Bump `distroless/base-debian11:nonroot` -> `49d2923f35d6`

api/bazel/api_build_system.bzl, source/extensions/all_extensions.bzl
Use of depsets, and `to_list` are recomended against unless actually necessary (https://docs.bazel.build/versions/main/skylark/performance.html)
The recommended advice to simulate a set in starlark is to use dictionary keys (https://docs.bazel.build/versions/main/skylark/lib/depset.html)
> The elements of a depset must be hashable and all of the same type (as defined by the built-in type(x) function), but depsets are not simply hash sets and do not support fast membership tests. If you need a general set datatype, you can simulate one using a dictionary where all keys map to True.
Risk Level:
Testing:
Docs Changes:
Release Notes: …
=> bazel: Remove uses of `depset.to_list` where possible

bazel/envoy_library.bzl, test/proto/BUILD
The usage of this variable was removed in
https://github.com/envoyproxy/envoy/commit/4e858f17fe08224c9c089240908ccd0c518e01a7,
only 1 target provided these today. If more did this would change
behavior since now they're included in kwargs, but I don't think the
intent was to ignore them. Buildifier now flags these as unused.
=> bazel: remove external_deps from envoy_proto_library

docs/root/intro/arch_overview/other_protocols/redis.rst
Signed-off-by: Brian P O'Rourke <brian@orourke.io>
pfcount/pfadd were added in #12608 but not documented. This just adds them.
Risk Level: 
Testing:
Docs Changes:
Release Notes:
=> docs: note pfcount and pfadd support 

source/common/http/conn_manager_impl.cc, source/common/http/conn_manager_impl.h, source/common/http/filter_manager.cc, source/common/http/filter_manager.h
moving filter end decode from the FM (an upstream /downstream concept) to HCM as it should only be done once.
Part of https://github.com/envoyproxy/envoy/issues/10455
=> fm: handling decode data better

source/common/protobuf/BUILD, source/common/protobuf/utility.cc, source/common/protobuf/utility.h, test/common/protobuf/BUILD, test/common/protobuf/utility_test.cc, tools/code_format/check_format.py, tools/code_format/check_format_test_helper.py
Return the error message to the caller site and let caller decides how to handle it (e.g., logging etc) instead of throwing the exception.
=> Implement no throw version of `unpackTo` to avoid throwing exception on dataplane

bazel/foreign_cc/BUILD, source/common/io/BUILD, test/common/io/BUILD
This is a workaround for
https://github.com/envoyproxy/envoy/issues/22217 with the downside that
it disables it for all platforms.
=> bazel: disable uring with compilation database

source/extensions/filters/http/file_system_buffer/filter.cc
provide type to std::weak_ptr template
Most compilers do not have problems deducing type for `std::weak_ptr` without explicit type
`std::weak_ptr(shared_from_this())`, but lack of the type breaks a build on macos 10.15: https://github.com/Homebrew/homebrew-core/pull/105900
Testing: Use existing unit tests.
Release Notes: No 
=> c++: provide type to std::weak_ptr template

contrib/qat/private_key_providers/test/ops_test.cc
Remove a test that is causing flakes in CI (https://github.com/envoyproxy/envoy/pull/21984#issuecomment-1188826531). A quick analysis indicates that there is a non-working interaction between MockTransportSocketFactoryContext and MockClusterInfo. Rethink later how to implement the test properly.
=> qat: remove flaking test.

.bazelrc, ci/build_setup.sh
Commit Message: build: ensure gold linker is used by the gcc compiler
The `build_setup.sh` will export `/opt/llvm/bin` to the `$PATH`. And the bazel will use the lld linker first. This PR will ensure the gold linker is used by the gcc compiler.
Testing: n/a.
=> build: ensure gold linker is used by the gcc compiler

bazel/BUILD
See https://github.com/bazelbuild/bazel/issues/14982
Testing: Verified by building Envoy Mobile for Android armeabi-v7a
=> bazel: fix android armeabi-v7a constraint

source/common/http/http1/codec_impl.cc, test/common/http/http1/codec_impl_test.cc
Prefix "{headers,trailers} {size,count} exceeds limit" error messages
with "http/1.1 protocol error: " to make them consistent with other
error messages generated by ConnectionImpl.  This is necessary for
BalsaParser, as header size will be enforced by the parser itself
instead of ConnectionImpl, and the "http/1.1 protocol error: " string is
prepended to parser error messages at
https://github.com/envoyproxy/envoy/blob/62633018b2d0ea2e16d5acfea3673acb3aeaa7c8/source/common/http/http1/codec_impl.cc#L687.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
=> [http] Change header size and count limit error messages.

source/extensions/filters/network/http_connection_manager/config.cc
Commit Message: hcm: fix switch-case scopes in config
Fixing a strange curly-brackets scopes in a switch statement that was introduced in #22301.
This doesn't seem to impact the behavior after compilation, but fixes the readability of the code.
Testing: N/A.
=> hcm: fix switch-case scopes in config

api/envoy/config/metrics/v3/stats.proto
Commit Message: The documentation in the protobuf comments for stats tag extractors has been stale since 2018. This corrects the documentation to match the current behavior.
Additional Description: This documents a change that was done in Feb 2018: https://github.com/envoyproxy/envoy/pull/2515 -- obviously we should've fixed the doc then but it was overlooked.
Testing: none
Docs Changes: this is a doc change only, to reflect current reality
=> stats: Correct the documentation around tag extraction

source/extensions/filters/listener/http_inspector/http_inspector.cc, source/extensions/filters/listener/http_inspector/http_inspector.h, test/extensions/filters/listener/http_inspector/http_inspector_test.cc
Commit Message: http inspector: fix incorrect protocol detection
The http inspector will search first `\r\n` in the buffer and decode the data before the `\r\n`  with http parser. If there is no parsing error, the message will treated as http message.
**However, the message that contains only `\r\n` or started with `\r\n` will be inspected as http message also.** For example, `\r\n\r\n\r\n LS`.
This PR fix this problem.
=> http inspector: fix incorrect protocol detection

api/envoy/extensions/compression/gzip/decompressor/v3/gzip.proto, changelogs/current.yaml, source/extensions/compression/gzip/decompressor/config.cc, source/extensions/compression/gzip/decompressor/config.h, source/extensions/compression/gzip/decompressor/zlib_decompressor_impl.cc, source/extensions/compression/gzip/decompressor/zlib_decompressor_impl.h, test/extensions/compression/gzip/compressor_fuzz_test.cc, test/extensions/compression/gzip/decompressor/zlib_decompressor_impl_test.cc, test/extensions/filters/http/compressor/compressor_filter_integration_test.cc, test/extensions/filters/http/decompressor/decompressor_filter_integration_test.cc
Due to [quickfix of decompression oom](https://github.com/envoyproxy/envoy/commit/d4c39e635603e2f23e1e08ddecf5a5fb5a706338), decompressed data size will be truncated at around `input-size` * `fixed-ratio` currently which may cause incomplete decompression, see [1](https://github.com/envoyproxy/envoy/issues/21647), [2](https://github.com/envoyproxy/envoy/pull/21818).
So I add `max_inflate_ratio` in config instead of const value to limit output size.
=> decompressor: more flexible way to limit output size of gzip decompressor

test/integration/listener_lds_integration_test.cc
Commit Message: listener: fix flaky listener integration test
The listener socket is closed async https://github.com/envoyproxy/envoy/blob/3f0efa989f9776a8e1fcff3b1d1464da66aecb7e/source/server/listener_manager_impl.cc#L561-L567
So there can be a chance the listener was removed, but the socket doesn't remove yet.
Fixes #22348
=> listener: fix flaky listener integration test

envoy/upstream/load_balancer.h, test/integration/load_balancers/BUILD, test/integration/load_balancers/config.proto, test/integration/load_balancers/custom_lb_policy.h, test/mocks/upstream/typed_load_balancer_factory.h
Note: this is a breaking change for any TypedLoadBalancerFactory that does not currently implement `createEmptyConfigProto()`.
Signed-off-by: Eugene Chan <eugenechan@google.com>
Commit Message: Make TypedLoadBalancerFactory a TypedFactory
Additional Description: It's currently an UntypedFactory.
Testing: modified the existing CI tests
=> Make TypedLoadBalancerFactory a TypedFactory

source/common/http/utility.cc, test/common/http/utility_test.cc
* Decode only if the two characters following a '%' are hexadecimal
characters.
* Decode parameters that have a name without a value.
Example query string: "?test%20name"
It's safe to fix these bugs with a public pull request (checked with envoy-security@googlegroups.com).
=> utility: fix percent decoding of parameters

source/common/http/http2/nghttp2.cc
The current code flow is that install logger when ENVOY_NGHTTP2_TRACE is set, while the comment is the opposite.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> nghttp: update code comments

source/extensions/filters/network/thrift_proxy/router/upstream_request.cc, source/extensions/filters/network/thrift_proxy/router/upstream_request.h
We have too many boolean state for response state which makes the code is hard to read.
Testing: unit
Docs Changes:
Release Notes:
=> Thrift: refactor the response flags into one enum class

.azure-pipelines/pipelines.yml, tools/code_format/check_format_test_helper.py
This removes the protobuf test from this script test as the script no longer provides this functionality
It also (correctly) enables the test in CI
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> check_format: Fix related test

docs/root/intro/arch_overview/advanced/matching/matching_api.rst
Commit Message: docs: fix typo in matching API
Testing: N/A
Docs Changes: Matching API
=> docs: fix typo in matching API

envoy/stream_info/stream_info.h, source/common/http/conn_manager_impl.cc, source/common/http/conn_manager_impl.h, source/common/http/filter_manager.cc, source/common/http/filter_manager.h, source/common/stream_info/stream_info_impl.h, test/common/http/filter_manager_test.cc, test/mocks/http/mocks.h, test/mocks/stream_info/mocks.h
This PR does two things.  
1) it moves the translation of metadata map types to the HCM, so we consistently use MetadataMapPtr&& everywhere in between the upstream codec and the downstream codec and
2) start moving downstream-only code out of the generic FM base class into a downstream-specific base class.  Specifically I'm claiming (and documenting) that if an upstream filter sends a local reply, as the response is not generated by the cluster so should only traverse the downstream filter chain, so UpstreamFM sendLocal Reply will just forward sendLocalReply to the DownstreamFM and HCM. 
Risk Level: low (minor refactors)
Testing: n/a
Part of https://github.com/envoyproxy/envoy/issues/10455
=> filter:manager change metadata and downstream APIs.

source/extensions/common/wasm/context.cc, test/extensions/filters/http/wasm/test_data/test_grpc_call_cpp.cc, test/extensions/filters/http/wasm/wasm_filter_test.cc, test/per_file_coverage.sh
Commit Message: A fix to address an issue in istio/proxy. There's a major problem in ABI implementation dealing with `proxy_done`. The code is written so that `ContextBase` may delete `Context` while executing methods on `Context`. This PR addresses known use of `proxy_done` when called from gRPC handler by wrapping continuation into deferred actions before calling `ContextBase`.
Testing: manual verification, regression test
Docs Changes:
Release Notes:
=> wasm: fix crash in gRPC/HTTP handlers calling proxy_done

changelogs/current.yaml, source/server/admin/prometheus_stats.cc, test/server/admin/prometheus_stats_test.cc, test/server/admin/stats_handler_test.cc
Signed-off-by: 白泽 <patrickjiang0530@gmail.com>
Additional Description: comptiable with openmetrics that removing blank line on prometheus metrics 
=> comptiable with openmetrics that removing blank line on prometheus metrics 

source/common/http/http1/codec_impl.cc, source/common/http/http1/codec_impl.h
=> Rename H/1 codec method to reduce confusion

envoy/network/listener.h, source/server/admin/admin.h, source/server/listener_impl.h, source/server/listener_manager_impl.cc, test/common/quic/active_quic_listener_test.cc, test/extensions/bootstrap/internal_listener/active_internal_listener_test.cc, test/extensions/common/proxy_protocol/proxy_protocol_regression_test.cc, test/extensions/filters/listener/common/fuzz/listener_filter_fuzzer.h, test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc, test/extensions/filters/network/echo/echo_integration_test.cc, test/integration/fake_upstream.h, test/integration/integration_admin_test.cc, test/integration/server.cc, test/mocks/network/mocks.cc, test/mocks/network/mocks.h, test/mocks/server/worker.cc, test/per_file_coverage.sh, test/server/active_udp_listener_test.cc, test/server/connection_handler_test.cc, test/server/listener_manager_impl_quic_only_test.cc, test/server/listener_manager_impl_test.cc
Commit Message: multiple addresses listener: remove the legacy interface
Since the multiple addresses listener is implemented,  all the code moves to use the new multiple socket factories interface, then those old single socket factory interfaces can be removed now.
Fixes #11184
=> multiple addresses listener: remove legacy interface

source/server/connection_handler_impl.cc, source/server/connection_handler_impl.h
Commit Message: ConnectionHandlerImpl: refactor to share common code
Both `getUdpListenerCallbacks` and `getBalancedHandlerByTag` are doing the similar thing. create a common method `findPerAddressActiveListenerDetails` for finding the specific address listener details.
=> ConnectionHandlerImpl: refactor to share common code

source/common/http/http2/codec_impl.cc, test/common/http/http2/codec_impl_test.cc
Right now if we call newStream and then reset the stream before sending headers, we attempt to have the codec send a reset stream to stream_id -1.  nghttp2 appears to silently swallow this without complaint. oghttp2 will soon as well but either way it doesn't make sense to reset the stream before a stream id has been assigned.
=> http2: guarding against stream reset before stream creation

test/common/protobuf/utility_test.cc, test/common/router/config_impl_test.cc, test/common/upstream/upstream_impl_test.cc, test/extensions/filters/http/decompressor/decompressor_filter_test.cc, test/extensions/filters/http/health_check/config_test.cc, test/extensions/filters/http/ratelimit/config_test.cc, test/extensions/filters/http/router/config_test.cc, test/extensions/filters/network/http_connection_manager/config_test.cc, test/extensions/http/header_formatters/preserve_case/config_test.cc, test/tools/schema_validator/test/schema_validator_test.cc
(on behalf of protobuf-team)
Protobuf does not guarantee the contents of these messages, so these
tests may be broken by upgrades if not fixed.
Signed-off-by: Miguel Young de la Sota <mcyoung@google.com>
=> Fix brittle tests that depend on the contents of Protobuf JSON error messages

changelogs/current.yaml, source/extensions/transport_sockets/tcp_stats/tcp_stats.cc, test/extensions/transport_sockets/tcp_stats/tcp_stats_test.cc
The syscall might change the optlen value to hold the actual value of
the resturned value in optval.
In my case it's reducing that value to 192, and thus some tests are
failing.
Signed-off-by: Jonh Wendell <jonh.wendell@redhat.com>
=> Fix the analisys of getsockopt() call

source/common/router/config_impl.cc
Fixes the following build errors when `-Wnonnull` is enabled:
```
source/common/router/config_impl.cc:1395:31: error: null passed to a callee that requires a non-null argument [-Werror,-Wnonnull]
finalizePathHeader(headers, nullptr, insert_envoy_original_path);
^~~~~~~
source/common/router/config_impl.cc:1400:61: error: null passed to a callee that requires a non-null argument [-Werror,-Wnonnull]
return currentUrlPathAfterRewriteWithMatchedPath(headers, nullptr);
^~~~~~~
```
It's my understanding from reading the implementations of `finalizePathHeader` and `currentUrlPathAfterRewriteWithMatchedPath` that passing empty strings should have the same behavior.
Commit Message: build: fix `-Wnonnull` errors
Risk Level: Moderate
Testing: Unit tests & CI …
=> build: fix `-Wnonnull` errors

docs/root/start/sandboxes/gzip.rst, examples/gzip/gzip-envoy.yaml, examples/gzip/service.py, examples/gzip/verify.sh
Due to [quickfix of decompression oom](https://github.com/envoyproxy/envoy/commit/d4c39e635603e2f23e1e08ddecf5a5fb5a706338), `decompressed-size` will be truncated at around the size of file.gz * `MaxInflateRatio` . And we could not get fixed `decompressed-size` which is approximately 1130000. 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> examples: fix gzip decompression

source/extensions/filters/http/cache/cache_filter.cc
ENVOY_BUG should be used here as ENVOY_BUG no longer crashes when running code coverage.
Signed-off-by: Jiayu Wu <jiayu1.wu@intel.com>
Testing:
Docs Changes:
Release Notes:
=> CacheFilter: update cachefilter logs type

docs/root/version_history/current.rst, source/extensions/transport_sockets/tcp_stats/tcp_stats.cc, test/extensions/transport_sockets/tcp_stats/tcp_stats_test.cc
Fix cases when the running kernel has an older version of
`struct tcp_info` than the kernel headers Envoy was compiled with.
Backport of https://github.com/envoyproxy/envoy/pull/22433
Signed-off-by: Jonh Wendell <jonh.wendell@redhat.com>
=> tcp_stats: fix when kernel doesn't provide all stats

support/bootstrap
Currently bootstrap does not support paths with symlinks.
For example:
ln -s envoy/ envoy-symlink
cd envoy-symlink
support/bootstrap
ERROR: this script must be run at the root of the envoy source tree
$ echo $PWD
/envoy-symlink
$ echo "$(git rev-parse --show-toplevel)"
/envoy
Solution is to use pwd -P (physical: avoid all symlinks) instead of $PWD
$ echo "$(pwd -P)"
/envoy
Signed-off-by: Ruslan Mstoi <ruslan.mstoi@intel.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tools: bootstrap: add support for symlinks in pwd

envoy/upstream/thread_local_cluster.h, test/common/upstream/cluster_manager_impl_test.cc
Exposing the `drainConnections` method on the connection pool, so that [Nighthawk](https://github.com/envoyproxy/nighthawk) can correctly drain the connection pools used by its individual workers.
Fixes #22527.
Works on https://github.com/envoyproxy/nighthawk/issues/873.
/cc @alyssawilk 
Risk Level: low, existing functionality isn't affected.
Testing: unit tests.
Signed-off-by: Jakub Sobon <mumak@google.com>
=> upstream: Expose the `drainConnections` method on the connection pool.

source/common/http/http1/balsa_parser.cc, test/common/http/http1/codec_impl_test.cc
Also add test expectation for status.message().
Commit Message: Fix Http1ServerConnectionImplTest.Http11InvalidTrailerPost.
Testing: Http1ServerConnectionImplTest.Http11InvalidTrailerPost
=> [balsa] Fix Http1ServerConnectionImplTest.Http11InvalidTrailerPost.

envoy/http/filter.h, source/common/http/async_client_impl.h, source/common/http/filter_manager.cc, source/common/http/filter_manager.h, test/mocks/http/mocks.h
will be used to allow upstream filters to set downstream chunked encoding options.
Testing: n/a
part of https://github.com/envoyproxy/envoy/issues/10455
=> http: making http1StreamEncoderOptions a decoder function

docs/root/start/building/local_docker_build.rst
Fix #21899
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: Use `bazel.release.server_only` for building docker image

source/extensions/common/matcher/trie_matcher.cc, source/extensions/common/matcher/trie_matcher.h, source/extensions/extensions_metadata.yaml, test/extensions/common/matcher/trie_matcher_test.cc, tools/extensions/extensions_schema.yaml
Commit Message: matcher: fix missing HTTP support in IP matcher
Fixes #22336
=> matcher: fix missing HTTP support in IP matcher

source/extensions/clusters/redis/redis_cluster.h
The warning of ClangTidy is:
function
'Envoy::Extensions::Clusters::Redis::RedisCluster::RedisDiscoverySession::ipAddressFromClusterEntry'
has a definition with different parameter names
Signed-off-by: Wei Si <weisisea@google.com>
/assign @yanavlasov 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> redis: change parameter name of RedisDiscoverySession::ipAddressFromClusterEntry function to resolve ClangTidy warning.
