envoyproxy/envoy

- docs/root/api-docs/xds_protocol.rst
Clusters expect EDS response even if they do not change so EDS response is mandatory to finish warming. But listener use route configuration that Envoy is aware of and response is only needed for new routes. This PR clarifies that part in resource warming docs.
Commit Message:clarify resource warming docs in xds protocol
Additional Description:clarify resource warming docs in xds protocol
Risk Level:N/A
Testing:N/A
Docs Changes:N/A
Release Notes:N/A
> clarify resource warming docs in xds protocol

- changelogs/current.yaml
- source/server/connection_handler_impl.cc
- test/server/connection_handler_test.cc
Commit Message: connection handler: correct the handling of listener update
To balance the IPv4 mapped address request to IPv4-mapped IPv6 address listener, inserting a mapping item into `tcp_listener_map_by_address_` using IPv4 mapped address as the key.
There can be a chance to override the mapping with the same key(the IP address key). The override cases are:
1. a listener using the same IPv4 address with a listener which has the same IPv4 mapped address.
2. an update of IPv4 mapped address listener.
Currently, the override checks only allow the stopped listener can be overridden, since it prevents the IPv4 listener was override by the listener which has the same IPv4-mapped address. …
> connection handler: correct the handling of listener update

- source/common/network/connection_impl.h
- test/common/network/BUILD
- test/common/network/connection_impl_test.cc
Commit Message: https://github.com/envoyproxy/envoy/pull/22156 introduced ability to override SSL info. However, `ConnectionImpl` continued to use the original value instead of the new value. This aligns the info provider and `ssl()` method on `ConnectionImpl`.
Risk Level: low, nothing changes unless setSslConnectionInfo is used in a filter
Testing: unit
Fixes: https://github.com/envoyproxy/envoy/issues/22617
> connection: propagate set SSL info

- source/extensions/filters/http/gcp_authn/filter_config.cc
- source/extensions/filters/http/gcp_authn/gcp_authn_filter.h
- test/extensions/filters/http/gcp_authn/gcp_authn_filter_test.cc
- The `filter_config` shared_ptr should be created in main thread when we receive the config and add shared owner for each worker thread when we create the filter object. Also, update the filter's constructor accordingly.
- Small refactor on the test code: Initialize the config at constructor and update/override it later if needed
> Correct the shared_ptr pattern for filter config

- source/common/quic/platform/quiche_flags_impl.h
- test/common/quic/platform/quic_platform_test.cc
- test/common/quic/platform/quiche_test_impl.h
Signed-off-by: Renjie Tang <renjietang@google.com>
Commit Message: Address leftover comments from https://github.com/envoyproxy/envoy/pull/22588
Additional Description: With the recent quiche changes, I think we no longer need those empty impl functions. I removed them and we can add them back when needed.
Added unit tests for the new QUICHE protocol flags.
Testing: Unit tests.
> Add tests for Quiche protocol flags

- source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc
- source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.h
- test/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter_test.cc
Commit Message: this PR updates the  gRPC JSON transcoding API so that allows transcode the gRPC response status in other format. The details are:
- have another filter wrapping the JsonTranscoder filter object and intercept the response if it is gRPC error response
- JsonTranscoderConfig can be updated with additional proto info for the wrapping filter where JsonTranscoderConfig is also used
For more context, see https://github.com/envoyproxy/envoy/pull/22456. 
Risk Level:low
> Update Transcoding Lib API

- docs/root/version_history/current.rst
- source/server/connection_handler_impl.cc
- test/server/connection_handler_test.cc
Commit Message: connection handler: correct the handling of listener update
This is cherry-pick from https://github.com/envoyproxy/envoy/pull/22622
Testing: unittest added
Release Notes: an item for bug fixes added.
Fixes https://github.com/envoyproxy/envoy/issues/22449
> [backport][release/v1.22] connection handler: correct the handling of listener update

- tools/code_format/check_format.py
Commit Message: tools: Use `Union` instead of `|` for Python 3.9 support
Additional Description: 3.9 is the default installed on macOS, so this makes it a bit easier to run the script
Testing: Local
> tools: Use `Union` instead of `|` for Python 3.9 support

- test/extensions/filters/network/thrift_proxy/driver/generate_fixture.sh
Test failure only happen on Windows so let's give it a shot to see if it's an port retrying issue
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #21017
> Thrift: enable retrying fetch port in windows integration test

- .azure-pipelines/pipelines.yml
- ci/do_ci.sh
- tools/base/requirements.in
- tools/base/requirements.txt
- tools/project/BUILD
Fix #22560 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> repo: Add automated tagging/publishing

- envoy/server/access_log_config.h
- envoy/server/factory_context.h
- source/common/access_log/access_log_impl.cc
- source/common/access_log/access_log_impl.h
- source/extensions/access_loggers/file/config.cc
- source/extensions/access_loggers/file/config.h
- source/extensions/access_loggers/grpc/http_config.cc
- source/extensions/access_loggers/grpc/http_config.h
- source/extensions/access_loggers/grpc/tcp_config.cc
- source/extensions/access_loggers/grpc/tcp_config.h
- source/extensions/access_loggers/open_telemetry/config.cc
- source/extensions/access_loggers/open_telemetry/config.h
- source/extensions/access_loggers/stream/config.cc
- source/extensions/access_loggers/stream/config.h
- source/extensions/access_loggers/wasm/config.cc
- source/extensions/access_loggers/wasm/config.h
- test/common/access_log/access_log_impl_test.cc
- test/integration/BUILD
- test/integration/typed_metadata_integration_test.cc
- test/integration/typed_metadata_integration_test.proto
We have internal access loggers that need to get listener properties. This refactor adds creator methods for such access logger with a new factory context interface.
Risk Level: Low,
> access log: Add context interface with access to listener properties

- .azure-pipelines/bazel.yml
This should fix cache issue in non-RBE workers.
Fixes #22701.
> [v1.23] ci: disable non-RBE cache for release branches

- bazel/repository_locations.bzl
Commit Message: Bump com_google_cel_cpp release date to 2022-07-21
Additional Description: Noticed the following error in the pipeline ([link](https://dev.azure.com/cncf/envoy/_build/results?buildId=115138&view=logs&j=1c04237c-5f52-5959-5f83-5522b3556331&t=db3f3889-c922-566b-fa2e-4bc4948bc467)):
```
DependencyChecker ERROR ERRORS Summary [release_dates]:
--------------------------------------------------------------------------------
Mismatch: com_google_cel_cpp 2022-07-20 != 2022-07-21
```
Looks like the version was bumped in https://github.com/envoyproxy/envoy/pull/22315, and I noticed this on a separate PR after that was submitted.
Risk Level: Very low, just dev.
> deps: Bump com_google_cel_cpp release date to 2022-07-21

- tools/protodoc/BUILD
- tools/protodoc/generate_empty.py
- tools/protodoc/protodoc.py
- tools/protodoc/rst_filters.py
- tools/protodoc/templates/comment.rst.tpl
- tools/protodoc/templates/content.rst.tpl
- tools/protodoc/templates/contrib_message.rst.tpl
- tools/protodoc/templates/enum.rst.tpl
- tools/protodoc/templates/extension.rst.tpl
- tools/protodoc/templates/file.rst.tpl
- tools/protodoc/templates/header.rst.tpl
- tools/protodoc/templates/message.rst.tpl
- tools/protodoc/templates/security.rst.tpl
This shifts the rendering code from python into jinja templates.
The logic for parsing protodoc should not change much, but how we want to present it does so this separates the changeable code out, and should make it easier to update, it should also make the code easier to read/understand
This is a further step towards using templates (we use some already) and once it has landed we can look at moving further in this direction.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.m …
> protodoc: Use (more) templates for api build

- .azure-pipelines/bazel.yml
> [v1.22] ci: disable non-RBE cache for release branches

- bazel/BUILD
The old style will stop working in Bazel 6.0 (see https://github.com/bazelbuild/bazel/commit/3469784a4935c91b4ac22bcfed6be52e6dfec878)
Signed-off-by: Xùdōng Yáng <wyverald@gmail.com>
Commit Message: see above
Testing: CI
> bazel: switch to using new-style platform constraints

- tools/stack_decode.py
Commit Message: Improve stack_decode.py exit code if binary terminated by signal
Additional Description: Pythons subprocess returncode is negative if process terminated by signal, which leads to unexpected exit code if passed directly to sys.exit. For example sigkill leads to sys.exit(-9) which becomes 247 on unix as -9 signed int is cast to unsigned 8bit int. Bash and docker will convert the exit to 128 + signal int, e.g. 137 in the above example. Therefore follow that convention for more obvious exit codes.
Testing: N/A
> Improve stack_decode.py exit code if binary terminated by signal

- api/envoy/service/discovery/v3/discovery.proto
Added  a new metadata to Resources wrapper to unblock the possibility to carry more ad-hoc info, e.g. the trace data for each resources. 
Testing: 
Docs Changes:
> [API]xds: Add additional metadata field to Resource wrapper

- api/contrib/envoy/extensions/network/connection_balance/dlb/v3alpha/dlb.proto
- contrib/network/connection_balance/dlb/source/BUILD
- contrib/network/connection_balance/dlb/source/connection_balancer_impl.cc
- contrib/network/connection_balance/dlb/source/connection_balancer_impl.h
Commit Message: Support config dlb device id and auto-detect available device.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #22711
> dlb: support config devices

- .vscode/tasks.json
- tools/vscode/refresh_compdb.sh
Now refresh compilation database excludes contrib as default, so add it as an option.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> vscode: add target for contrib compdb

- contrib/all_contrib_extensions.bzl
This is going away in newer bazel versions
> bazel: replace bazel_tools//platforms use

- source/extensions/tracers/skywalking/skywalking_tracer_impl.cc
- source/extensions/tracers/skywalking/tracer.cc
- source/extensions/tracers/skywalking/tracer.h
- test/extensions/tracers/skywalking/tracer_test.cc
Commit Message: Add common tag name, to specify app protocol
Additional Description: #22594 Span of skywalking has a field called `spanLayer`, indicate it's http, rpc, db and so on. Currently this field is hardcoded to http as it's default value in ctor. Other telemetry impls may also have similar concept, so it's better introduce a common tag key,  to specify app protocol through `setTag`, to achieve protocol independent.
Why not add something like `setSpanLayer` to `Tracing::Span` interface:
\- Because, the parameter type varies and coupling with impl, e.g. `skywalking::v3::SpanLayer`. And there are impls without this concept, currently among tracers that envoy supported, only skywalking comes with this. On the other hand, opentelemetry comes with `kind` indicating it's server or …
> tracing: Add common tag name, to specify app protocol

- envoy/http/filter.h
- source/common/http/async_client_impl.cc
- source/common/http/async_client_impl.h
- source/common/http/conn_manager_impl.cc
- source/common/http/conn_manager_impl.h
- source/common/http/filter_manager.cc
- source/common/http/filter_manager.h
- test/common/http/filter_manager_test.cc
- test/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter_test.cc
- test/extensions/filters/http/wasm/wasm_filter_test.cc
- test/mocks/http/mocks.h
This allows the upstream filter chain to reset without losing details.
Testing: n/a
https://github.com/envoyproxy/envoy/issues/10455
> http: unifying reset APIs

- .bazelrc
This depends on https://github.com/envoyproxy/envoy-build-tools/pull/181
which currently requires some unknown fixes for windows.
> bazel: disable incompatible flag for now

- bazel/repository_locations.bzl
Commit Message: update BoringSSL to b9512430(5195)
Risk Level:
Testing:
Docs Changes:
Release Notes:
> tls: update BoringSSL to b9512430(5195)

- source/common/common/BUILD
- source/common/common/assert.h
- test/common/common/assert_test.cc
Signed-off-by: Alan Diaz <diazalan@google.com>
Commit Message: Added stacktrace to ENVOY_BUG
Additional Description: ENVOY_BUG will now capture a stack trace to log what was called before ENVOY_BUG. This will help provide additional context for errors
Testing: Expanded one of the unit tests to see if the stacktrace was logged and ran all other unit tests.
[Optional Fixes #Issue] N/A
[Optional Fixes commit #PR or SHA] N/A
[Optional Deprecated:] N/A
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):] N/A
> Added stacktrace to ENVOY_BUG

- test/extensions/filters/http/ext_proc/mutation_utils_test.cc
Signed-off-by: chaoqin-li1123 <chaoqinli@google.com>
Commit Message: add a test case to verify filter behavior
Risk Level: low, only testing
Testing:
Docs Changes:
Release Notes:
> [ext_proc]: verify that header entry removal is applied before header entry append

- examples/verify-common.sh
This might resolve a very infrequent CI bug in which docker doesnt
clean up containers before removing the network.
This relates to a very long-standing docker bug that never seems to
have been fully resolved.
cf https://github.com/moby/moby/issues/17217
Risk Level:
Testing:
Docs Changes:
Release Notes:
> examples: Add `--remove-orphans` when bringing down examples

- test/extensions/filters/http/common/fuzz/http_filter_fuzzer.h
- test/extensions/filters/http/common/fuzz/uber_filter.cc
- test/extensions/filters/http/common/fuzz/uber_filter.h
- test/extensions/filters/http/common/fuzz/uber_per_filter.cc
Commit Message: Make filter fuzz tester support filters that process off-thread
Additional Description: This is an alternative approach to #21757  
This option also makes the tester verify that filters complete their task - previously a filter could go into a "waiting" mode and stay there, and still pass the fuzz test.
Risk Level: Low (test-only)
Testing: n/a
Fixes Issue: #21726
> Make filter fuzz tester support filters that process off-thread

- test/integration/fake_upstream.cc
`//test/integration:tcp_proxy_odcds_integration_test` was observed to fail as follows:
```
==================== Test output for //test/integration:tcp_proxy_odcds_integration_test:
[==========] Running 24 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 24 tests from IpVersionsClientType/TcpProxyOdcdsIntegrationTest
[ RUN      ] IpVersionsClientType/TcpProxyOdcdsIntegrationTest.SingleTcpClient/0
[2022-08-25 20:22:46.750][3969][critical][assert] [test/integration/fake_upstream.cc:832] assert failure: !dispatcher_->isThreadSafe().
[2022-08-25 20:22:46.752][3969][critical][backtrace] [./source/server/backtrace.h:104] Caught Aborted, suspect faulting address 0x6b00000f81
[2022-08-25 20:22:46.752][3969][critical][backtrace] [./source/server/backtrace.h:91] …
```
> test: run fake upstream initialization from the dispatcher thread

- source/common/runtime/runtime_features.cc
- test/common/router/BUILD
- test/common/router/upstream_request_test.cc
- test/extensions/filters/http/buffer/buffer_filter_integration_test.cc
- test/per_file_coverage.sh
Temporarily disable by default upstream filters introduced in #22553
Risk Level: Low, disabled new feature
Fixes commit #22553
> Disable upstream filters by default

- docs/root/configuration/http/http_filters/lua_filter.rst
Commit Message: lua: clear outdated attention in lua filter docs
This attention is outdated after #21102.
Risk Level: Docs only.
Testing: n/a.
> lua: clear outdated attention in lua filter docs

- test/integration/tcp_tunneling_integration_test.cc
The HeaderEvaluatorConfigUpdate test needs to wait for a listener to be replaced. Its previous attempt to achieve that did not account for the intermediate warming state of new listeners, which could lead to the test continuing prematurely and failing.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> test: fix a race in tcp_tunneling_integration_test

- restarter/hot-restarter.py
Risk Level:
Testing: None (research how envoy is currently running on modern systems reveals people are using hacks like the package [python-is-python3](https://askubuntu.com/questions/1296790/python-is-python3-package-in-ubuntu-20-04-what-is-it-and-what-does-it-actually))
Docs Changes:
Release Notes:
As brought up in https://github.com/envoyproxy/envoy/issues/4552#issuecomment-1224654557 I've submitted a PR. Pinging @phlax as suggested.
Note that this MR *will* break envoy on Platforms that are still using …
> Execute hot-restarter using python3

- source/common/router/upstream_request.cc
- test/integration/protocol_integration_test.cc
Fixing a bug in upstream filters where the host was accessed before it was set (iff auto_rewrite was configured)
Part of https://github.com/envoyproxy/envoy/issues/10455
> http: fixing auto_rewrite for upstream filters

- test/integration/tcp_tunneling_integration_test.cc
Commit Message: follow-up to https://github.com/envoyproxy/envoy/pull/22802, wait for quic to receive STOP_SENDING before closing the connection.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> test: deflake quic test

- changelogs/current.yaml
- ci/do_ci.sh
- docs/root/configuration/http/http_filters/lua_filter.rst
- source/extensions/filters/http/lua/lua_filter.cc
- source/extensions/filters/http/lua/lua_filter.h
- test/extensions/filters/http/lua/lua_filter_test.cc
Commit Message: lua: support setting http call options by table
A new `httpCall` signature is added. We can set http call options by named key in options table.
To close both #14785 and #22173.
This PR is inherited from #14882. Thanks for all these great work of @dio.
Risk Level: Low. Only updates for lua filter.
Docs Changes: Added.
> lua: support setting http call options by table

- api/envoy/config/route/v3/route_components.proto
- source/common/router/router.cc
- test/common/router/router_test.cc
Commit Message: http: not buffering data for CONNECT when mirror polices are specified
Fixes #22736
> http: not buffering data for CONNECT when mirror polices are specified

- changelogs/current.yaml
- source/extensions/filters/http/cache/cache_filter.cc
- source/extensions/filters/http/cache/http_cache.h
- source/extensions/filters/http/cache/simple_http_cache/simple_http_cache.cc
- test/extensions/filters/http/cache/http_cache_implementation_test_common.cc
Commit Message: Add a completion callback to insertTrailers in cache_filter
Additional Description: Without this additional callback, an asynchronous cache implementation has no way to signal completion of an insert operation involving trailers. This also changes the cache test implementation to require that the completion callback has been called, before continuing to other parts of the test, where previously it would assume completion as soon as insertTrailers was called.
Risk Level: Low (change to a WIP filter)
Testing: Tests updated
Release Notes: added a completion callback to insertTrailers in cache interface. Any external cache implementation extensions will need to also add this callback, and call it on completion.
> Add a completion callback to insertTrailers in cache_filter

- source/common/upstream/upstream_impl.cc
- test/common/upstream/upstream_impl_test.cc
- test/config/utility.cc
- test/extensions/transport_sockets/http_11_proxy/connect_integration_test.cc
Fixing a bug where the proxy address was overridden by happy eyeballs addesses
testing HTTP/2 and ALPN for the inner TLS connection
Risk Level: low (config guarded)
Testing: new unit tests, integration
> connect: fixing a bug with virtual hosts / happy eyeballs and testing ALPN

- api/envoy/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto
Commit Message: fixing a typo in the docs (removing an extra `:` and adding a `.`)
Testing: built and confirmed the docs locally 
> docs: fix incorrect punctuation

- api/buf.lock
- api/buf.yaml
Commit Message: This updates the version of buf.build/googleapis/googleapis to the latest pushed version. The BSR had a change in the googleapis module to to concerns with the number of files in BSR, requiring previous commits to be removed. See https://docs.buf.build/faq#googleapis-failure for more details. This PR fixes the issue for envoy.
Testing:
Release Notes:
> api: update googleapis buf module version

- api/bazel/repository_locations.bzl
- api/bazel/repository_locations_utils.bzl
- bazel/repository_locations.bzl
- tools/docs/generate_external_deps_rst.py
Commit Message: docs: list dependencies' license
TODO:
- BoringSSL (FIPS): unknown repo
- liburing: dual license needs to be chosen by code owners
- skywalking-data-collect-protocol: license in README only
- zstd: dual license needs to be chosen by code owners
- wavm: version not found
- V8: unknown repo
- Chromium's trace event headers: license not found
- Common Expression Language (CEL) C++ library: version not found
- Kafka (server binary): unknown repo
- Intel Dlb: unknown repo
Testing: N/A
Partial fix for #22874
> docs: list dependencies' license

- source/common/router/router.cc
- test/common/router/router_test.cc
- test/extensions/filters/http/alternate_protocols_cache/BUILD
- test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc
the connect proxy code was originally only designed to work with explicit HTTP/1.1 upstreams.
It happened to work for auto_config with TCP, and this allows it to work with auto_config and TCP or QUIC.
Testing: new unit, integration tests
> http: making http11 connect proxy work with HTTP/3 auto_config

- api/envoy/admin/v3/clusters.proto
- source/server/admin/clusters_handler.cc
- test/server/admin/clusters_handler_test.cc
Commit Message: Expose eds_service_name as an optional string to the ClusterStatus proto, and adding populating logic.
Additional Description: The data is already available in the ClusterInfo class. ([getter function](https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/upstream_impl.h#L770); [data generation](https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/upstream_impl.cc#L997-L1002))
Docs Changes:
Release Notes:
[Optional Fixes #Issue] [22903](https://github.com/envoyproxy/envoy/issues/22903)
> api: expose eds_service_name to admin response of clusters

- .bazelrc
Commit Message: minor fix: include/envoy is moved to envoy/
Minor update to fix path error in the coverage build options.
Testing: n/a.
> minor fix: include/envoy is moved to envoy/

- source/common/upstream/health_checker_impl.cc
- source/common/upstream/health_checker_impl.h
- test/common/upstream/health_check_corpus/http_headers-with-proxy-connection-close
- test/common/upstream/health_check_fuzz.cc
Commit Message: fuzz: fix http health-check when connection is closed
The http health-check fuzzer only handled a case where a "proxy-connection:close" header key-value was passed, but should have handled cases where one of the values is close.
Risk Level: Low (fuzzer only)
Testing: Fixed fuzz test.
> fuzz: fix http health-check when connection is closed

- changelogs/current.yaml
- docs/root/configuration/http/http_filters/lua_filter.rst
- source/extensions/filters/http/lua/BUILD
- source/extensions/filters/http/lua/wrappers.cc
- source/extensions/filters/http/lua/wrappers.h
- test/extensions/filters/http/lua/lua_integration_test.cc
- test/extensions/filters/http/lua/wrappers_test.cc
:wave: 
Note:
This is a PoC PR to ensure the validity of the approach and the feasibility of the eventual upstream merge.
All the missing parts (docs, tests) will be added later if maintainers find the approach acceptable. 
This PR is somewhat complementary to https://github.com/envoyproxy/envoy/pull/18997/files and uses some machinery established in it.
Essentially, we'd need to be able to customize HTTP1 reason phrase based on the responses from `ext_authz` filter. 
Currently it's possible to override the code but the reason phrase (being HTTP1-specific) is set to the default value.
The approach in this PR adds a lua function to override reason phrase. It is done by injecting a stateful header formatter into the response headers map if it hasn't been set yet and setting the reason …
> http.lua: allow setting HTTP1 reason phrase

- test/integration/fake_upstream.h
Signed-off-by: Kateryna Nezdolii <nezdolik@spotify.com>
In logs for integration tests same log message is logged twice. As decoded grpc message can be quite large it spams logs a lot. Message is logged inside the call to `decodeGrpcFrame` and straight after the call to `decodeGrpcFrame`.  `message` data is not mutated inside `decodeGrpcFrame`, log content is identical.
Testing:
Docs Changes:
Release Notes:
> [test/integration] Remove duplicate log message

- bazel/envoy_test.bzl
I accidentally only added this flag to fuzz tests, this moves it to the private `_envoy_test_linkopts` function which is used by all test targets in this file.
2a3643ec5d90b6302b13196e21ce0df14fb99c92
> bazel: fix -no_deduplicate for test targets

- source/common/http/async_client_impl.h
- source/common/router/router.cc
- source/common/router/router.h
- test/integration/filters/add_body_filter.cc
- test/integration/shadow_policy_integration_test.cc
Fixing a bug where the router was not properly shut down for shadowing with upstream filters.
Fixing a second bug where headers were latched too late, and request headers were not isolated from shadow headers
Testing: new integration tests
Part of https://github.com/envoyproxy/envoy/issues/10455
> http: improving shadowing with upstream filters

- api/buf.lock
- api/buf.yaml
Backport of #23001
This updates the version of buf.build/googleapis/googleapis to the latest pushed version. The BSR had a change in the googleapis module to to concerns with the number of files in BSR, requiring previous commits to be removed. See https://docs.buf.build/faq#googleapis-failure for more details. This PR fixes the issue for envoy.
Signed-off-by: bufdev <bufdev-github@buf.build>
Signed-off-by: bufdev <bufdev-github@buf.build>
(cherry picked from commit 68758cef311f65e8813df6b7235ead660cd952f8)
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional …
> backport: api: update googleapis buf module version

- source/common/network/listen_socket_impl.h
No longer override socketType() in ConnectionSocketImpl
Risk Level:
Testing:
Docs Changes:
Release Notes:
> No longer override socketType() in ConnectionSocketImpl

- changelogs/current.yaml
- source/common/config/well_known_names.cc
- test/common/stats/tag_extractor_impl_test.cc
- test/integration/xfcc_integration_test.cc
stats: fix tag extraction for `worker_id` to avoid double counting
Default tag extraction rules were changed for `worker_id` extraction. Previously, `worker_` was removed from the original name during the extraction. This led to the same base stat name for both the per-worker and overall stat. For instance, in prometheus stats, the following stats were produced:
envoy_listener_downstream_cx_total{} 2
envoy_listener_downstream_cx_total{envoy_worker_id="0"} 1
envoy_listener_downstream_cx_total{envoy_worker_id="1"} 1
This resulted in ``sum(envoy_listener_downstream_cx_total)`` producing 4, even though there are only 2 connections.
The new behavior results in stats such as this:
envoy_listener_downstream_cx_total{} 2 …
> stats: fix tag extraction for `worker_id` to avoid double counting

- source/common/upstream/upstream_impl.cc
- test/extensions/transport_sockets/http_11_proxy/connect_integration_test.cc
As a follow-on to https://github.com/envoyproxy/envoy/pull/23002 make sure the proxy transport socket can be configured for auto_upstream with http/3
This changes the validation from "the transport socket is an HTTP/3 socket" to "the transport socket wraps an HTTP/3 socket" allowing the HTTP/3 socket to be wrapped in an http_11_proxy socket.  As previously tested, if a proxy address is present, we will force the request to be served over TCP, where the proxy code will be applied.
Testing: yes
> proxy: fix alpn proxy with HTTP3

- source/common/network/socket_impl.cc
- source/common/network/socket_option_factory.cc
- source/common/network/socket_option_impl.cc
- source/common/network/socket_option_impl.h
- test/integration/multiplexed_upstream_integration_test.cc
Make TCP_KEEPALIVE socket options only apply to TCP sockets
Fixes #22663
Testing: New integration tests
> Make TCP_KEEPALIVE socket options only apply to TCP sockets

- api/envoy/extensions/filters/http/compressor/v3/compressor.proto
- changelogs/current.yaml
- source/extensions/filters/http/compressor/compressor_filter.cc
- source/extensions/filters/http/compressor/compressor_filter.h
- test/extensions/filters/http/compressor/compressor_filter_test.cc
Signed-off-by: giantcroc [changran.wang@intel.com](mailto:changran.wang@intel.com)
As #21068, we need to add an option to let user not order to choose specific compressor when the q-values in `Accept-Encoding` are same.
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #21068
> compression: support choosing compressor first when the q-values are same

- bazel/googletest.patch
- bazel/repositories.bzl
This has landed upstream, but updating googletest proved harder than expected. This fixes https://github.com/envoyproxy/envoy/issues/22758 in the meantime.
> bazel: Add temporary patch for googletest

- docs/root/start/sandboxes/kafka.rst
- examples/kafka/docker-compose.yaml
- examples/kafka/envoy.yaml
- examples/kafka/verify.sh
Commit Message: Improve the example for the Kafka Broker filter
Additional Description: Makes the client traffic actually go through Envoy
Testing: README.md guideline
> Improve the example for the Kafka Broker filter

- source/extensions/filters/network/thrift_proxy/router/upstream_request.cc
- test/extensions/filters/network/thrift_proxy/router_test.cc
We've seen upstream connection is closed between response start and response end, which closes downstream connection and leads SR drop.
This disconnection is an intentional behavior from the service since thrift doesn't have a RST semantic.
In this diff, we do local reply to downstream instead of resetting it since we haven't sent any byte to downstream. 
Testing: unit
> Thrift: Do not reset downstream for partial response

- api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
Fix how the link to `envoy_v3_api_field_service.auth.v3.AttributeContext.HttpRequest.body` is rendered.
Commit Message: Fix how the link to `envoy_v3_api_field_service.auth.v3.AttributeContext.HttpRequest.body` is rendered.
Before:
After:
Testing: N/A
Docs Changes: This is a small docs change
> docs: Fix link to AttributeContext.HttpRequest.body

- source/extensions/transport_sockets/http_11_proxy/BUILD
- source/extensions/transport_sockets/http_11_proxy/connect.cc
- source/extensions/transport_sockets/http_11_proxy/connect.h
- test/extensions/transport_sockets/http_11_proxy/BUILD
- test/extensions/transport_sockets/http_11_proxy/connect_test.cc
When the proxy filter was implemented it did direct string checks to ensure a 200 response.  This addresses a TODO to accept any well formed 200 response.
Testing: new unit tests, integration tests
Part of https://github.com/envoyproxy/envoy-mobile/issues/1622
> http: Improving HTTP/1.1 proxy support

- source/extensions/filters/http/cache/simple_http_cache/simple_http_cache.cc
- source/extensions/filters/http/cache/simple_http_cache/simple_http_cache.h
- test/extensions/filters/http/cache/http_cache_implementation_test_common.cc
Commit Message: [cache] Make an aborted insert operation call the callback with false
Additional Description: The callback's parameter is currently only used in testing (though it could potentially be used to abandon an insert operation early); the previous implementation asserted that the insert callback was called with true, before checking that the insert did not in fact complete, which doesn't really make a lot of sense. The reasonable fixes were either to have the test ignore the callback's value and have it only check that the insert didn't actually happen, or validate that the return value correctly reflects an uncompleted insert operation, which involved also making simple_http_cache fulfill that expectation.
Risk Level: Very low (mostly test-only change to WIP extension)
Testing: …
> [cache] Make an aborted insert operation call the callback with false

- test/integration/http2_flood_integration_test.cc
This test sends a large number of metadata frames in order to trigger a disconnect. However, it was possible for the disconnect to happen and the connection to be torn down before all the metadata frames had been sent. If that happened, ASAN detected a UAF:
```
==95==ERROR: AddressSanitizer: heap-use-after-free on address 0x60700037e5a0 at pc 0x000004811f9e bp 0x7ffc903af990 sp 0x7ffc903af988
READ of size 8 at 0x60700037e5a0 thread T0
#0 0x4811f9d in Envoy::IntegrationCodecClient::sendMetadata(Envoy::Http::RequestEncoder&, Envoy::Http::MetadataMap) /proc/self/cwd/test/integration/http_integration.cc:168:3
#1 0x46ed711 in Envoy::Http2FloodMitigationTest_RequestMetadata_Test::TestBody() /proc/self/cwd/test/integration/http2_flood_integration_test.cc:1486:20
#2 0xd380e64 in void …
```
> test: fix a race in http2 flood integration test

- tools/api_proto_plugin/annotations.py
- tools/protoprint/protoprint.py
- tools/testdata/protoxform/envoy/v2/fully_qualified_names.proto
- tools/testdata/protoxform/envoy/v2/fully_qualified_names.proto.active_or_frozen.gold
https://github.com/envoyproxy/envoy/issues/23135 discussed some situations where the proto_format.sh tool normalizes the fully-qualified-name (FQN) of a field, when such normalization actually results in a build error from the compiler.
This PR introduces a new annotation, allow-fully-qualified-name, that can be used to annotate the comments of a field for which the proto_format.sh tool should permit a FQN to be used and not try to normalize the field type.
> tools: Enable FQN in proto fields through an annotation

- source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc
- source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.h
- test/extensions/filters/http/grpc_json_transcoder/BUILD
- test/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter_test.cc
- test/extensions/filters/http/grpc_json_transcoder/transcoder_async_inject_body_test.cc
- test/integration/filters/BUILD
- test/integration/filters/async_inject_body_at_end_stream_filter.cc
grpc_json_transcoder: bug fix to allow async continuation of trailers
We discovered a bug in the encoder path when gRPC JSON transcoder filter is chained with any other filter that does async continuation of trailers. See https://github.com/envoyproxy/envoy/issues/22064 for details.
Root cause: gRPC transcoder uses the `FilterManager` buffer to wait for a full response in the unary gRPC response path. But unfortunately Envoy does not correctly track which filter the buffered data belongs to (@KBaichoo can explain this). This results in the internal buffer being posted to `encodeData` for the wrong filter (i.e. filters before the transcoder in the encode path).
Fix: Modify the transcoder to not use `FilterManager` buffer. It now:
- Uses its own …
> grpc_json_transcoder: bug fix to allow async continuation of trailers

- source/extensions/filters/http/file_system_buffer/filter.cc
Commit Message: backport: c++: provide type to std::weak_ptr template 
Cherry-picked from [68aa00067bbeb7aaf13599f75e54e8837cfb13ef](https://github.com/envoyproxy/envoy/commit/68aa00067bbeb7aaf13599f75e54e8837cfb13ef). 
Signed-off-by: Christoph Pakulski <christoph@tetrate.io>
This is asked by: https://github.com/Homebrew/homebrew-core/pull/110883#discussion_r974679771.
Testing: Provided
Docs Changes: N/A 
> backport: c++: provide type to std::weak_ptr template 

- changelogs/current.yaml
- source/common/http/conn_manager_impl.cc
- source/common/http/conn_manager_impl.h
- test/integration/redirect_integration_test.cc
Previously, if performing an internal redirect on a drained connection, the HCM would checkForDrainedConnections and for HTTP/1.1 downstream, seeing no streams between the close and the recreate, would close the connection before serving the redirect.
> http: fixing a bug where internal redirects aren't served on drained connections

- source/common/router/config_impl.cc
Commit Message: use prefix_rewrite_ that has already been initialized directly. This avoids unnecessary function calls to route() and prefix_rewrite(). Follow-up PR for #23160
> route: Use `prefix_rewrite_` directly

- test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc
The `QUITRequestAndResponse` test could sometimes be seen to fail like this:
```
[ RUN      ] IpVersions/RedisProxyIntegrationTest.QUITRequestAndResponse/IPv6
test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc:606: Failure
Value of: redis_client->write(request)
Actual: false (Failed to complete write or unexpected disconnect. disconnected_: true bytes_drained: 14 bytes_expected: 14)
Expected: true
Stack trace:
0x28ab1de: Envoy::(anonymous namespace)::RedisProxyIntegrationTest::proxyResponseStep()
0x28ab05d: Envoy::(anonymous namespace)::RedisProxyIntegrationTest::simpleProxyResponse()
0x28aad6a: Envoy::(anonymous namespace)::RedisProxyIntegrationTest_QUITRequestAndResponse_Test::TestBody()
0x695f34b: testing::internal::HandleSehExceptionsInMethodIfSupported<>() …
```
> redis: fix flake in QUIT test

- docs/root/configuration/listeners/network_filters/wasm_filter.rst
- docs/root/configuration/other_features/wasm_service.rst
- examples/wasm-cc/envoy.yaml
`vm_config.runtime` is currently optional. This PR updates the config examples to remove the wasm runtime defaults.
Signed-off-by: Jiayu Wu <jiayu1.wu@intel.com>
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #21749
> remove default wasm runtime in the config examples

- docs/root/configuration/http/http_filters/oauth2_filter.rst
- test/extensions/filters/http/oauth2/config_test.cc
- test/extensions/filters/http/oauth2/oauth_integration_test.cc
`redirect_uri` should not be `"%REQ(:x-forwarded-proto)%://%REQ(:authority)%/callback"` in the files below:
* `test/extensions/filters/http/oauth2/config_test.cc`
* `test/extensions/filters/http/oauth2/oauth_integration_test.cc`
Signed-off-by: Mohamed Bana <mohamed@bana.io>
> `envoy.filters.http.oauth2`: Change to `%REQ(x-forwarded-proto)%`

- source/extensions/filters/udp/dns_filter/dns_filter.cc
max_pending_lookups_ is uninitialized by some branches, but it
unconditionally passed into DnsFilterResolver on the line 254.
It's UB in C++.
> Initialize max_pending_lookups_ without client_config

- docs/root/configuration/best_practices/_include/edge.yaml
doc fix about the listener filter order in best practice example
Proxy protocol listener filter should be ahead of tls_inspector listener filter. See this issue for more context: https://github.com/envoyproxy/envoy/issues/23205 
Risk Level:
Low
Testing:
Manual testing with envoy 1.22.2
Docs Changes:
yes
> docs: fix listener filter order in best practice envoy config 

- test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc
A few async certificate validation tests want to make assertions while async validation is pending. If the vagaries of scheduling caused async validation to finish before the test code finished running, the test would fail.
To reduce the chance of this flakiness, increase the time the fake "timed" certificate validator waits before validating the certificate. This mitigation is inspired by [similar code in the QUIC integration tests](https://github.com/envoyproxy/envoy/blob/deded6dcf86b2762ab885af88e0e3ae3f27eee7b/test/integration/quic_http_integration_test.cc#L1084-L1091).
Also, modify some loops in tests so that they do not loop forever if the handshake state machine advances past the state they are waiting for. …
> tls: reduce flakiness of ssl_integration_test

- source/extensions/filters/listener/tls_inspector/tls_inspector.cc
- source/extensions/filters/listener/tls_inspector/tls_inspector.h
- test/extensions/filters/listener/tls_inspector/tls_inspector_integration_test.cc
Commit Message:Cleanup for TLS inspector. 
1) Avoid making share ptr copy
2) Use std algo vs loop
3) Make member const since it's only read after init
Risk Level:low
> Minor cleanup for TLS inspector filter.

- test/extensions/filters/network/thrift_proxy/conn_manager_test.cc
`close_downstream_on_upstream_error` is not a reloadable feature but a field only.
> Thrift: remove non-exsisting reloadable feature in test

- api/envoy/api/v2/route/route_components.proto
…ATIC clusters, provided that the hostname attribute of teh endpoint is configured.
Commit Message: Update documentation to indicate that auto_host_rewrite works with STATIC clusters, provided that the hostname attribute of the endpoint is configured.
Additional Description: Current documentation indicates that the auto_host_rewrite feature does not work with STATIC clusters. However, if the hostname attribute of the endpoints is configured, it works and sets the authority to the string configured at the hostname of the endpoint. 
Relates to issues https://github.com/envoyproxy/envoy/issues/23131
Docs Changes: Update documentation to indicate that auto_host_rewrite works with STATIC clusters, provided that the hostname attribute of the endpoint is …
> doc: auto_host_rewrite works with STATIC clusters if hostname is provided

- test/common/http/http1/codec_impl_test.cc
Update Http1ServerConnectionImplTest.Utf8Path to reflect that BalsaParser always signals error on UTF8 path.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Upgrade Http1ServerConnectionImplTest.Utf8Path/BalsaParser.

- api/envoy/extensions/filters/network/thrift_proxy/filters/header_to_metadata/v3/header_to_metadata.proto
Fix thrift header_to_metadata proto annotation
(a) As we can see in the following test, empty value will copy the header value to metadata.
https://github.com/envoyproxy/envoy/blob/6bba2d69a17e4cf374eb09f7f51fbf0f0ce4b7da/test/extensions/filters/network/thrift_proxy/filters/header_to_metadata/header_to_metadata_filter_test.cc#L68
(b) Fail to set value for on_missing will throw instead of not setting metadata
https://github.com/envoyproxy/envoy/blob/6bba2d69a17e4cf374eb09f7f51fbf0f0ce4b7da/source/extensions/filters/network/thrift_proxy/filters/header_to_metadata/header_to_metadata_filter.cc#L41
(c) `oneof` in proto guarantee no value is set when we have regex
> Thrift: fix header_to_metadata proto annotation

- api/contrib/envoy/extensions/filters/network/generic_proxy/action/v3/action.proto
- contrib/generic_proxy/filters/network/source/interface/filter.h
- contrib/generic_proxy/filters/network/source/proxy.cc
- contrib/generic_proxy/filters/network/source/proxy.h
- contrib/generic_proxy/filters/network/test/mocks/filter.cc
- contrib/generic_proxy/filters/network/test/mocks/filter.h
- contrib/generic_proxy/filters/network/test/proxy_test.cc
Commit Message: generic proxy: make the l7 filter could be configured repeatedly
Add a new `perFilterConfig` API to the `StreamFilterCallbacks` of generic proxy. This API will get route level filter config from the route entry by the filter config name.
It's similar to #21525.
**I think there is no third-party L7 filter for generic proxy for now. So, this change won't break anything.**
Testing: Unit.
> generic proxy: provides per filter config API to L7 filters to get route level config by the filter config name

- bazel/external/quiche.BUILD
Signed-off-by: Martin Duke <martinduke@google.com>
Commit Message: compile libraries for QUICHE load balancer interactions
Additional Description: See draft-ietf-quic-load-balancers
Testing: bazel build completes successfully
> quiche: add build targets for load_balancer libraries

- .bazelrc
- bazel/v8.patch
Commit Message: This applies changes from https://chromium-review.googlesource.com/c/v8/v8/+/3700352 as a fix for `MemoryAllocator::PartialFreeMemory()` which shouldn't try to change permissions of RWX pages.
This mainly affects macOS > 11.2 due to `mprotect()` behavior changes (https://github.com/envoyproxy/envoy/issues/23243, https://chromium-review.googlesource.com/c/v8/v8/+/3610445/comment/6294ada3_a3cab643/) on Apple silicon.
This also flips the Wasm feature to be enabled by default on macOS.
The future patch removal task is tracked in https://github.com/envoyproxy/envoy/issues/23258.
Additional description:
By applying this patch on my local (macOS, 12.6 (21G115), M1), I can run `envoy` to load a `.wasm` from the `examples/wasm-cc`. …
> macOS: Enable wasm and allow to load .wasm on Apple silicon

- api/envoy/config/route/v3/route.proto
- envoy/http/filter.h
- envoy/router/router.h
- source/common/http/async_client_impl.h
- source/common/router/config_impl.cc
- source/common/router/config_impl.h
- test/common/router/config_impl_test.cc
- test/mocks/router/mocks.h
Commit Message: Add Top RouteConfiguration level per-filter-config
Docs Changes: 
Release Notes:
[Optional Fixes #Issue] #17662
> [RDS] Add Top RouteConfiguration level per-filter-config

- source/extensions/access_loggers/open_telemetry/grpc_access_log_impl.cc
- source/extensions/access_loggers/open_telemetry/grpc_access_log_impl.h
- test/extensions/access_loggers/open_telemetry/access_log_integration_test.cc
- test/extensions/access_loggers/open_telemetry/grpc_access_log_impl_test.cc
OpenTelemetry introduced a rename of `instrumentation_library_logs` field to
`scope_logs`, while keeping the protobuf field number (2). The
`intrumentation_library_logs` field was readded though with different number
(1000) for compatibility reasons. As an effect, Envoy code using
`instrumentation_library_logs` continued to compile, but with change in wire
format (emitting field with number 1000 instead of 2). This commit fixes that
by using `scope_logs` field (with number 2).
See #23234
Note: this PR is submitted to a release branch, as main is already fixed by #22694.
Risk Level:
not sure
Testing:
Unit tests adjusted.
Docs Changes:
n/a
Release Notes:
fixed OpenTelemetry access logger wire format, bringing it back to the same behaviour as with …
>  access_log/opentelemetry: stop emitting deprecated fields

- api/envoy/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto
- changelogs/current.yaml
- source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc
- source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.h
- test/extensions/filters/http/grpc_json_transcoder/grpc_json_transcoder_integration_test.cc
Commit Message: updated `grpc-httpjson-transcoding` to include the newlin-delimited streaming option.
Additional Description: this PR pulls in the work in [this upstream PR](https://github.com/grpc-ecosystem/grpc-httpjson-transcoding/pull/73) that is required to enable newline-delimited streaming for transcoded gRPC streams.
Testing: Integration Tests
Docs Changes: documentation is inline in `transcoder.proto`
Release Notes: Add newline-delimited streaming option for gRPC JSON transcoder.
> grpc_json_transcoder: add newline-delimited streaming option

- api/envoy/config/core/v3/protocol.proto
- changelogs/current.yaml
- envoy/http/http_server_properties_cache.h
- source/common/http/http_server_properties_cache_impl.cc
- source/common/http/http_server_properties_cache_impl.h
- source/common/http/http_server_properties_cache_manager_impl.cc
- test/common/http/conn_pool_grid_test.cc
- test/common/http/http_server_properties_cache_impl_test.cc
- test/common/http/http_server_properties_cache_manager_test.cc
Add a "canonical suffix" list to the Alt-Svc cache so that Alt-Svc entries can be shared across origins which share the same hostname suffix.
Testing: New unit tests
Docs Changes: Update proto docs
> upstream: Add support for sharing alt-svc entries between hosts.

- .bazelrc
- bazel/v8.patch
Commit Message: This applies https://chromium-review.googlesource.com/c/v8/v8/+/3700352 as a fix for MemoryAllocator::PartialFreeMemory() which shouldn't try to change permissions of RWX pages.
This mainly affects macOS > 11.2 due to mprotect behavior changes (#23243) on Apple silicon.
This is cherry-picked from: https://github.com/envoyproxy/envoy/commit/63f27a6b6de0b2172f4721c31c69a050713c4c56
Platform Specific Features: macOS
> backport: macOS: Allow to load .wasm on Apple silicon

- tools/extensions/extensions_schema.yaml
Commit Message: extensions: add category envoy.tls_handshakers.
`HandshakerFactory` at [envoy/ssl/handshaker.h](https://github.com/envoyproxy/envoy/blob/main/envoy/ssl/handshaker.h#L130) specifies extension category `envoy.tls_handshakers`, but it's missing from the extensions schema. Add it so that we can specify extensions in that category.
> extensions_schema: add category envoy.tls_handshakers.

- test/integration/base_integration_test.cc
- test/integration/base_integration_test.h
- test/integration/server.cc
- test/integration/server.h
Prior to this commit, the test integration server was created with an OptionsImpl that contains hard-coded default cluster, node, and zone values. Since the non-empty values in Options overwrites the node metadata in Bootstrap, this meant that the integration test server always used the same hard-coded metadata without being able to override it.
This commit introduces a new knob to BaseIntegrationTest: `use_bootstrap_node_metadata_`. If set to true, the node metadata from the Bootstrap config's `node` field will be used by Envoy instead of the OptionsImpl overrides. This enables Envoy tests to use node metadata specified in the Bootstrap config, which is necessary for some integration tests being written for Envoy Mobile.
> test: Add option to use node metadata in Bootstrap config

- changelogs/current.yaml
- source/extensions/transport_sockets/tls/cert_validator/default_validator.cc
- test/extensions/transport_sockets/tls/cert_validator/default_validator_test.cc
- test/extensions/transport_sockets/tls/ssl_socket_test.cc
This PR is a preparatory fix for PR #23320.
The intent was to upload a pair of dependent PRs. I've made them into separate PRs because it looked like you all prefer one commit per PR (since PR descriptions ask for a commit message), and it seemed worth keeping the changes ultimately separate. Let me know if this isn't the preferred workflow.
---
This fixes a bug in the pre-tls_async_cert_validation codepath. The tls_async_cert_validation codepath is unaffected.
Per both OpenSSL and BoringSSL documentation, if you use SSL_CTX_set_cert_verify_callback, the library expects to find the error code in X509_STORE_CTX. This error determines the TLS alert. X509_verify_cert does this for you, but Envoy's callback was not doing this when doSynchronousVerifyCertChain runs the extra …
> tls: fix error-reporting in doSynchronousVerifyCertChain

- bazel/get_workspace_status
Signed-off-by: Will Martin <will@engflow.com>
This change adds the BUILD_SCM_REMOTE and BUILD_SCM_BRANCH variables to those reported by Bazel. This will allow downstream consumers of the BEP within the CI system to include information regarding the repository and branch that a build was triggered from.
Specifically, this adds repository and branch to the [EngFlow UI][1] for envoy-mobile but may be used by any BEP consumer.
[1]: https://envoy.cluster.engflow.com/
> ci: Add branch and remote to Bazel get_workspace_status

- source/common/quic/platform/quiche_flags_impl.cc
- source/common/quic/platform/quiche_flags_impl.h
- source/common/runtime/runtime_features.cc
- test/common/quic/platform/quic_platform_test.cc
- test/common/runtime/runtime_impl_test.cc
- test/integration/quic_http_integration_test.cc
Since Envoy is only one embedder of the QUICHE library, this will help reduce conflicts if a project has multiple dependencies on QUICHE.
Commit Message: Prepends 'envoy' to the names of QUICHE flags within QUICHE platform.
Testing: ran all tests locally
Docs Changes:
Release Notes:
> Prepends 'envoy_' to the names of QUICHE flags within QUICHE platform.

- test/extensions/internal_redirect/redirect_extension_integration_test.cc
- test/integration/base_integration_test.cc
- test/integration/filter_integration_test.cc
- test/integration/multiplexed_integration_test.cc
- test/integration/protocol_integration_test.cc
- test/integration/redirect_integration_test.cc
- test/integration/upstream_filter_state_integration_test.cc
the test access log function doesn't truncate logs.  Fixing this.
And also removing the trailing \n (which requires test fix ups and I can revert this part if it feels too toily)
> test: fixing access log function

- contrib/cryptomb/private_key_providers/test/BUILD
- contrib/qat/private_key_providers/test/BUILD
Commit Message: Make bazel only run QAT and cryptomb private key provider tests on `linux_x86_64` platform.
The QAT and cryptomb private key provider features are hardware dependent, but the tests use mock libraries which can run on other platforms. This pull request changes the tests to only run on the `linux_x86_64` platform.
Testing: Manual testing
Platform Specific Features: Change unit tests to only run on `linux_x86_64`
> contrib: make qat and cryptomb unit tests only run on specific platform

- bazel/README.md
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docs: fix confusing statements

- source/extensions/common/wasm/context.cc
- source/extensions/common/wasm/context.h
- test/extensions/common/wasm/test_data/test_context_cpp.cc
- test/extensions/common/wasm/wasm_test.cc
fix #23047 
Testing:
Docs Changes:
Release Notes:
> fix sendLocalResponse in wasm

- api/envoy/config/core/v3/address.proto
- api/envoy/config/core/v3/socket_option.proto
- api/envoy/config/listener/v3/listener.proto
Commit Message: api: add socket_options for multiple addresses
Since the ipv4 and ipv6 have different socket option flags, when using multiple addresses, the user has to specify different socket options for the ipv4 address and the ipv6 address.
For the listener, the additional address can be the Ipv6 address, then it should be able to set an Ipv6 flag corresponding to the ipv4 one. Add socket_option field for each additional address.
For the upstream, the endpoint can be ipv4 or ipv6, currently, the user can specify the ipv4 and ipv6 local bind address in the bind config, but there is only a global socket_options that apply to both the ipv4 and ipv6 addresses. Add socket_options for each extra source address. …
> api: add socket_options for multiple addresses

- source/common/config/grpc_mux_impl.cc
Commit Message: Improve logging while resuming xds to indicate clearly when it is actually resuming the xds 
Testing:
Docs Changes:
Release Notes:
> Improve logs for resuming xds

- changelogs/current.yaml
- source/extensions/filters/network/thrift_proxy/conn_manager.cc
Filters could change cluster_header's value, which affect the routing decision.
Therefore, we need to apply filter chain before the routing decision is made and cached.
Testing: unit
> Thrift: Defer route cache after apply applyDecoderFilters

- contrib/config/test/kv_store_xds_delegate_integration_test.cc
- envoy/config/xds_resources_delegate.h
- source/common/config/decoded_resource_impl.h
- source/common/config/grpc_mux_impl.cc
- source/common/config/subscription_factory_impl.cc
- source/common/config/xds_mux/BUILD
- source/common/config/xds_mux/delta_subscription_state.h
- source/common/config/xds_mux/grpc_mux_impl.cc
- source/common/config/xds_mux/grpc_mux_impl.h
- source/common/config/xds_mux/sotw_subscription_state.cc
- source/common/config/xds_mux/sotw_subscription_state.h
- source/common/config/xds_mux/subscription_state.h
- source/common/upstream/cluster_manager_impl.cc
- test/common/config/decoded_resource_impl_test.cc
- test/common/config/sotw_subscription_state_test.cc
- test/integration/xds_delegate_extension_integration_test.cc
https://github.com/envoyproxy/envoy/pull/22473 and https://github.com/envoyproxy/envoy/pull/22921 added support for the xDS resources delegate in the gRPC Sotw mux. This PR adds support for the xDS resources delegate feature to the unified gRPC Sotw implementation, which is intended to be the default implementation in the future.
> xds: Add xDS delegate feature support to the unified mux

- source/extensions/filters/http/ext_authz/ext_authz.h
Commit Message: Change ext_authz Filter logger id
Additional Description: -
Testing: Tested build locally and confirmed by running this command
```
./bazel-bin/source/exe/envoy-static -c /mnt/disks/envoy-project/examples/ext_authz.yaml --component-log-level ext_authz:trace
```
generated logs:
```
[2022-10-12 12:45:56.310][103024][trace][ext_authz] [source/extensions/filters/http/ext_authz/ext_authz.cc:73] [C0][S14765918889036524211] ext_authz filter calling authorization server
[2022-10-12 12:45:56.315][103024][trace][ext_authz] [source/extensions/filters/http/ext_authz/ext_authz.cc:417] [C0][S14765918889036524211] ext_authz filter rejected the request with an error. Response status code: 403
``` …
> Change ext_auth logger id

- source/server/server.h
Commit Message: Ensure that SSL context manager outlives the dispatcher during shutdown. ClusterInfo deletion is posted on the dispatcher and it references SSL socket factory shared pointers, which remove themselves from the SSL context manager on destruction.
Risk Level: low, SSL manager is a fairly dumb container of objects
Testing: TODO
Fixes: https://github.com/envoyproxy/envoy/issues/21447
> ssl: extend SSL manager lifetime beyond the dispatcher

- source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc
msan triggers use of uninitialized value in the GrpcJsonTranscoderFilterTest.ResponseBodyExceedsBufferLimit test when a new slice with size == 0 is added to the buffer. Trigger point is just passing uninitialized value to the add() call. With size == 0 the add() call is a no-op.
> Fix msan failure in the GrpcJsonTranscoderFilterTest.ResponseBodyExceedsBufferLimit

- source/extensions/common/dubbo/BUILD
- source/extensions/common/dubbo/message_impl.cc
- source/extensions/common/dubbo/message_impl.h
- source/extensions/common/dubbo/metadata.h
- test/extensions/common/dubbo/message_test.cc
Commit Message: dubbo codec: remove Http HeaderMap in the dubbo message
In the original implementation of dubbo proxy, `Http::HeaderMap` is used to store a copy of dubbo attachments. By this way, we can reuse `HeaderMatcher`-related functions/classes. It's not necessary for now because the unified matcher API will be used.
And the key of `Http::HeaderMap` is case-insensitive and only string value could be stored in. So, we must use a `Hessian2::Object::UntypedMap` to store complete attachments. It would bring some additional overhead.
This PR removed `Http::HeaderMap` from our new dubbo codec.
Testing: n/a.
> dubbo codec: remove Http HeaderMap in the dubbo message

- envoy/network/filter.h
- envoy/tcp/upstream.h
- source/common/network/filter_manager_impl.cc
- source/common/network/filter_manager_impl.h
- source/common/tcp_proxy/tcp_proxy.cc
- source/common/tcp_proxy/tcp_proxy.h
- source/common/tcp_proxy/upstream.cc
- source/common/tcp_proxy/upstream.h
- source/server/api_listener_impl.h
- test/common/network/filter_manager_impl_test.cc
- test/common/tcp_proxy/tcp_proxy_test.cc
- test/extensions/transport_sockets/starttls/upstream_starttls_integration_test.cc
- test/mocks/network/mocks.h
filter manager: ability to convert upstream Starttls to secure mode
This PR provides a signalling path from a downstream read filter to a terminal filter in order to convert StartTLS upstream transport socket from non-secure mode to secure mode. StartTLS transport socket is basically a wrapper around raw (cleartext socket) and TLS socket. StartTLS transport socket always starts in cleartext and in order to convert it to secure mode, `startSecureTransport` method must be called. The main use of StartTLS transport socket is implementation of Opportunistic TLS protocol, where the first few messages are exchanged in cleartext and then TLS handshake is done on the same TCP session. The first few cleartext messages are protocol specific. Postgres messages …
> filter manager: ability to convert upstream Starttls to secure mode

- contrib/config/source/kv_store_xds_delegate.cc
- contrib/config/source/kv_store_xds_delegate.h
- contrib/config/test/kv_store_xds_delegate_test.cc
- envoy/config/xds_resources_delegate.h
- source/common/config/grpc_mux_impl.cc
- source/common/config/grpc_mux_impl.h
- source/common/config/xds_mux/sotw_subscription_state.cc
- test/common/config/BUILD
- test/common/config/sotw_subscription_state_test.cc
- test/integration/xds_delegate_extension_integration_test.cc
The resource names requested in the `getResources` function should take a set of unique elements, so this commit changes the the `getResources` interface to take a `absl::flat_hash_set` for the resource names instead of a `std::vector`.
Risk Level: low (hidden, as-of-yet unused API)
Testing: existing unit & integration test coverage
> xds: change XdsResourcesDelegate::getResources to take a set

- source/common/http/conn_manager_impl.cc
- source/common/http/conn_manager_impl.h
- test/integration/protocol_integration_test.cc
Fixes an issue where route spans were not performed correctly when HCM config was absent. Now if HCM is not configured, the egress config defaults will again be used.
Fixes commit #22987
> tracing: fixing a regression in router initiated spans

- source/common/json/json_internal.cc
- source/common/router/header_parser_utils.cc
- test/common/router/header_formatter_test.cc
- tools/code_format/config.yaml
use re2 for header formatter utilities.
This PR addresses @jmarantz comment [about performance](https://github.com/envoyproxy/envoy/pull/21932#discussion_r988278306)
Testing: Added few unit test cases, but functionality should be identical as before
> router: use re2 for header formatter utilities.

- envoy/http/codec.h
- source/common/http/conn_manager_impl.cc
- source/common/http/http1/codec_impl.h
- source/common/http/http2/codec_impl.h
- source/common/quic/envoy_quic_stream.h
- test/integration/buffer_accounting_integration_test.cc
- test/mocks/http/stream.h
Fix memory leak with stream recreated when watermark buffer tracking enabled.
Do not create a new memory account for the recreated stream in ConnectionManagerImpl::ActiveStream::recreateStream.
Re-use an account from the old stream.
Testing: integration
> http conn man: fix memory leak with watermark buffer

- source/common/http/http2/codec_impl.cc
Commit Message: Adds a debug log message to the HTTP/2 codec.
Testing:
Docs Changes:
Release Notes:
> Adds a debug log to help diagnose an issue.

- docs/root/intro/arch_overview/http/http3.rst
Signed-off-by: Adam Anderson <6754028+AdamEAnderson@users.noreply.github.com>
Commit Message: Fix broken link in HTTP3 arch overview
Additional Description: QUIC error code reference link broken by remote repo renames, fixed
Risk Level: Minimal
Testing: Click the link, it works
Docs Changes: That's all this is
Release Notes: Fix broken link in HTTP3 arch overview
> Docs: Fix broken link in HTTP3 arch overview

- .azure-pipelines/pipelines.yml
- ci/publish_github_assets.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [BACKPORT/v1.23] ci: Add/publish release artefacts (#23246)

- docs/root/faq/debugging/why_is_my_route_not_found.rst
Commit Message: doc: fix FAQ doc for route match
Testing: n/a
Docs Changes: faq doc
Related to the issue #23416
> doc: fix FAQ doc for route match

- source/server/admin/admin.cc
- source/server/admin/stats_handler.cc
- test/server/admin/admin_test.cc
Commit Message: In https://github.com/envoyproxy/envoy/pull/21058 the default regex engine used for admin `/stats?filter=` was changed from std::regex (ecmascript) to Google re2. However the prompt in the admin HTML launch page was not flipped accordingly. This PR fixes that..
Testing: just CI
> change regex UI prompt to say 'Google re2' rather than ecmascript in the description

- source/extensions/extensions_metadata.yaml
Change the status of internal listener related extensions from wip to stable.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Change the status of internal listener related extensions to alpha

- api/envoy/config/core/v3/base.proto
Commit Message: api: add attention to HeaderValueOption.append to avoid removing this field
See #22845.
Testing: n/a.
Docs Changes: added.
> api: add attention to HeaderValueOption.append to avoid removing this field

- contrib/network/connection_balance/dlb/source/connection_balancer_impl.cc
- contrib/network/connection_balance/dlb/source/connection_balancer_impl.h
- contrib/network/connection_balance/dlb/test/BUILD
- contrib/network/connection_balance/dlb/test/config_test.cc
The default of type uint32 in protobuf is 0, so the `else` field can not run into.
Fix the above issue and add tests to cover some cases.
DLB mock functions are in development, so only test the config logic for now.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> dlb: optimize auto detect logic

- api/envoy/type/matcher/v3/regex.proto
- test/common/router/route_corpus/clusterfuzz-testcase-minimized-route_fuzz_test-4718246398132224.fuzz
It is observed that Envoy crash in ASSERT() due to regex rewrite path string contains invalid character '\r'.
We should prohibit null characters \0, \r, \n in the regex rewrite substitution string.   This is well guarded in most other cases like RouteAction:prefix_rewrite, but is missing in RouteAction:regex_rewrite:substitution.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Envoy ASSERT() due to regex rewrite path string contains \r

- envoy/upstream/upstream.h
- source/common/conn_pool/conn_pool_base.cc
- source/common/upstream/health_discovery_service.cc
- source/common/upstream/load_balancer_impl.cc
- source/common/upstream/upstream_impl.cc
- source/common/upstream/upstream_impl.h
- source/extensions/clusters/dynamic_forward_proxy/cluster.cc
- source/extensions/clusters/redis/redis_cluster.cc
- source/extensions/clusters/redis/redis_cluster_lb.cc
- source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc
- source/server/admin/config_dump_handler.cc
- test/common/conn_pool/conn_pool_base_test.cc
- test/common/upstream/eds_test.cc
- test/common/upstream/health_checker_impl_test.cc
- test/common/upstream/load_balancer_fuzz_base.cc
- test/common/upstream/load_balancer_impl_test.cc
- test/common/upstream/maglev_lb_test.cc
- test/common/upstream/ring_hash_lb_test.cc
- test/common/upstream/subset_lb_test.cc
- test/common/upstream/upstream_impl_test.cc
- test/common/upstream/utility.h
- test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc
- test/mocks/upstream/host.h
- test/server/admin/config_dump_handler_test.cc
Commit Message: upstream: new healthStatus method to provide more detailed host health status
Part of work to fix #23213.
Because the canonical `health()` method is used widely and is enough for most of cases. We can treat it as abbreviated status. So, we won't update the `health()` directly.
This PR added a new `healthStatus()` method to the host to provide more specific health status (with type of EDS `envoy::config::core::v3::HealthStatus`). 
**This status is hybrid of EDS status and runtime active status (from active health checker or outlier detection). Runtime active status will be taken as a priority.**
This is simplest implementation for this feature. 
Risk Level: none. not change any exist code but add …
> upstream: new healthStatus method to provide more detailed host health status

- docs/root/intro/arch_overview/other_protocols/redis.rst
Signed-off-by: Brian P O'Rourke <brian@orourke.io>
Commit Message: Correct command name in Redis docs
Additional Description: s/MUTLI/MULTI/
Testing: Docs only
Docs Changes: Docs only
Release Notes:
> docs: correct spelling of multi

- OWNERS.md
Signed-off-by: Kirtimaan <krajshiva@google.com>
Commit Message:Add Robert Femmer from X41 to setec for working on Fuzzers
Additional Description: Robert Femmer is new X41 team member to work on cleaning up fuzz issues
> Request to add Robert Femmer to setec from X41 to work on Fuzz issues

- changelogs/current.yaml
- source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc
- source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.h
- test/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter_test.cc
To fix: https://github.com/envoyproxy/envoy/issues/16629
When using http2, and request body has google.api.HttpBody, the size is < 16KB, it will cause EOF.
Testing:  unit-tested
Docs Changes:
[
> grpc_transcoder: fix a bug with http2 when request body is Http.Body

- source/server/server.cc
Currently we set this flag only if it is fips build. So non FIPS versions, do not set this stat and hence not publishes to stats sinks like metrics sinks. Publishing it will help creating alerts more easily.
Commit Message: set fips mode explicitly to publish to stats sinks
Testing: N/A
> set fips mode explicitly to publish to stats sinks

- bazel/README.md
- tools/github/write_current_source_version.py
Commit Message: This adds a script to produce the `SOURCE_VERSION` file which is useful to build envoy in a non-git (from an extracted release tarball) directory. See: `bazel/get_workspace_status` for more information.
Relevant: https://github.com/envoyproxy/envoy/issues/2181.
Additional Description: This is useful to have a way to produce `SOURCE_VERSION`, for example, to solve: https://github.com/Homebrew/homebrew-core/blob/923bb7a622b86876a662d1ed4a7ac51ccb2befcf/Formula/envoy.rb#L4. So downstream builder can consume release tarballs to build envoy without adding custom scripts to create `SOURCE_VERSION`.
Risk Level: Low, since this is an optional tool.
Testing: Run the script in git and non-git environments.
Docs Changes: Added.
> tools, github: Add current SOURCE_VERSION writer

- test/extensions/filters/listener/common/fuzz/listener_filter_fuzzer.cc
- test/extensions/filters/listener/common/fuzz/listener_filter_fuzzer.h
Let fuzzer own filter to avoid dangling reference if listener filter chain doesn't get created in connect. 
We'd need to upgrade googletest in order to support moveable actions hence why I can't just move the filter into the lambda, but we have some build breakages associated with googletest, a windows patch. 
Commit Message: Listener Fuzzer: avoid dangling reference to dtor unique_ptr.
Risk Level: low (fuzz)
Testing: ran fuzzer
Fixes #23520
> Listener Fuzzer: avoid dangling reference to dtor unique_ptr

- changelogs/current.yaml
- source/common/router/config_impl.cc
- test/common/router/config_impl_test.cc
Commit Message: router: fix `regex_rewrite` for redirects matched on prefix
These changes fixes an issue when using `regex_rewrite` as a part of a redirect when the path that is matched does not equal the full path. The issue was that only the matched section of the original path (e.g. prefix) was replaced with the substitution of the regex rewrite, while the expected behaviour is that the full path should be replaced.
This solves this by adding a case for these scenarios, i.e. if we have a redirect and use `regex_rewrite`, replace the full path with the rewritten path.
Risk Level: medium (changes the behaviour of how `regex_rewrite` and redirects works together)
Testing: Implemented unit tests to ensure the expected behaviour.
Release Notes: …
> router: fix `regex_rewrite` for redirects matched on prefix

- source/common/http/http1/codec_impl.cc
Commit Message: Cleanup dead code in HTTP1 codec.
See coverage, but also the fact that between the two calls to `resetStreamCalled()` none of the calls change would change that state.
Risk Level: low, dead code
Testing:
Docs Changes:
Release Notes:
> HTTP1 codec: Remove dead code.

- bazel/README.md
- tools/github/write_current_source_version.py
Commit Message: This adds a script to write the current SOURCE_VERSION.
Cherry-picked from:
- 9dcd8063a93bb7aec2cc271eb3fc05dfa96b177e
- 8e73e50126094174054c5dcfbef5bacae00af65f
Additional Description: To provide the script inside the source code tarball for each release version. The next tag will have this, but even before I can use the merged patch to get it, without `curl`-ing directly from https://raw.githubusercontent.com.
Docs Changes: Updated. 
> backport: tools, github: Add current SOURCE_VERSION writer

- bazel/repository_locations.bzl
This fixes https://github.com/envoyproxy/envoy/issues/23570 and https://github.com/envoyproxy/envoy/issues/23342
There haven't been many commits since the previous pinned version, here is the full diff: https://github.com/google/brotli/compare/0cd2e3926e95e7e2930f57ae3f4885508d462a25...6d03dfbedda1615c4cba1211f8d81735575209c8
> bazel: update brotli

- source/common/http/headers.h
Signed-off-by: Bootsie Heffernan <bheff@google.com>
Commit Message: Adding a new CustomHeaderValue for grpc-encoding
Testing: none
> Adding a new CustomHeaderValue for grpc-encoding

- tools/gen_compilation_database.py
For the compilation commands json file we only care about C/C++ targets of which there are nearly 0 of in tools/, this avoids hitting any jq rules, which fail to resolve on arm64 linux.
Fixes https://github.com/envoyproxy/envoy/issues/23649
> bazel: remove //tools/... from default compdb

- source/common/protobuf/utility.cc
- test/common/protobuf/utility_test.cc
Internally protobuf first converts seconds to nanoseconds before converting to milliseconds. This can overflow if the default bound checks are applied to the `seconds` value.
This can potentially be a breaking change for configuration that erroneously supplied values higher than 9223372036, since Envoy will now be rejecting such config. Before it was accepting it and using the "wrapped around" value.
This case is also verified by the test/server/server_corpus/clusterfuzz-testcase-server_fuzz_test-5988544525893632 corpus, however the asan sanitizer needs to be of a newer version to catch the error.
Risk Level: Low. Small possibility of a breaking change.
Testing: Unit Test 
Signed-off-by: Yan Avlasov …
> Stricter boundary checks for Duration when it is converted to std::chrono::milliseconds

- api/envoy/config/filter/http/ext_authz/v2/ext_authz.proto
- api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
Commit Message:  fix a typo in ext_authz docs
Additional Description: removes an extra dot from ext_authz field comments
Testing:
Release Notes:
> docs: fix a typo in ext_authz docs

- source/common/common/json_escape_string.h
char defaults to signed on most x86 platforms, but unsigned on arm64. When targeting linux arm64 this produced a warning because character was always >= 0. This change circumvents this warning without changing behavior even though it seems pretty unreasonable to have a character less than 0 in this use case. Theoretically we could disable a warning flag instead but that differs between clang and gcc.
Fixes https://github.com/envoyproxy/envoy/issues/23569
> build: fix char signed vs unsigned warning

- test/mocks/router/mocks.h
detected internally by an updated msan
> Fix uninitialized value in the retry policy mock

- api/envoy/config/listener/v3/listener_components.proto
* Currently envoy expects that if `server_names` contains a  wildcard `*`, it must start with `*.`. So just including `*` in the `server_names` is rejected by Envoy. A simple workaround is to not fill up the `server_names` field with `*` and leave it empty to achieve the same result
* Updated the doc string to mention that the user cannot specify just `*` in the `server_names` field
* Relates to https://github.com/envoyproxy/gateway/issues/601#issuecomment-1283113482
Signed-off-by: Arko Dasgupta <arko@tetrate.io>
Risk Level:
Testing:
Release Notes:
[Optional [API …
> Update doc string for `server_names`

- bazel/BUILD
Fixes https://github.com/envoyproxy/envoy/issues/23390
This is an edge case, upstream issue: https://github.com/bazelbuild/bazel-skylib/issues/404
> bazel: fix more config_setting visibility

- test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
Commit Message: Remove unused method in test (ext_authz integration test), since `envoy.reloadable_features.ext_authz_http_service_enable_case_sensitive_string_matcher` flag is removed.
Testing: Test only
> test, ext_authz: Remove unused method

- tools/github/write_current_source_version.py
Commit Message: This avoids rate-limited calls when calling GitHub API anonymously when resolving commit information.
Additional Description: I experienced this on my own homebrew tap. For homebrew-core, it needs to get a valid token from `HOMEBREW_GITHUB_API_TOKEN`.
> tools, github: Avoid rate-limited calls when calling GitHub API

- source/extensions/filters/network/redis_proxy/proxy_filter.cc
- test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc
Signed-off-by: asheryer <asheryer@amazon.com>
This commit fixes the issue https://github.com/envoyproxy/envoy/issues/23651
found by @untitaker
When pipelining a transaction the transaction connection terminates early which causes a segmentation fault.
I fixed this by checking that there are no more pending requests before closing the transaction.
I've tested this with several different scenarios and it works well.
Transactions can be pipelined now through envoy:
```
$printf '*1\r\n$5\r\nMULTI\r\n*3\r\n$3\r\nset\r\n$4\r\nfoo1\r\n$4\r\nbar1\r\n*2\r\n$3\r\nGET\r\n$4\r\nfoo1\r\n*1\r\n$4\r\nEXEC\r\n' | nc -w1 localhost 1998
+OK
+QUEUED
+QUEUED
*2
+OK
$4
bar1
```
Commit Message: Fix premature termination of transaction client
Additional Description: When transactions are pipelined the …
> Fix premature termination of transaction client

- bazel/foreign_cc/BUILD
Risk: Low
Testing: test/dependencies/curl_test.cc tests that libpsl is disabled
On my workstation (running Arch Linux) I had a linker error:
```
ld.lld: error: undefined symbol: psl_is_cookie_domain_acceptable
>>> referenced by cookie.c
>>>               cookie.c.o:(Curl_cookie_add) in archive bazel-out/k8-opt/bin/external/envoy/bazel/foreign_cc/curl/lib/libcurl.a
...
```
In test/dependencies/curl_test.cc I see that it is expected that curl does not use libpsl.
Apparently did curl somehow compile with libpsl support but failed to link against it since it is not included in Envoy. Explicitly disabling libpsl fixed my problem.
Signed-off-by: Jonatan Vela <jonatan.vela@ergon.ch>
> Explicitly disable libpsl for curl

- test/integration/idle_timeout_integration_test.cc
Commit Message: test: wait for response in request timeout integration test
The client connection will not wait for body in the replied response, but the following expect checks the body part.
Testing: N/A
> test: wait for response in request timeout integration test

- source/common/router/upstream_request.cc
Commit Message: router: set stream_info_'s request headers of upstream request
Now custom_tags are applied also for upstream spans due to https://github.com/envoyproxy/envoy/pull/22987/files#diff-36ebe2d9da39e88ceeccb197a9ff0b8a1dc97a5f72c8597c40d27f61a9ead00f.
But requestHeaders of stream_info is not set for UpstreamRequest and custom_tags won't work. So this PR set it to make it work.
Testing:
Docs Changes:
Release Notes:
> router: set stream_info_'s request headers of upstream request

- .bazelrc
Related: https://github.com/envoyproxy/envoy/issues/23580#issuecomment-1296488433
> bazel: avoid type-limits warning on arm64 Linux

- bazel/v8.patch
Since gcc 12 it seems there are some false positives around this warning.
Upstream gcc reports:
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107252
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100366
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106199
We can't use `--per_file_copt` in this case because we build this in the host configuration https://github.com/bazelbuild/bazel/issues/12406
Upstream v8 report: https://bugs.chromium.org/p/v8/issues/detail?id=13441
Fixes https://github.com/envoyproxy/envoy/issues/23692
> bazel: workaround invalid nonnull warning in v8

- tools/github/write_current_source_version.py
Commit Message: Pick the authorization prefix based on the provided token. 
Additional Description: Reference: https://github.com/octokit/auth-token.js/blob/902a172693d08de998250bf4d8acb1fdb22377a4/src/with-authorization-prefix.ts#L6-L12
> tools, github: Pick authorization prefix based on provided token

- bazel/boringssl_static.patch
New warning with gcc 12, upstream issue: https://bugs.chromium.org/p/boringssl/issues/detail?id=492
Fixes https://github.com/envoyproxy/envoy/issues/23568
> bazel: workaround boringssl warning

- changelogs/current.yaml
- contrib/generic_proxy/filters/network/source/proxy.cc
- contrib/generic_proxy/filters/network/source/proxy.h
- contrib/generic_proxy/filters/network/test/proxy_test.cc
Commit Message: generic proxy: make sure the execute order of encoder filters is the reverse of decoder filters'
Minor fix to the execute order of generic l7 filters.
Risk Level: Low. WIP extension.
Testing: unit test added.
> generic proxy: make sure the execute order of encoder filters is the reverse of decoder filters'

- api/envoy/extensions/common/async_files/v3/async_file_manager.proto
Risk Level:
Testing:
Docs Changes:
Release Notes:
> fixing OSS filter_fuzz_test OOM issue when thread_count is 800 million.

- BUILD
- CODEOWNERS
- OWNERS.md
- bazel/envoy_build_system.bzl
- changelogs/current.yaml
- ci/do_ci.sh
- ci/run_clang_tidy.sh
- mobile/library/common/extensions/filters/http/assertion/BUILD
- mobile/library/common/extensions/filters/http/assertion/config.cc
- mobile/library/common/extensions/filters/http/assertion/config.h
- mobile/library/common/extensions/filters/http/assertion/filter.cc
- mobile/library/common/extensions/filters/http/assertion/filter.h
- mobile/library/common/extensions/filters/http/assertion/filter.proto
- mobile/test/common/extensions/filters/http/assertion/BUILD
- mobile/test/common/extensions/filters/http/assertion/assertion_filter_test.cc
- source/extensions/extensions_build_config.bzl
- tools/code_format/envoy_build_fixer.py
This PR sets up the directory structure, visibility rules, codeowners, adds E-M C++ tests to Envoy CI, and moves one extension over as a proof of concept.
Testing: ported test to Envoy CI.  did not turn up platform CI _yet_
Part of https://github.com/envoyproxy/envoy/issues/23758
> mobile: starting the repo merge with the assertion filter

- source/common/runtime/runtime_impl.cc
> typo: replace 'Enovy' with 'Envoy'

- test/integration/http_timeout_integration_test.cc
Commit Message: test: wait for end stream in HTTP timeout integration tests
Currently, these integration tests only wait for headers and close the codec client, which will cause the response stay incomplete and lead to expect failure in an extremely slow network. The patch makes these tests wait for end stream before closing codec client.
Testing: N/A
> test: wait for end stream in HTTP timeout integration tests

- ci/run_envoy_docker.sh
Previously `/var/run/docker.sock` is readable/writable inside docker run because group ID of `envoygroup` coincidentally matches host docker group, while it is no longer true during rolling out new image. Fixing that by forcing `envoygroup` has host docker group ID.
Testing: CI
Docs Changes:
Release Notes:
> ci: use host docker gid for envoybuild

- bazel/external/googleurl.patch
Upstream fix: https://quiche-review.googlesource.com/c/googleurl/+/11260
> bazel: update googleurl patch with missing header

- tools/base/requirements.in
- tools/base/requirements.txt
Fix #22222 
Fix #23348 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> repo: Add yaml linting

- ci/run_envoy_docker.sh
Since the stat on mac missing the -c option, i.e.
stat: illegal option -- c
usage: stat [-FLnq] [-f format | -l | -r | -s | -x] [-t timefmt] [file ...]
Risk Level:
Testing:
Docs Changes:
Release Notes:
> improve the run_envoy_docker.sh compatibility on mac.

- ci/do_ci.sh
Create a TAR waste lots of time, skip it if not release.
Before this:
```
Copying binary for image build...
real    0m32.585s
user    0m30.830s
sys     0m2.557s
```
After this:
```
Copying binary for image build...
real    0m1.912s
user    0m0.806s
sys     0m1.105s
```
Save 30s in total.
Testing:
Docs Changes:
Release Notes:
> ci: accelerate local build

- bazel/foreign_cc/BUILD
- bazel/repositories.bzl
- bazel/repository_locations.bzl
- ci/run_envoy_docker.sh
Cherry-picked from: 
- https://github.com/envoyproxy/envoy/commit/7ac5336bc807f32e84f04cd20d2c95d95e923aa7
- 835dc50
> [backport/v1.23]: ci: use host docker gid for envoybuild + deps: Update ragel

- bazel/README.md
- tools/github/write_current_source_version.py
Commit Message: This makes sure we are not rate-limited when calling GitHub API 
Cherry-picked from:
- ceb45a32da8c9886c0eb87f8723068b6cd96c5f8
- 36fc1ccc1de30b79594ca5ef9d8f0799a0f399a0
- 3ea63d73407f5af8992e20e1bf0fb4b481b71d13
> [backport/v1.23] tools, github: Add error handling and update README

- test/extensions/transport_sockets/alts/tsi_handshaker_test.cc
std::list's back() is UB when called on an empty list.
Signed-off-by: yurykats <yurykats@yahoo.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Fix undefined behavior

- source/extensions/transport_sockets/tls/cert_validator/default_validator.cc
Both things the comment says are inaccurate: After #23320, this mechanism no longer uses the X509_STORE callback, but a flag. After #21417, Envoy is also not (always) using
SSL_CTX_set_cert_verify_callback, but a different one.
Just remove the comment altogether, as it doesn't seem to provide any value. All it's saying is that, because Envoy still uses `store` at the end of the day, configuring things on `store` does stuff. But the whole function configures things on `store`, so it's not specific to that block anyway.
Signed-off-by: David Benjamin <davidben@google.com>
Risk Level: none (comment-only change)
Testing: CI (comment-only change)
Docs Changes: n/a (comment-only change)
Release Notes: n/a (comment-only change) …
> tls: remove stale comment

- contrib/generic_proxy/filters/network/source/codecs/dubbo/config.cc
Commit Message: dubbo: fix compilation error.
There's a compilation error in dubbo (gcc version 11.3.1 20220421), because the switch/case statement isn't handling the default case:
contrib/generic_proxy/filters/network/source/codecs/dubbo/config.cc: In function 'absl::string_view Envoy::Extensions::NetworkFilters::GenericProxy::Codec::Dubbo::{anonymous}::responseStatusToStringView(Envoy::Extensions::Common::Dubbo::ResponseStatus)':
contrib/generic_proxy/filters/network/source/codecs/dubbo/config.cc:38:1: error: control reaches end of non-void function [-Werror=return-type]
38 | }
| ^
contrib/generic_proxy/filters/network/source/codecs/dubbo/config.cc: In function 'Envoy::Extensions::NetworkFilters::GenericProxy::StatusCode …
> dubbo: fix compilation error.

- source/extensions/filters/http/local_ratelimit/local_ratelimit.cc
- source/extensions/filters/http/local_ratelimit/local_ratelimit.h
- test/extensions/filters/http/local_ratelimit/local_ratelimit_integration_test.cc
Commit Message: local ratelimit: make sure the timer of local limit could be destoryed safely
Timer is used by the `LocalRatelimitImpl`, so we should ensure the `LocalRatelimitImpl` always be destroyed in the thread where its inner timer is created and running.
However, the `LocalRatelimitImpl` in the `FilterConfig` of local rate limit filter may be created in the main thread and destroyed in the worker theads when the route configuration is updated by the RDS.
Testing: integration test.
> local ratelimit: make sure the timer of local limit could be destoryed safely

- test/mocks/stream_info/mocks.cc
Signed-off-by: silverstar195 <seanmaloney@google.com>
Fix bug in stream_info mock 
``Return(value)`` in gmock copies ``value`` at setup time. Any updates to ``value`` during use of mock will not be reflected.
This caused ``responseFlags`` to always return the default value of ``0`` instead of any updates done by  ``setResponseFlag``
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Fix bug in stream_info mock

- source/common/common/key_value_store_base.cc
- source/common/common/key_value_store_base.h
- source/extensions/key_value/file_based/config.cc
- test/config/utility.cc
- test/extensions/key_value/file_based/key_value_store_test.cc
Turns out the TTL functionality I added needs the ability to persist to disk.  Do this by piggybacking on the existing persistence code; writing an optional absolute TTL to disk and then converting it back to relative form for the `ttl_manager` to use.
> Persist key-value-store TTLs to disk in flush()

- source/extensions/filters/http/cache/simple_http_cache/simple_http_cache.cc
- source/extensions/filters/http/cache/simple_http_cache/simple_http_cache.h
- test/extensions/filters/http/cache/http_cache_implementation_test_common.cc
Commit Message: Fix simple_http_cache updateHeaders for vary
Additional Description: There was a TODO for this, and a test that validates the behavior was incorrect in a way that matched the implementation, with comments falsely suggesting it was validating the correct behavior. This change makes the behavior correct and the validation correct, thereby enabling other correct cache implementations to pass the test suite.
Risk Level: Very low. Changes only to WIP filter, only fixing incorrect behavior.
Testing: Fixed existing test.
> Fix simple_http_cache updateHeaders for vary

- ci/run_envoy_docker.sh
Since the stat on mac missing the -c option, i.e.
stat: illegal option -- c
usage: stat [-FLnq] [-f format | -l | -r | -s | -x] [-t timefmt] [file ...]
Signed-off-by: doujiang24 <doujiang24@gmail.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] improve the run_envoy_docker.sh compatibility on mac. (#23832)

- .github/workflows/check-deps.yml
- .github/workflows/codeql-daily.yml
- .github/workflows/codeql-push.yml
- .github/workflows/depsreview.yml
- .github/workflows/pr_notifier.yml
- .github/workflows/stale.yml
Prevent bitrot on release branches
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] ci: Pin images in github actions (#23860)

- .github/workflows/check-deps.yml
- .github/workflows/codeql-daily.yml
- .github/workflows/codeql-push.yml
- .github/workflows/depsreview.yml
- .github/workflows/pr_notifier.yml
- .github/workflows/stale.yml
Prevent bitrot on release branches
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] ci: Pin images in github actions (#23860)

- source/common/common/key_value_store_base.cc
- source/common/common/key_value_store_base.h
- source/extensions/key_value/file_based/config.cc
std::pair tends to result in fairly unreadable code so use a named struct instead.
Also make members private instead of public as per the style guide.
> Use a named struct instead of a pair in key_value_store_base.h

- contrib/config/source/kv_store_xds_delegate.cc
- contrib/config/test/BUILD
- contrib/config/test/kv_store_xds_delegate_test.cc
https://github.com/envoyproxy/envoy/pull/22921 added the KeyValueStore based xDS delegate, but the TTLs were not set on the resources processed by the delegate.
Now that support has been added for TTLs in the KeyValueStore interface[1][2], this commit ensures the TTL of the resource gets processed by the KeyValueStore based delegate.
[1] https://github.com/envoyproxy/envoy/pull/22884 
[2] https://github.com/envoyproxy/envoy/pull/23318
> xds: Add TTL support to the KeyValueStore xDS delegate

- docs/root/configuration/other_protocols/thrift_filters/payload_to_metadata_filter.rst
- source/extensions/filters/network/thrift_proxy/decoder.cc
- source/extensions/filters/network/thrift_proxy/decoder.h
- source/extensions/filters/network/thrift_proxy/filters/payload_to_metadata/payload_to_metadata_filter.cc
- source/extensions/filters/network/thrift_proxy/filters/payload_to_metadata/payload_to_metadata_filter.h
- test/extensions/filters/network/thrift_proxy/filters/payload_to_metadata/payload_to_metadata_filter_test.cc
…yload_to_metadata filter
This PR fixes two issues:
(a) the decoder actually `drain` the buffer so the router couldn't get the data to send.
we copy to buffer to parse for now as we're waiting for https://github.com/envoyproxy/envoy/issues/23901
(b) passthrough data is not the whole thrift request, 
therefore we introduce `DecoderStateMachine::runPassthroughData` to decode the protocol part only.
Docs Changes: filter rst
> thrift_proxy: decode passthrough data by protocol parsing only for payload_to_metadata filter

- api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
This is a comments-changes-only PR.
The `ExternalProcessor` has a `mutation_rules` field, whose purpose is to let users modify otherwise-restricted headers, such as `"host"` and `":authority"`. Odds are that users who are modifying such headers are trying to influence the routing decisions that Envoy makes, such as was the case in https://github.com/envoyproxy/envoy/issues/23919.
However, setting only `"host"` or `":authority"` is not sufficient to change such routing decisions; users must also set a `clear_route_cache` field.
This PR aims to make it harder to overlook the `clear_route_cache` field, like I did in https://github.com/envoyproxy/envoy/issues/23919, by improving the comments on the `mutation_rules` field.
> Expand comment on `ExternalProcessor.mutation_rules`

- source/common/http/utility.cc
- source/common/http/utility.h
- test/common/http/utility_test.cc
One of the overloads of sendLocalReply was only used by the utility test file. Move it there to avoid having users to decide which to use.
See coverage from another PR; only used in this test file: 
Commit Message: Cleanup: Move sendLocalReply utility to test file where it was only being used
Testing: ran tests
> Clean up: Move sendLocalReply utility just used in this test file to the test file.

- ci/Dockerfile-envoy
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docker: Bump `distroless/base-debian11:nonroot` -> `4b22ca3c6`

- ci/Dockerfile-envoy-distroless
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/v1.21] docker: Bump `distroless/base-debian11:nonroot` -> `4b22ca3c6`

- .bazelrc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> build: fixing brokend dead strip

- .bazelrc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> build: More sizeopt fixes

- source/extensions/filters/http/cache/cache_entry_utils.cc
- source/extensions/filters/http/cache/cache_entry_utils.h
- source/extensions/filters/http/cache/simple_http_cache/simple_http_cache.cc
- test/extensions/filters/http/cache/cache_entry_utils_test.cc
Commit Message: Move header-merging from simple_http_cache to cache_entry_utils
Additional Description: This operation should behave the same for all cache implementations, and is non-trivial, so it should be a shared function.
Risk Level: Low; WIP filter only, no behavior change.
Testing: Unit tests.
> Move header-merging from simple_http_cache to cache_entry_utils

- CODEOWNERS
Commit Message: generic proxy: update codeowners of generic proxy
There was only one active contributor (me) for the generic proxy in the past.
Now the @soulxu is glad to help review and maintain code of generic proxy.
He is active contributor of Envoy and has done lots of great contributions. Thanks. 🌹 
Testing: n/a.
> generic proxy: update codeowners of generic proxy

- CODEOWNERS
- source/extensions/http/cache/file_system_http_cache/BUILD
- source/extensions/http/cache/file_system_http_cache/cache_file_fixed_block.cc
- source/extensions/http/cache/file_system_http_cache/cache_file_fixed_block.h
- test/extensions/http/cache/file_system_http_cache/BUILD
- test/extensions/http/cache/file_system_http_cache/cache_file_fixed_block_test.cc
- tools/spelling/spelling_dictionary.txt
Commit Message: cache_file_fixed_block: part one of filesystem_cache
Additional Description: #23175 is the target end state of this.
Risk Level: None, it is dead-code until the API part is added.
Testing: Unit tested.
> Add cache_file_fixed_block as first piece of filesystem_cache

- .azure-pipelines/bazel.yml
- api/bazel/repository_locations.bzl
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] ci: disable non-RBE cache for release branches (#22745)

- api/contrib/envoy/extensions/network/connection_balance/dlb/v3alpha/dlb.proto
- contrib/network/connection_balance/dlb/source/connection_balancer_impl.cc
- contrib/network/connection_balance/dlb/source/connection_balancer_impl.h
- contrib/network/connection_balance/dlb/test/config_test.cc
When big traffic come, dlb_send() may fail due to temporarily unavailable resource.
Add retry logic to ensure every connection is sent successfully by dlb.
Testing: Add
> dlb: add retry logic

- source/extensions/filters/http/jwt_authn/matcher.cc
- test/extensions/filters/http/jwt_authn/BUILD
- test/extensions/filters/http/jwt_authn/jwt_authn_corpus/allow_missing_remote_jwks.txtpb
- test/extensions/filters/http/jwt_authn/jwt_authn_corpus/cors_bypass.txtpb
- test/extensions/filters/http/jwt_authn/jwt_authn_corpus/filter_state_local_jwks.txtpb
- test/extensions/filters/http/jwt_authn/jwt_authn_corpus/match_rule_local_jwks.txtpb
- test/extensions/filters/http/jwt_authn/jwt_authn_corpus/match_rule_remote_jwks_custom_header.txtpb
- test/extensions/filters/http/jwt_authn/jwt_authn_corpus/per_route_local_jwks.txtpb
- test/extensions/filters/http/jwt_authn/jwt_authn_corpus/require_any_remote_jwks.txtpb
- test/extensions/filters/http/jwt_authn/jwt_authn_fuzz.proto
- test/extensions/filters/http/jwt_authn/jwt_authn_fuzz_test.cc
Add a fuzz test.   It is for https://github.com/envoyproxy/envoy/pull/23617
Testing:  Add fuzz tests
Release Notes:  None
> jwt_authn: add a fuzz test for http filter jwt_authn

- source/common/config/grpc_mux_impl.cc
- source/common/config/watch_map.cc
Fix #23156
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.22] Release 1.22 build fix

- source/extensions/extensions_metadata.yaml
jwt_authn http filter have been used by many products.  But its security status is still alpha.
Did not find the process of upgrading its status. 
Testing:  None
> jwt_authn: upgrade its security status to stable

- ci/Dockerfile-envoy
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] docker: Bump `distroless/base-debian11:nonroot` -> `4b22ca3c6` (#23987)

- test/integration/listener_lds_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.22] listener: fix flaky listener integration test (#22383)

- contrib/generic_proxy/filters/network/source/BUILD
- contrib/generic_proxy/filters/network/source/codecs/dubbo/config.cc
- contrib/generic_proxy/filters/network/source/codecs/dubbo/config.h
- contrib/generic_proxy/filters/network/source/config.cc
- contrib/generic_proxy/filters/network/source/config.h
- contrib/generic_proxy/filters/network/source/interface/BUILD
- contrib/generic_proxy/filters/network/source/interface/codec.h
- contrib/generic_proxy/filters/network/source/interface/codec_callbacks.h
- contrib/generic_proxy/filters/network/source/interface/proxy_config.h
- contrib/generic_proxy/filters/network/source/proxy.cc
- contrib/generic_proxy/filters/network/source/proxy.h
- contrib/generic_proxy/filters/network/test/BUILD
- contrib/generic_proxy/filters/network/test/codecs/dubbo/config_test.cc
- contrib/generic_proxy/filters/network/test/config_test.cc
- contrib/generic_proxy/filters/network/test/fake_codec.cc
- contrib/generic_proxy/filters/network/test/fake_codec.h
- contrib/generic_proxy/filters/network/test/mocks/codec.cc
- contrib/generic_proxy/filters/network/test/mocks/codec.h
- contrib/generic_proxy/filters/network/test/proxy_test.cc
Commit Message: generic proxy: added support for custom read filter
Developers could add new protocol proxying function to the Envoy by implementing a codec for the related protocol.
In the previous implementation, although the codec is extensible but the implementation of L4 read filter is fixed.
This PR added new extension point to make the implementation of L4 read filter customizable based on the codec config.
Risk Level: Low. contrib code update.
Testing: n/a.
> generic proxy: added support for custom read filter

- STYLE.md
Commit Message: add a discussion about size_t vs uint64_t to the style guide.
Additional Description: This was discussed during reviews, but not called out in the style guide.
Testing: none
> doc: add size_t discussion to style guide, and correct OptRef doc

- source/common/network/connection_impl.cc
- source/common/network/connection_impl.h
- source/extensions/transport_sockets/alts/tsi_socket.cc
- source/extensions/transport_sockets/alts/tsi_socket.h
- test/extensions/transport_sockets/alts/tsi_socket_test.cc
Commit Message: Trigger downstream transport socket `onConnect`. Server connections start out as socket connected, but not necessarily transport socket connected. The server socket may need this event to trigger the transport socket connected event (e.g. raw_buffer). 
Some server downstream transport sockets may share implementation with the upstream transport socket and not expect this event, in which case these custom downstream transport sockets may need to ignore this event after this change.
Risk Level: medium (for downstream integrations, no functional change in this repo)
Testing: done
Release Notes:
Issue: https://github.com/envoyproxy/envoy/issues/9023
> transport socket: trigger onConnect for downstream transport sockets

- api/envoy/type/v3/ratelimit_unit.proto
Even though for us (who introduced the rate_limit_quota feature), `month` and `year` unit are too coarse-grained unit as our traffic will be huge and we will update the Envoy config on more frequent basis, there is business need/case for monthly and yearly subscription from @renuka-fernando side.  
More detailed discussion can be found #23844.
Signed-off-by: tyxia <tyxia@google.com>
> rate_limit_quota: [API] Add time unit `month` and `year`

- .azure-pipelines/pipelines.yml
the 1.24 branch is mostly passing coverage but frequently timesout often when it has already completed the actual coverage tests.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] ci: Increase coverage timeout

- source/common/http/headers.h
This fixes a mistake made in https://github.com/envoyproxy/envoy/pull/23723/.
Signed-off-by: Bootsie Heffernan <bheff@google.com>
Commit Message:  N/A
Testing: N/A
> Switching "grpc-message-encoding" to "grpc-message-type" in headers.h.

- test/integration/tcp_tunneling_integration_test.cc
The HeaderEvaluatorConfigUpdate test needs to wait for a listener to be replaced. Its previous attempt to achieve that did not account for the intermediate warming state of new listeners, which could lead to the test continuing prematurely and failing.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.22] test: fix a race in tcp_tunneling_integration_test (#22883)

- test/integration/tcp_tunneling_integration_test.cc
The HeaderEvaluatorConfigUpdate test needs to wait for a listener to be replaced. Its previous attempt to achieve that did not account for the intermediate warming state of new listeners, which could lead to the test continuing prematurely and failing.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] test: fix a race in tcp_tunneling_integration_test (#22883)

- api/envoy/service/ratelimit/v3/rls.proto
- changelogs/current.yaml
- source/extensions/filters/http/ratelimit/ratelimit_headers.cc
Per #23844 and #24031,  @renuka-fernando wants to have time unit `month` and `year` for his business need
Release note added.
> rate_limit: Add time unit month and year

- ci/Dockerfile-envoy
> docker: Don't include su-exec in the distroless image

- source/common/router/route_config_update_receiver_impl.cc
- source/common/router/route_config_update_receiver_impl.h
If there is no VHDS, do not allocate a map and do not clear/reset RDS vhosts during RDS update.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Reduce VHDS overhead in RDS update

- source/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter.cc
Commit Message: Explicitly disable read during async DNS call. 
Additional Description: tcp_proxy implicitly disables read before this filter during `initialize`, but we cannot always assume it is going to do that. Context: https://github.com/envoyproxy/envoy/pull/23944
Testing: regression
> sni proxy: disable read while waiting for DNS

- ci/run_envoy_docker.sh
I think Ubuntu expects systemd to have set permissions for this in the container, but systemd doesnt run.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix /dev/stderr err

- .azure-pipelines/pipelines.yml
ci mostly passing coverage but occasionally timesout, sometimes when it has already completed the actual coverage tests.
the problem is worse on postsubmit and release branches due to less caching.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Increase coverage timeout

- source/common/config/utility.h
This PR fixes the broken URL link in `checkTransportVersion()` method inside utility file by pointing it to `/latest` so that it points to the correct page i.e. https://www.envoyproxy.io/docs/envoy/latest/faq/api/envoy_v3
**Commit Message:** Fixes broken URL in `checkTransportVersion()`.
**Additional Description:** This PR fixes the broken URL for the warning that gets printed while using xDS v2.
**Risk Level:** Very Low
**Signed-off-by:** Rohit Agrawal <rohit.agrawal@databricks.com>
> utility: fix broken URL in checkTransportVersion() utility method

- mobile/docs/root/api/starting_envoy.rst
> mobile: fix a typo

- test/common/http/http1/BUILD
- test/common/http/http1/codec_impl_test.cc
- test/extensions/filters/http/health_check/health_check_integration_test.cc
- test/extensions/http/header_formatters/preserve_case/BUILD
- test/extensions/http/header_formatters/preserve_case/preserve_case_formatter_reason_phrase_integration_test.cc
- test/integration/BUILD
- test/integration/drain_close_integration_test.cc
- test/integration/http_integration.cc
- test/integration/http_integration.h
- test/integration/http_protocol_integration.cc
- test/integration/http_protocol_integration.h
- test/integration/idle_timeout_integration_test.cc
- test/integration/protocol_integration_test.cc
- test/test_common/utility.h
Consolidate these existing implementations.
Tracking issue: https://github.com/envoyproxy/envoy/issues/21245
Commit Message: Move Http1ParserImpl and pretty-printer to test_common/utility.h.
Risk Level: low, test-only refactor
> Move Http1ParserImpl and pretty-printer to test_common/utility.h.

- changelogs/current.yaml
- docs/root/configuration/http/http_filters/aws_lambda_filter.rst
- source/extensions/common/aws/signer.h
- source/extensions/common/aws/signer_impl.cc
- source/extensions/common/aws/signer_impl.h
- source/extensions/filters/http/aws_lambda/aws_lambda_filter.cc
- test/extensions/common/aws/mocks.h
- test/extensions/common/aws/signer_impl_test.cc
- test/extensions/filters/http/aws_lambda/aws_lambda_filter_test.cc
- test/extensions/filters/http/aws_request_signing/aws_request_signing_filter_test.cc
Commit Message: Support multi region routing for AWS Lambda Filter
Additional Description: Expose a variable to take a string to override the AWS region to sign the headers
Testing: UT
Docs Changes: Yes, plus includes the update needed for #22213
Release Notes: bug fix
Fixes: https://github.com/envoyproxy/envoy/issues/23076
> Support multi region routing for AWS Lambda Filter

- api/envoy/extensions/filters/http/ext_authz/v3/BUILD
- api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
- changelogs/current.yaml
- source/extensions/filters/common/ext_authz/check_request_utils.cc
- source/extensions/filters/common/ext_authz/check_request_utils.h
- source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc
- source/extensions/filters/common/ext_authz/ext_authz_http_impl.h
- source/extensions/filters/http/ext_authz/ext_authz.cc
- source/extensions/filters/http/ext_authz/ext_authz.h
- test/extensions/filters/common/ext_authz/BUILD
- test/extensions/filters/common/ext_authz/check_request_utils_test.cc
- test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc
- test/extensions/filters/http/ext_authz/config_test.cc
- test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
- test/extensions/filters/http/ext_authz/ext_authz_test.cc
Commit Message: add support for allowlisting request headers included in the check request to the authorization server, be it HTTP or gRPC (currently, this is supported for HTTP only). This patch deprecates the current `allowed_headers` config field (on the `authorization_request` message) and introduces a new one on the `ext_authz` message. To note is that the default behaviour (i.e. no config specified) differs based on the type of authorization server (this is to maintain backwards compatibility).
Testing: updated unit and integration tests
Docs Changes: updated API protos
Release Notes: updated release notes
[Optional Fixes #Issue]: https://github.com/envoyproxy/envoy/issues/21535
> Support allowlisting request headers for both gRPC and HTTP authorization servers

- source/extensions/transport_sockets/tls/context_impl.cc
RSA_size() returns size in bytes, while RSA_bits() returns size in bits. Replace RSA_size with RSA_bits to reduce redundant calculations.
Signed-off-by: Luyao Zhong <luyao.zhong@intel.com>
> Reduce redundant calculations with RSA_bits

- .github/workflows/release_validation.yml
- .gitignore
copied from the mobile repo, and edited to run for repo merge.  Only runs for mobile PRs.
Testing: first push shows it worked successfully
part of https://github.com/envoyproxy/envoy/issues/23758
> mobile: turning up release validation CI

- .gitignore
Ignore *.s?? instead of *.sw* to make sure git does not ignore .swift files
Part of #23758
> Ignore *.s?? intead of *.sw* to make sure git does not ignore .swift 

- test/test_common/utility.h
This is to make the compiler enforce that an (unlikely) new Http1ParserImpl value is handled.
Follow-up on
https://github.com/envoyproxy/envoy/pull/24146/files/bbb1683342ad670a380fb4fbebc370c1ca5c43d8#r1033605725.
Commit Message: Use switch in http1ParserImplToString().
Risk Level: low, test-only change
> Use switch in http1ParserImplToString().

- api/envoy/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto
- changelogs/current.yaml
- envoy/tcp/upstream.h
- source/common/tcp_proxy/tcp_proxy.cc
- source/common/tcp_proxy/tcp_proxy.h
- source/common/tcp_proxy/upstream.cc
- test/common/tcp_proxy/upstream_test.cc
Commit Message: tcp proxy: enable to specify a path for HTTP tunneling with POST method
Docs Changes: API doc
Release Notes: new feature
Fixes #24038
> tcp proxy: enable to specify a path for HTTP tunneling with POST method

- source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc
Commit Message: Use per_route_config_ in grpc_json_transcoder
Additional Description: Fixes a minor bug in grpc_json_transcoder; if configured per-route with an empty config at the listener level, the request_validation_options fields at the route level would be ignored.
Risk Level: Low (bug fix only)
Testing: Tested live. I don't think adding a unit test to cover this error would be meaningful *after* the bug is fixed. The fix is trivial, the test is hard.
Docs Changes: No, the docs already describe the 'after' behavior.
> Use per_route_config_ in grpc_json_transcoder

- source/common/http/utility.cc
- source/common/http/utility.h
- source/extensions/access_loggers/common/grpc_access_logger.h
- source/extensions/filters/http/gcp_authn/filter_config.cc
- source/extensions/filters/http/jwt_authn/jwks_cache.cc
- test/common/http/utility_test.cc
- test/extensions/filters/http/jwt_authn/jwt_authn_corpus/clusterfuzz-testcase-minimized-jwt_authn_fuzz_test-5696765294936064
This issue is found by newly added fuzz test from jwt_authn filter.  The root course is 
```
Utility::convertCoreToRouteRetryPolicy 
```
may throw an exception [here](https://github.com/envoyproxy/envoy/blob/main/source/common/http/utility.cc#L1088)
This function is called by `jwt_authn` filter and `gcp_authn` filters in the worker thread.   
The changes:
* change the `throw EnvoyException` to `ENVOY_BUG`.  It should not throw exception if it may be called at worker threads.
* Add a new function `validate` to be called at main thread.
* 
Testing:  None
Release Notes:  None
> Validate core retry policy at config parsing time

- api/envoy/extensions/filters/http/jwt_authn/v3/config.proto
- changelogs/current.yaml
- source/extensions/filters/http/jwt_authn/jwks_async_fetcher.cc
- source/extensions/filters/http/jwt_authn/jwks_async_fetcher.h
- test/extensions/filters/http/jwt_authn/filter_integration_test.cc
- test/extensions/filters/http/jwt_authn/jwks_async_fetcher_test.cc
This is just an improvement to async_fetch feature of remote jwks.
*  For a successful fetch,  adjust its re_fetch time to be the jwks_cache_duration - 5s.   This is to avoid of triggering on-demand fetching.   During authentication,  if jwks is not fetched, or is expired,  it will trigger an on-demand fetching.  If async_fetch can refetch the jwks a little bit earlier, it will avoid the on-demand fetch. 
* For a failed fetch,  trigger a re_fetch after 1 second.  Getting jwks is important.  We should keep retrying.  This retrying is after [remote_jwks.retry_policy](https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/filters/http/jwt_authn/v3/config.proto#L366).  
Risk Level: Low, added more frequence refetch for a failed …
> jwt_authn: adjust remote_jwks.async_fetch refetch timer

- changelogs/current.yaml
- source/extensions/filters/http/jwt_authn/authenticator.cc
- source/extensions/filters/http/jwt_authn/stats.h
- test/extensions/filters/http/jwt_authn/provider_verifier_test.cc
If jwt_cache is enabled, it may break [ProviderWithAudiences](https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/filters/http/jwt_authn/v3/config.proto#L398) feature. 
The `ProviderWithAudiences` may need to check different audiences. But when a cached jwt is used, the audiences will not be checked.  
Risk Level:  Low
Testing:  Unit-test
> jwt_authn: fix jwt cache bug with requirement_with_audiences

- .gitignore
- mobile/examples/java/hello_world/.bazelproject
- mobile/examples/kotlin/hello_world/.bazelproject
- mobile/test/kotlin/apps/baseline/.bazelproject
- mobile/test/kotlin/apps/experimental/.bazelproject
Commit Message: Add missing `.bazelproject` files. This fixes a dev workflow which allows us to run example/test applications from within Android Studio IDE. The addition of the `.bazelrpoject` was most probably missed in https://github.com/envoyproxy/envoy/pull/24104 as dot files are ignored by default in Envoy repo.
Testing: N/A
> mobile tools: add missing .bazelproject files

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
part of https://github.com/envoyproxy/envoy/issues/23758
> ci: Add pipeline change detection

- api/envoy/config/listener/v3/listener.proto
- changelogs/current.yaml
- source/server/listener_impl.cc
- source/server/listener_impl.h
- source/server/listener_manager_impl.cc
- test/integration/base_integration_test.cc
- test/integration/base_integration_test.h
- test/integration/listener_lds_integration_test.cc
- test/server/listener_manager_impl_test.cc
- test/server/listener_manager_impl_test.h
Commit Message: listener: enable socket_options for multiple addresses
This PR enables specifying socket_options for each additional address. Since when using dual-stack, the IPv4 and IPv6 address have different socket option, then we need a way to specify different socket option for multiple addresses.
notes for implementation:
* To simplify the implementation, the new listener will only clone the old listener's socket when all the addresses' socket_options are equal when updating the listener. This is the same as when updating additional addresses, we only clone the socket when all the addresses are the same.
* For updating socket options for additional addresses, it is also under the runtime guard protection of …
> listener: enable socket_options for multiple addresses

- test/integration/BUILD
I have seen TSAN test timeouts, for example, in #24108.  This is presumably due to #24003 increasing the test parameter space two-fold for HttpProtocolIntegrationTest and its derived classes, like WebsocketIntegrationTest.  Increase shard count to prevent timeouts.
Commit Message: Increase shard count for //test/integration:websocket_integration_test.
Risk Level: low, test-only change
Testing: //test/integration:websocket_integration_test
> Increase shard count for //test/integration:websocket_integration_test.

- source/extensions/filters/http/gcp_authn/token_cache.h
- test/extensions/filters/http/gcp_authn/BUILD
- test/extensions/filters/http/gcp_authn/token_cache_test.cc
- tools/base/requirements.txt
`VerifyTimeConstraint()` interface is correct for the token consumer. However, as the token producer here, we should instead include the clock skew as the part of the `now` time up front to account for the clock skew on the consumer side where the token will be consumed. Also, in this way, we can avoid changing the third-party library interface `VerifyTimeConstraint()` (which might requires longer turnaround time)
> gcp_authn: Modify the token time constraint check

- api/envoy/service/health/v3/hds.proto
- source/common/upstream/health_discovery_service.cc
- source/common/upstream/health_discovery_service.h
- test/common/upstream/hds_test.cc
Commit Message: feat(hds): allow to configure upstream bind address for hds
Additional Description: Sometimes when an application doesn't bind to localhost and the machine uses iptables for traffic redirection, HDS might need to override the source address for iptables to redirect traffic to the application instead of getting into the loop.
Testing: small unit test configuration, upstream cluster tests binding functionality, manual testing
Docs Changes: API docs
> feat(hds): allow to configure upstream bind address for HDS

- source/common/http/filter_manager.cc
- source/common/http/filter_manager.h
Commit Message: Rename overloaded term (dual filter), Remove unnecessary duplicated bit in base class.
Testing: ran filter tests
> Refactor: Filter Manager

- source/extensions/access_loggers/common/grpc_access_logger.h
- source/extensions/access_loggers/open_telemetry/grpc_access_log_impl.cc
- test/extensions/access_loggers/common/grpc_access_logger_test.cc
- test/extensions/access_loggers/open_telemetry/access_log_integration_test.cc
- test/extensions/access_loggers/open_telemetry/grpc_access_log_impl_test.cc
Commit Message: Change OpenTelemetry grpc access logger to use unary RPCs rather than streaming, to match the [non streaming OTLP RPC service](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/collector/logs/v1/logs_service.proto#L30-L34).
Additional Description: The OTel access logger used the existing Envoy GRPC client libraries which sent streamed messages, on a non-streaming RPC service. The result is usually that after every request->response the server closes the connection and the stream is reset. Sometimes, Envoy tries to send another log before the response from the server returns (and closes the stream), so the 2nd log is sent on a closed stream and gets lost.
Using unary RPCs, this shouldn't happen (tested and verified). …
> Change OpenTelemetry grpc access logger to use unary RPCs rather than streaming

- source/extensions/transport_sockets/http_11_proxy/connect.cc
- source/extensions/transport_sockets/http_11_proxy/connect.h
- test/extensions/transport_sockets/http_11_proxy/connect_test.cc
By the HTTP/1.1 spec, all headers are supposed to end with CRLF (\r\n)
Turns out the HTTP/1.1 spec also call out some broken legacy servers only return LF (\n")
Removing a performance optimization that was breaking on proxies with this bug.
Release Notes: not included
> http_11_proxy: fixing a bug with buggy proxies

- .circleci/config.yml
- mobile/docs/build.sh
- mobile/docs/publish.sh
This is the CI job that's responsible for building the public website docs at https://envoymobile.io.
Commit Message: mobile: add CircleCI docs generation CI job
Additional Description: This is the CI job that's responsible for building the public website docs at https://envoymobile.io.
Testing: In Envoy Mobile repo.
Docs Changes: Yes :)
Platform Specific Features: Only relevant to mobile.
Part of https://github.com/envoyproxy/envoy/issues/23758
> mobile: add CircleCI docs generation CI job

- .azure-pipelines/pipelines.yml
- fix stage dependency
- fix change detection
- add some debugging information
---
This fixes the `jq` expression to use "slurp" to ensure the json is a single list (and works with subsequent code), and adds some debugging info
also adds a `not(cancelled())` condition to the `check` stage as the dep on `env` is triggering this when the run is cancelled
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix change detection (part 2)

- .azure-pipelines/pipelines.yml
ci mostly passing coverage but occasionally timesout, sometimes when it has already completed the actual coverage tests.
the problem is worse on postsubmit and release branches due to less caching.
Signed-off-by: Ryan Northey ryan@synca.io
Risk Level:
Testing:
Docs Changes:
Release Notes:
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] ci: Increase coverage timeout (#24102)

- .circleci/config.yml
- .github/workflows/android_tests.yml
- .github/workflows/asan.yml
- .github/workflows/cc_tests.yml
- .github/workflows/coverage.yml
- .github/workflows/format.yml
- .github/workflows/perf.yml
- .github/workflows/python_tests.yml
- .github/workflows/tsan.yml
- mobile/third_party/rbe_configs/config/BUILD
This makes the build images used in mobile ci consistent with those in Envoy
it will also allow updating the github checkout action (cf #24123) which breaks due to the git version in the currently used images
NB: this changes the ubuntu version of the container 18 -> 20
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Bump mobile build images

- .github/workflows/asan.yml
- .github/workflows/cc_tests.yml
- .github/workflows/core.yml
- .github/workflows/coverage.yml
- .github/workflows/format.yml
- .github/workflows/perf.yml
- .github/workflows/release_validation.yml
- .github/workflows/tsan.yml
To help clarify their scope and purpose.
I only prefixed the generically-named CI jobs, I didn't prefix the ones that already have something mobile-themed in their name, like the jobs starting with `ios_` or `android_` or `python_`.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: prefix some CI jobs with `mobile_`

- source/extensions/http/header_validators/envoy_default/BUILD
- source/extensions/http/header_validators/envoy_default/error_codes.h
- source/extensions/http/header_validators/envoy_default/header_validator.cc
- source/extensions/http/header_validators/envoy_default/header_validator.h
- source/extensions/http/header_validators/envoy_default/http1_header_validator.cc
- source/extensions/http/header_validators/envoy_default/http2_header_validator.cc
- source/extensions/http/header_validators/envoy_default/path_normalizer.cc
- test/extensions/http/header_validators/envoy_default/BUILD
- test/extensions/http/header_validators/envoy_default/header_validator_test.cc
- test/extensions/http/header_validators/envoy_default/header_validator_test.h
- test/extensions/http/header_validators/envoy_default/http1_header_validator_test.cc
- test/extensions/http/header_validators/envoy_default/http2_header_validator_test.cc
- test/extensions/http/header_validators/envoy_default/path_normalizer_test.cc
Makes adding fuzz test targets easier.
> Break dependency loop in UHV headers

- source/extensions/clusters/common/logical_host.h
- test/extensions/clusters/common/BUILD
- test/extensions/clusters/common/logical_host_test.cc
- test/per_file_coverage.sh
Partt of https://github.com/envoyproxy/envoy/issues/24353
> coverage: adding tests, bumping up

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix change detection (part 3)

- mobile/bazelw
This pulls in a number of small but useful fixes: https://github.com/bazelbuild/bazelisk/compare/v1.10.1...v1.15.0
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile: update `bazelw` to pull bazelisk 1.15.0

- mobile/tools/vscode_compdb.sh
This script is still necessary for now because mobile can only be built from the mobile directory due to bazelrc magic. Let's fix the script in-place for now and hopefully clean it up later once mobile can be built from the top-level directory.
Verified that it runs successfully and seems to make vscode happy.
> Fix mobile/vscode_compdb script for repo merge

- contrib/kafka/filters/network/source/mesh/BUILD
- contrib/kafka/filters/network/source/mesh/command_handlers/BUILD
- contrib/kafka/filters/network/source/mesh/command_handlers/api_versions.cc
- contrib/kafka/filters/network/source/mesh/command_handlers/list_offsets.cc
- contrib/kafka/filters/network/source/mesh/command_handlers/list_offsets.h
- contrib/kafka/filters/network/source/mesh/request_processor.cc
- contrib/kafka/filters/network/source/mesh/request_processor.h
- contrib/kafka/filters/network/test/mesh/command_handlers/BUILD
- contrib/kafka/filters/network/test/mesh/command_handlers/list_offsets_unit_test.cc
- contrib/kafka/filters/network/test/mesh/request_processor_unit_test.cc
Commit Message: kafka: add support for list-offsets request
Additional Description: When Kafka consumer starts getting records from upstream Kafka cluster, the first request it sends to upstream is actually asking for its position (this data is then used in following requests, updated as records are received). As the offset management is going to be left to proxy/Envoy we can send a trivial `0` here, simplifying the code.
Required for https://github.com/envoyproxy/envoy/issues/24372
Testing: unit tests, full integration stack with Fetch requets
> kafka: add support for list-offsets request

- .github/workflows/android_build.yml
- .github/workflows/android_tests.yml
- .github/workflows/asan.yml
- .github/workflows/format.yml
- .github/workflows/tsan.yml
https://github.com/actions/setup-java/releases/tag/v3.8.0
This should fix a number of GitHub Actions deprecations:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/setup-java@v1
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional …
> ci: update `actions/setup-java` from v1 to v3.8

- mobile/.bazelrc
Works around https://github.com/bazelbuild/rules_swift/issues/949
Testing: Local: `./bazelw build --config=ios //library/swift:ios_framework`
Docs Changes:
Release Notes:
> mobile: build Swift with whole module optimization

- .github/workflows/android_build.yml
- .github/workflows/android_tests.yml
- .github/workflows/asan.yml
- .github/workflows/core.yml
- .github/workflows/coverage.yml
- .github/workflows/format.yml
- .github/workflows/ios_build.yml
- .github/workflows/ios_tests.yml
- .github/workflows/python_tests.yml
- .github/workflows/release_validation.yml
- .github/workflows/tsan.yml
- mobile/tools/should_run_ci.sh
But early-exit for changes that shouldn't impact Envoy Mobile.
On top of `mobile/**` changes and changes to workflow files, now when Envoy dependencies are updated in `bazel/repository_locations.bzl`, mobile CI jobs will run too.
Risk Level: Might cause issues with CI if a mistake was made
Testing:
Docs Changes:
Release Notes:
> ci: run mobile GitHub Actions on every PR

- envoy/server/factory_context.h
- source/common/quic/BUILD
- source/common/quic/envoy_quic_dispatcher.h
- source/common/quic/envoy_quic_proof_source.h
- source/common/quic/envoy_quic_proof_source_factory_interface.h
- source/common/quic/envoy_quic_server_connection.h
- source/extensions/matching/actions/format_string/BUILD
- source/extensions/matching/actions/format_string/config.cc
- source/extensions/matching/actions/format_string/config.h
- source/server/BUILD
- source/server/active_listener_base.h
- source/server/filter_chain_manager_impl.cc
- source/server/filter_chain_manager_impl.h
- source/server/listener_stats.h
- test/common/quic/BUILD
- test/common/quic/envoy_quic_dispatcher_test.cc
- test/extensions/matching/actions/format_string/config_test.cc
Risk Level: low (simply moving code around)
Testing: n/a
> downstream: refactoring code to remove listener hard deps

- envoy/http/codec.h
- mobile/library/common/http/client.h
- source/common/http/conn_manager_impl.cc
- source/common/http/http1/codec_impl.h
- source/common/http/http2/codec_impl.cc
- source/common/http/http2/codec_impl.h
- source/common/quic/envoy_quic_server_stream.h
- test/mocks/http/stream_encoder.h
Commit Message: Add setRequestDecoder to ResponseEncoder interface
Additional Description: This change was introduced in #23648 but was moved into a separate PR given its more general scope.
Testing: No tests added.
> Add setRequestDecoder to ResponseEncoder interface

- mobile/library/cc/engine_builder.cc
This file uses `this->` whenever referencing class members but it doesn't need to. Let's just ctrl-f and delete them all.
Unit tests still work!
> Remove uneccessary `this->` from mobile engine builder

- contrib/kafka/filters/network/source/mesh/BUILD
- contrib/kafka/filters/network/source/mesh/librdkafka_utils.h
- contrib/kafka/filters/network/source/mesh/librdkafka_utils_impl.cc
- contrib/kafka/filters/network/source/mesh/librdkafka_utils_impl.h
- contrib/kafka/filters/network/source/mesh/upstream_kafka_client_impl.cc
- contrib/kafka/filters/network/source/mesh/upstream_kafka_client_impl.h
- contrib/kafka/filters/network/test/mesh/BUILD
- contrib/kafka/filters/network/test/mesh/kafka_mocks.h
- contrib/kafka/filters/network/test/mesh/upstream_kafka_client_impl_unit_test.cc
Commit Message: kafka: cleanup librdkafka utils
Additional Description: Extract "librdkafka utilities" to dedicated headers/libs so they can be referenced by (future) consumer code (as we are going to have create-conf + set-conf + create-consumer steps all over again) for https://github.com/envoyproxy/envoy/issues/24372 . Same happens in tests.
Testing: unit tests, integration tests
> kafka: cleanup librdkafka utils

- mobile/library/common/config/config.cc
- mobile/library/common/extensions/filters/http/local_error/BUILD
- mobile/library/common/extensions/filters/http/local_error/filter.cc
- mobile/library/common/extensions/filters/http/network_configuration/BUILD
- mobile/library/common/extensions/filters/http/network_configuration/filter.cc
- mobile/library/common/extensions/filters/http/platform_bridge/filter.cc
- mobile/library/common/http/BUILD
- mobile/library/common/http/header_utility.cc
- mobile/library/common/http/header_utility.h
- mobile/test/common/integration/client_integration_test.cc
This changes swift's direct responses from being proxied upstream and handled by the "fake" (real) listener, to being handled locally, and bypassing the "do not forward local replies" logic in the onLocalReply classes
Commit Message: na/a
Risk Level: medium (mobile only)
part of https://github.com/envoyproxy/envoy/issues/24428
> swift: stop using loopback for direct responses

- test/per_file_coverage.sh
Coverage test is now failing with message `Code coverage for source/common/common/posix is lower than limit of 94.5 (92.7)`. Change it back to 92.7 which is the original coverage limits.
Signed-off-by: tyxia <tyxia@google.com>
> test_coverage: fix posix test coverage

- mobile/test/common/integration/base_client_integration_test.cc
- mobile/test/common/integration/base_client_integration_test.h
Some integration tests do not send data plane requests (we are building one such test now), so optionally allow those tests to skip stream metrics validation, controlled by a test knob.
> mobile: Enable BaseClientIntegrationTest to bypass stream metrics checks

- source/common/stats/histogram_impl.h
Commit Message: stats: setting default value for returned values
Our internal msan test fails here, because the 2 data-members could be directly fetched without these values being explicitly initialized. Initializing the values solves the issue.
There should not be any impact, as the explicit values are the also the default ones.
Testing: N/A.
> stats: setting default value for returned values

- .github/workflows/docs.yml
Skip this step for forks, since secrets aren't available to PRs from forks.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: only set up mobile docs deploy key for main repo

- .github/workflows/ios_build.yml
Failing due to a missing extension: https://envoyproxy.slack.com/archives/C02F93EEJCE/p1670613863641819
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: disable running the Objective-C integration app

- contrib/kafka/filters/network/source/mesh/BUILD
- contrib/kafka/filters/network/source/mesh/inbound_record.h
- contrib/kafka/filters/network/source/mesh/librdkafka_utils.h
- contrib/kafka/filters/network/source/mesh/librdkafka_utils_impl.cc
- contrib/kafka/filters/network/source/mesh/librdkafka_utils_impl.h
- contrib/kafka/filters/network/source/mesh/upstream_kafka_consumer.h
- contrib/kafka/filters/network/source/mesh/upstream_kafka_consumer_impl.cc
- contrib/kafka/filters/network/source/mesh/upstream_kafka_consumer_impl.h
- contrib/kafka/filters/network/test/mesh/BUILD
- contrib/kafka/filters/network/test/mesh/kafka_mocks.h
- contrib/kafka/filters/network/test/mesh/upstream_kafka_client_impl_unit_test.cc
- contrib/kafka/filters/network/test/mesh/upstream_kafka_consumer_impl_unit_test.cc
Commit Message: kafka: add upstream-kafka-consumer
Additional Description: Add the upstream Kafka consumer (analogous to already existing upstream Kafka producer). As it is performing blocking operations (`consume`) it needs to run in a dedicated worker thread to consume the records. Compared to the producer it is a bit more complex, as it does not always need to consume the records - first it needs to check whether there is anyone interested in these topics (== if there are unfinished `Fetch` requests received by the mesh filter). Part of https://github.com/envoyproxy/envoy/issues/24372.
Testing: unit tests, integration tests with full stack
> kafka: add upstream-kafka-consumer

- mobile/test/common/integration/base_client_integration_test.cc
- mobile/test/common/integration/base_client_integration_test.h
This will facilitate writing some Envoy Mobile tests where we want to start with a different base Bootstrap config.
> mobile: Allow passing a Bootstrap override to BaseClientIntegrationTest

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Skip build/release jobs if only mobile or docs changed

- source/common/network/utility.cc
- test/common/network/utility_test.cc
- test/config_test/config_test.cc
- test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc
- test/extensions/listener_managers/listener_manager/listener_manager_impl_test.h
- test/extensions/network/dns_resolver/cares/dns_impl_test.cc
Commit Message: use only `getaddrinfo` to parse IPv6
> Use getaddrinfo to parse IPv6 addresses to allow link local addresses

- .github/workflows/ios_build.yml
- mobile/envoy_build_config/BUILD
- mobile/envoy_build_config/extension_registry.cc
- source/extensions/listener_managers/listener_manager/listener_manager_impl.h
Additional Description: Register default listener. Envoy Mobile crashes in optimized builds without this change. The crash was introduced in https://github.com/envoyproxy/envoy/pull/24294. The objc hello world app CI job was disabled in https://github.com/envoyproxy/envoy/pull/24363 to make main green again.
Testing:
Docs Changes:
Release Notes:
> ci/mobile: register listener

- .github/workflows/docs.yml
The previous logic meant that we were never installing the deploy key.
E.g.: https://github.com/envoyproxy/envoy/actions/runs/3673844011/jobs/6211361666#step:7:7
Risk Level: No Envoy code changes, moderate risk of keeping this CI job broken in some cases.
Testing:
Docs Changes:
Release Notes:
> ci: fix check for forks in `mobile_docs` job

- .github/workflows/ios_build.yml
- mobile/envoy_build_config/BUILD
- mobile/envoy_build_config/extension_registry.cc
- source/common/quic/quic_transport_socket_factory.h
Additional Description: Re-enables CI job as it should be green again as https://github.com/envoyproxy/envoy/pull/24490 was merged
Testing:
Docs Changes:
Release Notes:
> ci: revert disable running the Objective-C integration app (#24478)"

- contrib/kafka/filters/network/source/kafka_types.h
- contrib/kafka/filters/network/source/mesh/BUILD
- contrib/kafka/filters/network/source/mesh/shared_consumer_manager.h
- contrib/kafka/filters/network/source/mesh/shared_consumer_manager_impl.cc
- contrib/kafka/filters/network/source/mesh/shared_consumer_manager_impl.h
- contrib/kafka/filters/network/source/mesh/upstream_config.cc
- contrib/kafka/filters/network/source/mesh/upstream_config.h
- contrib/kafka/filters/network/source/mesh/upstream_kafka_consumer.h
- contrib/kafka/filters/network/test/mesh/BUILD
- contrib/kafka/filters/network/test/mesh/command_handlers/metadata_unit_test.cc
- contrib/kafka/filters/network/test/mesh/shared_consumer_manager_impl_unit_test.cc
- contrib/kafka/filters/network/test/mesh/upstream_config_unit_test.cc
- contrib/kafka/filters/network/test/mesh/upstream_kafka_facade_unit_test.cc
Commit Message: kafka: add shared consumer manager
Additional Description: Stub for shared consumer manager. In future, SCM is going to be interacted-with by incoming Fetch requests, which are going to register themselves as callbacks for inbound fetch records. Part of https://github.com/envoyproxy/envoy/issues/24372.
Testing: unit tests, integration tests with full stack 
> kafka: add shared consumer manager

- mobile/library/objective-c/BUILD
- mobile/library/objective-c/EnvoyBridgeUtility.h
- mobile/library/objective-c/EnvoyEngineImpl.m
- mobile/library/objective-c/EnvoyKeyValueStoreBridgeImpl.h
- mobile/library/objective-c/EnvoyKeyValueStoreBridgeImpl.m
- mobile/test/objective-c/BUILD
- mobile/test/objective-c/EnvoyKeyValueStoreBridgeImplTest.m
Additional Description: Fixes a typo kind of bug in the implementation of the iOS platform key value store and adds a test coverage for iOS platform key value store to test other parts of the implementation and avoid regressions.
Docs Changes:
Release Notes:
> ios: fix platform key value store

- test/test_common/status_utility.h
- test/test_common/status_utility_test.cc
Commit Message: Make IsOkAndHolds matcher work with submatchers
Additional Description: Before this change you can do `IsOkAndHolds(5)` but not `IsOkAndHolds(Eq(5))`. Also, `IsOkAndHolds(unprintable_but_equality_comparable_value)` wouldn't build before this change, and will after.
Testing: Test-only.
> Make IsOkAndHolds matcher work with submatchers

- .github/workflows/docs.yml
Fixes https://github.com/envoyproxy/envoy/issues/24526
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: only publish mobile docs from `main` branch

- .azure-pipelines/pipelines.yml
prevent azp from checking out the repo when only echoing a success message
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Dont checkout repo for dependent/required jobs

- mobile/library/common/jni/BUILD
- mobile/test/java/integration/BUILD
- mobile/test/java/io/envoyproxy/envoymobile/engine/BUILD
- mobile/test/java/org/chromium/net/BUILD
- mobile/test/java/org/chromium/net/impl/BUILD
- mobile/test/java/org/chromium/net/testing/BUILD
- mobile/test/java/org/chromium/net/urlconnection/BUILD
- mobile/test/kotlin/integration/BUILD
- mobile/test/kotlin/integration/proxying/BUILD
- Remove unnecessary copts now that c++17 is the default.
- Rename libndk_envoy_jni.jnilib -> libndk_envoy_jni_jnilib to squelch warning
- Use ":base_java_jni_lib" instead of "base_java_jni_lib", per standards
- Depend on jni_utility_lib in base_java_jni_lib instead of duplicating the srcs
Fixes #24544
> Clean up mobile/library/common/jni/BUILD targets

- mobile/library/common/jni/BUILD
Remove unused linkopt on libenvoy_jni.so
> Remove unused linkopt on libenvoy_jni.so

- .azure-pipelines/pipelines.yml
this will allow us to flip the defaults for all of the other jobs and speed up CI
Fix #24551 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Set fetch depth/tags for `env` job explicitly

- contrib/kafka/filters/network/source/mesh/shared_consumer_manager.h
- contrib/kafka/filters/network/source/mesh/shared_consumer_manager_impl.cc
- contrib/kafka/filters/network/source/mesh/shared_consumer_manager_impl.h
- contrib/kafka/filters/network/source/mesh/upstream_kafka_consumer.h
- contrib/kafka/filters/network/test/mesh/shared_consumer_manager_impl_unit_test.cc
Commit Message: kafka: inbound record distributor/store
Additional Description: `RecordDistributor` object that's responsible for routing records to callbacks (downstream Fetch requests) that are waiting for these requests. Needs to be thread-safe just like it's owner SHM, as it's going to be accessed by multiple threads (from the callback side: multiple filters -> multiple worker threads, from the message side: kafka consumer's worker thread that pushes the messages in). Part of https://github.com/envoyproxy/envoy/issues/24372
Testing: unit tests, integration test with a full stack
> kafka: inbound record distributor/store

- bazel/dependency_imports.bzl
So we can do cross-compilation on macOS hosts.
This is how the rules_go folks recommend to do this in https://github.com/bazelbuild/rules_go/issues/3402.
Risk Level: Low, CI should 
Testing: Tested on CI and with RBE locally on an M1 Mac.
Docs Changes:
Release Notes:
> bazel: download Go SDKs for each supported platform

- bazel/dependency_imports.bzl
The include_rustc_srcs causes a warning now. If we setup rust_analyzer we should use the `rust_analyzer_toolchain_repository` for this. We also aren't using these mobile triples for now. We can add them back as needed.
Fixes https://github.com/envoyproxy/envoy/issues/24548
> bazel: remove unused rust setup

- docs/root/configuration/other_features/rate_limit.rst
Signed-off-by: Erik Engberg <ejohansson@spotify.com>
Commit Message: Remove duplicate paragraph in rate limiting docs
Additional Description: Lines 15-18 are duplicates of lines 20-23.
Testing: N/A
> Remove duplicate paragraph in rate limiting docs

- mobile/library/cc/engine_builder.h
- mobile/test/common/integration/base_client_integration_test.cc
- mobile/test/common/integration/base_client_integration_test.h
- mobile/test/common/integration/client_integration_test.cc
- mobile/test/common/integration/xds_integration_test.cc
Currently the unit test fixture inherits from the engine builder. This is mostly just a readability win and also allows setting up multiple builders within one test.
> Remove inheritance from base_client_integration_test to engine_builder

- api/envoy/extensions/filters/http/bandwidth_limit/v3/bandwidth_limit.proto
- changelogs/current.yaml
- source/extensions/filters/http/bandwidth_limit/bandwidth_limit.cc
- source/extensions/filters/http/bandwidth_limit/bandwidth_limit.h
- source/extensions/filters/http/common/stream_rate_limiter.cc
- source/extensions/filters/http/common/stream_rate_limiter.h
- source/extensions/filters/http/fault/fault_filter.cc
- test/extensions/filters/http/bandwidth_limit/filter_test.cc
- test/extensions/filters/http/common/stream_rate_limiter_test.cc
The original bandwidth delay use envoy histogram metric which include the data moving time, when payload is large, the original logic is not accurate, fix this bug by only calculate the waiting time for available tokens.
> [Bandwidth-Limit] Fix bandwidth delay calculation logic

- source/common/http/http2/codec_impl.cc
Commit Message: http2: Use uncheckedGetStream.
Use uncheckedGetStream() in a location where a null-stream is pretty fine due to null checks further on.
Testing: n/a
> http2: Use uncheckedGetStream.

- envoy/http/filter.h
- source/docs/flow_control.md
Commit Message: Recommend filters not decrease buffer limits
Additional Description: Just changing `flow_control.md` to recommend not calling `set(En|De)coderBufferLimit` when it would decrease the buffer limit, as that's likely to conflict with other filters, vs. increasing the limit is unlikely to cause conflicts. This is inspired by #23774, in which it turned out that a code solution to this awkwardness is not reasonable, so a documentation solution is the next best thing.
Risk Level: None, it's documentation.
Testing: No, it's documentation.
Docs Changes: Yes, it is.
> Recommend filters not decrease buffer limits

- mobile/library/cc/engine_builder.cc
Change the C++ engine builder to not override the stats_domain with an empty value
> Change the C++ engine builder to not override the stats_domain with an empty value

- mobile/test/common/integration/base_client_integration_test.cc
- mobile/test/common/integration/base_client_integration_test.h
We clarify that BaseClientIntegrationTest::defaultConfig *only* gets used if `override_builder_config_` is set to true.
The code is very confusing to read without knowing this.
> test: Add clarifying comments to BaseClientIntegrationTest

- source/extensions/filters/http/jwt_authn/jwks_async_fetcher.cc
- source/extensions/filters/http/jwt_authn/jwks_async_fetcher.h
- source/extensions/filters/http/jwt_authn/jwks_cache.cc
- test/extensions/filters/http/jwt_authn/filter_config_test.cc
- test/extensions/filters/http/jwt_authn/jwt_authn_corpus/clusterfuzz-testcase-minimized-jwt_authn_fuzz_test-5019912976596992
Fix jwt_auth_fuzz [bug](https://oss-fuzz.com/testcase-detail/5019912976596992)
It complains about the config `remote_jwks.duration.seconds` field is too big.
Testing:  Unit-tested
Release Notes:  None
> jwt_authn: Fix a jwt_authn fuzz bug about too big remote_jwks.duration

- ci/Dockerfile-envoy
The new distroless image "base-nossl" is available ( https://github.com/GoogleContainerTools/distroless/commit/521f5971e09959b8ae8a04cd989611f1a0767c7e ), use it.
> docker: Use the distroless base image without OpenSSL (base-nossl-debian11:nonroot)

- mobile/test/kotlin/integration/StatFlushIntegrationTest.kt
Since merging #24645, StatFlushIntegrationTest.kt fails reliably on CI and locally.
While trying to debug, let's temporarily disable the test.
See #24657 for details.  Note that it doesn't seem like StatFlushIntegrationTest was working, even before #24645 as detailed in https://github.com/envoyproxy/envoy/issues/24657#issuecomment-1362224102
> mobile: Disable Kotlin StatFlushIntegrationTest

- envoy/http/codes.h
- envoy/upstream/resource_manager.h
- source/common/router/config_impl.cc
- source/common/router/config_impl.h
Reduce Route memory utilization by reducing  alignment overhead.
The PR re-arranges class members so that small ones (bools and enums) are last members, instead of being sprayed between larger data types. This reduces alignment overhead, and shrinks Route size by 72 bytes.
For additional size reduction, small enum classes are qualified with smaller integer types, so that they use 1 or 2 bytes, instead of the default 4.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
> Reduce Route memory utilization by reducing  alignment overhead

- mobile/envoy_build_config/BUILD
- mobile/envoy_build_config/extension_registry.cc
- mobile/examples/objective-c/hello_world/ViewController.m
- mobile/library/common/extensions/key_value/platform/config.cc
- mobile/library/common/extensions/key_value/platform/config.h
- mobile/library/swift/KeyValueStore.swift
Additional Description: Make `addKeyValueStore...` method on the `EngineBuilder` available to objc code by adding `@objc` attribute to `KeyValueStore` protocol. Fix the crash caused by the the lack of registration of `PlatformKeyValueStoreConfig` type.
Testing: objc hello world app ci job
Docs Changes:
Release Notes:
> mobile: dns cache registration

- mobile/bazelw
- mobile/remote
Envoy Mobile project developers can use EngFlow's RBE to speed up and offload local builds to EngFlow's remote execution cluster.
Most bazel commands should work by replacing `./bazelw` with `./remote`.
For example:
```console
$ ./remote build --config ios ios_dist
$ ./remote build --config android android_dist
```
With certificates places in the `mobile/tmp/certs` directory (which is ignored by git), it should "just work".
Note that `protoc` commands fail with a "Bad CPU type in executable" error message when using RBE on an M1 Mac with an arm64 bazel binary, so to work around this we tell `bazelw` to use the amd64 version, which appears to work just fine.
Risk Level: Low, only used for local development.
Testing: Local on an M1 Mac.
Docs Changes: …
> mobile: add `./remote` helper

- source/common/router/config_impl.cc
- source/common/router/config_impl.h
Reduce Route memory utilization by avoiding `absl::optional` overhead for optional timeouts.
`std::duration` values wrapped in an absl::optional take twice as much memory as the durations themseves -- 16 bytes for each optional milliseconds value.
This PR removes the optional overhead by
1. Packing all timeouts into a separate data structure, sharing a single bool to track which timeout is set. This saves 8 bytes per timeout.
2. Not creating the data structure at all, if none of the optional timeouts are present. This saves another 8 bytes per timeout, for routes that don't configure them.
There are 6 optional timeouts, so this saves either 40 or 90 bytes per route.
Signed-off-by: Yury Kats …
> Reduce Route memory utilization by avoiding `absl::optional` overhead for optional timeouts

- docs/root/configuration/http/http_conn_man/header_casing.rst
Commit Message: clarify stateful formatter docs
Additional Description: clarify stateful formatter docs to indicate headers added by envoy and other filters will still be lowercased.
Testing: N/A
> clarify stateful formatter docs

- source/server/admin/stats_request.cc
https://clang.llvm.org/extra/clang-tidy/checks/misc/uniqueptr-reset-release.html
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Fix clang-tidy `misc-uniqueptr-reset-release` warning

- source/common/router/config_impl.cc
https://clang.llvm.org/extra/clang-tidy/checks/performance/inefficient-vector-operation.html
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Fix clang-tidy `performance-inefficient-vector-operation` warning

- envoy/upstream/upstream.h
- source/common/upstream/upstream_impl.h
- source/extensions/upstreams/http/config.cc
- source/extensions/upstreams/http/config.h
- test/mocks/upstream/cluster_info.h
this makes it easier to reason about immutability of shared config objects
> Make ProtocolOptionsConfigImpl const correct

- mobile/library/cc/headers_builder.cc
- source/common/protobuf/utility.cc
- source/common/router/config_impl.cc
- source/extensions/http/header_validators/envoy_default/http1_header_validator.cc
https://clang.llvm.org/extra/clang-tidy/checks/performance/faster-string-find.html
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Fix clang-tidy `performance-faster-string-find` warning

- source/common/http/http1/codec_impl.cc
- test/common/http/http1/codec_impl_test.cc
- test/extensions/filters/http/health_check/health_check_integration_test.cc
- test/integration/drain_close_integration_test.cc
- test/integration/integration_test.cc
- test/integration/protocol_integration_test.cc
This makes the following integration tests pass with BalsaParser:
DownstreamProtocolIntegrationTest.LargeRequestHeadersRejected DownstreamProtocolIntegrationTest.LargeRequestTrailersRejected DownstreamProtocolIntegrationTest.LargeRequestUrlRejected DownstreamProtocolIntegrationTest.VeryLargeRequestHeadersRejected
The following tests, also re-enabled here for BalsaParser, were already passing without the change in ConnectionImpl::dispatchSlice():
DownstreamProtocolIntegrationTest.InvalidRequestHeaderName DownstreamProtocolIntegrationTest.InvalidResponseHeaderName DrainCloseIntegrationTest.AdminDrain
HealthCheckIntegrationTest.HealthCheckWithoutServerStats IntegrationTest.BadFirstline
IntegrationTest.UpstreamProtocolError …
> [balsa] Set error code to 431 for too large headers.

- source/common/http/http1/balsa_parser.cc
- test/common/http/http1/codec_impl_test.cc
- test/integration/protocol_integration_test.cc
Signal an error when BalsaParser::execute() is called with zero length except for the already handled special cases. Reset `headers_done_` in BalsaParser::MessageDone(). Add a number of tests for EOF handling and other special cases.
Balsa work tracking issue: #21245
Fixes #24557.
Risk Level: low, changed code protected by existing default-false runtime flag.
Runtime guard: envoy.reloadable_features.http1_use_balsa_parser
> [balsa] Fix EOF handling.

- test/per_file_coverage.sh
reinstating HCM coverage, bumping a few others, and adding verbose logging 
Testing: CI
> coverage: reinstating prior bar

- test/extensions/filters/http/custom_response/custom_response_integration_test.cc
mutable_type_url() methods of any.proto is a private method in some systems.
Using mutable_type_url()->assign() in those systems cause build failure. Replacing it with set_type_url() which is a public method.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Fixing a CEP filter test failure due to using private mutable_type_url() methods of any.proto

- mobile/library/common/config/config.cc
Commit Message: Converting regex matches to prefix matches as the former are way more costly. This is supposed to help with Envoy Mobile initialization times. The changes increase the number of stats that are enabled with default configuration of Envoy Mobile from 317 to 461. The profiling did not show any significant performance impact of this change but in theory reducing the number of places where we use regex should help.
Additional Description: related PR https://github.com/envoyproxy/envoy/pull/24521
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_che …
> config/perf: use prefix matchers instead of regexes

- source/common/router/config_impl.cc
- source/common/router/config_impl.h
Reduce Route memory utilization by avoiding weighted clusters config overhead when no such clusters are configured
Currently each Route instance contains 3 member variables that are representing weighted clusters config, whether the route has such clusters or not. For routes without weighted clusters that's 56 bytes overhead (empty vector, empty string, int64).
This PR packs all weighted cluster related config into a separate data structure and only creates an instance of it when the route has such clusters. This is saving 50 bytes for any route that does not have weighted clusters.
Risk Level:
Testing:
Docs Changes:
Release …
> Reduce Route memory utilization by avoiding weighed clusters config overhead when no such clusters are configured

- changelogs/current.yaml
- source/extensions/common/aws/credentials_provider_impl.cc
- source/extensions/common/aws/credentials_provider_impl.h
- source/extensions/common/aws/utility.cc
- test/extensions/common/aws/aws_metadata_fetcher_integration_test.cc
- test/extensions/common/aws/credentials_provider_impl_test.cc
Signed-off-by: Sunil Narasimhamurthy <sunnrs@amazon.com>
Commit Message: aws: fetch EC2 instance role credentials securely a.k.a IMDSv2
Additional Description: Use token to fetch the credentials from EC2 Instance Metadata
Fixes: #24592
> aws: fetch EC2 instance role credentials securely aka IMDSv2

- ci/Dockerfile-envoy-distroless
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.21] docker: Use distroless-nossl

- test/extensions/transport_sockets/tls/ssl_socket_test.cc
https://github.com/envoyproxy/envoy/pull/24483 added below test 
TEST_P(SslSocketTest, MultiCertWithFullScanDisabledOnSniMismatch) {
and a runtime flag: 
RUNTIME_GUARD(envoy_reloadable_features_no_full_scan_certs_on_sni_mismatch);
However, the test is specific to the case when the runtime flag is true.  If the flag is false, this test does not work and crashing.
Explicitly set no_full_scan flag to true for this TLS test case to get test cases pass regardless the default flag setting.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
> Explicitly set  no_full_scan flag to true for a TLS test case which requires it

- source/common/router/config_impl.cc
Reduce VirtualHost memory utilization by avoiding Stats scope for virtual clusters when no virtual clusters are present.
Currently every virtual host always creates a stats scope for virtual clusters, but that scope is only used when there are actual virtual clusters present. If no such clusters exist, the scope is just memory overhead.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Reduce VirtualHost memory utilization by avoiding Stats scope for virtual clusters when no virtual clusters are present

- source/exe/BUILD
This sets up the stripped main library to not pull in all extensions (which in monorepo, pulls in all upstream Envoy extensions).
Risk Level: Low for Envoy, Medium for Envoy Mobile (worst case explicitly link your extensions)
Testing: CI
> build: removing optional extensions from stripped_main_base

- docs/root/configuration/http/http_filters/lua_filter.rst
Signed-off-by: RRobot-lm <RRobot-lm@users.noreply.github.com>
Commit Message: Lua: describe the get result when multiple headers have the same key
Testing: N/A
Release Notes:
Fixes #24718
> Lua: describe the get result when multiple headers have the same key

- mobile/docs/root/intro/version_history.rst
- mobile/library/kotlin/io/envoyproxy/envoymobile/grpc/GRPCStream.kt
- mobile/library/swift/grpc/GRPCStream.swift
- mobile/test/kotlin/integration/BUILD
- mobile/test/kotlin/integration/CancelGRPCStreamTest.kt
- mobile/test/kotlin/io/envoyproxy/envoymobile/GRPCStreamTest.kt
- mobile/test/swift/GRPCStreamTests.swift
- mobile/test/swift/integration/BUILD
- mobile/test/swift/integration/CancelGRPCStreamTest.swift
Commit Message: Expose `cancel` method on a gRPC stream.
Risk Level: Low, new API
Testing: Unit/integration tests
Docs Changes:
Release Notes:
> mobile grpc: expose cancel method on a stream

- test/common/http/http1/codec_impl_test.cc
Also simplify some EXPECT_CALL().WillOnce(Invoke()) constructs.
Commit Message: [balsa] Remove unused ResponseEncoder* variables from codec_impl_test.
Risk Level: n/a, test-only change
> [balsa] Remove unused ResponseEncoder* variables from codec_impl_test.

- mobile/.bazelrc
- source/common/runtime/BUILD
Move the copt for ABSL_FLAGS_STRIP_NAMES from the .bazelrc to the appropriate BUILD file
Testing: CI
> Move the copt for ABSL_FLAGS_STRIP_NAMES from the .bazelrc to the appropriate BUILD file

- source/common/config/new_delta_subscription_state.cc
Commit Message: fix map name in state tracking
Seems that this is a copy-paste error. Fixing var name.
Testing: N/A.
> delta-xds: fix map name in state tracking

- mobile/library/cc/BUILD
envoy_engine_cc_lib_no_stamp is insufficient by itself. engine_builder_lib is required because it's the target that exports the engine_builder.h header. And anyone using a stamped binary needs access to envoy_engine_cc_lib.
Signed-off-by: Michael Bradshaw <mjbshaw@google.com>
Commit Message: Make Envoy Mobile's C++ targets public
Additional Description: envoy_engine_cc_lib_no_stamp is insufficient by itself. engine_builder_lib is required because it's the target that exports the engine_builder.h header. And anyone using a stamped binary needs access to envoy_engine_cc_lib.
Testing: None, honestly.
> Make Envoy Mobile's C++ targets public

- bazel/envoy_binary.bzl
When using only the command line tools (not a full Xcode installation) on macOS, bazel does not pass `-fobjc-link-runtime` and therefore does not link to the CoreFoundation framework, which is required by absl. This adds the required framework, and makes this a linker error instead of a runtime error for the future.
Fixes https://github.com/envoyproxy/envoy/issues/24782
> bazel: fix missing framework on macOS

- docs/root/configuration/listeners/stats.rst
This patch fixes a tiny format issue in [Per-handler Listener Stats](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats#per-handler-listener-stats).
The table has two empty rows (please find the rows under `downstream_cx_active`) due to invalid table end line.
Testing: n/a
> docs: Fix the invalid end of table

- source/common/grpc/codec.cc
- source/common/grpc/codec.h
Commit Message: Clean up byte-swapping operations in grpc/codec.cc
Additional Description: The review of #23847 suggested we don't like raw byte-shifting operations. This change removes the raw byte-shifting operations from codec.cc (the only non-test code that still does this sort of thing), and also removes some unnecessary double-indexing from the state machine.
Risk Level: Very low, should be effectively a no-op change, just cleanup.
Testing: Continues to pass existing tests.
> Clean up byte-swapping operations in grpc/codec.cc

- .github/workflows/android_build.yml
- mobile/ci/mac_start_emulator.sh
Wait at most 5 minutes for the emulator to start.  A more correct solution would be to find a better way to determine if the emulator is actually booted, but hopefully this fails faster, at least.
Bug: #24841
Risk Level: Low - CI only
Testing: CI
> Wait at most 5 minutes for the emulator to start

- mobile/library/cc/retry_policy.cc
https://clang.llvm.org/extra/clang-tidy/checks/performance/inefficient-vector-operation.html and
https://releases.llvm.org/5.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/readability-container-size-empty.html
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Fix clang-tidy warnings

- source/common/rds/rds_route_config_provider_impl.cc
- source/common/rds/rds_route_config_subscription.cc
- source/common/rds/rds_route_config_subscription.h
- source/common/router/rds_impl.cc
- source/common/router/vhds.cc
- source/common/router/vhds.h
- test/common/router/rds_impl_test.cc
- test/common/router/vhds_test.cc
Reduce RDS subscription memory overhead by removing unnecessary `absl:optional`
Wrapping a raw pointer in `absl::optional` does not provide much value, but adds extra 8 bytes of memory overhead. A nullptr conveys the same meaning as "no value".
This PR switches `absl::optional<RouteConfigProvider*>` to just `RouteConfigProvider*` and `has_value` checks with checks against nullptr.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
> Reduce RDS subscription memory overhead by removing unnecessary `absl:optional`

- source/common/common/backoff_strategy.cc
- source/common/common/backoff_strategy.h
Hi,
this is my first time contributing to this project.
I noticed that the `std::min()` call in the exponential backoff interval calculation wasn't needed since `backoff <= max_interval` is already guaranteed, so I removed the call.
Additionally, since `max_interval` is const,  I added a const member for the "halfway point" when checking whether we can double again or clamp to max. Trying this in godbolt it seemed to get rid of the div/shift. Hope this is okay, tested it locally and UTs where green.
Best, 
Frank
Testing: Unit Test (backoff_strategy_test)
[Optional [API …
> common: refactor exponential backoff calculation

- mobile/tools/should_run_ci.sh
Commit Message: ci: run all mobile CI jobs on `main`
Additional Description: This will give us more visibility when changes that break Envoy Mobile land in Envoy. Slack discussion: https://envoyproxy.slack.com/archives/C02QMNG92A3/p1673288665957089
Risk Level: Moderate on CI stability, low on the Envoy libraries themselves
Testing: CI, these jobs have already been running for nearly two months on PRs with mobile/deps changes
> ci: run all mobile CI jobs on `main`

- api/envoy/extensions/filters/http/on_demand/v3/on_demand.proto
Signed-off-by: Jacek Ewertowski <jewertow@redhat.com>
Commit Message: Clarify that on-demand CDS does not support SotW xDS
Testing: n/a
Docs Changes: It's a doc change.
I was trying to configure on-demand CDS in an Istio ingress-gateway, but the process failed with the following error:
```
2023-01-04T13:38:10.587354Z     critical        envoy assert    panic: not supported
2023-01-04T13:38:10.587411Z     critical        envoy backtrace Caught Aborted, suspect faulting address 0x5390000001e
2023-01-04T13:38:10.587416Z     critical        envoy backtrace Backtrace (use tools/stack_decode.py to get line numbers):
2023-01-04T13:38:10.587418Z     critical        envoy backtrace Envoy version: …
```
> Clarify that on-demand CDS does not support SotW xDS

- .github/workflows/android_build.yml
- mobile/ci/mac_start_emulator.sh
And if 5 minutes elapses, assume the emulator booted successfully and we missed the `sys.boot_completed` event.
Remove the `timeout-minutes` setting on the GitHub Actions job definitions so we only consider booting the emulator in the timeout and not installing the SDK or creating the emulator.
Bug: #24841
Risk Level: Low - CI only
Testing: CI
> ci: wait up to 5 minutes for Android emulator to start

- mobile/test/swift/integration/CancelGRPCStreamTest.swift
Commit Message: That test is flaky. It continues to fail due to a wrong order in which expectations are fulfilled - there appears to be some kind of a race condition in there. Making the problematic test weaker by making it not check the order in which expectations are fulfilled.
Testing: 
Docs Changes:
Release Notes:
> ci: fix flaky swift test

- source/extensions/filters/network/mongo_proxy/bson_impl.cc
- test/extensions/filters/network/mongo_proxy/bson_impl_test.cc
Fixes a possible OOB read in removeString of the bson parser. The std::string constructor relies on finding a null-byte, but should rely on the bounds-checked length given by the line format.
Signed-off-by: Robert Femmer <robert.femmer@x41-dsec.de>
> mongo proxy bson: fix OOB read in removeString

- mobile/library/cc/engine.cc
- mobile/library/cc/engine.h
- mobile/test/common/integration/base_client_integration_test.cc
Add a destructor to Envoy::Platform::Engine which calls terminate()
> Add a destructor to Envoy::Platform::Engine which calls terminate()

- test/test_common/file_system_for_test.cc
Non-64-bit ARM builds fail to compile without the static cast from uint64_t to size_t when calling the std::string constructor.
> test: Add explicit static casting to size_t in the string ctor

- source/common/http/http2/codec_impl.cc
- source/common/http/http2/codec_impl.h
- source/common/http/http2/protocol_constraints.cc
- source/common/http/http2/protocol_constraints.h
- test/common/http/http2/protocol_constraints_test.cc
Commit Message: Removes nghttp2-specific names and types from CodecImpl. Cleanup related to https://github.com/envoyproxy/envoy/issues/23596.
Testing: ran http and integration tests locally
Docs Changes:
Release Notes:
> http2: updates method signatures to remove nghttp2-specific names and types.

- mobile/test/swift/integration/CancelGRPCStreamTest.swift
- mobile/test/swift/integration/CancelStreamTest.swift
- mobile/test/swift/integration/FilterResetIdleTest.swift
- mobile/test/swift/integration/GRPCReceiveErrorTest.swift
- mobile/test/swift/integration/IdleTimeoutTest.swift
- mobile/test/swift/integration/ReceiveErrorTest.swift
- mobile/test/swift/integration/ResetConnectivityStateTest.swift
- mobile/test/swift/integration/SendDataTest.swift
- mobile/test/swift/integration/SendHeadersTest.swift
- mobile/test/swift/integration/SendTrailersTest.swift
- mobile/test/swift/integration/SetLoggerTest.swift
Commit Message: Saw another timeout in Swift `ResetConnectivityStateTest` ([link](https://github.com/envoyproxy/envoy/actions/runs/3897119069/jobs/6654451915)). Decided to go through Swift integration tests and bump timeout values used in them so that they match their Android counterparts. This should help to remove some of the flakiness from our tests.
Testing:
Docs Changes:
Release Notes:
> ci: increase timeouts in swift integration tests

- source/common/http/http2/codec_impl.cc
- source/common/http/http2/codec_impl.h
Commit Message: Removes nghttp2 types from CodecImpl method signatures. Cleanup related to https://github.com/envoyproxy/envoy/issues/23596.
Additional Description: This will make it easier to implement http2::adapter::Http2VisitorInterface in the future.
Testing: ran unit tests and integration tests locally
Docs Changes:
Release Notes:
> http2: removes nghttp2 types from CodecImpl method signatures

- contrib/client_ssl_auth/filters/network/test/client_ssl_auth_test.cc
- contrib/cryptomb/private_key_providers/test/ops_test.cc
- contrib/dynamo/filters/http/test/dynamo_filter_test.cc
- contrib/dynamo/filters/http/test/dynamo_stats_test.cc
- contrib/kafka/filters/network/test/broker/filter_protocol_test.cc
- contrib/kafka/filters/network/test/metrics_integration_test.cc
- contrib/mysql_proxy/filters/network/test/mysql_filter_test.cc
- contrib/postgres_proxy/filters/network/test/postgres_filter_test.cc
- contrib/postgres_proxy/filters/network/test/postgres_integration_test.cc
- contrib/rocketmq_proxy/filters/network/test/active_message_test.cc
- contrib/rocketmq_proxy/filters/network/test/conn_manager_test.cc
- contrib/rocketmq_proxy/filters/network/test/mocks.cc
- contrib/sip_proxy/filters/network/test/conn_manager_test.cc
- contrib/sip_proxy/filters/network/test/decoder_test.cc
- contrib/sip_proxy/filters/network/test/mocks.cc
- contrib/sip_proxy/filters/network/test/router_test.cc
- contrib/sip_proxy/filters/network/test/tra_test.cc
- contrib/sxg/filters/http/test/filter_test.cc
- envoy/stats/store.h
- test/extensions/network/dns_resolver/apple/apple_dns_impl_test.cc
Commit Message: Last of 3 PRs to remove dependencies on Store::operator Scope&().
Additional Description: This fixes technical debt that was taken in https://github.com/envoyproxy/envoy/pull/23851 and partially resolved in https://github.com/envoyproxy/envoy/pull/24567 and https://github.com/envoyproxy/envoy/pull/24843 in order to solve a structural problem where Stats::Store was a subclass of Stats::Scope, which didn't make OO sense (a Store is not a Scope), but was convenient (you could pass a Store into a function that was expecting a Scope), and the Store worked as a root Scope. That needed to be cleaned up to clarify the ownership model where Store is typically instantiated directly in a production factory or test, and Scope is always held by shared_ptr.
We still need one more PR …
> stats: Remove operator Scope hack phase 3/3 (see #24567 and #24843)

- mobile/library/cc/log_level.h
Add // IWYU: export to log_level.h in order to fix a clang-tidy error which shows up internally.
> Add // IWYU: export to log_level.h

- mobile/library/java/org/chromium/net/EffectiveConnectionType.java
- mobile/library/java/org/chromium/net/NetworkQualityObservationSource.java
Signed-off-by: Renjie Tang <renjietang@google.com>
Commit Message: add enums in Cronvoy to match Cronet interface
Additional Description: In Cronet, those java enums are generated from the native code as such: https://source.chromium.org/chromium/chromium/src/+/main:net/BUILD.gn;l=1724. In Cronvoy, we don't have such native code. Thus we need to manually create the enum classes so that Cronvoy customers get the full API.
Testing: n/a
Platform Specific Features: Android only
> [Envoy-mobile]add enums in Cronvoy to match Cronet interface

- mobile/test/java/org/chromium/net/impl/CancelProofEnvoyStreamTest.java
Avoid a race condition in CancelProofEnvoyStreamTest by creating the CountDownLatch before starting the thread which uses it to countdown.
> Avoid a race condition in CancelProofEnvoyStreamTest

- source/common/api/BUILD
Without this, building test/common/... on Android fails because "os_sys_calls_impl_linux.h" can not be found when included in api/mocks.h.
> build: Add Android explicitely to the os_sys_calls_lib select

- mobile/library/cc/engine_builder.cc
- mobile/test/cc/unit/envoy_config_test.cc
Allow C++ engine builder to use platform cert verification on iOS.
Remove PANIC from the engine builder since we do actually support platform cert verification on iOS and update test expectations accordingly.
> Allow C++ engine builder to use platform cert verification on iOS

- .github/workflows/ios_build.yml
- .github/workflows/release_validation.yml
- mobile/.bazelrc
- mobile/ci/start_ios_simulator.sh
Similar to https://github.com/envoyproxy/envoy/pull/24919 but this time for iOS.
Instead of relying on `bazel run` to launch the simulator, we do this ahead of time so we can retry that step if it fails.
Slack discussion: https://envoyproxy.slack.com/archives/C02F93EEJCE/p1673618671587659
Risk Level: Low, CI only
Testing:
Docs Changes:
Release Notes:
> mobile: retry starting iOS Simulator up to 3 times

- mobile/library/common/jni/BUILD
Commit Message: Without this option the app crashes when attempted to being launched on arm64 emulator. The `ldl` flag was removed in https://github.com/envoyproxy/envoy/pull/24806.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile linker: add 'ldl' linker option

- contrib/sxg/filters/http/source/config.cc
- contrib/sxg/filters/http/test/config_test.cc
- contrib/sxg/filters/http/test/filter_test.cc
- envoy/secret/secret_manager.h
- source/common/secret/secret_manager_impl.cc
- source/common/secret/secret_manager_impl.h
- source/extensions/filters/http/oauth2/config.cc
- source/extensions/transport_sockets/tls/context_config_impl.cc
- test/common/secret/secret_manager_impl_test.cc
- test/extensions/filters/http/oauth2/config_test.cc
- test/extensions/filters/http/oauth2/filter_test.cc
- test/extensions/filters/http/oauth2/oauth_integration_test.cc
- test/integration/sds_generic_secret_integration_test.cc
- test/mocks/secret/mocks.h
* Pass correct transport_socket_factory to the secret manager
Signed-off-by: Vikas Choudhary <choudharyvikas16@gmail.com>
* Fix mocks
Signed-off-by: Vikas Choudhary <choudharyvikas16@gmail.com>
* update tests and add code comment
Signed-off-by: Vikas Choudhary <choudharyvikas16@gmail.com>
* Fix sxg http filter as well
Signed-off-by: Vikas Choudhary <choudharyvikas16@gmail.com>
* Adjust another test
Signed-off-by: Vikas Choudhary <choudharyvikas16@gmail.com>
* Add regression test
Signed-off-by: Vikas Choudhary <choudharyvikas16@gmail.com>
* Add integration test
Signed-off-by: Vikas Choudhary <choudharyvikas16@gmail.com>
* Revert "Add regression test"
This reverts commit 8a14c3dc328b6e739d91bc34ebf5f84e4812438b.
Signed-off-by: Vikas Choudhary <choudharyvikas16@gmail.com>
* fix format …
> [backport/1.24] Pass correct init manager to the secret manager (#23356)

- mobile/library/common/config/config.cc
Commit Message: As a result of changes from https://github.com/envoyproxy/envoy/pull/24733 we ended up increasing the number of enabled stats from 317 to 462. We did not really want to increase the number of enabled stats but doing this was required if we wanted our stats inclusion list to use as many `prefix`es that end up with a dot "." character as possible. That kind of `prefix`es are optimized in a special way that we hoped would help us to improve envoy mobile launch times. Since then, we learnt that as they are now upload of Envoy Mobile stats consumes a lot of bandwidth and we are working on balancing the app launch time with the use of network bandwidth - for this reason, we decided to disable some of the stats enabled in https://github.com/envoyproxy/envoy/pull/24733. We are not …
> mobile: reducing the number of enabled Envoy stats

- source/common/http/http2/codec_impl.cc
- source/common/http/http2/codec_impl.h
Commit Message: Removes nghttp2_data_provider from CodecImpl. Cleanup related to https://github.com/envoyproxy/envoy/issues/23596.
Testing: ran unit test and integration tests locally
Docs Changes:
Release Notes:
> http2: simplifies CodecImpl by implementing http2::adapter::DataFrameSource directly

- api/envoy/config/route/v3/route_components.proto
- source/common/router/config_impl.cc
- test/common/router/config_impl_test.cc
Commit Message: weighted-clusters: validate that total sum of weights does not exceed max uint32
Adds additional validation that the sum of weights of weighted clusters in a route does not exceed max uint32.
Risk Level: low - although this is a new validation, previously there was a similar validation when [total_weight](https://github.com/envoyproxy/envoy/blob/93b76c70ae0153452109934818c805b63d8f1221/api/envoy/config/route/v3/route_components.proto#L483) was used.
Testing: Added unit test
> weighted-clusters: validate that total sum of weights below max int

- envoy/upstream/upstream.h
- source/common/upstream/load_balancer_impl.h
- source/common/upstream/maglev_lb.cc
- source/common/upstream/maglev_lb.h
- source/common/upstream/ring_hash_lb.cc
- source/common/upstream/ring_hash_lb.h
- source/common/upstream/subset_lb.cc
- source/common/upstream/subset_lb.h
- source/common/upstream/upstream_impl.cc
- source/common/upstream/upstream_impl.h
- test/common/upstream/load_balancer_benchmark.cc
- test/common/upstream/maglev_lb_test.cc
- test/common/upstream/ring_hash_lb_test.cc
- test/common/upstream/round_robin_load_balancer_fuzz_test.cc
- test/mocks/upstream/cluster_info.cc
- test/mocks/upstream/cluster_info.h
Commit Message: Changes how LB policies are stored to save memory
Changed how some of these configs are stored to be unique_ptr instead of optionals. This will help save memory in cases where some of these policies are not set or used.
This will save a percentage of memory used by ClusterInfo and Subset_Lb
sizeof() test results:
Without these changes:
ClusterInfoImpl: 2896
Subset_LB: 536
With these changes:
ClusterInfoImpl: 2704
Subset_Lb: 384
Testing: Updated existing load balancing tests to ensure success with new types
> upstream: lb policy configuration memory optimization

- source/common/upstream/upstream_impl.cc
- test/common/upstream/cluster_manager_impl_test.cc
- test/common/upstream/upstream_impl_test.cc
Commit Message: only throw when the load_balancing_policy and specific fields of common_lb_config are set
An exception will be throwed when the common_lb_config and load_balancing_policy are set in the same time in the previous implemention.
But in fact, It should only throw an exception when the specific fields of common_lb_config and load_balancing_policy are set.
This PR correct it to make the behavior more appropriate.
Testing: Unit.
> only throw when the load_balancing_policy and specific fields of common_lb_config are set

- source/extensions/transport_sockets/tls/cert_validator/default_validator.cc
- source/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator.cc
`STACK_OF(T)`'s comparison functions take a double pointer (the double pointer is silly, but it dates to C `qsort`). Both pointers are supposed to be const, but we incorrectly only marked one as const in BoringSSL. I.e. our type is `const T **`. In OpenSSL, the type is `const T *const *` https://www.openssl.org/docs/man1.1.1/man3/DEFINE_SPECIAL_STACK_OF.html
We plan on switching BoringSSL to match OpenSSL in https://boringssl-review.googlesource.com/c/boringssl/+/56190, making it both more const-correct and to remove an unnecessary OpenSSL/BoringSSL API divergence.
To avoid Envoy breaking, this patch switches the call sites to C++14 generic lambdas. This will keep Envoy compatible both before and after that PR. Once your minimum BoringSSL revision moves past that CL, you …
> tls: Use a generic lambda for BoringSSL comparison functions

- source/extensions/filters/network/zookeeper_proxy/decoder.cc
- test/extensions/filters/network/zookeeper_proxy/filter_test.cc
Signed-off-by: Zhewei Hu <zhu@pinterest.com>
Commit Message: ZK filter: add RelativeZxid support for SetWatches requests
Additional Description: When parsing the SetWatches requests, we noticed some decoder errors. After looking into the requests bytes, we found that the [RelativeZxid](https://github.com/apache/zookeeper/blob/master/zookeeper-jute/src/main/resources/zookeeper.jute#L78) was not skipped during the decoding. This diff try to skip RelativeZxid then the filter could parse later watches data correctly without raising the "read beyond the max length" or "packet is too big" errors.
> ZK filter: add RelativeZxid support for SetWatches requests

- source/extensions/filters/network/zookeeper_proxy/decoder.cc
- test/extensions/filters/network/zookeeper_proxy/filter_test.cc
Commit Message: ZK filter: Fix "buffer underflow" error
Additional Description: When using ZK filter, we noticed some decoder errors. After looking into the issue, we found that some create requests had negative data len without real data and then the ZK filter failed to parse/skip the real data. Negative data len is because the data fetched from buffer is `0xffffffff` in our case, and the type of `len` is `int32_t`. Since the data is beyond the max value of int32, it becomes negative.
Signed-off-by: Zhewei Hu \<zhu@pinterest.com\>
> ZK filter: Fix "buffer underflow" error

- tools/code_format/check_format.py
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Remove deprecated `proto_format` check warning

- examples/wasm-cc/Dockerfile-envoy-build
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] ci: Fix kitware apt key (#25061)

- mobile/bazel/envoy_mobile_repositories.bzl
Commit Message: Bump the version of https://github.com/buildbuddy-io/rules_xcodeproj/releases/tag/0.12.2. It seem to be fixing some issues with lldb when debugging locally.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile tooling: bump xcodeproj rule version

- source/common/upstream/subset_lb.h
- test/common/upstream/subset_lb_test.cc
This was approved for a public repo fix because the PR causing the issue was merged 4 days ago.
Commit Message: subset-lb: fixing a mismatch between checked and returned lb config
PR #24905 optimized the memory used for clusters. However it introduced a subtle bug when Least-Request LB is used, which results in returning the default config for that policy.
Testing: This is a private method that is not easy to validate.
Fixes commit #24905
> subset-lb: fixing a mismatch between checked and returned lb config

- OWNERS.md
Remove entry for old sr extension maintainer from OWNERS.md
> Remove entry for old sr extension maintainer from OWNERS.md

- changelogs/current.yaml
- docs/root/intro/arch_overview/upstream/connection_pooling.rst
- mobile/library/cc/engine_builder.cc
- mobile/library/common/config/config.cc
- mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
- mobile/library/objective-c/EnvoyConfiguration.m
- mobile/test/cc/unit/envoy_config_test.cc
- mobile/test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
- mobile/test/swift/EngineBuilderTests.swift
- source/common/common/dns_utils.cc
- source/common/runtime/runtime_features.cc
- test/common/common/dns_utils_test.cc
- test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc
(Not removing the moble APIs as they still control the DNS lookup type and so are still functional)
Testing: n/a
Fixes https://github.com/envoyproxy/envoy/issues/25008
> runtime: removing envoy.reloadable_features.dns_multiple_addresses

- mobile/bazel/apple_test.bzl
- mobile/test/objective-c/BUILD
- mobile/test/swift/BUILD
- mobile/test/swift/stats/BUILD
Until I can fix the timeouts we're seeing on CI.
Slack: https://envoyproxy.slack.com/archives/CKQ2LK23G/p1674577196513449
Risk Level: Risks introducing more flakiness in these tests, but hopefully this is a short-lived temporary workaround
Testing:
Docs Changes:
Release Notes:
> mobile: mark some iOS tests as flaky

- test/exe/version_out_test.sh
Commit Message: update hyphen matching in regex in version_out_test.sh
Additional Description: We're looking to update the output string of the `--version` command to include more info about the build version in our envoy fork using additional hyphens. In the version_out_test.sh file, we noticed that the regex for these tests could be updated to support that and the current version output by changing the hyphen to be the last character in the `[...]` expression in the third group to avoid it being considered a range.
Testing: successful run of version_out_test.sh using `bazel test //test/exe:version_out_test`
> test: update hyphen matching in regex in version_out_test.sh

- envoy/stats/scope.h
- envoy/stats/store.h
- test/common/upstream/load_balancer_benchmark.cc
- test/common/upstream/multiplexed_subscription_factory_test.cc
Commit Message: Removes Stats::ScopePtr definition as well as the cast operator from Stats::Store to Stats::Scope.
Risk Level: medium -- other PRs may be adding use of this; but the cleanup should be easy if necessary. There may also be out-of-repo deps which I mostly tried to clean up where I could find them.
Testing: //test/...
Fixes: #20911
Fixes: #24007
> stats: remove use and definition of deprecated functions

- .github/workflows/android_build.yml
- .github/workflows/android_tests.yml
- .github/workflows/asan.yml
- .github/workflows/cc_tests.yml
- .github/workflows/codeql-daily.yml
- .github/workflows/codeql-push.yml
- .github/workflows/core.yml
- .github/workflows/coverage.yml
- .github/workflows/depsreview.yml
- .github/workflows/docs.yml
- .github/workflows/format.yml
- .github/workflows/ios_build.yml
- .github/workflows/ios_tests.yml
- .github/workflows/perf.yml
- .github/workflows/python_tests.yml
- .github/workflows/release_validation.yml
- .github/workflows/tsan.yml
Signed-off-by: glokta1 <rafeyahmad@protonmail.com>
Commit Message: [mobile ci: cancel ongoing mobile CI jobs when new SHA pushed to PR](https://github.com/glokta1/envoy/commit/ff707a607086cb32cd82ecde3d3d8d03bd0a5a9a)
Additional Description:  Added the `concurrency` key to all workflows which had a `pull_request` event attached. Some workflows are also additionally triggered on push to main, so added a fallback variable `github.run_id` to avoid syntax errors.
I was a little confused on whether to cancel the workflows that are run by cronjobs like  `codeql-daily.yml` but still include a `pull_request` event in some step. I have set it to cancel but let me know if this needs to be changed.
Fixes #24982
> mobile ci: cancel ongoing mobile CI jobs when new SHA pushed to PR

- mobile/test/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator_test.cc
- mobile/test/common/http/client_test.cc
- mobile/test/common/integration/quic_test_server.cc
This was missed in https://github.com/envoyproxy/envoy/pull/25136 because we don't run Envoy Mobile CI jobs for every PR (yet).
Slack discussion: https://envoyproxy.slack.com/archives/C02F93EEJCE/p1674678980377169
Risk Level: Low, mirrored the changes done in https://github.com/envoyproxy/envoy/pull/25136
Testing: test/common/...
> Fix envoy mobile tests after recent stats change

- mobile/ci/mac_ci_setup.sh
These don't appear to be used in macOS CI and take time to install on every CI job.
Risk Level: Low in general, moderate on Envoy Mobile CI if something is actually using these and I missed them
Testing:
Docs Changes:
Release Notes:
> mobile: remove unnecessary macOS CI dependencies

- test/common/http/http1/http1_codec_impl_fuzz_test.cc
Commit Message: 2 unrelated PRs crossed paths causing a build breakage to land in main. This fixes it.
Testing: //test/...
> fuzz: fix to avoid calling a removed function.

- source/common/upstream/load_balancer_impl.cc
- source/common/upstream/load_balancer_impl.h
- test/common/upstream/least_request_load_balancer_corpus/least_request-max-request-value
Signed-off-by: AlanDiaz <diazalan@google.com>
Commit Message: Fix for divide by zero bug
Additional Description: If the number of active requests meets the max value of uint64, the + 1 will overflow the value to zero and cause a divide by zero error. This is unlikely to happen in normal cases but stops a fuzz test from failing.
Testing: N/A
> Fix divide by zero fuzz issue

- envoy/upstream/upstream.h
- source/common/upstream/upstream_impl.cc
- source/common/upstream/upstream_impl.h
- source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc
- source/extensions/filters/network/redis_proxy/conn_pool_impl.cc
- test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_test.cc
- test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc
- test/mocks/upstream/cluster_info.cc
- test/mocks/upstream/cluster_info.h
Commit Message: Saves memory in cluster info
Additional Description: In cases where CustomClusterType is not used, the unique_ptr will be null and save memory
Testing: Changed mock for new typing
> CustomCluster configuration memory optimization

- mobile/test/objective-c/BUILD
- mobile/test/swift/BUILD
- mobile/test/swift/stats/BUILD
By setting `tags = ["no-remote-exec"]`. It appears that the EngFlow RBE machines are having trouble connecting to the `testmanagerd` socket due to permission errors. Perhaps a sandboxing issue.
See https://envoyproxy.slack.com/archives/C02QMNG92A3/p1674766800532359 for discussion.
Risk Level: Moderate to Envoy Mobile iOS CI jobs
Testing:
Docs Changes:
Release Notes:
> mobile: run iOS tests locally

- ci/Dockerfile-envoy
from `3ee458a` to `cd7fe70` in /ci (#25153)
Bumps distroless/base-nossl-debian11 from `3ee458a` to `cd7fe70`.
---
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
> [backport/1.22] build(deps): bump distroless/base-nossl-debian11

- mobile/tools/should_run_ci.sh
Environment variable reference docs: https://docs.github.com/en/enterprise-server@3.7/actions/learn-github-actions/variables
> `GITHUB_BASE_REF`
> The name of the base ref or target branch of the pull request in a workflow run. This is only set when the event that triggers a workflow run is either `pull_request` or `pull_request_target`. For example, `main`.
Commit Message: mobile: skip Envoy Mobile CI jobs on PRs targeting release branches
Risk Level:
Testing: Local
Docs Changes:
Release Notes:
Fixes https://github.com/envoyproxy/envoy/issues/25205
> mobile: skip Envoy Mobile CI jobs on PRs targeting release branches

- api/contrib/envoy/extensions/filters/http/golang/v3alpha/golang.proto
Signed-off-by: wangfakang <fakangwang@gmail.com>
Commit Message: use min_len instead of min_bytes for golang.proto.
Additional Description: use min_len instead of min_bytes for golang.proto.
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] Fix #25198
> use min_len instead of min_bytes for golang.proto.

- envoy/upstream/upstream.h
- source/common/router/router.cc
- source/common/tcp_proxy/tcp_proxy.cc
- source/common/upstream/upstream_impl.cc
- source/common/upstream/upstream_impl.h
- test/common/router/router_test.cc
- test/common/tcp_proxy/tcp_proxy_test.cc
- test/mocks/upstream/cluster_info.cc
- test/mocks/upstream/cluster_info.h
Commit Message: Reduce memory usage if cluster does not contain an upstream config
Additional Description: In cases where a cluster does not have a set upstream config, this will save memory using unique pointers
Testing: Changed mocks as needed
> Upstream config memory optimization

- mobile/library/cc/engine_builder.cc
- mobile/library/cc/engine_builder.h
- mobile/test/cc/unit/envoy_config_test.cc
Brings the C++ parity to the Java builder for DNS
Testing: unit
> mobile: adding dns config knobs to C++ builder

- source/common/http/http2/codec_impl.cc
- source/common/http/http2/codec_impl.h
- test/common/http/codec_impl_corpus/oss-fuzz-47120-codec_impl_fuzz_test-6205436203761664
Commit Message: http2: use getStreamUnchecked wherever possible
Let h2 codec use the non-asserting getStream() function, because it
handles no stream gracefully, but the asserting one blocks fuzzing.
- Use getStreamUnchecked() more often where stream == nullptr is in
place anyway.
- Add logging for some places.
- Add const getStreamUnchecked().
Testing: n/a
> http2: use getStreamUnchecked wherever possible

- contrib/kafka/filters/network/source/mesh/BUILD
- contrib/kafka/filters/network/source/mesh/abstract_command.h
- contrib/kafka/filters/network/source/mesh/command_handlers/BUILD
- contrib/kafka/filters/network/source/mesh/command_handlers/fetch.cc
- contrib/kafka/filters/network/source/mesh/command_handlers/fetch.h
- contrib/kafka/filters/network/source/mesh/command_handlers/fetch_record_converter.cc
- contrib/kafka/filters/network/source/mesh/command_handlers/fetch_record_converter.h
- contrib/kafka/filters/network/source/mesh/filter.cc
- contrib/kafka/filters/network/source/mesh/filter.h
- contrib/kafka/filters/network/test/mesh/abstract_command_unit_test.cc
- contrib/kafka/filters/network/test/mesh/command_handlers/BUILD
- contrib/kafka/filters/network/test/mesh/command_handlers/api_versions_unit_test.cc
- contrib/kafka/filters/network/test/mesh/command_handlers/fetch_unit_test.cc
- contrib/kafka/filters/network/test/mesh/command_handlers/list_offsets_unit_test.cc
- contrib/kafka/filters/network/test/mesh/command_handlers/metadata_unit_test.cc
- contrib/kafka/filters/network/test/mesh/command_handlers/produce_unit_test.cc
- contrib/kafka/filters/network/test/mesh/request_processor_unit_test.cc
Commit Message: kafka: add Fetch request handling
Additional Description: Fetch request represents a single request coming from downstream clients "_please give me records for partitions p1, p2, ... pN_". In our implementation this will mean we will ask SharedConsumerManager to [process](https://github.com/adamkotwasinski/envoy/blob/59cfbef8571472ed7f37b741b59304e687dca3fc/contrib/kafka/filters/network/source/mesh/shared_consumer_manager_impl.cc#L55) our request (== fill it with records, if any stored; register as callback if nothing). When our processing is finished (which can happen in one of two ways: record times out (no records!) / stuff got provided (either [initial seeding](https://github.com/adamkotwasinski/envoy/blob/59cfbef8571472ed7f37b741b59304e687dca3fc/contrib/kafka/filters/n …
> kafka: fetch request

- ci/Dockerfile-envoy
from `3ee458a` to `cd7fe70` in /ci (#25153)
Bumps distroless/base-nossl-debian11 from `3ee458a` to `cd7fe70`.
---
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
> [backport/1.23] build(deps): bump distroless/base-nossl-debian11 

- distribution/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
> distribution: Fix binary stripping to reduce deb size

- source/common/filesystem/inotify/watcher_impl.cc
With the order previously if `inotify_init1` failed then Envoy would crash in `createFileEvent` with `SOCKET_VALID(fd)` and the inotify specific assert would never hit.
I recently tried to debug this failure and I had to use `strace` to figure out how things are failing and that release assert could have saved me quite a bit of time.
Signed-off-by: Sotiris Nanopoulos <sotiris.nanopoulos@reddit.com>
> Release assert `inotify_init1` output

- contrib/golang/filters/http/source/cgo.cc
- contrib/golang/filters/http/source/go/pkg/api/api.h
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
- contrib/golang/filters/http/source/processor_state.cc
- contrib/golang/filters/http/source/processor_state.h
- contrib/golang/filters/http/test/golang_filter_test.cc
To make the APIs robust, users could call the Go exposed API safely.
Now, just panic while invoking C API in an unexpected stage,  will add go recover in the Goroutine entry function, in another PR.
Testing:
Docs Changes:
Release Notes:
> go filter extension: check the filter state while invoking C api from Go

- .github/workflows/perf.yml
Was debugging a binary size increase in https://github.com/envoyproxy/envoy/actions/runs/4008291380/workflow and noticed that the comparison is based on --config=remote-ci-linux-clang.  Talked with JP and it seems more appropriate to compare a release build instead.
Test plan: Look at CI
> Change mobile binary size comparison workflow to use release build

- changelogs/current.yaml
- docs/root/configuration/http/http_filters/lua_filter.rst
- source/extensions/filters/http/lua/lua_filter.cc
- test/extensions/filters/http/lua/lua_filter_test.cc
Commit Message: lua: new option of http call to skip sending xff
To close #25190
Testing: unit.
Docs Changes: added.
> lua: new option of http call to skip sending xff

- mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java
- mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
- mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyEngine.java
- mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java
- mobile/library/kotlin/io/envoyproxy/envoymobile/EngineImpl.kt
- mobile/library/kotlin/io/envoyproxy/envoymobile/mocks/MockEnvoyEngine.kt
- mobile/test/java/io/envoyproxy/envoymobile/engine/BUILD
- mobile/test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
- mobile/test/kotlin/io/envoyproxy/envoymobile/BUILD
- mobile/test/kotlin/io/envoyproxy/envoymobile/EngineBuilderTest.kt
Changing the java and kotlin APIs to by default, createYaml(), and optionally run with custom registrations and yaml.
This allows Lyft (and OSS CI) to retain the ability to run custom yaml, but changes the default to doing builder-only engines, in preparation for moving Java to use the C++ engine in bootstrap mode.
Risk Level: Medium (though some test tweaks may be necessary for Lyft)
Testing: CI
Docs Changes: n/a (runWithTemplate didn't show up in docs)
Release Notes: n/a (ditto)
https://github.com/envoyproxy/envoy/issues/24976
> mobile: cleaning up runWithTemplate APIs

- mobile/test/kotlin/integration/CancelGRPCStreamTest.kt
- mobile/test/kotlin/integration/GRPCReceiveErrorTest.kt
- mobile/test/kotlin/integration/ReceiveErrorTest.kt
- mobile/test/kotlin/integration/ResetConnectivityStateTest.kt
Akin to https://github.com/envoyproxy/envoy/pull/25159 moving the rest of the non-proxy Kotlin tests to use the builder APIs
Testing: n/a
part of https://github.com/envoyproxy/envoy/issues/24976
> kotlin: more test clean up

- contrib/hyperscan/matching/input_matchers/source/BUILD
Commit Message: hyperscan: fix missing fat runtime flag
Testing: N/A
Fixes #25099
> hyperscan: fix missing fat runtime flag

- ci/Dockerfile-envoy
in /ci (#25291)
Bumps distroless/base-nossl-debian11 from `cd7fe70` to `bf61596`.
---
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.22] build(deps): bump distroless/base-nossl-debian11 to `bf61596`

- ci/Dockerfile-envoy
in /ci (#25291)
Bumps distroless/base-nossl-debian11 from `cd7fe70` to `bf61596`.
---
Signed-off-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md): …
> [backport/1.25] build(deps): bump distroless/base-nossl-debian11 to `bf61596`

- ci/Dockerfile-envoy
in /ci (#25291)
Bumps distroless/base-nossl-debian11 from `cd7fe70` to `bf61596`.
---
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] build(deps): bump distroless/base-nossl-debian11 to `bf61596`

- mobile/library/cc/engine_builder.cc
- mobile/library/cc/engine_builder.h
- mobile/test/cc/unit/envoy_config_test.cc
Undoing the API change from https://github.com/envoyproxy/envoy/pull/25259/files and adding builder support for the original API.
Testing: yes
Part of https://github.com/envoyproxy/envoy/issues/24976
> mobile: moving stats back to string vector

- envoy/upstream/load_balancer_type.h
- source/common/upstream/upstream_impl.cc
- source/common/upstream/upstream_impl.h
Signed-off-by: AlanDiaz <diazalan@google.com>
Commit Message: Reduce overhead via alignment
Additional Description: Moved smaller values like enums, int32 and bools to the end of the class to save on memory via alignment
> Reduce overhead by changing alignment

- docs/conf.py
- docs/root/_static/searchtools.js
- tools/base/requirements.in
- tools/base/requirements.txt
this PR:
- updates main docs deps
- sphinx 
- sphinx extensions
- docutils
- related envoy deps 
- updates custom js search `jquery` -> `js`
Risk Level:
Testing:
Docs Changes:
Release Notes:
> deps: Update docs dependencies

- mobile/docs/root/api/starting_envoy.rst
- mobile/examples/objective-c/hello_world/ViewController.m
- mobile/library/cc/engine_builder.cc
- mobile/library/cc/engine_builder.h
- mobile/library/common/config/config.cc
- mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
- mobile/library/java/org/chromium/net/impl/NativeCronetEngineBuilderImpl.java
- mobile/library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
- mobile/library/objective-c/EnvoyConfiguration.h
- mobile/library/objective-c/EnvoyConfiguration.m
- mobile/library/swift/EngineBuilder.swift
- mobile/test/cc/unit/envoy_config_test.cc
- mobile/test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
- mobile/test/swift/EngineBuilderTests.swift
In Lyft's usage, we have up to 14 calls per second to save DNS results to the key value store. Buffering these to save at most once per second should be sufficient.
Commit Message: mobile: set dns cache key value save interval to 1s
Additional Description: In Lyft's usage, we have up to 14 calls per second to save DNS results to the key value store. Buffering these to save at most once per second should be sufficient.
Testing: In Lyft's apps
> mobile: allow overriding dns cache key value save interval

- repokitteh.star
Add `/milestone` command
As discussed with @phlax , as the first step, this will add the `milestone/review` label, for maintainers to review easier.
Usage: `/milestone 48`
that means suggest adding this issue/pr to [milestone 48](https://github.com/envoyproxy/envoy/milestone/48), but it will not be applied automatically -  instead - adding the `milestone/review` label - waiting for maintainers to review.
Testing:
Docs Changes:
Release Notes:
> repokitteh: Add `/milestone` command

- source/extensions/http/cache/file_system_http_cache/cache_eviction_thread.cc
Commit Message: [build] fix Apple M1 build
After https://github.com/envoyproxy/envoy/commit/5991a2053e981038c105a421886af073be9c5941 was merged compiling Envoy on an Apple M1 machine began to fail with:
```
ERROR: /Users/tamal/go/src/github.com/envoyproxy/envoy/source/extensions/http/cache/file_system_http_cache/BUILD:19:19: Compiling source/extensions/http/cache/file_system_http_cache/cache_eviction_thread.cc failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target //source/extensions/http/cache/file_system_http_cache:config) external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics ... (remaining 157 arguments skipped) …
```
> [build] fix Apple M1 build

- source/extensions/filters/http/rate_limit_quota/filter.cc
- source/extensions/filters/http/rate_limit_quota/matcher.cc
- source/extensions/filters/http/rate_limit_quota/matcher.h
- test/extensions/filters/http/rate_limit_quota/filter_test.cc
Fix typo: `RateLimitOnMactchAction` ---> `RateLimitOnMatchAction`
Signed-off-by: tyxia <tyxia@google.com>
> rate_limit_quota: Fix typo

- bazel/dependency_imports.bzl
rules_rust does not include s390x platform by default, added it manually.
Fixes https://github.com/envoyproxy/envoy/issues/25340
> Added rules_rust toolchain for s390x

- .github/workflows/android_build.yml
- .github/workflows/android_tests.yml
- .github/workflows/asan.yml
- .github/workflows/cc_tests.yml
- .github/workflows/commands.yml
- .github/workflows/core.yml
- .github/workflows/coverage.yml
- .github/workflows/docs.yml
- .github/workflows/format.yml
- .github/workflows/ios_build.yml
- .github/workflows/ios_tests.yml
- .github/workflows/perf.yml
- .github/workflows/python_tests.yml
- .github/workflows/release_validation.yml
- .github/workflows/tsan.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.25] ci: Only run mobile jobs in the Envoy repo

- .github/workflows/android_build.yml
- .github/workflows/android_tests.yml
- .github/workflows/asan.yml
- .github/workflows/cc_tests.yml
- .github/workflows/commands.yml
- .github/workflows/core.yml
- .github/workflows/coverage.yml
- .github/workflows/docs.yml
- .github/workflows/format.yml
- .github/workflows/ios_build.yml
- .github/workflows/ios_tests.yml
- .github/workflows/perf.yml
- .github/workflows/python_tests.yml
- .github/workflows/release_validation.yml
- .github/workflows/tsan.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Only run mobile jobs in the Envoy repo

- test/integration/quic_http_integration_test.cc
Commit Message: Fix flaky QUIC test for deferred logging
Risk Level: N/A, test-only
Fixes https://github.com/envoyproxy/envoy/issues/25264
> Fix flaky QUIC test for deferred logging

- .github/workflows/compile_time_options.yml
These will give us some level of additional coverage to ensure that builds don't break with custom compile time options. 
For stronger coverage we'd also run the tests but I'm concerned about the additional CI load for that, so prefer starting with just builds.
Risk Level:
Testing: CI :)
Docs Changes:
Release Notes:
Fixes: https://github.com/envoyproxy/envoy/issues/25379
> mobile: add CI jobs to build Envoy Mobile with custom compile time flags

- ci/do_ci.sh
- examples/shared/build/build-entrypoint.sh
- examples/verify-common.sh
- examples/wasm-cc/docker-compose-wasm.yaml
- examples/wasm-cc/verify.sh
if the env var `DOCKER_RMI_CLEANUP` is set, this will remove any images listed for the `RMI` variable in an example's verify.sh.
also:
- fixes some permissions in the build entrypoint
- adds some cleanups for the `wasm-cc` example
Risk Level:
Testing:
Docs Changes:
Release Notes:
> examples: Add (optional) image cleanup (rmi)

- mobile/library/common/jni/jni_interface.cc
Fixes the following crash:
```
FATAL ERROR in native method: Bad global or local ref passed to JNI
at io.envoyproxy.envoymobile.engine.JniLibrary.compareYaml(Native Method)
```
By mapping Java's `long` type to `jlong` in JNI instead of `jint`.
The process I took was taking the function definition from `JniLibrary.java`, converting the parameter names from CamelCase to snake_case, and mapping the following types:
* `String` -> `jstring`
* `long` -> `jlong`
* `boolean` -> `jboolean`
* `byte[][]` -> `jobjectArray`
Because of this, I changed the parameter names in the JNI function to match the Java function definition, which I believe will make repeating this process easier and less error prone moving forward.
Risk Level:
Testing: `./bazelw test …
> mobile: fix types in `compareYaml` JNI function

- .azure-pipelines/pipelines.yml
- ci/run_envoy_docker.sh
- docs/BUILD
- docs/build.sh
This uses the commit sha from the PR HEAD in the staged docs version string, which should make it easier to associate with a pushed PR version
The staged docs are still published to a URL using the merged commit sha - so individual builds (from the same pr commit) are still distinct
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docs: Use PR commit sha

- docs/root/configuration/http/http_conn_man/response_code_details.rst
"original_ip_detection_failed" does not exist, use the correct value "rejecting_because_detection_failed" instead.
Fixes #25147
Docs Changes: replaced "original_ip_detection_failed" with "rejecting_because_detection_failed"
> docs: fix the name of a response code detail

- mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
Prior builder PR checked the filter chain didn't change, but in doing so changed the filter chain.  Thankfully only under junit but still buggy.
> mobile: fixing a bug for junit config

- .github/workflows/perf.yml
This was accidentally disabled in https://github.com/envoyproxy/envoy/pull/25189, causing the CI job to be extremely slow.
> mobile: re-enable RBE for `mobile_perf` CI jobs

- source/extensions/filters/http/gcp_authn/token_cache.h
This TODO has already been addressed in PR #23366 (i.e., token_cache_test.cc tests token_cache)
Signed-off-by: tyxia <tyxia@google.com>
> Clean up: Remove obsolete TODO

- envoy/network/address.h
- source/common/network/address_impl.cc
- source/common/network/address_impl.h
- source/common/network/utility.cc
- test/common/network/address_impl_test.cc
- test/common/network/utility_test.cc
Signed-off-by: Renjie Tang <renjietang@google.com>
Commit Message: Remove scope id from ipv6 address in getLocalAddress
Additional Description: This fixes the issue where Envoy-mobile fails to send out any packet on ipv6.
Fixes #25326
> Remove scope id from ipv6 address in getLocalAddress

- source/common/tracing/BUILD
- source/common/tracing/tracer_impl.cc
- source/common/tracing/tracer_manager_impl.cc
- source/common/tracing/tracer_manager_impl.h
- source/extensions/filters/network/http_connection_manager/config.cc
Commit Message: minor update: move TracerManager registration to common/tracing
Move the tracer manager registration out from HCM. This make other proxy could reuse this tracer manager easily and needn't to register a new tracer manager instance.
Testing: n/a.
> minor update: move TracerManager registration to common/tracing

- mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
- mobile/test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
* The virtual clusters builder was omitting the first comma and adding an extra trailing comma
* The DNS preresolved host names builder wasn't adding any commas at all
Commit Message: mobile: fix producing comma-separated lists in Java/Kotlin builders
Testing: Added regression tests
> mobile: fix producing comma-separated lists in Java/Kotlin builders

- mobile/library/cc/engine_builder.cc
- mobile/library/common/jni/jni_interface.cc
* Quote `dns_preresolve_hostnames_` values
* Don't set `EngineBuilder::setAppId` twice
Testing:
Docs Changes:
Release Notes:
> mobile: minor fixes to C++ engine builder

- mobile/docs/root/api/starting_envoy.rst
- mobile/docs/root/intro/version_history.rst
- mobile/library/objective-c/EnvoyConfiguration.h
- mobile/library/objective-c/EnvoyConfiguration.m
- mobile/library/swift/EngineBuilder.swift
- mobile/test/swift/EngineBuilderTests.swift
This mirrors what was done to builders for other languages in #25297 and #25259.
Testing: Unit tests & Lyft apps
> mobile: update ObjC/Swift APIs to take arrays instead of strings

- mobile/library/cc/engine_builder.cc
mobile: Use true not "true" as an arg to set_bool_value()
> mobile: Use true not "true" as an arg to set_bool_value()

- source/common/upstream/upstream_impl.cc
Commit Message: uhv : use h3 codec stat.
Testing: 
> uhv : use h3 codec stat.

- contrib/kafka/filters/network/source/mesh/BUILD
- contrib/kafka/filters/network/source/mesh/command_handlers/BUILD
- contrib/kafka/filters/network/source/mesh/command_handlers/fetch_record_converter.cc
- contrib/kafka/filters/network/source/mesh/command_handlers/fetch_record_converter.h
- contrib/kafka/filters/network/source/mesh/inbound_record.h
- contrib/kafka/filters/network/source/mesh/upstream_kafka_consumer_impl.cc
- contrib/kafka/filters/network/source/serialization.cc
- contrib/kafka/filters/network/source/serialization.h
- contrib/kafka/filters/network/test/mesh/command_handlers/BUILD
- contrib/kafka/filters/network/test/mesh/command_handlers/fetch_record_converter_unit_test.cc
- contrib/kafka/filters/network/test/mesh/command_handlers/fetch_unit_test.cc
- contrib/kafka/filters/network/test/mesh/shared_consumer_manager_impl_unit_test.cc
- contrib/kafka/filters/network/test/serialization_test.cc
Commit Message: kafka: fetch record converter
Additional Description: Add a way to convert (at least somewhat) the received records (from upstream Kafka clusters) to record bytes we are going to [send to downstream clients](https://github.com/adamkotwasinski/envoy/blob/4cf23532d00fe879c8bbbd8260fa14ccc0b1b779/contrib/kafka/filters/network/source/mesh/command_handlers/fetch.cc#L178). Part of https://github.com/envoyproxy/envoy/issues/24372
Testing: unit tests, integration tests with full stack
> kafka: fetch record converter

- source/extensions/filters/network/zookeeper_proxy/decoder.cc
Signed-off-by: Zhewei Hu <zhu@pinterest.com>
Commit Message: ZK filter: add more trace logs
Additional Description: These additional trace logs will be helpful to debug decoder errors.
> ZK filter: add more trace logs

- mobile/bazel/envoy_mobile_repositories.bzl
There have been lots of fixes, features and optimizations since the last time we updated.
In particular, the releases now include prebuilt optimized binaries.
https://github.com/buildbuddy-io/rules_xcodeproj/releases/tag/1.1.0
Read the release blog post to learn more about the state of the project: https://www.buildbuddy.io/blog/introducing-rules_xcodeproj-1-0/
Testing:
Docs Changes:
Release Notes:
> mobile: update rules_xcodeproj to 1.1.0

- .azure-pipelines/pipelines.yml
This makes the 1.23 branch work with the newer ubuntu images and prevents failure during github brownouts (or after apr 1st when the deprecation period ends)
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] ci: Bump Ubuntu images

- mobile/docs/root/intro/version_history.rst
- mobile/library/common/extensions/filters/http/test_remote_response/filter.cc
- mobile/library/common/extensions/filters/http/test_remote_response/filter.h
- mobile/library/common/jni/jni_interface.cc
- mobile/test/kotlin/integration/BUILD
- mobile/test/kotlin/integration/ReceiveTrailersTest.kt
We started seeing crashes in these codepaths last week and although I haven't been able to reproduce it, it seems prudent to stop iteration rather than crash due to an out-of-bounds array access.
@alyssawilk added unit tests (thank you!)
Risk Level: Low to Envoy, Medium to Envoy Mobile. Instead of crashing this could lead to incorrect behavior if my patch is the wrong way to fix this.
Testing: `//test/java/...` & Alyssa added some regression tests
Docs Changes:
Release Notes:
> mobile: perform bounds checks before accessing JNI arrays

- mobile/library/cc/engine_builder.cc
- mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
- mobile/library/objective-c/EnvoyConfiguration.mm
- mobile/test/cc/unit/envoy_config_test.cc
- mobile/test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
- mobile/test/swift/EngineBuilderTests.swift
Otherwise if we set something that looks like an integer for app version it'll lead to C++ yaml comparison mismatches.
Risk Level:
Testing: Existing unit tests were updated, and Lyft's downstream tests are now passing when yaml validation is enabled.
Docs Changes:
Release Notes:
> mobile: always set metadata values as strings

- mobile/library/cc/engine_builder.cc
Removing this cuts the remaining load time in half for C++ (h/t Michael Bradshaw)
> mobile: changing release assert to assert

- source/common/upstream/upstream_impl.cc
- source/common/upstream/upstream_impl.h
Additional Description: Moving around a couple of variables to save a small amount of memory in Cluster Info.
Sizeof before changes: 2632
Sizeof after changes: 2624
> Alignment change to save memory in cluster info

- docs/root/_include/tcp_stats.rst
- source/extensions/transport_sockets/tcp_stats/tcp_stats.cc
- source/extensions/transport_sockets/tcp_stats/tcp_stats.h
Commit Message: adding bytes received/sent to cluster TCP stats
Additional Description: Adding more tcp stats taken from tcpi_bytes_received and tcpi_bytes_sent data
Testing: Compiled and tested with tcpdump for comparison
Docs Changes: No docs changed.
> adding bytes received/sent to cluster TCP stats

- mobile/bazel/apple.bzl
These started being reported when we switched to building ObjC++.
Commit Message: mobile: silence `-Wshorten-64-to-32` warnings when building ObjC
Testing:
Docs Changes:
Release Notes:
> mobile: silence `-Wshorten-64-to-32` warnings when building ObjC

- mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
- mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java
- mobile/library/java/org/chromium/net/impl/NativeCronetEngineBuilderImpl.java
- mobile/library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
- mobile/test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
- mobile/test/kotlin/apps/experimental/MainActivity.kt
I missed this when reviewing https://github.com/envoyproxy/envoy/pull/25392.
Also add additional coverage by setting this to true in the experimental Kotlin app, mirroring what we did on the Swift side.
Testing: Updated unit tests, enabled this for the experimental Kotlin app
> mobile: add `EngineBuilder.useLegacyBuilder()` to Kotlin

- .github/workflows/compile_time_options.yml
- mobile/library/cc/engine_builder.cc
- mobile/library/common/config/config.cc
- mobile/test/cc/unit/envoy_config_test.cc
The stats_prefix field in the GoogleGrpc config has a proto validation rule that the field must be populated and have a length of at least 1.
This change adds the stat_prefix field whenever the ADS builder API is used, and adds tests to validate it.
Lastly, this change makes the mobile_compile_time_options CI job turn on proto validation, so we can ensure we never commit invalid proto, even though mobile normally disables proto validation for binary size purposes. The default value for the PVG template is the empty string (https://github.com/bufbuild/protoc-gen-validate/blob/38260ee45796b420276ac925d826ecec8fc3e9a8/bazel/BUILD#L11), so the mobile_compile_time_options sets template-flavor to the empty string instead of the default `nop` for mobile.
Signed-off-by: Ali Beyad …
> mobile: Add the stats prefix to the ADS xDS registration

- source/common/stats/isolated_store_impl.cc
- source/common/stats/isolated_store_impl.h
- source/extensions/http/cache/file_system_http_cache/file_system_http_cache.cc
- source/extensions/http/cache/file_system_http_cache/file_system_http_cache.h
- source/extensions/http/cache/file_system_http_cache/stats.cc
- source/extensions/http/cache/file_system_http_cache/stats.h
- test/common/stats/isolated_store_impl_test.cc
- test/extensions/http/cache/file_system_http_cache/file_system_http_cache_test.cc
Commit Message: [file_system_http_cache] Rename stat with tags
Additional Description: Discovered in testing that a stat named `a.b.c` is not the same as a stat that prints out as `a.b.c`, if `b.c` is derived from tags. This changes the stats for `file_system_http_cache` from having the cache path in the stat-name to having the cache path as a tag value.
Risk Level: Very low, extension is WIP.
Testing: Coverage is there; stat-names could be tested better, but right now the fake metrics don't support it correctly. It would make more sense to test stat name generation while creating and migrating to a stats-common method to make tagged stats anyway.
> [file_system_http_cache] Rename stat with tags

- tools/local_fix_format.sh
Commit Message: Fixes "-all" behavior, which needs a special case due to messy shell quoting.
Testing: ran the formatter with and without -all
> util: special-case "-all" which was previously not working.

- mobile/test/common/integration/BUILD
I think this test works without the dependency because it's included as a sub-dependency. But some build flags will cause the dependency to be missing because it's not directly included
Anyways I tested and this makes things work inside Google without breaking anything.
> Add a missing build dep for mobile xds_integration_test

- source/common/http/http1/balsa_parser.cc
- source/common/http/http1/balsa_parser.h
- test/common/http/http1/codec_impl_test.cc
BalsaVisitorInterface provides two ways of processing headers: OnHeader() is called for each header line, and ProcessHeaders() and ProcessTrailers() are called with the entire header/trailer block.  All of these methods are only called after the entire header block or trailer block is parsed, so using OnHeader() does not actually allow early processing of headers.
The major difference is that some header validation happens after OnHeader() is called, for example, check for empty header names (both for headers and trailers), multiple Content-Length headers, multiple Transfer-Encoding headers, and the presence of Content-Length and Transfer-Encoding in the same header block (not for trailers).  (Some of these test can be disabling using HttpValidationPolicy.)  If the headers fail, for …
> [balsa] Use ProcessHeaders() instead of OnHeader().

- bazel/repositories.bzl
- tools/base/requirements.in
- tools/base/requirements.txt
This adds a JSON data target to the repo repository rule.
The data is provided by pytooling from the repo environment, changelogs, etc, and can then be used to create eg Dockerhub pages with "supported version" information.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> bazel/tooling: Add `@envoy_repo//:project`

- test/integration/redirect_integration_test.cc
Should fix #25544.
Commit Message: Fix a flaky redirect integration test for HTTP/3.
Additional Description: This test fails when the check for a counter happens before deferred logging (a new HTTP/3 feature) is complete. 
Risk Level: Test only.
> Fix flaky redirect integration test for H/3

- mobile/tools/should_run_ci.sh
This will save 7 macOS CI jobs for every `main` commit, reducing CI load.
The Swift and Kotlin "Hello World" example apps will still run on main branch CI.
All mobile CI jobs still run for PRs touching mobile files.
Tested with the following invocations:
```console
$ GITHUB_JOB=swiftbaselineapp GITHUB_REF_NAME=main ./mobile/tools/should_run_ci.sh
Skipping swiftbaselineapp because current branch is main
$ GITHUB_JOB=swifthelloworld GITHUB_REF_NAME=main ./mobile/tools/should_run_ci.sh
Running swifthelloworld because current branch is main
```
Testing: Yes, see above
> mobile: skip most example apps on main branch CI

- mobile/bazel/android_artifacts.bzl
PR removes `R.class` and `R$*.class` from the final Android library `.aar` distribution because as per Android library publishing guidelines libraries must not include R classes — they're generated at the consumer side, otherwise consumer will get `Type X is defined multiple times` error during their build preventing them from using the Enovy Mobile as a `.aar` library!
Verified content before and after:
```swift
diff -r ~/Desktop/before ~/Desktop/after
Only in Desktop/before/io/envoyproxy/envoymobile: R$attr.class
Only in Desktop/before/io/envoyproxy/envoymobile: R$color.class
Only in Desktop/before/io/envoyproxy/envoymobile: R$dimen.class
Only in Desktop/before/io/envoyproxy/envoymobile: R$drawable.class
Only in Desktop/before/io/envoyproxy/envoymobile: R$id.class
Only in …
```
> Fix accidentally included R classes in the android lib

- ci/docker_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docker/ci: Add debugging info

- source/common/upstream/subset_lb.cc
- source/common/upstream/subset_lb.h
Commit Message: Reduce overhead by fixing alignment in SubsetLb
> Reduce overhead by fixing alignment in SubsetLb

- contrib/golang/filters/http/source/cgo.cc
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
- contrib/golang/filters/http/test/test_data/echo/filter.go
should deep copy the GoString when it will be used in a callback.
since the Go String object may be freed after the current cgo function returns.
Testing:
Docs Changes:
Release Notes:
> Golang filter extension: should deepcopy the GoString when it will be used in a callback.

- source/common/upstream/cluster_manager_impl.h
Commit Message: Reduce overhead by fixing alignment in ClusterData
> Reduce overhead by fixing alignment in ClusterData

- mobile/library/cc/BUILD
- mobile/library/cc/engine_builder.cc
- mobile/library/cc/engine_builder.h
- mobile/library/common/config/config.cc
- mobile/library/common/config/templates.h
- mobile/test/cc/unit/envoy_config_test.cc
- mobile/test/common/integration/cds_integration_test.cc
- mobile/test/common/integration/rtds_integration_test.cc
- tools/spelling/spelling_dictionary.txt
This commit does a few things:
- adds an API to EngineBuilder for setting the Bootstrap's node locality.
- adds the ability to set call and channel credentials in ADS.
- adds the ability to use xdstp for CDS via the cds_resources_locator field.
- removes the `api_type` parameter from the ADS API, since the only supported API type is `GRPC`.
- adds tests for all of these in envoy_config_test.cc.
- adds an xdstp integration test in CdsIntegrationTest.
- removes the Delta parameter in CdsIntegrationTest since mobile xDS doesn't support Delta.
> mobile: Improve xDS APIs in EngineBuilder

- source/common/upstream/load_balancer_impl.cc
- source/common/upstream/load_balancer_impl.h
Commit Message: Reduce overhead in SubsetSelectorImpl by fixing alignment
> Reduce overhead in SubsetSelectorImpl by fixing alignment

- mobile/library/cc/request_headers_builder.cc
- mobile/library/cc/request_method.cc
- mobile/library/cc/request_method.h
This is just a minor improvement to avoid unnecessary usages of std::string.
> Use string_view for requestMethod* functions

- .github/workflows/compile_time_options.yml
- mobile/library/cc/engine_builder.cc
- mobile/test/cc/unit/envoy_config_test.cc
Currently, the `mobile_compile_time_options` workflow just builds the C++ library using the custom compile time options. However, this won't necessarily catch runtime errors (e.g. protoc validation errors). This commit changes the C++ build to run the C++ tests instead.
The new cc_test workflow also uncovered a bug related to enabling HTTP3 in the mobile EngineBuilder, which is fixed in 
this same commit.
> ci: make the mobile compile options workflow run C++ tests

- ci/docker_ci.sh
Include `tools` and `google-vrp` images as variants.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docker: Unify image names (part2)

- docs/root/intro/arch_overview/observability/tracing.rst
The OpenTracing project has been merged (together with OpenCensus) into OpenTelemetry.
https://www.cncf.io/blog/2022/01/31/cncf-archives-the-opentracing-project/
Signed-off-by: Sascha Brawer <sascha@brawer.ch>
> docs: Link to OpenTelemetry instead of OpenTracing

- docs/root/start/sandboxes/locality_load_balancing.rst
- examples/locality-load-balancing/envoy-proxy.yaml
Commit Message: Add locality_weighted_lb_config to locality-load-balancing example
Additional Description: For the load_balancing_weight option to be used, this option must be set. Discussed in https://github.com/envoyproxy/envoy/issues/25692
Testing:
Docs Changes: 
Release Notes:
Wasn't sure if there was a good spot to update the docs. The page on the locality weighted load balancer does describe that you need to set this [field](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/locality_weight#arch …
> examples: Add locality_weighted_lb_config to locality-load-balancing example

- CODEOWNERS
Commit Message: change ext_proc owner 
Additional Description: s/chaoqin/stevenzzzz/ as ext_proc owner
Testing:
Docs Changes:
Release Notes:
> s/chaoqin/stevenzzzz/ as ext_proc owner

- source/extensions/listener_managers/listener_manager/listener_manager_impl.cc
- test/extensions/listener_managers/listener_manager/listener_manager_impl_test.cc
Now if we set a listener without address ,it would panic: https://github.com/envoyproxy/envoy/blob/73d776bea723cb69380bf2e44776d827c811d274/source/common/network/utility.cc#L536-L537
An example is like:
```
[2023-02-15 09:54:07.472][1415996][critical][assert] [source/common/network/utility.cc:534] panic: unset oneof             《====
[2023-02-15 09:54:07.472][1415996][critical][backtrace] [./source/server/backtrace.h:104] Caught Aborted, suspect faulting address 0x752f00159b3c
[2023-02-15 09:54:07.472][1415996][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2023-02-15 09:54:07.472][1415996][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: bae2e9d642a6a8ae6c5d3810f77f3e888f0d97da/1.25.1/Clean/RELEASE/Bori …
```
> listener: make address field required

- .azure-pipelines/pipelines.yml
- ci/Dockerfile-envoy
- ci/docker_ci.sh
- ci/test/docker/linux/dev/main
- ci/test/docker/linux/dev/other
- ci/test/docker/linux/dev/release
- ci/test/docker/linux/dev/tag
- ci/test/docker/linux/nondev/main
- ci/test/docker/linux/nondev/other
- ci/test/docker/linux/nondev/release
- ci/test/docker/linux/nondev/tag
- ci/test/docker/windows/dev/main
- ci/test/docker/windows/dev/other
- ci/test/docker/windows/dev/release
- ci/test/docker/windows/dev/tag
- ci/test/docker/windows/nondev/main
- ci/test/docker/windows/nondev/other
- ci/test/docker/windows/nondev/release
- ci/test/docker/windows/nondev/tag
- ci/test_docker_ci.sh
This refactors and adds regression tests to `./ci/docker_ci.sh`.
Images are no longer built repeatedly (in postsubmit) so it should be much faster.
Fixes missing `-latest` images from release builds.
Fix #25767 
Fix #25766 
Fix #25765 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docker: Refactor `docker_ci.sh`

- source/extensions/filters/common/lua/lua.h
- source/extensions/filters/http/grpc_json_transcoder/http_body_utils.cc
- source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc
- source/extensions/filters/http/rate_limit_quota/filter.h
- source/extensions/filters/http/rate_limit_quota/matcher.cc
- source/extensions/filters/network/connection_limit/connection_limit.h
- source/extensions/filters/network/dubbo_proxy/app_exception.h
- source/extensions/filters/network/dubbo_proxy/decoder.h
- source/extensions/filters/network/thrift_proxy/decoder.h
- source/extensions/filters/udp/dns_filter/dns_parser.h
Commit Message: clang-tidy: fix source/extensions/filters
Fixing some of the clang-tidy errors.
Testing: N/A.
> clang-tidy: fix source/extensions/filters

- source/common/upstream/load_balancer_impl.cc
- source/common/upstream/load_balancer_impl.h
Commit Message: Reduce overhead in ZoneAwareLoadBalancerBase by fixing alignment
> Reduce overhead in ZoneAwareLoadBalancerBase by fixing alignment

- source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc
- source/extensions/tracers/skywalking/skywalking_tracer_impl.cc
- source/extensions/tracers/xray/localized_sampling.cc
- source/extensions/tracers/xray/reservoir.h
- source/extensions/tracers/xray/tracer.h
- source/extensions/tracers/zipkin/zipkin_core_types.h
Commit Message: clang-tidy: fix rest of source/extensions
Fixing clang-tidy on source/extensions (continuation of #25772).
Testing: N/A
> clang-tidy: fix rest of source/extensions

- source/extensions/bootstrap/internal_listener/client_connection_factory.cc
- test/extensions/transport_sockets/internal_upstream/internal_upstream_integration_test.cc
Always populate the socket address type of internal client connection as Type::EnvoyInternal.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Always populate the address type of internal client connection as EnvoyInternal

- .azure-pipelines/bazel.yml
I believe these currently share the same azp cache that is used as a `repository_cache` in the build and packaging jobs
iiuc then for the most part arm just never gets a cache for any binary blobs (or other way round, not sure)
this should force them to use separate ones
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Use separate azp `repository_cache` arm64/x64

- envoy/server/request_id_extension_config.h
- source/common/http/request_id_extension_impl.cc
- source/common/http/request_id_extension_impl.h
- source/extensions/request_id/uuid/config.h
- test/extensions/filters/network/http_connection_manager/config_test.cc
Change factory context to CommonFactoryContext so that RequestIDExtension can also be used from upstream filters.
Testing: Covered by existing tests (e.g., //test/extensions/request_id/uuid:config_test)
Docs Changes:
Release Notes:
> RequestIDExtension: Make usable for upstream filters

- source/common/upstream/cluster_manager_impl.h
Commit Message: Reduce overhead by fixing alignment in PerPriority
> Reduce overhead by fixing alignment in PerPriority

- docs/root/operations/cli.rst
The section about [Command line options](https://www.envoyproxy.io/docs/envoy/v1.25.2/operations/cli) starts by introducing JSON as Envoy’s format for configuration files. But immediately after the introduction, in the section that documents `-c`/`--config-path`, other formats are mentioned as well.
Signed-off-by: Sascha Brawer <sascha@brawer.ch>
> docs: Fix introduction to config file formats

- .github/workflows/core.yml
- mobile/library/common/BUILD
- test/integration/BUILD
Changing one of our CI builds to remove a listener file, to ensure the downstream listener code doesn't leak back into the envoy_mobile_listener=disabled build.
Also removing a spurious library include so the build passes.
Testing: CI update
Part of https://github.com/envoyproxy/envoy/pull/25852
> mobile: ensuring the non-listener build works correctly

- .azure-pipelines/bazel.yml
- ci/do_ci.sh
- ci/run_clang_tidy.sh
- ci/run_envoy_docker.sh
Fix #25871 
this also fixes `run_clang_tidy` when run against other CI branches (eg release) which would have broken after the next release otherwise
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Make clang-tidy repo/diff more robust

- source/common/http/http1/balsa_parser.cc
- test/common/http/http1/codec_impl_test.cc
- test/integration/integration_test.cc
- test/integration/protocol_integration_test.cc
This long-standing feature request is one of the major drivers of the http-parser to Balsa migration.
There are two projects happening in parallel: HTTP/1 codec migration from http-parser to BalsaParser, and UHV (universal header validator).  http-parser rejects custom methods.  UHV has a configuration option to reject them, but allows them by default.  It is possible that BalsaParser will be deployed before UHV.  Since the status quo is to reject custom methods, and the end goal (when both Balsa and UHV have launched) is to have configurable behavior, it would be too risky to unconditinally allow custom methods in BalsaParser when UHV is disabled.  Therefore this PR changes BalsaParser (which currently rejects custom methods for parity with http-parser) to only allow custom methods when …
> [balsa] Enable custom request methods.

- source/common/filter/config_discovery_impl.h
Commit Message: cleanup: remove redundant private function
Minor cleanup - call directly to a method without going through a private method.
Risk Level: Low - no changes to behavior
Testing: N/A.
> cleanup: remove redundant private function

- source/common/network/connection_impl.cc
- test/common/network/connection_impl_test.cc
Commit Message: Move sharing code to support internal listeners. Because of hashing, the downstream filters can only use the upstream filter state to access the objects shared with the upstream internal listener. This allows easy access from the downstream filters for the back-propagated information.
Additional Description: Example:
HTTP Listener 1 writes a shared object `x_i` per request,
Cluster 1 has internal endpoint for listener 2. One of `x_i` objects from the transport options is written.
Listener 2 writes CONNECT response headers back to `x_i` from cluster 1.
Because the upstream is shared, HTTP filter on listener 1 should consult the connection filter state of listener 2 for the tunnel headers. But because of the user space socket, it's not directly accessible. The work around, …
> network: share filter state objects always

- test/common/filesystem/filesystem_impl_test.cc
- test/per_file_coverage.sh
Fixes:
https://github.com/envoyproxy/envoy/issues/25614
Signed-off-by: Aliasgar Ginwala <aginwala@ebay.com>
> FileReadToEndNotReadable keeps failing

- source/common/stream_info/stream_info_impl.h
- test/common/stream_info/stream_info_impl_test.cc
These were missed in https://github.com/envoyproxy/envoy/pull/23648.
Commit Message: Add a couple of missing fields to StreamInfoImpl::setFrom
Testing: Unit tested.
> Add a couple of missing fields to StreamInfoImpl::setFrom

- bazel/foreign_cc/luajit.patch
- bazel/repository_locations.bzl
- tools/code_format/check_format.py
Commit Message: lua: Upgrade the LuaJIT version to 2022-12-22
Additional Description: The current LuaJIT version used in Envoy is 1d8b747c161db457e032a023ebbff511f5de5ec2, which is created on 2020-10-12, more than 2 years ago. Plenty of bugfix and new features happen after that.
Risk Level: Middle
Testing:
Docs Changes:
Release Notes:
Fixes #25763
> lua: Upgrade the LuaJIT version to 2022-12-22

- source/common/upstream/load_balancer_impl.h
Commit Message: Reduce overhead in LoadBalancerSubsetInfoImpl by fixing alignment
> Reduce overhead in LoadBalancerSubsetInfoImpl by fixing alignment

- source/common/upstream/conn_pool_map.h
Commit Message: Reduce overhead in conn_pool_map by fixing alignment
> Reduce overhead in conn_pool_map by fixing alignment

- envoy/http/protocol.h
- source/common/upstream/health_checker_impl.cc
- source/common/upstream/health_checker_impl.h
Commit Message:  Reduce overhead in health_checker_impl by fixing alignment
> Reduce overhead in health_checker_impl by fixing alignment

- .azure-pipelines/pipelines.yml
This resolves ongoing disk issues (at least for this job), and also provides a pretty big speedup to CI
Partial fix for #25737 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Use `x64-large` ami/pool for x64 release/build/test

- docs/root/configuration/listeners/network_filters/zookeeper_proxy_filter.rst
- source/extensions/filters/network/zookeeper_proxy/decoder.cc
- source/extensions/filters/network/zookeeper_proxy/decoder.h
- source/extensions/filters/network/zookeeper_proxy/filter.cc
- source/extensions/filters/network/zookeeper_proxy/filter.h
- test/extensions/filters/network/zookeeper_proxy/filter_test.cc
Commit Message: [ZK filter] Add support for setwatches2 ZK opcode
Additional Description: Add support for setwatches2 ZK opcode: https://github.com/apache/zookeeper/blob/de7c5869d372e46af43979134d0e30b49d2319b1/zookeeper-jute/src/main/resources/zookeeper.jute#L83-L90
Docs Changes: [Updates the ZK filter statistics](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/zookeeper_proxy_filter#statistics)
> [ZK filter] Add support for setwatches2 ZK opcode

- docs/root/configuration/listeners/network_filters/mysql_proxy_filter.rst
- docs/root/start/sandboxes/mysql.rst
- examples/mysql/verify.sh
The mysql example tracks the `latest` mysql version so limiting the client to 5.7 (ie different from server) seems wrong.
This unpins the client version and improves the example/documentation about tested mysql versions.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> examples: Improve mysql version information

- mobile/library/common/extensions/filters/http/network_configuration/filter.cc
- mobile/test/common/integration/client_integration_test.cc
- mobile/test/common/integration/xds_integration_test.cc
- source/common/upstream/upstream_impl.cc
documenting why xDS tests don't have DNS timing metrics and fixing proxying test to use explicit IPs (loopback on CI resolved to an IPv6 address on IPv4 builds)
> mobile: cleaning up some test TODOs

- source/extensions/filters/network/zookeeper_proxy/decoder.cc
- source/extensions/filters/network/zookeeper_proxy/decoder.h
- test/extensions/filters/network/zookeeper_proxy/filter_test.cc
Commit Message: [ZK filter] Implement ZK filter buffer
Additional Description: Whenever new data appended to the read/write buffer, in general, the ZK filter will 
(1) prepends previous partial data fetched from the ZK filter buffer to the read/write buffer,
(2) decodes all full packet(s),
(3) adds the rest of the data to the ZooKeeper filter buffer,
(4) removes the prepended data.
In this case, the ZK filter will not prevent packets from being sent to the ZK service.
- Scenario 1:
```
| REQ 1 ---------- |
(onData1 )(onData2 )
```
- The `onData1` data will be copied to ZK filter buffer since it is not a full packet.
- When `onData2` data comes, ZK filter will
- prepend data from the ZK filter buffer to `onData2` data
- decode the REQ1 data since it is a full packet,
- drain ZK filter …
> [ZK filter] Implement ZK filter buffer

- envoy/network/connection.h
- source/common/network/connection_impl.h
- source/common/network/multi_connection_base_impl.cc
- source/common/network/multi_connection_base_impl.h
- source/common/quic/quic_filter_manager_connection_impl.cc
- source/common/quic/quic_filter_manager_connection_impl.h
- source/server/api_listener_impl.h
- test/mocks/network/connection.h
Commit Message: isHalfCloseEnabled() will work also on const Connections, as returned by many Envoy APIs, if we make it const.
Testing: Exiting test coverage is sufficient
Docs Changes:
Release Notes:
> connection: Make isHalfCloseEnabled const

- .azure-pipelines/bazel.yml
Currently the mobile `.bzl` files are included in the cache key despite belonging to a separate workspace, this excludes them
This also excludes the `envoy-docs` folder as this is created in the `publish/docs` job and appears to azp as a changed cache key.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/cache: Add cache key exclusions (mobile/generated docs)

- mobile/library/swift/EngineBuilder.swift
This is a really minor cleanup but will make upcoming Swift / C++ interop easier.
> mobile: store `runtimeGuards` values as booleans in Swift

- mobile/library/cc/engine_builder.cc
Commit Message: Remove `base_h2` cluster stats from stats inclusion list as `base_h2` cluster was removed and is no longer used.
Testing: N/A
Docs Changes:
Release Notes:
> envoy mobile stats: remove base_h2 stats

- bazel/envoy_build_system.bzl
- bazel/envoy_internal.bzl
- bazel/envoy_library.bzl
- bazel/envoy_mobile_copts.bzl
- bazel/envoy_mobile_defines.bzl
- mobile/bazel/apple.bzl
- mobile/library/common/jni/BUILD
- mobile/library/swift/BUILD
This is more correct and will work with upcoming changes to enable Swift and C++ interop.
Risk Level: Medium.
Testing: Existing.
Docs Changes: None.
> mobile: replace `envoy_mobile_copts` with `envoy_mobile_defines`

- source/common/http/http1/settings.cc
- source/common/http/http1/settings.h
- source/common/http/utility.cc
- source/common/http/utility.h
- test/common/http/utility_test.cc
BoolValue is a protobuf "Well known type" so should be referenced via the ProtobufWkt namespace not Protobuf. 
> cleanup: use ProtobufWkt::BoolValue instead of Protobuf::BoolValue

- bazel/setup_clang.sh
Currently if any of this file fails it silently continues with borked filepaths etc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> bazel: Fix error handling in `setup_clang.sh`

- envoy/http/filter.h
- source/common/http/match_delegate/config.h
- source/common/http/matching/data_impl.h
- source/common/router/config_impl.cc
- source/common/router/router_ratelimit.cc
- source/extensions/filters/common/rbac/engine_impl.cc
- source/extensions/filters/http/custom_response/config.cc
- source/extensions/filters/http/rate_limit_quota/filter.cc
- test/common/http/matching/BUILD
- test/common/http/matching/inputs_test.cc
- test/common/http/matching/status_code_input_test.cc
- test/common/network/matching/inputs_test.cc
- test/common/ssl/matching/BUILD
- test/common/ssl/matching/inputs_integration_test.cc
- test/common/ssl/matching/inputs_test.cc
- test/extensions/common/matcher/trie_matcher_test.cc
- test/extensions/filters/common/rbac/engine_impl_test.cc
- test/extensions/filters/http/rbac/rbac_filter_test.cc
- test/extensions/filters/network/rbac/filter_test.cc
With streamInfo as the input to Http matching data, it not only fulfills the existing functionality provided by ConnectionInfoProvider (ConnectionInfoProvider is got from stream_info.downstreamAddressProvider()), it but also provides more info that is available in streamInfo, via, for example, dynamic_metatdata and filter state.
The use case could be : the matching library like CEL expression could match on, for example, client_ip, upstream cluster name, etc that can be retrieved  from stream info.
Signed-off-by: tyxia [tyxia@google.com](mailto:tyxia@google.com)
> match: Pass streamInfo as input to Http matching data

- mobile/library/swift/EnvoyCxxSwiftInterop/BUILD
- mobile/library/swift/EnvoyCxxSwiftInterop/cxx_swift_interop.cc
- mobile/library/swift/EnvoyCxxSwiftInterop/cxx_swift_interop.h
- mobile/library/swift/EnvoyCxxSwiftInterop/module.modulemap
This exposes some headers and adds a minimal amount of C++ in order to be able to interact with Envoy's C++ code from Swift.
It will be tested via the Swift tests once hooked up.
Risk Level: Low/None, not used
Testing: Upcoming via Swift tests
> mobile: add `EnvoyCxxSwiftInterop` library

- mobile/library/objective-c/EnvoyConfiguration.h
- mobile/library/objective-c/EnvoyConfiguration.mm
- mobile/library/swift/EngineBuilder.swift
- mobile/test/swift/EngineBuilderTests.swift
This was never fully hooked up to the C++ builder in `-[EnvoyConfiguration applyToCXXBuilder]`.
Testing: Yes
> mobile: fix `setRuntimeGuard` Swift API

- source/common/quic/active_quic_listener.cc
- source/common/quic/active_quic_listener.h
- source/common/quic/envoy_quic_server_preferred_address_config_factory.h
- source/extensions/listener_managers/listener_manager/listener_impl.cc
- source/extensions/quic/server_preferred_address/fixed_server_preferred_address_config.cc
- source/extensions/quic/server_preferred_address/fixed_server_preferred_address_config.h
- test/common/quic/active_quic_listener_test.cc
- test/integration/fake_upstream.h
Commit Message: add ProcessContextOptRef into a bunch of factory interfaces.
Risk Level: low, no behavior change
Testing: existing tests passs
> quic: plumb ProcessContext reference into QUIC listener and server preferred address factory

- api/envoy/extensions/load_balancing_policies/client_side_weighted_round_robin/v3/client_side_weighted_round_robin.proto
- tools/spelling/spelling_dictionary.txt
Commit Message: api: add error_utilization_penalty param to WRR
Additional Description: Client-wide WRR added with #24520 needs to support the weight penalty using the error rate. This change adds a parameter that configures this behavior.
Testing: N/A
CC @markdroth
> api: add error_utilization_penalty param to WRR

- mobile/bazel/android_artifacts.bzl
- mobile/library/java/io/envoyproxy/envoymobile/engine/BUILD
Before:
```console
$ ./bazelw build --config release-android android_dist
INFO: Analyzed target //:android_dist (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //library/kotlin/io/envoyproxy/envoymobile:envoy_aar_with_artifacts up-to-date:
bazel-bin/library/kotlin/io/envoyproxy/envoymobile/envoy.aar
bazel-bin/library/kotlin/io/envoyproxy/envoymobile/envoy-pom.xml
bazel-bin/library/kotlin/io/envoyproxy/envoymobile/envoy-sources.jar
bazel-bin/library/kotlin/io/envoyproxy/envoymobile/envoy-javadoc.jar
INFO: Elapsed time: 0.282s, Critical Path: 0.07s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
$ rg chromium bazel-bin/library/kotlin/io/envoyproxy/envoymobile | wc -l
5
```
After:
```console
$ ./bazelw build --config release-android …
```
> mobile: remove chromium from main Android AAR

- mobile/docs/root/intro/version_history.rst
- mobile/library/objective-c/EnvoyConfiguration.h
- mobile/library/objective-c/EnvoyConfiguration.mm
- mobile/library/objective-c/EnvoyEngineImpl.mm
- mobile/library/swift/EngineBuilder.swift
- mobile/test/swift/EngineBuilderTests.swift
- mobile/test/swift/apps/experimental/ViewController.swift
Lyft ran experiments with this feature and it performed better than with Envoy's certificate validation.
Testing: Lyft apps, unit tests
> mobile: always enable using platform certificate validation on iOS

- mobile/library/cc/direct_response_testing.h
- mobile/library/cc/engine_builder.cc
- mobile/library/objective-c/EnvoyConfiguration.mm
- mobile/library/swift/EnvoyCxxSwiftInterop/cxx_swift_interop.h
They seem to have a number of advantages over "plain" enums according to https://stackoverflow.com/a/18335862, and this will allow them to be imported properly into Swift.
Also change case names to be PascalCase to conform to the style guide: https://github.com/envoyproxy/envoy/blob/main/STYLE.md
Similar to https://github.com/envoyproxy/envoy/pull/26036
Risk Level: Low, only used for Swift tests at the moment.
Testing: Existing tests.
Docs Changes: None.
> mobile: make `Envoy::DirectResponseTesting::MatchMode` an `enum class`

- .azure-pipelines/bazel.yml
- ci/build_setup.sh
- test/run_envoy_bazel_coverage.sh
Allowing flaky tests to pass hides a multitude of sins and means we dont actually deal with issues until they hit a critical mass of failure. Also, not all flakes are the same, most are just ~incorrect test assumptions and ~inconsequential, in some cases it can point to a critical failure or problem
Not allowing this still does not mean we will detect flakes immediately but it means we are going to see them a lot sooner and it will be a lot clearer where they started. Atm, we cant really trust CI without click, clikcking through to see what really happened.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional …
> ci: Remove `flaky_test_attempts`

- source/common/network/socket_interface_impl.cc
Failing to set the socket to v6 is no longer a fatal error. Instead it will be an ENVOY_BUG and using the socket (connect) may fail.
Part of https://github.com/envoyproxy/envoy/issues/24801
> envoy: changing a release assert to envoy bug

- test/server/BUILD
- test/server/guarddog_impl_test.cc
- test/server/guarddog_test_interlock.h
Commit Message: We need to run our own guard dog tests internally, and to make them non-flaky we need to share this interlock override. So this PR just pulls that out of the test.cc file and gives it a better name.
Additional Description:  n/a
Testing: test/server:guarddog_impl_test
> test: split out the test interlock so it can be re-used from test in other with guarddog functionality.

- .azure-pipelines/pipelines.yml
Since we switched off flaky acceptance in #26028 , the x64 job can fail in postsubmit sometimes which means the remaining checks are not run and we dont get the full ci reading
This makes them run in postsubmit even when the build tests fail
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Always run checks in postsubmit

- api/envoy/extensions/filters/http/cache/v3/cache.proto
- source/extensions/filters/http/cache/cache_filter.cc
- source/extensions/filters/http/cache/cache_filter.h
- source/extensions/filters/http/cache/config.cc
- test/extensions/filters/http/cache/cache_filter_test.cc
- test/extensions/filters/http/cache/config_test.cc
Commit Message: [cache-filter] Add disabled option
Additional Description: Adds the ability to have cache filter present but disabled. This makes it so a cache filter can more easily be configured with ECDS, and is a good precursor to making the configuration "inheritable". Addresses part of #25819.
This model is forward-compatible with the idea of inheritable/overrideable config, and the implementation is backward-compatible with existing config.
Risk Level: Low - cache filter is WIP, and change should be no-op for existing configs.
Testing: Added unit test coverage.
Docs Changes: Automatic from proto.
> [cache-filter] Add disabled option

- .azure-pipelines/pipelines.yml
moves the `bazel` call of of `run_envoy_docker` as the env vars are not accessible there
also fixes a case where CI is run manually on presubmit
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix bazel invokation for dockerhub README

- mobile/library/objective-c/EnvoyEngineImpl.mm
Commit Message: https://github.com/envoyproxy/envoy/pull/26010 replaces obj-c with Swift. Swift interop with C++ does not support all c++ features: all uncaught c++ exceptions become UB in Swift. Adding logging of C++ exceptions to see whether we have any. If yes, we may need to rethink whether we want to migrate to Swift.
Testing: 
Docs Changes:
Release Notes:
> core: log caught exceptions

- api/envoy/config/route/v3/route_components.proto
Commit Message: api: new field to the FilterConfig to disable a filter in specific route or vh
Testing: n/a.
> api: new field to the FilterConfig to disable a filter in specific route or vh

- source/extensions/filters/listener/http_inspector/http_inspector.cc
- source/extensions/filters/listener/original_dst/original_dst.cc
- source/extensions/filters/listener/tls_inspector/tls_inspector.cc
Currently, we have a generic "new connection accepted" at debug level, but "set to {}" at trace. This ends up being the inversion of what we typically want; we know any new connection will call the listener filter, but what is interesting is knowing the result.
This PR simply inverts the scopes, so we have the same amount of logs at `debug` but get more information.
Before this PR, a typical log would look like:
```
{"level":"debug","msg":"original_dst: new connection accepted"}
{"level":"trace","msg":"original_dst: set destination to 1.2.3.4:80"}
```
Inverting this will have a big impact for us, as folks usually send us `debug` level logs, which skips this critical bit of info
Commit Message: listener filters: improve logging levels
Testing: NONE …
> listener filters: improve logging levels

- mobile/.bazelrc
- mobile/BUILD
- mobile/bazel/apple.bzl
- mobile/docs/root/intro/version_history.rst
- mobile/library/objective-c/EnvoyConfiguration.h
- mobile/library/objective-c/EnvoyConfiguration.mm
- mobile/library/objective-c/EnvoyEngineImpl.mm
- mobile/library/swift/BUILD
- mobile/library/swift/EngineBuilder.swift
- mobile/library/swift/EnvoyCxxSwiftInterop/cxx_swift_interop.cc
- mobile/library/swift/EnvoyCxxSwiftInterop/cxx_swift_interop.h
- mobile/library/swift/cxx/Bootstrap.swift
- mobile/library/swift/cxx/DirectResponse+Cxx.swift
- mobile/library/swift/cxx/LogLevel+Cxx.swift
- mobile/library/swift/cxx/Swift+Cxx.swift
- mobile/test/swift/EngineBuilderTests.swift
- mobile/test/swift/apps/experimental/ViewController.swift
- mobile/test/swift/cxx/BUILD
- mobile/test/swift/cxx/LogLevelCxxTests.swift
Which will generate the `envoy::config::bootstrap::v3::Bootstrap` config using Swift / C++ interop instead of going through Objective-C.
This will allow us to remove the duplication between `EngineBuilder.swift` and `EnvoyConfiguration.{h,mm}` after we've run some experiments ensuring this performs well.
This is a lower risk alternative to https://github.com/envoyproxy/envoy/pull/26010 and https://github.com/envoyproxy/envoy/pull/26011.
Risk Level: Low, passing all tests, limited to generating the bootstrap config, validated that the bootstrap debug strings match between ObjC and Swift in Lyft's apps.
Testing: Yes
Docs Changes: No, intended to be a temporary transition and should be removed after experimentation.
Platform Specific …
> mobile: add `useSwiftBootstrap(...)` option to Swift engine builder

- mobile/.bazelrc
To work around this issue: https://github.com/buildbuddy-io/rules_xcodeproj/issues/1878
Risk Level: Low, local Xcode usage only
Testing: Locally in Xcode
> mobile: disable global index store

- mobile/.bazelrc
* `--host_java_toolchain` and `--java_toolchain` are no-ops in Bazel 6
* `--auth_enabled` is replaced with `--google_default_credentials`
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile: adjust bazel flags for Bazel 6

- ci/Dockerfile-envoy
The Envoy binary changes the most frequently (at least when publishing `dev` from `main`) and so should be last in the Docker recipes to preserve cached layers.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docker: Reorder layers by change frequency

- api/envoy/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto
- changelogs/current.yaml
- docs/root/intro/arch_overview/observability/access_logging.rst
- source/common/tcp_proxy/tcp_proxy.cc
- source/common/tcp_proxy/tcp_proxy.h
- test/common/tcp_proxy/tcp_proxy_test.cc
- test/integration/tcp_proxy_integration_test.cc
Commit Message: Add on-upstream-connected access log flush for TCP Proxy.
Additional Description:  None
Testing: Unit test, integration tests
Docs Changes: Access logs
Resolves #26058
> tcp_proxy: add on-upstream-connected access log flush

- source/common/router/upstream_codec_filter.h
Commit Message: Small reduction in memory by changing alignment in UpstreamCodecFilter
Sizeof test:
Before changes: 88
After changes: 80
> Reduce overhead in UpstreamCodecFilter by fixing alignment

- source/common/common/utility.cc
- source/common/common/utility.h
- source/common/http/date_provider_impl.cc
- source/common/http/date_provider_impl.h
We've seen shutdown crashes in E-M due to the deletion of this static object.
Testing: internal tsan now green
Fixes https://github.com/envoyproxy/envoy/issues/26091
> date provider: using a ConstSingleton date formatter

- .azure-pipelines/bazel.yml
- .azure-pipelines/cached.yml
- .azure-pipelines/docker/load_cache.sh
- .azure-pipelines/docker/prepare_cache.sh
- .azure-pipelines/docker/prime_cache.sh
- .azure-pipelines/pipelines.yml
- .azure-pipelines/stages.yml
This uses azp cache to store the envoy-build-ubuntu image
To make it work the cache is restored to/from tmpfs 
it also restores to/from `/var/lib/docker` as this was the only way to make it faster
It is slightly faster than just pulling the image from dockerhub
ive tested it quite a bit and its a lot more reliable (when the fix from #26056 is included) and brings down the average CI times by a consistent amount
priming the cache is slow and due to the issue discussed in #26050 it will currently happen on every pr by default, but that is easy to (manually atm) work around
partial fix for #25545 
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes commit #PR or …
> ci: Cache build image

- source/common/router/retry_state_impl.cc
- source/common/router/retry_state_impl.h
Commit Message: Reduce overhead in RetryStateImpl by fixing alignment
Sizeof test
Before changes: 280
After changes: 264
> Reduce overhead in RetryStateImpl by fixing alignment

- ci/setup_cache.sh
This provides a small but significant speed up for the arm and coverage jobs which have a lot cpus in CI and probably reflects better the intention in terms of CPU usage
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Use more CPUs for non-RBE

- ci/do_ci.sh
- docs/build.sh
- test/run_envoy_bazel_coverage.sh
- tools/proto_format/proto_format.sh
This reverts commit b2b03883a0a8ba3c83b499326cf6d4b82a1f3a93.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Revert "bazel: Use `remote_download_minimal` where possible (#26031)"

- test/integration/tcp_tunneling_integration_test.cc
Avoiding deleting the upstream while it's still serializing a goaway
Part of https://github.com/envoyproxy/envoy/issues/26068
Passes 2k runs clearly (before 7/2000 failed)
> test: fixing a tsan flake

- source/common/router/router.h
Commit Message: Reduce memory overhead in Filter by fixing alignment
Sizeof test:
Before changes: 536
After changes: 512
> Reduce memory overhead in Filter by fixing alignment

- api/envoy/config/rbac/v3/rbac.proto
- api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
- tools/extensions/extensions_schema.yaml
Commit Message: Add audit_log typed config in HCM and audit_condition enum in RBAC config protos.
[API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):
This API change is proposed for the feature implementation in gRPC first.
gRPC authorization is based on xDS RBAC proto. The audit logging support we are trying to add is to enable users configure loggers and audit authorization events when the audit condition is met.
The primary difference from the access log is that audit log should be invoked right after the RBAC evaluation is done and will not wait till after the entire call finishes. It seems to me this is something Envoy also lacks and could potentially benefit from.
The API change presented …
> api: audit_log api specific to RBAC http filters

- ci/do_ci.sh
- docs/build.sh
- tools/proto_format/proto_format.sh
This is the second attempt to minimize downloads in the checks, this time without touching coverage
Risk Level:
Testing:
Docs Changes:
Release Notes:
> bazel: Use `remote_download_minimal` where possible (/take2)

- test/integration/listener_lds_integration_test.cc
Commit Message: test: waiting for the upstream connection disconnected before invoke EXPECT_LOG_CONTAINS 
There is a race when `EXPECT_LOG_CONTAINS` invoke `Envoy::Logger::DelegatingLogSink::setShouldEscape(bool)` in the main test thread and the FakeUpstreamConnection will invoke `Envoy::Logger::DelegatingLogSink::setShouldEscape(bool)` in their own thread also.
So this PR will wait for the FakeUpstreamConnection disconnect first, then invoke the `EXPECT_LOG_CONTAINS`
Testing: n/a
Fixes #26082
> test: waiting for the upstream connection disconnected before invoke EXPECT_LOG_CONTAINS

- source/common/network/io_socket_handle_impl.cc
- source/common/network/io_socket_handle_impl.h
- source/common/runtime/runtime_features.cc
- test/integration/quic_http_integration_test.cc
Commit Message: if a UDP listener is configured with `ipv4_compat: true`, normalize the source address and the destination address from the control message of each incoming packet.
Testing: added new dual stack integration test
Runtime guard: envoy.restart_features.udp_read_normalize_addresses
Platform Specific Features: platforms supporting dual stack socket will see packet addresses normalized.
> udp: normalize local address if using dual stack socket

- source/common/upstream/upstream_impl.cc
- source/common/upstream/upstream_impl.h
Additional Description: Since LBConfigs are one-ofs, storing them inside a std::variant will allow us to save a bit of space.
Sizeof(ClusterInfoImpl)
Before changes: 2624
After changes: 2592
> Create LbPolicyConfig class to store variant for LBConfigs

- contrib/golang/filters/http/source/go/pkg/http/type.go
Commit Message: fix a small annotation mistake in go extension
Testing: N/A
> fix a small annotation mistake in go extension

- .azure-pipelines/cached.yml
- .azure-pipelines/docker/prime_cache.sh
- .azure-pipelines/stages.yml
Docker can pull images from other arches (now) so there is no need to use a huge arm instance to warm this cache
Doing this currently is creating a bottleneck on these expensive servers
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/cache: Use x86 agent to prime arm Docker cache

- .azure-pipelines/bazel.yml
- .azure-pipelines/stages.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Use tmpfs directories for self-hosted agents

- examples/golang/docker-compose-go.yaml
- examples/wasm-cc/docker-compose-wasm.yaml
this is a minor cleanup/optimization in which the go/wasm bazel compile examples re/use a bazel cache. 
also adds retry flags for those jobs
partial/possible fix for #26074 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/examples: Use bazel cache directories for compiling

- source/common/conn_pool/conn_pool_base.cc
Commit Message: Relax the over-zealous assertion. The assertion is triggered in the following scenario:
* pool has 2 pending streams and 2 connecting clients;
* pool is put into drain&delete mode;
* 1 client connects, onUpstreamReady is invoked
* 1 pending stream attached to a ready client, 2nd pending stream triggers tryCreateNewConnections
* assertion failure
Risk Level: low, debug assertion
Testing: manually verified no longer triggered
> conn pool: relax assertion for pending streams in draining

- source/extensions/filters/network/zookeeper_proxy/decoder.cc
- test/extensions/filters/network/zookeeper_proxy/filter_test.cc
Commit Message: [ZK filter] make multi request support delete operation
Additional Description: Based on the [ZK codebase](https://github.com/apache/zookeeper/blob/f4f0bed00dd254e34aedfe408799f557d60fd0e7/zookeeper-client/zookeeper-client-c/include/zookeeper.h#L339-L384), the multi request should support four operations (create, delete, set, and check). This diff add the support for the delete operation.
> [ZK filter] make multi request support delete operation

- .github/dependabot.yml
This prevents depdendabot from opening a load of PRs when the CI queue is busy
Risk Level:
Testing:
Docs Changes:
Release Notes:
> dependabot: At 9am UTC

- .github/workflows/mobile-compile_time_options.yml
- mobile/test/cc/unit/envoy_config_test.cc
This flag is enabled in regular tests, but we should test the case where it's disabled.  Seems like this test suite is the place intended for doing that!
Resolves https://github.com/envoyproxy/envoy/issues/26259
> Mobile: add google_grpc=disabled to compile_time_options test

- source/common/http/http3/conn_pool.cc
- test/common/common/packed_struct_test.cc
- test/common/http/http3/conn_pool_test.cc
- test/extensions/filters/http/buffer/buffer_filter_integration_test.cc
- test/extensions/filters/http/cache/cache_filter_integration_test.cc
- test/extensions/filters/http/compressor/compressor_integration_tests.cc
- test/extensions/filters/http/csrf/csrf_filter_integration_test.cc
- test/extensions/filters/http/custom_response/custom_response_integration_test.cc
- test/extensions/filters/http/fault/fault_filter_integration_test.cc
- test/extensions/filters/http/file_system_buffer/filter_integration_test.cc
- test/extensions/filters/http/jwt_authn/filter_integration_test.cc
- test/extensions/filters/http/kill_request/crash_integration_test.cc
- test/extensions/filters/http/kill_request/kill_request_filter_integration_test.cc
- test/extensions/filters/http/local_ratelimit/local_ratelimit_integration_test.cc
- test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
- test/extensions/internal_redirect/redirect_extension_integration_test.cc
- test/extensions/transport_sockets/http_11_proxy/connect_integration_test.cc
- test/integration/circuit_breakers_integration_test.cc
- test/integration/fake_upstream.cc
- test/integration/filter_integration_test.cc
- test/integration/header_integration_test.cc
- test/integration/http_conn_pool_integration_test.cc
- test/integration/http_protocol_integration.h
- test/integration/idle_timeout_integration_test.cc
- test/integration/instantiate_protocol_integration_test.cc
- test/integration/local_reply_integration_test.cc
- test/integration/overload_integration_test.cc
- test/integration/protocol_integration_test.cc
- test/integration/protocol_integration_test.h
- test/integration/websocket_integration_test.cc
Commit Message: Enable HTTP/3 in tests
Additional Description: This PR sets the stage to work on HTTP/3 upgrade header normalization by enabling HTTP/3 in various tests
This PR is a relanding of #26197 with all the non-test changes reverted
This PR is based on https://github.com/envoyproxy/envoy/pull/26107 by @asingh-g
> Enable HTTP/3 in tests

- contrib/golang/filters/http/test/BUILD
- contrib/golang/filters/http/test/golang_integration_test.cc
fix #26182
it's due to sendData on terminated request could cause segfault.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> fix flake golang test.

- test/integration/fake_upstream.cc
- test/integration/fake_upstream.h
Commit Message: test: fix the race of release read filter in FakeRawConnection
There is a race when the destructor of FakeRawConnection is invoked in the test main thread.
The shared ptr of `FakeRawConnection::read_filter_` will be released both in the test main thread and upstream connection's own thread by calling `removeReadFilter`.
This PR just use the shared ptr for `FakeRawConnection::read_filter_`, then after the read_filter_ move into the lambda, there will be no release work for the read_filter in the test main thread anymore.
Fixes part of #26082
> test: fix the race of release read filter in FakeRawConnection

- test/extensions/http/cache/file_system_http_cache/file_system_http_cache_test.cc
Commit Message: Skip stats validation in file_system_cache tests, due to flakes
Additional Description: The stats validation aspect of these tests appears to be flaky. For quick deflaking, just commenting out those parts of the test, to be investigated and reenabled once the flakiness is resolved. #26261 is one example.
Risk Level: test-only
Testing: test-only
> Skip stats validation in file_system_cache tests, due to flakes

- CODEOWNERS
Update codeowners for qat and cryptomb extensions.
@VillePihlava @soulxu @giantcroc
Testing: N/A
> CODEOWNERS: update qat and cryptomb extension owners.

- test/extensions/filters/network/http_connection_manager/config_test.cc
https://dev.azure.com/cncf/envoy/_build/results?buildId=131803&view=logs&j=8bf29878-a4cc-50f7-4e84-2255e6fd4065&t=10423dec-52d0-5521-c797-f153bdaa8e53&l=861
[ RUN      ] HttpConnectionManagerConfigTest.OverallSampling
test/extensions/filters/network/http_connection_manager/config_test.cc:676: Failure
Expected: (900) <= (sampled_count), actual: 900 vs 898
Stack trace:
0x564605d3ccc3: Envoy::Extensions::NetworkFilters::HttpConnectionManager::(anonymous namespace)::HttpConnectionManagerConfigTest_OverallSampling_Test::TestBody()
0x56460840c924: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
0x5646084079f7: testing::internal::HandleExceptionsInMethodIfSupported<>()
0x5646083ee9c2: testing::Test::Run()
0x5646083ef399: testing::TestInfo::Run()
... Google Test internal frames ...
> test: increasing range for non-determinstic check

- test/extensions/filters/http/cache/cache_filter_integration_test.cc
Commit Message: Fix issue 26081: cache_filter_integration_test is flakey.
Additional Description: Test-only change
Testing: bazel test //test/extensions/filters/http/cache:cache_filter_integration_test --test_output=errors --runs_per_test=10000 --test_filter=Protocols/CacheIntegrationTest.ServeGetFromUpstreamAfterHeadRequest/*
Fixes #26081
> Fix issue 26213: cache_filter_integration_test is flakey.

- test/integration/buffer_accounting_integration_test.cc
Commit Message: Fix rare flake that occurs in buffer_accounting_integration_test under coverage.
Additional Description: Timeout should be < request timeout, otherwise it's possible in rare cases for the request timeout to fire and there to be 0 acct, 0 buffers
```
[02:56:51] kbaichoo:flakes:8 $bazel test  //test/integration:buffer_accounting_integration_test --test_filter="*Http2BufferWatermarksTest.ShouldCreateFourBuffersPerAccount*" --config=coverage --runs_per_test=500 --test_arg="-l trace"
INFO: Analyzed target //test/integration:buffer_accounting_integration_test (0 packages loaded, 526 targets configured).
INFO: Found 1 test target...
INFO: LCOV coverage report is located at /usr/local/google/home/kbaichoo/.cache/bazel/_bazel_kbaichoo/61c1ba18b260ff88e00a438d66dafab5/execroot/envoy/ …
```
> CI Flake: Set timeout to be less than request timeout.

- api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
- api/envoy/service/auth/v3/attribute_context.proto
- changelogs/current.yaml
- source/extensions/filters/common/ext_authz/check_request_utils.cc
- source/extensions/filters/common/ext_authz/check_request_utils.h
- source/extensions/filters/http/ext_authz/ext_authz.cc
- source/extensions/filters/http/ext_authz/ext_authz.h
- test/extensions/filters/common/ext_authz/check_request_utils_test.cc
There isn't any way to pass along SNI used for the underlying connection to the external authorization server.
This patch introduces a new field on the CheckRequest to send TLS session data to the authorization server. Only SNI is sent with this patch, more TLS session-related data can be introduced in the future.
Commit Message: ext-authz: send SNI in CheckRequest to the authorization server
Risk Level: Low because this is an optional feature in a filter
Work in progress, I will fill the below out if the change seems acceptable from an API perspective.
Testing: added a unit test to ensure that the additional data is correctly populated
Docs Changes: No docs changes are done assuming that the doc string in filter configuration is sufficient 
Release Notes: Included …
> ext-authz: send SNI in CheckRequest to the authorization server

- test/integration/http2_flood_integration_test.cc
I'm unable to recreate this failure so far. Disabling the test while continuing to debug.
Related Issue #26088
> Temporarily disable flaky Http2FloodMitigationTest.RequestMetadata test

- mobile/docs/root/intro/version_history.rst
- mobile/library/objective-c/EnvoyConfiguration.h
- mobile/library/objective-c/EnvoyConfiguration.mm
- mobile/library/objective-c/EnvoyEngineImpl.mm
- mobile/library/swift/EngineBuilder.swift
- mobile/test/swift/EngineBuilderTests.swift
- mobile/test/swift/apps/experimental/ViewController.swift
Commit Message: Reverting https://github.com/envoyproxy/envoy/pull/26033 as platform cert validation breaks the upload of Envoy Mobile stats. The issue is being discussed offline.
Testing:
Docs Changes:
Release Notes:
> mobile: Revert "mobile: always enable using platform certificate validation"

- source/common/network/utility.cc
- test/common/network/utility_test.cc
Commit Message: implement protobufAddressToAddress for EnvoyInternalAddress
Testing: CI
Signed off by: Eugene Chan <eugenechan@google.com>
> upstream: implement protobufAddressToAddress for EnvoyInternalAddress

- contrib/hyperscan/matching/input_matchers/source/BUILD
- contrib/hyperscan/matching/input_matchers/source/config.cc
- contrib/hyperscan/matching/input_matchers/source/matcher.cc
- contrib/hyperscan/matching/input_matchers/source/matcher.h
- contrib/hyperscan/matching/input_matchers/test/BUILD
- contrib/hyperscan/matching/input_matchers/test/matcher_speed_test.cc
- contrib/hyperscan/matching/input_matchers/test/matcher_test.cc
- contrib/hyperscan/regex_engines/source/config.cc
- contrib/hyperscan/regex_engines/source/regex.cc
- contrib/hyperscan/regex_engines/source/regex.h
- contrib/hyperscan/regex_engines/test/BUILD
- contrib/hyperscan/regex_engines/test/regex_test.cc
Commit Message: hyperscan: fix matching with uninitialized thread local
Additional Description: when compiling and using stats matcher, TLS may not be initialized at that time. The patch allows Hyperscan to generate temporary scratch space for matching without TLS.
Testing: Unit
> hyperscan: fix matching with uninitialized thread local

- examples/BUILD
- examples/cache/ci-responses.yaml
- examples/cache/docker-compose.yaml
- examples/cache/verify.sh
- examples/front-proxy/verify.sh
- speed up cache example by reducing `max-age`
- remove sleep from front-proxy example
Risk Level:
Testing:
Docs Changes:
Release Notes:
> examples: Further cleanups/optimizations

- source/docs/async_http_filters.md
Commit Message: Add a doc about async http filters
Additional Description: The async behavior of http filters is unclear and not very well documented. I explained it somewhat incorrectly in Slack, learned more, and I believe this explanation is reasonably accurate and helpful.
Risk Level: None, code-doc-only.
Testing: n/a
Docs Changes: Code-doc only.
> Add a doc about async http filters

- .azure-pipelines/stages.yml
- .gitignore
- ci/do_ci.sh
- distribution/BUILD
- distribution/packages.bzl
This allows the distribution packaging (ie debs) to be provided with the path to a custom envoy binary, which means we dont have to rebuild the binary in the packaging jobs, saving quite a lot of time and resources, and also using the same binary as the one in the docker container/github assets
Risk Level:
Testing:
Docs Changes:
Release Notes:
> distribution: Allow customization of Envoy binary and speed up packaging

- docs/root/intro/arch_overview/advanced/data_sharing_between_filters.rst
- docs/root/intro/arch_overview/upstream/connection_pooling.rst
- envoy/stream_info/filter_state.h
- source/common/stream_info/filter_state_impl.cc
- source/common/stream_info/filter_state_impl.h
- test/common/network/connection_impl_test.cc
- test/common/network/transport_socket_options_impl_test.cc
- test/common/stream_info/filter_state_impl_test.cc
- test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc
- test/extensions/io_socket/user_space/io_handle_impl_test.cc
- test/extensions/transport_sockets/internal_upstream/internal_upstream_test.cc
- test/integration/filters/header_to_filter_state.cc
Commit Message: Add warning to documentation about using filter state "shared with upstream". Rename the enum to explicitly warn.
Testing: none
> docs: warn against shared objects

- mobile/envoy_build_config/BUILD
- mobile/envoy_build_config/extension_registry.cc
Moving 2 more extensions to the listener-on build
Testing: CI
Platform Specific Features
> mobile: cleaning up listener registry

- test/common/http/conn_manager_impl_test.cc
Commit Message: add stream state tests for new request access logs
Additional Description: Follow up to https://github.com/envoyproxy/envoy/pull/26155 and https://github.com/envoyproxy/envoy/pull/26256 to add checks for filter state value
> hcm: add stream state tests for new request access logs

- source/extensions/clusters/eds/eds.cc
- source/extensions/clusters/eds/eds.h
Commit Message: improve memory usage switching from optional to unique_ptr in EDS
EDS has an optional field to keep its contents that is used in LEDS. This PR changes from optional to unique_ptr, thus switching from 944 bytes per EDS-cluster to 792 bytes per EDS-cluster.
Risk Level: low - shouldn't impact behavior.
Testing: N/A
> eds: improve memory usage switching from optional to unique_ptr

- source/common/filter/config_discovery_impl.h
- test/integration/extension_discovery_integration_test.cc
Commit Message: Ensure extension config is always deleted on the main thread.
Additional Description: There is an implicit data race with the following interleaving:
1) TLS runOnAllThreads invoked to clear the extension config.
2) TLS deleted, a post is invoked on all workers to delete its storage.
3) TLS runOnAllThreads on workers does nothing because of step 2). 
4) TLS runOnAllThreads runs the completion callback on the main thread.
5) TLS deletion post invoked on some worker, deleting the last instance of the extension config.
The workaround is to prevent 2) from happening while `runOnAllThreads` is running. This is done by capturing TLS in the completion callback, and explicitly resetting it and the associated filter config in the callback.
Note that we cannot rely on the main_config …
> ecds: fix the clean deletion logic

- distribution/binary/compiler.bzl
This allows the output from differently compiled outputs to be packaged together
Risk Level:
Testing:
Docs Changes:
Release Notes:
> bazel/distribution: Add `bundled` rule and compiler transition

- ci/build_setup.sh
- test/run_envoy_bazel_coverage.sh
- tools/zstd/BUILD
- tools/zstd/zstd.bzl
This PR exposes the zstd binary and speedsup coverage by compressing zst files multi-core
i will follow up with some speedups for `pkg_tar` and other places
Risk Level:
Testing:
Docs Changes:
Release Notes:
> bazel/ci: Speed up compression with zstd

- distribution/binary/compiler.bzl
this wasnt needed for current use, and its effect is not entirely clear
Risk Level:
Testing:
Docs Changes:
Release Notes:
> distribution: Remove `linkopts` from bundle rule

- bazel/foreign_cc/BUILD
Disables unused icu features by using configuration options and environment variables and reduces the icu build time by half.
- Disables the icu-io (ustdio/iostream) library (`--disable-icuio`)
- Hardcodes the default icu charset to UTF-8
- Turns off conversion apart from UTF, CESU-8, SCSU, BOCU-1, US-ASCII, and ISO-8859-1
- Turns off break iteration
- Turns off collation and collation-based string search
- Turns off all formatting (date, time, number, etc), and calendar/timezone services
- Turns off script-to-script transliteration
- Turns off the regular expression functionality
Documentation
- icu feature flags: [https://github.com/unicode-org/icu/icu4c/source/configure#L1449](https://github.com/unicode-org/icu/blob/29443b8be710640ded073116b768da35f00cf0dd/icu4c/source/configure#L1449) …
> ci: disable unused icu features

- source/common/upstream/cluster_manager_impl.cc
- source/common/upstream/upstream_impl.cc
- test/common/upstream/upstream_impl_test.cc
Otherwise, we'll hit assert in allocateConnPool.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> upstreamHttpProtocol: choose HTTP11 when use_downstream_protocol_config is enabled and downstream protocol is HTTP10.

- .azure-pipelines/stages.yml
In #26535 the skip checks were skipped in postsubmit
In the case of publishing this check is required to proceed to publish docs etc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix publishing in postsubmit

- ci/Dockerfile-envoy
…
Bumps distroless/base-nossl-debian11 from `8c880fa` to `9523ef8`.
---
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.25] build(deps): bump distroless/base-nossl-debian11 to `523ef8` in /ci (#26531)

- ci/Dockerfile-envoy
… in /ci (#25748)
Bumps distroless/base-nossl-debian11 from `8c880fa` to `78d2ac0`.
---
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.22] build(deps): bump distroless/base-nossl-debian11 to `78d2ac0`

- ci/Dockerfile-envoy
…
Bumps distroless/base-nossl-debian11 from `8c880fa` to `9523ef8`.
---
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] build(deps): bump distroless/base-nossl-debian11 to `523ef8` in /ci (#26531)

- ci/Dockerfile-envoy
Bumps distroless/base-nossl-debian11 from `8c880fa` to `9523ef8`.
---
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] build(deps): bump distroless/base-nossl-debian11 to `523ef8` (#26531)

- mobile/test/common/integration/BUILD
Both the RTDS and CDS integration tests rely on Google gRPC now, and should only be run if the tests are run with
`--define=ENVOY_GOOGLE_GRPC`.
> mobile: Add a select on Google gRPC to the RTDS and CDS tests

- test/extensions/filters/network/http_connection_manager/config_test.cc
https://dev.azure.com/cncf/envoy/_build/results?buildId=133169&view=logs&j=e969334a-0e55-5c18-ac96-8b546753391e&t=5f9366f5-7a33-57e0-9006-756d2debe841
```console
[ RUN      ] HttpConnectionManagerConfigTest.OverallSampling
external/envoy/test/extensions/filters/network/http_connection_manager/config_test.cc:677: Failure
Expected: (1100) >= (sampled_count), actual: 1100 vs 1103
Stack trace:
0x15f6afa: Envoy::Extensions::NetworkFilters::HttpConnectionManager::(anonymous namespace)::HttpConnectionManagerConfigTest_OverallSampling_Test::TestBody()
0x3e7f57b: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
0x3e6ff0d: testing::internal::HandleExceptionsInMethodIfSupported<>()
0x3e584f3: testing::Test::Run()
0x3e590ba: testing::TestInfo::Run()
... Google Test internal frames ... …
```
> test: widen range for non-deterministic test

- test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc
https://dev.azure.com/cncf/envoy/_build/results?buildId=133169&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=00ade0d6-ffae-5af0-b5e0-e33b1813c8bc
test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc:231: Failure
Expected equality of these values:
3u
Which is: 3
test_server_->counter("cluster.cluster_0.upstream_cx_destroy")->value()
Which is: 2
Stack trace:
0x9bc70a: (unknown)
0x7f0f4048d32d: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
0x7f0f404740ae: testing::internal::HandleExceptionsInMethodIfSupported<>()
0x7f0f4045b9ad: testing::Test::Run()
0x7f0f4045c49e: testing::TestInfo::Run()
... Google Test internal frames ...
> test: waiting on a counter

- test/common/http/http1/http1_connection_fuzz_test.cc
Currently, the http1 connection fuzz test only fuzzes the (default-enabled) "legacy" http1 codec.
This patch enables fuzzing the balsa codec.
> http1 codec fuzzing: fuzz balsa, too

- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/test/golang_filter_test.cc
i.e. stream reset may happen before entering a golang filter, so that onDestroy will be invoked before any decodeHeaders or encodeHeaders.
fix #26537
Risk Level:
Testing:
Docs Changes:
Release Notes:
> fix panic in golang filter: req_ may be nullptr

- source/extensions/http/cache/file_system_http_cache/cache_eviction_thread.cc
- test/extensions/http/cache/file_system_http_cache/file_system_http_cache_test.cc
Commit Message: [file_system_http_cache] re-enable deflaked tests
Additional Description: Fixes the flake from issue #26261 - reproduced by adding a `std::this_thread::yield()` in the racy area, making it fail ~20%; passed with runs_per_test=50 after the fix with/without the yield.
Risk Level: Low, stats-only, WIP-extension-only
> [file_system_http_cache] re-enable deflaked tests

- test/integration/admin_html/BUILD
Currently these tests never respect cached test results and are always run when the commit is different
Risk Level:
Testing:
Docs Changes:
Release Notes:
> test: Dont stamp admin_html test

- .github/dependabot.yml
- ci/do_ci.sh
- tools/base/requirements.in
- tools/base/requirements.txt
- tools/dependency/BUILD
the `pip_check` tool has been renamed to `dependatool` and includes docker and go checks and related fixes
Fix #26163 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> deps: Switch `envoy.dependency.pip_check` -> `dependatool`

- envoy/filesystem/filesystem.h
- source/common/filesystem/posix/filesystem_impl.cc
- source/common/filesystem/posix/filesystem_impl.h
- source/common/filesystem/win32/filesystem_impl.cc
- source/common/filesystem/win32/filesystem_impl.h
- test/common/filesystem/filesystem_impl_test.cc
- test/mocks/filesystem/mocks.h
- test/test_common/file_system_for_test.cc
- test/test_common/file_system_for_test.h
Commit Message: Add createPath to Filesystem abstraction
Additional Description: This will be useful for file_system_http_cache, enabling it to create a cache directory rather than requiring the target path to already exist.
Risk Level: None, the additional function is not used in this change, and will only impact where it is added later.
Testing: Added test for the success behavior; not sure it's feasible to reliably test the failure behavior.
Platform Specific Features: Implemented identically per-platform.
> Add createPath to Filesystem abstraction

- bazel/BUILD
- bazel/get_workspace_status
- ci/format_pre.sh
- tools/code/BUILD
- tools/code/check_test.sh
- tools/proto_format/BUILD
- fix a subtle bug introduced in #26496 
- use `no-remote-exec` over `no-remote` to get caching
- switch `envoy.code.check` to use bazel test
Switching to bazel test gives a reasonable speedup in the default case, and in some rare circumstances (cached run against same files) it will allow the test to use cached results
it will also potentially allow the test to be run alongside others, but it already uses any procs available so this probably wont help unless either this test or the other is run remotely - in the case of this test that is probs not desirable as currently it checks non-bazel files from the local fs
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional …
> bazel/ci: Cleanups/fix/update

- envoy/filesystem/filesystem.h
- source/common/filesystem/posix/filesystem_impl.cc
- source/common/filesystem/posix/filesystem_impl.h
- source/common/filesystem/win32/filesystem_impl.cc
- source/common/filesystem/win32/filesystem_impl.h
- test/common/filesystem/filesystem_impl_test.cc
- test/mocks/filesystem/mocks.h
- test/test_common/file_system_for_test.cc
- test/test_common/file_system_for_test.h
This reverts commit 7b18ae855ab2605234420d85b5d6e3ada808ff55.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Revert "Add createPath to Filesystem abstraction (#26609)"

- test/integration/listener_lds_integration_test.cc
Commit Message: test: fix the flaky of RemoveListenerAfterInPlaceUpdate
The listener sockets are closed async, so using a while loop to detect a connect success or not.
Testing: flaky test
Fixes #22348
> test: fix the flaky of RemoveListenerAfterInPlaceUpdate

- .azure-pipelines/bazel.yml
- .azure-pipelines/pipelines.yml
- .azure-pipelines/stages.yml
- ci/build_setup.sh
- ci/run_envoy_docker.sh
This separates the pipelines ->  schedule/post/presubmit and allows setting test cache policies independently
In this Pr only scheduled jobs run tests uncached, which should massively speed up the normal postsubmit run, increase the pass rate and reduce resources
To compensate for the loss of information about flaky tests (that can sometimes pass and will be cached) scheduled uncached runs are configured
I will set up the azp scheduling for this as soon as this lands - Im thinking `main` 2x daily and `release/vX` 2x weekly
Fix #26643 
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
> ci: Switch postsubmit default tests -> cached  in separated CI pipelines

- .azure-pipelines/bazel.yml
- .azure-pipelines/stages.yml
Currently the clang-tidy script uses git to determine what to compare using clang-tidy-diff
This requires either a full repo checkout or unshallowing it in the script (which it does in some circumstances)
This breaks in cache-warming CI runs (or any non-PR run on presubmit) currently
This PR fixes that by ensuring that clang-tidy always has a full checkout in CI 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Make repo checkout configurable and fix clang-tidy

- contrib/generic_proxy/filters/network/test/router/router_test.cc
- source/common/http/async_client_impl.cc
- source/common/tracing/http_tracer_impl.cc
- source/common/tracing/tracer_impl.cc
- test/common/http/async_client_impl_test.cc
- test/common/router/router_2_test.cc
- test/common/tracing/http_tracer_impl_test.cc
- test/common/tracing/tracer_impl_test.cc
Commit Message: tracing: get cluster name from cluster info rather than upstream info
See #25887. In the previous impl, we will try to get cluster name from upstream info and set the name in the span. But if there is no valid upstream host, the upstream info will be null and the cluster name will not be set in the span.
In the new impl, we will try to get the cluster name from the cluster info to ensure even there is no valid upstream host, the cluster name will be set in the span.
Testing: unit.
> tracing: get cluster name from cluster info rather than upstream info

- envoy/http/header_validator.h
- source/extensions/http/header_validators/envoy_default/header_validator.cc
- source/extensions/http/header_validators/envoy_default/header_validator.h
- source/extensions/http/header_validators/envoy_default/http1_header_validator.cc
- source/extensions/http/header_validators/envoy_default/http1_header_validator.h
- source/extensions/http/header_validators/envoy_default/http2_header_validator.cc
- source/extensions/http/header_validators/envoy_default/http2_header_validator.h
- test/extensions/http/header_validators/envoy_default/BUILD
- test/extensions/http/header_validators/envoy_default/header_validator_test.cc
- test/extensions/http/header_validators/envoy_default/http1_header_validator_test.cc
- test/extensions/http/header_validators/envoy_default/http2_header_validator_test.cc
- test/mocks/http/header_validator.h
The public API for individual header validation was not used. This PR removes it from public interface and updates unit tests for these methods with equivalent tests using entire header map validation.
> Remove unused public UHV API for individual header validation

- .github/workflows/release_branch.yml
- ci/create_release_branch.sh
- ci/reopen_branch.sh
This PR:
- forks `main` to a new release branch upon a tagged release
- reopens the `main` branch
As a follow up we could lock `main` when a release commit lands and then unlock it here
I was tempted to do this but figured leave that to a further iteration as it requires some thought about failure handling
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Automate creation of release branch from `main`

- .azure-pipelines/stages.yml
Currently there is an issue where using an injected tarball with Docker can hang
This is (hopeful) workaround to just limit the time
Also adds some debugging so we can see what it has downloaded
Related to #26634 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Set a timeout on docker publish job

- source/common/quic/envoy_quic_server_stream.cc
- test/common/quic/envoy_quic_server_stream_test.cc
- test/integration/quic_http_integration_test.cc
Commit Message: Fix bad assertion on malformed QUIC trailer
Additional Description: This change allows for a graceful stream reset instead of failing an assertion on a malformed QUIC trailer (e.g. uppercase or empty name). Found via fuzz testing by robert.femmer@x41-dsec.de.
Testing: Includes unit test
> Fix bad assertion on malformed QUIC trailer

- ci/run_clang_tidy.sh
the cause of the issue addressed here is that when we were checking out with a shallow checkout github creates a "merge" commit, so the comparison algo worked - it compared against the merge commit.
Switching to non-shallow checkout (to make clang-tidy work more generally and to avoid needing to unshallow in this case) meant that instead the comparison commit was the actual unmerged commit in a given PR - hence a lot more change
Fix #26743
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix clang-tidy-diff (again)

- source/extensions/filters/network/zookeeper_proxy/decoder.cc
- source/extensions/filters/network/zookeeper_proxy/decoder.h
Commit Message: [ZK filter] Decoding with request/response data + full packets length
Additional Description: Using request/response data with full packets length to do decoding instead of copying data to a new buffer or using the buffer fragment.
The benefit of buffer fragment is minimal. This is because we have to use `linearize()` to fetch the pointer of the data. Within `linearize()`, it will move the data chunk to a continuous location.
If we pass the original data, together full packets length, we are able to decode full packets without moving any full packets data.
> [ZK filter] Decoding with request/response data + full packets length

- .azure-pipelines/bazel.yml
- .bazelrc
- bazel/get_workspace_status
- ci/run_envoy_docker.sh
Fix #26632 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Dont stamp Envoy binary in Pull Requests

- ci/build_setup.sh
- ci/setup_cache.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix for setting `test_tmpdir` in non-RBE

- test/common/router/retry_state_impl_test.cc
Commit Message: add additional test case for retriable-status-codes
Additional Description: add additional test case for retriable-status-codes to validate that it does not work for gRPC status
Testing: N/A
> add additional test case for retriable-status-codes

- test/run_envoy_bazel_coverage.sh
The self-hosted machines used to run coverage are far from the azp artefact upload, and these machines have lots of cores so compressing more is beneficial.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Compress coverage tarballs more

- .github/actions/pr_notifier/pr_notifier.py
- CODEOWNERS
- OWNERS.md
- mobile/bazel/pom_template.xml
Lyft is winding down its involvement in the Envoy Mobile project, and consequently JP and Rafal will no longer be actively maintaining Envoy Mobile.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> owners: update Envoy Mobile owners

- mobile/docs/root/intro/version_history.rst
- mobile/library/kotlin/io/envoyproxy/envoymobile/Stream.kt
- mobile/library/kotlin/io/envoyproxy/envoymobile/grpc/GRPCStream.kt
- mobile/library/swift/grpc/GRPCStream.swift
- mobile/test/kotlin/io/envoyproxy/envoymobile/GRPCStreamTest.kt
- mobile/test/swift/GRPCStreamTests.swift
Commit Message: `GRPCStream` should be closed using `cancel` and not a `close` method. Both manual testing and A/B experimentation confirm that the latter results in desired (and better in comparison) perf characteristics.
Testing:
Docs Changes:
Release Notes:
> mobile: remove GRPCStream's close method

- mobile/.bazelrc
- mobile/.swiftlint.yml
- mobile/bazel/config.bzl
- mobile/docs/root/intro/version_history.rst
- mobile/docs/root/start/building/building.rst
Commit Message: change Envoy Mobile min ios version from 12.0 to 13.0
Docs Changes: version history is updated
Release Notes: added this change in the pending release note.
Platform Specific Features: ios only
> change Envoy Mobile min ios version from 12.0 to 13.0

- mobile/.bazelrc
- mobile/docs/root/intro/version_history.rst
Commit Message: bump Envoy-mobile's min macOS version to 10.15
Docs Changes: added to pending release note
Release Notes: changed
Platform Specific Features: Apple platforms only.
> bump Envoy-mobile's min macOS version to 10.15

- ci/docker_ci.sh
Workaround/~ fix #26338
This is a docker bug that seems to be triggered by some kinda transient network issue
Not sure how well this will work, but there are not many other options atm
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Add retry on flaky Docker tag command

- source/common/http/headers.h
Signed-off-by: Hiram Silvey [hiramj@google.com](mailto:hiramj@google.com)
Commit Message: Adds the RFC 9211 `Cache-Status` standard header constant to headers.h.
Additional Description: This allows clients of Envoy to easily populate the header using an Envoy-defined constant rather than creating their own constants.
Testing: N/A
> http headers: add the rfc 9211 cache-status standard header constant

- mobile/test/common/http/client_test.cc
- test/test_common/environment.cc
- test/test_common/environment.h
We'd like to run common and cc tests on the iOS simulator inside Google.  The ::system and EXPECT_DEATH calls are not supported on iOS, so I have ifdeffed them out.
I've already made this change internally and enabled iOS tests!
> Mobile: Ifdef escape some test code which isn't supported on iOS

- changelogs/current.yaml
- envoy/http/codec.h
- source/extensions/filters/network/http_connection_manager/config.cc
- test/extensions/filters/network/http_connection_manager/config_test.cc
Commit Message: add runtime value for max requests headers size
Additional Description: add runtime value for max requests headers size so that the global value can be configured and changed at runtime as needed
Testing: Updated
> http: add runtime value for max requests headers size

- test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
- test/test_common/utility.h
Tests are timing out due to waitForHttpConnection() call or waitForNewStream() taking longer in ASAN tests.  Changing the timeout to be 3 times longer.
Also, the timer added for the new time out API tests are too tight. For example, it sends out a new time out as 500ms, then let the ext_proc service idle for 300ms. In normal cases, the response from upstream will be able to be sent back to the downstream client in time, i.e, before that 500ms timer expires.  However, if the CPU is busy in ASAN tests, the timer can fire up causing the test fails.  So, changing the new timeout to be a much larger number, like 60s to largely avoid such timing issue.
Risk Level:
Testing:
Docs Changes:
Release Notes: …
> Some ext_proc_integration_tests are timinig out in ASAN test

- ci/build_setup.sh
Commit Message: append variable, then export
Additional Description: As seen in issue https://github.com/envoyproxy/envoy/issues/26921 exporting and appending in the same line works in @phlax environment. It also works for me in a clean ubuntu image. However, in our company build environment, something is different in the environment where it does not tolerate the the export statement ending in '+'.
So break the line into 2 lines.
Testing:
Docs Changes:
Release Notes:
> ci: remove unneeded export

- source/extensions/filters/network/local_ratelimit/local_ratelimit.cc
- test/extensions/filters/network/local_ratelimit/local_ratelimit_test.cc
Commit Message: fix network local ratelimit connection close without reason
Testing: ut
> fix network local ratelimit connection close without reason

- envoy/filesystem/filesystem.h
- mobile/test/common/integration/base_client_integration_test.cc
- source/common/filesystem/posix/filesystem_impl.cc
- source/common/filesystem/posix/filesystem_impl.h
- source/common/filesystem/win32/filesystem_impl.cc
- source/common/filesystem/win32/filesystem_impl.h
- test/common/filesystem/filesystem_impl_test.cc
- test/mocks/filesystem/mocks.h
- test/test_common/file_system_for_test.cc
- test/test_common/file_system_for_test.h
This reverts commit e2dec80d6a1cbfba9144cf5f6e290e1d1af285d5 and fixes the broken Envoy Mobile tests
Fixes commit e2dec80d6a1cbfba9144cf5f6e290e1d1af285d5
> Revert "Add createPath to Filesystem abstraction (#26740)"

- bazel/BUILD
- bazel/proxy_wasm_cpp_host.patch
- bazel/repositories.bzl
- changelogs/current.yaml
- source/common/version/BUILD
- source/common/version/version.cc
> [release/v1.23] fips: fix Wasm extensions to comply with FIPS

- bazel/proxy_wasm_cpp_host.patch
- bazel/repositories.bzl
- changelogs/current.yaml
- source/common/version/BUILD
- source/common/version/version.cc
> [release/v1.24] fips: fix Wasm extensions to comply with FIPS

- bazel/proxy_wasm_cpp_host.patch
- bazel/repositories.bzl
- changelogs/current.yaml
- source/common/version/BUILD
- source/common/version/version.cc
> [release/v1.25] fips: fix Wasm extensions to comply with FIPS

- bazel/proxy_wasm_cpp_host.patch
- bazel/repositories.bzl
- changelogs/current.yaml
- source/common/version/BUILD
- source/common/version/version.cc
> [release/v1.26] fips: fix Wasm extensions to comply with FIPS

- source/extensions/health_checkers/tcp/health_checker_impl.cc
Commit Message: TCP Health Check: log parity if TCP HC succeed with no payload.
Additional Description: Already exist if there is payload.
> TCP Health Check: log parity if TCP HC succeed with no payload.

- .gitignore
these files are created when you run the example, and can inadvertently get added
Risk Level:
Testing:
Docs Changes:
Release Notes:
> repo: Ignore websocket example certs dir

- source/extensions/http/header_formatters/preserve_case/preserve_case_formatter.cc
- test/extensions/http/header_formatters/preserve_case/preserve_case_formatter_test.cc
We prefer having explicit failure on out-of-bounds protos to having defaults in switch statements which are often missed when protos are extended.
Testing: n/a
> header formatter: handling out of bounds protos consistently

- bazel/proxy_wasm_cpp_host.patch
- bazel/repositories.bzl
- changelogs/current.yaml
- source/common/version/BUILD
- source/common/version/version.cc
> fips: fix Wasm extensions to comply with FIPS

- .github/dependabot.yml
dependabot takes a while to run, and then triggers a load of CI, and then more if any of the prs are landed
the idea of setting a time was to avoid all this CI during busy times, but atm its running into them
Risk Level:
Testing:
Docs Changes:
Release Notes:
> dependabot: Run earlier

- .github/workflows/mobile-android_build.yml
- .github/workflows/mobile-compile_time_options.yml
Also fixes mobile compile-time-options test broken in #26451 (and increases timeout for job that needs it)
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile/ci: Add timeout and err handling on hanging jobs

- mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.cc
- mobile/test/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator_test.cc
Commit Message: stop matching empty hostname to SAN list in the cert.
Testing: New unit tests
Platform Specific Features: mobile-only
> mobile: skip SNI matching for empty hostname

- envoy/access_log/access_log.h
- source/common/access_log/access_log_impl.cc
- source/common/access_log/access_log_impl.h
- source/common/local_reply/local_reply.cc
- source/extensions/access_loggers/common/access_log_base.cc
- source/extensions/access_loggers/filters/cel/cel.cc
- source/extensions/access_loggers/filters/cel/cel.h
- source/extensions/access_loggers/wasm/wasm_access_log_impl.h
- test/common/access_log/access_log_impl_test.cc
- test/extensions/access_loggers/common/access_log_base_test.cc
- test/extensions/access_loggers/grpc/http_grpc_access_log_impl_test.cc
- test/extensions/access_loggers/open_telemetry/access_log_impl_test.cc
- test/mocks/access_log/mocks.h
Commit Message: access_log: pass access log type parameter to evaluate function
Additional Description: This change is a no-op, a follow up PR will add a new feature to filter access logs based on ``AccessLogType`` (#26755)
Testing: None
> access_log: pass access log type parameter to evaluate function

- contrib/golang/filters/http/source/golang_filter.h
- envoy/access_log/access_log.h
- source/common/quic/quic_stats_gatherer.cc
- source/extensions/access_loggers/common/access_log_base.h
- source/extensions/access_loggers/common/file_access_log_impl.h
- source/extensions/access_loggers/grpc/http_grpc_access_log_impl.h
- source/extensions/access_loggers/grpc/tcp_grpc_access_log_impl.h
- source/extensions/access_loggers/wasm/wasm_access_log_impl.h
- source/extensions/common/wasm/context.h
- source/extensions/common/wasm/wasm.cc
- source/extensions/common/wasm/wasm.h
- source/extensions/filters/http/composite/filter.h
- source/extensions/filters/http/tap/tap_filter.h
- source/extensions/filters/network/thrift_proxy/conn_manager.cc
- source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc
- source/extensions/listener_managers/listener_manager/active_stream_listener_base.cc
- test/common/access_log/access_log_impl_test.cc
- test/extensions/access_loggers/common/access_log_base_test.cc
- test/extensions/access_loggers/file/config_test.cc
- test/extensions/access_loggers/grpc/http_grpc_access_log_impl_test.cc
- test/extensions/access_loggers/open_telemetry/access_log_impl_test.cc
- test/extensions/access_loggers/stream/stream_test_base.h
- test/extensions/access_loggers/wasm/config_test.cc
- test/extensions/filters/http/common/fuzz/http_filter_fuzzer.h
- test/extensions/filters/http/composite/filter_test.cc
- test/extensions/filters/http/tap/tap_filter_test.cc
- test/extensions/filters/http/wasm/wasm_filter_test.cc
Commit Message: access_log: use AccessLogType::NotSet instead of default value
Additional Description: Remove default value for the access_log_type parameter in any log function and instead call log() with AccessLogType::NotSet to explicitly indicate that the access log type is irrelevant or not handled
> access_log: use AccessLogType::NotSet instead of default value

- .azure-pipelines/bazel.yml
- .azure-pipelines/stage/publish.yml
- .azure-pipelines/stage/verify.yml
- ci/build_setup.sh
- ci/do_ci.sh
Currently we publish to quite a few artifact targets
This means that pulling artifacts often requires pulling from several targets, and doing so sequentially
This consolidates some of the targets and should optimize CI a little, and allow more/easier use of the artifacts
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Consolidate artifact targets

- source/extensions/filters/network/thrift_proxy/conn_manager.cc
- source/extensions/filters/network/thrift_proxy/conn_manager.h
- test/extensions/filters/network/thrift_proxy/conn_manager_test.cc
Currently we don't have reply information access log for local replies. 
Testing: unit
Docs Changes:
Release Notes:
> thrift_proxy: add access log support for local reply

- .azure-pipelines/bazel.yml
- .bazelrc
- .github/workflows/mobile-compile_time_options.yml
- ci/build_setup.sh
- mobile/.bazelrc
This adds a `ci` bazel config target and sets the `noshow...progress` settings there
Both mobile and envoy ci use this target and we can add any more common ci config there
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/mobile: Hide CI progress in .bazelrc

- .github/workflows/mobile-android_tests.yml
- mobile/test/kotlin/integration/StatFlushIntegrationTest.kt
There are several Java tests that fail without the `--define=signal_trace=disabled` flag. The flag is already on for Java tests; this commit turns them on for Kotlin tests on CI as well.
Also, this solves one of the problems with flaky tests in StatsFlushIntegrationTest.kt, as described in
https://github.com/envoyproxy/envoy/issues/24657, so we re-enable the test that now passes. The other StatsFlushIntegrationTest test still fails and will be debugged separately.
Testing: `bazelisk test --config=test-android --define=signal_trace=disabled --test_output=streamed --cache_test_results=no  test/kotlin/integration:stat_flush_integration_test --runs_per_test=100`
> ci: run Kotlin tests with signal_trace disabled

- source/extensions/access_loggers/open_telemetry/access_log_impl.h
Commit Message: access_log: remove leftover default access log type parameter
Testing: None
Release Notes: None 
> access_log: remove leftover default access log type parameter

- test/integration/shadow_policy_integration_test.cc
Commit Message: test: fix shadow test flakes
Additional Description: The second time we call `sendRequestAndValidateResponse()`, we have to wait for the counter to be g.e. 2.
> test: fix shadow test flake

- .bazelrc
- test/common/common/logger_test.cc
- test/test_runner.cc
> Redirect trace log output to /dev/null for coverage tests

- .bazelrc
Its not clear what this flag does - the docs say it outputs warnings about "tests that are too big"
currently we get such warnings without any useful info, just advice to add this flag
in my testing adding this flag does nothing other than make the warnings go away - seems worth adding 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Add `--test_verbose_timeout_warnings`

- bazel/foreign_cc/luajit.patch
Failing to build `luajit` on Macos with the current target. Thus bumping it up.
```
lj_err.c:716:8: error: thread-local storage is not supported for the current target
static __thread struct {
^
1 error generated.
make[1]: *** [lj_err.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Bump MACOSX_DEPLOYMENT_TARGET to 10.8

- tools/proto_format/proto_sync.py
Fix #27147 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> proto_format: Use char (not text) len when encoding diff

- ci/do_ci.sh
fastbuild produces less debug info in the binaries, considerably speeding up compilation and linking. Other than that it is equivalent to the dbg build.
> Use fastbuild mode for compile_time_options build

- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
Otherwise, might lead to segfault.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> golang filter: fix segfault: should check filter expired before touch mutex_ lock.
