envoyproxy/envoy

- source/common/upstream/cluster_factory_impl.cc
- source/common/upstream/cluster_factory_impl.h
- source/common/upstream/cluster_manager_impl.cc
- source/common/upstream/cluster_manager_impl.h
- test/common/upstream/cluster_factory_impl_test.cc
- test/common/upstream/test_cluster_manager.h
- test/config_test/config_test.cc
- test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc
- test/extensions/clusters/redis/redis_cluster_test.cc
cleaning up a TODO and a bunch of redundant variables.
Testing: updates tests
Docs Changes: n/a (theoretical no-op)
> cluster: cleaning up factory access

- docs/root/intro/arch_overview/http/http3.rst
- docs/root/intro/arch_overview/upstream/connection_pooling.rst
Fixing some out of date content with our HTTP/3 developer docs
> docs: HTTP/3 updates

- test/integration/protocol_integration_test.cc
This test wants to send a stream reset when the remote has the response EOD buffered. However, nothing prevented the request being fully completed before the reset was sent. If that happened, a UAF would happen as observed by ASAN:
```
==12094==ERROR: AddressSanitizer: heap-use-after-free on address 0x607000296ab0 at pc 0x000004b55448 bp 0x7ffe4d1e97a0 sp 0x7ffe4d1e9798
READ of size 8 at 0x607000296ab0 thread T0
#0 0x4b55447 in Envoy::IntegrationCodecClient::sendReset(Envoy::Http::RequestEncoder&) /proc/self/cwd/test/integration/http_integration.cc:159:3
#1 0x494bfda in Envoy::ProtocolIntegrationTest_ResetLargeResponseUponReceivingHeaders_Test::TestBody() /proc/self/cwd/test/integration/protocol_integration_test.cc:3317:18
#2 0xd58fe24 in void …
```
> test: fix a race in ResetLargeResponseUponReceivingHeaders

- source/extensions/transport_sockets/http_11_proxy/config.h
Testing: n/a
https://github.com/envoyproxy/envoy-mobile/issues/1622
> proxy: declaring the factory

- source/common/router/upstream_codec_filter.h
Testing: n/a
https://github.com/envoyproxy/envoy-mobile/issues/1622
> http: declare the upstream codec filter

- docs/root/api-v3/config/filter/generic/generic.rst
Commit Message: docs only: fix spelling error
Fix the spelling error in previous PR #23157.
Testing: n/a.
> docs only: fix spelling error

- test/extensions/filters/http/cache/http_cache_implementation_test_common.cc
Commit Message: Call onDestroy for InsertContext in cache tests
Additional Description: Minor test cleanup; the onDestroy function for InsertContext was not called in tests, which is a potential leak for future cache implementations. Also, calling it correctly improves coverage.
Testing: Test-only change.
> Call onDestroy for InsertContext in cache tests

- contrib/sip_proxy/filters/network/source/conn_manager.cc
- contrib/sip_proxy/filters/network/source/decoder.cc
- contrib/sip_proxy/filters/network/source/decoder.h
- contrib/sip_proxy/filters/network/source/metadata.cc
- contrib/sip_proxy/filters/network/source/metadata.h
- contrib/sip_proxy/filters/network/source/router/router_impl.cc
- contrib/sip_proxy/filters/network/source/router/router_impl.h
- contrib/sip_proxy/filters/network/test/decoder_test.cc
- contrib/sip_proxy/filters/network/test/router_test.cc
Signed-off-by: Doris Ding <mingling.ding01@gmail.com>
Commit Message: code optimization for performance
Testing: UT/MT
> sipproxy code optimization for performance

- docs/root/configuration/observability/access_log/usage.rst
Risk Level: n/a (docs only)
Testing: n/a
follow up from https://github.com/envoyproxy/envoy/issues/19725
> docs: response code update

- source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc
grpc_json_transcoder: improve debug logs
- Add more debug logs to better understand what transcoder is doing with headers/body/trailer
- Change all `ENVOY_LOG` to `ENVOY_STREAM_LOG`
Testing: None
Signed-off-by: nareddyt <tejunareddy@gmail.com>
> grpc_json_transcoder: improve debug logs

- source/extensions/filters/http/grpc_stats/grpc_stats_filter.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> grpc_stats: fix a typo

- test/common/router/config_impl_test.cc
- test/extensions/path/match/uri_template/library_test.cc
- test/extensions/path/rewrite/uri_template/library_test.cc
Signed-off-by: silverstar195 <seanmaloney@google.com>
Change names to match rewriter and matcher extensions
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Change names to match rewriter and matcher extensions

- test/extensions/filters/http/jwt_authn/provider_verifier_test.cc
Signed-off-by: yurykats <yurykats@yahoo.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Rename identifiers named using a C++20 keyword

- .github/workflows/check-deps.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix dep checker permissions

- bazel/repositories.bzl
interation -> integration
Signed-off-by: Ikko Ashimine <eltociear@gmail.com>
> bazel: fix typo in repositories.bzl

- source/common/upstream/cluster_factory_impl.cc
- source/common/upstream/health_discovery_service.cc
- source/server/listener_impl.cc
- source/server/transport_socket_config_impl.h
- test/common/upstream/cluster_factory_impl_test.cc
- test/common/upstream/eds_speed_test.cc
- test/common/upstream/eds_test.cc
- test/common/upstream/hds_test.cc
- test/common/upstream/leds_test.cc
- test/common/upstream/logical_dns_cluster_test.cc
- test/common/upstream/original_dst_cluster_test.cc
- test/common/upstream/upstream_impl_test.cc
- test/extensions/clusters/aggregate/cluster_test.cc
- test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc
- test/extensions/clusters/redis/redis_cluster_test.cc
- test/server/listener_manager_impl_test.h
As follow-on clean up for upstream filters, cleaning up more factory code.
> refactor: factory cleanup

- envoy/stream_info/stream_info.h
Risk Level:
Testing:
Docs Changes:
Release Notes:
> update out of date todo

- api/envoy/config/cluster/v3/cluster.proto
- api/envoy/config/core/v3/address.proto
Commit Message: upstream: remove unused message UpstreamBindConfig
Testing: n/a
Docs Changes: API doc
> upstream: remove unused message UpstreamBindConfig

- bazel/protobuf.patch
- bazel/repository_locations.bzl
Fix #23326 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> deps: Bump `com_google_protobuf` -> 21.7

- contrib/network/connection_balance/dlb/source/connection_balancer_impl.cc
- contrib/network/connection_balance/dlb/test/BUILD
- contrib/network/connection_balance/dlb/test/config_test.cc
Add tests for dlb config.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> dlb: add tests

- source/common/common/logger.h
- source/extensions/filters/http/oauth2/oauth_client.h
Commit Message: change oauth2 filter log name
Testing: N/A
> change oauth2 filter log name

- .gitignore
- .yamllint
- changelogs/current.yaml
and add a basic yamllint file
partial fix for #23348 and #22222 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> changelog: Fix duplicate entries

- source/extensions/matching/input_matchers/ip/config.cc
Commit Message: minor fix comment
Found by accident.
Testing: n/a.
> minor fix comment

- RELEASES.md
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docs: updating release info

- source/common/router/upstream_request.cc
Commit Message: Clean up: Avoid temp string use absl str lib.
Release Notes:na
> Clean up: Avoid temp string use absl str lib.

- changelogs/current.yaml
- source/common/http/utility.cc
- source/common/runtime/runtime_features.cc
Testing: n/a
Fixes https://github.com/envoyproxy/envoy/issues/23588
> deprecating envoy.reloadable_features.allow_adding_content_type_in_local_replies

- examples/csrf/crosssite/docker-compose.yml
Trivial fix csfr port confilict.
> #23543 revert csfr/crossite default port to 8002

- source/common/tcp_proxy/tcp_proxy.h
Commit Message: minor: minor fix for typo error
minor fix for typo error. found by accident.
Testing:  n/a. 
> minor: minor fix for typo error

- source/common/upstream/resource_manager_impl.h
`ManagedResourceImpl` reuse parent api when possible, just like inc/decBy
Signed-off-by: Sekiro CC <sekirocc@gmail.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:
> refactor: code sytle consistency

- tools/base/requirements.in
- tools/base/requirements.txt
and update `envoy.code.check` to work with them
Risk Level:
Testing:
Docs Changes:
Release Notes:
> deps: Bump `flake8` and associated packages

- test/extensions/filters/listener/original_dst/BUILD
- test/extensions/filters/listener/original_dst/original_dst_integration_test.cc
- test/integration/BUILD
- test/integration/base_integration_test.cc
- test/integration/base_integration_test.h
- test/integration/integration_tcp_client.cc
- test/integration/integration_tcp_client.h
- test/integration/protocol_integration_test.cc
Part of https://github.com/envoyproxy/envoy/issues/22583
> test: adding original dst tests.

- source/docs/flow_control.md
Commit Message: fix typo in flow_control.md
Testing:
Release Notes:
> docs: fix typo in flow_control.md

- api/envoy/service/extension/v3/config_discovery.proto
Fixing ECDS documentation
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Fixing ECDS documentation

- bazel/README.md
Signed-off-by: 牧心 <chengqinglin@icloud.com>
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Chore: correct `write_current_source_version.py` link

- bazel/README.md
- tools/github/write_current_source_version.py
Commit Message: This adds error handling and update README
> tools, github: Add error handling and update README

- examples/grpc-bridge/docker-compose-protos.yaml
Signed-off-by: zackzhangkai <zhangkaiamm@gmail.com>
The URL in the comment is invalid already.
just fix comments
> fix comments

- test/common/tcp/conn_pool_test.cc
> test: clean up unused variable

- bazel/repository_locations.bzl
Fix #22912
Risk Level:
Testing:
Docs Changes:
Release Notes:
> deps: Bump `rules_fuzzing` -> 0.3.2

- envoy/server/BUILD
- envoy/server/hot_restart.h
- source/server/BUILD
- source/server/hot_restarting_base.h
- test/mocks/server/hot_restart.h
- test/mocks/server/instance.h
> hot_restart: removing the proto from the no-hot-restart build

- .azure-pipelines/pipelines.yml
- ci/publish_github_assets.sh
This:
- switches to using a securefile rather than env var for the gpg key
- adds a key password
- improves error handling in asset publishing code
Risk Level:
Testing:
Docs Changes:
Release Notes:
> repo: Improve key signing of binaries

- bazel/external/googleurl.patch
Fixing one remaining missing arm include
> googleurl: further fixes

- examples/route-mirror/README.md
Signed-off-by: zackzhangkai <zhangkaiamm@gmail.com>
fix doc link
> fix doc link

- test/extensions/filters/http/common/fuzz/filter_corpus/clusterfuzz-testcase-minimized-filter_fuzz_test-5022310482706432
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Committing the OSS fuzz test case file associated with #23782

- .github/workflows/check-deps.yml
- .github/workflows/codeql-daily.yml
- .github/workflows/codeql-push.yml
- .github/workflows/depsreview.yml
- .github/workflows/pr_notifier.yml
- .github/workflows/stale.yml
Prevent bitrot on release branches
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Pin images in github actions

- .azure-pipelines/pipelines.yml
- ci/publish_github_assets.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] repo: Improve key signing of binaries (#23640)

- .azure-pipelines/pipelines.yml
- ci/publish_github_assets.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] repo: Improve key signing of binaries (#23640)

- .bazelrc
For https://github.com/envoyproxy/envoy-mobile/issues/180
> build: dead strip and gc the sizeopt build

- envoy/http/filter.h
Commit Message: Cleanup: Update comment.
Additional Description: In original PR: **https://github.com/envoyproxy/envoy/pull/15172** we send onLocalReply to all filters, there's no `onLocalError`
Testing: 
> Cleanup: Update comment.

- source/common/event/dispatcher_impl.cc
- source/common/network/connection_impl.cc
- source/common/network/connection_impl.h
- test/common/network/connection_impl_test.cc
Commit Message: Server connection is always "connected".
Testing:
Docs Changes:
Release Notes:
> cleanup: remove superfluous argument

- test/common/upstream/upstream_impl_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> build: fix merge issue

- .azure-pipelines/bazel.yml
- api/bazel/repository_locations.bzl
Fix #24004 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.21] ci: disable non-RBE cache for release branches (#22745)

- api/bazel/repository_locations.bzl
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] api/deps: Fix bufbuild links

- test/integration/fake_upstream.cc
Fixes #22324
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] test: fixing a flake (#22328)

- test/integration/listener_lds_integration_test.cc
Testing: yes: 1k runs now pass
> test: fixing lds flake

- test/integration/listener_lds_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] test: fixing lds flake (#24071)

- test/integration/listener_lds_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] test: fixing lds flake (#24071)

- test/integration/listener_lds_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.21] test: fixing lds flake (#24071)

- source/docs/http3_upstream.md
requets -> requests
Signed-off-by: Ikko Ashimine <eltociear@gmail.com>
Commit Message:Fix typo in http3_upstream.md
> Fix typo in http3_upstream.md

- test/integration/listener_lds_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.22] test: fixing lds flake (#24071)

- mobile/bazel-envoy-mobile
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile: Fix dangling link

- .github/workflows/perf.yml
Note: this will run for all Envoy changes, not simply Envoy Mobile changes.  
Risk Level: Medium - we can add "only on mobile runs" if it overloads engflow
Testing: see below
> mobile: turning up perf workflow

- test/run_envoy_bazel_coverage.sh
Fix #24119 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> coverage: Fail if report is empty or missing

- .github/workflows/android_build.yml
- .github/workflows/format.yml
- .github/workflows/ios_build.yml
Fix #24147 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile: Increase CI timeouts for build and format job/s

- api/envoy/extensions/transport_sockets/tls/v3/tls_spiffe_validator_config.proto
> Correct example SPIFFE URIs in the doc

- .github/workflows/android_build.yml
- .github/workflows/android_tests.yml
- .github/workflows/asan.yml
- .github/workflows/core.yml
- .github/workflows/coverage.yml
- .github/workflows/format.yml
- .github/workflows/ios_build.yml
- .github/workflows/ios_tests.yml
- .github/workflows/python_tests.yml
- .github/workflows/tsan.yml
If the workflow has changed but is not tested, it might break next time it actually is tested
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Trigger mobile workflows on workflow change

- .github/workflows/android_tests.yml
- .github/workflows/asan.yml
- .github/workflows/cc_tests.yml
- .github/workflows/coverage.yml
- .github/workflows/format.yml
- .github/workflows/perf.yml
- .github/workflows/python_tests.yml
- .github/workflows/tsan.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Pin mobile gh action Ubuntu images

- docs/root/version_history/current.rst
Risk Level:
Testing:
Docs Changes:
Release Notes:
> repo: Release `1.21.6` (take 2)

- .github/workflows/format.yml
- mobile/.swiftlint.yml
Commit Message: ci: run SwiftLint on `mobile/**` changes
Risk Level: Low, CI job, only runs when on `mobile/**` changes
Testing: Local
Platform Specific Features: only runs when on `mobile/**` changes
part of https://github.com/envoyproxy/envoy/pull/24224
> ci: run SwiftLint on `mobile/**` changes

- bazel/BUILD
- bazel/README.md
- bazel/envoy_build_system.bzl
- bazel/envoy_internal.bzl
- bazel/envoy_select.bzl
- ci/do_ci.sh
- source/common/common/logger.h
This nets us another .8M savings for the EM build
Testing: CI
Most of https://github.com/envoyproxy/envoy-mobile/issues/174
> build: allow disabling logging

- source/common/router/config_impl.cc
- source/common/router/config_impl.h
For optional config sub-messages, use unique_ptr members and a default singleton implementation.
This is a step towards more memory efficient config data structures. 
This PR covers RetryPolicy, HedgePolicy and  InternalRedirectPolicy.
Issue #24154.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Reduce memory utilization of Route/VirtualHost.

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix change detection script

- .github/workflows/commands.yml
Allow retest for E-M workflows
Part of https://github.com/envoyproxy/envoy/issues/23758 workaround until we have https://github.com/envoyproxy/envoy/issues/24156
> workflows: copying envoy mobile command workflow

- .github/workflows/android_build.yml
- .github/workflows/android_tests.yml
- .github/workflows/asan.yml
- .github/workflows/cc_tests.yml
- .github/workflows/core.yml
- .github/workflows/coverage.yml
- .github/workflows/format.yml
- .github/workflows/ios_build.yml
- .github/workflows/ios_tests.yml
- .github/workflows/perf.yml
- .github/workflows/python_tests.yml
- .github/workflows/release_validation.yml
- .github/workflows/tsan.yml
this also allows the the checkout action to be updated
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Remove unused submodules config

- source/extensions/formatter/req_without_query/req_without_query.cc
> formatter: fix parameter type

- .circleci/config.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix yamllint

- mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.cc
- mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.h
- mobile/test/common/extensions/cert_validator/platform_bridge/BUILD
- mobile/test/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator_test.cc
Imports the following commits from the Envoy Mobile repo:
- https://github.com/envoyproxy/envoy-mobile/pull/2704
- https://github.com/envoyproxy/envoy-mobile/pull/2713
> mobile: import envoy-mobile commits (2022-12-01)

- .bazelci/presubmit.yml
Fixes https://github.com/envoyproxy/envoy/issues/23891
> ci: update llvm on bazel CI

- .circleci/config.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] ci: Add noop circleci config

- .circleci/config.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] ci: Add noop circleci config

- .gitignore
Risk Level:
Testing:
Docs Changes:
Release Notes:
> repo: Dont gitignore .circleci dir

- .github/actions/pr_notifier/pr_notifier.py
Risk Level:
Testing:
Docs Changes:
Release Notes:
> tools: adding mobile maintainers to pr notifier

- OWNERS.md
Risk Level:
Testing:
Docs Changes:
Release Notes:
> governance: email fixup

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Skip docker/examples verification for docs or mobile only changes

- test/common/buffer/buffer_fuzz.cc
Testing:
Docs Changes:
Release Notes:
> build: fix compile error for mac

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Skip distribution build/checks for docs or mobile only changes

- source/common/http/http2/codec_impl.cc
- source/common/network/io_socket_handle_impl.cc
> Fix broken format strings

- .azure-pipelines/pipelines.yml
preceeding -> preceding
Signed-off-by: Ikko Ashimine <eltociear@gmail.com>
Commit Message:ci: fix typo in pipelines.yml
> ci: fix typo in pipelines.yml

- docs/root/configuration/other_protocols/thrift_filters/payload_to_metadata_filter.rst
- docs/root/faq/debugging/how_to_dump_heap_profile_of_envoy.rst
- docs/root/faq/debugging/xfp_vs_scheme.rst
- docs/root/start/sandboxes/local_ratelimit.rst
- docs/root/start/sandboxes/lua.rst
Testing: N/A
Docs Changes:
Release Notes:
> docs: fix some typos

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Add `examplesOnly` condition

- .github/workflows/format.yml
- mobile/bazel/envoy_mobile_repositories.bzl
- mobile/tools/check_format.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile: update SwiftLint to 0.50.3

- source/common/quic/BUILD
- source/exe/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
> build: fixing a linking bug for quic extensions

- test/per_file_coverage.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> coverage: Fix coverage for CI

- CONTRIBUTING.md
Risk Level:
Testing:
Release Notes:
> docs: add "Repo Etiquette" section to `CONTRIBUTING.md`

- repokitteh.star
> process: adding cc on runtime guard change

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/non--crash-security--bug.md
Signed-off-by: pcrao <pcrao@google.com>
Testing: N/A
Docs Changes:
Release Notes:
> Remove ambiguity about asserts for crash bugs.

- source/common/config/filesystem_subscription_impl.cc
Commit Message: add filename to Filesystem config update failure
Testing: N/A
> add filename to Filesystem config update failure

- source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc
Additional Description: Introduce better observability into whether DNS cache is used.
Testing:
Docs Changes:
Release Notes:
> mobile: add event for when DNS cache is loaded

- test/fuzz/utility.h
- test/integration/base_integration_test.h
> Remove dead test code

- test/extensions/filters/network/http_connection_manager/config_test.cc
> Bump coverage in the HCM config test

- test/common/http/status_test.cc
> Small compliance fix for C++20

- docs/root/intro/arch_overview/upstream/load_balancing/slow_start.rst
Commit Message: clarify slow start mode docs
Testing: N/A
> clarify slow start mode docs

- source/common/common/logger.h
- source/common/common/perf_annotation.cc
- source/extensions/network/dns_resolver/cares/dns_impl.cc
- test/extensions/common/tap/admin_test.cc
- test/extensions/filters/common/local_ratelimit/local_ratelimit_test.cc
- test/extensions/filters/http/local_ratelimit/filter_test.cc
- test/extensions/filters/http/local_ratelimit/local_ratelimit_integration_test.cc
> C++20: More compliance fixes in fmtlib use.

- ci/Dockerfile-envoy
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.22] docker: Use distroless-nossl

- ci/Dockerfile-envoy
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] docker: Use distroless-nossl

- api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
Risk Level: Very low
Testing: docs only change
Docs Changes:
Release Notes:
Fixes #24748
> ext_authz: fix docs for `status_on_error`

- docs/root/intro/arch_overview/upstream/service_discovery.rst
Commit Message: minor fix of service_discovery page
Making EDS an heading, and moving references to consistent positions.
Testing: N/A.
Docs Changes: Minor fixes of docs.
> docs: minor fix of service_discovery page

- source/common/tcp_proxy/tcp_proxy.cc
upstream exists.
Commit Message: Cleanup: fix nullptr check.
Testing: 
> Cleanup: Negate nullptr check in debug log to have it correspond to whether

- changelogs/current.yaml
- source/server/BUILD
- source/server/config_validation/server.cc
- source/server/regex_engine.cc
- source/server/regex_engine.h
- source/server/server.cc
Testing: N/A
Fixes #24022
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] config validation: inject regex engine before validation (#24037)

- test/common/protobuf/BUILD
- test/common/protobuf/utility_test.cc
- test/common/protobuf/utility_test_message_field_wip.proto
> Eliminate extension dependencies from core proto test

- .azure-pipelines/cleanup.sh
- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Workaround disk space issues in release job

- source/common/singleton/threadsafe_singleton.h
Correct an RELEASE_ASSERT message in threadsafe_singleton.h
> Correct an error message in threadsafe_singleton.h

- source/common/network/socket_interface_impl.cc
Improved assert logging for https://github.com/envoyproxy/envoy/issues/24801
> sockets: adding debug logs

- mobile/test/kotlin/integration/EngineApiTest.kt
Commit Message: The change has a low chance of helping us with a flakiness of this test. https://github.com/envoyproxy/envoy/actions/runs/3894061911/jobs/6647516688
Risk Level: Low, tests change only.
Testing:
Docs Changes:
Release Notes:
> ci: simplify the clean up of kotlin test

- mobile/WORKSPACE
> bazel: run buildifier on EM WORKSPACE

- mobile/library/common/BUILD
- mobile/test/common/BUILD
Fixing a bad merge where an Envoy test is missing a required extension
> build: test fix

- .github/workflows/android_build.yml
- mobile/ci/mac_start_emulator.sh
Risk Level: Low, CI only
Testing: CI
Docs Changes:
Release Notes:
> mobile: retry starting emulator up to 3 times

- test/common/stats/BUILD
- test/common/stats/real_thread_test_base.cc
- test/common/stats/real_thread_test_base.h
- test/common/stats/thread_local_store_test.cc
Commit Message:refactor test  libs to be shared between thread_local_store_test.cc and future lazyinit_stats_benchmark_test
Risk Level:
Testing:
Docs Changes:
Release Notes:
> stats: refactor test  libs to be shared between thread_local_store_test.cc and future lazyinit_stats_benchmark_test

- envoy/http/header_validator.h
- envoy/stats/store.h
- test/extensions/load_balancing_policies/least_request/config_test.cc
- test/extensions/load_balancing_policies/random/config_test.cc
- test/extensions/load_balancing_policies/round_robin/config_test.cc
- test/extensions/transport_sockets/tls/ssl_socket_test.cc
Fix common typos found in recent import
> Fix common typos found in recent import

- RELEASES.md
Risk Level:
Testing:
Docs Changes:
Release Notes:
> repo: Update release notes

- mobile/bazel/envoy_mobile_repositories.bzl
https://github.com/buildbuddy-io/rules_xcodeproj/releases/tag/0.11.0
This has a number of performance improvements that should benefit us.
Risk Level: Low, local dev tool for Envoy Mobile only
Testing:
Docs Changes:
Release Notes:
> mobile: update rules_xcodeproj to 0.11.0

- mobile/library/cc/headers.cc
- mobile/library/cc/headers.h
- mobile/library/cc/headers_builder.cc
- mobile/library/cc/request_headers.cc
- mobile/library/cc/request_headers_builder.cc
- mobile/library/cc/request_trailers.cc
- mobile/library/cc/request_trailers_builder.cc
- mobile/library/cc/response_headers.cc
- mobile/library/cc/response_headers_builder.cc
- mobile/library/cc/response_trailers.cc
- mobile/library/cc/response_trailers_builder.cc
- mobile/library/cc/retry_policy.cc
- mobile/library/cc/stream.cc
- mobile/library/cc/stream_client.cc
- mobile/library/cc/stream_prototype.cc
- mobile/library/common/http/client.cc
- mobile/library/common/network/proxy_settings.h
Remove redundant "this->" in Envoy Mobile code
> Remove redundant "this->" in Envoy Mobile code

- examples/wasm-cc/Dockerfile-envoy-build
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix google sdk apt key

- examples/wasm-cc/Dockerfile-envoy-build
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] ci: Fix google sdk apt key (#24979)

- .azure-pipelines/pipelines.yml
Signed-off-by: wangfakang <fakangwang@gmail.com>
Commit Message: ci: Workaround disk space issues in verify examples job. thanks @phlax.
https://dev.azure.com/cncf/envoy/_build/results?buildId=125010&view=logs&j=f1a49366-51c0-540f-0294-f73c2bb311a9&t=7fd036c9-61ec-5b59-3645-e90950dc67a6&l=16290
```
wasm-cc errors: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /opt/llvm/lib/libclangBasic.a: no space left on device
```
Testing:
Release Notes:
> ci: Workaround disk space issues in verify examples job

- source/common/upstream/load_balancer_impl.cc
Commit Message: minor update for type error
Fix typo error that found occationally.
Testing: n/a.
> minor update for type error

- mobile/library/common/engine.cc
- mobile/library/common/network/android.cc
> fix: for android without AlternateGetifaddrs support

- docs/redirects.txt
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docs: Remove old redirects

- examples/wasm-cc/Dockerfile-envoy-build
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix kitware apt key

- mobile/ci/mac_ci_setup.sh
Logic is copied over from the version of the script at `ci/mac_ci_setup.sh`.
Commit Message: ci: retry Homebrew installations and updates
Additional Description: Logic is copied over from the version of the script at `ci/mac_ci_setup.sh`.
Risk Level: Low, CI only
Testing: CI
> ci: retry Homebrew installations and updates

- repokitteh.star
> repokitteh: removing the E-M autoassign

- bazel/external/http_parser/http_parser.c
> build: fix -Wstring-conversion warning

- docs/root/faq/debugging/how_to_dump_heap_profile_of_envoy.rst
Signed-off-by: wangfakang <fakangwang@gmail.com>
Commit Message: fix invalid path for mem dump.
Additional Description: fix invalid path for mem dump.
Testing:
Docs Changes:
Release Notes:
> fix invalid path for mem dump

- .azure-pipelines/pipelines.yml
…29)"
This reverts commit cc6a6027b9e5c1aabfce1ca1743807c8b10651b5.
Signed-off-by: wangfakang <fakangwang@gmail.com>
Commit Message: Revert "ci: Workaround disk space issues in verify examples job”
Additional Description: Revert "ci: Workaround disk space issues in verify examples job”
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/pull/25039
> Revert "ci: Workaround disk space issues in verify examples job”

- api/bazel/api_build_system.bzl
Risk Level:
Testing:
Docs Changes:
Release Notes:
> api/bazel: Remove legacy comment

- ci/do_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Temporary workaround for nist DNS failure

- configs/BUILD
- configs/configgen.sh
- contrib/exe/BUILD
- docs/BUILD
- examples/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Cleanup contrib configs server tests

- test/common/router/config_impl_test.cc
Add new test to validate multi. part pattern match
Risk Level:
Low. Testing only.
Testing:
Pattern match test.
Docs Changes:
Release Notes:
> Add new test to validate multi. part pattern match

- CODEOWNERS
Risk Level:
Testing:
Docs Changes:
Release Notes:
> repo: Add Golang filter CODEOWNERS

- .bazelignore
Risk Level:
Testing:
Docs Changes:
Release Notes:
> bazel: Add `mobile` to ignore

- api/contrib/envoy/extensions/filters/http/golang/v3alpha/golang.proto
- tools/code_format/check_format.py
- tools/code_format/check_format_test_helper.py
- tools/code_format/config.yaml
- tools/protoprint/protoprint.py
- tools/testdata/check_format/pgv_string.proto
Fix #25208 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> proto_format: Shift `min_bytes` check

- source/common/http/conn_manager_impl.cc
Commit Message: Update comment re: QUIC network filters
Additional Description: This comment is out of date since #22722.
> Update comment re: QUIC network filters

- OWNERS.md
Signed-off-by: William A Rowe Jr <wrowe@rowe-clan.net>
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Move to helpers, off of security and maintainers

- docs/root/configuration/http/http_filters/golang_filter.rst
Partial fix for https://github.com/envoyproxy/envoy/issues/25178
> docs: Golang filter requires disabling cgocheck.

- ci/README.md
- ci/run_envoy_docker.sh
Commit Message: dev: add ENVOY_DOCKER_SKIP_PULL to skip docker pull
Additional Description: it  saves lots of time when developing with run_envoy_docker.sh wrapper
Risk Level:
Testing:
Docs Changes:
Release Notes:
> dev: add ENVOY_DOCKER_SKIP_PULL to skip docker pull

- mobile/test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
Making most of the data legal yaml
Explicitly testing the order of native filters and platform filters prior to making builder changes.
Testing: yes
part of https://github.com/envoyproxy/envoy/issues/24976
> mobile: improving kotlin builder tests

- mobile/library/cc/engine_builder.cc
- mobile/library/cc/engine_builder.h
- mobile/test/cc/unit/envoy_config_test.cc
Changing the order of native template insertion to preserve template characteristics
Adding and testing setSkipDnsLookupForProxiedRequests
https://github.com/envoyproxy/envoy/issues/24976
> mobile: c++ builder fix ups

- mobile/library/cc/engine_builder.cc
By adding newlines and "titles" to the sections so you can easily find both versions of the yaml, which can then be pasted into a diff tool.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile: improve mismatched bootstrap config yaml logging

- source/extensions/listener_managers/listener_manager/active_stream_listener_base.cc
Testing:
Docs Changes:
Release Notes:
> nit: fix active listener base comment

- changelogs/1.22.7.yaml
- changelogs/current.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] repo: Cleanup changelogs

- changelogs/1.22.7.yaml
- changelogs/1.23.4.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] repo: Cleanup changelogs

- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/test/BUILD
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/basic/BUILD
- contrib/golang/filters/http/test/test_data/basic/config.go
- contrib/golang/filters/http/test/test_data/basic/filter.go
- contrib/golang/filters/http/test/test_data/routeconfig/BUILD
- contrib/golang/filters/http/test/test_data/routeconfig/config.go
- contrib/golang/filters/http/test/test_data/routeconfig/filter.go
add more tests for golang filter extension.
already covered the existing APIs, it's a good start for the new coming APIs.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> test: add more tests for golang filter extension.

- examples/skywalking/docker-compose.yaml
- examples/skywalking/verify.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> examples: Make skywalking/elasticsearch less greedy

- bazel/boringssl_CVE-2023-0286.patch
- bazel/repositories.bzl
- changelogs/current.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> boringssl: Patch CVE-2023-0286

- docs/root/version_history/current.rst
(minor changelog fix)
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.22] repo: Release v1.22.7

- test/test_common/utility.cc
> Cleanup unused using-declaration

- mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java
- mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyEngine.java
- mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java
- mobile/library/kotlin/io/envoyproxy/envoymobile/mocks/MockEnvoyEngine.kt
> mobile: changing an API to clearly return status

- tools/base/requirements.in
- tools/base/requirements.txt
Risk Level:
Testing:
Docs Changes:
Release Notes:
> deps: Bump `flake8` -> 6.0.0

- envoy/stats/refcount_ptr.h
> C++20 compliance fix

- .gitattributes
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] changelogs: Merge normally (#25378)

- .gitattributes
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.25] changelogs: Merge normally (#25378)

- contrib/golang/filters/http/source/go/pkg/api/filter.go
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/go/pkg/http/filter.go
- contrib/golang/filters/http/source/go/pkg/http/shim.go
- contrib/golang/filters/http/source/go/pkg/http/type.go
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/basic/filter.go
fix https://github.com/envoyproxy/envoy/issues/25288
Risk Level:
Testing:
Docs Changes:
Release Notes:
> golang filter extension: add recover in defer to catch panic in go code

- source/common/http/conn_manager_impl.cc
Commit Message: add reset reason to stream log
Additional Description: add reset reason to stream log
Testing: N/A
> add reset reason to stream log

- changelogs/current.yaml
- source/common/router/router.cc
- test/integration/BUILD
- test/integration/circuit_breakers_integration_test.cc
Commit Message: Fix outlier detection false positives caused by max requests circuit breaker.
Release Notes: Done.
Fixes: #25487
> router: Fix outlier detection false positives

- .azure-pipelines/pipelines.yml
This PR
- merges the `docker` and `publish` stages in CI
- splits the `distribution` jobs between `publish` and `verify`
partial fix for issues raised in #25426 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Reorganize release pipelines

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.25] ci: Reorganize release pipelines (#25505)

- tools/base/envoy_python.bzl
This macros provides an easy way to generate templated content from a jinja template and json/yaml configs
Risk Level:
Testing:
Docs Changes:
Release Notes:
> tooling: Add macro for generating templated content

- contrib/sip_proxy/filters/network/source/conn_manager.cc
- contrib/sip_proxy/filters/network/source/metadata.h
- contrib/sip_proxy/filters/network/source/router/router_impl.cc
- contrib/sip_proxy/filters/network/source/tra/tra_impl.cc
- contrib/sip_proxy/filters/network/test/router_test.cc
Commit Message: enhance inst-ip and skey
Testing: Ut/Mt
Docs Changes:
Release Notes:
> [contrib-sipproxy] enhance inst-ip and skey

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] ci: Reorganize release pipelines (#25505)

- envoy/stats/refcount_ptr.h
> More C++20 compliance fixes

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] ci: Reorganize release pipelines (#25505)

- examples/golang/simple/filter.go
Risk Level:
Testing:
Docs Changes:
Release Notes:
> golang filter example: remove the unused method.

- ci/do_ci.sh
Fix #25623 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix flaky test reporting

- contrib/golang/filters/http/source/go/pkg/http/type.go
Commit Message: golang filter extension: the error msg can be constant
Additional Description: There is no need to define error msg as non-constant variable
Testing: N/A
> golang filter extension: the error msg can be constant

- test/extensions/filters/network/thrift_proxy/BUILD
Fix #25627 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> test: Disable flaky windows `thrift_proxy` test

- ci/do_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Run flake reporting even when there is failure

- ci/docker_ci.sh
Fix #25593 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docker: Unify image names

- .azure-pipelines/cleanup.sh
- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] ci: Workaround disk space issues in release job (#24856)

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Improve stage/job names

- api/envoy/config/core/v3/health_check.proto
- envoy/upstream/BUILD
- envoy/upstream/host_description.h
- source/common/conn_pool/conn_pool_base.cc
- source/common/router/BUILD
- source/common/router/router.cc
- source/common/upstream/health_checker_base_impl.cc
- source/common/upstream/health_checker_base_impl.h
- source/common/upstream/health_checker_impl.cc
- source/common/upstream/upstream_impl.h
- source/extensions/clusters/common/logical_host.h
- test/common/upstream/health_checker_impl_test.cc
- test/extensions/clusters/common/logical_host_test.cc
- test/integration/health_check_integration_test.cc
- test/mocks/upstream/host.h
Attempt to Fix #25607 
This reverts commit 1f4f60003ea4331e71d661a536e6c4dcdf23f8db.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Revert "add idle active hc for TCP/HTTP/GRPC (#24903)"

- source/common/upstream/maglev_lb.h
Risk Level:
Testing:
Docs Changes:
Release Notes:
> clang-tidy: Fix maglev errors

- .azure-pipelines/cleanup.sh
- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] ci: Workaround disk space issues in release job (#24856)

- mobile/BUILD
- mobile/bazel/envoy_mobile_repositories.bzl
https://github.com/buildbuddy-io/rules_xcodeproj/releases/tag/1.2.0
And set indent/tab width to 2 to follow this project's code style conventions.
Risk Level: Low, local dev tool only
Testing:
Docs Changes:
Release Notes:
> mobile: update rules_xcodeproj to 1.2.0

- source/extensions/clusters/redis/redis_cluster.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> redis_cluster: remove an unused variable.

- ci/docker_ci.sh
not from the tag
Partial fix for #23773
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docker: Publish images from release branches/commits

- docs/build.sh
- docs/publish.sh
Partial fix for #23773
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docs: Publish versioned docs on release branches/commits

- ci/Dockerfile-envoy
- ci/docker_ci.sh
- docs/root/version_history/v1.22.7.rst
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.22] Updates and cleanups

- envoy/api/io_error.h
- source/common/common/stl_helpers.h
- source/common/config/new_delta_subscription_state.h
- source/common/config/xds_mux/delta_subscription_state.h
- source/common/filesystem/directory.h
- source/common/http/async_client_impl.h
- source/common/json/json_internal.cc
- source/common/network/cidr_range.cc
- source/common/network/io_socket_error_impl.cc
- source/common/network/udp_packet_writer_handler_impl.h
- source/common/network/win32_socket_handle_impl.cc
- source/common/quic/envoy_quic_packet_writer.cc
- source/common/quic/envoy_quic_utils.cc
- source/common/quic/quic_io_handle_wrapper.h
- source/common/quic/udp_gso_batch_writer.cc
- source/common/rds/util.cc
- source/common/router/header_formatter.cc
- source/common/stats/allocator_impl.cc
- source/common/stats/null_text_readout.h
- source/server/admin/admin.h
- test/common/http/http2/metadata_encoder_test.cc
- test/common/quic/test_utils.h
- test/integration/dynamic_validation_integration_test.cc
- test/tools/schema_validator/validator.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Apply 'modernize-return-braced-init-list' clangtidy (~100 more fixes)

- ci/run_clang_tidy.sh
Fix #24485 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix clang-tidy diff

- ci/do_ci.sh
- examples/verify-common.sh
- examples/wasm-cc/build-entrypoint.sh
- examples/wasm-cc/docker-compose-wasm.yaml
- examples/wasm-cc/verify.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.25] example diskspace fixes

- docs/root/intro/arch_overview/upstream/load_balancing_policies.rst
I’m new to Envoy and impressed by the nicely written introduction. However, the page about [Load Balancing Policies](https://www.envoyproxy.io/docs/envoy/v1.25.1/intro/arch_overview/upstream/load_balancing_policies) seems a little confusing. Here’s an attempt to make it more legible; please double-check whether my changes actually make sense.
> docs: Clarify load balancing policies

- mobile/library/cc/engine_builder.h
Some comments in EngineBuilder still referenced the old YAML string method of configuring the Bootstrap. We got rid of the YAML string config in favor of the protocol buffer config in
https://github.com/envoyproxy/envoy/pull/25717, so this commit just cleans up the comments.
> mobile: update comments in EngineBuilder

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> assets: Publish immediately on release

- .azure-pipelines/pipelines.yml
Fix #25759 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Shift dev/release detection to env stage

- contrib/golang/filters/http/source/go/pkg/api/capi.go
- contrib/golang/filters/http/source/go/pkg/api/type.go
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/go/pkg/http/type.go
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/basic/filter.go
Also update Lua snippet to avoid deprecated warning
Commit Message: golang filter: add HeaderMap.Values
Docs Changes:
Release Notes:
> golang filter: add HeaderMap.Values

- envoy/network/socket.h
- source/common/common/bit_array.h
- test/common/buffer/owned_impl_test.cc
- test/common/common/packed_struct_test.cc
- test/common/network/connection_impl_test.cc
- test/common/quic/envoy_quic_alarm_test.cc
- test/common/stream_info/filter_state_impl_test.cc
- test/config/utility.h
- test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
- test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
- test/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter_integration_test.cc
- test/extensions/transport_sockets/starttls/starttls_integration_test.cc
- test/integration/autonomous_upstream.cc
- test/integration/eds_integration_test.cc
- test/integration/filter_manager_integration_test.cc
- test/integration/integration_tcp_client.cc
- test/integration/leds_integration_test.cc
- test/integration/load_stats_integration_test.cc
- test/integration/multiplexed_integration_test.cc
- test/integration/sds_dynamic_integration_test.cc
- test/integration/tcp_proxy_integration_test.cc
- test/integration/utility.h
- test/server/admin/config_tracker_impl_test.cc
- test/server/config_validation/server_test.cc
- test/test_common/printers.h
Commit Message: Clangtidy, various readability-identifier-naming fixes. 
Additional Description: ~60 fixes
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Clang tidy fix batch 3

- test/common/network/matching/inputs_integration_test.cc
- test/common/router/config_impl_test.cc
- test/common/router/scoped_rds_test.cc
- test/common/ssl/matching/inputs_integration_test.cc
- test/common/upstream/cluster_manager_impl_test.cc
- test/common/upstream/upstream_impl_test.cc
- test/extensions/clusters/eds/eds_test.cc
- test/extensions/filters/http/grpc_json_transcoder/grpc_json_transcoder_integration_test.cc
- test/extensions/filters/http/on_demand/odcds_integration_test.cc
- test/extensions/filters/http/on_demand/on_demand_integration_test.cc
- test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc
- test/extensions/filters/udp/dns_filter/dns_filter_test.cc
- test/extensions/listener_managers/listener_manager/lds_api_test.cc
- test/extensions/load_balancing_policies/least_request/integration_test.cc
- test/extensions/load_balancing_policies/maglev/integration_test.cc
- test/extensions/load_balancing_policies/random/integration_test.cc
- test/extensions/load_balancing_policies/ring_hash/integration_test.cc
- test/extensions/load_balancing_policies/round_robin/integration_test.cc
- test/integration/listener_lds_integration_test.cc
- test/integration/scoped_rds_integration_test.cc
- test/integration/sds_dynamic_integration_test.cc
- test/integration/vhds.h
- test/tools/schema_validator/test/schema_validator_test.cc
Additional Description: fix types of format parameters for fmtlib for C++20 compliance
> C++20: fix fmtlib format parameters

- mobile/docs/root/intro/version_history.rst
- mobile/library/cc/engine_builder.cc
- mobile/library/common/http/client.cc
- mobile/test/cc/unit/envoy_config_test.cc
Testing: test pass.
https://github.com/envoyproxy/envoy/issues/25813
> mobile: removing base_h3 cluster

- mobile/docs/root/intro/version_history.rst
- mobile/library/cc/engine_builder.cc
Testing: n/a
https://github.com/envoyproxy/envoy/issues/25813
> mobile: only creating stats cluster if needed

- test/per_file_coverage.sh
3 more directories good to go.  go team!
Fixes https://github.com/envoyproxy/envoy/issues/11993
> coverage: ratcheting limits

- ci/test/docker/linux/dev/main
- ci/test/docker/linux/dev/other
- ci/test/docker/linux/dev/release
- ci/test/docker/linux/dev/tag
- ci/test/docker/linux/nondev/main
- ci/test/docker/linux/nondev/other
- ci/test/docker/linux/nondev/release
- ci/test/docker/linux/nondev/tag
- ci/test/docker/windows/dev/main
- ci/test/docker/windows/dev/other
- ci/test/docker/windows/dev/release
- ci/test/docker/windows/dev/tag
- ci/test/docker/windows/nondev/main
- ci/test/docker/windows/nondev/other
- ci/test/docker/windows/nondev/release
- ci/test/docker/windows/nondev/tag
- ci/test_docker_ci.sh
this allows the test to work in other repos.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docker/ci: Use a mock repo for regression test

- mobile/library/cc/log_level.h
For pragma syntax, see https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-export
> Correct IWYU export pragma

- ci/test/docker/linux/dev/main
- ci/test/docker/linux/dev/other
- ci/test/docker/linux/dev/release
- ci/test/docker/linux/dev/tag
- ci/test/docker/linux/nondev/main
- ci/test/docker/linux/nondev/other
- ci/test/docker/linux/nondev/release
- ci/test/docker/linux/nondev/tag
- ci/test/docker/windows/dev/main
- ci/test/docker/windows/dev/other
- ci/test/docker/windows/dev/release
- ci/test/docker/windows/dev/tag
- ci/test/docker/windows/nondev/main
- ci/test/docker/windows/nondev/other
- ci/test/docker/windows/nondev/release
- ci/test/docker/windows/nondev/tag
- ci/test_docker_ci.sh
this allows the test to work in other repos.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] docker/ci: Use a mock repo for regression test

- ci/test/docker/linux/dev/main
- ci/test/docker/linux/dev/other
- ci/test/docker/linux/dev/release
- ci/test/docker/linux/dev/tag
- ci/test/docker/linux/nondev/main
- ci/test/docker/linux/nondev/other
- ci/test/docker/linux/nondev/release
- ci/test/docker/linux/nondev/tag
- ci/test/docker/windows/dev/main
- ci/test/docker/windows/dev/other
- ci/test/docker/windows/dev/release
- ci/test/docker/windows/dev/tag
- ci/test/docker/windows/nondev/main
- ci/test/docker/windows/nondev/other
- ci/test/docker/windows/nondev/release
- ci/test/docker/windows/nondev/tag
- ci/test_docker_ci.sh
this allows the test to work in other repos.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] docker/ci: Use a mock repo for regression test

- .azure-pipelines/bazel.yml
Fix #25735 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Use local (named) cache for non-RBE jobs

- mobile/library/common/jni/jni_interface.cc
- mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
- mobile/library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java
- mobile/test/common/jni/BUILD
- mobile/test/common/jni/test_jni_interface.cc
- mobile/test/java/io/envoyproxy/envoymobile/engine/BUILD
- mobile/test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
- mobile/test/java/io/envoyproxy/envoymobile/engine/testing/BUILD
- mobile/test/java/io/envoyproxy/envoymobile/engine/testing/QuicTestServerTest.java
- mobile/test/java/io/envoyproxy/envoymobile/engine/testing/TestJni.java
- mobile/test/kotlin/integration/SendDataTest.kt
Following up on a TODO to move createYaml to be test-only code.
Testing: yes
> mobile: moving createYaml to be test-only code

- ci/repokitteh/modules/versionchange.star
- repokitteh.star
Risk Level:
Testing:
Docs Changes:
Release Notes:
> repokitteh: Label version change PRs

- OWNERS.md
Risk Level: low (he's already doing reviews)
Testing: trial by fire
> process: adding Raven to maintainers

- source/common/http/utility.cc
> Small optimization fix: Use string_view instead of char*

- .azure-pipelines/bazel.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.25] ci: Use local (named) cache for non-RBE jobs (#25829)

- .azure-pipelines/bazel.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] ci: Use local (named) cache for non-RBE jobs (#25829)

- .azure-pipelines/bazel.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] ci: Use local (named) cache for non-RBE jobs (#25829)

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fail PRs if branch VERSION.txt is not open/dev

- ci/setup_cache.sh
Possibly fix #25913 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Set non-RBE options correctly

- contrib/golang/filters/http/source/config.cc
Commit Message: use REGISTER_FACTORY for Go extension.
Additional Description: use REGISTER_FACTORY for Go extension.
Testing:
Docs Changes:
Release Notes:
> use `REGISTER_FACTORY` for Go extension

- contrib/golang/filters/http/source/cgo.cc
- contrib/golang/filters/http/source/go/pkg/api/api.h
- contrib/golang/filters/http/source/go/pkg/api/capi.go
- contrib/golang/filters/http/source/go/pkg/api/filter.go
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/go/pkg/http/filter.go
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
- contrib/golang/filters/http/source/processor_state.h
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/basic/filter.go
Commit Message: fix #25806
Risk Level:
Testing:
Docs Changes:
Release Notes:
> golang filter extension: add more methods in the StreamInfo interface.

- .github/actions/pr_notifier/pr_notifier.py
- .github/workflows/pr_notifier.yml
Fix #25742 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Add credentials for maintainer PR notifier

- ci/do_ci.sh
- docs/root/start/sandboxes/redis.rst
- docs/root/start/sandboxes/setup.rst
- examples/redis/verify.sh
this removes any requirement for redis from the host env, and tidies docs.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> examples: Improve redis (client/env)

- .github/workflows/check-deps.yml
Hopefully fix #25929 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix (gh) dependency checker creds

- source/common/http/conn_manager_impl.cc
- test/extensions/filters/udp/dns_filter/dns_filter_test.cc
> More c++20 fixes

- .azure-pipelines/pipelines.yml
- ci/run_envoy_docker.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Remove docker (by default) and capabilities from build container

- contrib/golang/filters/http/source/common/dso/dso.cc
- contrib/golang/filters/http/source/common/dso/dso.h
- contrib/golang/filters/http/source/config.cc
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
- contrib/golang/filters/http/test/BUILD
- contrib/golang/filters/http/test/common/dso/BUILD
- contrib/golang/filters/http/test/common/dso/dso_test.cc
- contrib/golang/filters/http/test/common/dso/mocks.cc
- contrib/golang/filters/http/test/common/dso/mocks.h
- contrib/golang/filters/http/test/golang_filter_corpus/leak
- contrib/golang/filters/http/test/golang_filter_corpus/request_data
- contrib/golang/filters/http/test/golang_filter_fuzz.proto
- contrib/golang/filters/http/test/golang_filter_fuzz_test.cc
- contrib/golang/filters/http/test/golang_filter_test.cc
Partial fix #25807
Risk Level:
Testing:
Docs Changes:
Release Notes:
> golang filter extension: simple fuzz for downstream input.

- test/integration/ads_integration_test.cc
In particular, the xDS gRPC stream reset test is enhanced by adding a Listener response and ensuring that after the reset, the subsequent DiscoveryRequests (both SotW and Delta) include the last known version info when sending the request, including wildcard requests.
> xds: enhances coverage in AdsIntegrationTest

- api/envoy/extensions/filters/http/cors/v3/cors.proto
- docs/root/configuration/http/http_filters/cors_filter.rst
- examples/cors/backend/front-envoy.yaml
- examples/csrf/samesite/front-envoy.yaml
Commit Message: docs: update cors related docs and examples
There are some issues/quesions about the cors filter usage. And this PR do a minor update to the cors filter's docs and example to clarify the function and latest recommend usage of cors filter.
Testing: n/a.
> docs: update cors related docs and examples

- test/extensions/filters/http/csrf/BUILD
- test/extensions/filters/http/kill_request/BUILD
- test/extensions/filters/http/rbac/BUILD
- test/extensions/listener_managers/listener_manager/BUILD
- test/integration/BUILD
Maybe fix #25760 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Increase sharding to prevent timeout flakes

- .azure-pipelines/pipelines.yml
this workaround is sub-optimal but should fix CI until a better solution can be tested.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> examples: Workaround disk space issue

- mobile/library/objective-c/EnvoyHTTPCallbacks.h
- mobile/library/objective-c/EnvoyHTTPFilter.h
- mobile/library/swift/mocks/MockStream.swift
Since they're not guaranteed to be set, and we do already check if they're nil.
Testing: Existing.
Docs Changes: None.
> mobile: mark some block properties as nullable

- .github/workflows/android_build.yml
for https://github.com/envoyproxy/envoy/issues/25980
> mobile: bumping CI timeouts

- contrib/golang/filters/http/source/go/pkg/api/type.go
- contrib/golang/filters/http/source/go/pkg/http/type.go
- contrib/golang/filters/http/test/test_data/basic/filter.go
Commit Message: golang filter extension: implement the Range method.
Testing:
Docs Changes:
Release Notes:
> golang filter extension: implement the Range method.

- ci/build_setup.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Use cached test results for release runs

- .bazelrc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> bazel/ci: Add download retries

- mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
- mobile/library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
- mobile/test/kotlin/io/envoyproxy/envoymobile/EngineBuilderTest.kt
> mobile: add `setRuntimeGuard` to Kotlin engine builder

- mobile/library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
Testing:
Docs Changes:
Release Notes:
> mobile: fix indentation in `EngineBuilder.kt`

- contrib/golang/filters/http/test/golang_filter_fuzz.proto
Risk Level:
Testing:
Docs Changes:
Release Notes:
> protos: Remove unused golang test imports

- mobile/envoy_build_config/extension_registry.cc
Risk Level: low: should be comment-only
Testing: n/a
> mobile: documenting registered extensions

- test/extensions/filters/http/buffer/BUILD
- test/extensions/filters/http/tap/BUILD
- test/integration/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Increase sharding (further) to lessen test flakes

- test/integration/xds_integration_test.cc
For https://github.com/envoyproxy/envoy/issues/22489
> test: adding a log to debug an infrequent flake

- test/integration/protocol_integration_test.cc
Fixes https://github.com/envoyproxy/envoy/issues/26080
> test: fixing tsan flake

- test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc
Adding a DNS cache impl test for demonstrating dns_cache_config name configuration.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Adding a DNS cache impl test for demonstrating dns_cache_config name configuration

- contrib/vcl/source/vpp_vcl_build.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Quieten `VCL` build

- test/common/quic/active_quic_listener_test.cc
Testing: yep
Fixes https://github.com/envoyproxy/envoy/issues/26089
> quic: attempting to reduce an infrequent test flake

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix condition for postsubmit pipeline dependency resolution

- ci/do_ci.sh
This more than halves the time to run the arm build/release tests
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Download minimal for release tests

- .azure-pipelines/stages.yml
Minor cleanup that saves 30s
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docker/ci: Speed up download of release assets

- source/common/router/upstream_request.cc
- source/common/router/upstream_request.h
Commit Message: Small reduction in memory with Upstream Requests by changing alignment
Sizeof test
Before changes: 1168
After changes: 1160
> Reduce overhead in UpstreamRequest by fixing alignment

- .github/dependabot.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> dependabot: Fix docker/go paths

- .azure-pipelines/pipelines.yml
- .bazelrc
- ci/build_setup.sh
- ci/do_ci.sh
- ci/setup_cache.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] Assorted CI optimizations

- contrib/golang/filters/http/test/BUILD
- test/extensions/filters/http/cache/cache_filter_integration_test.cc
Part of https://github.com/envoyproxy/envoy/issues/26081
Part of https://github.com/envoyproxy/envoy/issues/26182
> test: disabling flaky tests until the can be debugged

- .azure-pipelines/pipelines.yml
- .bazelrc
- ci/build_setup.sh
- ci/do_ci.sh
- ci/setup_cache.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.22] Assorted CI optimizations

- .azure-pipelines/pipelines.yml
- .bazelrc
- ci/build_setup.sh
- ci/do_ci.sh
- ci/setup_cache.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] Assorted CI optimizations

- test/extensions/filters/network/http_connection_manager/config_test.cc
Commit Message:rename few variables as per variable naming standards
Additional Description:rename few variables as per variable naming standards
Risk Level:N/A
Testing: N/A
> rename few variables as per variable naming standards

- .azure-pipelines/bazel.yml
- .azure-pipelines/pipelines.yml
- ci/do_ci.sh
- ci/setup_cache.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.22] ci: Use local cache

- test/integration/xds_integration_test.cc
Fixes https://github.com/envoyproxy/envoy/issues/22489
> test: hopefully finally fixing lds flake

- test/integration/http_integration.cc
Fixes https://github.com/envoyproxy/envoy/issues/26068
> test: removing size checks that never work well

- docs/root/version_history/v1.22.9.rst
- docs/root/version_history/version_history.rst
- examples/tls-inspector/docker-compose.yaml
- examples/tls-inspector/envoy.yaml
- examples/tls-sni/docker-compose.yaml
- examples/tls-sni/envoy.yaml
- examples/tls/docker-compose.yaml
- examples/tls/envoy-http-https.yaml
- examples/tls/envoy-https-http.yaml
- examples/tls/envoy-https-https.yaml
- examples/tls/envoy-https-passthrough.yaml
- examples/tls/verify.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [dev/1.22] repo: Dev v1.22.10

- mobile/library/swift/EngineBuilder.swift
Commit Message: Format fix.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile: format fix in Swift EngineBuilder

- test/integration/xds_integration_test.cc
https://github.com/envoyproxy/envoy/issues/26188
> test: possibly improving a flake

- test/common/router/scoped_rds_test.cc
- test/common/upstream/cluster_manager_impl_test.cc
- test/extensions/filters/udp/dns_filter/dns_filter_test.cc
> Compliance fixes for C++20

- RELEASES.md
- ci/do_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix project publish command/docs

- changelogs/current.yaml
- source/extensions/common/dubbo/codec.cc
- source/extensions/filters/network/dubbo_proxy/dubbo_protocol_impl.cc
- test/extensions/common/dubbo/codec_test.cc
- test/extensions/filters/network/dubbo_proxy/dubbo_protocol_impl_test.cc
Commit Message: fix: fix the error of the dubbo response status validation
To close #26242.
Testing: unit.
> fix: fix the error of the dubbo response status validation

- contrib/golang/filters/http/source/cgo.cc
- contrib/golang/filters/http/source/go/pkg/api/api.h
- contrib/golang/filters/http/source/go/pkg/api/capi.go
- contrib/golang/filters/http/source/go/pkg/api/filter.go
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/go/pkg/http/filter.go
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
- contrib/golang/filters/http/test/golang_filter_test.cc
- contrib/golang/filters/http/test/test_data/basic/filter.go
Commit Message: support logging in Go plugin.
Additional Description:  support logging in Go plugin.
Testing: yes
Release Notes:
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/26238
> Support logging in Go plugin

- .azure-pipelines/stages.yml
https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Update Github's SSH key

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.22] ci: Update Github's SSH key (#26330)

- .github/workflows/mobile-docs.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile/ci: Fix gitub ssh key for docs

- ci/do_ci.sh
due to CVE scanner data download issues
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Temporarily disable dependency checker

- docs/root/intro/arch_overview/upstream/load_balancing/slow_start.rst
Commit Message: Update user docs for slow start with priorities.
Risk Level: Low (doc update of current functionality)
Testing: NA
Release Notes:
Fixes #25283
> Update docs for slow start with priorities

- contrib/golang/common/dso/dso.cc
- contrib/golang/common/dso/test/dso_test.cc
- contrib/golang/common/dso/test/test_data/BUILD
- contrib/golang/common/dso/test/test_data/bad.go
fix loaded_ may be overwritten unexpectedly.
fix #25757
Risk Level:
Testing:
Docs Changes:
Release Notes:
> golang extension: fix loaded_ may be overwritten unexpectedly.

- docs/root/configuration/http/http_filters/golang_filter.rst
fix #26393
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docs: fix command line example in golang filter

- examples/cors/frontend/service.py
Modify the content-type returned by index.html，let browser parse right
Risk Level:
Testing:
Docs Changes:
Release Notes:
> fix examples cors

- bazel/repository_locations.bzl
- ci/do_ci.sh
This reverts commit d0fb05936f28b514d0c1f9fc9c63425816423563.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Revert "ci: Temporarily disable dependency checker (#26389)"

- source/common/upstream/upstream_impl.h
Commit Message: upstream: minor code clean up
Testing: n/a.
> upstream: minor code clean up

- changelogs/current.yaml
- docs/root/configuration/operations/overload_manager/overload_manager.rst
- source/server/overload_manager_impl.cc
- source/server/overload_manager_impl.h
- test/server/BUILD
- test/server/overload_manager_impl_test.cc
Commit Message: : Add loop delay histogram for overload manager resource refresh loop.
Testing: added unit test
Release Notes:  included
> Overload Manager: Add loop delay histogram for overload manager resource refresh loop.

- CODEOWNERS
- source/common/upstream/BUILD
- source/common/upstream/health_checker_event_logger.cc
- source/common/upstream/health_checker_event_logger.h
- source/common/upstream/health_checker_impl.h
- source/extensions/health_checkers/common/BUILD
- source/extensions/health_checkers/common/health_checker_base_impl.cc
- source/extensions/health_checkers/common/health_checker_base_impl.h
- source/extensions/health_checkers/grpc/BUILD
- source/extensions/health_checkers/grpc/health_checker_impl.h
- source/extensions/health_checkers/http/BUILD
- source/extensions/health_checkers/http/health_checker_impl.h
- source/extensions/health_checkers/redis/BUILD
- source/extensions/health_checkers/redis/redis.h
- source/extensions/health_checkers/tcp/BUILD
- source/extensions/health_checkers/tcp/health_checker_impl.h
- source/extensions/health_checkers/thrift/BUILD
- source/extensions/health_checkers/thrift/thrift.h
- test/common/upstream/hds_test.cc
- test/extensions/transport_sockets/starttls/starttls_integration_test.cc
> health checkers: moving more code to extensions

- changelogs/current.yaml
- envoy/stream_info/stream_info.h
- source/common/router/upstream_request.cc
- source/common/router/upstream_request.h
- test/common/router/upstream_request_test.cc
- test/integration/filters/stream_info_to_headers_filter.cc
- test/integration/multiplexed_upstream_integration_test.cc
Commit Message: Upstream Timing: Time pool callback latency.
Testing: Added unit, integration test
Fixes #25480
> Upstream Timing: Time pool callback latency

- mobile/test/kotlin/apps/experimental/MainActivity.kt
Platform cert validation causing experimental kotlin app CI job to be red.
> mobile: disable platform cert validation

- ci/do_ci.sh
This reverts commit 67f149f70f8824319831eb548f551c5d1228a953.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Revert "ci: Temporarily disable dependency checker (#26477)"

- contrib/golang/filters/http/source/go/pkg/api/type.go
- contrib/golang/filters/http/source/go/pkg/http/shim.go
- contrib/golang/filters/http/source/go/pkg/http/type.go
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/basic/filter.go
Commit Message: added more APIs for RequestHeaderMap & ResponseHeaderMap interface for golang extension
1. Added more APIs for golang header api:
```
type RequestHeaderMap interface {
HeaderMap
Protocol() string
Scheme() string
Method() string
Host() string
Path() string
}
type ResponseHeaderMap interface {
HeaderMap
Status() (int, bool)
}
```
2. Split trailer function to make the code more clearer.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> golang extension: added more APIs for RequestHeaderMap & ResponseHeaderMap interface

- .azure-pipelines/stages.yml
- .dockerignore
- ci/Dockerfile-envoy
- ci/do_ci.sh
- contrib/exe/BUILD
- distribution/BUILD
- distribution/binary/BUILD
- examples/vrp-local/verify.sh
- add release bundle targets
- use zstd for bundling release tarball
- cleanup/optimize Docker recipe
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/release: Use bazel to build binary bundles

- .azure-pipelines/stages.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Improve display names

- .azure-pipelines/stages.yml
Fix #26487 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Only run dependency checker when dependencies change

- test/per_file_coverage.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> build: fix coverage

- test/integration/protocol_integration_test.cc
Commit Message: Flake: Disable test for post submit flake.
Risk Level:
Testing:
Docs Changes:
Release Notes:
Related to #26484
> Flake: Disable test for post submit flake.

- .azure-pipelines/stages.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix dependency condition for postsubmit

- .azure-pipelines/stages.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Dont run skip/ped checks in postsubmit

- test/integration/listener_lds_integration_test.cc
- test/integration/xds_integration_test.cc
Part of https://github.com/envoyproxy/envoy/issues/26336 https://github.com/envoyproxy/envoy/issues/22489
> test: disabling flaky tests

- source/extensions/common/tap/extension_config_base.cc
- test/extensions/filters/http/tap/tap_filter_integration_test.cc
- test/test_common/logging.h
Hopefully fixes https://github.com/envoyproxy/envoy/issues/26258 (see issue for failure details)
> test: adding synchronization for tap tests

- test/extensions/filters/http/grpc_json_transcoder/grpc_json_transcoder_integration_test.cc
- test/integration/integration_stream_decoder.cc
- test/integration/multiplexed_integration_test.cc
This may help https://github.com/envoyproxy/envoy/issues/26258
> test: handling multi-request tests better

- test/extensions/resource_monitors/injected_resource/injected_resource_monitor_integration_test.cc
Commit Message: Test: add logging for flake debugging
Testing: test only
Docs Changes:
Release Notes:
Related Issue #26264
> Test: add logging for flake debugging

- .azure-pipelines/bazel.yml
- ci/run_envoy_docker.sh
- ci/setup_cache.sh
Fix #26566 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix local cache key

- envoy/stream_info/stream_info.h
Commit Message: fix: minor fix to the upstreaim timing methods' comment
n/a.
Testing: n/a.
> fix: minor fix to the upstreaim timing methods' comment

- test/integration/tcp_proxy_integration_test.cc
Testing:
Docs Changes:
Release Notes:
> test: fix common typo

- envoy/server/options.h
- source/server/options_impl.cc
- source/server/options_impl.h
- source/server/server.cc
- test/mocks/server/options.cc
- test/mocks/server/options.h
removing a transient options API added for the mobile API listener transition.
Testing: n/a
> options: cleaning up listener config

- changelogs/current.yaml
- docs/root/configuration/observability/access_log/usage.rst
- envoy/stream_info/stream_info.h
- source/common/formatter/substitution_formatter.cc
- source/common/formatter/substitution_formatter.h
- source/common/http/conn_manager_impl.cc
- source/common/stream_info/BUILD
- source/common/stream_info/stream_info_impl.h
- source/common/stream_info/utility.cc
- source/common/stream_info/utility.h
- source/common/tcp_proxy/tcp_proxy.cc
- test/common/formatter/substitution_formatter_test.cc
- test/common/http/conn_manager_impl_test.cc
- test/common/stream_info/stream_info_impl_test.cc
- test/common/stream_info/utility_test.cc
- test/common/tcp_proxy/tcp_proxy_test.cc
- test/integration/tcp_proxy_integration_test.cc
- test/mocks/stream_info/mocks.cc
- test/mocks/stream_info/mocks.h
Commit Message: Reverts the following PRs: https://github.com/envoyproxy/envoy/pull/26456 and https://github.com/envoyproxy/envoy/pull/26256
Additional Description: commits: 1665a05f474700302b29771d17238e19eee9e015 and  721f456e4481b82661e5d3076c04686b3ec93005
Testing: CI
> Revert stream state changes

- test/extensions/filters/network/echo/echo_integration_test.cc
- test/integration/listener_lds_integration_test.cc
- test/integration/utility.cc
- test/integration/utility.h
- test/integration/xds_integration_test.cc
> test: verifying waitForConnection waits for a connection.

- test/integration/shadow_policy_integration_test.cc
Commit Message: fix flaky shadowing test.
Risk Level: no risk
Testing: test fix.
> test: fix streaming shadow flake

- tools/testdata/check_format/bad_envoy_build_sys_ref.BUILD
- tools/testdata/check_format/bad_envoy_build_sys_ref.BUILD.gold
- tools/testdata/check_format/bazel_tools.BUILD
- tools/testdata/check_format/proto.BUILD
- tools/testdata/check_format/proto.BUILD.gold
Risk Level:
Testing:
Docs Changes:
Release Notes:
> proto/tools: Dont stamp proto test data

- contrib/vcl/source/vpp_vcl_build.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> build: Quieten pushd/popd in VCL build

- .azure-pipelines/stages.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Merge docs and docker prechecks -> publishing

- tools/testdata/check_format/bad_envoy_build_sys_ref.BUILD
- tools/testdata/check_format/bad_envoy_build_sys_ref.BUILD.gold
- tools/testdata/check_format/bazel_tools.BUILD
- tools/testdata/check_format/proto.BUILD
- tools/testdata/check_format/proto.BUILD.gold
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Really dont stamp proto test bins

- ci/format_pre.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> format_pre: Minor cleanups

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix typo that caused pipelines to fail

- .azure-pipelines/stages.yml
- ci/filter_example_mirror.sh
- checkout full repo where required
- ignore empty commits for scheduled runs
Fix #26703 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix handling of git sync

- test/extensions/http/header_validators/envoy_default/header_validator_test.h
- test/extensions/http/header_validators/envoy_default/http1_header_validator_test.cc
- test/extensions/http/header_validators/envoy_default/http2_header_validator_test.cc
> Add missing default UHV tests

- contrib/golang/filters/http/source/cgo.cc
- contrib/golang/filters/http/source/go/pkg/api/api.h
- contrib/golang/filters/http/source/go/pkg/api/capi.go
- contrib/golang/filters/http/source/go/pkg/api/filter.go
- contrib/golang/filters/http/source/go/pkg/http/BUILD
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/go/pkg/http/filter.go
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
- contrib/golang/filters/http/source/processor_state.h
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/basic/filter.go
Part 1 from https://github.com/envoyproxy/envoy/issues/25371.
Chose to implement the set and get in individual commits mostly to
make reviewing process more easy. Can either follow up with get in
a seperate PR or commit.
Signed-off-by: Sotiris Nanopoulos <sotirisnan@gmail.com>
> Golang filter: Add suport for setting dynamic metadata

- .azure-pipelines/docker/load_cache.sh
- .azure-pipelines/docker/prime_cache.sh
- .azure-pipelines/docker/save_cache.sh
Fix #26676 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix cache tarball compression

- test/common/http/http1/codec_impl_test.cc
- test/common/http/http2/codec_impl_test.cc
> Refactor codec tests to work with UHV with fewer ifdefs

- .azure-pipelines/stages.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix scheduled git sync fail (/cont)

- bazel/dependency_imports.bzl
Risk Level:
Testing:
Docs Changes:
Release Notes:
> deps: Specify emscripten dependency

- source/common/http/filter_manager.cc
Commit Message: Minor simplification to the filter-manager code
Converting `&*this` to `this`.
Testing: N/A
> filter-manager: minor simplification

- api/envoy/api/v2/route/route_components.proto
- api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto
- api/envoy/config/route/v3/route_components.proto
- api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
Commit Message: fix client sampling annotation
Testing: N/A
> fix client sampling annotation

- contrib/golang/filters/http/source/cgo.cc
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/processor_state.cc
- contrib/golang/router/cluster_specifier/source/cgo.cc
Commit Message: using envoy code style.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> golang filter: code style tweak.

- .azure-pipelines/stages.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Update pool names

- api/envoy/config/overload/v3/overload.proto
- changelogs/current.yaml
- docs/root/configuration/operations/overload_manager/overload_manager.rst
- envoy/network/BUILD
- envoy/network/listener.h
- envoy/server/overload/BUILD
- envoy/server/overload/load_shed_point.h
- envoy/server/overload/overload_manager.h
- source/common/network/tcp_listener_impl.cc
- source/common/network/tcp_listener_impl.h
- source/common/network/udp_listener_impl.h
- source/extensions/bootstrap/internal_listener/active_internal_listener.h
- source/extensions/listener_managers/listener_manager/connection_handler_impl.cc
- source/extensions/listener_managers/listener_manager/connection_handler_impl.h
- source/server/listener_manager_factory.h
- source/server/worker_impl.cc
- test/common/network/BUILD
- test/common/network/listener_impl_test.cc
- test/integration/base_overload_integration_test.cc
- test/integration/base_overload_integration_test.h
- test/integration/overload_integration_test.cc
- test/mocks/network/mocks.h
- test/mocks/server/overload_manager.h
- test/server/connection_handler_test.cc
Commit Message: Overload Manager: Implement LoadshedPoint for Tcp Accept.
Risk Level: low/ med
Testing: unit, integration test
Docs Changes: included 
Runtime guard: n/a , config needed 
> Overload Manager: Implement LoadshedPoint for Tcp Accept.

- changelogs/current.yaml
Commit Message: fix changelog.yaml for code format checks
Risk Level:
Testing:
Docs Changes:
Release Notes:
> fix changelog.yaml

- ci/filter_example_mirror.sh
- ci/run_clang_tidy.sh
- filter example
- clang_tidy
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Assorted fixes for scheduled runs

- ci/build_setup.sh
- ci/do_ci.sh
- ci/setup_cache.sh
Fix #16788
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Dont set `TEST_TMPDIR`

- ci/setup_cache.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix/workaround caching for manual run PR commits

- .azure-pipelines/stages.yml
- ci/do_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> repo: Release v1.26.0

- source/server/server.cc
Commit Message: fix local variable name
Update non-member variable name to comply with the style guide.
Testing: N/A
> server: fix local variable name

- api/envoy/extensions/transport_sockets/tls/v3/common.proto
Commit Message: fix crl docs
Additional Description: fix crl docs
Testing: N/A
Release Notes:
> fix crl docs

- .azure-pipelines/stages.yml
Fix #26818 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Increase timeouts for slow builds

- envoy/http/header_validator.h
- source/extensions/http/header_validators/envoy_default/http1_header_validator.cc
- source/extensions/http/header_validators/envoy_default/http2_header_validator.cc
> UHV: Remove unused cast operator

- docs/root/configuration/http/http_filters/lua_filter.rst
Commit Message: fix lua doc
Testing: N/A
Docs Changes: lua
> fix lua doc

- envoy/stream_info/BUILD
- envoy/stream_info/filter_state.h
- source/common/network/connection_impl.cc
- source/common/quic/envoy_quic_client_session.cc
- source/common/router/upstream_request.cc
- source/common/stream_info/filter_state_impl.cc
- source/common/stream_info/filter_state_impl.h
- source/common/stream_info/stream_info_impl.h
- source/extensions/filters/http/common/factory_base.h
- test/common/http/async_client_impl_test.cc
- test/common/router/router_test_base.cc
- test/common/router/router_upstream_filter_test.cc
- test/common/router/router_upstream_log_test.cc
- test/common/stream_info/BUILD
- test/common/stream_info/filter_state_impl_test.cc
- test/integration/BUILD
- test/integration/filters/header_to_filter_state.cc
- test/integration/upstream_access_log_integration_test.cc
- test/mocks/stream_info/mocks.cc
- test/mocks/stream_info/mocks.h
This reverts commit dd39b3aa1e8b649f48655350b57a3078ead1b143.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Revert "upstream: enhance upstream filter state (#25917)"

- .azure-pipelines/stages.yml
Partial fix for #26810
Risk Level:
Testing:
Docs Changes:
Release Notes:
> release: Fix asset publishing

- examples/shared/websocket/Dockerfile
Risk Level:
Testing:
Docs Changes:
Release Notes:
> examples: Fix websocket Docker recipe

- contrib/golang/filters/http/source/go/pkg/api/filter.go
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/go/pkg/http/filter.go
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/basic/filter.go
Commit Message: add downstream local and remote address in StreamInfo interface for golang extension
> add downstream local and remote address in StreamInfo interface for golang extension

- source/exe/BUILD
Commit Message: build: include validation listener manager in the envoy exe build
Testing: n/a
Fixes #26822
> build: include validation listener manager in the envoy exe build

- .github/workflows/mobile-compile_time_options.yml
- bazel/BUILD
- bazel/envoy_build_system.bzl
- bazel/envoy_mobile_defines.bzl
- bazel/envoy_select.bzl
- mobile/library/cc/engine_builder.cc
- mobile/test/common/jni/test_jni_interface.cc
- source/common/config/utility.cc
- source/common/config/xds_context_params.cc
- source/common/formatter/substitution_formatter.cc
- source/common/http/filter_chain_helper.h
- source/common/protobuf/BUILD
- source/common/protobuf/utility.cc
- source/common/protobuf/utility.h
- source/common/protobuf/visitor.cc
- source/common/protobuf/yaml_utility.cc
- source/common/runtime/runtime_impl.cc
- source/common/tracing/custom_tag_impl.cc
- source/common/upstream/health_checker_event_logger.cc
- source/common/upstream/outlier_detection_impl.cc
- source/common/upstream/subset_lb.cc
- source/server/server.cc
- test/integration/BUILD
- test/integration/utility.cc
- test/test_common/network_utility.cc
- test/test_common/utility.h
- tools/code_format/config.yaml
e2e tests will not pass until https://github.com/envoyproxy/envoy/pull/26451 lands
Risk Level: medium (should be no-op but includes refactors)
Testing: n/a
part of https://github.com/envoyproxy/envoy/issues/26450
> build: allow Envoy mobile to build sans YAML.

- .azure-pipelines/pipelines.yml
- .azure-pipelines/stages.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Reduce docker publish timeout and make configurable

- .azure-pipelines/bazel.yml
- .azure-pipelines/cached.yml
- .azure-pipelines/env.yml
- .azure-pipelines/pipelines.yml
- .azure-pipelines/stages.yml
- bazel/setup_clang.sh
- ci/build_setup.sh
- ci/check_and_fix_format.sh
- ci/do_ci.sh
- ci/filter_example_setup.sh
- ci/format_pre.sh
- ci/run_envoy_docker.sh
- docs/build.sh
- test/run_envoy_bazel_coverage.sh
- tools/api/generate_go_protobuf.py
- tools/gen_compilation_database.py
- tools/proto_format/proto_format.sh
- tools/vscode/generate_debug_config.py
- fix bazel invokation in build_setup.sh
- use bazel.yml and matrix for precheck jobs
- separate env -> `env.yml`
- add cache for bazel artefacts - external directory, install dir, .cache
- mount more tmpfs in self-hosted
- ensure all bazel invokations use correct options to prevent creation of duplicate build environments
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Cleanups/optimizations for azp, Docker build and bazel

- .azure-pipelines/env.yml
- .azure-pipelines/stages.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Upgrade Docker to latest in `docker_ci.sh` job

- contrib/golang/filters/http/test/golang_integration_test.cc
Commit Message: fix go extension test annotation
Testing: N/A
> fix go extension test annotation

- .bazelci/presubmit.yml
Fixes https://github.com/envoyproxy/envoy/issues/26913
> bazel: fix presubmit CI

- .azure-pipelines/stages.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix sync auth bug

- .azure-pipelines/stage/publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix docs publishing

- contrib/golang/filters/http/source/go/pkg/api/filter.go
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/go/pkg/http/filter.go
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/basic/filter.go
Commit Message: add upstream host and cluster in StreamInfo interface for golang extension
> add upstream host and cluster in StreamInfo interface for golang extension

- examples/websocket/Dockerfile-websocat
- examples/websocket/Dockerfile-websocat-client
- test/common/filesystem/filesystem_impl_test.cc
- test/per_file_coverage.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.25] Backport stack

- examples/websocket/Dockerfile-websocat
- examples/websocket/Dockerfile-websocat-client
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.24] Backport stack

- examples/websocket/Dockerfile-websocat
- examples/websocket/Dockerfile-websocat-client
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.23] Backport stack

- .azure-pipelines/stage/prechecks.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.26] ci: Fix protobuf diff upload (#26976)

- test/integration/multiplexed_integration_test.cc
- test/integration/shadow_policy_integration_test.cc
verifies https://github.com/envoyproxy/envoy/issues/26820
> test: adding e2e testing for conn pool per downstream connection

- changelogs/current.yaml
- source/common/router/router.cc
- source/common/runtime/runtime_features.cc
Testing: n/a
Fixes https://github.com/envoyproxy/envoy/issues/26899
> runtime: removing envoy.reloadable_features.closer_shadow_behavior

- .azure-pipelines/pipelines.yml
- .azure-pipelines/stage/publish.yml
- .azure-pipelines/stages.yml
- ci/docker_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [backport/1.26] ci: Add timeouts and fail handling on some hanging actions #26996

- mobile/library/common/extensions/filters/http/test_event_tracker/filter.proto
- mobile/library/common/extensions/filters/http/test_logger/filter.proto
- mobile/library/common/extensions/filters/http/test_read/filter.proto
- mobile/library/common/extensions/retry/options/network_configuration/predicate.proto
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile: cleaning up unused validate imports

- mobile/library/cc/BUILD
- mobile/library/cc/engine.cc
- mobile/library/cc/engine.h
- mobile/library/common/engine_handle.cc
- mobile/library/common/engine_handle.h
- mobile/library/common/jni/BUILD
- mobile/library/common/main_interface.cc
- mobile/library/common/main_interface.h
- mobile/test/common/engine_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile: fixing a tsan flake

- ci/do_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> do/ci: Switch switch to switch

- CODEOWNERS
ext_proc is now heavily used in our projects. Update the file per offline conversation, @pradeepcrao is not working closely on any projects in this domain. Also, update ext_authz as discussed offline.
> Update owner file

- docs/root/configuration/listeners/network_filters/_include/wasm-network-filter.yaml
- docs/root/configuration/listeners/network_filters/wasm_filter.rst
Commit Message: fix network wasm example doc
Testing: N/A
Docs Changes: wasm
> fix network wasm example doc

- docs/root/intro/arch_overview/http/http_filters.rst
- docs/root/intro/life_of_a_request.rst
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docs: updating life of a request

- docs/root/start/building.rst
Fix #26965
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docs: Point compiler info to repo

- bazel/repository_locations.bzl
> docs: fix the license URL of the dependency "dd-trace-cpp"

- tools/base/requirements.in
- tools/base/requirements.txt
Risk Level:
Testing:
Docs Changes:
Release Notes:
> deps: Bump `sphinx` -> 7.0.0

- test/common/http/http2/http2_connection_fuzz_test.cc
Commit Message: Cleanup: Cleanup clang tidy errors in fuzzer
> Cleanup: Cleanup clang tidy errors in fuzzer

- test/integration/idle_timeout_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> test: hopefully fixing a tsan flake

- source/common/http/conn_manager_impl.cc
- source/common/http/conn_manager_impl.h
> Remove unused ConnectionManagerImpl::http_context_ member variable

- .azure-pipelines/bazel.yml
- .azure-pipelines/pipelines.yml
- ci/Dockerfile-envoy
- ci/filter_example_mirror.sh
- ci/run_clang_tidy.sh
- ci/run_envoy_docker.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.23] Backport stack

- .azure-pipelines/bazel.yml
- .azure-pipelines/pipelines.yml
- ci/Dockerfile-envoy
- ci/do_ci.sh
- ci/filter_example_mirror.sh
- ci/run_clang_tidy.sh
- ci/run_envoy_docker.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.24] Backport stack

- .azure-pipelines/bazel.yml
- .azure-pipelines/pipelines.yml
- ci/Dockerfile-envoy
- ci/do_ci.sh
- ci/filter_example_mirror.sh
- ci/run_clang_tidy.sh
- ci/run_envoy_docker.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.25] Backport stack

- ci/do_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Workaround dep checker (cves) issue again

- source/common/common/regex.cc
- source/common/common/regex.h
- source/common/stats/tag_extractor_impl.cc
- test/common/common/regex_test.cc
> stats: moving a single-use utilility inline into the class

- .bazelrc
- ci/do_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Cleanups/optimizations

- test/per_file_coverage.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> test: racheting coverage

- ci/do_ci.sh
This reverts commit 97a2f2b94e944c58d4214cf5ecd4fce818a2351e.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Revert "ci: Workaround dep checker (cves) issue again (#27141)"

- .azure-pipelines/stages.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Improve/clarify var name

- mobile/.bazelrc
- mobile/tools/should_run_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile/ci: Trigger run with .bazelrc (and fix)

- source/common/http/filter_manager.h
- source/common/router/config_impl.h
- source/common/router/upstream_request.cc
- source/extensions/health_checkers/common/health_checker_base_impl.h
- test/integration/utility.h
> Remove dead code

- source/common/router/config_impl.cc
- test/common/router/config_impl_test.cc
- test/integration/http_typed_per_filter_config_test.cc
Commit Message: minor opt: fix the content of exceptions to make it more accurate
Testing: n/a.
> minor opt: fix the content of exceptions to make it more accurate

- envoy/http/filter.h
Commit Message: fix typo of comments of http filter interface
Testing: n/a.
> fix typo of comments of http filter interface

- source/common/http/conn_manager_impl.cc
- source/common/http/conn_manager_impl.h
Commit Message: minor optimization: minor optimization to improve the code quality/readability
Split from #27242
Testing: n/a.
Release Notes: n/a. 
> minor optimization: minor optimization to improve the code quality/readability

- source/common/http/conn_manager_impl.cc
Commit Message: minor optimization: minor optimization to improve the code quality
As title.
Testing: n/a.
> minor optimization: minor optimization to setRoute to improve the code quality

- mobile/test/common/integration/cds_integration_test.cc
> Fix msan error in mobile cds_integration_test

- mobile/test/common/integration/client_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile: adding a test of large response body

- bazel/foreign_cc/vpp_vcl.patch
- contrib/vcl/source/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
> contrib: avoid building unnecessary vpp targets

- ci/do_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> do/ci: Improve readability

- .azure-pipelines/bazel.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Improve presubmit caching

- .azure-pipelines/bazel.yml
- .azure-pipelines/stage/checks.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix test/artefact conditions

- source/common/http/codec_client.cc
- source/common/http/codec_wrappers.h
- test/common/http/codec_wrappers_test.cc
- test/per_file_coverage.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> http: adding test coverage

- api/envoy/config/cluster/v3/cluster.proto
Risk Level:
Testing:
Docs Changes:
Release Notes:
> remove duplicated comments words

- ci/do_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> do/ci: Reorder case statements and improve block spacing

- .azure-pipelines/bazel.yml
- .azure-pipelines/stage/checks.yml
- .azure-pipelines/stage/macos.yml
- .azure-pipelines/stage/publish.yml
- .azure-pipelines/stage/windows.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Dont publish anything if cancelled

- mobile/library/kotlin/io/envoyproxy/envoymobile/StreamPrototype.kt
Fix #27398 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile: Fix kotlin lint problem

- test/extensions/filters/http/file_system_buffer/filter_integration_test.cc
> Deflake file_system_buffer_integration_test under TSAN

- tools/base/envoy_python.bzl
Risk Level:
Testing:
Docs Changes:
Release Notes:
> python: Workaround for template macro

- api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Cleanup an ext_proc filter API comments.

- docs/root/configuration/other_features/internal_listener.rst
Risk Level:
Testing:
Docs Changes:
Release Notes:
> fix a typo in internal_listener.rst

- .github/workflows/mobile-coverage.yml
- mobile/.bazelrc
- test/run_envoy_bazel_coverage.sh
afaict mobile coverage has been broken for a long time - certainly any envoy ci that i can find has failed
i believe it was this commit https://github.com/envoyproxy/envoy/commit/4fa64fa7c7d47151495bf67c772b36e2fc666f1f that broke it - EDIT: seems it was broken before then - not sure, but hard to find a time when it would have worked
certainly it would not have been detectable since https://github.com/envoyproxy/envoy-mobile/commit/a34f26ed35e6eb95a08c0ec94e5f3d777a8be17c
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist …
> mobile/ci: Fix coverage

- test/extensions/filters/http/alternate_protocols_cache/BUILD
- test/extensions/filters/http/custom_response/BUILD
- test/integration/BUILD
> Add more CPU for next batch of flaky integration tests

- source/common/http/conn_manager_impl.cc
- source/common/http/http1/codec_impl.cc
- source/common/runtime/runtime_features.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> runtime: cleaning up flag which was turned down

- tools/code_format/check_format.py
- tools/code_format/config.yaml
Risk Level: n/a (tool only)
Testing: n/a
Part of https://github.com/envoyproxy/envoy/issues/27412
> tools: discouraging exceptions in core c++ files

- contrib/golang/filters/http/source/cgo.cc
- contrib/golang/filters/http/source/go/pkg/api/api.h
- contrib/golang/filters/http/source/go/pkg/api/capi.go
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/go/pkg/http/type.go
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/basic/filter.go
Commit Message: add go extension trailer del api
Testing: interation test
> add go extension trailer del api

- ci/do_ci.sh
- ci/run_envoy_docker.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix dockerhub publishing credentials

- .github/workflows/commands.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix `/retest` permissions

- changelogs/current.yaml
update changelog after PR27296
Risk Level:
Testing:
Docs Changes:
Release Notes:
> nit: update rel1.24 changelog after PR27296

- changelogs/current.yaml
update changelog after PR27296
Risk Level:
Testing:
Docs Changes:
Release Notes:
> nit: update rel1.23 changelog after PR27296

- changelogs/current.yaml
update changelog after PR27296
Risk Level: Zero.
Testing:
Docs Changes:
Release Notes:
> nit: update changelog after PR27296

- changelogs/current.yaml
update changelog after PR27296
Risk Level:
Testing:
Docs Changes:
Release Notes:
> nit: update rel1.25 changelog after PR27296

- contrib/generic_proxy/filters/network/source/interface/BUILD
- contrib/generic_proxy/filters/network/source/interface/route.h
- contrib/generic_proxy/filters/network/source/route.cc
- contrib/generic_proxy/filters/network/source/route.h
- contrib/generic_proxy/filters/network/test/mocks/route.h
- contrib/generic_proxy/filters/network/test/route_test.cc
Commit Message: generic proxy: typed metadata support for the generic route
Minor enhancement to the generic route.
Testing: n/a.
> generic proxy: typed metadata support for the generic route

- .azure-pipelines/stage/publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Use bazel.yml for docs publishing

- .github/workflows/mobile-ios_build.yml
Partial fix for #27048 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/mobile: Improve `swift_async_await` timeout

- api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Adding allow_mode_override API in ext_proc filter config.

- .github/workflows/mobile-ios_build.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile/ci: Fix workflow dependencies

- source/docs/network_filter_fuzzing.md
- test/extensions/filters/network/common/fuzz/BUILD
- test/extensions/filters/network/common/fuzz/config.bzl
- tools/base/requirements.in
- tools/base/requirements.txt
- tools/code/BUILD
Fix #27575 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/fuzz: Update to use `--extensions_fuzzed_count` flag for check

- test/extensions/filters/network/common/fuzz/config.bzl
- tools/base/requirements.in
- tools/base/requirements.txt
- tools/code/BUILD
address one of the issues raised here https://github.com/envoyproxy/envoy/pull/27610#issuecomment-1561577553
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/fuzz: Ensure fuzz check is included in code check

- contrib/golang/filters/http/source/cgo.cc
- contrib/golang/filters/http/source/go/pkg/api/api.h
- contrib/golang/filters/http/source/go/pkg/api/capi.go
- contrib/golang/filters/http/source/go/pkg/api/filter.go
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/go/pkg/http/filter.go
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/basic/filter.go
Commit Message: add go extension filter state set api
Testing: intergation test
> add go extension filter state set api

- .github/workflows/envoy-verify.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Cleanup/fix for verify move

- .github/workflows/envoy-verify.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Further cleanup/fix for verify move

- .azure-pipelines/bazel.yml
- .azure-pipelines/stage/publish.yml
- .azure-pipelines/stage/verify.yml
- .azure-pipelines/stages.yml
Cleanups:
- use bazel.yml for Docker publishing
- simplify publishing scripts
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Use `bazel.yml` for Docker publishing

- contrib/golang/filters/http/source/go/pkg/api/BUILD
- contrib/golang/filters/http/source/go/pkg/api/cgocheck.go
- contrib/golang/filters/http/source/go/pkg/http/config.go
Commit Message: reject if the cgocheck is not disabled
Testing:
Docs Changes:
Release Notes:
> golang filter: reject if the cgocheck is not disabled

- ci/do_ci.sh
Minor cleanup to remove unnecessary exit code
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/examples: Minor cleanup

- .github/workflows/POLICY.md
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Add github workflow POLICY

- .azure-pipelines/pipelines.yml
- .bazelrc
- test/common/common/logger_test.cc
- test/test_runner.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.25] Backport stack (2)

- .azure-pipelines/pipelines.yml
- .bazelrc
- test/common/common/logger_test.cc
- test/test_runner.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.24] Backport stack (2)

- .github/workflows/envoy-verify.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/examples: Add diskspace hack (github version)

- .github/workflows/env.yml
- .github/workflows/mobile-android_build.yml
- .github/workflows/mobile-android_tests.yml
- .github/workflows/mobile-asan.yml
- .github/workflows/mobile-cc_tests.yml
- .github/workflows/mobile-core.yml
- .github/workflows/mobile-coverage.yml
- .github/workflows/mobile-docs.yml
- .github/workflows/mobile-format.yml
- .github/workflows/mobile-perf.yml
- .github/workflows/mobile-tsan.yml
- .github/workflows/mobile_release.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/mobile: Set build images in one place

- api/envoy/extensions/transport_sockets/s2a/v3/s2a.proto
Original link 404, use the latest
> fix problematic link

- examples/cache/service.py
Commit Message: fix aiohttp exception reference in examples/cache/service.py
Testing: pytype
Docs Changes:
Release Notes:
> Fix examples/cache

- docs/root/configuration/http/cluster_specifier/golang.rst
- docs/root/configuration/http/http_filters/golang_filter.rst
- docs/root/start/sandboxes/golang.rst
- examples/golang/docker-compose.yaml
Testing:
Docs Changes:
Release Notes:
> add the GODEBUG=cgocheck=0 env variable for golang plugin example.

- source/common/router/router.cc
- source/common/router/router.h
- test/common/router/router_test.cc
Testing:  already integration tested
> router: cleaning up 1xx coalescing now done in codec filter

- changelogs/current.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> changelog: Add `wasmtime`, `c-ares` CVE updates

- docs/root/api-docs/xds_protocol.rst
Clarification for a workaround to https://github.com/envoyproxy/envoy/issues/27702.
> docs: Add info about xDS cluster ordering in the Bootstrap

- source/extensions/filters/http/composite/config.h
> composite: add CEL matcher to allow list

- contrib/golang/filters/http/source/cgo.cc
- contrib/golang/filters/http/source/go/pkg/api/api.h
- contrib/golang/filters/http/source/go/pkg/api/capi.go
- contrib/golang/filters/http/source/go/pkg/api/filter.go
- contrib/golang/filters/http/source/go/pkg/api/type.go
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/go/pkg/http/filter.go
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/basic/filter.go
Commit Message: support getting log level
Docs Changes:
Release Notes:
> golang filter: support getting log level

- .azure-pipelines/stage/publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> release/ci: Prevent release if Docker job fails

- mobile/docs/root/api/starting_envoy.rst
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile: better filter docs

- changelogs/current.yaml
- docs/root/configuration/listeners/listener_filters/tls_inspector.rst
- source/extensions/filters/listener/tls_inspector/tls_inspector.cc
- source/extensions/filters/listener/tls_inspector/tls_inspector.h
- test/common/stats/stat_test_utility.cc
- test/common/stats/stat_test_utility.h
- test/extensions/filters/listener/tls_inspector/BUILD
- test/extensions/filters/listener/tls_inspector/tls_inspector_integration_test.cc
- test/extensions/filters/listener/tls_inspector/tls_inspector_test.cc
- test/test_common/utility.cc
- test/test_common/utility.h
Commit Message: TLS Inspector: Capture client hello size distribution.
[Optional Runtime guard:] na
> TLS Inspector: Capture client hello size distribution.

- test/per_file_coverage.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> coverage: ratcheting

- envoy/common/exception.h
- source/common/ssl/certificate_validation_context_config_impl.cc
- source/common/ssl/certificate_validation_context_config_impl.h
- source/extensions/transport_sockets/tls/context_config_impl.cc
- test/common/secret/sds_api_test.cc
- test/common/secret/secret_manager_impl_test.cc
- tools/code_format/config.yaml
Part of https://github.com/envoyproxy/envoy-mobile/issues/176
> tls: making CertificateValidationContextConfigImpl exception free

- source/common/runtime/runtime_impl.cc
- test/integration/circuit_breakers_integration_test.cc
Fixes https://github.com/envoyproxy/envoy/issues/27376
> Runtime: correctly outputting runtime on admin console

- configs/encapsulate_http_in_http2_connect.yaml
- configs/encapsulate_in_http1_connect.yaml
- configs/encapsulate_in_http2_connect.yaml
- configs/encapsulate_in_http2_post.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Update curl command in the tunneling examples

- test/extensions/http/cache/file_system_http_cache/file_system_http_cache_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Fix flaky race in file_system_http_cache_test

- contrib/generic_proxy/filters/network/test/BUILD
- test/extensions/filters/http/alternate_protocols_cache/BUILD
- test/extensions/filters/http/custom_response/BUILD
- test/extensions/filters/http/ext_proc/BUILD
- test/extensions/filters/http/file_system_buffer/BUILD
- test/extensions/filters/http/grpc_json_transcoder/BUILD
- test/extensions/filters/http/local_ratelimit/BUILD
- test/extensions/filters/http/on_demand/BUILD
- test/extensions/filters/network/echo/BUILD
- test/extensions/filters/network/local_ratelimit/BUILD
- test/integration/BUILD
Commit Message: [backport] backport some patchs about the integration cpu
Try to backport some patchs about the integration cpu to fix the flaky lds test.
Testing: n/a.
> [backport] backport some patchs about the integration cpu

- envoy/upstream/load_balancer.h
- source/common/upstream/thread_aware_lb_impl.cc
- source/common/upstream/thread_aware_lb_impl.h
- source/extensions/clusters/aggregate/cluster.h
- source/extensions/clusters/dynamic_forward_proxy/cluster.h
- source/extensions/clusters/original_dst/original_dst_cluster.h
- source/extensions/clusters/redis/redis_cluster_lb.cc
- source/extensions/clusters/redis/redis_cluster_lb.h
- source/extensions/load_balancing_policies/common/factory_base.h
- source/extensions/load_balancing_policies/subset/config.cc
- test/common/upstream/load_balancer_benchmark.cc
- test/common/upstream/subset_lb_test.cc
- test/extensions/clusters/aggregate/BUILD
- test/extensions/clusters/aggregate/cluster_test.cc
- test/extensions/clusters/dynamic_forward_proxy/BUILD
- test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc
- test/extensions/clusters/redis/BUILD
- test/extensions/clusters/redis/redis_cluster_lb_test.cc
- test/extensions/load_balancing_policies/least_request/config_test.cc
- test/extensions/load_balancing_policies/maglev/config_test.cc
- test/extensions/load_balancing_policies/maglev/maglev_lb_test.cc
- test/extensions/load_balancing_policies/random/config_test.cc
- test/extensions/load_balancing_policies/ring_hash/config_test.cc
- test/extensions/load_balancing_policies/ring_hash/ring_hash_lb_test.cc
- test/extensions/load_balancing_policies/round_robin/config_test.cc
- test/extensions/load_balancing_policies/subset/config_test.cc
- test/integration/load_balancers/custom_lb_policy.h
- test/per_file_coverage.sh
Commit Message: upstream code cleanup: remove unnecessary create() method and test
Testing: n/a.
> upstream code cleanup: remove unnecessary create() method and test

- .github/workflows/mobile-traffic_director.yml
Discovered the issue through a manual run of the workflow: https://github.com/envoyproxy/envoy/actions/runs/5257781938/jobs/9501080688
> ci: Fix the Envoy Mobile Traffic Director YAML

- contrib/golang/filters/http/source/go/pkg/http/capi.go
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/go/pkg/http/filter.go
- contrib/golang/filters/http/source/go/pkg/http/type.go
Commit Message: go extension: add lock in go side to avoid concurrency race
Testing: intergation test
> go extension: add lock in go side to avoid concurrency race

- envoy/upstream/health_check_event_sink.h
Add pragma once to header
Testing:
Docs Changes:
Release Notes:
> hc: add pragma once

- test/extensions/filters/http/ext_proc/test_processor.cc
> Fix tsan error in the ext_proc_grpc_fuzz_test_persistent test

- api/envoy/extensions/filters/http/jwt_authn/v3/config.proto
- test/extensions/filters/http/jwt_authn/BUILD
- test/extensions/filters/http/jwt_authn/jwt_authn_corpus/out_of_range_duration
Resolves filer initialization exception from config with too high duration. Detected by jwt_authn_fuzz_test
> jwt_authn: Add upper bound on JWT cache_duration

- envoy/stream_info/BUILD
- envoy/stream_info/uint64_accessor.h
- source/common/stream_info/BUILD
- source/common/stream_info/uint64_accessor_impl.h
- test/common/stream_info/BUILD
- test/common/stream_info/uint64_accessor_impl_test.cc
> stream_info: add uint64 accessor

- changelogs/current.yaml
- docs/root/configuration/listeners/stats.rst
- envoy/network/listener.h
- source/common/network/tcp_listener_impl.cc
- source/extensions/listener_managers/listener_manager/active_tcp_listener.cc
- source/extensions/listener_managers/listener_manager/active_tcp_listener.h
- source/server/listener_stats.h
- test/common/http/codec_client_test.cc
- test/common/network/connection_impl_test.cc
- test/common/network/listener_impl_test.cc
- test/extensions/network/dns_resolver/cares/dns_impl_test.cc
- test/extensions/resource_monitors/injected_resource/injected_resource_monitor_integration_test.cc
- test/extensions/transport_sockets/tls/ssl_socket_test.cc
- test/mocks/network/mocks.h
Commit Message: Follow up adding a histogram of connections accepted per socket event.
Additional Description: https://github.com/envoyproxy/envoy/pull/27773#discussion_r1222002852
Risk Level: low / med
Testing: unit, integration
> Listener: Connections accepted per socket event histogram.

- tools/dependency/cve.yaml
fix #28038 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> deps: Ignore CVE-2023-32732 in scanner

- test/extensions/matching/input_matchers/cel_matcher/cel_matcher_test.cc
- test/extensions/matching/input_matchers/cel_matcher/cel_matcher_test.h
Test CEL matching on xDS attributes -- route metadata
> cel_matcher: matching on xds route metadata

- docs/root/configuration/operations/overload_manager/overload_manager.rst
Commit Message: Docs: Add stats doc for load shed points.
Additional Description: See for stat https://github.com/envoyproxy/envoy/blob/1090a531f523ff8c6f1647e80d2e57194af8ea4d/source/server/overload_manager_impl.cc#L313
Risk Level: na
Testing: na
> Docs: Add stats doc for load shed points.

- source/common/common/utility.cc
- source/common/common/utility.h
- source/common/stream_info/filter_state_impl.cc
- source/common/upstream/cds_api_impl.cc
- source/common/upstream/cluster_manager_impl.cc
- source/extensions/clusters/eds/eds.cc
- source/extensions/config_subscription/grpc/grpc_mux_impl.cc
Commit Message: Clean up: Use contains where count is being used as contains.
Testing: n/a
Platform Specific Features:n/a
> Clean up: Use contains where count is being used as contains.

- mobile/.bazelrc
Hopefully fix #27459 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile/ci: Use async mode for BEP uploads

- .github/workflows/envoy-sync.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/actions: Fix sync dispatch action

- ci/Dockerfile-envoy
- ci/docker_ci.sh
- ci/test/docker/linux/dev/main
- ci/test/docker/linux/dev/other
- ci/test/docker/linux/dev/release
- ci/test/docker/linux/dev/tag
- ci/test/docker/linux/nondev/main
- ci/test/docker/linux/nondev/other
- ci/test/docker/linux/nondev/release
- ci/test/docker/linux/nondev/tag
Fix #28100 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docker/ci: Fix debug images

- changelogs/current.yaml
Commit Message: Supply change note for https://github.com/envoyproxy/envoy/pull/28102.
Risk Level:
Testing:
Docs Changes:
> docs: add changelog to #28102

- docs/root/configuration/http/http_filters/golang_filter.rst
- examples/golang/simple/go.mod
Risk Level:
Testing:
Docs Changes:
Release Notes:
> doc: add API compatibility section for golang filter.

- api/envoy/extensions/filters/http/ext_proc/v3/BUILD
- api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
- api/envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto
- api/envoy/service/ext_proc/v3/BUILD
- api/envoy/service/ext_proc/v3/external_processor.proto
- source/extensions/extensions_metadata.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Turn ext_proc into API stable.

- test/common/http/header_map_impl_test.cc
This PR seeks to improve this issue: #1963
Commit Message: test coverage added for LowerCaseString class
Additional Description: a test added to header_map_impl_test
Testing: Added Unit test
> test coverage added for LowerCaseString class

- test/extensions/filters/network/common/fuzz/network_readfilter_fuzz_test.cc
Commit Message: protobuf mutator utility functions cleanup - followup on #27580
In #27580 the fuzzer used libprotobuf-mutator internal functions to serialize/deserialize a protobuf test case.
This PR calls the protobuf functions directly instead.
Risk Level: low - fuzz tests only
Testing: N/A
> fuzz: protobuf mutator utility functions cleanup

- source/common/upstream/load_balancer_impl.h
Commit Message: Efficiency: Compact HostSource.
Additional Description:  Goes from 12B -> 8B. The enum needs fewer bits to represent the number of states (5) and the priority is limited to be <=128 by pgv see: https://github.com/envoyproxy/envoy/blob/83d633d9ff0f0a9ea550ffda2fef20f7f9f3ede1/api/envoy/config/endpoint/v3/endpoint_components.proto#L202
Testing: na
> Efficiency: Compact HostSource.

- docs/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docs/config: Exclude tap config from server test

- test/extensions/resource_monitors/injected_resource/injected_resource_monitor_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/tests: Disable flakey resource monitor test

- source/common/tcp/BUILD
- source/common/tcp/async_tcp_client_impl.cc
- source/common/tcp/async_tcp_client_impl.h
- test/common/tcp/async_tcp_client_impl_test.cc
- test/integration/tcp_async_client_integration_test.cc
Add useful async connection metrics to cluster info.
Testing:
Docs Changes:
Release Notes:
> tcp: add metrics to async client

- ci/do_ci.sh
> Workaround dep checker issue again

- ci/do_ci.sh
This reverts commit 00faa843f839c35531c61ed0d9e79490eb333e36.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Revert "Workaround dep checker issue again (#28269)"

- source/extensions/filters/network/thrift_proxy/router/shadow_writer_impl.cc
- source/extensions/filters/network/thrift_proxy/router/shadow_writer_impl.h
Refactor to favor type-safe ThreadLocal::TypedSlot
Testing: existing unit test
> thrift_proxy: favor type-safe ThreadLocal::TypedSlot

- source/extensions/filters/http/ext_authz/ext_authz.cc
> ext_authz: fix a trace log message

- contrib/golang/filters/http/source/cgo.cc
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/basic/filter.go
fix #28098
Risk Level:
Testing:
Docs Changes:
Release Notes:
> golang http filter: sendLocalReply support response headers.

- source/extensions/grpc_credentials/example/BUILD
> Remove unused visibility rule

- contrib/golang/common/go/api/filter.go
- contrib/golang/filters/http/source/go/pkg/http/passthrough.go
- contrib/golang/filters/http/test/test_data/basic/filter.go
- contrib/golang/filters/http/test/test_data/echo/filter.go
- contrib/golang/filters/http/test/test_data/routeconfig/filter.go
- examples/golang/simple/filter.go
Two advantages:
1. no longer need to copy dummy implementations in every plugins
2. add new API in StreamFilter won't break existing plugins
Commit Message: provide default stream filter impl
Testing: use current tests is enough
Docs Changes:
Release Notes:
> golang filter: provide default stream filter impl

- bazel/coverage/collect_cc_coverage.sh
- bazel/coverage/fuzz_coverage_wrapper.sh
- dont use `-x` as it spews 1000s of lines of useless info (and not much else)
- do use `-e` as otherwise fails fail silently
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Improve bash flags for coverage

- api/contrib/envoy/extensions/network/connection_balance/dlb/v3alpha/dlb.proto
- contrib/network/connection_balance/dlb/source/connection_balancer_impl.cc
- contrib/network/connection_balance/dlb/source/connection_balancer_impl.h
- contrib/network/connection_balance/dlb/test/BUILD
- contrib/network/connection_balance/dlb/test/config_test.cc
Commit Message: Support fallback to pure software connection balance if any error occurs.
Testing: Add
> dlb: support fallback

- .bazelrc
- bazel/io_opentracing_cpp.patch
- ci/do_ci.sh
- source/common/common/logger.h
- source/extensions/common/aws/signer_impl.cc
- source/extensions/common/aws/utility.cc
- source/extensions/filters/common/rbac/matchers/upstream_ip_port.cc
- source/extensions/filters/network/mongo_proxy/codec_impl.h
- source/extensions/filters/network/mongo_proxy/proxy.cc
- source/server/hot_restarting_base.cc
- test/common/access_log/access_log_impl_test.cc
- test/extensions/filters/http/aws_lambda/aws_lambda_filter_integration_test.cc
- test/extensions/filters/http/bandwidth_limit/filter_test.cc
- test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
- test/extensions/filters/http/rbac/rbac_filter_test.cc
- test/extensions/filters/http/tap/tap_filter_integration_test.cc
- test/extensions/filters/network/local_ratelimit/local_ratelimit_test.cc
- test/extensions/filters/network/rbac/config_test.cc
- test/extensions/filters/network/rbac/filter_test.cc
- test/extensions/filters/network/thrift_proxy/router_test.cc
- test/extensions/filters/network/thrift_proxy/trds_integration_test.cc
- test/extensions/tracers/opentelemetry/opentelemetry_tracer_impl_test.cc
- test/fuzz/validated_input_generator.h
- test/test_common/utility.h
First step for enabling C++20. For now just enabled for compile-options build to prevent bit rot. No effect on production binary.
Part of #27757
> C++20 build config

- test/per_file_coverage.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> coverage: Lower threshold for `transport_sockets`

- bazel/envoy_test.bzl
- test/server/BUILD
- test/server/config_validation/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
> fuzz/coverage: Increase sharding for timing out tests

- source/extensions/filters/network/thrift_proxy/router/router.h
- source/extensions/filters/network/thrift_proxy/router/shadow_writer_impl.cc
- source/extensions/filters/network/thrift_proxy/router/shadow_writer_impl.h
- test/extensions/filters/network/thrift_proxy/mocks.h
- test/extensions/filters/network/thrift_proxy/shadow_writer_test.cc
simple change
Testing: existing unit
> thrift_proxy: favor OptRef than reference_wrapper

- distribution/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
> distribution/binary: Fix version/platform in binary names

- distribution/BUILD
Fix #28146 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.26] distribution/binary: Fix version/platform in binary names (#28402)

- .azure-pipelines/env.yml
- .azure-pipelines/stage/publish.yml
Fix #28403
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.26] release/publishing: Fix `dry-run` conditions (#28405)

- .azure-pipelines/env.yml
- .azure-pipelines/stage/publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> release/publishing: Fix `dry-run` conditions

- .azure-pipelines/stage/publish.yml
- ci/do_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/release: Use GCP to up/download signed binaries

- .azure-pipelines/bazel.yml
- .azure-pipelines/stage/macos.yml
- .azure-pipelines/stage/verify.yml
- .azure-pipelines/stage/windows.yml
- ci/run_clang_tidy.sh
- ci/run_envoy_docker.sh
- ci/setup_cache.sh
- docs/build.sh
removes/consolidates CI env vars, and makes the names non-azp specific
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Assorted cleanups

- source/extensions/filters/http/oauth2/filter.cc
- source/extensions/filters/http/oauth2/filter.h
Commit Message: add debug logs in oauth2 proxy
Additional Description: add debug logs in oauth2 proxy to aid in debugging
Testing: N/A
> add debug logs in oauth2 proxy

- .github/actions/do_ci/action.yml
- .github/workflows/_ci.yml
- Print diskspace at beginning/end of jobs
- Add diskspace hack for jobs that need it
- Add pre/post steps
- Add `env` parser for reusable workflows
- Separate `do_ci` to an action so it can be reused more easily
Risk Level:
Testing:
Docs Changes:
Release Notes:
> do/ci: Improve github `workflow_call`

- test/per_file_coverage.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> coverage: Lower `source/common/quic` to fix permafail (93.3)

- .github/actions/verify/examples/setup/action.yml
- .github/workflows/_env.yml
- .github/workflows/_stage_verify.yml
- .github/workflows/envoy-publish.yml
- .github/workflows/workflow-complete.yml
- Separate verify to a stage file
- Fix disassociation of check status in PRs (hopefully)
- Attempt to restrict access based on `[bot]` trigger
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/github: Further workflow improvements

- ci/verify_examples.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> examples: Warn on `golang-network` flake

- .github/workflows/envoy-publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/github: Minor fix for untrusted code

- .github/actions/env/action.yml
- .github/workflows/_env.yml
- .github/workflows/_stage_verify.yml
- .github/workflows/envoy-publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/github: Fix repo contexts /cont

- .github/workflows/_workflow-start.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/github: Minor fix for triggering check status

- .azure-pipelines/stage/publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/github: Shift azp trigger to after publishing success

- .azure-pipelines/stage/prechecks.yml
- .azure-pipelines/stage/publish.yml
- .azure-pipelines/stages.yml
- .github/actions/publish/release/setup/action.yml
- .github/workflows/_stage_publish.yml
- .github/workflows/envoy-publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/github: Shift (some) publish jobs to github

- .azure-pipelines/stage/publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Free some diskspace for Docker caching

- .azure-pipelines/pipelines.yml
- .azure-pipelines/stage/prechecks.yml
- .azure-pipelines/stage/publish.yml
- .azure-pipelines/stages.yml
- .github/actions/publish/release/setup/action.yml
- .github/workflows/_stage_publish.yml
- .github/workflows/_workflow-start.yml
- .github/workflows/envoy-publish.yml
- test/common/network/BUILD
- test/common/network/io_socket_handle_impl_integration_test.cc
- test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
- test/extensions/network/dns_resolver/cares/BUILD
- test/extensions/network/dns_resolver/cares/dns_impl_test.cc
- test/extensions/network/dns_resolver/getaddrinfo/BUILD
- test/extensions/network/dns_resolver/getaddrinfo/getaddrinfo_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.26] Backport stack (2)

- .github/actions/publish/release/setup/action.yml
- .github/workflows/_stage_publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Fix for download publishing paths

- .azure-pipelines/env.yml
- .azure-pipelines/stage/publish.yml
- .azure-pipelines/stages.yml
- Remove unused azp var
- Dont trigger in non-envoy repos
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Cleanups for publishing trigger

- source/common/upstream/upstream_impl.cc
- source/common/upstream/upstream_impl.h
- test/integration/stats_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> fix clang tidy and bump the memory limit per host to reduce flakes

- ci/verify_examples.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> examples: Warn dont error on `wasm-cc` sandbox fail

- ci/verify_examples.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> examples/ci: Warn, dont error on `websocket` example

- .azure-pipelines/env.yml
This is a better tested version of what #28535 hoped to achieve
Fix #26830 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Only trigger release CI if explicitly set

- .azure-pipelines/env.yml
- .github/actions/env/action.yml
- .github/workflows/_env.yml
- .github/workflows/_workflow-start.yml
- .github/workflows/envoy-publish.yml
- ci/verify_examples.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.26] Backport stack (4)

- bazel/protobuf.patch
Partial fix for #28536 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> protobuf: Quieten unhelpful logging (DEBUG def)

- .github/workflows/_ci.yml
- .github/workflows/_env.yml
- .github/workflows/envoy-publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/github: Fix workflow concurrency

- .azure-pipelines/stage/checks.yml
Related to #28566 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Temporarily disable clang-tidy

- .github/actions/publish/release/setup/action.yml
- .github/workflows/_cache_docker.yml
- .github/workflows/_ci.yml
- .github/workflows/_env.yml
and update action dep to resolve ci warning
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/github: Improve display names

- bazel/cel-cpp.patch
Risk Level:
Testing:
Docs Changes:
Release Notes:
> cel-cpp: Quieten unhelpful logging

- test/server/BUILD
- test/server/config_validation/BUILD
This reverts commit 805a425cdb662702d741f010c12525e4669870d5.
and adjust limits
Risk Level:
Testing:
Docs Changes:
Release Notes:
> fuzz/coverage: Adjust test sizing

- changelogs/current.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> changelogs: Add arm64 FIPS build

- .github/actions/publish/release/setup/action.yml
- .github/workflows/_cache_docker.yml
- .github/workflows/_ci.yml
- .github/workflows/_env.yml
- .github/workflows/envoy-publish.yml
- ci/do_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.26] Backport stack (5)

- source/extensions/clusters/original_dst/original_dst_cluster.cc
- source/extensions/clusters/original_dst/original_dst_cluster.h
Commit Message: fixes an issue found during testing. We need to follow up with an integration test once I'm back.
Testing: yes
> original_dst cluster: follow up to #28453

- contrib/golang/filters/http/source/golang_filter.cc
Commit Message: fix typo in log msg
Testing:
Docs Changes:
Release Notes:
> golang filter: fix typo in log msg

- contrib/golang/common/dso/dso.cc
- contrib/golang/common/dso/dso.h
- contrib/golang/common/dso/test/mocks.h
- contrib/golang/common/dso/test/test_data/simple.go
- contrib/golang/common/go/api/api.h
- contrib/golang/common/go/api/capi.go
- contrib/golang/common/go/api/filter.go
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/go/pkg/http/filter.go
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
- contrib/golang/filters/http/test/test_data/basic/filter.go
- contrib/golang/filters/network/source/cgo.cc
- contrib/golang/filters/network/source/go/pkg/network/capi.go
- contrib/golang/filters/network/source/go/pkg/network/filter.go
- contrib/golang/filters/network/source/go/pkg/network/shim.go
- contrib/golang/filters/network/source/golang.cc
- contrib/golang/filters/network/source/golang.h
- contrib/golang/filters/network/test/filter_test.cc
- examples/golang-network/simple/filter.go
ref: https://github.com/envoyproxy/envoy/issues/25906
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Golang L4 Filter: Support Get/Set FilterState

- .github/workflows/_env.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/github: Fix workflow association

- changelogs/current.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> changelogs: Add CVE info to changelogs

- .github/actions/env/action.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/release: Fix dev version detection

- changelogs/current.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> changelogs: Pre-release cleanups

- bazel/envoy_library.bzl
- bazel/external/quiche.BUILD
- source/common/common/BUILD
Remove implicit dependencies on absl/container from every target and just add them to targets that use them.
> Remove implicit deps on absl/container

- source/common/common/logger.h
- source/common/http/conn_manager_impl.cc
- source/common/http/http1/codec_impl.cc
- source/common/http/http2/codec_impl.cc
- source/common/network/tcp_listener_impl.cc
- source/server/overload_manager_impl.cc
- test/common/common/log_macros_test.cc
- test/server/overload_manager_impl_test.cc
Commit Message: Reduce log spam of load shed points if not configured. 
Additional Description: LOG_ONCE_IF in the various callsites so each point gets logged about at most once.
> Reduce log spam of load shed points if not configured. 

- OWNERS.md
Risk Level:
Testing:
Docs Changes:
Release Notes:
> project: Add @nezdolik and @botengyao to the security team

- source/common/common/logger.h
Risk Level:
Testing:
Docs Changes:
Release Notes:
> logger: Minor comment/copy edit to blow coverage cache

- source/common/config/utility.cc
- source/common/config/utility.h
- test/common/config/utility_test.cc
Commit Message: utility: cleanup - remove unused code
Removing unused code.
Testing: N/A
> utility: cleanup - remove unused code

- test/integration/BUILD
- test/per_file_coverage.sh
Fix #28695 
Create #28723 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> coverage: Disable hotrestart test

- test/extensions/filters/http/ext_proc/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ext_proc/test: Increase shards to prevent timeouts

- .azure-pipelines/stages.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Pass through `--nocache_test_results` correctly on scheduled runs

- source/server/active_udp_listener.cc
Commit Message: Cleanup ActiveUdpListenerBase dispatcher call
Additional Description: dispatcher accepts single-use lambdas now, so we no longer need to wrap captured arguments in shared_ptr.
Risk Level: Low, should be a no-op.
Testing: Covered by existing tests.
> Cleanup ActiveUdpListenerBase dispatcher call

- bazel/protobuf.patch
- bazel/repository_locations.bzl
Risk Level:
Testing:
Docs Changes:
Release Notes:
> deps: Bump `com_google_protobuf` -> 23.4

- .azure-pipelines/stage/prechecks.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Increase precheck/publishing timeout

- test/integration/stats_integration_test.cc
Workaround for issue raised in #28793 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> test/ci: Workaround cluster host memory issue

- .azure-pipelines/bazel.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Dont upload azp test attachments

- source/common/router/router.cc
- source/common/router/router.h
Hope the existing name is not intentional :-)
Commit Message: rename function
Testing: N/A
> router: minor function rename

- .azure-pipelines/stage/checks.yml
- .bazelrc
- bazel/envoy_test.bzl
- changelogs/current.yaml
- source/extensions/filters/network/connection_limit/connection_limit.cc
- test/common/http/BUILD
- test/common/http/http2/BUILD
- test/extensions/clusters/redis/BUILD
- test/extensions/filters/http/buffer/BUILD
- test/extensions/filters/http/cache/BUILD
- test/extensions/filters/http/csrf/BUILD
- test/extensions/filters/http/custom_response/BUILD
- test/extensions/filters/http/ext_proc/BUILD
- test/extensions/filters/http/fault/BUILD
- test/extensions/filters/http/file_system_buffer/BUILD
- test/extensions/filters/http/grpc_field_extraction/BUILD
- test/extensions/filters/http/health_check/BUILD
- test/extensions/filters/http/jwt_authn/BUILD
- test/extensions/filters/http/kill_request/BUILD
- test/extensions/filters/http/rbac/BUILD
- test/extensions/filters/http/tap/BUILD
- test/extensions/filters/http/wasm/BUILD
- test/extensions/filters/network/redis_proxy/BUILD
- test/extensions/filters/network/thrift_proxy/BUILD
- test/extensions/listener_managers/listener_manager/BUILD
- test/extensions/transport_sockets/tls/BUILD
- test/integration/BUILD
- test/per_file_coverage.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.27] Backport stack

- SECURITY.md
Additional Description: Docs were out of sync with reality, and other notes about security releases in RELEASES.md. 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docs: correct error in SECURITY.md

- contrib/generic_proxy/filters/network/source/BUILD
- contrib/generic_proxy/filters/network/source/interface/proxy_config.h
- contrib/generic_proxy/filters/network/source/proxy.cc
- contrib/generic_proxy/filters/network/source/proxy.h
- contrib/generic_proxy/filters/network/source/stats.h
- contrib/generic_proxy/filters/network/test/integration_test.cc
- contrib/generic_proxy/filters/network/test/proxy_test.cc
Commit Message: initial commit for generic proxy stats
Additional Description: N.A.
Testing:
Docs Changes:
Release Notes:
> initial commit for generic proxy stats

- source/extensions/load_balancing_policies/subset/subset_lb.h
Risk Level:
Testing:
Docs Changes:
Release Notes:
> minor cleanup: remove invalid function declaration

- changelogs/current.yaml
- source/extensions/filters/network/common/redis/supported_commands.h
- source/extensions/filters/network/redis_proxy/command_splitter_impl.cc
- test/extensions/filters/network/redis_proxy/command_splitter_impl_test.cc
Replying locally is probably fine.
Fixes: #28839
Signed-off-by: Raul Gutierrez Segales <rsegales@nvidia.com>
> [redis] implement time command

- source/extensions/config_subscription/grpc/grpc_mux_impl.h
- test/extensions/config_subscription/grpc/grpc_mux_impl_test.cc
Commit Message: eds-caching: removing SotW EDS cached resource on last subscription
#28273 introduced the support of EDS caching in the gRPC muxes.
However, there's a bug when multiple SotW subscriptions are added to the same resource, and the resource is removed once the first subscription is deleted. This PR fixes the issue by removing the resource from the cache only after the last subscription is removed.
Risk Level: Low - code not used yet (already runtime guarded)
Testing: Added an appropriate unit test.
> eds-caching: removing SotW EDS cached resource on last subscription

- docs/root/intro/arch_overview/http/upgrades.rst
Commit Message: docs: fix file name in docs/root/intro/arch_overview/http/upgrades.rst
Testing: Check sample works and check other file names are valid
Platform Specific Features:No
> docs: fix file name in upgrades.rst

- test/integration/BUILD
Lower the overall running time of this test
> Add more shards to the default_header_validator_integration_test

- changelogs/current.yaml
- source/extensions/filters/network/common/redis/supported_commands.h
Fixes #28845.
Signed-off-by: Raul Gutierrez Segales <rsegales@nvidia.com>
> [redis] add support for LMOVE

- source/common/protobuf/utility.cc
- test/common/protobuf/utility_test.cc
Commit Message: fix possible crash of admin /config_dump
Testing: unit.
> fix possible crash of admin `/config_dump`

- ci/run_envoy_docker.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docker/ci: Add support for running cross platform build image

- ci/do_ci.sh
this is causing various prs to fail - eg #28892 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci: Add clang toolchain for python dep compilation

- .github/workflows/mobile-perf.yml
- mobile/.bazelrc
Follow up from #28856 and removal of duplicate flag
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile/ci: Minor cleanups

- .github/workflows/commands.yml
- .github/workflows/envoy-publish.yml
- .github/workflows/envoy-sync.yml
- .github/workflows/mobile-release.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/github: Fix workflow conditions

- .azure-pipelines/bazel.yml
- .azure-pipelines/cached.yml
- .azure-pipelines/stage/publish.yml
- .azure-pipelines/stage/verify.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> arm64/ci: Use small VMs for publishing/verify jobs

- contrib/golang/common/go/api/logger.go
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/go/pkg/http/filter.go
- contrib/golang/filters/http/test/test_data/basic/config.go
- contrib/golang/filters/http/test/test_data/basic/filter.go
- examples/golang-http/simple/filter.go
Commit Message: add more log helpers and tweak log fmt
Docs Changes:
Release Notes:
> golang filter: add more log helpers and tweak log fmt

- bazel/envoy_library.bzl
- bazel/external/quiche.BUILD
- contrib/kafka/filters/network/source/mesh/BUILD
- source/common/common/BUILD
- source/common/html/BUILD
- source/extensions/clusters/redis/BUILD
> Remove implicit dep on absl/strings

- CONTRIBUTING.md
- EXTENSION_POLICY.md
> Clarify extension removal policy

- contrib/kafka/filters/network/source/mesh/BUILD
- envoy/buffer/BUILD
- envoy/common/BUILD
- envoy/protobuf/BUILD
- source/common/common/BUILD
- source/common/common/hex.cc
- source/common/common/logger.cc
- source/common/filesystem/BUILD
- source/extensions/filters/http/admission_control/evaluators/BUILD
- source/server/BUILD
- test/server/config_validation/BUILD
- test/server/config_validation/xds_verifier.cc
- test/server/config_validation/xds_verifier.h
This makes it more explicit what build targets actually need it.
> Separate exception.h into a dedicated build target

- source/common/upstream/cluster_factory_impl.h
- source/extensions/clusters/aggregate/cluster.cc
- source/extensions/clusters/aggregate/cluster.h
- source/extensions/clusters/dynamic_forward_proxy/cluster.cc
- source/extensions/clusters/dynamic_forward_proxy/cluster.h
- source/extensions/clusters/redis/redis_cluster.cc
- source/extensions/clusters/redis/redis_cluster.h
- test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc
- test/extensions/clusters/redis/redis_cluster_test.cc
- test/integration/clusters/custom_static_cluster.h
> cluster: changing createClusterWithConfig to take a statusOr 

- .bazelrc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> bazel/coverage: Increase buffer memory

- mobile/bazel/apple.bzl
- mobile/test/swift/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile/ci: Increase size of timeouting swift test

- .github/dependabot.yml
- contrib/golang/common/dso/dso.cc
- contrib/golang/common/dso/dso.h
- contrib/golang/common/dso/libgolang.h
- contrib/golang/common/dso/test/mocks.h
- contrib/golang/common/dso/test/test_data/simple.go
- contrib/golang/common/go/api/filter.go
- contrib/golang/filters/http/source/go/pkg/http/shim.go
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/processor_state.cc
- contrib/golang/filters/http/source/processor_state.h
- contrib/golang/filters/http/test/BUILD
- contrib/golang/filters/http/test/golang_filter_fuzz_test.cc
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/access_log/BUILD
- contrib/golang/filters/http/test/test_data/access_log/config.go
- contrib/golang/filters/http/test/test_data/access_log/filter.go
- contrib/golang/filters/http/test/test_data/access_log/go.mod
- contrib/golang/filters/http/test/test_data/basic/filter.go
Commit Message: add OnLog
Additional Description: TODO: pass AccessLogType & allow logging in the middle
Docs Changes:
Release Notes:
> golang filter: add OnLog

- .azure-pipelines/stage/checks.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/coverage: Temprorarily disable coverage requirement

- source/extensions/transport_sockets/tls/ssl_socket.cc
> tls: make error message more concise

- .github/workflows/commands.yml
- repokitteh.star
Fix #28934 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/retest: Update retest to add AZP

- CODEOWNERS
Risk Level:
Testing:
Docs Changes:
Release Notes:
> add spacewander & antJack to go extension code owner

- .github/workflows/commands.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/retest: Minor fix

- .azure-pipelines/pipelines.yml
- ci/do_ci.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/cache: Ensure failure on cache non-fetch

- RELEASES.md
giving credit to folks on the last and upcoming security release.  Thanks so much, all
> docs: update releases doc

- .azure-pipelines/docker/load_caches.sh
- .azure-pipelines/stage/checks.yml
also adds a cleanup for the load_cache script
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/checks: Use self-hosted x64 small VMs

- .azure-pipelines/stage/verify.yml
verify job uses the `bazel.yml` template
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/verify: Use bazel.yml

- .azure-pipelines/bazel.yml
- .azure-pipelines/docker/load_caches.sh
- .azure-pipelines/stage/checks.yml
- .azure-pipelines/stage/publish.yml
- .azure-pipelines/stage/verify.yml
Syncing CI
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.27] Backport stack (3)

- bazel/repository_locations.bzl
Risk Level:
Testing:
Docs Changes:
Release Notes:
> RLQS: Fix CEL dep in bzl

- contrib/golang/filters/network/source/go/pkg/network/capi.go
- contrib/golang/router/cluster_specifier/source/go/pkg/cluster_specifier/capi_impl.go
fix: https://github.com/envoyproxy/envoy/issues/29168
ref: https://github.com/envoyproxy/envoy/pull/28722/files
Risk Level:
Testing:
Docs Changes:
Release Notes:
> fix issue 29168: add the real api.h file into the include path

- bazel/repository_locations.bzl
Fix #28973 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> deps: Bump `com_github_jbeder_yaml_cpp` -> 0.8.0

- bazel/protobuf.patch
Risk Level:
Testing:
Docs Changes:
Release Notes:
> build/ci: Quieten windows warnings

- .azure-pipelines/stage/linux.yml
- .azure-pipelines/stages.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/x64: Use small VM for x64 build

- test/extensions/matching/input_matchers/cel_matcher/cel_matcher_test.cc
- test/extensions/matching/input_matchers/cel_matcher/cel_matcher_test.h
Risk Level:
Testing:
Docs Changes:
Release Notes:
> cel_matcher:  Validate match on dynamic metadata

- OWNERS.md
@KBaichoo and @tyxia have been doing fantastic behind-the-scenes work securing Envoy, now officially welcoming them to Envoy's security team.  Thanks for all the help thusfar and going forwards!
> setec: welcome Kevin and Tianyu!

- examples/brotli/docker-compose.yaml
- examples/front-proxy/docker-compose.yaml
- examples/shared/envoy/Dockerfile
Risk Level:
Testing:
Docs Changes:
Release Notes:
> examples: Fix healthcheck recipe

- .azure-pipelines/env.yml
- examples/front-proxy/docker-compose.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> examples: Ensure CI is run for PRs and fix

- OWNERS.md
Risk Level:
Testing:
Docs Changes:
Release Notes:
> repo: Add @doujiang24 as senior Golang extension maintainer

- contrib/golang/common/go/api/filter.go
- contrib/golang/filters/network/test/test_data/filter.go
- examples/golang-network/simple/filter.go
Commit Message: golang filter: provide default ds/us filter impl
Additional Description: For the same reason in https://github.com/envoyproxy/envoy/pull/28312
Testing:
Docs Changes:
Release Notes:
> golang filter: provide default ds/us filter impl

- api/envoy/data/tap/v3/http.proto
- api/envoy/extensions/filters/http/tap/v3/tap.proto
- changelogs/current.yaml
- source/extensions/common/tap/BUILD
- source/extensions/common/tap/tap.h
- source/extensions/filters/http/tap/BUILD
- source/extensions/filters/http/tap/tap_config.h
- source/extensions/filters/http/tap/tap_config_impl.cc
- source/extensions/filters/http/tap/tap_config_impl.h
- source/extensions/filters/http/tap/tap_filter.cc
- source/extensions/filters/http/tap/tap_filter.h
- test/extensions/filters/http/tap/BUILD
- test/extensions/filters/http/tap/common.h
- test/extensions/filters/http/tap/tap_config_impl_test.cc
- test/extensions/filters/http/tap/tap_filter_integration_test.cc
- test/extensions/filters/http/tap/tap_filter_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Add caught time stamp for http tap filter

- ci/mac_ci_setup.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mac/ci: Dont reinstall bazelisk

- .github/dependabot.yml
- contrib/golang/common/go/api/api.h
- contrib/golang/common/go/api/capi.go
- contrib/golang/common/go/api/filter.go
- contrib/golang/filters/http/source/cgo.cc
- contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
- contrib/golang/filters/http/source/go/pkg/http/filter.go
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
- contrib/golang/filters/http/test/BUILD
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/basic/config.go
- contrib/golang/filters/http/test/test_data/basic/filter.go
- contrib/golang/filters/http/test/test_data/metric/BUILD
- contrib/golang/filters/http/test/test_data/metric/config.go
- contrib/golang/filters/http/test/test_data/metric/filter.go
- contrib/golang/filters/http/test/test_data/metric/go.mod
Commit Message: go http extension add record metric api
Testing: intergation test
> go http extension add record metric api

- .azure-pipelines/stage/checks.yml
- .azure-pipelines/stage/linux.yml
- .azure-pipelines/stage/macos.yml
- .azure-pipelines/stage/prechecks.yml
- .azure-pipelines/stage/publish.yml
- .azure-pipelines/stage/verify.yml
- .azure-pipelines/stage/windows.yml
as we no longer have so much of a contention issue with azp-hosted agents, it makes sense to use them for these tasks
Risk Level:
Testing:
Docs Changes:
Release Notes:
> azp/ci: Use ms-hosted agents for confirmation

- .azure-pipelines/stage/publish.yml
- .azure-pipelines/stage/verify.yml
- .azure-pipelines/stage/windows.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> azp/ci: Prevent empty uploads

- changelogs/current.yaml
- envoy/runtime/runtime.h
- source/common/runtime/runtime_features.cc
- source/server/config_validation/server.cc
- source/server/config_validation/server.h
- source/server/server.cc
- source/server/server.h
- test/common/runtime/runtime_impl_test.cc
- test/integration/filter_integration_test.cc
- test/integration/multi_envoy_test.cc
- test/integration/protocol_integration_test.cc
- test/server/config_validation/server_test.cc
- test/test_common/test_runtime.h
> runtime: removing envoy.restart_features.remove_runtime_singleton

- source/common/router/router.h
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Initialize request_vcluster_ pointer as {} to avoid dangling pointer problem

- source/common/upstream/cluster_factory_impl.cc
- source/common/upstream/cluster_factory_impl.h
- source/extensions/clusters/eds/eds.cc
- source/extensions/clusters/eds/eds.h
- source/extensions/clusters/logical_dns/logical_dns_cluster.cc
- source/extensions/clusters/logical_dns/logical_dns_cluster.h
- source/extensions/clusters/original_dst/original_dst_cluster.cc
- source/extensions/clusters/original_dst/original_dst_cluster.h
- source/extensions/clusters/static/static_cluster.cc
- source/extensions/clusters/static/static_cluster.h
- source/extensions/clusters/strict_dns/strict_dns_cluster.cc
- source/extensions/clusters/strict_dns/strict_dns_cluster.h
- test/common/upstream/cluster_factory_impl_test.cc
- test/common/upstream/upstream_impl_test.cc
- test/extensions/clusters/logical_dns/logical_dns_cluster_test.cc
- test/extensions/clusters/original_dst/original_dst_cluster_test.cc
> cluster: removing exceptions from cluster creation

- .azure-pipelines/stage/windows.yml
windows has a never-expiring cache, so we should fix
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/windows: Fix cache key

- .github/workflows/_ci.yml
- .github/workflows/_env.yml
- .github/workflows/_workflow-start.yml
- .github/workflows/check-deps.yml
- .github/workflows/codeql-daily.yml
- .github/workflows/codeql-push.yml
- .github/workflows/depsreview.yml
- .github/workflows/mobile-android_build.yml
- .github/workflows/mobile-android_tests.yml
- .github/workflows/mobile-asan.yml
- .github/workflows/mobile-cc_tests.yml
- .github/workflows/mobile-compile_time_options.yml
- .github/workflows/mobile-core.yml
- .github/workflows/mobile-coverage.yml
- .github/workflows/mobile-docs.yml
- .github/workflows/mobile-format.yml
- .github/workflows/mobile-ios_build.yml
- .github/workflows/mobile-ios_tests.yml
- .github/workflows/mobile-perf.yml
- .github/workflows/mobile-release.yml
- .github/workflows/mobile-release_validation.yml
- .github/workflows/mobile-traffic_director.yml
- .github/workflows/mobile-tsan.yml
- .github/workflows/pr_notifier.yml
- .github/workflows/release_branch.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> github/ci: Bump `actions/checkout` -> v4

- source/extensions/common/wasm/ext/BUILD
> Remove unused load

- bazel/repository_locations.bzl
Fix #29375 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> deps: Bump `org_brotli` -> 1.1.0

- source/extensions/extensions_metadata.yaml
- tools/base/requirements.in
- tools/base/requirements.txt
with added `status_upstream` setting
Risk Level:
Testing:
Docs Changes:
Release Notes:
> deps/tooling: Bump `envoy.code.check` -> 0.5.5

- ci/mac_ci_setup.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mac/ci: Retry flakey bazel invokation

- ci/do_ci.sh
- tools/local_fix_format.sh
This will make this script _a lot_ faster with the caveat that the first time you run bazel will have to build the build tools for you
Risk Level:
Testing:
Docs Changes:
Release Notes:
> tools/ci: Optimize local formatter

- tools/local_fix_format.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> tools: Add option to skip bazel for format fix

- test/mocks/server/BUILD
> Use short package local dependencies

- api/envoy/extensions/bootstrap/internal_listener/v3/BUILD
- api/envoy/extensions/bootstrap/internal_listener/v3/internal_listener.proto
- source/extensions/extensions_metadata.yaml
Internal listener extensions had been there for a while. It's time to change them to stable.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Changing the internal_listener related extensions to stable.

- mobile/third_party/rbe_configs/config/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile/bazel: Fix platform image to use mobile

- source/server/config_validation/server.cc
- source/server/server.cc
- source/server/utils.cc
- source/server/utils.h
- test/server/utils_test.cc
- tools/code_format/config.yaml
> server: making LogFormat return absl status

- test/extensions/filters/udp/udp_proxy/udp_proxy_integration_test.cc
Additional Description: deflaking integration tests by ``waitingForCounterEq`` rather than ``EXPECT_EQ()``.
> udp_proxy: deflake integration tests

- contrib/golang/filters/http/source/golang_filter.cc
- tools/code_format/check_format.py
Commit Message: style: ensure FALLTHRU is used everywhere 
Testing:
Docs Changes:
Release Notes:
> style: ensure FALLTHRU is used everywhere

- support/hooks/pre-push
- tools/code_format/check_format.py
also contains fix for issue found by @ravenblackx 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> git/hooks: Prevent pre-push from looping format check

- docs/root/configuration/listeners/listener_filters/tls_inspector.rst
Risk Level:
Testing:
Docs Changes:
Release Notes:
> nit: make tls_inspect doc consistant

- source/extensions/listener_managers/listener_manager/active_tcp_socket.h
Risk Level:
Testing:
Docs Changes:
Release Notes:
> listener: fix listener filter comment

- contrib/dlb/test/config_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> contrib/format: Fix clang-format issue

- contrib/golang/filters/http/source/go/pkg/http/filtermanager.go
- contrib/golang/filters/http/test/golang_integration_test.cc
Docs Changes:
Release Notes:
Fixes #29332
> golang filter: log if wrong plugin name is configured

- contrib/golang/common/dso/dso.cc
- contrib/golang/common/dso/dso.h
- contrib/golang/common/dso/libgolang.h
- contrib/golang/common/dso/test/mocks.h
- contrib/golang/common/dso/test/test_data/simple.go
- contrib/golang/common/go/api/filter.go
- contrib/golang/common/go/api/type.go
- contrib/golang/filters/http/source/go/pkg/http/shim.go
- contrib/golang/filters/http/source/golang_filter.cc
- contrib/golang/filters/http/source/golang_filter.h
- contrib/golang/filters/http/source/processor_state.h
- contrib/golang/filters/http/test/golang_filter_fuzz_test.cc
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/access_log/filter.go
- contrib/golang/filters/http/test/test_data/property/filter.go
- examples/golang-http/simple/filter.go
> golang filter: support DownstreamPeriodic & DownstreamStart access log

- .azure-pipelines/pipelines.yml
- ci/do_ci.sh
- small do_ci.sh cleanups
- thin out the precache further
- add more specific fetching for individual jobs
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/cache: Optimize per-job caching

- source/common/grpc/common.cc
- source/common/grpc/common.h
- test/common/grpc/common_test.cc
- tools/code_format/config.yaml
> grpc: removing unused code

- OWNERS.md
Commit Message: update wbpcode's labels according to recent work
Add more clear labels to help PR/issue assignment according to my recent work.
Testing: n/a.
> update wbpcode's labels according to recent work

- tools/code_format/check_format.py
Include error output if the subcommand fails 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> tools/format: Minor improvement for err handling

- ci/run_envoy_docker.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile/ci: Fix docs publishing

- mobile/docs/publish.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile/docs: Fix path for publishing

- tools/gen_compilation_database.py
Risk Level:
Testing:
Docs Changes:
Release Notes:
> tools: add option to gen_compilation_db for system clang

- test/integration/udp_tunneling_integration_test.cc
udp_tunneling_integration_test.cc only had the terminating proxy test cases. I added more test cases to test the forwarding proxy scenario.
Risk Level: Low, changed only the test code.
Testing: Integration test
> http: add CONNECT-UDP forwarding proxy test

- .azure-pipelines/docker/save_cache.sh
- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/bazel: Fix bazelisk cache

- source/common/network/BUILD
- source/common/network/connection_impl.cc
- source/common/network/connection_socket_impl.h
- source/common/network/listen_socket_impl.h
- source/common/quic/BUILD
- source/common/quic/envoy_quic_client_connection.cc
- source/common/quic/envoy_quic_utils.h
step one of not needing E-M to pull in (more) listener code
Risk Level: low (code move)
Testing: n/a
> sockets: splitting connection socket out of listen_socket_impl

- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/http/test/test_data/access_log/filter.go
- examples/golang-http/simple/config.go
- examples/golang-http/simple/filter.go
Commit Message: golang filter: document how can we use goroutine in each callback
Testing: N/A
Docs Changes:
Release Notes:
> golang filter: document how can we use goroutine in each callback

- test/integration/integration_test.cc
- test/integration/multiplexed_integration_test.cc
- test/integration/protocol_integration_test.cc
> Enable tests that now work correctly in UHV mode

- .clang-tidy
- contrib/checksum/filters/http/test/checksum_filter_test.cc
- contrib/golang/common/dso/dso.cc
- contrib/golang/common/dso/dso.h
- contrib/golang/common/dso/libgolang.h
- contrib/golang/common/go/api/api.h
- contrib/golang/filters/http/test/golang_integration_test.cc
- contrib/golang/filters/network/source/cgo.cc
- contrib/golang/filters/network/source/upstream.cc
- contrib/golang/filters/network/source/upstream.h
- contrib/kafka/filters/network/source/mesh/outbound_record.h
- contrib/kafka/filters/network/source/mesh/upstream_config.cc
- contrib/kafka/filters/network/source/serialization.h
- contrib/qat/private_key_providers/source/qat.cc
- contrib/qat/private_key_providers/source/qat.h
- contrib/rocketmq_proxy/filters/network/source/router/router_impl.cc
- contrib/rocketmq_proxy/filters/network/source/router/router_impl.h
- contrib/sip_proxy/filters/network/source/metadata.cc
- contrib/squash/filters/http/source/squash_filter.cc
- contrib/squash/filters/http/source/squash_filter.h
- contrib/squash/filters/http/test/squash_filter_test.cc
- contrib/vcl/source/vcl_io_handle.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> clang/tidy: Fixes (`/contrib`)

- ci/run_envoy_docker.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docker/ci: Workaround skopeo issue properly

- .azure-pipelines/stage/publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docker/ci: Fix artefact path bug

- OWNERS.md
Risk Level: negative
Testing: IRL
Docs Changes: inline
Release Notes: now he can do them too ;-)
> owners: welcoming wbpcode to senior maintainers!

- .github/workflows/mobile-docs.yml
- ci/run_envoy_docker.sh
- mobile/docs/publish.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile/ci: Further fix for docs publishing

- .azure-pipelines/pipelines.yml
- ci/Dockerfile-envoy
- disable clang_tidy
- update rules_rust
- update distroless
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.24] Backport stack (latest)

- .github/workflows/mobile-docs.yml
- ci/run_envoy_docker.sh
- mobile/docs/publish.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile/docs: Publish outside of build container

- .azure-pipelines/stage/prechecks.yml
- ci/format_pre.sh
- ci/run_envoy_docker.sh
- docs/build.sh
- tools/proto_format/proto_format.sh
- remove dead code
- fix AZP/CI env vars
- disable pusblishing precheck on postsubmit
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/docs: Assorted fixes and cleanups

- docs/root/configuration/http/http_filters/checksum_filter.rst
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docs/checksum: Fix rst ref

- source/extensions/filters/http/ext_proc/ext_proc.cc
Commit Message: By switching the order of those two, the logging is only needed in `onFinishProcessorCalls` for immediate response case
Testing: existing tests covered this PR
> ext_proc: switch the order of `onFinishProcessorCalls` and `closeStream`

- source/extensions/filters/http/rate_limit_quota/BUILD
- source/extensions/filters/http/rate_limit_quota/client_impl.cc
- source/extensions/filters/http/rate_limit_quota/filter.cc
- source/extensions/filters/http/rate_limit_quota/filter.h
- source/extensions/filters/http/rate_limit_quota/quota_bucket_cache.h
- test/extensions/filters/http/rate_limit_quota/integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> RLQS: Implement throttling with token bucket

- mobile/library/common/engine.cc
Risk Level: n/a (trivial error message fix)
Testing: n/a
> mobile: Fix typo in the Engine::dumpStats ASSERT

- source/common/upstream/upstream_impl.cc
- source/common/upstream/upstream_impl.h
Commit Message: upstream: remove unnecessary dead code
I found this when working another PR. But to avoid make that PR to complex, split the clean up here.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> upstream: remove unnecessary dead code

- .azure-pipelines/stage/publish.yml
- .azure-pipelines/stages.yml
- .github/workflows/_stage_publish.yml
- .github/workflows/envoy-publish.yml
- ci/do_ci.sh
- ci/run_envoy_docker.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> docs/publishing: Use github trigger to update website

- .github/workflows/_stage_publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> github/ci: Fix publish workflow

- .github/workflows/envoy-sync.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/sync: Add mobile-website as downstream sync target

- source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc
- source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h
- source/extensions/common/dynamic_forward_proxy/dns_cache_manager_impl.cc
- test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc
> dns: switching cache to take statusor

- source/common/http/hash_policy.cc
- test/common/router/config_impl_test.cc
> hash: removing a switch default

- source/extensions/extensions_build_config.bzl
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Clarify comment-documentation on disabled by default

- source/extensions/extensions_build_config.bzl
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Disabled by default comment applies to only one filter

- envoy/event/dispatcher.h
- source/common/event/dispatcher_impl.cc
- source/common/event/dispatcher_impl.h
- source/common/network/base_listener_impl.cc
- source/common/network/base_listener_impl.h
- source/common/network/udp_listener_impl.cc
- source/common/network/udp_listener_impl.h
- source/common/quic/active_quic_listener.cc
- source/server/BUILD
- source/server/active_udp_listener.cc
- test/mocks/event/mocks.h
- test/mocks/event/wrapped_dispatcher.h
- test/server/active_udp_listener_test.cc
- test/server/connection_handler_test.cc
- test/test_listener.cc
> moving create udp listener out of dispatcher

- .azure-pipelines/pipelines.yml
- examples/zstd/Dockerfile-service
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.24] ci: Add required hacks/fixes

- test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Adding an ext_proc integration test to verify with allow_envoy and allow_all_routing enabled in the ext_proc filter configure, the host header can be modified and x-envoy-xxxx header can be added.
This is to address: https://github.com/envoyproxy/envoy/issues/29573
Risk Level:
Testing:
Docs Changes:
Release Notes:
> Ext_proc adding integration test to verify host header can be added

- .github/workflows/_stage_publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/publishing: Minor fix for website publishing

- examples/zstd/Dockerfile-service
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.25] verify/examples: Pin zstd example dependency

- .github/workflows/codeql-push.yml
Additional Description: Adding disk cleanup task to Code-QL before it starts to avoid fail due to "No space left on device"
> code-ql cleanup before start

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/cache: Bump version to expire failing auth

- distribution/debian/packages.bzl
- distribution/distros.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> distribution/debs: Produce/test bookworm debs

- .github/workflows/envoy-publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/verify: Minor fix for postsubmit verify

- ci/do_ci.sh
- distribution/debian/packages.bzl
- distribution/packages.bzl
Risk Level:
Testing:
Docs Changes:
Release Notes:
> distribution/debs: Add/test contrib debs

- source/common/stream_info/utility.cc
- source/common/stream_info/utility.h
Risk Level:
Testing:
Docs Changes:
Release Notes:
> proxy status: TLS_CERTIFICATE_ERROR

- test/integration/multiplexed_integration_test.cc
> Add validation of H/2 max concurrent streams

- examples/shared/python/Dockerfile
Risk Level:
Testing:
Docs Changes:
Release Notes:
> verify/examples: Revert shared python version 

- .azure-pipelines/stage/publish.yml
- ci/do_ci.sh
- distribution/BUILD
Fix #29956 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> distribution/publishing: Add debs to releases

- .azure-pipelines/stage/publish.yml
- bazel/external/boringssl_fips.BUILD
- ci/Dockerfile-envoy
- ci/do_ci.sh
- contrib/vcl/source/BUILD
- distribution/BUILD
- docs/BUILD
- tools/base/envoy_python.bzl
- tools/dependency/BUILD
- tools/proto_format/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.26] Backport stack (publishing)

- .azure-pipelines/stage/publish.yml
- bazel/external/boringssl_fips.BUILD
- ci/Dockerfile-envoy
- ci/do_ci.sh
- contrib/vcl/source/BUILD
- distribution/BUILD
- docs/BUILD
- tools/base/envoy_python.bzl
- tools/dependency/BUILD
- tools/proto_format/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.27] Backport stack (publishing)

- .github/workflows/check-deps.yml
- .github/workflows/pr_notifier.yml
Should fix #29961 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> github/workflows: Bump/fix/cleanup python/version

- distribution/debian/packages.bzl
- distribution/distros.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.26] distribution/debs: Produce/test bookworm debs (#29972)

- .github/workflows/pr_notifier.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/notifier: Revert python bump

- changelogs/current.yaml
- source/common/http/conn_manager_config.h
- source/common/http/conn_manager_impl.cc
- source/common/http/conn_manager_impl.h
- source/common/runtime/runtime_features.cc
- test/common/http/conn_manager_impl_test_2.cc
- test/common/http/conn_manager_impl_test_base.cc
- test/common/http/conn_manager_impl_test_base.h
- test/common/http/http2/http2_frame.cc
- test/common/http/http2/http2_frame.h
- test/integration/multiplexed_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.24] http: Fix CVE CVE-2023-44487

- docs/publish.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [release/1.24] repo: Fix format issue

- .azure-pipelines/pipelines.yml
- docs/publish.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [release/1.25] repo: Disable old website publishing

- changelogs/current.yaml
- source/common/http/conn_manager_config.h
- source/common/http/conn_manager_impl.cc
- source/common/http/conn_manager_impl.h
- source/common/runtime/runtime_features.cc
- test/common/http/conn_manager_impl_test_2.cc
- test/common/http/conn_manager_impl_test_base.cc
- test/common/http/conn_manager_impl_test_base.h
- test/common/http/http2/http2_frame.cc
- test/common/http/http2/http2_frame.h
- test/integration/multiplexed_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.25] http: Fix CVE CVE-2023-44487

- .github/workflows/_env.yml
- .github/workflows/_stage_publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.27] ci/env: Use correct checkout commit (#30085)

- tools/repo/notify.py
Risk Level:
Testing:
Docs Changes:
Release Notes:
> pr/notifier: Assorted fixes/cleanups

- .github/workflows/pr_notifier.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> pr/notifier: Fix dry-run condition

- tools/repo/notify.py
Risk Level:
Testing:
Docs Changes:
Release Notes:
> pr/notifier: Fix bad string replace

- ci/Dockerfile-envoy
- Update distroless image
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.25] Backport stack (0)

- ci/Dockerfile-envoy
- Update distroless image
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.27] Backport stack (0)

- .azure-pipelines/pipelines.yml
The removed code is unnecessary and slows things down.
Ideally we add a trigger but as this branch is EOL in 3 months it might make sense to just trigger manually when required.
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [1.25] docs/publishing: Remove postsubmit build

- api/envoy/config/common/matcher/v3/BUILD
- api/envoy/config/common/matcher/v3/matcher.proto
Commit Message: The API is now used in many places and must follow safe deprecation practices.
Testing: none
Docs Changes:
Release Notes:
> api: mark the unified matcher API as stable

- .github/workflows/envoy-prechecks.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> github/prechecks: Minor fix for workflow

- test/per_file_coverage.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/coverage: Adjust limit for `source/common/config`

- .azure-pipelines/pipelines.yml
- ci/Dockerfile-envoy
- Update` docker image
- Remove docs publishing
- Disable coverage
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.24] Backport/update stack (0)

- .github/workflows/envoy-prechecks.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> github/prechecks: Add back statuses cred for now

- .azure-pipelines/env.yml
- .azure-pipelines/stage/linux.yml
- .azure-pipelines/stage/prechecks.yml
- .azure-pipelines/stages.yml
- .github/actions/env/action.yml
- .github/workflows/_env.yml
- .github/workflows/envoy-prechecks.yml
- Speed up release pipeline
- ci updates
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.26] Backport stack (1)

- test/common/json/utf8.h
> Add missing <cstdint>

- .azure-pipelines/env.yml
- .azure-pipelines/stage/linux.yml
- .azure-pipelines/stage/prechecks.yml
- .azure-pipelines/stages.yml
- .github/actions/env/action.yml
- .github/workflows/_env.yml
- .github/workflows/envoy-prechecks.yml
- Release pipeline speedups
- ci updates
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.27] Backport stack (1)

- tools/base/requirements.in
- tools/base/requirements.txt
- tools/repo/notify.py
Risk Level:
Testing:
Docs Changes:
Release Notes:
> pr/notifier: Use async lib and escape messages

- tools/repo/notify.py
Risk Level:
Testing:
Docs Changes:
Release Notes:
> pr/notifier: Fix escaping

- contrib/generic_proxy/filters/network/source/codecs/dubbo/config.h
- contrib/generic_proxy/filters/network/source/interface/codec.h
- contrib/generic_proxy/filters/network/source/interface/codec_callbacks.h
- contrib/generic_proxy/filters/network/source/interface/filter.h
- contrib/generic_proxy/filters/network/source/interface/stream.h
- contrib/generic_proxy/filters/network/source/proxy.cc
- contrib/generic_proxy/filters/network/source/proxy.h
- contrib/generic_proxy/filters/network/source/router/router.cc
- contrib/generic_proxy/filters/network/source/router/router.h
- contrib/generic_proxy/filters/network/test/codecs/dubbo/config_test.cc
- contrib/generic_proxy/filters/network/test/fake_codec.h
- contrib/generic_proxy/filters/network/test/integration_test.cc
- contrib/generic_proxy/filters/network/test/mocks/codec.h
- contrib/generic_proxy/filters/network/test/mocks/filter.cc
- contrib/generic_proxy/filters/network/test/mocks/filter.h
- contrib/generic_proxy/filters/network/test/proxy_test.cc
- contrib/generic_proxy/filters/network/test/router/router_test.cc
Commit Message: generic proxy: refactor the codec API to support variable length load (streamline)
~~**This is API only change first for dicussion.**~~
Risk Level: low. Contrib only change.
Testing: wait.
> generic proxy refactoring part 1: refactor the codec API to support variable length load (streamline)

- .bazelrc
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/rbe: Fix credential helper

- changelogs/current.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> changelogs: Add release note for updated container images

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [1.25] ci/checks: Speed up by increasing concurrency

- tools/base/requirements.in
- tools/base/requirements.txt
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/publishing: Bump `envoy.base.utils` and fix fail

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [1.24] ci/checks: Speed up by increasing concurrency

- .azure-pipelines/pipelines.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [1.24] ci/checks: Dont wait for release job

- .bazelrc
- .github/workflows/_ci.yml
- .github/workflows/_env.yml
- .github/workflows/_stage_publish.yml
- .github/workflows/envoy-prechecks.yml
- .github/workflows/envoy-publish.yml
- bazel/engflow-bazel-credential-helper.sh
- tools/base/requirements.in
- tools/base/requirements.txt
- publishing workflow fixes/cleanups
- enable engflow RBE
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.27] Backport stack (2)

- mobile/library/kotlin/io/envoyproxy/envoymobile/EngineBuilderHTTP3Util.kt
Risk Level:
Testing:
Docs Changes:
Release Notes:
> mobile/kotlin: Fix var shadow warning

- docs/root/faq/debugging/how_to_dump_heap_profile_of_envoy.rst
Commit Message: Docs: Fix pprof command.
Risk Level: na
Testing: ran command
> Docs: Fix pprof command.

- .github/workflows/envoy-prechecks.yml
This ensures the correct commit is checked
Risk Level:
Testing:
Docs Changes:
Release Notes:
> github/ci: Pass ref in prechecks

- docs/root/configuration/listeners/network_filters/_include/generic_proxy_filter.yaml
Commit Message: generic proxy doc fix
Testing: N/A
> generic proxy doc fix

- changelogs/current.yaml
- source/common/http/conn_manager_impl.cc
- test/common/http/http2/http2_frame.cc
- test/common/http/http2/http2_frame.h
- test/integration/BUILD
- test/integration/filters/local_reply_during_decoding_filter.cc
- test/integration/multiplexed_integration_test.cc
> v1.27: HCM: Make reverse iteration resilient to element deletion (#30158)

- changelogs/current.yaml
- source/common/http/conn_manager_impl.cc
- test/common/http/http2/http2_frame.cc
- test/common/http/http2/http2_frame.h
- test/integration/BUILD
- test/integration/filters/local_reply_during_decoding_filter.cc
- test/integration/multiplexed_integration_test.cc
> v1.26: HCM: Make reverse iteration resilient to element deletion (#30158)

- changelogs/current.yaml
- source/common/http/conn_manager_impl.cc
- test/common/http/http2/http2_frame.cc
- test/common/http/http2/http2_frame.h
- test/integration/BUILD
- test/integration/filters/local_reply_during_decoding_filter.cc
- test/integration/multiplexed_integration_test.cc
> v1.25: HCM: Make reverse iteration resilient to element deletion (#30158)

- api/envoy/config/route/v3/route.proto
- api/envoy/config/route/v3/route_components.proto
- changelogs/current.yaml
- docs/root/configuration/advanced/advanced.rst
- docs/root/configuration/advanced/metadata_configurations.rst
- envoy/router/router.h
- source/common/config/metadata.h
- source/common/http/null_route_impl.h
- source/common/router/config_impl.cc
- source/common/router/config_impl.h
- test/common/router/config_impl_test.cc
- test/mocks/router/mocks.cc
- test/mocks/router/mocks.h
Commit Message: route: implement virtual host/route configuration level metadata support
Testing: unit.
Docs Changes: added.
> route: implement virtual host/route configuration level metadata support

- .bazelrc
- .github/workflows/_env.yml
- examples/shared/build/Dockerfile
Risk Level:
Testing:
Docs Changes:
Release Notes:
> build/image: Fix sha

- .github/workflows/_ci.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/github: Fix app auth publishing token

- contrib/golang/filters/http/source/go/pkg/http/shim.go
Risk Level:
Testing:
Docs Changes:
Release Notes:
> golang http: fix memory leaking.

- contrib/golang/filters/http/source/go/pkg/http/config.go
Risk Level:
Testing:
Docs Changes:
Release Notes:
> golang http: longer delay deletion time.

- ci/do_ci.sh
Temporary workaround for #30286 
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/deps: Disable requirements check

- .azure-pipelines/ci.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/rbe: Only enable BES where project is set

- .azure-pipelines/ci.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [bp/1.27] ci/rbe: Only enable BES where project is set (#30318)

- source/common/http/http1/balsa_parser.cc
Replace the existing heavyweight implementation with something more straightforward. Behavior is identical.
Tracking issue: https://github.com/envoyproxy/envoy/issues/21245
Signed-off-by: Bence Béky [bnc@google.com](mailto:bnc@google.com)
Commit Message: [balsa] Replace isVersionValid() implementation in balsa_parser.cc.
Additional Description: Replace the existing heavyweight implementation with something more straightforward. Behavior is identical.
Risk Level: low, no behavioral change
Testing: //test/common/http/http1:codec_impl_test and various integration tests
Optional Runtime guard: envoy.reloadable_features.http1_use_balsa_parser (default enabled)
> [balsa] Replace isVersionValid() implementation in balsa_parser.cc.

- examples/cache/service.py
- examples/cache/verify.sh
Commit Message: fix cache demo issue https://github.com/envoyproxy/envoy/issues/29105
Additional Description: fix cache demo issue https://github.com/envoyproxy/envoy/issues/29105
Testing: N/A
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/29105
> fix cache demo issue https://github.com/envoyproxy/envoy/issues/29105

- test/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/BUILD
> Deflake UDP proxy DFP test

- .azure-pipelines/env.yml
- .azure-pipelines/stage/linux.yml
- .azure-pipelines/stages.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> release/ci: Fix test condition

- .github/workflows/envoy-dependency.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
> ci/deps: Fix dependency bot id

- bazel/dependency_imports.bzl
Risk Level:
Testing:
Docs Changes:
Release Notes:
> deps: Fix jq version

- source/common/grpc/async_client_manager_impl.cc
- test/common/grpc/async_client_manager_impl_test.cc
backport  of https://github.com/envoyproxy/envoy/pull/30123
Risk Level:
Testing:
Docs Changes:
Release Notes:
> [1.28 backport] Fix intermittent cpu spike in grpc async client (#30123)
