envoyproxy/envoy

source/common/formatter/substitution_formatter.cc, test/common/upstream/health_check_fuzz.cc
Commit Message: [fuzz] Address various issues in the health_check_fuzz_test
Fix some issues in the health_check_fuzz_test where:
* EXPECT_CALL had willOnce but was called multiple times
* Interval timer trigger was applied to a closed connection
* an action event CONNECTED was applied multiple time consecutively
* header substitution for DOWNSTREAM_* was applied with no downstream connection
Testing: n/a
=> [fuzz] Address various issues in the health_check_fuzz_test

test/extensions/transport_sockets/tls/ssl_socket_test.cc
Commit Message: minor fix: eliminate the gmock warning of ssl sock test
```
2023-05-05T02:43:10.9572063Z [ RUN      ] IpVersions/SslReadBufferLimitTest.WritesLargerThanBufferLimit/IPv4_with_custom_cert_validation
2023-05-05T02:43:10.9572308Z 
2023-05-05T02:43:10.9572560Z GMOCK WARNING:
2023-05-05T02:43:10.9572930Z test/extensions/transport_sockets/tls/ssl_socket_test.cc:5925: Too few actions specified in EXPECT_CALL(*client_write_buffer, drain(_))...
2023-05-05T02:43:10.9573326Z Expected to be called twice, but has only 1 WillOnce().
2023-05-05T02:43:10.9573619Z GMOCK WARNING:
2023-05-05T02:43:10.9573956Z test/extensions/transport_sockets/tls/ssl_socket_test.cc:5925: Actions ran out in EXPECT_CALL(*client_write_buffer, drain(_))...
2023-05-05T02:43:10.9574481Z …
```
=> minor fix: eliminate the gmock warning of ssl sock test

test/integration/overload_integration_test.cc
Commit Message: Fix flake in overload_integration_test. 
Additional Description: wait for headers so the response starts for `LoadShedPointIntegrationTest.Http1ServerDispatchAbortClosesConnectionWhenResponseStarted`
Testing: ran 500x
=> Fix flake: //test/integration:overload_integration_test

test/integration/BUILD, test/integration/integration_tcp_client.cc, test/integration/integration_tcp_client.h, test/integration/tcp_proxy_integration_test.cc, test/integration/tcp_proxy_many_connections_test.cc
The reason for flakes is that integration tests oversubscribe CPU by a factor of 4 or 5. This causes timing issues, especially for CPU heavy builds (i.e. sanitizers), or builds that do not run on RBE/EngFlow (coverage, arm).
TcpProxyManyConnections fails in two places when starved for CPU. Creating autonomous upstreams (which is less likely) and then exchanging data over the connections (more likely). Stretching timeouts decreases probability of failure significantly, but does not eliminate it.
Splitting it from the TcpProxyIntegrationTest suite deflakes the tests in the TcpProxyIntegrationTest suite completely in my tests.
If the TcpProxyManyConnections continues to fail, the next step is to eliminate the data exchange step, as the only condition it tests is …
=> Deflake TcpProxyManyConnections test

test/server/admin/BUILD, test/server/admin/prometheus_stats_test.cc
Commit Message: Reproduces a scenario where it's difficult to use a streaming optimization for Prometheus stats based on scopes without introducing a bug. Context:
* Issue that /stats/prometheus endpoint takes too much much memory: https://github.com/envoyproxy/envoy/issues/16139
* Solution for non-Prometheus endpoints to use less memory for /stats and run faster: https://github.com/envoyproxy/envoy/pull/19693 which I believe is working well.
* This solution mapped to Prometheus: https://github.com/envoyproxy/envoy/pull/24998 
* A case where this solution has a duplicate`# TYPE` line due to two stats with the same tag-extracted-stat name from two different scopes: https://github.com/envoyproxy/envoy/issues/27173
Note that the existing unit tests did not exercise that scenario so this PR …
=> stats: reproduce redundant TYPE tags problem in Prometheus.

mobile/library/common/common/BUILD, mobile/library/common/common/default_system_helper.cc, mobile/library/common/common/default_system_helper.h, mobile/library/common/common/default_system_helper_android.cc, mobile/library/common/common/system_helper.cc, mobile/library/common/common/system_helper.h, mobile/library/common/http/BUILD, mobile/library/common/http/client.cc, mobile/test/common/integration/BUILD, mobile/test/common/integration/client_integration_test.cc, mobile/test/common/mocks/common/BUILD, mobile/test/common/mocks/common/mocks.cc, mobile/test/common/mocks/common/mocks.h
Add a SystemHelper abstraction for Envoy Mobile which provides
a platform-agnostic API for platform-specific system services in 
a manner that can be swapped out in tests.
Testing: New unit tests
=> Add a SystemHelper abstraction for Envoy Mobile

.github/workflows/mobile-android_tests.yml, bazel/BUILD, bazel/envoy_library.bzl, mobile/library/common/common/BUILD, mobile/library/common/common/default_system_helper.cc, mobile/library/common/common/default_system_helper.h, mobile/library/common/common/default_system_helper_android.cc, mobile/library/common/common/default_system_helper_apple.cc, mobile/library/common/common/system_helper.cc, mobile/library/common/common/system_helper.h, mobile/library/common/extensions/cert_validator/platform_bridge/BUILD, mobile/library/common/extensions/cert_validator/platform_bridge/c_types.h, mobile/library/common/extensions/cert_validator/platform_bridge/config.cc, mobile/library/common/extensions/cert_validator/platform_bridge/config.h, mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.cc, mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.h, mobile/library/common/jni/android_jni_interface.cc, mobile/library/common/jni/android_network_utility.cc, mobile/library/common/jni/android_network_utility.h, mobile/library/common/network/BUILD, mobile/library/common/network/apple_platform_cert_verifier.cc, mobile/library/common/network/apple_platform_cert_verifier.h, mobile/library/objective-c/EnvoyEngineImpl.mm, mobile/library/swift/EnvoyCxxSwiftInterop/cxx_swift_interop.h, mobile/test/common/extensions/cert_validator/platform_bridge/BUILD, mobile/test/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator_test.cc, mobile/test/common/integration/client_integration_test.cc, mobile/test/common/mocks/common/mocks.cc, mobile/test/common/mocks/common/mocks.h
Add cert verification support to the mobile SystemHelper
Change the PlatformBridgeCertValidator to get the underlying platform verifier from the SystemHelper instead of the Envoy Mobile register API mechanism. This allows the Envoy Mobile certificate verification API to be C++-ified by using string_view instead of envoy_data. This change fixed a memory leak in the Apple platform cert verified.
=> Add cert verification support to the mobile SystemHelper

envoy/stats/store.h, source/common/stats/isolated_store_impl.h, source/common/stats/thread_local_store.cc, source/common/stats/thread_local_store.h, test/common/stats/thread_local_store_test.cc, test/integration/server.h
Commit Message: stats: allow combining configured tags with custom tags
Additional Description: Adds a way to create a StatNameTagVector that contains extracted tags names from both the configured and well defined tags, and custom provided tags. Resolves #27030.
=> stats: allow combining configured tags with custom tags

test/extensions/filters/http/local_ratelimit/BUILD, test/extensions/filters/network/local_ratelimit/BUILD, test/integration/BUILD
This should reduce the rate of timing related flakes (which it does in local runs). However to take full advantage of CPU reservation all integration tests need to be configured with more CPU cores.
=> Reserve more CPU cores for integration tests with high rate of flakes

test/integration/protocol_integration_test.cc
Test timeout did not take into account sanitizer slowdown factor.
=> Deflake ManyRequestHeadersTimeout under TSAN

bazel/envoy_library.bzl, bazel/envoy_pch.bzl, bazel/envoy_test.bzl, source/common/common/BUILD, test/tools/schema_validator/BUILD, test/tools/schema_validator/validator.cc
This should break some unnecessary rebuilding in the case you don't actually use the pch feature.
=> bazel: remove pch dep when disabled

api/envoy/type/matcher/v3/regex.proto
Commit Message: Correction of a proto model to fix the actual state in envoy. The field was both required & deprecated. During execution, it was not required anymore. 
Testing: None
Docs Changes: Correction of a proto model to fix the actual state in envoy. The field was both required & deprecated. During execution, it was not required anymore.
Fixes https://github.com/envoyproxy/envoy/issues/26875
=> doc: `google_re2` for type type.matcher.v3.RegexMatcher is not required any more

.github/workflows/commands.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> github/ci: Dont trigger command workflow for bots

mobile/library/common/common/default_system_helper_android.cc, mobile/test/common/BUILD, mobile/test/common/http/BUILD, mobile/test/common/http/client_test.cc, mobile/test/common/main_interface_test.cc
This is a follow-up to https://github.com/envoyproxy/envoy/pull/27237 applying the same fix to the remaining 2 tests which needed it.  
Tested by forcing the system_helper to use android, verifying tests fail, and then fixing it via this change.
=> [Mobile] Use SystemHelper abstraction for remaining mobile C++ integration tests

test/run_envoy_bazel_coverage.sh
Commit Message: coverage test: make LLVM_VERSION configurable
Additional Description: with PR, you can run `LLVM_VERSION=Ubuntu14.0.6 test/run_envoy_bazel_coverage.sh` on ubuntu
Testing:
Release Notes:
=> coverage test: make LLVM_VERSION configurable

source/common/runtime/runtime_impl.cc, test/common/runtime/runtime_impl_test.cc, tools/code_format/config.yaml
reinstates prior behavior when parsing "buggy" yaml, where fractional structs are encoded as strings.  Previously when doing a round trip from json -> proto -> json this formatting would be parsed, so doing some string checks to support it going forward
Fixes commit #PR: https://github.com/envoyproxy/envoy/pull/26451
=> Runtime: reinstate yaml behavior when using strings instead of structs

envoy/upstream/cluster_factory.h, envoy/upstream/cluster_manager.h, source/common/upstream/cluster_factory_impl.cc, source/common/upstream/cluster_factory_impl.h, source/common/upstream/cluster_manager_impl.cc, source/common/upstream/cluster_manager_impl.h, test/common/upstream/cluster_factory_impl_test.cc, test/common/upstream/test_cluster_manager.h, test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc, test/mocks/upstream/cluster_manager_factory.h
Testing: n/a
part of https://github.com/envoyproxy/envoy-mobile/issues/176
=> cluster: moving exceptions to higher level of code

.azure-pipelines/stage/publish.yml, .azure-pipelines/stage/verify.yml, .azure-pipelines/stages.yml, ci/do_ci.sh
This uses GCS rather than azp's artefact storage to host the images created in CI that are tested in example verification
The benefit of doing this is that we can far more easily move the verify job out of azp by adding a trigger azp -> github, and github can then pick up the built artefacts from a public URL
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: Upload Docker images to GCS

api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto, api/envoy/service/ext_proc/v3/external_processor.proto, source/common/protobuf/utility.cc, source/common/protobuf/utility.h, source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, test/common/protobuf/utility_test.cc, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_corpus/crash-caae576f1c5a5c4bd6f831dd7d159b2504f476b0
Properly handle dataplane exception when received response timeout Duration is too large.
Also adding PGVs for ext_proc filter config.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Envoy ext_proc filter throw exception when received response timeout Duration is too large

api/envoy/config/rbac/v3/rbac.proto
Commit Message: Correct deprecation comment
Additional Description: I added this comment (#26762), and it turns out I was wrong - direct_remote_ip is not behaviorally equivalent to source_ip, it turns out remote_ip is a better match. So reversing the recommendation in the doc-comment.
Risk Level: doc-only
Testing: tried replacing source_ip with direct_remote_ip and broke a live service; replacing it with remote_ip maintained existing behavior.
Docs Changes: Yes.
=> [rbac] Correct deprecation comment

test/per_file_coverage.sh
Bump coverage for source/extensions/transport_sockets down to 95.6
Looks like post-submit coverage broke after #27116
```
Code coverage for source/extensions/transport_sockets is lower than limit of 95.7 (95.6)
```
https://dev.azure.com/cncf/envoy/_build/results?buildId=137095&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=299ff00a-2cef-5552-88aa-ea9cf69316f0
=> Bump coverage for source/extensions/transport_sockets down to 95.6

source/common/upstream/cluster_manager_impl.cc, test/common/upstream/cluster_manager_impl_test.cc
Commit Message: cluster-manager: allow cluster update callback removal during iteration
The update callbacks list in the cluster manager is an RAII list.
This PR allows removing a callback while iterating over the update callbacks list (calling either the `onClusterAddOrUpdate` or the `onClusterRemoval` callbacks).
Testing: Unit-test
=> cluster-manager: allow cluster update callback removal during iteration

bazel/io_opentracing_cpp.patch
Commit Message: Opentracing dynamic: Commit generated files to avoid cmake.
Additional Description: See related PRs, issues
Testing: Covered by CI
[Optional Runtime guard:] No
[Optional Fixes #Issue]: Related to #9958
[Optional Fixes commit #PR or SHA]: Potentially replaces #27244, #27246
[Optional Deprecated:] Needs to be considered in future for this OpenTracing dynamic component
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):] N/A
=> Opentracing dynamic: Commit generated files to avoid cmake.

contrib/generic_proxy/filters/network/test/BUILD, test/extensions/filters/http/file_system_buffer/BUILD, test/extensions/filters/http/on_demand/BUILD, test/extensions/filters/network/echo/BUILD, test/integration/BUILD
Add more CPU for recently flaked integration tests.
=> Add more CPU for integration tests

api/envoy/extensions/filters/http/custom_response/v3/custom_response.proto
Commit Message: docs: Fix type URI for custom_response example
Additional Description: The type URI `envoy.extensions.filters.http.custom_response.v3.LocalResponsePolicy` is not/no longer valid, the correct URI is `envoy.extensions.http.custom_response.local_response_policy.v3.LocalResponsePolicy` as evidenced by the fact that there are no longer any other references to the former for all of Envoy's codebase
Testing:
Docs Changes: The use of `envoy.extensions.filters.http.custom_response.v3.LocalResponsePolicy` in the custom_response example is updated with `envoy.extensions.http.custom_response.local_response_policy.v3.LocalResponsePolicy` …
=> docs: Fix type URI for custom_response example

source/common/http/conn_manager_impl.cc, test/extensions/access_loggers/grpc/http_grpc_access_log_integration_test.cc, test/extensions/filters/http/lua/lua_integration_test.cc, test/integration/integration_test.cc, test/integration/xds_integration_test.cc
This change allows UHV to validate HTTP/1.0 and HTTP/0.9 requests. Envoy does not treat pre HTTP/1.1 requests differently other than allowing the Host header to be optional and adding it using the `default_host_for_http_10` configuration value if it is not present in the request.
This change moves check for pre HTTP/1.1 protocol and addition of the Host header to before the UHV is invoked (instead of doing it after). This allows UHV to check it as 1.1 protocol as the Host header should be present at this point.
Moving this check into UHV is problematic, because validation is immutable and the Host header can not be added during validation (and transformation is done after validation). Given that this is an edge case, it should be ok to leave this check in HCM. …
=> UHV: allow validation of HTTP/1.0 requests

source/common/stats/isolated_store_impl.h, test/integration/server.h
Commit Message: stats: change extractAndAppendTags() implementation of IsolatedStatsStore to no-op
Additional Description: PR #27215 added ``extractAndAppendTags()`` methods for ``Stats::Store``, which is not implemented in the IsolatedStore, as it is meant for testing and does not have configured tags. The problem is that unit tests that use ``MockIsolatedStatsStore`` will always fail if the underlying production code calls ``extractAndAppendTags()``. Since IsolatedStoreImpl does not use the configured or well-known tags, a no-op is the practical implementation here.
Testing: None
cc @jmarantz
=> stats: change extractAndAppendTags() implementation of IsolatedStatsStore to no-op

contrib/golang/filters/http/source/cgo.cc, contrib/golang/filters/http/source/go/pkg/api/api.h, contrib/golang/filters/http/source/go/pkg/api/capi.go, contrib/golang/filters/http/source/go/pkg/http/capi_impl.go, contrib/golang/filters/http/source/go/pkg/http/type.go, contrib/golang/filters/http/source/golang_filter.cc, contrib/golang/filters/http/source/golang_filter.h, contrib/golang/filters/http/source/processor_state.h, contrib/golang/filters/http/test/golang_integration_test.cc, contrib/golang/filters/http/test/test_data/basic/filter.go
Commit Message: go extension trailer add api
=> go extension trailer add api

bazel/foreign_cc/BUILD, bazel/foreign_cc/ipp-crypto-skip-dynamic-lib.patch, bazel/repositories.bzl, contrib/cryptomb/private_key_providers/source/BUILD, contrib/qat/BUILD, contrib/sxg/filters/http/source/BUILD
enable contrib build with boringssl_fips
The problem was that `contrib` build was always successful with `boringssl=fips` flag, but executable asserted on `FIPS_mode` check. The root cause of that problem was that certain libraries in `contrib` linked non-fips version of `boringssl` and eclipsed fips version during the final linking state.
Risk Level: Low (no changes unless `boringssl=fips` flag is specified)
Release Notes: No 
Platform Specific Features:No
=> contrib: enable build with boringssl_fips

contrib/sip_proxy/filters/network/test/mocks.h
Commit Message: sip_proxy: work around the clang tidy error of mock method
Testing: n/a.
=> sip_proxy: work around the clang tidy error of mock method

contrib/golang/common/dso/dso.cc, contrib/golang/common/dso/dso.h, contrib/golang/common/dso/libgolang.h, contrib/golang/common/dso/test/dso_test.cc, contrib/golang/common/dso/test/mocks.h, contrib/golang/common/dso/test/test_data/simple.go, contrib/golang/filters/http/source/go/pkg/http/config.go, contrib/golang/filters/http/source/go/pkg/http/filtermanager.go, contrib/golang/filters/http/source/golang_filter.cc, contrib/golang/filters/http/source/golang_filter.h, contrib/golang/filters/http/test/golang_filter_fuzz_test.cc, contrib/golang/filters/http/test/test_data/basic/config.go, contrib/golang/filters/http/test/test_data/dummy/plugin.go, contrib/golang/filters/http/test/test_data/echo/config.go, contrib/golang/filters/http/test/test_data/passthrough/filter.go, contrib/golang/filters/http/test/test_data/routeconfig/config.go, examples/golang/simple/config.go
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> golang filter: register config factory and config parser in a single API

test/extensions/filters/network/common/fuzz/network_readfilter_fuzz_test.cc, test/extensions/filters/network/common/fuzz/network_writefilter_fuzz_test.cc
Commit Message: [fuzz] Reduce valid input gen depth to 20.
Reducing the maximum allowed depth during Protobuf message traversal in the valid input generation visitor to 20 to further reduce the possibility of stack overflows.
Testing: n/a
=> [fuzz] Reduce valid input gen depth to 20.

source/common/http/conn_manager_impl.cc, source/common/http/http1/codec_impl.cc, source/common/http/http1/codec_impl.h, test/common/http/conn_manager_impl_test.cc, test/common/http/http1/codec_impl_test.cc
Move HTTP/1.0 check into HTTP1 codec to better encapsulate it since it is HTTP/1 specific logic.
=> Move HTTP/1.0 check into HTTP1 codec

test/common/upstream/BUILD
=> Increase cluster_manager_impl_test test timeout to avoid TSAN flakes

mobile/.bazelrc
Currently Prs are failing if they trigger mobile coverage with lower counts
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> mobile/ci: Dont cache results for coverage

bazel/foreign_cc/BUILD, bazel/foreign_cc/ipp-crypto-skip-dynamic-lib.patch, bazel/repositories.bzl, contrib/cryptomb/private_key_providers/source/BUILD, contrib/sxg/filters/http/source/BUILD
backport PR 27296: enable build with boringssl_fips in contrib
Testing: compiled locally and run the image
=> backport PR 27296 to v1.23: enable build with boringssl_fips in contrib

bazel/foreign_cc/BUILD, bazel/foreign_cc/ipp-crypto-skip-dynamic-lib.patch, bazel/repositories.bzl, contrib/cryptomb/private_key_providers/source/BUILD, contrib/qat/BUILD, contrib/sxg/filters/http/source/BUILD
backport PR 27296: enable build with boringssl_fips in contrib
Testing: compiled locally and run the image
=> backport PR 27296 to v1.24: enable build with boringssl_fips in contrib

bazel/foreign_cc/BUILD, bazel/foreign_cc/ipp-crypto-skip-dynamic-lib.patch, bazel/repositories.bzl, contrib/cryptomb/private_key_providers/source/BUILD, contrib/qat/BUILD, contrib/sxg/filters/http/source/BUILD
backport PR 27296: enable build with boringssl_fips in contrib
Testing: compiled locally and run the image
=> backport PR 27296 to v1.25: enable build with boringssl_fips in contrib

.azure-pipelines/stage/prechecks.yml, .azure-pipelines/stage/publish.yml, ci/do_ci.sh
When we updated python in #25359 it broke the dockerhub publishing 
As this is only currently used on `main` it wasnt detected. This Pr adds a precheck test and improves the existing publishing target
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/dockerhub: Improve publishing and add test

source/common/common/hex.h, source/extensions/clusters/redis/crc16.h
This fixes a build problem on Fedora 38 with clang 16. (there are other build problems in external libraries)
Testing:
Docs Changes:
Release Notes:
=> build: include "cstdint" for the types uint8_t and uint16_t

source/extensions/network/dns_resolver/cares/dns_impl.cc
Commit Message: dns_cares: Add debug log entry when resolution response holds no records
Additional Description: Better tracking of empty DNS resolution responses (all details on the linked ticket)
Testing: Existing coverage.
Fixes #27214
=> dns_cares: Add debug log entry when resolution response holds no records

source/common/access_log/access_log_manager_impl.cc, source/common/access_log/access_log_manager_impl.h, test/common/access_log/access_log_manager_impl_test.cc, test/mocks/filesystem/mocks.cc, test/mocks/filesystem/mocks.h
Commit Message: CI showed a failure in TEST_F(AccessLogManagerImplTest, ReopenFileOnTimerOnly). Attempting to use more rigid thread-syncronization primitives instead of atomics to avoid races and/or undefined/misunderstood behavior.
Testing: Modified tests to fit new expectations
Docs Changes: noen
=> access log: attempt to fix test flake

bazel/foreign_cc/BUILD, bazel/foreign_cc/ipp-crypto-skip-dynamic-lib.patch, bazel/repositories.bzl, changelogs/current.yaml, contrib/cryptomb/private_key_providers/source/BUILD, contrib/qat/BUILD, contrib/sxg/filters/http/source/BUILD
backport PR 27296: enable build with boringssl_fips in contrib
Testing: compiled locally and run the image
=> backport PR 27296 to v1.26: enable build with boringssl_fips in contrib

changelogs/current.yaml, source/common/quic/envoy_quic_utils.cc, source/common/quic/envoy_quic_utils.h, source/extensions/quic/connection_id_generator/envoy_deterministic_connection_id_generator.cc
Commit Message: Fix typo - adjustNewConnectionIdForRouting
Additional Description: `adjustNewConnectionIdForRoutine` should be `adjustNewConnectionIdForRouting`. When corrected the function is self-explanatory, before correction it's actively misleading.
Risk Level: Negligible; no practical change.
Testing: Existing coverage.
Release Notes: Yes.
=> Fix typo - adjustNewConnectionIdForRouting

.github/workflows/commands.yml, ci/repokitteh/modules/azure_pipelines.star
- `/retest envoy` is ignored by mobile retest
- mobile retest works with the command at the start of any line
- `/retest mobile` is ignored by repokitteh
- repokitteh is a load quieter
- mobile creds have been restricted
this uses a forked version of the `/retest` module in the toolshed repo
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: Improve `/retest`

test/common/http/conn_manager_impl_test_base.cc, test/common/http/conn_manager_impl_test_base.h
Currently, HttpConnectionManagerImplMixin uses a self-allocated symbol table. When used together with other mock classes that use the globally shared symbol table, debug assertions are tripped that require symbol table addresses to be equal. This change would force HttpConnectionManagerImplMixin to use the globally shared test symbol table.
=> conn_manager_impl_test_base: Use global test symbol table

api/envoy/extensions/http/cache/file_system_http_cache/v3/file_system_http_cache.proto
Commit Message: [file_system_http_cache] fix broken design doc link
Additional Description: Link before goes to 404. Link after works.
Testing: n/a
Docs Changes: Yes it is.
=> [file_system_http_cache] fix broken design doc link

envoy/server/api_listener.h, mobile/library/common/engine.cc, mobile/library/common/http/client.cc, mobile/library/common/http/client.h, mobile/test/common/http/client_test.cc, source/extensions/filters/network/http_connection_manager/config.cc, source/extensions/filters/network/http_connection_manager/config.h, source/server/api_listener_impl.cc, source/server/api_listener_impl.h, source/server/server.cc, test/integration/api_listener_integration_test.cc, test/server/api_listener_test.cc
Commit Message: server: support using the ApiListener from a worker thread
Before this change, the SyntheticReadCallbacks used by the ApiListener hard-coded the main thread dispatcher, resulting in dispatcher assertion failures if the ApiListener was used from a worker thread. This change allows it to use the appropriate dispatcher whether used from the main thread or a worker thread.
This change is motivated by a project at Google that needs to run synthetic requests through the Envoy filter chain at a relatively high QPS; doing so via the ApiListener seems much cleaner and more efficient than doing so via a loopback interface. Thus, to sustain a higher level of QPS efficiently, we seek to use the ApiListener from multiple worker threads in parallel.
Risk Level: …
=> server: support using the ApiListener from a worker thread

mobile/bazel/envoy_mobile_repositories.bzl
mobile: remove the mobile-specific BoringSSL repo
Instead, use the Envoy's BoringSSL repo. Fixes the build error uncovered in #27467
=> mobile: remove the mobile-specific BoringSSL repo

source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_corpus/clusterfuzz-testcase-minimized-ext_proc_unit_test_fuzz-5547889199546368.test
ext_proc filter crash when sending trailers when request has no body.
The code is assuming the request always has body available and stored in the ext_proc buffer state when processing trailers, which leads into the crash.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ext_proc filter crash when sending trailers when request has no body

source/common/stats/stats_matcher_impl.cc, test/common/stats/BUILD, test/common/stats/stats_matcher_impl_speed_test.cc, test/common/stats/stats_matcher_impl_test.cc
Commit Message: Checking stat rejection using the stats matcher is ALWAYS a two step process. We first do a fast check using fastRejects, and then call slowRejects with the output of fastRejects. The slow check needs to happen only if the answer from fastRejects is not definitive, i.e. if it is `FastResult::NoMatch` and not one of `FastResult::Matches` or `FastResult::Rejects`. 
We were previously doing the slow check on a few occasions even when we had a definitive answer from fastRejects (for eg. for `FastResult::Matches`). This PR fixes that.
Result of `stats_matcher_impl_speed_test` benchmark with and without changes:
```
Without changes:
-------------------------------------------------------
Benchmark             Time             CPU   Iterations …
```
=> stats: Skip slowRejects if we have a definitive answer from fastRejects.

bazel/foreign_cc/hyperscan.patch, contrib/hyperscan/matching/input_matchers/source/BUILD
Commit Message: hyperscan: skip compilation on unused libs
Testing: N/A
=> hyperscan: skip compilation on unused libs

contrib/postgres_proxy/filters/network/test/postgres_decoder_test.cc, envoy/buffer/buffer.h, source/common/buffer/buffer_impl.cc, source/common/buffer/buffer_impl.h, source/common/buffer/watermark_buffer.cc, source/common/buffer/watermark_buffer.h, source/extensions/io_socket/user_space/io_handle_impl.cc, test/common/buffer/buffer_fuzz.cc, test/extensions/io_socket/user_space/io_handle_impl_test.cc, test/mocks/buffer/mocks.h
Fix use-after-free in user space IO handle where a drain callback may refer to a freed object (i.e. the connection on the other side of the internal listener, which may already have died). The solution employed herein is to call and clear the drain trackers on write(), since - as far as the handle being written to is concerned - we don't care about the write buffer as soon as it has been written to the peer's IO handle.
Signed off by: Eugene Chan <eugenechan@google.com>
Commit Message: socket: user space io handle invokes drain trackers immediately upon write
Risk Level: low (affects alpha feature only)
Testing: CI
=> socket: user space io handle invokes drain trackers immediately upon write

test/integration/buffer_accounting_integration_test.cc, test/integration/filters/test_socket_interface.h, test/integration/http2_flood_integration_test.cc, test/integration/multiplexed_integration_test.cc, test/integration/protocol_integration_test.cc, test/integration/shadow_policy_integration_test.cc, test/integration/socket_interface_swap.cc, test/integration/socket_interface_swap.h
The test manually introduces EBADF error on the connection between Envoy and the test client. However, the IoHandleMatcher doesn't  distinguish UDP socket from TCP. If the upstream HTTP/3 connection gets the same port number as downstream TCP connection, the EBADF error will be applied to the wrong connection.
Enforce IoHandleMatcher to match socket type.
Partially Fix #27490
=> test: fix flaky test DownstreamProtocolIntegrationTest.HandleDownstreamSocketFail

test/integration/tcp_proxy_odcds_integration_test.cc
Commit Message: ci: fix the flaky of TcpProxyOdcdsIntegrationTest.ShutdownAllConnectionsOnClusterLookupTimeout
This test is showing flaky when adding iouring support in https://github.com/envoyproxy/envoy/pull/24958, but it isn't related to the iouring, it is possible to happen in the current code.
The test created two clients.
https://github.com/envoyproxy/envoy/blob/fc5361a35bcfeeae8603e5d3957fefddf9d68a4d/test/integration/tcp_proxy_odcds_integration_test.cc#L306-L307
When invoking the TCP client's `waitForHalfClose`, both clients are blocking on the same dispatcher
https://github.com/envoyproxy/envoy/blob/fc5361a35bcfeeae8603e5d3957fefddf9d68a4d/test/integration/integration_tcp_client.cc#L129
The dispatcher will exit when it gets the end of the stream. …
=> ci: fix the flaky of TcpProxyOdcdsIntegrationTest.ShutdownAllConnectionsOnClusterLookupTimeout

api/bazel/repositories.bzl, api/bazel/repository_locations.bzl
I don't think these do anything here except for produce this warning:
```
DEBUG: Rule 'com_github_bufbuild_buf' indicated that a canonical reproducible form can be obtained by dropping arguments ["tags"]
DEBUG: Repository com_github_bufbuild_buf instantiated at:
/Users/ksmiley/dev/envoy4/WORKSPACE:9:23: in <toplevel>
/Users/ksmiley/dev/envoy4/bazel/api_repositories.bzl:4:21: in envoy_api_dependencies
/private/var/tmp/_bazel_ksmiley/81424bb29de8eeef22a825a179047d5f/external/envoy_api/bazel/repositories.bzl:47:26: in api_dependencies
/private/var/tmp/_bazel_ksmiley/81424bb29de8eeef22a825a179047d5f/external/envoy_api/bazel/repositories.bzl:9:23: in external_http_archive
/private/var/tmp/_bazel_ksmiley/81424bb29de8eeef22a825a179047d5f/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in …
```
=> bazel: remove tags from repository definition

contrib/network/connection_balance/dlb/source/connection_balancer_impl.cc
Commit Message: remove unused isOpen call
Additional Description: The call `socket->isOpen()` is unnecessary as we throw an exception after it
Testing: N/A
=> chore(dlb): remove unused isOpen call

api/envoy/extensions/filters/http/aws_request_signing/v3/aws_request_signing.proto, docs/root/configuration/http/http_filters/_include/aws-request-signing-filter-route-level-override.yaml, docs/root/configuration/http/http_filters/_include/aws-request-signing-filter.yaml, docs/root/configuration/http/http_filters/aws_request_signing_filter.rst, source/extensions/extensions_metadata.yaml, source/extensions/filters/http/aws_request_signing/aws_request_signing_filter.cc, source/extensions/filters/http/aws_request_signing/aws_request_signing_filter.h, source/extensions/filters/http/aws_request_signing/config.cc, source/extensions/filters/http/aws_request_signing/config.h, source/extensions/transport_sockets/tcp_stats/tcp_stats.cc, test/extensions/filters/http/aws_request_signing/aws_request_signing_filter_test.cc, test/extensions/filters/http/aws_request_signing/config_test.cc
Commit Message: Add route-level config for AWS request signing filter.
Additional Description: If route-level config is specified then it overrides the configuration on the virtual host level if set. Route-level sets a stats prefix so more granular stats may be exposed.
[Optional Fixes #Issue] #21541
=> Route level config support for AWS request signing filter

changelogs/current.yaml, source/common/router/upstream_request.cc, source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc, test/common/router/router_2_test.cc, test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc
Commit Message: [back port] backport some fixs of ext_authz, tracing
See #27416, #27220.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [back port] backport some fixs of ext_authz, tracing

.azure-pipelines/bazel.yml, .azure-pipelines/stage/publish.yml
In #27514 one of the env vars that the docs/build.sh script uses to determine whether to create rst or html was lost
this resolves it
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: Fix latest docs publishing

test/integration/BUILD, test/integration/ssl_utility.cc
This reverts commit 9f1aa4330060331bd074be2ee20516252f909d1a.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Revert "test: moving ssl utility to use parsed protos (#27585)"

test/common/formatter/substitution_formatter_test.cc
https://github.com/envoyproxy/envoy/pull/26464 removed JsonOrDie function but added ENVOY_BUG in the format call path.
The pre-release version of Protobuf includes this change:
`Expect fail when serialize inf and nan for Value.number_value in json format. fixes #11259` 
https://github.com/protocolbuffers/protobuf/commit/ca1cb1ba80ef18f5dccfb5b6ee7fa623ba6caab5
If we bump the Protobuf version, there will be an exception & crash using `NaN/inf/-inf` in `protobuf.struct` `number_value` when performing the serialization, while there is no check for this behavior right now.
Added 2 tests to catch this behavior change in the future.
Testing: unit
Docs Changes:
Release Notes:
[Optional …
=> formatter: add two tests NaN and Infinity

test/fuzz/BUILD, test/fuzz/mutable_visitor.cc
Commit Message: [fuzz] Use absl::Cleanup to ensure leaveMessage is called.
In the traverseMessageWorkerExt for the mutable_visitor make sure the leaveMessage() method is called on every exit of the routine.
Testing: n/a
=> [fuzz] Use absl::Cleanup to ensure leaveMessage is called.

source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/mutation_utils.cc, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/mutation_utils_test.cc
When ext_proc server sends back some header mutation settings which contain NULL characters, like /n, /r or /0, this will cause ext_proc filter ASSERT(valid) being fired up when Envoy is built in debug mode. 
In release mode, the ASSERT is no-op, however, we should add an explicit check to avoid such kind of headers get injected into Envoy.
Assert(valid) when ext_proc filter apply header mutations.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Assert(valid) when ext_proc filter apply header mutations

test/common/http/conn_manager_utility_test.cc
If custom header is already registered by `RegisterCustomInlineHeader` (for example, due to linking described in #27540), there will be only single entry added in the test here. 
Thus, check and fail earlier to manifest the failure reason. Otherwise, people will waste time debugging `callMutateRequestHeaders`
=> http: Ensure that multiple referer header entries are added

.azure-pipelines/pipelines.yml, .azure-pipelines/stage/verify.yml, .azure-pipelines/stages.yml, .github/workflows/check-deps.yml, .github/workflows/envoy-verify.yml, .github/workflows/mobile_release.yml, .github/workflows/pr_notifier.yml, .github/workflows/stale.yml, .github/workflows/workflow-complete.yml, .github/workflows/workflow-start.yml, bazel/repositories.bzl, ci/do_ci.sh, ci/run_envoy_docker.sh, ci/upload_gcs_artifact.sh, tools/base/requirements.in
This provides an initial implementation of a github workflow for examples verification
It will require some hookup in azp to make it work
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: Add github workflow for verify examples

test/extensions/filters/network/common/fuzz/uber_per_writefilter.cc
Commit Message: [fuzz] Remove conn_manager from writefilter white list.
Due to build dependencies the network.http_connection_manager makes it into the list of filters, that are registered with the factories in the network_writefilter_fuzz_test. But that filter shall not be fuzzed there, because the environment is not set up correctly. Therefore remove it from the list of available filters.
Testing: n/a
=> [fuzz] Remove conn_manager from writefilter white list.

bazel/README.md
If we try to install bazelisk & bazel, there will be an error:
Error: Cannot install bazel because conflicting formulae are installed.
bazelisk: because Bazelisk replaces the bazel binary
Please `brew unlink bazelisk` before continuing.
The rest of this doc recommends using bazelisk, so we replace bazel here to bazelisk.
Commit Message: we can only choose bazelisk via Homebrew
Testing: N/A
Docs Changes: bazel/README.md
Release Notes:
=> docs: we can only choose bazelisk via Homebrew

docs/root/configuration/listeners/network_filters/zookeeper_proxy_filter.rst
Commit Message: [ZK filter] update doc for *_resp_fast metrics
Additional Description: Based on [the code](https://github.com/envoyproxy/envoy/blob/a170b03435c4b12c0b6e46b6b9800f08dba2bdd5/source/extensions/filters/network/zookeeper_proxy/filter.cc#L111-L114), `*_resp_fast` metrics will be increased if the response latency is faster or equal to the threshold. This diff updates the doc accordingly.
Docs Changes: This diff will change [this page](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/zookeeper_proxy_filter#statistics).
=> [ZK filter] update doc for *_resp_fast metrics

bazel/BUILD, bazel/external/boringssl_fips.genrule_cmd
Commit Message: support fips-compliant build for arm
Additional Description:  related issue: https://github.com/envoyproxy/envoy/issues/27620
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> support fips-compliant build for arm

source/extensions/filters/network/zookeeper_proxy/decoder.cc, source/extensions/filters/network/zookeeper_proxy/decoder.h, source/extensions/filters/network/zookeeper_proxy/filter.cc, source/extensions/filters/network/zookeeper_proxy/filter.h
Commit Message: [ZK filter] pass std::chrono::milliseconds by value
Additional Description: We prefer to pass `std::chrono::milliseconds` by value since the overhead of copying is minimal and it aligns with the rest of the repo.
=> [ZK filter] pass std::chrono::milliseconds by value

test/integration/sds_dynamic_integration_test.cc
When the xDS cluster is specified after the cluster that depends on it (e.g. for SDS) in the Bootstrap config, the cluster isn't available when making the xDS request, causing a backoff retry after [0,1s).  This adds an delays to the tests.
This commit fixes the issue by specifying the xDS cluster first in order, before the static cluster that depends on it, in the Bootstrap config.
There are about 120 tests in this file, so we save on average about 60 seconds of test runtime everytime the tests in this file are executed.
=> tests: Eliminate retry backoffs in the SDS integration tests

.github/workflows/mobile-compile_time_options.yml, test/common/upstream/utility.h, test/config/utility.cc, test/extensions/health_checkers/redis/redis_test.cc, test/integration/BUILD, test/integration/base_integration_test.cc, test/integration/ssl_utility.cc
bazel test --config=remote --define=envoy_yaml=disabled  //test/common/integration:client_integration_test
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> test: making E-M e2e test work sans yaml

contrib/golang/filters/http/source/go/pkg/http/shim.go
It could be safer since people may still use the request object in Go even after it told C++ it had already finished processing.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> golang filter: always use GC finalizer to delete the req object in C++

contrib/generic_proxy/filters/network/source/interface/filter.h, contrib/generic_proxy/filters/network/source/proxy.cc, contrib/generic_proxy/filters/network/source/proxy.h, contrib/generic_proxy/filters/network/source/router/BUILD, contrib/generic_proxy/filters/network/source/router/router.cc, contrib/generic_proxy/filters/network/source/router/router.h, contrib/generic_proxy/filters/network/test/mocks/filter.h, contrib/generic_proxy/filters/network/test/proxy_test.cc, contrib/generic_proxy/filters/network/test/router/router_test.cc
Commit Message: generic proxy: add support to the original dst cluster and subset lb
Minor extending to the generic router filter make it support the `donstreamConnection` and `metadataMatchCriteria`. Then the subset lb and original dst cluster could be used for generic proxy.
Testing: unit.
=> generic proxy: add support to the original dst cluster and subset lb

docs/root/api-docs/xds_protocol.rst
*Commit Message:*
In restructured text, nested lists need a blank line separator to make them render as lists rather than as paragraph content.
*Additional Description:* N/A
*Risk Level:* Low.
*Testing:* Local docs build.
*Docs Changes:* Yes.
*Release Notes:* N/A
*Platform Specific Features:* N/A
Before:
After:
=> docs: fix xDS RPC variant list

.github/workflows/mobile-compile_time_options.yml
reinstating compile time options build (broken by bad yaml)
removing linux !h3 tests as we have swift e2e.  I could add it to the kotlin build if we have concerns
otherwise moving linux compile time options build to mimic common test options, and simplifying down to client integration test (avoid a bunch of flakey android deps and macos constraints) now that the client integration test works.
=> mobile: compile time options fix

test/fuzz/validated_input_generator.cc
Commit Message: [fuzz] Look at the correct class name for cut off.
network_read/writefilter_fuzz_test could still run into a stack-overflow, because the class
to match for in the cut off was the wrong one. Now looking at the current message's class
instead of the parent's one.
Testing: n/a
=> [fuzz] Look at the correct class name for cut off.

contrib/generic_proxy/filters/network/test/integration_test.cc
Commit Message: generic proxy: fix flaky integration test
To close #27023
Testing: n/a.
=> generic proxy: fix flaky integration test

ci/build_setup.sh
The env var `NO_BUILD_SETUP` is used to skip running `./ci/build_setup.sh`
It was moved into the file itself to make the file idempotent, but i inadvertently made it `exit` rather than `return` - this fixes that
This fix is necessary for the go-control-plane repo to sync correctly
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: Minor cleanup for build script

.azure-pipelines/env.yml, .azure-pipelines/stage/publish.yml, .azure-pipelines/stages.yml, ci/do_ci.sh, ci/run_envoy_docker.sh
Currently the release publishing code is tested in all ci - but if the version is `-dev` then it run dry-run
This can create an issue for release prs that have the `-dev` removed but are not postsubmit/ready to publish
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> release/ci: Add dry-run var for non-postsubmit

test/server/config_validation/server_test.cc, test/server/server_test.cc
Commit Message: Fixing clang-tidy caused by #27278.
Additional Description: https://dev.azure.com/cncf/envoy/_build/results?buildId=139360&view=logs&j=b7634614-24f3-5416-e791-4f3affaaed6c&t=d565ee52-b888-5d80-7fea-dfaed104c390
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Fix post-submit clang tidy

source/extensions/matching/http/cel_input/cel_input.h, test/extensions/matching/input_matchers/cel_matcher/cel_matcher_test.cc, test/extensions/matching/input_matchers/cel_matcher/cel_matcher_test.h, test/mocks/stream_info/mocks.cc, test/mocks/stream_info/mocks.h
With PR #25818, xds attributes (like upstream cluster metadata) are provided via streamInfo and are available to CEL library. This PR enables them and tests upstream cluster metadata specifically.
=> cel_matcher: match on xds attributes. 

bazel/BUILD, bazel/envoy_build_system.bzl, bazel/envoy_internal.bzl, bazel/envoy_mobile_defines.bzl, bazel/envoy_select.bzl, mobile/library/common/engine.cc, source/common/common/thread.h, source/common/filter/config_discovery_impl.cc, source/common/router/header_parser_utils.cc, source/common/runtime/runtime_impl.cc, source/common/secret/sds_api.cc, source/common/stats/tag_extractor_impl.cc, source/common/upstream/cds_api_helper.cc, source/common/upstream/health_discovery_service.cc, source/common/upstream/upstream_impl.cc, source/exe/stripped_main_base.cc, source/extensions/grpc_credentials/file_based_metadata/config.cc, source/extensions/network/dns_resolver/cares/dns_impl.cc, source/server/options_impl.cc, source/server/server.cc
The new build option simply compiles out all try/catch code, while leaving in the exceptions.   This can not yet be successfully used as it turns up fno-exceptions which chokes on throw statements.  This is by design as if we compiled out throw as well, config failures would be fatal instead of gracefully handled.
Testing: manual testing 
Part of https://github.com/envoyproxy/envoy/issues/27412
=> build: adding an disable_exceptions (which does not yet work)

source/common/http/codec_client.cc, test/integration/http2_flood_integration_test.cc
HTTP/2 flood test was using decommissioned `envoy.reloadable_features.http2_new_codec_wrapper` flag (which is no-op) and was not using oghttp2 or UHV. This change enables testing of oghttp2 with and without UHV by the flood test.
Also removed duplicated increment of the `upstream_cx_protocol_error` flag in UHV mode which triggered errors in the flood test.
=> UHV: Enable oghttp2 and UHV in HTTP/2 flood test

source/common/http/http_server_properties_cache_manager_impl.cc, source/extensions/filters/http/alternate_protocols_cache/filter.cc, source/extensions/upstreams/http/config.cc, test/common/http/http_server_properties_cache_manager_test.cc, test/extensions/upstreams/http/config_test.cc, tools/code_format/config.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
part of https://github.com/envoyproxy/envoy-mobile/issues/176
=> http: moving exceptions out of http_server_properties_cache_manager_impl

test/integration/quic_http_integration_test.cc
Fixes #27841:
- Increase the sleep from 500->1000 ms.
- Properly clean up the SocketInterfaceSwap.
Commit Message: Fix flaky test DeferredLoggingWithRetransmission
Risk Level: N/A, just testing
=> Fix flaky test QuicHttpIntegrationTest::DeferredLoggingWithRetransmission

CODEOWNERS
I renamed my gh handle, email is the same
=> chore: update owner for http language filter contrib extension

source/common/common/posix/thread_impl.cc
=> Avoid copying garbage if pthread_getname_np fails

.azure-pipelines/bazel.yml, .azure-pipelines/cached.yml, .azure-pipelines/docker/load_cache.sh, .azure-pipelines/docker/prepare_cache.sh, .azure-pipelines/docker/save_cache.sh, .azure-pipelines/stage/publish.yml
The Docker publishing job now caches the docker build image, and the docker cache for building images (and the bazel cache)
For other jobs, the Docker cache is loaded to/from tmpfs to speed up caching, for the Docker job there is insufficient room for this, so this switches it to using fs
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: Fix cache mount

api/contrib/envoy/extensions/filters/http/language/v3alpha/language.proto, contrib/language/filters/http/source/config.cc, contrib/language/filters/http/source/language_filter.cc, contrib/language/filters/http/source/language_filter.h
Adds a new option to the contrib http language filter to allow users to clear the route cache when the x-language header was added.
Related
- https://github.com/envoyproxy/envoy/issues/27840
=> filter: clear route cache in language filter

api/contrib/envoy/extensions/filters/network/generic_proxy/matcher/v3/matcher.proto, contrib/generic_proxy/filters/network/source/match.cc, contrib/generic_proxy/filters/network/source/match.h, contrib/generic_proxy/filters/network/test/match_test.cc
Commit Message: generic proxy: add new request matcher to simplify route table
A new custom matcher for generic proxy is added to simplify the route table. When simple AND semantic is used, the users needn't write complex configuration to combine different input/match.
Testing: unit.
=> generic proxy: add new request matcher to simplify route table

source/common/upstream/outlier_detection_impl.cc, test/common/upstream/outlier_detection_impl_test.cc
Part 1: https://github.com/envoyproxy/envoy/issues/26877 
Commit Message: Do not eject more hosts than max_ejection_percentage allows.
Additional Description: Currently max_ejection_percentage of 50% will eject 2/3 pods. Which is more than 50%. This PR fixes that. 
Testing: can add a unit test
Docs Changes: will do
Release Notes: Will add
=> a step towards enforcing max_ejection_percentage

source/extensions/filters/http/composite/filter.cc, source/extensions/filters/http/composite/filter.h, test/extensions/filters/http/composite/filter_test.cc
`onStreamComplete` is missing in composite filter. Without the fix, `onStreamComplete` will not be invoked in composite's delegated filter even if the delegated filter implements this function. 
Test: unit test with mock. Also, confirmed this function will be invoked in `filter_A + composite_filter(delegated to filter_B)` as expected.
=> composite: Implements onStreamComplete

source/common/grpc/common.cc
Commit Message: optimize getGrpcStatus implementation
Additional Description: optimize getGrpcStatus implementation by removing extra allocation and avoiding extra evaluations.
=> grpc: optimize getGrpcStatus implementation

api/envoy/extensions/filters/network/zookeeper_proxy/v3/zookeeper_proxy.proto, changelogs/current.yaml, docs/root/configuration/listeners/network_filters/zookeeper_proxy_filter.rst, source/extensions/filters/network/zookeeper_proxy/decoder.cc, source/extensions/filters/network/zookeeper_proxy/decoder.h, source/extensions/filters/network/zookeeper_proxy/filter.cc, source/extensions/filters/network/zookeeper_proxy/filter.h, test/extensions/filters/network/zookeeper_proxy/config_test.cc, test/extensions/filters/network/zookeeper_proxy/filter_test.cc
Commit Message: [ZK filter] Add 'addWatch' opcode support
Additional Description: Add the 'addWatch' opcode support to Envoy ZK filter, based on the [ZK opcode list](https://github.com/apache/zookeeper/blob/master/zookeeper-server/src/main/java/org/apache/zookeeper/ZooDefs.java#L94).
Docs Changes: Update the addWatch-opcode-related metrics in the [ZK proxy filter doc](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/zookeeper_proxy_filter#statistics).
Release Notes: Added the "addWatch" opcode support to the ZooKeeper proxy filter.
[[API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):] Update the ZK proxy proto opcode enum list by adding the …
=> [ZK filter] Add 'addWatch' opcode support

source/common/common/logger.cc, source/common/common/logger.h, test/common/common/log_macros_test.cc, test/common/common/logger_test.cc
Commit Message: logging: Add ENVOY_TAGGED_LOG macro to enable tagged logging
Additional Description: Further description below
Risk Level: low (new macro)
Example usage:
```
std::map<std::string, std::string> tags{{"key", "val"}, {"key2", "val2"}};
ENVOY_TAGGED_LOG(info, tags, "some_message {}", "val");
```
Expected output message: ``[Tags: "key":"val","key2":"val2"] some message val``
The idea here is that after #27278 was introduced to enable flushing application logs in JSON format, if ``json_format`` is set, then the ``%j`` flag would extract the tags from the message flushed to the sink, so the ``[Tags: "key":"val","key2":"val2"]`` part will be removed from the message. Additionally, a new …
=> logging: Add ENVOY_TAGGED_LOG macro to enable tagged logging

api/envoy/service/ext_proc/v3/external_processor.proto
This PR fixed three small doc issues in ext_proc service proto:
1) Stating mode_override is disabled if ext_proc filter config allow_mode_override is set to false.
2) body_mutation actually can be sent when responding to header request when status is CONTINUE_AND_REPLACE.
3) clear_route_cache flag is ignored when processing upstream response messages.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> fixing a few issues in ext_proc service doc

.github/workflows/mobile-traffic_director.yml
Switching to use the default value of `1`, as the workflow doesn't operate on pull requests.
=> ci: Remove fetch-depth in Traffic Director workflow YAML

api/envoy/extensions/filters/listener/tls_inspector/v3/tls_inspector.proto, changelogs/current.yaml, source/extensions/filters/listener/tls_inspector/tls_inspector.cc, source/extensions/filters/listener/tls_inspector/tls_inspector.h, test/extensions/filters/listener/tls_inspector/tls_inspector_integration_test.cc, test/extensions/filters/listener/tls_inspector/tls_inspector_test.cc
Commit Message: TLS Inspector: Enable tls_inspector buffer to dynamically size.
Additional Description: Users can set initial buffer size based on data from the histogram added in #27742. The filter will request more data (growing the listener filter buffer) as needed.
Risk Level: low / med
Testing: uint test
Runtime guard: Config guarded
=> TLS Inspector: Enable tls_inspector buffer to dynamically size.

source/extensions/filters/http/oauth2/filter.cc, test/extensions/filters/http/oauth2/filter_test.cc, test/extensions/filters/http/oauth2/oauth_integration_test.cc
If request hits callback endpoint with cookies(access toke, hmac etc), then oauth2-filter sends a 302 response to redirect to original location but misses to call `StopIteration`. This leads to [`ENVOY_BUG` condition](https://github.com/envoyproxy/envoy/blob/main/source/common/http/filter_manager.cc#L544)  to get triggered in filter manager.
This PR is invoking StopIteration at  required place and also covering this scenario in the integration test.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Oauth2: Fix ENVOY_BUG crash if request with cookies at callback endpoint

envoy/network/socket.h
Commit Message: Make ENVOY_MAKE_SOCKET_OPTION_NAME macro more explicit
Additional Description: This macro (and the macros that depend on it) are currently unusable from a namespace with `Network` at a different level, or outside of `::Envoy` namespace. This change makes the macro more explicit so it will work anywhere.
Risk Level: Negligible, it's a no-op.
Testing: Covered by existing tests.
=> Make ENVOY_MAKE_SOCKET_OPTION_NAME macro more explicit

source/common/upstream/upstream_impl.cc
Commit Message: upstream: minor code refactor calling a function once
Minor refactor - calling the function once instead of twice.
Considered using a switch instead but only 2 of the 3 values are relevant here.
Testing: N/A.
=> upstream: minor code refactor calling a function once

test/per_file_coverage.sh
#27621 introduced a change which is leading to CI for subsequent (unrelated) PRs to fail with low coverage errors for the `ext_proc` extension: https://dev.azure.com/cncf/envoy/_build/results?buildId=140094&view=logs&j=5035ce29-be3c-5fcf-dc50-abb6a265f8b1&t=fa1604b8-8cc1-5fec-21c7-5a4fad8d70ea
Temporarily reduce the coverage for `source/extensions/filters/http/ext_proc` to unblock unrelated PRs as @tyxia works on adding a test to fix it.
Testing: N/A
=> Temporary fix for ext_proc coverage issue.

envoy/common/exception.h, source/common/upstream/cluster_factory_impl.cc, source/common/upstream/health_checker_event_logger.h, source/common/upstream/health_checker_impl.cc, source/common/upstream/health_checker_impl.h, source/common/upstream/health_discovery_service.cc, source/common/upstream/health_discovery_service.h, source/extensions/health_checkers/http/health_checker_impl.cc, source/extensions/health_checkers/http/health_checker_impl.h, source/extensions/health_checkers/tcp/health_checker_impl.cc, source/extensions/health_checkers/tcp/health_checker_impl.h, test/common/upstream/hds_test.cc, test/common/upstream/health_checker_impl_test.cc, test/extensions/health_checkers/redis/config_test.cc, test/extensions/health_checkers/thrift/config_test.cc, tools/code_format/config.yaml
Part of https://github.com/envoyproxy/envoy-mobile/issues/176
=> health checker: removing exceptions

contrib/golang/common/dso/dso.cc, contrib/golang/common/dso/dso.h, contrib/golang/common/dso/test/dso_test.cc, contrib/golang/common/dso/test/mocks.h, contrib/golang/common/dso/test/test_data/simple.go, contrib/golang/filters/http/source/golang_filter.cc, contrib/golang/filters/http/source/golang_filter.h
to avoid memory leaking on the Go side.
fix #25370
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> golang filter: remove config on the Go side while deconstructing filter config.

CODEOWNERS
Commit Message: add StarryVae to go extension code owner
Testing: N/A
=> add StarryVae to go extension code owner

changelogs/current.yaml, source/extensions/filters/network/redis_proxy/router_impl.cc, source/extensions/filters/network/redis_proxy/router_impl.h, test/extensions/filters/network/redis_proxy/router_impl_test.cc
Commit Message: `catch_all_route` is of type `extensions.filters.network.redis_proxy.v3.RedisProxy.PrefixRoutes.Route`. However `remove_prefix`, `prefix` and `key_formatter` does not work when set against `catch_all_route`. This PR fixes the same and adds a unit test exercising these properties against `catch_all_route`
Additional Description: Related to https://github.com/envoyproxy/envoy/pull/26560
=> redis_proxy: add formatter support for catch_all_route

mobile/library/swift/EnvoyCxxSwiftInterop/cxx_swift_interop.h, mobile/library/swift/cxx/Bootstrap.swift
This change passes a reference, instead of a copy, to the generateBootstrapPtr bridge function. Copying the EngineBuilder can be quite expensive, since it can hold lots of large strings (certs, filter configs, etc).
The Swift bridge's generateBootstrap method needs to be declared `mutating` because the EngineBuilder reference is not constant (const&). The method parameter cannot be const& because of an interop oddity described in
https://github.com/apple/swift/blob/main/docs/CppInteroperability/InteropOddities.md.
=> mobile: Optimize the Swift-C++ interop generateBootstrap bridge

source/extensions/filters/http/rate_limit_quota/filter.cc, source/extensions/filters/http/rate_limit_quota/filter.h, source/extensions/filters/http/rate_limit_quota/matcher.cc, source/extensions/filters/http/rate_limit_quota/matcher.h, test/extensions/filters/http/rate_limit_quota/filter_test.cc, test/per_file_coverage.sh
Improve test coverage by : add a test case for data_unavailable/MatchState::UnableToMatch and remove untested code.
Fix: #24353
=> RLQS: Improve the test coverage

test/integration/buffer_accounting_integration_test.cc, test/integration/filters/test_socket_interface.h, test/integration/http2_flood_integration_test.cc, test/integration/multiplexed_integration_test.cc, test/integration/protocol_integration_test.cc, test/integration/shadow_policy_integration_test.cc, test/integration/socket_interface_swap.cc, test/integration/socket_interface_swap.h
The test manually introduces EBADF error on the connection between Envoy and the test client. However, the IoHandleMatcher doesn't distinguish UDP socket from TCP. If the upstream HTTP/3 connection gets the same port number as downstream TCP connection, the EBADF error will be applied to the wrong connection.
Enforce IoHandleMatcher to match socket type.
Partially Fix #27490
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.26] test: fix flaky test DownstreamProtocolIntegrationTest.HandleDownstreamSocketFail (#27546)

mobile/library/java/org/chromium/net/impl/CronvoyUrlRequest.java, mobile/test/java/org/chromium/net/impl/CronvoyEngineTest.java, mobile/test/java/org/chromium/net/testing/TestUrlRequestCallback.java
Commit Message:Fix CronvoyUrlRequest state transition and callback logic
Suppose the application sends a Cronvoy request and keeps calling request.read() until the end is reached, and the response is structured in a way such that the endStream signal comes by itself without any data.
Before this change, the behavior at the end of the stream is: 
EnvoyMobile calls OnData() and OnComplete() callbacks to Cronvoy. As a result, the application gets an OnReadCompleted() callback with no data read, but no OnSucceeded() because the [stream](https://source.corp.google.com/piper///depot/google3/third_party/envoy/src/mobile/library/java/org/chromium/net/impl/CronvoyUrlRequest.java;l=1000) hasn't reached its final state.
The application tries to read again, and …
=> [mobile]Fix CronvoyUrlRequest state transition and callback logic

source/common/http/http1/balsa_parser.cc, test/common/http/http1/codec_impl_test.cc
This is for consistency with http-parser behavior.
Commit Message: [balsa] Do not signal error on POST method with no Content-Length.
Additional Description: This is for consistency with http-parser behavior.
Risk Level: low, changed code protected by existing default-false runtime flag.
Runtime guard: envoy.reloadable_features.http1_use_balsa_parser
=> [balsa] Do not signal error on POST method with no Content-Length.

source/extensions/clusters/dynamic_forward_proxy/cluster.cc
Testing: None
For context about why I'm adding this - I'm experiencing weird behavior where some host is resolved in the sni_dfp filter, then sometimes flows work as expected, but sometimes they fail (to the same dest host) due to ``no healthy host for HTTP connection pool`` (I'm using TCP tunneling therefore the upstream is HTTP).
Since I'm using DFP cluster that has its own load balancer logic, it seems as runtime is going through either one of the flows I added debug logs to. These debug logs could help further understand what's going on.
=> Add debug logs to dynamic forward proxy failure paths

source/extensions/clusters/original_dst/original_dst_cluster.h, test/extensions/clusters/original_dst/original_dst_cluster_test.cc
Commit Message: Ensure timer is not invoked past parent cluster deletion.
Testing: unit
=> original_dst: fix timer lifetime

.github/workflows/mobile-compile_time_options.yml, mobile/test/common/integration/BUILD
All C++ test targets are added to the cc_test job in the workflow.
This can help us catch test build failures when the standard build
options are disabled as they would often be in a release build.
This update caught a bug in the sds_integration_test.cc, which
wasn't guarded with `envoy_select_google_grpc` in the BUILD
file, so that problem has been fixed in this commit as well.
=> ci: Add test targets to the mobile compile options workflow

mobile/test/swift/integration/ResetConnectivityStateTest.swift, mobile/test/swift/integration/SetLoggerTest.swift
Some work was done previously in
https://github.com/envoyproxy/envoy/pull/24892 to increase the Swift integration test timeout to 10 seconds to match the Kotlin test counterparts and reduce test flakiness.
However, there are still some places where the timeout was low and it caused flakey tests, see
https://github.com/envoyproxy/envoy/issues/28115.
This change increases the timeout to 10 seconds in the other Swift tests as well.
Fixes #28115
=> ci: Increase timeout in Swift integration tests

test/extensions/filters/network/common/fuzz/BUILD, test/extensions/filters/network/common/fuzz/network_readfilter_fuzz.proto, test/extensions/filters/network/common/fuzz/network_readfilter_fuzz_test.cc
Commit Message: [fuzz] Keep config part of input for network_readfilter.
In network_readfilter_fuzz_test keep the config part of the input and mutate the actions only for some time. Only every 1000 fuzz runs allow to mutate the config.
Testing: n/a
=> [fuzz] Keep config part of input for network_readfilter.

test/integration/http2_flood_integration_test.cc
=> Address flakiness of http2 flood test in CPU heavy builds

source/common/common/logger.h, test/common/common/BUILD, test/common/common/log_macros_test.cc, test/common/common/logger_test.cc
Additional Description: These macros extend ``ENVOY_TAGGED_LOG`` (added in https://github.com/envoyproxy/envoy/pull/27882) with a connection/stream and add the connection/stream ID to the tags, similar to ``ENVOY_CONN_LOG`` and ``ENVOY_STREAM_LOG``
=> application logs: add ENVOY_TAGGED_CONN_LOG and ENVOY_TAGGED_STREAM_LOG

test/common/http/hcm_router_fuzz_test.cc
I forgot to switch one call to the correct `fromHeaders` implementation that will not debug assert when faced with invalid headers. This PR fixes the call otherwise leading to noise in oss-fuzz.
=> hcm router fuzzer: call correct fromHeaders implementation

api/envoy/config/cluster/v3/BUILD, api/envoy/config/cluster/v3/cluster.proto, changelogs/current.yaml, envoy/upstream/load_balancer.h, source/common/router/router.h, source/common/upstream/load_balancer_impl.h, source/extensions/clusters/original_dst/original_dst_cluster.cc, source/extensions/clusters/original_dst/original_dst_cluster.h, source/extensions/load_balancing_policies/subset/subset_lb.h, test/extensions/clusters/original_dst/original_dst_cluster_test.cc, test/mocks/upstream/load_balancer_context.h
Commit Message: Add dynamic metadata support for ORIGINAL_DST cluster to pick a host
Additional Description: One can specify a MetadataKey with a path selector to pick up a host from the dynamic metadata of the request. Selected value can either be a string or a list with at least a single element of string type.
Testing: Unit Testing
=> Add dynamic metadata support for ORIGINAL_DST cluster to pick a host

source/common/upstream/upstream_impl.cc
Commit Message: lb: reserve space for vectors on hosts filtering
Minor fix - allocate space for vectors before running an insertion loop.
Testing: N/A
=> lb: reserve space for vectors on hosts filtering

api/tools/tap2pcap.py
When run 'bazel run @envoy_api//tools:tap2pcap path_0.pb path_0.pcap':
...
Traceback (most recent call last):
File "..../tools/tap2pcap.runfiles/envoy_api/tools/tap2pcap.py", line 88, in <module>
tap2pcap(sys.argv[1], sys.argv[2])
File "..../tools/tap2pcap.runfiles/envoy_api/tools/tap2pcap.py", line 53, in tap2pcap
wrapper.ParseFromString(f.read())
^^^^^^^^
File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 1: invalid start byte
...
Since protobuf file is binary format, open this file in binary mode will help to generate the PCAP successfully.
=> tap: Fix the failure of protobuf to PCAP generation

source/exe/terminate_handler.cc, source/exe/terminate_handler.h, test/exe/terminate_handler_test.cc, tools/code_format/config.yaml
Currently when the terminate handler handles an uncaught exception, it provides limited information about what happened and what exception was thrown. This change attempts to log additional details about the exception. 
Commit Message: Log uncaught exceptions when possible
Additional Description: Provide more details when possible when an uncaught exception is handled in terminate handler.
=> Log uncaught exception

test/common/buffer/owned_impl_test.cc, test/integration/base_integration_test.h, test/test_common/utility.h
Commit Message: Avoids a recent test-flake on Windows by returning early from that test. This works around (but does not fix) https://github.com/envoyproxy/envoy/issues/28177
Testing: Just the failed test.
=> buffer: Disable flaky test on windows.

envoy/json/json_object.h, source/common/json/json_internal.cc, test/common/json/BUILD, test/common/json/json_loader_test.cc
Address https://github.com/envoyproxy/envoy/pull/27926#discussion_r1245729093 so we don't need to catch exception
in data plane, specifically in http json to metadata filter which is WIP.
Testing: unit
=> Make json value getter no throw for data plane usage

test/extensions/resource_monitors/injected_resource/injected_resource_monitor_integration_test.cc
Commit Message: Fix flake in ListenerMaxConnectionPerSocketEventTest.AcceptsConnectionsUpToTheMaximumPerSocketEvent.
Testing: ran 1000x under conditions where flaked prior to fix
Docs Changes:
Release Notes:
Fixes #28175
=> Fix flake in ListenerMaxConnectionPerSocketEventTest.AcceptsConnectionsUpToTheMaximumPerSocketEvent

envoy/upstream/load_balancer.h, source/common/upstream/cluster_manager_impl.cc, source/extensions/load_balancing_policies/common/factory_base.h, source/extensions/load_balancing_policies/subset/config.cc, source/extensions/load_balancing_policies/subset/subset_lb.cc
Commit Message: upstream: only recreate worker local lb for thread aware lb
If the new `load_balancing_policy` is configured, the `least request`, `random`, etc. non-thread-aware Lbs will also be created by the `LoadBalancerFactory`. This means these LBs will be recreated when the host is changed even it's unnecessary.
This PR add a new flag to tell envoy don't recreate these LBs when the host is changed.
Testing: n/a.
=> upstream: only recreate worker local lb for thread aware lb

test/integration/http2_flood_integration_test.cc
This tests sets-up two timers. 1 for sending the PING packer that overflows the send queue and another overall timeout (just in case). Both timers needs to be scaled in CPU heavy builds, like TSAN (and before only the overall timer was scaled). In CPU heavy build it takes more time to pre fill the send queue and the PING packet sent on timer does not cause overflow and as a result the test fails.
Fixes #27886
=> Add TSAN timeout scale to both timers

source/server/admin/html/active_stats.js, source/server/admin/stats_html_render.cc, source/server/admin/stats_html_render.h, test/server/admin/stats_html_render_test.cc
Commit Message: The detailed histograms may be too detailed for the default HTML view. Instead, respect the buckets-mode, and only use detailed mode if this was requested by the user.
Also, fix an accidental script-driven change (#27987) to a JS file that made it invalid JS, breaking active_html mode.
Testing: added new test for histogram modes in HTML, and manually rendered in a server.
Docs Changes: n/a -- this change makes the system behave as documented, rather than ignoring the buckets-mode for HTML.
=> admin: Histogram html use summary-buckets mode by default

contrib/golang/filters/http/test/BUILD, contrib/golang/filters/http/test/golang_filter_test.cc, test/common/http/match_delegate/BUILD, test/common/http/match_delegate/config_test.cc, test/common/upstream/BUILD, test/common/upstream/upstream_impl_test.cc, test/extensions/access_loggers/common/BUILD, test/extensions/access_loggers/common/grpc_access_logger_test.cc, test/extensions/clusters/original_dst/BUILD, test/extensions/clusters/original_dst/original_dst_cluster_test.cc, test/extensions/filters/http/compressor/BUILD, test/extensions/filters/http/compressor/compressor_filter_test.cc, test/extensions/filters/http/connect_grpc_bridge/BUILD, test/extensions/filters/http/connect_grpc_bridge/connect_grpc_bridge_filter_test.cc, test/extensions/filters/http/connect_grpc_bridge/end_stream_response_test.cc, test/extensions/filters/http/cors/BUILD, test/extensions/filters/http/cors/cors_filter_integration_test.cc, test/extensions/filters/http/grpc_http1_bridge/BUILD, test/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter_test.cc, test/extensions/filters/http/health_check/BUILD, test/extensions/filters/http/health_check/health_check_test.cc, test/extensions/filters/http/jwt_authn/BUILD, test/extensions/filters/http/jwt_authn/matcher_test.cc, test/extensions/filters/http/local_ratelimit/BUILD, test/extensions/filters/http/local_ratelimit/filter_test.cc
Clean-up, `test_runtime.h` is not used in some tests.
Testing:
Docs Changes:
Release Notes:
=> test: more clean up test runtime

changelogs/current.yaml, source/extensions/filters/network/common/redis/client.h, source/extensions/filters/network/common/redis/supported_commands.h, source/extensions/filters/network/redis_proxy/command_splitter_impl.cc, source/extensions/filters/network/redis_proxy/conn_pool_impl.cc, test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc
Duplicate of: https://github.com/envoyproxy/envoy/pull/28149
I had to open this new PR since the commits in the previous PR were not signed properly.
Signing the commits retroactively was problematic because of a merge commit in the middle.
Commit Message: Fix redis transaction when traffic is mirrored
When envoy is configured to mirror Redis traffic, using transactions (MULTI) would not work well, possibly leading to a crash. This PR fixes this issue by making the following changes:
1) I have defined MULTI, EXEC, and DISCARD as write commands, so they will be mirrored even when read commands are excluded from mirroring.
2) A dedicated connection for the transaction is opened for each redis server that receives mirrored commands, the same way a dedicated connection …
=> Fix redis transaction when traffic is mirrored (new PR instead of https://github.com/envoyproxy/envoy/pull/28149)

api/envoy/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto
Commit Message: Response headers are applied only when requests are rate-limited and filter is enforced. Currently doc comment was ambiguous in the sense that it was mentioning `either enabled or enforced` and also mentioning that `requests that have been rate-limited`.  
Testing:
Docs Changes:
Release Notes:
=> local-rate-limit: Fix doc comment for response_headers_to_add

.gitignore
In c7850756ae1bf42b6117804b11b592d7a0c12890 the exclusion for swap files was changed to exclude `.s??`
This broke the original intention of the exclusion - ie `.swap` would not be ignored, but it also broke gitignore for any other file with a 3-letter extension starting with `s` (eg `go.sum`)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> git: Dont ignore go.sum files

CODEOWNERS
I am no longer able to work on the Wasm-related codebase.
cc @lizan @mpwarres 
ref https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/360
=> CODEOWNERS: removes @mathetake from Wasm extensions

source/extensions/transport_sockets/tls/context_impl.cc
Suggested by Boring SSL team (David), related [comment](https://github.com/envoyproxy/envoy/issues/28246#issuecomment-1626073919)
=> tls: Update the preprocessor macro check to check against boringssl version

test/integration/listener_lds_integration_test.cc
Verified with compile-breaking gibberish the prior #define didn't work on our arm build and this one does.
disabling a flaky test on arm
https://github.com/envoyproxy/envoy/issues/22489
=> test: actually disabling on arm

test/per_file_coverage.sh
removing  
source/common/router
source/common/tracing
source/server/admin
as they are now above the bar.
=> coverage: ratcheting

source/extensions/transport_sockets/tls/context_impl.cc
Seems to cause coverage to fail.
This reverts commit bd836c22030b20624142c78fc16773d4bb2e582e.
=> Revert "tls: Update the preprocessor macro check to check against boringssl version (#28296)"

docs/BUILD
In #28104 the sds configs were separated into yaml files - these seem to fail when tested - not sure how they got through presubmit
testing locally and it reliably fails, but only for the 2 configs excluded here
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs/config: Exclude sds configs from tests

source/common/http/http1/balsa_parser.cc, test/common/http/http1/codec_impl_test.cc
Commit Message: [balsa] Disallow invalid character in response header names.
Additional Description: This is for consistency with http-parser behavior.
Risk Level: low, changed code protected by existing default-false runtime flag.
Runtime guard: envoy.reloadable_features.http1_use_balsa_parser
=> [balsa] Disallow invalid character in response header names.

source/common/common/logger.h, test/common/common/logger_test.cc
Additional Description: Resolves #28307. Following the addition of ``ENVOY_TAGGED_LOG`` and it's derivatives, this PR changes ``ENVOY_CONN_LOG`` and ``ENVOY_STREAM_LOG`` to print connection and stream IDs as tags. Examples below.
When JSON logs are not enabled:
Log line: ``ENVOY_CONN_LOG(info, "fake message {}", connection_, "val");``
Expected log: ``[Tags: "ConnectionId":"52"] fake message val``
When JSON logs are enabled:
Log line: ``ENVOY_CONN_LOG(info, "fake message {}", connection_, "val");``
Expected log: ``{"Message":"fake message val","ConnectionId":"52"}``
=> application_logs: serialize ENVOY_CONN_LOG connection id as tags

bazel/foreign_cc/nghttp2.patch, changelogs/current.yaml, test/integration/filters/test_socket_interface.cc, test/integration/filters/test_socket_interface.h, test/integration/http2_flood_integration_test.cc, test/integration/socket_interface_swap.cc, test/integration/socket_interface_swap.h
Fix memory leak in nghttp2 when it processes pending requests after receiving the GOAWAY frame.
Fix https://github.com/envoyproxy/envoy/security/advisories/GHSA-jfxv-29pc-x22r
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.23] CVE/http: Fix memory leak in nghttp2 codec

bazel/foreign_cc/nghttp2.patch, changelogs/current.yaml, test/integration/filters/test_socket_interface.cc, test/integration/filters/test_socket_interface.h, test/integration/http2_flood_integration_test.cc, test/integration/socket_interface_swap.cc, test/integration/socket_interface_swap.h
Fix memory leak in nghttp2 when it processes pending requests after receiving the GOAWAY frame.
Fix https://github.com/envoyproxy/envoy/security/advisories/GHSA-jfxv-29pc-x22r
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.25] CVE/http: Fix memory leak in nghttp2 codec

bazel/foreign_cc/nghttp2.patch, changelogs/current.yaml, test/integration/filters/test_socket_interface.cc, test/integration/filters/test_socket_interface.h, test/integration/http2_flood_integration_test.cc, test/integration/socket_interface_swap.cc, test/integration/socket_interface_swap.h
Fix memory leak in nghttp2 when it processes pending requests after receiving the GOAWAY frame.
Fix https://github.com/envoyproxy/envoy/security/advisories/GHSA-jfxv-29pc-x22r
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.24] CVE/http: Fix memory leak in nghttp2 codec

bazel/foreign_cc/nghttp2.patch, changelogs/current.yaml, test/integration/filters/test_socket_interface.cc, test/integration/filters/test_socket_interface.h, test/integration/http2_flood_integration_test.cc, test/integration/socket_interface_swap.cc, test/integration/socket_interface_swap.h, test/per_file_coverage.sh
Fix memory leak in nghttp2 when it processes pending requests after receiving the GOAWAY frame.
Fix https://github.com/envoyproxy/envoy/security/advisories/GHSA-jfxv-29pc-x22r
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> CVE/http: Fix memory leak in nghttp2 codec

.bazelrc, bazel/io_opentracing_cpp.patch, ci/do_ci.sh, source/common/common/logger.h, source/extensions/common/aws/signer_impl.cc, source/extensions/common/aws/utility.cc, source/extensions/filters/common/rbac/matchers/upstream_ip_port.cc, source/extensions/filters/network/mongo_proxy/codec_impl.h, source/extensions/filters/network/mongo_proxy/proxy.cc, source/server/hot_restarting_base.cc, test/common/access_log/access_log_impl_test.cc, test/extensions/filters/http/aws_lambda/aws_lambda_filter_integration_test.cc, test/extensions/filters/http/bandwidth_limit/filter_test.cc, test/extensions/filters/http/rbac/rbac_filter_integration_test.cc, test/extensions/filters/http/rbac/rbac_filter_test.cc, test/extensions/filters/http/tap/tap_filter_integration_test.cc, test/extensions/filters/network/local_ratelimit/local_ratelimit_test.cc, test/extensions/filters/network/rbac/config_test.cc, test/extensions/filters/network/rbac/filter_test.cc, test/extensions/filters/network/thrift_proxy/router_test.cc, test/extensions/filters/network/thrift_proxy/trds_integration_test.cc, test/extensions/tracers/opentelemetry/opentelemetry_tracer_impl_test.cc, test/fuzz/validated_input_generator.h, test/test_common/utility.h
First step for enabling C++20. For now just enabled for compile-options build to prevent bit rot. No effect on production binary.
This PR fixes the bad merge of the original PR #28337 and reverts the #28372 revert.
Part of #27757
=> C++20 build config

source/common/signal/signal_action.h
Commit Message: signal: set altstack size a multiple of page size
We use `mprotect` to protect address space for signal handling, and `mprotect` requires its arguments (`altstack_` + `guard_size_` + `altstack_size_`) to be aligned to a page boundary. Here, `guard_size_` is the system page size and `altstack_size_` is a multiple of page size. `altstack_size_` is initialized as the maximum of `4 * guard_size_` and `MINSIGSTKSZ` while `MINSIGSTKSZ` may **NOT** be a multiple of page size.
Testing: N/A
=> signal: set altstack size a multiple of page size

source/server/overload_manager_impl.cc, source/server/overload_manager_impl.h
Commit Message: Fix Symbol::operator== implementation
Additional Description: This causes compilation issue on Windows
Risk Level: zero
Testing:
Docs Changes:
=> Fix Symbol::operator== implementation

contrib/generic_proxy/filters/network/test/integration_test.cc
Commit Message: generic proxy: fix flaky integration test 2
To close #27842.
Testing: n/a.
=> generic proxy: fix flaky integration test 2

envoy/config/subscription.h, source/common/config/decoded_resource_impl.h, test/common/config/decoded_resource_impl_test.cc
One fromResource variant is taking the `ProtobufWkt::Any& resource` as the input, and then a temp value is introduced in this static method.
```
envoy::service::discovery::v3::Resource r;
MessageUtil::unpackTo(resource, r); 
```
A ref to a temp val can cause `segv` fault when the temp is distroied.
Docs Changes:
Release Notes:
=> config: metadata life time with Any conversion

api/envoy/extensions/transport_sockets/tls/v3/common.proto
Commit Message: api: introduce the private key provider list field
This PR introduces a new `private_key_provider_list` field. It allows the end user provide a list of private key providers which he want to use. Then Envoy will find out one of private key provider which available on the host. If there is none of available in the list. The Envoy will fallback to BoringSSL default implementation.
When the new field `private_key_provider_list` implemented,  there are list of fields are going to deprecate:
* `private_key_provider` will be replaced by `private_key_provider_list`
https://github.com/envoyproxy/envoy/blob/c49f392561ba8c246f845d61e555c9536d5edbea/api/envoy/extensions/transport_sockets/tls/v3/common.proto#L236
* qat provider's `private_key` field will be …
=> api: introduce the private key provider list field

contrib/golang/filters/http/test/test_data/basic/filter.go, contrib/golang/filters/http/test/test_data/echo/filter.go, examples/golang/simple/filter.go
Some plugins in wild set headers and grpc args even they don't use the args. Clean up the unused args in the example to show these args are not required.
Commit Message: clean up unused args in SendLocalReply
Additional Description: Some plugins in wild set headers and grpc args even they don't use the args. Clean up the unused args in the example to show these args are not required.
Testing:
Docs Changes:
Release Notes:
=> golang filter: clean up unused args in SendLocalReply

.github/workflows/_cache_docker.yml
This just adds a workflow/job to cache the Docker build image in github, similar to how we do already in azp
Its not used in this PR, but will follow up immediately to make use of it
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/github: Add build image caching

.github/workflows/_ci.yml
This ~replicates the functionality of `.azure-pipelines/bazel.yml` for github workflows - allowing us to run do_ci.sh commands with ~the same env vars/args between azp <> gh
This is not used in this PR but i will follow up to make use of it immediately
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/github: Add `do_ci.sh` `workflow_call`

.azure-pipelines/env.yml, .azure-pipelines/stage/prechecks.yml, .azure-pipelines/stages.yml, .github/workflows/envoy-prechecks.yml
This shifts the dep-check job gh -> azp
It means that for now errors in this check wont block azp - we probably do want to make it required tho 
This check is currently quite error prone and this may/not help with that, certainly wont fix
With the implementation so far this doesnt use RBE, but i can follow up straight away to add it
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/github: Shift dependency check/s to github

ci/verify_examples.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/examples: Warn, dont error on flakey `double-proxy` test

contrib/golang/common/go/api/filter.go, contrib/golang/filters/http/source/go/pkg/http/capi_impl.go, contrib/golang/filters/http/source/go/pkg/http/filter.go, contrib/golang/filters/http/source/golang_filter.cc, contrib/golang/filters/http/source/golang_filter.h, contrib/golang/filters/http/test/golang_integration_test.cc, contrib/golang/filters/http/test/test_data/basic/filter.go
Commit Message: golang filter: add VirtualClusterName getter
Additional Description: Add a new method to get matched virtual cluster name
Docs Changes:
Release Notes:
=> golang filter: add VirtualClusterName getter

api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
Adding disallowed_headers in the ext_proc header forwarding rule.
This is to specifically disallow certain headers to be forwarded to the ext_proc server.
This PR is a follow up PR of https://github.com/envoyproxy/envoy/pull/27333.  It addresses the API changes to add the disallowed_headers.  The actual implementation will follow later.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Adding disallowed_headers in the ext_proc header forwarding rule.

.github/actions/env/action.yml, .github/actions/verify/examples/setup/action.yml, .github/workflows/_cache_docker.yml, .github/workflows/_ci.yml, .github/workflows/_env.yml, .github/workflows/_stage_verify.yml, .github/workflows/_workflow-start.yml, .github/workflows/commands.yml, .github/workflows/envoy-prechecks.yml, .github/workflows/envoy-publish.yml, .github/workflows/envoy-sync.yml, .github/workflows/workflow-complete.yml
- reenable untrusted code checkout in prs
- fix wf check dependency
- separate env to an action, and run initial jobs concurrently
- fix workflow-complete handling
Currently the v/examples job always runs with the current `main` (ie doesnt correctly check out the pr commit)
This fixes that but also opens up the workflow to potential request attacks so defensive coding is applied in various places to ensure that only untrusted ci runs (ie no access to secrets) can run untrusted code
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review …
=> ci/github: Fixes/cleanups for env and workflows

.azure-pipelines/stage/publish.yml, .github/actions/env/action.yml, .github/workflows/_cache_docker.yml, .github/workflows/_ci.yml, .github/workflows/_env.yml, .github/workflows/_stage_verify.yml, .github/workflows/envoy-publish.yml
- Improve names in newer/triggered github CI
- Attempt to ensure untrusted code is able to run in triggered (only correct) CI
- Dont checkout the repo for build image
- Remove fail supression from azp trigger
- make `.github/workflows/_env.yml` the authoritative source for build image config (doesnt require repo checkout)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/github: Fix repo contexts

test/common/network/BUILD, test/common/network/io_socket_handle_impl_integration_test.cc, test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc, test/extensions/network/dns_resolver/cares/dns_impl_test.cc, test/extensions/network/dns_resolver/getaddrinfo/getaddrinfo_test.cc
Commit Message: temporarily workaround failed test on windows
See #28504 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> temporarily workaround failed test on windows

api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto, source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, source/extensions/filters/http/ext_proc/mutation_utils.cc, source/extensions/filters/http/ext_proc/mutation_utils.h, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/mutation_utils_test.cc
This is a follow up commit for : https://github.com/envoyproxy/envoy/pull/28468.
It is to implement header forwarding disallow list feature for ext_proc filter.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Implement header forwarding disallow list feature for ext_proc filter.

source/extensions/clusters/original_dst/original_dst_cluster.cc, source/extensions/clusters/original_dst/original_dst_cluster.h, test/extensions/clusters/original_dst/original_dst_cluster_test.cc
Commit Message: Ensure original dst cluster is deleted on the main thread since it owns a main timer.
Risk Level: low, fixes violation of deletion on worker
Testing: regression
CC @howardjohn
=> original_dst cluster: post deletion to main

api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto, changelogs/current.yaml, source/extensions/filters/http/ext_authz/ext_authz.h, test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
Commit Message: Commit 664f3fce4730544f34ae767e10150fb6be11cdc6 changed how this data is handled, but was only intended to apply when calling grpc_service.
Testing: added new tests
Docs Changes: updated
[Optional Fixes #Issue] #27386
=> ext_authz: fix handling of non-UTF-8 bodies calling http_service

ci/upload_gcs_artifact.sh
This makes postsubmit work similar to how PRs currently work - ie uploads (docs/coverage/etc) are pushed to a path using the current commit hash, and the a redirect from the branch name is added
This will resolve a recent issue where coverage was failing in postsubmit but we lost the record of why
It also fixes github postsubmit publishing which is looking for the tarball in the wrong place
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: GCS postsubmit uploads use redirect

.github/actions/env/action.yml, .github/workflows/_env.yml
Currently its quite hard to associate a CI run <> PR 
This adds a link in the `env/repo::Print env` step to the PR and provides the environment with a pr number where appropriate 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/github: Improve PR/commit info in `env`

.github/actions/env/action.yml, .github/workflows/_env.yml, .github/workflows/_workflow-start.yml, .github/workflows/envoy-publish.yml
Unfortunately, ~the check was either not fixed previously or~ i broke it again - this should fix and prevent Prs from always showing pending for the `Verify/examples` stage
This also tightens the code for trusted runs by unsetting the checkout sha earlier in ci 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/github: Prevent github CI from staying `pending` (again)

test/server/BUILD, test/server/config_validation/BUILD
In #28366 we increased the sharding to resolve timeout issues in Envoy CI
that seems to have worked, but in mirror repos with less caching this is still timing out so this PR increases the sharding further
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/fuzz: Increase resources for failing fuzz_coverage tests

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/filter_test.cc
This is to address https://github.com/envoyproxy/envoy/issues/28568.
https://github.com/envoyproxy/envoy/pull/27812 added a streaming body test in ext_proc_integration_test.cc.   That test case is not really needed for that PR since all the gRPC call stats related test cases are already added in the filter_test.cc.  Removing that test from ext_proc_integration_test.cc for now.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Fixing ext_proc integration test timeout issue.

.azure-pipelines/stage/checks.yml
currently this is timeouting in low/non-cached CI runs
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/coverage: Increase timeout to 5 hours

api/contrib/envoy/extensions/filters/network/postgres_proxy/v3alpha/postgres_proxy.proto, docs/root/intro/arch_overview/other_protocols/postgres.rst
* note that upstream encryption is available in the overview
* mention the starttls transport socket requirement for upstream encryption
Signed-off-by: Raul Gutierrez Segales <rsegales@nvidia.com>
=> [postgres] improve docs

changelogs/current.yaml, source/common/quic/active_quic_listener.cc, source/common/quic/active_quic_listener.h, source/common/runtime/runtime_features.cc, test/common/quic/active_quic_listener_test.cc
Commit Message: add `envoy.reloadable_features.quic_reject_all` runtime guard to allow Envoy stop QUIC processing via Abseil flag --envoy_reloadable_features_quic_reject_all. The flag has default value false.
Additional Description: the runtime guard is a temporary solution which will be deprecated when QUICHE has its own flag to reject all traffic.
Testing: added new unit test 
Release Notes: edited
Runtime guard: envoy.reloadable_features.quic_reject_all
Follow up of #9230
=> quic: add a runtime guard to reject all traffic 

tools/code_format/check_format.py
`go get -u` is deprecated in this case. Run the previous command will get:
```
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
Commit Message: update installation of buildtools
Testing: N/A
Docs Changes:
Release Notes:
[Optional [API …
=> tools: update installation of buildtools

docs/root/intro/arch_overview/http/http3.rst, docs/root/intro/arch_overview/upstream/connection_pooling.rst
This should be failing on `main` not sure why its not - we defo have an error in our rst
This triggered the expected CI fail when reopening the 1.26 branch - confusing that its only happening there, and a bit troubling - seems like a sphinx bug, most likely in multicore support 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: Fix duplicate rst label

envoy/http/header_validator_errors.h, source/common/http/conn_manager_impl.cc, source/extensions/filters/network/http_connection_manager/config.cc, source/extensions/http/header_validators/envoy_default/header_validator.cc, source/extensions/http/header_validators/envoy_default/header_validator.h, source/extensions/http/header_validators/envoy_default/header_validator_factory.cc, source/extensions/http/header_validators/envoy_default/header_validator_factory.h, source/extensions/http/header_validators/envoy_default/http1_header_validator.cc, source/extensions/http/header_validators/envoy_default/http2_header_validator.cc, source/extensions/http/header_validators/envoy_default/path_normalizer.cc, test/extensions/filters/network/http_connection_manager/config_test.cc, test/extensions/http/header_validators/envoy_default/config_test.cc, test/extensions/http/header_validators/envoy_default/header_validator_test.h, test/extensions/http/header_validators/envoy_default/http1_header_validator_test.cc, test/extensions/http/header_validators/envoy_default/http2_header_validator_test.cc, test/extensions/http/header_validators/envoy_default/http_common_validation_test.cc, test/extensions/http/header_validators/envoy_default/path_normalizer_test.cc
Make UHV decoding of slashes in URL path consistent with existing implementation. Specifically:
* make it work independently from path normalization
* make UHV decode backslash (%5C)
Risk Level: Low, build flag protect
Docs Changes: proto doc
=> Make UHV consistent with existing decoding of slashes in the URL :path

test/extensions/common/async_files/mocks.h, tools/spelling/spelling_dictionary.txt
=> Add deduction guides to support compilers with ctad-maybe-unsupported warning enabled

source/common/http/conn_manager_impl.cc, source/extensions/http/header_validators/envoy_default/BUILD, source/extensions/http/header_validators/envoy_default/path_normalizer.cc, test/common/http/BUILD, test/common/http/conn_manager_impl_test.cc, test/common/http/conn_manager_impl_test_base.cc, test/common/http/conn_manager_impl_test_base.h, test/extensions/filters/http/ext_proc/filter_test.cc, test/extensions/filters/http/ext_proc/utils.h
This commit disabled legacy path normalization code when UHV is enabled (otherwise it is done twice). 
The big diff in the test/extensions/filters/http/ext_proc/filter_test.cc is a no-op and the change was needed to correct uses of relative namespaces after UHV header was added to one of the dependencies, causing namespace name collision.
=> UHV: Remove duplicated URL path normalization in UHV mode

source/common/common/assert.h
Commit Message: Add a new MOBILE_RELEASE_ASSERT macro to implement assertion for Envoy Mobile only
Additional Description: Sometimes when investigating an Envoy Mobile issue, it's helpful to add some assertions to make sure invariables are respected. Doing a normal RELEASE_ASSERT affects servers and puts a lot more at stake.
Testing: n/a
Platform Specific Features: Envoy mobile feature
=> add a new MOBILE_RELEASE_ASSERT macro to implement assertion for Envoy Mobile only

envoy/http/api_listener.h, mobile/library/common/http/client.cc, mobile/library/common/http/client.h, mobile/test/common/http/client_test.cc, source/common/http/conn_manager_impl.cc, source/common/http/conn_manager_impl.h, source/server/api_listener_impl.cc, source/server/api_listener_impl.h, test/integration/api_listener_integration_test.cc, test/mocks/http/api_listener.h
Add a RequestDecoderHandle type which is effectively a weak reference to a RequestDecoder. 
Attempt to clarify the lifetime of RequestDecoder in mobile.
Risk Level: Low - mobile only
=> Add a RequestDecoderHandle type which is effectively a weak reference to a RequestDecoder

.github/workflows/mobile-release.yml, .github/workflows/mobile_release.yml
The `mobile_release` workflow has been failing the last couple months: https://github.com/envoyproxy/envoy/actions/workflows/mobile_release.yml.  This is likely due to the `_env.yml` file missing from the job config, as the job fails due to clang toolchain failures.
Also, rename the file to `mobile-release.yml` since the convention is to use dashes, not underscores.
=> mobile: Fix the mobile_release CI workflow

contrib/golang/filters/http/source/go/pkg/http/capi_impl.go, contrib/golang/filters/http/source/go/pkg/http/filter.go, contrib/golang/filters/http/source/go/pkg/http/shim.go, contrib/golang/filters/network/source/go/pkg/network/shim.go
Since go module will ignore symlink:
https://github.com/golang/go/issues/39600#issuecomment-644487979
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bugfix: add the real api.h file into the include path

source/extensions/transport_sockets/tls/context_impl.cc
It was reverted in #28334, but it appears to be unrelated to coverage drop (which lead to reversion)
=> tls: Update the preprocessor macro check

source/common/config/utility.cc, source/common/config/utility.h
Commit Message: cleanup: moving checkApiConfigSourceNames to unnamed namespace
Minor cleanup moving checkApiConfigSourceNames to unnamed namespace.
Testing: N/A
=> cleanup: moving checkApiConfigSourceNames to unnamed namespace

bazel/external/boringssl_fips.BUILD, contrib/vcl/source/BUILD, distribution/BUILD, docs/BUILD, tools/base/envoy_python.bzl, tools/dependency/BUILD, tools/proto_format/BUILD
These parameters have been merged, with `exec_tools` the current behaviour
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel: Switch `exec_tools` -> `tools`

envoy/http/header_validator_errors.h, source/common/http/conn_manager_impl.cc, source/extensions/http/header_validators/envoy_default/config_overrides.h, source/extensions/http/header_validators/envoy_default/header_validator.cc, source/extensions/http/header_validators/envoy_default/header_validator.h, source/extensions/http/header_validators/envoy_default/http1_header_validator.cc, source/extensions/http/header_validators/envoy_default/http2_header_validator.cc, test/extensions/http/header_validators/envoy_default/http_common_validation_test.cc, test/integration/default_header_validator_integration_test.cc
Make UHV reject requests with %00 sequence in URL path for backward compatibility with the legacy path normalization.
Refactor common code from some methods.
Part of #26642
=> UHV: harmonize check for %00 with legacy path normalization

bazel/envoy_library.bzl, bazel/external/quiche.BUILD, envoy/stream_info/BUILD, source/common/common/BUILD, source/common/filesystem/BUILD, source/common/quic/platform/BUILD, source/extensions/filters/http/admission_control/evaluators/BUILD
Replaces implicit dependency on fmt_lib that is added to every target with explicit to just the targets that need it.
=> Remove implicit deps on fmt_lib

contrib/sip_proxy/filters/network/test/tra_test.cc
Commit Message: fix 28524
Risk Level:Low
Testing: Ut
[Optional Fixes #Issue] #28524 
=> [contrib-siporoxy] fix 28524

contrib/golang/filters/http/source/go/pkg/http/capi_impl.go, contrib/golang/filters/http/source/go/pkg/http/filter.go, contrib/golang/filters/http/source/go/pkg/http/shim.go, contrib/golang/filters/network/source/go/pkg/network/shim.go
Since go module will ignore symlink:
https://github.com/golang/go/issues/39600#issuecomment-644487979
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> backport PR 28722 to v1.27: bugfix: add the real api.h file into the include path

source/common/common/logger.h, source/common/http/conn_manager_impl.cc, source/common/http/http1/codec_impl.cc, source/common/http/http2/codec_impl.cc, source/common/network/tcp_listener_impl.cc, source/server/overload_manager_impl.cc, test/common/common/log_macros_test.cc, test/server/overload_manager_impl_test.cc
This is just https://github.com/envoyproxy/envoy/pull/28654 now that CI issues have been addressed.
Commit Message: Reduce log spam of load shed points if not configured.
Additional Description: LOG_ONCE_IF in the various callsites so each point gets logged about at most once.
=> Reduce log spam of load shed points if not configured.

.azure-pipelines/stage/checks.yml, .bazelrc, bazel/envoy_test.bzl, test/common/http/BUILD, test/common/http/http2/BUILD, test/extensions/clusters/redis/BUILD, test/extensions/filters/http/buffer/BUILD, test/extensions/filters/http/cache/BUILD, test/extensions/filters/http/csrf/BUILD, test/extensions/filters/http/custom_response/BUILD, test/extensions/filters/http/ext_proc/BUILD, test/extensions/filters/http/fault/BUILD, test/extensions/filters/http/file_system_buffer/BUILD, test/extensions/filters/http/grpc_field_extraction/BUILD, test/extensions/filters/http/health_check/BUILD, test/extensions/filters/http/jwt_authn/BUILD, test/extensions/filters/http/kill_request/BUILD, test/extensions/filters/http/rbac/BUILD, test/extensions/filters/http/tap/BUILD, test/extensions/filters/http/wasm/BUILD, test/extensions/filters/network/redis_proxy/BUILD, test/extensions/filters/network/thrift_proxy/BUILD, test/extensions/listener_managers/listener_manager/BUILD, test/extensions/transport_sockets/tls/BUILD, test/integration/BUILD
Sharding can help speed up bazel CI especially in the RBE case, but especially in the non-RBE case it can slow things done as it prevents jobs from running concurrently/together that otherwise could
One problem in envoy's ci is that a lot of tests have been configured to the slowest test-case - ie `tsan` - despite a lot of the tests not requiring the same limits/constraints/resources
This PR is the product of removing all of the bazel sizing attributes in a mostly non-cached environment and then selectively readding them as required
It brings the time for an uncached coverage run from ~4.5h -> <3h - the arm job is likely to similarly benefit
We can tweak the settings if we experience further flakes or for optimizing the RBE case in follow ups 
Risk …
=> ci/bazel: Optimize test sizings

changelogs/current.yaml, source/extensions/filters/network/connection_limit/connection_limit.cc
Commit Message: Fix UAF bug in connection limit filter.
Thanks to Haoruo Lei <haoruolei@microsoft.com> for pointing out the issue.
The issue is that the lambda's body deletes the timer which owns the lambda, and the lambda owners __this which is accessed in the next line. This is the fix as it should not mather if there's a delay what action we do when closing the connection -- the close event also handles resetting the time.
This is an issue that really should have been caught by ASAN but unfortunately due to the dtor of the lambda being trivial it won't do anything and no code will be emitted for it.
You can see simplified reproduction copies of this situation in the following:
1. We can see the __this is saved by the lambda in https://cppinsights.io/s/2559fe02 …
=> Fix UAF bug in connection limit filter.

test/extensions/filters/http/custom_response/BUILD, test/extensions/filters/http/ext_proc/BUILD, test/extensions/filters/http/rbac/BUILD, test/integration/BUILD
As ~expected some tests are now timeouting esp in tsan
This adds back some sharding to resolve issues that have come up so far
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/test: Add back some sharding

changelogs/current.yaml, source/common/quic/envoy_quic_client_stream.cc, source/common/quic/envoy_quic_client_stream.h, source/common/quic/envoy_quic_server_stream.cc, source/common/quic/envoy_quic_server_stream.h, source/common/quic/platform/quiche_flags_impl.cc, test/common/quic/envoy_quic_server_session_test.cc, test/common/quic/envoy_quic_server_stream_test.cc, test/integration/protocol_integration_test.cc, test/integration/quic_http_integration_test.cc
Commit Message: flip quic_reloadable_flag_quic_act_upon_invalid_header in QUICHE to enable request and response headers validation.
Additional Description: QUICHE reports invalid headers in callback `OnInvalidHeaders()` and Envoy will act based on configuration. Some invalid requests will be reset immediately instead of receiving 400 response.
Risk Level: high, request pipeline changed
Testing: existing tests 
Release Notes: changed.
Runtime guard: envoy.reloadable_features.FLAGS_envoy_quic_reloadable_flag_quic_act_upon_invalid_header
=> quic: enable headers validation in QUICHE

envoy/common/io/io_uring.h
My local build fails with the undefined std::function in the io_uring.h file. Not sure why this works for CI, maybe some slight different in my local setup. 
=> Include missing header

test/integration/filter_integration_test.cc, test/integration/protocol_integration_test.cc
`decode-headers-return-stop-all-watermark-filter` doesn't exist.
=> fix filter name decode-headers-return-stop-all-filter in comments

source/common/filter/config_discovery_impl.h, test/common/filter/config_discovery_impl_test.cc
Additional Description: Upstream network filters don't use the concept of terminal/non-terminal network filters. Separating downstream/upstream config provider implementations so that upstream don't validate terminal conditions.
=> ecds: no terminal check for upstream network filters

envoy/filter/BUILD, envoy/filter/config_provider_manager.h, source/common/filter/config_discovery_impl.cc, source/common/filter/config_discovery_impl.h, source/common/http/filter_chain_helper.h, source/common/router/router.h, source/common/upstream/upstream_impl.cc, source/extensions/filters/network/http_connection_manager/config.cc, source/extensions/listener_managers/listener_manager/listener_manager_impl.cc, test/common/filter/config_discovery_impl_test.cc
Additional Description: As described in: #28795, upstream filters use invalid reference to ``Upstream::ClusterManager`` which is a known issue by #26653. It seems like lack of ECDS with upstream HTTP filter integration tests did not capture this issue. A follow up will be adding integration tests for upstream HTTP filters with ECDS. Resolves #28795.
Testing: Unit tests, integration tests
=> ecds: fix upstream filters dynamic flows by explicitly passing ClusterManager object

contrib/golang/common/go/api/BUILD, contrib/golang/common/go/api/api.h, contrib/golang/common/go/api/logger.go, contrib/golang/common/log/BUILD, contrib/golang/common/log/cgo.cc, contrib/golang/common/log/cgo.h, contrib/golang/filters/http/source/BUILD, contrib/golang/filters/http/source/cgo.cc, contrib/golang/filters/http/source/go/pkg/http/capi_impl.go, contrib/golang/filters/http/source/golang_filter.cc, contrib/golang/filters/http/source/golang_filter.h, contrib/golang/filters/http/test/test_data/basic/config.go, contrib/golang/filters/http/test/test_data/basic/filter.go, contrib/golang/filters/network/source/BUILD
Now we can log sth without the HTTP request.
Some projects, like https://github.com/mosn/envoy-go-waf, require this feature so they can work properly.
Commit Message: move log funcs to global scope
Docs Changes:
Release Notes:
=> golang filter: move log funcs to global scope

mobile/WORKSPACE
Currently mobile has a pretty broken gazelle setup - it attempts to resolve modules in test data, trying to download bananas from fruit.io etc
This is an attempt to fix that (seems to work)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> deps/mobile: Bump `bazel_gazelle` -> 0.32.0

source/extensions/config_subscription/grpc/BUILD, source/extensions/config_subscription/grpc/grpc_collection_subscription_factory.cc, source/extensions/config_subscription/grpc/grpc_mux_context.h, source/extensions/config_subscription/grpc/grpc_mux_impl.cc, source/extensions/config_subscription/grpc/grpc_mux_impl.h, source/extensions/config_subscription/grpc/grpc_subscription_factory.cc, source/extensions/config_subscription/grpc/new_grpc_mux_impl.cc, source/extensions/config_subscription/grpc/new_grpc_mux_impl.h, source/extensions/config_subscription/grpc/xds_mux/BUILD, source/extensions/config_subscription/grpc/xds_mux/grpc_mux_impl.cc, source/extensions/config_subscription/grpc/xds_mux/grpc_mux_impl.h, test/common/config/grpc_subscription_test_harness.h, test/extensions/clusters/eds/eds_speed_test.cc, test/extensions/config_subscription/grpc/delta_subscription_impl_test.cc, test/extensions/config_subscription/grpc/delta_subscription_test_harness.h, test/extensions/config_subscription/grpc/grpc_mux_impl_test.cc, test/extensions/config_subscription/grpc/new_grpc_mux_impl_test.cc, test/extensions/config_subscription/grpc/xds_grpc_mux_impl_test.cc
Commit Message: grpc-mux: refactor c'tor arguments
Following #28273 this is a cleanup requested to pass c'tor parameters in a single struct.
Risk Level: low - refactor
Testing: N/A
=> grpc-mux: refactor c'tor arguments

.azure-pipelines/stage/verify.yml
Not sure how this ever worked but its related to some weird rbe issues i am seeing
Either way, the arm job shouldnt be using rbe
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/verify: Dont use RBE for arm verify job

test/integration/BUILD
The tests sometimes time out on CI, for example:
https://dev.azure.com/cncf/envoy/_build/results?buildId=145636&view=logs&j=d1f76054-8f79-554b-6f4a-11d6a63b8e00&t=a193292f-96b1-53c3-0505-a923ddcc3f84&l=4868.
Running `bazel test //test/integration:protocol_integration_test` also times out when I run it locally on my workstation.
Changing the test size from `large` to `enormous` results in the tests no longer timing out for me locally.  Hopefully the same will hold on CI.
=> tests: Declare the [quic_]protocol_integration_test `enormous` in Bazel

test/extensions/config_subscription/grpc/grpc_mux_impl_test.cc, test/extensions/config_subscription/grpc/new_grpc_mux_impl_test.cc, test/extensions/config_subscription/grpc/xds_grpc_mux_impl_test.cc
Otherwise this code fails with newer gtest
=> Fix checks for absl::optional state

.azure-pipelines/pipelines.yml
I had hoped that we could expire these independently but PRs that change the bazel version are failing as their cache is not working
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/cache: Expire bazel cache on version change

.bazelrc
I have a client who vendored this file into their Bazel workspace, and it caused every new machine to have a non-incremental build with all cache misses, due to the CI system (CircleCI in that case) injecting an unstable value into the PATH (`/tmp/circleci-launch-agent150557664/circleci-agent/1.0.193225-b3de599b/linux/amd64`)
Commit Message: Above
Risk Level: Unsure
Testing: Not familiar with this project, so whatever tests you normally run? The client says this change is green for them.
Docs Changes:
Release Notes:
=> fix(hermeticity): do not leak PATH to actions

api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
This is the API change to address issue: https://github.com/envoyproxy/envoy/issues/28698
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Adding API to disable ext_proc immedate response

source/common/router/config_impl.cc, source/common/router/config_impl.h
Commit Message: perf: move weighted clusters config instead of copy
Move a data-structure instead of copying it.
Testing: N/A.
=> perf: move weighted clusters config instead of copy

.azure-pipelines/bazel.yml, .azure-pipelines/cached.yml, .azure-pipelines/docker/load_caches.sh, .azure-pipelines/docker/prepare_cache.sh, .azure-pipelines/docker/prime_cache.sh, .azure-pipelines/pipelines.yml, ci/do_ci.sh
As we cant really expire bazelisk/bazel caches separately its simpler/more optimal to use a single bazel cache
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/caching: Simplify bazel cache

api/envoy/config/core/v3/protocol.proto
Commit Message:update comments on QUIC connection options protos
Additional Description: The new comments refer to where the connections options are defined.
Testing: n/a
=> [QUIC]update comments on QUIC connection options protos

docs/root/configuration/http/http_filters/json_to_metadata_filter.rst, source/extensions/filters/http/json_to_metadata/filter.cc, test/extensions/filters/http/json_to_metadata/filter_test.cc
Pure number or string is considered as a valid json body.
It that case, we should apply on_missing for all rules for  non-object json payload.
Testing: unit
=> json_to_metadata: apply on_missing for all rules for  non-object json payload

mobile/bazel/kotlin_test.bzl
Remove -Xcheck:jni from kotlin tests
As noted in #28981, //test/kotlin/integration:filter_throwing_exception_test produces tons of warnings which is causing tests to fail with new rules_java.
Risk Level: Low - Test only
=> mobile: Remove -Xcheck:jni from kotlin tests

source/common/router/header_parser_utils.cc, source/common/runtime/runtime_impl.cc, source/extensions/filters/udp/dns_filter/dns_filter_utils.cc
a += b + c + .. may introduce some unnecessary temp string.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> perf: use absl string append

source/common/http/BUILD, source/common/http/async_client_impl.cc, source/common/http/async_client_impl.h, source/common/http/null_route_impl.cc, source/common/http/null_route_impl.h, source/extensions/early_data/default_early_data_policy.h, test/common/http/async_client_impl_test.cc
Commit Message: Refactor NullRouteImpl out of async client. 
Testing:
Docs Changes:
Release Notes:
=> Refactor NullRouteImpl out of async client

source/common/http/http1/balsa_parser.cc, test/integration/integration_test.cc
Risk Level: Low, Balsa is not enabled by default
=> Make Balsa consistent with http-parser for multiple content-length check

.github/workflows/mobile-release.yml
The mobile Bazel options were updated in
https://github.com/envoyproxy/envoy/pull/28856, but the mobile_release workflow wasn't updated to use mobile-release-android. It was probably not caught by CI because it is a scheduled workflow that is run once a week as opposed to running on every PR.
=> ci: Update the mobile_release workflow with the changed config options

source/common/http/async_client_impl.cc, source/common/http/conn_manager_impl.cc, source/common/router/upstream_request.cc, source/common/stream_info/stream_info_impl.h, test/common/access_log/access_log_impl_test.cc, test/common/local_reply/local_reply_test.cc, test/common/stream_info/stream_info_impl_test.cc, test/extensions/access_loggers/file/config_test.cc, test/extensions/access_loggers/grpc/http_grpc_access_log_impl_test.cc, test/extensions/access_loggers/open_telemetry/access_log_impl_test.cc, test/extensions/access_loggers/stream/stream_test_base.h, test/fuzz/utility.h
Commit Message: Use the existing accessors instead of the direct field.
Testing: 
=> stream_info: encapsulate response_code_

mobile/test/non_hermetic/gcp_traffic_director_integration_test.cc
The test now uses API keys instead of JWT tokens, so removing an obsolete TODO.
=> mobile: Remove obsolete TODO on API keys

source/extensions/transport_sockets/tls/cert_validator/cert_validator.h, source/extensions/transport_sockets/tls/context_impl.cc, test/extensions/transport_sockets/tls/cert_validator/timed_cert_validator.cc
Callback can provide all the needed information besides existing address, such as stream info for logging and communication between extension point.
Pass the pointer to long lived object throughout the handshake (e.g., valid in [shutdownSsl](https://github.com/envoyproxy/envoy/blob/5fde158a3ae3d80a51bb826781e777dd781bd63f/source/extensions/transport_sockets/tls/ssl_socket.cc#L321)) .  PS: `ExtraValidationContext` is only a wrapper for passing argument.
=> cert_validator: Pass the callback through extra validation context 

test/integration/integration_tcp_client.cc
Return from waitForDisconnect immediately if connection was already disconnected.
=> Make waitForDisconnect more responsive

source/extensions/transport_sockets/tls/cert_validator/default_validator.cc, test/extensions/transport_sockets/tls/cert_validator/default_validator_test.cc
Have `DefaultCertValidator` return `NoClientCertificate` when `cert_chain` is empty.
=> Return NoClientCertificate in DefaultCertValidator

source/extensions/filters/http/set_metadata/config.cc, source/extensions/filters/http/set_metadata/config.h, test/extensions/filters/http/set_metadata/config_test.cc
Implements `createFilterFactoryFromProtoWithServerContextTyped` API for set_metadata filter. Actually this filter doesn't care/use the context object
=> set_metadata: Implement filter creation from server factory context

source/extensions/filters/common/ratelimit/ratelimit.h, source/extensions/filters/common/ratelimit/ratelimit_impl.cc, source/extensions/filters/common/ratelimit/ratelimit_impl.h, source/extensions/filters/http/ratelimit/ratelimit.cc, source/extensions/filters/network/ratelimit/ratelimit.cc, source/extensions/filters/network/thrift_proxy/filters/ratelimit/ratelimit.cc, test/extensions/filters/common/ratelimit/mocks.h, test/extensions/filters/common/ratelimit/ratelimit_impl_test.cc, test/extensions/filters/http/ratelimit/ratelimit_test.cc, test/extensions/filters/network/ratelimit/ratelimit_test.cc, test/extensions/filters/network/thrift_proxy/filters/ratelimit/ratelimit_test.cc
Commit Message: Adds support for passing hits_addend to ratelimit grpc client for weighted ratelimit request.
Additional Description: Note: This only modifies the grpc client. The ratelimit filter's behavior remains unchanged in this PR.
[Optional Runtime guard:] N/A. Added default argument to 0 so ratelimit filter's behavior will remain unchanged.
=> Adds support for passing hits_addend to ratelimit grpc client

docs/root/operations/tools/route_table_check_tool.rst, test/tools/router_check/coverage.cc, test/tools/router_check/coverage.h, test/tools/router_check/router.cc, test/tools/router_check/router.h, test/tools/router_check/router_check.cc, test/tools/router_check/test/config/DetailedCoverage.golden.proto.json, test/tools/router_check/test/config/DetailedCoverage.yaml, test/tools/router_check/test/route_tests.sh
route_check_tool: add new detailed-coverage flag
Add a new flag to enable displaying/printing not covered routes in non-comprehensive code coverage mode. 
Currently,  you can see missing tests/not covered routes only if you use comprehensive code coverage mode (--covall). These changes enable this feature for non-comprehensive mode.
`route_table_check_tool.rst` has been updated
Fixes #28709
=> route_check_tool: add new detailed-coverage flag

source/common/common/logger.h, test/common/common/logger_test.cc
Additional Description: in case ``ENVOY_TAGGED_STREAM_LOG_TO_LOGGER`` and ``ENVOY_TAGGED_CONN_LOG_TO_LOGGER`` are used with inline tags, e.g., ``ENVOY_TAGGED_CONN_LOG(info, (std::map<std::string, std::string>{{"key_inline", "val"}}), connection_, "fake message")``, the printed log will only include tags from the inline map, and will not include the connection/stream ID tags. The PR fixes this so both the inline tags as well as the connection/stream ID are included in the output tags.
=> logs: fix tagged logs macros for inline usage

envoy/common/BUILD, envoy/http/BUILD, envoy/stats/BUILD, source/common/network/BUILD, source/extensions/access_loggers/common/BUILD
This makes the targets that need it more explicit.
=> Split out optref into a dedicated target

api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto, changelogs/current.yaml, source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, test/extensions/filters/http/ext_proc/filter_test.cc
This is implementation to address issue: https://github.com/envoyproxy/envoy/issues/28698.
It's a follow up PR of https://github.com/envoyproxy/envoy/pull/28907
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Implementaion of ext_proc filter disable immediate response

docs/root/configuration/other_features/vcl.rst
**Commit Message:**  Improve the documentation on the minimum configuration of vpp
**Additional Description:** The vpp minimization configuration given on the official website does not enable the session layer, which will cause envoy to fail to register with vpp when it is started in vcl mode, because the session layer of vpp is disabled by default, although vpp can also enable session enbale through cli, but for People who do not have a deep understanding of vpp are prone to encounter some pitfalls, so improve the minimum configuration document of vpp
Testing:
Release Notes:
[Optional Fixes #26085 ] 
[Optional [API …
=> Improve the minimal configuration of vpp (#26085)

source/extensions/filters/http/header_to_metadata/header_to_metadata_filter.cc, source/extensions/filters/network/thrift_proxy/filters/header_to_metadata/header_to_metadata_filter.cc, source/extensions/filters/network/thrift_proxy/filters/payload_to_metadata/payload_to_metadata_filter.cc, source/extensions/filters/network/thrift_proxy/filters/payload_to_metadata/payload_to_metadata_filter.h, test/extensions/filters/http/header_to_metadata/header_to_metadata_filter_test.cc, test/extensions/filters/network/thrift_proxy/filters/header_to_metadata/config_test.cc, test/extensions/filters/network/thrift_proxy/filters/header_to_metadata/header_to_metadata_filter_test.cc, test/extensions/filters/network/thrift_proxy/filters/payload_to_metadata/payload_to_metadata_filter_test.cc
inspired by #28394, apply reviewer's suggestion to existing metadata handling filters.
Testing: existing unit
=> header_to_metadata: refactor to preferred style

.azure-pipelines/stage/checks.yml
This reverts commit 8d48ccd79683ba5e2cb2a550c4bb0885a6d78ce6.
Per discussion with other maintainers, the unblock of coverage is rolled back. Given that the approach of using RBE caches for coverage seems to be  solving the issue, it is ok to block PRs from submitting until the coverage build is restored.
=> Revert "ci/coverage: Temporarily disable coverage requirement (#29112)"

source/extensions/tracers/skywalking/trace_segment_reporter.cc, test/extensions/tracers/skywalking/trace_segment_reporter_test.cc
Commit Message: Fix the memory leak in skywalking trace reporter
Additional Description: The flow control based on `onAboveWriteBufferHighWatermark` did not work before. When the skywalking server does not read data, the grpc stream will always accumulate tracing data until OOM.
Risk Level: Mid
Docs Changes:
Release Notes:
=> fix the memory leak in skywalking trace reporter

CODEOWNERS
Due to github issue, none of current code owners of ext_proc will receive automatic notifications for PRs, except @mattklein123 .(Maintainer who have write access)
Add @htuch 
(IMHO, that will be great if we can workaround this github issue as it applies to all the extensions.)
=> Add htuch to code owner of ext_proc

.azure-pipelines/stage/checks.yml, .azure-pipelines/stages.yml, .bazelrc, mobile/.bazelrc
- Use RBE for coverage tests
- Switch coverage VMs to ms-hosted small
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel/coverage: Test remotely

tools/deprecate_version/deprecate_version.py
Turns out we only filed bugs for reloadable flags not restart flags, sigh.
=> tooling: handling restart flag deprecation

api/envoy/config/trace/v3/opencensus.proto, changelogs/current.yaml, source/extensions/extensions_metadata.yaml, test/extensions/tracers/opencensus/config_test.cc
related to #9958 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tracing: Deprecate Opencensus (@1.30)

mobile/examples/cc/fetch_client/BUILD
mobile: Remove bogus target in mobile/examples/cc/fetch_client/BUILD
Testing: N/A
=> mobile: Remove bogus target in mobile/examples/cc/fetch_client/BUILD

changelogs/current.yaml, source/common/http/filter_manager.cc, source/common/http/filter_manager.h, test/extensions/filters/http/ext_proc/streaming_integration_test.cc, test/integration/filter_integration_test.cc, test/integration/http_protocol_integration.h
Commit Message: Clean up: Remove http_filter_avoid_reentrant_local_reply runtime guard.
Additional Description: na
Testing: ran tests
Release Notes: inc
Fixes #29095
=> Clean up: Remove http_filter_avoid_reentrant_local_reply runtime guard.

contrib/golang/filters/network/source/golang.cc, contrib/golang/filters/network/source/upstream.cc, contrib/golang/filters/network/test/filter_test.cc, contrib/golang/filters/network/test/upstream_test.cc
Commit Message: fix go network extension close without reason
Testing: N/A
=> fix go network extension close without reason

source/common/upstream/cluster_manager_impl.cc, test/integration/eds_integration_test.cc
load balancer factory provided.
Commit Message: Config: preserve the load balancer factory when merging CIOs if there's no new load balancer factory provided.
Risk Level: low / med 
Testing: modified test include testing this behavior
[Optional Runtime guard:] Config guarded feature
=> Config: preserve the load balancer factory when merging CIOs if there's no new

envoy/server/factory_context.h, envoy/server/filter_config.h, source/common/filter/config_discovery_impl.h, source/common/http/filter_chain_helper.h, source/common/router/BUILD, source/common/router/router.h, source/common/router/upstream_codec_filter.h, source/common/upstream/BUILD, source/common/upstream/upstream_factory_context_impl.h, source/common/upstream/upstream_impl.cc, source/common/upstream/upstream_impl.h, source/extensions/filters/http/common/factory_base.h, test/common/filter/config_discovery_impl_test.cc, test/common/upstream/cluster_manager_impl_test.cc, test/extensions/filters/http/buffer/config_test.cc, test/extensions/filters/http/common/empty_http_filter_config.h, test/integration/cluster_filter_integration_test.cc, test/integration/filters/add_header_filter.cc, test/mocks/server/factory_context.cc, test/mocks/server/factory_context.h
Additional Description: Rename ``UpstreamHttpFactoryContext`` to ``UpstreamFactoryContext`` and change upstream network filters factory to use ``UpstreamFactoryContext``. The goal is saving from code duplication and creating a factory context for network filters which is not needed.
Testing: None
=> upstream filters: change upstream factory context to fit network filters

source/common/formatter/BUILD, source/common/formatter/http_specific_formatter.cc, source/common/formatter/http_specific_formatter.h, source/common/formatter/stream_info_formatter.cc, source/common/formatter/stream_info_formatter.h, source/common/formatter/substitution_format_utility.cc, source/common/formatter/substitution_format_utility.h, source/common/formatter/substitution_formatter.cc, source/common/formatter/substitution_formatter.h, source/extensions/access_loggers/common/stream_access_log_common_impl.h, source/extensions/access_loggers/file/config.cc, source/extensions/formatter/metadata/metadata.cc, source/extensions/formatter/req_without_query/req_without_query.cc, source/server/configuration_impl.cc, test/common/formatter/substitution_formatter_speed_test.cc, test/common/formatter/substitution_formatter_test.cc, test/common/http/conn_manager_impl_test_base.cc, test/server/admin/admin_instance.cc, test/server/admin/admin_test.cc, tools/code_format/config.yaml
Commit Message: formatter: move context independent util function/class to seperated source file
First sub PR that splited out from #29021 
This PR is simple refactor to move some utility function/class to seperated source file. This is necessary because the templated formatter will change the deps of different libs.
Testing: n/a.
=> formatter: move context independent util function/class to seperated source file

changelogs/current.yaml, source/extensions/filters/network/redis_proxy/router_impl.cc, test/extensions/filters/network/redis_proxy/router_impl_test.cc
Revert "redis_proxy: fix crash if catch_all_route is not defined (#29138)"
This reverts commit 1438a10da220f32b3c29219c2afda42287e162cf.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Revert "redis_proxy: fix crash if catch_all_route is not defined (#29138)

api/bazel/repository_locations.bzl, bazel/repository_locations.bzl
Docs Changes: Fix license URLs
=> docs: fix the license URLs of client_model, flatbuffers and hyperscan

changelogs/current.yaml, envoy/ssl/ssl_socket_extended_info.h, source/extensions/transport_sockets/tls/context_impl.cc, source/extensions/transport_sockets/tls/ssl_handshaker.cc, source/extensions/transport_sockets/tls/ssl_handshaker.h, test/extensions/transport_sockets/tls/cert_validator/test_common.h, test/extensions/transport_sockets/tls/ssl_socket_test.cc
Commit Message: tls: fix handshake failure when both private key provider and cert validation are set
Additional Description: See #29002
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [backport/1.27] tls: fix handshake failure when both private key provider and cert validation are set

examples/front-proxy/docker-compose.yaml, examples/shared/envoy/Dockerfile
Commit Message: front-proxy sandbox adds service envoy healthcheck
Additional Description: main purpose to pass this idea by phlax
Testing: the front-proxy sandbox's verify.sh script
Release Notes: revise front-proxy sandbox front-envoy to depend on service envoy healthy
=> front-proxy sandbox adds service envoy healthcheck

changelogs/current.yaml, envoy/ssl/ssl_socket_extended_info.h, source/extensions/transport_sockets/tls/context_impl.cc, source/extensions/transport_sockets/tls/ssl_handshaker.cc, source/extensions/transport_sockets/tls/ssl_handshaker.h, test/extensions/transport_sockets/tls/cert_validator/test_common.h, test/extensions/transport_sockets/tls/ssl_socket_test.cc, test/per_file_coverage.sh
Commit Message: tls: fix handshake failure when both private key provider and cert validation are set
Additional Description: See #29002
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [backport/1.26] tls: fix handshake failure when both private key provider and cert validation are set

changelogs/current.yaml, envoy/ssl/ssl_socket_extended_info.h, source/extensions/transport_sockets/tls/context_impl.cc, source/extensions/transport_sockets/tls/ssl_handshaker.cc, source/extensions/transport_sockets/tls/ssl_handshaker.h, test/extensions/transport_sockets/tls/cert_validator/test_common.h, test/extensions/transport_sockets/tls/ssl_socket_test.cc
Commit Message: tls: fix handshake failure when both private key provider and cert validation are set
Additional Description: See #29002
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [backport/1.25] tls: fix handshake failure when both private key provider and cert validation are set

bazel/wasm/wasm.bzl
The change has been made in Bazel in 2020, so it should be safe to rename.
Commit Message: Rename whitelist to allowlist
Additional Description: The change has been made in Bazel in 2020, so it should be safe to rename.
Testing: manual testing
=> Rename whitelist to allowlist

source/extensions/http/cache/file_system_http_cache/insert_context.cc, source/extensions/http/cache/file_system_http_cache/insert_context.h, test/extensions/filters/http/cache/http_cache_implementation_test_common.cc, test/extensions/http/cache/file_system_http_cache/file_system_http_cache_test.cc
Commit Message: Remove redundant queue from FileSystemHttpCache
Since a queue was added to the http cache filter in #26841, the file system cache implementation no longer needs its own queue. Removing this redundant queue is also necessary to fully address https://github.com/envoyproxy/envoy/issues/29064.
Risk Level: Low; WIP filter and unit test coverage.
Testing: Modified unit tests, removed coverage for things that no longer exist, and ensured existing coverage still applies for what remains.
=> Remove redundant queue from FileSystemHttpCache

source/extensions/config_subscription/grpc/BUILD
Commit Message: config subscription: make grpc_mux_lib an extension
Testing: N/A
My envoy deployment overrides `extensions_build_config.bzl`. After upgrading from v1.25 v1.27, we saw the following error when starting envoy
```
2023-08-16_06:40:39.05042 [2023-08-16 06:40:39.050][123041][critical][main] [external/envoy/source/server/server.cc:134] error initializing config 'config.yaml': envoy.config_mux.grpc_mux_factory not found
```
This PR makes `grpc_mux_lib` an extension so that we can include `envoy.config_mux.grpc_mux_factory` in our `extensions_build_config.bzl`, which resolves the error.
=> config subscription: make grpc_mux_lib an extension

bazel/foreign_cc/luajit.patch
The "make" binary that is referenced by the environment variable "MAKE" must be used to build LuaJIT, not the "make" binary of the system.
The build rules of "rules_foreign_cc" create an own "make" binary (currently GNU Make 4.3). The "MAKE" environment variable references this binary.
LuaJIT's Makefile uses "make" recursively:
default all $(INSTALL_DEP):
@echo "==== Building LuaJIT $(VERSION) ===="
$(MAKE) -C src
This means that at this point, the "make" binary referenced by the "MAKE" environment variable will be invoked.
The system's "make" binary may be newer than the "make" of "rules_foreign_cc" (e.g. GNU Make 4.4 vs GNU Make 4.3), and this can lead to errors, because the newer "make" passes information in the "MAKEFLAGS" environment variable to the older "make", and the older "make" …
=> build: use the correct "make" binary for building LuaJIT

source/extensions/filters/http/cache/cache_filter.cc, source/extensions/filters/http/cache/cache_filter.h, source/extensions/filters/http/cache/cache_insert_queue.cc, source/extensions/filters/http/cache/cache_insert_queue.h, source/extensions/filters/http/cache/config.cc, source/extensions/http/cache/file_system_http_cache/file_system_http_cache.h, test/extensions/filters/http/cache/cache_filter_test.cc, test/extensions/filters/http/cache/http_cache_test.cc
Commit Message: Fix http cache crash on config reload (part 1)
With the presence of a queue, it is no longer enough for a cache to outlive the filter, it must also outlive the queue that can outlive the filter.
This was already a problem for file_system_http_cache because it already contained a queue that could outlive the filter, but it has just been noticed in #29064 which I guess is the first time the cache has been used in conjunction with a dynamic configuration that causes the cache instance to be removed and re-added.
This change fixes it so that a cache shared pointer is persisted into the queue object, ensuring its lifetime is long enough for all actions to complete. The cleanup in which file_system_http_cache's now redundant queue is removed will still …
=> Fix http cache crash on config reload (part 1)

source/common/formatter/stream_info_formatter.cc, source/common/protobuf/create_reflectable_message.cc, source/common/protobuf/protobuf.h, source/common/protobuf/utility.cc, source/common/protobuf/utility.h, source/exe/process_wide.cc, test/mocks/grpc/mocks.h, test/test_common/utility.h
Change `#ifdef ENVOY_ENABLE_FULL_PROTOS` to `#if defined(ENVOY_ENABLE_FULL_PROTOS)`, 
and `#ifndef ENVOY_ENABLE_FULL_PROTOS` to `#if !defined(ENVOY_ENABLE_FULL_PROTOS)`
in order to improve readability.
Risk Level: N/A - No behavior change
Testing: N/A
=> Use #if defined(ENVOY_ENABLE_FULL_PROTOS instead of #ifdef ENVOY_ENABLE_FULL_PROTOS to be more readable

source/extensions/filters/http/json_to_metadata/filter.cc, test/extensions/filters/http/json_to_metadata/filter_test.cc
Commit Message: the metadata can be used in the RouteMatch configuration, so need to call clearRouteCache() if some metadata is added
Docs Changes:
Release Notes:
=> clear route cache in json_to_metadata filter

envoy/ssl/handshaker.h, source/extensions/transport_sockets/tls/ssl_handshaker.cc, source/extensions/transport_sockets/tls/ssl_socket.cc, source/extensions/transport_sockets/tls/ssl_socket.h, test/extensions/transport_sockets/tls/handshaker_test.cc, test/extensions/transport_sockets/tls/ssl_socket_test.cc
Backport of #29263
Fixes #28415
This reverts part of #24923
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [1.27 backport] tls: Remove additional tracking on SSL_ERROR_SYSCALL

test/common/formatter/command_extension.cc, test/common/formatter/command_extension.h, test/common/formatter/substitution_format_string_test.cc, test/common/formatter/substitution_formatter_fuzz_test.cc, test/common/formatter/substitution_formatter_speed_test.cc, test/common/formatter/substitution_formatter_test.cc, test/extensions/formatter/cel/cel_test.cc, test/extensions/formatter/metadata/metadata_test.cc, test/extensions/formatter/req_without_query/req_without_query_test.cc
Commit Message: code cleanup 1: update all `format` to `formatWithContext` in the tests
After adding templated formatter support, a new `HttpFormatterContext` is introduced to suppies necessary data like request headers, response headers to the formatter.
In the previous PR (#29201), to simplify the review, HTTP template specialization is introduced. All HTTP formatter could still use the old interfaces.
**But I still want to cleanup all the old interface usages and finally remove the HTTP template specialization. This PR cleaned up all these code in the tests first.**
**Note, this is tests only change and in current implementation, the new `formatWithContext` is implemented as to call `format` method directly. So, this change will note reduce the code test …
=> code cleanup 1: update all `format` to `formatWithContext` in the tests

test/common/formatter/substitution_formatter_test.cc
Commit Message: fix test failure because the sync of multiple commits
#28804 and #29314 introduced a test fature because they update same file and don't result in conflict.
Testing: n/a.
=> fix test failure because the sync of multiple commits

mobile/library/common/jni/jni_interface.cc, mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java, mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyEngine.java, mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java, mobile/library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java, mobile/library/java/org/chromium/net/impl/BUILD, mobile/library/java/org/chromium/net/impl/CronvoyEngineBuilderImpl.java, mobile/library/java/org/chromium/net/impl/CronvoyLogger.java, mobile/library/java/org/chromium/net/impl/CronvoyUrlRequestContext.java, mobile/library/java/org/chromium/net/impl/NativeCronvoyEngineBuilderImpl.java, mobile/library/kotlin/io/envoyproxy/envoymobile/mocks/MockEnvoyEngine.kt, mobile/test/java/org/chromium/net/BidirectionalStreamTest.java, mobile/test/java/org/chromium/net/CronetUrlRequestContextTest.java, mobile/test/java/org/chromium/net/impl/BUILD, mobile/test/java/org/chromium/net/impl/CronvoyLoggerTest.java, mobile/test/java/org/chromium/net/testing/NativeTestServer.java
This has 2 major changes for Cronvoy.
1) turn logs off by default (theoretically no-op for optimized build, but avoids context switching for non-opt)
2) wait for engine creation before allowing further down-calls. This avoids a race condition where logging is changed before the engine is created but also will slow app start-up.  We can revisit and do per-downcall waits if necessary
Risk Level: low (off by default)
Testing: basic tests
=> mobile: adding a cronvoy logger

envoy/formatter/substitution_formatter.h, source/common/formatter/substitution_formatter.h, source/common/local_reply/local_reply.cc, source/common/router/header_formatter.h, source/common/tcp_proxy/tcp_proxy.cc, source/extensions/access_loggers/common/file_access_log_impl.cc, source/extensions/access_loggers/open_telemetry/substitution_formatter.cc, source/extensions/filters/http/oauth2/filter.cc, source/extensions/filters/network/ratelimit/ratelimit.cc, source/extensions/http/custom_response/local_response_policy/local_response_policy.cc, source/extensions/matching/actions/format_string/config.cc, test/extensions/formatter/cel/cel_test.cc, test/extensions/formatter/req_without_query/req_without_query_test.cc
Commit Message: code cleanup 2: update all format to formatWithContext in the source and remove unnecessary specialization
Related PR: #29314.
After adding templated formatter support, a new `HttpFormatterContext` is introduced to suppies necessary data like request headers, response headers to the formatter.
In the previous PR (#29201), to simplify the review, HTTP template specialization is introduced. All HTTP formatter could still use the old interfaces.
**But I still want to cleanup all the old interface usages and finally remove the HTTP template specialization. This PR cleaned up all these code in the tests first.**
**Note, this is tests only change and in current implementation, the new `formatWithContext` is implemented as to call `format` method directly. …
=> code cleanup 2: update all format to formatWithContext in the source and remove unnecessary specialization

test/integration/protocol_integration_test.cc
Commit Message: fix a data race between the SocketInterfaceSwap object destruction race and the fake upstream QUIC connection sending. So explicitly clean up the upstream connection before exiting the test body.
Testing: passed with 1000 runs
Platform Specific Features: N/A 
Fixes #29191
=> test: deflake a HTTP/3 test with SocketInterfaceSwap

source/common/http/match_delegate/config.cc, source/common/router/config_impl.cc
proto: Use GetTypeName() instead of GetDescriptor to be compatible with lite protos
=> proto: Use GetTypeName() instead of GetDescriptor to be compatible with lite protos

.azure-pipelines/pipelines.yml, .azure-pipelines/stages.yml
This runs all checks concurrently and should speed up CI
As we have mostly resolved the vm contention issue this should be safe to do - i will watch the wait times for the related pool and we can revert if its delaying PRs
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/checks: Increase concurrency

test/integration/autonomous_upstream.cc, test/integration/autonomous_upstream.h, test/integration/fake_upstream.h, test/integration/http_integration.cc
Commit Message: it's a potential fix to https://github.com/envoyproxy/envoy/issues/29191#issuecomment-1702384740. No matter whether it fixes the issue or not, it should improve test speed under TSAN.
Fixes #29191
=> test: fix contention in HttpIntegrationTest::testLargeRequestHeaders

source/server/options_impl.cc
Previously, envoy flag help texts started with a mix of upper- and lower-case letters. Now, all help
texts start with upper-case.
This PR also adds a hyphen to one instance of "comma-separated".
Commit Message: Previously, envoy flag help texts started with a mix of upper- and lower-case letters. Now, all help
texts start with upper-case. This PR also adds a hyphen to one instance of "comma-separated".
Testing: None
Docs Changes: Docs-only change. See commit message.
=> docs: fix grammar errors in cli help texts

source/exe/terminate_handler.cc, test/exe/terminate_handler_test.cc
This does lose us a bit of granularity but non-Envoy throws are few and far between so I think consistency outweighs?
Testing: updated test
=> terminate_handler: using try macros

envoy/grpc/async_client_manager.h, source/common/grpc/async_client_manager_impl.cc, source/common/grpc/async_client_manager_impl.h, source/extensions/filters/http/ext_authz/config.cc, test/common/grpc/BUILD, test/common/grpc/async_client_manager_benchmark.cc, test/common/grpc/async_client_manager_impl_test.cc, test/extensions/filters/http/ext_authz/config_test.cc, test/mocks/grpc/mocks.h
Commit Message: Optimize AsyncClientManager by moving hashing to control plane
Additional Description: This change removes the hashing of the config away from the data plane on every request to the control plane when the filter callback is created. This is accomplished by creating a wrapper object for the config which precomputes the hash and also serializes it to string ahead of time so that calls to the AsyncClientManager with that wrapper can avoid unnecessary overhead.
Testing: Changed some ext_authz tests to account for changes
Added a benchmark test that observed the following improvement
Benchmark                                         Time             CPU   Iterations
testGetOrCreateAsyncClientWithConfig          27199 us        27182 us            1 …
=> Optimize AsyncClientManager by moving hashing to control plane

test/extensions/filters/http/grpc_json_transcoder/grpc_json_transcoder_integration_test.cc
By default UHV now accepts [] that gRPC transcoder needs.
Part of #23291
=> gRPC transcoder now works with UHV

source/extensions/common/wasm/BUILD, source/extensions/common/wasm/context.cc, source/extensions/common/wasm/context.h, source/extensions/common/wasm/ext/BUILD, source/extensions/common/wasm/ext/set_envoy_filter_state.proto, source/extensions/common/wasm/foreign.cc, test/extensions/common/wasm/BUILD, test/extensions/common/wasm/foreign_test.cc
Proxy wasm supports setProperty method. However that method always prefixes all property keys with `wasm.`. So currently there's no way to set envoy filter state from wasm which prevents from using it for some scenarios (like chaining a custom network wasm filter with tcp proxy filter and setting `envoy.tcp_proxy.cluster` filter state to select upstream cluster).
This change adds a new wasm foreign function `set_envoy_filter_state` and uses the [object factory to create filter state objects](https://github.com/envoyproxy/envoy/pull/29030).
Related Issue: https://github.com/envoyproxy/envoy/issues/28673
Commit Message: Add set_envoy_filter_state proxy wasm foreign function
Additional Description: Adds a proxy wasm foreign function to set envoy filter state
Risk Level:
Testing:
Docs …
=> Add set_envoy_filter_state proxy wasm foreign function

support/hooks/pre-push
Additional Description: The changes in https://github.com/envoyproxy/envoy/pull/29397 broke the pre-push hook. This changes that hook to use the new bazel target
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> fix push hook to use the new bazel-y check format call

contrib/golang/filters/http/source/go/pkg/http/capi_impl.go, contrib/golang/filters/http/source/go/pkg/http/cgo_go122.go, contrib/golang/filters/network/source/go/pkg/network/cgo_go122.go
they could prevent the Go compiler from allocating function parameters on the heap.
`noescape` and `nocallback` are new go1.22 cgo directives that help the Go compiler make better decisions. See https://github.com/golang/go/issues/56378 for more context.
=> golang extension: optimization: added noescape and nocallback directives for C functions.

.azure-pipelines/bazel.yml, .azure-pipelines/pipelines.yml
Currently ci uses `.devcontainer/Dockerfile` for the docker cache key, but `.bazelrc` is actually more reliable
The cache is currently broken as `.devcontainer/Dockerfile` changed and it confused ci
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/cache: Use `.bazelrc` for docker cache key

.azure-pipelines/docker/prime_cache.sh, .azure-pipelines/pipelines.yml
Currently if only docker changed and not bazel its creating an empty cache, this should fix
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/cache: Fix cache priming for Docker only

source/common/upstream/BUILD, source/common/upstream/upstream_impl.cc, source/extensions/transport_sockets/http_11_proxy/BUILD, test/common/upstream/BUILD, test/common/upstream/upstream_impl_test.cc, test/extensions/transport_sockets/http_11_proxy/connect_integration_test.cc
quic: Use name() instead of DebugString() when checking that the QUIC transport socket is configured
=> quic: Use name() instead of DebugString() 

mobile/test/cc/integration/lifetimes_test.cc, mobile/test/cc/integration/send_headers_test.cc
This updates the `lifetimes_test` and `send_headers_test` to use `EngineBuilder` directly instead of `TestEngineBuilder`. `TestEngineBuilder` will soon be removed.
Risk Level: low (clean up)
=> mobile: Remove the use of TestEngineBuilder from the lifetimes_test and send_headers_test.

source/common/buffer/BUILD, source/common/buffer/buffer_util.cc, source/common/buffer/buffer_util.h, source/common/json/BUILD, source/common/json/json_streamer.cc, source/server/admin/stats_render.cc, test/common/buffer/BUILD, test/common/buffer/buffer_util_test.cc
Commit Message: A performance regression was found in a late commit as part of #28988 where we switched from a low-precision fast serialization of doubles (absl::StrCat) to a high-precision slow serialization of doubles (absl::StrFormat("%.15g", ...). This resolves that issue using std::to_chars which is faster than absl::StrCat and is also high precision. The downside is it doesn't work on all platforms, so an intermediate high-precision medium-speed solution was found for Apple and GCC. The serialize-double-to-buffer functionality is moved out of Json::Streamer and into a new Buffer::Util namespace.
Latest Json histogram serialization performance:
```
------------------------------------------------------------------------
Benchmark                              Time             CPU …
```
=> buffer: use std::to_chars for serializing doubles

.azure-pipelines/bazel.yml, .azure-pipelines/cached.yml, .azure-pipelines/docker/create_cache.sh, .azure-pipelines/docker/load_caches.sh, .azure-pipelines/docker/prepare_cache.sh, .azure-pipelines/docker/prime_cache.sh, .azure-pipelines/docker/save_cache.sh, .azure-pipelines/pipelines.yml, .azure-pipelines/stage/checks.yml, .azure-pipelines/stage/linux.yml, .azure-pipelines/stage/prechecks.yml, .azure-pipelines/stage/publish.yml, .azure-pipelines/stage/verify.yml, ci/do_ci.sh
This PR makes a number of changes to CI esp wrt to caching
Essentially it revives per-job caches, but also retains the precaches of docker and a minimal bazel fetch
The bazel precache is slimmed down
Whenever a cache is not available for a job it will instead use either/both of the precaches
As the github download issue is still there it also allows the jobs to run (retriable) bazel fetch before running the actual job
All ci jobs that previously invoked `./ci/do_ci.sh bazel.$JOBNAME` now just invoke with the job name and a deprecation message has been added to `do_ci.sh` - this simplifies a number of things
I have experimented quite a bit to derive the best fetches for precache and individual jobs - this will most likely iterate once we have the framework for pre and per-job caching …
=> ci/caching: Optimize bazel cache/fetch

changelogs/current.yaml, source/extensions/filters/udp/udp_proxy/session_filters/filter.h, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h, test/extensions/filters/udp/udp_proxy/BUILD, test/extensions/filters/udp/udp_proxy/mocks.h, test/extensions/filters/udp/udp_proxy/session_filters/BUILD, test/extensions/filters/udp/udp_proxy/session_filters/buffer_filter.h, test/extensions/filters/udp/udp_proxy/session_filters/buffer_filter.proto, test/extensions/filters/udp/udp_proxy/udp_proxy_integration_test.cc
Additional Description: Part of the UDP tunneling effort (#29277). This PR adds the option to inject datagrams downstream/upstream from a UDP session filter. This allows UDP session filters to buffer datagrams for arbitrary purposes while returning ``StopIteration`` and then flushing the buffered datagrams when the filter is ready to continue, for example, due to async callback. An example use case would be a dynamic forward proxy filter that will create a DNS request, waiting for a DNS response, allowing datagrams received meanwhile to be buffered until the response is ready.
Testing: Integration tests
=> udp_session_filters: add callback to inject read/write datagrams to filter chain

changelogs/current.yaml, source/common/network/io_socket_handle_impl.cc
Commit Message: On some versions of macOS, `getpeeraddr` returns a length of 3, which is enough to read the `ss_family` and include a 1-byte `sun_path`, but Envoy was incorrectly treating this as invalid. This resulted in an uncaught exception.
Testing: Existing tests cover this
Docs Changes:
=> network: fix bug in unix-domain socket peerAddress() on macOS

source/common/buffer/buffer_util.cc
Commit Message: In #29500 I introduced a conditional-compilation for using the best available library API to serialize doubles. This is because clang library v14, the primary development platform, has a better API available than older compilers.
The conditional compilation structure I used focused on excluding GCC and Apple, and that passed on CI.
However, the ifdefing didn't quite work for people that develop with older version of clang, or hybrid library environments. I did not think people would be doing that, but they are :) So this changes the conditional compilation strategy to look specifically for clang library versions >= 14.
Testing: just CI
=> buffer: use compiler version rather than other platform ifdefs to determine library call to use to serialize doubles

tools/base/requirements.in, tools/base/requirements.txt, tools/clang-format/BUILD, tools/clang-format/clang_format.bzl, tools/code_format/BUILD, tools/code_format/check_format.py, tools/local_fix_format.sh
This massively reduces the overhead for running the clang tooling
In this PR only clang-format is hooked up to the format precheck, but we can use the clang-tidy install when bringing it back
Ideally we would be able to do the same with lcov and friends which would reduce the cost of running coverage, but i dont see a package for them
We may decide in the future to fetch these tools from a different channel - the one in this PR is not ideal although it meets our current needs
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_check …
=> clang/tools: Use python distributed versions

source/common/common/matchers.cc, source/extensions/stat_sinks/graphite_statsd/config.cc, source/extensions/stat_sinks/statsd/config.cc, test/per_file_coverage.sh
In general Envoy config enums we don't allow default: (which makes it easy to add new variables and not implement handling) and we PANIC on completely invalid values.  Bringing 2 files in line with this.
Testing: n/a (can't test panic)
=> matchers: removing switch default

source/server/hot_restarting_base.cc, source/server/hot_restarting_base.h, source/server/hot_restarting_child.cc, source/server/hot_restarting_parent.cc, test/server/hot_restarting_base_test.cc
Commit Message: Refactor hot restart RPC stream
Additional Description: Before this PR, the RPC stream behavior is hardcoded into HotRestartingBase. This change breaks it out into a member class, as a precursor to udp forwarding during hot restart, which will require an additional channel for forwarded UDP. By unifying the RPC behavior into a separate class, we can have two instances of the class rather than duplicating a lot of code.
Risk Level: Very low, as this is essentially a no-op.
Testing: As covered as it was before. Coverage should be improved with the change that comes after this (#29328).
=> Refactor hot restart rpc stream

docs/BUILD
With this PR any configs in the `/configs` folder can be accessed in rst using something like ...:
```rst
:download:`terminate_http_in_http2_connect.yaml </_configs/repo/terminate_http_in_http2_connect.yaml>`
```
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: Make repo configs available to Sphinx rst

envoy/network/connection_handler.h, envoy/server/instance.h, envoy/server/listener_manager.h, envoy/server/worker.h, mobile/library/common/extensions/listener_managers/api_listener_manager/api_listener_manager.h, source/extensions/listener_managers/listener_manager/connection_handler_impl.cc, source/extensions/listener_managers/listener_manager/connection_handler_impl.h, source/extensions/listener_managers/listener_manager/listener_manager_impl.cc, source/extensions/listener_managers/listener_manager/listener_manager_impl.h, source/server/admin/listeners_handler.cc, source/server/config_validation/server.h, source/server/hot_restarting_parent.cc, source/server/hot_restarting_parent.h, source/server/server.cc, source/server/server.h, source/server/worker_impl.cc, source/server/worker_impl.h, test/extensions/listener_managers/listener_manager/listener_manager_impl_quic_only_test.cc, test/extensions/listener_managers/listener_manager/listener_manager_impl_test.cc, test/mocks/network/mocks.h, test/mocks/server/instance.h, test/mocks/server/listener_manager.h, test/mocks/server/worker.cc, test/mocks/server/worker.h, test/server/config_validation/server_test.cc, test/server/connection_handler_test.cc, test/server/hot_restarting_parent_test.cc, test/server/worker_impl_test.cc
Commit Message: Register HotRestartingParent as udp forwarding packet recipient
Additional Description: When listeners start draining during hot restart, pass them a reference to HotRestartingParent so that ActiveQuicListeners can forward non-routable UDP packets to the child instance.
Risk Level: Low, no behaviors are actually changed yet.
Testing: Existing coverage should cover all touched paths (except the TODO one).
=> Register HotRestartingParent as udp forwarding packet recipient

test/per_file_coverage.sh
Commit Message: Reduce coverage threshold for source/server
Additional Description: This is a temporary reduction of a flaky coverage (https://github.com/envoyproxy/envoy/issues/15239) because my recent changes have added some comment lines which aren't covered. #29585 is going to add a lot of coverage here.
Testing: n/a
=> Reduce coverage threshold for source/server

envoy/stats/primitive_stats_macros.h, envoy/stats/stats_macros.h, support/README.md, tools/code_format/check_format.py
Commit Message: Update instructions for running the code format tool
Additional Description: #29397 changed the way to run the `check_format` python script but the some of the docs are still referring to the "old" way of running it, which does not work anymore.
Risk Level: 
Testing:
Docs Changes:
Release Notes:
=> docs: Update instructions for running the code format tool

mobile/library/cc/engine_builder.cc, mobile/test/common/integration/sds_integration_test.cc, mobile/test/common/integration/xds_integration_test.h
This PR rewrites `SdsIntegrationTest` to be more realistic. especially for the Envoy Mobile use cases.
The changes are the following:
- Uses CDS + SDS with ADS to create a dynamic cluster instead of overriding the Bootstrap config to create static clusters since Envoy Mobile does not support adding static clusters.
- Exports SDS related stats.
- Updates the test parameters to only use state-of-the-world since Envoy Mobile does not support delta.
Risk Level: low (rewriting test)
=> mobile: Rewrite SdsIntegrationTest

support/hooks/pre-push
This is step towards removing any system python from ci - and means the hook is running the same tools that actual CI runs
Follow-ups planned:
- unify local formatting code paths
- route local formatting through do_ci.sh to ensure consistent bazel env
Fix #29597 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> git/hooks: Use `envoy.code.check`

source/common/network/connection_impl.cc, test/common/network/connection_impl_test.cc
Fix #29595 
It is possible that we will get data + rst from the wrapped transport socket since there is a `do {} while` loop. We should trigger the `onRead` if there is any processed data.
Do not flake anymore.
```
bazel test test/integration:protocol_integration_test --test_filter="*LargeRequestMethod*" --test_arg="-l trace" -c opt --runs_per_test=1000
```
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tcp: fix socket read data with rst flake

.github/workflows/mobile-format.yml, bazel/README.md, ci/build_setup.sh, support/hooks/pre-push, tools/protoprint/BUILD, tools/protoprint/protoprint.bzl, tools/protoprint/protoprint.py
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tools/clang: Remove remaining host clang-format usage (+docs update)

source/common/http/header_utility.cc, source/common/router/config_impl.cc, test/common/http/header_utility_test.cc
Per RFC 9110, the Upgrade value comparison should be case-insensitive. The existing implementation used case-sensitive comparison for CONNECT-UDP, so I fixed the bug. Also, I made the upgrade_type config check use case-insensitive comparison for both CONNECT and CONNECT-UDP.
See  RFC 9110 (https://www.rfc-editor.org/rfc/rfc9110#section-7.8) for the Upgrade value comparison semantics, and https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-upgradeconfig-upgrade-type for the correct upgrade_type config check semantics.
Risk Level: Low, this is a bug fix.
Testing: Added a unit …
=> http: make connect-udp upgrade case-insensitive

bazel/foreign_cc/BUILD, bazel/repositories.bzl, source/common/io/BUILD
This fixes some uncommon bazel invocations such as `bazel build //source/...` and `tools/gen_compilation_database.py` on non-Linux.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> build: exclude liburing from non-Linux builds

tools/sha/BUILD, tools/sha/replace.sh
This provides a tool for replacing shas in the repo which can be helpful updating dependencies.
The tool is actually a generic string replacer (with many limitations), but as the focus is for shas ive added it to `tool/sha`
It can be run:
```console
$ bazel run //tools/sha:replace 1f2f7ee78f894859de0fa7a415b0bedde1f6c560:56f235b141079013e64912d676fe7da981368402
```
where the string/shas to be replaced are specified `$target:$replacement`
multiple replacements can be specified
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_check …
=> repo/tools: Add (sha) replacement tool

test/extensions/filters/http/ext_proc/streaming_integration_test.cc
This PR is to fix the issue: https://github.com/envoyproxy/envoy/issues/29625.
The root cause of the issue is that,  if ext_proc filter header mode is SEND, and body mode is STREAMED, then the number of body chunks Envoy received are not necessarily the same as the number of body chunks the downstream client sends, because kernel might be buffering.   
So the number of chunks Envoy receives, and each chunk size could be complete different from the downstream client sends.  In the extreme case, like if the ext_proc server is slow during header processing, the kernal might buffer all the data chunks it received from downstream client, and dispatched to Envoy in one shot.  This will ends up the number of data_chunks Envoy receives, thus forwarded to the ext_proc server,  is just one.  This …
=> Fixing flaky ext_proc streaming integration test.

.github/workflows/mobile-release.yml
Instead of hard-coding the Ubuntu version number, it will get it from the env.yml macro.
=> mobile/ci: Set the mobile-release workflow to use agent_ubuntu

source/server/guarddog_impl.cc, test/server/guarddog_impl_test.cc
Commit Message: Debug: Update watchdog multikill to log number of threads stuck.
Testing: test
=> Debug: Update watchdog multikill to log number of threads stuck.

source/common/network/io_socket_handle_impl.cc
The `mobile-release` workflow has been failing:
https://github.com/envoyproxy/envoy/actions/runs/6162864940/job/16725227974#step:5:53. This is due to a compiler error when the `-Werror` and `-Wsign-compare` compilation options are turned on on certain platforms.
On certain platforms, socklen_t is an int instead of unsigned int, making the comparison with an integer of size_t (unsigned int) cause a compilation failure.
Instead of changing the `mobile-release` workflow to figure out the right compiler options to make the error go away, we fix the problem in the code to ensure we are comparing integers of the same type (both are now compared as unsigned ints).
=> network: Fix incorrect int comparison with -Werror,-Wsign-compare

.github/dependabot.yml, contrib/golang/common/go/api/api.h, contrib/golang/common/go/api/capi.go, contrib/golang/common/go/api/type.go, contrib/golang/filters/http/source/cgo.cc, contrib/golang/filters/http/source/go/pkg/http/capi_impl.go, contrib/golang/filters/http/source/go/pkg/http/type.go, contrib/golang/filters/http/source/golang_filter.cc, contrib/golang/filters/http/source/golang_filter.h, contrib/golang/filters/http/test/BUILD, contrib/golang/filters/http/test/golang_integration_test.cc, contrib/golang/filters/http/test/test_data/buffer/BUILD, contrib/golang/filters/http/test/test_data/buffer/config.go, contrib/golang/filters/http/test/test_data/buffer/filter.go, contrib/golang/filters/http/test/test_data/buffer/go.mod, examples/golang-http/simple/filter.go
Since we can't provide Peek feature in the callback (the body data is already read and we can't peek unread data), here I remove the Peek method. It's fine as this method is not implemented and can be replaced with Bytes.
Docs Changes:
Release Notes:
=> golang filer: support Drain & Reset

api/envoy/extensions/transport_sockets/tls/v3/tls.proto, changelogs/current.yaml, envoy/ssl/context_config.h, source/extensions/transport_sockets/tls/context_config_impl.cc, source/extensions/transport_sockets/tls/context_config_impl.h, source/extensions/transport_sockets/tls/context_impl.cc, test/extensions/transport_sockets/tls/ssl_socket_test.cc, test/mocks/ssl/mocks.h
Commit Message: tls: add disable_stateful_session_resumption option
Docs Changes: API proto comments
Release Notes: new feature
Implements #19876.
=> tls: add disable_stateful_session_resumption option

mobile/test/kotlin/integration/BUILD, mobile/test/kotlin/integration/StreamIdleTimeoutTest.kt
Prior to this PR, `StreamIdleTimeoutTest` did not have a build target, which means the test was never executed. This PR fixes the issue by adding a build target for `StreamIdleTimeoutTest` as well as updating it, so that it compiles and passes the test.
Risk Level: low (fixing test only)
=> mobile: Fix StreamIdleTimeoutTest

source/common/upstream/cluster_manager_impl.cc, source/common/upstream/cluster_manager_impl.h, test/common/upstream/BUILD, test/common/upstream/deferred_cluster_initialization_test.cc, test/common/upstream/test_cluster_manager.h
Commit Message: upstream: minor optimization to the cluster initialization object merge
Defering cluster creation is a interesting/great feature. But in the current implementation, there may be unexpected merge of cluster initialization objects.
Now, previous cluster initialization objects will be merged to the new one when the cluster name, cluster type are same and the type is EDS.
However, if an EDS cluster is updated by the CDS API, they have same cluster name, same cluster type, but they may have complete different eds service name or lb config. They are complete different two cluster and merge shouldn't happen.
Testing: unit.
=> upstream: fix bug of unexpected cluster initialization object merge

docs/root/start/sandboxes/golang-http.rst
Commit Message: "doc: fix golang-http example path in the doc"
Additional Description: After adding adding golang-network plugin and sandboxes, this directory and sandbox path didn't change in the docs
Risk Level:
Testing: 
Docs Changes: docs/root/start/sandboxes/golang-http
Release Notes:
=> doc: fix golang-http example path in the doc

mobile/bazel/kotlin_test.bzl, mobile/library/common/jni/jni_interface.cc, mobile/library/common/jni/jni_utility.cc, mobile/library/common/jni/jni_utility.h
This PR fixes #28981 by creating wrappers for JNI's `Call<Type>Method` and `CallStatic<Type>Method` that will check on the exception that might be thrown to satisfy `-Xcheck:jni` and updating the code to use the wrappers.
=> mobile: Re-enable -Xcheck:jni

.azure-pipelines/pipelines.yml, ci/Dockerfile-envoy
- disable clang-tidy
- update rules_rust
- update distroless
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.25] Backport stack (latest)

mobile/test/kotlin/integration/CancelGRPCStreamTest.kt, mobile/test/kotlin/integration/CancelStreamTest.kt, mobile/test/kotlin/integration/EngineApiTest.kt, mobile/test/kotlin/integration/FilterThrowingExceptionTest.kt, mobile/test/kotlin/integration/GRPCReceiveErrorTest.kt, mobile/test/kotlin/integration/KeyValueStoreTest.kt, mobile/test/kotlin/integration/ReceiveDataTest.kt, mobile/test/kotlin/integration/ReceiveDataWithDeliveryLimitsTest.kt, mobile/test/kotlin/integration/ReceiveErrorTest.kt, mobile/test/kotlin/integration/ReceiveTrailersTest.kt, mobile/test/kotlin/integration/ResetConnectivityStateTest.kt, mobile/test/kotlin/integration/SendDataTest.kt, mobile/test/kotlin/integration/SendHeadersTest.kt, mobile/test/kotlin/integration/SendTrailersTest.kt, mobile/test/kotlin/integration/SetLoggerTest.kt, mobile/test/kotlin/integration/StatFlushIntegrationTest.kt, mobile/test/kotlin/integration/StreamIdleTimeoutTest.kt
This PR cleans up Kotlin integrations to make it more idiomatic Kotlin. The changes are as follows:
- Removed useless `setOnEngineRunning {}`
- Removed other methods that take empty lambda
- Renamed the constants to use UPPER_SNAKE_CASE
- Removed unused imports
- Renamed the class name to match the file name prevent class redeclaration
Risk Level: low (clean up)
=> mobile: Clean up Kotlin integration tests

api/envoy/extensions/common/matching/v3/BUILD, api/envoy/extensions/common/matching/v3/extension_matcher.proto, api/envoy/extensions/filters/http/composite/v3/BUILD, api/envoy/extensions/filters/http/composite/v3/composite.proto, docs/root/configuration/http/http_filters/composite_filter.rst, docs/root/intro/arch_overview/advanced/matching/matching_api.rst, source/extensions/extensions_metadata.yaml
- Composite filter has already been declared as stable in extensions_metadata.yaml
- matching API and its extensions have been used for a while. So I think breaking API changes are not allowed.
=> Update the doc and status for composite_filter and matching API

mobile/library/common/jni/android_network_utility.cc, mobile/library/common/jni/jni_utility.cc
This fixes the following compiler warnings:
- `-Wsign-compare`
- `-Wreturn-type`
=> mobile: Fix compiler warnings.

api/envoy/config/route/v3/route_components.proto, envoy/http/query_params.h, source/common/http/utility.cc, source/common/router/config_impl.cc, source/common/router/config_utility.cc, source/common/router/config_utility.h, source/common/router/router_ratelimit.cc, source/extensions/filters/http/jwt_authn/matcher.cc, test/common/http/utility_test.cc, test/common/router/config_impl_test.cc
router: switch from old QueryParams type to new QueryParamsMulti type
This PR is follow-up work I promised @ggreenway as part of #28788 in [this comment chain](https://github.com/envoyproxy/envoy/pull/28788#issuecomment-1664328670).
It switches the router from the old `QueryParams` type to the replacement `QueryParamsMulti` type.
How the router handles repeating query parameters is actually specified [in the docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/http_inputs.proto#type-matcher-v3-httprequestqueryparammatchinput):
> The resulting input string will be the first query parameter for the value ‘query_param’.
I preserved this functionality in the cutover.  At some point in the future I might file a PR to add an matcher …
=> router: switch to use new QueryParametersMulti type

test/integration/BUILD, test/integration/hotrestart_handoff_test.py, test/integration/null_test.py
Commit Message: Add hot restart handoff integration test
> Tests the behavior of connection handoff between instances during hot restart.
> 
> Specifically, tests that:
> 1. A tcp connection opened before hot restart begins continues to function during drain.
> 2. A tcp connection opened after hot restart begins while the old instance is still running
>    goes to the new instance.
>
> The intent is to add the same test for QUIC connections, when the work to make that
> supported is complete.
Risk Level: Very low, test only. Minor risk of making CI flakier, as the test has timing aspects.
Testing: Passed 100% with runs_per_test=100
Platform Specific Features: Disabled on Windows where there is no hot restart support.
=> Add hot restart handoff integration test

changelogs/current.yaml, docs/root/configuration/http/http_filters/lua_filter.rst, source/extensions/filters/http/lua/wrappers.cc, source/extensions/filters/http/lua/wrappers.h, test/extensions/filters/http/lua/lua_integration_test.cc, test/extensions/filters/http/lua/wrappers_test.cc
Commit Message: lua: add downstreamRemoteAddress() method
Testing: updated unit test and lua integration test
Docs Changes: updated lua filter docs
Release Notes: added to changelog
Fixes #29738
=> lua: add downstreamRemoteAddress() method

source/server/config_validation/server.h
Commit Message: config_validation: extend ssl manager lifetime beyond the dispatcher
This is similar to the fix of #23452 which fixed the same issue for the Envoy server, but applied to the config-validator mode.
Risk Level: low - config-validator only,
=> config_validation: extend ssl manager lifetime beyond the dispatcher

mobile/test/common/integration/BUILD, mobile/test/common/integration/xds_test_server.cc, mobile/test/common/integration/xds_test_server.h, mobile/test/common/integration/xds_test_server_interface.cc, mobile/test/common/integration/xds_test_server_interface.h, mobile/test/common/jni/BUILD, mobile/test/common/jni/test_jni_interface.cc, mobile/test/java/io/envoyproxy/envoymobile/engine/testing/TestJni.java, mobile/test/kotlin/integration/BUILD, mobile/test/kotlin/integration/XdsTest.kt
This PR adds an xDS test server to make it easy testing xDS functionality for Android tests as well as adding a simple xDS integration test for Android.
=> mobile: Add Android xDS integration test

mobile/test/kotlin/integration/BUILD, mobile/test/kotlin/integration/TestUtilities.kt, mobile/test/kotlin/integration/XdsTest.kt
This PR creates test utilities that can be useful for asserting stats in the integration tests. This PR also updates `XdsTest` to use these test utilities.
=> mobile: Create test utilities for dealing with stats

api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto, envoy/server/factory_context.h, source/extensions/extensions_metadata.yaml, source/extensions/filters/common/ext_authz/check_request_utils.cc, source/extensions/filters/http/common/factory_base.h, source/extensions/filters/http/ext_authz/config.cc, source/extensions/filters/http/ext_authz/config.h, source/extensions/filters/http/ext_authz/ext_authz.cc, source/server/server.h, test/extensions/filters/common/ext_authz/check_request_utils_test.cc, test/extensions/filters/http/ext_authz/config_test.cc, test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc, test/mocks/server/server_factory_context.cc, test/mocks/server/server_factory_context.h
This reverts commit 9918a0a06deaf0cb3c935566523ab3fdd7a2bab1.
Commit Message: Revert "ext_authz: make the ext_authz filter a dual filter (#29173)"
Additional Description: Causing CI flakiness
Fixes: #29759
=> Revert "ext_authz: make the ext_authz filter a dual filter (#29173)"

contrib/golang/common/go/api/capi.go, contrib/golang/filters/http/source/go/pkg/http/capi_impl.go, contrib/golang/filters/http/source/go/pkg/http/type.go, contrib/golang/filters/http/test/test_data/basic/filter.go
Most of the Go libraries consider using []byte is more efficient. Therefore, they only provide api with []byte. By returning []byte instead of string, we can avoid an extra `string -> []byte` copy.
This change also aligns the behavior with the proxy-wasm-go-sdk, making it easier to port Wasm plugin to Go plugin.
Testing: Integration. Should also pass the existing tests.
Docs Changes:
Release Notes:
=> golang filter: fetch body data as []byte

source/common/quic/envoy_quic_server_session.cc, source/common/quic/quic_filter_manager_connection_impl.cc, source/common/quic/quic_filter_manager_connection_impl.h, test/integration/protocol_integration_test.cc
Fix ProtocolIntegrationTest.HittingEncoderFilterLimit when --quic_no_send_alarm_unless_necessary is true.
Previously, the test passes because at the end of `EnvoyQuicServerSession::ProcessUdpPacket`, a send alarm is always scheduled, and `QuicFilterManagerConnectionImpl::onWriteEventDone` will be called when the alarm fires. 
With the flag=true, send alarm is only scheduled when it is necessary, so `QuicFilterManagerConnectionImpl::onWriteEventDone` may not be called. This change adds a `QuicFilterManagerConnectionImpl::maybeApplyDelayedClose` method(which does the same thing as onWriteEventDone) and always call it at the end of `EnvoyQuicServerSession::ProcessUdpPacket`.
=> [test] Fix ProtocolIntegrationTest.HittingEncoderFilterLimit

source/extensions/filters/http/connect_grpc_bridge/filter.cc
Commit Message: connect_grpc_bridge: use new query params struct
#28788 fixed a bug in query param handling, and introduced a new data structure for query parameters in the process. In that PR, I committed to going through and swapping out the old data struct for the new one, feature by feature.
This PR swaps the old data structure for the new data structure. No behavior is changed.
Testing: Existing unit tests
cc @ggreenway  - here's another small query param data struct replacement
=> connect_grpc_bridge: use new query params struct

docs/root/configuration/observability/access_log/usage.rst
These access log variables use identical code so they should always be equivalent. I was initially wondering how these variables differed, but after digging in, I found they have identical source code, so I thought this might be worth pointing out in the docs that these reflect the same value.
I suppose one of these could be deprecated if you all wanted to eliminate the duplication, but that would obviously be a bigger change. In the meantime, I thought clarifying the fact that they are the same might help clear up any confusion, like my own. It seems like `UPSTREAM_REMOTE_ADDRESS` was added more recently (https://github.com/envoyproxy/envoy/pull/19613) and is part of a more consistent set of variables, but `UPSTREAM_HOST` has been around much longer.
Current identical implementation …
=> docs: Clarify UPSTREAM_REMOTE_ADDRESS and UPSTREAM_HOST access log variables are the same

api/envoy/config/route/v3/route_components.proto, source/common/http/hash_policy.cc, test/common/router/config_impl_test.cc
Commit Message: update query params hash policy to use new data structure
Additional Description:  
#28788 fixed a bug in query param handling, and introduced a new data structure for query parameters in the process.  In that PR, I committed to going through and swapping out the old data struct for the new one, feature by feature.
This PR:
* Swaps the old data structure for the new data structure.  No behavior is changed
* Updates the docs to make clear what happens when query parameters are repeated
* Extends an existing unit test to ensure that the repeated query param behavior specified in the docs is respected
Testing: Existing unit tests + new unit test
Docs Changes: Added clarity around (unchanged) behavior when query params are repeated.
Platform …
=> router: update query params hash policy to use new data structure

test/fuzz/fuzz_runner.cc
Commit Message: fuzz: ensure runCleanupHooks is invoked on exit
#29522 introduced cleanup hooks, and assumes a call will be made to `runCleanupHooks` at the end.
Some executions don't use our custom `main` file, so this PR ensures that the function will be invoked.
Testing: N/A
=> fuzz: ensure runCleanupHooks is invoked on exit

docs/root/operations/admin.rst
Fix the example in admin.rst to use the correct syntax for setting the log level for multiple loggers.
Commit Message: Fix the example in admin.rst to use the correct syntax for setting the log level for multiple loggers.
Risk Level: Low (docs only)
Testing: N/A
=> docs: Fix multiple log level example in admin.rst

test/extensions/stats_sinks/open_telemetry/open_telemetry_integration_test.cc
Additional Description: This change will mitigate the test flakes as described in #29518. Requires further investigation to understand root cause
=> otlp_stat_sink: mitigate test flakes

.azure-pipelines/stage/prechecks.yml, .bazelrc, tools/protodoc/protodoc.py
This is a partial resolution for issues raised in #29850 and should stop the website breaking
it also brings the rst checker back online - i will follow up with some format fixes
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> protodoc: Fix rst checker and load lazily

.azure-pipelines/env.yml, .azure-pipelines/stage/publish.yml, .azure-pipelines/stages.yml, .github/workflows/_stage_publish.yml
this is now handled downstream
For normal commits to Envoy `main` this will trigger an update in the website repo, which will update its envoy dep shas, and rebuild the website for the latest docs
For commits that create a release, it instead triggers an update in the archive repo, which builds a static version of the docs for the release and commits it to the archive. In turn the archive repo triggers an update in the website so the new release docs are included in the published site
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/rev …
=> ci/publishing: Remove postsubmit docs build

bazel/repositories.bzl, docs/BUILD, docs/build.sh, tools/base/requirements.in, tools/base/requirements.txt, tools/docs/BUILD, tools/docs/generate_version_histories.py, tools/protodoc/protodoc.bzl
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs/build: Assorted fixes for building as external target

BUILD, bazel/repositories.bzl, distribution/dockerhub/BUILD, mobile/BUILD, mobile/docs/BUILD, tools/BUILD, tools/base/envoy_python.bzl, tools/code/BUILD, tools/dependency/BUILD, tools/distribution/BUILD, tools/docs/BUILD, tools/proto_format/BUILD, tools/protodoc/BUILD, tools/protoprint/BUILD
This allows repo tooling to work externally alongside our namepsaced pypi packages
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> py/tools: Namespace repo packages to prevent conflict

docs/root/configuration/advanced/well_known_filter_state.rst, source/common/network/BUILD, source/common/network/application_protocol.cc, source/common/network/upstream_server_name.cc, source/common/network/upstream_subject_alt_names.cc, test/common/network/transport_socket_options_impl_test.cc
Commit Message: Documents and exposes well known transport socket filter state objects for dynamic extensions
Testing: added
Release Notes: no (not a new feature)
Issue: #29681
=> filter state: add more well-known objects

test/extensions/filters/http/ext_proc/BUILD
As more ext_proc integration tests are added, it is noticed that the tests become flaky sometimes.  All of the flaky are due to timeouts.  Let's adding shard count to reduce the probability of flaky for now.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Adding more shards to ext_proc integration test

test/common/network/udp_listener_impl_test.cc
Commit Message: potential fix to flakiness caused by missing Read event when I/O event callback is triggered. 
```
test/common/network/udp_listener_impl_test.cc:610: Failure
Actual function call count doesn't match EXPECT_CALL(listener_callbacks_, onReadReady())...
Expected: to be called once
Actual: never called - unsatisfied and active
```
This indicates Read event is not present when the test is unblocked. Maybe a Write only event is bubbled up at the beginning.
Fixes #29310
=> quic: fix flaky gso test

test/integration/fake_upstream.h
Additional Description: when reading gRPC frame in ``FakeStream``, in case a gRPC frame is received in multiple data payloads, it's required to subtract the count of bytes already read on previous payloads from the expected bytes left to wait for. Otherwise - ``FakeStream`` will keep waiting for the original frame length, although the ``body_`` has already been drained from the first data payload.
=> fake_upstream: subtract already read bytes from required frame length

CODEOWNERS
I stopped working at AWS in 2021. Removing myself from the relevant OWNERS file entries.
=> owners: Remove tonya11en from AWS files

distribution/BUILD
This ensures a rebuild of the Docker image before running package verify tests
When changing the version number it was creating a mismatch between what was being tested and what was expected
This flag is probably a good idea generally as it will still rebuild from cache but will expire anything that has changed
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> verify/packages: Force rebuild of docker image

.github/workflows/_stage_publish.yml
Publishing docs can take quite a while after CI has started.
If `main` has been updated by the time the wf is dispatched then the website gets updated to the wrong hash
with https://github.com/envoyproxy/envoy-website/pull/362 this should fix that
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/website: Use commit sha when dispatching website build

test/common/http/codec_impl_corpus/h10_empty_hostname, test/common/http/codec_impl_fuzz_test.cc
Commit Message: fuzz: fix h10 codec validation
The HTTP/1 codec fuzzer can receive any string in its [default_host_for_http_10](https://github.com/envoyproxy/envoy/blob/9a3c8967e98a6f5c5e689e3a0e30d4a3b1ff7a2a/test/common/http/codec_impl_fuzz.proto#L93) field. This PR validates that input to prevent wrong config.
Testing: added corpus entry.
=> fuzz: fix h10 codec validation

.github/workflows/_ci.yml, .github/workflows/_stage_publish.yml, .github/workflows/_stage_verify.yml, .github/workflows/envoy-publish.yml
Currently when the publishing ci is triggered in postsubmit, it just uses the latest commit of the branch (main/release/etc)
This fixes it to use the correct commit, and adds a check to ensure it is a commit of that branch.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/publish: Fix checked out ref for postsubmit

api/envoy/config/core/v3/protocol.proto, source/common/quic/envoy_quic_client_session.cc, test/integration/quic_http_integration_test.cc
Commit Message: Fix the default config for port migration. It's supposed to be 4 PTOs, but it was incorrectly set to 1.
Platform Specific Features: client only.
=> [quic]fix default config for port migration

bazel/external/quiche.BUILD
Commit Message: Remove the unnecessary dep in quic_core_qpack_qpack_stream_sender_delegate_lib
Additional Description: The dep was initially added to fix my local build. But the actual root cause is me not using the right build config. So let's remove it.
Testing: n/a
=> Fix quiche build file

.azure-pipelines/stage/verify.yml
This should fix a bad merge causing diskspace issues in the x64 verify job
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/verify: Use self-hosted vm for x64 job

SECURITY.md
Aspen Mesh was an incubator that was rolled into back its parent organization. The email distribution list has already been updated, this is only to update the org list.
Commit Message: Update SECURITY.md.
Testing: N/A
=> Change aspenmesh org to F5 in security members

bazel/README.md, ci/README.md, support/README.md
The build emits a warning when you use `bazel.`-prefixed CI commands.
Commit Message: bazel: remove deprecated `bazel` prefixes in docker CI
Additional Description: The build emits a warning when you use `bazel.`-prefixed CI commands.
Testing: I have invoked commands with a `bazel.` prefix and observed warnings that went away when it was removed.
@phlax I [was advised](https://github.com/envoyproxy/envoy/pull/29877#discussion_r1347920828) to ping you for review.
=> bazel: remove deprecated `bazel` prefixes in docker CI

ci/Dockerfile-envoy
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.25] docker/build: Bump distroless -> debian 12 and pin ubuntu (#30029)

ci/Dockerfile-envoy
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.24] docker/build: Bump distroless -> debian 12 and pin ubuntu (#30029)

source/extensions/filters/http/oauth2/filter.cc, source/extensions/filters/http/oauth2/filter.h
oauth2: replace old query param data structure with new version
In #24054, a new data structure for storing query parameters was introduced.  In that PR, I committed to going through and ripping out all usage of the old data structure (cc @ggreenway). 
This PR swaps out the old structure for the new one throughout the oauth2 filter.  No behavior changed.
Testing: Existing unit tests appear to provide sufficient coverage.
=> oauth2: replace old query param data structure with new version

ci/run_envoy_docker.sh
Especially for env var GOPROXY, which is the name defined in the Go standard.
Commit Message: ci: support different cases of the env vars
Testing:
Docs Changes:
Release Notes:
=> ci: support different cases of the env vars

api/envoy/config/route/v3/route_components.proto
auto-host-rewrite does have effect when using EDS and setting hostname field.
Commit Message: This fixes auto_host_rewrite explanation. Since [this pr](https://github.com/envoyproxy/envoy/pull/10456), auto_host_rewrite does have effect even with route types of 'static' or 'eds' when 'hostname' field is set for the endpoints.
Testing: n/a
Docs Changes: 
Release Notes:
=> docs: Fix auto-host-rewrite doc

changelogs/current.yaml, source/common/http/conn_manager_config.h, source/common/http/conn_manager_impl.cc, source/common/http/conn_manager_impl.h, source/common/runtime/runtime_features.cc, test/common/http/conn_manager_impl_test_2.cc, test/common/http/conn_manager_impl_test_base.cc, test/common/http/conn_manager_impl_test_base.h, test/common/http/http2/http2_frame.cc, test/common/http/http2/http2_frame.h, test/integration/multiplexed_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> http: Fix CVE CVE-2023-44487

source/common/network/utility.cc, source/common/network/utility.h, source/server/hot_restart.proto, source/server/hot_restart_impl.cc, source/server/hot_restarting_base.cc, source/server/hot_restarting_base.h, source/server/hot_restarting_child.cc, source/server/hot_restarting_child.h, source/server/hot_restarting_parent.cc, source/server/hot_restarting_parent.h, test/common/network/utility_test.cc, test/server/BUILD, test/server/hot_restart_impl_test.cc, test/server/hot_restart_udp_forwarding_test_helper.h, test/server/hot_restarting_child_test.cc, test/server/hot_restarting_parent_test.cc
Commit Message: encapsulate and forward udp packets from parent instance to child
Additional Description: During hot restart, forward UDP packets as delivered to HotRestartingParent (from ActiveQuicListeners) to HotRestartingChild, for delivery to the appropriate listener in the new instance.
Risk Level: Some risk as hot restart behavior is changed by this.
Testing: Unit tests validate the packet delivery.
=> encapsulate and forward udp packets from parent instance to child

ci/Dockerfile-envoy
- Update distroless image
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.26] Backport stack (0)

source/server/config_validation/server.cc, source/server/config_validation/server.h, test/server/config_validation/server_test.cc
Commit Message: Implement drainManager API for config validation server instance
Additional Description: The drainManager() API can be used in configuration validation, but the current implementation panic's on access.
Testing: Tested on local machine with a configuration that requires a drain manager.
Docs Changes:
Release Notes:
=> Implement drainManager API for config validation server instance

mobile/test/common/http/filters/test_read/filter.cc, source/common/config/xds_resource.cc, source/common/http/matching/inputs.h
replace miscellaneous usages of query param data structure with new version
In #24054, a new data structure for storing query parameters was introduced. In that PR, I committed to going through and ripping out all usage of the old data structure (cc @ggreenway).
This PR swaps out the old structure for the new one in a couple small, self-contained usages. No behavior changed.
Once this PR is merged, there will be one large PR to remove the old data structure from the admin server (where it is used heavily), then one more to remove the data structure itself.
Testing: Existing unit tests appear to provide sufficient coverage.
=> replace miscellaneous usages of query param data structure with new version

.azure-pipelines/env.yml, .azure-pipelines/stage/linux.yml, .azure-pipelines/stage/prechecks.yml, .azure-pipelines/stages.yml
This is part of an effort to make releasing more immediate (#30074 )
We need to build the binary *at* commit so obviously that cant be skipped, but the tests and prechecks are not necessary  assuming we are confident with presubmit
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/release: Dont run release tests/prechecks during actual release

.github/actions/env/action.yml, .github/workflows/_env.yml, .github/workflows/envoy-prechecks.yml
Currently the code checks for `inputs.trusted` before that var has been derived/set - this fixes that issue
It also switches the github deps/prechecks wf to `pull_request_target` - this will require an update in our ci policy, but is a necessary step to enabling RBE for these workflows
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> github/ci: Switch prechecks to pull_request_target and fix

test/integration/BUILD
=> Shard multiplexed_upstream_integration_test to prevent overall timeout

docs/root/_configs/go/golang-with-per-route-config.yaml, docs/root/_configs/go/golang-with-per-virtualhost-config.yaml
Currently, when the plugin requires a plugin configuration, using these per-route configuration examples will cause an error: `proto: mismatched message type: got "xds.type.v3.TypedStruct", want ""`. Even the filter level's configuration is only used to define the filter order.
One solution is to provide an empty xds.TypedStruct{}  as fallback. But then I thought about it, and an empty configuration is not necessarily a valid configuration. And technically, if there is no perRoute configuration, then the filter will still be executed. So it looks like the only way to go is to change the config file and add plugin configuration to it.
Commit Message: golang filter: need to provide a plugin configuration in the http filter if the configuration is required
Risk Level: …
=> golang filter: need to provide a plugin configuration in the http filter if the configuration is required

.github/workflows/_stage_publish.yml, .github/workflows/envoy-publish.yml, ci/do_ci.sh, tools/base/requirements.in, tools/base/requirements.txt
The updated tool accepts some new args and improves the release commit message:
`release --release-message-path`
allows additional commit message content to be included from file
`publish --publish-commit-message`
this uses the last commit message (ie releaes commit) as the body/description of the release
it would do this anyway but submitting as a body ensures correct rendering
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/publishing: Improve/automate release messaging

api/envoy/config/route/v3/route_components.proto, docs/root/configuration/http/http_filters/lua_filter.rst
Commit Message: docs: add warnings about client cert validation
Add a warning to TlsContextMatchOptions.validated that the validation
status will always be false for resumed TLS sessions, as validation is
not currently performed upon TLS session resumption.
Add a similar warning to the Lua filter API documentation, regarding the
peerCertificateValidated() method. Fix a couple of existing typos here.
Testing: manual (built docs site)
Docs Changes: proto comments and Lua filter API docs
Related to #21235
=> docs: add warnings about client cert validation

source/common/quic/envoy_quic_client_connection.cc, source/common/quic/envoy_quic_client_connection.h, source/common/quic/quic_network_connection.h, test/integration/quic_http_integration_test.cc
Commit Message: Limit the max number of connection migrations to 5.
Additional Description: This prevents too many new sockets being created.
Risk Level: Low. Can be turned off via num_timeouts_to_trigger_port_migration proto
=> [quic]impose a limit on the number of connection migrations

.github/workflows/_ci.yml, .github/workflows/_env.yml, .github/workflows/_stage_publish.yml, .github/workflows/envoy-prechecks.yml, .github/workflows/envoy-publish.yml, .github/workflows/mobile-android_build.yml, .github/workflows/mobile-android_tests.yml, .github/workflows/mobile-asan.yml, .github/workflows/mobile-cc_tests.yml, .github/workflows/mobile-compile_time_options.yml, .github/workflows/mobile-core.yml, .github/workflows/mobile-coverage.yml, .github/workflows/mobile-docs.yml, .github/workflows/mobile-format.yml, .github/workflows/mobile-ios_build.yml, .github/workflows/mobile-ios_tests.yml, .github/workflows/mobile-release.yml, .github/workflows/mobile-release_validation.yml, .github/workflows/mobile-tsan.yml, tools/base/requirements.in, tools/base/requirements.txt
Hopefully this fixes a number of issues
- switches to using correct bot for publishing
- fixes issue on postsubmit where `ENVOY_SHA` was not being set
- separates out status setting from `_env.yml` this requires permissions and is only required by the triggered wf
- bumps `envoy.base.utils` to improve publishing ci feedback
- thins vars a little
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/publishing: Assorted fixes/cleanups for gh wfs

.github/workflows/_ci.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> github/publishing: Fix appauth condition

.bazelrc, .github/workflows/envoy-prechecks.yml, bazel/engflow-bazel-credential-helper.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/rbe: Enable Engflow RBE for prechecks

changelogs/current.yaml, source/extensions/tracers/datadog/tracer.cc, test/extensions/tracers/datadog/tracer_test.cc
tracing: fix Datadog span name
Backport c3646f994e0296ed44ecac2869fa65e7f58bf986 to 1.26
Additional testing:
Also, I ran the sources/extensions/tracers/datadog/demo both with and without these changes. Verified that the produced span's "operation name" before these changes is not as desired. Verified that the produced span's "operation name" after these changes is as desired.
Desired: "Operation name" is "envoy.proxy", and "resource name" is the operation_name passed to startSpan.
Testing: See the modified unit test.
Release Notes: updated
=> [Backport 1.26] tracing: fix Datadog span name (#29932)

changelogs/current.yaml, source/extensions/tracers/datadog/tracer.cc, test/extensions/tracers/datadog/tracer_test.cc
tracing: fix Datadog span name
Backport c3646f994e0296ed44ecac2869fa65e7f58bf986 to 1.27
Additional testing:
Also, I ran the sources/extensions/tracers/datadog/demo both with and without these changes. Verified that the produced span's "operation name" before these changes is not as desired. Verified that the produced span's "operation name" after these changes is as desired.
Desired: "Operation name" is "envoy.proxy", and "resource name" is the operation_name passed to startSpan.
Testing: See the modified unit test.
Release Notes: updated
=> [Backport 1.27] tracing: fix Datadog span name (#29932)

mobile/test/java/org/chromium/net/CronetUrlRequestTest.java
Since landing https://github.com/envoyproxy/envoy/pull/30161, which moves the Android Cronet test
to run on Linux instead of Mac, we now get pretty regular failures on the CronetUrlRequestTest, e.g. https://github.com/envoyproxy/envoy/actions/runs/6512040855/job/17688913785?pr=30198.
Disabling the test for now and have an open bug to look into this:
https://github.com/envoyproxy/envoy/issues/30199
=> mobile: Disable flaky test on CI

bazel/external/quiche.BUILD, source/common/quic/platform/BUILD, source/common/quic/platform/mobile_quiche_bug_tracker_impl.h
Commit Message: Use ABSL_LOG for quiche logging on Envoy Mobile
Additional Description: There are 2 benefits:
1. ABSL_LOG will log to logcat to help with debug on Android.
2. ABSL_DLOG will be compiled out in opt build and thus reduces EM's binary size.
Testing: n/a
=> [Envoy Mobile]Implement QUICHE_LOG with ABSL_LOG

api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto, test/extensions/filters/network/common/fuzz/network_readfilter_corpus/hcm_header_value_extractor_key_name
Commit Message: HCM: prevent scoped-route invalid HeaderValueExtractor key config
Prior to this PR the [name](https://github.com/envoyproxy/envoy/blob/1eb64ee65f37853a3693fe5f5d616e6d4b5277fa/api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#L1057) field in `HeaderValueExtractor` could have been any string. This limits it to valid HTTP header names.
Testing: Added fuzz test
Docs Changes:
Release Notes:
Fixes fuzz issue [60277](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60277)
=> HCM: prevent scoped-route invalid HeaderValueExtractor key config

envoy/tracing/trace_driver.h, envoy/tracing/tracer.h, source/common/tracing/tracer_impl.h, source/extensions/tracers/common/ot/opentracing_driver_impl.cc, source/extensions/tracers/common/ot/opentracing_driver_impl.h, source/extensions/tracers/datadog/tracer.cc, source/extensions/tracers/datadog/tracer.h, source/extensions/tracers/opencensus/opencensus_tracer_impl.cc, source/extensions/tracers/opencensus/opencensus_tracer_impl.h, source/extensions/tracers/opentelemetry/opentelemetry_tracer_impl.cc, source/extensions/tracers/opentelemetry/opentelemetry_tracer_impl.h, source/extensions/tracers/opentelemetry/tracer.cc, source/extensions/tracers/opentelemetry/tracer.h, source/extensions/tracers/skywalking/skywalking_tracer_impl.cc, source/extensions/tracers/skywalking/skywalking_tracer_impl.h, source/extensions/tracers/xray/xray_tracer_impl.cc, source/extensions/tracers/xray/xray_tracer_impl.h, source/extensions/tracers/zipkin/zipkin_tracer_impl.cc, source/extensions/tracers/zipkin/zipkin_tracer_impl.h, test/common/tracing/tracer_manager_impl_test.cc, test/mocks/tracing/mocks.h
Commit Message:  Cleanup: Remove useless const in tracing interface.
Additional Description: Remove const value since implementation could be non-const and effects
aren't visible anyhow to caller.
Testing:
Docs Changes:
=> Cleanup: Remove useless const in tracing interface.

bazel/repositories.bzl, bazel/v8_include.patch
See https://github.com/envoyproxy/envoy/issues/29311.
The patch fixes include types for late clang (15.0.7) / gcc (13.2.1) for Arch linux / Fedora, like in
In file included from external/v8/src/torque/torque.cc:5:
In file included from external/v8/src/torque/source-positions.h:10:
In file included from external/v8/src/torque/contextual.h:10:
In file included from external/v8/src/base/macros.h:12:
external/v8/src/base/logging.h:154:26: error: use of undeclared identifier 'uint16_t'
...
Commit Message: build(deps): fix v8 missing include for numeric_t types
Testing: Compiles
---
in main it's fixed by https://chromium.googlesource.com/v8/v8.git/+/c2792e58035fcbaa16d0cb70998852fbeb5df4cc%5E%21/#F1 since `10.8.136`.
See …
=> build(deps): fix v8 missing include for numeric_t types

.azure-pipelines/ci.yml, .azure-pipelines/stage/checks.yml, .azure-pipelines/stage/macos.yml, .azure-pipelines/stage/prechecks.yml, .azure-pipelines/stage/publish.yml, .bazelrc, ci/build_setup.sh, ci/run_envoy_docker.sh, ci/setup_cache.sh, ci/upload_gcs_artifact.sh
This should simplify and improve sep of responsibility between parts of CI, and make it easier to document dev paths
In a follow up i will do something similar for the github ci which was designed to mimic azp, and can be simplified in a similar manner
This is a step - ive tried not to be too disruptive and added some deprecation on stuff that can be removed, to be sure noone else is using it.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel/ci: Cleanup flags and env vars

docs/root/configuration/http/http_filters/geoip_filter.rst
Currently all links in geoip filter docs look like this:
This patch fixes the links.
Testing:
Release Notes:
=> [Geoip Filter] Fix links in docs

test/extensions/filters/udp/dns_filter/dns_filter_test.cc, test/extensions/filters/udp/dns_filter/dns_filter_test_utils.cc
Commit Message:  Random transaction id generator can generate 0, while our current dns_parser apparently doesn't support 0 id. https://github.com/envoyproxy/envoy/blob/091ca544df4b190d197461f525a4accc6e644480/source/extensions/filters/udp/dns_filter/dns_parser.cc#L214-L217
In RFC1035, there is no clear objection for 0 id use though. IMO it is still based on the implementation of the clients. To unblock the release, we can avoid 0 in the test. And I also find the similar setting [non-zero query ID for each lookup in the previous tests](https://github.com/envoyproxy/envoy/blob/091ca544df4b190d197461f525a4accc6e644480/test/extensions/filters/udp/dns_filter/dns_filter_test.cc#L647) 3 years ago, though the code is also not correct.
Need further investigation for id = 0 handling based on RFC. …
=> dns_filter: avoid 0 for transaction id in tests at current stage

docs/root/intro/arch_overview/upstream/load_balancing/slow_start.rst
Clarify how slow start works with weighted locality load balancing during cross zone routing. This came out as TODO from #29008.
Testing: 
Release Notes:
Fixes #29008
=> Clarify slow start+locality weighted lb

test/integration/cds_integration_test.cc, test/integration/server.h, test/integration/server_stats.h
Commit Message: Flake: Fix flake in CDS integration test.
Additional Description: cc @stevenzzzz since I think this was added when you added deferred stats / these tests. This is a "well sychronized race" in the sense that TSAN won't error due to proper synchronization primatives used but ref-count of stat going to 0 might take some time e.g. for stat to be non-existent. 
Testing: ran 1000x 
Fixes #30107
=> Flake: Fix flake in CDS integration test.

.devcontainer/devcontainer.json
VS Code specific customizations should go to `customizations/vsocde` as per https://containers.dev/supporting. This change will also enable supporting other tools to use devcontainer for developing Envoy.
Testing: n/a
=> devex: Move VS Code specific settings to customizations/vscode

mobile/test/java/org/chromium/net/CronetUrlRequestTest.java
Fixes #30199.
The test cases for `CANCEL_ASYNC_WITHOUT_PAUSE` in `CronetUrlRequestTest::testFailures` will perform a cancellation asynchronously, but the order whether `onCanceled` or `onResponseStarted` is called first is is not deterministic, which means sometimes the response may be available if `onResponseStarted` is called first before `onCanceled` and sometimes the response may not be available if `onCanceled` is called first. This PR attemps to fix the issue by ignoring the assertion that checks whether the response is empty since it is not very critical for this specific test. The assertion that checks for the error remains unchanged to keep the same level of coverage.
Testing: unit test (`--runs_per_test=100`)
Platform Specific …
=> mobile: Fix flaky `CronetUrlRequestTest::testFailures`

changelogs/current.yaml, source/extensions/config_subscription/grpc/grpc_mux_impl.cc, source/extensions/config_subscription/grpc/grpc_mux_impl.h, test/extensions/config_subscription/grpc/grpc_mux_impl_test.cc
Commit Message: xds-sotw: reset nonce when reconnecting
Similar to #16037, this PR resets the nonce after reconnection for SotW.
This change is a bug fix that ensures SotW behaves according to the xDS protocol.
Testing: Added a test.
Fixes: #30155
=> xds-sotw: reset nonce when reconnecting

ci/README.md, ci/do_ci.sh
Add a release target to opt into behavior before #29646 was merged, specifically the copying of the final binary to something akin to `envoy_binary.tar.gz`
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Add release target to copy binary after build server_only

source/common/http/conn_manager_impl.cc, test/integration/multiplexed_integration_test.cc
Prevent doConnectionClose to be called recursively when connection with active requests is disconnected due to premature reset check. 
It was able to make the test crash with 17K outstanding requests. I think this is low severity bug, since it is unlikely that edge Envoys would set the limit on concurrent streams this high.
=> Prevent recursion during premature reset check

.github/workflows/mobile-android_build.yml, mobile/ci/start_android_emulator.sh
The plan is to use Java 11 throughout to reduce the number of JDKs installed. In the follow-up PR, the Linux Docker image for mobile will be updated to use Java 11.
Testing: CI
=> mobile: Use Java 11 to build Android apps on macOS

docs/root/configuration/http/http_filters/ext_authz_filter.rst, docs/root/configuration/listeners/network_filters/ext_authz_filter.rst
The `ext_authz_duration` field is only emitted if the  dynamic metadata `Struct` in the response is [non-empty](https://github.com/envoyproxy/envoy/blob/cbe2fb292899b1a8e7ebca16c540d7ca23a104a9/source/extensions/filters/http/ext_authz/ext_authz.cc#L200) (e.g. contains at least one key-value pair). Replace "filled" with "non-empty" to avoid ambiguity.
=> docs: clarify requirement for ext_authz dynamic metadata

tools/h3_request/h3_request.py
Commit Message: Make h3_request stream output
Additional Description: Hot restart test requires streaming response (so we can test connections persistence while draining). h3_request was accidentally postponing output until complete. This change makes it output as the packets arrive. Also removes some unused imports.
Risk Level: None, tool not yet used.
Testing: Used with upcoming test update, addresses the problem.
=> Make h3_request stream output

contrib/postgres_proxy/filters/network/source/postgres_filter.cc, contrib/postgres_proxy/filters/network/source/postgres_filter.h, contrib/postgres_proxy/filters/network/test/postgres_filter_test.cc, contrib/postgres_proxy/filters/network/test/postgres_integration_test.cc, test/integration/integration_tcp_client.h
postgres: fix connection issue when downstream and upstream SSL is enabled
The problem was with how postgres filter replied to downstream client during SSL negotiation. The reply was sent through entire filter chain instead of only through downstream filters. That caused postgres filter to receive one extra character which was not recognized by decoder and caused connection reset. 
Testing: Added integration test for upstream and downstream SSL connections.
Docs Changes: No.
Release Notes: No.
Fixes #27808
=> postgres: fix connection issue when downstream and upstream SSL is enabled

test/integration/multiplexed_integration_test.cc
to resolve compile-time-options test fail
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/tests: Lengthen the timeout

ci/README.md, ci/do_ci.sh
v1.27 cherry-pick of https://github.com/envoyproxy/envoy/pull/30204
=> [bp/1.27] Add release target to copy binary after build server_only (#30204)

ci/README.md, ci/do_ci.sh
=> [bp/1.26] Add release target to copy binary after build server_only (#30204)

test/integration/hotrestart_handoff_test.py
Commit Message: Make hotrestart_handoff_test not port conflict
Additional Description: There's a flake when hot restart related tests all use `@envoy_domain_socket` as the communication port path; if two such tests run in parallel, the socket can be in use and cause a failure. This change fixes hotrestart_handoff_test to avoid such conflicts (other tests still may experience it.)
Risk Level: None, test-only
Testing: Not even verified it addresses the problem, because it's a hard to repro rare flake.
=> Make hotrestart_handoff_test not port conflict

test/integration/hotrestart_test.sh, test/server/BUILD, test/server/hot_restart_impl_test.cc, test/server/hot_restarting_child_test.cc, test/server/hot_restarting_parent_test.cc, test/server/utility.h
Commit Message: Fix envoy_domain_socket conflict flakes
Additional Description: Various hot-restart-related tests use `@envoy_domain_socket` as a communication channel. If more than one of these tests run at the same time, a conflict can occur, resulting in a flaky failure. This change makes all these instances use `@envoy_domain_socket_{process_id}`, which should prevent those flakes.
Risk Level: Test-only.
=> Fix envoy_domain_socket conflict flakes

mobile/library/cc/engine_builder.cc, mobile/test/common/integration/cds_integration_test.cc
This PR exports `cluster_manager.updated_clusters` and `cluster_manager.cluster_removed` when CDS is used in Envoy Mobile.
=> mobile: Export clusters updated/removed stats

.azure-pipelines/ci.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.26] ci/rbe: Only enable BES where project is set (#30318)

.azure-pipelines/ci.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.28] ci/rbe: Only enable BES where project is set (#30318)

mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h
This PR does some code clean up by:
- Adding missing `std::move` to avoid unncessary copy.
- Removing unncessary `std::move`, especially when calling a function that accepts a const reference.
- Removing unncesssary `apple_dns_resolver` include when the platform is not Apple.
Testing: n/a
=> mobile: Code clean up in engine_builder.cc

BUILD, distribution/dockerhub/BUILD, mobile/BUILD, mobile/docs/BUILD, tools/BUILD, tools/base/envoy_python.bzl, tools/code/BUILD, tools/dependency/BUILD, tools/distribution/BUILD, tools/docs/BUILD, tools/h3_request/BUILD, tools/proto_format/BUILD, tools/protodoc/BUILD, tools/protoprint/BUILD, tools/python/BUILD, tools/python/namespace.bzl, tools/repo/BUILD
Commit Message: Separate envoy_py_namespace to avoid cascading dependencies
Additional Description: Before this change, envoy_py_namespace cascading into a `bzl load()` dependency on `@base_pip3`, which makes binary builds that don't actually have this dependency need to pull in a bunch more repos than they actually need.
Risk Level: None, change is a no-op.
Testing: CI should tell us if anything build-related broke.
=> Separate envoy_py_namespace to avoid cascading dependencies

.github/workflows/mobile-android_build.yml, mobile/ci/start_android_emulator.sh
This is an attempt to fix multiple timeout failures when starting the Android emulator by doing the following:
- Update the system image to Android 30 ATD image instead of 29. The ATD image is a headless system image that consumes less CPU and memory. 
- Use a specific hardware profile, i.e. Pixel 4 instead of the default hardware profile since the default hardware profile only has 128MB.
This also adds some logging when starting the emulator instead of redirecting everything to `/dev/null` to make debugging easier.
Testing: CI
=> mobile/ci: Fix flaky start Android emulator step

contrib/postgres_proxy/filters/network/test/postgres_integration_test.cc
fixed race condition in postgres integration test
Typical race condition. Reply was received before calling _clearData_, which basically dropped received reply.
Testing: Verified that previously failing test does not fail anymore.
Fixes #30330
=> test: fixed race condition in postgres integration test

source/common/grpc/async_client_manager_impl.cc, source/common/grpc/async_client_manager_impl.h, test/common/grpc/async_client_manager_impl_test.cc
In grpc async client, if timer expiry handler function gets fired where time to next_expiry is less than 1 sec, a loop gets created where timer gets enabled with 0 secs expiry again and again until 'now' becomes as next_expiry. This causes random cpu spikes. If there is HPA configured on cpu, this will result in scale up and scale down on proxies.
I added some logs while debugging it. Sharing here might help understanding the issue more clearly:
```
AsyncClientManagerImpl::evictEntriesAndResetEvictionTimer
[2023-09-08 10:27:32.640][22][info][grpc] [external/envoy/source/common/grpc/async_client_manager_impl.cc:198] AsyncClientManagerImpl::evictEntriesAndResetEvictionTimer next_expire: 966826645315069, now 966825877367850
[2023-09-08 10:27:32.640][22][info][grpc] …
```
=> Fix intermittent cpu spike in grpc async client

.github/workflows/_env.yml, .github/workflows/envoy-dependency.yml, BUILD, tools/dependency/BUILD, tools/dependency/version.sh
This ~automates the tricky process of updating the build images
This iteration is very limited
- no handling of existing PRs (you must manually deleted existing/branch to update)
- no update of toolchains - this will be addressed in a follow up
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> gh/wf: Add build image updater

source/extensions/filters/http/connect_grpc_bridge/filter.cc, test/extensions/filters/http/connect_grpc_bridge/connect_grpc_bridge_filter_test.cc
Commit Message: connect_grpc_bridge: support requests with no body
gRPC calls with no body are sent with Content-Length: 0 from the browser and makes `decodeData` to not be called. It's worth noting that when using `buf curl` this doesn't happen because `buf` sends the request with `Transfer-Encoding: chunked` which makes the body non-zero even in the empty case (which is `\x30\x0d\x0a\x0d\x0a`)
Testing: n/a
=> connect_grpc_bridge: support requests with no body

.github/workflows/mobile-android_build.yml, mobile/ci/start_android_emulator.sh
This PR increases the emulator timeout to 15 minutes from 10 minutes since I have seen a number of instances where the emulator took close to 10 minutes.
Testing: CI
=> mobile/ci: Increase the emulator timeout to 15 minutes

api/envoy/type/matcher/v3/value.proto, source/common/common/matchers.cc, source/common/common/matchers.h, test/common/common/matchers_test.cc
Commit Message: Extend matcher to support alternatives.
Additional Description: JWT claims allow optional lists, e.g. `"x"` and `["x"]` are allowed for `aud` claim. When used for routing using dynamic metadata ([here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routematch)), we cannot express a way to match either of these options.
Testing: done
Release Notes: none (minor feature)
Issues: #29681
=> value matcher: add OR matcher

source/extensions/filters/http/connect_grpc_bridge/filter.cc, test/extensions/filters/http/connect_grpc_bridge/connect_grpc_bridge_filter_test.cc
Commit Message: connect_grpc_bridge: remove request content-length
We need to always remove Content-Length since the request on the other side of the filter is chunked with a different body size.
=> connect_grpc_bridge: remove request content-length

mobile/test/common/integration/client_integration_test.cc, source/common/common/logger.cc
Fixes the TSAN issue in ClientIntegrationTest.Http3WithQuicHints. The crux of the problem appears to be that Envoy and Envoy mobile both share current_context[1] to configure their logging subsystem. (Which, of course they do because they're both "Envoy")
But Envoy consults this variable when starting the UDP listener and Envoy Mobile sets this variable when starting Envoy Mobile. Annoyingly, in this test, we need to start Envoy first in order to get the IP address/port which we write into the config we use when starting Envoy Mobile.
This switches current_context to std::atomic which should be pretty low overhead, as it's guaranteed to be lock-free.
1. https://github.com/envoyproxy/envoy/blob/main/source/common/common/logger.cc#L161
=> logging: Use std::atomic for Envoy::Logger::current_context

mobile/bazel/envoy_mobile_dependencies.bzl, mobile/library/cc/BUILD, mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h, mobile/library/common/jni/BUILD, mobile/library/common/jni/jni_interface.cc, mobile/library/common/jni/jni_utility.cc, mobile/library/common/jni/jni_utility.h, mobile/library/java/io/envoyproxy/envoymobile/engine/BUILD, mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java, mobile/library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java, mobile/library/java/org/chromium/net/impl/BUILD, mobile/library/java/org/chromium/net/impl/NativeCronvoyEngineBuilderImpl.java, mobile/library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt, mobile/test/cc/unit/envoy_config_test.cc, mobile/test/java/io/envoyproxy/envoymobile/engine/BUILD, mobile/test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt, mobile/test/kotlin/integration/EngineApiTest.kt
This adds `EngineBuilder::setNodeMetadata` to set `node.metadata` field in `Bootstrap` configuration in addition to those that are automatically set by Envoy Mobile, i.e. `api_id`, `api_version`, and `device_os`.
Risk Level: low (new API addition)
Testing: unit test + integration test
=> mobile: Add an API to set node metadata in the EngineBuilder

source/common/quic/BUILD, source/common/quic/http_datagram_handler.cc, source/common/quic/send_buffer_monitor.cc, test/common/quic/BUILD, test/common/quic/envoy_quic_h3_fuzz_helper.h
This should not affect any functionality -- the only impact should be a modest compile-time impact, in exchange for making the code more resilient to changes in dependencies.
Commit Message: quic: include some missing headers.
Testing: n/a
Docs Changes:
Release Notes:
=> quic: include some missing headers.

.github/workflows/mobile-release.yml, mobile/BUILD, mobile/bazel/android_artifacts.bzl, mobile/bazel/pom_template.xml, mobile/examples/java/hello_world/BUILD, mobile/examples/kotlin/hello_world/BUILD, mobile/library/java/org/chromium/net/BUILD, mobile/library/kotlin/io/envoyproxy/envoymobile/BUILD, mobile/library/proguard.txt, mobile/test/kotlin/apps/baseline/BUILD, mobile/test/kotlin/apps/experimental/BUILD
This PR builds a separate Android library (AAR) that supports xDS and publishes it to Maven Central. This library will have `artifactId`: `envoy-xds`.
Testing: CI
=> mobile: Publish Android library (AAR) with xDS support

docs/README.md
Commit Message: docs: add note about building docs without docker
Testing: none
Docs Changes: README
#30077
=> docs: add note about building docs without docker

bazel/aspect.patch, bazel/repositories.bzl
upstream issue is https://github.com/aspect-build/bazel-lib/issues/548 pr is: https://github.com/aspect-build/bazel-lib/pull/547
Currently the websites and archive patch this independently
This caused a breakage (in all 3) when aspect lib was updated
https://github.com/envoyproxy/envoy-website/issues/368
This should prevent that until there is some upstream resolution
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel: Patch aspect lib to resolve external build issue

changelogs/current.yaml, source/common/grpc/async_client_manager_impl.cc, test/common/grpc/async_client_manager_impl_test.cc
backport of https://github.com/envoyproxy/envoy/pull/30123
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [backport 1.27] Fix intermittent cpu spike in grpc async client (#30123)

.github/workflows/mobile-release.yml, mobile/ci/sonatype_nexus_upload.py
This PR adds a `--artifact_id` flag in the `sonatype_nexus_upload.py` to allow specifying the artifact ID when publishing to Maven Central.
Testing: CI
=> mobile: Add a flag to specify the artifact ID when publishing to Maven

api/envoy/extensions/filters/http/jwt_authn/v3/config.proto, changelogs/current.yaml, docs/root/configuration/http/http_filters/jwt_authn_filter.rst, source/extensions/filters/http/jwt_authn/authenticator.cc, test/extensions/filters/http/jwt_authn/authenticator_test.cc, test/extensions/filters/http/jwt_authn/test_common.h
Commit Message: Allow to extract object from jwt struct claims
Serialize non-primitive custom claim objects from JWT tokens. The JWT filter will now serialize these claim as JSON and encode it to Base64.
Docs Changes: Updated `docs/root/configuration/http/http_filters/jwt_authn_filter.rst`
Release Notes: Updated `changelogs/current.yaml`
=> jwt_authn: Allow to extract keys from jwt struct claims

test/common/upstream/cluster_manager_impl_test.cc, test/common/upstream/test_cluster_manager.h
The class is only used within cluster_manager_impl_test and is very specific in its behavior, so I think it makes more sense to locate it in the same file as the test that uses it, instead of keeping it in test_cluster_manager.h.
=> test: Move MockedUpdatedClusterManagerImpl to cluster_manager_impl_test

source/server/config_validation/BUILD, source/server/config_validation/server.h
Commit Message: Make config_validation not have hot_restart panics
Additional Description: Now that there is a call to `server_.hotRestart()` (introduced in https://github.com/envoyproxy/envoy/commit/bd7225e068a45ebda184036fb851af7fa97e8500) that can apparently occur in the validation context, that can provoke a panic. Instead of panicking, we should just do nothing, which is easily achieved by using the `HotRestartNopImpl` class.
Risk Level: Fix.
Testing: The code path that provokes this should have been already tested; fixing it first seems more important than testing it. Plan to add that test later but no time right now.
=> Make config_validation not have hot_restart panics

mobile/test/common/integration/BUILD, mobile/test/common/integration/xds_test_server.cc, mobile/test/common/jni/test_jni_interface.cc, mobile/test/kotlin/integration/XdsTest.kt
This required fixing a couple issues in XdsTestServer:
(1) Initialize Libevent before creating the Dispatcher. If we don't do this, and we start the XdsTestServer without starting the Http2TestServer, the LibeventScheduler fails the
Libevent::Global::initialized() assert.
(2) Add a Thread::SkipAsserts before calling the YAML to Bootstrap parsing. The YAML utilities make some non-relevant asserts on being on the main thread, which aren't applicable when calling the YAML utilities from JNI and tests.
To remove the need for the Http2TestServer, we remove the endpoints from the dynamic cluster returned in the test xDS response. This allows us to test the essential xDS behavior without depending on an endpoint for cluster initialization.
=> test: Enable XdsTest to run without the test HTTP server

mobile/library/cc/engine_builder.cc, mobile/library/common/jni/jni_utility.cc
This fixes a bug in the JNI code where a call to `ASSERT(some_func())` gets elided causing the code to do nothing.
Testing: unit test + manual test
=> mobile: Fix a bug where ASSERT is elided on a release build

.github/workflows/mobile-release.yml
`--config=mobile-release-android` has `--define=google_grpc=disabled` and if it appears after `--define=google_grpc=enabled`, it will set `--define=google_grpc=disabled` because the last one set wins. This PR fixes this issue by moving the `--define=google_grpc=enabled` last since xDS feature in Envoy Mobile requires Google gRPC.
=> mobile: Fix envoy-xds AAR

bazel/repositories.bzl
=> bazel: remove unused helper functions

contrib/generic_proxy/filters/network/source/codecs/dubbo/config.cc, contrib/generic_proxy/filters/network/source/codecs/dubbo/config.h, contrib/generic_proxy/filters/network/source/interface/codec.h, contrib/generic_proxy/filters/network/source/interface/codec_callbacks.h, contrib/generic_proxy/filters/network/source/proxy.cc, contrib/generic_proxy/filters/network/source/proxy.h, contrib/generic_proxy/filters/network/source/router/router.cc, contrib/generic_proxy/filters/network/source/router/router.h, contrib/generic_proxy/filters/network/source/upstream.cc, contrib/generic_proxy/filters/network/source/upstream.h, contrib/generic_proxy/filters/network/test/codecs/dubbo/config_test.cc, contrib/generic_proxy/filters/network/test/fake_codec.cc, contrib/generic_proxy/filters/network/test/fake_codec.h, contrib/generic_proxy/filters/network/test/integration_test.cc, contrib/generic_proxy/filters/network/test/mocks/codec.cc, contrib/generic_proxy/filters/network/test/mocks/codec.h, contrib/generic_proxy/filters/network/test/proxy_test.cc, contrib/generic_proxy/filters/network/test/router/router_test.cc
* generic proxy refactoring part 3: merge decoder and encoder to same interface
* fix test
---------
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.28] generic proxy refactoring part 3: merge decoder and encoder to same interface (#30381)

changelogs/current.yaml, source/extensions/access_loggers/grpc/grpc_access_log_utils.cc, source/extensions/access_loggers/grpc/grpc_access_log_utils.h, test/extensions/access_loggers/grpc/BUILD, test/extensions/access_loggers/grpc/grpc_access_log_utils_test.cc
At client side, if metadata exchange filter is an upstream filter, received filter state gets stored in the upstream streaminfo. While emitting access logs, streaminfo passed to the extractCommonAccessLogProperties() is the downstream side streaminfo. filter_state_objects_to_log keys must be searched in the usptream streaminfo's filter state as well.
Testing: done
backport of https://github.com/envoyproxy/envoy/pull/30057
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
=> [backport 1.27]Check upstreamInfo's filter state as well in grpc access logs (#30057)

.bazelrc
While this may slow builds down a little and result in slightly larger debug builds, it should reduce the size of production bins.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> build: Add `-fdebug-types-section`

source/common/http/http1/balsa_parser.cc, source/common/http/http1/balsa_parser.h
A new API for taking trailers has been introduced to BalsaFrame and BalsaVisitorInterface: EnableTrailers() and OnTrailers(unique_ptr<>). The old API of set_balsa_trailers() and ProcessTrailers() is deprecated. There is no behavior change.
Commit Message: [balsa] Use new BalsaFrame trailers API.
Testing: //test/common/http/http1:codec_impl_test and various integration tests
Runtime guard: envoy.reloadable_features.http1_use_balsa_parser (default enabled)
=> [balsa] Use new BalsaFrame trailers API.

mobile/library/common/jni/jni_interface.cc, mobile/library/common/jni/jni_utility.cc, mobile/library/common/jni/jni_utility.h, mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java
This PR adds the code to throw `java.lang.UnsupportedOperationException` when xDS feature is enabled on an unsupported Envoy Mobile AAR.
This PR also fixes a bug where it swallows every exception when trying to start Envoy.
=> mobile: Throw an exception when xDS is used on an unsupported Envoy Mobile

source/extensions/tracers/datadog/demo/docker-compose.yaml, source/extensions/tracers/datadog/demo/envoy, source/extensions/tracers/datadog/span.cc, test/extensions/tracers/datadog/span_test.cc
These changes restore the Dataodog tracer's ability to set the Datadog notion of span "resource name" by setting a special tag named "resource.name".
This was previously possible with the OpenTracing-based implementation of Datadog tracing, but I removed the capability when I moved Envoy's Datadog extension away from OpenTracing.
It turns out that [customers were using this feature][1]. This pull request restores it.
Please consider backporting this revision as a bug fix once it is merged.
I modified some existing unit tests.
Also, by applying the patch below, I used the Datadog "demo" with a local build of Envoy to verify that a `request_header`-based custom tag for the tag "resource.name" really does result in a change to the resource name:
```diff
diff --git …
```
=> Datadog: restore "resource.name" tag

source/extensions/extensions_metadata.yaml
Updating extension status of `envoy.resource_monitors.downstream_connections` to alpha, as it is functional with no known  TODOs. We have deployed it today on canary instances within prod environment. 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Update status for envoy.resource_monitors.downstream_connections

.github/workflows/mobile-android_build.yml, mobile/ci/start_android_emulator.sh
This PR adds a logic to fail fast when starting an emulator on a machine that is likely to fail. This PR also updates the `max_attempts` to 1 so that it is much faster to retest.
Testing: CI
=> mobile/ci: Fail fast when running on a machine that is likely to fail

.github/actions/do_ci/action.yml
I used dependabot to bump to make earlier pr work - but it seems it didnt bump this dep
ill look to see if i can see why
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/verify: Bump toolshed action to fix env

ci/do_ci.sh, ci/run_envoy_docker.sh
Couldn't see another way to make docker export to tarballs without needlessly setting a dummy DOCKER_PASSWORD
=> Add var to force docker save

envoy/http/filter.h, source/common/http/async_client_impl.cc, source/common/http/async_client_impl.h, source/common/http/filter_manager.cc, source/common/http/filter_manager.h, test/common/http/filter_manager_test.cc, test/mocks/http/mocks.h
Commit Message: unified interfaces to access request/response headers/trailers
It is a usual requirement to access request/response headers/trailers in different phases of request/response processing.
In current implementation, the most common way to achieve this target is the filter itself to store the headers/trailers pointers.
And I found the `StreamDecoderFilterCallbacks` has provided some methods to access response headers/trailers.
This patch extended exist methods and moved all them to `StreamFilterCallbacks` to ensure it's a common way to access request/response headers/trailers.
Risk Level: low. Thought I moved some interface but doesn't update any implementation.
Testing: unit.
=> unified interfaces to access request/response headers/trailers

api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
The docs around `metadata_context_namespaces` and `typed_metadata_context_namespaces` fields in the [ExtAuthZ filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-msg-extensions-filters-http-ext-authz-v3-buffersettings) are a little confusing as they don't specify that these are only applicable for gRPC variant and not HTTP.
Commit Message: add some clarification around the use of metadata in ExtAuthZ
Additional Description: added some clarification around `metadata_context_namespaces` and `typed_metadata_context_namespaces` fields to specify that they are only applicable for gRPC service.
Risk Level: Very Low
Testing: N/A …
=> docs: add some clarification around the use of metadata in ExtAuthZ

source/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/proxy_filter.cc, source/extensions/filters/udp/udp_proxy/session_filters/filter.h, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h, test/extensions/filters/udp/udp_proxy/mocks.cc, test/extensions/filters/udp/udp_proxy/mocks.h, test/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/proxy_filter_integration_test.cc, test/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/proxy_filter_test.cc
Commit Message: Fix segmentation fault in udp proxy filter
Additional Description: - proxy_filter.cc => Check host_info in onLoadDnsCacheComplete to verify that DNS lookup wasn't 
failed (because in case of failure "read_callbacks_->continueFilterChain();" will remove the session).
- udp_proxy_filter.cc => Add the session before calling "onNewSession" (because "onNewSession" will 
remove the session if it failed to create upstream connection pool).
Risk Level: low, fix a bug
=> Fix segmentation fault in udp proxy filter

.github/workflows/check-deps.yml, .github/workflows/envoy-prechecks.yml, ci/do_ci.sh, tools/dependency/BUILD
the dep checker tool can load the cve data dynamically or (for the purposes of bazel) from an existing file
currently it always downloads the file (subject to bazel caches)
this makes the preloading optional
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> deps/tooling: Make cve data preload optional

.bazelrc
Commit Message: Update c++ to 20 for windows.
Risk Level:
Testing:
Successful Local build
Docs Changes:
Release Notes:
=> Update to c++ 20 for windows

changelogs/current.yaml, source/extensions/filters/network/redis_proxy/router_impl.cc, test/extensions/filters/network/redis_proxy/router_impl_test.cc
Commit Message: Fix proxy crash if catch_all_route is not defined
Additional Description: If an incoming redis key does not match against any of the prefix_routes that maybe defined, the proxy crashes if catch_all_route is not defined. This bug handles "no route" matching scenario.
Docs Changes:
Release Notes:
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/29120
[Optional Fixes commit #PR or SHA] https://github.com/envoyproxy/envoy/pull/27902 / https://github.com/envoyproxy/envoy/pull/29138 ( change was reverted )
=> redis_proxy: fix crash if catch_all_route is not defined

tools/vscode/refresh_compdb.sh
Minor fix to clangdb refresh script. The `"$opts"` will be treat as variable length arguments if the `EXCLUDE_CONTRIB` is not set. In this case, the `bazel_targets` will be empty.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> fix: minor fix to the refresh clangdb script

ci/build_setup.sh, ci/run_envoy_docker.sh
Currently calling `ci/build_setup.sh` without specifying a `BUILD_DIR` defaults to `/build`
This was done as this is what is mounted in the build container, but this assumption makes most of the CI unusable outside of the container.
This PR uses a cache folder in the user's home directory as a default fallback which is a much more reasonable expectation.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> build/setup: Dont assume `/build` writeability

test/common/crypto/utility_test.cc, test/per_file_coverage.sh
This PR add some additional tests for `importPublicKey()` and `verifySignature()` methods to increase the unit test coverage of the crypto utils class. 
**Old:** 88.1% | **New:** 95.5%
[Coverage Report Link](https://storage.googleapis.com/envoy-pr/444c1b8/coverage/index.html)
Commit Message: increase test coverage of crypto utils.
Additional Description: added additional tests for `importPublicKey()` and `verifySignature()` to increase the unit test coverage of crypto utils.
Risk Level: Very Low
Testing: Yes
=> test: increase test coverage of crypto utils

changelogs/current.yaml, source/common/runtime/runtime_features.cc, test/common/http/codec_impl_fuzz_test.cc, test/integration/shadow_policy_integration_test.cc, test/mocks/event/mocks.cc, test/mocks/event/mocks.h
Commit Message: Flip the runtime guard ``envoy.reloadable_features.defer_processing_backedup_streams`` to be on by default.
Additional Description: This has had extensive burn time internally.
Testing: added tests in PR when originally committed, fixed minor breakages when this was not enabled for certain tests.
=> HTTP2: Enable deferred processing by default

mobile/tools/ktfmt.sh
Occassionally I've seen an error with `NoClassDefFoundError` when running the older JDK 11. After updating to the latest JDK 11, I no longer see the error.
Testing: n/a
=> mobile: Upgrade to the latest JDK 11 for ktfmt

api/bazel/envoy_http_archive.bzl, bazel/repositories.bzl, bazel/repository_locations.bzl, contrib/cryptomb/private_key_providers/source/BUILD
Envoy build with boringssl-fips is broken. #30001 introduces a patch to remove BoringSSL-specific definition of BN_bn2lebinpad in ipp-crypto library. It works for non-fips build but fips build fails with declaration error, remove the patch for fips build.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Fix broken fips build

.azure-pipelines/stages.yml
This reverts the build/test stage to using a faster machine
I think this is justified on the basis that many other stages wait for this, so it can have a big impact.
Also in the majority of cases the larger machine is offset (at least in part) by the faster run
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> azp/ci: Boost x64 build/test

.github/workflows/mobile-compile_time_options.yml, .github/workflows/mobile-core.yml
Removing options in mobile bazelrc to make things more clear.
=> mobile: removing default build options from CI

api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto, api/envoy/service/auth/v3/attribute_context.proto, changelogs/current.yaml, source/extensions/filters/common/ext_authz/check_request_utils.cc, source/extensions/filters/common/ext_authz/check_request_utils.h, source/extensions/filters/http/ext_authz/ext_authz.cc, source/extensions/filters/http/ext_authz/ext_authz.h, test/extensions/filters/common/ext_authz/check_request_utils_test.cc, test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc, test/extensions/filters/http/ext_authz/ext_authz_test.cc
Add the ability to ext_authz that collect spcified namespaces from route metadata, and propagate them to external auth service. #30252
The instruction of what namespace to select from route metadata, and the field in CheckRequest where the metadata context from route is filled are totally separate from those metadata context from connection or request.
Docs Changes: Proto description updated.
Release Notes: Updated changelog
=> Propagate route metadata in ext_authz

source/common/quic/envoy_quic_utils.cc
Casting old_connection_id_ptr to a uint32_t is not safe because there is no guarantee that old_connection_id_ptr is 32 bit aligned. Instead, just call memcpy() explicitly with the size of 4.
=> quic: Fix potential pointer alignmnet issue in adjustNewConnectionIdForRouting

mobile/library/common/jni/android_jni_interface.cc, mobile/library/common/jni/android_jni_utility.cc, mobile/library/common/jni/android_network_utility.cc, mobile/library/common/jni/jni_helper.cc, mobile/library/common/jni/jni_helper.h, mobile/library/common/jni/jni_interface.cc, mobile/library/common/jni/jni_utility.cc, mobile/library/common/jni/jni_utility.h
There is no reason why `jni_interface.(h|cc)` cannot have a namespace since it does not use `extern "C"`.
Risk Level: low (cosmetic changes)
Testing: n/a
=> mobile: Add namespace to jni_interface.(h|cc)

mobile/library/cc/engine_builder.cc, mobile/test/common/integration/cds_integration_test.cc
In Envoy Mobile, we limit the stats exported to a specific set: https://github.com/envoyproxy/envoy/blob/e1139dad262eef175d35978337d9879c246ccb46/mobile/library/cc/engine_builder.cc#L137. It turns out that the logic in ClusterManagerImpl requires checking the `warming_clusters` guage to see if we can resume sending DiscoveryRequests for a given type (including ACKs): https://github.com/envoyproxy/envoy/blob/e1139dad262eef175d35978337d9879c246ccb46/source/common/upstream/cluster_manager_impl.cc#L1017. That ScopedResume object never gets reset to have its cleanup run (which would reduce the pauses_ count and allow DiscoveryRequests to resume), because, despite updating the warming_clusters stat, we haven't allowlisted that stat in Envoy Mobile, so the stat doesn't actually get set (a no-op …
=> mobile: Fix xDS DiscoveryRequest ACKs in Envoy Mobile

mobile/library/cc/engine_builder.cc, source/common/upstream/cluster_manager_impl.cc, source/common/upstream/cluster_manager_impl.h
As discussed in https://github.com/envoyproxy/envoy/pull/30700, ClusterManagerImpl relies on the `warming_cluster` gauge to determine when DiscoveryRequests can be unpaused. However, if the stat is not allowlisted (like it wasn't in Envoy Mobile, resulting in a no-op implementation being used), there will be bugs in the resumption of the Cluster type's DiscoveryRequests.
This commit fixes the issue by introducing a "last recorded warming clusters count" variable in ClusterManagerImpl, which we use to record the previous warming clusters size. This way, we don't need to rely on the stat to do the record keeping and makes the DiscoveryRequest resumption code more robust to different stat configurations.
We don't need additional tests, since this is an internal implementation detail, and we …
=> xds: Don't rely on stats to keep track of warming clusters

source/common/formatter/BUILD, source/common/formatter/substitution_formatter.cc, source/common/formatter/substitution_formatter.h, tools/code_format/config.yaml
Commit Message: Don't compile an expensive regex for each substitution formatter
Additional Description: Static regex can be a singleton.
Risk Level: ~Zero, behavior should be identical but faster
Testing: Existing test coverage, plus tested on some of our end to end test initialization which went from taking 70s to 26s.
=> Don't compile an expensive regex for each substitution formatter

envoy/router/router.h, source/common/router/router.cc, source/extensions/upstreams/http/generic/config.cc, source/extensions/upstreams/http/generic/config.h, source/extensions/upstreams/http/http/config.cc, source/extensions/upstreams/http/http/config.h, source/extensions/upstreams/http/http/upstream_request.h, source/extensions/upstreams/http/tcp/config.cc, source/extensions/upstreams/http/tcp/config.h, source/extensions/upstreams/http/tcp/upstream_request.h, source/extensions/upstreams/http/udp/config.cc, source/extensions/upstreams/http/udp/config.h, test/common/http/hcm_router_fuzz_test.cc, test/extensions/upstreams/http/generic/config_test.cc, test/extensions/upstreams/http/tcp/upstream_request_test.cc, test/extensions/upstreams/http/udp/config_test.cc, test/integration/upstreams/per_host_upstream_config.h
upstream: Pass in UpstreamPriority not RouteEntry when creating connection pools
Risk Level: N/A - Simple refactor
=> upstream: Pass in UpstreamPriority not RouteEntry when creating connection pools

changelogs/current.yaml, source/common/network/tcp_listener_impl.cc, source/server/server.cc, test/extensions/resource_monitors/downstream_connections/cx_limit_overload_integration_test.cc, test/integration/cx_limit_integration_test.cc
Backport for https://github.com/envoyproxy/envoy/pull/30620
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Undeprecate global_downstream_max_connections key (#30620)

mobile/library/common/jni/jni_helper.cc, mobile/library/common/jni/jni_helper.h, mobile/library/common/jni/jni_interface.cc, mobile/library/common/jni/jni_utility.cc, mobile/test/common/jni/jni_helper_test.cc, mobile/test/java/io/envoyproxy/envoymobile/jni/JniHelperTest.java
This updates the following methods:
- `SetObjectArrayElement`
- `SetByteArrayRegion`
This PR also adds missing `Set<Primitive>ArrayRegion` methods into `JniHelper`.
=> mobile: Part 3: Update JNI usages with JniHelper

configs/proxy_connect_udp_http3_downstream.yaml, configs/terminate_http3_connect_udp_dns_resolution.yaml
Enabling CONNECT-UDP support requires `allow_extended_connect` option set, which was missing in the existing config examples. I fixed this issue and also added another example config that utilizes the dynamic forward proxy filter for DNS resolution.
Risk Level: Low, config only change.
Testing: N/A
=> configs: fix and add CONNECT-UDP configs

bazel/repositories.bzl, bazel/repository_locations.bzl
Commit Message: deps: update the deprecation status of libcurl
Following the merge of https://github.com/envoyproxy/envoy/pull/29880 and https://github.com/envoyproxy/envoy/pull/30626 we can mark the curl usage as deprecated. Meanwhile bazel/repositories.bzl had stale info that OpenCensus tracer was still using libcurl. 
We can continue to keep the Issue https://github.com/envoyproxy/envoy/issues/11816 open until curl is removed entirely after the deprecation time (Probably for v1.31 release).
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_che …
=> deps: update the deprecation status of libcurl

source/extensions/filters/http/ext_proc/processor_state.cc
Commit Message: ext_proc: fix typo
small comment typo.
Testing: N/A
Release Notes: N/a
=> ext_proc: fix typo

mobile/library/common/jni/android_jni_utility.cc, mobile/library/common/jni/android_network_utility.cc, mobile/library/common/jni/jni_helper.cc, mobile/library/common/jni/jni_helper.h, mobile/library/common/jni/jni_interface.cc, mobile/library/common/jni/jni_utility.cc
This updates the following JNI methods:
- `Get<Type>ArrayElements`
- `GetObjectArrayElement`
- `GetStaticMethodID`
This also updates `GetObjectArrayElement` to be a template method that does an automatic casting to make the API easier to use, especially for converting `jobject` into a different type since that use case is quite common in the codebase.
=> mobile: Part 4: Update JNI usages with JniHelper

api/contrib/envoy/extensions/filters/network/kafka_broker/v3/kafka_broker.proto, api/envoy/config/filter/network/kafka_broker/v2alpha1/kafka_broker.proto, contrib/kafka/filters/network/source/broker/BUILD, contrib/kafka/filters/network/source/broker/config.cc, contrib/kafka/filters/network/source/broker/filter.cc, contrib/kafka/filters/network/source/broker/filter_config.cc, contrib/kafka/filters/network/source/broker/filter_config.h, contrib/kafka/filters/network/source/broker/rewriter.cc, contrib/kafka/filters/network/source/broker/rewriter.h, contrib/kafka/filters/network/source/kafka_response.h, contrib/kafka/filters/network/source/protocol/complex_type_template.j2, contrib/kafka/filters/network/test/broker/BUILD, contrib/kafka/filters/network/test/broker/filter_protocol_test.cc, contrib/kafka/filters/network/test/broker/integration_test/envoy_config_yaml.j2, contrib/kafka/filters/network/test/broker/integration_test/kafka_server_properties.j2, contrib/kafka/filters/network/test/broker/mock_filter_config.h, contrib/kafka/filters/network/test/broker/rewriter_unit_test.cc, docs/root/configuration/listeners/network_filters/kafka_broker_filter.rst
Commit Message: kafka: make broker filter rewrite metadata, find-coordinator responses
New optional ability - Kafka client does the server discovery via metadata/find-coordinator requests (this way it knows which nodes actually host the Kafka partitions to send/receive from).
This makes proxying Kafka harder than usual because the Kafka broker itself needs to advertise itself with _proxy's_ listener. To make our lives a bit easier - why not let the filter rewrite the responses so that someone can just put Envoy proxies in front of the cluster. Possibly even multiple "Envoy fleets" if we want to play with multitenancy etc. Part of https://github.com/envoyproxy/envoy/issues/30669
Testing: unit + integration tests; manual tests with …
=> kafka: make broker filter rewrite metadata, find-coordinator responses

changelogs/current.yaml, source/extensions/tracers/datadog/tracer.cc, source/extensions/tracers/datadog/tracer.h, test/extensions/tracers/datadog/tracer_test.cc
Commit Message: datadog: honor extracted sampling decisions (backport #30577 onto v1.27)
Additional Description: This is a backport of PR #30577 onto the v1.27 release branch.
Testing: See the unit test included here and the description of manual testing from <https://github.com/envoyproxy/envoy/pull/30577>.
Release Notes: See included modifications to `changelogs/current.yaml`.
=> datadog: honor extracted sampling decisions (backport #30577 onto v1.27)

changelogs/current.yaml, source/extensions/tracers/datadog/tracer.cc, source/extensions/tracers/datadog/tracer.h, test/extensions/tracers/datadog/tracer_test.cc
Commit Message: datadog: honor extracted sampling decisions (backport #30577 onto v1.28)
Additional Description: This is a backport of PR #30577 onto the v1.28 release branch.
Testing: See the unit test included here and the description of manual testing from <https://github.com/envoyproxy/envoy/pull/30577>.
Release Notes: See included modifications to `changelogs/current.yaml`.
=> datadog: honor extracted sampling decisions (backport #30577 onto v1.28)

mobile/library/common/jni/android_network_utility.cc, mobile/library/common/jni/android_network_utility.h, mobile/library/common/jni/jni_helper.cc, mobile/library/common/jni/jni_helper.h, mobile/library/common/jni/jni_interface.cc, mobile/library/common/jni/jni_utility.cc, mobile/library/common/jni/jni_utility.h
This updates the following methods:
- `CallObjectMethod`
- `CallStaticObjectMethod`
This PR adds `[[nodiscard]]` to make sure we always assign the `unique_ptr` into a variable when calling some JNI functions to avoid any leaks. The `callObjectMethod` and `callStaticObjecMethod` from `JniHelper` has been templatized to make them easy to use, especially when casting from `jobject` to a different type. Some usages of `Envoy::JNI::checkAndClear` have also been removed since we don't want to shallow the exceptions in most cases.
=> mobile: Part 5: Update JNI usages with JniHelper

mobile/library/common/jni/jni_interface.cc, mobile/library/common/jni/jni_utility.cc, mobile/library/common/jni/jni_utility.h
This updates the following methods:
- `GetObjectArrayElement`
- `GetObjectClass`
This PR also deletes `javaObjectArrayToMatcherData` since it's unused.
=> mobile: Part 6: Update JNI usages with JniHelper

mobile/library/common/jni/android_network_utility.cc, mobile/library/common/jni/jni_helper.h, mobile/library/common/jni/jni_interface.cc, mobile/library/common/jni/jni_utility.cc, mobile/library/common/jni/jni_utility.h
This PR updates the following methods:
- `New<Type>Array`
- `NewObject`
This PR also updates some functions in `jni_utility.(h|cc)` to return a smart pointer instead of a raw pointer.
=> mobile: Part 7: Update JNI usages with JniHelper

source/common/upstream/load_balancer_impl.cc, test/common/upstream/load_balancer_impl_test.cc, test/integration/http_subset_lb_integration_test.cc
Commit Message: fix: only enable full scan when enable_full_scan is set explicitly forleast request lb
https://github.com/envoyproxy/envoy/pull/29873 introduced a minor breaking change. The full scan will be enabled automatically when host num is less than choice count.
Although from technical point, I think this change basically harmless and could make a better load balancing result, a new runtime guard should be enough.
But in practice, it effects our downstream users in a unexpected way. See https://github.com/envoyproxy/envoy/pull/30768#discussion_r1387092315
No change log is updated or added because our change log or doc doesn't mention that full scan will be enabled automatically when host num less than choice count.
Risk Level:
Testing:
Docs Changes:
Release …
=> fix: only enable full scan when enable_full_scan is set explicitly forleast request lb

contrib/kafka/filters/network/source/broker/rewriter.cc, contrib/kafka/filters/network/source/broker/rewriter.h, contrib/kafka/filters/network/test/broker/rewriter_unit_test.cc, docs/root/configuration/listeners/network_filters/kafka_broker_filter.rst
Commit Message: kafka: rewrite DescribeCluster responses
Additional Description: newer versions of Kafka support DC request that basically tells us how does the upstream cluster look like - we can amend that response as well; part of https://github.com/envoyproxy/envoy/issues/30669
Testing: unit tests, integration tests, manual testing via [envoy-kafka-tests](https://github.com/adamkotwasinski/envoy-kafka-tests/pull/10/files#diff-de48746df8477559316fbec54827b49974712b530d746181d874bbb4ea602514R151)
Docs Changes: minor doc update
=> kafka: rewrite DescribeCluster responses

mobile/library/common/jni/jni_helper.cc, mobile/library/common/jni/jni_helper.h, mobile/library/common/jni/jni_interface.cc, mobile/library/common/jni/jni_utility.cc
This PR updates the following methods:
- `NewGlobalRef`
- `GetPrimitiveArrayCritical`
This should be the last PR that updates the JNI usages to `JniHelper`. Most JNI code has been updated to use automatic memory management, except in few places.
=> mobile: Part 9: Update JNI usages with JniHelper

api/envoy/extensions/filters/http/rate_limit_quota/v3/rate_limit_quota.proto, api/envoy/service/rate_limit_quota/v3/rlqs.proto, docs/root/configuration/http/http_filters/rate_limit_quota_filter.rst
RLQS documentation updates intended to prevent memory exhaustion caused by the number of tracked buckets.
- Changes the default behavior of unset ExpiredAssignmentBehavior.expired_assignment_behavior_timeout from "retain unlimited time" to "abandon immediately"
- Clarifies the retention policy for the buckets that never received the initial assignment.
- Clarifies the implementation details for evicting buckets that never received the initial assignment.
---
Commit Message: rlqs: update and document failure mode behaviors
Additional Description: RLQS documentation updates intended to prevent memory exhaustion caused by the number of tracked buckets.
Testing: do_ci.sh 
Docs Changes:
- Changes the default behavior of unset …
=> rlqs: update and document failure mode behaviors

changelogs/current.yaml, source/common/formatter/substitution_format_string.h, source/common/local_reply/local_reply.cc, test/common/access_log/access_log_impl_test.cc, test/common/formatter/substitution_formatter_test.cc
When formatting access logs using `text_format_source`, the `omit_empty_values` field was not honored. This patch fixes that behavior.
Fixes: #29876 
=> access log: Honor `omit_empty_values` for text source

api/envoy/extensions/filters/http/credential_injector/v3/BUILD, api/envoy/extensions/injected_credentials/generic/v3/BUILD, api/envoy/extensions/injected_credentials/oauth2/v3/BUILD
Commit Message: cleanup: udpa to xds naming fix in BUILD files
PR #30802 updated the used repo name, and PR #27769 which was submitted concurrently did not have the same fix.
Fixing that.
Testing: N/A
=> cleanup: udpa to xds naming fix in BUILD files

mobile/library/common/common/default_system_helper_android.cc, mobile/library/common/http/client.cc, mobile/library/common/jni/android_jni_interface.cc, mobile/library/common/jni/android_jni_utility.cc, mobile/library/common/jni/android_jni_utility.h, mobile/library/common/jni/android_network_utility.cc, mobile/library/common/jni/android_network_utility.h, mobile/library/common/jni/jni_interface.cc, mobile/library/common/jni/jni_utility.cc, mobile/library/common/jni/jni_utility.h, mobile/library/common/network/socket_tag_socket_option_impl.cc
This PR refactors some functions that have mixed code styles from PascalCase to snake_case into camelCase, which is the Envoy code convention. Some functions have been renamed to give better names as well as adding more comments into the functions.
Testing: n/a
=> mobile: Use camelCase for function names

source/extensions/transport_sockets/tls/context_impl.cc
Commit Message: fix typo from candicate_ctx to candidate_ctx so searching with correct spelling works
Additional Description: Although typos in variables names don't affect the logic/execution it's good to have correctly spelt names so that searching with correct spelling works. So I wanted to fix this
Testing: rebuild/recompile
=> tls: fix typo from candicate_ctx to candidate_ctx so searching with correct spelling works!

api/bazel/repository_locations.bzl
Changes: https://github.com/cncf/xds/compare/e9ce688...523115e
- cel: add a description to the AST (cncf/xds#61)
- Bump bazel to 4.2.2 (cncf/xds#68)
- bazel: fix "missing strict dependencies" build issue (cncf/xds#72)
- bazel version updated from `4.2.2` to `6.3.2`
- `protoc-gen-validate` dependencies updated to match Envoy's
---
```
deps: Bump `com_github_cncf_xds` to cncf/xds@523115e
```
```
Changes: https://github.com/cncf/xds/compare/e9ce688...523115e
- cel: add a description to the AST (cncf/xds#61)
- Bump bazel to 4.2.2 (cncf/xds#68)
- bazel: fix "missing strict dependencies" build issue (cncf/xds#72)
- bazel version updated from `4.2.2` to `6.3.2`
- `protoc-gen-validate` dependencies updated to match Envoy's
```
Testing: …
=> deps: Bump `com_github_cncf_xds` to cncf/xds@523115e

mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h, mobile/test/cc/unit/BUILD, mobile/test/cc/unit/envoy_config_test.cc
Also, we add a test to verify the addDnsPreresolveHostnames behavior.
=> mobile: Update EngineBuilder's addDnsPreresolveHostnames to add a port

mobile/library/common/jni/jni_utility.cc, mobile/library/common/jni/jni_utility.h, mobile/test/common/jni/BUILD, mobile/test/common/jni/jni_utility_test.cc, mobile/test/java/io/envoyproxy/envoymobile/jni/BUILD, mobile/test/java/io/envoyproxy/envoymobile/jni/JniUtilityTest.java
Prior to this PR, `jni_utility.(h|cc)` did not have any unit tests, which would make refactoring that file a bit risky. This PR sets up an initial infrastructure for writing unit tests for `jni_utility.(h|cc)` as well as adds an example unit test, so that we can slowly add unit tests for the functions defined in that file as well as requiring unit tests for future changes to that file.
Risk Level: low (adding unit tests only)
=> mobile: Add initial unit tests for jni_utility.(h|cc)

mobile/library/BUILD, mobile/library/java_proto_proguard.txt, mobile/library/proguard.txt
Commit Message: Split java proto proguard rule into a separate spec file
Additional Description: This makes it easier to modify and patch different proguard spec files.
Testing: n/a
=> [mobile]Split java proto proguard rule into a separate spec file

api/STYLE.md
Commit Message: API: change style guide to discourage use of "oneof"
Testing: N/A
=> API: change style guide to discourage use of "oneof"

source/common/config/xds_resource.cc, source/common/config/xds_resource.h, test/common/config/xds_resource_test.cc, test/per_file_coverage.sh
Replacing DecodeException with a normal EnvoyException.  coverage lowered simply due to lines of code being lowered.
Testing: n/a
=> exceptions: removing DecodeException

changelogs/current.yaml
Commit Message: changelog: for buffer: separate the BufferFragement release and drain tracker
Testing: n/a
Release Notes: bugfix
=> changelog: for buffer: separate the BufferFragement release and drain tracker

test/common/quic/platform/quic_platform_test.cc, test/extensions/filters/http/cache/cache_filter_test.cc, test/test_common/logging.h
Commit Message: Make EXPECT_ENVOY_BUG not leak between test cases
Additional Description: Resolves #29217 (the problem is in release mode, bug-logs have exponential 'drop', which means if you EXPECT_ENVOY_BUG for the same line more than 2 times in a whole test suite, at least one of them will fail in coverage runs, without either this change, explicitly calling to clear the bug counters, or some common call to clear the bug counters deeper in the test framework.)
Risk Level: Negligible, test-only
Testing: Yes it is
=> Make EXPECT_ENVOY_BUG not leak between test cases

tools/repo/notify.py
I assume this change will let first-pass reviewers receive slack notifications.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tools: slack notification for first pass reviewers

api/bazel/BUILD, api/bazel/api_build_system.bzl, api/bazel/external_proto_deps.bzl, api/bazel/repository_locations.bzl, bazel/repositories.bzl, tools/protodoc/BUILD, tools/protoprint/BUILD, tools/protoxform/BUILD
`py_proto_library` provided by `@com_google_protobuf//:protobuf.bzl` has been deprecated for a while now:
> This is provided for backwards compatibility only. Bazel 5.3 will
> introduce support for py_proto_library, which should be used instead.\
> https://github.com/protocolbuffers/protobuf/blob/32af7d211b85f71920acdfa9b796db008f8c2a45/protobuf.bzl#L642-L644
However, native `py_proto_library` has never been provided, see https://github.com/bazelbuild/bazel/issues/3935. Instead `@rules_python//python:proto.bzl` is [recommended](https://github.com/bazelbuild/bazel/issues/3935#issuecomment-1680850640). I attempted switching to this library, but it's not compatible with `@com_google_googleapis`'s py_proto_library targets, see https://github.com/cncf/xds/pull/69. I found a hacky workaround by …
=> bazel: Migrate py_proto_library to `@com_github_grpc_grpc`

source/extensions/tracers/datadog/demo/docker-compose.yaml, source/extensions/tracers/datadog/demo/envoy, source/extensions/tracers/datadog/span.cc, test/extensions/tracers/datadog/span_test.cc
Hi 👋 - I hope opening a backport like this is the right approach. We would like to have this fix so that we can upgrade to 1.27 in our cluster - without it our trace spans have incorrect names.
I ran the tests locally as follows `bazel test --config=libc++ //test`. I used libc because my development environment had an unrelated issue with using the stdlib, which I believe is related to #30837.
Commit Message: [bp/1.27] Datadog: restore "resource.name" tag (#30503)
This is the backport of #30503 
Testing: local unit tests
Fixes: #30235
=> [bp/1.27] Datadog: restore "resource.name" tag (#30503)

source/extensions/tracers/datadog/demo/docker-compose.yaml, source/extensions/tracers/datadog/demo/envoy, source/extensions/tracers/datadog/span.cc, test/extensions/tracers/datadog/span_test.cc
Hi 👋 - I hope opening a backport like this is the right approach. We would like to have this fix so that we can upgrade to 1.27/1.28 in our cluster - without it our trace spans have incorrect names.
I ran the tests locally as follows `bazel test --config=libc++ //test`. I used libc because my development environment had an unrelated issue with using the stdlib, which I believe is related to #30837.
Commit Message: [bp/1.28] Datadog: restore "resource.name" tag (#30503)
This is the backport of #30503 
Testing: local unit tests
Fixes: #30235
=> [bp/1.28] Datadog: restore "resource.name" tag (#30503)

source/exe/BUILD
This should have no effect on Envoy, but for E-M in monorepo it avoids unnecessary extensions.
Testing: n/a
=> build: not auto-including core extensions in stripped main base

changelogs/current.yaml, source/common/buffer/buffer_impl.h, test/common/buffer/owned_impl_test.cc, test/extensions/io_socket/user_space/io_handle_impl_test.cc
Commit Message: [bp/1.28] buffer: separate the BufferFragement release and drain tracker (#28770)
This the backport of https://github.com/envoyproxy/envoy/pull/28770
There is a requirement for the user space io handle and iouring io handle to move the write buffer to its own buffer and invoke the drain trackers. But becomes an issue for the BufferFragment, the BufferFragement's releasor is invoked by the drain tracker also. After moving with invoke drain trackers, the memory in the BufferFragment will be released too, which leads to the Buffer reference some memory already released.
Related to issue: …
=> [bp/1.28] buffer: separate the BufferFragement release and drain tracker (#28770)

source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc, test/integration/udp_tunneling_integration_test.cc
Additional Description: Setting response flag in udp session info
Testing: integration test.
Docs Changes:
=> UDP Tunneling: Set response flag in udp session info

test/integration/multiplexed_integration_test.cc
Commit Message: iouring: disable request timeout for test CloseConnectionWithDeferredStreams
The test `CloseConnectionWithDeferredStreams` assumes the Envoy will receive all the new streams, but this is only true for the socket API. When using the socket API, Envoy will try to drain all the data from the system buffer.
But when using the iouring, the read request was submitted in advance. The size of data drained from the system buffer depends on the initial request setup. After reading part of the data, the envoy is going to the next event loop iteration. Then the request may get timeout in the next event loop. The request timeout triggers a response to the downstream, which will lead to the Envoy finding the downstream connection already closed. Then it closes …
=> iouring: disable request timeout for test CloseConnectionWithDeferredStreams

source/extensions/path/uri_template_lib/uri_template.cc, source/extensions/path/uri_template_lib/uri_template.h, test/extensions/path/uri_template_lib/uri_template_test.cc
Commit Message: uri_template: supporting operator<<
This minor change adds pretty-print support for thr uri_template `ParsedSegment`.
Testing: N/A
=> uri_template: supporting operator<<

changelogs/current.yaml, source/common/buffer/buffer_impl.h, test/common/buffer/owned_impl_test.cc, test/extensions/io_socket/user_space/io_handle_impl_test.cc
Commit Message: [bp/1.27] buffer: separate the BufferFragement release and drain tracker (#28770)
This the backport of https://github.com/envoyproxy/envoy/pull/28770
There is a requirement for the user space io handle and iouring io handle to move the write buffer to its own buffer and invoke the drain trackers. But becomes an issue for the BufferFragment, the BufferFragement's releasor is invoked by the drain tracker also. After moving with invoke drain trackers, the memory in the BufferFragment will be released too, which leads to the Buffer reference some memory already released.
Related to issue: …
=> [bp/1.27] buffer: separate the BufferFragement release and drain tracker (#28770)

changelogs/current.yaml, source/common/buffer/buffer_impl.h, test/common/buffer/owned_impl_test.cc, test/extensions/io_socket/user_space/io_handle_impl_test.cc
Commit Message: [bp/1.25] buffer: separate the BufferFragement release and drain tracker (#28770)
This the backport of https://github.com/envoyproxy/envoy/pull/28770
There is a requirement for the user space io handle and iouring io handle to move the write buffer to its own buffer and invoke the drain trackers. But becomes an issue for the BufferFragment, the BufferFragement's releasor is invoked by the drain tracker also. After moving with invoke drain trackers, the memory in the BufferFragment will be released too, which leads to the Buffer reference some memory already released.
Related to issue: …
=> [bp/1.25] buffer: separate the BufferFragement release and drain tracker (#28770)

changelogs/current.yaml, source/common/buffer/buffer_impl.h, test/common/buffer/owned_impl_test.cc, test/extensions/io_socket/user_space/io_handle_impl_test.cc
Commit Message: [bp/1.28] buffer: separate the BufferFragement release and drain tracker (#28770)
This the backport of https://github.com/envoyproxy/envoy/pull/28770
There is a requirement for the user space io handle and iouring io handle to move the write buffer to its own buffer and invoke the drain trackers. But becomes an issue for the BufferFragment, the BufferFragement's releasor is invoked by the drain tracker also. After moving with invoke drain trackers, the memory in the BufferFragment will be released too, which leads to the Buffer reference some memory already released.
Related to issue: …
=> [bp/1.26] buffer: separate the BufferFragement release and drain tracker (#28770)

api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
allowed_upstream_headers_to_append appends to client request, not response.
Testing: N/A
Docs Changes: update ext_authz.proto
Release Notes:
=> ext_authz: fix allowed_upstream_headers_to_append doc

source/extensions/upstreams/http/udp/upstream_request.cc, test/extensions/upstreams/http/udp/BUILD, test/extensions/upstreams/http/udp/upstream_request_test.cc
The existing implementation of UDP upstream did not make use of the upstream_bind_config. I modified the UDP Upstream code to check whether the bind config is specified and set the local address and socket option accordingly.
Risk Level: Low, this is a bug fix.
Testing: Added unit tests covering added code.
=> upstream: make upstream_bind_config work in udp upstream

envoy/formatter/http_formatter_context.h
logging: Add has() methods for to HttpFormatterContext
HttpFormatterContext was recently added to store request headers, response headers and trailers. It provides simple accessors for those which return the static empty maps if not present. However, there are some envoy users which would like to test if the headers are present or not.
=> logging: Add has() methods for to HttpFormatterContext

changelogs/current.yaml
Additional Description: Previous PR https://github.com/envoyproxy/envoy/pull/30434 did remove the flag but there was a typo on the release notes. The flag `correctly_validate_alpn` was already removed in [v1.24.0](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.24/v1.24.0.html)
Fixes: https://github.com/envoyproxy/envoy/issues/30424
=> docs: correcting flag removal

envoy/http/query_params.h, envoy/server/admin.h, source/common/http/utility.cc, source/common/http/utility.h, source/extensions/filters/http/aws_lambda/aws_lambda_filter.cc, source/extensions/filters/http/jwt_authn/extractor.cc, source/server/admin/admin_filter.cc, source/server/admin/admin_filter.h, source/server/admin/admin_html.cc, source/server/admin/admin_html_util.cc, source/server/admin/admin_html_util.h, source/server/admin/config_dump_handler.cc, source/server/admin/init_dump_handler.cc, source/server/admin/listeners_handler.cc, source/server/admin/logs_handler.cc, source/server/admin/logs_handler.h, source/server/admin/profiling_handler.cc, source/server/admin/runtime_handler.cc, source/server/admin/stats_params.cc, source/server/admin/stats_params.h, source/server/admin/utils.cc, source/server/admin/utils.h, test/common/http/utility_fuzz_test.cc, test/common/http/utility_test.cc, test/extensions/filters/http/oauth2/oauth_integration_test.cc, test/integration/admin_html/test_server.cc, test/mocks/server/admin_stream.h, test/server/admin/admin_html_util_test.cc, test/server/admin/stats_html_render_test.cc, test/server/admin/utils_test.cc
remove old version of QueryParams data structure
This is the final piece of series of PRs that began with #28788.  That PR fixed a bug in ext_authz query parameter mutation which was caused by treating query params as a `map<string, string>` when in fact they are a `map<string, vector<string>>`.
The `QueryParams` type also had a bunch of `TODO` comments around it.  @ggreenway suggested that we just replace it entirely with the new, nicely encapsulated type, and I agreed to do that.  This led to #29385, #29756, #29757, #29909, and #29910.
This PR:
* Converts the remaining usages of `QueryParams` to `QueryParamsMulti`
* Removes `QueryParams`
* Removes associated unit tests.
Testing: Existing unit tests appear to provide sufficient …
=> refactor to remove QueryParams in favor of QueryParamsMulti

source/extensions/geoip_providers/maxmind/geoip_provider.cc, test/extensions/filters/http/geoip/geoip_filter_integration_test.cc, test/extensions/geoip_providers/maxmind/geoip_provider_test.cc
According to [API docs
](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/geoip_providers/common/v3/common.proto#envoy-v3-api-msg-extensions-geoip-providers-common-v3-commongeoipproviderconfig) geolocation provider will populate country header with ISO country code, but currently it populates that header with country name instead.
Testing: Done
Release Notes:
=> [geoip] Lookup country and region iso code instead of name

.github/workflows/mobile-perf.yml, envoy/server/listener_manager.h, envoy/server/worker.h, mobile/library/common/engine_common.cc, mobile/library/common/extensions/listener_managers/api_listener_manager/api_listener_manager.h, source/extensions/listener_managers/listener_manager/listener_manager_impl.cc, source/extensions/listener_managers/listener_manager/listener_manager_impl.h, source/server/BUILD, source/server/instance_impl.cc, source/server/instance_impl.h, source/server/server.cc, source/server/server.h, source/server/worker_impl.cc, source/server/worker_impl.h, test/mocks/server/listener_manager.h, test/mocks/server/worker.cc, test/mocks/server/worker.h
Risk Level: low (refactor for Envoy)
Testing: n/a
=> mobile: removing guarddog and watchdog

mobile/test/common/integration/test_server.cc, mobile/test/common/integration/test_server.h
This PR updates the cert paths to use `TestEnvironment::runfilesPath` so that we can use `data` attribute without relying on the actual directory structure between Envoy Core and Envoy Mobile. This PR will make the code more portable and this is also best practice that Bazel recommends.
Risk Level: low (only affects tests)
Testing: n/a
=> mobile: Use TestEnvironment::runfilesPath for the cert paths

mobile/examples/cc/fetch_client/BUILD, mobile/examples/cc/fetch_client/fetch_client.cc, mobile/examples/cc/fetch_client/fetch_client.h
Without the MutexLock, tsan gives data race errors.
=> mobile: Fix data race in fetch_client

test/common/http/http1/codec_impl_test.cc
Commit Message: [balsa] Add test to document obsolete line folding behavior.
Additional Description: BalsaParser rejects line folding as suggested by RFC9110.
Risk Level: low, test-only
Also see #31009 for additional context.
Signed-off-by: Bence Béky [bnc@google.com](mailto:bnc@google.com)
=> [balsa] Add test to document obsolete line folding behavior.

source/exe/BUILD
refactoring source/exe/BUILD so only one library has stripped_main_base
Testing: CI
=> exe: build cleanup

source/common/protobuf/utility.cc, source/common/protobuf/utility.h, source/common/router/scoped_config_impl.cc, test/common/http/conn_manager_impl_fuzz_test.cc, test/common/protobuf/utility_test.cc, test/extensions/filters/network/common/fuzz/uber_per_readfilter.cc, test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test.cc, test/per_file_coverage.sh, test/tools/schema_validator/validator.cc
moving  ProtoValidationException,  MissingFieldException OutOfRangeException to EnvoyException
Testing: updated unit tests
https://github.com/envoyproxy/envoy/issues/30857
=> exceptions : normalizing 3 more exceptions

envoy/http/query_params.h, source/common/http/utility.cc
non const functions prevent us to pass parameters like `const Http::Utility::QueryParamsMulti&`
Testing:
Docs Changes:
Release Notes:
=> favor const member functions for Http::Utility::QueryParamsMulti

envoy/common/exception.h, envoy/filesystem/filesystem.h, source/common/filesystem/directory.h, source/common/filesystem/posix/directory_iterator_impl.cc, source/common/filesystem/posix/directory_iterator_impl.h, source/common/filesystem/win32/directory_iterator_impl.cc, source/common/filter/config_discovery_impl.cc, source/common/runtime/runtime_impl.cc, test/common/filesystem/BUILD, test/common/filesystem/directory_test.cc
Commit Message: Make directory iterators not throw exceptions
Additional Description: With the file system cache using directory iterators in the eviction thread, exceptions can be a problem (e.g. if a file is deleted while the directory iterator iterates, a stat() call can be provoked to fail and throw an exception). This change removes those exceptions, and also makes the directory iterator behavior less ambiguous with respect to trailing slashes (one error message showed `path//file` which should be remedied by this).
Incidentally partially cleaned up THROW_IF_NOT_OK set of macros.
Risk Level: Maybe in some context someone would prefer an exception to be thrown?
Testing: Modified existing tests.
Platform Specific Features: Implemented.
=> Make directory iterators not throw exceptions

changelogs/current.yaml, docs/root/configuration/http/http_filters/_include/aws_credentials.rst, source/common/runtime/runtime_features.cc, source/extensions/common/aws/credentials_provider_impl.cc, test/extensions/common/aws/credentials_provider_impl_test.cc
Commit Message: aws: fix usage of reloadable_features.use_http_client_to_fetch_aws_credentials
Additional Description: This feature flag will be release in v1.29. In v1.30 we will flip this feature flag to be default enabled. Finally in v1.31 release this feature flag will be removed.
Risk Level:
Testing:
Fixes: https://github.com/envoyproxy/envoy/issues/31119
=> aws: fix usage of reloadable_features.use_http_client_to_fetch_aws_credentials

examples/kafka/verify.sh, examples/websocket/verify.sh
Commit Message: ci: explicitly specify the service want to start for kafka example
CI failed on kafka and websocket example verify test:
```
kafka is missing dependency kafka-client
ERROR: starting kafka .
```
```
websocket is missing dependency client-ws
ERROR: starting websocket .
```
Testing: CI test
=> CI: explicitly specify the service want to start for kafka and websocket example

source/common/http/http1/balsa_parser.cc, test/common/http/http1/codec_impl_test.cc
Commit Message: [balsa] Enable line folding.
Additional Description: Enable line folding in BalsaParser; remove CR and LF characters to match http-parser behavior.
Risk Level: low, BalsaParser has only recently been default-enabled, and this PR makes its behavior match that of http-parser.
Runtime guard: envoy.reloadable_features.http1_use_balsa_parser (default enabled)
Fixes #31009.
=> [balsa] Enable line folding.

test/common/http/http1/codec_impl_test.cc
Commit Message: [balsa] Add tests to document that header value with null char is rejected.
Additional Description: Add tests to document that both BalsaParser and http-parser rejects a message that has a header value with null character in it.
Risk Level: low, test-only
=> [balsa] Add tests to document that header value with null char is rejected.

source/common/common/hash.cc, source/common/common/hash.h, test/common/common/hash_test.cc
Commit Message: Add HashUtil function for reliable hashing of scalar types
Additional Description: `xxHash64Value` is intended to be an improvement to https://github.com/envoyproxy/envoy/pull/30761 - in its current state that PR is not endian-safe, and this change will also make it more readable by removing a number of cast operations.
Risk Level: None, adding a function which is not yet used.
Platform Specific Features: Endianness!
=> Add HashUtil function for reliable hashing of scalar types

contrib/qat/compression/qatzip/compressor/source/BUILD
Add the related "-Wno-error" build options to suppress the warning errors:
[-Werror,-Wstrict-prototypes]
[-Werror,-Wunused-but-set-variable]
make[1]: Entering directory '../envoy/bazel-out/k8-opt/bin/contrib/qat/compression/qatzip/compressor/source/qatzip.build_tmpdir/src'
CC       libqatzip_la-qatzip.lo
In file included from qatzip.c:67:
./qatzip_internal.h:460:25: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void streamBufferCleanup();
^
void
qatzip.c:1703:18: error: variable 'sleep_cnt' set but not used [-Werror,-Wunused-but-set-variable]
unsigned int sleep_cnt = 0;
^
qatzip.c:2626:18: error: variable 'sleep_cnt' set but not used [-Werror,-Wunused-but-set-variable]
unsigned int sleep_cnt = 0;
^
3 errors generated. …
=> contrib: Fix libqatzip build errors on local clang-15

changelogs/current.yaml, docs/root/intro/arch_overview/other_protocols/redis.rst, source/extensions/filters/network/common/redis/supported_commands.h
Commit Message: Add support for the redis WATCH command
Additional Description: Allows the WATCH command to be used.  When a WATCH is in place on a given server, any changes to a watched key will cause subsequent MULTI transactions to abort.  Having support for WATCH is important as it allows transaction-like functionality (even though redis doesn't support transactions).  There is no special client support required for WATCH.
Testing: manual.  There doesn't appear to be CI tests for individual, supported, commands.
Docs Changes: Added "WATCH" to the supported command table.
=> redis: Add support for the WATCH command

mobile/library/cc/engine_builder.cc, mobile/library/common/api/external.cc, mobile/library/common/api/external.h, mobile/library/common/extensions/key_value/platform/config.cc, mobile/test/common/integration/client_integration_test.cc
previously the singleton nature of the PlatformInterfaceImpl meant a first envoy engine would setAPI to set the location of the platform bridge k-v store, we'd retreiveApi locate it and use it.  A subsequent engine would allocate setApi to a new location (for YT hopefully the same k-v store) but we'd never retreiveApi and use it.  We now don't allocate it - the original API will be used for the lifetime of the engines existing to better handle MultiEnvoyMobile deployments.
This updates the test to use the same k-v store across tests, as deployments also need to have a shared store across engines.
This fixes a failure mode in the H3 test where a second test pointed at the store for the first test.
Testing: yes
=> mobile: changing the lifetime of k-v store

test/mocks/api/mocks.cc
Commit Message: Fix undefined behavior in MockOsSysCalls::setsockopt
Additional Description: optval may point to an arbitrary type, and casting it to int* is a violation of strict aliasing. The correct way to use it as an int is to memcpy the contents to an int.
=> Fix undefined behavior in MockOsSysCalls::setsockopt

source/extensions/filters/http/ext_proc/ext_proc.cc
Commit Message: ext_proc: fix end_stream typo
Testing: N/A
=> ext_proc: fix end_stream typo

third_party/android/ifaddrs-android.h
This was discovered through figuring out another bug within Google's build environment when upgrading the NDK version to 26.
Thankfully, there are no users of this code right now.
Risk Level: Low (no users right now)
Testing: Within Google's build infra where an upgrade to NDK26 was available
Platform Specific Features: Android only
=> android: Fix Netlink message length in Android's getifaddrs

changelogs/current.yaml, source/common/upstream/upstream_impl.cc, test/common/upstream/upstream_impl_test.cc
Commit Message: upstream: fix a bug of legacy lb config convertions
in the #29235, we deprecated legacy load balancer creation code path and covert the legacy load balancer config to the latest typed extensions.
However, that change introduced a bug. When a empty `lb_subset_config` (without `subset_selectors`) is provided, the conversion logic will always try to create a subset lb extension. This is not match with our previous logic and may result in unexpected load balancing results.
Testing: unit.
=> upstream: fix a bug of legacy lb config convertions

.github/workflows/envoy-publish.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> github/ci: Add back missing publishing secrets

source/extensions/filters/http/alternate_protocols_cache/filter.cc, test/extensions/filters/http/alternate_protocols_cache/filter_test.cc
Previously, to get the Origin, we would use the host->address() to get
the port.  However, it's possible that host->address() is not set,
resulting in a SIGSEGV.
In this commit, we check if host->address() is set, and if not, we use
the default port of 443.
Fixes #31250
=> filters: Handle possible missing port info in AlternateProtocolsCache

contrib/golang/filters/http/test/test_data/buffer/go.mod, contrib/golang/router/cluster_specifier/source/go/pkg/cluster_specifier/capi_impl.go, contrib/golang/router/cluster_specifier/test/test_data/simple/go.mod
it makes the dependabot-updater processing error, also fix CFLAGS.
Testing:
Docs Changes:
Release Notes:
=> golang: fix replace path in go.mod

examples/grpc-bridge/server/kv/go.mod
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> examples/grpc: fix go.mod

changelogs/current.yaml, source/server/server.cc
This warning is unhelpful, given that its preferable to have no admin configured, than configured badly.
It also doesnt seem correct to assume that a user _should_ have admin configured, or that they should be warned if not.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> config/logging: Switch no admin warning -> info

test/integration/protocol_integration_test.cc
Commit Message: fix a race between receiving STOP_SENDING frame and test tear down in CONNECT request with 4xx or 5xx early response which could cause UAF of IntegrationStreamDecoder. In `DownstreamProtocolIntegrationTest.ConnectIsBlocked` IntegrationStreamDecoder is created in the test body and destroyed before test Teardown().
```
[ RUN      ] DownstreamProtocols/DownstreamProtocolIntegrationTest.ConnectIsBlocked/IPv4_Http3Downstream_HttpUpstreamBalsaParserNghttp2NoDeferredProcessingLegacy
=================================================================
==18==ERROR: AddressSanitizer: heap-use-after-free on address 0x60f0000ce448 at pc 0x00000a958af0 bp 0x7ffec37fede0 sp 0x7ffec37fedd8
READ of size 8 at 0x60f0000ce448 thread T0
#0 0xa958aef in …
```
=> quic: deflake CONNECT request test with early response 

test/extensions/tracers/common/ot/opentracing_driver_impl_test.cc, test/extensions/tracers/datadog/config_test.cc, test/extensions/tracers/dynamic_ot/dynamic_opentracing_driver_impl_test.cc, test/extensions/tracers/opencensus/tracer_test.cc, test/extensions/tracers/opentelemetry/opentelemetry_tracer_impl_test.cc, test/extensions/tracers/skywalking/skywalking_tracer_impl_test.cc, test/extensions/tracers/skywalking/tracer_test.cc, test/extensions/tracers/xray/tracer_test.cc, test/extensions/tracers/xray/xray_tracer_impl_test.cc, test/extensions/tracers/zipkin/zipkin_tracer_impl_test.cc, test/test_common/utility.h
Commit Message: test: use TestTraceContextImpl to replace header map in tracer tests
Using `TestTraceContextImpl` to relace all header map tracer tests because the `TraceContext` is the actual abstraction that tracers use.
Risk Level: n/a. Test only changes.
Testing: n/a.
=> test: use TestTraceContextImpl to replace header map in tracer tests

mobile/test/common/integration/client_integration_test.cc, test/integration/autonomous_upstream.cc, test/integration/autonomous_upstream.h
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> mobile: adding some more lifetime tests

bazel/foreign_cc/BUILD, bazel/repositories.bzl, bazel/repository_locations.bzl, contrib/kafka/filters/network/source/mesh/upstream_kafka_client.h, contrib/kafka/filters/network/source/mesh/upstream_kafka_consumer_impl.cc, tools/dependency/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> deps: Rename edenhill -> confluentinc

api/bazel/cc_proto_descriptor_library/builddefs.bzl
=> build: Remove decommissioned (in v5.x) bazel attribute

contrib/qat/private_key_providers/test/config_test.cc, contrib/qat/private_key_providers/test/ops_test.cc, envoy/singleton/manager.h, source/common/singleton/manager_impl.cc, source/common/singleton/manager_impl.h, test/common/singleton/manager_impl_test.cc, test/extensions/http/cache/file_system_http_cache/file_system_http_cache_test.cc, test/extensions/transport_sockets/alts/alts_integration_test.cc
Commit Message: singleton manager: enhance singleton manager to support pin
A new enhancement to the singleton manager:
`pin` support: By default, the singleton manager only stores a weak pointer to the instance and  the instance will be destroyed if no one keep its shared pointer. But now, if the `pin` is enabled, the manager will keep a shared pointer of the instance.
This is caused by the #29289. The #29289 introduced a new server factory context method because an object require server wide lifetime. But I think bringing these objects/methods that only make sense for specific modules/features to server factory context is not a good design. And a pinned singleton should be enough for this scenario. (And I think it could do more)
Risk Level: low, no change for …
=> singleton manager: enhance singleton manager to support pin

envoy/http/filter_factory.h, envoy/server/BUILD, envoy/server/factory_context.h, source/common/filter/config_discovery_impl.h, source/common/http/filter_chain_helper.cc, source/common/http/filter_chain_helper.h, source/extensions/filters/http/composite/action.cc, source/extensions/filters/network/http_connection_manager/config.cc, source/extensions/filters/network/http_connection_manager/config.h, source/server/BUILD, source/server/server.h, test/common/filter/config_discovery_impl_test.cc, test/common/http/filter_chain_helper_test.cc, test/mocks/server/server_factory_context.cc, test/mocks/server/server_factory_context.h
Commit Message: clean server factory context and partly revert #29289
#29289 added ECDS support to the composite filter which is great. But it also introduced a new method to the server factory context which is not recommended.
SingletonManager is better choice to achieve this target. If more stable lifetime is necessary, then a pinned singleton instance should be enough.
Testing: n/a.
=> clean server factory context and partly revert #29289

.github/workflows/envoy-dependency.yml
This fixes an issue where the updater was incorrectly trying to use the short sha
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel/updater: Fix for version

api/envoy/extensions/access_loggers/filters/cel/v3/cel.proto, api/envoy/extensions/formatter/cel/v3/cel.proto
Commit Message: improvement CEL doc
Additional Description: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/formatter/cel/v3/cel.proto#extensions-formatter-cel-v3-cel
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> improvement CEL doc

mobile/test/common/integration/BUILD, mobile/test/common/integration/client_integration_test.cc
Tested with:
```
bazelisk test --runs_per_test=100 --config=remote --test_output=streamed --cache_test_results=no --test_arg="-l trace" //test/common/integration:client_integration_test 
```
=> mobile: Add an engine termination test with open streams

api/envoy/config/accesslog/v3/accesslog.proto, source/common/stream_info/utility.h, test/common/access_log/access_log_impl_test.cc
Two response flag are missing their string representation for access logging, adding them.
=> stream_info: add missing response flag strings

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
It should be http filter (`envoy::extensions::filters::network::http_connection_manager::v3::HttpFilter`), rather than listener filter
=> ext_proc: Correct the filter type in the tests

source/extensions/clusters/logical_dns/logical_dns_cluster.cc
This makes the debug logging for logical dns consistent with that in strict and prevents (some) continual repeated logging in debug mode
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> dns: Switch resolution debug -> trace

test/common/quic/envoy_quic_client_stream_test.cc, test/common/quic/envoy_quic_utils_test.cc, test/common/router/config_impl_test.cc
This commit fixes compiler warnings of the type [-Werror=range-loop-construct]
Here is one example:
```
test/common/router/config_impl_test.cc:2207:27: error: loop variable 'header' of type 'const string&' {aka 'const std::__cxx11::basic_string<char>&'} binds to a temporary constructed from type 'const char* const'
```
=> Fix compiler warnings in unit tests.

contrib/generic_proxy/filters/network/source/codecs/dubbo/config.cc, contrib/generic_proxy/filters/network/source/codecs/dubbo/config.h, contrib/generic_proxy/filters/network/source/interface/stream.h, contrib/generic_proxy/filters/network/test/codecs/dubbo/config_test.cc, contrib/generic_proxy/filters/network/test/fake_codec.h, contrib/generic_proxy/filters/network/test/integration_test.cc, contrib/generic_proxy/filters/network/test/proxy_test.cc
Commit Message: generic proxy: application specific status support
Now, the absl::Status is used to indicate the response status but this is not a good choice in practices. The codec need to convert the application specific status to the absl::Status and this also make the logging or tracing cannot record the actual application specific status.
This patch split the status to absl::Status and StreamStatus. The former one will be used by generic proxy to indicate statuses or error types of stream. And another one will be used by the codec to tell the application specific status of stream.
Testing: n/a.
=> generic proxy: application specific status support

docs/root/configuration/observability/access_log/usage.rst
Testing: N/A
Docs Changes: docs/root/configuration/observability/access_log/usage.rst
Release Notes:
=> docs(access_log): only one param is allowed in command operators

mobile/library/common/BUILD, mobile/library/common/engine.cc
Envoy Mobile always requires dfp_mixed_scheme for the TLS and cleartext DFP clusters. While dfp_mixed_scheme defaults to true, some environments (like within Google), force it to false for the Envoy use case, so we force it back to true here in Envoy Mobile, so we don't break the mobile integration tests.
Once general use of dfp_mixed_scheme is fixed everywhere, we can revert this commit.
Tested by changing dfp_mixed_scheme to FALSE_RUNTIME_GUARD and running the mobile xDS integration tests:
```
cd mobile
bazelisk test --test_output=streamed --cache_test_results=no //test/common/integration:rtds_integration_test
```
=> mobile: Force the dfp_mixed_scheme flag to true in Envoy Mobile

changelogs/current.yaml, source/extensions/tracers/datadog/span.cc, test/extensions/tracers/datadog/BUILD, test/extensions/tracers/datadog/naming_test.cc, test/extensions/tracers/datadog/span_test.cc
This is an additional fix for the bug described in https://github.com/envoyproxy/envoy/pull/29932.
There are still situations in which the spans produced by the Datadog tracer have the wrong name (operation name). We want all Datadog spans to be named "envoy.proxy", but sometimes they have another value which should instead be the span's resource name.
https://github.com/envoyproxy/envoy/pull/29932 addressed spans created by `class Tracer`, https://github.com/envoyproxy/envoy/pull/30503 (which was about something else) addressed name changes due to `Span::setOperation`, and this pull request that you are reading addresses spans created by `Span::spawnChild`.
For a little background, there was a substantial [rewrite][1] of the Datadog tracing extension within Envoy in October 2022. Since …
=> Datadog: fix names in Span::spawnChild

test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc, test/integration/quic_http_integration_test.cc, test/integration/ssl_utility.cc, test/integration/ssl_utility.h
This PR refactor the code in the test utility to :
(1) Allow testing multiple connection cases (i.e., call `makeSslClientConnection` multiple times).
(2) Clarify the memory management. 
It is because:
Old code is using new operator and using proto's `set_allocated ()` to free the memory immediately. No memory leak but the memory management is not clear and custom_validator_config can not be reused by other connections
=> tls: Refactor the way custom_validator is configured

contrib/generic_proxy/filters/network/source/config.cc, contrib/generic_proxy/filters/network/source/config.h, contrib/generic_proxy/filters/network/source/interface/config.h, contrib/generic_proxy/filters/network/test/config_test.cc, contrib/generic_proxy/filters/network/test/mocks/filter.h
Commit Message: generic proxy: codec validation from L7 filter
Generic proxy provides abstract response/request to L7 filters. By this way, lots of L7 filters (rate limit, fault, etc) could be shared by different application protocols.
But it's also possible to create some application protocol specific filter. For example, one filter may cast the abstract message to specific message and do some application specific logic (like protocol conversion).
This new patch allow the filter to validate the codec and return a status at configuration loading time. 
Testing: unit.
=> generic proxy: codec validation from L7 filter

.github/workflows/codeql-daily.yml, .github/workflows/codeql-push.yml, .github/workflows/envoy-sync.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/permissions: Restrict permissions for remaining workflows

.gitattributes
This marks package lock files as binary - which means they are ignored in line counts and not merged by git (ie just overwritten)
The latter point is most likely a good thing as this breaks quite a bit currently - but i will monitor for the effect
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> deps/lockfiles: Mark as binary

contrib/generic_proxy/filters/network/source/config.cc, contrib/generic_proxy/filters/network/source/proxy.h
Commit Message: fix stats prefix for generic proxy filters
Additional Description: without this commit, generic proxy filters stats will lose the prefix generic_proxy.{}.
Testing:
Docs Changes:
Release Notes:
=> fix generic proxy stat prefix

changelogs/current.yaml, source/common/http/conn_pool_grid.cc, source/common/runtime/runtime_features.cc, test/extensions/filters/http/alternate_protocols_cache/BUILD, test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc, test/integration/fake_upstream.cc, test/integration/fake_upstream.h
Fixing an issue where "prefetched" H3 streams were not cleaned up promptly.
Testing: new e2e tests
[Optional Runtime guard:] yes
=> grid: cleaning up potential zombie streams

changelogs/current.yaml, source/common/config/well_known_names.cc, source/common/config/well_known_names.h, source/extensions/filters/common/rbac/utility.cc, test/common/stats/tag_extractor_impl_test.cc, test/extensions/filters/http/rbac/rbac_filter_test.cc, test/extensions/filters/network/rbac/integration_test.cc
This change adds a tag extraction rule for the RBAC network filter. It also adds a dot between `<stat_prefix>` and `rbac.` in the statistics namespace according to [docs of the RBAC network filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/rbac_filter#statistics) and [the RBAC http filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rbac_filter#statistics).
Commit Message: stats: add tag extraction rule for RBAC network filter
Testing: added unit tests to confirm extraction works properly
[Optional Fixes #Issue] #21595 …
=> stats: add tag extraction rule for RBAC network filter

api/envoy/extensions/filters/http/oauth2/v3/oauth.proto, changelogs/current.yaml, source/common/protobuf/utility.h, source/extensions/filters/http/oauth2/config.cc, source/extensions/filters/http/oauth2/filter.cc, source/extensions/filters/http/oauth2/filter.h, source/extensions/filters/http/oauth2/oauth_client.cc, source/extensions/filters/http/oauth2/oauth_client.h, test/extensions/filters/http/oauth2/oauth_test.cc
Currently this filter does not work with Github - which would seem like one of the most likely use cases
This is a revival of https://github.com/envoyproxy/envoy/pull/14625
Should fix #14542
Unblocks #31534 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> oauth2: Add default expiry for RFC compliance

mobile/library/common/http/client.cc
This is just a cleanup of the getStream() branch checks to simplify reading the code.
No functional change was introduced in this commit.
=> mobile: Remove redundant check in Client::getStream()

changelogs/current.yaml, source/extensions/tracers/datadog/span.cc, test/extensions/tracers/datadog/BUILD, test/extensions/tracers/datadog/naming_test.cc, test/extensions/tracers/datadog/span_test.cc
This is a backport of https://github.com/envoyproxy/envoy/pull/31366/ onto the v1.28 release branch.
These changes fix a bug in the Datadog tracing extension. Previously, `Span::spawnChild` would produce spans whose "operation name" had the value of what should instead be the "resource name." With these changes, setting the "operation name" sets the "resource name" instead, and the "operation name" is always the hard-coded value "envoy.proxy".
=> [bp/1.28] datadog: fix names in Span::spawnChild

changelogs/current.yaml, source/extensions/tracers/datadog/span.cc, test/extensions/tracers/datadog/BUILD, test/extensions/tracers/datadog/naming_test.cc, test/extensions/tracers/datadog/span_test.cc
This is a backport of https://github.com/envoyproxy/envoy/pull/31366/ onto the v1.27 release branch.
These changes fix a bug in the Datadog tracing extension. Previously, `Span::spawnChild` would produce spans whose "operation name" had the value of what should instead be the "resource name." With these changes, setting the "operation name" sets the "resource name" instead, and the "operation name" is always the hard-coded value "envoy.proxy".
=> [bp/1.27] datadog: fix names in Span::spawnChild

source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, test/extensions/filters/http/ext_proc/filter_test.cc
Config objects, including per route configs, are main thread objects and should be immutable. In practice, the ext_proc `FilterConfigPerRoute` is not mutated on the request path, but due to the config merging strategy employed in `Http::Utility::getMergedPerFilterConfig` ([link](https://github.com/envoyproxy/envoy/blob/b18ea4488a540aaab4979aea7ebeb252b77d4fe7/source/common/http/utility.h#L604)), fields on the object must be mutable in order to set them on an already-constructed object. This is because the reduce function accepted by that function as an argument takes as its first parameter a reference to the target final object.
In this PR we refactor the logic, bringing the `traversePerFilterConfig` call directly into `mergePerFilterConfig`. We add a "merge constructor" …
=> ext_proc: refactor per route config for immutability

envoy/network/resolver.h, source/common/listener_manager/listener_impl.cc, source/common/listener_manager/listener_manager_impl.cc, source/common/network/resolver_impl.cc, source/common/network/resolver_impl.h, source/common/upstream/health_discovery_service.cc, source/common/upstream/upstream_impl.cc, source/extensions/network/dns_resolver/cares/dns_impl.cc, source/extensions/stat_sinks/dog_statsd/config.cc, source/extensions/stat_sinks/graphite_statsd/config.cc, source/extensions/stat_sinks/statsd/config.cc, source/server/api_listener_impl.cc, source/server/api_listener_impl.h, source/server/configuration_impl.cc, test/common/network/resolver_impl_test.cc, test/fuzz/utility.h, test/mocks/network/mocks.h, test/server/api_listener_test.cc, tools/code_format/config.yaml
This reverts commit 7a1a883aed9dce124f449a82331228c055812356.
Most mobile ci has started permafailing since this landed
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Revert "Resolver: switching to statusor (#31312)"

source/common/quic/envoy_quic_client_stream.cc, source/common/quic/envoy_quic_server_stream.cc, source/common/quic/http_datagram_handler.cc, source/common/quic/http_datagram_handler.h, test/common/quic/envoy_quic_client_stream_test.cc, test/common/quic/http_datagram_handler_test.cc
stream_decoder_ member variable must outlive the HttpDatagramHandler. Previously, stream_decoder_ became a dangling pointer when the stream is reset before OnHttp3Datagram is called.
I made Envoy QUIC stream unregister the HTTP/3 Datagram visitor when the stream is reset to ensure the lifetime assumption.
Risk Level: Low, this is a bug fix.
Testing: Unit tests and integration tests.
=> http: fix HttpDatagramHandler object lifetime issue.

api/envoy/config/route/v3/route.proto
Clarify the behavior of `most_specific_header_mutations_wins `
See the discussion [here](https://github.com/envoyproxy/envoy/pull/30220/files#r1437341650)
=> route: Clarify the `most_specific_header_mutations_wins`

ci/README.md
This PR solves two very simple typos `ci/README.md`
Commit Message: Fix typos in ci/README.md
Additional Description: It fixes a typo and place a missing a single quote in a command in ci/README.md
Testing:
Release Notes:
=> Fix typos in ci/README.md

docs/root/intro/arch_overview/operations/hot_restart.rst
Commit Message: docs(hot_restart): include the example as a link
Additional Description: The hot-restart documentation was mentioning that the repository contains an example but it was not being linked for quick access.
Testing: N/A
Docs Changes: docs/root/intro/arch_overview/operations/hot_restart.rst
Release Notes:
=> Docs: include the hot-restart example as a link

mobile/library/common/http/client.cc, mobile/library/common/http/client.h, mobile/test/common/integration/BUILD, mobile/test/common/integration/client_integration_test.cc, mobile/test/java/integration/AndroidEnvoyExplicitFlowTest.java, test/integration/fake_upstream.cc, test/integration/fake_upstream.h
When deferring the error for the explicit flow control case, we didn't close the stream, which could result in attempting to send data to the weak pointer (now an ENVOY_BUG)
When deferring an error, we also never actually sent it.  Now forwarding it on unless the response is complete.
Risk Level: n/a (mobile only)
=> mobile: fixing explicit flow control bugs.

mobile/envoy_build_config/BUILD, mobile/envoy_build_config/extension_registry.cc
we should eventually either add a compile time options build for this or remove support entirely but simply fixing for now.
tested locally
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> mobile: fix build for unused buildopt

mobile/library/java/org/chromium/net/impl/CronvoyUrlRequest.java, mobile/library/java/org/chromium/net/impl/CronvoyUrlRequestContext.java
This PR removes the unused `isQuicEnabled` parameter that is no longer used since the protocol-based routing was removed in https://github.com/envoyproxy/envoy/pull/25893
Risk Level: low (unused code)
Testing: n/a
=> mobile: Remove isQuicEnabled parameter

source/extensions/filters/http/rate_limit_quota/filter.cc, source/extensions/filters/http/rate_limit_quota/quota_bucket_cache.h, test/extensions/filters/http/rate_limit_quota/integration_test.cc
Enable timer in the callback function. Also, add the integration test to confirm that the timer is triggered 10 times after filter is destroyed. (i.e., still report the quota usage periodically)
=> rlqs: Enable timer in the callback function

source/common/http/conn_manager_impl.h, test/common/http/conn_manager_impl_test.cc
the HCM active stream shouldn't be used when in the deferredDelete queue.
Fixing the weak pointer wrapper lifetime by invalidating the pointer when the class is added to the list, rather than when it's deleted.
Risk Level: low: normal envoy use not affected only Envoy mobile and other newStreamHandle users
=> api_listener: fixing a lifetime issue with the weak pointer wrapper in the HCM

changelogs/current.yaml, source/extensions/tracers/datadog/BUILD, source/extensions/tracers/datadog/span.cc, test/extensions/tracers/datadog/span_test.cc
This is a backport of https://github.com/envoyproxy/envoy/pull/31669 onto the v1.27 release branch.
These changes fix a bug in the Datadog tracing extension. In releases before v1.27, when the "error" tag was set on a Datadog span, a corresponding private property on the span would also be set to indicate the presence of an error. Release v1.27 included a rewrite of the Datadog tracing extension that removed this behavior, and the removal is a bug. These changes restore the old behavior.
=> [bp/1.27] datadog: fix span error property

changelogs/current.yaml, source/extensions/tracers/datadog/BUILD, source/extensions/tracers/datadog/span.cc, test/extensions/tracers/datadog/span_test.cc
This is a backport of https://github.com/envoyproxy/envoy/pull/31669 onto the v1.28 release branch.
These changes fix a bug in the Datadog tracing extension. In releases before v1.27, when the "error" tag was set on a Datadog span, a corresponding private property on the span would also be set to indicate the presence of an error. Release v1.27 included a rewrite of the Datadog tracing extension that removed this behavior, and the removal is a bug. These changes restore the old behavior.
=> [bp/1.28] datadog: fix span error property

.github/workflows/codeql-push.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/codeql: Fix build target acquisition

test/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/BUILD, test/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/proxy_filter_integration_test.cc
Additional Description: Resolves #31089. Adding retry on expecting a UDP datagram, due to async DNS resolution.
=> udp_dfp_tests: deflake UDP DFP integration tests

mobile/library/common/http/client.cc, mobile/library/common/http/client.h
This PR changes the `bytes_to_send_` to `size_t` instead of `int32_t`, so that there is no longer a narrowing conversion issue.
Testing: n/a
=> mobile: Fix narrowing conversion issue

.github/workflows/_cache.yml, .github/workflows/_finish.yml, .github/workflows/_load.yml, .github/workflows/_load_env.yml, .github/workflows/_request.yml, .github/workflows/_run.yml, .github/workflows/_stage_publish.yml, .github/workflows/_stage_verify.yml, .github/workflows/_start.yml, .github/workflows/codeql-push.yml, .github/workflows/command.yml, .github/workflows/envoy-dependency.yml, .github/workflows/envoy-release.yml, .github/workflows/envoy-sync.yml, .github/workflows/mobile-android_build.yml, .github/workflows/mobile-ios_build.yml
This reverts commit 32d8e3bd9986864809b301b4c326bcaf7ccecef6.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Revert "deps: Bump toolshed actions -> 0.2.23 (#31725)"

source/extensions/common/wasm/context.cc, test/extensions/filters/http/wasm/test_data/metadata_rust.rs, test/extensions/filters/http/wasm/test_data/test_cpp.cc
Commit Message: wires `xds` attribute into wasm, follow-up to https://github.com/envoyproxy/envoy/pull/31319
Additional Description: none
Testing: done
=> wasm: fix xds attribute support

changelogs/current.yaml, source/common/quic/envoy_quic_client_connection.cc, source/common/quic/envoy_quic_client_connection.h, test/common/quic/envoy_quic_client_session_test.cc, test/common/quic/test_utils.h
Commit Message: the probing socket is released when port migration fails. If this happens in response to an incoming packet during an I/O event, the follow socket read could cause use-after-free.
```
[2024-01-08 16:30:53.386][12][critical][backtrace] [./source/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0x0
[2024-01-08 16:30:53.387][12][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2024-01-08 16:30:53.387][12][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: 0/1.29.0-dev/test/DEBUG/BoringSSL
[2024-01-08 16:30:53.413][12][critical][backtrace] [./source/server/backtrace.h:96] #0: Envoy::SignalAction::sigHandler() [0x55bb876d499e]
[2024-01-08 …
```
=> quic: fix socket UAF during port migration

ci/do_ci.sh
Commit Message: protos: for Go, allow *opt-out* of PGV
PGV is extremely expensive in terms of binary size. This directly feeds into memory usage, storage and transmission costs, etc. For our binary, disable PGV (which we don't use) trims our binaries by a whopping 15MB!
This PR has no negative impact on any users unless they explicitly opt out of PGV (with `-tags=disable_pgv`). All existing users are un-impacted. This change only impacts Go via the go-control-plane repo.
This change is do as a post-processing step rather than in PGV upstream as PGV has moved to v1.0 and totally rewritten the repo, so the old PGV is frozen AFAIK. Since moving to v1.0 is a major effort (possibly not planned), the simple approach here was taken.
This mirrors …
=> protos: for Go, allow *opt-out* of PGV

.github/workflows/mobile-compile_time_options.yml
That specific job has been covered in [mobile-android_build.yml](https://github.com/envoyproxy/envoy/blob/234dcc646cbfc1cd512742fc92ad704f514b5948/.github/workflows/mobile-android_build.yml#L45-L47).
This fixes #31726.
Risk Level: low (has already been covered by another job)
Testing: CI
=> mobile/ci: Remove kotlin-build from mobile-compile-time-options

source/server/drain_manager_impl.cc
Commit Message: The new asserts in #31452 don't allow child draining threads. Sadly there are no tests that catch this in OSS. This tweaks the asserts so this can work, and we have verified this with internal tests.
Testing: just CI
=> server: switch the assert to allow child threads.

CODEOWNERS
Our team inside Google owns the transcoder filter. As Teju left Google, add myself as owner.
=> Add @taoxuy as http transcoder owner

.github/workflows/envoy-macos.yml, .github/workflows/mobile-compile_time_options.yml, .github/workflows/mobile-ios_build.yml, .github/workflows/mobile-ios_tests.yml, .github/workflows/mobile-release_validation.yml
The error:
```
ERROR: /Users/runner/work/envoy/envoy/mobile/WORKSPACE:98:18: fetching android_sdk_repository rule //external:androidsdk: Android SDK api level 30 was requested but it is not installed in the Android SDK at /Users/runner/Library/Android/sdk. The api levels found were [34, 33, 32, 31]. Please choose an available api level or install api level 30 from the Android SDK Manager.
```
This PR is a workaround to install Android SDK 30 even though it's not used for building iOS apps, that's because `mobile/WORKSPACE` expects the Android SDK 30 to be available and GitHub Runner image no longer includes Android SDK 30. See https://github.com/actions/runner-images/issues/8952. Passing `--android` in the `./ci/mac_ci_setup.sh` will install the Android SDK 30.
Testing: CI …
=> mobile/ci: Fix iOS build failures

.github/workflows/envoy-macos.yml
=> Fix accidental --android on non-mobile ci/mac_ci_setup.sh

mobile/ci/test_size_regression.sh
Recent changes, including the removal of the Brotli compressor in Envoy Mobile, have brought the Envoy Mobile test binary size down to ~4.27MB, so we are updating the maximum allowed size in the regression check CI job.
=> mobile/ci: Update the binary size expectations

source/extensions/filters/http/header_mutation/header_mutation.cc
Assert here is redundant. [getAllPerFilterConfig](https://github.com/envoyproxy/envoy/blob/d5de0df4e2cbc452df9e89864ccc6410ea109197/source/common/http/utility.h#L645-L648)  will guarantee here would not be nullptr (i.e., would not crash).  
So clean up the leftover from last PR
=> header_mutation: Remove redundant assert

tools/h3_request/h3_request.py
Commit Message: Add streaming POST support to h3_request tool
Additional Description: The last piece of hot restart quic packet wrangling involves making sure incoming packets on draining requests go to the right instance - in order to end-to-end test that, we need to be able to have a connection open that's still going to be sending packets to a draining connection, which means we need to be able to stream request data.
Risk Level: None, test-tool-only.
Testing: Yes it is for testing.
Platform Specific Features: Not sure if this will break the tool for windows because of os.nonblocking. Hot restart doesn't work for windows anyway so it shouldn't matter.
=> Add streaming POST support to h3_request tool

mobile/.bazelrc, mobile/docs/root/intro/version_history.rst
It is no longer in use anywhere.
=> mobile: Remove the envoy_mobile_stats_reporting build option

bazel/cel-cpp.patch
=> cel: fix gcc contrib build

changelogs/1.28.0.yaml, source/common/http/filter_manager.cc, source/common/http/filter_manager.h, source/common/runtime/runtime_features.cc, test/integration/filter_integration_test.cc, test/integration/filters/reset_stream_filter.cc
Commit Message: http: abort filter chain after reset stream was called
To close https://github.com/envoyproxy/envoy/issues/26994. The #26994 is caused by that the filter chain still continue and try to send reply after the whole stream is closed. We should abort the filter chain to avoid any possible further logic after the stream is reset.
Also see https://github.com/envoyproxy/envoy/pull/30835 for more context.
Testing: integration.
=> http: abort filter chain after reset stream was called

.azure-pipelines/ci.yml, .azure-pipelines/stage/linux.yml, .github/config.yml, .github/workflows/_run.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> release/ci: Fix artefact publishing

tools/h3_request/h3_request.py
Commit Message: fix h3_request to work with delays
Additional Description: It turns out the aiohttp functions named with the prefix `send_` only *sometimes* send, and would be more accurately prefixed `queue_`, or more accurately still `queue_or_send_`. This fixes the tool to always send.
Risk Level: None, test-tool only.
Testing: Tested manually with the call that wasn't working right before, and it does now.
=> Fix h3_request to work with delays

api/contrib/envoy/extensions/private_key_providers/cryptomb/v3alpha/cryptomb.proto, contrib/cryptomb/private_key_providers/source/cryptomb_private_key_provider.cc, contrib/cryptomb/private_key_providers/source/cryptomb_private_key_provider.h, contrib/cryptomb/private_key_providers/source/cryptomb_stats.h, contrib/cryptomb/private_key_providers/source/ipp_crypto.h, contrib/cryptomb/private_key_providers/source/ipp_crypto_impl.h, contrib/cryptomb/private_key_providers/test/fake_factory.cc, contrib/cryptomb/private_key_providers/test/fake_factory.h, contrib/cryptomb/private_key_providers/test/ops_test.cc
Commit Message: cryptomb: support ECDSA
Additional Description: The CryptoMB private key provider only supports RSA at the time, the patch adds ECDSA support to it.
Risk Level: Low (as contrib extension)
Testing: Unit and integration tests
Platform Specific Features: Requires AVX512 or equivalent CPU instruction set
=> cryptomb: support ECDSA

api/bazel/BUILD, api/bazel/api_build_system.bzl, bazel/dependency_imports.bzl, ci/do_ci.sh
Commit Message: go proto: include vtprotobuf generation
See https://github.com/envoyproxy/go-control-plane/issues/824 for more information
This PR adds the vtprotobuf protoc plugin for Go. This works _on top_ of the existing protoc-gen-go, to add optimized marshal functions that callers can _opt in_ to using. This is not like `gogo`, which was a very invasive change -- everything is layered and opt-in. See issue for benchmarks, etc.
Additionally, to avoid possible binary size increase, the entire new code is protected under a go build tag. Users will need to opt-in at build time (`-tags=vtprotobuf`). **By default, there is no impact for users at all**.
Risk Level: Low - only additional opt-in code
Testing: Manually tested in Istio codebase
Docs Changes: NONE …
=> go proto: include (opt-in) vtprotobuf generation

source/common/network/socket_impl.cc, test/common/network/address_impl_test.cc, tools/code_format/config.yaml
Replacing a (not exerted) data plane crash with error handling.
=> socket: using error return

.devcontainer/Dockerfile, .devcontainer/setup.sh
=> devcontainer: Use libc++ when building Envoy

docs/root/configuration/other_protocols/thrift_filters/router_filter.rst, source/extensions/filters/network/thrift_proxy/router/router.h, source/extensions/filters/network/thrift_proxy/router/upstream_request.cc, test/extensions/filters/network/thrift_proxy/router_test.cc
Currently `upstream_resp_exception_local` in thrift_proxy is not fine grain enough for debugging online services
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> break down local exception for thrift_proxy

source/common/http/conn_pool_grid.cc, source/common/http/conn_pool_grid.h
class `Envoy::Http::ConnectivityGrid` needs 20 bytes of padding,
non-tail padding is 20 (fields: 20 padded fields: 3) total_size: 304
```
Padding	Size	Alignment	| Field name
8	8		| dispatcher_
8	8		| random_generator_
16	8		| host_
7	1	1		| priority_
16	8		| options_
16	8		| transport_socket_options_
8	8		| state_
8	8		| next_attempt_duration_
8	8		| time_source_
16	8		| alternate_protocols_
7	1	1		| draining_
24	8		| idle_callbacks_
24	8		| pools_
1	1		| destroying_
6	1	1		| deferred_deleting_
24	8		| wrapped_callbacks_
8	8		| quic_stat_names_
8	8		| scope_
56	8		| origin_
8	8		| quic_info_
```
The new class layout structure will save 16 bytes by minimizing padding.
Testing: CI
=> conn_pool_grid: Restructure the class layout to minimize padding

ci/do_ci.sh
Without this fix, vtprotobuf is accidentally enabled for everyone instead of just opt-in.
Fixing https://github.com/envoyproxy/envoy/pull/31172
Commit Message: `ci: fix typo in vtprotobuf disable logic`
Without this fix, vtprotobuf is accidentally enabled for everyone
instead of just opt-in.
Fixing https://github.com/envoyproxy/envoy/pull/31172
Testing: Manually ran
Docs Changes:
Release Notes:
=> ci: fix typo in vtprotobuf disable logic

source/common/upstream/cluster_manager_impl.cc, source/common/upstream/cluster_manager_impl.h
We also remove an ASSERT that appears unneeded and was getting tripped in certain settings.
Calling `.reset()` on an already null unique_ptr is a no-op, so the ASSERT isn't needed.
=> xds: Fix the resume_cds_ logic in ClusterManagerImpl

source/extensions/filters/http/ext_authz/ext_authz.cc
There is a MSAN issue in ext_authz due to recently commit: #31437.
The error indicates use-of-uniniialized value of max_request_bytes_.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Fix a MSAN issue in ext_authz due to max_request_bytes_ change

api/envoy/extensions/resource_monitors/downstream_connections/v3/BUILD, api/envoy/extensions/resource_monitors/downstream_connections/v3/downstream_connections.proto, source/extensions/extensions_metadata.yaml
Since [downstream connections monitor](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/resource_monitors/downstream_connections/v3/downstream_connections.proto#extensions-resource-monitors-downstream-connections-v3-downstreamconnectionsconfig) has been [enabled](https://github.com/envoyproxy/envoy/pull/28202) in the hot request path in tcp listener in the beginning of October 2023, it has been deployed into high scale prod env at Spotify and has been running with no observed issues for 2.5 month. This patch suggests to promote this extension to stable.
Risk Level:
Testing:
Docs Changes:
Release Notes: TBD
=> Promote downstream connections monitor extension to stable

changelogs/1.29.0.yaml
#31762 solves a potential bug of postgres proxy that was not mentioned in the changelogs of _v1.29.0_ though the PR appeared in this release. This PR updates `changelogs/1.29.0.yaml ` file to cover the change.
Testing:
Docs Changes: 
=> Update changelogs/1.29.0.yaml for PR#31762

source/common/http/http2/codec_impl.cc, source/common/http/http2/codec_impl.h
This PR removes a few references to the `nghttp2_frame` type in codec API methods.
Commit Message: http2: more cleanup in preparation for removing nghttp2 callbacks
Risk Level: low; refactoring, no functional change intended
Docs Changes:
Release Notes:
=> http2: more cleanup in preparation for removing nghttp2 callbacks

contrib/all_contrib_extensions.bzl, contrib/exe/BUILD
Commit Message: Contrib builds excluding skipped targets
Additional Description: Previously the contrib static binary did not exclude targets that were tagged for skipping, which seems like it was a mistake.
This also adds a target skip for `boringssl=fips` configuration, because the qatzip extension currently breaks the FIPS build.
This is imperfect, in that an aarch64 build with boringssl=fips will still not work, but should repair the majority of currently surprise-broken cases.
Fixes #31874 
Risk Level: Small risk of surprising aarch64 and ppc builds by actually excluding extensions that were nominally excluded all along.
Testing: `bazel build --define boringssl=fips //contrib/exe:envoy-static` in the devcontainer works after and does not work before.
Release Notes: …
=> Contrib builds actually excluding skipped targets

api/envoy/service/status/v3/csds.proto
Add a `client_scope` field to `ClientConfig`
Extends an CSDS API with an additional field that includes extra information for implementations that can have multiple unrelated configs.
Risk Level:
Low
Testing:
Manual
Docs Changes:
None
Release Notes:
None
None
=> Add a `client_scope` field to `ClientConfig`

envoy/common/platform.h, source/common/network/connection_impl.cc, test/common/network/connection_impl_test.cc, test/integration/tcp_async_client_integration_test.cc
Only limit the RST send and detect feature to linux.
There is already a release note before.
Testing:
Docs Changes:
Release Notes:
Fixes #31564
=> tcp: add platform check to avoid RST setting spam

mobile/.bazelrc
Also, we rename `test-android` to `mobile-test-android` for consistency.
=> mobile/ci: Adds a `mobile-test-ios` Bazel build option

test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc
I think the connection idle timeout and stats timeout were too close, causing the flake. Shortening connect timeout and crossing fingers (since I couldn't repro locally)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> test: hopefully fixing a flake

contrib/generic_proxy/filters/network/source/access_log.cc, contrib/generic_proxy/filters/network/source/interface/stream.h, contrib/generic_proxy/filters/network/source/proxy.cc, contrib/generic_proxy/filters/network/test/fake_codec.h, contrib/generic_proxy/filters/network/test/proxy_test.cc
Commit Message: generic proxy: change the status code type to int
To support minus response code and output.
Testing: n/a.
=> generic proxy: change the status code type to int

contrib/generic_proxy/filters/network/source/interface/config.h, contrib/generic_proxy/filters/network/source/route.cc, contrib/generic_proxy/filters/network/source/route.h, contrib/generic_proxy/filters/network/test/BUILD, contrib/generic_proxy/filters/network/test/mocks/filter.cc, contrib/generic_proxy/filters/network/test/route_test.cc
Commit Message: generic proxy: get filter factory by type for route config
The type should be used first to find the filter factory. This patch fixed previous logic problem. And the
runtime guard `envoy.reloadable_features.no_extension_lookup_by_name` could be used to ensure the legacy name searching still could works.
Testing: unit.
=> generic proxy: get filter factory by type for route config

changelogs/current.yaml
#31762 solves a potential bug of postgres proxy that was not mentioned in the changelogs of _v1.29.0_ though the PR appeared in this release. This PR updates `changelogs/current.yaml ` file to cover the change.
Testing:
Docs Changes: 
=> Update changelogs/current.yaml for PR#31762

mobile/library/common/http/client.cc, mobile/library/common/http/client.h, source/common/http/conn_manager_impl.h, test/common/http/conn_manager_impl_test.cc
Last time we tried to check this in it didn't run Envoy Mobile CI
Turns out we had several issues accessing the weak pointer, some of which look like they could be legitimate Envoy Mobile bugs in certain circumstances.  
Risk Level: low (Envoy changes should only affect Envoy Mobile or other API listener users)
Testing: new unit tests, existing tests enhanced by ENVOY_BUG
=> api_listener: fixing a lifetime issue with the weak pointer wrapper
