envoyproxy/envoy

.github/workflows/envoy-dependency.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/dependency: Fix bot signoff

---

test/integration/BUILD

Testing: n/a
Docs Changes: n.a

flake: improve tsan flake

---

api/envoy/extensions/filters/http/json_to_metadata/v3/json_to_metadata.proto

Commit Message: remove a TODO that shows up in the docs. 
CC @JuniorHsu: not sure if you want to open a separate issue for this TODO you had here.
Testing: built and verified locally
Docs Changes: removing the TODO from the documentation section

docs: remove a TODO that shows up in the docs

---

contrib/generic_proxy/filters/network/source/codecs/dubbo/config.cc
contrib/generic_proxy/filters/network/source/codecs/dubbo/config.h
contrib/generic_proxy/filters/network/source/interface/codec.h
contrib/generic_proxy/filters/network/source/interface/codec_callbacks.h
contrib/generic_proxy/filters/network/source/proxy.cc
contrib/generic_proxy/filters/network/source/proxy.h
contrib/generic_proxy/filters/network/source/router/router.cc
contrib/generic_proxy/filters/network/source/router/router.h
contrib/generic_proxy/filters/network/source/upstream.cc
contrib/generic_proxy/filters/network/source/upstream.h
contrib/generic_proxy/filters/network/test/codecs/dubbo/config_test.cc
contrib/generic_proxy/filters/network/test/fake_codec.cc
contrib/generic_proxy/filters/network/test/fake_codec.h
contrib/generic_proxy/filters/network/test/integration_test.cc
contrib/generic_proxy/filters/network/test/mocks/codec.cc
contrib/generic_proxy/filters/network/test/mocks/codec.h
contrib/generic_proxy/filters/network/test/proxy_test.cc
contrib/generic_proxy/filters/network/test/router/router_test.cc

Commit Message: generic proxy refactoring part 3: merge decoder and encoder to same interface
Additional Description: n/a.
Testing: unit.

generic proxy refactoring part 3: merge decoder and encoder to same interface

---

.azure-pipelines/pipelines.yml
bazel/repositories.bzl
bazel/repository_locations.bzl

Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Add libpfm for google benchmark

---

changelogs/current.yaml

backport of #30408
Risk Level:
Testing:
Docs Changes:
Release Notes:

[backport 1.28] Add release-notes for fix merged in #30123 (#30408)

---

contrib/golang/filters/network/source/go/pkg/network/shim.go
contrib/golang/filters/network/source/golang.cc

https://github.com/envoyproxy/envoy/issues/30210
Risk Level:
Testing:
Docs Changes:
Release Notes:

golang network: fix issue 30210 (memory leaking caused by circular reference)

---

tools/deprecate_version/deprecate_version.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

tools: fix deprecate version bug

---

.github/dependabot.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

dependabot: Increase PR limit for tools/base requirements

---

.github/workflows/codeql-daily.yml
.github/workflows/codeql-push.yml

Currently codeql is erroring  https://github.com/envoyproxy/envoy/security/code-scanning/tools/CodeQL/status
Not sure if this is the issue but its telling us to do it
Risk Level:
Testing:
Docs Changes:
Release Notes:

codeql/ci: Fix configuration

---

tools/repo/notify.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

tools: more pr notifier printing

---

source/common/router/config_impl.cc

Commit Message: minor update: fix comment
Risk Level:
Testing:
Docs Changes:
Release Notes:

minor update: fix comment

---

.github/actions/do_ci/action.yml
.github/workflows/_ci.yml
.github/workflows/envoy-prechecks.yml

This tool desperately needs some work and is prone to failure
Risk Level:
Testing:
Docs Changes:
Release Notes:

deps/ci: Catch errors in github precheck ci

---

.github/actions/do_ci/action.yml
.github/workflows/envoy-prechecks.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

github/precheck: Fix/improve error handling

---

docs/root/start/sandboxes/dynamic-configuration-control-plane.rst

Commit Message: docs: clarify snapshot versions only need to change not increase
Additional Description: Previously the docs suggested the version had to "increase" in some sense, but this is not true - the version only needs to change.
Testing: N/A
Docs Changes: Yes, dynamic cp sandbox
Release Notes: docs: clarify snapshot versions only need to change not increase

docs: clarify snapshot versions only need to change not increase

---

contrib/golang/filters/network/source/go/pkg/network/shim.go
contrib/golang/filters/network/source/golang.cc

https://github.com/envoyproxy/envoy/pull/30338
Risk Level:
Testing:
Docs Changes:
Release Notes:

backport pr: fix issue-30210 to release/v1.28

---

.github/actions/do_ci/action.yml
.github/workflows/_ci.yml
.github/workflows/envoy-prechecks.yml

This improves github CI by bubbling notice, error, and warning to the github UI
Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Improve action runner

---

ci/build_setup.sh
ci/do_ci.sh

Fix https://github.com/envoyproxy/go-control-plane/issues/806
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/go: Fix compiler for api.go target

---

.github/workflows/envoy-release.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/release: Add version history sync workflow

---

bazel/repository_locations.bzl

docs: fix the license URL of brotli

---

ci/do_ci.sh
ci/run_envoy_docker.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.28] Add var to force docker save (#30502)

---

ci/do_ci.sh
ci/run_envoy_docker.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.26] Add var to force docker save (#30502)

---

.github/workflows/_stage_verify.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Use boosted vm for verify/examples

---

.github/workflows/_stage_verify.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

verify/examples: Remove diskspace hack

---

.github/workflows/envoy-release.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

github/actions: Fix action version

---

.github/workflows/envoy-windows.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

win/ci: Fix ref for PRs

---

.azure-pipelines/env.yml
.azure-pipelines/stages.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/prechecks: Fix condition for postsubmit

---

.azure-pipelines/stage/publish.yml
.github/workflows/_env.yml
.github/workflows/_stage_publish.yml
.github/workflows/_workflow-start.yml
.github/workflows/envoy-publish.yml
.github/workflows/workflow-complete.yml
ci/do_ci.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Make it work in other repos

---

docs/root/configuration/http/http_filters/_include/compressor-filter-request-response.yaml
docs/root/configuration/http/http_filters/_include/compressor-filter.yaml
docs/root/configuration/http/http_filters/compressor_filter.rst

Replace https://github.com/envoyproxy/envoy/pull/30515 and fix envoy config error
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: fix indentation in the compressor filter configuration

---

contrib/generic_proxy/filters/network/source/BUILD
contrib/generic_proxy/filters/network/test/proxy_test.cc
source/common/upstream/BUILD

Commit Message: generic proxy: fix test in debug mode
Risk Level:
Testing:
Docs Changes:
Release Notes:

generic proxy: fix test in debug mode

---

ci/build_setup.sh
ci/run_envoy_docker.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

build/setup: Fix build dir creation

---

.github/workflows/envoy-windows.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

win/ci: Use smaller VMs

---

.github/workflows/_env.yml
.github/workflows/envoy-macos.yml
.github/workflows/envoy-prechecks.yml
.github/workflows/envoy-publish.yml
.github/workflows/envoy-windows.yml
.github/workflows/mobile-android_build.yml
.github/workflows/mobile-android_tests.yml
.github/workflows/mobile-asan.yml
.github/workflows/mobile-cc_tests.yml
.github/workflows/mobile-compile_time_options.yml
.github/workflows/mobile-core.yml
.github/workflows/mobile-coverage.yml
.github/workflows/mobile-docs.yml
.github/workflows/mobile-format.yml
.github/workflows/mobile-ios_build.yml
.github/workflows/mobile-ios_tests.yml
.github/workflows/mobile-release.yml
.github/workflows/mobile-release_validation.yml
.github/workflows/mobile-tsan.yml

I tested the current solution previously and it appeared to work, but it seems its unreliable, and the only reliable way to get the merge commit in a pull_request_target is to ask for it
Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Fix ref properly for PRs

---

.github/workflows/_env.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Minor fix for PR refs

---

.github/workflows/envoy-macos.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

mac/ci: Fix bad merge in refactoring

---

.github/workflows/_stage_publish.yml
.github/workflows/_stage_verify.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

publish/verify: Fix pre steps for CI

---

.github/workflows/_stage_publish.yml
.github/workflows/_stage_verify.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

publish/verify: Fix for ci downloads

---

mobile/library/common/engine_common.cc
source/exe/main_common.cc
source/server/server.cc
source/server/server.h
test/integration/server.cc
test/server/server_fuzz_test.cc
test/server/server_test.cc

Risk Level: low (any overrides must be updated due to constructor change)

server: make initialize non-virtual

---

.github/actions/verify/examples/setup/action.yml
.github/workflows/_stage_publish.yml
.github/workflows/_stage_verify.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

publish-verify-fixes

---

.github/workflows/_stage_publish.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Fix steps in postsubmit publish

---

.github/workflows/_ci.yml
.github/workflows/envoy-macos.yml
ci/mac_ci_steps.sh

- cleanups for macos wf
- switch macos bazel to `--test_output=errors` (ie default)
- improve log capture
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/mac: Improve log output/bubbling

---

.github/workflows/_ci.yml
.github/workflows/_env.yml
.github/workflows/envoy-macos.yml
.github/workflows/envoy-prechecks.yml
.github/workflows/envoy-windows.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Fix PR concurrency

---

test/per_file_coverage.sh

https://storage.googleapis.com/envoy-postsubmit/e1139da/coverage/source/common/api/posix/os_sys_calls_impl.cc.gcov.html
vs
https://storage.googleapis.com/envoy-pr/79b9c3f/coverage/source/common/api/posix/os_sys_calls_impl.cc.gcov.html
line 334
Risk Level:
Testing:
Docs Changes:
Release Notes:

coverage: fix flake

---

source/extensions/extensions_metadata.yaml

It's time.
Risk Level:
Testing:
Docs Changes:
Release Notes:

Turn ext_proc filter into stable.

---

docs/root/intro/arch_overview/http/upgrades.rst

The order of the sections in the upgrades.rst was messed up recently since the new "CONNECT-UDP support" and "Tunneling UDP over HTTP" were inserted in-between the "CONNECT support" and "Tunneling TCP over HTTP". I moved the Tunneling TCP over HTTP section abvoe the CONNECT-UDP support to fix the order.
Risk Level: Low, fixed the documentation only.
Testing: N/A
Docs Changes: Re-ordered the sections in the upgrades.rst.

docs: reorder sections in the upgrades.rst

---

CODEOWNERS
source/extensions/common/aws/utility.cc
source/extensions/tracers/xray/daemon_broker.cc
source/extensions/tracers/xray/xray_tracer_impl.cc

Commit Message: owners: Include suniltheta under AWS files
Additional Description: *Update few TODO comments. Plus removed suniltheta from zipkin extension*
Testing: NA

owners: Include suniltheta under AWS files

---

changelogs/current.yaml
source/common/config/well_known_names.cc
source/common/config/well_known_names.h
test/common/stats/tag_extractor_impl_test.cc
test/extensions/filters/udp/dns_filter/dns_filter_integration_test.cc

Commit Message: Working towards #21595 
Additional Description: extract tag fix for dns filter
Testing: added unit tests to confirm extraction works properly

stats: properly extract tag for dns filter

---

api/envoy/extensions/filters/http/ratelimit/v3/rate_limit.proto
changelogs/current.yaml
docs/root/configuration/http/http_filters/rate_limit_filter.rst
source/extensions/filters/common/ratelimit/stat_names.h
source/extensions/filters/http/ratelimit/ratelimit.h
test/extensions/filters/http/ratelimit/ratelimit_test.cc

Commit Message: ratelimit support stat prefix
Testing: ut

ratelimit support stat prefix

---

source/extensions/filters/http/basic_auth/basic_auth_filter.cc
source/extensions/filters/http/basic_auth/basic_auth_filter.h
source/extensions/filters/http/basic_auth/config.cc
test/extensions/filters/http/basic_auth/basic_auth_integration_test.cc
test/extensions/filters/http/basic_auth/config_test.cc
test/extensions/filters/http/basic_auth/filter_test.cc

Commit Message: basic auth: optimize code and improve the exception/response message
Risk Level: minor.
Testing: unit.

basic auth: optimize code and improve the exception/response message

---

.azure-pipelines/stage/linux.yml
.azure-pipelines/stages.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/rbe: Give build/test higher priority

---

source/extensions/common/wasm/context.h

Testing:
Docs Changes:
Release Notes:

typo: fix common spell error in wasm

---

mobile/library/common/common/default_system_helper_android.cc
mobile/library/common/http/BUILD
mobile/library/common/http/client.cc
mobile/library/common/jni/android_jni_utility.cc
mobile/library/common/jni/android_jni_utility.h
mobile/library/common/jni/android_network_utility.cc
mobile/library/common/jni/android_network_utility.h
mobile/library/common/network/socket_tag_socket_option_impl.cc

mobile: Add namespace to JNI files that don't use C-style convention

---

mobile/test/common/jni/jni_helper_test.cc
mobile/test/java/io/envoyproxy/envoymobile/jni/JniHelperTest.java

Risk Level: low (adding unit tests only)

mobile: Add unit tests for `JniHelper::get<Type>ArrayElements`

---

.github/workflows/mobile-perf.yml
envoy/server/overload/overload_manager.h
mobile/library/common/BUILD
mobile/library/common/engine_common.cc
source/server/BUILD
source/server/admin/BUILD
source/server/admin/admin.cc
source/server/admin/admin.h
source/server/config_validation/BUILD
source/server/config_validation/server.cc
source/server/instance_impl.cc
source/server/instance_impl.h
source/server/null_overload_manager.h
source/server/overload_manager_impl.cc
source/server/overload_manager_impl.h
source/server/server.cc
source/server/server.h
test/mocks/server/overload_manager.h
test/server/admin/admin_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: using a light overloadmanger

---

envoy/tcp/async_tcp_client.h
source/common/tcp/async_tcp_client_impl.h
test/common/tcp/async_tcp_client_impl_test.cc

Testing:
Docs Changes:
Release Notes:

tcp client: expose optional streamInfo

---

.github/workflows/mobile-core.yml
bazel/BUILD
mobile/.bazelrc
source/common/http/header_utility.cc
source/common/quic/envoy_quic_client_stream.h
source/common/quic/envoy_quic_server_stream.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: actually disable datagrams

---

contrib/client_ssl_auth/filters/network/source/config.cc
contrib/client_ssl_auth/filters/network/test/config_test.cc
contrib/dlb/source/connection_balancer_impl.cc
contrib/dlb/source/connection_balancer_impl.h
contrib/dlb/test/config_test.cc
contrib/dynamo/filters/http/source/config.cc
contrib/generic_proxy/filters/network/source/config.cc
contrib/generic_proxy/filters/network/source/proxy.h
contrib/generic_proxy/filters/network/test/config_test.cc
contrib/golang/filters/network/source/config.cc
contrib/golang/filters/network/source/golang.h
contrib/golang/filters/network/source/upstream.cc
contrib/golang/filters/network/test/config_test.cc
contrib/golang/filters/network/test/upstream_test.cc
contrib/kafka/filters/network/source/broker/config.cc
contrib/kafka/filters/network/source/mesh/config.cc
contrib/kafka/filters/network/test/mesh/config_unit_test.cc
contrib/rocketmq_proxy/filters/network/source/config.cc
contrib/sip_proxy/filters/network/source/config.cc
contrib/sip_proxy/filters/network/source/router/config.cc
contrib/sip_proxy/filters/network/source/tra/tra_impl.cc
contrib/squash/filters/http/source/config.cc
contrib/squash/filters/http/test/config_test.cc
contrib/sxg/filters/http/source/config.cc
contrib/sxg/filters/http/test/config_test.cc

See #26476 for related context.
Risk Level:
Testing:
Docs Changes:
Release Notes:

factory context simplification: update code in contrib to access server-wide resource only by server context

---

envoy/upstream/upstream.h
source/common/grpc/BUILD
source/common/grpc/google_grpc_utils.cc
source/common/upstream/default_local_address_selector_factory.cc
source/common/upstream/default_local_address_selector_factory.h
source/common/upstream/upstream_impl.cc
test/common/upstream/default_local_address_selector_test.cc
test/common/upstream/test_local_address_selector.h
test/mocks/upstream/cluster_info.h

exceptions: moving localAddress code over to statusOr

---

api/contrib/envoy/extensions/matching/input_matchers/hyperscan/v3alpha/hyperscan.proto
api/contrib/envoy/extensions/regex_engines/hyperscan/v3alpha/hyperscan.proto
docs/BUILD
docs/root/configuration/other_features/_include/hyperscan_matcher.yaml
docs/root/configuration/other_features/_include/hyperscan_matcher_multiple.yaml
docs/root/configuration/other_features/_include/hyperscan_regex_engine.yaml
docs/root/configuration/other_features/hyperscan.rst
docs/root/configuration/other_features/other_features.rst
docs/root/intro/arch_overview/advanced/matching/matching.rst
docs/root/intro/arch_overview/advanced/matching/matching_api.rst

Commit Message: hyperscan: add configuration docs
Testing: N/A
Docs Changes: Yes, added in configuration reference

hyperscan: add configuration docs

---

contrib/dlb/source/BUILD
contrib/dlb/test/BUILD

Commit Message: Update dlb BUILD make `istio/proxy` buildable on m1 mac, cc @daixiang0 
Risk Level:
Testing:
Docs Changes:
Release Notes:

update dlb BUILD

---

test/integration/filter_integration_test.cc

Test-only change to surface a log message seen in a deployment.
Risk Level: none, test only
Testing:
Docs Changes:
Release Notes:

Adds a log expectation for a test case that matches behavior seen in a deployment

---

source/extensions/filters/network/direct_response/config.cc

Commit Message: network direct response: avoid repeated api reading when creating filter instances
Risk Level:
Testing:
Docs Changes:
Release Notes:

network direct response: avoid repeated api reading when creating filter instances

---

.github/dependabot.yml
contrib/golang/filters/http/source/go/pkg/http/shim.go
contrib/golang/filters/http/source/processor_state.cc
contrib/golang/filters/http/test/BUILD
contrib/golang/filters/http/test/golang_integration_test.cc
contrib/golang/filters/http/test/test_data/action/BUILD
contrib/golang/filters/http/test/test_data/action/config.go
contrib/golang/filters/http/test/test_data/action/filter.go
contrib/golang/filters/http/test/test_data/action/go.mod

golang filter: avoid segfault when the DecodeHeaders returns status ode Stop and the request doesn't have body

---

contrib/golang/filters/http/source/go/pkg/http/type.go
contrib/golang/filters/http/test/test_data/basic/filter.go

Testing: Integration test added
Docs Changes:
Release Notes:
Fixes #30861

golang filter: operate the header case-insensitive

---

api/envoy/config/route/v3/route_components.proto

ConnectMatcher now matches CONNECT-UDP requests as well. I updated the description of ConnectMatcher accordingly.
Risk Level: Low, document only change.
Testing: N/A
Docs Changes: The ConnectMatcher API description has changed. 

api: update ConnectMatcher description.

---

source/common/http/filter_manager.cc

Commit Message: http: add filter names to route-specific filter config warning
Additional Description: improves ease of debugging this warning.
Testing: none -- log-only change

http: add filter names to route-specific filter config warning

---

api/envoy/extensions/upstreams/http/generic/v3/generic_connection_pool.proto
envoy/router/router.h

Update existing comments for newly added UDP Upstream.
Risk Level: Low, comment only change.
Testing: N/A

http: update comments for newly added UDP Upstream.

---

.github/workflows/mobile-tsan.yml

build: Wrap line in .github/workflows/mobile-tsan.yml
Missed a comment from #31093

build: Wrap line in .github/workflows/mobile-tsan.yml

---

mobile/library/java_proto_proguard.txt
mobile/library/proguard.txt

mobile: Move the remaining protobuf rules to java_proto_proguard.txt

---

docs/root/configuration/http/http_filters/oauth2_filter.rst

Commit Message: Typo fix in Oauth2 Filter documentation
Testing:
Docs Changes: Typo fix
Release Notes:

docs: typo fix

---

mobile/envoy_build_config/BUILD
mobile/envoy_build_config/extension_registry.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: removing gzip compressor

---

source/common/http/filter_manager.cc
source/common/init/manager_impl.h
test/common/common/lock_guard_test.cc
test/common/http/conn_manager_impl_fuzz_test.cc

`include` folder is removed for a while and we should update the comment which is related
Risk Level: no
Testing:

fix the path in the comment

---

source/common/grpc/BUILD
source/common/grpc/common.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

Optimize grpc header magic number

---

docs/root/configuration/observability/access_log/usage.rst
source/common/formatter/stream_info_formatter.cc
test/common/formatter/substitution_formatter_test.cc

Commit Message: add connectionPoolCallbackLatency to access log
Testing: ut

add connectionPoolCallbackLatency to access log

---

CONTRIBUTING.md

governance: updating review changes

---

envoy/secret/secret_manager.h
source/common/secret/secret_manager_impl.cc
source/common/secret/secret_manager_impl.h
source/server/configuration_impl.cc
test/common/secret/secret_manager_impl_test.cc
test/extensions/transport_sockets/tls/context_impl_test.cc
test/mocks/secret/mocks.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

secret manager: refactoring to use statusor

---

source/extensions/clusters/dynamic_forward_proxy/cluster.cc
source/extensions/clusters/dynamic_forward_proxy/cluster.h
source/extensions/common/dynamic_forward_proxy/dns_cache.h
source/extensions/common/dynamic_forward_proxy/dns_cache_manager_impl.cc
source/extensions/common/dynamic_forward_proxy/dns_cache_manager_impl.h
source/extensions/filters/http/dynamic_forward_proxy/config.cc
source/extensions/filters/http/dynamic_forward_proxy/config.h
source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc
source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.h
source/extensions/filters/network/redis_proxy/proxy_filter.cc
source/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter.cc
source/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter.h
source/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/proxy_filter.cc
source/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/proxy_filter.h
test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc
test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc
test/extensions/common/dynamic_forward_proxy/mocks.h
test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_test.cc

dns: removing exceptions from cache manager

---

bazel/repository_locations.bzl

Risk Level:
Testing:
Docs Changes:
Release Notes:

bazel/deps: Fix for opencensus/curl deps

---

source/common/buffer/buffer_impl.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: update slice data pointer same as other pointer naming

---

source/common/http/conn_manager_impl.cc
source/common/http/conn_manager_impl.h
test/common/http/conn_manager_impl_test_2.cc

Testing: yes
Release Notes: no, intentionally
fixes https://github.com/envoyproxy/envoy/issues/30010

http: adding in a runtime knob to tune delay-close

---

.github/config.yml
.github/workflows/mobile-cc_tests.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

gh/ci: Improve check names

---

.github/workflows/_precheck_deps.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Fix dependency review action

---

.github/workflows/_finish.yml
.github/workflows/_load.yml

this prevents the CI scanner triggering false positives on words like `value`, thins the data model, and fixes some output
Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Fix/cleanup data model

---

.github/workflows/command.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Add back missing condition on command

---

.github/config.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Fix path/conditions for mobile CI

---

.github/config.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Improve CI path conditions

---

.github/workflows/_load.yml
.github/workflows/_start.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Small fix for skipped checks

---

.github/workflows/_cache.yml
.github/workflows/_finish.yml
.github/workflows/_load.yml
.github/workflows/_request.yml
.github/workflows/_run.yml
.github/workflows/_stage_publish.yml
.github/workflows/_start.yml
.github/workflows/codeql-push.yml
.github/workflows/command.yml
.github/workflows/envoy-dependency.yml
.github/workflows/envoy-release.yml
.github/workflows/envoy-sync.yml

and thin out data model
Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Fix false positive in Githubs secret scanner

---

.github/workflows/_cache.yml
.github/workflows/_finish.yml
.github/workflows/_load.yml
.github/workflows/_request.yml
.github/workflows/_run.yml
.github/workflows/_stage_publish.yml
.github/workflows/_start.yml
.github/workflows/codeql-push.yml
.github/workflows/command.yml
.github/workflows/envoy-dependency.yml
.github/workflows/envoy-release.yml
.github/workflows/envoy-sync.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Fix URI handling of check name

---

.github/workflows/_cache.yml
.github/workflows/_finish.yml
.github/workflows/_load.yml
.github/workflows/_request.yml
.github/workflows/_run.yml
.github/workflows/_stage_publish.yml
.github/workflows/_stage_verify.yml
.github/workflows/_start.yml
.github/workflows/codeql-push.yml
.github/workflows/command.yml
.github/workflows/envoy-dependency.yml
.github/workflows/envoy-release.yml
.github/workflows/envoy-sync.yml
.github/workflows/mobile-android_build.yml
.github/workflows/mobile-ios_build.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Improve retest err/output handling

---

.github/workflows/command.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Format fix

---

.github/workflows/mobile-android_build.yml
.github/workflows/mobile-android_tests.yml
.github/workflows/mobile-asan.yml
.github/workflows/mobile-cc_tests.yml
.github/workflows/mobile-compile_time_options.yml
.github/workflows/mobile-core.yml
.github/workflows/mobile-ios_build.yml
.github/workflows/mobile-ios_tests.yml
.github/workflows/mobile-release_validation.yml
.github/workflows/mobile-tsan.yml
mobile/.bazelrc

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/ci: Shift bazel configs to .bazelrc

---

.github/workflows/_cache.yml
.github/workflows/_finish.yml
.github/workflows/_load.yml
.github/workflows/_request.yml
.github/workflows/_run.yml
.github/workflows/_stage_publish.yml
.github/workflows/_stage_verify.yml
.github/workflows/_start.yml
.github/workflows/codeql-push.yml
.github/workflows/command.yml
.github/workflows/envoy-release.yml
.github/workflows/envoy-sync.yml
.github/workflows/mobile-android_build.yml
.github/workflows/mobile-ios_build.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Improve checks handling

---

.github/workflows/envoy-dependency.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/tooling: Improve/update dependency updater

---

.github/workflows/_run.yml
.github/workflows/_stage_publish.yml
.github/workflows/_stage_verify.yml
.github/workflows/mobile-android_build.yml
.github/workflows/mobile-ios_build.yml

dependabot is not seeing/updating dynamic actions
Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Manually update actions missed by dependabot

---

envoy/common/exception.h
envoy/upstream/cluster_manager.h
source/common/grpc/async_client_manager_impl.cc
source/common/upstream/cluster_manager_impl.cc
source/common/upstream/cluster_manager_impl.h
source/server/config_validation/cluster_manager.cc
source/server/server.cc
test/common/grpc/async_client_manager_impl_test.cc
test/common/upstream/cluster_manager_impl_test.cc
test/common/upstream/deferred_cluster_initialization_test.cc
test/common/upstream/test_cluster_manager.h
test/extensions/clusters/aggregate/cluster_update_test.cc
test/mocks/upstream/cluster_manager.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

cluster: removing some exceptions in favor of error handling

---

.github/config.yml
.github/dependabot.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

deps/ci: Fix missing go.mod config and dep check conditions

---

.github/workflows/mobile-ios_build.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/ci: Fix/cleanup iOS build tests

---

mobile/test/common/integration/client_integration_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: adding more h2 tests

---

test/per_file_coverage.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/coverage: Adjust quic limit

---

.github/workflows/_finish.yml
.github/workflows/_load.yml

small cleanups to improve action I/O
Risk Level:
Testing:
Docs Changes:
Release Notes:

github/ci: Assorted cleanups

---

ci/verify_examples.sh

https://github.com/envoyproxy/envoy/issues/31333
Risk Level:
Testing:
Docs Changes:
Release Notes:

verify/examples: Expect/allow failure for locality-load-balancing

---

examples/shared/build/Dockerfile

This reverts commit 536caa8999ba2a89f5962fda9293da9c390b9386.
Risk Level:
Testing:
Docs Changes:
Release Notes:

Revert "examples: Workaround kitware apt issue in wasm example (#27206)"

---

.github/workflows/_cache.yml
.github/workflows/_finish.yml
.github/workflows/_load.yml
.github/workflows/_request.yml
.github/workflows/_run.yml
.github/workflows/_stage_publish.yml
.github/workflows/_stage_verify.yml
.github/workflows/_start.yml
.github/workflows/codeql-push.yml
.github/workflows/command.yml
.github/workflows/envoy-dependency.yml
.github/workflows/envoy-release.yml
.github/workflows/envoy-sync.yml
.github/workflows/mobile-android_build.yml
.github/workflows/mobile-ios_build.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/ci: Fix/improve iOS build tests

---

ci/verify_examples.sh

https://github.com/envoyproxy/envoy/issues/31347
Risk Level:
Testing:
Docs Changes:
Release Notes:

verify/examples: Expect/allow failure for local_ratelimit

---

source/extensions/config_subscription/grpc/BUILD
source/extensions/config_subscription/grpc/grpc_stream.h
source/extensions/config_subscription/grpc/grpc_stream_interface.h
test/extensions/config_subscription/grpc/grpc_stream_test.cc

Commit Message: xds: minor refactor introducing an interface for GrpcStream
Introducing an interface for GrpcStream to make it easier to test (as part of the work of xDS-Failover support #28099)
Testing: N/A

xds: minor refactor introducing an interface for GrpcStream

---

bazel/BUILD
tools/dependency/BUILD

Risk Level:
Testing:
Docs Changes:
Release Notes:

bazel/updater: Use workaround to filter deps + format fix

---

.github/workflows/envoy-windows.yml
.github/workflows/mobile-release.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/actions: Revert artefact up/download update to fix windows

---

.github/workflows/mobile-traffic_director.yml

Until https://github.com/envoyproxy/envoy/issues/31416 is resolved.

mobile/ci: Disable the Mobile Traffic Director workflow

---

.github/config.yml
bazel/foreign_cc/BUILD
bazel/repositories.bzl
bazel/repository_locations.bzl
contrib/kafka/filters/network/source/mesh/upstream_kafka_client.h
contrib/kafka/filters/network/source/mesh/upstream_kafka_consumer_impl.cc
tools/dependency/BUILD

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.27] deps/tooling: Fix for CVE scanner

---

examples/shared/golang/Dockerfile
examples/shared/node/Dockerfile
examples/shared/python/Dockerfile
examples/shared/websocket/Dockerfile

Risk Level:
Testing:
Docs Changes:
Release Notes:

examples: Bump `debian` -> bookworm

---

.github/workflows/_cache.yml
.github/workflows/_finish.yml
.github/workflows/_load.yml
.github/workflows/_load_env.yml
.github/workflows/_mobile_container_ci.yml
.github/workflows/_request.yml
.github/workflows/_run.yml
.github/workflows/_stage_publish.yml
.github/workflows/_stage_verify.yml
.github/workflows/_start.yml
.github/workflows/codeql-push.yml
.github/workflows/command.yml
.github/workflows/envoy-dependency.yml
.github/workflows/envoy-release.yml
.github/workflows/envoy-sync.yml
.github/workflows/mobile-android_build.yml
.github/workflows/mobile-ios_build.yml
.github/workflows/mobile-perf.yml
.github/workflows/mobile-release.yml
mobile/.bazelrc

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/ci: Use new CI for scheduled/triggered (+cleanups)

---

changelogs/current.yaml
contrib/generic_proxy/filters/network/source/proxy.h

Commit Message: Optimize generic proxy stats classification
Risk Level: 
Testing:
Docs Changes:
Release Notes:

generic proxy : Optimize generic proxy stats classification

---

contrib/golang/common/go/api/capi.go
contrib/golang/common/go/api/filter.go
contrib/golang/filters/http/source/cgo.cc
contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
contrib/golang/filters/http/source/go/pkg/http/filter.go
contrib/golang/filters/http/test/golang_integration_test.cc
contrib/golang/filters/http/test/test_data/basic/filter.go

fix https://github.com/envoyproxy/envoy/issues/31127
Risk Level:
Testing:
Docs Changes:
Release Notes:

Golang filter: SendLocalReply support multiple header values for a header name

---

source/extensions/filters/http/cache/cache_filter.cc

Commit Message: [cache-filter] don't set empty content-length
Additional Description: Filter was indiscriminately setting content-length header to the value from the cache, including, in the problem case, empty-string.
Risk Level: Can't imagine anyone is relying on invalid headers in cache responses, but you never know.
Testing: Covered by existing tests; doesn't seem worth including a regression test given the enormous size of the existing test for this function - the maintenance burden would exceed the value.
Fixes #31420

[cache-filter] don't set empty content-length

---

source/common/tcp_proxy/tcp_proxy.cc
source/common/tcp_proxy/tcp_proxy.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

tcp_proxy: simply flushAccessLog

---

.github/workflows/_stage_verify.yml
examples/verify-common.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

examples: New utility and host util installs

---

.github/workflows/_cache.yml
.github/workflows/_finish.yml
.github/workflows/_load.yml
.github/workflows/_load_env.yml
.github/workflows/_precheck_deps.yml
.github/workflows/_request.yml
.github/workflows/_run.yml
.github/workflows/_stage_publish.yml
.github/workflows/_stage_verify.yml
.github/workflows/_start.yml
.github/workflows/codeql-daily.yml
.github/workflows/codeql-push.yml
.github/workflows/command.yml
.github/workflows/envoy-dependency.yml
.github/workflows/envoy-release.yml
.github/workflows/envoy-sync.yml
.github/workflows/envoy-windows.yml
.github/workflows/mobile-android_build.yml
.github/workflows/mobile-compile_time_options.yml
.github/workflows/mobile-format.yml
.github/workflows/mobile-ios_build.yml
.github/workflows/mobile-release.yml
.github/workflows/mobile-traffic_director.yml
.github/workflows/pr_notifier.yml
.github/workflows/scorecard.yml
.github/workflows/stale.yml
README.md

Commit Message: Setup scorecard workflow and pin actions versions
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional ]
Fixes #31540
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

Setup scorecard workflow and pin actions versions

---

.github/workflows/codeql-daily.yml
.github/workflows/codeql-push.yml

Commit Message: fix github/codeql-action version in comments
Risk Level:
Testing:
Docs Changes:
Release Notes:
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

fix github/codeql-action version in comments

---

.vscode/tasks.json

Commit Message: always need run this before a push, so maybe it's good to add it here.
Risk Level:
Testing:
Docs Changes:
Release Notes:

add format task for vscode

---

mobile/test/common/integration/client_integration_test.cc
test/integration/autonomous_upstream.cc
test/integration/autonomous_upstream.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: more lifetime tests

---

.github/dependabot.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

dependabot: Group updates

---

examples/shared/node/Dockerfile
examples/shared/node/routes.jq
examples/shared/node/scripts/build-routed.sh
examples/shared/node/scripts/build.sh
examples/shared/node/scripts/dev.sh
examples/shared/node/scripts/entrypoint.sh

This is a breakout from #31534 but can be useful for a bunch of existing sandboxes also
Risk Level:
Testing:
Docs Changes:
Release Notes:

examples: Add shared node/yarn recipe/s

---

docs/root/start/quick-start/_include/envoy-dynamic-filesystem-demo.yaml
docs/root/start/quick-start/configuration-dynamic-filesystem.rst
examples/dynamic-config-fs/envoy.yaml

Risk Level:
Testing:
Docs Changes:
Release Notes:

configs: Fix `dynamic_resources` API version

---

test/extensions/filters/http/buffer/buffer_filter_integration_test.cc
test/integration/http_integration.cc
test/integration/protocol_integration_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

quic: fixing a test flake

---

envoy/network/resolver.h
source/common/listener_manager/listener_impl.cc
source/common/listener_manager/listener_manager_impl.cc
source/common/network/resolver_impl.cc
source/common/network/resolver_impl.h
source/common/upstream/health_discovery_service.cc
source/common/upstream/upstream_impl.cc
source/extensions/network/dns_resolver/cares/dns_impl.cc
source/extensions/stat_sinks/dog_statsd/config.cc
source/extensions/stat_sinks/graphite_statsd/config.cc
source/extensions/stat_sinks/statsd/config.cc
source/server/api_listener_impl.cc
source/server/api_listener_impl.h
source/server/configuration_impl.cc
test/common/network/resolver_impl_test.cc
test/fuzz/utility.h
test/mocks/network/mocks.h
test/server/api_listener_test.cc
tools/code_format/config.yaml

Risk Level:
Testing:
Docs Changes:
Release Notes:

Resolver: switching to statusor

---

source/common/quic/envoy_quic_client_stream.cc
source/common/quic/envoy_quic_server_stream.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

build: fix no-datagram build

---

test/per_file_coverage.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

coverage: bumping

---

source/common/router/config_impl.cc
source/common/router/config_utility.cc
source/common/router/config_utility.h
test/common/router/config_impl_test.cc
tools/code_format/config.yaml

router: changing config util to take statusOr

---

.circleci/config.yml
ci/Dockerfile-envoy-windows
source/extensions/tracers/datadog/demo/docker-compose.yaml
source/extensions/tracers/datadog/demo/http.dockerfile

Commit Message: Pin docker versions
Risk Level:
Testing:
Docs Changes:
Release Notes:

Pin docker versions

---

contrib/golang/filters/http/test/test_data/buffer/go.mod

Fix #31551 
Risk Level:
Testing:
Docs Changes:
Release Notes:

go/deps: Fix bad dependency

---

changelogs/current.yaml

Risk Level:
Testing:
Docs Changes:
Release Notes:

changelogs: Cleanups

---

api/envoy/config/core/v3/base.proto

Commit Message: fix HeaderAppendAction comment
Testing: N/A

fix HeaderAppendAction comment

---

.github/config.yml
.github/workflows/mobile-compile_time_options.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/ci: Always run CC compile-time-options tests in PRs

---

changelogs/current.yaml

I forgot to update `changelogs/current.yaml` in <https://github.com/envoyproxy/envoy/pull/31669>.
This pull request has the appropriate `bug_fixes` entry.

update changelog for #31669

---

.github/workflows/mobile-compile_time_options.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/ci: Ensure request complete job always runs

---

mobile/library/common/http/client.cc

Risk Level: low (variable name change only)
Testing: n/a

mobile: Fix a typo

---

changelogs/current.yaml

This PR move 2 new features in release note from the incorrect seccion of changing behavior to new features without current user possible incompatibilities
Testing: n/a

Move 2 new features into the correct release note section

---

api/envoy/extensions/filters/common/set_filter_state/v3/value.proto
docs/root/configuration/advanced/well_known_filter_state.rst
source/extensions/filters/common/set_filter_state/BUILD
source/extensions/filters/common/set_filter_state/filter_config.cc
source/extensions/filters/common/set_filter_state/filter_config.h
test/extensions/filters/common/set_filter_state/filter_config_test.cc

Commit Message: add an option to use a generic string object for the value
Risk Level: low (new oneof but a recent extension)
Testing: done

set_filter_state: add a string key option

---

.github/workflows/_cache.yml
.github/workflows/_finish.yml
.github/workflows/_load.yml
.github/workflows/_load_env.yml
.github/workflows/_request.yml
.github/workflows/_run.yml
.github/workflows/_stage_publish.yml
.github/workflows/_stage_verify.yml
.github/workflows/_start.yml
.github/workflows/codeql-push.yml
.github/workflows/command.yml
.github/workflows/envoy-dependency.yml
.github/workflows/envoy-release.yml
.github/workflows/envoy-sync.yml
.github/workflows/mobile-android_build.yml
.github/workflows/mobile-ios_build.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Bump toolshed actions -> 0.2.23

---

bazel/python_dependencies.bzl
tools/base/requirements.in
tools/base/requirements.txt

Risk Level:
Testing:
Docs Changes:
Release Notes:

deps/docs: Update `sphinx` and friends

---

.github/workflows/_cache.yml
.github/workflows/_finish.yml
.github/workflows/_load.yml
.github/workflows/_load_env.yml
.github/workflows/_request.yml
.github/workflows/_run.yml
.github/workflows/_stage_publish.yml
.github/workflows/_stage_verify.yml
.github/workflows/_start.yml
.github/workflows/codeql-push.yml
.github/workflows/command.yml
.github/workflows/envoy-dependency.yml
.github/workflows/envoy-release.yml
.github/workflows/envoy-sync.yml
.github/workflows/mobile-android_build.yml
.github/workflows/mobile-ios_build.yml

- use appauth
- fix commit/pr messaging
Risk Level:
Testing:
Docs Changes:
Release Notes:

release/ci: Assorted fixes/cleanups

---

.github/workflows/mobile-format.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/ci: Fix format job dependency

---

.github/workflows/envoy-release.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/release: Fix appauth

---

envoy/common/io/io_uring.h
source/common/io/io_uring_worker_impl.cc
source/common/io/io_uring_worker_impl.h
test/common/io/io_uring_worker_impl_integration_test.cc
test/common/io/io_uring_worker_impl_test.cc
test/mocks/io/mocks.h

Commit Message: io_uring: add client socket
Testing: Unit and integration tests, #28824
Part of Issue #28395 
Continue of #28706 #30773

io_uring: add client socket

---

test/integration/run_envoy_test.sh
test/per_file_coverage.sh

Commit Message: fixes a flake about binding to UDS hot restart socket.
Risk Level:
Testing:
Docs Changes:
Release Notes:

test: disable hot restart to prevent sharing

---

.github/workflows/mobile-compile_time_options.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/ci: Fix compile-time-options check completion

---

tools/repo/notify.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

tools/notify: Reorder/cleanup maintainer lists

---

.github/workflows/codeql-push.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/codeql: Remove errant debugging

---

changelogs/summary.md

v1.29.0 change summary

---

test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc

Enhancing grid tests to wait on connection pool teardown
Testing:  yes

test: adding more grid tests

---

source/common/http/http2/codec_impl.cc

This is refactoring in preparation for removing the nghttp2_callback API layer.
Commit Message: http2: moves some frame accounting to onBeforeFrameReceived.
Risk Level: low; refactoring, no functional change intended
Docs Changes:
Release Notes:

http2: moves some frame accounting to onBeforeFrameReceived.

---

source/common/network/resolver_impl.cc
test/common/network/resolver_impl_test.cc

resolver: using statusor

---

source/common/event/timer_impl.h
test/common/event/dispatcher_impl_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

timer: error handling over crashing

---

RELEASES.md

Testing:
Docs Changes:
Release Notes:

doc: fix a release typo

---

source/common/rds/rds_route_config_subscription.cc
source/common/rds/rds_route_config_subscription.h
source/common/router/rds_impl.cc
source/common/router/rds_impl.h
source/common/router/vhds.cc
source/common/router/vhds.h
test/common/router/vhds_test.cc
tools/code_format/config.yaml

Risk Level:
Testing:
Docs Changes:
Release Notes:

vhds: removing an exception

---

source/extensions/filters/http/ext_authz/ext_authz.h

Fix ASAN error in ext_authz tests

---

source/common/quic/quic_server_transport_socket_factory.cc
tools/code_format/config.yaml

Risk Level:
Testing:
Docs Changes:
Release Notes:

quic: removing a legacy OrPanic

---

changelogs/1.29.0.yaml

This reverts commit 2dfe2ec0c054a60e833cd55605c96ec61c3a5dda.
Risk Level:
Testing:
Docs Changes:
Release Notes:

Revert "Update changelogs/1.29.0.yaml for PR#31762 (#31906)"

---

OWNERS.md
README.md
SECURITY-INSIGHTS.yml

Clomonitor requires a SECURITY-INSIGHTS.yml,
See https://clomonitor.io/projects/cncf/envoy#envoy_security
This is a first draft based https://github.com/ossf/security-insights-spec/blob/v1.0.0/specification.md and what I could find on the repository.
[![CLOMonitor](https://img.shields.io/endpoint?url=https://clomonitor.io/api/projects/cncf/envoy/badge)](https://clomonitor.io/projects/cncf/envoy)
Commit Message: Create OSSF SECURITY-INSIGHTS.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:

Create OSSF SECURITY-INSIGHTS.yml

---

SECURITY-INSIGHTS.yml

Commit Message: Fix a typo in the SECURITY-INSIGHT.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:

fix: status instead of stage

---

source/common/config/config_provider_impl.h
source/common/config/datasource.cc
source/common/config/subscription_factory_impl.cc
source/common/config/utility.cc
source/common/config/utility.h
source/common/secret/sds_api.h
source/common/upstream/cluster_manager_impl.cc
source/extensions/config_subscription/grpc/grpc_collection_subscription_factory.cc
source/extensions/config_subscription/grpc/grpc_mux_impl.cc
source/extensions/config_subscription/grpc/grpc_subscription_factory.cc
source/extensions/config_subscription/grpc/xds_mux/grpc_mux_impl.cc
source/extensions/config_subscription/rest/http_subscription_impl.cc
source/extensions/config_subscription/rest/http_subscription_impl.h
source/extensions/stat_sinks/common/statsd/statsd.cc
source/extensions/tracers/datadog/tracer.cc
source/extensions/tracers/zipkin/zipkin_tracer_impl.cc
source/server/server.cc
test/common/config/utility_test.cc
tools/code_format/config.yaml

Risk Level:
Testing:
Docs Changes:
Release Notes:

config: moving utils over to using error handling

---

SECURITY-INSIGHTS.yml

This completes https://clomonitor.io/docs/topics/checks/#dependencies-policy
Commit Message: Add policy-url for env-dependencies-policy
Risk Level:
Testing:
Docs Changes:
Release Notes:

ossf: provide env-dependencies-policy

---

mobile/test/common/integration/client_integration_test.cc

for https://github.com/envoyproxy/envoy/issues/32024

mobile: adding flake logging

---

source/common/upstream/upstream_impl.cc

Avoid copying proto sub object when parsing config

---

examples/single-page-app/ui/yarn.lock

Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Bump single page app example deps

---

RELEASES.md

No longer tweeting (X-ing?) the new release
Witty emails still required though, @ravenblackx  :-P

docs: updating release instructions

---

OWNERS.md

Switch to personal email due to me changing companies
Risk Level:
Testing:
Docs Changes:
Release Notes:

Update nezdolik to personal email

---

envoy/server/filter_config.h
source/common/http/utility.cc
source/common/http/utility.h
source/common/upstream/upstream_impl.cc
source/extensions/filters/network/common/factory_base.h
source/extensions/filters/network/http_connection_manager/config.cc
source/extensions/upstreams/http/config.cc
source/extensions/upstreams/http/config.h
source/extensions/upstreams/tcp/config.h
source/server/admin/admin.cc
test/common/http/codec_impl_fuzz_test.cc
test/common/http/http2/frame_replay.cc
test/common/http/http2/http2_connection_fuzz_test.cc
test/common/http/utility_fuzz_test.cc
test/common/http/utility_test.cc
test/common/upstream/upstream_impl_test.cc
test/extensions/upstreams/http/config_test.cc
test/integration/fake_upstream.h
test/integration/http_integration.cc
test/integration/multiplexed_integration_test.cc
test/integration/protocol_integration_test.cc
test/mocks/upstream/cluster_info.cc
tools/code_format/config.yaml

Risk Level:
Testing:
Docs Changes:
Release Notes:

http: moving validaite options to statusor

---

contrib/generic_proxy/filters/network/test/BUILD
contrib/generic_proxy/filters/network/test/access_log_test.cc

Commit Message: generic proxy: add more unit test for the access log
Testing: unit.

generic proxy: add more unit test for the access log

---

docs/root/intro/arch_overview/advanced/attributes.rst

Commit Message: fix table layout
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: fix layout for attributes

---

api/envoy/config/listener/v3/quic_config.proto
changelogs/current.yaml
source/common/quic/active_quic_listener.cc
test/integration/quic_http_integration_test.cc

Testing: Added new tests
Docs Changes: documented new field

quic: add option to send disable_active_migration

---

source/extensions/resource_monitors/downstream_connections/downstream_connections_monitor.cc

Testing:
Docs Changes:
Release Notes:

nit: change increment to decrement

---

CODEOWNERS

Risk Level:
Testing:
Docs Changes:
Release Notes:

repo: Add docs-shepherds to CODEOWNERS

---

.github/workflows/envoy-macos.yml
test/common/api/os_sys_calls_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

test using macos-14 runner instead of macos-12

---

envoy/http/query_params.h
source/common/buffer/watermark_buffer.cc
source/common/common/perf_tracing.cc
source/common/http/date_provider_impl.h
source/common/http/http_server_properties_cache_impl.cc
source/common/http/match_delegate/config.cc
source/common/http/null_route_impl.cc
source/common/network/io_socket_handle_base_impl.cc
source/common/network/tcp_listener_impl.h
source/common/quic/envoy_quic_client_session.cc
source/common/quic/envoy_quic_server_session.cc
source/common/upstream/load_balancer_impl.cc
source/extensions/clusters/redis/crc16.cc
source/extensions/clusters/redis/redis_cluster.cc
source/extensions/clusters/redis/redis_cluster_lb.cc
source/extensions/common/dubbo/codec.cc
source/extensions/common/dubbo/codec.h
source/extensions/common/dubbo/hessian2_serializer_impl.cc
source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc
source/extensions/filters/http/connect_grpc_bridge/filter.h
source/extensions/filters/http/ext_proc/processor_state.cc
source/extensions/filters/listener/proxy_protocol/proxy_protocol.h
source/extensions/geoip_providers/maxmind/config.cc
source/extensions/http/cache/file_system_http_cache/lookup_context.cc
source/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector.cc
source/extensions/tracers/opentelemetry/span_context_extractor.cc
source/server/config_validation/dispatcher.h

Commit Message: minor update: minor update to fix the header including in the 'source'
The relative path to the workspace root should be used for the header file including. But some lines are wrong and this patch fix all this type issues (?) in the 'source'.
Risk Level:
Testing:
Docs Changes:
Release Notes:

minor update: minor update to fix the header including in the 'source'

---

test/per_file_coverage.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

test/coverage: Lower `source/common` (related to `io_uring` execution)

---

mobile/library/common/internal_engine.cc
mobile/library/common/internal_engine.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: fixing internal engine destructor

---

envoy/common/io/io_uring.h
source/common/io/BUILD
source/common/io/io_uring_impl.cc
source/common/io/io_uring_impl.h
source/common/io/io_uring_worker_factory_impl.cc
source/common/io/io_uring_worker_factory_impl.h
test/common/io/BUILD
test/common/io/io_uring_impl_test.cc
test/common/io/io_uring_worker_factory_impl_test.cc
test/mocks/io/mocks.h

Commit Message: io_uring: add io_uring worker factory
Additional Description: `IoUringWorkerFactory` replaces `IoUringFactory` and initializes `IoUringWorker` in the thread local storage.

io_uring: add io_uring worker factory

---

source/extensions/filters/http/rate_limit_quota/client_impl.cc
source/extensions/filters/http/rate_limit_quota/filter.cc

- Add more logging around stream start and close
- Clean up obsolete TODO

rlqs: Add more logging around stream start and close

---

test/per_file_coverage.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

coverage: removing flake

---

bazel/cel-cpp.patch

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.29] macos: fix linker error from CEL library (#32148)

---

api/envoy/config/core/v3/protocol.proto

Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: updating to correct initial window sizes

---

ci/osx-build-config/extensions_build_config.bzl

Commit Message: Attempting to catch build breaks similar to those in #31932
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: add a few more extensions to macOS

---

contrib/generic_proxy/filters/network/source/file_access_log.h
envoy/access_log/access_log.h
source/common/access_log/access_log_manager_impl.cc
source/common/access_log/access_log_manager_impl.h
source/common/common/logger_delegates.cc
source/common/upstream/health_checker_event_logger.h
source/common/upstream/outlier_detection_impl.h
source/extensions/access_loggers/common/file_access_log_impl.cc
source/extensions/filters/network/mongo_proxy/proxy.cc
source/extensions/health_check/event_sinks/file/file_sink_impl.h
source/extensions/transport_sockets/tls/context_impl.cc
test/common/access_log/access_log_impl_test.cc
test/common/access_log/access_log_manager_impl_test.cc
test/mocks/access_log/mocks.h
tools/code_format/config.yaml

envoy: moving access log manager to statusor

---

.azure-pipelines/ci.yml
.azure-pipelines/stage/linux.yml
.github/config.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.26] Backport stack (/cont)

---

.azure-pipelines/ci.yml
.azure-pipelines/stage/linux.yml
.github/config.yml
ci/verify_examples.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.27] Backport stack (/cont)

---

.github/config.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.29] ci/release: Ensure windows is built on release

---

.github/config.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/release: Ensure windows is built on release

---

.github/workflows/_cache.yml
.github/workflows/_finish.yml
.github/workflows/_load.yml
.github/workflows/_load_env.yml
.github/workflows/_request.yml
.github/workflows/_run.yml
.github/workflows/_stage_publish.yml
.github/workflows/_stage_verify.yml
.github/workflows/_start.yml
.github/workflows/codeql-push.yml
.github/workflows/command.yml
.github/workflows/envoy-dependency.yml
.github/workflows/envoy-release.yml
.github/workflows/envoy-sync.yml
.github/workflows/mobile-android_build.yml
.github/workflows/mobile-ios_build.yml

Fix #32044 (hopefully)
Risk Level:
Testing:
Docs Changes:
Release Notes:

deps/ci: Bump `toolshed` actions -> 0.2.24

---

.github/workflows/codeql-daily.yml
.github/workflows/codeql-push.yml

- fix concurrency groups
- add diskspace hack for scheduled job
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: CodeQL fixes

---

test/common/http/conn_manager_impl_corpus/clusterfuzz-testcase-minimized-conn_manager_impl_fuzz_test-5160321246167040
test/common/http/conn_manager_impl_fuzz_test.cc

Add additional catch for end stream to disallow other response, also correct the mock method.
Testing:
Docs Changes:
Release Notes:

hcm: fuzz to handle upgrade and end stream correctly.

---

envoy/stats/stats.h

Commit Message: Comment: Update comment since nameCStr was removed.
Testing: na

Comment: Update comment since nameCStr was removed.

---

.github/config.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/ci: Ensure core CI is run for only top-level files

---

tools/repo/notify.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: tracking open issues

---

OWNERS.md

Commit Message: owners: updating kbaichoo's email address
Additional Description: owners: updating kbaichoo's email address

owners: updating kbaichoo's email address

---

test/extensions/filters/http/geoip/BUILD
test/extensions/geoip_providers/maxmind/BUILD

Risk Level:
Testing:
Docs Changes:
Release Notes:

Execute geoip tests on osx

---

envoy/server/overload/load_shed_point.h
source/common/http/conn_manager_impl.cc
source/common/http/http1/codec_impl.cc
source/common/http/http2/codec_impl.cc
source/common/network/tcp_listener_impl.cc

Testing:
Docs Changes:
Release Notes:

OM: move lsp names to one place

---

.bazelrc
.github/workflows/envoy-macos.yml

Fix #32467 
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/macos: Use Engflow for bazel cache

---

.bazelrc
.github/workflows/envoy-macos.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.29] ci/macos: Use Engflow for bazel cache (#32520)

---

.github/workflows/mobile-ios_build.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/ios: Prevent use of android NDK in CI

---

ci/Dockerfile-envoy

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.28] Update distroless image

---

ci/Dockerfile-envoy

Risk Level:
Testing:
Docs Changes:
Release Notes:

[1.29/bp] Update distroless image

---

ci/Dockerfile-envoy

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.26] Update distroless image

---

source/common/network/address_impl.cc

Testing:
Docs Changes:
Release Notes:
Fixes #32527

network: fix tsan test flake

---

.github/workflows/_run.yml
.github/workflows/envoy-windows.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Set default timeout (and add for windows)

---

.github/workflows/_cache.yml
.github/workflows/_finish.yml
.github/workflows/_load.yml
.github/workflows/_load_env.yml
.github/workflows/_request.yml
.github/workflows/_run.yml
.github/workflows/_stage_publish.yml
.github/workflows/_stage_verify.yml
.github/workflows/_start.yml
.github/workflows/codeql-daily.yml
.github/workflows/codeql-push.yml
.github/workflows/command.yml
.github/workflows/envoy-dependency.yml
.github/workflows/envoy-release.yml
.github/workflows/envoy-sync.yml
.github/workflows/garbage.yml
.github/workflows/mobile-android_build.yml
.github/workflows/mobile-ios_build.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Add scheduled garbage collection (and fix retest)

---

OWNERS.md

Testing: he's done lots
Docs Changes: less of these by project nature

owners: adding Fredy as an Enovy Mobile maintainer

---

.bazelrc
ci/Dockerfile-envoy

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.27] Update distroless image (and fix macos CI)

---

source/extensions/stat_sinks/metrics_service/grpc_metrics_service_impl.cc
test/extensions/stats_sinks/metrics_service/grpc_metrics_service_impl_test.cc

Commit Message: missed this on https://github.com/envoyproxy/envoy/pull/25812
Risk Level:
Testing:
Docs Changes:
Release Notes:

metrics_service: populate histogram summary sample sum

---

api/envoy/extensions/filters/http/jwt_authn/v3/config.proto

Commit Message: docs: render extensions.filters.http.jwt_authn.v3.JwtProvider#claim_to_headers yaml example
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: render extensions.filters.http.jwt_authn.v3.JwtProvider#claim_to_headers yaml example

---

source/common/http/utility.cc
source/common/http/utility.h
source/extensions/filters/http/gcp_authn/filter_config.cc
source/extensions/filters/http/jwt_authn/jwks_cache.cc
test/common/http/utility_test.cc
tools/code_format/config.yaml

http: moving http utilities to use statusor

---

.bazelrc

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/ci: Add `--nolegacy_important_outputs`

---

source/extensions/stat_sinks/metrics_service/grpc_metrics_service_impl.cc
test/extensions/stats_sinks/metrics_service/grpc_metrics_service_impl_test.cc

backport of https://github.com/envoyproxy/envoy/pull/32666
Risk Level:
Testing:
Docs Changes:
Release Notes:

 metrics_service: populate histogram summary sample sum v1.26

---

source/extensions/stat_sinks/metrics_service/grpc_metrics_service_impl.cc
test/extensions/stats_sinks/metrics_service/grpc_metrics_service_impl_test.cc

backport of #32666
Risk Level:
Testing:
Docs Changes:
Release Notes:

metrics_service: populate histogram summary sample sum v1.27

---

source/extensions/stat_sinks/metrics_service/grpc_metrics_service_impl.cc
test/extensions/stats_sinks/metrics_service/grpc_metrics_service_impl_test.cc

backport of #32666
Risk Level:
Testing:
Docs Changes:
Release Notes:

metrics_service: populate histogram summary sample sum v1.29

---

docs/root/configuration/http/http_conn_man/route_matching.rst

Commit Message: Add matcher to route documentation.
Testing: n/a
Docs Changes: Yes it is.

Add matcher to route documentation

---

.bazelrc

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.28] ci/macos: Use Engflow for bazel cache

---

.bazelrc

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.26] ci/macos: Use Engflow for bazel cache (#32520)

---

source/common/quic/quic_server_transport_socket_factory.cc
source/extensions/config_subscription/rest/http_subscription_impl.cc

removing a few throwEnvoyExceptionOrPanic not needed by E-M
Risk Level:
Testing:
Docs Changes:
Release Notes:

envoy: reverting unnecessary E-M macro

---

CODEOWNERS

Add fredyw as mobile CODEOWNERS

---

source/common/router/config_impl.cc
source/common/router/router_ratelimit.cc
source/common/router/router_ratelimit.h
test/common/router/router_ratelimit_test.cc
test/extensions/rate_limit_descriptors/expr/config_test.cc
tools/code_format/config.yaml

ratelimit: switching to statusor

---

envoy/runtime/runtime.h
source/common/runtime/runtime_impl.cc
source/common/runtime/runtime_impl.h
source/server/admin/runtime_handler.cc
source/server/server.cc
test/common/runtime/runtime_impl_test.cc
test/common/stats/thread_local_store_test.cc
test/extensions/filters/network/http_connection_manager/config_test.cc
test/mocks/runtime/mocks.h
test/test_common/test_runtime.h
tools/code_format/config.yaml

runtime: removing most of the exceptions

---

tools/repo/notify.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

tools: hopefully fix repo notifier

---

test/per_file_coverage.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

test: bumping coverage

---

tools/repo/notify.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

tools: fixing typo

---

tools/repo/notify.py

Updating per (https://api.slack.com/reference/surfaces/formatting#mentioning-users)

tooling: hopefully improving mention

---

source/common/common/posix/thread_impl.cc
test/common/common/thread_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

mac: fix PosixThread test

---

test/integration/protocol_integration_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

test: improving bad header testing

---

mobile/bazel/EnvoyMobileTestSuite.kt
mobile/test/java/integration/AndroidEngineSocketTagTest.java
mobile/test/java/integration/AndroidEnvoyEngineStartUpTest.java
mobile/test/java/integration/AndroidEnvoyExplicitFlowTest.java
mobile/test/java/integration/AndroidEnvoyFlowTest.java

This PR fixes the Java package name to match the directory structure.
Testing: bazel test

mobile: Fix Java package name

---

test/integration/fake_upstream.cc

fixes https://github.com/envoyproxy/envoy/issues/32424

test: fixing a slow tst

---

test/common/router/route_corpus/testcase-6001880544444416

Adding corpus that was problematic for internal runs.

Add fuzz corpus with empty config

---

test/extensions/http/header_validators/envoy_default/http1_header_validator_test.cc

Commit Message: minor variable rename
Testing: N/A

minor variable rename

---

bazel/external/boringssl_fips.genrule_cmd

Risk Level:
Testing:
Docs Changes:
Release Notes:

fips/build: Add `-fPIC`

---

.github/workflows/mobile-perf.yml
source/server/BUILD
source/server/configuration_impl.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

 logs: removing a hard linkage on file based access logs

---

tools/repo/notify.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: envoy-ci ping

---

envoy/common/exception.h

Breaks usage in proprietary extensions.

Make macro work outside of the Envoy namespace

---

envoy/filesystem/watcher.h
source/common/config/watched_directory.cc
source/common/filesystem/inotify/watcher_impl.cc
source/common/filesystem/inotify/watcher_impl.h
source/common/filesystem/kqueue/watcher_impl.cc
source/common/filesystem/kqueue/watcher_impl.h
source/common/filesystem/win32/watcher_impl.cc
source/common/filesystem/win32/watcher_impl.h
source/common/runtime/runtime_impl.cc
source/common/secret/sds_api.cc
source/extensions/compression/zstd/common/dictionary_manager.h
source/extensions/config_subscription/filesystem/filesystem_subscription_impl.cc
source/extensions/resource_monitors/injected_resource/injected_resource_monitor.cc
test/common/config/watched_directory_test.cc
test/common/filesystem/watcher_impl_test.cc
test/common/runtime/runtime_impl_test.cc
test/common/secret/sds_api_test.cc
test/extensions/compression/zstd/zstd_compression_test.cc
test/extensions/config_subscription/filesystem/filesystem_subscription_impl_test.cc
test/extensions/config_subscription/filesystem/filesystem_subscription_test_harness.h
test/mocks/filesystem/mocks.h
tools/code_format/config.yaml

filesystem: move addWatch to statusor

---

test/integration/http_protocol_integration.cc

Commit Message: Reduce the number of permutations to reduce resources required to build in CI
Risk Level:
Testing:
Docs Changes:
Release Notes:

tests: reduce integration test http permutations

---

.github/config.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: triggering mobile ci on mobile .bazelrc changes

---

source/server/config_validation/server.cc
source/server/server.cc
source/server/server.h
test/config_test/config_test.cc

server: removing a few more exceptions

---

.github/workflows/envoy-macos.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/macos: Increase runner timeout

---

.github/workflows/mobile-ios_build.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/ios: Increase action timeouts

---

envoy/filesystem/watcher.h
source/common/config/watched_directory.cc
source/common/config/watched_directory.h
source/common/filesystem/inotify/watcher_impl.cc
source/common/filesystem/kqueue/watcher_impl.cc
source/common/runtime/runtime_impl.cc
source/common/secret/sds_api.cc
source/extensions/compression/zstd/common/dictionary_manager.h
source/extensions/config_subscription/filesystem/filesystem_subscription_impl.cc
source/extensions/resource_monitors/injected_resource/injected_resource_monitor.cc
test/common/config/watched_directory_test.cc
test/common/filesystem/watcher_impl_test.cc
test/common/runtime/runtime_impl_test.cc
test/common/secret/sds_api_test.cc
test/extensions/compression/zstd/zstd_compression_test.cc
test/extensions/config_subscription/filesystem/filesystem_subscription_impl_test.cc
test/extensions/config_subscription/filesystem/filesystem_subscription_test_harness.h
tools/code_format/config.yaml

runtime: removing exceptions

---

.github/workflows/_mobile_container_ci.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/mobile: Fix container CI timeouts

---

ci/README.md

Commit Message: Update the CI README.md for the bazel remote cache setup
Testing: N/A
Docs Changes: ci/README.md
Fixes Issues: https://github.com/envoyproxy/envoy/issues/32989

Update CI README.md for the bazel remote cache setup

---

contrib/generic_proxy/filters/network/source/match.cc
contrib/rocketmq_proxy/filters/network/source/router/route_matcher.h
source/common/common/matchers.cc
source/common/common/matchers.h
source/common/http/header_utility.cc
source/common/matcher/value_input_matcher.h
source/common/router/config_impl.h
source/common/router/config_utility.cc
source/common/router/config_utility.h
source/common/stats/histogram_impl.cc
source/common/stats/histogram_impl.h
source/common/stats/stats_matcher_impl.cc
source/common/stats/stats_matcher_impl.h
source/common/tls/cert_validator/san_matcher.h
source/extensions/common/aws/signer_base_impl.h
source/extensions/filters/common/ext_authz/check_request_utils.cc
source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc
source/extensions/filters/common/rbac/matchers.h
source/extensions/filters/http/cache/cache_headers_utils.cc
source/extensions/filters/http/csrf/csrf_filter.h
source/extensions/filters/http/ext_proc/matching_utils.cc
source/extensions/filters/http/jwt_authn/jwks_cache.cc
source/extensions/filters/network/dubbo_proxy/router/route_matcher.h
source/extensions/health_checkers/http/health_checker_impl.h
test/common/common/matchers_test.cc
test/extensions/common/aws/utility_test.cc
test/extensions/filters/http/cache/cache_headers_utils_test.cc
test/extensions/filters/http/cors/cors_filter_test.cc
test/extensions/filters/http/ext_proc/mutation_utils_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

Stringmatcher: rename StringMatcherImplWithContext to StringMatcherImpl

---

mobile/.bazelrc

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: defaulting xDS off

---

test/integration/filters/backpressure_filter.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

backpressure_filter: Correct the filter description

---

mobile/.bazelrc

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: switching all builds to using the no-op genproto

---

envoy/ssl/BUILD
envoy/ssl/handshaker.h
source/common/tls/context_config_impl.cc
source/common/tls/context_config_impl.h
source/common/tls/ssl_handshaker.h
test/common/tls/handshaker_factory_test.cc
test/mocks/server/transport_socket_factory_context.cc
test/mocks/server/transport_socket_factory_context.h

Plumb the server lifecycle notifier to the HandshakerFactoryContext
Testing:
Docs Changes:
Release Notes:

Plumb the server lifecycle notifier to the HandshakerFactoryContext

---

source/common/tcp_proxy/tcp_proxy.cc
source/common/tcp_proxy/tcp_proxy.h

Fix forward broken main

---

.github/workflows/mobile-release.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/ci: Prevent release from running in non-envoy repos

---

source/common/filter/config_discovery_impl.cc
source/common/filter/config_discovery_impl.h

exceptions: making config_discovery_impl.cc exception free

---

mobile/test/cc/unit/envoy_config_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: fix ci permafail

---

source/common/http/match_delegate/config.cc
source/common/http/match_delegate/config.h
test/common/http/match_delegate/config_test.cc
tools/code_format/config.yaml

match delegate: making exception free

---

test/common/config/utility_test.cc
test/common/network/resolver_impl_test.cc
test/common/protobuf/utility_test.cc
test/common/router/config_impl_test.cc

DebugString output is changing in the upcoming protobuf release. This change adjusts the tests that would be affected.

Make tests less reliant on DebugString implementation

---

mobile/library/common/internal_engine.cc
mobile/library/common/internal_engine.h

mobile: Move some InternalEngine implementation from .h to .cc

---

test/common/access_log/access_log_manager_impl_test.cc

Tests that do not check returned AssertionResult value would pass whether assertion is successful or not, creating potential false positives.
Risk Level:
Testing:
Docs Changes:
Release Notes:

Ensure verification methods that return AssertionResult use the return value

---

bazel/repository_locations.bzl

xref: https://github.com/envoyproxy/envoy/actions/runs/8494850712/job/23270504800

chore: fix precheck

---

bazel/repositories.bzl
bazel/rules_foreign_cc.patch

Commit Message: fix build issue on m1
Additional Description: related to https://gitlab.freedesktop.org/pkg-config/pkg-config/-/issues/81
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #33225

ci: fix build issue on m1

---

envoy/server/overload/load_shed_point.h

Testing:
Docs Changes:
Release Notes:

LSP: clarify codec creation checking point 

---

mobile/test/kotlin/integration/SendDataTest.kt

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: fixing a noyaml test

---

tools/repo/notify.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

oncall: handle begining of month

---

.azure-pipelines/stage/checks.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/azp: Use free runners for checks

---

CODEOWNERS

As discussed with @alyssawilk offline, I am happy to be code owner from Google side, I have designed/reviewed PR https://github.com/envoyproxy/envoy/pull/27088 and contributed some other PRs(#26735, #27621)

match_delegate: add owner

---

bazel/foreign_cc/nghttp2.patch
changelogs/current.yaml
source/common/http/http2/codec_impl.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.26] deps/CVE: Fix (nghttp2) CVE-2024-30255

---

bazel/foreign_cc/nghttp2.patch
changelogs/current.yaml
source/common/http/http2/codec_impl.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

 [bp/1.27] deps/CVE: Fix (nghttp2) CVE-2024-30255

---

bazel/foreign_cc/nghttp2.patch
changelogs/current.yaml
source/common/http/http2/codec_impl.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.28] deps/CVE: Fix (nghttp2) CVE-2024-30255

---

mobile/test/cc/engine_test.cc

Fix ctad-maybe-unsupported error for internal builds

---

.azure-pipelines/ci.yml
.azure-pipelines/stage/checks.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/azp: Set path for cache save

---

mobile/.bazelrc
mobile/library/cc/engine_builder.cc
mobile/test/common/extensions/retry/options/network_configuration/predicate_test.cc
mobile/test/common/http/filters/assertion/assertion_filter_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

 mobile: moving linux builds to not full proto

---

source/common/tcp_proxy/upstream.h

Allow request cleanup to access headers

---

mobile/test/common/internal_engine_test.cc

Fix ifdef directive

---

source/common/ssl/tls_certificate_config_impl.cc
source/common/ssl/tls_certificate_config_impl.h
source/common/tls/context_config_impl.cc
source/common/tls/context_config_impl.h
test/common/secret/sds_api_test.cc
test/common/secret/secret_manager_impl_test.cc
tools/code_format/config.yaml

tls: making tls_certificate_config_impl exception freee

---

source/common/formatter/http_specific_formatter.cc
source/common/formatter/stream_info_formatter.h
source/common/formatter/substitution_format_utility.cc
source/common/formatter/substitution_format_utility.h
test/common/formatter/substitution_formatter_test.cc
tools/code_format/config.yaml

substitution_format_utility: exception free

---

.github/workflows/mobile-perf.yml
mobile/test/performance/files_em_does_not_use

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: moving file checks to their own file

---

.github/workflows/mobile-perf.yml
mobile/test/performance/files_em_does_not_use

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/mobile: Fix perf source script

---

docs/root/_include/ssl_stats.rst
test/common/tcp/async_tcp_client_impl_test.cc

Testing:
Docs Changes:
Release Notes:

docs: fix ssl and async client typo

---

source/common/protobuf/utility.cc
source/common/protobuf/visitor.cc
source/common/protobuf/visitor.h
source/common/protobuf/visitor_helper.h
test/fuzz/mutable_visitor.cc
tools/code_format/config.yaml

proto: moving visitor functions to statusor

---

source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc
source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.h

backport DFP: move CM callbacks to thread local objects (#33303)

backport to rel1.29: DFP - move CM callbacks to thread local objects (#33303)

---

source/common/listener_manager/lds_api.cc
source/common/listener_manager/listener_impl.cc

Risk Level: n/a - only affects E-M test builds
Testing: tested manually locally - @fredyw has an upcoming PR that will use it for E-M CI

envoy: allowing listener to build with lite protos

---

envoy/protobuf/message_validator.h
source/common/protobuf/message_validator_impl.cc
source/common/protobuf/message_validator_impl.h
source/common/protobuf/utility.cc
source/common/protobuf/yaml_utility.cc
source/extensions/config_subscription/filesystem/filesystem_subscription_impl.cc
source/extensions/filters/udp/dns_filter/dns_filter.cc
test/common/protobuf/message_validator_impl_test.cc
test/extensions/filters/network/zookeeper_proxy/config_test.cc
test/mocks/protobuf/mocks.h
test/server/server_test.cc
test/tools/schema_validator/validator.cc
tools/code_format/config.yaml

validator: removing exceptions

---

RELEASES.md

don't want to be a nit picker, just saw and fix it ;-)
Risk Level:
Testing:
Docs Changes:
Release Notes:

release: change release note

---

.bazelrc
ci/build_setup.sh
ci/do_ci.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

bazel: Shift GCC flags to .bazelrc

---

contrib/all_contrib_extensions.bzl
contrib/exe/BUILD

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.29] Contrib builds actually excluding skipped targets (#31910)

---

.bazelrc
ci/build_setup.sh
ci/do_ci.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

bazel/clang: Cleanup arg mangler

---

changelogs/summary.md

Commit Message: Creating the summary file for v 1.30

docs: updating summary for v1.30

---

test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.30] ext_authz test deflaking

---

api/contrib/envoy/extensions/filters/network/generic_proxy/action/v3/action.proto

Commit Message: generic proxy router api and timeout field
Testing:
Docs Changes:
Release Notes:

generic proxy router api add timeout field

---

changelogs/summary.md

Risk Level:
Testing:
Docs Changes:
Release Notes:

[release/1.29] changelog: Add summary

---

changelogs/summary.md

Risk Level:
Testing:
Docs Changes:
Release Notes:

[release/1.30] changelog: Add summary

---

mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.h
source/common/tls/cert_validator/cert_validator.h
source/common/tls/cert_validator/default_validator.cc
source/common/tls/cert_validator/default_validator.h
source/common/tls/context_impl.cc
source/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator.cc
source/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator.h
test/common/tls/cert_validator/default_validator_test.cc
test/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator_test.cc

tls: moving cert validation to statusor

---

contrib/generic_proxy/filters/network/source/interface/route.h
contrib/generic_proxy/filters/network/source/route.cc
contrib/generic_proxy/filters/network/source/route.h
contrib/generic_proxy/filters/network/test/mocks/route.cc
contrib/generic_proxy/filters/network/test/mocks/route.h
contrib/generic_proxy/filters/network/test/route_test.cc

Commit Message: add timeout to route entry
Risk Level:
Testing:
Docs Changes:
Release Notes:

generic proxy: add timeout to route entry

---

changelogs/current.yaml
source/common/http/utility.cc
source/common/runtime/runtime_features.cc
test/common/http/utility_test.cc

Testing: n/a
fixes https://github.com/envoyproxy/envoy/issues/33619

runtime: deprecate envoy.reloadable_features.handle_uppercase_scheme

---

source/common/matcher/field_matcher.h
source/common/matcher/matcher.h
test/common/matcher/field_matcher_test.cc
test/common/matcher/test_utility.h
tools/code_format/config.yaml

field matcher: removing exceptions

---

source/common/tls/context_impl.cc
source/common/tls/ocsp/ocsp.cc
source/common/tls/ocsp/ocsp.h
test/common/tls/ocsp/ocsp_test.cc
tools/code_format/config.yaml

Ocsp: removing most exceptions

---

api/envoy/extensions/wasm/v3/wasm.proto

Commit Message: docs: improves language in comment that is present in the official documentation.
Additional Description: This is a minor typo that I stumbled across in the docs. I adjusted the sentenced to read a bit smoother.
Testing: 
Docs Changes: yes, generated
Release Notes: Minor grammatical fix

Fix typo found in documentation

---

test/common/io/BUILD
test/common/io/io_uring_impl_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.30] `io_uring` fix

---

test/common/io/BUILD
test/common/io/io_uring_impl_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.29] `io_uring` fix

---

test/common/io/BUILD
test/common/io/io_uring_impl_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.28] `io_uring` fix

---

docs/root/configuration/http/http_filters/json_to_metadata_filter.rst

Given we have #29460, doc should address the responses part
Testing: n/a

json_to_metadata: fix doc for responses

---

source/extensions/filters/network/http_connection_manager/config.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

Hcm: removing a throw-or-panic

---

CODEOWNERS

Add @adisuissa as an owner of stateful_session HTTP filter

---

envoy/registry/registry.h
mobile/test/common/integration/BUILD
mobile/test/common/integration/client_integration_test.cc
source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc
source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.h
test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
test/extensions/filters/http/dynamic_forward_proxy/test_resolver.cc
test/extensions/filters/http/dynamic_forward_proxy/test_resolver.h
test/test_common/registry.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: more DNS testing

---

tools/base/envoy_python.bzl

Risk Level:
Testing:
Docs Changes:
Release Notes:

tools/python: Fix namespacing for external use

---

source/common/protobuf/utility.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

Fix typo of comment

---

mobile/library/cc/engine_builder.cc
mobile/test/common/integration/base_client_integration_test.cc
mobile/test/common/integration/base_client_integration_test.h
mobile/test/common/integration/client_integration_test.cc
mobile/test/common/internal_engine_test.cc
test/extensions/filters/http/dynamic_forward_proxy/test_resolver.h

"unfortunately" I think this is WAI :-/

mobile: testing drain on reresolve

---

source/common/filesystem/kqueue/watcher_impl.cc
source/common/filesystem/kqueue/watcher_impl.h
test/server/drain_manager_impl_test.cc

filesystem: removing an exception

---

mobile/library/cc/stream.cc
mobile/library/cc/stream.h

mobile: Remove the deprecated Stream::sendData and Stream::close

---

envoy/upstream/load_balancer.h
source/common/upstream/cluster_manager_impl.cc
source/extensions/clusters/aggregate/cluster.h
source/extensions/clusters/dynamic_forward_proxy/cluster.h
source/extensions/clusters/original_dst/original_dst_cluster.h
source/extensions/clusters/redis/redis_cluster_lb.h
source/extensions/load_balancing_policies/common/factory_base.h
source/extensions/load_balancing_policies/common/thread_aware_lb_impl.cc
source/extensions/load_balancing_policies/common/thread_aware_lb_impl.h
source/extensions/load_balancing_policies/subset/config.cc
source/extensions/load_balancing_policies/subset/subset_lb.cc
test/common/upstream/load_balancer_benchmark.cc
test/extensions/clusters/redis/redis_cluster_lb_test.cc
test/extensions/load_balancing_policies/least_request/config_test.cc
test/extensions/load_balancing_policies/maglev/config_test.cc
test/extensions/load_balancing_policies/maglev/maglev_lb_test.cc
test/extensions/load_balancing_policies/random/config_test.cc
test/extensions/load_balancing_policies/ring_hash/config_test.cc
test/extensions/load_balancing_policies/ring_hash/ring_hash_lb_test.cc
test/extensions/load_balancing_policies/round_robin/config_test.cc
test/extensions/load_balancing_policies/subset/config_test.cc
test/integration/load_balancers/custom_lb_policy.h
test/mocks/upstream/thread_aware_load_balancer.h
tools/code_format/config.yaml

load balancers: removing exceptions from thread aware LB

---

.bazelrc

Fixes #33225
Risk Level:
Testing:
Docs Changes:
Release Notes:

build: fix macOS build with most recent toolchain

---

test/common/router/config_impl_test.cc
test/common/tls/BUILD
test/common/tls/handshaker_factory_test.cc
test/extensions/filters/http/geoip/BUILD
test/extensions/filters/http/geoip/geoip_filter_test.cc
test/server/BUILD
test/server/overload_manager_impl_test.cc

Change-Id: I1e585541b28e2ebca54ec6135616cdd2ff081d2a
Commit Message: flip flag to the expected default in more tests

tests: disable more extension lookup by name

---

mobile/library/common/extensions/filters/http/network_configuration/filter.cc

mobile: Fix the debug log message in the network configuration filter

---

source/extensions/network/dns_resolver/cares/dns_impl.cc
test/extensions/network/dns_resolver/cares/dns_impl_test.cc

forward fixing so https://github.com/envoyproxy/envoy/issues/34114 doesn't break CI

cares: handling no-exception build

---

envoy/config/dynamic_extension_config_provider.h
source/common/filter/config_discovery_impl.cc
source/common/filter/config_discovery_impl.h

discovery: removing some exceptions

---

source/common/common/logger.h
source/extensions/stat_sinks/metrics_service/grpc_metrics_service_impl.cc
source/extensions/stat_sinks/metrics_service/grpc_metrics_service_impl.h

Commit Message: add debug logs to metrics service
Additional Description: add debug logs to metrics service
Testing: N/A

add debug logs to metrics service

---

.github/workflows/pr_notifier.yml
BUILD
reviewers.yaml
tools/repo/BUILD
tools/repo/notify.py

This consolidates the currently repeated reviewer data into a config file which can then be used anywhere that requires this info
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Add reviewers config

---

mobile/test/common/integration/client_integration_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: fix apple c++ ci

---

source/common/tls/ocsp/asn1_utility.cc
source/common/tls/ocsp/asn1_utility.h
source/common/tls/ocsp/ocsp.cc
test/common/tls/ocsp/asn1_utility_test.cc
tools/code_format/config.yaml

ocsp: removing the rest of exceptions

---

source/extensions/upstreams/http/config.cc
source/extensions/upstreams/http/config.h
test/extensions/upstreams/http/config_test.cc

upstream: exception free

---

contrib/generic_proxy/filters/network/source/codecs/http1/config.cc
contrib/generic_proxy/filters/network/source/proxy.cc
contrib/generic_proxy/filters/network/test/codecs/dubbo/config_test.cc
contrib/generic_proxy/filters/network/test/codecs/kafka/config_test.cc
contrib/generic_proxy/filters/network/test/route_test.cc
envoy/stats/stats.h
mobile/envoy_build_config/extension_registry.cc
mobile/test/common/internal_engine_test.cc

Fix this by running ` tools/local_fix_format.sh -main`
Testing:
Docs Changes:
Release Notes:

pedantic correction on contrib and mobile

---

.azure-pipelines/pipelines.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

[1.29] ci/azp: Run build stage immediately

---

tools/code_format/config.yaml

Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: cleaning up exception free files

---

test/extensions/filters/common/expr/evaluator_test.cc
test/extensions/transport_sockets/internal_upstream/internal_upstream_test.cc

Commit Message: tests: upgrading tests to work with future protobuf upgrade
Modifying tests to support future protobuf debug changes.
Testing: N/A

tests: upgrading tests to work with future protobuf upgrade

---

examples/grpc-bridge/client/requirements.in
examples/grpc-bridge/client/requirements.txt
tools/base/requirements.in
tools/base/requirements.txt

Risk Level:
Testing:
Docs Changes:
Release Notes:

[1.30] ci/tooling/examples: Update vulnerable deps

---

changelogs/current.yaml
source/common/quic/envoy_quic_utils.cc

Commit Message: add quic tag to quic sockets to help with debugging
Testing: n/a
Release Notes: changelogs/current.yaml

[quic]add quic info to quic sockets

---

test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc

turns out several dfp tests don't use the dynamic proxy cluster so also don't use the dfp filter.

Dfp: cleaning up e2e test

---

source/extensions/filters/http/json_to_metadata/filter.cc

fix wrong semantic after we introduce response processing
Risk Level:
Testing:
Docs Changes:
Release Notes:

rename variables in json_to_metadata filter

---

mobile/test/java/integration/AndroidEngineExplicitFlowTest.java

Related to https://github.com/envoyproxy/envoy/issues/34288
Testing: n/a

mobile: Temporarily ignore AndroidEngineExplicitFlowTest#post_simple

---

mobile/examples/java/hello_world/README.md
mobile/examples/kotlin/hello_world/README.md
mobile/test/kotlin/apps/baseline/README md
mobile/test/kotlin/apps/experimental/README.md

mobile: Fix the READMEs about running local Android test apps

---

contrib/golang/filters/http/source/go/pkg/http/filter.go

Commit Message: golang: don't log client cancellation as error
Testing: Pass existing tests
Docs Changes:
Release Notes:

golang: don't log client cancellation as error

---

docs/root/configuration/other_protocols/thrift_filters/payload_to_metadata_filter.rst

make the referred filter name small case in payload_to_metadata_filter

---

source/common/config/xds_resource.cc
source/common/config/xds_resource.h
source/common/router/scoped_rds.cc
source/common/upstream/cluster_manager_impl.cc
source/extensions/clusters/eds/leds.cc
source/extensions/filters/http/on_demand/on_demand_update.cc
source/server/server.cc
test/common/config/xds_resource_test.cc
test/common/upstream/cluster_manager_impl_test.cc
test/extensions/config_subscription/common/subscription_factory_impl_test.cc
test/extensions/filters/http/on_demand/on_demand_filter_test.cc
tools/code_format/config.yaml

decodeUrl: changing to statusor

---

source/common/http/async_client_impl.cc
source/common/http/async_client_impl.h
test/common/http/async_client_impl_test.cc
tools/code_format/config.yaml

async_client: moving to statusor

---

test/per_file_coverage.sh
test/run_envoy_bazel_coverage.sh

removing several covered directories and bumping more
outputting high results when CI passes/
Risk Level:
Testing:
Docs Changes:
Release Notes:

coverage: adding details for passing coverage

---

docs/root/configuration/other_features/dlb.rst

dlb: update doc

---

source/common/config/datasource.cc
source/common/config/datasource.h

Commit Message: datasource: refactor - hide internal method
Small refactor, converting a function to an anonymous namespace function.
Risk Level: low - no change
Testing: N/A

datasource: refactor - hide internal method

---

source/common/common/posix/thread_impl.cc
source/common/common/posix/thread_impl.h
test/common/common/thread_test.cc
test/per_file_coverage.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

posix: testing an error case

---

tools/code_format/check_format.py
tools/code_format/config.yaml

Risk Level:
Testing:
Docs Changes:
Release Notes:

tooling: extending exception checks to extensions

---

bazel/repositories_extra.bzl

Commit Message: Upgraded Python version which supports s390x, ref [here](https://github.com/indygreg/python-build-standalone/releases/tag/20230726)
Additional Description: This helps in completion of build on s390x and envoy binary is generated successfully.
Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Bump `Python` -> 3.11.4 

---

mobile/test/common/internal_engine_test.cc

https://productionresultssa11.blob.core.windows.net/actions-results/20c6bc1d-a543-4566-8758-83d884608a27/workflow-job-run-d2c4c874-8b8b-5fed-920d-f5a0759b8c9b/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-05-30T14%3A53%3A27Z&sig=rgmX5sWOqG3kzirFC8iOVuMGfKcjASTkc2QxhQVAaKU%3D&sp=r&spr=https&sr=b&st=2024-05-30T14%3A43%3A22Z&sv=2021-12-02
Looks like *san wait times can be more like 5s on slow machines.
Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: hopefully reducing test flakes

---

source/extensions/load_balancing_policies/common/load_balancer_impl.cc
source/extensions/load_balancing_policies/common/load_balancer_impl.h

Commit Message: make distributeLoad available under Envoy::Upstream::
Additional Description: This method is useful in customized retryPriority impls, where some priorities have been excluded in priorityload calculation. 
Risk Level: LOW (code move only).
Testing: N/A
Docs Changes:
Release Notes:

make distributeLoad available under Envoy::Upstream::

---

source/common/tls/client_context_impl.cc
source/common/tls/client_context_impl.h
source/common/tls/context_impl.cc
source/common/tls/context_impl.h
source/common/tls/context_manager_impl.cc
source/common/tls/server_context_impl.cc
source/common/tls/server_context_impl.h
test/common/quic/envoy_quic_proof_source_test.cc
test/common/quic/envoy_quic_proof_verifier_test.cc
test/common/tls/context_impl_test.cc
test/common/tls/ssl_socket_test.cc
tools/code_format/config.yaml

tls: removing exceptions

---

mobile/.bazelrc

This is to fix this failure: https://github.com/envoyproxy/envoy/actions/runs/9370761969/job/25798515708#step:8:2281
Testing: CI

mobile: Run tests on IPv4

---

mobile/.bazelrc

mobile: Remove unused Bazel config

---

mobile/test/common/integration/rtds_integration_test.cc

See https://github.com/envoyproxy/envoy/issues/34537

mobile: Temporarily disable RtdsIntegrationTest

---

test/per_file_coverage.sh

this adjustment is required for the recent security patches to land
Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/coverage: Adjust `extensions/tracers`

---

.github/config.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/ci: Remove config for `Mobile/Core`

---

source/common/listener_manager/filter_chain_manager_impl.cc
source/common/network/cidr_range.cc
source/common/network/cidr_range.h
source/common/router/router_ratelimit.cc
source/extensions/common/matcher/trie_matcher.h
source/extensions/filters/common/rbac/matchers.h
source/extensions/filters/common/rbac/matchers/upstream_ip_port.cc
source/extensions/filters/http/ip_tagging/ip_tagging_filter.cc
source/extensions/matching/input_matchers/ip/config.cc
test/common/network/cidr_range_test.cc
test/common/network/lc_trie_speed_test.cc
test/common/network/lc_trie_test.cc
test/extensions/matching/input_matchers/ip/matcher_test.cc

cidr: removing exceptions

---

test/extensions/network/dns_resolver/getaddrinfo/getaddrinfo_test.cc

Hopefully fixes https://github.com/envoyproxy/envoy/issues/34560

dns: hopefully fixing a test flake

---

CODEOWNERS

Commit Message: aws: add nbaws as aws codeowner
Additional Description: @suniltheta 
Testing: N/A

aws: add nbaws as aws codeowner

---

mobile/test/common/integration/rtds_integration_test.cc

Fixes https://github.com/envoyproxy/envoy/issues/34537

mobile: Fix RtdsIntegrationTest

---

mobile/library/common/http/client.cc
mobile/library/java/org/chromium/net/impl/Errors.java
mobile/test/common/http/client_test.cc
mobile/test/java/org/chromium/net/CronetUrlRequestTest.java

mobile: Add protocol info in the error details

---

RELEASES.md

Testing:
Docs Changes:
Release Notes:

sec-release: updated 2024 q2 release

---

docs/root/_static/searchtools.js

Additional Description: By using textContent, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML.
textContent is More Useful Instead of Using InnerText By Using textContent over innerText enhances security by preventing potential vulnerabilities such as Cross-Site Scripting (XSS) attacks. textContent retrieves only the raw text content of an element, avoiding interpretation of HTML tags, thereby reducing the risk of malicious script injection and unintended content disclosure. …

Update searchtools.js DOM text reinterpreted as HTML

---

mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.h
mobile/library/common/extensions/filters/http/platform_bridge/filter.cc
mobile/library/common/http/client.cc
mobile/library/common/http/client.h
mobile/test/common/http/client_test.cc
mobile/test/common/integration/client_integration_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: removing some PANIC calls from Enovy mobile

---

mobile/WORKSPACE
mobile/bazel/envoy_mobile_repositories.bzl

Risk Level: low (not used)
Testing: CI

mobile: Remove Python from Envoy Mobile Bazel files

---

changelogs/current.yaml
source/common/router/BUILD
source/common/router/shadow_writer_impl.cc
test/integration/shadow_policy_integration_test.cc

Testing: new e2e test
fixes https://github.com/envoyproxy/envoy/issues/34596

shadow: fixing hostnames for ipv6 addresses

---

examples/BUILD

This fixes currently broken docs build in the website
Thanks to @zirain for headsup on broken build
Risk Level:
Testing:
Docs Changes:
Release Notes:

examples/docs: Fix external build

---

docs/root/configuration/http/http_filters/local_rate_limit_filter.rst

Commit Message: docs: fix typo issue
Testing: building & verifying locally
Docs Changes: typos

docs: fix typo issue

---

mobile/library/objective-c/EnvoyHTTPStreamImpl.mm

This PR updates the iOS stream callback implementation to remove the need for going through intermediate C wrapper types. This should help to reduce the unnecessary copies.

mobile: Remove intermediate C wrapper types in the iOS callback implementation

---

source/common/tcp_proxy/upstream.cc
source/common/tcp_proxy/upstream.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

tcp_proxy: switching a data type

---

mobile/library/common/bridge/BUILD
mobile/library/common/bridge/utility.cc
mobile/library/common/bridge/utility.h
mobile/library/common/extensions/filters/http/platform_bridge/BUILD
mobile/test/common/bridge/utility_test.cc
mobile/test/common/http/header_utility_test.cc

mobile: Remove unused utilities

---

test/integration/tcp_tunneling_integration_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:
trying to repro https://github.com/envoyproxy/envoy/issues/34055

Tcp proxy: adding a test

---

.bazelrc

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: changing bes values per bazel team advice

---

.bazelrc

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: hopefully getting better test logs

---

test/integration/protocol_integration_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

flow control: adding a test

---

mobile/library/common/http/client.cc
mobile/test/common/http/client_test.cc
mobile/test/java/org/chromium/net/CronetUrlRequestTest.java
source/common/router/router.cc
test/common/router/router_test.cc

Commit Message: Shorten Envoy Mobile error details
Additional Description: This PR also changes , to | for one of the error string.
Testing: n/a

Shorten Envoy Mobile error details

---

.bazelrc

Risk Level:
Testing:
Docs Changes:
Release Notes:

bazel: bumping test log limit

---

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

ext_proc: remove debugging logs

---

source/extensions/filters/http/oauth2/filter.cc

Commit Message: oauth2: minor code cleanup
Minor code cleanup - removing unnecessary temp var.
Testing: N/A

oauth2: minor code cleanup

---

CODEOWNERS

Risk Level:
Testing:
Docs Changes:
Release Notes:

owners: swapping out some entries

---

test/common/memory/memory_release_test.cc

Testing:
Docs Changes:
Release Notes:

memory_release_test: consume TestUtility::waitForCounterEq return value

---

CODEOWNERS

owners: add code owners

---

changelogs/current.yaml
source/server/admin/config_dump_handler.cc
test/server/admin/config_dump_handler_test.cc

Commit Message: Fix missing additional addresses from endpoint config dump
Testing: updated existing unit test to provide coverage
Fixes #34740

Fix missing additional addresses from endpoint config dump

---

.github/workflows/_stage_verify.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

examples/docker: Downgrade Docker to workaround image copy issue

---

examples/websocket/docker-compose.yaml
examples/websocket/envoy-ws-route.yaml
examples/websocket/example.rst
examples/websocket/verify.sh

Commit Message: A new example using the WebSocket protocol on a specific Route has been added to the documentation and example of working with WebSocket.
Testing: A new example for automated testing has been added to the verify.sh script.
Docs Changes: example.rst has been updated

docs: add example with ws route

---

source/extensions/filters/network/connection_limit/connection_limit.cc
test/extensions/filters/network/connection_limit/connection_limit_test.cc

Commit Message: connection_limit: fix connection close without reason
[Optional Fixes #Issue] #26856

connection_limit: fix connection close without reason

---

source/server/admin/admin.cc
test/server/admin/admin_test.cc

The usage is confusing, and add more texts:
Testing:
Docs Changes:
Release Notes:

admin_logging_handler: add more usage info for /logging handler

---

mobile/examples/kotlin/hello_world/MainActivity.kt
mobile/test/kotlin/apps/baseline/MainActivity.kt
mobile/test/kotlin/apps/experimental/MainActivity.kt

mobile: Remove duplicate setLogger call

---

.github/workflows/_stage_verify.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.29] docker fix

---

.github/workflows/_stage_verify.yml
changelogs/current.yaml

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.30] Docker fix and datadog changelog

---

source/common/upstream/cluster_manager_impl.cc

Commit Message: cm: moving exception throwing to absl::Status
Removing a few exception throws from cluster-manager.
Testing: N/A

cm: moving exception throwing to absl::Status

---

source/common/tls/client_ssl_socket.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

ssl socket: allow subclasses

---

source/common/common/random_generator.cc
source/common/common/random_generator.h

Commit Message: random: changes the random() and uuid() to static methods
Testing: n/a.

random: changes the random() and uuid() to static methods

---

changelogs/current.yaml
source/common/http/hash_policy.cc
test/integration/multiplexed_integration_test.cc

---------
Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.30] http: fix cookie attributes (#34885)

---

changelogs/current.yaml
source/common/http/hash_policy.cc
test/integration/multiplexed_integration_test.cc

---------
Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.28] http: fix cookie attributes (#34885)

---

changelogs/current.yaml
source/common/http/hash_policy.cc
test/integration/multiplexed_integration_test.cc

---------
Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.27] http: fix cookie attributes (#34885)

---

changelogs/current.yaml
source/common/http/hash_policy.cc
test/integration/multiplexed_integration_test.cc

---------
Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.29] http: fix cookie attributes (#34885)

---

source/common/quic/envoy_quic_client_stream.cc
source/common/quic/envoy_quic_server_stream.cc
test/integration/http_integration.cc
test/integration/local_reply_integration_test.cc
test/integration/protocol_integration_test.cc

Commit Message: add QUIC connection close detail to transport close details

[QUIC]add QUIC connection close detail to transport close details

---

changelogs/current.yaml

Risk Level:
Testing:
Docs Changes:
Release Notes:

changelogs: Add changelog for Datadog fix

---

envoy/ssl/context.h
mobile/test/performance/files_em_does_not_use
source/common/tls/BUILD
source/common/tls/client_context_impl.h
source/common/tls/context_impl.h
source/common/tls/ocsp/ocsp.cc
source/common/tls/ocsp/ocsp.h
source/common/tls/server_context_impl.cc
test/common/tls/ocsp/ocsp_test.cc

tls: remove ocsp from client classes

---

docs/root/intro/arch_overview/upstream/load_reporting_service.rst

Commit Message: docs: fix LRS example link
Fixing a broken link.
Risk Level: low - docs only
Testing: N/A

docs: fix LRS example link

---

bazel/BUILD
bazel/envoy_build_system.bzl
bazel/envoy_mobile_defines.bzl
bazel/envoy_select.bzl
mobile/.bazelrc
mobile/bazel/envoy_mobile_android_test.bzl
mobile/docs/root/development/performance/binary_size.rst
mobile/envoy_build_config/BUILD
mobile/envoy_build_config/extension_registry.cc
mobile/test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt

A follow-up of https://github.com/envoyproxy/envoy/pull/35017
Risk Level: low (unused)
Testing: CI

mobile: More xDS cleanup

---

mobile/library/cc/engine_builder.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: fixing use_cares

---

mobile/test/common/integration/test_server.cc
test/integration/server.cc
test/integration/server.h

includes a minor Envoy test refactor
prep work for https://github.com/envoyproxy/envoy/pull/35021

mobile: changing proxy tests to use well formed protos

---

ci/README.md

Risk Level:
Testing:
Docs Changes:
Release Notes:

add comments for check_and_fix_proto_format

---

mobile/.bazelrc

mobile: cleaning up CI file

---

mobile/library/common/apple/utility.cc
mobile/library/common/network/apple_pac_proxy_resolver.cc
mobile/library/common/network/apple_system_proxy_settings_monitor.cc
mobile/library/common/network/connectivity_manager.cc
mobile/test/common/apple/BUILD
mobile/test/common/apple/utility_test.cc

And adds unit tests for the Apple utility functions.

mobile: Fixes to the Apple Core Foundation to C++ conversion

---

mobile/library/common/extensions/filters/http/network_configuration/filter.cc

Addresses unresolved comments from https://github.com/envoyproxy/envoy/pull/35140.

mobile: Minor improvements to NetworkConfigurationFilter

---

docs/root/configuration/observability/access_log/usage.rst

Commit Message: looks like this's missed in https://github.com/envoyproxy/envoy/pull/32623, cc @botengyao
Risk Level:
Testing:
Docs Changes:
Release Notes:

accesslog: update docs for DR

---

examples/opentelemetry/Dockerfile-opentelemetry
examples/shared/envoy/Dockerfile
examples/shared/golang/Dockerfile
examples/shared/node/Dockerfile
examples/shared/python/Dockerfile
examples/shared/websocket/Dockerfile

Risk Level:
Testing:
Docs Changes:
Release Notes:

examples: Fix docker recipe casing

---

test/extensions/filters/http/ext_proc/BUILD

Risk Level:
Testing:
Docs Changes:
Release Notes:

ext_proc: Increase the test shard count

---

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

ext_proc: Disable the inactive flaky test

---

changelogs/summary.md

Commit Message: Docs: Updating summary for v1.31

Docs: Updating summary for v1.31

---

ci/Dockerfile-envoy

Risk Level:
Testing:
Docs Changes:
Release Notes:

docker: Fix remaining casing issues

---

test/integration/direct_response_integration_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

fix flaky direct response test in tsan mode

---

.github/workflows/codeql-daily.yml
.github/workflows/codeql-push.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/codeql: Free up more disk space

---

README.md

Commit Message: Adds a releases section to the README.md referencing the RELEASES.md page.
Testing: N/A
Release Notes: Adds a section to the README.md referencing where to find the details about the release schedule and process.
Addresses #35258

Add a Releases section to the README

---

mobile/examples/swift/async_await/ContentView.swift

mobile: Enabling logging in swift-async-await test app

---

api/envoy/config/cluster/v3/cluster.proto

Commit Message: api: pluralize recently added repeated field name
Additional Description: Addresses a post-merge comment from #35210.
Testing: N/A
CC @wbpcode @efimki @AndresGuedez @ejona86 @dfawley @vishalpowar

api: pluralize recently added repeated field name

---

tools/base/requirements.in
tools/base/requirements.txt
tools/distribution/BUILD

Risk Level:
Testing:
Docs Changes:
Release Notes:

deps/py: Update aidocker and remove workaround

---

source/common/listener_manager/filter_chain_manager_impl.cc
source/common/listener_manager/filter_chain_manager_impl.h
source/common/listener_manager/listener_impl.cc
test/common/listener_manager/filter_chain_benchmark_test.cc
test/common/listener_manager/filter_chain_manager_impl_test.cc
tools/code_format/config.yaml

listener: removing exceptions from the filter chain manager

---

examples/golang-http/simple/go.mod
examples/golang-http/simple/go.sum
examples/golang-network/simple/go.mod
examples/golang-network/simple/go.sum

Risk Level:
Testing:
Docs Changes:
Release Notes:

[1.29] examples/golang: Run go mod tidy

---

test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc

Testing: tested with flag manually false

dns: fix a test to work with a default-false flag

---

mobile/bazel/envoy_mobile_repositories.bzl
mobile/bazel/envoy_mobile_toolchains.bzl

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/deps: Bump `rules_detekt` -> 0.8.1.2

---

changelogs/current.yaml

for https://github.com/envoyproxy/envoy/pull/32465#issuecomment-2250994877
Risk Level:
Testing:
Docs Changes:
Release Notes:

doc: add change log for custom_tls_certificate_selector.

---

changelogs/current.yaml
source/common/quic/quic_filter_manager_connection_impl.cc
test/common/quic/quic_filter_manager_connection_impl_test.cc

Testing: added new test
Docs Changes:

quic: fix access log `%CONNECTION_ID%`

---

bazel/repositories.bzl

Risk Level:
Testing:
Docs Changes:
Release Notes:

bazel/protoc: Fix mobile build

---

test/common/http/async_client_impl_test.cc
test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc

Commit Message: remove dead code
Testing:
Docs Changes:
Release Notes:

test: remove dead code

---

examples/golang-http/simple/filter.go

Commit Message: small fix in comment, goroutine DecoderFIlterCallbacks

Update filter.go, small fix in comment

---

test/common/http/http1/codec_impl_test.cc

Commit Message: Add http-parser and BalsaParser tests for "Connection: close".
Additional Description: new tests

Add http-parser and BalsaParser tests for "Connection: close".

---

envoy/common/exception.h
envoy/server/listener_manager.h
source/common/listener_manager/filter_chain_manager_impl.cc
source/common/listener_manager/filter_chain_manager_impl.h
source/common/listener_manager/listener_impl.cc
source/common/listener_manager/listener_manager_impl.cc
source/common/listener_manager/listener_manager_impl.h
source/extensions/listener_managers/validation_listener_manager/validation_listener_manager.h
test/common/listener_manager/filter_chain_benchmark_test.cc
test/common/listener_manager/filter_chain_manager_impl_test.cc
test/common/listener_manager/listener_manager_impl_test.cc
test/common/listener_manager/listener_manager_impl_test.h
test/config_test/config_test.cc
test/extensions/config_subscription/common/subscription_factory_impl_test.cc
test/mocks/server/listener_component_factory.cc
test/mocks/server/listener_component_factory.h
tools/code_format/config.yaml

listener manager: removing exceptions

---

tools/repo/notify.py

Risk Level: n/a (tooling only)
Testing: manually tested link

tools: fixing broken link in PR notifier

---

test/integration/quic_http_integration_test.cc

Fixes #35467
Additional Description: I have been unable to reproduce the failure, so this is my best guess at what could be going wrong, given the available data.
Risk Level:
Testing:
Docs Changes:
Release Notes:

quic: fix test flake

---

source/common/config/utility.h
source/common/filter/config_discovery_impl.h
source/common/http/filter_chain_helper.h
source/common/listener_manager/listener_manager_impl.cc
test/extensions/filters/network/http_connection_manager/config_filter_chain_test.cc

utility: removing some exceptions

---

api/bazel/repositories.bzl
api/bazel/repository_locations.bzl
bazel/repositories.bzl
bazel/repositories_extra.bzl
bazel/repository_locations.bzl
source/extensions/transport_sockets/alts/BUILD

Risk Level:
Testing:
Docs Changes:
Release Notes:

deps: Remove duplicated rules_proto_grpc dep

---

envoy/http/http_server_properties_cache.h
mobile/library/common/internal_engine.cc
mobile/library/common/internal_engine.h
source/common/http/http_server_properties_cache_impl.cc
source/common/http/http_server_properties_cache_impl.h
source/common/http/http_server_properties_cache_manager_impl.cc
source/common/http/http_server_properties_cache_manager_impl.h
source/common/runtime/runtime_features.cc
test/common/http/http_server_properties_cache_impl_test.cc
test/common/http/http_server_properties_cache_manager_test.cc
test/mocks/http/http_server_properties_cache.h

Risk Level: low (new functions for Envoy)

http/3: allow refreshing brokenness

---

source/common/http/http2/codec_impl.cc

Commit Message: downgrade http2visitor logs to trace
Additional Description: in debug mode, these logs create lot of noise
Testing:
Docs Changes:
Release Notes:

downgrade http2visitor logs to trace

---

.github/workflows/_stage_verify.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci/verify: Fix failing ubuntu downgrade

---

mobile/test/performance/files_em_does_not_use

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: updating files

---

.azure-pipelines/ci.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

ci: Remove failing Docker cleanup

---

mobile/library/common/http/header_utility.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: direct response cleanup

---

.github/workflows/mobile-perf.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile/ci: Minor fix for download paths

---

README.md

Adding s390x CI build status
Signed-off-by: namrata-ibm <Namrata.Bhave@ibm.com>
Additional Description: Fixes #35518 
Risk Level:
Testing:
Docs Changes:
Release Notes:

Add s390x CI build status

---

source/extensions/filters/http/rate_limit_quota/filter.cc

Testing: 
Docs Changes:
Release Notes:

rate_limit: statusor to avoid potential template argument deduction

---

ci/build_setup.sh
ci/do_ci.sh

Commit Message: tools/ci: minor optimization to the ci scripts for macos
Testing: n/a.

tools/ci: minor optimization to the ci scripts for macos

---

STYLE.md

Commit Message: style-guide: update testing links
minor update to some links in the style guide.
Testing: N/A

style-guide: update testing links

---

bazel/sh_test_wrapper.sh
ci/build_setup.sh
ci/do_ci.sh
ci/envoy_build_sha.sh
ci/run_envoy_docker.sh
mobile/bazelw
mobile/remote
mobile/tools/check_format.sh
test/common/tls/ocsp/test_data/certs.sh
test/common/tls/test_data/certs.sh
test/extensions/filters/network/thrift_proxy/driver/generate_bindings.sh
tools/bazel-test-docker.sh
tools/debugging/run-valgrind.sh
tools/git/modified_since_last_github_commit.sh
tools/vscode/refresh_compdb.sh

Commit Message: use bash source rather than dirname $0
Testing: n/a.

use bash source rather than dirname $0

---

bazel/repositories.bzl
source/exe/BUILD
test/config_test/BUILD

Fix the NO_HTTP3_SKIP_TARGETS variable

Fix the NO_HTTP3_SKIP_TARGETS variable

---

repokitteh.star
source/docs/repokitteh.md

Commit Message: Add /nostalebot repokitteh option
Additional Description: This will reduce user toil and maintainer load.
Testing: NA

Add /nostalebot repokitteh option

---

test/per_file_coverage.sh

Risk Level:
Testing:
Docs Changes:
Release Notes:

test/coverage: Reduce quic to fix fail

---

docs/root/configuration/http/http_conn_man/stats.rst

Commit Message: Docs: add doc premature reset stat.
Additional Description: Was missed in https://github.com/envoyproxy/envoy/commit/230331f9bd4ec8d2ca25ae104436fcab3747985b
Testing: low

Docs: add doc premature reset stat.

---

source/extensions/filters/http/rate_limit_quota/client_impl.cc
source/extensions/filters/http/rate_limit_quota/filter.cc
source/extensions/filters/http/rate_limit_quota/filter.h
source/extensions/filters/http/rate_limit_quota/quota_bucket_cache.h
test/extensions/filters/http/rate_limit_quota/integration_test.cc

Reverts envoyproxy/envoy#35723

Revert "RLQS: Refactor traffic processing in the RLQS filter & fix a broken expiration check"

---

mobile/test/common/integration/test_server.cc
mobile/test/java/io/envoyproxy/envoymobile/engine/testing/HttpProxyTestServerFactory.java
mobile/test/jni/BUILD
mobile/test/jni/jni_http_proxy_test_server_factory.cc
mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestUsingAsyncProxyTest.kt
mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestUsingProxyTest.kt

Fixes https://github.com/envoyproxy/envoy/issues/33014

mobile: Fix HTTPS proxy Android tests

---

.github/workflows/_publish_build.yml
.github/workflows/envoy-publish.yml

release/ci: Fix Dockerhub publishing

---

mobile/.bazelrc

Risk Level: low (unused configs)
Testing: CI

mobile: Clean up unused .bazelrc configurations

---

api/envoy/extensions/transport_sockets/http_11_proxy/v3/upstream_http_11_connect.proto

Add clarifications to the proto documentation.

docs: Clarify docs for Http11ProxyUpstreamTransport

---

source/common/json/BUILD
source/common/json/json_internal.cc
source/common/json/json_sanitizer.cc
test/common/json/json_sanitizer_fuzz_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

json: drop exceptions from the json sanitizer

---

api/envoy/extensions/filters/udp/udp_proxy/v3/BUILD
api/envoy/extensions/filters/udp/udp_proxy/v3/udp_proxy.proto
api/envoy/service/extension/v3/config_discovery.proto
changelogs/current.yaml
docs/root/configuration/listeners/udp_filters/udp_proxy.rst
docs/root/configuration/overview/extension.rst
envoy/network/filter.h
source/extensions/filters/udp/udp_proxy/config.cc
source/extensions/filters/udp/udp_proxy/config.h
source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc
source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h
test/extensions/filters/udp/udp_proxy/BUILD
test/extensions/filters/udp/udp_proxy/session_filters/drainer_filter.proto
test/extensions/filters/udp/udp_proxy/udp_session_extension_discovery_integration_test.cc

Additional Description: Adding support for dynamic extension config with ECDS, for UDP session filters
Testing: unit tests, integration tests

ecds: support dynamic config for UDP session filters

---

envoy/network/listener.h
envoy/server/listener_manager.h
mobile/library/common/extensions/listener_managers/api_listener_manager/api_listener_manager.h
source/common/listener_manager/listener_impl.cc
source/common/listener_manager/listener_impl.h
source/common/listener_manager/listener_manager_impl.cc
source/common/listener_manager/listener_manager_impl.h
source/server/admin/admin.h
source/server/server.cc
test/common/listener_manager/listener_manager_impl_test.cc
test/common/listener_manager/listener_manager_impl_test.h
test/integration/fake_upstream.cc
test/integration/fake_upstream.h
test/mocks/network/mocks.h
test/mocks/server/listener_manager.h
test/server/admin/admin_test.cc

listener: removing some exceptions

---

.github/workflows/envoy-sync.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

repo: Sync openssl project on push to `main` or `release/v1.28/31`

---

.github/workflows/envoy-sync.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

repo/sync: Fix bad workflow condition

---

.github/workflows/_cache.yml
.github/workflows/_finish.yml
.github/workflows/_load.yml
.github/workflows/_load_env.yml
.github/workflows/_publish_publish.yml
.github/workflows/_request.yml
.github/workflows/_run.yml
.github/workflows/_start.yml
.github/workflows/codeql-daily.yml
.github/workflows/codeql-push.yml
.github/workflows/command.yml
.github/workflows/envoy-dependency.yml
.github/workflows/envoy-release.yml
.github/workflows/envoy-sync.yml
.github/workflows/garbage.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.31] gh-actions update

---

mobile/library/cc/engine_builder.cc
mobile/library/cc/engine_builder.h
mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
mobile/library/java/io/envoyproxy/envoymobile/engine/JniBridgeUtility.java
mobile/library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java
mobile/library/java/org/chromium/net/impl/NativeCronvoyEngineBuilderImpl.java
mobile/library/jni/jni_impl.cc
mobile/library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
mobile/test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt

Commit Message: Allow user to specify fallback resolvers when c-ares fails to find resolver hosts from system configs.
Platform Specific Features: android only

[mobile]Configure fallback resolver for cares

---

.azure-pipelines/stages.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

release/ci: Skip build tests on publishing run

---

source/common/config/utility.h
source/common/http/conn_manager_impl.cc

Commit Message: code-cleanup: move static string declaration scope
minor refactor to address internal fuzzers issues.
Testing: N/A

code-cleanup: move static string declaration scope

---

.azure-pipelines/pipelines.yml
.azure-pipelines/stages.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

[bp/1.30] CI stack

---

envoy/network/dns.h
mobile/test/common/network/connectivity_manager_test.cc
source/extensions/clusters/logical_dns/logical_dns_cluster.cc
source/extensions/clusters/redis/redis_cluster.cc
source/extensions/clusters/strict_dns/strict_dns_cluster.cc
source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc
source/extensions/common/wasm/context.cc
source/extensions/filters/udp/dns_filter/dns_filter.cc
source/extensions/filters/udp/dns_filter/dns_filter_resolver.cc
source/extensions/filters/udp/dns_filter/dns_parser.h
source/extensions/network/dns_resolver/apple/apple_dns_impl.cc
source/extensions/network/dns_resolver/apple/apple_dns_impl.h
source/extensions/network/dns_resolver/cares/dns_impl.cc
source/extensions/network/dns_resolver/cares/dns_impl.h
source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc
test/common/upstream/cluster_manager_impl_test.cc
test/common/upstream/upstream_impl_test.cc
test/extensions/clusters/common/logical_host_integration_test.cc
test/extensions/clusters/logical_dns/logical_dns_cluster_test.cc
test/extensions/clusters/redis/redis_cluster_test.cc
test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc
test/extensions/common/wasm/wasm_test.cc
test/extensions/filters/http/aws_request_signing/aws_request_signing_integration_test.cc
test/extensions/filters/udp/dns_filter/dns_filter_test.cc
test/extensions/network/dns_resolver/apple/apple_dns_impl_test.cc
test/extensions/network/dns_resolver/cares/dns_impl_test.cc
test/extensions/network/dns_resolver/getaddrinfo/getaddrinfo_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

optimize: rename `Success` to `Completed`

---

RELEASES.md

Testing:
Docs Changes:  release

sec-release: update the Q3 actual security release date

---

.github/workflows/_publish_build.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

arm/ci: Fix RBE authentication issue

---

source/common/listener_manager/listener_impl.cc
source/common/listener_manager/listener_impl.h
source/common/listener_manager/listener_manager_impl.cc
test/common/listener_manager/listener_manager_impl_test.cc

listener: more exception cleanup

---

contrib/postgres_proxy/filters/network/source/postgres_filter.cc

Commit Message: without build on m1 return with following error:
```console
ERROR: /private/var/tmp/_bazel_zirain/c9b2d3f5dca31997d353206ef73d3b4e/external/envoy/contrib/postgres_proxy/filters/network/source/BUILD:17:17: Compiling contrib/postgres_proxy/filters/network/source/postgres_filter.cc failed: (Exit 1): wrapped_clang_pp failed: error executing command (from target @envoy//contrib/postgres_proxy/filters/network/source:filter) external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' ... (remaining 205 arguments skipped)
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging …
```

postgres_filter: fix build error on m1

---

envoy/upstream/upstream.h
source/common/upstream/upstream_impl.h
source/extensions/load_balancing_policies/client_side_weighted_round_robin/client_side_weighted_round_robin_lb.cc
test/common/upstream/upstream_impl_test.cc
test/extensions/load_balancing_policies/client_side_weighted_round_robin/client_side_weighted_round_robin_lb_test.cc
test/mocks/upstream/host.cc
test/mocks/upstream/host.h

Commit Message: minor optimization to the upstream host code
1. unique_ptr over shared_ptr by default.
2. OptRef rather than reference of smart pointer.
3. fix style.
Testing: n/a.

minor optimization to the upstream host code

---

envoy/http/original_ip_detection.h
source/extensions/filters/network/http_connection_manager/config.cc
source/extensions/http/original_ip_detection/custom_header/config.cc
source/extensions/http/original_ip_detection/custom_header/config.h
source/extensions/http/original_ip_detection/xff/config.cc
source/extensions/http/original_ip_detection/xff/config.h
source/extensions/http/original_ip_detection/xff/xff.cc
source/extensions/http/original_ip_detection/xff/xff.h
test/extensions/filters/network/http_connection_manager/config_test.cc
test/extensions/http/original_ip_detection/custom_header/config_test.cc
test/extensions/http/original_ip_detection/xff/config_test.cc
test/extensions/http/original_ip_detection/xff/xff_test.cc
tools/code_format/config.yaml

original_ip: removing exceptions

---

source/common/formatter/substitution_formatter.h
source/common/json/json_streamer.h
source/server/admin/stats_html_render.cc
source/server/admin/stats_render.cc
source/server/admin/stats_render.h

Commit Message: naming: renamed the Streamer to BufferStreamer for unification
Testing: n/a.

naming: renamed the Streamer to BufferStreamer for unification

---

source/server/server.cc

Commit Message: add log line to indicate the admin server address
Testing: N/A

add log line to indicate the admin server address

---

.github/workflows/_check_coverage.yml
.github/workflows/_precheck_publish.yml
.github/workflows/_run.yml
.github/workflows/envoy-checks.yml
.github/workflows/envoy-prechecks.yml

github/ci: Upload coverage/docs to GCP

---

source/common/router/config_impl.h

Commit Message: router-config: remove unused field
Removing unused field.
Testing: N/A

router-config: remove unused field

---

mobile/test/kotlin/integration/proxying/ProxyPollPerformHTTPRequestWithoutUsingPACProxyTest.kt

mobile: Fix broken link

---

source/extensions/filters/http/ext_proc/processor_state.cc

Commit Message: fix typo in log

ext_proc: fix typo in log

---

source/common/formatter/http_formatter_context.cc
source/common/formatter/http_formatter_context.h
source/common/formatter/substitution_format_string.h
source/common/formatter/substitution_formatter.h
source/common/router/header_parser.cc
source/extensions/access_loggers/common/stream_access_log_common_impl.h
source/extensions/access_loggers/file/config.cc
source/extensions/access_loggers/open_telemetry/substitution_formatter.cc
source/extensions/filters/http/oauth2/filter.cc
source/extensions/filters/network/ratelimit/ratelimit.cc
source/extensions/filters/network/redis_proxy/router_impl.cc
test/common/formatter/substitution_formatter_fuzz_test.cc
test/common/formatter/substitution_formatter_speed_test.cc
test/common/formatter/substitution_formatter_test.cc
test/common/http/conn_manager_impl_test_base.cc
test/extensions/filters/network/generic_proxy/access_log_test.cc
test/extensions/formatter/req_without_query/req_without_query_test.cc
test/server/admin/admin_instance.cc
test/server/admin/admin_test.cc

Upstream: removing exceptions from hostimp

---

source/common/upstream/health_discovery_service.cc
source/common/upstream/upstream_impl.cc
source/common/upstream/upstream_impl.h

upstream: reducing exceptions

---

bazel/repository_locations.bzl

ci: change googleurl dep

---

source/common/matcher/exact_map_matcher.h
source/common/matcher/map_matcher.h
source/common/matcher/matcher.h
source/common/matcher/prefix_map_matcher.h
test/common/matcher/exact_map_matcher_test.cc
test/common/matcher/prefix_map_matcher_test.cc
test/extensions/filters/http/match_delegate/config_test.cc
tools/code_format/config.yaml

map matcher: removing exceptions

---

changelogs/current.yaml

Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: cleanups for release

---

test/extensions/filters/http/cache/http_cache_implementation_test_common.cc
test/extensions/filters/http/cache/http_cache_implementation_test_common.h
test/per_file_coverage.sh

coverage: adding cache test and updating coverage

---

RELEASES.md
tools/deprecate_guards/BUILD
tools/deprecate_guards/deprecate_guards.py

Risk Level:
Testing:
Docs Changes:
Release Notes:

tools: renaming deprecate version

---

api/envoy/config/route/v3/BUILD
api/envoy/config/route/v3/route_components.proto

Commit Message: remove WIP annotation. unified matcher has been used in production for quite a while

matcher: remove WIP annotation.

---

mobile/library/cc/engine.cc
mobile/library/cc/engine.h

Commit Message: expose network change available/unavailable APIs
Testing: n/a

[mobile]expose network change available/unavailable APIs

---

source/extensions/clusters/redis/redis_cluster.h

Signed-off-by: Raul Gutierrez Segales <rsegales@nvidia.com>

redis: clean up out of date friend refs

---

CODEOWNERS

Per discussion https://github.com/envoyproxy/envoy/pull/36619#issuecomment-2417696028

codeowner: add code owner

---

mobile/library/common/http/client.cc
mobile/test/java/org/chromium/net/CronetHttp3Test.java

Risk Level:
Testing:
Docs Changes:
Release Notes:

mobile: change to being more aggressive about HTTP/3 retries

---

mobile/library/common/network/connectivity_manager.h
mobile/test/common/extensions/filters/http/network_configuration/network_configuration_filter_test.cc
source/common/upstream/health_discovery_service.cc
source/common/upstream/upstream_impl.cc
source/common/upstream/upstream_impl.h
source/extensions/clusters/common/logical_host.cc
source/extensions/clusters/common/logical_host.h
source/extensions/clusters/dynamic_forward_proxy/cluster.cc
source/extensions/clusters/dynamic_forward_proxy/cluster.h
source/extensions/clusters/logical_dns/logical_dns_cluster.cc
source/extensions/clusters/original_dst/original_dst_cluster.cc
source/extensions/clusters/redis/redis_cluster.cc
source/extensions/clusters/redis/redis_cluster.h
source/extensions/clusters/strict_dns/strict_dns_cluster.cc
source/extensions/common/dynamic_forward_proxy/dns_cache.h
source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc
source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h
source/extensions/filters/network/redis_proxy/conn_pool_impl.cc
test/common/http/conn_pool_grid_test.cc
test/common/upstream/health_checker_impl_test.cc
test/common/upstream/load_balancer_simulation_test.cc
test/common/upstream/upstream_impl_test.cc
test/common/upstream/utility.h
test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc
test/extensions/common/dynamic_forward_proxy/mocks.h
test/extensions/load_balancing_policies/random/random_lb_simulation_test.cc
test/integration/clusters/custom_static_cluster.cc
test/integration/utility.cc

upstream: removing exceptions from hostimpl

---

bazel/repository_locations.bzl

current upstream has gone super flakey, this should hopefully fix

deps: Switch hosting server for kafka server binary download

---

source/extensions/filters/udp/udp_proxy/config.h
source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc
source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h
test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc

Commit Message: Refactor UDP proxy to support deferred cluster selection
Additional Description: More details in #36037 
Testing: N/A (Refactor)

Refactor UDP proxy to support deferred cluster selection

---

source/common/network/address_impl.h
source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc

proxy_protocol: use no-throw addresses to remove exception handling

---

bazel/grpc.patch

https://github.com/grpc/grpc/commit/17f0e28b4b71b8d5424f2bd26cf5b18b42755b00

Backport grpc change to fix some protoc warnings

---

.bazelrc
.github/workflows/_run.yml

This allows per-repo configuration/customization of the bazel (eg rbe) settings

bazel/ci: Add repo customizations

---

.bazelrc
.github/workflows/_run.yml

This allows per-repo configuration/customization of the bazel (eg rbe) settings

[bp/1.32] bazel/ci: Add repo customizations (#36831)

---

.bazelrc

This allows per-repo configuration/customization of the bazel (eg rbe) settings

[bp/1.29] bazel/ci: Add repo customizations (#36831)

---

.bazelrc

This allows per-repo configuration/customization of the bazel (eg rbe) settings

[bp/1.30] bazel/ci: Add repo customizations (#36831)

---

test/common/grpc/grpc_client_integration_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

fix typo in the code comment

---

source/common/config/decoded_resource_impl.h
source/common/config/utility.cc
source/common/config/utility.h
source/common/protobuf/utility.cc
source/common/protobuf/utility.h
source/extensions/common/wasm/plugin.h
source/extensions/common/wasm/wasm.cc
source/extensions/config_subscription/filesystem/filesystem_subscription_impl.cc
source/extensions/config_subscription/grpc/grpc_mux_impl.cc
source/extensions/config_subscription/grpc/watch_map.cc
source/extensions/config_subscription/grpc/xds_mux/sotw_subscription_state.cc
source/extensions/config_subscription/rest/http_subscription_impl.cc
test/common/config/decoded_resource_impl_test.cc
test/common/protobuf/utility_test.cc
test/test_common/utility.h
tools/code_format/config.yaml

config: removing unpackToOrThrow in favor of unpackTo

---

source/common/protobuf/utility.cc
source/common/protobuf/visitor.cc
source/common/protobuf/visitor.h

proto: reducing exceptions

---

api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
changelogs/current.yaml
source/common/runtime/runtime_features.cc
source/extensions/filters/network/http_connection_manager/config.cc
test/extensions/filters/network/http_connection_manager/config_test.cc

Testing: adapted tests previously

http: removing the default trusted address list

---

tools/repo/notify.py

Risk Level: n/a (tools only)
Testing: n/a

tools: updating oncall test triage location

---

contrib/golang/common/go/api/api.h
contrib/golang/common/go/api/capi.go
contrib/golang/common/go/api/filter.go
contrib/golang/filters/http/source/cgo.cc
contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
contrib/golang/filters/http/source/go/pkg/http/filter.go
contrib/golang/filters/http/source/golang_filter.cc
contrib/golang/filters/http/source/golang_filter.h
contrib/golang/filters/http/test/golang_integration_test.cc
contrib/golang/filters/http/test/test_data/basic/filter.go

Commit Message: golang: provide method to refresh route cache
Risk Level: Low, add new method
Docs Changes:
Release Notes:
Fixes #36848

golang: provide method to refresh route cache

---

source/common/network/address_impl.cc
source/common/network/address_impl.h
source/common/network/io_socket_handle_base_impl.cc
source/common/network/tcp_listener_impl.cc
source/common/network/tcp_listener_impl.h

address: removing some exceptions

---

bazel/repository_locations.bzl

deps: Bump `com_google_cel_cpp` -> 0.10.0

---

.github/workflows/codeql-daily.yml
.github/workflows/codeql-push.yml

ci/codeql: Disable "trap" caching

---

.github/dependabot.yml
contrib/golang/common/go/api/api.h
contrib/golang/common/go/api/capi.go
contrib/golang/common/go/api/filter.go
contrib/golang/filters/http/source/cgo.cc
contrib/golang/filters/http/source/go/pkg/http/capi_impl.go
contrib/golang/filters/http/source/go/pkg/http/filter.go
contrib/golang/filters/http/source/golang_filter.cc
contrib/golang/filters/http/source/golang_filter.h
contrib/golang/filters/http/source/processor_state.h
contrib/golang/filters/http/test/BUILD
contrib/golang/filters/http/test/golang_integration_test.cc
contrib/golang/filters/http/test/test_data/add_data/BUILD
contrib/golang/filters/http/test/test_data/add_data/config.go
contrib/golang/filters/http/test/test_data/add_data/filter.go
contrib/golang/filters/http/test/test_data/add_data/go.mod

Commit Message: golang: expose add{Decoded,Encoded}Data
Testing: Integration test
Docs Changes:
Release Notes:
Fixes #36911

golang: expose add{Decoded,Encoded}Data

---

source/common/protobuf/utility.cc
source/common/protobuf/utility.h
source/extensions/config_subscription/filesystem/filesystem_subscription_impl.cc
source/extensions/filters/udp/dns_filter/dns_filter.cc
source/server/server.cc
test/test_common/utility.h

proto: removing some exceptions

---

source/extensions/filters/http/ext_proc/ext_proc.cc
source/extensions/filters/http/ext_proc/ext_proc.h

ext_proc: refactoring onData() to make it modularized based on the comments:
https://github.com/envoyproxy/envoy/pull/34942/files#r1829466794
Fixes: issue: #36970

ext_proc: refactoring onData() to make it modularized

---

mobile/test/performance/files_em_does_not_use
source/extensions/filters/http/router/BUILD

build file change removing an unnecessary (and disallowed) extension dependency.
Testing: n/a

router: removing unused files

---

test/extensions/filters/common/rbac/matchers_test.cc

This PR add some more unit tests to improve the code coverage of RBAC matchers class.
---
**Commit Message:** rbac: add unit tests for matchers to increase coverage
**Additional Description:** Added some more unit tests to improve the code coverage of RBAC matchers class.
**Risk Level:** Very Low

rbac: add unit tests for matchers to increase coverage

---

envoy/upstream/cluster_manager.h
mobile/test/performance/files_em_does_not_use
source/common/tcp_proxy/BUILD
source/common/tcp_proxy/tcp_proxy.h
source/common/upstream/BUILD
source/common/upstream/cluster_manager_impl.cc
source/common/upstream/cluster_manager_impl.h
source/common/upstream/od_cds_api_impl.h
source/extensions/filters/http/on_demand/BUILD
source/extensions/filters/http/on_demand/on_demand_update.cc
test/common/tcp_proxy/tcp_proxy_test.cc
test/common/upstream/cluster_manager_impl_test.cc
test/mocks/upstream/cluster_manager.cc
test/mocks/upstream/cluster_manager.h

odcds: only including if needed

---

bazel/protobuf.patch
bazel/repository_locations.bzl

bump protobuf to 28.3

---

envoy/common/io/io_uring.h
mobile/test/performance/files_em_does_not_use
source/common/io/BUILD
source/common/io/io_uring_worker_factory_impl.cc
source/common/io/io_uring_worker_factory_impl.h
source/common/network/BUILD
source/common/network/socket_interface_impl.cc
test/common/network/BUILD
test/mocks/io/mocks.h

iouring: compiling out for E-M linux

---

test/extensions/matching/input_matchers/cel_matcher/cel_matcher_test.cc
test/extensions/matching/input_matchers/cel_matcher/cel_matcher_test.h

Add CEL test using typed_filter_config

---

.bazelrc

mac: set `-Wno-deprecated-declarations`

---

source/common/formatter/substitution_formatter.h

Commit Message: sub-formatter: store a bool instead of a string
The `FormatterBaseImpl` class stored a string in each instance where it could've stored a bool.
Testing: N/A

sub-formatter: store a bool instead of a string

---

mobile/library/jni/android_network_utility.cc

https://clang.llvm.org/extra/clang-tidy/checks/performance/inefficient-vector-operation.html
Risk Level:
Testing:
Docs Changes:
Release Notes:

Resolve performance-inefficient-vector-operation clang-tidy warning

---

source/common/router/upstream_codec_filter.h

Signed-off-by: Yury Kats ykats@google.com
Risk Level:
Testing:
Docs Changes:
Release Notes:

Optimize UpstreamCodecFilter  class layout

---

source/common/router/header_parser.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

Optimize HeadersToAddEntry class layout

---

bazel/repository_locations.bzl
bazel/rules_fuzzing.patch
tools/code_format/check_format.py
tools/code_format/envoy_build_fixer.py
tools/code_format/header_order.py

* deps: Bump `rules_fuzzing` -> 0.5.2
* patch-fix

[bp/1.29] deps: Bump `rules_fuzzing` -> 0.5.2 (#34167)

---

contrib/cryptomb/private_key_providers/source/config.cc
contrib/cryptomb/private_key_providers/test/fake_factory.cc
contrib/qat/private_key_providers/source/config.cc
contrib/qat/private_key_providers/test/fake_factory.cc
mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.cc
source/common/config/utility.cc
source/common/config/utility.h
source/common/router/config_impl.cc
source/common/upstream/cluster_factory_impl.h
source/common/upstream/upstream_impl.cc
source/common/watchdog/abort_action_config.cc
source/extensions/filters/network/dubbo_proxy/config.cc
source/extensions/filters/network/generic_proxy/config.cc
source/extensions/filters/network/generic_proxy/route_impl.cc
source/extensions/health_checkers/redis/utility.h
source/extensions/health_checkers/thrift/utility.h
source/extensions/load_balancing_policies/subset/subset_lb_config.cc
source/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator.cc
source/extensions/watchdog/profile_action/config.cc
test/common/config/utility_test.cc
test/extensions/clusters/aggregate/cluster_test.cc
test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc
test/extensions/clusters/redis/redis_cluster_test.cc
tools/code_format/config.yaml

utility: remove exceptions for translation

---

source/common/ssl/certificate_validation_context_config_impl.cc
source/common/ssl/certificate_validation_context_config_impl.h
tools/code_format/config.yaml

validation context: removing exceptions

---

OWNERS.md
reviewers.yaml

Testing: He's great at it :-)
Docs Changes: inline

maintainers: promoting Boteng!

---

source/common/router/config_impl.cc
source/common/router/config_impl.h

Signed-off-by: Yury Kats ykats@google.com
Risk Level:
Testing:
Docs Changes:
Release Notes:

Optimize HedgePolicyImpl class layout

---

source/common/upstream/health_checker_event_logger.h
source/common/upstream/health_checker_impl.cc
test/common/upstream/health_checker_impl_test.cc
tools/code_format/config.yaml

health check: remove exceptions

---

changelogs/current.yaml
docs/root/configuration/http/http_filters/lua_filter.rst

followup of https://github.com/envoyproxy/envoy/pull/36920
Commit Message: add docs for lua filter and change log
Testing: no

add docs for lua filter and change log

---

contrib/hyperscan/regex_engines/test/integration_test.cc
source/common/common/matchers.h
source/common/common/regex.h
source/common/http/async_client_impl.cc
source/common/http/hash_policy.cc
source/common/http/hash_policy.h
source/common/http/header_utility.cc
source/common/http/header_utility.h
source/common/http/null_route_impl.h
source/common/router/config_impl.cc
source/common/tcp_proxy/tcp_proxy.cc
source/extensions/filters/common/mutation_rules/mutation_rules.cc
source/extensions/filters/http/header_to_metadata/header_to_metadata_filter.cc
source/extensions/filters/http/json_to_metadata/filter.cc
source/extensions/filters/network/thrift_proxy/filters/header_to_metadata/header_to_metadata_filter.cc
source/extensions/filters/network/thrift_proxy/filters/payload_to_metadata/payload_to_metadata_filter.cc
source/server/admin/config_dump_handler.cc
test/common/common/regex_test.cc
test/common/http/async_client_impl_test.cc
test/common/http/hash_policy_test.cc
test/integration/regex_engine_integration_test.cc
tools/code_format/config.yaml

regex: removing exceptions

---

source/extensions/filters/http/cors/cors_filter.cc

Commit Message: cors: refactor loop to if
PR #36079 updated the policies of the CORS filter to be a vector of references that must exist.
This followup changes the original for-loop to an if statement that returns the first element, if exists.
Testing: N/A

cors: refactor loop to if

---

test/tools/schema_validator/BUILD

Fixes https://github.com/envoyproxy/envoy/issues/36808

[bp/1.30] validator: add in removed extension (#37261)

---

test/tools/schema_validator/BUILD

Fixes https://github.com/envoyproxy/envoy/issues/36808

[bp/1.32] validator: add in removed extension (#37261)

---

test/tools/schema_validator/BUILD

Fixes https://github.com/envoyproxy/envoy/issues/36808

[bp/1.31] validator: add in removed extension (#37261)

---

source/extensions/path/uri_template_lib/uri_template.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

Fix unchecked StatusOr dereference

---

source/extensions/filters/http/cors/BUILD
source/extensions/filters/http/cors/cors_filter.cc
source/extensions/filters/http/cors/cors_filter.h
test/extensions/filters/http/cors/cors_filter_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

cors: remove unnecessary code

---

docs/build.sh

ci: removes docs/build.sh

---

test/integration/socket_interface_swap.h

Commit Message: fix unchecked statusor value access
This this file there are a couple accesses to a StatusOr with no check to see whether the status is actually ok or not.
Testing: test only change
Release Notes: none 

fix unchecked statusor value access

---

source/common/profiler/profiler.cc
source/extensions/access_loggers/common/grpc_access_logger_clients.h

clang-tidy: fixes some errors

---

.github/workflows/envoy-release.yml
tools/deprecate_guards/BUILD
tools/deprecate_guards/deprecate_guards.py

- use a runner
- switch pygithub -> gidgethub
- minor fixes
step towards #35378

ci: Add workflow for guards deprecation and update tool

---

GOVERNANCE.md

Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: fix link

---

.circleci/config.yml

ci: removes unused CircleCI config

---

envoy/config/context_provider.h
source/common/config/context_provider_impl.h
test/common/config/context_provider_impl_test.cc
test/common/local_info/local_info_impl_test.cc
test/integration/server.cc
test/mocks/config/mocks.h
tools/code_format/config.yaml

context_provider: exception free

---

.github/workflows/_publish_build.yml

github/ci: Workaround failing `gsutil` issue

---

source/common/secret/sds_api.cc
source/common/secret/sds_api.h
tools/code_format/config.yaml

Risk Level: n/a (pure code move)
Testing: prior tests

sds: moving code to cc file

---

source/common/upstream/upstream_impl.cc
source/common/upstream/upstream_impl.h
source/extensions/load_balancing_policies/subset/subset_lb.h
tools/code_format/config.yaml

upstream: removing header exceptions

---

mobile/library/common/extensions/cert_validator/platform_bridge/config.cc
mobile/library/common/extensions/cert_validator/platform_bridge/config.h
mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.cc
mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.h
mobile/test/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator_test.cc
source/common/tls/cert_validator/default_validator.cc
source/common/tls/cert_validator/factory.h
source/common/tls/context_impl.cc
source/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator.cc
test/common/tls/cert_validator/timed_cert_validator.h

validator: allowing creation failure

---

source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc
source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h
tools/code_format/config.yaml

dns_cache: removing exceptions

---

source/common/config/watched_directory.cc
source/common/config/watched_directory.h
source/common/secret/sds_api.cc
source/extensions/config_subscription/filesystem/filesystem_subscription_impl.cc
test/common/config/watched_directory_test.cc
tools/code_format/config.yaml

watched: removing exceptions

---

source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

Replace string addition with absl::StrCat

---

source/common/upstream/cds_api_helper.cc

Commit Message: cds: perf improvement - avoid cluster resource copy
This PR changes the CDS ingestion pipeline to avoid unnecessary copy of the Cluster resource.
Testing: N/A

cds: perf improvement - avoid cluster resource copy

---

source/common/listener_manager/lds_api.cc

Commit Message: lds: perf improvement - avoid listener resource copy
This PR changes the LDS ingestion pipeline to avoid unnecessary copy of the Listener resource.
Testing: N/A

lds: perf improvement - avoid listener resource copy

---

docs/root/_static/searchtools.js

i thought i had checked this when i landed these PRs but it seems they broke search

docs/search: Revert `innerHTML` changes

---

source/extensions/filters/http/aws_request_signing/config.cc
test/extensions/filters/http/aws_request_signing/config_test.cc
tools/code_format/config.yaml

Commit Message: aws: removes exceptions from signing filter
This is a follow up from #37498 

aws: removes exceptions from signing filter

---

docs/root/_static/searchtools.js

We customize our search results to add proto labels - this had gotten out of sync with sphinx/theme - this updates it to use the latest searchtools.js with our customizations

docs: Fix search tool

---

source/extensions/filters/http/api_key_auth/api_key_auth.cc
source/extensions/filters/http/api_key_auth/api_key_auth.h
source/extensions/filters/http/api_key_auth/config.cc
source/extensions/filters/http/api_key_auth/config.h
test/extensions/filters/http/api_key_auth/config_test.cc

Commit Message: api key auth: fix broken test and use const for config
Risk Level:
Testing:
Docs Changes:
Release Notes:

api key auth: fix broken test and use const for config

---

source/extensions/filters/network/http_connection_manager/config.cc
source/extensions/filters/network/http_connection_manager/config.h
source/server/api_listener_impl.cc
source/server/api_listener_impl.h
tools/code_format/config.yaml

hcm: making exception free

---

api/envoy/config/grpc_credential/v3/BUILD
api/envoy/config/grpc_credential/v3/aws_iam.proto
changelogs/current.yaml

aws_iam: deprecate extension and mark for future deletion

---

api/envoy/extensions/transport_sockets/tls/v3/common.proto

Commit Message: Doc: private_key_provider description update
Risk Level:  low
Testing:
Docs Changes: 
Platform Specific Features: 
[Optional Fixes #Issue] #37285

Doc: private_key_provider description update

---

source/common/common/matchers.cc
source/common/common/matchers.h

Commit Message: matchers: remove unused path pattern matcher
Removing dead code.
Testing: N/A

matchers: remove unused path pattern matcher

---

api/envoy/config/cluster/redis/redis_cluster.proto
api/envoy/extensions/clusters/redis/v3/redis_cluster.proto

Commit Message: redis proxy: fix example in the proto comment
Risk Level:
Testing:
Docs Changes:
Release Notes:

redis proxy: fix example in the proto comment

---

mobile/bazel/envoy_mobile_dependencies.bzl

this is the most up-to-date i could get them without hacking any java

mobile/deps: Bump android (maven) test deps

---

bazel/repository_locations.bzl
source/extensions/dynamic_modules/sdk/rust/Cargo.Bazel.lock

deps: Bump `rules_rust` -> 0.56.0

---

api/envoy/extensions/filters/http/jwt_authn/v3/config.proto

Commit Message: JWT Document minor space fix 
**Updated:**

Minor JWT Document space fix from #36458

---

.github/workflows/_run.yml

workaround https://github.com/envoyproxy/envoy/issues/37603 to unblock release

github/ci: Workaround release branch Docker cache issue

---

test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc

part of https://github.com/envoyproxy/envoy/issues/37611

test: adding logging for a flake

---

bazel/README.md
tools/vscode/generate_debug_config.py

Commit Message: Docs improvements on macOS development
I recently got a new mac and wanted to setup Envoy development. Ran into several roadbumps, and after some frustrations I can build and debug locally on macOS + VSCode. So I thought about documenting what I did to avoid others getting frustrated :)
Testing: N/A
Platform Specific Features: macOS

Docs improvements on macOS development

---

docs/root/configuration/http/http_filters/_include/aws_credentials.rst

This PR fixes some notes in the AWS Credentials docs and reword some text to make it clear.
---
**Commit Message:** docs: fix notes in AWS Credentials filter docs
**Additional Description:** Fixes some notes in the AWS Credentials docs and reword some text to make it clear.

docs: fix notes in AWS Credentials filter docs

---

envoy/grpc/async_client_manager.h
source/common/grpc/async_client_impl.cc
source/common/grpc/async_client_impl.h
source/common/grpc/async_client_manager_impl.cc
source/common/grpc/async_client_manager_impl.h
source/common/upstream/cluster_manager_impl.cc
source/extensions/access_loggers/grpc/grpc_access_log_impl.cc
source/extensions/access_loggers/open_telemetry/grpc_access_log_impl.cc
source/extensions/config_subscription/grpc/grpc_collection_subscription_factory.cc
source/extensions/config_subscription/grpc/grpc_subscription_factory.cc
source/extensions/filters/network/ext_authz/config.cc
source/extensions/filters/network/redis_proxy/config.cc
source/extensions/tracers/opentelemetry/opentelemetry_tracer_impl.cc
source/extensions/tracers/skywalking/trace_segment_reporter.cc
source/server/server.cc
test/common/grpc/async_client_impl_test.cc
test/common/grpc/buffered_async_client_test.cc
test/common/grpc/grpc_client_integration_test_harness.h
test/extensions/access_loggers/common/grpc_access_logger_test.cc
test/mocks/grpc/mocks.h
tools/code_format/config.yaml

grpc: removing exceptions from client creation

---

test/extensions/config_subscription/grpc/xds_failover_integration_test.cc

Commit Message: tests: remove unused xds-failover test code
tests: remove unused xds-failover test code
Testing: N/A

tests: remove unused xds-failover test code

---

mobile/WORKSPACE

mobile: Bump the ndk_api_level to 23

---

envoy/common/execution_context.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

scoped context nit: change comments

---

api/envoy/extensions/filters/http/rbac/v3/rbac.proto

This PR fixes some styling in the RBAC protos and adds the missing backticks, notes, etc.
---
Commit Message: rbac: fix styling in the RBAC protos
Additional Description: Fix RBAC proto styling.
Testing: N/A

rbac: fix styling in the RBAC protos

---

CODEOWNERS
OWNERS.md
SECURITY-INSIGHTS.yml
reviewers.yaml

Thanks for all your work on Envoy and best of luck with the new job!
Testing: n/a

owners: moving soulxu to emeritus

---

source/extensions/filters/http/cdn_loop/config.cc
source/extensions/filters/http/cdn_loop/config.h
test/extensions/filters/http/cdn_loop/config_test.cc
tools/code_format/config.yaml

Commit Message: Make cdn_loop exception free

Make cdn_loop exception free

---

source/extensions/filters/http/ext_proc/ext_proc.cc
source/extensions/filters/http/ext_proc/processor_state.cc

Commit Message: change ENVOY_LOG in ext_proc.cc and process_state.cc to ENVOY_STREAM_LOG
Risk Level: LOW, log-only
Testing: N/A
Docs Changes:
Release Notes:

ext_proc: change ENVOY_LOG in ext_proc.cc and process_state.cc to ENVOY_STREAM_LOG

---

source/common/rds/common/route_config_provider_manager_impl.h
source/common/rds/rds_route_config_subscription.cc
source/common/rds/rds_route_config_subscription.h
source/common/rds/route_config_provider_manager.h
source/common/router/rds_impl.cc
source/common/router/rds_impl.h
tools/code_format/config.yaml

rds: removing an exception

---

docs/root/operations/admin.rst

Testing:
Docs Changes:
Release Notes:

admin_logging_doc: replace int with actual log level

---

changelogs/current.yaml

This PR fixes some small typos in the current changelogs.
---
**Commit Message:** changelog: fix typos in the current changelogs
**Additional Description:** Fixes some typos in the current changelogs.

changelog: fix typos in the current changelogs

---

test/per_file_coverage.sh

This is to fix this coverage failure: https://github.com/envoyproxy/envoy/actions/runs/13016805974/job/36307963503
Testing: CI

coverage: Adjust tcp_proxy coverage

---

docs/root/intro/arch_overview/listeners/listener_filters.rst

Commit Message: Grammar fix
Additional Description: The word "to" appears repeated where it seems to be a mistake.
Testing:
Docs Changes: Removing repeated word.
Release Notes:

Grammar fix

---

test/integration/tcp_tunneling_integration_test.cc
test/per_file_coverage.sh

Resolve #38240 
Risk Level:
Testing:
Docs Changes:
Release Notes:

fix tcp proxy coverage

---

source/common/rds/rds_route_config_subscription.cc
source/common/rds/rds_route_config_subscription.h
source/common/router/rds_impl.cc
source/common/router/rds_impl.h

Commit Message: Removes one exception from rds_impl.cc
There's one another exception left in the file which 
requires a bit broader refactoring. This is the easy one. 
Testing: existing ones 

Removes one exception from rds_impl.cc

---

tools/code_format/config.yaml

This removes a couple of files no longer having exceptions
from config.yaml.

Updates exception allowed files

---

docs/root/configuration/http/http_conn_man/stats.rst

Commit Message: Add stat to docs.
Additional Description: See: https://github.com/envoyproxy/envoy/blob/c87c3e4ea6c4d564ac69f8da4de79544bdc8c0c5/source/common/http/user_agent.cc#L20
Testing: n/a
Docs Changes: incl

Docs: Add stat to docs.

---

docs/root/configuration/http/http_filters/_include/jwt-authn-claim-filter.yaml
docs/root/configuration/http/http_filters/_include/jwt-authn-filter.yaml
docs/root/configuration/http/http_filters/_include/jwt-authn-group-filter.yaml
docs/root/configuration/http/http_filters/_include/jwt-authn-headers-filter.yaml
docs/root/configuration/http/http_filters/_include/jwt-authn-inline-filter.yaml
docs/root/configuration/http/http_filters/_include/jwt-authn-single-filter.yaml
docs/root/configuration/http/http_filters/jwt_authn_filter.rst

Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Update JWT config reference to use literalincludes

---

mobile/library/cc/engine_builder.cc
mobile/library/cc/engine_builder.h
mobile/library/common/internal_engine.cc
mobile/library/common/internal_engine.h
mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
mobile/library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java
mobile/library/java/org/chromium/net/impl/NativeCronvoyEngineBuilderImpl.java
mobile/library/jni/jni_impl.cc
mobile/library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
mobile/test/common/integration/client_integration_test.cc
mobile/test/common/internal_engine_test.cc
mobile/test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
mobile/test/swift/integration/BUILD

mobile: Add a knob to disable DNS refresh on network change

---

source/common/common/containers.h
source/common/filter/config_discovery_impl.cc
source/common/filter/config_discovery_impl.h
test/common/common/containers_test.cc
tools/code_format/config.yaml

config discovery: removing exceptions

---

envoy/upstream/cluster_manager.h
source/common/tcp_proxy/tcp_proxy.cc
source/common/tcp_proxy/tcp_proxy.h
source/common/upstream/cds_api_impl.cc
source/common/upstream/cds_api_impl.h
source/common/upstream/cluster_manager_impl.cc
source/common/upstream/cluster_manager_impl.h
source/common/upstream/od_cds_api_impl.cc
source/common/upstream/od_cds_api_impl.h
source/extensions/filters/http/on_demand/on_demand_update.cc
source/server/config_validation/cluster_manager.cc
source/server/config_validation/cluster_manager.h
test/common/upstream/cds_api_impl_test.cc
test/common/upstream/cluster_manager_impl_test.cc
test/common/upstream/od_cds_api_impl_test.cc
test/common/upstream/test_cluster_manager.h
test/mocks/upstream/cluster_manager.cc
test/mocks/upstream/cluster_manager.h
test/mocks/upstream/cluster_manager_factory.h
tools/code_format/config.yaml

cds: removing exceptions

---

mobile/envoy_build_config/extension_registry.cc
source/common/quic/quic_client_transport_socket_factory.h

It confuses an internal toolchain otherwise.

Fully qualify namespace

---

.vscode/tasks.json

Commit Message: `git push --set-upstream origin vscode` take too long time, add a new task which is faster. cc @phlax 
Risk Level:
Testing:
Docs Changes:
Release Notes:

chore: add faster fix format task

---

source/common/filter/config_discovery_impl.h

Commit Message: minor-perf: move ECDS factory
Minor perf nit, move the ECDS factory callback, instead of copying it.
Testing: N/A

minor-perf: move ECDS factory acllback

---

ci/docker_ci.sh

docker: Fix/workaround broken qemu builder

---

OWNERS.md
SECURITY-INSIGHTS.yml
reviewers.yaml

Per Slack discussion
Testing: N/A
Docs Changes:  N/A

Promote tonya11en to maintainer

---

ci/docker_ci.sh

[bp/1.33] docker: Fix/workaround broken qemu builder (#38415)

---

ci/docker_ci.sh

[bp/1.32] docker: Fix/workaround broken qemu builder (#38415)

---

ci/docker_ci.sh

[bp/1.31] docker: Fix/workaround broken qemu builder (#38415)

---

ci/docker_ci.sh

[bp/1.30] docker: Fix/workaround broken qemu builder (#38415)

---

api/envoy/extensions/filters/http/router/v3/router.proto
api/envoy/extensions/upstreams/http/v3/http_protocol_options.proto

Commit Message: docs: fix note for upstream HTTP filters
Additional Description: Currently, the "Note" box is not displayed.
Testing: N/A

docs: fix note for upstream HTTP filters

---

api/envoy/config/core/v3/substitution_format_string.proto
test/integration/access_log_integration_test.cc

Commit Message: docs: update docs and annotation of json formatter
Testing: n/a.
Docs Changes:
Release Notes:

docs: update docs and annotation of json formatter

---

.github/workflows/_run.yml

Risk Level:
Testing:
Docs Changes:
Release Notes:

[ci] Set `--remote_execution_priority` for RBE

---

source/common/secret/secret_provider_impl.cc

comment: delete thread_local update can throw

---

test/extensions/dynamic_modules/http/abi_impl_test.cc

Commit Message: dynamic_modules: add more test coverage
Testing: done

dynamic_modules: add more test coverage

---

CODEOWNERS
OWNERS.md
SECURITY-INSIGHTS.yml
reviewers.yaml

It has been a fantastic 18 year run at Google and 8 year run on Envoy but alas I am moving on.
Thanks to all for the amazing community and proxy we've built together

docs: alyssar -> emeritus

---

docs/root/configuration/http/http_filters/_include/lua-filter-override.yaml
docs/root/configuration/http/http_filters/_include/lua-filter.yaml
docs/root/configuration/http/http_filters/lua_filter.rst

Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Update lua config reference to use literalincludes

---

docs/root/configuration/http/http_filters/_include/rate-limit-routes.yaml
docs/root/configuration/http/http_filters/rate_limit_filter.rst

Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: Update rate limit config reference to use literalincludes

---

test/extensions/common/wasm/BUILD

test: increase resources for wasm_test

---

test/common/grpc/grpc_client_integration_test.cc
test/common/grpc/grpc_client_integration_test_harness.h
test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc

Clarify comments and add more tests for gRPC clients

---

envoy/access_log/access_log.h
envoy/access_log/access_log_config.h
envoy/formatter/substitution_formatter.h
envoy/formatter/substitution_formatter_base.h
source/common/formatter/BUILD
source/common/formatter/http_specific_formatter.cc
source/common/formatter/http_specific_formatter.h
source/common/formatter/stream_info_formatter.cc
source/common/formatter/stream_info_formatter.h
source/common/formatter/substitution_format_string.cc
source/common/formatter/substitution_format_string.h
source/common/formatter/substitution_formatter.cc
source/common/formatter/substitution_formatter.h
source/common/tcp_proxy/tcp_proxy.cc
source/extensions/access_loggers/common/stream_access_log_common_impl.h
source/extensions/access_loggers/file/config.cc
source/extensions/access_loggers/fluentd/config.cc
source/extensions/access_loggers/open_telemetry/config.cc
source/extensions/filters/common/set_filter_state/filter_config.cc
source/extensions/filters/udp/udp_proxy/config.cc
source/extensions/formatter/metadata/metadata.cc
source/extensions/http/custom_response/local_response_policy/local_response_policy.cc
source/extensions/matching/actions/format_string/config.cc
test/common/formatter/substitution_formatter_test.cc
test/extensions/access_loggers/file/config_test.cc
test/extensions/formatter/metadata/metadata_test.cc
tools/code_format/config.yaml

Commit Message: formatter: no template is necessary now
continuous work after #38164.
Risk Level: low. no any logic change.
Testing: n/a.

formatter: no template is necessary for logger/formatter now

---

changelogs/current.yaml
mobile/test/common/integration/client_integration_test.cc
source/common/runtime/runtime_features.cc
source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc
test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
test/extensions/network/dns_resolver/getaddrinfo/getaddrinfo_test.cc

runtime: Remove dns_nodata_noname_is_success and legacy code paths

---

mobile/envoy_build_config/extension_registry.h
mobile/test/performance/files_em_does_not_use
source/common/network/socket_interface_impl.cc

Signed-off-by: Xie Zhihao <xzh1206@gmail.com>
Commit Message: io_uring: fix create bootstrap extension on Android
Testing: N/A
Fix #38660

io_uring: fix create bootstrap extension on Android

---

envoy/formatter/http_formatter_context.h

Commit Message: minor clean up: remove unnecessary method
Risk Level:
Testing:
Docs Changes:
Release Notes:

minor clean up: remove unnecessary method

---

source/extensions/filters/network/sni_dynamic_forward_proxy/config.cc
source/extensions/filters/network/sni_dynamic_forward_proxy/config.h
source/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter.cc
source/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter.h
test/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter_test.cc
tools/code_format/config.yaml

Commit Message: Make SNI dynamic foward proxy exception free

Make SNI dynamic foward proxy exception free

---

source/extensions/matching/input_matchers/cel_matcher/matcher.cc
test/extensions/matching/input_matchers/cel_matcher/cel_matcher_test.cc

Commit Message: cel_mather: support `cel_expr_checked` and `cel_expr_parsed`
Risk Level:
Testing:
Docs Changes:
Release Notes:

cel_mather: support cel_expr_checked and cel_expr_parsed

---

source/common/memory/stats.cc

configureBackgroundMemoryRelease() method is only called in tcmalloc builds. Coverage reports are built with gperftools tcmalloc instead of the regular one.
This creates a situation when coverage report does not recognize that configureBackgroundMemoryRelease cannot be called at all and declares it as not covered pushing the coverage stats down.
Given that configureBackgroundMemoryRelease currently cannot be covered by tests in principle, I think it makes sense to exclude the dead parts of the code from the coverage reports.
This refactoring moves the logic from AllocatorManager::AllocatorManager to configureBackgroundMemoryRelease (including all the #ifdefs), and instead of calling configureBackgroundMemoryRelease conditionally calls it unconditionally.
This way all the …

Refactor #ifdefs in stats.cc to help coverage tools figure out dead code

---

api/envoy/extensions/tracers/opentelemetry/samplers/v3/cel_sampler.proto

Risk Level:
Testing:
Release Notes:

typofix in doc title cel_sampler.proto

---

source/extensions/extensions_metadata.yaml
source/extensions/filters/http/dynamic_modules/BUILD
source/extensions/filters/http/dynamic_modules/factory.cc
source/extensions/filters/http/dynamic_modules/factory.h
source/extensions/filters/http/dynamic_modules/factory_registration.cc
test/extensions/dynamic_modules/http/integration_test.cc

fixes https://github.com/envoyproxy/envoy/issues/38448
Commit Message: dynamic_modules: make dynamic module filter a dual filter
Risk Level:
Testing:
Docs Changes:
Release Notes:

dynamic_modules: make dynamic module filter a dual filter

---

CODEOWNERS

Commit Message: CI: Add unowned to fix ci.
Additional Description: Context: https://envoyproxy.slack.com/archives/C78HA81DH/p1742304245494679
Testing: n/a
Docs Changes:
Release Notes:

CI: Add unowned to fix ci.

---

test/extensions/filters/http/grpc_json_reverse_transcoder/filter_test.cc
test/extensions/filters/http/grpc_json_reverse_transcoder/grpc_json_reverse_transcoder_integration_test.cc

Commit Message: Fix the flaky grpc_json_reverse_transcoder tests
Additional Description: There are certain tests that pass in certain environments but fail in others, this PR makes those tests consistent across all environments.
Risk Level: None, as this PR only updates the tests.
Testing: n/a, as this change itself fixes some of the tests

Fix the flaky grpc_json_reverse_transcoder tests

---

api/envoy/extensions/filters/common/dependency/v3/dependency.proto

Recently used this, works well :partying_face: !
Commit Message:  Fix typo on proto doc.
Testing: n/a
Docs Changes: y

Typo: Fix typo on proto doc.

---

api/envoy/config/endpoint/v3/BUILD
api/envoy/config/endpoint/v3/endpoint_components.proto

Commit Message: xDS: add LEDS list collection
Additional Description: Also clean up docs for some existing LEDS-related fields.
Testing: N/A
CC @adisuissa

xDS: add LEDS list collection

---

README.md

It is a scamming link, and I will not click it a second time ;|
Testing:
Docs Changes:
Release Notes:

docs: remove bad scary link

---

api/envoy/data/tap/v3/transport.proto
api/envoy/extensions/transport_sockets/tap/v3/tap.proto
changelogs/current.yaml
source/extensions/transport_sockets/tap/BUILD
source/extensions/transport_sockets/tap/tap.cc
source/extensions/transport_sockets/tap/tap.h
source/extensions/transport_sockets/tap/tap_config.h
source/extensions/transport_sockets/tap/tap_config_impl.cc
source/extensions/transport_sockets/tap/tap_config_impl.h
test/extensions/transport_sockets/tap/tap_config_impl_test.cc

Additional Description: Check [the issue](https://github.com/envoyproxy/envoy/issues/38582) for detailed description 
Testing:
Docs Changes:
Release Notes:

Enhancement for Transport Tap: output connection information per event per configuration

---

mobile/library/jni/jni_helper.h

Commit Message: mobile: add missing vector include
Adding missing include statement.
Testing: N/A

mobile: add missing vector include

---

source/extensions/filters/network/ext_authz/config.h

Testing:
Docs Changes:
Release Notes:

nit: remove ext_authz comment extra space

---

CODEOWNERS

Commit Message: add @niax as codeowner
@niax is a service team member who will be helping with code review on the aws extension components.
Testing:
Docs Changes:
Release Notes:

aws: add @niax as codeowner

---

OWNERS.md
SECURITY-INSIGHTS.yml
reviewers.yaml

add mathetake to maintainers

---

source/extensions/filters/http/oauth2/filter.h

Testing:
Docs Changes:
Release Notes:

oauth2: make the OauthFilter parameters consistent with .cc

---

contrib/golang/filters/http/test/test_data/go.mod
contrib/golang/filters/network/test/test_data/go.mod
contrib/golang/router/cluster_specifier/test/test_data/simple/go.mod
contrib/golang/upstreams/http/tcp/test/test_data/go.mod

These deps are flagging as having the recently published envoy vuln

go/deps: Fix vulnerability in envoy deps

---

test/common/matcher/matcher_test.cc

Commit Message: Improve matcher_test readability
Additional description: Also improves the test quality, as it's now validating that the action is the specific one it's expected to be rather than just validating "there is an action".

Improve matcher_test readability

---

source/common/http/conn_manager_impl.cc

Commit Message:  Reduce temporary variable and optimize parameter passing via RVO(return value optimization).
Testing: In high qps testing, refreshCachedRoute function have better performance than before.

optimize: Reduce temporary variable and optimize parameter passing via RVO

---

api/envoy/extensions/load_balancing_policies/common/v3/common.proto
docs/root/configuration/upstream/cluster_manager/cluster_runtime.rst
source/extensions/load_balancing_policies/common/load_balancer_impl.cc
source/extensions/load_balancing_policies/common/load_balancer_impl.h
test/extensions/load_balancing_policies/common/load_balancer_impl_base_test.h
test/extensions/load_balancing_policies/round_robin/round_robin_lb_test.cc

Commit Message: zone aware routing: add force_direct_routing
Additional Description: Allow forcing LocalityDirect routing mode for Zone Aware LB Config
Risk Level:
Testing:
Fixes #38758

add force_locality_direct_routing feature

---

OWNERS.md

project: Add Raven to security team

---

source/common/protobuf/protobuf.h
test/extensions/filters/http/grpc_json_reverse_transcoder/BUILD
test/extensions/filters/http/grpc_json_reverse_transcoder/filter_test.cc

Fix include paths in grpc_json_reverse_transcoder test

---

source/extensions/filters/listener/http_inspector/config.cc
source/extensions/filters/listener/http_inspector/http_inspector.cc
source/extensions/filters/listener/http_inspector/http_inspector.h
test/extensions/filters/listener/http_inspector/http_inspector_test.cc

Commit Message: cherry-pick of #37002 
Risk Level:
Testing:
Docs Changes:
Release Notes:

[release-1.33] http_inspector dynamic buffering (#37002)

---

test/common/quic/quic_filter_manager_connection_impl_test.cc
test/per_file_coverage.sh

#39076 
Thanks @abeyad for catching this.
Risk Level:
Testing:
Docs Changes:
Release Notes:

coverage: fix setbufferlimit quic coverage

---

docs/root/configuration/http/http_filters/ext_proc_filter.rst

Address the comments in this PR: https://github.com/envoyproxy/envoy/pull/38940#issuecomment-2762211605

Fix ext_proc release documentation

---

changelogs/current.yaml
test/extensions/clusters/eds/eds_test.cc

Testing: added test. I verified that the test crashes without #39083.
Release Notes: added release note for previous change

eds: add test for fix in #39083

---

changelogs/summary.md

This commit adds a release summary for Envoy 1.34.0, highlighting key changes including:
- Security fixes (CVE-2025-30157 and CVE-2025-31498)
- HTTP improvements
- Performance enhancements
- Reliability fixes
- New features
- Observability enhancements

changelog: Update summary for 1.34.0 release

---

changelogs/current.yaml
source/common/network/io_socket_handle_impl.h
source/common/quic/envoy_quic_utils.cc
source/common/runtime/runtime_features.cc

Testing: n/a
Fixes: https://github.com/envoyproxy/envoy/issues/39125

runtime: Remove `quic_connect_client_udp_sockets` and legacy code paths

---

docs/root/start/install.rst

Remove link to a broken doc

---

changelogs/current.yaml
source/common/http/codec_client.cc
source/common/runtime/runtime_features.cc
test/integration/multiplexed_integration_test.cc

runtime: delete http2_no_protocol_error_upon_clean_close

---

source/extensions/filters/http/grpc_json_reverse_transcoder/filter.cc

Commit Message: grpc-json-transcoder: refactor string copy to move
Follow up to #38997 refactoring a string copy to move semantics.
Testing: N/A

grpc-json-transcoder: refactor string copy to move

---

api/envoy/type/metadata/v3/metadata.proto

This PR changes the note annotation to the new style for consistency and rewords some of the description in the metadata docs to make it more clear.
---
**Commit Message:** docs: change note annotation and reword the metadata docs
**Additional Description:** This PR improves the styling and readability of the Metadata docs.

docs: change note annotation and reword the metadata docs

---

CODEOWNERS

Commit Message: Codeowners: Add bplotnick as oauth2 owner.
Additional Description: Thank you for providing expertise here!
Testing: n/a

Codeowners: Add bplotnick as oauth2 owner.

---

source/extensions/filters/http/dynamic_modules/abi_impl.cc
test/extensions/dynamic_modules/http/abi_impl_test.cc

Commit Message: add request id attribute to dynamic modules

dynamic_modules: add request id attribute support

---

api/envoy/extensions/filters/network/ext_proc/v3/ext_proc.proto
api/envoy/service/network_ext_proc/v3/network_external_processor.proto

Testing:
Docs Changes:
Release Notes:

network: fixed ext_proc api and service page formats

---

source/extensions/filters/http/ext_proc/ext_proc.h

Testing:
Docs Changes:
Release Notes:

http_ext_proc: use const reference for stats_ in the filter

---

source/extensions/filters/http/ext_proc/processor_state.cc

ext_proc: Remove duplicate none-op clear watermarks

ext_proc: Remove duplicate none-op clear watermarks

---

bazel/repository_locations.bzl

Cleanup gtest repository info

---

source/extensions/load_balancing_policies/override_host/BUILD

Risk Level:
Testing:
Docs Changes:
Release Notes:

clean up unexpected build target

---

test/common/upstream/BUILD
test/extensions/common/wasm/BUILD
test/extensions/filters/udp/dns_filter/BUILD

Remove unnecessary c-ares library dependencies

Remove unnecessary c-ares library dependencies

---

source/extensions/load_balancing_policies/override_host/BUILD

fix error when running `tools/gen_compilation_database.py --exclude_contrib`
```console
ERROR: /Users/zirain/Codes/servicemesh/envoy/source/extensions/load_balancing_policies/override_host/BUILD:67:17: //source/extensions/load_balancing_policies/override_host:least_request_lb_lib, aspect @@bazel_compdb//:aspects.bzl%compilation_database_aspect: missing input file '//source/extensions/load_balancing_policies/override_host:least_request_lb.h'
```
Risk Level:
Testing:
Docs Changes:
Release Notes:

chore: fix refresh_compdb

---

RELEASES.md

Risk Level:
Testing:
Docs Changes:
Release Notes:

doc: update the release doc

---

source/extensions/filters/network/ext_proc/ext_proc.cc
source/extensions/filters/network/ext_proc/ext_proc.h
test/extensions/filters/network/ext_proc/ext_proc_integration_test.cc

Risk Level:
Testing:
Docs Changes:
Release Notes:

network ext_proc: add close and rst support

---

changelogs/1.30.0.yaml
docs/root/configuration/http/http_filters/aws_request_signing_filter.rst

Risk Level:
Testing:
Docs Changes:
Release Notes:

spell: fix separate spell across the code base

---

api/envoy/admin/v3/clusters.proto

This PR cleans up the clusters docs to use the proper note annotations.
---
**Commit Message:** docs: clean up the clusters docs
**Additional Description:** Clean up the clusters docs.

docs: clean up the clusters docs

---

api/envoy/config/rbac/v3/rbac.proto

This PR cleans up the RBAC filter docs to use the proper note annotations.
---
**Commit Message:** docs: clean up the RBAC filter docs
**Additional Description:** Clean up the RBAC filter docs.

docs: clean up the RBAC docs

---

source/extensions/filters/common/rbac/utility.cc
source/extensions/filters/common/rbac/utility.h
source/extensions/filters/http/rbac/rbac_filter.cc

Commit Message: rbac: minor string->string_view refactor
Modifying the use of std::string to string_view to remove some string copies.
Testing: N/A

rbac: minor string->string_view refactor

---

test/run_envoy_bazel_coverage.sh

This reverts commit e7f411d15f0a702e56d9dc99d9ed94f3cf756556.

Revert "ci/coverage: Remove mobile workaround (#39594)"

---

CODEOWNERS

Commit Message: Remove suniltheta from CODEOWNERS
Risk Level:
Testing:
Docs Changes:
Release Notes:

Remove suniltheta from CODEOWNERS

---

source/extensions/common/aws/credential_providers/container_credentials_provider.cc
source/extensions/common/aws/credential_providers/iam_roles_anywhere_credentials_provider.cc
source/extensions/common/aws/credential_providers/instance_profile_credentials_provider.cc
source/extensions/common/aws/credential_providers/webidentity_credentials_provider.cc
test/extensions/common/aws/credential_providers/container_credentials_provider_test.cc
test/extensions/common/aws/credential_providers/credentials_file_credentials_provider_test.cc
test/extensions/common/aws/credential_providers/environment_credentials_provider_test.cc
test/extensions/common/aws/credential_providers/iam_roles_anywhere_credentials_provider_test.cc
test/extensions/common/aws/credential_providers/instance_profile_credentials_provider_test.cc
test/extensions/common/aws/credential_providers/webidentity_credentials_provider_test.cc
test/extensions/common/aws/metadata_fetcher_test.cc
test/extensions/common/aws/mocks.h
test/extensions/common/aws/region_provider_impl_test.cc
test/extensions/common/aws/utility_test.cc

Commit Message: aws: improve test coverage
Additional Description: Removes multiple unreachable code paths. All other changes are just purely code coverage improvements within test cases.
Testing: Unit
Docs Changes:
Release Notes:

aws: improve test coverage

---

envoy/grpc/async_client_manager.h

Commit Message: grpc-config: minor perf to reduce a proto copy
Change a copy of a proto passed to a function to passing by ref.
Testing: N/A

grpc-config: minor perf to reduce a proto copy

---

test/extensions/filters/network/ext_proc/ext_proc_integration_test.cc

network_ext_proc: improve intergation tests due to TCP read segmentation

---

docs/root/configuration/http/http_filters/compressor_filter.rst

Commit Message: docs: fix typo in compressor_filter.rst
Testing: N/A
Docs Changes: fix typo

docs: fix typo in compressor_filter.rst

---

source/common/listener_manager/filter_chain_manager_impl.cc
source/common/listener_manager/filter_chain_manager_impl.h

Additional Description: Refactor for #39141, the code extracted to utility methods will be later used by a new method
Testing: current tests

filter_chain_manager: refactor by extracting to utility methods

---

bazel/aspect.patch
bazel/repositories.bzl
bazel/repository_locations.bzl

Missing YQ broke docs build. Reverting it for now.

Revert "deps: bump up aspect_bazel_lib to v2.17.1 (#39719)"

---

source/extensions/filters/network/redis_proxy/command_splitter_impl.cc
source/extensions/filters/network/redis_proxy/command_splitter_impl.h
test/extensions/filters/network/redis_proxy/command_splitter_impl_test.cc

Commit Message: redis_proxy: Add full implementation of select
Additional Description: The implementation of the SELECT command in the existing [PR #37706](https://github.com/envoyproxy/envoy/pull/37706) was incorrect. It only modified the client’s visible state without actually changing the selected database. This PR provides a proper implementation of the SELECT command.
Testing:unit test
Release Notes:

redis_proxy: Add full implementation of select

---

source/common/router/BUILD
source/common/router/config_impl.cc
source/common/router/config_impl.h
source/common/router/delegating_route_impl.h
source/common/router/header_cluster_specifier.cc
source/common/router/header_cluster_specifier.h

Commit Message: Split the cluster header as implmentation of cluster specifier plugin.
I will split the weighted cluster out also at next PR.
Testing: n/a.

Split the cluster header as implmentation of cluster specifier plugin.

---

.bazelrc
mobile/.bazelrc

and quieten warnings about impending disappearance of 8

bazel/java: Bump language version -> 11

---

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc

Adding an integration test to demonstrate below case
1)  Ext_proc with FULL_DUPLEX_STREAMED body mode
2) If client HTTP request does not contain trailers
3) the ext_proc server synthesize a trailer response and sends it back to Envoy
Such synthesized trailer response is ignored by Envoy and never reaches the backend server.

Ext_proc: Adding an integration test to demonstrate ext_proc server synthesized trailer response is ignored by Envoy

---

.github/workflows/_check_coverage.yml
.github/workflows/_finish.yml
.github/workflows/_load.yml
.github/workflows/_load_env.yml
.github/workflows/_precheck_publish.yml
.github/workflows/_publish_publish.yml
.github/workflows/_request.yml
.github/workflows/_request_cache_bazel.yml
.github/workflows/_request_cache_docker.yml
.github/workflows/_request_checks.yml
.github/workflows/_run.yml
.github/workflows/codeql-daily.yml
.github/workflows/codeql-push.yml
.github/workflows/command.yml
.github/workflows/envoy-dependency.yml
.github/workflows/envoy-release.yml
.github/workflows/envoy-sync.yml
.github/workflows/mobile-android_build.yml
.github/workflows/mobile-ios_build.yml

Reverts envoyproxy/envoy#40077

Revert "build(deps): bump envoyproxy/toolshed from actions-v0.3.20 to 0.3.21"

---

contrib/kafka/filters/network/source/broker/rewriter.cc

Commit Message: [kafka] Fix incorrect exception code
Additional Description: This isn't java, we don't `new` everything.

[kafka] Fix incorrect exception code

---

source/common/http/filter_manager.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

http: remove unnecessry dead code

---

OWNERS.md
SECURITY-INSIGHTS.yml
reviewers.yaml

Promote krinkinmu to maintainer

---

ci/Dockerfile-buildkit
ci/Dockerfile-distroless-testing
ci/Dockerfile-envoy
ci/do_ci.sh
ci/docker_ci.sh

Fix https://github.com/envoyproxy/envoy/issues/40207
---------

[bp/1.32] ci/docker: Pin buildkit and test distroless build (#40209)

---

changelogs/current.yaml

changelogs: Add entry for dynatrace div by zero fix

---

test/extensions/upstreams/http/config_test.cc

Fix error message check to accommodate new protobuf

---

test/common/http/http_server_properties_cache_manager_test.cc

test: Fix error message to work with new protobuf

---

test/extensions/filters/listener/proxy_protocol/proxy_protocol_fuzz_test.cc

Fix proxy_protocol_fuzz_test config validation

---

test/extensions/config_subscription/grpc/xds_failover_integration_test.cc

Commit Message: tests: avoid flakes in xds_failover_integration_test-GoogleGrpc case by waiting for a stream before disconnecting
A ~recent gRPC library upgrade caused it to automatically reconnecting to the server if the TLS handshake did not complete, which caused the test to not detect that the connection was terminated.
This PR updates the GoogleGrpc tests that emulate a disconnection, so they first waits for a stream to be established, and then disconnects.
Testing: N/A

tests: avoid flakes in xds_failover_integration_test-GoogleGrpc case by waiting for a stream before disconnecting

---

source/common/common/BUILD
source/common/common/radix_tree.h
test/common/common/radix_tree_test.cc

This PR refactors the Radix Tree code to make it cleaner. It also add some more tests to improve the overall coverage.
---
**Commit Message:** radix_tree: refactor the code to make it cleaner
**Additional Description:** Refactors the Radix Tree implementation to make it cleaner.
**Testing:** Unit Tests

radix_tree: refactor the code to make it cleaner

---

ci/docker-compose.yml
ci/run_envoy_docker.sh

also removes no longer used/tested windows container support

ci/docker: Update run_envoy_docker.sh to use docker compose

---

source/extensions/tracers/fluentd/fluentd_tracer_impl.cc
source/extensions/tracers/fluentd/fluentd_tracer_impl.h
test/extensions/tracers/fluentd/tracer_impl_test.cc
test/extensions/tracers/fluentd/tracer_integration_test.cc

Commit Message: tracing: clean up code of fluentd to eliminate unnecessary copy/const ructing
Clean up the code of fluentd to eliminate unnecessary copy/constructing and all unnecessary thao code.
Testing: n/a.

tracing: clean up code of fluentd to eliminate unnecessary copy/construction

---

api/envoy/extensions/stat_sinks/open_telemetry/v3/open_telemetry.proto
changelogs/current.yaml
docs/root/api-v3/config/trace/opentelemetry/resource_detectors.rst
source/extensions/stat_sinks/open_telemetry/BUILD
source/extensions/stat_sinks/open_telemetry/config.cc
source/extensions/stat_sinks/open_telemetry/open_telemetry_impl.cc
source/extensions/stat_sinks/open_telemetry/open_telemetry_impl.h
source/extensions/tracers/opentelemetry/opentelemetry_tracer_impl.cc
source/extensions/tracers/opentelemetry/resource_detectors/dynatrace/config.cc
source/extensions/tracers/opentelemetry/resource_detectors/dynatrace/config.h
source/extensions/tracers/opentelemetry/resource_detectors/environment/config.cc
source/extensions/tracers/opentelemetry/resource_detectors/environment/config.h
source/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector.cc
source/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector.h
source/extensions/tracers/opentelemetry/resource_detectors/resource_detector.h
source/extensions/tracers/opentelemetry/resource_detectors/resource_provider.cc
source/extensions/tracers/opentelemetry/resource_detectors/resource_provider.h
source/extensions/tracers/opentelemetry/resource_detectors/static/config.cc
source/extensions/tracers/opentelemetry/resource_detectors/static/config.h
source/extensions/tracers/opentelemetry/resource_detectors/static/static_config_resource_detector.h
test/extensions/stats_sinks/open_telemetry/config_test.cc
test/extensions/stats_sinks/open_telemetry/open_telemetry_impl_test.cc
test/extensions/tracers/opentelemetry/opentelemetry_tracer_impl_test.cc
test/extensions/tracers/opentelemetry/resource_detectors/dynatrace/config_test.cc
test/extensions/tracers/opentelemetry/resource_detectors/environment/config_test.cc
test/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector_test.cc
test/extensions/tracers/opentelemetry/resource_detectors/resource_provider_test.cc
test/extensions/tracers/opentelemetry/resource_detectors/static/config_test.cc
test/extensions/tracers/opentelemetry/resource_detectors/static/static_config_resource_detector_test.cc

Expose API to support configuring resource attribute in OTLP statSink

statSink: add resource attributes for otlp statSink

---

source/common/config/type_to_endpoint.cc

Commit Message: cleanup: remove redundant line in a list
This is just a cleanup that removes a redundant line in a list (see the line above).
Testing: N/A

cleanup: remove redundant line in a list

---

source/common/http/conn_manager_impl.cc

It is not enabled on all toolchains.

Use specific type to avoid template argument deduction

---

test/common/config/datasource_test.cc

Add missing include fstream

---

test/coverage.yaml

This PR adjusts the latest LCOV numbers per the current state.
---
**Commit Message:** coverage: adjusting coverage numbers to reflect current state
**Additional Description:** This PR adjusts the latest LCOV numbers per the current state.

coverage: adjusting coverage numbers to reflect current state

---

test/common/router/config_impl_test.cc

Make test work with newer absl::Status

---

test/common/router/router_test.cc

Commit Message: test: removing a test code that is never executed
Removing the test `RouterShadowingTest/BufferingShadowWithClusterHeader` that is always skipped.
This was introduced in #40659.
Testing: N/A

test: removing a test code that is never executed

---

source/common/router/router.h

Remove unused streaming_shadows_ variable

---

OWNERS.md

Add Dan Zhang as EM and QUIC maintainer

---

source/common/quic/envoy_quic_client_stream.cc
source/common/quic/envoy_quic_server_stream.cc

Prep for future QUICHE update.

Add missing includes

---

source/extensions/filters/http/stateful_session/stateful_session.cc
source/extensions/filters/http/stateful_session/stateful_session.h

Risk Level:
Testing:
Docs Changes:
Release Notes:

stateful session: fix statefulSessionConfig typo

---

test/common/stats/thread_local_store_test.cc

Commit Message: cleanup: followup on PR 40606 - cleaning the tests
Minor cleanup for the histogram tests that were updated in #40606.
Testing: N/A

cleanup: followup on PR 40606 - cleaning the tests

---

source/extensions/filters/http/proto_message_extraction/extraction_util/extraction_util.cc
source/extensions/filters/http/proto_message_extraction/extraction_util/proto_extractor.cc
tools/testdata/check_format/serialize_as_string.cc

Fix protobuf namespace alias

---

tools/repo/notify.py

Commit Message: tools: update notifier script to handle calendar fetching and parsing errors
The current maintainer oncall calendar link is not working, and will probably require updating opsgenie (which is unclear what can be done there at the moment).
This PR introduces graceful handling of errors in the script that fetches the current oncaller.
Risk Level: low - script only
Testing: Executed manually - `bazel run //tools/repo:notify -- --dry_run` 

tools: update notifier script to handle calendar fetching and parsing errors

---

api/envoy/config/common/mutation_rules/v3/mutation_rules.proto
changelogs/current.yaml
source/common/http/BUILD
source/common/http/header_mutation.cc
source/common/http/header_mutation.h
source/extensions/filters/http/header_mutation/config.cc
source/extensions/filters/http/header_mutation/header_mutation.cc
source/extensions/filters/http/header_mutation/header_mutation.h
source/extensions/http/early_header_mutation/header_mutation/config.cc
source/extensions/http/early_header_mutation/header_mutation/header_mutation.cc
source/extensions/http/early_header_mutation/header_mutation/header_mutation.h
test/common/http/BUILD
test/common/http/header_mutation_test.cc
test/extensions/filters/http/header_mutation/header_mutation_test.cc
test/extensions/http/early_header_mutation/header_mutation/BUILD
test/extensions/http/early_header_mutation/header_mutation/header_mutation_test.cc

Commit Message: header mutation: support remove on match
To close https://github.com/envoyproxy/envoy/issues/41067, https://github.com/envoyproxy/envoy/issues/21054, https://github.com/envoyproxy/envoy/issues/10778, https://github.com/envoyproxy/envoy/issues/34642
Testing: unit.

header mutation: support remove on match

---

api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto

This PR have some styling changes and small nits in the ExtAuthZ docs to make it consistent to rest of the docs.
---
**Commit Message:** docs: small nits in the ExtAuthZ docs
**Additional Description:** Some styling changes and small nits in the ExtAuthZ docs to make it consistent to rest of the docs.

docs: small nits in the ExtAuthZ docs

---

.github/workflows/envoy-dependency.yml

temporarily pending resolution to #41168

github/ci: Disable scheduled CVE checker

---

docs/root/configuration/http/http_filters/header_mutation_filter.rst

This PR refactored the Header Mutation filter docs and added some more info on per-route and upstream config, etc.
---
**Commit Message:** docs: refactor header mutation filter docs and add more details
**Additional Description:** Refactored the Header Mutation filter docs and added some more info on per-route and upstream config, etc.

docs: refactor header mutation filter docs and add more details
