mobile/test/cc/integration/send_headers_test.cc
This fixes the ASAN test failure by releasing the `envoy_data` after use.
Testing: unit tests with ASAN
=> mobile: Fix send_headers_test ASAN failure for not releasing a memory

mobile/library/common/http/client.h
This PR cleans up the code in Envoy Mobile's `client.cc` by removing functions declarations that have no implementations.
Testing: CI
=> mobile: Remove function declarations without implementations

test/integration/base_integration_test.h, test/integration/xds_integration_test.cc
Having an unexpected request makes debugging significantly harder.
=> tests: don't always do tag extraction checks

source/extensions/filters/http/ext_proc/processor_state.cc
Clarify the ENVOY_BUG check condition that `chunk != nullptr` explicit.
=> ext_proc: Clarify the ENVOY_BUG

mobile/library/common/engine.cc, mobile/library/common/engine.h
The YAML `config` can be pretty big, so passing by const reference is more efficient than passing by value.
=> mobile: Pass by const reference instead of value in Engine::run

source/extensions/path/match/uri_template/uri_template_match.cc, source/extensions/path/match/uri_template/uri_template_match.h
Commit Message: Avoid compiling regex in every match, instead pre-compile regex on constructor
Testing:
Docs Changes:
Release Notes:
=> uri_template: pre compile regex in uri template matcher

source/common/runtime/runtime_features.cc
Documenting that the framer changes should stick around longer than the usual reloadable flag cycle as they're higher risk changes.
=> runtime: documenting 2 unusual flags

mobile/library/cc/BUILD, mobile/library/common/BUILD, mobile/library/common/jni/BUILD, mobile/library/objective-c/BUILD, mobile/test/common/BUILD, mobile/test/common/stats/BUILD, mobile/test/non_hermetic/BUILD, mobile/test/performance/BUILD
`main_interface.(h|cc)` has been removed in https://github.com/envoyproxy/envoy/pull/32018. This PR updates the build target names to not have `main_interface` in the  name.
Risk Level: low (cosmetic changes)
Testing: CI
=> mobile: main_interface BUILD clean up

mobile/library/common/api/external.cc, mobile/library/common/api/external.h, mobile/library/common/jni/jni_impl.cc, mobile/test/common/common/lambda_logger_delegate_test.cc, mobile/test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_integration_test.cc, mobile/test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc
`string&&` makes it clear on setting that the `name` param will be `std::move`'d when creating the key.
`string_view` for lookup because flat_hash_map supports heterogenous lookups: https://abseil.io/docs/cpp/guides/container#heterogeneous-lookup
=> mobile: API registration takes string&&, retrieval takes string_view

mobile/library/cc/engine.cc, mobile/library/cc/engine.h, mobile/library/common/engine.cc, mobile/library/common/engine.h, mobile/library/common/jni/jni_impl.cc, mobile/library/objective-c/EnvoyEngineImpl.mm, mobile/test/common/engine_test.cc
This PR is needed as part of unifying the two `Engine` code. With this change, `Platform::Engine` will simply delegate its tasks to `Envoy::Engine`.
=> mobile: Consolidate dumpStats and terminate implementations to common/engine.cc

mobile/test/non_hermetic/BUILD
This build target does not run as part of CI, that's why we didn't catch this issue.
=> mobile: Fix build error target name

docs/root/faq/configuration/sni.rst
Commit Message: docs: add missing typed_config for tls_inspector
Additional Description: Without typed_config, the following error is returned: "Didn't find a registered implementation for 'envoy.filters.listener.tls_inspector' with type URL: ''
Testing:
Docs Changes:
Release Notes:
=> docs: add missing typed_config for tls_inspector

source/common/http/http2/codec_impl.cc, source/common/http/http2/codec_impl.h
Hoists (Client|Server)ConnectionImpl::trackInboundFrames() to the base class, since they are identical.
Commit Message: http2: merges identical implementations of ConnectionImpl::trackInboundFrames()
Docs Changes:
Release Notes:
=> http2: merges identical implementations of ConnectionImpl::trackInboundFrames()

changelogs/current.yaml, source/common/http/http1/codec_impl.cc, source/common/runtime/runtime_features.cc, test/integration/overload_integration_test.cc
Commit Message: Runtime flag remove: Deprecated legacy code paths for allow-codec-error-after-1xx.
Testing:
Docs Changes:  release notes
Fixes #31976
=> Runtime flag remove: Deprecated legacy code paths for allow-codec-error-after-1xx.

contrib/golang/filters/http/source/go/pkg/http/capi_impl.go, contrib/golang/filters/http/source/go/pkg/http/filter.go, contrib/golang/filters/http/source/go/pkg/http/shim.go
fix #31654 and #29496 
Thanks @spacewander for founding this race:
`envoyGoRequestSemaDec` may be invoked eariler than `r.sema.Wait`, then, there is no one to resume the `r.sema.Wait`.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> golang http fitler: fix race when waiting callback from Envoy

contrib/golang/common/go/api/api.h, contrib/golang/filters/http/source/config.cc, contrib/golang/filters/http/source/go/pkg/http/config.go, contrib/golang/filters/http/source/go/pkg/http/shim.go, contrib/golang/filters/http/source/golang_filter.cc, contrib/golang/filters/http/source/golang_filter.h, contrib/golang/filters/http/test/config_test.cc, contrib/golang/filters/http/test/golang_filter_fuzz_test.cc, contrib/golang/filters/http/test/golang_filter_test.cc
The current HTTP Go filter utilizes a sync.Map to manage the lifecycle of the requests memory between Go and C++. Envoy instances that have a larger number of workers (>=32), the sync.Map causes contention on the underlying lock and reduces performance.
Before this fix, a direct reply benchmark would get about `210,000 req/sec` which is considerably lower than `400,000 req/sec` (Envoy that uses a direct reply within a route with no Go HTTP filter). The same benchmark with this fix included gets `350,000 req/sec`, a 67% increase in performance.
The `sync.Map` is replaced with a `[]map[*C.httpRequest]*httpRequest` which allows each worker to get its own map. This slice is initialized `envoyGoFilterNewHttpPluginConfig` which now passes along the `concurrency` value that Envoy was started …
=> Go HTTP Filter: Improve performance

test/common/quic/envoy_quic_client_session_test.cc
Commit Message: the unit test hard coded ip version to be v6 and hasn't needed to use real I/O on the socket util recent. Test `StatelessResetOnProbingSocket` needs to call sendmsg() on the socket, so if the environment doesn't support v6, the sys call will fail.
Testing: verified StatelessResetOnProbingSocket passes on v4 environment.
=> quic: fix client session test

source/extensions/filters/common/expr/context.cc, source/extensions/filters/common/expr/context.h, source/extensions/filters/common/expr/evaluator.cc, test/extensions/filters/common/expr/context_test.cc, test/extensions/filters/http/wasm/test_data/metadata_rust.rs, test/extensions/filters/http/wasm/test_data/test_cpp.cc, test/extensions/filters/http/wasm/wasm_filter_test.cc
Commit Message: fixes an early exit due to empty stream info when calling xds attributes during configuration
Testing: added
Docs Changes:
=> wasm: fix xds node during configuration

contrib/golang/common/go/api/filter.go, contrib/golang/filters/http/source/go/pkg/http/filter.go, contrib/golang/filters/http/source/go/pkg/http/shim.go, contrib/golang/filters/network/source/go/pkg/network/filter.go
Adds new functions to the Go SDK `EnvoyConcurrency()` and `StreamInfo.WorkerID()`. This information will allow Go HTTP plugins to optimize their performance in certain use cases. Follow up from #31987
cc @doujiang24  
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Go HTTP Filter: Expose envoy concurrency and request worker_id in public API

api/envoy/config/route/v3/route_components.proto, changelogs/current.yaml, source/common/http/utility.cc, source/common/runtime/runtime_features.cc, test/common/http/utility_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #31971
=> chore: remove `append_x_forwarded_host_idempotent` runtime flag

test/per_file_coverage.sh
Coverage CI is failing because coverage is too low in source/common/io because CI is not executing io_uring code. #32149
=> coverage: lower coverage for source/common/io/

mobile/library/java/org/chromium/net/impl/CronvoyEngineBuilderImpl.java, mobile/library/java/org/chromium/net/impl/CronvoyLogger.java, mobile/library/java/org/chromium/net/impl/CronvoyUrlRequestContext.java
This PR updates the Cronvoy's `EngineBuilder` API to allow setting the log level and custom logger implementation similar to the standard `EngineBuilder` API. For backward compatibility, the log level will be set to `OFF` and the custom logger will be set to the default `CronvoyLogger` implementation.
Testing: tests
=> mobile: Update Cronvoy API to allow setting log level and logger

changelogs/current.yaml, source/common/tcp_proxy/tcp_proxy.cc, source/extensions/filters/udp/udp_proxy/config.h, test/integration/tcp_tunneling_integration_test.cc, test/integration/udp_tunneling_integration_test.cc
Additional Description: Currently, if ``propagate_response_headers`` option is enabled, either for UDP tunneling and TCP tunneling, and retry is also enabled, the second HTTP response headers will cause a crash in Envoy, since the first filter state object is set with ``ReadOnly`` attribute. Fixing this by changing to ``Mutable`` with relevant tests that check this use case.
=> tunneling: fix propagateResponseHeaders in retry cases

test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc
It is causing test flakes and friction on CI. I was able to reproduce this, and the crash happens in
https://github.com/envoyproxy/envoy/blob/faec43168bb50028b4b4351f477dfef40e0fb227/test/integration/fake_upstream.h#L714.
But I'm not sure cause, so will disable it for now until we have deflaked it.
See https://github.com/envoyproxy/envoy/issues/32151 for details.
=> test: Disable recently added AltSvcCachedH2Slow

mobile/test/common/integration/client_integration_test.cc
The `ResetWithBidiTrafficExplicitData` was crashing sporadically with memory errors when run for HTTP3. Running with msan showed that the crashes were caused in `headers_callback.setReady()` being called after the test finished and member variables of the test were already destroyed.
I noticed that in the test, we didn't call `headers_callback.waitReady()` when the test was running for HTTP3.  It wasn't clear to me why, but that seemed like the cause.  I removed the if-guard so we always call `headers_callback.waitReady()`, and the test seems to pass now (over 500 runs).
Fixes #32024
=> mobile: Fix a flake in the ClientIntegrationTest

changelogs/current.yaml, contrib/golang/common/go/api/filter.go, contrib/golang/filters/http/source/go/pkg/http/config.go, contrib/golang/filters/http/source/go/pkg/http/filtermanager.go, contrib/golang/filters/http/source/go/pkg/http/passthrough.go, contrib/golang/filters/http/source/go/pkg/http/shim.go, contrib/golang/filters/http/test/test_data/access_log/config.go, contrib/golang/filters/http/test/test_data/action/config.go, contrib/golang/filters/http/test/test_data/basic/config.go, contrib/golang/filters/http/test/test_data/buffer/config.go, contrib/golang/filters/http/test/test_data/dummy/plugin.go, contrib/golang/filters/http/test/test_data/echo/config.go, contrib/golang/filters/http/test/test_data/metric/config.go, contrib/golang/filters/http/test/test_data/passthrough/filter.go, contrib/golang/filters/http/test/test_data/property/config.go, contrib/golang/filters/http/test/test_data/routeconfig/config.go, examples/golang-http/simple/config.go
We followed the C++ style to register configFactory, but it's not a proper choice for Golang filter.
Here is the Reasons:
1. Golang introduced the ConfigParser interface to Parse/validate a config, configFactory does not need to parse config.
2. better performance. By using fiterFactory, we could ommit generate a closure per http request, that may take ~1ns.
Yep, this is a breaking change, people need to change the register API.
So, I suggest we fix it earlier.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> golang filter: change register configFactory to filterFactory

mobile/library/common/common/system_helper.cc, mobile/library/common/common/system_helper.h, mobile/test/common/mocks/common/mocks.h
Prior to this PR, the `SystemHelper::instance_` was a `std::unique_ptr`, which means there could be a  possibility that the `SystemHelper::instance_`'s destructor gets called upon program termination while the cert verification thread is still running causing `SystemHelper::getInstance()` to return a destroyed instance. This PR fixes the issue by making the `SystemHelper::instance_` a raw pointer, such that the destructor is never called.
Testing: CI
=> mobile: Update the singleton instance to never call its destructor

contrib/generic_proxy/filters/network/source/router/router.cc, contrib/generic_proxy/filters/network/test/router/router_test.cc
Commit Message: generic proxy: only create child span if the spawnUpstreamSpan return true
Not all tracers require dual-spans. This patch fix a minor bug of generic proxy tracing where always create the upstream span for the upstream request.
Testing: n/a.
=> generic proxy: only create child span if the spawnUpstreamSpan return true

source/common/api/posix/os_sys_calls_impl.cc
The fallback is pointless since accept will fail for the same reasons as accept4. However it creates coverage problem since the fallback code is not covered by tests.
=> Remove fallback from accept4 to accept

test/integration/multiplexed_integration_test.cc
In my repro attempts, I saw failures with both the `nghttp2` and `oghttp2` codecs.
Addresses the bulk of the failures from https://github.com/envoyproxy/envoy/issues/32132.
Tested via:
```
$ baze test --config=clang-tsan --config=remote test/integration:multiplexed_integration_test \
--runs_per_test=1000 --test_filter='IpVersions/Http2FrameIntegrationTest.CloseConnectionWithDeferredStreams/*' \
--test_sharding_strategy=disabled
```
With the timeout extension, I saw 1 failure in 1000 runs, which is significantly better than before.
Commit Message: Increases a test timeout to avoid flaky failures
Risk Level: none, tests only
Testing: ran 1000 iterations of the suspicious test case
Docs Changes:
Release Notes:
=> test: increases a test timeout to avoid flaky failures

bazel/envoy_binary.bzl, bazel/envoy_build_system.bzl, bazel/envoy_test.bzl, test/integration/BUILD, test/integration/run_envoy_test.sh, test/tools/router_check/BUILD
Dynamic linking prevents build failure due to size of coverage instrumentation.
This PR changed two known problematic binaries.
=> Link test binaries dynamically for coverage builds

bazel/cel-cpp.patch
Additional Description: As described in the linked issue, on macOS (at least in some OS/compiler combos) there is a linker error in CEL. The missing symbol is specified as a weak symbol. The definition of the function is in `cel-cpp/extensions/protobuf:data`. As far as I can tell, only a test in CEL actually builds that target; Envoy does not build that target, so this function will not ever be compiled into Envoy. So commenting out the block in this PR should not have behavior change to how Envoy uses CEL.
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes #31932
=> macos: fix linker error from CEL library

changelogs/current.yaml, source/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector.cc, test/extensions/tracers/opentelemetry/resource_detectors/environment/BUILD, test/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector_integration_test.cc, test/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector_test.cc
Commit Message: Not crash envoy when env resource detector can't detect attributes
Testing: Unit/Integration/Manual 
[Optional Runtime guard:] 
[Optional Fixes #32225]
=> opentelemetry tracer: Not crash envoy when environment resource detector can't detect attributes

source/extensions/http/early_header_mutation/header_mutation/config.cc, source/extensions/http/original_ip_detection/custom_header/config.cc, test/common/formatter/command_extension.cc, test/extensions/filters/http/common/fuzz/uber_per_filter.cc, test/extensions/filters/network/common/fuzz/uber_per_readfilter.cc
Replace dynamic_cast with a protobuf method that can work even when RTTI is disabled.
=> Use protobuf's DynamicCastToGenerated instead of dynamic_cast<>

source/common/network/io_socket_handle_base_impl.cc, test/common/network/io_socket_handle_impl_test.cc
In the mobile world, `getifaddrs` sometimes returns ERRNO 19 (`ENODEV`). Given that `interfaceName()` is designed to return an optional anyway, release assert is not the right thing to do here and instead, we log a warning and return `nullopt`.
`interfaceName()` is mainly used for logging purposes, so this change seems low risk.
=> network: Allow interfaceName() to gracefully handle getifaddrs failures

test/integration/xfcc_integration_test.cc
Given it's a worker thread related stat, this makes sure the worker threads are up and registered.
hopefully fixes https://github.com/envoyproxy/envoy/issues/32237
=> test: hopefully deflaking tag extraction test

docs/root/intro/arch_overview/listeners/listener_filters.rst
docs: Fix incorrect link in listener_filters.rst
The docs currently link to network filters instead of listener filters.
Testing: Generated preview and confirmed link works
=> docs: Fix incorrect link in listener_filters.rst

mobile/library/common/network/connectivity_manager.cc
ConnectivityManager's enumerateInterfaces relies on getifaddrs. However, getifaddrs could fail for a number of reasons. Instead of RELEASE_ASSERT'ing, which causes crashes, we log the failure and return an empty vector of interfaces, similar to how if there is no support for getifaddrs.
=> mobile: Allow ConnectivityManager to handle getifaddrs failures

bazel/envoy_internal.bzl, mobile/.bazelrc
Having `-fno-unwind-tables` will cause the crashes to not have any useful backtrace information. This PR removes `-fno-unwind-tables` when exceptions are disabled.
Risk Level: low (only Envoy Mobile has exceptions disabled)
Testing: CI
Platform Specific Features: mobkle
=> mobile: Remove -fno-unwind-tables

.bazelrc
this fixes an issue where clang was checking the wrong c++ function signatures and throwing errors/warnings
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel/rc: Add `-fsized-deallocation` to cxx opts

changelogs/current.yaml, source/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector.cc, test/extensions/tracers/opentelemetry/resource_detectors/environment/BUILD, test/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector_integration_test.cc, test/extensions/tracers/opentelemetry/resource_detectors/environment/environment_resource_detector_test.cc
As discussed with @wbpcode I'm creating this backport to 1.29 for this bug. We just merged this feature in Istio and would be great if this can be ported, so maybe the current to be release Istio version can have this. 
Commit Message: Backport from https://github.com/envoyproxy/envoy/pull/32229
Testing: Unit, Integration and Manual
=> [bp/1.29] Not crash envoy when env resource detector can't detect attributes

source/common/http/http2/codec_impl.cc, test/common/http/codec_impl_corpus/content_length_mismatch-5806467830579200
This ASSERT triggers with a specific `codec_impl_fuzz_test.cc` input, but the condition itself appears arbitrary. For the purpose of code correctness, it doesn't matter whether the error code passed in is NO_ERROR or something else.
All unit and integration tests continue to pass without the ASSERT in place.
```
$ bazel test --config=remote test/integration/... test/common/http/...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: a59c05fc-a314-4957-8e1c-188bfbec3704
INFO: Analyzed 507 targets (714 packages loaded, 37077 targets configured).
INFO: Found 361 targets and 146 test targets...
INFO: Elapsed time: 920.573s, Critical Path: 849.49s
INFO: 4318 processes: 2722 remote cache hit, 158 internal, 1438 remote.
INFO: Build completed successfully, 4318 total actions …
```
=> http2: removes an unnecessary ASSERT

mobile/.bazelrc
Envoy Mobile requires `--define=signal_trace=disabled`. This PR makes `--define=signal_trace=disabled` to be the default and removes a lot of `--define=signal_trace=disabled` in the Envoy Mobile Bazel configs.
Risk Level: low (clean up)
Testing: CI
=> mobile: Set --define=signal_trace=disabled to be the default

test/tools/router_check/test/BUILD
Running this test does not produce useful coverage and disabling it does not affect coverage numbers.
=> Exclude //test/tools/router_check/test:router_tool_test from coverage builds

mobile/bazel/kotlin_lib.bzl, mobile/bazel/kotlin_test.bzl, mobile/library/kotlin/io/envoyproxy/envoymobile/BUILD, mobile/test/java/io/envoyproxy/envoymobile/engine/AndroidNetworkMonitorTest.java, mobile/test/java/io/envoyproxy/envoymobile/engine/BUILD, mobile/test/kotlin/io/envoyproxy/envoymobile/BUILD, mobile/test/kotlin/io/envoyproxy/envoymobile/GRPCStreamTest.kt, mobile/test/kotlin/io/envoyproxy/envoymobile/mocks/BUILD, mobile/test/kotlin/io/envoyproxy/envoymobile/mocks/MockEnvoyEngine.kt, mobile/test/kotlin/io/envoyproxy/envoymobile/mocks/MockEnvoyHTTPStream.kt, mobile/test/kotlin/io/envoyproxy/envoymobile/mocks/MockStream.kt, mobile/test/kotlin/io/envoyproxy/envoymobile/mocks/MockStreamClient.kt, mobile/test/kotlin/io/envoyproxy/envoymobile/mocks/MockStreamPrototype.kt
Prior to this PR, building `//library/kotlin/io/envoyproxy/envoymobile:envoy_interfaces_lib` would also include the mocks, which is not ideal. This PR moves the mocks from `library` to `test` and uses Bazel `associates` attribute in `kt_jvm_library` to allow accessing `internal` code without having to include the mocks into the `library` JAR.
Testing: CI
=> mobile: Move mocks from library to test

mobile/library/cc/engine_builder.cc, mobile/test/cc/unit/BUILD, mobile/test/cc/unit/envoy_config_test.cc
Cronet sets the UDP receive buffer size to 1MB:
https://source.chromium.org/chromium/chromium/src/+/main:net/quic/quic_session_pool.cc;l=839;drc=7dc3003765c74daa4bb49e4463e3a7963d8c7ea1
If we don't set the receive buffer size explicitely, the operating system defaults are used, which are typically too small for UDP.
=> mobile: Set the socket receive buffer size to 1MB for QUIC

changelogs/current.yaml, source/common/http/conn_manager_utility.cc, source/common/http/conn_manager_utility.h, test/common/http/conn_manager_utility_test.cc, test/integration/protocol_integration_test.cc
Official grpc library [does not allow empty TE header](https://github.com/grpc/grpc/blob/master/src/core/ext/filters/http/server/http_server_filter.cc#L102). This causes an issue when proxying requests through Envoy which currently deletes the TE header since https://github.com/envoyproxy/envoy/pull/30535.
I opened a related MR on the grpc library to allow this header to be empty as the HTTP/2 RFC allows it but it might cause issues with other libraries.
Risk Level: medium (behavioral change)
Testing: modified an existing test
Runtime guard: keep the previous one
=> http: keep `trailers` TE header instead of removing it

changelogs/current.yaml, source/extensions/filters/http/jwt_authn/extractor.cc, test/extensions/filters/http/jwt_authn/extractor_test.cc
Commit Message: jwt: do not concatenate duplicated headers
Duplicated headers should not be concatenated with a comma, because comma is not allowed in a JWT token, so concatenation invalidates tokens.
This PR fixes #31468. 
Risk Level:
Release Notes:
=> jwt: do not concatenate duplicated headers

examples/lua/envoy.yaml
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> fix missing "|" in inline_string  lua examples

changelogs/current.yaml, docs/root/intro/arch_overview/other_protocols/redis.rst, source/extensions/filters/network/common/redis/supported_commands.h, source/extensions/filters/network/redis_proxy/command_splitter_impl.cc, test/extensions/filters/network/redis_proxy/command_splitter_impl_test.cc
Commit Message: redis proxy: add support for echo command
Testing: Unit test added
Fixes #31459
=> redis-proxy: support echo command

changelogs/current.yaml, source/extensions/filters/http/jwt_authn/extractor.cc, test/extensions/filters/http/jwt_authn/extractor_test.cc
Duplicated headers should not be concatenated with a comma, because comma is not allowed in a JWT token, so concatenation invalidates tokens. This PR fixes https://github.com/envoyproxy/envoy/issues/31468.
Risk Level:
Release Notes:
=> [bp/1.28] jwt: do not concatenate duplicated headers (#32248)

changelogs/current.yaml, source/extensions/filters/http/jwt_authn/extractor.cc, test/extensions/filters/http/jwt_authn/extractor_test.cc
Duplicated headers should not be concatenated with a comma, because comma is not allowed in a JWT token, so concatenation invalidates tokens. This PR fixes #31468.
Risk Level:
Release Notes:
=> [bp/1.29] jwt: do not concatenate duplicated headers (#32248)

envoy/common/optref.h, test/common/common/optref_test.cc
Commit Message: optref: supporting nullopt conversion
Followup to #32256 addressing a case where the conversion is for nullopt.
Risk Level: low - new code
=> optref: supporting nullopt conversion

mobile/test/objective-c/BUILD, mobile/test/swift/BUILD, mobile/test/swift/RetryPolicyTests.swift, mobile/test/swift/integration/BUILD, mobile/test/swift/stats/BUILD
This allows the test to run on RBE instead of the local CI machines, speeding up the CI run time (hopefully).
Tests that start an `EnvoyTestServer` must still have the `no-remote-exec` tag because they try to bind a 
local socket, which is not permitted on the remote environments (we get errors to this effect, e.g. https://github.com/envoyproxy/envoy/actions/runs/7893306052/job/21541684998#step:8:2268).
=> mobile: Remove the no-remote-exec tag for most iOS tests

source/common/http/http2/codec_impl.cc, source/common/http/http2/codec_impl.h
These log statements were accidentally omitted in the refactoring performed in https://github.com/envoyproxy/envoy/pull/31878.
This change also removes the redundant frame type argument from `ConnectionImpl::onBeginData()`.
```
$ bazel test //test/common/http/http2/... //test/integration/...
INFO: Invocation ID: 2516e9a0-c488-4630-93d9-a01e0e81d5c3
INFO: Analyzed 397 targets (0 packages loaded, 0 targets configured).
INFO: Found 295 targets and 102 test targets...
INFO: Elapsed time: 752.367s, Critical Path: 750.91s
INFO: 399 processes: 1 remote cache hit, 399 remote.
INFO: Build completed successfully, 399 total actions
Executed 102 out of 102 tests: 102 tests pass.
```
Commit Message: http2: restores some log statements, simplifies onBeginData() …
=> http2: restores some log statements, simplifies onBeginData()

mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidProxyMonitor.java
In Java, doing an equality comparison using `==` will only return true if the two instances are the same object. If they are not the same object, the `==` will return false. Using `equals()` is a safer way of doing an equality comparison.
Testing: CI
=> mobile: Fix possible inequality bug

source/common/http/conn_pool_grid.cc, test/common/http/conn_pool_grid_test.cc
I think somewhere in our journey from drain idle callbacks to drain enums we didn't handle this correctly.
I don't know if any call sites do Envoy::ConnectionPool::DrainBehavior::DrainExistingConnections then Envoy::ConnectionPool::DrainBehavior::DrainAndDelete but I think we should pass all drain calls to inner pools.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> grid: fixing double drain behavior

source/common/http/conn_pool_grid.cc, source/common/http/conn_pool_grid.h, test/common/http/conn_pool_grid_test.cc
Fixing an issue where the grid didn't always inform newStream subscribers of stream creation fail on teardown.
Fixing a second issue where on teardown, we might try to fail from UDP to TCP.
Testing: fixes a mobile RTDS flake, new unit test
=> grid: fixing a teardown bug

test/mocks/stream_info/mocks.h
Without this move constructor, this mock does not build in newer versions of gtest.
=> stream_info: Add a move constructor the the ResponseFlag matcher

changelogs/current.yaml, source/common/http/http1/balsa_parser.cc, test/common/http/http1/codec_impl_test.cc
Commit Message: [balsa] Backport line folding support to 1.28
Additional Description: Backport #31080 (test-only) and #31168 to release 1.28 to support obsolete line folding in BalsaParser
Release Notes: Enable obsolete line folding in BalsaParser.
=> [balsa] Backport line folding support to 1.28

source/common/http/async_client_impl.cc, source/common/http/async_client_impl.h, test/common/http/async_client_impl_test.cc
Commit Message: Guarantee reset after complete for async streams does not crash.
Additional Description: This is a rare race condition when the shadow streaming flag is on. envoy-security has already been notified of this crash and has decided that since it is protected by a default-off flag and is a rare race condition, it is OK to fix in the open.
=> Guarantee reset after complete for async streams does not crash.

bazel/BUILD, contrib/all_contrib_extensions.bzl, contrib/exe/BUILD
Previously, the ARM build with FIPS enabled was failing when building on main with this commit https://github.com/envoyproxy/envoy/commit/92bc83698450258650a2b7d20216abbb819ad1be
```
ERROR: /go/src/github.com/DataDog/envoy/contrib/exe/BUILD:31:16: Illegal ambiguous match on configurable attribute "deps" in //contrib/exe:envoy-static:
//bazel:linux_aarch64
//bazel:boringssl_fips
```
This adds `config_setting_group` to make the match explicit - that is, we will skip the `qatzip` extension
for FIPS + AMD or ARM.
This relates to https://github.com/envoyproxy/envoy/pull/31910, which added a fix for the v1.29.0 build with FIPS + AMD.
Risk Level:
Testing: built an image in our CI with FIPS enabled and targeting aarch64, `bazel build --compilation_mode=opt …
=> contrib: Fix build for fips arm

.gitattributes
This ensures that the files in the working tree always use `lf` line termination, even on Windows.
This should resolve various issues with tooling.
I believe this preserves the git conversion `lf` <> `crlf` - which is important for any new files added to repo in a windows env (i believe vscode will honour existing line termination for a file, but use the os default on new files)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> repo/windows: Enforce `lf` line endings for local checkout

test/common/router/BUILD
Disable a fuzz test under fuzz-coverage that uses a statically linked binary that can no longer link with coverage instrumentation due to size.
=> Disable test/common/router:route_fuzz_test under fuzz-coverage

bazel/envoy_test.bzl, mobile/library/cc/BUILD, mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h, mobile/library/objective-c/EnvoyConfiguration.h, mobile/library/objective-c/EnvoyConfiguration.mm, mobile/library/objective-c/EnvoyEngine.h, mobile/library/objective-c/EnvoyEngineImpl.mm, mobile/library/swift/EngineBuilder.swift, mobile/library/swift/mocks/MockEnvoyEngine.swift, mobile/test/cc/unit/BUILD, mobile/test/common/integration/BUILD, mobile/test/common/integration/client_integration_test.cc
Previously, Apple proxy resolution API registration only happened in the Objective-C engine. For those Apple/iOS users using the C++ APIs directly, we need to support proxy resolution API registration in the C++ EngineBuilder as well.
This commit also moves the Objective-C API registration to the same place where other API registration (e.g. key-value store) takes place.
Lastly, to add tests for this, we had to add the Apple CFNetwork and CoreFoundation frameworks to the linkopts, which required envoy_cc_test being able to take in an optional linkopts to add to its defaults.
=> mobile: Add Apple proxy resolution APIs to the C++ EngineBuilder

bazel/repository_locations.bzl
Docs Changes: Fix license URL of QATzip
=> docs: fix the license URL of QATzip

test/extensions/filters/http/common/fuzz/filter_corpus/create_filter_factory_from_proto_not_ok, test/extensions/filters/http/common/fuzz/uber_filter.cc
Commit Message: Check createFilterFactoryFromProto is ok before accessing its value
Additional Description: This was causing the following fuzz error: https://oss-fuzz.com/testcase-detail/5123115348721664
Testing: Added fuzz test case
=> Check createFilterFactoryFromProto is ok before accessing its value

source/extensions/filters/http/cache/cache_filter.cc, test/extensions/filters/http/cache/cache_filter_test.cc
Commit Message: [http-cache-filter] limit cache read chunk size to buffer size
Additional Description: Before this change, the cache filter will request the entire body of a cache entry in a single request from its associated cache extension, and both existing cache extensions would try to simply fulfill the request. When a file is very large, this results in trying to load an entire very large file into memory, which typically leads to a crash.
This change makes the cache filter request only the amount of data that would fill the streaming buffer per chunk, which should make it more tolerant of very large cache entries. If there is no buffer limit, an arbitrary 64MB limit is imposed.
Risk Level: Very small; change is to a WIP filter and addresses an existing crash.
Testing: Added unit …
=> [http-cache-filter] limit cache read chunk size to buffer size

source/extensions/transport_sockets/tls/io_handle_bio.cc, source/extensions/transport_sockets/tls/io_handle_bio.h, test/extensions/transport_sockets/tls/io_handle_bio_test.cc
Rather than reaching into private structures, Envoy should stick to supported public APIs. This covers both the implementation and the tests. I did my best to salvage io_handle_bio_test.cc, as it was previously testing mostly incoherent things. However, it warrants another pass by Envoy folks.
What you all should be testing is that *public* BIO APIs correctly call the underlying io_handle operations.  Instead, the old tests mostly forcibly called the underlying function pointers with cases that will never be called in the first place. (E.g. the destroy callback will never be called with a null BIO.)
I've also removed the BIO_CTRL_SET_CLOSE (BIO_set_close) bits as it seems to be entirely dead code. Envoy never actually configures the BIO to close the io_handle when …
=> tls: Fix Envoy reaching into private structures in io_handle_bio.cc

source/extensions/common/tap/tap_config_base.cc, test/extensions/common/tap/admin_test.cc, test/extensions/filters/http/common/fuzz/filter_corpus/tap_filter_admin
Commit Message: tap: rejecting invalid config that requires an admin
Rejecting a config that requires TAP to output to an admin-based output when the admin isn't configured.
Testing: Added corpus.
Fixes fuzz issue [55142](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55142)
=> tap: rejecting invalid config that requires an admin

mobile/library/cc/engine_builder.cc, mobile/test/cc/unit/envoy_config_test.cc
https://github.com/envoyproxy/envoy/pull/32370 introduced the allow_client_socket_creation_failure runtime guard, but had to default it to off due to test failures.
In Envoy Mobile, we are turning it on as it's been the source of assert failures.
=> mobile: Set the allow_client_socket_creation_failure runtime guard

mobile/library/jni/jni_impl.cc
This PR replaces manual calls to `DeleteLocalRef` with RAII-style deletion.
=> mobile: Remove manual DeleteLocalRef calls

source/common/quic/envoy_quic_client_session.cc, source/common/quic/envoy_quic_client_session.h
Commit Message: change EnvoyQuicClientSession to downcast transport socket factory to QuicTransportSocketFactoryBase instead of QuicClientTransportSocketFactory. 
Additional Description: this will enable the usage of other upstream transport socket extensions for QUIC.
Testing: existing test passed
=> quic: loosen transport socket factory downcast type

test/run_envoy_bazel_coverage.sh
The regular expressions currently used to extract clang and LLVM versions in `run_envoy_bazel_coverage.sh` can include spurious non-version characters which can result in an accidental mismatch.
This change revises the expressions assuming that clang and LLVM versions will always match `[0-9.]*`, the characters expected in semantic versioning, which should be a reasonable assumption.
Testing:
`./ci/run_envoy_docker.sh ./ci/do_ci.sh coverage` should succeed
=> ci/coverage: revise regex for extracting clang and LLVM versions

mobile/library/cc/stream_callbacks.cc, mobile/library/common/types/c_types.h, mobile/library/jni/jni_impl.cc, mobile/library/objective-c/EnvoyHTTPStreamImpl.mm, mobile/test/common/http/client_test.cc, mobile/test/common/main_interface_test.cc
Remove the Envoy callbacks to return `void` instead of `void *` since we never care about the return values. Prior to this PR, in an implementation like JNI, we would return a raw JNI local reference, which would not be automatically deleted causing the number of JNI local references to go up.
Risk Level: low (the return values are never used)
Testing: CI
=> mobile: Change the return type to void from void* in the callbacks

test/common/stream_info/uint32_accessor_impl_test.cc
Additional Description: found some non-tested functions in UInt32AccessorImpl
=> add unit tests for uint32_accessor

.github/workflows/envoy-macos.yml, .github/workflows/mobile-compile_time_options.yml, .github/workflows/mobile-ios_build.yml, .github/workflows/mobile-ios_tests.yml, .github/workflows/mobile-release_validation.yml, mobile/ci/mac_ci_setup.sh
The default github action runners have ANDROID_HOME and ANDROID_NDK_HOME set automatically. Because of this our bazel logic requires android to be installed. For jobs that don't request android explicitly we now unset this to save that install CI time. This also changes the CI setup to actively source the mac_ci_setup script since previously those env vars would be ignored, since github actions sources the text listed there, but not each line
This reverts commit f37ef3ff03bb78035e80b65159c0ec35b7544e0d.
=> Revert "mobile/ci: Fix iOS build failures (#31756)"

mobile/test/swift/BUILD, mobile/test/swift/cxx/BUILD, mobile/test/swift/integration/BUILD
This will turn off RBE for the Swift tests.  This will make the Swift tests go slower, but right now they are timing out at a regular rate on CI, seemingly due to DNS timeouts on the MacOS machines.
See https://github.com/envoyproxy/envoy/issues/31957 for details.
Opened https://github.com/envoyproxy/envoy/issues/32551 to find a fix that allows us to use RBE with the Swift tests.
=> mobile/ci: Tag the Swift tests with `no-remote-exec`

changelogs/current.yaml, source/extensions/tracers/opentelemetry/resource_detectors/dynatrace/dynatrace_resource_detector.cc, test/extensions/tracers/opentelemetry/resource_detectors/dynatrace/dynatrace_resource_detector_test.cc
Commit Message: Dynatrace OTel resource detector: Only log failure when no enrichment file is found
Additional Description: Today, the resource detector logs a warn message, whenever any of the Dynatrace enrichment files is not present. This is a bug, because it is normal for a file to not exist. The files are injected depending on the environment (k8s or not for ex). It is only a problem when ALL files are not present. Then in that case, Dynatrace is not properly deployed and the user should be able to know via the Dynatrace UI/Deployment page.
Testing: Unit tests added
[Optional [API …
=> dynatraceresourcedetector: Only log message when no enrichment file is found

source/docs/logging.md
Additional Description: adding docs that explain the usage for ENVOY_TAGGED_LOG kind of macros
Docs Changes: source dev docs
=> source_docs: add tagged log macros documentation

source/common/quic/BUILD, source/common/quic/envoy_quic_client_stream.cc, source/common/quic/envoy_quic_client_stream.h, source/common/quic/envoy_quic_server_stream.cc, source/common/quic/envoy_quic_server_stream.h, source/common/quic/envoy_quic_stream.cc, source/common/quic/envoy_quic_stream.h, source/common/quic/quic_stats_gatherer.cc
quic: remove duplicate code in QUIC `encodeData()`, `encodeMetadata()` and `encodeTrailers()` implementations
Add a `QuicSpdyStream&` member to `EnvoyQuicStream` so that the `encodeData()`, `encodeMetadata()` and `encodeTrailers()` implementation can be moved to EnvoyQuicStream and out of the subclasses.
=> quic: remove duplicate code in QUIC encodeData(), encodeMetadata() and encodeTrailers() implementations

source/extensions/filters/network/thrift_proxy/router/router.h, source/extensions/filters/network/thrift_proxy/router/router_impl.cc, source/extensions/filters/network/thrift_proxy/router/shadow_writer_impl.cc
own our scope by `createScope` as shadow request could have as long as the lifecycle of thread local storage
Risk Level: mid
Testing: unit
[Optional Fixes #Issue] #32234
=> use createScope to guruantee longer lifetime than shadow writer

bazel/io_opentelemetry_cpp.patch, bazel/repositories.bzl
Fixes https://github.com/envoyproxy/envoy/issues/32591
=> bazel: fix opentelemetry-cpp warning

tools/code_format/check_format.py, tools/code_format/envoy_build_fixer.py, tools/code_format/header_order.py
Commit Message: Fix warnings/errors after upgrading to python3.12.2.
example error:
./tools/code_format/check_format.py:260: SyntaxWarning: invalid escape sequence '\s'  return re.compile("^\s*namespace\s+%s\s*{" % self.namespace_check, re.MULTILINE)
Testing:
Docs Changes:
Release Notes:
=> tools: fix python regex warnings for newer python

source/extensions/filters/network/zookeeper_proxy/decoder.cc, test/extensions/filters/network/zookeeper_proxy/filter_test.cc
Commit Message: [ZK filter] Add missing operation supports for multi opcode
Additional Description: The ZK filter did not support some operations for the multi opcode based on the [ZK source code](https://github.com/apache/zookeeper/blob/58eed9f5280be1c6a9ccacc47dd6afa65e916ae8/zookeeper-server/src/main/java/org/apache/zookeeper/MultiOperationRecord.java#L97-L105). This could lead to decode errors. This PR tries to fill this gap by adding the opcode support of `Create2`, `CreateContainer`, `CreateTtl`, `GetChildren`, and `GetData` for the `Multi` operation.
=> [ZK filter] Add missing operation supports for multi opcode

changelogs/current.yaml, source/common/runtime/runtime_features.cc
Commit Message: xDS: enable envoy.restart_features.use_eds_cache_for_ads by default
Caching of EDS responses was added in #28273 and we have been using it internally.
This PR flips the runtime guard to be true by default.
This solves the issue of not receiving EDS assignments after receiving a cluster update (in a CDS response).
Risk Level: medium - may impact memory, but should not impact data-plane/config-plane behavior
Testing: updated in previous PRs
Docs Changes: updated in previous PRs
=> xDS: enable envoy.restart_features.use_eds_cache_for_ads by default

envoy/tcp/async_tcp_client.h, source/common/tcp/async_tcp_client_impl.cc, source/common/tcp/async_tcp_client_impl.h, test/common/tcp/async_tcp_client_impl_test.cc, test/integration/filters/test_network_async_tcp_filter.cc, test/integration/tcp_async_client_integration_test.cc
Additional Description: small modifications to allow reconnecting in ``TcpAsyncClient`` along with tests
Testing: unit tests, integration tests
=> TcpAsyncClient: enhance reconnect robustness

changelogs/current.yaml, source/common/network/listen_socket_impl.cc, source/common/network/listen_socket_impl.h, source/common/runtime/runtime_features.cc
Allowing graceful client socket creation failure by default in Envoy
Testing: yes
[Optional Runtime guard:] yes.
=> sockets: flipping graceful client socket creation failure

api/bazel/repositories.bzl, bazel/repositories.bzl
Commit Message: Change udpa renaming workaround to not compile the same archive twice
Additional Description: I copied the prior workaround into a different build environment and it caused linker errors in one subset of the space, which made it clear that the repo was downloaded and compiled twice in the bazel cache under different paths. This change fixes that.
Risk Level: None - if it builds it's better.
Testing: If it builds it ships.
=> Change udpa renaming workaround to not compile the same archive twice

.github/workflows/_cache.yml, .github/workflows/_finish.yml, .github/workflows/_load.yml, .github/workflows/_load_env.yml, .github/workflows/_request.yml, .github/workflows/_run.yml, .github/workflows/_stage_publish.yml, .github/workflows/_stage_verify.yml, .github/workflows/_start.yml, .github/workflows/codeql-daily.yml, .github/workflows/codeql-push.yml, .github/workflows/command.yml, .github/workflows/envoy-dependency.yml, .github/workflows/envoy-release.yml, .github/workflows/envoy-sync.yml, .github/workflows/garbage.yml, .github/workflows/mobile-android_build.yml, .github/workflows/mobile-ios_build.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/logging: Add failure detection

source/extensions/filters/network/thrift_proxy/filters/payload_to_metadata/payload_to_metadata_filter.cc, source/extensions/filters/network/thrift_proxy/filters/payload_to_metadata/payload_to_metadata_filter.h, test/extensions/filters/network/thrift_proxy/filters/payload_to_metadata/payload_to_metadata_filter_test.cc
Previously we rely on `fieldBegin` right before `structBegin` to determine this is not top-level struct.
i.e., `fieldBegin structBegin structEnd fieldEnd` sequence.
However, while we have a list of struct, this assumption doesn't hold since the structure inside a container inherits the field id of the container.
i.e., we had `fieldBegin listBegin (structBegin structEnd)*n listEnd fieldEnd` sequence.
Therefore, introduce a stack of field ids so could we track field id better.
In the added unit test, it hits assertion before fix.
Testing: unit
=> Fix null node for list of struct in payload_to_metadaata filter

test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc
After some upstream changes, the test no longer seems to flake.
Tested with:
```
bazelisk test --runs_per_test=500 --test_output=streamed
--cache_test_results=no
--test_arg="--gtest_filter=*FilterIntegrationTest*AltSvcCachedH2Slow*"
test/extensions/filters/http/alternate_protocols_cache:filter_integration_test
```
Fixes #32151
=> mobile: Reenable the FilterIntegrationTest.AltSvcCachedH2Slow test

source/common/http/filter_manager.cc
OTherwise it is not clear which filter triggered the bug.
Commit Message: Logging:  include filter name for decodeHeaders ENVOY_BUG.
Testing: ran tests
=> Logging: ENVOY_BUG include filter name.

changelogs/current.yaml, source/common/grpc/BUILD, source/common/grpc/google_grpc_creds_impl.cc, source/common/runtime/runtime_features.cc, test/common/grpc/BUILD, test/common/grpc/grpc_client_integration_test.cc, test/common/grpc/grpc_client_integration_test_harness.h
Backport of https://github.com/envoyproxy/envoy/pull/32315
=> [1.28] google_grpc: add a runtime flag to disable TLSv1.3 (#32532)

changelogs/current.yaml, source/common/grpc/BUILD, source/common/grpc/google_grpc_creds_impl.cc, source/common/runtime/runtime_features.cc, test/common/grpc/BUILD, test/common/grpc/grpc_client_integration_test.cc, test/common/grpc/grpc_client_integration_test_harness.h
Backport of https://github.com/envoyproxy/envoy/pull/32315
=> [1.26] google_grpc: add a runtime flag to disable TLSv1.3 (#32532)

source/extensions/filters/http/rate_limit_quota/client_impl.cc, source/extensions/filters/http/rate_limit_quota/filter.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> rlqs: add logging around token bucket

changelogs/current.yaml, source/common/runtime/runtime_features.cc, source/common/stream_info/utility.cc, test/common/http/conn_manager_impl_test.cc, test/common/stream_info/utility_test.cc
DurationTimeout -> ConnectionTimeout
UnauthorizedExternalService -> ConnectionRefused
DownstreamConnectionTermination -> ConnectionTerminated
OverloadManager -> ConnectionLimitReached
DropOverLoad -> ConnectionLimitReached
FaultInjected -> HttpRequestError
Testing:
Docs Changes:
Release Notes:
=> proxy status: add more mapping to proxystatus

changelogs/current.yaml, docs/root/intro/arch_overview/http/http3.rst, source/common/quic/quic_client_transport_socket_factory.cc, source/common/quic/quic_client_transport_socket_factory.h, test/common/http/conn_pool_grid_test.cc, test/common/http/http3/conn_pool_test.cc, test/common/quic/client_connection_factory_impl_test.cc, test/common/quic/quic_transport_socket_factory_test.cc, test/integration/base_integration_test.cc, test/integration/base_integration_test.h, test/integration/http_integration.cc, test/integration/quic_http_integration_test.cc, test/integration/utility.cc, test/integration/utility.h
Envoy as a community is not in the habit of moving "GA" code to alpha. It was believed at the time that HTTP/3 upstream code had been deployed successfully in production but based on the severity of the bug fixed here it appears that was not the case.  Changing security status to reflect the current perceived code stability.
Testing: e2e test
Docs Changes: inline
=> http3: fixing an upstream threading issue and bumping http3 upstream code back to alpha

api/envoy/config/trace/v3/zipkin.proto, changelogs/current.yaml, source/extensions/tracers/zipkin/span_context.h, source/extensions/tracers/zipkin/tracer.cc, source/extensions/tracers/zipkin/tracer.h, test/extensions/tracers/zipkin/tracer_test.cc
Commit Message: zipkin: deprecate split_spans_for_request by the unified spawn_upstream_span
Enable the `spawn_upstream_span` support for the zipkin tracer and deprecated the legacy `split_spans_for_request`.
Testing: unit.
=> zipkin: deprecate split_spans_for_request by the unified spawn_upstream_span

mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h, mobile/test/common/internal_engine_test.cc
Implement a `setLogger` in the C++ `EngineBuilder` API. This is to allow delegating the Envoy logger into a different logging implementation depending on the platform. This change also aims to make the C++ API more consistent with other language APIs.
Risk Level: low (new function)
=> mobile: Implement setLogger in the C++ API

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
`SetHostHeaderRoutingSucceeded` : ext_proc triggers route re-pick and set host header to match the domain of virtual host in routing configuration.  This makes routing to upstream successful.
`SetHostHeaderRoutingFailed`:  ext_proc triggers route re-pick but set host header to wrong header that doesn't match the  virtual host domain in routing configuration.  This makes routing to upstream failed since no route is found.
`GetAndSetPathHeader`: when `allow_all_routing` is false, path header is updated successfully but routing header mutation(e.g., host, method, scheme) are failed
=> ext_proc: Validate route re-pick and routing/path header mutation

changelogs/current.yaml, source/common/grpc/BUILD, source/common/grpc/google_grpc_creds_impl.cc, source/common/runtime/runtime_features.cc, test/common/grpc/BUILD, test/common/grpc/grpc_client_integration_test.cc, test/common/grpc/grpc_client_integration_test_harness.h
Backport of https://github.com/envoyproxy/envoy/pull/32315
=> [1.27] google_grpc: add a runtime flag to disable TLSv1.3 (#32532)

changelogs/current.yaml, source/common/quic/envoy_quic_client_connection.h, source/common/runtime/runtime_features.cc
Commit Message: change the current behavior from reading up to 16 * number of in-flight requests to reading 32 packets per-connection.
Risk Level: low, HTTP/3 upstream is in Alpha now
Runtime guard: envoy.reloadable_features.quic_upstream_reads_fixed_number_packets
=> quic: upstream connections read 32 packets per loop

source/extensions/filters/network/zookeeper_proxy/decoder.cc, test/extensions/filters/network/zookeeper_proxy/filter_test.cc
Commit Message: [ZK filter] Fix CreateTTL request parse
Additional Description: CreateTTL request is different from other create requests. It has additional ttl data at the end of payload ([reference](https://github.com/apache/zookeeper/blob/de7c5869d372e46af43979134d0e30b49d2319b1/zookeeper-jute/src/main/resources/zookeeper.jute#L150)). This PR tries to let ZK filter parse CreateTTL request correctly and avoid potential decode errors.
=> [ZK filter] Fix CreateTTL request parse

envoy/network/BUILD, envoy/network/parent_drained_callback_registrar.h, envoy/network/socket.h, envoy/server/hot_restart.h, source/common/listener_manager/listener_manager_impl.cc, source/common/network/BUILD, source/common/network/listen_socket_impl.h, source/common/network/udp_listener_impl.cc, source/common/network/udp_listener_impl.h, source/server/BUILD, source/server/hot_restart_impl.cc, source/server/hot_restart_impl.h, source/server/hot_restart_nop_impl.h, source/server/hot_restarting_child.cc, source/server/hot_restarting_child.h, test/common/network/BUILD, test/common/network/udp_listener_impl_batch_writer_test.cc, test/common/network/udp_listener_impl_test.cc, test/common/network/udp_listener_impl_test_base.h, test/integration/python/hotrestart_handoff_test.py, test/mocks/network/BUILD, test/mocks/network/mock_parent_drained_callback_registrar.h, test/mocks/server/hot_restart.h, test/server/hot_restart_impl_test.cc, test/server/hot_restarting_child_test.cc
Commit Message: QUIC hot restart part 6 - child instance pauses listening until parent is drained (second try)
Additional Description: This is a redo of #31130 which was reverted in #32658. For ease of review, pushed as two commits, the revert that duplicates the original PR, and the small fix with a mutex. (I mistakenly thought the listeners were created on the main thread, but apparently they are created on the worker threads.)
Risk Level: A little, for quic with hot restart.
Testing:
```
bazel test -c dbg --config=clang-asan //test/integration/python:hotrestart_handoff_test --runs_per_test=50
```
Passes after the fix, fails 5 of 50 with a pointer error before the fix.
=> QUIC hot restart part 6 - child instance pauses listening until parent is drained (second try)

test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
Commit Message: Add integration tests for ext_authz timeout
Additional Description: This PR adds integration tests for the http and grpc implementations of ext_authz. For each, it tests the fail open and fail closed modes. It also tests that ext_authz's `failure_mode_allow_header_add` config works as expected for the fail open cases.
Testing: test-only PR
=> Add integration tests for ext_authz timeout

source/common/tls/BUILD
Commit Message: build: remove incorrect cc_library after tls code move
Additional Description: This fixes building `//source/...` or generating a compile_commands.json
```
ERROR: /source/common/tls/BUILD:13:17: //source/common/tls:config, aspect @bazel_compdb//:aspects.bzl%compilation_database_aspect: missing input file '//source/common/tls:config.h'
ERROR: //source/common/tls:config, aspect @bazel_compdb//:aspects.bzl%compilation_database_aspect 1 input file(s) do not exist
```
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> build: remove incorrect cc_library after tls code move

changelogs/current.yaml, source/extensions/tracers/opentelemetry/BUILD, source/extensions/tracers/opentelemetry/grpc_trace_exporter.h, source/extensions/tracers/opentelemetry/http_trace_exporter.cc, source/extensions/tracers/opentelemetry/otlp_utils.cc, source/extensions/tracers/opentelemetry/otlp_utils.h, test/extensions/tracers/opentelemetry/grpc_trace_exporter_test.cc, test/extensions/tracers/opentelemetry/http_trace_exporter_test.cc
Commit Message: opentelemetrytracer: Add User-Agent header to OTLP trace exporters
Additional Description: The [OpenTelemetry specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.30.0/specification/protocol/exporter.md#user-agent) defines that OTLP exporters should emit the User-Agent header to help identify the the source/exporter. This PR adds such header to both the OTLP gRPC and HTTP exporters.
[Optional Fixes #Issue] 
=> opentelemetrytracer: Add User-Agent header to OTLP trace exporters

source/common/grpc/codec.cc, source/common/grpc/codec.h, test/common/grpc/codec_test.cc
**The workflow:**
-  Client of gRPC decoder configure the  `max_frame_length`  via `setMaxFrameLength()`
-  If `max_frame_length`  is configured and total length exceeds the limit, the future decoding process will be skipped and returned
**The use case/ motivation**: Enable `max_receive_message_length` in Envoy-gRPC (which use gRPC decoder) . 
-  When the message is over limit, it can be rejected  before frame data [is fully decoded (i.e. expanded](https://github.com/envoyproxy/envoy/blob/ffbf1889ef788ccb4b1d0e402ed2c3976d7204fd/source/common/grpc/async_client_impl.cc#L144)). 
- This can prevent malicious attack , for example, unbounded and huge message is sent over channel and is injected and buffered in Envoy over Envoy-gRPC.
**Next step**:  
- Refactor `bool Decoder::decode` method: …
=> grpc: Add support for max frame length in gPRC frame decoding

mobile/library/java/io/envoyproxy/envoymobile/engine/BUILD, mobile/library/java/io/envoyproxy/envoymobile/engine/ByteBuffers.java, mobile/library/java/io/envoyproxy/envoymobile/engine/JvmCallbackContext.java, mobile/library/java/io/envoyproxy/envoymobile/engine/JvmFilterContext.java, mobile/library/java/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPFilter.java, mobile/library/jni/jni_helper.cc, mobile/library/jni/jni_helper.h, mobile/library/jni/jni_impl.cc, mobile/library/jni/jni_utility.cc, mobile/library/jni/jni_utility.h, mobile/test/java/io/envoyproxy/envoymobile/engine/BUILD, mobile/test/java/io/envoyproxy/envoymobile/engine/ByteBuffersTest.java, mobile/test/java/io/envoyproxy/envoymobile/jni/JniHelperTest.java, mobile/test/java/io/envoyproxy/envoymobile/utilities/ByteBuffersTest.java, mobile/test/jni/jni_helper_test.cc
This PR updates the JNI code to use direct `ByteBuffer` to pass the data between C++ and Java. This change helps to reduce the number of copying needed, especially between `jbyteArray` (C++) and `byte[]` (Java). The direct `ByteBuffer` is backed by `envoy_data` without any copy.
Before:
1. `Buffer:Instance` is created by Envoy.
2. Create `envoy_data` from `Buffer::Instance` by copying.
3. Create `jbyteArray` from `envoy_data` by copying.
4. Pass the `jbyteArray` (C++) to `byte[]` (Java). This typically involves a copy, but it's implementation dependent.
5. Wrap the `byte[]` into `ByteBuffer` (no copy, memory managed by the JVM).
After:
1. `Buffer:Instance` is created by Envoy.
2. Create `envoy_data` from `Buffer::Instance` by copying.
3. Wraps the `envoy_data` into direct `ByteBuffer` (no …
=> mobile: Use direct ByteBuffer to pass data between C++ and Java

envoy/http/BUILD, envoy/http/header_map.h, source/common/http/BUILD, source/common/http/header_map_impl.cc, source/common/http/header_map_impl.h, source/common/tcp_proxy/BUILD, source/common/tcp_proxy/tcp_proxy.cc, source/common/tcp_proxy/tcp_proxy.h, source/extensions/filters/udp/udp_proxy/config.cc, source/extensions/filters/udp/udp_proxy/config.h
Commit Message: Common TunnelResponseHeadersOrTrailers for UDP & TCP tunneling
Testing:
=> Common TunnelResponseHeadersOrTrailers for UDP & TCP tunneling

mobile/test/common/integration/test_server.cc
Commit Message: the test failed after https://github.com/envoyproxy/envoy/pull/32260 because the test server uses a mocked MockTransportSocketFactoryContext which doesn't return a real  ContextManager object in sslContextManager(). The mocked object returns nullptr in createSslServerContext(), thus fail to initialize the new member ssl_ctx_ in QuicServerTransportSocketFactory.
Additional Description: bazel test //test/java/io/envoyproxy/envoymobile/engine/testing:quic_test_server_test passes in this PR
=> mobile: fix quic_test_server_test

mobile/library/java/io/envoyproxy/envoymobile/engine/JvmCallbackContext.java, mobile/library/java/io/envoyproxy/envoymobile/engine/JvmFilterContext.java, mobile/library/java/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPFilter.java
This PR does the following cleanup:
- Fixed typos.
- Used generic types instead of raw types.
- Used lambda expression instead of anonymous class.
- Removed unused imports.
Risk Level: low (cosmetic changes only)
Testing: CI
=> mobile: Java code cleanup

source/common/upstream/upstream_impl.cc, source/extensions/clusters/dynamic_forward_proxy/cluster.cc, source/extensions/clusters/dynamic_forward_proxy/cluster.h, test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc
reintroduces https://github.com/envoyproxy/envoy/issues/30999 :-/
=> dfp: reverting 31433

changelogs/current.yaml, source/common/runtime/runtime_features.cc
http2: Switch the value of envoy.reloadable_features.http2_use_oghttp2 to false
A number of users have reported issues with oghttp2 including #32611 and #32401 
so reverting this flag seems wise.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> http2: Switch the value of envoy.reloadable_features.http2_use_oghttp2 to false

contrib/golang/filters/network/test/BUILD, contrib/golang/filters/network/test/config_test.cc, contrib/golang/filters/network/test/upstream_test.cc, contrib/kafka/filters/network/test/mesh/BUILD, contrib/kafka/filters/network/test/mesh/config_unit_test.cc, contrib/kafka/filters/network/test/mesh/shared_consumer_manager_impl_unit_test.cc, contrib/kafka/filters/network/test/mesh/upstream_kafka_facade_unit_test.cc, test/mocks/thread/mocks.h
This cleans up the tests to use `Envoy::Thread::MockThreadFactory` to reduce code duplication.
Testing: CI
=> test: Use Envoy::Thread::MockThreadFactory

changelogs/current.yaml, source/common/runtime/runtime_features.cc
Commit Message: This reverts commit 136f7fd53f0546d8abf6f42a8293ff91fd573eef.
We are investigating a race between cluster destruction and EDS caching removal.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Revert "xDS: enable envoy.restart_features.use_eds_cache_for_ads by default (#32604)"

test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc
It's still flaky and causing failures on CI.
See https://github.com/envoyproxy/envoy/issues/32151.
=> test: Disable the FilterIntegrationTest.AltSvcCachedH2Slow test (again)

source/extensions/filters/http/oauth2/filter.cc, test/extensions/filters/http/oauth2/filter_test.cc
Commit Message: Remove extraneous and deprecated version attribute on Set-Cookie
The oauth2 filter sets a `version` attribute on the cookies, which is obsolete per [RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265) (2011). It was specified in [RFC 2965](https://datatracker.ietf.org/doc/html/rfc2965) (2000) and [RFC 2109](https://datatracker.ietf.org/doc/html/rfc2109) (1997) but AFAICT, no browsers use this. The change should be a noop and is simply a code cleanup. Also removes the attribute in the request cookies in the tests (not sure if this even did anything, since it likely is parsed as a separate cookie entirely)
Testing: unit testing
[Optional …
=> oauth2: remove version attribute from Set-Cookie

test/common/filesystem/directory_test.cc
Commit Message: This test is right to be concerned about arbitrary iteration order. However, it failed to list `"file2"` as a possibility.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Deflake FileDeletedWhileIterating

source/server/server.cc, source/server/server.h
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> server: cleaning up some exception throwing

source/common/quic/platform/quiche_flags_impl.cc, test/common/runtime/runtime_impl_test.cc
These flags are leftover artifacts from the time when there were three different kind of flags in QUICHE. This PR is part of the effort to clean up QUICHE flag framework. See also
https://quiche.googlesource.com/quiche/+/b36587781c9532e3b0715ea522cca57dec561854
Commit Message: Remove spdy_testonly and http2_testonly flags.
Additional Description: These flags are leftover artifacts from the time when there were three different kind of flags in QUICHE. This PR is part of the effort to clean up QUICHE flag framework. See also https://quiche.googlesource.com/quiche/+/b36587781c9532e3b0715ea522cca57dec561854
Testing: test/common/runtime:runtime_impl_test
=> Remove spdy_testonly and http2_testonly flags.

tools/vscode/generate_debug_config.py
This PR updates `tools/vscode/generate_debug_config.py` to not run with `bazel build <target>.dwp` since it generates corrupted / truncated data. See also https://github.com/envoyproxy/envoy/issues/13578.
This fixes https://github.com/envoyproxy/envoy/issues/32700.
Risk Level: low (development tool only)
Testing: tested inside devcontainer and ran `tools/vscode/generate_debug_config.py //source/exe:envoy-static --args "-c configs/demo-envoy.yaml" --debugger lldb`
=> tools: Fix generate_debug_config.py

changelogs/current.yaml, source/extensions/filters/http/oauth2/filter.cc, test/extensions/filters/http/oauth2/filter_test.cc
Commit Message: oauth2: on refresh, replace instead of append cookies
The [issue](https://github.com/envoyproxy/envoy/issues/32771) has most of the context, but in short when we refresh the access token we aren't removing the existing access token cookie and instead are appending the new cookie, which is not valid.
Testing: unit testing. wrote the failing test first
Docs Changes:
Release Notes:
fixes https://github.com/envoyproxy/envoy/issues/32771
=> oauth2: on refresh, replace instead of append cookies

mobile/.github/CODEOWNERS
Envoy Mobile uses [envoy/CODEOWNERS](https://github.com/envoyproxy/envoy/blob/8714c2e537746862e459c154f7db586135c26e04/CODEOWNERS#L367-L368).
Testing: n/a
=> mobile: Delete outdated mobile CODEOWNERS

source/extensions/filters/http/cache/cache_filter.cc, source/extensions/filters/http/cache/cache_filter.h, source/extensions/filters/http/cache/cache_headers_utils.cc, source/extensions/filters/http/cache/cache_headers_utils.h, source/extensions/filters/http/cache/config.cc, test/extensions/filters/http/cache/BUILD, test/extensions/filters/http/cache/cache_filter_test.cc, test/extensions/filters/http/cache/cache_headers_utils_test.cc, test/extensions/filters/http/cache/cacheability_utils_test.cc, test/extensions/filters/http/cache/http_cache_implementation_test_common.cc, test/extensions/filters/http/cache/http_cache_implementation_test_common.h, test/extensions/filters/http/cache/http_cache_test.cc, test/extensions/http/cache/file_system_http_cache/file_system_http_cache_test.cc
Part of https://github.com/envoyproxy/envoy/issues/32792
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Stringmatcher: factory context for http cache filter

source/extensions/filters/common/rbac/engine_impl.cc, source/extensions/filters/common/rbac/engine_impl.h, source/extensions/filters/common/rbac/matchers.cc, source/extensions/filters/common/rbac/matchers.h, source/extensions/filters/common/rbac/utility.h, source/extensions/filters/network/dubbo_proxy/router/route_matcher.cc, source/extensions/filters/network/dubbo_proxy/router/route_matcher.h, test/extensions/filters/common/rbac/BUILD, test/extensions/filters/common/rbac/engine_impl_test.cc, test/extensions/filters/common/rbac/matchers_test.cc, test/extensions/filters/common/rbac/mocks.h, test/extensions/filters/http/rbac/rbac_filter_test.cc
Part of #32792
Testing:
Docs Changes:
Release Notes:
=> Stringmatcher: factory context for rbac, dubbo_proxy

api/bazel/cc_proto_descriptor_library/builddefs.bzl
This is a no-op, as Bazel already enables `--incompatible_merge_genfiles_directory` by default, which makes the distinction between `genfiles` and `bin` moot.
=> bazel: remove `output_to_genfiles = True`

test/integration/http_integration.cc
Commit Message: Down casting upstream transport socket factory to `QuicClientTransportSocketFactory` type is too strong, making the test function unusable for a different quic upstream transport socket factory extension.
Risk Level: N/A, test only
Testing: existing test pass
=> quic: remove unnecessary type cast in integration test

source/common/http/http3_status_tracker_impl.cc, test/common/http/http3_status_tracker_impl_test.cc
turns out we always ran with roughly this override in production
=> quic: lowering quic brokenness  timer

mobile/library/jni/android_network_utility.cc, mobile/library/jni/java_jni_support.cc, mobile/library/jni/jni_impl.cc, mobile/library/jni/jni_support.h, mobile/library/jni/ndk_jni_support.cc, mobile/test/jni/test_jni_impl.cc
The `jni_log_fmt` and `jni_log` functions have empty implementations and their uses are not very useful other than cluttering the code.
Testing: CI
=> mobile: Remove jni_log

source/server/BUILD
Caused by newer interval version.
=> Make the instance_interface dependency explicit

source/common/formatter/substitution_format_string.h, test/common/formatter/substitution_format_string_test.cc
Additional Description: Small refactor by extracting the part that parses formatters config in ``SubstitutionFormatStringUtils`` to a separate method, and using it in ``fromProtoConfig``. The motivation for this is allowing to create formatters and logger in cases the configuration does not use ``SubstitutionFormatString`` and would directly list the formatters config. Specifically this is meant for supporting formatters in Fluentd access logger (next PR).
=> access_logs: extract commands parsing to a separate method

mobile/.bazelrc
This PR does the following:
- Removes duplicate `--config=mobile-remote-ci-macos`.
- Removes `--define=envoy_mobile_swift_cxx_interop=disabled` because it is always set to `enabled` and the code does not build without it.
Testing: CI
=> mobile: Clean up .bazelrc for Swift

test/extensions/filters/http/file_system_buffer/BUILD
Attempt to deflake this test timeouts in compile time options build.
=> Shard file_system_buffer_integration_test to avoid bazel timeouts

test/integration/BUILD
Attempt to reduce number of timeout flakes we're witnessing.
=> test: bump shard count for idle_timeout_integration_test

test/common/tls/integration/BUILD, test/common/tls/integration/ssl_integration_test.cc, test/common/tls/integration/ssl_integration_test_base.cc, test/common/tls/integration/ssl_integration_test_base.h, test/extensions/transport_sockets/tap/BUILD, test/extensions/transport_sockets/tap/ssl_tap_integration_test.cc
Commit Message: tests: refactor SSL TAP tests
Moved SSL TAP based tests to be under the transport_socket/tap extension directory (old TODO).
Testing: N/A
=> tests: refactor SSL TAP tests

test/extensions/clusters/common/BUILD, test/extensions/clusters/common/logical_host_integration_test.cc
Adding an integration test to reproduce: https://github.com/envoyproxy/envoy/issues/32850
This test is able to reproduce the race issue when run with below command:
bazel test test/extensions/clusters/common:logical_host_integration_test  --config=clang-tsan --cache_test_results=no --runs_per_test=100   --config=remote
This test is used by all the approaches mentioned under https://github.com/envoyproxy/envoy/issues/32850 to verify the fix, including: https://github.com/envoyproxy/envoy/pull/32830.
This PR is to separate the test from protocol_integration_test.cc. And just to have a simple integration test using logical DNS cluster.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional …
=> Adding an integration test to reproduce a race issue with logical host.

mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestUsingAsyncProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestUsingProxyTest.kt, mobile/test/swift/integration/proxying/HTTPRequestUsingProxyTest.swift
They are causing issues on CI.
See https://github.com/envoyproxy/envoy/issues/33014.
=> mobile: Disable the Swift and Kotlin proxying tests

changelogs/current.yaml, source/common/http/conn_manager_utility.cc, source/common/http/conn_manager_utility.h, test/common/http/conn_manager_utility_test.cc, test/integration/protocol_integration_test.cc
Official grpc library does not allow empty TE header. This causes an issue when proxying requests through Envoy which currently deletes the TE header since #30535.
I (@quantumsheep ) opened a related MR on the grpc library to allow this header to be empty as the HTTP/2 RFC allows it but it might cause issues with other libraries.
Risk Level: medium (behavioral change)
Testing: modified an existing test
Runtime guard: keep the previous one
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
=> [bp/1.29] http: keep `trailers` TE header instead of removing it (#32255)

mobile/.bazelrc
It was defaulting to C++20 due to
https://github.com/envoyproxy/envoy/pull/32585, but for mobile, we are still on C++17. This change enables local builds to build with C++17 without encountering toolchain errors.
=> mobile: Force mobile-release-common build to use C++17

mobile/library/kotlin/io/envoyproxy/envoymobile/BUILD
The opt build should use the non-debug version of libenvoy_jni.so, not the other way around.
=> mobile: Make the opt AAR build use the non-debug .so file

mobile/library/cc/BUILD, mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h, mobile/library/common/BUILD, mobile/library/common/engine_types.h, mobile/library/common/internal_engine.cc, mobile/library/common/internal_engine.h, mobile/library/jni/jni_impl.cc, mobile/library/objective-c/EnvoyConfiguration.mm, mobile/library/objective-c/EnvoyEngineImpl.mm, mobile/test/common/internal_engine_test.cc
This PR adds a new API `EngineBuilder::setEngineCallbacks` to allow setting the `Engine` callbacks. It also deprecates `EngineBuilder::setOnEngineRunning` since the same thing can be achieved by using `EngineBuilder::setEngineCallbacks`.
By introducing `EngineBuilder::setEngineCallbacks`, the C++ API now has support for `on_exit` callback similar to the other languages. The goal is to make the C++ API a first-class citizen instead of a low-level implementation for the other languages.
Risk Level: low (not used)
=> mobile: Add EngineBuilder::setEngineCallbacks

api/envoy/extensions/access_loggers/fluentd/v3/fluentd.proto, changelogs/current.yaml, source/extensions/access_loggers/fluentd/config.cc, test/extensions/access_loggers/fluentd/BUILD, test/extensions/access_loggers/fluentd/fluentd_access_log_impl_test.cc, test/extensions/access_loggers/fluentd/fluentd_access_log_integration_test.cc
Additional Description: Adding option to provide formatters by extension to Fluentd access logger
Testing: unit tests, integration tests
=> fluentd_access_logger: add option for extended formatters

mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h, mobile/library/common/BUILD, mobile/library/common/engine_types.h, mobile/library/common/internal_engine.cc, mobile/library/common/internal_engine.h, mobile/library/common/logger/BUILD, mobile/library/common/logger/logger_delegate.cc, mobile/library/common/logger/logger_delegate.h, mobile/library/common/types/c_types.h, mobile/library/jni/jni_impl.cc, mobile/library/objective-c/EnvoyEngine.h, mobile/library/objective-c/EnvoyEngineImpl.mm, mobile/test/common/internal_engine_test.cc, mobile/test/common/logger/logger_delegate_test.cc
This PR removes the `envoy_logger` C wrapper type and replaces it with the standard C++ code.
=> mobile: Remove envoy_logger C wrapper type

api/bazel/api_build_system.bzl, api/bazel/repository_locations.bzl
Commit Message: Migrate from github.com/golang/protobuf to google.golang.org/protobuf
Additional Description: `github.com/golang/protobuf` has been superseded by `google.golang.org/protobuf`
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Migrate from github.com/golang/protobuf to google.golang.org/protobuf

mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h, mobile/test/common/internal_engine_test.cc
This PR adds `EngineBuilder::setLogLevel` and deprecates `EngineBuilder::addLogLevel`. The `EngineBuilder::setLogLevel` takes `Envoy::Logger::Logger::Levels` directly instead of `Envoy::Platform::LogLevel`, which is a wrapper around `Envoy::Logger::Logger::Levels`. Eventually, we will remove the `Envoy::Platform::LogLevel`.
Risk Level: low (a new function)
=> mobile: Add EngineBuilder::setLogLevel

mobile/library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java, mobile/library/jni/jni_impl.cc
The return type is `void`, so the JNI type should also be `void` instead of `jint`.
Testing: CI
=> mobile: Fix incorrect JNI signature for setLogLevel

mobile/test/cc/BUILD, mobile/test/cc/engine_test.cc, mobile/test/common/internal_engine_test.cc
This PR moves the tests that use `Envoy::Platform::EngineBuilder` to `engine_test.cc`. This change will also allow us to add more tests using the high-level `Envoy::Platform::Engine` C++ API.
Platform Specific Features:  n/a
=> mobile: Add Envoy::Platform::Engine tests

changelogs/current.yaml, source/common/config/well_known_names.cc
Commit Message: Expand worker_id tag matcher to include thread_local_cluster_manager
Additional Description: It was noticed in our local configuration (where we had a historical worker_id tag matcher) that our tag matcher conflicts with the default one and causes worker_id metrics not to be registered. However, there was one metric with a worker_id tag still being registered. My assumption is this was an oversight envoy-side, and that this one should be also picked up, which would make removing our custom tag matcher leave all the stats working correctly, rather than switching from `thread_local_cluster_manager` being the only one working, to `thread_local_cluster_manager` being the missing one.
Risk Level: Small, change is only to sunk metrics.
Testing: Same as it is for the rest of the …
=> Expand worker id tag matcher to include thread_local_cluster_manager

source/common/common/matchers.cc, source/common/common/matchers.h, source/extensions/string_matcher/lua/match.cc, source/extensions/string_matcher/lua/match.h, source/server/server.cc, test/common/router/route_fuzz_test.cc, test/extensions/string_matcher/lua/BUILD, test/extensions/string_matcher/lua/lua_test.cc, test/per_file_coverage.sh
Commit Message: Removes temporary extra classes, and moves to a better way to handle string matcher extension factories
Fixes #32792
Testing:
Docs Changes:
Release Notes:
=> Stringmatcher: cleanup temporary code

api/bazel/BUILD, api/bazel/api_build_system.bzl
Commit Message: pgv_plugin_go : Use protoc_gen_validate instead of envoy_api
Additional Description: protoc_gen_validate  has an official declaration of the pgv_plugin_go
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> pgv_plugin_go : Use protoc_gen_validate instead of envoy_api

test/common/upstream/BUILD, test/common/upstream/least_request_load_balancer_corpus/small_agression, test/common/upstream/least_request_load_balancer_fuzz_test.cc, test/common/upstream/round_robin_load_balancer_corpus/small_aggression, test/common/upstream/round_robin_load_balancer_fuzz_test.cc, test/common/upstream/zone_aware_load_balancer_fuzz_base.cc, test/common/upstream/zone_aware_load_balancer_fuzz_base.h
Commit Message: fuzz: adding constraint for slow-start aggression values
Alternative solution to #32506.
The SlowStartConfig has an aggression field, that if set to too small may cause the weights to be very small.
In this PR we limit the aggression value *of fuzz tests*  to be GTE than 1e-30, which I think should be small enough for a reasonable value.
Following [this comment](https://github.com/envoyproxy/envoy/pull/32506#issuecomment-1970047351), more work needs to be done to estimate the correct boundaries of configs.
Risk Level: low - fuzz tests only
Testing: N/A
=> fuzz: adding constraint for slow-start aggression values

test/common/tls/integration/ssl_integration_test.cc
Commit Message: tests: fixed & expanded checking of ocsp response
Additional Description: Expand the checking of OCSP response to check for expected length and bytes, to prevent false positive results.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tests: fixed & expanded checking of ocsp response

source/server/server.cc, test/server/server_test.cc
Change the lifecycle notifier to invoke callbacks after incrementing the iterator. This will allow callbacks to delete their registration handle when they are called.
=> Fix lifecycle notifier callback loop

test/extensions/common/async_files/async_file_handle_thread_pool_test.cc, test/extensions/http/cache/file_system_http_cache/file_system_http_cache_test.cc, test/per_file_coverage.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Disable file system tests broken by infra change

test/extensions/common/async_files/async_file_handle_thread_pool_test.cc, test/extensions/http/cache/file_system_http_cache/file_system_http_cache_test.cc, test/per_file_coverage.sh
This reverts commit 2d368c340833ce1a86db81a7eb48700c13575435.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Revert "Disable file system tests broken by infra change (#33117)"

mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h, mobile/library/common/BUILD, mobile/library/common/engine_types.h, mobile/library/common/internal_engine.cc, mobile/library/common/internal_engine.h, mobile/library/common/logger/logger_delegate.cc, mobile/library/common/logger/logger_delegate.h, mobile/library/common/types/c_types.cc, mobile/library/common/types/c_types.h, mobile/library/jni/jni_impl.cc, mobile/library/jni/jni_utility.h, mobile/library/objective-c/EnvoyEngineImpl.mm, mobile/test/cc/BUILD, mobile/test/cc/engine_test.cc, mobile/test/common/http/filters/test_event_tracker/BUILD, mobile/test/common/http/filters/test_event_tracker/filter.cc, mobile/test/common/http/filters/test_event_tracker/filter.h, mobile/test/common/internal_engine_test.cc, mobile/test/common/logger/logger_delegate_test.cc, mobile/test/java/io/envoyproxy/envoymobile/jni/JniUtilityTest.java, mobile/test/java/org/chromium/net/BidirectionalStreamTest.java, mobile/test/jni/jni_utility_test.cc
This PR removes `envoy_event_tracker` C wrapper type and replaces it with `EnvoyEventTracker` C++ type. This PR also fixes a memory leak by introducing `EnvoyEventTracker.on_exit`, which adds a callback to allow doing any clean up prior to the engine termination.
This PR also adds `EngineBuilder:setEventTracker` in the C++ API to keep the same feature parity as the other language APIs.
=> mobile: Remove envoy_event_tracker C wrapper type

source/common/common/logger.cc, source/common/common/logger.h
This reverts commit 6d1363a40824ee31dd6643e03e17568c8fa502df.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Revert "Enable static validation of the EVENT log macros (#33067)"

api/envoy/extensions/filters/network/ext_authz/v3/ext_authz.proto, api/envoy/service/auth/v3/attribute_context.proto, changelogs/current.yaml, source/extensions/filters/common/ext_authz/check_request_utils.cc, source/extensions/filters/common/ext_authz/check_request_utils.h, source/extensions/filters/network/ext_authz/ext_authz.cc, source/extensions/filters/network/ext_authz/ext_authz.h, test/extensions/filters/common/ext_authz/check_request_utils_test.cc
Commit Message: network ext_authz filter: support include_tls_session option from http variant
Additional Description: the http ext_authz filter supports [including tls session details](https://github.com/envoyproxy/envoy/blob/bd81cea070e5dbf45a60f56fa599822f8cef8ae1/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L209-L213) in the check request. This PR ports that functionality over to the network ext_authz filter using the exact same mechanisms and the same field in the check request.
Testing: unit tests included
Docs Changes: docs are included in the protodoc for api changes. Slightly altered the protodoc for the check request attribute to link to both filters' config.
Release Notes: included as a new feature
=> network ext_authz filter: support include_tls_session option from http variant

contrib/qat/BUILD
Commit Message: qatzstd: remove useless build parameters
Those useless building parameters break the CI of istio proxy https://github.com/istio/proxy/pull/5411#issuecomment-2007333439
Testing: n/a
=> qatzstd: remove useless build parameters

mobile/library/common/extensions/filters/http/platform_bridge/filter.cc, mobile/library/common/http/client.cc, mobile/library/common/internal_engine.cc, mobile/library/common/network/connectivity_manager.cc, mobile/library/jni/types/exception.cc, source/common/common/logger.cc, source/common/common/logger.h
The fmt::runtime method prevents static validation of format strings. This change eliminates the need for fmt::runtime by formatting the message before calling the logWithStableName method.
=> Enable static validation of the EVENT log macros

mobile/library/kotlin/io/envoyproxy/envoymobile/BUILD
Reverts #33038.
Unfortunately, this change had the opposite effect. The AAR size in Maven went from 28MB[1] to 123MB[2].
Probably, the opt_build condition isn't met, even for opt builds, so it defaults to the "conditions:default", causing the debug build to get produced. The previous change will be reverted and we can investigate bazel:opt_build separately.
[1] https://repo1.maven.org/maven2/io/envoyproxy/envoymobile/envoy/0.5.0.20240318/
[2] https://repo1.maven.org/maven2/io/envoyproxy/envoymobile/envoy/0.5.0.20240325/
=> mobile: Revert "mobile: Make the opt AAR build use the non-debug .so file"

api/envoy/extensions/filters/http/basic_auth/v3/basic_auth.proto, changelogs/current.yaml, source/extensions/filters/http/basic_auth/basic_auth_filter.cc, source/extensions/filters/http/basic_auth/basic_auth_filter.h, source/extensions/filters/http/basic_auth/config.cc, test/extensions/filters/http/basic_auth/basic_auth_integration_test.cc, test/extensions/filters/http/basic_auth/filter_test.cc
Related to https://github.com/envoyproxy/envoy/issues/32419
=> Support forwarding username to backends

.github/config.yml
It's important for us to run the mobile C++ unit and integration tests on any Envoy change. If we don't, we run the risk of breaking Envoy Mobile with seemingly benign changes.
For example, https://github.com/envoyproxy/envoy/pull/32775 caused Envoy Mobile to permafail because an Envoy Mobile unit test wasn't run (see https://github.com/envoyproxy/envoy/pull/33158 for the fix).
This change ensures that the Envoy Mobile C++ tests run on all core Envoy changes. There aren't too many of these tests, so it shouldn't add much to the runtime of CI per PR.
=> ci: Make the mobile-cc CI job run on all Envoy changes

changelogs/current.yaml, source/extensions/filters/http/geoip/geoip_filter.cc, test/extensions/filters/http/geoip/geoip_filter_test.cc
Commit Message: use StopAllIterationAndWatermark in geoip filter
Use `StopAllIterationAndWatermark` in geoip filter to stop both headers and data when performing async geoip lookup. This fixes the issue in #33021 where large POST request data got corrupted.
Testing:
Docs Changes: 
Release Notes:
Fixes #33021 
=> use StopAllIterationAndWatermark in geoip filter

test/extensions/path/uri_template_lib/uri_template_test.cc, tools/spelling/spelling_dictionary.txt
Commit Message: Adds additional test cases for path and text glob path pattern matching.
Additional Description: Specifically verifies that `=**` or `**` must be the last operator in the path pattern match.
Testing: Ran new tests locally.
=> tests: text and path glob path matching

mobile/.bazelrc, mobile/bazel/android_configure.bzl, mobile/test/common/integration/BUILD, mobile/test/java/io/envoyproxy/envoymobile/engine/testing/BUILD, mobile/test/java/io/envoyproxy/envoymobile/engine/testing/HttpProxyTestServerFactory.java, mobile/test/java/io/envoyproxy/envoymobile/engine/testing/HttpTestServerFactory.java, mobile/test/java/io/envoyproxy/envoymobile/engine/testing/TestJni.java, mobile/test/jni/BUILD, mobile/test/jni/jni_http_proxy_test_server_factory.cc, mobile/test/jni/test_jni_impl.cc, mobile/test/kotlin/integration/BUILD, mobile/test/kotlin/integration/SendDataTest.kt, mobile/test/kotlin/integration/proxying/BUILD, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPRequestUsingProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestBadHostnameTest.kt, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestUsingAsyncProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestUsingProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyPollPerformHTTPRequestUsingProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyPollPerformHTTPRequestWithoutUsingPACProxyTest.kt
This PR removes the HTTP server code from `TestJni`. The tests have been updated to use either `HttpTestServer` or `HttpProxyTestServer`.
This PR also moves `test_server_interface.[h|cc]` into its own build target.
=> mobile: Remove HTTP server code from TestJni

source/common/protobuf/utility.cc, source/common/protobuf/utility.h, source/extensions/common/tap/tap_config_base.cc, test/config/utility.cc
Add canonical formatter of the text proto representation and use in places where text proto were expected.
Future protobuf update adds PII sanitization to DebugString() and will stop producing valid text proto. Unfortunately Envoy incorrectly used DebugString to produce text proto representation when ::proto::TextFormat::Printer should have been used. This PR fixes known places where canonical text printer should have been used.
=> Replace DebugString with text proto printer

docs/root/configuration/http/http_filters/cors_filter.rst, source/extensions/filters/http/cors/cors_filter.cc, test/extensions/filters/http/cors/cors_filter_test.cc
cors: Do not modify response headers for requests not matching origin
Regular cors requests (not preflights), which did not match configured allowed origins are forwarded upstream to the server. It seems that treatment of responses to such requests was undefined. There was no documentation, no unit nor integration tests which enforced whether extra headers should be added to responses to such request. Before #33051, the headers were not added and after the #33051 headers were added. This PR brings the behaviour to original and headers are not added. Docs have been updated and unit test was added to enforce this behaviour. 
Docs Changes: Updated.
Fixes #33086
=> cors: do not modify response headers for requests not matching origin

api/envoy/extensions/filters/http/json_to_metadata/v3/json_to_metadata.proto, source/extensions/filters/http/json_to_metadata/filter.cc, test/extensions/filters/http/json_to_metadata/filter_test.cc
Currently filters after json_to_metadata couldn't get hints from metadata if we have a mismatched content type.
Therefore, we set `on_error` which matches semantic meaning the best.
=> mismatch content type should set on_error metadata in json_to_metadata filter

source/common/listener_manager/filter_chain_manager_impl.cc, test/common/listener_manager/filter_chain_manager_impl_test.cc, test/common/listener_manager/listener_manager_impl_test.cc
when duplicate filter chain match error happens, it is hard to find the offending matcher, especially when there are many of them. This commit adds the matcher to the error message, so it is easier to understand the cause.
This is  especially a problem with large multi tenant setups, making it hard to find the tenant that added the duplicate matcher.
Risk Level:
Low - just a message change
=> make the error message better when there's a duplicate filter chain matcher.

envoy/common/exception.h, source/common/stats/tag_extractor_impl.cc, source/common/stats/tag_extractor_impl.h, source/common/stats/tag_producer_impl.cc, test/common/stats/tag_extractor_impl_test.cc
=> tag extractor: removing exceptions

source/extensions/filters/http/cache/cacheability_utils.cc, test/extensions/filters/http/cache/cacheability_utils_test.cc
Commit Message: [http-cache] Don't bypass the cache for if-unmodified-since or if-match
Additional Description: There's a whole section of the cache filter to do with conditional headers that's unimplemented ("if needed, implement it to this spec!"). Turns out we only need the very easy to implement subset, where the cache is supposed to ignore one of the conditional headers. I threw in the other one that's supposed to be ignored as well.
Risk Level: Very low, it's a WIP filter and an edge case use of it where before the change it does the wrong thing.
Testing: Doesn't even make sense to have a special test for this - there are an infinite number of headers the cache should ignore.
=> [http-cache] Don't bypass the cache for if-unmodified-since or if-match

changelogs/current.yaml, source/common/secret/sds_api.cc, source/common/secret/sds_api.h, test/common/secret/sds_api_test.cc, test/integration/ads_integration_test.cc
Commit Message: Ignore Delta SDS removals
Additional Description: Fixes #24373 and #32832
Testing: Manual testing with the Istio scenario described in #32832. Investigating how to add a unit test
Docs Changes:
Release Notes: Delta SDS removals will no longer result in a "Missing SDS resources" error message
=> sds: Ignore Delta Removals

mobile/library/common/types/c_types.h, mobile/library/jni/BUILD, mobile/library/jni/android_network_utility.cc, mobile/library/jni/android_network_utility.h
This PR removes `envoy_cert_verify_status_t` C `enum` type from `c_types.h` and replaces it with `CertVerifyStatus` C++ `enum class`. This PR also moves the enum into `android_network_utility.cc` since it's internal to the implementation.
Testing: CI
=> mobile: Remove envoy_cert_verify_status_t C type

contrib/language/filters/http/test/language_integration_test.cc, mobile/test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc, source/extensions/common/aws/signer_base_impl.cc, source/extensions/common/aws/sigv4_signer_impl.cc, source/extensions/common/aws/sigv4a_signer_impl.cc, source/extensions/network/dns_resolver/cares/dns_impl.cc, source/server/hot_restarting_base.cc, test/extensions/common/aws/sigv4a_signer_impl_test.cc, test/extensions/common/tap/admin_test.cc, test/extensions/filters/common/local_ratelimit/local_ratelimit_test.cc, test/extensions/filters/http/local_ratelimit/filter_test.cc, test/extensions/filters/http/local_ratelimit/local_ratelimit_integration_test.cc, test/extensions/filters/http/tap/tap_filter_integration_test.cc, test/extensions/filters/network/rbac/config_test.cc, test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc
Use static format validation where format string is already constexpr.
=> Enable static format validation where possible

contrib/cryptomb/private_key_providers/source/cryptomb_private_key_provider.cc, contrib/cryptomb/private_key_providers/source/cryptomb_private_key_provider.h, contrib/cryptomb/private_key_providers/test/BUILD, contrib/cryptomb/private_key_providers/test/ops_test.cc, contrib/cryptomb/private_key_providers/test/speed_test.cc
Commit Message: cryptomb: reduce memory copy in ECDSA
The original implementation serializes signatures into a temporary output buffer during processing phase and then copy to the BoringSSL buffer in the completion phase. This patch change the way and directly serializes signatures to the BoringSSL buffer.
In addition, the patch adds a speed test to track the performance change by mathematical implementation of private key provider.
Testing: N/A
Platform Specific Features: Requires AVX512 or equivalent CPU instruction set
=> cryptomb: reduce memory copy in ECDSA

changelogs/current.yaml, contrib/golang/common/go/api/api.h, contrib/golang/common/go/api/capi.go, contrib/golang/common/go/api/filter.go, contrib/golang/common/go/api/type.go, contrib/golang/filters/http/source/cgo.cc, contrib/golang/filters/http/source/go/pkg/http/capi_impl.go, contrib/golang/filters/http/source/go/pkg/http/filter.go, contrib/golang/filters/http/source/go/pkg/http/type.go, contrib/golang/filters/http/source/golang_filter.cc, contrib/golang/filters/http/source/golang_filter.h, contrib/golang/filters/http/test/golang_integration_test.cc, contrib/golang/filters/http/test/test_data/basic/filter.go
introduce a new API `ClearRouteCache` to clear route cache.
fix #33082
Testing:
Docs Changes:
Release Notes:
=> golang filter: do not clear route cache in ·HeaderMap.Set` by default.

source/exe/terminate_handler.cc, source/server/backtrace.cc, source/server/backtrace.h, tools/stack_decode.py
Commit Message: Make backtrace addresses useable with post-hoc stack_decode
Additional Description: When we get a backtrace, typically the addresses are offset because of ASLR. That offset is not logged anywhere, and after the process has crashed the information is no longer available. `stack_decode.py` therefore only actually works if it's running as a wrapper around envoy; the "run afterwards" version with `-s` is unusable unless ASLR was disabled.
This change makes envoy also retrieve and log the address offset if possible (using the same mechanism `stack_decode.py` uses), and has `stack_decode.py` consume and use that logged address offset.
If `/proc/self/maps` is not present or not readable or doesn't match the expected format, the log output is unchanged.
Risk Level: Low, …
=> Make backtrace addresses useable with post-hoc stack_decode

bazel/repository_locations.bzl, bazel/rules_fuzzing.patch
This reverts commit d47731444bcd5a11671f5ffda203b5cb093bb883.
The new rules_fuzzing requires Bazel v7.0.0+ whereas we currently use v6.5.0 (see more details [here](https://github.com/envoyproxy/envoy/pull/33188#issuecomment-2029769819)).
Reverting the upgrade for now.
=> Revert "deps: Bump `rules_fuzzing` -> 0.5.1 (#33188)"

mobile/test/jni/BUILD, mobile/test/kotlin/integration/BUILD, mobile/test/kotlin/integration/SendDataTest.kt
The test failed when adding the native Assertion filter, with an error from loadFromYaml:
```
INVALID_ARGUMENT: could not find @type 'type.googleapis.com/envoymobile.extensions.filters.http.assertion.Assertion
```
The failure was reproduced locally with:
```
./bazelw test --cache_test_results=no --test_output=streamed --config=mobile-test-android //test/kotlin/integration:send_data_test 
```
After running git bisect, it turns out the bad commit came from https://github.com/envoyproxy/envoy/pull/33169. That PR introduces HttpTestServer to the SendDataTest.kt, which causes the required proto types to not get loaded.
In this commit, the test is fixed by using a TestRemoteResponse filter, similar to the other Kotlin tests (e.g. SendTrailersTest). However, we need to figure out why the config …
=> mobile: Fix the flaky SendDataTest Kotlin test

mobile/test/jni/BUILD, mobile/test/jni/jni_http_proxy_test_server_factory.cc, mobile/test/kotlin/integration/SendDataTest.kt
This PR fixes the JNI test server BUILD files by not depending on `//library/jni:envoy_jni_lib` but making it depend on `//@envoy/test/test_common:test_version_linkstamp` that can generate the `build_scm_revision` and `build_scm_status` constants.
This PR also fixes the issue raised in https://github.com/envoyproxy/envoy/pull/33230 but the fix in https://github.com/envoyproxy/envoy/pull/33230 to use `TestRemoteResponse` is more correct and also more consistent with the other tests, so this PR simply removes the TODO instead of reverting the PR. I tested this by reverting the PR and running `./bazelw test --cache_test_results=no --test_output=streamed --config=mobile-test-android //test/kotlin/integration:send_data_test` with and without this fix. Although, I still can't fully figure out …
=> mobile: Fix JNI test server BUILD files

test/common/upstream/least_request_load_balancer_corpus/large_active_request_bias, test/common/upstream/least_request_load_balancer_fuzz_test.cc
Commit Message: fuzz: fix least request LB maximal active_request_bias value
The default_value of the [active_request_bias](https://github.com/envoyproxy/envoy/blob/014a68f303074fb743b780548ac58d2e1340ec53/api/envoy/extensions/load_balancing_policies/least_request/v3/least_request.proto#L79) config field can be high, which will end up setting the weight value in [this line](https://github.com/envoyproxy/envoy/blob/014a68f303074fb743b780548ac58d2e1340ec53/source/common/upstream/load_balancer_impl.cc#L1303) (`1.0 / 2^active_request_bias`) to essentially make all weights 0.
This PR adds a check to avoid setting this value to more than 25 in the fuzz tests.
Testing: Added fuzz corpus
Platform Specific …
=> fuzz: fix least request LB maximal active_request_bias value

mobile/.bazelrc, mobile/test/kotlin/integration/BUILD, mobile/test/kotlin/integration/CancelStreamTest.kt, mobile/test/kotlin/integration/KeyValueStoreTest.kt, mobile/test/kotlin/integration/ReceiveDataTest.kt, mobile/test/kotlin/integration/ResetConnectivityStateTest.kt, mobile/test/kotlin/integration/SendDataTest.kt, mobile/test/kotlin/integration/SendHeadersTest.kt, mobile/test/kotlin/integration/SendTrailersTest.kt, mobile/test/kotlin/integration/StreamIdleTimeoutTest.kt
This PR updates the Kotlin tests to use `HttpTestServer` instead of using a native `TestRemoteResponse` to make the tests more realistic. This PR also updates the tests to set the logger because debugging the test failure without any debugging info can be very difficult.
This PR also fixes https://github.com/envoyproxy/envoy/issues/25180 because the `ResetConnectivityStateTest` now makes a real connection.
=> mobile: Use test server instead of TestRemoteResponse filter for the Kotlin tests

mobile/test/swift/integration/BUILD, mobile/test/swift/integration/CancelGRPCStreamTest.swift
Also, updates the BUILD target for some tests to have the _test suffix, for consistency in how test targets are named.
=> mobile: Use Builder APIs in Swift integration tests

mobile/test/java/integration/AndroidEngineSocketTagTest.java, mobile/test/java/integration/AndroidEnvoyEngineStartUpTest.java, mobile/test/java/integration/AndroidEnvoyExplicitFlowTest.java, mobile/test/java/integration/AndroidEnvoyFlowTest.java, mobile/test/java/io/envoyproxy/envoymobile/engine/testing/QuicTestServerTest.java, mobile/test/java/org/chromium/net/testing/AndroidEnvoyExplicitH2FlowTest.java, mobile/test/java/org/chromium/net/testing/Http2TestServerTest.java, mobile/test/kotlin/integration/CancelGRPCStreamTest.kt, mobile/test/kotlin/integration/EngineApiTest.kt, mobile/test/kotlin/integration/EnvoyEngineSimpleIntegrationTest.kt, mobile/test/kotlin/integration/FilterThrowingExceptionTest.kt, mobile/test/kotlin/integration/GRPCReceiveErrorTest.kt, mobile/test/kotlin/integration/ReceiveErrorTest.kt, mobile/test/kotlin/integration/SetEventTrackerTest.kt, mobile/test/kotlin/integration/SetLoggerTest.kt, mobile/test/kotlin/integration/XdsTest.kt, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPRequestUsingProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestBadHostnameTest.kt, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestUsingAsyncProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestUsingProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyPollPerformHTTPRequestUsingProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyPollPerformHTTPRequestWithoutUsingPACProxyTest.kt
This PR adds a call to `addLogLevel` and `setLogger` with `DEBUG` log level to make it easier to debug any test failures.
=> mobile: Call setLogger in the Java and Kotlin tests

mobile/library/cc/engine_builder.cc, mobile/library/common/engine_types.h, mobile/library/common/internal_engine.cc, mobile/library/common/logger/logger_delegate.cc, mobile/library/jni/jni_impl.cc, mobile/library/objective-c/EnvoyEngineImpl.mm, mobile/test/cc/engine_test.cc, mobile/test/common/http/filters/test_event_tracker/filter.h, mobile/test/common/internal_engine_test.cc, mobile/test/common/logger/logger_delegate_test.cc
This PR updates the code to use suffix `_` for `struct` member variables as per [Envoy Code Style](https://github.com/envoyproxy/envoy/blob/main/STYLE.md?plain=1#L30).
Risk Level: low (rename only)
Testing: CI
=> mobile: Use suffix _ for struct member variables

test/common/router/config_impl_test.cc
Commit Message: add IpVersion guard to HashIpv6DifferentAddresses case
Testing:
Docs Changes:
Release Notes:
=> chore: add IpVersion guard to HashIpv6DifferentAddresses case

.github/config.yml, ci/Dockerfile-envoy
…99c134` in /ci (#32843)
build(deps): bump distroless/base-nossl-debian12 in /ci
Bumps distroless/base-nossl-debian12 from `0e777c6` to `099c134`.
---
- dependency-name: distroless/base-nossl-debian12 dependency-type: direct:production ...
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.28] distroless and disable windows

bazel/BUILD, contrib/all_contrib_extensions.bzl, contrib/exe/BUILD
Previously, the ARM build with FIPS enabled was failing when building on v1.29.0
```
ERROR: /go/src/github.com/DataDog/envoy/contrib/exe/BUILD:31:16: Illegal ambiguous match on configurable attribute "deps" in //contrib/exe:envoy-static:
//bazel:linux_aarch64
//bazel:boringssl_fips
```
This adds `config_setting_group` to make the match explicit - that is, we will skip the `FIPS_LINUX_X86_SKIP_CONTRIB_TARGETS` targets if the target arch is linux x86 and boringssl fips is enabled.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_ch …
=> [bp/1.29] contrib: Fix build for fips arm (#32382)

mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidNetworkMonitor.java, mobile/library/jni/jni_impl.cc, mobile/test/java/org/chromium/net/CronetUrlRequestTest.java
This PR fixes a memory leak by deleting the `InternalEngine *` after calling the `InternalEngine::terminate`.
This PR also fixes an issue with `CronetUrlRequestTest.testInternetDisconnectedError()` to always load a new singleton instance of `AndroidNetworkMonitor` by calling `AndroidNetworkMonitor.shutdown()`. Prior to this, `AndroidNetworkInstance` singleton instance might be holding on an `EnvoyEngine` that had been destroyed. Ideally, we should fix this by exposing the `EngineCallbacks.on_exit_` callback to automatically reset the instance of `AndroidNetworkMonitor` to `null` instead of manually calling `AndroidNetworkMonitor.shutdown()`. However, that `EngineCallbacks.on_exit_` callback has not been exposed yet into the Java API. …
=> mobile: Fix memory leak in the terminate JNI code

mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java, mobile/test/kotlin/integration/EnvoyEngineSimpleIntegrationTest.kt
Calling operations on a terminated engine can lead to a crash. This PR fixes the issue by having a check to ensure no other operations can be executed once the engine has been terminated.
=> mobile: Add a precondition to throw an exception when an engine has been terminated

mobile/test/common/internal_engine_test.cc
The setpriority() sys call doesn't take effect on some Apple environments. Disabling the test on Apple while we investigate further.
=> mobile: Disable SetThreadPriority test for Apple

mobile/test/jni/BUILD
Occasionally I have seen test failures due to missing cluster factory implementation, such as
```
Didn't find a registered cluster factory implementation for name: 'envoy.cluster.static
```
This PR fixes the issue by linking the JNI test servers with `@envoy_build_config//:test_extensions` to force the factory registrations.
Testing: n/a
=> mobile: Link the test servers with test_extensions

changelogs/current.yaml
Move it from deprecated to new feature  introduced from #32711
Testing:
Docs Changes:
Release Notes:
=> grpc: fix maximum gRPC message size changelogs

api/bazel/BUILD, bazel/dependency_imports.bzl, ci/do_ci.sh
Commit Message: build: bump vtprotobuf dependency
Additional Description: This picks up a few bug fixes and allows us to remove our build tag hacks
Testing: Manually tested build + import into go-control-plane
Docs Changes:
Release Notes:
=> build: bump vtprotobuf dependency

test/common/stats/tag_producer_impl_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> increase stats coverage

bazel/dependency_imports.bzl
Commit Message: deps: update vtprotobuf
Apologies for the churn here; there was one small bug with the latest version I didn't pick up in my manual testing. This commit has a fix, and I fixed my manual testing to cover everything, so I am confident this should work
Risk Level: None; opt-in experimental feature was broken before this PR and now fixed
Docs Changes:
Release Notes:
=> deps: update vtprotobuf

source/common/formatter/http_specific_formatter.cc, source/common/formatter/substitution_format_utility.cc, source/common/formatter/substitution_format_utility.h, test/common/formatter/substitution_formatter_test.cc
Additional Description: Memory optimization. New function SubstitutionFormatUtils::truncateStringView()
Docs Changes:
Release Notes:
=> formatter: truncate with a string view

api/envoy/extensions/filters/http/basic_auth/v3/basic_auth.proto, changelogs/current.yaml, docs/root/configuration/http/http_filters/basic_auth_filter.rst, source/extensions/extensions_metadata.yaml, source/extensions/filters/http/basic_auth/BUILD, source/extensions/filters/http/basic_auth/basic_auth_filter.cc, source/extensions/filters/http/basic_auth/basic_auth_filter.h, source/extensions/filters/http/basic_auth/config.cc, source/extensions/filters/http/basic_auth/config.h, test/extensions/filters/http/basic_auth/BUILD, test/extensions/filters/http/basic_auth/basic_auth_integration_test.cc, test/extensions/filters/http/basic_auth/config_test.cc, test/extensions/filters/http/basic_auth/filter_test.cc
Commit Message: "basic_auth: add support for per-route filter"
Testing: unit, integration, manual
Docs Changes: added
Platform Specific Features: -
Fixes #32550
[Here](https://github.com/jewertow/envoy-playground/tree/master/basic-auth-per-route) you can find configuration and steps for manual tests.
=> basic_auth: add support for per-route filter

mobile/.bazelrc, mobile/test/swift/integration/BUILD, mobile/test/swift/integration/KeyValueStoreTest.swift, mobile/test/swift/integration/ReceiveDataTest.swift, mobile/test/swift/integration/ResetConnectivityStateTest.swift, mobile/test/swift/integration/SendDataTest.swift, mobile/test/swift/integration/SendHeadersTest.swift, mobile/test/swift/integration/SendTrailersTest.swift, mobile/test/swift/integration/SetEventTrackerTest.swift, mobile/test/swift/integration/SetEventTrackerTestNoTracker.swift, mobile/test/swift/integration/SetLoggerTest.swift
As part of this change, the native filters that get added on the EngineBuilder use the proto format, not YAML.
As a result, iOS CI is also updated to build without YAML enabled.
=> mobile: Moves all Swift tests to EngineBuilder APIs

source/common/secret/sds_api.cc, test/integration/ads_integration_test.cc
As discussed in Slack, a delta removal should complete cluster warming
Commit Message: (fix/sds): Mark cluster as ready after 
Testing: integration
Docs Changes:
Release Notes:
=> (delta/sds): Mark secret as ready if server says the resource doesn't exist

source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc, source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.h
DFP: move CM callbacks to thread local objects
This is third attempt to fix #32427. (The previous are #32692 and #32798). 
The solution simply moves callbacks out of main object to thread local objects. Thread local objects do not hold any references to the main object, so both object types are independent and may have different lifespans.
This fixes the reported crash, but is not a generic solution.
I also played with combination of shared/weak pointers and modified signature of the function registering callbacks in CM. That also fixed the problem, but affected other modules (CM itself, aggregate cluster, redis proxy and udp proxy).
At this moment I believe that it is possible to build a generic mechanism which will take care of difference in …
=> DFP: move CM callbacks to thread local objects

mobile/library/cc/bridge_utility.cc, mobile/library/cc/bridge_utility.h, mobile/library/cc/stream.cc, mobile/library/common/http/client.cc, mobile/library/common/http/client.h, mobile/library/common/http/header_utility.cc, mobile/library/common/http/header_utility.h, mobile/library/common/internal_engine.cc, mobile/library/common/internal_engine.h, mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyHTTPStream.java, mobile/library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java, mobile/library/jni/jni_impl.cc, mobile/library/jni/jni_utility.cc, mobile/library/jni/jni_utility.h, mobile/library/objective-c/EnvoyHTTPStreamImpl.mm, mobile/test/common/http/client_test.cc, mobile/test/common/http/header_utility_test.cc, mobile/test/common/internal_engine_test.cc
This PR updates `InternalEngine::sendTrailers` to use C++ `Envoy::Http::RequestTrailerMap` instead of `envoy_headers` C wrapper type. This helps to reduce the number of indirection as well as unnecessary copies. The JNI code for `sendTrailers` has been rewritten to use proper Java type, such as `Map<String, List<String>>` instead of `byte[][]`. This change also helps to reduce unnecessary copies.
=> mobile: Update InternalEngine::sendTrailers to use Envoy::Http::RequestTrailerMap

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ext_proc: Add the test for overlimit response from ext_proc server

docs/root/configuration/operations/overload_manager/overload_manager.rst, source/server/overload_manager_impl.cc, source/server/overload_manager_impl.h, test/server/overload_manager_impl_test.cc
Added one counter stats that will +1 when `shouldShedLoad()` is true.
Testing:
Docs Changes:
Release Notes:
=> load shed: add total count metrics for lsp in overload manager

mobile/test/kotlin/integration/ReceiveTrailersTest.kt
Fixes https://github.com/envoyproxy/envoy/issues/33429.
Before this PR, the test would do this.
```
assertThat(trailersReceived.count).isEqualTo(0)
trailersReceived.await(10, TimeUnit.SECONDS) 
```
It was problematic because if the `setOnResponseTrailers` hadn't finished, the `trailersReceived.count` would still be set to 1. This PR fixes it by calling `trailersReceived.await` first and then doing an assert on `trailersReceived.count`.
Testing: ` bazel test --runs_per_test=100 //test/kotlin/integration:receive_trailers_test`
=> mobile: Fix flaky ReceiveTrailersTest.kt

.dockerignore, ci/Dockerfile-envoy, ci/do_ci.sh, docs/root/operations/tools/route_table_check_tool.rst
This change adds `router_check_tool` binary to tools image.
Fixes #32032
Commit Message: Add router_check_tool to tools container image
Testing: Manual container build was executed
Docs Changes: update [doc](https://www.envoyproxy.io/docs/envoy/latest/operations/tools/route_table_check_tool) about availability in tools image.
=> build: Add router_check_tool to tools container image

.github/workflows/mobile-ios_build.yml
This should hopefully fix the flakiness issue, such as https://github.com/envoyproxy/envoy/actions/runs/8636677357/job/23677319014
Testing: CI
=> mobile: Bump swift-async-await test timeout

mobile/test/swift/integration/SendDataTest.swift
https://github.com/envoyproxy/envoy/pull/33402 added a setOnCancel to assert the cancel callback is never called in the SendDataTest. However, this causes test flakes and even locally, we see ocassional flakes.
It's not clear why sometimes the onCancel callback gets called, but removing that check for now since it introduces flakiness and didn't exist before.
=> mobile/test: Fix SendDataTest.swift flake

mobile/test/swift/integration/SetEventTrackerTest.swift
The event tracker callback can get called multiple times at different junctures in the code, not just from the TestEventTracker filter. This PR ensures that we only fulfill the test expectation when the TestEventTracker filter's events appear in the callback.
=> mobile/test: Fix SetEventTracker test flakes

.bazelrc, bazel/setup_clang.sh, mobile/.bazelrc
This is a first step towards removing `bazel/setup_clang.sh` - it just removes the flags that have no reason to be there
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel: Shift ASAN flags to .bazelrc

changelogs/current.yaml, docs/root/configuration/http/http_filters/lua_filter.rst, source/extensions/filters/http/lua/lua_filter.cc, source/extensions/filters/http/lua/lua_filter.h, source/extensions/filters/http/lua/wrappers.cc, source/extensions/filters/http/lua/wrappers.h, test/extensions/filters/http/lua/lua_filter_test.cc
**Previous PR:** https://github.com/envoyproxy/envoy/pull/22246
Currently, there seems to be no way to access the dynamic metadata set by any network filters in LUA or any other HTTP filters. `streamInfo()` is accessible on the connection and could be used to fetch the `dynamicMetadata()` from the network filters but it's is currently not exposed in HTTP LUA filter.
We want to read the TLV values set by the `proxy_protocol` filter in the dynamic metadata in the LUA filter so that we can propagate these TLV pairs to the upstream services for some further processing. 
This PR adds a new `connectionStreamInfo()` methods to LUA filter that could be used to access the Stream Info object on the connection and then fetch the dynamic metadata from network filters like this:
``` …
```
=> lua: add new methods to access network connection streamInfo() & dynamicMetadata()

source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc, source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.h
DFP: move CM callbacks to thread local objects (#33303)
Backport #33303 to rel 1.28
=> backport to rel1.28: DFP - move CM callbacks to thread local objects (#33303)

source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc, source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.h
backport to 1.27: DFP: move CM callbacks to thread local objects (#33303)
Backport of #33303 to release 1.27
=> backport to 1.27: DFP: move CM callbacks to thread local objects (#33303)

docs/root/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter.rst
I thought it would be a good idea to help people quickly understand what we are referring to
=> docs: add the link to term definition/explanation

test/common/upstream/least_request_load_balancer_corpus/zero_min_weight_percent, test/common/upstream/zone_aware_load_balancer_fuzz_base.cc
Commit Message: fuzz: slow-start prevent low min_weight_percent
Getting non-zero weights fo slow-start is not-easy, and requires the correct configuration of the aggression and time-out factors. The alternative is to set a minimal min_weight_percent config when aggression is used, that will ensure that not all of the weights are 0.
Risk Level: low - fuzz tests only
Testing: Added corpus
Fixes fuzz issue [67870](https://oss-fuzz.com/testcase-detail/6146447478161408)
=> fuzz: slow-start prevent low min_weight_percent

mobile/examples/cc/fetch_client/fetch_client.cc, mobile/test/cc/integration/lifetimes_test.cc, mobile/test/cc/integration/send_headers_test.cc, mobile/test/common/integration/base_client_integration_test.cc, mobile/test/common/integration/client_integration_test.cc
`EngineBuilder::addLogger` has been deprecated and it'll be removed in the future.
=> mobile: Use setLogger instead of addLogger in the C++ code

docs/root/intro/arch_overview/security/google_vrp.rst
Bugs should be reported to both Envoysec and VRP. Rewards should be claimed from VRP directly.
=> docs: update VRP guidance around reporting and rewards.

api/envoy/admin/v3/server_info.proto, changelogs/current.yaml, docs/root/operations/cli.rst, envoy/server/options.h, source/exe/stripped_main_base.cc, source/server/hot_restart.proto, source/server/hot_restart_impl.cc, source/server/hot_restart_impl.h, source/server/hot_restarting_base.cc, source/server/hot_restarting_base.h, source/server/hot_restarting_child.cc, source/server/hot_restarting_child.h, source/server/hot_restarting_parent.cc, source/server/options_impl.cc, source/server/options_impl_base.h, test/integration/python/hotrestart_handoff_test.py, test/mocks/server/options.h, test/server/hot_restart_impl_test.cc, test/server/hot_restarting_child_test.cc, test/server/hot_restarting_parent_test.cc
Commit Message: Make hot restart tolerate premature death of the parent instance
Additional Description: The current behavior of hot restart makes it difficult to manage crashes, especially when envoy instances are run in containers - if epoch 1 crashed before epoch 2 tries to start up, there's no simple mechanism to have epoch 2 detect the crash and run as epoch 0 instead. If epoch 2 tries to start up while epoch 1 is not running, epoch 2 also crashes during startup, potentially causing an endless crashloop if there isn't some sort of "break out" detection.
This change makes it so instead of crashing during startup if the parent instance is not responsive, the child instance does one check at the beginning of its initialization of whether the parent is responsive, and if it is not, the …
=> Make hot restart tolerate premature death of the parent instance

mobile/test/cc/BUILD, mobile/test/cc/engine_test.cc, mobile/test/cc/integration/BUILD, mobile/test/cc/integration/lifetimes_test.cc, mobile/test/cc/integration/send_headers_test.cc, mobile/test/common/integration/BUILD, mobile/test/common/integration/engine_with_test_server.cc, mobile/test/common/integration/engine_with_test_server.h, mobile/test/common/integration/test_server.cc, mobile/test/common/integration/test_server_interface.cc
This PR updates some C++ tests to use `TestServer` instead of `TestRemoteResponse` native filter to make the tests more realistic. This PR also removes the `envoy_select_enable_yaml` so that the tests run since Envoy Mobile build has no YAML enabled by default.
=> mobile: Use TestServer instead of TestRemoteResponse native filter

changelogs/current.yaml, source/common/common/utility.h, test/common/common/utility_test.cc
[[prefix_trie] Fixed issue in matcher prefix trie lookup](https://github.com/sergkir85/envoy/pull/1/commits/0e9ad18806ffca9cf47193b869abd98657751ee9)
Lookup in matcher prefix tree does not lookup correctly in certain scenario. If trie contains two overlapped prefixes (eg "/foo" and "foo/bar") then the following path "/foo/" is not matched to "/foo" and Envoy returns 404 response code.
Config snippet:
```
matcher:
matcher_tree:
input:
name: request-headers
typed_config:
"@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
header_name: :path
prefix_match_map:
map:                              
"/foo":
action:
name: route_foo
typed_config:
"@type": type.googleapis.com/envoy.config.route.v3.Route
match:
prefix: /
route: …
```
=> [prefix_trie] Fixed issue in matcher prefix trie lookup

mobile/test/cc/engine_test.cc, mobile/test/cc/integration/lifetimes_test.cc, mobile/test/cc/integration/send_headers_test.cc, mobile/test/common/integration/engine_with_test_server.cc, mobile/test/common/integration/test_server.cc, mobile/test/common/integration/test_server.h, mobile/test/common/integration/test_server_interface.cc, mobile/test/jni/jni_http_proxy_test_server_factory.cc, mobile/test/jni/jni_http_test_server_factory.cc
This PR cleans up the `TestServer` code to follow Envoy naming convention as well as some C++ best practices.
=> mobile: Clean up TestServer code

mobile/library/cc/BUILD, mobile/library/cc/stream.cc, mobile/library/cc/stream.h, mobile/test/cc/integration/BUILD, mobile/test/cc/integration/send_headers_test.cc, mobile/test/cc/integration/send_trailers_test.cc
This PR adds `Stream::sendHeaders(Http::RequestHeaderMapPtr headers, bool end_stream)` and `close(Http::RequestTrailerMapPtr trailers)` that use Envoy Core types and deprecates the `sendHeaders(RequestHeadersSharedPtr headers, bool end_stream)` and `close(RequestTrailersSharedPtr trailers)` that use wrapper types. This change will eliminate unnecessary copies and indirection.
This PR also adds a missing a unit test for sending a trailer.
Risk Level: low (new functions)
=> mobile: Add sendHeaders and close with Envoy::Http::HeaderMap types

mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h, mobile/library/common/BUILD, mobile/library/common/engine_types.h, mobile/test/kotlin/integration/SendDataTest.kt
This PR switches from `std::function` to `absl::AnyInvocable` since `absl::AnyInvocable` is more flexible, such that it does not have a copyability requirement. The change should mostly be backward compatible.
This change also undeprecates `setOnEngineRunning` and introduces `setOnEngineExit` since it makes adding engine callbacks much nicer.
This PR also removes the comment about Swift/C++ interop since that support has been removed in https://github.com/envoyproxy/envoy/pull/33484.
=> mobile: Switch to absl::AnyInvocable for engine_types.h

api/envoy/extensions/filters/http/aws_lambda/v3/aws_lambda.proto, changelogs/current.yaml, source/extensions/common/aws/credentials_provider_impl.cc, source/extensions/common/aws/credentials_provider_impl.h, source/extensions/filters/http/aws_lambda/config.cc, source/extensions/filters/http/aws_lambda/config.h, test/extensions/common/aws/credentials_provider_impl_test.cc, test/extensions/filters/http/aws_lambda/config_test.cc
Commit Message: aws_lambda: add credential profile config to be used with AWS credentials file.
Additional Description: Adds a new config to allow a filter instance use an specific profile from the AWS Credential File.
Due to this new config only has meaning for AWS Credentials File provider, in case it is set, only that provider will be taken in consideration to avoid getting wrong credentials. If a user set this config is because it xpect to get the credentials from the file and should failed if the file is not present or the env var does is missed or incorrectly set
Related: https://github.com/envoyproxy/envoy/issues/31403
Testing: yes
=> Add credentials profile in aws_lambda config

bazel/README.md
Newer versions of this Clang+LLVM budnel are not available in the Clang releases, and other means of installing Clang-16 suggest that it fails building various Envoy dependencies. Clang-14 is used in CI, so recommend that version.
This is based on my experience trying to build Envoy from source (without using the docker image).
=> Recommend the Clang-14 tarball

test/extensions/filters/common/expr/evaluator_test.cc
Internal protobuf uses different number of spaces.
=> Adjust test to expect variable whitespace

ci/verify_examples.sh
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/examples: Expect failure of `lua-cluster-specifier` example

mobile/bazel/dokka.bzl
Loads are being added in preparation for moving the symbols out of Bazel and into `@rules_java`.
Commit Message: Add `load()` statements for the Bazel builtin top-level java symbols
Additional Description: Loads are being added in preparation for moving the symbols out of Bazel and into `@rules_java`.
Testing: `bazel build //library/kotlin/io/envoyproxy/envoymobile:envoy_aar_android_javadocs` 
Docs Changes:
Release Notes:
=> Add `load()` statements for the Bazel builtin top-level java symbols

source/common/common/utility.h, source/common/matcher/prefix_map_matcher.h, source/extensions/filters/network/redis_proxy/router_impl.cc
Commit Message: Make findLongestPrefix less error-prone
Additional Description: Old version assumes a null-terminated char* with no enforcement, and all callers were calling `c_str` on a `std::string` which can potentially provoke a performance cost depending on implementation. The code is also more readable with a string_view, and safer against e.g. a modification that breaks out of the loop, or that wants to do something with the key after the loop is over (key was previously modified and now is not). Also removes a comment citing external code where the link was broken anyway and the code now in place barely resembles the original code, after the bug fix #33478 and this change.
Also makes findLongestPrefix signature and behavior consistent with the signature and behavior of `find` …
=> Make findLongestPrefix less error-prone

mobile/library/common/engine_types.h, mobile/library/common/internal_engine.cc, mobile/library/common/internal_engine.h, mobile/library/common/network/BUILD, mobile/library/common/network/connectivity_manager.cc, mobile/library/common/network/connectivity_manager.h, mobile/library/common/types/c_types.h, mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidNetworkMonitor.java, mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java, mobile/library/java/io/envoyproxy/envoymobile/engine/types/EnvoyNetworkType.java, mobile/library/jni/jni_impl.cc, mobile/library/objective-c/EnvoyNetworkMonitor.mm, mobile/test/common/extensions/filters/http/network_configuration/network_configuration_filter_test.cc, mobile/test/common/network/connectivity_manager_test.cc
This PR removes `envoy_network_t` and replaces it with `Envoy::NetworkType` as an effort to get rid of `c_types.h`.
Testing: CI
=> mobile: Replace envoy_network_t with Envoy::NetWorkType enum class

source/extensions/access_loggers/open_telemetry/access_log_impl.cc, source/extensions/tracers/zipkin/zipkin_tracer_impl.h, test/extensions/access_loggers/open_telemetry/access_log_impl_test.cc, test/extensions/tracers/zipkin/zipkin_tracer_impl_test.cc
Commit Message: make zipkin tracer work with opentelemetry accesslogger
Additional Description: follow up https://github.com/envoyproxy/envoy/pull/33281
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tracer: implement zipkin getTraceIdAsHex

bazel/repositories.bzl
Replaces a duplicated item with the correct one.
=> Fix the `NO_HTTP3_SKIP_TARGETS` variable

mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.cc, mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.h, mobile/library/common/extensions/filters/http/network_configuration/filter.cc, mobile/library/common/http/client.cc, mobile/library/common/http/client.h, mobile/library/common/network/apple_proxy_resolver.cc, mobile/library/common/network/connectivity_manager.cc, mobile/library/common/network/connectivity_manager.h, mobile/library/common/network/proxy_resolver_interface.h, mobile/library/jni/android_network_utility.cc, mobile/test/common/extensions/filters/http/network_configuration/network_configuration_filter_test.cc, mobile/test/common/network/connectivity_manager_test.cc
According to [Envoy C++ coding style](https://github.com/envoyproxy/envoy/blob/main/STYLE.md), enum values should use PascalCase. This PR also updates some enums to use `enum class`.
Testing: CI
=> mobile: Rename the enum values to PascalCase

bazel/external/boringssl_fips.genrule_cmd
- Move `HOME` var up so that `curl` reads it and does not fail
- Adjust `PATH` var. `cmake` directory will be added to `PATH` a few lines later
- Actually perform the `SHA` verification for clang.
=> Small fixes to boringssl_fips.genrule_cmd

mobile/test/non_hermetic/gcp_traffic_director_integration_test.cc
This fixes the compilation error in `gcp_traffic_director_integration_test.cc`.
Testing: `bazel build --define=envoy_mobile_xds=enabled test/non_hermetic:gcp_traffic_director_integration_test`
=> mobile: Use setLogLevel in the gcp_traffic_director_integration_test.cc

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Commit Message: deflaky ExtProcIntegrationTest.RetryOnDifferentHost: cleanup connection before closing the test
Risk Level: LOW, test cleanup
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/32849
=> [cleanup] deflaky ExtProcIntegrationTest.RetryOnDifferentHost: cleanup connection before closing the test

test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
Commit Message: fix flaky integration tests
Additional Description: The ext_authz timeout integration tests were calling `waitForExtAuthzRequest` when it wasn't necessary. This, combined with a short timeout duration (10ms), led to very rare flakes where the request would timeout before the stream was established or before the grpc message was sent. The request would then get cancelled and `waitForExtAuthzRequest` would fail.
This PR removes all side stream expectations from the timeout integration tests since they are unnecessary. The HTTP tests weren't not flaky, but out of principle I did the same to them.
Testing: test-only PR
Fixes #33510
[Optional Fixes commit #PR or …
=> Fix flaky integration test

source/common/common/macros.h, source/common/common/posix/thread_impl.cc
Commit Message: thread: refactor the thread id getter to cache the id in thread local storage
In the current implementation of posix thread id getter, every `currentThreadId()` call will involves a system call. This make this call pretty expensive. And this also make the `Dispatcher::isThreadSafe()` call very expensive.
This PR refactor the implementation to cache the id in thread local storage to improve the performance.
Here is the benchmark result:
```
-------------------------------------------------------------
Benchmark                   Time             CPU   Iterations
-------------------------------------------------------------
bmThreadIdGetter/0       2595 ns         2595 ns       278564
bmThreadIdGetter/1       2.09 ns         2.09 ns    337318151
``` …
=> thread: refactor the thread id getter to cache the id in thread local storage

mobile/.bazelrc
This PR removes unused `mobile-asan-dev` and `mobile-tsan-dev` since they don't really work. This PR also adds `mobile-clang-tsan` and `mobile-clang-msan` that can be executed locally.
=> mobile: Clean up .bazelrc

changelogs/current.yaml, source/common/tls/context_impl.cc, source/common/tls/context_impl.h, source/common/tls/ssl_socket.cc, source/common/tls/ssl_socket.h, test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
If the `:authority` was longer than 255 characters, Envoy would RELEASE_ASSERT when creating an upstream TLS connection when `auto_sni` (https://www.envoyproxy.io/docs/envoy/v1.30.0/api-v3/config/core/v3/protocol.proto.html#config-core-v3-upstreamhttpprotocoloptions) was used.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tls: fix RELEASE_ASSERT when using `auto_sni`

source/extensions/tracers/opentelemetry/resource_detectors/dynatrace/dynatrace_resource_detector.cc
As discussed with @wbpcode I'm creating this backport to 1.30 for this small change. It just changes the log level to avoid unnecessary logs when the resource detector is added. Only back porting to 1.30 is enough, as we changed the error handling of the detector in after 1.29 
Commit Message: Backport from #33564
=> [bp/1.30] DynatraceResourceDetector: Change log level to debug

changelogs/current.yaml, source/common/tls/context_impl.cc, source/common/tls/context_impl.h, source/common/tls/ssl_socket.cc, source/common/tls/ssl_socket.h, test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
* tls: fix RELEASE_ASSERT when using `auto_sni`
If the `:authority` was longer than 255 characters, Envoy would RELEASE_ASSERT when creating an upstream TLS connection when `auto_sni` (https://www.envoyproxy.io/docs/envoy/v1.30.0/api-v3/config/core/v3/protocol.proto.html#config-core-v3-upstreamhttpprotocoloptions) was used.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.30] tls: fix RELEASE_ASSERT when using `auto_sni` (#33637)

changelogs/current.yaml, source/extensions/transport_sockets/tls/context_impl.cc, source/extensions/transport_sockets/tls/context_impl.h, source/extensions/transport_sockets/tls/ssl_socket.cc, source/extensions/transport_sockets/tls/ssl_socket.h, test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
* tls: fix RELEASE_ASSERT when using `auto_sni`
If the `:authority` was longer than 255 characters, Envoy would RELEASE_ASSERT when creating an upstream TLS connection when `auto_sni` (https://www.envoyproxy.io/docs/envoy/v1.30.0/api-v3/config/core/v3/protocol.proto.html#config-core-v3-upstreamhttpprotocoloptions) was used.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.28] tls: fix RELEASE_ASSERT when using `auto_sni` (#33637)

changelogs/current.yaml, source/extensions/transport_sockets/tls/context_impl.cc, source/extensions/transport_sockets/tls/context_impl.h, source/extensions/transport_sockets/tls/ssl_socket.cc, source/extensions/transport_sockets/tls/ssl_socket.h, test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc, test/per_file_coverage.sh
* tls: fix RELEASE_ASSERT when using `auto_sni`
If the `:authority` was longer than 255 characters, Envoy would RELEASE_ASSERT when creating an upstream TLS connection when `auto_sni` (https://www.envoyproxy.io/docs/envoy/v1.30.0/api-v3/config/core/v3/protocol.proto.html#config-core-v3-upstreamhttpprotocoloptions) was used.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.29] tls: fix RELEASE_ASSERT when using `auto_sni` (#33637)

bazel/repositories.bzl, source/extensions/geoip_providers/maxmind/BUILD
`maxmind` is causing the build to not honor the flag `--//bazel:http3=False`: The define `ENVOY_ENABLE_QUIC` is still being passed to the compiler. This causes code that rely on the presence (or not) of that define to behave wrongly.
I am not 100% sure of what causes it, but Bazel doc says 1) to not use `bind` and 2) that `bind` and `select` do not play well together: https://bazel.build/reference/be/workspace#bind
By removing the `bind` and pointing directly to the actual dependency in `maxmind` BUILD file, we fix this issue.
=> Fix build error with `maxmind` if http3 is disabled

changelogs/current.yaml, source/server/admin/config_dump_handler.cc, source/server/admin/init_dump_handler.cc, source/server/admin/utils.cc, source/server/admin/utils.h, test/server/admin/config_dump_handler_test.cc, test/server/admin/init_dump_handler_test.cc, test/server/admin/utils_test.cc
Fix #33435
Backport of #33044
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.29] admin: fix broken UI pages when called with empty query params (#33044)

bazel/repositories.bzl, source/extensions/geoip_providers/maxmind/BUILD
`maxmind` is causing the build to not honor the flag `--//bazel:http3=False`: The define `ENVOY_ENABLE_QUIC` is still being passed to the compiler. This causes code that rely on the presence (or not) of that define to behave wrongly.
I am not 100% sure of what causes it, but Bazel doc says 1) to not use `bind` and 2) that `bind` and `select` do not play well together: https://bazel.build/reference/be/workspace#bind
By removing the `bind` and pointing directly to the actual dependency in `maxmind` BUILD file, we fix this issue.
Backport of https://github.com/envoyproxy/envoy/pull/33638
=> [bp/1.28] Fix build error with `maxmind` if http3 is disabled (#33638)

.azure-pipelines/stage/publish.yml, ci/docker_ci.sh
Ubuntu repos have been ~broken for the last day or so - the ppas have had major outages, but it seems to be affecting their other repos as just doing `apt update` is currently ridiculously slow
Trying to repro with a minimal example locally and it passes but after a very long time - this increases the timeout to handle that and workaround the issue
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/docker: Increase timeouts to handle broken Ubuntu repos

test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc
Commit Message: tests: fixed & expanded checking of ocsp response
Additional Description: Expand the checking of OCSP response to check for expected length and bytes, to prevent false positive results.
Backport of #33030
=> [bp/1.28] tests: fixed & expanded checking of ocsp response (#33030)

api/envoy/service/ext_proc/v3/external_processor.proto, test/extensions/filters/http/ext_proc/filter_test.cc
Commit Message: inplace change the ImmediateResponse::body type from string to bytes
Additional Description: in issue https://github.com/envoyproxy/envoy/issues/32071 Folks found the immediateResponse::body was a string, which fails Envoy ext_proc filter to receive a non-utf8 payload 
Risk Level: LOW  (the in-place type change only drops the utf8 verification in generated code).
Testing: existing tests. 
Docs Changes:
Release Notes:
=> [extension inplace change the ImmediateResponse::body type from string to bytes

source/extensions/filters/http/ext_proc/config.h, test/extensions/filters/http/composite/composite_filter_integration_test.cc, test/integration/filters/server_factory_context_filter.cc, test/integration/filters/server_factory_context_filter_config.proto
This PR adding integration test to verify match_delegate + composite + callout_filter works in both downstream and upstream. 
It addresses this comments: https://github.com/envoyproxy/envoy/pull/33273#pullrequestreview-1998264437
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Adding integration test for match_delegate + composite + callout_filter in both downstrean and upstream

source/common/stats/symbol_table.cc, source/common/stats/symbol_table.h, test/common/stats/symbol_table_impl_test.cc
Commit Message: Add the ability to add a StatName to a StatNamePool directly.
Additional Description: If one maintains a StatNamePool to reference count symbols, provide a way to add to the pool directly vs needing to stringify. 
Risk Level: low / medium
=> Stats: Add the ability to add a StatName to a StatNamePool directly.

docs/root/configuration/http/http_filters/composite_filter.rst, source/extensions/filters/http/composite/config.cc, source/extensions/filters/http/composite/filter.cc, source/extensions/filters/http/composite/filter.h, test/extensions/filters/http/composite/filter_test.cc
This is to address issue: https://github.com/envoyproxy/envoy/issues/33343
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Skip filter state update when composite filter is in upstream

envoy/network/transport_socket.h, source/extensions/transport_sockets/common/passthrough.h, test/extensions/transport_sockets/common/passthrough_test.cc, test/mocks/network/BUILD, test/mocks/network/transport_socket.h
We're planning to make some changes to GoogleTest that requires having the definition of various types available in order to detect whether they're protobufs or not.
Commit Message: Fix layering issue in TransportSocket mocks.
Testing: n/a
Docs Changes:
Release Notes:
=> Fix layering issue in TransportSocket mocks.

test/common/network/listener_impl_test.cc
enable listener after client connections to ensure socket event once to fix the flaky test #33704
```
bazel test //test/common/network:listener_impl_test --test_filter=*EachQueuedConnectionShouldQueryTheLoadShedPoint* --runs_per_test=10000
```
Testing:
Docs Changes:
Release Notes:
Fix: #33704
=> load_shed: enable listener after client connections to ensure socket event once

api/bazel/api_build_system.bzl, api/bazel/repository_locations.bzl
Commit Message: rules_go//proto : use go_grpc_v2 instead of go_grpc
Additional Description: go_grpc is deprecated and shall be replaced by go_grpc_v2 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> rules_go//proto : use go_grpc_v2 instead of go_grpc

api/envoy/extensions/transport_sockets/tls/v3/common.proto, api/envoy/extensions/transport_sockets/tls/v3/tls.proto
Commit Message: api: define precedence between TLS cert fields
Additional Description: Instead of requiring fields to be mutually exclusive as was originally done in #17201, define precendence between them, to be consistent with the API guidance updated in #30851.  Note that this should not affect Envoy's implementation, since Envoy does not yet support CertificateProviders.
Testing: N/A
=> xds: define precedence between TLS cert fields

api/envoy/config/endpoint/v3/endpoint.proto, source/common/upstream/upstream_impl.cc, source/common/upstream/upstream_impl.h, test/common/upstream/upstream_impl_test.cc
This is the 2nd attempt for the PR : https://github.com/envoyproxy/envoy/pull/32062.
Adding runtime key to protect drop overload feature.
The runtime key "load_balancing_policy.drop_overload_limit" can be configured with an integer 0 to 100. 0 means 0%. 100 means 100%. So, when there is an EDS update with drop_overloads configuration, if this runtime key is enabled, Envoy will pick up the smaller one between these two to perform the drops.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Drop overload runtim key

source/common/json/json_streamer.cc, source/common/json/json_streamer.h, test/common/json/json_streamer_test.cc
Commit Message: Add support for boolean type to Envoy::Json::Streamer
Additional Description: Fixes #33752
Testing: Unit
Release Notes: Add support for boolean type to Envoy::Json::Streamer
@tonya11en @jmarantz
=> Add support for boolean type to Envoy::Json::Streamer

mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h, mobile/library/java/org/chromium/net/impl/NativeCronvoyEngineBuilderImpl.java
Envoy Mobile uses the system resolver for both Apple and Android, and the use_system_resolver_ variable doesn't control any code, so just cleaning up the unused method.
=> mobile: Remove the EngineBuilder::useDnsSystemResolver method

mobile/library/java/org/chromium/net/impl/NativeCronvoyEngineBuilderImpl.java
The C++ EngineBuilder API already supports setting runtime feature flags. This commit enables setting it from Cronvoy.
=> mobile: Add a setRuntimeGuard method on the Cronvoy Engine Builder

docs/root/configuration/observability/access_log/usage.rst
Fix `%RESPONSE_FLAGS_LONG%` command operator description.
=> docs: fix RESPONSE_FLAGS_LONG description

test/common/io/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> arm/tests: Temporarily disable failing `io_uring` test

contrib/dlb/source/BUILD
In the high kernel like 6.8, it would raise an error:
```
[dlb_domain_server()] Error: failed to share domain fd
[2024-04-16 04:55:50.055][7055][critical][backtrace] [./source/server/backtrace.h:127] Caught Segmentation fault, suspect faulting address 0x10
```
The dlb connection balancer does not need it, so disable it and make it work in high kernel.
Testing:
Docs Changes:
Release Notes:
=> dlb: disable domain server

envoy/config/config_provider_manager.h, envoy/router/BUILD, envoy/router/route_config_provider_manager.h, mobile/envoy_build_config/extension_registry.cc, mobile/test/performance/files_em_does_not_use, source/common/config/config_provider_impl.h, source/common/router/scoped_rds.cc, source/common/router/scoped_rds.h, source/exe/BUILD, source/extensions/filters/network/http_connection_manager/BUILD, source/extensions/filters/network/http_connection_manager/config.cc, source/extensions/filters/network/http_connection_manager/config.h, test/extensions/filters/network/http_connection_manager/config_filter_chain_test.cc, test/extensions/filters/network/http_connection_manager/config_filter_dependencies_test.cc, test/extensions/filters/network/http_connection_manager/config_test.cc, test/extensions/filters/network/http_connection_manager/config_test_base.h, test/integration/BUILD
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> envoy: removing srds from E-M

contrib/generic_proxy/filters/network/source/interface/codec_callbacks.h, contrib/generic_proxy/filters/network/source/interface/stream.h, contrib/generic_proxy/filters/network/source/proxy.cc, contrib/generic_proxy/filters/network/source/proxy.h, contrib/generic_proxy/filters/network/source/router/router.cc, contrib/generic_proxy/filters/network/source/router/router.h, contrib/generic_proxy/filters/network/test/codecs/dubbo/config_test.cc, contrib/generic_proxy/filters/network/test/codecs/http1/config_test.cc, contrib/generic_proxy/filters/network/test/codecs/kafka/config_test.cc, contrib/generic_proxy/filters/network/test/integration_test.cc, contrib/generic_proxy/filters/network/test/mocks/codec.h, contrib/generic_proxy/filters/network/test/proxy_test.cc, contrib/generic_proxy/filters/network/test/router/router_test.cc
Commit Message: generic proxy: expose the codec error to upper layer
This PR extend the interface of generic codec to expose error from codecs to upper layer. Than the upper layer could use the error message to generate meaningful log or local response.
Risk Level: low, contrib only change.
Testing: unit.
=> generic proxy: expose the codec error to upper layer

envoy/http/async_client.h, source/common/http/async_client_impl.cc, source/common/stream_info/stream_info_impl.h, test/common/http/async_client_impl_test.cc
Commit Message: Add support for FilterState to AsyncClient
Additional Description: This allows upstream filters used in an AsyncClient request to access the FilterState.
Testing: Updated unit tests.
=> async_client: add support for filter state

test/common/io/BUILD, test/common/io/io_uring_impl_test.cc
Commit Message: iouring: fix the IoUringImpl tests for the arm CI
The existing tests assume that the I/O request can be finished right after the request submission. Add waiting function before checking the I/O request completion, making those tests more reliable.
Fixes #33829
=> iouring: fix the IoUringImpl tests for latest kernel

source/common/config/well_known_names.cc, test/common/stats/tag_extractor_impl_test.cc
Commit Message: Extract route names with forward-slash.
Additional Description:  RDS protocol allows almost any route name, and stats are lightly sanitized before emitting to statsd and prometheus endpoints. This change slightly relaxes the capture group for RDS route names in stats, instead of opening the floodgates to everything, because YAGNI.
Testing: Updated unit test
Release Notes: N/A 
Fixes: #32976
=> stats: Extract route names with forward-slash

mobile/library/java/io/envoyproxy/envoymobile/engine/BUILD, mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyFinalStreamIntelImpl.java, mobile/library/java/org/chromium/net/impl/Errors.java, mobile/test/java/org/chromium/net/impl/BUILD, mobile/test/java/org/chromium/net/impl/ErrorsTest.java
`EnvoyFinalStreamIntel.getResponseFlags()` is set from the StreamInfo's response flags as a bitmap. It's possible that multiple filters set their own response flags, so there can end up being more than one response flag in `StreamInfo`. The previous logic of checking equality instead of checking in the bitmap was incorrect, so this commit fixes it and adds tests for the `mapEnvoyMobileErrorToNetError` method.
=> mobile: Fix the Cronvoy error mapping logic and add tests

source/docs/flow_control.md, source/docs/flow_control_downstream_backs_up_overview.drawio.svg
Commit Message: docs: Add figure: Downstream connection backs-up and backpressure overview. fix incorrect use Envoy::Http::ConnectionManagerImpl
Risk Level: na
Testing: na
=> Docs: flow control - Add a figure and fix suspected incorrect use of Envoy::Http::ConnectionManagerImpl

mobile/library/java/org/chromium/net/impl/CronvoyBidirectionalStream.java, mobile/library/java/org/chromium/net/impl/CronvoyBidirectionalStreamNetworkException.java, mobile/library/java/org/chromium/net/impl/CronvoyNetworkExceptionImpl.java, mobile/library/java/org/chromium/net/impl/CronvoyQuicExceptionImpl.java, mobile/library/java/org/chromium/net/impl/CronvoyUrlRequest.java, mobile/test/java/org/chromium/net/BidirectionalStreamTest.java, mobile/test/java/org/chromium/net/CronetUrlRequestTest.java
These details will be used by error consumers to add error details to logging pipelines.
=> mobile: Adds the ability to pass error details into Cronvoy exceptions

bazel/foreign_cc/ipp-crypto-bn2lebinpad.patch, bazel/repositories.bzl, contrib/cryptomb/private_key_providers/source/BUILD
Commit Message: cryptomb: add `BN_bn2lebinpad` definition for fips build (#33756)
The fips verison boringSSL is old. so it doesn't have the definition of BN_bn2lebinpad, so patch ipp-crypto to give a definition.
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes https://github.com/envoyproxy/envoy/issues/33585
=> [bp/1.30] cryptomb: add `BN_bn2lebinpad` definition for fips build (#33756)

test/extensions/filters/http/rate_limit_quota/integration_test.cc
=> RLQS: Add new throttling and disable flaky test that depends on pending stats implementation 

mobile/examples/cc/fetch_client/fetch_client.cc, mobile/library/cc/stream.cc, mobile/library/cc/stream.h, mobile/test/cc/engine_test.cc, mobile/test/cc/integration/BUILD, mobile/test/cc/integration/lifetimes_test.cc, mobile/test/cc/integration/send_headers_test.cc, mobile/test/common/integration/base_client_integration_test.cc, mobile/test/common/integration/base_client_integration_test.h, mobile/test/common/integration/client_integration_test.cc, mobile/test/common/integration/rtds_integration_test.cc
=> mobile: Remove the deprecated Stream::sendHeaders and Stream::sendTrailers

source/extensions/common/wasm/context.cc, test/extensions/common/wasm/test_data/test_context_cpp.cc, test/extensions/common/wasm/wasm_test.cc
Commit Message: wasm: Manage wasm invalid grpc code
Additional Description: In the scenario when the wasm generate a local reply with unset (invalid) grpc code. instead of propagate the -1, now the context will check and propagate the nullopt to let envoy populate it correctly.
Testing: yes
=> Manage wasm invalid grpc code

changelogs/current.yaml, source/common/runtime/runtime_features.cc
Flips the runtime feature `envoy_reloadable_features_http2_use_oghttp2` to be true by default.
Risk Level:
Testing: ran unit and integration tests locally, ran load tests exercising Envoy with oghttp2
Docs Changes:
Release Notes: Changes the default HTTP/2 codec from nghttp2 to oghttp2. Can be reverted by setting "envoy_reloadable_features_http2_use_oghttp2" to false.
=> http2: reenables oghttp2 by default

envoy/upstream/upstream.h, source/common/upstream/upstream_impl.cc, source/common/upstream/upstream_impl.h, source/extensions/clusters/original_dst/original_dst_cluster.cc, test/mocks/upstream/cluster_info.cc, test/mocks/upstream/cluster_info.h
Commit Message: upstream lb: remove unnecessary original dst lb config from cluster info
The orignal dst lb config is only used when we construct the original dst cluster. And we needn't store it in the cluster info because the constructor of original dst cluster could load the config directly.
Testing: n/a.
=> upstream lb: remove unnecessary original dst lb config from cluster info

mobile/library/jni/jni_utility.cc, mobile/test/jni/BUILD, mobile/test/jni/jni_utility_test.cc
This is to tell the JVM to not garbage collect the `ByteBuffer` until it's no longer used or else we might end up with a use-after-free. The `GlobalRef` will be deleted inside the `BufferFragmentImpl` releasor.
=> mobile: Wrap the direct ByteBuffer created by the JVM with a GlobalRef

mobile/ci/test_size_regression.sh, mobile/test/performance/test_binary_size.cc
The previous test_binary_size code was:
```
reinterpret_cast<Envoy::InternalEngine*>(0)->run(nullptr, nullptr);
```
This code has a couple problems: (1) we don't actually create an InternalEngine; we just cast an arbitrary
integer value (in this case, 0) to a InternalEngine pointer and (2) the `run()` function takes const references,
not pointers.  The way this code was structured, it's believed that the binary size expectations were incorrect,
because the compiler could strip/elide code that this particular program setup would render unused code.
After changing the program structure, we do indeed see a size difference.  Instead of 4.5MB, as is the current
expectation, we are seeing the program size actually as 5.41MB.
=> mobile: Fix the test_binary_size program to use the InternalEngine

source/common/http/header_map_impl.h, test/common/http/header_map_impl_speed_test.cc
Commit Message: Add static lookup benchmarks for header_map_impl
Additional Description: This aspect of header maps is not currently benchmarked and is apparently performance critical.
Output of the new benchmarks:
Benchmark | time | cpu | iterations
--- | --- | --- | ---
bmHeaderMapImplRequestStaticLookupHits        |  47.0 ns     |    47.0 ns  |  308763840
bmHeaderMapImplResponseStaticLookupHits      |   32.8 ns    |     32.8 ns |   428130226
bmHeaderMapImplRequestStaticLookupMisses     |   5.56 ns    |     5.56 ns |  1000000000
bmHeaderMapImplResponseStaticLookupMisses   |    5.85 ns   |      5.85 ns |  1000000000
Testing: It is.
=> Add static lookup benchmarks for header_map_impl

mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyFinalStreamIntelImpl.java
When a compiler has error-prone checks enabled, the VisibleForTesting annotation is not allowed on a public class.  This change removes the class-level annotation in favor of a comment.
=> mobile: Remove EnvoyFinalStreamIntelImpl's VisibleForTesting annotation

api/envoy/config/trace/v3/opencensus.proto, changelogs/current.yaml
Opencensus has been archived for some time upstream, i believe because it was folded in to opentelemetry.
The plan was to remove opencensus and opentracing altogether in the 1.31 release cycle, and both were set to deprecated.
Only opentracing had the `disabled_by_default` set in time for the release cycle, so this sets it for opencensus.
Original tracking issue is https://github.com/envoyproxy/envoy/issues/9958 bu there have been quite a few conversations around this since
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checkli …
=> opencensus: Disable by default

source/common/runtime/runtime_features.cc
Commit Message: Enable the quic_receive_ecn runtime guard.
Additional Description: Enable reporting of incoming Explicit Congestion Notification (ECN)  codepoints via QUIC ACK frames.
Testing: Previous PRs implement unit tests for this capability
Release Notes: Envoy now reports Explicit Congestion Notification (ECN, RFC 3168, RFC9330)  codepoints via QUIC ACK frames.
Platform Specific Features: Windows socket APIs for ECN are different. This is not implemented due to the lack of a Windows CI infrastructure.
=> Turn on receive_ecn runtime guard

source/extensions/http/injected_credentials/oauth2/token_provider.cc, test/extensions/http/credential_injector/oauth2/credential_injector_oauth_integration_test.cc
fixes: https://github.com/envoyproxy/envoy/issues/34040
Commit Message: OAuth2 Client Credential: Fix test flake
In tests, before firing http traffic request, make sure through stats that token is fetched. Since token fetching happens on main thread in async, without ensuring it is possible that before tls slot is set by main thread, worker thread attempts to inject the request, which would fail.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> OAuth2 Client Credential: Fix test flake

mobile/test/common/integration/base_client_integration_test.cc, mobile/test/common/integration/base_client_integration_test.h, mobile/test/common/integration/client_integration_test.cc, mobile/test/common/integration/rtds_integration_test.cc
This PR updates the code to follow Envoy coding style as well as using the `createNewStream` helper for consistency with the rest of the code.
=> mobile: ClientIntegrationTest cleanup

test/integration/python/BUILD, test/integration/python/hotrestart_handoff_test.py
Commit Message: Modify flake threshold for hotrestart_handoff_test
Additional Description: #33251 appears to be a racy flake due to tsan runs being slower. This adjustment is hopefully enough to keep it from flaking. If it continues to flake, it's probably worth considering making this test skipped for *san tests rather than increasing the tolerance any further, since integration tests don't really benefit much from *san anyway.
Turns out increasing the tolerance threshold actually makes the situation worse - it must be long enough for another envoy instance to fully start up, but also shorter than (some sort of connection idle timeout that occurs in quiche).
=> Modify flake threshold for hotrestart_handoff_test

source/extensions/tracers/opentelemetry/tracer.cc, source/extensions/tracers/opentelemetry/tracer.h, test/extensions/tracers/opentelemetry/BUILD, test/extensions/tracers/opentelemetry/operation_name_test.cc
Commit Message: implement setOperation for the opentelemetry provider
The detailed description is provided in [issue#34063](https://github.com/envoyproxy/envoy/issues/34063). In short, the MR implements a method for the OpenTelemetry tracing provider that was left empty and thus made the [`setOperation`](https://github.com/envoyproxy/envoy/blob/main/source/common/router/config_impl.cc#L460) method a no-op.
Testing: Unit testing and the [sandbox](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/opentelemetry).
Fixes [issue#34063](https://github.com/envoyproxy/envoy/issues/34063)
=> Implement setOperation for the opentelemetry provider

source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc
This PR adds the host information in the debug log messages to make debugging easier.
Risk Level: low (updating debug log messages only)
Testing: n/a
=> getaddrinfo: Add host info in the debug log messages

test/integration/BUILD, test/integration/tcp_tunneling_integration_test.cc
followup to https://github.com/envoyproxy/envoy/pull/32991
Commit Message: Add integration test for upstream http filters in tcp tunneling case
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Add integration test for upstream http filters in tcp tunneling case

api/envoy/admin/v3/server_info.proto, changelogs/current.yaml, docs/root/operations/cli.rst, envoy/server/options.h, source/exe/stripped_main_base.cc, source/server/hot_restart_impl.cc, source/server/hot_restart_impl.h, source/server/hot_restarting_child.cc, source/server/hot_restarting_child.h, source/server/options_impl.cc, source/server/options_impl_base.h, test/mocks/server/options.h, test/server/hot_restart_impl_test.cc, test/server/hot_restarting_child_test.cc, test/server/hot_restarting_parent_test.cc, test/server/options_impl_test.cc
Commit Message: Add command line flag to skip hot restart stats transfer
Additional Description: We had a number of issues with production servers having their main thread stuck trying to get stats from the parent instance. We're not entirely sure what the cause was, but we know stats can get big, we know that's where it was stuck, and we know there was 3 minutes of spare time during which the drain *should have* completed before the parent instance was hard-killed. It's possible that an out of memory occurred, it's possible the stream had a problem with the volume of data, it's possible there's a bug that causes the parent instance to lock up or crash during the stats retrieval, but one thing we can be confident of is that if we don't go down that branch at all then none of those things …
=> Add command line flag to skip hot restart stats transfer

mobile/.bazelrc
`//test/performance:test_binary_size` and `//library/cc/...` are not test targets, so passing `--build_tests_only` will not build those targets. That means the `cc-no-build-exceptions` CI will always have 0 targets. This PR fixes https://github.com/envoyproxy/envoy/issues/34114 by removing `--build_tests_only` from the build targets.
Testing: CI
=> mobile: Remove --build_tests_only from the build targets

mobile/test/common/integration/client_integration_test.cc, source/common/runtime/runtime_features.cc, source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc, source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> dfp: cleanup and cache feature

test/common/http/http1/codec_impl_test.cc
These characters are invalid according to RFC9110 Section 5.5 [1].
Either the message must be rejected, or the characters replaced by SP
according to the RFC. These tests confirm that both http-parser and
BalsaParser indeed either reject the message or remove the forbidden
characters, though neither of them seem to insert a SP in their place.
[1] https://www.rfc-editor.org/rfc/rfc9110.html#name-field-values
Commit Message: Add tests to document behavior when header value contains CR or LF.
Risk Level: low, test-only change
=> [balsa] Add tests to document behavior when header value contains CR or LF.

envoy/http/async_client.h, source/common/http/async_client_impl.cc, source/common/http/async_client_impl.h, test/common/http/async_client_impl_test.cc
Add option to disable `x-envoy-internal` on the async client path.
=> async_client: Add option to disable internal headers on async client path.

api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto, changelogs/current.yaml, source/extensions/filters/common/ext_authz/check_request_utils.cc, source/extensions/filters/common/ext_authz/check_request_utils.h, source/extensions/filters/http/ext_authz/ext_authz.cc, source/extensions/filters/http/ext_authz/ext_authz.h, test/extensions/filters/common/ext_authz/check_request_utils_test.cc, test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc, test/extensions/filters/http/ext_authz/ext_authz_test.cc
Commit Message: Add disallowed_headers knob to ext_authz config
Additional Description: This PR adds a config field to ext_authz that will prevent the specified headers from being sent to the external authentication service. This new field (disallowed_headers) will always override the allowed_headers field.
Testing: unit tests & integration tests
Release Notes: added to changelog
=> Add disallowed_headers knob to ext_authz config

mobile/library/jni/android_jni_utility.cc, mobile/library/jni/jni_impl.cc, mobile/library/jni/jni_utility.cc, mobile/library/jni/jni_utility.h
This PR does the following:
- Removes unused functions.
- Fixes typo in the function name.
- Updates  `isClearTextPermitted` implementation by converting from C++ String to `jstring` instead of going through an intermediate `envoy_data`.
=> mobile: JNI code clean up

source/extensions/upstreams/http/tcp/upstream_request.h
Commit Message: Fix for heap-use-after-free issue in Envoy::Tcp::ConnPoolImpl::onPoolReady (see #34055)
=> Clean up remaining streams in TcpConnPool dtor

changelogs/current.yaml, source/extensions/filters/common/ext_authz/check_request_utils.cc, source/extensions/filters/common/ext_authz/check_request_utils.h, test/extensions/filters/common/ext_authz/check_request_utils_test.cc
This is my first commit to the Envoy project and I haven't written C++ in many years. I'm still navigating the types and hierarchy and best practices for obtaining the data I need to complete this pull request. I have started in `draft` first to see the CI processes and look at how the tests run and if my changes cause any issues with current tests.
Commit Message: external authorization: set the SNI value from server name if it isn't available on the connection/socket
Additional Description: Leverages the TLS inspectors server name value, if one was set.
Testing: Will test that the SNI value is set from the server name of a connection when the TLS session doesn't have the SNI.
Release Notes: exterbal authorization …
=> external authorization: set the SNI value from server name if it isn't available on the connection/socket

source/common/router/BUILD, source/common/router/rds_impl.cc, source/common/router/rds_impl.h, source/common/router/route_provider_manager.cc, source/common/router/route_provider_manager.h, source/common/router/static_route_provider_impl.cc, source/common/router/static_route_provider_impl.h, source/extensions/filters/network/http_connection_manager/config.cc, source/extensions/filters/network/http_connection_manager/config.h, source/server/BUILD, source/server/server.cc, test/common/router/rds_impl_test.cc, test/common/router/scoped_rds_test.cc, test/common/router/vhds_test.cc
This also removes a utility which had switch-and-panic calls in favor of explicitly calling the create functions inline.
Risk Level: low: mostly code move.
Testing: n/a
=> route config: moving the route provider manager to its own file

docs/root/configuration/observability/access_log/usage.rst
To make the doc aligned with the actual behavior when proxy protocol filter is used on listener. We consistently set this in various places.
https://github.com/search?q=repo%3Aenvoyproxy%2Fenvoy%20Network%3A%3AProxyProtocolFilterState%3A%3Akey()&type=code
Testing:
Release Notes:
=> Clarify DOWNSTREAM_LOCAL_ADDRESS.

restarter/hot-restarter.py
**Current Behavior:**
The _hot-restarter.py_ script logs timestamps with a comma (,) separating seconds from milliseconds.
```
[2024-05-13 14:03:31,880][1][INFO][hot-restarter.py:210] starting hot-restarter with target: /usr/local/bin/start_envoy.sh
[2024-05-13 14:03:31,880][1][INFO][hot-restarter.py:183] forking and execing new child process at epoch 0
[2024-05-13 14:03:31,881][1][INFO][hot-restarter.py:192] forked new child process with PID=12
```
In addition, no category ID is output.
**Envoy's Format:**
Envoy, on the other hand, uses a dot (.) as the separator for milliseconds and outputs a category ID for each log entry.
```
[2024-05-13 15:25:30.105][12][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:369] dns resolution for filebrowser started
[2024-05-13 …
```
=> Adaptation of the log format of hot-restarter.py to the format of Envoy

source/extensions/access_loggers/common/BUILD, source/extensions/access_loggers/common/grpc_access_logger.h, source/extensions/access_loggers/common/grpc_access_logger_clients.h, source/extensions/access_loggers/grpc/BUILD, source/extensions/access_loggers/grpc/grpc_access_log_impl.cc, source/extensions/access_loggers/open_telemetry/BUILD, source/extensions/access_loggers/open_telemetry/grpc_access_log_impl.cc, source/extensions/access_loggers/open_telemetry/grpc_access_log_impl.h, test/extensions/access_loggers/common/grpc_access_logger_test.cc, test/extensions/access_loggers/open_telemetry/access_log_integration_test.cc, test/extensions/access_loggers/open_telemetry/grpc_access_log_impl_test.cc
This PR makes the OTel access logger to support log_written/log_dropped tracking
- failed gRPC requests
- partial rejected log entries, which is supported by [OTel protocol](https://github.com/open-telemetry/opentelemetry-proto/blob/b3060d2104df364136d75a35779e6bd48bac449a/opentelemetry/proto/collector/logs/v1/logs_service.proto#L69)
**Context**:
- After https://github.com/envoyproxy/envoy/pull/24268, OTel AccessLogger uses unary async client.
- The current `log_written/log_dropped` tracked in GrpcAccessLogger doesn't make sense for unary gRPC client, which always increment log_written for each incoming log entry. It couldn't record the 2 cases mentioned above.
**What this PR contains**:
- move grpc access loggers clients to a new file and make them DI for GrpcAccessLogger
- for unary …
=> OTel AccessLogger: support log_written/dropped for OTel partial rejected log records

api/envoy/extensions/filters/http/cache/v3/cache.proto, source/extensions/filters/http/cache/cache_filter.cc, source/extensions/filters/http/cache/cache_filter.h, source/extensions/filters/http/cache/config.cc, source/extensions/filters/http/cache/http_cache.cc, source/extensions/filters/http/cache/http_cache.h, test/extensions/filters/http/cache/cache_filter_test.cc, test/extensions/filters/http/cache/http_cache_test.cc
Commit Message: [cache filter] Add option to ignore cache-control directives from request
Additional Description: We noticed that, versus nginx cache, upstream was issuing many 304 responses. After some delving into what was happening, I tried commenting out the line that this change makes controllable, and the cache behaved more like our expectations. This PR makes it so we can have that sort of control via an option rather than via a patch.
Also addresses #12901 to make configuration more shared rather than initialized per-filter.
Risk Level: Low, it's a WIP filter and the behavior should be the same before and after unless the new option is set.
Testing: Added some.
=> [cache filter] Add option to ignore cache-control directives from request

mobile/library/common/http/client.cc, mobile/test/common/integration/client_integration_test.cc
1) errors should be able to precede headers
2) if we flush buffered data, we should immediately send a deferred error up.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> mobile: fixing an error flush bug with explicit flow control

test/common/router/corpus_from_config_impl.sh
If the config_impl_test_static executable exited with a non-zero exit code, the output text and the log message were not being printed as expected, thus obscuring the failure reason.
=> test: Fix exit code check in corpus_from_config_impl helper script

api/envoy/extensions/access_loggers/open_telemetry/v3/logs_service.proto, changelogs/current.yaml, source/extensions/access_loggers/open_telemetry/grpc_access_log_impl.cc, test/extensions/access_loggers/open_telemetry/grpc_access_log_impl_test.cc
As described in the API, this allows to distinguish emitted statistics between configured open telemetry access loggers in the logger chain. If empty, the default `access_logs.open_telemetry_access_log.` will be used.
It is based on https://github.com/envoyproxy/envoy/pull/34072 so please review from the 4th commit.
=> OTel Access Logger: support additional stat prefix

mobile/test/java/integration/AndroidEngineExplicitFlowTest.java
This PR fixes the flakiness issue in `AndroidEngineExplicitFlowTest` that relies on nondeterministic behavior related to the 0 byte when the end stream is true in Envoy Mobile. See https://github.com/envoyproxy/envoy-mobile/issues/1393. The PR also fixes the assertions to first check if there's an Envoy error and fails it other than executing the assertions and fails with NPE when there's an Envoy error.
Testing: --runs_per_test=100
=> mobile: Deflake AndroidEngineExplicitFlowTest

CODEOWNERS
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> add @tyxia to cel related code owner

mobile/test/java/integration/AndroidEngineExplicitFlowTest.java
=> mobile: Use getMessage() to print the error message in AndroidEngineExplicitFlowTest

mobile/.bazelrc
This is so that when building it locally, it will also use C++17 without having to manually pass `--cxxopt=-std=c++17 --host_cxxopt=-std=c++17`.
Testing: CI
=> mobile: Make C++17 a default build target

changelogs/current.yaml, source/extensions/filters/http/admission_control/thread_local_controller.cc, source/extensions/filters/http/admission_control/thread_local_controller.h, test/extensions/filters/http/admission_control/admission_control_filter_test.cc, test/extensions/filters/http/admission_control/controller_test.cc
This patch fixes a bug in the thread-local controller's average RPS
calculation. The controller was erroneously calculating the average over
the time elapsed since the oldest valid sample, which is incorrect. This
can result in erratic load shedding behavior for bursty request
distributions.
The correct behavior is to calculate the average RPS over the full
lookback window.
Release Notes: Documented the bugfix.
Fixes #33739
=> admission control filter: Fix average RPS calculation

contrib/generic_proxy/filters/network/source/proxy.cc, contrib/generic_proxy/filters/network/source/proxy.h, contrib/generic_proxy/filters/network/source/router/router.cc, contrib/generic_proxy/filters/network/test/router/router_test.cc
[generic proxy: fix possible infinite loop](https://github.com/envoyproxy/envoy/commit/d7347f72831a8a59faaf0be1ead970a47f04ca56)
Commit Message: generic proxy: fix possible infinite loop
The generic proxy will fall in infinite loop when the upstream connection is bound to downstream connection and the upstream request is reset because protocol error (or some other reasons), then the generic proxy router will fall in infinite loop because it can never complete the cleaning up of upstream request list.
Testing: unit.
=> generic proxy: fix possible infinite loop 

.bazelrc, bazel/repositories.bzl, bazel/rules_foreign_cc.patch
This extends the workaround that was added to macos to other builds
The need for the workaround wasnt macos specific - it relates more to the llvm/clang version used
fix #32426 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> bazel/build: Extend `no-int` workaround to `pkgconfig` for all builds

source/common/tcp_proxy/upstream.h
This change fixes ubsan error in the TcpTunnelingIntegrationTest.BasicUsePost test. This bug only affects ubsan builds as it can detect use of partially destructed objects. In this case the UpstreamRequest::clearRequestEncoder() which is called during destruction needs access to the CombinedUpstream::decoder_filter_callbacks_ member.
=> Fix ubsan error during CombinedUpstream destruction

source/common/http/http1/conn_pool.cc
parent_.stream_wrapper_->encode_complete_  is the same as this->encode_complete_
=> Remove redundant indirection

test/extensions/filters/listener/tls_inspector/tls_inspector_test.cc, test/extensions/filters/listener/tls_inspector/tls_utility.cc
Backport #34300  to release/v1.30 branch
This commit stops `generateClientHelloFromJA3Fingerprint()` generating client hellos containing an invalid ALPN extension. It also updates relevant `tls_inspector_test` functions to check the ALPN value, if expected.
When the `generateClientHelloFromJA3Fingerprint()` function was asked to include an ALPN extension (16) in the generated client hello, it was generating a default empty extension with the correct id (16) but a zero length. While this is technically a valid extension, it is not a valid ALPN extension, which must include a list of the client's preferred protocol(s).
This was causing test failures in the `envoyproxy/envoy-openssl` repo because OpenSSL responds to the malformed ALPN extension by sending a TLS alert 50 (Decode Error) which …
=> [Backport 1.30] tls_inspector: Fix invalid ALPN extension in test (#34300)

test/extensions/filters/listener/tls_inspector/tls_inspector_test.cc, test/extensions/filters/listener/tls_inspector/tls_utility.cc
Backport of #34300 to release/v1.28 branch.
This commit stops `generateClientHelloFromJA3Fingerprint()` generating client hellos containing an invalid ALPN extension. It also updates relevant `tls_inspector_test` functions to check the ALPN value, if expected.
When the `generateClientHelloFromJA3Fingerprint()` function was asked to include an ALPN extension (16) in the generated client hello, it was generating a default empty extension with the correct id (16) but a zero length. While this is technically a valid extension, it is not a valid ALPN extension, which must include a list of the client's preferred protocol(s).
This was causing test failures in the `envoyproxy/envoy-openssl` repo because OpenSSL responds to the malformed ALPN extension by sending a TLS alert 50 (Decode Error) …
=> [Backport 1.28] tls_inspector: Fix invalid ALPN extension in test (#34300)

mobile/library/common/internal_engine.cc, mobile/library/common/internal_engine.h, mobile/test/cc/engine_test.cc
When the `Engine` is not fully initialized, calling `terminate()` will cause an assertion failure.
```
[2024-05-21 21:28:16.718][18][critical][assert] [external/envoy/source/common/stats/thread_local_store.cc:49] assert failure: scopes_.empty().
```
This PR adds a workaround to wait until the `Engine` before proceeding to call `terminate()`.
=> mobile: Wait until the Engine is ready before calling terminate

mobile/test/common/integration/xds_integration_test.cc
This fixes the xDS related tests due to a missing SSL context.
=> mobile: Fix xDS integration tests

changelogs/current.yaml, docs/root/configuration/observability/access_log/usage.rst, source/common/formatter/http_specific_formatter.cc, source/common/formatter/http_specific_formatter.h, test/common/formatter/substitution_formatter_test.cc
Commit Message: for #34102, add %TRACE_ID% accesslog formatter.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #34102
=> accesslog: add %TRACE_ID% formatter

mobile/library/common/engine_types.h
This PR updates the comment for `on_data_` callback related to the `length`.
Risk Level: low (comment update only)
Testing: n/a
=> mobile: Update a comment about on_data_ callback

source/common/upstream/upstream_impl.cc, source/common/upstream/upstream_impl.h, source/extensions/clusters/eds/eds.cc, source/extensions/clusters/static/static_cluster.cc, source/extensions/clusters/strict_dns/strict_dns_cluster.cc
=> clusters: cleaning up some exceptions

mobile/library/kotlin/io/envoyproxy/envoymobile/AndroidEngineBuilder.kt
This fixes the following warning.
```
library/kotlin/io/envoyproxy/envoymobile/AndroidEngineBuilder.kt:7:28: warning: '@JvmOverloads' annotation has no effect for methods without default arguments
class AndroidEngineBuilder @JvmOverloads constructor(context: Context) : EngineBuilder() {
```
Testing: bazel build
=> mobile: Fix Kotlin warning

changelogs/current.yaml, source/common/http/http2/codec_impl.cc, source/common/http/http2/codec_impl.h, source/common/runtime/runtime_features.cc, test/common/http/http2/codec_impl_test.cc, test/common/http/http2/http2_frame.cc, test/common/http/http2/http2_frame.h, tools/spelling/spelling_dictionary.txt
This slightly simplifies the flow of DATA frame payloads; after this change, the `StreamDataFrameSource` class can be removed.
* `Http2Visitor::OnReadyToSendDataForStream()` is substantially the same implementation as `StreamDataFrameSource::SelectPayloadLength()`.
* `Http2Visitor::SendDataFrame()` is substantially the same as `StreamDataFrameSource::Send()`.
Commit Message: http2: migrates DATA frame payloads to the visitor API
Docs Changes:
Release Notes: added a note with the runtime feature to disable in case of problems
Runtime guard: `envoy_reloadable_features_http2_use_visitor_for_data`
=> http2: migrates DATA frame payloads to the visitor API

mobile/ci/mac_ci_setup.sh
This is an attempt to salvage some disk space since the iOS related tests are consistently running out of disk space.
Testing: CI
=> mobile: Remove homebrew caches and unused packages

ci/README.md, docs/root/_include/windows_support_ended.rst, docs/root/faq/overview.rst, docs/root/faq/windows/win_fips_support.rst, docs/root/faq/windows/win_not_supported_features.rst, docs/root/faq/windows/win_performance.rst, docs/root/faq/windows/win_requirements.rst, docs/root/faq/windows/win_run_as_service.rst, docs/root/faq/windows/win_security.rst, docs/root/start/building.rst, docs/root/start/install.rst, docs/root/start/quick-start/run-envoy.rst, docs/root/start/sandboxes/setup.rst, docs/root/start/sandboxes/win32_front_proxy.rst
Per #28588, Windows builds are unsupported. Make that clear in the documentation.
Additionally, remove references to the Windows docker image, which has not been updated
since 1.28.0 with the intention of not directing Windows operators towards a version missing
important security updates.
Risk Level: low, docs only
Testing: n/a
=> docs: clarify Windows build status

mobile/library/jni/jni_helper.cc, mobile/library/jni/jni_helper.h, mobile/library/jni/jni_impl.cc, mobile/library/jni/jni_utility.cc, mobile/library/jni/jni_utility.h, mobile/test/jni/jni_helper_test.cc, mobile/test/jni/jni_http_proxy_test_server_factory.cc, mobile/test/jni/jni_http_test_server_factory.cc, mobile/test/jni/jni_utility_test.cc, mobile/test/jni/jni_xds_test_server_factory.cc
Caching `jclass` should help with the performance as per https://developer.android.com/training/articles/perf-jni#jclass,-jmethodid,-and-jfieldid.
=> mobile: Cache the jclass objects

envoy/tracing/trace_driver.h, source/common/formatter/http_specific_formatter.cc, source/common/tracing/null_span_impl.h, source/extensions/access_loggers/open_telemetry/access_log_impl.cc, source/extensions/tracers/common/ot/opentracing_driver_impl.h, source/extensions/tracers/datadog/span.cc, source/extensions/tracers/datadog/span.h, source/extensions/tracers/opencensus/opencensus_tracer_impl.cc, source/extensions/tracers/opentelemetry/tracer.cc, source/extensions/tracers/opentelemetry/tracer.h, source/extensions/tracers/skywalking/tracer.h, source/extensions/tracers/xray/tracer.h, source/extensions/tracers/zipkin/zipkin_tracer_impl.h, test/common/formatter/substitution_formatter_test.cc, test/common/tracing/tracer_impl_test.cc, test/extensions/access_loggers/open_telemetry/access_log_impl_test.cc, test/extensions/filters/http/ext_proc/tracer_test_filter.cc, test/extensions/tracers/common/ot/opentracing_driver_impl_test.cc, test/extensions/tracers/datadog/span_test.cc, test/extensions/tracers/opencensus/tracer_test.cc, test/extensions/tracers/opentelemetry/opentelemetry_tracer_impl_test.cc, test/extensions/tracers/skywalking/tracer_test.cc, test/extensions/tracers/xray/tracer_test.cc, test/extensions/tracers/zipkin/zipkin_tracer_impl_test.cc, test/mocks/tracing/mocks.h
Commit Message: rename `getTraceIdAsHex` to `getTraceId`, becasuse not all tracer providers use hex format trace id.
Additional Description: follow up https://github.com/envoyproxy/envoy/pull/34198
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> rename getTraceIdAsHex to getTraceId

source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc
Commit Message: Fix a misplaced bracket in the switch statement
Testing: n/a
=> [dns]fix a switch statement syntax typo

configs/proxy_connect_udp_http3_downstream.yaml
I removed the unnecessary certificates provided in the client context and added SNI field that matches the testing certificate in the repo.
Risk Level: Low, this PR changes an example config.
Testing: N/A
=> config: Update CONNECT-UDP forwarding proxy config

.github/workflows/mobile-release.yml
This addresses job failures in the `Mobile Release` CI job: https://github.com/envoyproxy/envoy/actions/runs/9255379931/job/25460301873#step:6:33
=> mobile/ci: Set the default GPG key in the Mobile Release job

changelogs/current.yaml, source/extensions/filters/http/basic_auth/basic_auth_filter.cc, source/extensions/filters/http/basic_auth/basic_auth_filter.h, test/extensions/filters/http/basic_auth/basic_auth_integration_test.cc, test/extensions/filters/http/basic_auth/filter_test.cc
Commit Message: Adds valid WWW-Authenticate header for 401 response in Basic Auth filter
Testing: unit test, integration
Release Notes: Set ``WWW-Authenticate`` header for 401 responses from the Basic Auth filter.
Fixes #34015
=> basic_auth: add WWW-Authenticate header for 401 response

bazel/envoy_internal.bzl, test/extensions/tracers/dynamic_ot/config_test.cc, test/extensions/tracers/dynamic_ot/dynamic_opentracing_driver_impl_test.cc
Looks like this is slightly better as it catches things dynamic linking did not.
Testing: CI
=> build: static linking for sanitizers

test/extensions/filters/http/json_to_metadata/integration_test.cc
Realized that we use `GET` to send HTTP requests with body in integration test.
Testing: integ test
=> better semantic on http method for json_to_metadata filter

.github/workflows/mobile-release.yml
The changes in https://github.com/envoyproxy/envoy/pull/34390 resulted in an error:
```
/home/runner/.gnupg/gpg.conf: No such file or directory
```
=> mobile/ci: Set the default GPG key in the Mobile Release job (take 2)

test/extensions/filters/http/on_demand/odcds_integration_test.cc, test/extensions/filters/http/on_demand/on_demand_integration_test.cc, test/integration/ads_integration_test.cc, test/integration/base_integration_test.cc, test/integration/base_integration_test.h, test/integration/leds_integration_test.cc, test/integration/tcp_proxy_odcds_integration_test.cc, test/integration/vhds.h, test/integration/vhds_integration_test.cc
Commit Message: tests-refactor: pass unique_ptr pointer and not by ref
Passing a unique_ptr's pointer, instead of passing it by ref.
Part of #34417 that I took out of that PR to make it smaller.
Testing: N/A
=> tests-refactor: pass unique_ptr pointer and not by ref

mobile/library/jni/jni_helper.cc, mobile/library/jni/jni_helper.h, mobile/library/jni/jni_impl.cc, mobile/test/jni/jni_helper_test.cc, mobile/test/jni/jni_utility_test.cc
This PR does a clean by deleting the JNI caches as well as deleting the `jclass` global references in `JNI_OnUnload`.
=> mobile: Perform clean up in JNI_OnUnload

contrib/generic_proxy/filters/network/source/router/BUILD, contrib/generic_proxy/filters/network/source/router/router.cc, contrib/generic_proxy/filters/network/source/router/router.h, contrib/generic_proxy/filters/network/source/router/upstream.cc, contrib/generic_proxy/filters/network/source/router/upstream.h, contrib/generic_proxy/filters/network/test/router/BUILD, contrib/generic_proxy/filters/network/test/router/router_test.cc, contrib/generic_proxy/filters/network/test/router/upstream_test.cc
Commit Message: generic proxy: split the upstream to different module to simply test and mock
1. Splited current upstream to `DecoderEncoder` and `GenericUpstream`. This make all these modules depend others by interfaces. This make it's possible to do flexible mock.
2. Now the client `DecoderEncoder` has same lifetime with the client connection (upstream connection).
Risk Level: low. Contrib only change.
Testing: unit.
=> generic proxy: split the upstream to different module to simply test and mock

api/envoy/extensions/transport_sockets/tls/v3/common.proto
Commit Message: xds: add use_system_root_certs to CertificateValidationContext
Additional Description: This allows using system root certs in gRPC.  For details, see https://github.com/grpc/proposal/pull/436.
Testing: N/A
=> xds: add use_system_root_certs to CertificateValidationContext

source/common/upstream/upstream_impl.cc, test/common/tcp/conn_pool_test.cc, test/common/upstream/upstream_impl_test.cc, test/extensions/clusters/eds/eds_test.cc
Change-Id: Ia868bb4d9cbf78de23bc43b6a162edcc065aa762
Commit Message: set host info on stream info for upstream filters. This is useful in upstream filters since the host is known.
Testing: regression
=> upstream: set host on stream info for upstream filters

source/server/server.cc
#33907 
total connections are not strictly related to hot_start
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> stats: move out the total_connections from hot restart related stats

docs/root/intro/arch_overview/advanced/attributes.rst, source/extensions/filters/common/expr/context.h, source/extensions/filters/common/expr/evaluator.cc, test/extensions/filters/common/expr/BUILD, test/extensions/filters/common/expr/evaluator_test.cc, test/integration/filters/empty.proto
Commit Message: Add upstream filter state accessor, for consistency with Wasm and log formatters.
Testing: added
=> attribute: add upstream filter state

contrib/generic_proxy/filters/network/source/BUILD, contrib/generic_proxy/filters/network/source/access_log.cc, contrib/generic_proxy/filters/network/source/access_log.h, contrib/generic_proxy/filters/network/source/interface/BUILD, contrib/generic_proxy/filters/network/source/interface/proxy_config.h, contrib/generic_proxy/filters/network/source/interface/route.h, contrib/generic_proxy/filters/network/source/interface/stream.h, contrib/generic_proxy/filters/network/source/match.cc, contrib/generic_proxy/filters/network/source/match.h, contrib/generic_proxy/filters/network/source/match_input.h, contrib/generic_proxy/filters/network/source/proxy.cc, contrib/generic_proxy/filters/network/source/proxy.h, contrib/generic_proxy/filters/network/source/route.cc, contrib/generic_proxy/filters/network/source/route.h, contrib/generic_proxy/filters/network/test/match_test.cc, contrib/generic_proxy/filters/network/test/mocks/route.h, contrib/generic_proxy/filters/network/test/proxy_test.cc, contrib/generic_proxy/filters/network/test/route_test.cc
Commit Message: generic proxy: enhance match input data to support more attributes
Extended the match input of generic proxy to use both request and stream info. This provide more possible flexible matching.
Testing: n/a.
=> generic proxy: enhance match input data to support more attributes

test/common/router/header_parser_corpus/append_and_append_action, test/common/router/header_parser_fuzz_test.cc
Commit Message: header_parser_fuzz handle StatusOr error gracefully
Following #34388 this PR does graceful handling of a parser error.
Testing: Added corpus entry.
Fixes fuzz issue [69360](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69360).
=> fuzz: header_parser_fuzz handle StatusOr error gracefully

.github/workflows/mobile-release.yml
The `gpg --import` command does not use the `--default-key` option.
=> mobile/ci: Mobile Release job GPG import fix

envoy/network/dns_resolver.h, source/common/upstream/cluster_factory_impl.cc, source/common/upstream/cluster_factory_impl.h, source/extensions/clusters/logical_dns/logical_dns_cluster.cc, source/extensions/clusters/redis/redis_cluster.cc, source/extensions/clusters/strict_dns/strict_dns_cluster.cc, source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc, source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h, source/extensions/common/wasm/wasm.cc, source/extensions/filters/udp/dns_filter/dns_filter_resolver.h, source/extensions/network/dns_resolver/apple/apple_dns_impl.cc, source/extensions/network/dns_resolver/cares/dns_impl.cc, source/extensions/network/dns_resolver/cares/dns_impl.h, source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.h, source/server/config_validation/server.cc, source/server/config_validation/server.h, source/server/server.cc, test/extensions/filters/http/dynamic_forward_proxy/test_resolver.h, test/extensions/network/dns_resolver/apple/apple_dns_impl_test.cc, test/extensions/network/dns_resolver/cares/dns_impl_test.cc, test/extensions/network/dns_resolver/getaddrinfo/getaddrinfo_test.cc, test/mocks/network/mocks.h
=> dns: removing exceptions from resolver

mobile/bazel/kotlin_test.bzl, mobile/library/kotlin/io/envoyproxy/envoymobile/EngineImpl.kt, mobile/library/kotlin/io/envoyproxy/envoymobile/StreamCallbacks.kt, mobile/library/kotlin/io/envoyproxy/envoymobile/StreamPrototype.kt, mobile/test/java/io/envoyproxy/envoymobile/engine/BUILD, mobile/test/kotlin/io/envoyproxy/envoymobile/BUILD, mobile/test/kotlin/io/envoyproxy/envoymobile/mocks/BUILD
`associates` is not supported in Google's internal build rules. This PR also refactors the code to avoid needing `associates`.
=> mobile: Remove associates in Kotlin build rules

source/common/network/connection_impl.cc
Commit Message: Add ip address family info to error details upon socket connect failure
Additional Description: This helps reveal more info on why the socket connection fails immediately
Testing: n/a
=> [network]Add ip address family info to error details upon socket connect failure

.github/workflows/mobile-cc_tests.yml, .github/workflows/mobile-compile_time_options.yml, mobile/.bazelrc
The `compile-time-options` should be reserved for running the build different compilation options, such as enabling xDS, full protos, etc and not for running `//test/common` tests.
Testing: CI
=> mobile: Move all C++ tests into cc-tests

api/envoy/config/core/v3/protocol.proto, changelogs/current.yaml, envoy/stream_info/stream_info.h, source/common/http/async_client_impl.cc, source/common/http/conn_manager_config.h, source/common/http/conn_manager_impl.cc, source/common/router/router.cc, source/common/router/router.h, source/common/stream_info/stream_info_impl.h, source/extensions/filters/network/http_connection_manager/config.cc, source/extensions/filters/network/http_connection_manager/config.h, source/extensions/health_checkers/grpc/health_checker_impl.cc, source/extensions/health_checkers/http/health_checker_impl.cc, source/server/admin/admin.h, test/common/http/conn_manager_impl_fuzz_test.cc, test/common/http/conn_manager_impl_test_2.cc, test/common/http/conn_manager_impl_test_base.cc, test/common/http/conn_manager_impl_test_base.h, test/common/router/router_2_test.cc, test/common/router/router_test.cc, test/extensions/filters/network/http_connection_manager/config_test.cc, test/mocks/http/mocks.h, test/mocks/stream_info/mocks.h, test/server/admin/admin_test.cc
Commit Message: add match_upstream to SchemeHeaderTransformation
Additional Description: Define a new variant that configures the hcm to override the scheme with the upstream transport protocol. The value is accessible by all downstream filters and is specifically used by the Router filter. Renamed variant from `use_upstream_scheme` to be clear that the scheme matches the transport protocol.
Testing: unit testing
Fixes #33020
=> hcm: add match_upstream to SchemeHeaderTransformation

contrib/generic_proxy/filters/network/source/codecs/dubbo/config.h, contrib/generic_proxy/filters/network/source/codecs/http1/config.cc, contrib/generic_proxy/filters/network/source/codecs/http1/config.h, contrib/generic_proxy/filters/network/source/codecs/kafka/config.cc, contrib/generic_proxy/filters/network/source/codecs/kafka/config.h, contrib/generic_proxy/filters/network/source/interface/codec.h, contrib/generic_proxy/filters/network/source/interface/codec_callbacks.h, contrib/generic_proxy/filters/network/source/interface/filter.h, contrib/generic_proxy/filters/network/source/interface/stream.h, contrib/generic_proxy/filters/network/source/proxy.cc, contrib/generic_proxy/filters/network/source/proxy.h, contrib/generic_proxy/filters/network/source/router/router.cc, contrib/generic_proxy/filters/network/source/router/router.h, contrib/generic_proxy/filters/network/test/codecs/dubbo/config_test.cc, contrib/generic_proxy/filters/network/test/codecs/http1/config_test.cc, contrib/generic_proxy/filters/network/test/codecs/kafka/config_test.cc, contrib/generic_proxy/filters/network/test/fake_codec.h, contrib/generic_proxy/filters/network/test/integration_test.cc, contrib/generic_proxy/filters/network/test/mocks/codec.h, contrib/generic_proxy/filters/network/test/mocks/filter.h, contrib/generic_proxy/filters/network/test/proxy_test.cc, contrib/generic_proxy/filters/network/test/router/router_test.cc
Commit Message: generic proxy: change the encode interface to sync mode
In the initial design of generic codec, full async interface is used for both encoding and decoding. it make that offloading encoding and decoding to other hardware is possible. But, after the practice in the production env, we found the offloading just an illusion.
The async decoding is just well. But the async encoding bring nothing except complexity. This PR removed the async encoding and make it to use sync interface.
Testing: unit, integration
=> generic proxy: change the encoding interface to sync mode

test/extensions/tracers/zipkin/span_buffer_test.cc
Commit Message: Fix //test/extensions/tracers/zipkin:zipkin_test on big-endian systems.
Additional Description: The subtest "ZipkinSpanBufferTest.SerializeSpan" was failing due to discrepancies in the id field of the expected JSON string and the serialized JSON representation. The expected id was `AQAAAAAAAAA=` but we were getting `AAAAAAAAAAE=` on s390x. This was only occurring when serializing the buffer with HTTP_PROTO whereas HTTP_JSON was working fine. On checking more into the serialized MessageToJsonString, I found that the hexadecimal representation of id was `id: "\000\000\000\000\000\000\000\001"`  which is `id:"AAAAAAAAAAE="` on s390x and that on Intel was ` id: "\001\000\000\000\000\000\000\000"` which is  `id:"AQAAAAAAAAA="` . Further found that this is occurring due to …
=> Fix zipkin_test on big-endian systems

test/common/network/multi_connection_base_impl_test.cc
Additional Description: The Hashkey subtest fais when comparing the specific elements in id_array and hash_key vector. Byte-swapping the id_array resolves the issue. Little endian platforms are not affected by this change.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Fix //test/common/network:multi_connection_base_impl_test on big endian

mobile/library/common/http/client.cc, mobile/library/java/org/chromium/net/impl/Errors.java, mobile/test/common/http/client_test.cc, mobile/test/java/org/chromium/net/CronetUrlRequestTest.java, mobile/test/java/org/chromium/net/impl/ErrorsTest.java
This PR adds response flags into the error message for more debugging info. This PR also updates the logic in Cronvoy to perform an error check based on the response flags first and then do the HTTP/3 protocol error check last.
=> mobile: Add response flags in the error message

mobile/library/common/internal_engine.cc
=> mobile: Increase the engine running timeout to 30 seconds

mobile/examples/cc/fetch_client/fetch_client.cc, mobile/library/common/bridge/utility.cc, mobile/library/common/engine_types.h, mobile/library/common/http/client.cc, mobile/library/jni/jni_impl.cc, mobile/library/objective-c/EnvoyHTTPStreamImpl.mm, mobile/test/cc/engine_test.cc, mobile/test/cc/integration/lifetimes_test.cc, mobile/test/cc/integration/receive_data_test.cc, mobile/test/cc/integration/receive_headers_test.cc, mobile/test/cc/integration/receive_trailers_test.cc, mobile/test/cc/integration/send_data_test.cc, mobile/test/cc/integration/send_headers_test.cc, mobile/test/cc/integration/send_trailers_test.cc, mobile/test/common/http/client_test.cc, mobile/test/common/integration/client_integration_test.cc
This PR updates the `on_error_` callback to pass `EnvoyError` by const ref instead of value. This PR also appends `_` in the struct field members of `EnvoyError` to conform with Envoy naming convention.
=> mobile: Pass EnvoyError by const ref

source/extensions/config_subscription/grpc/xds_mux/BUILD, source/extensions/config_subscription/grpc/xds_mux/grpc_mux_impl.cc, source/extensions/config_subscription/grpc/xds_mux/grpc_mux_impl.h, test/extensions/config_subscription/grpc/xds_grpc_mux_impl_test.cc
Commit Message: xds-failover: add unified gRPC mux support
This PR introduces xDS-Failover support for unified gRPC mux implementations.
This is similar to #34437, and another part of #34417.
Risk Level: medium if the runtime flag is set to true and unified-gRPC-mux is used.
Testing: Updated the test cases (parameterized).
=> xds-failover: add unified gRPC mux support

bazel/BUILD, source/exe/BUILD, test/config_test/BUILD
To avoid ambiguity when building with `//bazel:http3=False` (on PPC and Windows) this commit adds 2 new `config_setting_group`s and updates the relevant `select()` statements.
Fixes #34482
=> Fixed bazel configuration ambiguity for non HTTP3 builds

envoy/config/subscription_factory.h, envoy/runtime/runtime.h, source/common/config/subscription_factory_impl.cc, source/common/config/subscription_factory_impl.h, source/common/filter/config_discovery_impl.cc, source/common/listener_manager/lds_api.cc, source/common/rds/rds_route_config_subscription.cc, source/common/router/scoped_rds.cc, source/common/router/vhds.cc, source/common/runtime/runtime_impl.cc, source/common/runtime/runtime_impl.h, source/common/secret/sds_api.cc, source/common/upstream/cds_api_impl.cc, source/common/upstream/od_cds_api_impl.cc, source/extensions/clusters/eds/eds.cc, source/extensions/clusters/eds/leds.cc, source/server/config_validation/server.cc, source/server/server.cc, test/common/runtime/runtime_impl_test.cc, test/common/secret/sds_api_test.cc, test/extensions/config_subscription/common/subscription_factory_impl_test.cc, test/mocks/config/mocks.h, test/mocks/runtime/mocks.h, tools/code_format/config.yaml
=> subscription: making exception free

source/extensions/filters/network/mongo_proxy/bson_impl.cc
Commit Message: Fix //test/extensions/filters/network/mongo_proxy:codec_impl_test and //test/extensions/filters/network/mongo_proxy:bson_impl_test and tests on big endian systems.
Additional Description: `//test/extensions/filters/network/mongo_proxy:codec_impl_test` and `//test/extensions/filters/network/mongo_proxy:bson_impl_test`
fails because applying `le32toh` or `le64toh` on big-endian systems incorrectly converts values that are already in the correct format, leading to data corruption.
Signed-off-by: Sankalp [Sankalp@ibm.com](mailto:Sankalp@ibm.com)
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
=> Fix mongo_proxy:codec_impl_test and mongo_proxy:bson_impl_test on big endian

mobile/library/java/io/envoyproxy/envoymobile/engine/JvmFilterContext.java
The filter implementations don't typically run in a separate thread, so creating a copy is unnecessary.
=> mobile: Remove unnecessary copies in the JvmFilterContext

api/envoy/extensions/filters/http/oauth2/v3/oauth.proto, source/extensions/filters/http/oauth2/config.cc, source/extensions/filters/http/oauth2/filter.cc, source/extensions/filters/http/oauth2/filter.h, test/extensions/filters/http/oauth2/config_test.cc, test/extensions/filters/http/oauth2/filter_test.cc
Allows to preserve the existing authorization header in oauth2 filter
Commit Message: oauth filter: preserve existing auth header: 
Risk Level: Low - small optional feature
Release Notes: Added oauth2 filter config preserve_authorization_header, which allows to preserve the existing authorization header in oauth2 filter
Fixes: #34236
=> oauth filter: preserve existing auth header

mobile/test/common/integration/BUILD, mobile/test/java/integration/BUILD, mobile/test/java/io/envoyproxy/envoymobile/engine/testing/BUILD, mobile/test/java/org/chromium/net/BUILD, mobile/test/java/org/chromium/net/impl/BUILD, mobile/test/java/org/chromium/net/testing/BUILD, mobile/test/java/org/chromium/net/urlconnection/BUILD, mobile/test/kotlin/integration/BUILD, mobile/test/kotlin/integration/proxying/BUILD
`sandboxNetwork=standard` is no longer needed.
Risk Level: low  (tests only)
Testing: CI
=> mobile: Remove sandboxNetwork=standard

test/extensions/tracers/datadog/agent_http_client_test.cc, test/per_file_coverage.sh
Basically revert this change #34553 with more tests
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> coverage: add datadog test and bring back `extensions/tracers` threshhold

changelogs/current.yaml, source/common/http/conn_manager_impl.cc, source/common/http/conn_manager_impl.h, source/common/runtime/runtime_features.cc, test/common/http/conn_manager_impl_test.cc, test/integration/filter_integration_test.cc
Commit Message: runtime: remove refresh rtt runtime flag
Long time go and seems no one complain this default false runtime flag. We will remove it now. Now this is no way to force envoy to refresh rtt for every request. But the rtt could be refreshed cyclically by the tcp_stats extension.
cc @ggreenway cc @botengyao cc @soulxu cc @alyssawilk 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> runtime: remove refresh rtt runtime flag

source/extensions/filters/udp/dns_filter/dns_parser.cc, source/extensions/filters/udp/dns_filter/dns_parser.h, test/extensions/filters/udp/dns_filter/dns_filter_test.cc
Fixes:
//test/extensions/filters/udp/dns_filter:dns_filter_integration_test //test/extensions/filters/udp/dns_filter:dns_filter_test on big endian platforms.
Additional Description: These changes fix the serialization of 128 bit ip address values on big endian platforms and adds a big endian definition of the dns header struct with the fields ordered so that they can be serialized easily on big endian platforms.
One test is skipped on s390x builds due to a known issue with the undetermined ordering of some of the test values that happens reliably on s390x.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
=> Add big endian support to the dns parser

source/common/websocket/codec.cc
Additional Description: As length is set using memcpy and further processed as per LE format, the test fails on s390x(big endian). Little endian platforms are not affected by this change.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Fix //test/common/websocket:codec_test on big endian

api/envoy/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto, changelogs/current.yaml, docs/root/configuration/listeners/listener_filters/proxy_protocol.rst, source/common/config/well_known_names.cc, source/common/config/well_known_names.h, source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc, source/extensions/filters/listener/proxy_protocol/proxy_protocol.h, test/common/stats/tag_extractor_impl_test.cc, test/extensions/filters/listener/proxy_protocol/proxy_proto_integration_test.cc
proxy_protocol_filter: Add field `stat_prefix` to the filter configuration
This field allows for differentiating statistics when multiple proxy protocol listener filters are configured.
This PR is a follow-up from previous conversation: https://github.com/envoyproxy/envoy/pull/32861#discussion_r1539832395
- All client-facing behavior changes are guarded by new filter config field.
Testing:
- Stats unit tests
- Proxy protocol listener filter integration tests
Docs Changes:
Done
Release Notes:
Done
None
=> proxy_protocol_filter: Add field `stat_prefix` to the filter configuration

test/extensions/filters/http/ext_authz/ext_authz_fuzz_lib.cc, test/extensions/filters/http/ext_authz/ext_authz_fuzz_lib.h
Commit Message: ext_authz fuzzers: fuzz request body
Additional Description: This PR allows the ext_authz fuzzers to access [this code block](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/common/ext_authz/check_request_utils.cc#L182-L210) and start fuzzing the request body handling code.
=> ext_authz fuzzers: fuzz request body

mobile/ci/mac_ci_setup.sh
This is to fix this CI failure: https://github.com/envoyproxy/envoy/actions/runs/9450017536/job/26029390577#step:8:1452
Prior to this PR, the script would check if a homebrew package had already been installed via `brew ls --versions <package>`, I suspect there is a change in behavior where `brew ls --versions <package>` no longer returns non-zero exit code causing the `install` function to not be executed, which means `coreutils` package would never be installed. The fix is to remove the `is_installed` function since reinstalling a homebrew package that already exists is fine.
Testing: CI
=> mobile: Remove is_installed function for checking installed Homebrew package

changelogs/current.yaml, source/common/http/http2/BUILD, source/common/http/http2/metadata_decoder.cc, source/common/http/http2/metadata_decoder.h, source/common/runtime/runtime_features.cc, test/common/http/http2/metadata_encoder_test.cc
Fixes https://github.com/envoyproxy/envoy/issues/30418
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> runtime: removing http2_decode_metadata_with_quiche

.bazelrc, test/common/quic/envoy_quic_client_session_test.cc
Commit Message: Fix flakiness in ECN test
Additional Description: Check that the device under test actually received packets before checking if those packets are marked ECT(1).
Testing: Was able to repro flakiness with 1000 runs of EnvoyQuicClientSessionTest without any test filter, and this PR fixes it.
[Optional Fixes #Issue] 34582
=> Fix ECN test flakiness

test/integration/quic_http_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes #34640
=> quic: fix test flake in UsesPreferredAddressDNAT

test/extensions/filters/http/common/fuzz/uber_filter.cc, test/extensions/filters/http/common/fuzz/uber_filter.h
Commit Message: Fix double-calling onDestroy bug in filter fuzzer
Additional Description: Prerequisite of #34612 which provokes an error if onDestroy is called twice on the same filter.
Risk Level: Test-only.
Testing: Test that fails without this change passes after this change.
=> Fix double-calling onDestroy bug in filter fuzzer

.bazelrc
I'm hoping making it async will make bes failure upload a non-fail for CI
see https://bazel.build/reference/command-line-reference#flag--bes_upload_mode
=> CI: bumping bes timeout, making aync

docs/root/configuration/http/http_filters/_include/aws_credentials.rst, source/extensions/common/aws/utility.cc, test/extensions/common/aws/utility_test.cc
Commit Message: aws: sts and webidentity fix for sigv4a edge case
If webidentity provider and sigv4a are both in use, and a regionset is used for sigv4a, sts endpoint could be generated incorrectly. This amends utility.cc to handle this edge case.
If a regionset is provided (ie the region string contains a comma or a *) the following logic will occur:
- Split the regionset by comma
- If first region still contains a *, return global endpoint sts.amazonaws.com (or FIPS us-east-1 if in FIPS mode)
- Otherwise, use the first region
Testing: Unit
Docs Changes:
Release Notes:
[Optional [API …
=> aws: sts and webidentity fix for sigv4a edge case

source/common/config/datasource.cc, source/common/router/config_impl.cc, source/common/router/config_utility.cc, source/common/router/config_utility.h, test/common/config/datasource_test.cc, test/common/router/config_impl_test.cc
Commit Message: data source: clean up unnecessary method and correct the behavior of max_size
We introduced dynamic file support at #32789. But there is error about the max_size (because my incorrect insistence when doing review.)
This PR fixed it and cleaned up unnecessary legacy method.
Testing: unit.
=> data source: clean up unnecessary method and correct the behavior of max_size

mobile/docs/root/api/starting_envoy.rst, mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h, mobile/library/java/org/chromium/net/impl/NativeCronvoyEngineBuilderImpl.java, mobile/library/jni/jni_impl.cc, mobile/library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt, mobile/library/objective-c/EnvoyConfiguration.mm, mobile/library/swift/EngineBuilder.swift, mobile/test/cc/unit/envoy_config_test.cc, mobile/test/common/integration/client_integration_test.cc, mobile/test/kotlin/io/envoyproxy/envoymobile/EngineBuilderTest.kt, mobile/test/swift/EngineBuilderTests.swift, mobile/test/swift/integration/KeyValueStoreTest.swift
Calling it `addRuntimeGuard` makes more sense since we can add multiple runtime guards. This PR also adds comments related to what the guard name is.
Testing: CI
=> mobile: Rename setRuntimeGuard to addRuntimeGuard

ci/filter_example_setup.sh, contrib/golang/common/dso/dso.cc, contrib/golang/common/dso/dso.h, contrib/golang/common/dso/libgolang.h, contrib/golang/common/dso/test/mocks.h, contrib/golang/common/dso/test/test_data/simple.go, contrib/golang/filters/http/source/go/pkg/http/BUILD, contrib/golang/filters/http/source/go/pkg/http/asan.go, contrib/golang/filters/http/source/go/pkg/http/config.go, contrib/golang/filters/http/source/go/pkg/http/shim.go, contrib/golang/filters/http/test/config_test.cc, contrib/golang/filters/http/test/golang_filter_test.cc, contrib/golang/filters/http/test/golang_integration_test.cc, contrib/golang/filters/http/test/websocket_integration_test.cc
add a new API(only for testing) to clean up resources that are referenced on the Golang side, to make asan happy.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Golang filter: make asan clean

source/common/common/bit_array.h
Commit Message: //test/common/common:bit_array_test fails on big endian(s390x) as safeMemcpyUnsafeDst doesn't return expected values.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Fix //test/common/common:bit_array_test on s390x

contrib/generic_proxy/filters/network/source/codecs/dubbo/config.h, contrib/generic_proxy/filters/network/source/codecs/http1/config.h, contrib/generic_proxy/filters/network/source/codecs/kafka/config.h, contrib/generic_proxy/filters/network/source/interface/stream.h, contrib/generic_proxy/filters/network/source/proxy.cc, contrib/generic_proxy/filters/network/source/router/router.cc, contrib/generic_proxy/filters/network/source/router/router.h, contrib/generic_proxy/filters/network/test/codecs/http1/config_test.cc, contrib/generic_proxy/filters/network/test/fake_codec.h, contrib/generic_proxy/filters/network/test/integration_test.cc, contrib/generic_proxy/filters/network/test/proxy_test.cc, contrib/generic_proxy/filters/network/test/router/router_test.cc, contrib/generic_proxy/filters/network/test/router/upstream_test.cc
Commit Message: generic proxy: filter chain support for local reply and refactored the stream flags
1. filter chain support for the local reply.
2. refactored the stream flags.
Risk Level: low, contrib only.
Testing: unit.
=> generic proxy: filter chain support for local reply and refactored the stream flags

api/envoy/config/core/v3/base.proto
Commit Message: api: common key/value pair and options for key/value appending
Seems until now, we still have no a common key/value API that be applied to string-map-like structures. This PR add one.
Then we can use this API for query mutation, cookie mutation. And this could also be used by non-HTTP headers (like dubbo attachment) or any string-map-like structures.
Risk Level: low. API only.
Testing: n/a.
=> api: common key/value pair and options for key/value appending

changelogs/current.yaml, source/common/grpc/async_client_impl.cc, source/common/grpc/google_async_client_impl.cc, source/common/grpc/google_async_client_impl.h, test/common/grpc/google_async_client_impl_test.cc, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/tracer_test_filter.cc
Commit Message: grpc: propagate tracing headers when using google grpc streams
Additional Description:  Following up on https://github.com/envoyproxy/envoy/pull/33665, which adds tracing to Envoy gRPC streams, this PR introduces the same support using Google gRPC for completeness to https://github.com/envoyproxy/envoy/issues/21119.
Testing: The same manual tests described in https://github.com/envoyproxy/envoy/pull/33665, besides the integration tests of extproc are also testing google grpc now.
=> grpc: propagate tracing headers when using google grpc streams

source/common/filesystem/posix/filesystem_impl.cc, test/common/filesystem/filesystem_impl_test.cc, tools/spelling/spelling_dictionary.txt
In our environment, the file system directory is as follows:
```
Tue Jun 04 22:28:35][#48# ]$df -h
Filesystem                 Size  Used Avail Use% Mounted on
tmpfs                       77G  104K   77G   1% /dev/shm
tmpfs                       31G  9.8M   31G   1% /run
tmpfs                      5.0M     0  5.0M   0% /run/lock
tmpfs                      4.0M     0  4.0M   0% /sys/fs/cgroup
/dev/mapper/atomicos-root  150G  144G  5.8G  97% /sysroot
/dev/vda2                  483M   84M  400M  18% /boot
/dev/vdc                   1.2T   87G  1.1T   8% /sysroot/home/centos/external
```
We have a directory named /sysroot. If the envoy config file is the that directory, envoy can not start up.
```
[2024-06-04 22:28:35.581][3382724][critical][main] [source/server/server.cc:131] error …
```
=> use exact match for illegal path check

bazel/boringssl_static.patch, bazel/repository_locations.bzl
Also updated the instructions to stop using a tool that no longer exists.
Note that it is no longer neccessary to use the `master-with-bazel` branch, as the main branch has bazel support.
Docs Changes:
Release Notes:
=> Upgrade boringssl version

contrib/golang/filters/http/source/BUILD, contrib/golang/filters/http/source/golang_filter.cc, contrib/golang/filters/http/source/golang_filter.h, contrib/golang/filters/network/source/BUILD, contrib/golang/filters/network/source/golang.cc, contrib/golang/filters/network/source/golang.h
fix #34183 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> golang fitler: use Router::StringAccessor instead of GoStringFilterState.

source/common/singleton/manager_impl.cc, source/common/singleton/manager_impl.h, source/server/config_validation/server.cc, source/server/config_validation/server.h, source/server/server.cc, source/server/server.h, test/common/http/http_server_properties_cache_manager_test.cc, test/common/singleton/manager_impl_test.cc, test/common/upstream/test_cluster_manager.h, test/extensions/common/async_files/async_file_handle_thread_pool_test.cc, test/extensions/common/async_files/async_file_manager_factory_test.cc, test/extensions/common/async_files/async_file_manager_thread_pool_test.cc, test/extensions/common/async_files/async_file_manager_thread_pool_with_mocks_test.cc, test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test.cc, test/extensions/filters/network/local_ratelimit/local_ratelimit_test.cc, test/extensions/http/cache/file_system_http_cache/file_system_http_cache_test.cc, test/extensions/key_value/file_based/alternate_protocols_cache_impl_test.cc, test/extensions/transport_sockets/alts/config_test.cc, test/mocks/server/instance.cc, test/mocks/server/server_factory_context.cc, test/mocks/server/transport_socket_factory_context.cc, test/mocks/upstream/cluster_manager_factory.h
Commit Message: singleton manager: use ASSERT_IS_MAIN_OR_TEST_THREAD rather than comparing tid directly
Singleton manager is introduced in the #1410 and `tid comparing` is used to ensure the singleton manager is only used in the thread where it's created (main thread or test thread).
However, in the integration test, the singleton manager is created in the separated thread and we cannot access it in the test thread.
This PR updated the `tid comparing` to the ASSERT_IS_MAIN_OR_TEST_THREAD to resolve the problem. (And I think the ASSERT_IS_MAIN_OR_TEST_THREAD macro should be an unified way to ensure we are in the main thread)
Testing: n/a.
=> singleton manager: use ASSERT_IS_MAIN_OR_TEST_THREAD rather than comparing tid directly

source/extensions/access_loggers/grpc/grpc_access_log_utils.cc, test/config/utility.h, test/extensions/access_loggers/grpc/tcp_grpc_access_log_integration_test.cc
Commit Message: grpc access logger: add downstream transport failure reason
This adds the missing downstream transport failure reason field to the grpc access logger. The field is already available when using the file logger, but is not populated when using the grpc logger.
Testing: yes, added a few integration tests; some small changes made to test fixtures to accommodate
Docs Changes: 
Release Notes:
=> grpc access logger: add downstream transport failure reason

test/common/http/http1/codec_impl_test.cc
Commit Message: [balsa] Add tests for CR handling.
Additional Description: Document differences between http-parser and BalsaParser before making changes.
Risk Level: low (test-only)
=> [balsa] Add tests for CR handling.

source/extensions/filters/http/cache/cache_filter.cc
Commit Message: [cache-filter] addEncodedData is streaming
Additional Description: It's possible that this change is incorrect, but I can't justify how it was, and the justification for this parameter being always true is is "the filter is streaming content, not buffering, and that doesn't change depending on whether there are trailers or not". I think probably the previous way was a misunderstanding that this argument is equivalent to `end_stream`, which I believe it is not. (One effect this argument can have is, if false, it can cause a response to fully abort if the buffer is over the watermark limit, which I believe is an argument in favor of this change.)
Risk Level: Might make a WIP filter misbehave if I'm wrong. Might be the filter already misbehaves if I'm right, so net-neutral. …
=> [cache-filter] addEncodedData is streaming

test/common/grpc/grpc_client_integration.h, test/common/grpc/grpc_client_integration_test.cc, test/common/grpc/grpc_client_integration_test_harness.h
Refactor the test:
- `GrpcClientIntegrationTestBase`: It can be used by different test time variants ; it also can be used by both Envoy-gRPC and google-gRPC OR just either of these two alone
- `EnvoyGrpcFlowControlTest` is an example to use `GrpcClientIntegrationTestBase`:  (1) For envoy-gRPC only with `EnvoyGrpcClientIntegrationParamTest` 
(2) use simulate test system instead of `testRealTime`
Risk: Low No change to existing tests functionality, `EnvoyGrpcFlowControlTest` in this PR serves as use example and it will be completed/used in a different PR
=> grpc: Refactor the gRPC integration test 

source/common/common/fine_grain_logger.h, source/common/common/logger.h, test/common/common/log_macros_test.cc
The `ENVOY_LOG_COMP_LEVEL` will lead to non-active fine-grain loggers are not managed by the fine-grain logger map when log level is lower than default, since `ENVOY_LOG_TO_LOGGER` is the only way to call `FINE_GRAIN_LOG` to initialize a fg-logger.
This PR creates a new `FINE_GRAIN_LOGGER()` and that can be used for getting fine-grain logger. 
Also creates a new `ENVOY_LOG_COMP_LEVEL_FINE_GRAIN_IF()` to consider fine-grain logger when doing comparison. 
Note, not all marcos are migrated.
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/ …
=> fine_grain_logger: make sure fine-grain-logger map registration in macros

source/common/common/fine_grain_logger.cc, test/common/common/log_macros_test.cc, test/server/admin/logs_handler_test.cc
Before:
```
active loggers:
source/server/admin/logs_handler.cc: 3
source/common/common/logger.cc: 3
```
After:
```
active loggers:
source/server/admin/logs_handler.cc: warn
source/common/common/logger.cc: warn
```
admin test:
Testing:
Docs Changes:
Release Notes:
=> admin_fine_logger: replace log level int with nice string

ci/Dockerfile-envoy, ci/docker-entrypoint.sh
Commit Message: Make envoy user part of the tty group instead of chown stderr/stdout
Additional Description: This PR addresses and issue with running Envoy on Openshift, where, with the built-in images, we the the following error:
```
kubectl logs -f envoy-secure-secureingress-7c4cc7f497-czjfn
chown: changing ownership of '/dev/stdout': Permission denied
chown: changing ownership of '/dev/stderr': Permission denied
```
This is was tested on Openshift Rosa:
```
kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8+8974577
```
This was inspired by https://github.com/moby/moby/issues/31243#issuecomment-406879017
Testing: Deployed this branch in the mentioned Openshift Cluster.
Release Notes: …
=> Make envoy user part of the tty group instead of chown stderr/stdout

source/extensions/common/aws/credentials_provider_impl.cc, test/extensions/common/aws/credentials_provider_impl_test.cc
Commit Message: aws: relocate async credential provider stats initialization
Additional Description: Fixes reported crash in dev due to statistics initialization being performed too late in the init cycle. Patch moves this initialization to the start of this init handler and removes extraneous checks for stats initialization.
Patch also makes a minor change to behaviour when credentials cannot be retrieved from the profile as the debug logs are misleading.
Testing: Unit
Docs Changes:
Release Notes:
=> aws: relocate async credential provider stats initialization

source/common/http/http2/BUILD, source/common/http/http2/nghttp2.cc, source/common/http/http2/nghttp2.h, source/exe/BUILD, source/exe/process_wide.cc, test/per_file_coverage.sh
This reverts commit 14cd80ff82a7f54a92e44e0ad0f0ca13b48d4c57.
This change prevents nghttp2 from dumping its verbose logs in integration tests. Excessive logging causes test timeouts in sanitizer builds.
=> Revert "http2: removes environment variable-triggered nghttp2 logging (#34354)"

changelogs/current.yaml, source/common/http/hash_policy.cc, test/integration/multiplexed_integration_test.cc
Commit Message: fix cookie attributes
Additional Description: store cookie attributes in normal vector instead of reference wrapper to retain the actual values. Without this, they are getting garbled.
Testing: Added
Fixes https://github.com/envoyproxy/envoy/issues/34818
=> http: fix cookie attributes

source/extensions/filters/http/ext_proc/matching_utils.cc, test/extensions/filters/http/ext_proc/BUILD, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/matching_utils_test.cc
Commit Message: ext_proc: Improve test coverage in matching_utils
Testing: Matching utils unit tests added, CelValue types covered more extensively in integration tests
Fixes #34496
=> ext_proc: Improve test coverage in matching_utils

envoy/upstream/upstream.h, source/common/upstream/upstream_impl.h, test/common/upstream/upstream_impl_test.cc, test/mocks/upstream/host.h
Add dynamic `LbPolicyData` to `Host`.
- Define base `HostLbPolicyData` interface that LB policy can implement in order to attach policy-specific dynamic data to the `Host`. Once attached the lbPolicyData is owned by the host.
- Add `Host::setLbPolicyData()` and `Host::lbPolicyData` methods to set and get it.
- In particular this will be used to implement `ClientSideWeightedRoundRobin` LB policy that needs to calculate host weight on the client side based on the ORCA load report received from the upstream.
Testing: Unit test in `upstream_impl_test`
Platform Specific Features: Cross-platform
Fixes #34529 
=> upstream: Add dynamic `LbPolicyData` to `Host`.

source/common/formatter/substitution_format_utility.cc, source/common/formatter/substitution_format_utility.h
Commit Message: formatter: removes unused getHostNameOrDefault
Previously getHostNameOrDefault was used to resolve HOSTNAME substitution, but now it's implemented via `const absl::optional<std::string> getHostname()`, and getHostNameOrDefault hasn't been used since then.
As a result, this would increase the test coverage of substitution_format_utility.cc. 
Risk Level: lo
Testing: done
=> formatter: removes unused getHostNameOrDefault

envoy/config/config_provider_manager.h, source/common/router/scoped_rds.h, test/common/config/config_provider_impl_test.cc, test/common/router/scoped_rds_test.cc, test/mocks/config/mocks.h
Commit Message: Removes unused createStaticConfigProvider
Previously, a variant of createStaticConfigProvider taking `Protobuf::Message` 
as a first param was not used, and that was one reason for the low test coverage 
of envoy/config package. This removes it, and potentially allows the package 
to be removed from the coverage exception.
Testing: done
=> Removes unused createStaticConfigProvider

.github/workflows/mobile-compile_time_options.yml, mobile/.bazelrc
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> mobile ci: removing the iOS no-http3 build

source/extensions/http/header_validators/envoy_default/BUILD, source/extensions/quic/connection_debug_visitor/BUILD, source/extensions/quic/connection_id_generator/BUILD, source/extensions/quic/server_preferred_address/BUILD, source/server/admin/BUILD
Commit Message: build: removes unnecessary `//test:__subpackages__` visibility
This removes the unnecessary visibility in some extension targets.
ref #35026 
Testing: n/a
=> build: removes unnecessary //test:__subpackages__ visibility

.github/workflows/mobile-compile_time_options.yml
The error:
```
Invalid workflow file: .github/workflows/mobile-compile_time_options.yml#L82
The workflow is not valid. .github/workflows/mobile-compile_time_options.yml (Line: 82, Col: 7): Job 'request' depends on unknown job 'build'.
```
A follow-up of https://github.com/envoyproxy/envoy/pull/35019
Testing: CI
=> mobile: Fix Mobile/Compile time options CI

source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
There is no response in observability mode by design, so logging on `onFinishProcessorCalls` which is invoked on response won't work. Note, existing error/close case still work as normal
Solution: Leverage the `encodeComplete` function to write the logging/billing info. This is also before the consumers (extensions/filters behind) reading it. 
Test: Existing Integration test frame with `logging_test_filter` as consumer
=> ext_proc: observability mode part 3: logging and billing support

contrib/client_ssl_auth/filters/network/source/client_ssl_auth.cc, contrib/client_ssl_auth/filters/network/test/client_ssl_auth_test.cc
Commit Message: Fix for SSL Client Auth filter closing connection without reason
Fixes #34997
=> Fix for SSL Client Auth filter closing connection without reason

api/envoy/config/cluster/v3/outlier_detection.proto, changelogs/current.yaml, source/common/runtime/runtime_features.cc, source/common/upstream/outlier_detection_impl.cc, source/common/upstream/outlier_detection_impl.h, test/common/upstream/outlier_detection_impl_test.cc
Commit Message: Add a config option to allow ejecting one host regardless of max_ejection_percentage
Testing: added test
Docs Changes: updated proto comment
Release Notes: todo
Fixes #34666
=> outlier_detection: add always_eject_one_host

examples/zstd/docker-compose.yaml
Commit Message: ci: remove zstd docker-compose 'version' as obsolete
Additional Description: from CI logs:
```time="2024-07-01T21:16:14Z" level=warning msg="/home/runner/work/envoy/envoy/examples/zstd/docker-compose.yaml: `version` is obsolete"```
Testing: N/A
=> ci: remove zstd docker-compose 'version' as obsolete

test/extensions/filters/http/lua/wrappers_test.cc
Commit Message: lua: adds test to cover LUA_TNIL metadata conversion
Previously, the conversion of LUA_TNIL type in dynamic 
metadata generation had no unit test coverage.
This modifies SetGetAndIterateDynamicMetadata test to cover the logic.
https://github.com/envoyproxy/envoy/blob/416e7a64d1d3f72bf3309938e22ca5f006fe429f/source/extensions/filters/common/lua/wrappers.cc#L140-L142
Risk Level: lo
Testing: done
=> lua: adds test to cover LUA_TNIL metadata conversion

test/common/common/utility_trie_speed_test.cc
template< class IntType = int > class uniform_int_distribution
[IntType](https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution) | - | The result type generated by the generator. The effect is undefined if this is not one of short, int, long, long long, unsigned short, unsigned int, unsigned long, or unsigned long long.
Testing:
Docs Changes:
Release Notes:
=> utility_trie_speed_test: remove char for uniform_int_distribution undifined behavior

source/extensions/common/aws/utility.cc, test/extensions/common/aws/utility_test.cc
Commit Message: aws: Fix for s3 double encoding 
Bugfix for issue https://github.com/envoyproxy/envoy/issues/35023 . Includes additional unit tests and support for s3-outposts which also has the same workaround in the SDK for double encoding.
Testing: Unit
Docs Changes:
Release Notes:
[Optional Fixes #Issue] 35023
=> aws: Fix for s3 double encoding

api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
The default timeout value is chosen same as [drain timeout](https://github.com/envoyproxy/envoy/blob/3feff04eeb2356cf16f799bc9fb812e5b765315f/api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#L553) `<envoy_v3_api_field_extensions.filters.network.http_connection_manager.v3.HttpConnectionManager.drain_timeout>`
=> ext_proc: observability mode part 4: add deferred closure timeout config

changelogs/current.yaml, source/extensions/router/cluster_specifiers/lua/lua_cluster_specifier.h, test/extensions/router/cluster_specifiers/lua/lua_cluster_specifier_test.cc
Commit Message: lua: fix a bug where the lifetime of userdata will result in crash
The RouteHandleWrapper will be desotryed when the lua doing the gc. And the embedded HeaderMapRef will call the reset() when it's destructed and will refer the invalid lua_State pointer and finally result in a crash.
Testing: unit.
=> lua: fix a bug where the lifetime of userdata will result in crash

mobile/.bazelrc, mobile/examples/kotlin/hello_world/MainActivity.kt, mobile/library/cc/engine_builder.cc, mobile/library/common/engine_common.h, mobile/library/java/org/chromium/net/impl/NativeCronvoyEngineBuilderImpl.java, mobile/library/jni/jni_utility.cc, mobile/library/jni/jni_utility.h, mobile/test/cc/unit/envoy_config_test.cc, mobile/test/common/integration/BUILD, mobile/test/common/integration/test_server.cc, mobile/test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt, mobile/test/kotlin/apps/baseline/MainActivity.kt, mobile/test/kotlin/apps/experimental/MainActivity.kt, mobile/test/kotlin/integration/BUILD, mobile/test/kotlin/integration/CancelGRPCStreamTest.kt, mobile/test/kotlin/integration/KeyValueStoreTest.kt, mobile/test/kotlin/integration/ReceiveErrorTest.kt, mobile/test/kotlin/integration/SendDataTest.kt, mobile/test/kotlin/integration/SendHeadersTest.kt, mobile/test/kotlin/integration/SendTrailersTest.kt, mobile/test/kotlin/integration/SetEventTrackerTest.kt, mobile/test/kotlin/integration/SetLoggerTest.kt
This switches the kotlin and java builds and releases to using proto lite, and only supporting binary protos.
Risk Level: medium for E-M, no-op for Envoy
Docs Changes: 
=> mobile: using lite protos on all linux builds

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
500 is returned because the onMessageTimeout is invoked by mistake, which is because test is missing skip_header_processing_on_response (or ext_proc test server should handle request)
404 should be returned from upstream sever in this case, as downstream client request failed to reach the server due to route mismatch.
=> ext_proc: Fix status code in the test

test/common/http/http1/codec_impl_test.cc
Commit Message: [balsa] Update comment for line folding tests.
Additional Description: Obsolete line folding was enabled for BalsaParser at https://github.com/envoyproxy/envoy/pull/31168 but the comment did not get updated at that time.
Risk Level: low, test-only change
Testing: n/a test-only change
=> [balsa] Update comment for line folding tests.

docs/root/configuration/http/http_filters/aws_request_signing_filter.rst, source/extensions/common/aws/signer_base_impl.cc, source/extensions/common/aws/sigv4a_signer_impl.cc, test/extensions/common/aws/sigv4_signer_impl_test.cc, test/extensions/common/aws/sigv4a_signer_impl_test.cc
Commit Message: aws: avoid duplicate headers
Additional Description: Fixes identified issue with headers being added, rather than replaced
Testing: Unit
Docs Changes: Doc changes made to explain header modifications by this extension
Release Notes:
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/35075
=> aws: avoid duplicate headers

changelogs/current.yaml, source/common/http/http1/balsa_parser.cc, source/common/runtime/runtime_features.cc, test/common/http/http1/codec_impl_test.cc, tools/spelling/spelling_dictionary.txt
Commit Message: [balsa] Add runtime guard for rejecting CR in chunk extension.
Additional Description: #34906 landed without runtime guard protection. This PR retroactively adds a default-true feature flag.
=> [balsa] Add runtime guard for rejecting CR in chunk extension.

api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto, source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/filter_test.cc
Implements the derferred closure timeout, the API was implemented in https://github.com/envoyproxy/envoy/pull/34971
=> ext_proc: observability mode part 4: Implement the deferred closure timeout. 

api/envoy/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto, source/extensions/filters/http/grpc_json_transcoder/BUILD, source/extensions/filters/http/grpc_json_transcoder/http_body_utils.cc, source/extensions/filters/http/grpc_json_transcoder/http_body_utils.h, source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc, source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.h, test/extensions/filters/http/grpc_json_transcoder/BUILD, test/extensions/filters/http/grpc_json_transcoder/http_body_utils_test.cc, test/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter_test.cc
Commit Message: [grpc-transcoder] Add option to pack unknown parameters into HttpBody extension
Additional Description: We've been using this behavior for years, with PR #15338 as a patch. Finally getting around to trying to upstream the behavior to make it available for others, and to make it so I don't have to keep repositioning the patch. Unlike #15338 I'm also adding a configuration option so that no behavior change will occur without a corresponding configuration change.
Risk Level: Very low, guarded by a new config field.
Testing: Added positive unit tests, added conditions to other tests for the negative case.
Docs Changes: Autogen
Fixes #14710
=> [grpc-transcoder] Add option to pack unknown parameters into HttpBody extension

changelogs/current.yaml, docs/root/intro/arch_overview/other_protocols/redis.rst, source/extensions/filters/network/common/redis/supported_commands.h
Add support for all the Bloom 1.0.0 commands, they are all based on the first argument (the key)
Similar to https://github.com/envoyproxy/envoy/pull/35105 but covers all the commands in the group.
Testing: Covered by existing simple command tests
Docs Changes:
Added reference to new commands.
Release Notes:
Added reference to new commands.
=> filter-network-redis: Add support for all Bloom 1.0.0 commands, and documentation

mobile/library/common/extensions/filters/http/network_configuration/BUILD, mobile/library/common/extensions/filters/http/network_configuration/filter.cc, mobile/library/common/network/apple_pac_proxy_resolver.cc
`onProxyResolutionCallback()` already posts the `continueDecoding()` call to the dispatcher,
so once a `shared_ptr` has been obtained from the `weak_ptr`, directly invoke `onProxyResolutionCallback()`.
=> mobile: Don't double post proxy resolution to the dispatcher

source/extensions/access_loggers/fluentd/fluentd_access_log_impl.cc, test/extensions/access_loggers/fluentd/fluentd_access_log_impl_test.cc
Additional Description: If a cluster does not exist at the time of logger creation, Envoy would crash. When running in validation mode, the cluster manager returns ``nullptr`` by design, which causes the process to crash. Fixes #35098
=> fluentd_access_logger: check cluster existance

source/common/quic/platform/quiche_flags_impl.cc
Earlier this year, QUICHE dropped support for protocol flags having different internal and external values.
https://github.com/google/quiche/commit/1ed2fb6c3ddce22a0baba689c16b76c53471013a
Something I noticed while dealing with the QUICHE feature flags changes in #35159, but figured should be a separate PR.
Testing: Existing tests pass
=> Simplify QUICHE protocol flag support

docs/root/configuration/http/http_filters/_include/aws_credentials.rst, docs/root/configuration/http/http_filters/aws_request_signing_filter.rst, source/extensions/common/aws/credentials_provider_impl.cc, source/extensions/common/aws/credentials_provider_impl.h, test/extensions/filters/http/aws_request_signing/aws_request_signing_integration_test.cc
Commit Message: aws: recreate cluster during cds deletion
Additional Description: Adds handler for onClusterRemoval to handle CDS refresh case identified in https://github.com/envoyproxy/envoy/issues/35022
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] 35022
=> aws: recreate cluster during cds deletion

api/envoy/config/trace/v3/datadog.proto, changelogs/current.yaml, source/extensions/tracers/datadog/config.cc, test/extensions/tracers/datadog/config_test.cc
Commit Message: tracer(datadog): improve remote configuration usability
Additional Description: Remote Configuration has been introduced in https://github.com/envoyproxy/envoy/pull/33294.
It was enabled by default with the only way to configure the feature being an environment variable. This commit disables the feature by default and adds a new fields to enable and configure it from Envoy's configuration.
Here's a snippet for enabling remote configuration with a 10s polling interval:
```yaml
...
tracing:
provider:
name: envoy.tracers.datadog
typed_config:
"@type": type.googleapis.com/envoy.config.trace.v3.DatadogConfig
collector_cluster: datadog_agent
service_name: envoy-demo
remote_config:
enabled: true
polling_interval: "10s"
...
```
Changes:
- Add configuration options for remote …
=> tracer(datadog): improve remote configuration usability

source/common/network/connection_impl.cc
Commit Message: report human readable delayed connection error message
Additional Description: turns "delayed_connect_error:_111" into "delayed_connect_error:_ECONNREFUSED" (or similar)
Risk Level: low? I don't really know what I'm doing. I'm just copying the fix for #20313
Testing:
Docs Changes:
Release Notes:
=> report human readable conn error msg

source/common/http/conn_pool_grid.cc, source/common/http/conn_pool_grid.h, test/common/http/common.h, test/common/http/conn_pool_grid_test.cc
Commit Message: make ConnectivityGrid to retain TCP pool failure reason enum and transport failure reason string if there is any H3 pool still connecting. This is unexpected case, though we observed it in production. The retained TCP failure details will be appended to the transport_failure_reason which gets propagated via onPoolFailure() callback and reported in stream intel in E-M to assist debugging.
Risk Level: low, logging only
=> conn_pool: TCP pool failure if H3 pool is still connecting in connectivity grid

examples/wasm-cc/envoy.yaml
Commit Message: Auto-config allows switching on protocols based on ALPN and that is not supported by the cluster's transport socket in the wasm-cc example.
Fixes: `error initializing config '  /etc/envoy.yaml': ALPN configured for cluster web_service_with_wasm_filter which has a non-ALPN transport socket: name: "web_service_with_wasm_filter"`
Testing: Manual testing, I have verified that with this fix both containers from wasm-cc example successfully start and are functional for the purposes of the example.
=> examples: wasm-cc: replace auto_config protocol option

source/extensions/filters/http/rate_limit_quota/client_impl.cc, source/extensions/filters/http/rate_limit_quota/filter.cc, source/extensions/filters/http/rate_limit_quota/filter.h, source/extensions/filters/http/rate_limit_quota/quota_bucket_cache.h, test/extensions/filters/http/rate_limit_quota/integration_test.cc
Add support for expired assignment. Currently supported expired assignment behavior: Fail-open or Fail close.
=> rlqs: Add support for expired assignment 

source/extensions/filters/http/jwt_authn/verifier.cc, test/extensions/filters/http/jwt_authn/provider_verifier_test.cc, test/extensions/filters/http/jwt_authn/test_common.h
Commit Message: jwt_authn: Set metadata irrespective of success/failure of JWT Verification
Previously, metadata was only set for successful JWT verification, restricting "failed_status_in_metadata". This change removes the condition, allowing both "payload_in_metadata" and "failed_status_in_metadata" to be set as needed.
If this condition was added to restrict setting "payload_in_metadata" only on successful verification, it is unnecessary since "payload_in_metadata" is set only by AuthenticatorImpl:handleGoodJwt().
Release Notes:
Fixes #32813
=> jwt_authn: Set metadata irrespective of success/failure of JWT Verification

docs/root/intro/arch_overview/upstream/outlier.rst
Commit Message: Moving the note about active health checking unejecting nodes in the outlier detection docs to more relevant section where Ejection algorithm is described. Currently it sits under gRPC giving it false impression that it is only relevant to gRPC which is wrong.
Testing: none
Docs Changes: outlier_detection
=> docs: move note about health checking to more relevant section in outlier.rst

source/extensions/extensions_metadata.yaml
Commit Message: Updating security posture of http router filter from robust_to_downstream to robust_to_downstream_and_upstream.
Additional Description: It seems Router filter is mislabeled as robust_to_downstream when it should be robust_to_downstream_and_upstream as it doesn't process responses and has been one of the last filters used for L7 load balancing in a typical edge deployment. AFAICT, it also matches guidelines for robustness mentioned here https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md#extension-stability-and-security-posture
Risk Level:Low
Testing: NA
Docs Changes: Y
Release Notes:
[Optional [API …
=> update security label for router filter

mobile/examples/swift/async_await/ContentView.swift
With the `onError` callback it'll be impossible to debug any error related to the test app.
Testing: CI
=> mobile: Add onError callback in the swift_async_await test app

source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h, test/extensions/filters/udp/udp_proxy/mocks.h, test/extensions/filters/udp/udp_proxy/session_filters/BUILD, test/extensions/filters/udp/udp_proxy/session_filters/drainer_filter.h, test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc, test/integration/BUILD, test/integration/udp_tunneling_integration_test.cc
Commit Message: Fix a crash in UDP proxy which happens because of UDP session idle timeout.
We've observed a crash in envoy that occurs when we get session idle timeout on a session that didn't connect yet to upstream for some reason (for example, this can happen when a filter returns a `StopIteration` in `onNewSession` and the session remains in idle state until the idle timeout).
In this case, "upstream_" will not be initialized and we will get a segment fault because of the following call in `onIdleTimer`:
`upstream_->onDownstreamEvent(Network::ConnectionEvent::LocalClose);`
As a fix for this issue, we're adding the following changes: 
- Calling `onDownstreamEvent` only if `upstream_` was already initialized.
- Handling the case when we're already connected to …
=> UDP Tunneling: Fix crashes in UDP proxy

api/envoy/config/cluster/v3/cluster.proto, api/envoy/config/endpoint/v3/load_report.proto
Commit Message: api: add fields for propagation of ORCA to LRS
Additional Description: Add fields in CDS to control which ORCA fields get propagated to LRS.  Also add fields in LRS for top-level ORCA metrics, to avoid having to encode the field name in LRS for these common cases.
Testing: N/A
CC @efimki @andresguedez @ejona86 @dfawley @vishalpowar
=> api: add fields for propagation of ORCA to LRS

test/common/tls/ssl_socket_test.cc
no_full_scan_certs_on_sni_mismatch runtime only change the default value and it is removed.
Added one more test with the config  `full_scan_certs_on_sni_mismatch: true`
Testing:
Docs Changes:
Release Notes:
=> tls: add one full scan certs test when sni mismatch

source/extensions/filters/http/local_ratelimit/local_ratelimit.cc, test/extensions/filters/http/local_ratelimit/filter_test.cc
Commit Message: local rate limit: fix a bug where the x-ratelimit-* headers is added by default
#35112 introduce a bug where the x-ratelimit-* headers will be added by default. See #35245 for more detail.
This PR fix it and add a unit test to ensue we won't regression.
Testing: unit.
Release Notes: n/a. No stable version contains this bug. So, I didn't add the change log.
=> local rate limit: fix a bug where the x-ratelimit-* headers is added by default

source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h, test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc, test/integration/udp_tunneling_integration_test.cc
Commit Message: Flush UdpTunnelUpstreamConnected access log only after receiving valid response headers from upstream
Docs Changes:
Release Notes:
=> Bugfix: Flush UdpTunnelUpstreamConnected access log only after receiving valid response headers

mobile/library/common/network/apple_proxy_resolver.h, mobile/library/common/network/apple_system_proxy_settings_monitor.h
Commit Message: Initialize booleans in Apple proxy resolvers
Additional Description: This fixes issue where the resolver thinks it's already started and system proxy setting is not read.
=> [mobile]Initialize booleans in Apple proxy resolvers

source/extensions/clusters/static/static_cluster.cc, source/server/admin/config_dump_handler.cc, test/common/upstream/cluster_manager_impl_test.cc, test/server/admin/config_dump_handler_test.cc
Commit Message: Fix unexpected output of endpoint additional_addresses dump
This commit will do two things:
- Fix static clusters not setting addresses_list for hosts  which led to incomplete configdumps of lb endpoints
- Fix a mistake I did in #34755 which led to adding the default_address in the additional_addresses for dynamic clusters.
I erronously considered addresses_list to be the list of additional_addresses instead of a list containing default_address+additional_addresses.
Testing: Updated unit tests
Release Notes: None as this is a continuation/fix of #35100 which is still not shipped in any envoy release
[Optional Fixes #Issue] #35100
[Optional Fixes commit #PR or SHA] #34755
=> Fix unexpected output of endpoint additional_addresses dump

bazel/BUILD, source/exe/BUILD, test/config_test/BUILD
Back port of #34483 to release/v1.29.
To avoid ambiguity when building with `//bazel:http3=False` (on PPC and Windows) this commit adds new config_setting_groups and updates the relevant select() statements.
=> [Backport 1.29] Fixed bazel configuration ambiguity for non HTTP3 builds (#34483)

bazel/BUILD, source/exe/BUILD, test/config_test/BUILD
Back port of #34483 to `release/v1.30`
To avoid ambiguity when building with //bazel:http3=False (on PPC and Windows) this commit adds new config_setting_groups and updates the relevant select() statements.
=> [Backport 1.30] Fixed bazel configuration ambiguity for non HTTP3 builds (#34483)

source/common/http/http_server_properties_cache_impl.cc, test/common/http/http_server_properties_cache_impl_test.cc
fix for crash in server properties cache
Reported the crash to envoy-security@googlegroups.com and got green light to proceed in public. The issue is that key_value_store_ used in cache may be NULL, so it should be checked before each use.
Testing: Converted to parameterized tests to run each test with valid and NULL key_value_store_.
=> server: fixed crash in server properties cache

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/ext_proc: Temporarily disable flaking test

docs/root/intro/arch_overview/other_features/local_rate_limiting.rst
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> doc: tweak ref format in local_rate_limiting.

source/common/http/http_server_properties_cache_impl.cc, test/common/http/http_server_properties_cache_impl_test.cc
backport https://github.com/envoyproxy/envoy/pull/35268 to rel1.29
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> backport to rel1.29: Fix crash in server properties cache.

source/common/http/http_server_properties_cache_impl.cc, test/common/http/http_server_properties_cache_impl_test.cc
backport https://github.com/envoyproxy/envoy/pull/35268 to rel1.28
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> backport to rel1.28: Fix crash in server properties cache.

source/common/http/http_server_properties_cache_impl.cc, test/common/http/http_server_properties_cache_impl_test.cc
backport #35268 to rel1.30
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> backport to rel1.30: Fix crash in server properties cache.

docs/root/intro/arch_overview/security/ssl.rst
Testing:
Docs Changes:
Release Notes:
=> tls: remove no_full_scan_certs_on_sni_mismatch runtime flag in the doc

source/extensions/filters/http/rate_limit_quota/client_impl.cc, test/extensions/filters/http/rate_limit_quota/BUILD, test/extensions/filters/http/rate_limit_quota/integration_test.cc
[abandon action](https://github.com/envoyproxy/envoy/blob/deaecafceb3f2c474485635345a956c78df04a90/api/envoy/service/rate_limit_quota/v3/rlqs.proto#L199) is a simple (and empty)response from RLQS server that ask client to erase the cached bucket.
=> rlqs: Add support for abandon action

source/extensions/network/dns_resolver/cares/dns_impl.cc
This should theoretically restore the defaults changed in https://github.com/c-ares/c-ares/pull/542/files 
Testing:
fixes https://github.com/envoyproxy/envoy/issues/35117
=> cares: restoring prior defaults

source/extensions/filters/http/ext_proc/client_impl.cc, source/extensions/filters/http/ext_proc/client_impl.h, source/extensions/filters/http/ext_proc/ext_proc.cc, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Commit Message: This PR is split from https://github.com/envoyproxy/envoy/pull/35077. The change is specifically needed for ext_proc's observability mode where the stream is deferred closed upon filter destruction (i.e., stream outlives the filter object)
Risk Level: Low, existing runtime guard and observability mode only
Testing: e2e test and load test
=> ext_proc: flow control in observability mode

source/common/router/config_impl.cc, source/common/router/config_impl.h, test/common/router/config_impl_test.cc
=> router: removing a few exceptions

changelogs/current.yaml, source/common/http/filter_manager.cc, source/common/runtime/runtime_features.cc, test/integration/filter_integration_test.cc
Commit Message: runtime: remove runtime flag envoy.reloadable_features.abort_filter_chain_on_stream_reset
Description: 
To close #35364
Testing: n/a.
=> runtime: remove runtime flag envoy.reloadable_features.abort_filter_chain_on_stream_reset

mobile/library/common/engine_common.cc, source/server/config_validation/server.cc, source/server/instance_impl.cc, source/server/instance_impl.h, source/server/overload_manager_impl.cc, source/server/overload_manager_impl.h, source/server/server.cc, source/server/server.h, test/server/overload_manager_impl_test.cc, tools/code_format/config.yaml
=> overload manager: removing exceptions

mobile/test/swift/BUILD, mobile/test/swift/integration/BUILD, mobile/test/swift/integration/proxying/BUILD, mobile/test/swift/stats/BUILD
A temporary fix for https://github.com/envoyproxy/envoy/issues/35316.
Testing: CI
=> mobile: Add no-remote-exec in the Swift tests

mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h, mobile/test/cc/unit/envoy_config_test.cc
This PR adds an option in the `EngineBuilder` to set the UDP socket send buffer size. By default it will use the same value as the one set in Chromium: https://source.chromium.org/chromium/chromium/src/+/main:net/quic/quic_session_pool.cc;l=790-793;drc=7f04a8e033c23dede6beae129cd212e6d4473d72
This PR also updates the code to only apply the default receive buffer size to UDP and not TCP given that the code in https://source.chromium.org/chromium/chromium/src/+/main:net/quic/quic_session_pool.cc;l=766;drc=7f04a8e033c23dede6beae129cd212e6d4473d72 only applies the socket option to UDP only.
=> mobile: Add an option to set the UDP socket send and receive buffer sizes

test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
Risk Level: low: test-only change
Testing:
Docs Changes:
Release Notes:
=> ext_authz: add test for retry

bazel/protoc/BUILD, bazel/protoc/BUILD.protoc, bazel/protoc/protoc.bzl, bazel/repositories.bzl, ci/filter_example_setup.sh
Our current implementation to use precompiled `protoc` patches protobuf with some of the rules from `rules_proto`
Those rules have now been completely removed in latest versions.
There is a bzlmod-only resolution for this here https://registry.bazel.build/modules/toolchains_protoc, but that doesnt help us until we have finally transitioned to bzlmod
this pr works around these issues by reviving the removed files here, which should unblock updates of several of our deps
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md …
=> bazel/protoc: Patch protoc setup to workaround removal

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/streaming_integration_test.cc
Commit Message:  (1) Test SendAndReceiveDynamicMetadata (2) verify the receive body message (3) Added a streaming integration test  which tests large chunk of bodies `PostAndProcessStreamedRequestBodyObservabilityMode`
=> ext_proc: Add more tests for observability mode

changelogs/current.yaml, docs/root/configuration/observability/access_log/usage.rst, source/common/formatter/stream_info_formatter.cc, test/common/formatter/substitution_formatter_test.cc, test/common/router/router_upstream_log_test.cc
1.31 Backport of #35265
Commit Message: Add %RAW_UPSTREAM_CLUSTER% access log formatter Additional Description:
Testing: unit
=> [bp/1.31] Add %UPSTREAM_CLUSTER_RAW% formatter (#35265)

mobile/test/swift/BUILD, mobile/test/swift/integration/BUILD, mobile/test/swift/integration/proxying/BUILD, mobile/test/swift/stats/BUILD
This reverts commit 88374d7111706d058b15ce57a177a0c3b92214aa.
Testing: CI
=> Revert "mobile: Add no-remote-exec in the Swift tests (#35345)"

api/envoy/extensions/resource_monitors/downstream_connections/v3/downstream_connections.proto, source/extensions/extensions_build_config.bzl, source/extensions/extensions_metadata.yaml, source/extensions/resource_monitors/downstream_connections/config.h, source/server/server.cc, test/extensions/resource_monitors/downstream_connections/BUILD, test/extensions/resource_monitors/downstream_connections/config_test.cc, test/integration/cx_limit_integration_test.cc
Commit Message: Fix extension name in docs to match the actual implementation. Currently user docs (`envoy.resource_monitors.downstream_connections`) and implementation (`envoy.resource_monitors.global_downstream_max_connections`) don't match in terms of monitor name. Another approach would be to fix the name in the implementation and leave extension name in the docs as it is, but it would affect users who already figured out the correct full name of extension. Since the extension has already been promoted to stable the second approach may be more correct?
Risk Level:
Testing: Done
Release Notes:
Fixes #34932
=> Fix extension monitor name

source/common/quic/envoy_quic_client_stream.cc, source/common/quic/envoy_quic_server_stream.cc, test/integration/http_integration.cc, test/integration/local_reply_integration_test.cc, test/integration/protocol_integration_test.cc
Commit Message:Export QUIC connection close source to transport error details
=> [quic]Export QUIC connection close source to transport error details

mobile/library/cc/engine_builder.cc, mobile/test/common/integration/client_integration_test.cc
Looks like we got rid of all the tests relying on 127.0.0.1 404s.
Risk Level: mobile-only
Testing: CI passes
=> mobile: removing direct response route

changelogs/current.yaml, envoy/http/filter_factory.h, source/common/http/filter_manager.cc, source/common/router/router.h, source/common/upstream/upstream_impl.h, source/extensions/filters/network/http_connection_manager/config.cc, source/extensions/filters/network/http_connection_manager/config.h, source/server/admin/admin.h, test/common/http/conn_manager_impl_fuzz_test.cc, test/common/http/conn_manager_impl_test.cc, test/common/upstream/upstream_impl_test.cc, test/extensions/filters/network/http_connection_manager/config_filter_chain_test.cc, test/integration/websocket_integration_test.cc, test/mocks/http/mocks.h, test/mocks/upstream/cluster_info.h
Signed-off-by: Dvoriankin Evgenii <evgenijdv@gmail.com>
Commit Message: Websocket: Fixed not ignoring of disabled filter for Websocket
Testing: Integration test
Fixes: #35191
(https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]
=> Websocket: Fixed not ignoring of disabled filter for Websocket

envoy/upstream/upstream.h, source/common/upstream/upstream_impl.cc, source/common/upstream/upstream_impl.h, test/common/upstream/upstream_impl_test.cc, test/mocks/upstream/cluster_info.h
This PR switches the optional\<T\> to OptRef backed by  unique_ptr and also fixes class alignment optimization by moving HappyEyeballsConfig above booleans.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Reduce Cluster memory utilization by avoiding optional HappyEyeballsConfig overhead

mobile/library/cc/engine_builder.cc, test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc
Risk Level: mobile-only
Testing: tested post-handshake retries with buffered bodies
=> envoy mobile: allow buffering small bodies for better H3 retry behavior

source/common/http/http2/metadata_encoder.h, source/common/http/http_server_properties_cache_impl.cc, source/common/quic/envoy_quic_client_stream.cc, source/common/quic/envoy_quic_server_stream.cc, source/common/quic/envoy_quic_utils.cc, source/common/quic/envoy_quic_utils.h, test/common/http/http2/http2_frame.cc
Updates Envoy code that depends on QUICHE HTTP/2 libraries to reference the new location of some header files.
Commit Message: fixes QUICHE HTTP/2 includes
Docs Changes:
Release Notes:
=> http2: fixing QUICHE includes

mobile/examples/java/hello_world/MainActivity.java, mobile/library/cc/stream.cc, mobile/library/cc/stream.h, mobile/library/common/http/client.cc, mobile/library/common/http/client.h, mobile/library/common/internal_engine.cc, mobile/library/common/internal_engine.h, mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyHTTPStream.java, mobile/library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java, mobile/library/java/org/chromium/net/impl/CancelProofEnvoyStream.java, mobile/library/java/org/chromium/net/impl/CronvoyUrlRequest.java, mobile/library/java/org/chromium/net/impl/CronvoyUrlRequestContext.java, mobile/library/jni/jni_impl.cc, mobile/library/kotlin/io/envoyproxy/envoymobile/Stream.kt, mobile/test/common/http/client_test.cc, mobile/test/java/integration/AndroidEngineExplicitFlowTest.java, mobile/test/java/integration/AndroidEngineFlowTest.java, mobile/test/java/integration/AndroidEngineSocketTagTest.java, mobile/test/java/io/envoyproxy/envoymobile/engine/testing/QuicTestServerTest.java, mobile/test/java/org/chromium/net/impl/CancelProofEnvoyStreamTest.java, mobile/test/java/org/chromium/net/testing/AndroidEnvoyExplicitH2FlowTest.java, mobile/test/java/org/chromium/net/testing/Http2TestServerTest.java, mobile/test/kotlin/io/envoyproxy/envoymobile/mocks/MockEnvoyHTTPStream.kt, mobile/test/kotlin/io/envoyproxy/envoymobile/mocks/MockStream.kt
This PR adds an optional parameter to indicate whether a request is an idempotent in the `sendHeaders`. This can be useful to automatically add a retry policy, such as `http3-post-connect-failure` when the `idempotent` flag is set. This makes the Envoy Mobile API similar to Cronet API. The Cronvoy implementation has also been updated to respect the `idempotency` flag.
=> mobile: Add an optional idempotency parameter in sendHeaders

mobile/library/jni/jni_helper.cc, mobile/library/jni/jni_helper.h, mobile/library/jni/jni_impl.cc
When the thread terminates, the `thread_local` storage will be destroyed. However, the `GlobalRef` `jclass` references inside the `thread_local` don't get destroyed automatically causing a leak. This PR fixes it by wrapping the `jclass` with an RAII-style wrapper, `GlobalRefUniquePtr` that has a custom deleter to delete the `GlobalRef` upon `threal_local` destruction.
Testing: CI
=> mobile: Fix JNI GlobalRef leak

bazel/foreign_cc/cares.patch, bazel/repositories.bzl, changelogs/current.yaml
v1.31 backport of [3f6a8c0](https://github.com/envoyproxy/envoy/commit/3f6a8c0f95a014550d1d8df5c849df36f9078b96).
When a GoogleGrpc service is configured with a domain name and using C-Ares as a resolver results in an immediate disconnect.
The fix (https://github.com/c-ares/c-ares/commit/a070d7835d667b2fae5266fe1b790677dae47d25) is being imported as a patch until c-ares can be upgraded.
Testing: N/A
=> [bp/1.31] c-ares gRPC library: fix a bug impacting gRPC's use of c-ares (#35487)

envoy/http/http_server_properties_cache.h, envoy/server/BUILD, envoy/server/factory_context.h, envoy/server/instance.h, source/common/http/http_server_properties_cache_manager_impl.cc, source/common/http/http_server_properties_cache_manager_impl.h, source/common/upstream/cluster_manager_impl.cc, source/common/upstream/cluster_manager_impl.h, source/extensions/filters/http/alternate_protocols_cache/config.cc, source/extensions/filters/http/alternate_protocols_cache/filter.cc, source/extensions/filters/http/alternate_protocols_cache/filter.h, source/server/config_validation/server.cc, source/server/config_validation/server.h, source/server/server.cc, source/server/server.h, test/common/http/http_server_properties_cache_manager_test.cc, test/extensions/filters/http/alternate_protocols_cache/filter_test.cc, test/extensions/key_value/file_based/alternate_protocols_cache_impl_test.cc, test/mocks/http/http_server_properties_cache.cc, test/mocks/http/http_server_properties_cache.h, test/mocks/server/BUILD, test/mocks/server/instance.cc, test/mocks/server/instance.h, test/mocks/server/server_factory_context.cc, test/mocks/server/server_factory_context.h
HttpServerPropertiesCacheManager was created in a weird way using the singleton manager and creating at whichever call site instantiated it first.  Changing to be a proper server-wide manager as most managers are.
=> http: moving HttpServerPropertiesCacheManager from custom singleton

api/envoy/type/http/v3/cookie.proto, changelogs/current.yaml, source/extensions/http/stateful_session/cookie/cookie.cc, source/extensions/http/stateful_session/cookie/cookie.h, test/extensions/http/stateful_session/cookie/cookie_test.cc
backporting #32093
related PR: https://github.com/envoyproxy/envoy/pull/35480
=> backports/1.29: backporting PR#32093 cookie session: support 0 ttl

source/common/singleton/threadsafe_singleton.h, test/common/listener_manager/listener_manager_impl_test.cc, test/common/network/listen_socket_impl_test.cc, test/integration/socket_interface_swap.cc, test/integration/socket_interface_swap.h
Fixes #35467
Additional Description: The failure is not during an important part of the test, but we are receiving some packet while there is no socket interface. To workaround this, do an atomic swap of the interface pointer so there is never a time when we don't have a socket interface.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> quic: fix test flake due to no socket interface

source/common/http/conn_manager_impl.cc
Commit Message: clean up doEndStream
Additional Description: There are some variables that are only used if check_for_deferred_close is true. Move them to be inside the `if (check_for_deferred_close)` block.
=> clean up doEndStream

api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
Testing: n/a
Fixes:
Description:
This is to address the 1st step, i.e, the API change needed for https://github.com/envoyproxy/envoy/issues/35488.
=> Adding HTTP service support for Envoy external processing

envoy/http/filter.h, source/extensions/filters/http/common/pass_through_filter.h
Change Stream(Decode|Encode)Filter to inherit from StreamFilterBase virtually.
Move the default implementation of PassThrough(Decoder|Encode)Filter::onDestroy into StreamFilterBase.
Commit Message: Ensure every instance of StreamFilter and PassThroughFilter to contain only one copy of Stream(Decode|Encode)Filter and StreamFilterBase.
Testing:
Docs Changes:
Release Notes:
=> Ensure every instance of StreamFilter and PassThroughFilter to contain only one copy of StreamFilterBase.

source/common/http/path_utility.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> optimeize unescape slash path

test/integration/quic_http_integration_test.cc
Commit Message: Switch to using `wait_for_log_contains` to fix race condition between stats increment and log flushing when expecting a LOG line caused by QUIC connection closing.
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes #34492
=> quic: fix flaky ConnectionDebugVisitor test

bazel/dependency_imports.bzl
Commit Message: build: Updates Go to 1.22.5
Go 1.20 has already reached EOF a few months ago.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> build: Updates Go to 1.22.5

mobile/library/common/internal_engine.cc
Since we are probing the Google DNS server, we should specify the DNS port, which is 53.
Testing: n/a
=> mobile: Specify the port number for the IPv6 probing code

api/envoy/extensions/filters/http/jwt_authn/v3/config.proto, configs/jwt_authn.yaml, tools/spelling/check_spelling_pedantic.py
Commit Message: jwt: fix claim to header example doc
Additional Description: The example is not [correct](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#extensions-filters-http-jwt-authn-v3-jwtclaimtoheader), got bitten by copy/paste.
=> jwt: fix claim to header example doc

source/common/formatter/http_specific_formatter.cc, source/common/formatter/stream_info_formatter.cc, test/integration/BUILD
formatter code was removed from the E-M build but still included in E-M tests so still had to use the OrPanic macros.
Fixed by removing it from the E-M tests as well.
Testing: CI
=> envoy: cleaning up formatter use for Envoy Mobile

envoy/router/router.h, source/common/router/upstream_request.cc, source/common/tcp_proxy/upstream.h, source/extensions/upstreams/http/http/upstream_request.h, source/extensions/upstreams/http/tcp/upstream_request.h, source/extensions/upstreams/http/udp/upstream_request.h, test/extensions/upstreams/http/udp/upstream_request_test.cc
Commit message:
This API was introduced by #32991 and it conflates support for half-close with TCP proxying mode in H/1 codec. This interferes with #34461 which enables support for server half-close in H/2 proxying.
This PR refactors API to separate enabling of the half-close behavior from TCP proxy behavior. Prior to #34461 half-close semativs were only enabled for TCP proxy upstreams, but #34461 introduces other cases as well. This necessitates setting half-close and TCP proxy modes separately. TCP proxy mode is now enabled in the class dedicated to the TCP proxy upstreams.
Testing: Unit Tests (with runtime flag enabled)
=> Refactor Upstream API for setting TCP tunneling mode

api/envoy/extensions/filters/http/oauth2/v3/oauth.proto, docs/root/configuration/http/http_filters/oauth2_filter.rst
Commit Message:  Minor comment and typo fixes for oauth2 http filter
Testing: None
Docs Changes:  No changes to code, just typo fixes.
=> docs: typos and minor clarifications to oauth2 http filter

source/extensions/filters/http/ext_authz/config.cc, source/extensions/filters/http/ext_authz/config.h, test/extensions/filters/http/ext_authz/config_test.cc
Commit Message: Prior art: [ext_proc](https://github.com/envoyproxy/envoy/blob/f58a812ed24bf7d552ece3642bdf9336ee1a7e20/source/extensions/filters/http/ext_proc/config.cc#L45). And we have use this approach in production 
Risk Level: low, no changes to existing code
=> ext_authz: create filter from server context

changelogs/current.yaml, docs/root/operations/cli.rst, source/server/options_impl.cc, test/server/options_impl_test.cc
Commit Message: Make incompatible command-line args an error
Additional Description: Per #35073, `--enable-fine-grain-logging` and `--component-log-level` don't make sense at the same time, one of them will be overridden by the other in a way that can be surprising for the user. This PR makes it an error to apply both, so the user is not surprised by not getting the logs they expected at runtime.
Risk Level: Small. May make existing command-lines with ineffective options fail.
Testing: Added coverage.
Docs Changes: Updated command-line options docs.
Release Notes: Yes, under minor behavior changes.
=> Make incompatible command-line args an error

changelogs/current.yaml, source/common/quic/envoy_quic_dispatcher.cc, source/common/quic/quic_filter_manager_connection_impl.cc, source/common/quic/quic_filter_manager_connection_impl.h, source/common/runtime/runtime_features.cc, test/integration/overload_integration_test.cc
Commit Message: deprecate `envoy.reloadable_features.quic_fix_filter_manager_uaf` and update change log
Fixes #35373
=> quic: deprecate `envoy.reloadable_features.quic_fix_filter_manager_uaf`

contrib/vcl/source/BUILD
There are multiple files named config.h and in some build environments it causes the build postscript to fail
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> vpp/build: Minor fix for cmake build

mobile/library/cc/engine_builder.cc, mobile/test/common/integration/test_server.cc, mobile/test/java/org/chromium/net/CronetHttp3Test.java
This adds testing of doing retries post HTTP/3 handshake, and resetting brokenness on networ kchange.
Risk Level: n/a (adds a stat to tracking)
Testing: yes
=> mobile: improved HTTP/3 cronet testing

.azure-pipelines/ci.yml, .azure-pipelines/stage/checks.yml
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci: Fix diskspace issue when caching checks

CODEOWNERS, source/extensions/dynamic_modules/BUILD, source/extensions/dynamic_modules/dynamic_modules.cc, source/extensions/dynamic_modules/dynamic_modules.h, test/extensions/dynamic_modules/BUILD, test/extensions/dynamic_modules/dynamic_modules_test.cc, test/extensions/dynamic_modules/test_data/BUILD, test/extensions/dynamic_modules/test_data/no_op.c, test/extensions/dynamic_modules/test_data/test_data.bzl, tools/spelling/spelling_dictionary.txt
Commit Message: dynamic_modules: adds initial object loading logic
This is the very first commit of the dynamic loading feature discussed among community
members. This is the effort to upstream the playground repository 
https://github.com/mathetake/envoy-dynamic-modules as an Envoy core extension.
Series of commits will follow this little by little.
#2053, #24230, #32502
Risk Level: N/A (not compiled into the final build yet)
Testing: unit
Release Notes: N/A 
[Optional Fixes #Issue] 
=> dynamic_modules: adds initial object loading logic

source/extensions/network/dns_resolver/cares/dns_impl.cc, test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
Similar to the `getaddrinfo` implementation, this PR adds the c-ares human readable status in the DNS response details.
=> c-ares: Add c-ares status in the DNS response details

source/extensions/tracers/opentelemetry/http_trace_exporter.cc, test/extensions/tracers/opentelemetry/http_trace_exporter_test.cc
Commit Message: opentelemetry: add the option to discard buffer response body for http async exporter
Additional Description: only the response code is used for logging purpose.
Docs Changes:
Release Notes:
=> opentelemetry: add the option to discard buffer response body for http async exporter

source/extensions/filters/http/rate_limit_quota/filter.cc, test/extensions/filters/http/rate_limit_quota/integration_test.cc
Commit Message: Add dynamic metadata to the rate_limit_quota filter to export the selected bucket for a given request for logging
Additional Description: Functionality tested using an access log filter in integration testing
Testing: integration testing
Docs Changes:
Release Notes:
=> BucketId Dynamic Metadata for RateLimitQuota filter

source/common/orca/BUILD, source/common/orca/orca_parser.cc, source/common/orca/orca_parser.h, test/common/orca/BUILD, test/common/orca/orca_parser_test.cc
Commit Message: Add utility methods to parse ORCA response headers from backends.
Additional Description: Add utility methods to parse ORCA response headers from backends. `parseOrcaLoadReportHeaders` will be called from the `RouterFilter`.
[Open Request Cost Aggregation (ORCA) Design Proposal](https://github.com/envoyproxy/envoy/issues/6614)
[Using ORCA load reports in Envoy](https://docs.google.com/document/d/1gb_2pcNnEzTgo1EJ6w1Ol7O-EH-O_Ysu5o215N9MTAg/edit#heading=h.bi4e79pb39fe)
Testing: See included unit tests.
Platform Specific Features: JSON formatted header not supported on Envoy Mobile
CC @efimki @AndresGuedez
=> Added utility methods to parse ORCA response headers from backends.

source/extensions/common/aws/metadata_fetcher.cc, test/extensions/common/aws/metadata_fetcher_test.cc, test/extensions/filters/http/aws_request_signing/aws_request_signing_integration_test.cc
Commit Message: aws: fix test flake when no IMDS can be found
Additional Description: Lack of IMDS (169.254.169.254 address) can cause a race condition and crash during testing due to the shutdown of cluster manager. This scenario should not occur normally, as cluster manager will still exist and the lack of IMDS is handled gracefully.
Testing: N/A
Docs Changes:
Release Notes:
=> aws: fix test flake when no IMDS can be found

test/extensions/filters/http/ext_proc/tracer_test_filter.cc
Commit Message: MSAN: fix issue in tracer test filter
Additional Description:  also fix other clang complains "clang: 'setOperation' overrides a member function but is not marked 'override'"
Fixes https://github.com/envoyproxy/envoy/issues/35630
=> MSAN: fix issue in tracer test filter

test/common/http/conn_manager_impl_test_2.cc
Commit Message: test: update a broken test due to PRs race
PR #35568 used an old `setup()` method call which was modified by PR #35209 that was merged just before it, causing a build failure.
This PR update the test and fixes the build failure.
Testing: N/A
=> test: update a broken test due to PRs race

source/common/router/config_impl.cc, source/common/router/config_impl.h, test/common/router/config_impl_test.cc
fix up crash while updating weighted clusters, when the total weight is changing through runtime keys.
```
[assert] [source/common/router/config_impl.cc:1366] panic: unexpected
[backtrace] [./source/server/backtrace.h:127] Caught Aborted, suspect faulting address 0xfffe00000001
[backtrace] [./source/server/backtrace.h:111] Backtrace (use tools/stack_decode.py to get line numbers):
[backtrace] [./source/server/backtrace.h:112] Envoy version: 16a0cedaba5335a8003c5077a07a49fafd3eea97/1.30.1/Clean/RELEASE/BoringSSL
[backtrace] [./source/server/backtrace.h:114] Address mapping: 560c90beb000-560c93592000 /usr/local/bin/envoy
[backtrace] [./source/server/backtrace.h:121] #0: [0x7f7cc0a1f520]
ActiveStream 0x55d99505500, stream_id_: …
```
=> router: fix dynamic weight crash

source/extensions/filters/http/file_system_buffer/filter.cc, test/extensions/filters/http/file_system_buffer/filter_test.cc
Commit Message: Fix file_system_buffer's adherence to continueEncoding API
Additional Description: According to the API, `continueEncoding` and `continueDecoding` should not be called after headers replied with anything other than `StopIteration`. This change makes it so if the stream is going to buffer, headers always return `StopIteration`.
Risk Level: Some from leaving it as-is, some from changing it.
Testing: Modified some tests. Integration tests still pass as before.
=> Fix file_system_buffer's adherence to continueEncoding API

envoy/http/filter_factory.h, source/common/filter/config_discovery_impl.h, source/common/http/filter_chain_helper.cc, source/common/http/filter_chain_helper.h, source/extensions/filters/http/composite/action.h, source/extensions/filters/network/http_connection_manager/config.h, test/common/filter/config_discovery_impl_test.cc, test/common/http/filter_chain_helper_test.cc, test/common/http/filter_manager_test.cc
Commit Message: http: remove unnecessary filter canonical name
This the `filter_name` field is unnecessary after #35331.
Testing: n/a.
Docs Changes:  n/a.
=> http: remove unnecessary filter canonical name

mobile/library/jni/android_jni_utility.cc, mobile/library/jni/android_network_utility.cc, mobile/library/jni/jni_helper.cc, mobile/library/jni/jni_helper.h, mobile/library/jni/jni_impl.cc, mobile/library/jni/jni_utility.cc, mobile/library/jni/jni_utility.h, mobile/test/java/io/envoyproxy/envoymobile/jni/JniHelperTest.java, mobile/test/jni/jni_helper_test.cc, mobile/test/jni/jni_http_proxy_test_server_factory.cc, mobile/test/jni/jni_http_test_server_factory.cc, mobile/test/jni/jni_utility_test.cc
This PR rewrites the JNI cache implementation to fix the GlobalRef leak. Prior to this PR, some code would call `getObjectClass` in order to get a `jclass` instance. If the `jclass` was not already in the cache, the code would create a new `GlobalRef` and add it into the cache. Given that there's no guarantee that we will get the same `jclass` instance, the previous code ended up creating a lot of `new GlobalRef` instances due to the cache misses causing a leak. The new implementation updates the code to load the `jclass` from the cache directly via `findClassFromCache` instead of using `getObjectClass`. This guarantees that we will use the same `jclass` instance. The new implementation also changes the cache initialization to be eager instead of lazy, thereby eliminating the need for …
=> mobile: Rewrite JNI cache implementation

envoy/http/filter_factory.h, source/extensions/filters/network/http_connection_manager/config.cc, source/extensions/filters/network/http_connection_manager/config.h, test/common/upstream/upstream_impl_test.cc, test/extensions/filters/network/http_connection_manager/config_filter_chain_test.cc, test/mocks/http/mocks.h
Commit Message: Made naming of some FilterChainOptions instances more consistent
Additional Description: This PR brings cosmetic changes discussed in https://github.com/envoyproxy/envoy/pull/35292#discussion_r1693184337
Testing: Not required
=> Made naming of some FilterChainOptions instances more consistent

envoy/grpc/async_client.h, envoy/http/async_client.h, envoy/stream_info/stream_info.h, source/common/grpc/async_client_impl.h, source/common/grpc/google_async_client_impl.h, source/common/grpc/typed_async_client.h, source/common/http/async_client_impl.cc, source/common/http/async_client_impl.h, source/common/stream_info/stream_info_impl.h, source/extensions/filters/http/ext_proc/client.h, source/extensions/filters/http/ext_proc/client_impl.h, test/common/http/async_client_impl_test.cc, test/extensions/filters/http/ext_proc/mock_server.h, test/extensions/filters/http/ext_proc/unit_test_fuzz/mocks.h, test/mocks/grpc/mocks.h, test/mocks/http/mocks.h, test/mocks/stream_info/mocks.h
Some upstream HTTP filters running in the ext_proc sidestream may require access to metadata associated with the main stream established for the client. This change exposes the main ("parent") stream_info from the async client's stream info. We need to clear this (to avoid a dangling reference) in the case of deferred stream closure, where the main stream closes before the async client stream.
=> ext_proc: expose main stream info from the async client steam info

contrib/golang/common/dso/dso.cc, contrib/golang/common/dso/dso.h, contrib/golang/common/dso/libgolang.h, contrib/golang/common/dso/test/mocks.h, contrib/golang/common/dso/test/test_data/simple.go, contrib/golang/common/go/api/filter.go, contrib/golang/filters/http/source/go/pkg/http/shim.go, contrib/golang/filters/http/source/golang_filter.cc, contrib/golang/filters/http/source/golang_filter.h, contrib/golang/filters/http/test/golang_filter_fuzz_test.cc, contrib/golang/filters/http/test/golang_integration_test.cc, contrib/golang/filters/http/test/test_data/access_log/filter.go
As discussed from https://github.com/envoyproxy/envoy/pull/35595#issuecomment-2278413889, the `AccessLogHandler::log` is not designed for mutating the StreamInfo. It's recommended to use `OnStreamComplete` to do the final metadata management.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> golang: add OnStreamComplete callback to mutate final metadata

test/config/BUILD, test/config/utility.cc, test/config/utility.h
Additional Description: Adding ``addConfigModifier`` testing utility for UdpProxy configurations. This will be used in a separate PR, but wanted to separate this to another so it's easier to review
Testing: none
=> test_utils: add config modifier for UDP proxy

source/extensions/filters/http/rate_limit_quota/client_impl.cc, source/extensions/filters/http/rate_limit_quota/filter.cc, source/extensions/filters/http/rate_limit_quota/filter.h, source/extensions/filters/http/rate_limit_quota/quota_bucket_cache.h, test/extensions/filters/http/rate_limit_quota/integration_test.cc
Commit Message: Refactor the RLQS filter's traffic processing & fix the broken action-assignment expiration check.
Current behavior: 
- Every request that hits the RLQS filter results in the cache thinking that its entry has expired due to the initial / default action of a newly created BucketCache index not having a TTL.  
- If the TTL was fixed, it would still start failing all expiration checks shortly after assignments were received, even if those assignments were sent routinely (not going stale). This is because the expiration time was calculated off of a private field set on BucketCache index creation, and never updated when receiving assignments.  
- Note: Integration testing was previously passing as it was incorrectly expecting multiple RLQS usage reports. …
=> RLQS: Refactor traffic processing in the RLQS filter & fix a broken expiration check

changelogs/current.yaml, docs/root/configuration/http/http_filters/_include/aws_credentials.rst, source/common/runtime/runtime_features.cc, test/extensions/common/aws/credentials_provider_impl_test.cc, test/extensions/filters/http/aws_request_signing/aws_request_signing_integration_test.cc
Commit Message: flip async provider runtime guard to default true
Additional Description: per https://github.com/envoyproxy/envoy/pull/30626#issuecomment-2286396182
Testing: Unit
Docs Changes: Changelog
Release Notes:
[Optional Runtime guard:] envoy_reloadable_features_use_http_client_to_fetch_aws_credentials
=> aws: flip async provider runtime guard to default true

source/extensions/filters/http/cache/cache_filter.cc, source/extensions/filters/http/cache/cache_filter.h, source/extensions/filters/http/cache/http_cache.cc, source/extensions/filters/http/cache/http_cache.h, source/extensions/filters/http/cache/range_utils.h, source/extensions/http/cache/file_system_http_cache/lookup_context.cc, source/extensions/http/cache/simple_http_cache/simple_http_cache.cc, test/extensions/filters/http/cache/cache_filter_test.cc, test/extensions/filters/http/cache/http_cache_implementation_test_common.cc, test/extensions/filters/http/cache/http_cache_implementation_test_common.h, test/extensions/filters/http/cache/http_cache_test.cc, test/extensions/http/cache/file_system_http_cache/file_system_http_cache_test.cc
Commit Message: [cache_filter] Determine end_stream later
Additional Description: Currently the cache filter is incompatible with streaming a result at the same time as populating it, because the lookup requires foreknowledge of whether the entry will have trailers or not, which isn't known until the end of the request (a `Trailers` header is a hint but not a guarantee). This change makes it so the end_stream value from the cache acts more like the way it does for every other stream, so no foreknowledge is required. Plus similar changes for content-length being potentially unknown under the same circumstances.
Risk Level: Some risk to changing behavior of a filter still tagged WIP.
Testing: Existing tests provide coverage, and are updated to verify the new value. Additional tests for …
=> [cache_filter] Determine end_stream later

mobile/library/common/http/client.cc, mobile/library/common/http/client.h
`Envoy::Http::Client` no longer uses C wrapper types, so the `toBridge` name no longer makes sense.
Risk Level: low (rename only)
Testing: CI
=> mobile: Remove toBridge from Envoy::Http::Client

api/envoy/extensions/filters/http/grpc_field_extraction/v3/config.proto
ProtobufWkt::Value is introduced by #35162
Testing:
Docs Changes:
Release Notes:
=> grpc_field_extraction: fix empty ListValue indication

docs/root/_static/searchtools.js
Additional Description: By using `innerText`, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML.
=> Update searchtools.js DOM text reinterpreted as HTML

test/common/tls/utility_test.cc
Introduced from https://github.com/envoyproxy/envoy/pull/35513
Testing:
Docs Changes:
Release Notes:
=> tls: fix openssl 509 null chain malloc leak

mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPRequestUsingProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestBadHostnameTest.kt, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestUsingAsyncProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestUsingProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyPollPerformHTTPRequestUsingProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyPollPerformHTTPRequestWithoutUsingPACProxyTest.kt
This PR updates the Android proxy tests to not use mocks, which have been causing an issue for me when running the tests locally due to the bytecode mismatch. Using a real object with `shadowOf` is also the recommended approach. This PR also updates the tests to not use a deprecated `sendStickyBroadcast` method.
=> mobile: Update Android proxy tests to not use mocks

test/extensions/geoip_providers/maxmind/geoip_provider_test.cc
On some runs mmdb_reload custom thread is not starting until tests ends which results in segfaults in the test. Addding cond var to await in the test for when mmdb reload thread has populated the callbacks.
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes #35829
=> Fix flaky geoip test

mobile/bazel/envoy_mobile_android_test.bzl
This can be useful for passing properties, such as `tags`, etc, for example tests that need to use external connection, IPv4/IPv6, etc.
Testing: CI
=> mobile: Add passing custom properties in envoy_mobile_android_test build rule

mobile/test/kotlin/integration/BUILD, mobile/test/kotlin/integration/FilterThrowingExceptionTest.kt
This PR updates the test by using a local test server instead of making an external network request, which can make the test flaky.
=> mobile: Make FilterThrowingExceptionTest hermetic

source/common/orca/orca_parser.cc, test/common/orca/orca_parser_test.cc
Commit Message: Add checks during ORCA header parsing to catch error cases gracefully handled by util method.
Additional Description: Add checks during ORCA header parsing to catch error cases gracefully handled by util method. ORCA parsing introduced in https://github.com/envoyproxy/envoy/pull/35422
https://github.com/envoyproxy/envoy/issues/6614
[Using ORCA load reports in Envoy](https://docs.google.com/document/d/1gb_2pcNnEzTgo1EJ6w1Ol7O-EH-O_Ysu5o215N9MTAg/edit#heading=h.bi4e79pb39fe)
Testing: See included unit tests.
CC @efimki @adisuissa @wbpcode
=> Add checks during ORCA header parsing to catch error cases gracefully handled by util method.

source/common/quic/envoy_quic_stream.cc, source/common/quic/envoy_quic_stream.h
Commit Message: quic: migrates one more reference to quiche::HttpHeaderBlock
Docs Changes:
Release Notes:
=> quic: migrates one more reference to quiche::HttpHeaderBlock

source/extensions/filters/http/ext_proc/processor_state.cc, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
If ext_proc filter is configured to send header, body but not send trailer, if the downstream request has trailer after body, then there is a problem when handling body response.
It supposes to return continueDecoding() to let the filter manager to send the trailer and finish the request sending. However, the current logic is missing that. This ends up timeout in this situation, and local reply is sent to downstream client.
Testing: inline
=> ext_proc: fix an issue with trailer

bazel/envoy_internal.bzl, source/common/network/upstream_server_name.h
Commit Message: Filter state: Add missing api to get filterstate format working
Consider the case where filter state is being set using the `set_filter_state` filter:
```
- name: "envoy.filters.http.set_filter_state"
typed_config:
"@type": "type.googleapis.com/envoy.extensions.filters.http.set_filter_state.v3.Config"
on_request_headers:
- object_key: "envoy.network.upstream_server_name"
format_string:
text_format_source:
inline_string: "%REQ(:AUTHORITY)%"
shared_with_upstream: "TRANSITIVE"
```
Now if one try to use the value from the filter state, for example in the tunneling config hostname:
```
- name: encap
internal_listener: {}
filter_chains:
- filters:
- name: tcp
typed_config:
"@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy …
```
=> Filter state: Add missing api to get filterstate format working

source/extensions/filters/http/oauth2/filter.cc, source/extensions/filters/http/oauth2/filter.h, test/extensions/filters/http/oauth2/filter_test.cc, test/extensions/filters/http/oauth2/oauth_integration_test.cc
* If specified, use the token domain to calculate the encoded HMAC to allow HMAC validation across multiple subdomains
* If specified, add the token domain to the Cookie delete headers
Adding missing parts while implementing https://github.com/envoyproxy/envoy/issues/35490 in https://github.com/envoyproxy/envoy/pull/35491
=> OAuth2: fix token session subdomain

source/extensions/filters/network/redis_proxy/proxy_filter.h
Commit Message: remove unseless import, which broken macos build, see https://github.com/envoyproxy/envoy/pull/35933
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> remove useless import

contrib/golang/filters/http/source/golang_filter.cc
Otherwise, Golang may panic when it found this invalid pointer.
It's not easy to add a test case for it, since Golang only panic during GC.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> golang: avoid setting invalid pointer in Golang side when header value is empty

ci/README.md, ci/do_ci.sh, ci/run_envoy_docker.sh
Commit Message: ci/tools: use gen comp db python script directly to provide more flexibility
```
$ ci/do_ci.sh refresh_compdb --vscode --include_all --exclude_contrib
```
This is much convenient now to specify parameters of .py script. 
Testing: n/a.
=> ci/tools: use gen comp db python script directly to provide more flexibility

bazel/foreign_cc/BUILD
Commit Message: use library target instead of the default all while build liburing
Otherwise, error `use of undeclared identifier "so_incoming_napi_id"` will happen in some old systems.
Also, it makes build faster, since the examples and test targets are unnecessary in the default all target.
Testing:
Docs Changes:
Release Notes:
=> use library target instead of the default all while build liburing

docs/root/start/sandboxes/setup.rst
see also #32737 and https://github.com/envoyproxy/envoy/issues/32737#issuecomment-2326210957, 
Commit Message: update git repo url in docs to refer to the new examples repo
Additional Description: might fix docs
Testing: none
Docs Changes: changes docs/root/start/sandboxes/setup.rst to refer to the right github repo (examples)
=> change git repo link for where examples are 

source/extensions/filters/http/grpc_json_transcoder/http_body_utils.cc, source/extensions/filters/http/grpc_json_transcoder/http_body_utils.h, tools/code_format/config.yaml
Commit Message: Use `ProtobufWkt::Field` instead of `Protobuf::Field` in grpc_json_transcoder to fix build issues.
Testing: `bazelisk test //test/extensions/filters/http/grpc_json_transcoder/...`
Docs Changes:
Release Notes:
=> Update function parameter in grpc_json_transcoder

mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java, mobile/library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java, mobile/library/jni/jni_impl.cc, mobile/test/kotlin/apps/experimental/MainActivity.kt
This PR fixes an issue with c-ares where the DNS servers are empty due to a missing initialization by calling [ares_library_init_android](https://c-ares.org/docs/ares_library_init_android.html).
Testing: test app
Platform Specific Features: mobile (Android)
=> mobile: Fix c-ares initialization on Android

.bazelrc, bazel/setup_clang.sh
setting `PATH` breaks caches by making otherwise hermetically equivalent builds build differently in different environments
to make things worse `PATH` can be set in multiple places, so we break our own caches dep on how things are built
=> bazel/ci: Dont break caches with `PATH`

source/extensions/filters/http/rate_limit_quota/client_impl.cc, source/extensions/filters/http/rate_limit_quota/filter.cc, source/extensions/filters/http/rate_limit_quota/filter.h, source/extensions/filters/http/rate_limit_quota/quota_bucket_cache.h, test/extensions/filters/http/rate_limit_quota/integration_test.cc
Commit Message: Refactor the RLQS filter's traffic processing & fix the broken action-assignment expiration check.
Additional Description: Addresses flakiness from [past PR](https://github.com/envoyproxy/envoy/pull/35723) by adding a missing `sendDenyResponse` & improving test consistency in asynchronous steps.
Risk Level: Minor
Testing: Integration and unit testing run 1k times to check flakiness
=> RLQS: Refactor traffic processing in the RLQS filter & fix a broken expiration check v2

mobile/test/kotlin/integration/proxying/BUILD, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPRequestUsingProxyTest.kt
This updates the Android HTTP proxy test hermetic by sending a request to a test proxy server instead of sending a request to `api.lyft.com`.
=> mobile: Make Android HTTP proxy test hermetic

test/integration/tcp_tunneling_integration_test.cc
Commit Message: fix flake in TcpTunnelingIntegrationTest.UpstreamHttpFiltersPauseAndResume
fixes: https://github.com/envoyproxy/envoy/issues/35523
=> fix flake in TcpTunnelingIntegrationTest.UpstreamHttpFiltersPauseAndResume

source/extensions/http/header_validators/envoy_default/header_validator.cc, test/extensions/http/header_validators/envoy_default/base_header_validator_test.cc
Commit Message: uhv: fully validate IPv6 Host address
Additional Description: Validate each part of ipv6 address splitted by `:` is 16 bit. No more than 8 parts. Only one double colon is allowed.
Docs Changes:
Release Notes:
Fixes #23314 #22859
=> uhv: fully validate IPv6 Host address

mobile/test/common/integration/test_server.cc, mobile/test/common/integration/test_server.h, mobile/test/java/io/envoyproxy/envoymobile/engine/testing/HttpProxyTestServerFactory.java, mobile/test/java/io/envoyproxy/envoymobile/engine/testing/HttpTestServerFactory.java
This is needed for tests that use HTTP1 with TLS.
Testing: n/a
=> mobile: Add support for HTTP1 with TLS in the TestServer

changelogs/current.yaml, source/common/upstream/upstream_impl.cc, source/common/upstream/upstream_impl.h, test/extensions/clusters/eds/eds_test.cc
Commit Message: Use previously calculated healthcheck when endpoints move priority levels repeatedly. This is done by changing how mutable_cross_priority_host_map_ tracks hosts. mutable_cross_priority_host_map_ is used to track if a host already exists in the previous configuration, and its healthcheck should not be recalculated. This worked only some of the time because it would remove and then add all hosts that have changed in a priority, to a map of string (ip addr:port) to Host instance. However this did not account for when an endpoint had two Host representatives in different priorities, as is in the case when an endpoint changes priorities and there is an edge case where a host can be removed from mutable_cross_priority_host_map_ before the "should we skip activate healthchecks" …
=> Fix healthchecks that do not persist when priority is changed

mobile/bazel/android_artifacts.bzl, mobile/bazel/test_manifest.xml, mobile/examples/java/hello_world/AndroidManifest.xml, mobile/examples/kotlin/hello_world/AndroidManifest.xml, mobile/examples/kotlin/shared/AndroidManifest.xml, mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidEngineManifest.xml, mobile/library/java/io/envoyproxy/envoymobile/utilities/UtilitiesManifest.xml, mobile/library/java/org/chromium/net/ChromiumNetManifest.xml, mobile/library/java/org/chromium/net/impl/CronvoyManifest.xml, mobile/library/java/org/chromium/net/urlconnection/URLConnectionManifest.xml, mobile/library/kotlin/io/envoyproxy/envoymobile/EnvoyManifest.xml, mobile/test/kotlin/apps/baseline/AndroidManifest.xml, mobile/test/kotlin/apps/experimental/AndroidManifest.xml
This PR bumps the minimum Android SDK version to 26.
Testing: CI
=> mobile: Bump min Android SDK version to 26

mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
Unnecessary auto-boxing from primitive to non-primitive types is wasteful.
Testing: CI
=> mobile: Remove unnecessary auto-boxing

mobile/library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java, mobile/library/jni/jni_impl.cc
This PR allows us to have a runtime guard check in the Android code.
Testing: n/a
=> mobile: Create a JNI binding for Runtime::runtimeFeatureEnabled

ci/do_ci.sh, tools/gen_compilation_database.py
Commit Message: ci/tools: minor fix to the compile db generation
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> ci/tools: minor fix to the compile db generation

docs/root/configuration/observability/access_log/usage.rst
Additional Description: The access logging keys documentation do not align with the functionality.
Testing: none
Docs Changes: access logs docs
=> udp_proxy: fix documentation for access logs

bazel/repositories.bzl
Commit Message: Skip all Lua extensions when building Envoy for the PPC architecture.
Testing: N/A
=> deps: Skip all Lua extensions for PPC

source/extensions/filters/http/ext_authz/config.cc
Commit Message: remove unnecessary shared pointer copies from ext authz filter factory
Additional Description: -
Testing: -
Docs Changes: -
Release Notes: -
Platform Specific Features: -
=> remove unnecessary shared pointer copies

tools/cat/BUILD, tools/jq/BUILD
these utils allow you to dump the contents of a build target, either directly (with `cat`) or as JSON (with `jq`)
=> bazel: Add output utils

.bazelrc
our existing RBE uses the GCR image rather than the dockerhub one
this may/not be related to dockerhub rate limiting that seems to have started recently
=> ci/rbe: Use GCR image for Engflow RBE

contrib/golang/filters/http/source/golang_filter.cc
In my local benchmark(requires some hack for benchmark), it makes header map init faster 10%+.
from 2656ns to 2269ns for per header map init.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> golang: optimize copyHeaderMapToGo: reduce memory copy.

mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidNetworkMonitor.java
This PR suppresses the linter for the constant check as well as removing `NetworkCapabilities.TRANSPORT_LOWPAN` since it's only supported in version SDK 27.
Testing: CI
=> mobile: Fix Android linter issues

.bazelrc, .github/workflows/codeql-daily.yml, .github/workflows/codeql-push.yml, bazel/setup_clang.sh, ci/build_setup.sh, ci/do_ci.sh, ci/filter_example_setup.sh
This fixes the recent issues with codeql caused by removing some of the setup in setup_clang.sh
this is a partial revert of that, essentially for containerless local builds
it also prevents this codepath from being used in RBE, which was a main goal of the previous changes
=> ci/codeql: Fix build setup

.azure-pipelines/ci.yml, .azure-pipelines/stage/checks.yml, ci/build_setup.sh, ci/do_ci.sh
Currently the compile-time-options/msan/asan tests are run in the context of the filter-example
This adds a lot of complexity to the build and messes up our test artefacts.
The example is not well maintained - it has circle CI configured which hasnt passed in years. Ideally we close that repo and add it instead to the examples repo
=> ci/example: Dont build/test the filter example in Envoy CI

source/common/http/filter_manager.h, test/common/http/conn_manager_impl_test_base.cc
Commit Message: http: minor code clean up to the http filter manager
1. simplify the code and remove unnecessary flag.
2. resolve clang tidy warning.
Testing: n/a.
=> http: minor code clean up to the http filter manager

mobile/library/swift/EngineBuilder.swift, mobile/test/swift/integration/CancelGRPCStreamTest.swift, mobile/test/swift/integration/CancelStreamTest.swift, mobile/test/swift/integration/EndToEndNetworkingTest.swift, mobile/test/swift/integration/EngineApiTest.swift, mobile/test/swift/integration/FilterResetIdleTest.swift, mobile/test/swift/integration/GRPCReceiveErrorTest.swift, mobile/test/swift/integration/IdleTimeoutTest.swift, mobile/test/swift/integration/KeyValueStoreTest.swift, mobile/test/swift/integration/ReceiveDataTest.swift, mobile/test/swift/integration/ReceiveErrorTest.swift, mobile/test/swift/integration/ResetConnectivityStateTest.swift, mobile/test/swift/integration/SendDataTest.swift, mobile/test/swift/integration/SendHeadersTest.swift, mobile/test/swift/integration/SendTrailersTest.swift, mobile/test/swift/integration/SetEventTrackerTest.swift, mobile/test/swift/integration/SetEventTrackerTestNoTracker.swift, mobile/test/swift/integration/SetLoggerTest.swift, mobile/test/swift/integration/proxying/HTTPRequestUsingProxyTest.swift
In Swift, `print` goes to stdout buffering. The fix is to flush the `stdout` and `stderr` before the end of the test.
See https://github.com/swiftlang/swift-corelibs-xctest/issues/422#issuecomment-1310952437
Testing: CI
=> mobile: Fix missing logging output in Swift integration tests

test/extensions/geoip_providers/maxmind/geoip_provider_test.cc
Fixing asan failures:
```
==16==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 48 byte(s) in 1 object(s) allocated from:
#0 0x323ecbe in malloc /local/mnt/workspace/bcain_clang_hu-bcain-lv_22036/final/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
#1 0xa58a194 in operator new(unsigned long) (/b/f/w/bazel-out/k8-dbg/bin/test/extensions/geoip_providers/maxmind/geoip_provider_test.runfiles/envoy/test/extensions/geoip_providers/maxmind/geoip_provider_test+0xa58a194)
#2 0x3348d04 in void std::__1::vector<std::__1::function<absl::lts_20230802::Status (unsigned int)>, std::__1::allocator<std::__1::function<absl::lts_20230802::Status (unsigned int)> > >::__emplace_back_slow_path<std::__1::function<absl::lts_20230802::Status (unsigned int)> …
```
=> Geoip fix asan failure

source/extensions/common/aws/metadata_fetcher.cc, test/extensions/common/aws/metadata_fetcher_test.cc
Commit Message: aws: fix test flake when no IMDS can be found 
Additional Description: Lack of IMDS (169.254.169.254 address) can cause a race condition and crash during testing due to the shutdown of cluster manager. This scenario should not occur normally, as cluster manager will still exist and the lack of IMDS is handled gracefully.
=> aws: fix test flake when no IMDS can be found (#35633)

test/common/quic/envoy_quic_client_stream_test.cc, test/common/quic/envoy_quic_h3_fuzz_helper.cc, test/common/quic/envoy_quic_server_stream_test.cc, test/common/quic/envoy_quic_utils_test.cc, test/common/quic/test_utils.h
spdy::Http2HeaderBlock is just an alias for quiche::HttpHeaderBlock.
Commit Message: removes more references to spdy::Http2HeaderBlock
Docs Changes:
Release Notes:
=> quic: removes more references to spdy::Http2HeaderBlock.

README.md
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: updating meeting info

docs/root/configuration/http/http_filters/original_src_filter.rst
The doc is about http original_src filter while in the example, the listed type is that of listener filter.
Existing example will result in following error:
Didn't find a registered implementation for 'envoy.filters.http.original_src' with type URL: 'envoy.extensions.filters.listener.original_src.v3.OriginalSrc'
Commit Message: Typo in documentation of http original_src filter
Testing: Locally
Release Notes: Typo in documentation of http original_src filter
=> Typo in documentation of http original_src filter

changelogs/current.yaml, source/common/runtime/runtime_features.cc, source/common/runtime/runtime_impl.cc, test/common/runtime/runtime_impl_test.cc
Commit Message: Load RTDS boolean config correctly as true/false instead of 1/0
Additional Description: Currently, RTDS boolean values are being loaded as `1` or `0`, which is inconsistent with the expected `true` or `false` values. This discrepancy needs to be corrected so that boolean values are consistently loaded and represented as `true` or `false`. For further details, please refer to the [issue comment](https://github.com/envoyproxy/envoy/issues/35762#issuecomment-2338685970) where this inconsistency is discussed.
Risk Level: Low (to be consistent with initially loaded true/false value)
Testing: new Unit Test
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/35762
=> runtime: load rtds bool correctly as true/false instead of 1/0

source/common/http/headers.h, source/extensions/filters/http/common/jwks_fetcher.cc, test/extensions/filters/http/common/jwks_fetcher_test.cc
Commit Message: Add the "Go-browser" UA string to the headers to make request for JWKS Fetcher
Additional Description: Since none of the requests are having a UA string it makes sense to add it as part of utility lib itself
Testing: N/A
Fixes #35785
=> jwks: Add UA string to headers

contrib/kafka/filters/network/source/protocol/generator.py, contrib/kafka/filters/network/source/serialization.h, docs/root/configuration/listeners/network_filters/kafka_broker_filter.rst
Commit Message: kafka: update protocol code to handle future versions of Kafka protocol (3.8)
Additional Description:  Refactor and enhance Kafka protocol generation code so that future versions of Kafka (3.8) can be trivially uptaken. The changes applied result in only one rename in generated code (`TopicPartitions -> RequestTopicPartitions`).
Testing: automated suite + manual with [envoy-kafka-tests](https://github.com/adamkotwasinski/envoy-kafka-tests/pull/12/files)
Docs Changes: clarification for Kafka broker
=> kafka: update protocol code to handle future versions of Kafka protocol (3.8)

source/extensions/filters/network/redis_proxy/proxy_filter.cc, source/extensions/filters/network/redis_proxy/proxy_filter.h, test/extensions/filters/network/redis_proxy/proxy_filter_test.cc, test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc
**Description**
We started using External Authentication and it works exactly as expected on a normal use-case. But on some setups, we notice that if an AUTH command is pipelined with another command, since the gRPC call is async, it may process another command before AUTH is fully processed, which by Redis standards should not be possible, ordering should be respected.
_Risk Level_: Low (small change to unreleased feature)
_Testing_:
**Unit Tests:** ✅ 
**Integration Tests:** ✅
**Manual Testing (repro):** ✅ 
Before fix:
After fix:
Fixes #35983
=> redis_proxy: Fix #35983 - External Authentication should respect pipelining

changelogs/current.yaml, source/common/http/header_utility.cc, source/common/runtime/runtime_features.cc
Commit Message: http: remove envoy.reloadable_features.http2_validate_authority_with_quiche
Deprecating and removing the runtime flag `envoy.reloadable_features.http2_validate_authority_with_quiche`.
Testing: N/A
Fixes #30419
=> http: remove envoy_reloadable_features_http2_validate_authority_with_quiche

mobile/test/common/integration/client_integration_test.cc
This PR removes the test expectation that the `end_stream` always contains 0 bytes since this behavior is not guaranteed causing test flakiness. This is similar to https://github.com/envoyproxy/envoy/pull/34252. See also https://github.com/envoyproxy/envoy-mobile/issues/1393.
Fixes https://github.com/envoyproxy/envoy/issues/36074.
Testing: `bazel test //test/common/integration:client_integration_test --runs_per_test=200`
=> mobile: Fix flaky ClientIntegrationTest

mobile/library/cc/engine_builder.cc, mobile/library/common/extensions/cert_validator/platform_bridge/BUILD, mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge.proto, mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.cc, mobile/library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.h, mobile/test/common/extensions/cert_validator/platform_bridge/BUILD, mobile/test/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator_test.cc
If the Envoy Mobile thread has a thread priority set, the Platform Cert Validator's validation thread also has the thread priority set to the same value.
=> mobile: Enable setting the Platform Cert Validator thread priority

contrib/vcl/source/BUILD
There are multiple files named config.h and in some build environments it causes the build postscript to fail
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API
Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.31] vpp/build: Minor fix for cmake build (#35583)

test/per_file_coverage.sh
NOTE: local runs of `bazel coverage` and `lcov` show 99% coverage.
Also, reorders some low coverage entries to be alphabetically friendly.
=> coverage: Adjust the coverage threshold for common/posix

test/extensions/geoip_providers/maxmind/geoip_provider_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
Partially Fixes #35829
=> [Geoip+ci] Fix flaky release check in ci

contrib/vcl/source/BUILD
Ensure build does not try to repeatedly copy same files to output
=> vpp: Additional fix for build file mangling

contrib/vcl/source/BUILD
Ensure build does not try to repeatedly copy same files to output
=> [bp/1.29] vpp: Additional fix for build file mangling (#36120)

mobile/test/kotlin/integration/proxying/BUILD, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPRequestUsingProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestBadHostnameTest.kt, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestUsingAsyncProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyInfoIntentPerformHTTPSRequestUsingProxyTest.kt, mobile/test/kotlin/integration/proxying/ProxyPollPerformHTTPRequestUsingProxyTest.kt
This should make the tests less flaky.
Testing: ` bazel test //test/kotlin/integration/proxying/...`
=> mobile: Make Android proxy tests hermetic

test/integration/quic_protocol_integration_test.cc, test/integration/ssl_utility.cc, test/integration/ssl_utility.h, test/integration/utility.cc, test/integration/utility.h
Adding test infra to allow a quic test client to talk to the quic test upstream
Adding an e2e test of reading when more than 32 packets are in the kernel buffer
Testing: yes
=> quic: batch packet testing

bazel/dependency_imports.bzl, contrib/golang/filters/http/test/test_data/access_log/go.mod, contrib/golang/filters/http/test/test_data/action/go.mod, contrib/golang/filters/http/test/test_data/basic/go.mod, contrib/golang/filters/http/test/test_data/buffer/go.mod, contrib/golang/filters/http/test/test_data/dummy/go.mod, contrib/golang/filters/http/test/test_data/echo/go.mod, contrib/golang/filters/http/test/test_data/metric/go.mod, contrib/golang/filters/http/test/test_data/passthrough/go.mod, contrib/golang/filters/http/test/test_data/property/go.mod, contrib/golang/filters/http/test/test_data/routeconfig/go.mod, contrib/golang/filters/http/test/test_data/websocket/go.mod, contrib/golang/filters/network/test/test_data/go.mod, contrib/golang/router/cluster_specifier/test/test_data/simple/go.mod, go.mod, go.sum
Commit Message: upgrade go version to 1.23
Given the [Go release policy](https://go.dev/doc/devel/release#policy):
> Each major Go release is supported until there are two newer major releases.
This PR upgrades Go toolchain to its latest release after seeking advices from @doujiang24.
Testing: n/a.
=> contrib: upgrade go version to 1.23

contrib/golang/filters/http/source/golang_filter.cc, source/common/http/utility.h, source/extensions/filters/http/cors/cors_filter.cc, source/extensions/filters/http/cors/cors_filter.h, source/extensions/filters/http/custom_response/custom_response_filter.cc, source/extensions/filters/http/ext_authz/ext_authz.cc, source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/header_mutation/header_mutation.cc, source/extensions/filters/http/header_mutation/header_mutation.h, test/extensions/filters/http/cors/cors_filter_test.cc
Commit Message: route: use reference wrapper for get all filter config
@alyssawilk I think we have a information gap at #36028. The pointer is better for the `perFilterConfigs()` because we always need to do a dynamic_cast. pointer is simpler and won't result in potential exception throwing.
But the `Utility::getAllPerFilterConfigs()` could use the reference wrapper because it take a template parameter and will return the typed configs.
Testing: n/a.
=> route: use reference wrapper for get all filter config

OWNERS.md
Removing an employee who has moved on.
=> docs: update owners to reflect RedHat access

source/extensions/filters/http/rate_limit_quota/client.h, source/extensions/filters/http/rate_limit_quota/client_impl.cc, source/extensions/filters/http/rate_limit_quota/client_impl.h, source/extensions/filters/http/rate_limit_quota/filter.cc, test/extensions/filters/http/rate_limit_quota/client_test.cc, test/extensions/filters/http/rate_limit_quota/client_test_utils.h, test/extensions/filters/http/rate_limit_quota/integration_test.cc, test/extensions/filters/http/rate_limit_quota/mocks.h
Commit Message: Implement RLQS stream restarts if the stream goes down mid-use.
Additional Description: Stream restarts are done during periodic usage reporting, which limits retry spam while backends are offline.
Risk Level:
Testing: Integration testing updated to exercise the filter before and after stream closure.
Docs Changes:
Release Notes:
=> [RLQS] Implement RLQS stream restarts if the stream goes down mid-use.

source/common/upstream/upstream_impl.cc
Commit Message: upstream-filter: update default upstream filter type
Prior to this the debug logs contain the following:
```
[source/common/http/filter_chain_helper.h:160]     config: Failed to convert protobuf message to JSON string: INVALID_ARGUMENT: @type must contain at least one / and a nonempty host; got: envoy.extensions.filters.http.upstream_codec.v3.UpstreamCodec
```
After this PR they contain:
```
[source/common/http/filter_chain_helper.h:160]     config: {"@type":"type.googleapis.com/envoy.extensions.filters.http.upstream_codec.v3.UpstreamCodec"}
```
Risk Level: low - seems to be impacting debug logs only
Testing: N/A
=> upstream-filter: update default upstream filter type

tools/code_format/config.yaml
I reviewed a PR adding exceptions to a previously exception free path without realizing it.  Narrowing the checks so we're more likely to catch this in CI.
Risk Level: n/a (tooling only)
Testing: ci
part of https://github.com/envoyproxy/envoy/issues/27412
=> tooling: narrowing exception checks

test/common/thread_local/thread_local_impl_test.cc, test/extensions/common/redis/cluster_refresh_manager_test.cc, test/mocks/event/mocks.cc
Commit Message: MockDispatcher to not accidentally run on other threads
Additional Description: Several issues have been found recently where the MockDispatcher's default behavior of just running the callback immediately causes tests to pass, but asan/tsan/release tests fail, because it ends up running the callback on a different thread, exactly the opposite of almost the whole point of posting things on a dispatcher which is to put them on a specific thread. This change makes MockDispatcher insist on being on whichever thread created the dispatcher, most likely the main thread in tests. This is still not great because the behavior of running the callback immediately is still quite different from the behavior of a dispatcher in production, e.g.
```
auto x = std::make_shared<int>(0); …
```
=> MockDispatcher to not accidentally run on other threads

docs/root/start/install.rst
Commit Message: Fix install commands for linux distribution
Testing: manual testing
Docs Changes:
Release Notes:
=> docs: fix install commands for linux distribution

source/extensions/config_subscription/grpc/watch_map.cc
Commit Message: grpc-xDS: reserve vector size
Modifying the watch-map to reserve a vector size prior to adding elements to it.
Risk Level: low - c++ internal only modification
Testing: N/A
Release Notes: N/A - no user facing changes
=> grpc-xDS: reserve vector size

test/integration/health_check_integration_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Fix typo in test name

api/envoy/extensions/load_balancing_policies/client_side_weighted_round_robin/v3/client_side_weighted_round_robin.proto
Add `metric_names_for_computing_utilization` field to `ClientSideWeightedRoundRobin` LB Policy config proto.
- This is a minor change to unblock config plane work while #35905 is going through review.
- See #35905 for initial LB policy implementation.
#34777
=> Add `metric_names_for_computing_utilization` field to `ClientSideWeightedRoundRobin` LB Policy proto.

source/common/quic/envoy_quic_client_connection.cc, source/common/quic/envoy_quic_client_connection.h, test/common/quic/BUILD, test/common/quic/envoy_quic_client_session_test.cc
Commit Message: today the connection will be closed with QUIC_INTERNAL_ERROR because of https://github.com/google/quiche/blob/4249f8025caed1e3d71d04d9cadf42251acb7cac/quiche/quic/core/quic_connection.cc#L2703 if the socket becomes write blocked and then unblocked. This change fixes it by calling [OnBlockedWriterCanWrite()](https://github.com/google/quiche/blob/4249f8025caed1e3d71d04d9cadf42251acb7cac/quiche/quic/core/quic_connection.cc#L2692) instead which set the writer to be unblocked before OnCanWrite().
Additional Message: also refined some comments in the same file.
Risk Level: low, fix existing issue
Testing: added unit tests
=> quic: fix connection close error when blocked socket gets unblocked

changelogs/current.yaml, source/common/http/codec_client.cc, source/common/http/http2/codec_impl.cc, source/common/http/status.cc, source/common/http/status.h, source/common/runtime/runtime_features.cc, test/integration/multiplexed_integration_test.cc
Testing: Added new tests
Runtime guard: envoy.reloadable_features.http2_no_protocol_error_upon_clean_close
Fixes #21522
=> http2: fix reported protocol error from graceful upstream close

source/extensions/filters/http/cache/cache_filter.cc, source/extensions/filters/http/cache/cache_filter.h, source/extensions/filters/http/cache/cache_insert_queue.cc, source/extensions/filters/http/cache/cache_insert_queue.h, source/extensions/filters/http/cache/http_cache.h, source/extensions/http/cache/file_system_http_cache/file_system_http_cache.cc, source/extensions/http/cache/file_system_http_cache/file_system_http_cache.h, source/extensions/http/cache/file_system_http_cache/insert_context.cc, source/extensions/http/cache/file_system_http_cache/insert_context.h, source/extensions/http/cache/file_system_http_cache/lookup_context.cc, source/extensions/http/cache/simple_http_cache/simple_http_cache.cc, source/extensions/http/cache/simple_http_cache/simple_http_cache.h, test/extensions/filters/http/cache/cache_filter_test.cc, test/extensions/filters/http/cache/http_cache_implementation_test_common.cc, test/extensions/filters/http/cache/http_cache_implementation_test_common.h, test/extensions/filters/http/cache/mocks.h
Commit Message: Refactor cache_filter to expect caches to post cb
Additional Description: This is a bit of an unintuitive change in that it moves some work from the common class to the plugin, meaning that work will be duplicated. However, there's a good reason for this - if the cache class needs to use a dispatcher to get back onto its own thread, having cache_filter also post means that actions end up being queued in the dispatcher twice.
A different possible solution would be to have the cache_filter callbacks only post if the callback comes in on the wrong thread, but there's a wrinkle in that model too - if the callback executes immediately, on the same thread, as was the case with the simple_http_cache, it executes too soon, trying to resume a connection that hasn't yet stopped, …
=> Refactor cache_filter to expect caches to post cb

tools/base/requirements.txt
this should reduce dependabot noise - also the release branches need something similar so will ~backport this
=> tools/python: Update all deps

mobile/test/java/org/chromium/net/CronetHttp3Test.java
Some `CronetHttp3Test` tests got accidentally commented out. This PR revert these accidental changes.
Testing: `blaze test //test/java/org/chromium/net:cronet_http3_test`
=> mobile: Revert accidental test changes

test/extensions/geoip_providers/maxmind/geoip_provider_test.cc
Fix for:
```
==12==ERROR: AddressSanitizer: heap-use-after-free on address 0x60300019d860 at pc 0xb7d3f059f8cc bp 0xe6dc6a8fde80 sp 0xe6dc6a8fd670
WRITE of size 24 at 0x60300019d860 thread T1
#0 0xb7d3f059f8c8 in __asan_memset (/home/nezdolik.linux/.cache/bazel/_bazel_nezdolik/9a5f062d7ba021dba530b9f40b2998a7/execroot/envoy/bazel-out/aarch64-fastbuild/bin/test/extensions/geoip_providers/maxmind/geoip_provider_test+0x48ef8c8)
#1 0xb7d3f065bb9c in std::function<absl::lts_20230802::Status (unsigned int)>& std::vector<std::function<absl::lts_20230802::Status (unsigned int)>, std::allocator<std::function<absl::lts_20230802::Status (unsigned int)>>>::emplace_back<std::function<absl::lts_20230802::Status (unsigned int)>>(std::function<absl::lts_20230802::Status (unsigned int)>&&) …
```
=> Fix asan failure

api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto, changelogs/current.yaml, source/extensions/filters/http/ext_proc/BUILD, source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Added allow list `allowed_override_modes` for mode_override.
Testing: Integration test 
=> ext_proc: Add allow list for mode override

CODEOWNERS
Description:
Adding new code owner for ext_proc filter
Testing: N/A
=> Adding new code owner for ext_proc filter

changelogs/current.yaml, source/extensions/tracers/opentelemetry/tracer.cc
Commit Message: opentelemetrytracer: avoid exporting when there are no spans
Additional Description: Today, the OpenTelemetry tracer exports a OTLP request on each interval, even when there are no spans to be sent. The OTLP is empty, only containing the resource (and its attributes). 
[Optional Fixes #35997] 
=> opentelemetrytracer: avoid exporting when there are no spans

.github/workflows/_precheck_publish.yml
this is an interim measure to reduce build times and mittigate VM overload, pending Engflow arm RBE pools coming online
after discussion we felt this was justified as without it we are likely to get jobs being retested, and larger machines should reduce the build times some
=> ci: Boost arm build machines

contrib/golang/filters/http/test/test_data/access_log/go.mod, contrib/golang/filters/http/test/test_data/action/go.mod, contrib/golang/filters/http/test/test_data/basic/go.mod, contrib/golang/filters/http/test/test_data/buffer/go.mod, contrib/golang/filters/http/test/test_data/dummy/go.mod, contrib/golang/filters/http/test/test_data/echo/go.mod, contrib/golang/filters/http/test/test_data/metric/go.mod, contrib/golang/filters/http/test/test_data/passthrough/go.mod, contrib/golang/filters/http/test/test_data/property/go.mod, contrib/golang/filters/http/test/test_data/routeconfig/go.mod, contrib/golang/filters/http/test/test_data/websocket/go.mod, contrib/golang/filters/network/test/test_data/go.mod, contrib/golang/router/cluster_specifier/test/test_data/simple/go.mod, go.mod
Commit Message: contrib: switch the minimal go version to a more stable version
It's too risky to use a version which is just released for a month as the minimal Go version requirement. That previous change hurts the adoption of Envoy Golang filter as it forced users to use the latest version as the minimal required version.
Testing:
Docs Changes:
Release Notes:
Fixes #36246
=> contrib: switch the minimal go version to a more stable version

changelogs/current.yaml, source/extensions/tracers/opentelemetry/tracer.cc
Commit Message: Backport #36395
[Optional Fixes #35997]
=> [bp/1.31] opentelemetrytracer: avoid exporting when there are no spans
