changelogs/current.yaml, source/extensions/tracers/opentelemetry/tracer.cc
Commit Message: Backport #36395
[Optional Fixes #35997]
=> [bp/1.29] opentelemetrytracer: avoid exporting when there are no spans

source/common/quic/envoy_quic_client_stream.cc, source/common/quic/envoy_quic_server_stream.cc, test/common/quic/envoy_quic_client_session_test.cc, test/integration/protocol_integration_test.cc
Commit Message: add `FROM_PEER`/`FROM_SELF` to the transport_failure_reason string when a QUIC stream gets reset.
Risk Level: low, error reporting format change
=> quic: report stream reset direction in reset callback failure string

mobile/test/java/org/chromium/net/BUILD, mobile/test/java/org/chromium/net/BidirectionalStreamTest.java
I still don't fully understand how removing the `shutdown` fixes the issue. Although it doesn't completely fix the flakiness but it reduces the flakiness by a lot.
Testing: `bazel test --runs_per_test=100 //test/java/org/chromium/net:bidirectional_stream_test`
=> mobile: Deflake BidirectionalStreamTest

source/common/config/utility.cc, source/common/config/utility.h, test/common/config/BUILD, test/common/config/utility_test.cc
Commit Message: Error message to mention UpstreamCodec filter
Additional Description: The requirement described in https://github.com/envoyproxy/envoy/issues/26138 doesn't seem to be mentioned in documentation, and even if it was I most likely wouldn't have seen it and probably neither would the person who filed the issue, so documenting the requirement in the failed validation error message seems a more practical solution.
I also moved the function implementation out of the header file, making for cleaner code but a more unpleasant review, sorry.
Risk Level: Only changes an error message, so ~none.
Testing: Added unit test coverage (previously coverage was partial and from integration tests).
=> Error message to mention UpstreamCodec filter

mobile/test/java/integration/AndroidEngineExplicitFlowTest.java, mobile/test/java/integration/BUILD
The `AndroidEngineExplicitFlowTest.post_multipleRequests_randomBehavior` seems to be the one that's causing the flakiness. Adding `flaky = True` and fixing the HTTP method to `POST` as what the test is intended seemed to reduce the flakiness.
Testing: `bazel test --runs_per_test=100 //test/java/integration:android_engine_explicit_flow_test`
=> mobile: Mark AndroidEngineExplicitFlowTest as flaky

envoy/stream_info/filter_state.h, source/common/formatter/stream_info_formatter.cc, source/common/formatter/stream_info_formatter.h, source/common/network/filter_state_dst_address.cc, source/common/network/filter_state_dst_address.h, source/extensions/filters/common/expr/context.cc, test/common/formatter/substitution_formatter_test.cc, test/extensions/clusters/original_dst/original_dst_cluster_test.cc, test/extensions/filters/common/expr/context_test.cc
Commit Message: refactoring: refactored the FilterState object field support
The filter state reflection provides a great feature to access the inner status/property of filter state. However, it has two limitations:
1. It requires the object key be same with the factory key. This limitation make we cannot set multiple objects that with same type.
2. It is a little complex to enable the Field support. We need to define additional reflection class and a factory class.
This PR make things much simpler.
Testing: n/a.
=> refactoring: refactored the FilterState object field support

.bazelrc
Without this, when building in the envoy docker without RBE, I see gcc trying to use `lld` instead, and it's (a) not in `$PATH` and (b) counter to what we had set in `--linkopt` for the gcc config.
Testing: local build in envoy docker
=> gcc: add a `--host_linkopt` to use `gold` too

api/envoy/extensions/transport_sockets/tls/v3/common.proto
Commit Message: xds: make certificate provider instance name required
Additional Description: The comment saying that there is a default value for this field is misleading.  All existing gRPC implementations have this as a required field.  Note that this change does not affect Envoy, since Envoy does not yet support this field.  However, I've added a PGV annotation (used by Envoy but not by gRPC) to avoid confusion when Envoy eventually adds support for this field.
Testing: N/A
=> xds: make certificate provider instance name required

source/extensions/access_loggers/grpc/grpc_access_log_utils.cc, source/extensions/common/dubbo/hessian2_utils.h, source/extensions/filters/network/dubbo_proxy/hessian_utils.h, source/extensions/health_checkers/grpc/health_checker_impl.cc, source/extensions/health_checkers/http/health_checker_impl.h, source/extensions/health_checkers/thrift/thrift.h
The false positive warnings have been resolved in current versions of gcc.
Testing: CI
=> gcc: remove -Wdangling-reference workaround

source/common/orca/BUILD, source/common/orca/orca_parser.cc, source/common/orca/orca_parser.h, test/common/orca/orca_parser_test.cc
Commit Message: Add support for multiple formats of ORCA headers.
Additional Description: Add support for multiple formats of ORCA headers. ORCA parsing introduced in https://github.com/envoyproxy/envoy/pull/35422
[Original Design Proposal](https://github.com/envoyproxy/envoy/issues/6614)
[Using ORCA load reports in Envoy](https://docs.google.com/document/d/1gb_2pcNnEzTgo1EJ6w1Ol7O-EH-O_Ysu5o215N9MTAg/edit#heading=h.bi4e79pb39fe)
Testing: See included unit tests.
Platform Specific Features: JSON format unsupported on Mobile.
CC @efimki @adisuissa @wbpcode
=> Add support for multiple formats of ORCA headers.

test/extensions/load_balancing_policies/client_side_weighted_round_robin/BUILD
//test/extensions/load_balancing_policies/client_side_weighted_round_robin:integration_test
Testing: CI
=> Adjust RBE resources for a memory-hungry test

mobile/test/common/integration/test_server_interface.cc, mobile/test/common/integration/test_server_interface.h, mobile/test/objective-c/EnvoyTestServer.h, mobile/test/objective-c/EnvoyTestServer.mm, mobile/test/swift/integration/CancelGRPCStreamTest.swift, mobile/test/swift/integration/CancelStreamTest.swift, mobile/test/swift/integration/EndToEndNetworkingTest.swift, mobile/test/swift/integration/FilterResetIdleTest.swift, mobile/test/swift/integration/GRPCReceiveErrorTest.swift, mobile/test/swift/integration/IdleTimeoutTest.swift, mobile/test/swift/integration/KeyValueStoreTest.swift, mobile/test/swift/integration/ReceiveDataTest.swift, mobile/test/swift/integration/ResetConnectivityStateTest.swift, mobile/test/swift/integration/SendDataTest.swift, mobile/test/swift/integration/SendHeadersTest.swift, mobile/test/swift/integration/SendTrailersTest.swift, mobile/test/swift/integration/SetEventTrackerTest.swift, mobile/test/swift/integration/SetEventTrackerTestNoTracker.swift, mobile/test/swift/integration/SetLoggerTest.swift, mobile/test/swift/integration/proxying/HTTPRequestUsingProxyTest.swift
This will be used by a subsequent change to test the Apple PAC proxy resolver.
=> mobile: Enable integration tests to run both a HTTP and a proxy server

source/common/stream_info/bool_accessor_impl.h, test/common/stream_info/bool_accessor_impl_test.cc
Change-Id: I2065f5ed863ca4b6b439f00dc39de0dcdbe2eb4c
Commit Message: add missing serializer for bool object. I discovered this gap while using Wasm `get_property`.
Testing: yes
=> stream info: add bool string serlalizer

envoy/stream_info/stream_info.h
Commit Message: Make DownstreamTiming a struct, instead of a class
Additional Description:This makes it consistent with UpstreamTiming, and makes it easier to dependency inject timing info for testing.
Risk Level: WCPGW
Testing: None
=> Make DownstreamTiming a struct, instead of a class

mobile/library/common/http/client.cc, mobile/library/common/http/client.h, mobile/test/common/http/client_test.cc, mobile/test/java/integration/BUILD
Fixing two bugs in the send window code.
One where the callback could be called late, after stream completion.  
One where the callback was per-client not per-stream so streams could overwrite each others upcalls.
Testing: first is tested by existing tests no longer flaking.  second TBTested
Fixes https://github.com/envoyproxy/envoy/issues/36493
=> mobile: fixing a flow control bug for multiple large uploads

.github/workflows/codeql-daily.yml, .github/workflows/codeql-push.yml
It doesn't work without sandboxing, and this build uses `--spawn_strategy=local`.
https://github.com/bazelbuild/bazel/issues/21592
Once we upgrade to a bazel 7.3.0+, this should no longer be needed.
Risk Level: Low; only affects CI CodeQL build
=> Disable bazel's layering_check feature during CodeQL build.

bazel/external/boringssl_fips.genrule_cmd
fips build: fixed an issue when tar is running as root causing 'Cannot change ownership to uid 1000, gid 1000: Invalid argument' error
Commit Message: fips build: fixed an issue when tar is running as root causing 'Cannot change ownership to uid 1000, gid 1000: Invalid argument' error
Additional Description: See this thread for issue and solution: https://superuser.com/questions/1435437/how-to-get-around-this-error-when-untarring-an-archive-tar-cannot-change-owner
Testing: Was tested with our internal build pipeline (buildkite)
Platform Specific Features: Build
[Optional [API …
=> fips build: fixed an issue when tar is running as root

source/extensions/filters/http/rate_limit_quota/client_impl.cc, test/extensions/filters/http/rate_limit_quota/client_test.cc
Commit Message: When an RLQS response comes in that would create a duplicate TokenBucket (because the underlying config hasn't changed), treat this as a refresh to the TTL but don't reset the TokenBucket's state by recreating it.
Docs Changes:
Release Notes:
=> Updated RLQS Response handling to not reset TokenBucket state

mobile/library/cc/engine.cc, mobile/library/cc/engine.h
Commit Message: expose onNetworkTypeChanged API to Engine
Additional Description: This prevents applications from directly depending on InternalEngine.
Testing: n/a
=> [mobile]expose onNetworkTypeChanged API to Engine

test/common/tls/context_impl_test.cc
`createSslClientContext` used to throw on error. In the refactoring some test validation was inadvertently removed.
=> tls: re-add validation that context is successfully created

source/extensions/filters/http/ext_proc/ext_proc.cc, test/extensions/filters/http/ext_proc/filter_test.cc, test/extensions/filters/http/ext_proc/ordering_test.cc
Commit Message: `StopIterationAndWatermark` will raise the watermark when buffered data exceeds the limits, the `requestWatermark` here is redundant and it will also introduce unnecessary stall of Envoy processing and overhead of raise and clear watermark possibly for small bodies
Testing: 
1.Passed all functional tests (unit test and integration test) 
2.This PR performs slightly better in load test.
```
4KB  request body:  
Without this PR:  Memory 183.29MB; Latency P99 : 2716
With this PR:  Memory: 160.17MB;    Latency P99: 2624
64KB request body:
Without this PR:  Memory 178.49MB; Latency P99 : 3512
With this PR:  Memory: 172.70MB;    Latency P99: 3505
```
=> ext_proc: remove unnecessary watermark

bazel/repository_locations.bzl
(cherry picked from commit 55b0fc45cfdc2c0df002690606853540cf794fab)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> 1.29 backport: ci: change googleurl dep (#36515)

bazel/repository_locations.bzl
(cherry picked from commit 55b0fc45cfdc2c0df002690606853540cf794fab)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> 1.31 backport: ci: change googleurl dep (#36515)

bazel/repository_locations.bzl
(cherry picked from commit 55b0fc45cfdc2c0df002690606853540cf794fab)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> 1.30 backport: ci: change googleurl dep (#36515)

source/common/protobuf/utility.h, source/common/protobuf/yaml_utility.cc
Commit Message: proto util: change the input string ref to string view
`absl::string_view` is better than`const string&` in most cases to avoid unnecessary copy.
Testing: n/a.
=> proto util: change the input string ref to string view

bazel/repository_locations.bzl
(cherry picked from commit 55b0fc45cfdc2c0df002690606853540cf794fab)
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> 1.28 backport: ci: change googleurl dep (#36515)

source/extensions/filters/http/ext_proc/ext_proc.cc, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Commit Message: Like header and body, timer/timeout should be skipped on trailer as well in async. It is because there is no response/ or response is ignored.
Testing: Integration test (test the timeout on header, body and trailer)
=> ext_proc: skip timeout timer on trailer in async mode.

source/common/orca/orca_parser.cc, source/common/orca/orca_parser.h, source/common/protobuf/utility.h, source/common/protobuf/yaml_utility.cc, test/common/orca/orca_parser_test.cc
Commit Message: minor opt: minor optimization to the orca parser
By this way, the parser needn't to scan the whole header value if the header value has invalid format. And the we needn't create a copy of the header value for json format now.
Testing: n/a.
=> minor opt: minor optimization to the orca parser

docs/root/configuration/http/http_filters/lua_filter.rst
Commit Message: lua: mention that body should be consumed before fetching trailers
Risk Level: Zero
Testing: N/A
Docs Changes: lua_filter.rst
Release Notes:
Fixes https://github.com/envoyproxy/envoy/issues/36507
=> lua: mention that body should be consumed before fetching trailers

source/extensions/filters/http/ext_authz/ext_authz.cc, source/extensions/filters/http/ext_authz/ext_authz.h, test/extensions/filters/http/ext_authz/ext_authz_test.cc
Commit Message: fix potential null dereference in ext_authz
Previously, if ext_authz had emit filter state stats set to true and another filter added filter state under the ext authz filter's name, it would result in a null dereference. The member logging_info_ would not be set in initiateCall after seeing there was already data there. Later, we would dereference logging_info_ to update the stats as if it were initialized already.
I've added a check for a null logging_info_ and added logging & a stat for when there's a filter state naming collision.
I also made some readability improvements to the ext_authz test.
Testing: unit tested
=> fix potential null dereference in ext_authz

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/tracer_test_filter.cc
Commit Message:  Increase log verbosity and add tracing logs to help diagnose potential flakiness in the GetAndCloseStreamWithTracing test case.
Additional Description: As per discussed in https://github.com/envoyproxy/envoy/issues/36041#issuecomment-2405065443
=> ext_proc: Increase log verbosity in a possible flake test

test/extensions/filters/http/ext_authz/ext_authz_fuzz_lib.cc, test/extensions/filters/http/ext_authz/ext_authz_grpc_corpus/emit_filter_state_stats
Commit Message: fix fuzz test failure
the fuzzer reuses the filter state between test cases currently which causes a fuzz bug. This PR makes it so that it resets the filter state every time a new filter is created.
=> fix fuzz test failure

source/extensions/network/dns_resolver/apple/apple_dns_impl.cc, test/extensions/network/dns_resolver/apple/apple_dns_impl_test.cc
Commit Message: Renames the resolution details from `apple_dns_success` to `apple_dns_completed` with error code since `completed` is more correct that `success` given that the callback will still be called when the error code is `kDNSServiceErr_NoSuchRecord`.
Additional Description: This behavior is also consistent with the implementations of other resolvers.
- [getaddrinfo](https://github.com/envoyproxy/envoy/blob/7847268600ed62e2485fc0c4ab853e7fd79ddf63/source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc#L216)
- [c-ares](https://github.com/envoyproxy/envoy/blob/7847268600ed62e2485fc0c4ab853e7fd79ddf63/source/extensions/network/dns_resolver/cares/dns_impl.cc#L219)
Platform Specific Features: apple_dns
=> apple_dns: Add error code in the DNS resolution details on completion

source/common/protobuf/utility.cc, source/common/runtime/runtime_features.cc, source/extensions/filters/http/cache/http_cache.cc, test/common/protobuf/utility_speed_test.cc, test/common/protobuf/utility_test.cc, test/extensions/filters/http/cache/http_cache_test.cc
Commit Message: Remove use_fast_protobuf_hash runtime flag
Additional Description: Fixes #36613 
Risk Level: Should be a no-op for anyone who didn't override the flag.
Testing: Same as before but without the branches that no longer exist.
=> Remove use_fast_protobuf_hash runtime flag

bazel/protobuf.patch, bazel/repository_locations.bzl, source/common/protobuf/deterministic_hash.cc, source/common/protobuf/protobuf.h, source/common/protobuf/visitor.cc, source/common/protobuf/visitor_helper.h, source/extensions/http/early_header_mutation/header_mutation/config.cc, source/extensions/http/original_ip_detection/custom_header/config.cc, test/common/formatter/command_extension.cc, test/extensions/filters/http/common/fuzz/uber_per_filter.cc, test/extensions/filters/network/common/fuzz/uber_per_readfilter.cc, test/fuzz/mutable_visitor.cc, test/fuzz/validated_input_generator.cc
Bump protobuf to 28.2
Testing: CI
=> bump protobuf to 28.2

bazel/protobuf.patch
The pragma here did not silence `-Wundef` on gcc.
Rework the `#if/#else/#endif` with an additional `defined(...)` check.
Backport of https://github.com/protocolbuffers/protobuf/commit/12eadfdfd9e6603fd5aa8e8e8887540324a4d56d
Testing: CI
=> Adjust bazel/protobuf.patch to better silence a -Wundef warning

mobile/library/cc/engine_builder.h, mobile/library/java/org/chromium/net/impl/NativeCronvoyEngineBuilderImpl.java, mobile/library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
Commit Message: change the  default connect timeout from 30s to 10s to align with Chromium default https://source.chromium.org/chromium/chromium/src/+/main:net/quic/quic_context.h;l=157;drc=04989307509c78d67b34f2282ca549397719d046;bpv=1;bpt=1
Additional Description: Also add Cronvoy  API to change to a different value.
Risk Level: low, mobile only
=> mobile: use 10s default value of connect timeout

test/extensions/config_subscription/grpc/grpc_mux_failover_test.cc, test/extensions/config_subscription/grpc/xds_failover_integration_test.cc
Commit Message: xds-failover: fixing runtime feature flag in tests
PR #36386 added a runtime flag to disable the move to primary feature.
This PR explicitly sets the knob to true on some tests that depend on that behavior.
Testing: N/A
=> xds-failover: fixing runtime feature flag in tests

test/integration/protocol_integration_test.cc
waitForAccessLog asserts the log you're waiting for is the last one.  For periodic logging on slow machines there may end up being extra log entries so allow excess.
https://github.com/envoyproxy/envoy/actions/runs/11371697784/job/31634429494
=> test: deflake an integration test

test/common/http/BUILD, test/common/http/hash_policy_test.cc
Commit Message: add test suites for classes in hash_policy.cc file
Additional Description: Unit test cases don't exist at all for classes defined in hash_policy.cc file at all. This PR adds the same.
Risk Level: Low (No API change)
Testing: All test cases passing.
=> add test suites for classes in hash_policy.cc file

ci/do_ci.sh
Adds `setup_clang_toolchain` to  properly generate compile_commands.json. Fixes [#36686](https://github.com/envoyproxy/envoy/issues/36686).
Commit Message: Adds setup_clang_toolchain command to fix compile_commands.json generation.
Additional Description: Fixes #36686
Testing: Passing
=> build: fix compile commands generation

api/envoy/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto
Commit Message: Fix documentation for TcpProxy.metadata_match
Additional Description: Currently, the documentation for TcpProxy.metadata_match implies that metadata matching will occur even when not using a subset lb, which I don't think is true.
Testing:
=> Fix documentation for TcpProxy.metadata_match

changelogs/current.yaml, docs/root/intro/arch_overview/advanced/attributes.rst, source/extensions/common/wasm/context.cc, source/extensions/common/wasm/remote_async_datasource.cc, test/extensions/filters/http/wasm/test_data/metadata_rust.rs, test/extensions/filters/http/wasm/test_data/test_cpp.cc, test/extensions/filters/http/wasm/wasm_filter_test.cc
Change-Id: I152e259f3f8e5f69463a64fedce4181ce606824b
Commit Message: Remove attributes that were marked as deprecated in https://github.com/envoyproxy/envoy/commit/ff991f3454b426bfec49c752d1e7ffbafa9fdd76. This improves the alignment of `get_property` ABI with the generic attribute support in Envoy in CEL, for example, and simplifies the implementation.
Risk Level: low, experimental filter, advanced warning to stop using attributes was given
=> wasm: remove redundant xds attributes

api/envoy/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.proto
For https://github.com/istio/istio/issues/53577
I'm trying to configure DNS resolvers (specifically `CaresDnsResolverConfig.udp_max_queries`) while using the default system resolvers. Right now, I need to add one resolver, otherwise I get a proto validation error.
Commit Message: Allow empty resolver list for cares dns
Testing:
Docs Changes:
Release Notes:
=> Allow empty resolver list for cares dns

.github/workflows/envoy-macos.yml
when caches are blown this CI takes longer than the current 90s allowed
=> ci/macos: Increase timeout to 120m

changelogs/current.yaml, source/common/runtime/runtime_features.cc, source/extensions/filters/listener/http_inspector/BUILD, source/extensions/filters/listener/http_inspector/http_inspector.cc, source/extensions/filters/listener/http_inspector/http_inspector.h, test/extensions/filters/listener/http_inspector/BUILD, test/extensions/filters/listener/http_inspector/http_inspector_test.cc
Commit Message: Add runtime flag for http_inspector parser
Additional Description: Add default false runtime flag to use balsa_parser in the http_inspector. As part of https://github.com/envoyproxy/envoy/issues/36433 to support parsing of custom methods with http_inspector. 
Risk Level: Low 
Testing:  parametrized all the existing tests of `HttpInspectorTest` to run for both http-parser and BalsaParser.
running the command `bazel test //test/extensions/filters/listener/http_inspector:http_inspector_test
` runs the tests for both the parsers. (Some BalsaParser tests are disabled for now.)
Docs Changes:
Release Notes:
[Optional [API …
=> [balsa] Add runtime flag for http_inspector parser

.github/workflows/codeql-push.yml
this is currently triggering on the release branches
codeql uses ci cache which is very limited and running this on multiple branches is expiring caches making this take a very long time
=> ci/codeql: Only run on main branch

changelogs/current.yaml, envoy/http/request_id_extension.h, source/common/http/conn_manager_utility.cc, source/extensions/request_id/uuid/config.cc, source/extensions/request_id/uuid/config.h, test/common/http/conn_manager_utility_test.cc, test/extensions/filters/network/http_connection_manager/config_test.cc, test/extensions/request_id/uuid/config_test.cc
Commit Message: request id: minor optimization or fix to the request id logic
This PR did some minor optimization (or fix) to the request logic:
1. If `pack_trace_reason` is set to `false`, then the Envoy will not try to read the trace reason from the request id. This ensure the read and write operation of the trace reason be consistant.
2. If `pack_trace_reason` is set to `true` and an external request id is used (by setting the `preserve_external_request_id` to true), then the trace reason from the external request id will be cleared. This ensure the trace reason from the external request id will not be used.
Testing: unit.
=> request id: minor optimization or fix to the request id logic

source/common/router/upstream_request.cc, source/common/router/upstream_request.h
Commit Message: router: clean up unnecessary field
Related logic is moved to UpstreamCodecFilter, this field will never be true in this scope.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> router: clean up unnecessary field

test/per_file_coverage.sh
96.5% for source/common was a bit too high to consistently pass. Let's try 96.4%, which is still better than the 96.2% it was earlier.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> coverage: loosen

source/common/router/config_impl.cc
There is nothing inherently wrong with having `strip_query` set when having a path redirect that has its own query. The `strip_query` is a noop in such case, but its presence does not negatively affect anything, and there is nothing special this code does in such a case other than log the fact. 
In our massively multitenant Envoy deployment, users are allowed to specify both strip_query and redirect path with its own query, and many users do, which leads to a lot of log spam from this WARNING.
Logging this at DEBUG level is also consistent with other purely advisory logs in this class.
Risk Level:
Testing:
Docs Changes:
Release Notes: …
=> Downgrade advisory log message

test/per_file_coverage.sh
This is failing on a bunch of unrelated PRs
=> ci/coverage: Fix coverage flake in `source/extensions/common`

.github/workflows/codeql-push.yml
this is currently triggering on the release branches
codeql uses ci cache which is very limited and running this on multiple branches is expiring caches making this take a very long time
=> [bp/1.32] ci/codeql: Only run on main branch (#36806)

.github/workflows/codeql-push.yml
this is currently triggering on the release branches
codeql uses ci cache which is very limited and running this on multiple branches is expiring caches making this take a very long time
=> [bp/1.29] ci/codeql: Only run on main branch (#36806)

.github/workflows/codeql-push.yml
this is currently triggering on the release branches
codeql uses ci cache which is very limited and running this on multiple branches is expiring caches making this take a very long time
=> [bp/1.31] ci/codeql: Only run on main branch (#36806)

envoy/upstream/load_balancer.h, source/common/upstream/upstream_impl.cc, source/common/upstream/upstream_impl.h, source/extensions/load_balancing_policies/client_side_weighted_round_robin/config.h, source/extensions/load_balancing_policies/cluster_provided/config.h, source/extensions/load_balancing_policies/common/BUILD, source/extensions/load_balancing_policies/common/factory_base.h, source/extensions/load_balancing_policies/least_request/config.h, source/extensions/load_balancing_policies/maglev/config.h, source/extensions/load_balancing_policies/random/config.h, source/extensions/load_balancing_policies/ring_hash/config.h, source/extensions/load_balancing_policies/round_robin/config.h, source/extensions/load_balancing_policies/subset/config.cc, source/extensions/load_balancing_policies/subset/config.h, source/extensions/load_balancing_policies/subset/subset_lb_config.cc, source/extensions/load_balancing_policies/subset/subset_lb_config.h, test/extensions/load_balancing_policies/client_side_weighted_round_robin/config_test.cc, test/extensions/load_balancing_policies/least_request/config_test.cc, test/extensions/load_balancing_policies/maglev/config_test.cc, test/extensions/load_balancing_policies/random/config_test.cc, test/extensions/load_balancing_policies/ring_hash/config_test.cc, test/extensions/load_balancing_policies/round_robin/config_test.cc, test/extensions/load_balancing_policies/subset/BUILD, test/extensions/load_balancing_policies/subset/config_test.cc, test/extensions/load_balancing_policies/subset/subset_benchmark.cc, test/extensions/load_balancing_policies/subset/subset_test.cc, test/integration/load_balancers/custom_lb_policy.h, test/mocks/upstream/load_balancer.h, test/mocks/upstream/typed_load_balancer_factory.h
Commit Message: context: use server factory context as lb context
1. Simplify the context. We needn't more and more factory context.
2. allow the lb to access other API like runtime when loading configuration.
NOTE: This PR also changed the signature of the loadConfig() method. The message validator is removed and you can use the messageValidationVisitor() of the input factory context to validate the proto message.
Testing: n/a.
=> context: use server factory context as lb context

api/envoy/config/listener/v3/listener_components.proto
Commit Message: Remove unused listener FilterChain on_demand_configuration field
API added in https://github.com/envoyproxy/envoy/pull/12599 but the implementation was abandoned in https://github.com/envoyproxy/envoy/pull/12310. The `FilterChain.OnDemandConfiguration` message still shows up in docs, which is confusing: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto.html#config-listener-v3-filterchain-ondemandconfiguration
Testing: none
Release Notes: Removed unused `config.listener.v3.FilterChain.OnDemandConfiguration` message
=> Remove unused listener FilterChain on_demand_configuration field

test/common/api/os_sys_calls_test.cc
supportsIpTransparent() and supportsMptcp() results depend on the OS being run on and the configuration of that OS, so remove the expectation of a specific value from the tests so that they'll pass in all environments.
=> test: fix os_sys_calls_test in some less common environments

source/extensions/common/wasm/plugin.h
Change-Id: I171afa0d240065d3f4872730fc71d70a46c03a93
Commit Message: remove listener info accessors in plugin config since they are dead code
=> wasm: remove unused public interfaces

source/common/common/matchers.cc, source/common/common/matchers.h
Commit Message: matchers: remove unneeded ListMatcher data member
Removed a protobuf that was kept as a data member but only used in the c'tor.
Testing: N/A
=> matchers: remove unneeded ListMatcher data member

source/common/common/BUILD, source/common/common/cancel_wrapper.h, test/common/common/BUILD, test/common/common/cancel_wrapper_test.cc
Commit Message: Add cancelWrapper helper function in /common.
Additional Description: In the cache filter implementation where there are multiple async streams and objects in flight any of which can be aborted from outside the filter's own flow, it's convenient and clear to have a cancel operation performed on being destroyed, rather than inferring "don't call the callback" from a `weak_ptr` (which can do the wrong thing in that onDestroy can happen before destructor, and is verbose and repetitive). Implementing these cancellation functions manually every time is also error-prone and repetitive. This introduces a reusable wrapper template to facilitate cancellable callbacks.
Risk Level: None, no change to production code yet.
Testing: Unit tested. …
=> Add cancelWrapper helper function in /common.

mobile/test/objective-c/EnvoyTestServer.h, mobile/test/objective-c/EnvoyTestServer.mm, mobile/test/swift/integration/CancelGRPCStreamTest.swift, mobile/test/swift/integration/CancelStreamTest.swift, mobile/test/swift/integration/EndToEndNetworkingTest.swift, mobile/test/swift/integration/FilterResetIdleTest.swift, mobile/test/swift/integration/GRPCReceiveErrorTest.swift, mobile/test/swift/integration/IdleTimeoutTest.swift, mobile/test/swift/integration/KeyValueStoreTest.swift, mobile/test/swift/integration/ReceiveDataTest.swift, mobile/test/swift/integration/ResetConnectivityStateTest.swift, mobile/test/swift/integration/SendDataTest.swift, mobile/test/swift/integration/SendHeadersTest.swift, mobile/test/swift/integration/SendTrailersTest.swift, mobile/test/swift/integration/SetEventTrackerTest.swift, mobile/test/swift/integration/SetEventTrackerTestNoTracker.swift, mobile/test/swift/integration/SetLoggerTest.swift, mobile/test/swift/integration/proxying/BUILD, mobile/test/swift/integration/proxying/HTTPRequestUsingPacProxyTest.swift, mobile/test/swift/integration/proxying/HTTPRequestUsingProxyTest.swift
This PR make the tests `HTTPRequestUsingProxyTest.swift` hermetic since it's causing 403 issues when hitting external URLs, for example:
- https://github.com/envoyproxy/envoy/actions/runs/11671611154/job/32500065249
- https://github.com/envoyproxy/envoy/actions/runs/11670461951/job/32494723883
This PR also fixes and enables `testHTTPSRequestUsingProxy` test that was previously disabled.
=> mobile: Fix HTTPRequestUsingProxyTest.swift

ci/README.md
PR updates the location of the envoy's build folder which was moved from `envoy-build-tools` to `docker`.
=> docs: update envoy build location

api/contrib/envoy/extensions/filters/network/kafka_broker/v3/kafka_broker.proto, api/envoy/config/filter/network/kafka_broker/v2alpha1/kafka_broker.proto, contrib/kafka/filters/network/source/broker/BUILD, contrib/kafka/filters/network/source/broker/filter.cc, contrib/kafka/filters/network/source/broker/filter.h, contrib/kafka/filters/network/source/broker/filter_config.cc, contrib/kafka/filters/network/source/broker/filter_config.h, contrib/kafka/filters/network/source/broker/request_handler.cc, contrib/kafka/filters/network/source/broker/request_handler.h, contrib/kafka/filters/network/source/kafka_request.h, contrib/kafka/filters/network/test/broker/BUILD, contrib/kafka/filters/network/test/broker/filter_protocol_test.cc, contrib/kafka/filters/network/test/broker/filter_unit_test.cc, contrib/kafka/filters/network/test/broker/mock_filter_config.h, contrib/kafka/filters/network/test/broker/mock_request.h, contrib/kafka/filters/network/test/broker/request_handler_unit_test.cc, docs/root/configuration/listeners/network_filters/kafka_broker_filter.rst
Commit Message: kafka: close connection when rejectable request appears
Additional Description: provides https://github.com/envoyproxy/envoy/issues/36978 by making the broker filter check the requests' API key against allow/denylists in the config - if we find a request to reject, we just close the connection. There is also a bonus: this sets up a framework for "_close connection if we don't like the request_" that we can expand upon later.
Testing: automated (no filtering) + manual (filtering)
Docs Changes: Kafka broker .rst
=> kafka: close connection when rejectable request appears

source/extensions/filters/http/ext_proc/client_impl.cc, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
- Remove obsolete TODO.  Refactor is not needed as it will actually incur more overhead: add a new isClosed() helper function which is virtual function. i.e., It will be called multiple layers/classes.
- Use isEnvoyGrpc helper in the test
=> ext_proc: clean up

bazel/envoy_library.bzl, distribution/binary/BUILD, docs/BUILD, tools/api_versioning/BUILD, tools/base/envoy_python.bzl, tools/bootstrap2pb/BUILD, tools/ci/BUILD, tools/clang-format/BUILD, tools/clang-tidy/BUILD, tools/code/BUILD, tools/code_format/BUILD, tools/code_format/config.yaml, tools/code_format/envoy_build_fixer.py, tools/dependency/BUILD, tools/distribution/BUILD, tools/docs/BUILD, tools/gcs/BUILD, tools/gsutil/BUILD, tools/h3_request/BUILD, tools/proto_format/BUILD, tools/protodoc/BUILD, tools/protoprint/BUILD, tools/repo/BUILD, tools/sha/BUILD, tools/socket_passing/BUILD, tools/type_whisperer/BUILD, tools/zstd/BUILD
the `envoy_package` rule works against bazel's visibility system by just making everything visible - which is a bit of an anti-pattern - but it also pulls in a lot of unused/unnecessary deps when accessing tools
=> tools: Remove `envoy_package`

source/common/common/utility.cc, source/common/common/utility.h, test/common/formatter/substitution_formatter_test.cc
Commit Message: Relax recent SNI restrictions
Note the intent of the SNI restrictions was not RFC compliance, etc -- but rather to fix [log injection](https://github.com/envoyproxy/envoy/security/advisories/GHSA-p222-xhp9-39rc) attacks (putting ANSI …
=> Relax recent SNI restrictions

source/common/common/BUILD, source/common/common/cancel_wrapper.h, test/common/common/cancel_wrapper_test.cc
Commit Message: Make CancelWrapper enforce thread constraint
Additional Description: Followup to #36938, in debug builds, enforcing the directive that callbacks and cancellations must be on the same thread.
Risk Level: None, still not touching production code.
=> Make CancelWrapper enforce thread constraint

changelogs/current.yaml
Adds a release note for https://github.com/envoyproxy/envoy/pull/36950#issuecomment-2458147011 
Commit Message: Add release note for "Relax recent SNI restrictions"
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Add release note for "Relax recent SNI restrictions"

changelogs/current.yaml, docs/root/configuration/http/cluster_specifier/lua.rst, source/extensions/router/cluster_specifiers/lua/lua_cluster_specifier.cc, source/extensions/router/cluster_specifiers/lua/lua_cluster_specifier.h, test/extensions/router/cluster_specifiers/lua/lua_cluster_specifier_test.cc
Add accessors from a cluster_specifier lua script for cluster connection and request counts
Testing: New tests added
=> lua cluster_specifier: give access to cluster connection/request counts

source/server/BUILD
With reference to PR https://github.com/envoyproxy/envoy/pull/36915 by mistake added the .cc extension instead of the .h extension. So fixing the extension to (options_impl_platform_linux.h).
=> S390x - Fix typo for envoy test

api/bazel/repository_locations.bzl, bazel/repository_locations.bzl
For cel, envoy_toolshed, fmt, protoc-gen-jsonschema, shellcheck rules
Docs Changes: add and fix license URLs of external components
=> docs: add and fix license URLs

changelogs/current.yaml, source/common/common/utility.cc, source/common/common/utility.h, test/common/formatter/substitution_formatter_test.cc
This change is being backported as it is a bug-fix for a regression for a fix that was also applied to this branch. Merging this fixes the regression.
Note the intent of the SNI restrictions was not RFC compliance, etc -- but rather to fix [log …
=> 1.32 backport: Relax recent SNI restrictions (#36950)

changelogs/current.yaml, source/common/common/utility.cc, source/common/common/utility.h, test/common/formatter/substitution_formatter_test.cc
This change is being backported as it is a bug-fix for a regression for a fix that was also applied to this branch. Merging this fixes the regression.
Note the intent of the SNI restrictions was not RFC compliance, etc -- but rather to fix [log …
=> 1.31 backport: Relax recent SNI restrictions (#36950)

source/common/common/BUILD
Commit Message: Remove extraneous target source/common/common:xds_manager_lib
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fairly sure that this was introduced in #36768 by mistake. I can't find any references to the target, `source/common/common/xds_manager_impl.{h,c}` don't exist.
=> Remove extraneous target source/common/common:xds_manager_lib

ci/do_ci.sh
fetch doesnt work very well or in ways you would expect (may improve with bzlmod)
currently this isnt used but when we add it back we will use `aquery` instead to populate the cache
=> bazel/ci: Remove old fetch setup

changelogs/current.yaml, source/common/common/utility.cc, source/common/common/utility.h, test/common/formatter/substitution_formatter_test.cc
This change is being backported as it is a bug-fix for a regression for a fix that was also applied to this branch. Merging this fixes the regression.
Note the intent of the SNI restrictions was not RFC compliance, etc -- but rather to fix [log …
=> 1.29 backport: Relax recent SNI restrictions

changelogs/current.yaml, source/common/common/utility.cc, source/common/common/utility.h, test/common/formatter/substitution_formatter_test.cc
This change is being backported as it is a bug-fix for a regression for a fix that was also applied to this branch. Merging this fixes the regression.
Note the intent of the SNI restrictions was not RFC compliance, etc -- but rather to fix [log …
=> 1.30 backport: Relax recent SNI restrictions

bazel/foreign_cc/BUILD
Clang and gcc are subtly different and it seems to be the cause of contrib build failures reported in
https://github.com/envoyproxy/envoy/issues/31807 (e.g., when using gcc to link the final binary it results in a bunch of essential for gcc C++ symbols like __gxx_personality_v0).
The issue appear to be the order of the libraries when linking. gcc, when building statically linked binaries basically needs libstdc++ to be the last library or alsmot the last library in the command line. And clang does not appear to care about it much.
This change provides libstdc++ library in LIBS environment variabe which will put it in the right position when building the ICU library. This works well for both clang and gcc.
It address the issue reported in …
=> [contrib][http language filter] Change position of libstdc++ library when linking ICU tools

.github/workflows/_load.yml, .github/workflows/_load_env.yml, .github/workflows/_request.yml, .github/workflows/_request_cache.yml, .github/workflows/_request_cache_docker.yml, .github/workflows/_run.yml, .github/workflows/envoy-checks.yml, .github/workflows/envoy-macos.yml, .github/workflows/envoy-prechecks.yml, .github/workflows/envoy-publish.yml, .github/workflows/mobile-android_build.yml, .github/workflows/mobile-android_tests.yml, .github/workflows/mobile-asan.yml, .github/workflows/mobile-cc_tests.yml, .github/workflows/mobile-coverage.yml, .github/workflows/mobile-docs.yml, .github/workflows/mobile-format.yml, .github/workflows/mobile-ios_build.yml, .github/workflows/mobile-ios_tests.yml, .github/workflows/mobile-perf.yml, .github/workflows/mobile-release_validation.yml, .github/workflows/mobile-tsan.yml, .github/workflows/request.yml
Currently all triggered CI jobs check for required caches (and prime where required)
This reduces the number of vms that get booted by checking once at the beginning of a run in the request phase
=> ci: Shift (Docker) cache priming to request workflow

contrib/vcl/source/vcl_io_handle.cc, contrib/vcl/source/vcl_io_handle.h, envoy/network/io_handle.h, source/common/network/io_socket_handle_base_impl.cc, source/common/network/io_socket_handle_base_impl.h, source/common/network/socket_impl.cc, source/common/network/tcp_listener_impl.cc, source/common/network/utility.cc, source/common/quic/quic_io_handle_wrapper.h, source/extensions/io_socket/user_space/io_handle_impl.cc, source/extensions/io_socket/user_space/io_handle_impl.h, test/common/network/io_uring_socket_handle_impl_integration_test.cc, test/common/quic/quic_io_handle_wrapper_test.cc, test/extensions/io_socket/user_space/connection_compatbility_test.cc, test/extensions/io_socket/user_space/io_handle_impl_test.cc, test/integration/filters/test_socket_interface.h, test/integration/socket_interface_swap.h, test/mocks/network/io_handle.h
unlike most exception PRs this includes a functional change to how Envoy handles completely invalid sockets or failed system calls.  Errors should be connection-local rather than throwing to whatever might catch, so it should be a whole sale improvement and is unlikely to affect anyone whose syscalls work.
=> socket: removing some exceptions

contrib/postgres_proxy/filters/network/source/postgres_message.h
Angle brackets are not required after constructor and, maybe, aren't even correct, though I'm not 100% sure on what the standard says on the matter.
It seems like clang is fine with this syntax, but when you try to build Envoy with gcc it complains:
```
./contrib/postgres_proxy/filters/network/source/postgres_message.h: At global scope:
./contrib/postgres_proxy/filters/network/source/postgres_message.h:397:14: error: expected unqualified-id before ')' token
397 |   Sequence<>() = default;
|              ^
Target //contrib/exe:envoy-static failed to build
```
Given that it's at least unusual to have angle brackets after constructor in a class template specialization let's remove them and satisfy both gcc and clang.
It's one of the issue that prevent …
=> [contrib][postgres] Remove <> after constructor in the PG proxy code

source/extensions/router/cluster_specifiers/lua/lua_cluster_specifier.h, test/extensions/router/cluster_specifiers/lua/lua_cluster_specifier_test.cc
Envoy would crash when the Lua garbage collector ran if `getCluster()` had been called.
This was added in #36998
=> lua cluster_specifier: fix crash in getCluster()

docs/root/start/install.rst
On more recent Debian/Ubuntu versions, not specifying the `arch` gives a warning like this:
```
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://apt.envoyproxy.io jammy InRelease' doesn't support architecture 'i386'
```
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Add `arch` to APT repository configuration

changelogs/current.yaml
This PR fixes a very small typo in the change logs for RBAC `metadata` deprecation line which is mistakenly spelled as `sourced_metadata`.
---
**Commit Message:** ****
**Additional Description:** Fixes a very small typo in the change logs for RBAC `metadata` deprecation line which is mistakenly spelled as `sourced_metadata`.
=> changelog: fix a small typo in rbac deprecation line

bazel/foreign_cc/vpp_vcl.patch, contrib/vcl/source/BUILD
There were a few issues with building Envoy with VCL. The fist issue is that vppinfra library is built with LTO enabled. While there is nothing wrong with enabling LTO, it apparently triggers some bug in GCC - during linking one of the LTO passes just consumes all the memory in the system and eventually crashes without finishing ( I tried to build Envoy on a system with 256GiB of memory and it wasn't enough, so it's way past what is reasonable).
To workaround the issue I updated vpp_vcl.patch to conditionally disable LTO when building using GCC.
Once LTO was disabled I hit another issue - the order of libraries in linker command line does matter, at least in the world of Unix-like systems.
Normally, Bazel can figure out the right order, but with VPP static libraries that …
=> [contrib][vcl] Fix VCL builds with GCC

changelogs/current.yaml, changelogs/summary.md, docs/root/configuration/observability/access_log/usage.rst, source/common/formatter/stream_info_formatter.cc, source/common/formatter/stream_info_formatter.h, test/common/formatter/substitution_formatter_test.cc
Commit Message: Added support for upstream connection establishment time points in the COMMON_DURATION access log operator. 
Testing: Unit
Docs Changes: Added reference to new supported time points in access log docs. 
=> access log: support upstream connect timing in COMMON_DURATION

envoy/common/exception.h
=> exceptions: Make THROW_OR_RETURN_VALUE work outside the "Envoy" namespace

source/extensions/filters/common/lua/lua.h, test/extensions/router/cluster_specifiers/lua/lua_cluster_specifier_test.cc
When Lua scripts called `getCluster` multiple times, earlier Lua references could become invalidated.
This was because the references were stored in a vector, and when the vector is resized, the references were copied (not moved), and the destructor of the old reference would mark the lua object as dead.
Testing: Added tests
Release Notes: none-this feature is only three days old
=> lua cluster_specifier: fix lua reference for multiple clusters

test/common/router/config_impl_speed_test.cc
This PR adds two new benchmarks to evaluate the performance of route matching using the new [matcher tree](https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/matcher.proto#xds-type-matcher-v3-matcher-matchertree) functionality:
1. `bmRouteTableSizeWithMatcherTree` - Tests [exact matching](https://arc.net/l/quote/arnhgeme) using matcher tree
2. `bmRouteTableSizeWithPrefixMatcherTree` - Tests [prefix matching](https://arc.net/l/quote/kajwgisw) using matcher tree with nested routes
These benchmarks follow the same pattern as existing route matching benchmarks, testing performance with varying table sizes from **1** to **2^13** routes. The prefix matcher benchmark creates a hierarchical structure with shelves containing multiple routes, similar to real-world use cases.
``` …
```
=> benchmark: add route matcher benchmarks for exact and prefix match

source/common/http/http2/codec_impl.cc, source/common/http/http2/codec_impl.h, source/common/runtime/runtime_features.cc, test/common/http/http2/codec_impl_test.cc
Commit Message: removes `envoy.reloadable_features.http2_use_visitor_for_data`
Docs Changes:
Release Notes:
=> http2: removes the false path for an old runtime feature

test/extensions/config_subscription/grpc/xds_failover_integration_test.cc, test/integration/ads_integration_test.cc
Commit Message: tests: use makeOptRef to create an OptRef object
C++17 attempts to enforce explicit deduction rules, so prior code fails in newer builds with the following error:
```
error: 'OptRef' may not intend to support class template argument deduction [-Werror,-Wctad-maybe-unsupported]
```
This PR changes the tests code to use `makeOptRef()` insted of letting `OptRef()` deduce the types.
Testing: N/A
=> tests: use makeOptRef to create an OptRef object

.bazelrc, .github/workflows/_check_build.yml, .github/workflows/_check_coverage.yml, .github/workflows/_check_san.yml, .github/workflows/_precheck_deps.yml, .github/workflows/_precheck_format.yml, .github/workflows/_precheck_publish.yml, .github/workflows/_publish_build.yml, .github/workflows/_publish_publish.yml, .github/workflows/_publish_verify.yml, .github/workflows/_request.yml, .github/workflows/_request_cache.yml, .github/workflows/_request_cache_bazel.yml, .github/workflows/_run.yml, .github/workflows/envoy-checks.yml, .github/workflows/envoy-prechecks.yml, .github/workflows/envoy-publish.yml, .github/workflows/request.yml
This readds bazel client caching which was lost in migration
It should resolve the issue of failing downloads (kafka/node) in build tests - if for some reason it doesnt initially, we can tweak to ensure it does
I gave up on trying to use the github actions cache as its too size-constrained so it was never going to work - so instead it uses a GCS bucket. 
The connection to GCP seems a bit slower than the github cache, but the implementation is faster so overall caching seems to be faster with GCS.
The time required to restore caches is easily offset by speedups in actual jobs - so adding this should be an optimization
Unlike the previous system it always caches against the target branch (`main`/`release/*`)  and ignores any changes in a PR
It also creates one cache per arch and not …
=> ci: Add bazel client caching

api/envoy/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.proto, changelogs/current.yaml, source/extensions/network/dns_resolver/cares/dns_impl.cc, source/extensions/network/dns_resolver/cares/dns_impl.h, test/extensions/network/dns_resolver/cares/dns_impl_test.cc
This PR adds support for [configuring round-robin nameserver selection](https://arc.net/l/quote/zjajnycz) in the c-ares DNS resolver. When enabled, this will rotate through the configured nameservers for each resolution request, helping to distribute query load across multiple nameservers.
---
**Commit Message:** dns: add round-robin nameserver rotation option to c-ares resolver
**Additional Description:**
This change adds a new `rotate_nameservers` option to the c-ares DNS resolver config proto. When enabled, Envoy will use round-robin selection of nameservers for DNS resolution, rather than always using them in configured order. This matches c-ares' native `ARES_OPT_ROTATE` and `ARES_OPT_NOROTATE` options.
The feature allows better load distribution across multiple nameservers without …
=> dns: add round-robin nameserver rotation option to c-ares resolver

api/envoy/config/cluster/v3/cluster.proto, changelogs/current.yaml, source/extensions/clusters/logical_dns/logical_dns_cluster.cc, source/extensions/clusters/strict_dns/strict_dns_cluster.cc, test/common/upstream/upstream_impl_test.cc, test/extensions/clusters/logical_dns/logical_dns_cluster_test.cc
Commit Message: Take absolute values when doing DNS jitter.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue] #36943
In response to #36943. Jitter is generated by taking a random value from the random generator and creating a std::chrono::millisecond.
Since the random value is a uint64, I figured that the resulting std::chrono::millisecond would have to be positive.
However, std::chrono::millisecond uses a int64 under the hood, so large random values were being converted to negative numbers.
For example, if the random generator …
=> Take absolute values when doing DNS jitter.

envoy/http/http_server_properties_cache.h, source/common/http/conn_pool_grid.cc, source/common/http/http_server_properties_cache_impl.cc, source/common/http/http_server_properties_cache_impl.h, source/common/runtime/runtime_features.cc, test/common/http/http_server_properties_cache_impl_test.cc, test/mocks/http/http_server_properties_cache.h
Commit Message: Check canonical suffix when checking checking QUIC brokenness
Risk Level: low. protected by default false runtime guard
Runtime guard: envoy_reloadable_features_use_canonical_suffix_for_quic_broken
=> [quic]Check canonical suffix when checking checking QUIC brokenness

source/extensions/filters/common/expr/context.cc, source/extensions/filters/common/expr/context.h, test/extensions/filters/common/expr/BUILD, test/extensions/filters/common/expr/context_test.cc, test/extensions/filters/common/expr/expr_context_speed_test.cc
This PR optimizes the CEL expression context implementation by replacing `if-else` chains with hash maps for `O(1)` lookups and improving memory management. This would enhance the performance for header and filter state access patterns while maintaining the same functionality.
This change introduces constant-time lookups using `absl::flat_hash_map` and improves the overall design through static initialization of lookup maps for better performance.
```
Run on (32 X 3364.47 MHz CPU s)
CPU Caches:
L1 Data 48 KiB (x16)
L1 Instruction 32 KiB (x16)
L2 Unified 2048 KiB (x16)
L3 Unified 107520 KiB (x1)
Load Average: 9.07, 16.88, 15.22
-------------------------------------------------------------------------
Benchmark                               Time             CPU   Iterations …
```
=> filters: optimize cel expression context with constant-time lookups

changelogs/current.yaml, docs/root/configuration/observability/access_log/usage.rst, source/common/formatter/stream_info_formatter.cc, source/common/http/header_utility.cc, source/common/http/header_utility.h, test/common/formatter/substitution_formatter_test.cc
Resolve #37095 
Commit Message: add UPSTREAM_HOST_NAME_WITHOUT_PORT variable for access log
Additional Description: when using Dynamic Forward Proxy cluster in addition to Strict DNS clusters, the UPSTREAM_HOST_NAME variable returns inconsistent value in access log:
For Strict DNS cluster: We're getting the DNS name only as expected.
For Dynamic Forward Proxy cluster: We're getting the DNS name with the port value.
Testing: unit
=> access_log: add UPSTREAM_HOST_NAME_WITHOUT_PORT variable

mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h, mobile/library/common/network/apple_proxy_resolution.cc, mobile/library/common/network/apple_proxy_resolution.h, mobile/library/common/network/apple_proxy_resolver.cc, mobile/library/common/network/apple_proxy_resolver.h, mobile/library/common/network/apple_system_proxy_settings_monitor.cc, mobile/library/common/network/apple_system_proxy_settings_monitor.h, mobile/library/objective-c/EnvoyEngineImpl.mm, mobile/test/common/proxy/test_apple_proxy_settings_monitor.cc
The default is set to 10 seconds, the same value Cronet uses.
=> mobile: Make the Apple proxy settings monitor refresh interval configurable

source/extensions/filters/common/expr/context.cc, test/extensions/filters/common/expr/context_test.cc
We recently refactored the CEL context expression logic in [this](https://github.com/envoyproxy/envoy/pull/37057) PR and as part of this refactoring the `Size` extractor's behavior got slightly changed to return the `bytes` when the `content-length` header exists but is invalid. 
This PR is to revert back to the original behavior of not returning anything in that case.
---
**Commit Message:** filters: revert to original behavior for invalid content-length handling in CEL Size extractor
**Additional Description:** This PR reverts back to the original behavior of the **Size** extractor when we have `content-length` header present but it's invalid.
=> filters: revert to original behavior for invalid content-length handling in CEL Size extractor

.bazelrc, bazel/envoy_internal.bzl
Currently contrib does not build with GCC because of various false positive compiler warnings turned to errors and a GCC compiler bug.
Let's first start with the bug, in GCC apparently
using -gsplit-dwarf (debug fission) and -fdebug-types-section (used to optimize the size of debug inforamtion), when used together, can result in a linker failure.
Refer to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110885 for the GCC bug report of this issue. When it comes to Envoy, optimized builds with GCC are affected on at least GCC 11 (used by --config=docker-gcc) and GCC 12 (and I'm pretty sure the bug isn't fixed in any newer versions either, though I didn't check each version).
Given that we cannot have both debug fission and a debug types section, we decided to abandon the debug …
=> [contrib] Disable GCC warnings and broken features

source/common/router/header_parser.cc
Commit Message: router: pre-reserve header_parser vectors by their sizes
Modifying HeaderParser creation to pre-reserve vectors sizes.
Small perf nit in the router ingestion.
Testing: N/A
=> router: pre-reserve header_parser vectors by their sizes

source/common/filesystem/inotify/watcher_impl.cc
Commit Message: update the inotify critical assertion message to provide more accurate feedback
Additional Description: If inotify fails to watch additional file descriptors the solution is usually a combination of setting max_user_instances as well as max_user_watches (from personal experience). In addition, it seems like the original message had `user` and `inotify` inverted by accident? 
Testing: -
Docs Changes: -
Release Notes: -
Platform Specific Features: -
=> doc: update inotify assertion to provide more accurate feedback

test/integration/quic_http_integration_test.cc
quic: Use MaybeSendRstStreamFrame instead of ResetWriteSide in a quic test
ResetWriteSide is deprecated and will be removed once this usage of it is removed.
Risk Level: None - test only
Testing: existing unit test
=> quic: Use MaybeSendRstStreamFrame instead of ResetWriteSide in a quic test

test/extensions/transport_sockets/http_11_proxy/connect_integration_test.cc, test/integration/fake_upstream.cc, test/integration/fake_upstream.h
Currently waitForInexactRawData is harded coded to support only 4 byte data as input. It's because the only callsite passes "\r\n\r\n".
Extend to support data of any length.
Also slightly adjust the signature.
Risk Level: LOW, test only
Testing: bazel test test/extensions/transport_sockets/http_11_proxy/...
Docs Changes:
Release Notes:
=> test: extend waitForInexactRawData

changelogs/current.yaml, source/extensions/http/original_ip_detection/custom_header/custom_header.cc, test/extensions/http/original_ip_detection/custom_header/custom_header_test.cc
This PR restores the original behavior prior to #31831, by explicitly setting `skip_xff_append` to `true`, as appending the `XFF` header from the custom header extension is not required.
See #37171 for more details.
---
**Commit Message:** original_ip_detection: revert unintended XFF header appending behavior in CustomHeaderIPDetection
**Additional Description:** This PR restores the pre #31831 behavior by explicitly setting `skip_xff_append` to `true`, as appending the `XFF` header from the custom header extension is not required.
=> original_ip_detection: revert unintended XFF header appending behavior in CustomHeaderIPDetection

changelogs/current.yaml, source/extensions/http/original_ip_detection/custom_header/custom_header.cc, test/extensions/http/original_ip_detection/custom_header/custom_header_test.cc
This PR restores the original behavior prior to #31831, by explicitly setting `skip_xff_append` to `true`, as appending the `XFF` header from the custom header extension is not required.
See #37171 for more details.
---
**Commit Message:** original_ip_detection: revert unintended XFF header appending behavior in CustomHeaderIPDetection
**Additional Description:** This PR restores the pre #31831 behavior by explicitly setting `skip_xff_append` to `true`, as appending the `XFF` header from the custom header extension is not required.
=> bp/1.32: original_ip_detection: revert unintended XFF header appending behavior in CustomHeaderIPDetection

source/common/protobuf/utility.cc, source/common/protobuf/utility.h, source/extensions/common/tap/admin.h, source/extensions/common/tap/extension_config_base.cc, source/extensions/common/tap/tap_config_base.cc, tools/code_format/config.yaml
=> proto: moving a utility to the one call location

CODEOWNERS
Commit Message: Add bsurber as a codeowner for the rate_limit_quota http extension
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Update rate_limit_quota CODEOWNERS

source/common/formatter/stream_info_formatter.cc
followup of https://github.com/envoyproxy/envoy/pull/36920
formatting source/common/formatter/stream_info_formatter.cc
Commit Message: stream_info_formatter.cc format file
Testing: no
Release Notes:
=> stream_info_formatter.cc format file

changelogs/current.yaml, source/common/upstream/load_stats_reporter.cc, source/common/upstream/load_stats_reporter.h, test/common/upstream/load_stats_reporter_test.cc
Reopening [this PR](https://github.com/envoyproxy/envoy/pull/35941)
Currently, we treat all remote grpc stream closes as errors, and log warnings and increment failure metrics for every instance. A remote grpc stream close with a 0 code is not a failure, but instead a graceful termination, so it should be a lower log level and should not increment failure metrics.
Testing:
Docs Changes:
Release Notes:
=> Change handling of graceful case of LoadStatsReporting onRemoteClose

source/common/tls/cert_validator/default_validator.cc, source/common/tls/cert_validator/san_matcher.cc, source/common/tls/cert_validator/san_matcher.h, test/common/tls/cert_validator/default_validator_test.cc
Commit Message: SAN-matcher: refactoring DNS exact SAN matcher out of regular matchers
The current SAN-matcher has a specific matching behavior when the matching general-type is DNS and the matcher-type is Exact.
This PR refactors that behavior into a different class `DnsStringSanMatcher` and ensures that when the code creates a SAN-Matcher the correct class is used.
Risk Level: low - internal refactor only
Testing: Updated tests.
=> SAN-matcher: refactoring DNS exact SAN matcher out of regular matchers

envoy/common/execution_context.h
Make `ScopedExecutionContext` no-op if `!ExecutionContext::isEnabled()`.
This saves a call to `ScopeTrackedObject::trackedStream()` when execution context is disabled.
Commit Message: Make ScopedExecutionContext no-op if !ExecutionContext::isEnabled().
Risk Level: None.
Testing: Existing execution_context_test.cc.
=> Make ScopedExecutionContext no-op if !ExecutionContext::isEnabled().

changelogs/current.yaml, source/extensions/tracers/opentelemetry/samplers/dynatrace/sampling_controller.cc, test/extensions/tracers/opentelemetry/samplers/dynatrace/sampling_controller_test.cc
Commit Message: Backport #37240
[Optional Fixes #37199]
=> [bp/1.30] opentelemetrytracer: limit calculated sampling exponent in Dynatrace sampler

changelogs/current.yaml, source/extensions/tracers/opentelemetry/samplers/dynatrace/sampling_controller.cc, test/extensions/tracers/opentelemetry/samplers/dynatrace/sampling_controller_test.cc
Commit Message: Backport #37240
[Optional Fixes #37199]
=> [bp/1.31] opentelemetrytracer: limit calculated sampling exponent in Dynatrace sampler

changelogs/current.yaml, source/extensions/tracers/opentelemetry/samplers/dynatrace/sampling_controller.cc, test/extensions/tracers/opentelemetry/samplers/dynatrace/sampling_controller_test.cc
Commit Message: Backport #37240
[Optional Fixes #37199]
=> [bp/1.32] opentelemetrytracer: limit calculated sampling exponent in Dynatrace sampler

source/common/upstream/cluster_manager_impl.cc, source/common/upstream/outlier_detection_impl.h, test/common/upstream/outlier_detection_impl_test.cc, tools/code_format/config.yaml
=> outlier: removing exceptions

source/extensions/dynamic_modules/abi.h, source/extensions/dynamic_modules/abi_version.h, source/extensions/dynamic_modules/dynamic_modules.cc, source/extensions/dynamic_modules/dynamic_modules.h, source/extensions/dynamic_modules/sdk/rust/src/lib.rs, source/extensions/filters/http/dynamic_modules/factory.cc, source/extensions/filters/http/dynamic_modules/filter_config.cc, source/extensions/filters/http/dynamic_modules/filter_config.h, test/extensions/dynamic_modules/BUILD, test/extensions/dynamic_modules/dynamic_modules_test.cc, test/extensions/dynamic_modules/http/BUILD, test/extensions/dynamic_modules/http/factory_test.cc, test/extensions/dynamic_modules/http/filter_test.cc, test/extensions/dynamic_modules/test_data/c/BUILD, test/extensions/dynamic_modules/test_data/c/abi_version_mismatch.c, test/extensions/dynamic_modules/test_data/c/no_http_config_destory.c, test/extensions/dynamic_modules/test_data/c/no_http_config_new.c, test/extensions/dynamic_modules/test_data/c/no_op.c, test/extensions/dynamic_modules/test_data/c/program_init_fail.c, test/extensions/dynamic_modules/test_data/rust/no_op.rs
Commit Message: dynamic_modules: HTTP filter config implementation
This expands the ABI for HTTP filter configurations. Especially this adds two
even hooks coupled with the life cycle of HTTP filter config handled in the main
thread.
The key idea is to do the direct pointer (context) passing between the boundary;
This allows us to avoid maintaining IDs and global mapping state, which makes it 
easier to test as well as it has benefit in terms of performance. E.g. there's no 
need to look up "contexts" on each event hook entry.
The next follow-up PR will add per-stream event hooks (filter implementation).
After the event hooks are done, module->Envoy functions will be added (e.g.
accessing headers, etc.)
Testing: done
Release Notes: …
=> dynamic_modules: HTTP filter config implementation

source/common/json/json_internal.cc, test/common/json/json_loader_test.cc, test/common/router/header_parser_corpus/large_number_value
Commit Message: json: replacing IS_ENVOY_BUG when a large number value is used with an error
Followup to #36919. In #36919, there was a behavior change when the JSON library parsed a large number.
Prior to #36919 Envoy would have thrown an exception which ended up rejecting the value or erroring out. After that an ENVOY_BUG was introduced, but probably shouldn't have had, as Envoy may receive a value that is large and should handle it correctly (e.g., when ingesting a config).
This was detected due to fuzz bug [379811166](https://g-issues.oss-fuzz.com/issues/379811166).
Testing: Added fuzz test case, and updated the unit-tests.
Docs Changes: N/A (no docs were updated in the original PR).
Release Notes: N/A (no release notes were introduced in the …
=> json: replacing IS_ENVOY_BUG when a large number value is used with an error

contrib/golang/filters/network/source/upstream.h, contrib/golang/filters/network/test/upstream_test.cc, envoy/upstream/load_balancer.h, source/common/router/router.h, source/common/tcp_proxy/tcp_proxy.h, source/common/upstream/load_balancer_context_base.h, source/extensions/clusters/dynamic_forward_proxy/cluster.cc, source/extensions/clusters/original_dst/original_dst_cluster.cc, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h, source/extensions/load_balancing_policies/subset/subset_lb.h, test/common/http/async_client_impl_test.cc, test/common/upstream/BUILD, test/common/upstream/cluster_manager_impl_test.cc, test/common/upstream/metadata_writer_lb.proto, test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc, test/extensions/clusters/original_dst/original_dst_cluster_test.cc, test/integration/load_balancers/custom_lb_policy.h, test/mocks/upstream/load_balancer_context.h
We have uses cases where LB policies need to be able to write to request metadata when choosing or picking hosts. The metadata can be used in logging or by HTTP filters.
This PR makes access to the request stream info non `const`.
=> Grant LB policies write access to connection stream info

api/envoy/extensions/filters/http/stateful_session/v3/stateful_session.proto
This PR adds some clarification around the behavior when `strict` is not set for `stateful_session` filter.
---
**Commit Message:** docs: added more info for stateful_session filter params
**Additional Description:** Added some clarification around the behavior when `strict` is not set for `stateful_session` filter.
=> docs: added more info for stateful_session filter params

changelogs/current.yaml, docs/root/configuration/http/http_filters/lua_filter.rst, source/extensions/filters/http/lua/lua_filter.cc, source/extensions/filters/http/lua/lua_filter.h, test/extensions/filters/http/lua/lua_filter_test.cc, test/extensions/filters/http/lua/lua_integration_test.cc
Adds new functionality to Lua filter flor allowing overriding the upstream host address.
**Example:**
```lua
function envoy_on_request(request_handle)
request_handle:setUpstreamOverrideHost("192.168.21.11", true)
end
```
---
**Commit Message:** adds new function to the LUA script for setting upstream host override
**Additional Description:** The new `setUpstreamOverrideHost()` allows the dynamic upstream host override from Lua scripts.
**Testing:** Added Unit + Integration tests
=> lua: add new function to set upstream host override

source/common/common/logger.h
Commit Message: Adds logger id for dynamic_modules
This commit adds a logger_id for the core dynamic_modules extension.
* https://github.com/envoyproxy/envoy/tree/main/source/extensions/dynamic_modules
* https://github.com/envoyproxy/envoy/tree/main/source/extensions/filters/http/dynamic_modules
This is to mainly avoid unnecessarily requesting review from logger owners into
dynamic_modules PRs just for adding one line.
Testing: none
=> Adds logger id for dynamic_modules

.clang-tidy, source/extensions/dynamic_modules/abi.h, source/extensions/dynamic_modules/abi_version.h
Commit Message: dynamic_modules: dynamic_modules: exclude abi.h from clang-tidy
This commit disables clang-tidy for the whole ABI header which is a pure C file. 
Previously, I added `// NOLINT` comment line on each place, 
clang-tidy is only for C++ source code, so this disables it considering the 
readability. This shouldn't be a problem as the header only has types and 
function declarations.
Testing: n/a
=> dynamic_modules: exclude abi.h from clang-tidy

.devcontainer/setup.sh
Commit Message: Removes unnecessary RBE default config in .devcontainer/setup.sh
This removes the unnecessary default bazelrc configuration used in .devcontainer.
This was a cause of #23239 people asked about multiple times before.
cc @phlax 
Closes #23239
=> Removes setting `BAZEL_BUILD_EXTRA_OPTIONS` in .devcontainer/setup.sh

.clang-tidy
This directive was introduced in #37317 but turns out this is not available in LLVM 14.
So for now we remove this. By the time we enable clang-tidy on CI we should find
a way to ignore it, but for now simply remove it so that we can run clang-tidy locally.
cc @phlax
=> clang-tidy: removes ExcludeHeaderFilterRegex not available in LLVM 14

.clang-tidy
This adds `value_or` to the ignore-list of naming convention.
The similar `has_value` was already in the list and both are to
be aligned with their `absl::optional` counterparts.
cc @phlax
=> clang-tidy: ignore value_or used in optref helper

source/extensions/resource_monitors/cpu_utilization/cpu_utilization_monitor.cc, source/extensions/resource_monitors/cpu_utilization/cpu_utilization_monitor.h
part of  #28566
___
```
cpu_utilization_monitor.h:25:10: error: use default member initializer for 'utilization_' [modernize-use-default-member-init,-warnings-as-errors]
```
=> clang-tidy: default member error in cpu_utilization

source/extensions/dynamic_modules/abi.h, source/extensions/dynamic_modules/abi_version.h, source/extensions/dynamic_modules/sdk/rust/build.rs, test/extensions/dynamic_modules/test_data/c/no_http_config_destory.c, test/extensions/dynamic_modules/test_data/c/no_op.c
Commit Message: dynamic_modules: use size_t for length of buffers 
Previously, `int` was used for the length of buffer/string, which was
obviously a bug as its size is 16-bit and signed. `size_t` is usually 
used for expressing the memory buffer by a pair of pointer and the length,
so this commit switches to use it.
Testing: done
=> dynamic_modules: use `size_t` for length of buffers

envoy/http/filter.h, source/common/common/utility.cc
=> clang-tidy: fixes some uncaught errors

envoy/common/execution_context.h, source/common/common/cleanup.h, test/common/common/execution_context_test.cc
=> clang-tidy: fixes error in common::Cleanup class 

.clang-tidy
Previously, `redefining builtin macro [clang-diagnostic-builtin-macro-redefined,-warnings-as-errors]` was reported
despite the existence of the `-Wno-builtin-macro-redefined` in the compiler argument.
This is a known issue for older version of clang as in
* https://github.com/llvm/llvm-project/issues/56709
* https://github.com/erenon/bazel_clang_tidy/issues/29
The workaround discussed was to explicitly add `-clang-diagnostic-builtin-macro-redefined`
in the checks of clang-tidy, which can be removed after we upgrade to LLVM 17. 
part of #28566 
cc @phlax
=> clang-tidy: respect '-Wno-builtin-macro-redefined' with c++20

ci/do_ci.sh
=> ci/clang-tidy: make CLANG_TIDY_TARGETS configurable

changelogs/current.yaml, source/extensions/filters/http/csrf/csrf_filter.cc, test/extensions/filters/http/csrf/csrf_filter_test.cc
Requests with a missing source origin should increase only the counter "missing_source_origin" but not the counter "request_invalid".
Before this bugfix, the counter "request_invalid" was also increased, depending on the value of the "Host" or ":authority" header.
Risk Level: Low (only metrics affected)
Testing: With improved tests
=> csrf: increase only one counter per request

source/extensions/filters/http/ext_proc/client.h, source/extensions/filters/http/ext_proc/ext_proc.h, source/extensions/filters/http/ext_proc/http_client/http_client_impl.cc, source/extensions/filters/http/ext_proc/http_client/http_client_impl.h, source/extensions/filters/http/ext_proc/processor_state.cc, source/extensions/filters/http/ext_proc/processor_state.h, test/extensions/filters/http/ext_proc/filter_test.cc
=> clang-tidy: fixes errors in extproc

test/extensions/filters/http/ext_proc/config_test.cc
This PR adds some more tests to increase the coverage of the ExtProc directory. Another refactoring PR currently fails as the overall coverage of the ExtProc directory fell short of 0.1
**Before:**
**After:**
---
**Commit Message:** ext_proc: add more tests to increase coverage
**Additional Description:** Adds additional tests for ExtProc Config.
=> ext_proc: add more tests to increase coverage

envoy/config/config_provider_manager.h, envoy/network/socket_interface.h, envoy/router/route_config_provider_manager.h, source/common/router/scoped_rds.h
=> clang-tidy: fixes some errors

api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
I noticed some minor mistakes in ExtAuthZ's documentation where certain words are duplicated and inconsistent style is used for some words like `gRPC` (Also spelled GRPC and grpc). This PR is fixing these nits.
---
**Commit Message**: docs: correct some spelling mistakes and de-dupe words in ExtAuthZ
**Additional Description**: Fixing documentation nits for ExtAuthZ filter.
**Risk Level**: N/A
**Testing**: N/A
**Docs Changes**: N/A
**Release Notes**: N/A
=> docs: correct some spelling mistakes and de-dupe words in ExtAuthZ

bazel/external/http_parser/BUILD, bazel/external/quiche.BUILD
The header _should_ be provided in `hdrs` - not in `srcs`
=> bazel: Remove stray headers from srcs

source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.cc, test/extensions/filters/common/local_ratelimit/local_ratelimit_test.cc, test/extensions/filters/http/common/fuzz/filter_corpus/local_rate_limit_descriptor_small_fill_interval
Commit Message: local-rate-limit: add descriptor fill_interval lower bound
The local-rate-limit filter has a lower-bound fill_interval validation for the non-descriptor field.
This PR adds the same lower-bound to the fill_interval of a descriptor.
Note that this will reject previously valid configs that were under 50msec. In this case the config must change to be at least 50msec.
This was found by a [fuzz test](https://oss-fuzz.com/testcase-detail/5797822746656768).
Testing: Added fuzz test corpus
=> local-rate-limit: add descriptor fill_interval lower bound

source/extensions/filters/http/proto_message_extraction/extractor.h, source/extensions/filters/http/proto_message_extraction/extractor_impl.h, source/extensions/filters/http/proto_message_extraction/filter.cc
Commit Message: Clear any previously cached result in extractor
Additional Description:  The extractor is created per proto path. In case the of previously received proto path, clear any cached result from the extractor.
Testing: Covered by unit tests and integration tests
Docs Changes: Nil
Release Notes: Nil
Platform Specific Features: Nil
=> [PME filter] Clear any previously cached result in extractor

test/extensions/filters/http/ext_proc/client_test.cc
This PR adds some more tests to increase the coverage of the ExtProc directory.
**Before:**
**After:**
---
**Commit Message:** ext_proc: add unit tests for client_impl to increase coverage
**Additional Description:** Adds additional tests for client_impl in ExtProc.
=> ext_proc: add unit tests for client_impl to increase coverage

changelogs/current.yaml, source/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/proxy_filter.cc, source/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/proxy_filter.h, test/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/proxy_filter_test.cc
Commit Message: Fixed bug where dynamic_forward_proxy udp session filter disabled buffer in filter config instead of disabling buffer for the filter instance.
Testing: unit
=> dynamic_forward_proxy: bugfix for udp dynamic forward proxy filter when displaying buffer

envoy/http/header_map.h, envoy/http/metadata_interface.h, source/common/quic/platform/quiche_logging_impl.h, source/common/quic/platform/quiche_mem_slice_impl.h, source/common/quic/quic_io_handle_wrapper.h, source/common/upstream/edf_scheduler.h, source/common/upstream/wrsq_scheduler.h
This is for optimizing build speed.
=> Include iosfwd instead of iostream in headers

changelogs/current.yaml, contrib/golang/filters/http/source/golang_filter.h
This patch is provided by @doujiang24.
Commit Message: golang: avoid accessing deleted state
Additional Description: During Golang GC there will be envoyGoFilterHttpFinalize -> deferredDeleteRequest -> getDispatcher. Before this fix, the getDispatcher will use the occasional deleted decoder callback, which will cause a crash. After this fix, we won't touch the deleted callback anymore.
Testing: after 3 hours load testing, the Envoy with this fix is still running well. 
Docs Changes:
Release Notes:
Fixes #37225
=> golang: avoid accessing deleted decoder_callbacks

.github/workflows/mobile-ios_build.yml
This app runs on CI and sends a 5MB POST request to httpbin.org. The app is flaky on CI due to sending requests to httpbin.org, and the app itself doesn't add much value to CI, as there are already hello world apps that test iOS app functionality on CI.
Fixes #37485
=> mobile/ci: Remove the Swift async app CI job

.github/workflows/mobile-ios_build.yml
One test app is sufficient to run on CI and validate that an iOS app can be built and run on iOS platforms. The one app that will be used is //test/swift/apps/experimental:app. It includes various types of test filters for more comprehensive usage. The rest of the apps are deleted to reduce the burden on CI's macos runners.
=> mobile/ci: Remove more unneeded iOS test apps

envoy/network/BUILD, envoy/network/drain_decision.h
Signed-off-by: James Heppenstall [james.heppenstall@mongodb.com](mailto:james.heppenstall@mongodb.com)
Commit Message: build: explicitly include absl/status/status.h in drain decision interface
Additional Description: MongoDB develops a number of custom filters in a repository that consumes Envoy as a submodule. While upgrading to `v1.32`, we started noticing some test build failures related to `absl::Status` being undeclared in `envoy/network/drain_decision.h`. It looks like `absl/status/status.h` is being included transitively in this file and should instead be declared explicitly.
=> build: explicitly include absl/status/status.h in drain decision interface

.github/workflows/_publish_build.yml
This reverts commit 6a4608f4c66f1932c9aa64325bc592ac309c7ca4.
i added a better workaround that forces install of gsutil if it detects a buggy vm
=> Revert "github/ci: Workaround failing `gsutil` issue (#37480)"

source/common/network/io_socket_handle_impl.cc
Commit Message: quic: fix parsing of UDP_GRO and ECN socket options to also work in big endian platforms
Check the actual cms_len so that the entire value will be parsed.
Fixes:
//test/common/quic:active_quic_listener_test
//test/integration:quic_http_integration_test
on big endian platforms.
Platform Specific Features: 
=> quic: fix parsing of UDP_GRO and ECN socket options to also work in big endian platforms

source/common/tcp/async_tcp_client_impl.cc, source/common/tcp/async_tcp_client_impl.h
=> clang-tidy: fixes errors in common/tcp

changelogs/current.yaml, source/extensions/filters/http/csrf/csrf_filter.cc, test/extensions/filters/http/csrf/csrf_filter_test.cc
Treat requests that have an opaque origin like requests that have no origin information.
Additional Description: For more information about "Origin: null", see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin
Release Notes: in `changelogs/current.yaml`
=> csrf: Handle opaque origins correctly ("Origin: null")

source/common/router/config_impl.cc, test/extensions/filters/http/local_ratelimit/config_test.cc
Commit Message: perf: router config_impl move a shared pointer
Minor perf, and variable renaming.
Followup to #37498 - moving a shared pointer instead of copying it.
Risk Level: low - internal only
Testing: N/A
=> perf: router config_impl move a shared pointer

source/extensions/filters/http/ext_proc/client.h, source/extensions/filters/http/ext_proc/client_base.h, source/extensions/filters/http/ext_proc/client_impl.cc, source/extensions/filters/http/ext_proc/client_impl.h, source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, source/extensions/filters/http/ext_proc/http_client/http_client_impl.cc, source/extensions/filters/http/ext_proc/http_client/http_client_impl.h, source/extensions/filters/http/ext_proc/processor_state.cc, test/extensions/filters/http/ext_proc/client_test.cc, test/extensions/filters/http/ext_proc/http_client/BUILD, test/extensions/filters/http/ext_proc/http_client/ext_proc_http_integration_test.cc, test/extensions/filters/http/ext_proc/logging_test_filter.cc, test/extensions/filters/http/ext_proc/mock_server.h
This is a follow up PR of: https://github.com/envoyproxy/envoy/pull/35740.
This PR added the bytes tracking support for ext_proc http service, which basically is counting how many bytes are sent to and received from ext_proc HTTP service.
It takes the stream_info from the active HTTP request, and saved in the ext_proc filter. When the external processing completes, the bytes counters from the stream_info are retrieved and stored into the filter state.
The existing logging test filter is leveraged to test the byte counters in the filter state are correctly updated.
=> ext_proc http bytes tracking support

source/extensions/filters/common/lua/lua.h
=> clang-tidy: fixes errors in Lua filter

source/extensions/stat_sinks/common/statsd/statsd.cc, source/extensions/stat_sinks/common/statsd/statsd.h, source/extensions/stat_sinks/dog_statsd/config.cc, source/extensions/stat_sinks/dog_statsd/config.h, source/extensions/stat_sinks/graphite_statsd/config.cc, source/extensions/stat_sinks/graphite_statsd/config.h, source/extensions/stat_sinks/hystrix/config.cc, source/extensions/stat_sinks/hystrix/config.h, source/extensions/stat_sinks/metrics_service/config.cc, source/extensions/stat_sinks/metrics_service/config.h, source/extensions/stat_sinks/metrics_service/grpc_metrics_service_impl.cc, source/extensions/stat_sinks/open_telemetry/config.cc, source/extensions/stat_sinks/open_telemetry/config.h, source/extensions/stat_sinks/statsd/config.cc, source/extensions/stat_sinks/statsd/config.h, source/extensions/stat_sinks/wasm/config.cc, source/extensions/stat_sinks/wasm/config.h, source/server/configuration_impl.cc, source/server/configuration_impl.h, test/extensions/stats_sinks/common/statsd/statsd_test.cc, test/extensions/stats_sinks/dog_statsd/config_test.cc, test/extensions/stats_sinks/graphite_statsd/config_test.cc, test/extensions/stats_sinks/hystrix/config_test.cc, test/extensions/stats_sinks/open_telemetry/config_test.cc, test/extensions/stats_sinks/statsd/config_test.cc, test/extensions/stats_sinks/wasm/config_test.cc, test/server/server_test.cc, tools/code_format/config.yaml
Commit Message: Remove exceptions from stat_sinks
This removes the exclusion of stat_sinks extensions from the
allow-list of exceptions.
=> Remove exceptions from stat_sinks

mobile/bazel/envoy_mobile_repositories.bzl
This will unblock updating the version of `rules_java` we are using.
Testing: ci
=> sync mobile's rules_jvm_external with core envoy (4.5 → 6.4)

source/common/http/async_client_impl.h, source/common/http/sidestream_watermark.h, test/common/http/async_client_impl_test.cc, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Noticed some crashes internally, due to http asyncClient layer changes in https://github.com/envoyproxy/envoy/pull/35827
It is probably because http asyncClient is not ready (i.e., miss some changes) for sidestream flow control part 3 or has pre-existing bugs.
Disable it while it is under investigation.
=> Disable sidestream flow control 3

bazel/repositories.bzl, bazel/repository_locations.bzl, mobile/bazel/envoy_mobile_repositories.bzl
Protobuf 29.0+ depends on `rules_java`, so let's bring it into Envoy core, syncing what we import in core and mobile.
- switch to release download url
- drop `strip_prefix` since the new url doesn't have a prefix to strip.
- add `rules_java` to `bazel/repository_locations.bzl`
- add `rules_java` to `_com_google_protobuf()` in `bazel/repositories.bzl`
Testing: CI
=> Hoist `java_rules` into envoy

mobile/library/cc/engine.cc, mobile/library/cc/engine.h, mobile/library/common/engine_types.h, mobile/library/common/internal_engine.cc, mobile/library/common/internal_engine.h, mobile/library/common/network/connectivity_manager.cc, mobile/library/common/network/connectivity_manager.h, mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java, mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidNetworkMonitor.java, mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyEngine.java, mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java, mobile/library/java/io/envoyproxy/envoymobile/engine/types/EnvoyNetworkType.java, mobile/library/jni/jni_impl.cc, mobile/library/objective-c/EnvoyNetworkMonitor.mm, mobile/test/common/extensions/filters/http/network_configuration/network_configuration_filter_test.cc, mobile/test/common/integration/client_integration_test.cc, mobile/test/common/network/connectivity_manager_test.cc, mobile/test/java/io/envoyproxy/envoymobile/engine/AndroidNetworkMonitorTest.java, mobile/test/java/org/chromium/net/CronetHttp3Test.java, mobile/test/kotlin/io/envoyproxy/envoymobile/mocks/MockEnvoyEngine.kt
Commit Message: Convert network type from enum to bitmap so that compound network type can be represented
Additional Description: One example is a network can be both VPN and WLAN.
=> [mobile]Convert network type from enum to bitmap so that compound network type can be represented

source/common/formatter/substitution_formatter.h, source/common/protobuf/utility.cc, source/common/protobuf/utility.h
Commit Message: sub-formatter: change string data member to bool
A couple of objects have a data member of string type, that could be of type bool.
Converting them to a bool type should reserve some memory that is allocated for each instantiated object.
Risk Level: low - internal refactor
Testing: N/A
=> sub-formatter: change string data member to bool

source/common/upstream/cluster_manager_impl.cc
The reason that client request can't find the on-demand cluster can be:
1. the on-demand request is not triggered
2. the requested cluster is not found
3. the request timed out
In the previous situation, the log level of failure reason 2/3 is 'debug', which is too low that we can't distinguish the reason via log. This change increases the log level so that user can troubleshoot the issue directly.
Commit Message: odcds: log abnormal message in higher level
Risk Level: Low, only log level changed
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md) …
=> odcds: log abnormal message in higher level

api/envoy/extensions/transport_sockets/tls/v3/tls.proto
I noticed that some of the sections of the TLS Context docs are very verbose and hard to read. This PR is to make it a little bit more user-friendly.
---
**Commit Message:** docs: refactor TLS Context docs to make it more reader friendly
**Additional Description:** Refining the TLS context docs to make it more user-friendly.
=> docs: refactor TLS Context docs to make it more reader friendly

source/extensions/extensions_metadata.yaml
Additional Description: I believe it is stable now since we conduct a security review and improvement for dns filter like #18651 #20744 #22861 #17479 #34409 #34456 #34490 and so on
Testing:
Docs Changes:
Release Notes:
=> dns_filter: change dns filter to stable

source/extensions/filters/network/redis_proxy/conn_pool_impl.cc, test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc
Commit Message: redis cluster: remove unnecessary validation to the lb type
This validation is unnecessary becase if cluster provided lb is not used, the following check when loading cluster will failed directly.
```
if (!cluster_provided_lb && lb != nullptr) {
return absl::InvalidArgumentError(
fmt::format("cluster manager: cluster provided LB not specified but cluster "
"'{}' provided one. Check cluster documentation.",
cluster_info->name()));
}
```
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> redis cluster: remove unnecessary validation to the lb type

bazel/repositories.bzl, bazel/rules_foreign_cc.patch
When upstream `rules_foreign_cc` builds its own GNUMake, it injects bazel's default libraries into `LDFLAGS`, which causes trouble on Darwin in newer versions of Bazel that added `-lm` to the list of default libraries.
As explained nicely in https://github.com/bazel-contrib/rules_foreign_cc/issues/1227, Apple's libm re-exports a bunch of symbols and, due to linker argument order, clobbers some symbols from make itself. We don't need any of the default libraries in GNUMake, so disable the feature to link them.
Testing: CI
=> Patch rules_foreign_cc to not link bazel default libraries into GNUMake

source/common/common/token_bucket_impl.cc, source/common/common/token_bucket_impl.h, source/extensions/filters/http/rate_limit_quota/global_client_impl.cc, test/extensions/filters/http/rate_limit_quota/integration_test.cc
Commit Message: When replacing a token bucket with another in a rate_limit_quota filter's bucket cache, initialize the replacement in a partially filled state, based on the ratio of available and max tokens of the existing token bucket. 
Additional Description: This enables more frequent updates in RateLimitQuotaResponses when giving assignments for token buckets. Previously, updates to an assignment had a side effect of resetting the available tokens in the token bucket. This implementation doesn't perfectly account for asynchronous flows but is better than the current implementation.
Risk Level: Low - the AtomicTokenBucketImpl class isn't widely used yet & changes are minimal. The rate_limit_quota filter is still in development.
Testing: Integration testing
Docs Changes:
Release Notes: …
=> Initialize rate_limit_quota token buckets with a partial fill

test/common/stream_info/stream_info_impl_test.cc, tools/spelling/spelling_dictionary.txt
I'm not fully familiar with the background of the assertStreamInfoSize, but it appears that the purpose of this check is to make sure that changes to StreamInfoImpl aren't going to break setFromForRecreateStream or setFrom.
Ideally we would not rely on such a test and instead test setFromForRecreateStream functionality directly, but I understand that it might be difficult to come up with a good test that covers all the cases.
However, this test was apprently broken by
https://github.com/envoyproxy/envoy/pull/35650. This PR addedd a new field to the StreamInfoImpl changing the layout of the structure and with that the test.
Interestingly enough, the same PR actually updated StreamInfoImpl::setFrom function (which the test reminds us to do every time we change …
=> [stream info] [test] Fix broken StreamInfoImpl test

source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h, test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc
Commit Message: udp_proxy_filter: Fix crash when accepting dynamic cds for UDP. Fixes #34195.
Please see #34195 and #26206 for details. This change fixes a usage of cluster info resource after the udp cluster be destroyed. 
I've got an approval from envoy-security list for the fix.
Testing: mentioned in both tickets
Release Notes:
=> udp_proxy_filter: Fix crash when accepting dynamic cds for UDP. Fixes #34195.

source/common/quic/envoy_quic_server_stream.cc, source/common/quic/envoy_quic_server_stream.h, source/common/quic/quic_stats_gatherer.h, source/common/runtime/runtime_features.cc, test/integration/quic_http_integration_test.cc
Commit Message: defer the logging till either last byte ACKed or QuicStream::OnSoonToBeDestroyed() called.
Additional Description: OnSoonToBeDestroyed() is newly added to be called before stream object destruction. This is a better place than QuicStatsGatherer destructor to flush the log if the last byte hasn't been fully ACKed for whatever reason.
Risk Level: low, behind default-false feature.
Testing: integration tests passed
Runtime guard: guarded by existing runtime guard `envoy.reloadable_features.quic_defer_logging_to_ack_listener`
Fixes #29930 for real
=> quic: fix defer logging of request in Access log

test/common/upstream/cluster_manager_impl_test.cc
Commit Message: test: initialize creation_status
Initialize a value to clarify initial value.
Testing: N/A
=> test: initialize creation_status

api/bazel/cc_proto_descriptor_library/testdata/text_format_transcoder_test.cc
- In Protobuf v22 `RecordWarning()` and `RecordError()` have been introduced and `AddWarning()` and `AddError()` deprecated
- In Protobuf v26 `AddWarning()` and `AddError()` have been removed
=> Migrate from Add*() to Record*() set of methods

api/bazel/external_proto_deps.bzl, api/bazel/repositories.bzl, api/envoy/extensions/access_loggers/open_telemetry/v3/BUILD, source/extensions/access_loggers/open_telemetry/BUILD, source/extensions/stat_sinks/open_telemetry/BUILD, source/extensions/tracers/opentelemetry/BUILD, source/extensions/tracers/opentelemetry/samplers/BUILD, test/extensions/access_loggers/open_telemetry/BUILD
Align target names for opentelemetry-proto with [Bazel Central Registry](https://github.com/bazelbuild/bazel-central-registry/tree/main/modules/opentelemetry-proto).
This is a requirement for compatibility with Bzlmod.
=> Align target names for opentelemetry-proto with BCR

bazel/envoy_examples.patch, bazel/repositories.bzl, changelogs/current.yaml, source/extensions/filters/http/oauth2/filter.cc, source/extensions/filters/http/oauth2/filter.h, test/extensions/filters/http/oauth2/filter_test.cc, test/extensions/filters/http/oauth2/oauth_integration_test.cc
Commit Message: The current CSRF token in the OAuth2 filter state is a random string. This PR improved it by signing the random string with the HMAC secret, adding protection agains CSRF token forgery.
The new CSRF token is in the format of `<nonce>.<hmac(nonce)>`, which is the [Signed Double-Submit Cookie](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#signed-double-submit-cookie-recommended
) pattern recommended by OWASP.
Testing: Unit test and integration test
[Optional Fixes #37560]
[Optional [API …
=> OAuth2 filter: improve the csrf token with "Signed Double-Submit Cookie"

contrib/qat/compression/qatzip/compressor/source/config.cc
Commit Message: qat: stop qat device before qatzip process exit
The QAT device remains occupied after the qatzip process exits. qzClose() must be called to fix it.
Testing: n/a
=> qat: stop qat device before qatzip process exit

test/extensions/filters/http/ext_proc/mock_server.cc, test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_corpus/http_client
Commit Message: generalize ext proc mock client for http service configs
There's a fuzz bug caused by an http service being configured in the ext_proc filter.  This is because the mock client currently dereferences the stream parameter since it was written assuming the ext_proc was a grpc service. With the introduction of http services, the mock client can no longer blindly dereference the stream.
Testing: fixing fuzz test
=> ext_proc: generalize ext proc mock client for http service configs

source/extensions/filters/http/bandwidth_limit/bandwidth_limit.cc, source/extensions/filters/http/bandwidth_limit/bandwidth_limit.h, source/extensions/filters/http/bandwidth_limit/config.cc, source/extensions/filters/http/bandwidth_limit/config.h, test/extensions/filters/http/bandwidth_limit/config_test.cc, test/extensions/filters/http/bandwidth_limit/filter_test.cc, tools/code_format/config.yaml
Commit Message: bandwidth_limit: make exception free
Testing: done
=> bandwidth_limit: make exception free

source/common/common/scope_tracked_object_stack.h, test/common/common/BUILD, test/common/common/scope_tracked_object_stack_test.cc, test/test_common/utility.h
Implement ScopeTrackedObjectStack::trackedStream() to return tracked streaminfo in reverse order.
Commit Message: Implement ScopeTrackedObjectStack::trackedStream() to return tracked streaminfo in reverse order.
Testing:
Docs Changes:
Release Notes:
=> Implement ScopeTrackedObjectStack::trackedStream()

OWNERS.md
He's a trusted Envoy developer, has a fix to an embargo-reported bug, and is happy to help with setec work going forward
=> setec: adding Yanjun

source/common/http/http2/codec_impl.cc
Small logging change in H2 codec to also include the `stream_id` to track which stream has the remaining payload.
---
**Commit Message:** codec: add stream_id to H2 logs
**Additional Description:** Small logging change in H2 codec to also include the `stream_id` to track which stream has the remaining payload.
=> codec: add stream_id to H2 logs

source/extensions/filters/common/ratelimit_config/ratelimit_config.cc
Commit Message: rate limit config: use warn and pow2 for invalid hits addend
To simplify debugging.
Testing: n/a.
=> rate limit config: use warn and pow2 for invalid hits addend

test/integration/protocol_integration_test.cc
Making sure the connection is successful before disabling sockets
Also avoiding a quic blackhole race condition
@antoniovleonti this should address the internal flake bug you pointed me at
=> test: reducing flakes

changelogs/current.yaml
This is a follow up on #37548, and forgot to add
the release note in the PR.
=> release note: add item for apply_on_stream_done ratelimit API

changelogs/current.yaml, docs/root/intro/arch_overview/other_protocols/redis.rst, source/extensions/clusters/redis/redis_cluster_lb.cc, source/extensions/clusters/redis/redis_cluster_lb.h, source/extensions/filters/network/common/redis/supported_commands.h, source/extensions/filters/network/redis_proxy/command_splitter_impl.cc, source/extensions/filters/network/redis_proxy/command_splitter_impl.h, source/extensions/filters/network/redis_proxy/conn_pool.h, source/extensions/filters/network/redis_proxy/conn_pool_impl.cc, source/extensions/filters/network/redis_proxy/conn_pool_impl.h, test/extensions/clusters/redis/redis_cluster_lb_test.cc, test/extensions/filters/network/redis_proxy/command_splitter_impl_test.cc, test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc, test/extensions/filters/network/redis_proxy/mocks.h, test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc
This RP mainly improves the compatibility of redis proxy, improvement as follows:
* Add support for the select command, referring to the implementation of Apache KVRocks and Microsoft Garnet, simply returns OK.
* Add keys command support, send keys commands to each shard on the backend, and then merge the results.
* For unsupport commands, the return value is the same as Redis, because some clients judge this return value, for example, [Java lettuce client](https://github.com/redis/lettuce/blob/14de5b88f922581f996c3b3311cb253eb36b32db/src/main/java/io/lettuce/core/RedisHandshake.java#L328)
=> [redis_proxy] Add support for SELECT and KEYS

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Ext_Proc : Adding integration test with MxN streaming enabled in both directions
fixes issue: https://github.com/envoyproxy/envoy/issues/37770
=> Ext_Proc : Adding integration test with MxN streaming enabled in both directions

source/extensions/tracers/opentelemetry/grpc_trace_exporter.cc, source/extensions/tracers/opentelemetry/grpc_trace_exporter.h, source/extensions/tracers/opentelemetry/trace_exporter.h, test/extensions/tracers/opentelemetry/BUILD, test/extensions/tracers/opentelemetry/grpc_trace_exporter_integration_test.cc, test/extensions/tracers/opentelemetry/grpc_trace_exporter_test.cc, test/extensions/tracers/opentelemetry/opentelemetry_tracer_impl_test.cc
Commit Message: extensions: fix OTel GRPC trace exporter dropping spans
Fixes otel exporter dropping spans in some cases, for example:
- If, while waiting for a response to an export request, the span buffer is flushed again.
- If the span buffer is flushed after an upstream span ends, and there exists a corresponding downstream span, and the buffer is flushed again when the downstream span ends. This can be triggered by setting the `tracing.opentelemetry.min_flush_spans` runtime variable to `1`, or if the flush timer expires just after the upstream span ends. This is similar to the first case, but the specific order of http callbacks prevented the exporter client from ever being reset before the downstream request completed, if it was used to export spans after …
=> Fix OTel GRPC trace exporter dropping spans

changelogs/current.yaml, envoy/common/backoff_strategy.h, source/common/common/backoff_strategy.h, source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc, test/common/common/backoff_strategy_test.cc, test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc
Commit Message: fix a bug in the dns refresh rate of the dns cache
Additional Description: Fixed a bug where the DNS refresh rate was the DNS TTL instead of the configured dns_refresh_rate/dns_failure_refresh_rate when we failed to resolve the DNS query after a successful resolution.
=> dns_cache: fix a bug in the DNS refresh rate

api/envoy/config/accesslog/v3/accesslog.proto
This PR adds some more description around `use_independent_randomness` to make it more user-friendly and clarify other fields.
---
**Commit Message:** docs: clarify the docs on runtime_filter
**Additional Description:** Added some more description around `use_independent_randomness` to make it more user-friendly.
**Risk Level:** Very Low
=> docs: clarify the docs on runtime_filter

docs/root/configuration/observability/access_log/usage.rst
This PR adds a blurb on the usage of `%TLS_JA3_FINGERPRINT%` in access logs to log the recorded JA3 fingerprint from the TLS Inspector.
---
**Commit Message:** docs: add a blurb on the JA3 to access_logs
**Additional Description:** Adds a blurb on the usage of `%TLS_JA3_FINGERPRINT%` in access logs.
=> docs: add a blurb on the JA3 to access_logs

changelogs/current.yaml, source/common/rds/route_config_provider_manager.cc, source/common/rds/route_config_provider_manager.h, source/common/runtime/runtime_features.cc, test/common/router/rds_impl_test.cc, tools/spelling/spelling_dictionary.txt
Backport https://github.com/envoyproxy/envoy/pull/37180 to release 1.31
This is not a security fix, but affects certain users and requires expensive work-around.
Identical to backport to 1.32: #37749 
Testing: Added unit test
Runtime guard: Yes
=> backport to 1.31: rds: normalize rds provider's config before calculating hash (#37180)

api/envoy/extensions/common/aws/v3/BUILD, api/envoy/extensions/common/aws/v3/credential_provider.proto, changelogs/current.yaml, docs/root/configuration/http/http_filters/_include/aws-request-signing-filter-credential-provider-config.yaml, docs/root/configuration/http/http_filters/_include/aws_credentials.rst, docs/root/configuration/http/http_filters/aws_request_signing_filter.rst, source/extensions/common/aws/BUILD, source/extensions/common/aws/credentials_provider_impl.cc, source/extensions/common/aws/credentials_provider_impl.h, source/extensions/common/aws/region_provider_impl.cc, source/extensions/common/aws/region_provider_impl.h, source/extensions/common/aws/utility.cc, source/extensions/common/aws/utility.h, source/extensions/filters/http/aws_lambda/config.cc, source/extensions/filters/http/aws_request_signing/config.cc, source/extensions/filters/http/aws_request_signing/config.h, test/extensions/common/aws/credentials_provider_impl_test.cc, test/extensions/common/aws/region_provider_impl_test.cc, test/extensions/common/aws/utility_test.cc, test/extensions/filters/http/aws_request_signing/config_test.cc
Commit Message: aws: update credential provider proto and support credential file reload
Additional Description: Allows for customisation of the credential provider settings, using the credential provider proto added in #36217
Testing: Unit
[Optional Fixes #Issue] Addresses #36769 and partially addresses #37432 
=> aws: update credential provider proto and support credential file reload

changelogs/current.yaml, source/common/rds/route_config_provider_manager.cc, source/common/rds/route_config_provider_manager.h, source/common/runtime/runtime_features.cc, test/common/router/rds_impl_test.cc, tools/spelling/spelling_dictionary.txt
Backport https://github.com/envoyproxy/envoy/pull/37180 to release 1.30
This is not a security fix, but affects certain users and requires expensive work-around.
Identical to backport to 1.32: https://github.com/envoyproxy/envoy/pull/37749
Testing: Added unit test
Runtime guard: Yes
=> backport to 1.30: rds: normalize rds provider's config before calculating hash (#37180)

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Adding ext_proc MxN test with ext_proc server send out-of-order response.
This is to address a left-over comments of the initial MxN PR: https://github.com/envoyproxy/envoy/pull/34942.
Fix: https://github.com/envoyproxy/envoy/issues/37064
=> Adding ext_proc MxN test with ext_proc server send out-of-order response

docs/root/api-docs/xds_protocol.rst
Commit Message: xDS docs: clarify that nonce is per-resource-type in ADS
Additional Description: Documentation fix.
Testing: N/A
CC @ejona86
=> xDS docs: clarify that nonce is per-resource-type in ADS

api/envoy/service/discovery/v3/discovery.proto, api/envoy/service/status/v3/csds.proto
Commit Message: xDS: add fields specified in xRFC TP3
Additional Description: See https://github.com/cncf/xds/blob/main/proposals/TP3-xds-error-propagation.md for details.
Testing: N/A
CC @adisuissa @anicr7
=> xDS: add fields specified in xRFC TP3

docs/root/intro/arch_overview/observability/access_logging.rst
This PR fixes some minor typos like `prediodic` => `periodic` and uses proper annotations for all the notes in the [access logging docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/access_logging).
[Preview Link](https://storage.googleapis.com/envoy-pr/28e8cf9/docs/intro/arch_overview/observability/access_logging.html)
---
**Commit Message:** docs: fix some typos and use proper note annotations in access logs docs
**Additional Description:** Fixes some minor typos and make notes use the proper annotations in Access Logging docs.
=> docs: fix some typos and use proper note annotations in access logs docs

source/common/http/async_client_impl.cc, source/common/http/async_client_impl.h, test/common/http/async_client_impl_test.cc
Commit Message: async-client: fix stream creation validation
PR #34323 added the use of status-or for the creation of the async-client stream.
This PR ensures that when the creation of the object is unsuccessful, an error will be returned.
Testing: Added a unit test
=> async-client: fix stream creation validation

api/envoy/admin/v3/config_dump_shared.proto
Commit Message: xDS: add enum specified in xRFC TP3 in the right place
Additional Description: In #37818, I incorrectly added this new value to the deprecated location for this enum, not the real location. :(
Testing: N/A
CC @adisuissa
=> xDS: add enum specified in xRFC TP3 in the right place

docs/root/intro/arch_overview/upstream/aggregate_cluster.rst
This PR tries to make the docs on [aggregate cluster](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/aggregate_cluster) a bit more reader friendly and also add some missing information like behavior of [Stateful Session](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/stateful_session_filter) when configured using the aggregate cluster(s).
---
**Commit Message:** docs: add some missing info to aggregated cluster docs
**Additional Description:** Add some missing information on aggregate cluster in docs.
=> docs: add some missing info to aggregated cluster docs

changelogs/current.yaml, source/extensions/tracers/opentelemetry/grpc_trace_exporter.cc, source/extensions/tracers/opentelemetry/http_trace_exporter.cc, source/extensions/tracers/opentelemetry/trace_exporter.h
Commit Message: Log (debug) the number of exported spans 
Adds a debug log message containing the number of (about to be) exported spans. This is helpful in troubleshooting for cases where the configuration looks "correct" but no spans are seen in the tracing back-end. The stats sink could be used, but that only exports via OTLP/gRPC which is not always possible. 
Testing: Manual and Unit tests
Docs Changes:
Release Notes:
=> opentelemetrytracer: Log (debug) the number of exported spans 

tools/code_format/check_format.py
Additional Description: In case a file does not end with a new line, the code format script will trim last character from last line, which will cause the file to be corrupted. To reproduce, for example, run the format tool on a bazel BUILD file that does not end with a new line
Testing: none
=> code_format: fix newline trim

tools/code_format/check_format.py
Commit Message: Adding an option to skip running build fixer script in case only linting is required
Testing: none
=> code_format: allow skipping build fixer

changelogs/current.yaml
This PR fixes some small typo in the change-logs. Some of the entries are not getting rendered properly due to missing backticks, etc.
For example,
---
**Commit Message:** docs: fix typos in the current changelogs
**Additional Description:** Fixes some small typo in the change-logs to render the entries properly.
=> docs: fix typos in the current changelogs

api/envoy/config/rbac/v3/rbac.proto
This PR fixes a small typo in the RBAC docs where the list is not being rendered properly due to missing newlines.
---
**Commit Message:** docs: fix small typo in RBAC docs
**Additional Description:** Fixes a small typo in the RABC docs to render the list on sourced metadata correctly.
=> docs: fix small typo in RBAC docs

api/envoy/admin/v3/config_dump_shared.proto
Commit Message: api: add TIMEOUT value to CSDS status enum
Additional Description: Also remove unnecessary `CLIENT_` prefix to the enum value added in #37858.  For context, see https://github.com/grpc/proposal/pull/466.
Testing: N/A
CC @adisuissa
=> api: add TIMEOUT value to CSDS status enum

source/extensions/dynamic_modules/sdk/rust/src/buffer.rs, source/extensions/dynamic_modules/sdk/rust/src/lib.rs
Commit Message: dynamic_modules: adds a lifetime param on EnvoyBuffer
This adds a lifetime parameter to `EnvoyBuffer` as well as 
to getter methods that return it. Since the data structure only holds 
a raw pointer and length, if a mutable setter method of EnvoyHttpFilter 
is used, it can be invalid. Previously it was relatively easy to write unsound logic
as there was no compile-time enforcement of invalidation.
This fixes the problem via life parameter and avoids making the EnvoyBuffer
variables outliving the next setter methods. For example, using the results returned 
by `get_request_trailers` _after_  `set_request_trailer` results in compilation
error:
```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for …
```
=> dynamic_modules: adds a lifetime param on EnvoyBuffer

source/extensions/dynamic_modules/BUILD, source/extensions/dynamic_modules/abi.h, source/extensions/dynamic_modules/abi_version.h, source/extensions/dynamic_modules/sdk/rust/src/lib.rs, source/extensions/filters/http/dynamic_modules/abi_impl.cc, source/extensions/filters/http/dynamic_modules/filter.h, test/extensions/dynamic_modules/http/abi_impl_test.cc, test/extensions/dynamic_modules/http/filter_test.cc, test/extensions/dynamic_modules/test_data/rust/http.rs
Commit Message: dynamic_modules: adds dynamic metadata callbakcs
This adds the following callbacks
* envoy_dynamic_module_callback_http_set_dynamic_metadata_number
* envoy_dynamic_module_callback_http_get_dynamic_metadata_number
* envoy_dynamic_module_callback_http_set_dynamic_metadata_string
* envoy_dynamic_module_callback_http_get_dynamic_metadata_string
for getting and setting basic dynamic metadata types from dynamic modules.
These callbacks are "typed" rather than accepting opaque "protobuf value".
The reason is that we discussed earlier that we shouldn't expose the protobuf
implementation detail at the ABI layer in order to avoid forcing all modules
to understand and bring in protobuf dependencies into their shared library.
More complex types can be added …
=> dynamic_modules: adds dynamic metadata callbakcs

source/extensions/filters/http/rate_limit_quota/config.cc, source/extensions/filters/http/rate_limit_quota/filter.cc, source/extensions/filters/http/rate_limit_quota/global_client_impl.cc, test/extensions/filters/http/rate_limit_quota/client_test.cc, test/extensions/filters/http/rate_limit_quota/client_test_utils.h, test/extensions/filters/http/rate_limit_quota/integration_test.cc
- Nit 1: Lambda capture for the RLQS filter factory callback should move shared_ptrs instead of copying. This only saves a shared_ptr copy op per var but is still good practice.
- Nit 2: Replace instances of if-conditions `(!ptr)` / `(ptr)`  with `(ptr == nullptr)` / `(ptr != nullptr)`  to conform to  existing code.
Risk Level: minimal
Testing: unit testing
Docs Changes:
Release Notes:
Fixes commit #37797
=> rlqs: address nits from PR #37797

source/common/network/BUILD, source/common/network/io_socket_handle_impl.cc, source/common/network/io_socket_handle_impl.h, source/common/quic/envoy_quic_utils.cc, test/common/network/BUILD, test/common/network/io_socket_handle_impl_benchmark_test.cc, test/common/network/io_socket_handle_impl_test.cc, test/test_common/network_utility.cc, test/test_common/network_utility.h
An LRU cache was introduced to cache `Envoy::Network::Address` instances because they are expensive to create. These addresses are cached for reading source and destination addresses from `recvmsg` and `recvmmsg` calls on QUIC UDP sockets. The current size of the cache is 4 entries for each IoHandle (i.e. each socket).
A locally run CPU profile of Envoy Mobile showed about 1.75% of CPU cycles going towards querying and inserting into the `quic::QuicLRUCache`.
Given the small number of elements in the cache, this commit uses a `std::vector` data structure instead of `QuicLRUCache`. `QuicLRUCache`, `std::vector`, and `std::deque` were compared using newly added benchmark tests, and the following were the results:
QuicLRUCache:
```
------------------------------------------------------------- …
```
=> network: More efficient caching for Envoy socket addresses

test/common/http/conn_manager_impl_corpus/maybe_end_decode, test/common/http/conn_manager_impl_fuzz_test.cc
Commit Message: fix hcm fuzz test case
This PR fixes a fuzzer issue caused by the fuzzer sending trailers to the HCM then calling continueDecoding (which then hits [this assertion](https://github.com/search?q=repo%3Aenvoyproxy%2Fenvoy%20ASSERT(!state_.decoder_filter_chain_complete_)%3B&type=code) in the HCM and fails). This PR adds a check to prevent this from happening.
Risk Level: none, test only
Testing: fuzz fix
=> fix hcm fuzz test case

source/extensions/dynamic_modules/BUILD, source/extensions/dynamic_modules/abi.h, source/extensions/dynamic_modules/abi_version.h, source/extensions/dynamic_modules/sdk/rust/src/lib.rs, source/extensions/filters/http/dynamic_modules/abi_impl.cc, source/extensions/filters/http/dynamic_modules/filter.h, test/extensions/dynamic_modules/http/abi_impl_test.cc, test/extensions/dynamic_modules/http/filter_test.cc, test/extensions/dynamic_modules/test_data/rust/http.rs
#37860 was reverted in #37896 because of the slight build fix
after #37880. This fixes the original commit.
=> Revert "Revert "dynamic_modules: adds dynamic metadata callbakcs"

docs/root/intro/arch_overview/upstream/aggregate_cluster.rst
This PR rewords the [example](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/aggregate_cluster#load-balancing-example) we have in the aggregate cluster to explain how the cluster level load balancer selects the cluster.
[Rendered Docs Link](https://storage.googleapis.com/envoy-pr/305d892/docs/intro/arch_overview/upstream/aggregate_cluster.html)
---
**Commit Message:** docs: reword the example in the aggregate cluster docs
**Additional Description:** Reword the example in aggregate cluster to make it more clear.
=> docs: reword the example in the aggregate cluster docs

mobile/library/common/engine_types.h, mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidNetworkMonitor.java, mobile/library/java/io/envoyproxy/envoymobile/engine/types/EnvoyNetworkType.java, mobile/test/java/io/envoyproxy/envoymobile/engine/AndroidNetworkMonitorTest.java
Commit Message: [mobile] Report network subtype when on cellular
Additional Description: Cellular networks will be further categorized as 2G/3G/4G/5G
Platform Specific Features: android only
=> [mobile] Report network subtype when on cellular

tools/repo/notify.py
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tools: making it clear when the ical code isn't working

api/envoy/extensions/filters/udp/udp_proxy/v3/udp_proxy.proto, changelogs/current.yaml, source/extensions/filters/udp/udp_proxy/config.cc, source/extensions/filters/udp/udp_proxy/config.h, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h, test/extensions/filters/udp/udp_proxy/mocks.h, test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc, test/integration/udp_tunneling_integration_test.cc
Commit Message: support backoff between retries in udp_proxy
Additional Description: This feature also fixes a bug in the retry mechanism in udp proxy in the following situation:
1. We are tunneling UDP over HTTP.
2. A new stream is created on existing upstream connection (multiplexing) and waiting for response headers.
3. The upstream connection is closed.
4. During the close process, all streams created on this connection will be reset.
5. The udp_proxy receives a callback on the stream reset.
6. They retry to connect.
7. The closed connection is picked as it is still in the connection pool (we are still in the process of the close).
8. The new stream that is created on the second attempt will be reset immediately.
9. The same process will happen (step 5 - step 8) until we reach the …
=> support backoff between retries in udp_proxy

mobile/.bazelrc
This  moves `--noincompatible_enable_android_toolchain_resolution` to `--config=mobile-android` so that it works on both local and remote builds.
Testing: CI
=> mobile: Move --noincompatible_enable_android_toolchain_resolution to mobile-android config

source/common/http/http2/codec_impl.cc
The library methods with a `DataFrameSource*` parameter were deprecated in https://github.com/google/quiche/commit/6e685764b0fe194610c04863f741b917ba47483d.
Commit Message: migrates away from deprecated methods
Docs Changes:
Release Notes:
=> http2: migrates away from deprecated methods

source/common/protobuf/create_reflectable_message.cc, source/common/protobuf/utility.cc
This makes the code compatible with a future Protobuf release where various methods return absl::string_view instead of std::string or const std::string&.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Replace string addition with absl::StrCat

test/common/config/config_provider_impl_test.cc, test/common/router/scoped_rds_test.cc
Commit Message: tests: remove unused protobuf repeated field variables
Removing unused vars from tests.
Testing: N/A
=> tests: remove unused protobuf repeated field variables

test/common/http/http2/codec_impl_test.cc
The only case where codec behavior differs is `\0`, so that case is still skipped.
UHV + oghttp2 is also skipped, as otherwise the `compile-time-options` build fails.
Risk Level: none, test only
Testing: ran codec_impl_test locally
Docs Changes:
Release Notes:
=> http2: updates test coverage for Http2CodecImplTest.CheckHeaderValueValidation

test/extensions/filters/http/oauth2/filter_test.cc
On newer version of Clang those generate a warning and with the settings we use ultimately result in a compilation failure.
We probably should either disable the warning or just adjust the test. Looking at the history of the test, it seems that these constants have never been used, so I prefer to just drop them.
It's related to #37911, it appears that the compiler warning that causes this test fail to compile on clang 18 didn't exist in clang 14 that we are currently using.
Testing: by running changed test
=> Drop unused constants to make newer versions of clang happy

source/extensions/filters/http/basic_auth/basic_auth_filter.cc, test/extensions/filters/http/common/fuzz/filter_corpus/build_original_uri, test/extensions/filters/http/common/fuzz/uber_filter.cc
Commit Message: check OptRef has_value before dereferencing
In the BasicAuthFilter there's a spot where an OptRef (`request_headers`) is dereferenced without checking `has_value` first. This is unlikely to cause production issues as that would require `decoder_callbacks_->requestHeaders()` to be unset. This does, however, crash the `filter_fuzz_test` since the mock callbacks object does not override that function call.
Testing: fuzz test fix
=> check OptRef has_value before dereferencing

mobile/test/common/logger/logger_delegate_test.cc
Internally we discovered an order-dependent test that will cause the test to fail because changing the log level is in `LogCbWithLevels` is global. The fix is to restore the log level in the `SetUp`.
=> mobile: Fix order-dependent //test/common/logger:logger_delegate_test 

.dockerignore, ci/Dockerfile-envoy, ci/do_ci.sh, docs/root/operations/tools/config_load_check_tool.rst
This change adds `config_load_check_tool` binary to `tools-*` image
Fixes https://github.com/envoyproxy/envoy/issues/37987
Risk Level:
Testing:
Docs Changes: Changes: update [doc](https://www.envoyproxy.io/docs/envoy/latest/operations/tools/config_load_check_tool) about availability in tools image.
Release Notes:
=> build: add config_load_check_tool to tools-* image

api/envoy/config/route/v3/route_components.proto
This PR fixes some mistakes in the RateLimit proto. The query param `skip_if_absent` description is reversed and the styling is off.
We do what's mentioned to be part of flag = `true` when the flag is actually `false` and vice-versa.
---
**Commit Message:** ratelimit: fix the RLS proto docs
**Additional Description:** Fix RateLimit proto docs.
=> ratelimit: fix the RLS proto docs

source/extensions/filters/http/ext_proc/processor_state.cc, test/extensions/filters/http/ext_proc/BUILD, test/extensions/filters/http/ext_proc/ext_proc_misc_test.cc, test/extensions/filters/http/ext_proc/filter_test.cc
Fixes: https://github.com/envoyproxy/envoy/issues/36119
The issue is due to ext_proc failed to send the last empty chunk with end_stream = true to the backend server. This ends up causing a copy of the data stored in the decoding buffer for the retry purpose are sent again, which caused duplicate data is sent to backend server. The fix is simply having the ext_proc filter inject the last empty chunk to the filter chain and send to the backend server.
=> Fix ext_proc duplicate data issue

mobile/library/cc/engine_builder.h
Prior to this PR, when `getaddrinfo` returns `EAI_AGAIN`, the code would retry the DNS indefinitely as can be seen in this CI failure: https://github.com/envoyproxy/envoy/actions/runs/12818760153/job/35744940259. This PR updates the default number of retries to 3.
Testing: CI
Platform Specific Features: android
=> mobile: Set the default DNS number of retries on Android to 3

api/envoy/extensions/upstreams/http/v3/http_protocol_options.proto
Commit Message: Remove incorrect/outdated doc for explicit_http_config
Additional Description: Per #38064, this docstring became incorrect with #14362 so should be removed.
Risk Level: None, doc-only.
Testing: n/a
Docs Changes: Yes it is.
=> Remove incorrect/outdated doc for explicit_http_config

mobile/library/common/network/BUILD, mobile/library/common/network/connectivity_manager.cc, mobile/library/common/network/network_type_socket_option_impl.cc, mobile/library/common/network/network_type_socket_option_impl.h, mobile/test/common/network/connectivity_manager_test.cc, source/common/runtime/runtime_features.cc
Commit Message: Create a real dummy socket option to manage network type hashing
Additional Description: The previous approach uses IP_TTL and it might cause unwanted behavior in production.
Runtime guard: envoy_reloadable_features_use_network_type_socket_option
=> [mobile]Create a real dummy socket option to manage network type hashing

bazel/repositories.bzl, bazel/tcmalloc.patch
I'm trying to build Envoy with Clang-18 and the version of tcmalloc we currently uses trips thread safety analysis, which generates a warning and ultimately results in a build failure.
The issue was fixed in the upstream tcmalloc, however the current version of binutils in the Envoy CI image not new enough to be able to build fresh versions of tcmalloc.
Given that we are already in a process of updating LLVM toolchain version in the Envoy CI, for now I'm going with patching tcmalloc instead of addressing all the issues required to bump the version of tcmalloc.
Additional Description: Related to the work in https://github.com/envoyproxy/envoy/issues/37911
Testing: built with clang-18, plus the usual CI tests
Platform …
=> Patch tcmalloc to fix the thread safety analysis warning

api/envoy/config/core/v3/protocol.proto, changelogs/current.yaml, source/common/http/http2/codec_impl.cc, source/common/http/http2/codec_impl.h, source/common/http/http2/metadata_decoder.cc, source/common/http/http2/metadata_decoder.h, test/common/http/http2/metadata_encoder_test.cc
Commit Message: Make the limit on HTTP/2 metadata configurable. Defaults to the current hardcoded value of 1 MiB.
Additional Description: The value can be configured through a new field on `Http2ProtocolOptions`
Testing: Adds a unit test that covers the new logic in MetadataDecoder
Docs Changes: Added to new proto field but kept hidden to be consistent with other H2 metadata configuration
=> Make the limit on HTTP/2 metadata that can be handled configurable

source/common/protobuf/utility.cc, test/extensions/string_matcher/lua/lua_test.cc
Commit Message: Reorder proto validation error message
Additional Description: As discussed in #38064, the error message is currently often hard to interpret due to the ordering being "high-level low-level high-level" rather than the usual high-to-low ordering error messages have, leading to confusing adjacencies. This is a minimal reordering that doesn't break tests and makes the error message easier to read, for example
`Proto constraint validation failed (HttpProtocolOptionsValidationError.ExplicitHttpConfig: embedded message failed validation | caused by field: "protocol_config", reason: is required): explicit_http_config`
becomes
`explicit_http_config: Proto constraint validation failed (HttpProtocolOptionsValidationError.ExplicitHttpConfig: embedded message failed validation | …
=> Reorder proto validation error message

test/extensions/common/wasm/wasm_test.cc
Commit Message: tests: update WasmCommonTest.DivByZero test for Emscripten 3.1.72
With newer (>=3.1.72) versions of Emscripten, division by zero in Wasm yields a value rather than generating a trap. Modify the WasmCommonTest.DivByZero test case to allow this behavior.
Risk Level: Low (testing-only change)
=> tests: update WasmCommonTest.DivByZero test for Emscripten 3.1.72

source/common/network/io_socket_handle_impl.cc, source/common/network/io_socket_handle_impl.h, source/common/quic/active_quic_listener.cc, source/common/quic/active_quic_listener.h, source/common/quic/envoy_quic_utils.cc, source/common/runtime/runtime_features.cc, test/common/quic/active_quic_listener_test.cc, test/common/quic/envoy_quic_client_session_test.cc
Commit Message: Deprecate envoy_reloadable_features_quic_receive_ecn
Testing: No new tests
[Optional Fixes #Issue] 38048
[Optional Deprecated:] envoy_reloadable_features_quic_receive_ecn
=> Deprecate quic_receive_ecn

api/envoy/config/core/v3/health_check.proto, api/envoy/extensions/filters/http/cors/v3/cors.proto, api/envoy/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto, docs/root/configuration/http/http_filters/compressor_filter.rst, docs/root/intro/arch_overview/upstream/connection_pooling.rst
Commit Message: Docs: Fix broken refs and attention blocks
ReStructuredText has a way to cross-reference sources using the :ref: syntax. It turns out that going over `/api/` (excluding `api/envoy/**/v2/*`) and `/docs` with regex `[^:]ref:` showed some hits, meaning the syntax was not parsed and the link was broken.
The same for the text blocks like `.. attention::`, the text to be highlighted needs to be indented with at least 2 spaces, otherwise the block is not interpreted, this was done using `\/\/\s+\.\.\s\w+::\n\s+\/\/(\s{0,1}\w)`
Docs Changes: 
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto.html#extensions-filters-network-tcp-proxy-v3-tcpproxy
- …
=> Docs: Fix broken refs and attention blocks

source/extensions/dynamic_modules/sdk/rust/src/lib.rs, source/extensions/dynamic_modules/sdk/rust/src/lib_test.rs, test/extensions/dynamic_modules/test_data/rust/http.rs, test/extensions/dynamic_modules/test_data/rust/http_test.rs, test/extensions/dynamic_modules/test_data/rust/no_op.rs
Commit Message: dynamic_modules: traitify EnvoyHttpFilterConfig to match EnvoyHttpFilter
In #37753, we made EnvoyHttpFilter as a trait for testability via mocks.
Even though there's no ABI methods for  EnvoyHttpFilterConfig, it will soon have 
a functionality like accessing metrics, per-filter-metadata etc. Then we will
need to make it as a trait just like we did EnvoyHttpFilter. 
Making it a trait changes multiple places, so this commit preemptively
does it to minimize the required change.
As a result, all callback accessing struct now will be hidden behind traits.
There's no functionality change in this commit.
=> dynamic_modules: traitify EnvoyHttpFilterConfig to match EnvoyHttpFilter

bazel/repository_locations.bzl, docs/root/intro/arch_overview/security/ssl.rst, source/common/crypto/utility_impl.cc, test/common/tls/ocsp/asn1_utility_test.cc
Commit Message: Update BoringSSL URLs from 'master' to 'main'
Testing: n/a
Docs Changes: updated URLs
=> Update BoringSSL URLs from 'master' to 'main'

bazel/foreign_cc/BUILD
The linker script generator that comes with the library is not quite correct and as a result sometimes generates symbols that are not exported by the library (see
https://github.com/confluentinc/librdkafka/issues/4593). Since LLVM version 17 it results in a link failure.
There is a fix sent upstream for this, but the PR fixing the issue has been out since October 2024 and didn't get any attention and I couldn't get maintainers of the library to look at the PR or the related bug either. So for now, I'm just disabling the use of linker script when building Kafka client library all together to work around the issue on our side.
I couldn't find the rationale for using custom linker script in the first place, but from what I can see in the upstream repo the linker script that …
=> Don't use generated linker script when build Kafka client library

api/envoy/config/cluster/v3/cluster.proto, source/extensions/extensions_metadata.yaml, tools/extensions/extensions_schema.yaml
Commit Message: Attempt to partially fix docgen for Cluster proto
Additional Description: `http_protocol_options` does not in fact work in `upstream_config`, it works in `typed_extension_protocol_options`. This PR changes the docgen behavior to reflect what actually works rather than being misleading. I don't know what else needs to be moved, I do know `upstream_config` only accepts four types, but the types I logged while debugging why `http_protocol_options` didn't work don't *clearly* map to the types in the tip at all so I'm not sure how to fix. It's clear `tcp.generic` doesn't belong, but I don't know where it should be moved to. This is, at least, a step in the right direction.
The set that does belong in `upstream_config` according to logging is:
``` …
```
=> Attempt to partially fix docgen for Cluster proto

source/common/router/upstream_request.cc, test/common/router/upstream_request_test.cc
Additional Description: upstream host info will be missing if it is triggered by downstream, e.g., idle timeout, this PR will add the upstream host info to the stream info when creating the upstream_request in router.
Testing:
Docs Changes:
Release Notes:
=> upstream: add host info when creating upstream request

mobile/library/java/org/chromium/net/impl/Errors.java, mobile/test/java/org/chromium/net/CronetHttp3Test.java, mobile/test/java/org/chromium/net/impl/ErrorsTest.java
This PR fixes the error mapping for the internet disconnection in Cronvoy to only check the network status instead of looking at the other errors because when the network is offline, the only logical error is `ERR_INTERNET_DISCONNECTED` irrespective of the other errors.
Platform Specific Features: android
=> mobile: Fix the internet disconnection error mapping

bazel/foreign_cc/BUILD
This should be turned off as it's not needed.
Ref https://github.com/Homebrew/homebrew-core/pull/205269
Fix #37470
=> deps: stop building libcurl docs

source/extensions/filters/common/ext_authz/ext_authz.h
I'm trying to make Envoy build with newer version of LLVM toolchain, specifically 18. I'm hitting a warning about missing initializers of the Request structure in tests when dedicated initializers are used to set values of some, but not all fields.
We can easily address this warning by just providing the default initializers in the struct definition. That's what this change does.
Additional Description: Related to work in #37911
Testing: `bazel build //test/extensions/filters/common/ext_authz:ext_authz_grpc_impl_test --config=clang-libc++` with clang-18
+cc @phlax
=> Fix missing initializer warning in ext_authz tests on newer version of clang

test/common/api/os_sys_calls_test.cc
supportsIpTransparent() and supportsMptcp() results depend on the OS being run on and the configuration of that OS, so remove the expectation of a specific value from the tests so that they'll pass in all environments.
Backport of https://github.com/envoyproxy/envoy/pull/36923
=> [bp/1.32] test: fix os_sys_calls_test in some less common environments

source/common/common/BUILD
Commit Message: swap out cidr_range_interface for ..._lib
Currently `//source/common/common:filter_state_object_matchers_lib` does not link `source/common/network/cidr_range.cc`. This PR fixes that.
Testing: none, quick build rule fix
=> swap out cidr_range_interface for ..._lib

changelogs/current.yaml, source/extensions/http/injected_credentials/oauth2/oauth_client.cc, test/extensions/http/credential_injector/oauth2/credential_injector_oauth_integration_test.cc
Current code inadvertently shadows the existing body declaration such that when scopes are specified, they are not actually sent to the authorization server.
Risk Level:
Testing:
Added test, verified it errors on current code and is resolved after this fix.
Docs Changes:
None, this now matches the existing documentation.
Release Notes:
Added CHANGELOG entry.
=> fix(credential_injector/oauth2): send scopes when specified

test/integration/BUILD, test/integration/filters/BUILD, test/integration/filters/async_upstream_filter.cc, test/integration/filters/async_upstream_filter.proto, test/integration/upstream_http_filter_integration_test.cc
Commit Message: Add integration test for upstream filters with AsyncClient
Additional Description: Behaviors were non-obvious to me and as far as I can tell there were no tests ensuring that the behavior is what it is; this adds a test for "AsyncClient bypasses router upstream filters but uses cluster upstream filters" and a test for "if both router and cluster upstream filters are set, router upstreams are ignored".
=> Add integration test for upstream filters with AsyncClient

source/extensions/filters/network/direct_response/config.cc, tools/code_format/config.yaml
Commit Message: Make direct_response exception free
Testing: existing one
=> Make direct_response exception free

source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc
Before this change, it was possible that the `addTrace(NotStarted)` occured after the resolver thread picked up the query and started work. This can be seen when running the getaddrinfo tests 1000 times in the form of failure around or just under 1% of the time.
```
bazel test --config=libc++ --runs_per_test 1000 //test/extensions/network/dns_resolver/getaddrinfo:getaddrinfo_test
```
Testing: CI
=> Add DNS query Trace of NotStarted before queuing.

test/extensions/filters/http/common/fuzz/uber_filter.cc
Commit Message: tests: update call to makeOptRef
This PR makes the cast more specific. It seems to be needed for future versions of googletest.
Testing: N/A
=> tests: update call to makeOptRef

source/common/stats/thread_local_store.cc, source/common/stats/thread_local_store.h
When I tried to build Envoy with Clang-18 I hit an issue that Clang thread safety analizer does not like the fact that we are returning a reference to a protected member (central_cache_) from centralCacheLockHeld method.
While I do think that the code is correct, when looking at the thread safety annotations I think we could do a little bit better.
Currently, centralCacheLockHeld is annotated with
ABLS_ASSERT_EXCLUSIVE_LOCK. My understanding is that this annotation should be used on functions that during runtime check that the right lock is held and fail if it's not the case. centralCacheLockHeld currently does not actually check that the lock is held - this seems somewhat misleading and I don't think that thread safety analysis should derive anything from this annotation …
=> Change thread safety annotations in thread local store code

source/common/upstream/cluster_manager_impl.h, test/common/http/BUILD, test/common/http/http3/conn_pool_test.cc, test/common/listener_manager/BUILD, test/common/quic/client_connection_factory_impl_test.cc, test/common/quic/quic_transport_socket_factory_test.cc, test/common/router/BUILD, test/common/stats/thread_local_store_test.cc, test/common/tcp_proxy/tcp_proxy_test.cc, test/common/tls/BUILD
This change contains multiple MSAN fixes detected by clang-18. They all in different places, but all of them are caused by a similar issue.
In C++ members of the class are always created in the same order in which they are declared in the class. And they are always destroyed in reverse order. So the first memeber of the class is created first and destroyed last.
When there are interdependencies between the members of a class the order of destruction becomes important. We typically don't want to access data of the already destroyed members in destructors of the members that are being destroyed.
MSAN on clang-18 detected a bunch of cases where we access some fields after they were destroyed. In all but one case, issues happens in tests only and not in the Envoy binary. There …
=> Fix MSAN warnings on clang-18 due to destruction order issues

source/common/common/assert.h, test/common/common/assert_test.cc
Commit Message: Add stacktrace to ASSERTs
Additional Description: Before this change, ASSERTs provoke a stacktrace, but it is always the useless two-line stacktrace
```
#0: sigHandler()
#1: restore_rt
```
as demonstrated by the test case added in this PR not passing before the change.
It's a bit odd that after this change there will be two stacktraces output on assert, but at least one of them will be useful.
Risk Level: Minimal, it's just output from asserts so if it does anything it's during a crash anyway.
Testing: Added a test case, and used to debug my production issue which I couldn't with the original version.
=> Add stacktrace to ASSERTs

bazel/foreign_cc/BUILD
This should be turned off as it's not needed.
Ref https://github.com/Homebrew/homebrew-core/pull/205269
Fix #37470
=> [bp/1.33] deps: stop building libcurl docs (#38172)

bazel/foreign_cc/BUILD
This should be turned off as it's not needed.
Ref https://github.com/Homebrew/homebrew-core/pull/205269
Fix #37470
=> [bp/1.32] deps: stop building libcurl docs (#38172)

source/common/local_reply/local_reply.cc, source/common/local_reply/local_reply.h, source/extensions/filters/network/http_connection_manager/config.cc, source/extensions/filters/network/http_connection_manager/config.h, test/common/local_reply/local_reply_test.cc, tools/code_format/config.yaml
=> local reply: removing exceptions

source/extensions/dynamic_modules/sdk/rust/src/buffer.rs, source/extensions/dynamic_modules/sdk/rust/src/lib.rs, test/extensions/dynamic_modules/test_data/rust/http.rs, test/extensions/dynamic_modules/test_data/rust/http_test.rs
Commit Message: dynamic_modules: add EnvoyMutBuffer in Rust SDK
This is a follow up on https://github.com/envoyproxy/envoy/pull/38102#discussion_r1932907500
=> dynamic_modules: add EnvoyMutBuffer in Rust SDK

.bazelrc
This is an attempt to fix the slow ICU download that's causing a lot of CI failures. See https://github.com/envoyproxy/envoy/issues/38135. For more information on `--http_timeout_scaling`, see https://bazel.build/reference/command-line-reference#flag--http_timeout_scaling.
Testing: CI
=> bazel: Increase the HTTP scale timeout to 2.0

.bazelrc
The default read timeout is [20 seconds](https://github.com/bazelbuild/bazel/blob/983f4022d0879edc37db8635b59c86e08044bfe8/src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpConnector.java#L60). This PR attempts to increase the read timeout to 120 seconds by increasing the scale timeout factor by 6.0.
Testing: CI
=> bazel: Increase the HTTP scale timeout to 6.0

source/common/router/vhds.cc, source/common/router/vhds.h, tools/code_format/config.yaml
Commit Message: Removes exception from vhds.cc
=> Removes exception from vhds.cc

source/extensions/filters/network/thrift_proxy/router/router.h, source/extensions/filters/network/thrift_proxy/router/shadow_writer_impl.h, source/extensions/filters/network/thrift_proxy/router/upstream_request.cc, test/extensions/filters/network/thrift_proxy/shadow_writer_test.cc
Addresses a segmentation fault in Envoy’s Thrift proxy when handling shadow traffic. The crash occurs due to a null pointer dereference of MessageMetadata within the shadow router path during response parsing from upstream. In scenarios where the Thrift decoder unexpectedly returns a complete parsing status without metadata, the previous logic led to crashing. Now, UpstreamRequest has been updated to include null-checks around metadata access during handleRegularResponse(), treating it as an error condition.
Added a new Counter to track null metadata from responses for Thrift router
`thrift.upstream_resp_metadata_null`
Backtrace from production machine
```
Program terminated with signal SIGSEGV, Segmentation fault.  
#0  0x00007f4ea0ea32ab in raise …
```
=> Fix null metadata dereference in Thrift proxy router for shadow traffic

mobile/test/common/integration/client_integration_test.cc
The DNS refresh on failure currently only works for `getaddrinfo` on Linux because the Apple DNS resolver treats `kDNSServiceErr_NoSuchRecord` as non-failure. 
=> mobile: Disable ClientIntegrationTest.DisableDnsRefreshOnFailure on macOS

contrib/golang/filters/http/source/config.h, contrib/golang/filters/http/source/golang_filter.cc, contrib/golang/filters/http/source/golang_filter.h, contrib/golang/filters/http/source/processor_state.cc, contrib/golang/upstreams/http/tcp/source/processor_state.cc, contrib/golang/upstreams/http/tcp/source/processor_state.h, contrib/golang/upstreams/http/tcp/source/upstream_request.cc, contrib/hyperscan/matching/input_matchers/source/matcher.cc, contrib/hyperscan/matching/input_matchers/test/matcher_test.cc, contrib/kafka/filters/network/source/mesh/command_handlers/fetch_record_converter.cc, contrib/kafka/filters/network/source/serialization.h, contrib/qat/compression/qatzip/compressor/test/qatzip_compressor_impl_test.cc, contrib/qat/compression/qatzstd/compressor/test/qatzstd_compressor_impl_test.cc, contrib/qat/private_key_providers/source/qat.h, contrib/sip_proxy/filters/network/source/metadata.h, contrib/sip_proxy/filters/network/source/router/router_impl.cc
Run `check_spelling_pedantic.py` tool in contrib/ folder and fix the obvious typos
Testing:
Docs Changes:
Release Notes:
=> fix typo in contrib/

source/extensions/filters/http/dynamic_modules/abi_impl.cc, source/extensions/filters/http/dynamic_modules/filter.cc, source/extensions/filters/http/dynamic_modules/filter.h, test/extensions/dynamic_modules/http/BUILD, test/extensions/dynamic_modules/http/filter_test.cc, test/extensions/dynamic_modules/http/integration_test.cc, test/extensions/dynamic_modules/test_data/rust/BUILD, test/extensions/dynamic_modules/test_data/rust/Cargo.toml, test/extensions/dynamic_modules/test_data/rust/http.rs, test/extensions/dynamic_modules/test_data/rust/http_integration_test.rs
Commit Message: dynamic_modules: adds integration tests
This adds various integration test cases for dynamic modules
that cover all currently implemented callbacks. While running
tests, I discovered a few edge cases around decodeData and
encodeData, so I fixed it.
Testing: added
=> dynamic_modules: adds integration tests

docs/root/configuration/http/http_filters/_include/aws-lambda-filter.yaml, docs/root/configuration/http/http_filters/_include/aws-lambda-typed-filter.yaml, docs/root/configuration/http/http_filters/aws_lambda_filter.rst
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: Update AWS config reference to use literalincludes

source/common/common/utility.cc, source/common/common/utility.h
The use of this symbol has been deprecated and marked for inlining. The function being deprecated is absl::container_internal::raw_hash_set::find.
=> Remove deprecated use of hash_set::find

test/extensions/http/credential_injector/oauth2/credential_injector_oauth_integration_test.cc
Commit Message: test flake: fix credential_injector_oauth_integration_test/RetryOnClusterNotFound
Test was verifying stat increment on every retry. Test was relying on retry timeout to approximate the stat increment verification timeout. This can fail based on resources/load on the underlying machine.
Now test has been changed from verifying stat increment on every failed retry to if any retry happened which will be more stable.
fixes: https://github.com/envoyproxy/envoy/issues/38263
=> flake: fix credential_injector_oauth_integration_test/RetryOnClusterNotFound

source/extensions/filters/http/admission_control/config.cc, source/extensions/filters/http/admission_control/evaluators/success_criteria_evaluator.cc, source/extensions/filters/http/admission_control/evaluators/success_criteria_evaluator.h, test/extensions/filters/http/admission_control/config_test.cc, test/extensions/filters/http/admission_control/success_criteria_evaluator_test.cc, tools/code_format/config.yaml
Commit Message: Make admission_control exception free
Testing: existing ones 
=> Make admission_control exception free

source/common/network/connection_impl.cc, source/common/runtime/runtime_features.cc, test/common/network/connection_impl_test.cc
This PR adds debugging info by logging the local and remote address families on network, such as an issue with trying to connect to an IPv6-only server on an IPv4-only network or IPv4-only server on an IPv6-only network. This feature can only be enabled by setting `envoy.reloadable_features.log_ip_families_on_network_error` runtime guard to true. It defaults to false.
Runtime guard: `envoy.reloadable_features.log_ip_families_on_network_error`
=> network: Log local and remote address families on network error

api/envoy/config/filter/http/jwt_authn/v2alpha/README.md, api/envoy/config/filter/http/jwt_authn/v2alpha/config.proto, api/envoy/extensions/filters/http/jwt_authn/v3/config.proto, api/envoy/service/auth/v2/attribute_context.proto, api/envoy/service/auth/v3/attribute_context.proto, changelogs/1.24.0.yaml, configs/jwt_authn.yaml, docs/root/configuration/http/http_filters/_include/jwt-authn-filter.yaml, docs/root/configuration/http/http_filters/_include/jwt-authn-headers-filter.yaml, docs/root/configuration/http/http_filters/jwt_authn_filter.rst, source/extensions/filters/http/jwt_authn/authenticator.cc, source/extensions/filters/http/jwt_authn/extractor.cc, source/extensions/filters/http/jwt_authn/extractor.h, source/extensions/filters/http/jwt_authn/filter.cc, source/extensions/filters/http/jwt_authn/jwt_cache.h, source/extensions/filters/http/jwt_authn/verifier.cc, test/extensions/filters/http/jwt_authn/filter_integration_test.cc, test/extensions/filters/http/jwt_authn/jwt_authn_fuzz_test.cc, test/extensions/filters/http/jwt_authn/provider_verifier_test.cc
JWT stands for *JSON Web Token*. Code comments and documentation both contain many "JWT token" which is double.
This pull request replaces those pieces of text with JWT (or sometimes plural).
This pull request should have no code changes.
---
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: remove all usages of "JWT token" in text

envoy/network/BUILD, envoy/network/io_handle.h, envoy/network/listener.h, source/common/network/io_socket_handle_impl.cc, source/common/network/udp_listener_impl.cc, source/common/network/udp_listener_impl.h, source/common/network/utility.cc, source/common/network/utility.h, source/common/quic/active_quic_listener.cc, source/common/quic/envoy_quic_client_connection.cc, source/common/quic/envoy_quic_client_connection.h, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h, source/extensions/upstreams/http/udp/upstream_request.cc, source/extensions/upstreams/http/udp/upstream_request.h, test/common/quic/envoy_quic_client_session_test.cc, test/integration/filters/test_listener_filter.h, test/integration/quic_http_integration_test.cc, test/mocks/network/mocks.h, test/test_common/network_utility.cc
Commit Message: Fix bug in UDP CMSG plumbing
Additional Description: Follow-up to #35382.
The original RawSlice that we wrote the csmg to points to stack memory that is immediately freed, so we use a different structure that properly moves the memory buffer up to the QuicReceivedPacket. The bug is reproduced in quic_http_integration_test with the change to TestQuicListenerFilter (i.e., if you remove the other changes in this PR) under ASAN builds.
Testing: Reproduced in integration test (quic_http_integration_test)
=> Fix bug in UDP CMSG plumbing

source/common/http/codec_client.cc, test/common/grpc/grpc_client_integration_test.cc, test/common/grpc/grpc_client_integration_test_harness.h, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/integration/fake_upstream.cc, test/integration/fake_upstream.h
These tests document current broken behavior of ext_proc always resetting gRPC side streams. 
=> Add tests for ext_proc stream resets

source/extensions/dynamic_modules/sdk/rust/src/lib.rs, source/extensions/dynamic_modules/sdk/rust/src/lib_test.rs, test/extensions/dynamic_modules/test_data/rust/http.rs, test/extensions/dynamic_modules/test_data/rust/http_integration_test.rs, test/extensions/dynamic_modules/test_data/rust/no_op.rs
Commit Message: dynamic_modules: add mut to &FilterConfig on filter creation
This adds `mut` keywrod to &HttpFilterConfig on new_http_filter method. Without this, for example, we cannot share a cache across multiple http filters on a central place.
=> dynamic_modules: add mut to &FilterConfig on filter creation

source/extensions/common/aws/aws_cluster_manager.cc, source/extensions/common/aws/aws_cluster_manager.h, source/extensions/common/aws/credentials_provider_impl.cc, source/extensions/common/aws/credentials_provider_impl.h, source/extensions/filters/http/aws_lambda/config.cc, source/extensions/filters/http/aws_request_signing/config.cc, source/extensions/grpc_credentials/aws_iam/config.cc, test/extensions/common/aws/BUILD, test/extensions/common/aws/aws_cluster_manager_test.cc, test/extensions/common/aws/credentials_provider_impl_test.cc, test/extensions/common/aws/mocks.h
Commit Message: aws: remove singleton calls and add virtual cluster manager
Additional Description: Minor cleanups and support for mocking new cluster manager component
Risk Level: Negligible
Testing: Unit
=> aws: remove singleton calls and add virtual cluster manager

source/common/tls/ocsp/ocsp.cc
Commit Message: minor-perf: move tls oscp string
Minor perf moving the tls oscp string instead of copying.
Testing: N/A
=> minor-perf: move tls oscp string

source/common/secret/secret_provider_impl.cc
Commit Message: minor-perf: move secret provider string
Minor perf-nit: moving a secret provider string instead of copying it
Testing: N/A
=> minor-perf: move secret provider string

source/common/network/tcp_listener_impl.cc
Commit Message: minor-perf: move tcp listener address shared ptr
Minor-perf: moving a shared pointer instead of copying it.
Testing: N/A
=> minor-perf: move tcp listener address shared ptr

source/extensions/dynamic_modules/BUILD, source/extensions/dynamic_modules/abi.h, source/extensions/dynamic_modules/abi_version.h, source/extensions/dynamic_modules/sdk/rust/src/lib.rs, source/extensions/filters/http/dynamic_modules/abi_impl.cc, test/extensions/dynamic_modules/http/abi_impl_test.cc, test/extensions/dynamic_modules/http/filter_test.cc, test/extensions/dynamic_modules/test_data/rust/http.rs, test/extensions/dynamic_modules/test_data/rust/http_test.rs
Commit Message: dynamic_modules: adds ClearRouteCache callback
This adds envoy_dynamic_module_callback_http_clear_route_cache that allows users to make a custom routing decision. This was one of many gaps between dynamic_modules and other extension mechanisms.
Testing: done
=> dynamic_modules: adds ClearRouteCache callback

source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc, source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h, test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc
- Improve retries by checking connect attempts immediately after the upstream connect failure.
- Prevent adding the same session more than once to cluster's sessions (it's not really a bug because absl::flat_hash_set is a hash set that only allows unique elements and the second attempt has no effect).
Testing:
Docs Changes:
Release Notes:
=> udp_proxy: improve retries by checking connect attempts immediately after failure

envoy/formatter/http_formatter_context.h, test/common/formatter/BUILD, test/common/formatter/formatter_context_test.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> formatter context: new method to provide extension data

envoy/network/BUILD, envoy/network/drain_decision.h, envoy/server/BUILD, envoy/server/drain_manager.h, mobile/envoy_build_config/BUILD, source/common/common/BUILD, source/common/common/callback_impl.cc, source/common/common/callback_impl.h, source/common/listener_manager/filter_chain_manager_impl.h, source/common/listener_manager/listener_impl.h, source/common/listener_manager/listener_manager_impl.cc, source/common/secret/BUILD, source/exe/stripped_main_base.cc, source/extensions/filters/network/http_connection_manager/BUILD, source/extensions/filters/network/redis_proxy/BUILD, source/server/BUILD, source/server/api_listener_impl.h, source/server/drain_manager_impl.cc, source/server/drain_manager_impl.h, test/common/common/callback_impl_test.cc, test/integration/server.h, test/mocks/network/mocks.h, test/mocks/server/drain_manager.h, test/server/BUILD, test/server/drain_manager_impl_test.cc, tools/code_format/config.yaml
This reverts commit 072831e7618957a640529ecfd970e643bcbfaf88.
Revert in PR-37465 created problems for boundary proxy for Google partner cloud, as it depends on the reverted internal API `addOnDrainCloseCb`. Boundary proxy is open source and Google cloud partners will be  unable to build OSS version, since it depends on OSS Envoy.
Putting back the reverted code for now, as it is unclear what exactly can be removed from Envoy at this point.
=> Revert "drain_manager: Unclean Revert of "HTTP2 Proactive GOAWAY on Drain - Preamble (#17026)" (#37465)"

source/extensions/dynamic_modules/sdk/rust/README.md
Commit Message: docs: updates outdated Rust dynamic_modules README
Testing: n/a
=> docs: updates outdated Rust dynamic_modules README

envoy/server/factory_context.h, source/server/server.h, test/mocks/server/server_factory_context.cc, test/mocks/server/server_factory_context.h
Commit Message: factory context: extend ServerFactoryContext with getTransportSocketFactoryContext
Additional Description: This change is necessary to allow upstream filters reading secrets from SDS.
Testing: -
Docs Changes: Not needed as it is only an internal change.
Release Notes: Not needed as it is only an internal change.
Platform Specific Features: -
This change is necessary to unblock:
1. injecting credentials to upstream requests #38398
2. reading image pull secret by upstream wasm filters #37635
=> factory context: extend ServerFactoryContext with getTransportSocketFactoryContext

source/common/quic/quic_client_transport_socket_factory.cc, source/common/runtime/runtime_features.cc, test/integration/multiplexed_upstream_integration_test.cc, test/integration/quic_http_integration_test.cc
This will be useful for certain mobile clients to disable early data / 0-RTT in the QUICHE layer itself.
=> quic: Add option to disable QUIC early data (0-RTT)

source/extensions/upstreams/http/udp/upstream_request.h, test/extensions/upstreams/http/udp/BUILD, test/extensions/upstreams/http/udp/upstream_request_test.cc
This allows for the remote address to be retrieved from the Network::ConnectionInfoProvider.
Also add a test to confirm that this is the case.
Testing: added new test, further tested wth a local envoy
=> CONNECT-UDP: set remote_address in udp upstream socket

envoy/http/header_map.h, test/integration/fake_upstream.h
Those methods return references to internal protected members, so ideally all the callers should acquire a lock before calling those.
I suspect that we got away with returning reference so far because in most cases we don't actully need to synchronize when calling any of these methods because synchronization happens erlier when we call one of waitForX methods.
Anyways, the new Clang complains about it, so we can as well fix it in a way that makes it clear that the methods are thread safe.
This PR changes the the signature of the methods to return a shared pointer to const data instead of references where it's not the case already. 
Related to #37911 and fixes one of the issues in #38093
body() method has a similar problem, but it's addressed in a …
=> Make FakeStream::{headers, trailers} thread safe to make clang-18 happy

source/extensions/dynamic_modules/abi.h, source/extensions/dynamic_modules/abi_version.h, source/extensions/dynamic_modules/sdk/rust/src/lib.rs, source/extensions/filters/http/dynamic_modules/abi_impl.cc, test/extensions/dynamic_modules/http/abi_impl_test.cc, test/extensions/dynamic_modules/http/filter_test.cc, test/extensions/dynamic_modules/test_data/rust/http.rs, test/extensions/dynamic_modules/test_data/rust/http_test.rs
Commit Message: dynamic_modules: adds support for header removal
This allows dynamic modules to remove headers/trailers by allowing setter callbacks to accept null pointer values.
Testing: done
=> dynamic_modules: adds support for header removal

test/extensions/filters/http/local_ratelimit/local_ratelimit_integration_test.cc
Unlike with swap, calling move without std:: is considered a somewhat bad practice. The concern revolves around C++ ADL and the fact that move is, unfortunately, a rather commonly used name. You can read some discussion on that in https://reviews.llvm.org/D119670?id=408276.
The reason why I want to fix it is that when I try to build and run Envoy tests with clang-18, uses of std::move without std::qualifier trigger unqualified-std-cast-call warning that is convered into an error.
We can disable the warning, but given that the fix is small, generally makes sense and does not cause troublems, I though it might be better to just submit a small fix like this.
NOTE: I grepped through Envoy codebase, and local ratelimit integration tests seem to be the only two occurances where …
=> When calling std::move use the name qualified with namespace instead of plain move

mobile/library/jni/BUILD, mobile/library/jni/jni_helper.cc, mobile/library/jni/jni_impl.cc, mobile/library/jni/jni_init.cc, mobile/library/jni/jni_init.h
This is needed so that we can initialize and shutdown the JNI code in a custom `JNI_OnLoad` and `JNI_OnUnLoad`.
Testing: CI
Platform Specific Features: android
=> mobile: Move the JNI initialization and shutdown into separate functions

source/extensions/dynamic_modules/dynamic_modules.cc, source/extensions/dynamic_modules/dynamic_modules.h
Commit Message: dynamic_modules: clean up duplicates call to filesystem::absolute
Previously, during module loading phase,  std::filesystem::absolute was called unnecessarily twice. This commit cleans up the code path and removes the duplicate call to it.
=> dynamic_modules: clean up duplicate call to filesystem::absolute

test/integration/fake_upstream.cc
In FakeUpstream class we capture local std::function by reference in lambda. That does not cause many problems in practice and it is not detected by the MSAN in clang-14 currently used by Envoy CI.
Still, it's not correct, and it does trigger a smarter MSAN in clang-18.
Related to https://github.com/envoyproxy/envoy/issues/37911 and fixes one of the issues that block clang-18 adoption in Envoy CI.
Testing: `do_ci.sh msan` using Envoy CI image with clang-18
=> Don't capture local objects by reference in lambda

changelogs/current.yaml, source/extensions/request_id/uuid/config.cc, test/extensions/request_id/uuid/config_test.cc
Commit Message: `feat(request_id): set request id when it's set but empty`
Testing: Yes
Release Notes:
* `generate_request_id` will generate a request id on non-present and empty `x-request-id` header.
Fixes #38445
=> feat(request_id): set request id when it's set but empty

README.md, bazel/BUILD, bazel/external/BUILD, bazel/external/aws_lc.BUILD, bazel/external/aws_lc.genrule_cmd, bazel/protobuf.patch, bazel/repositories.bzl, bazel/repository_locations.bzl, bazel/rules_java_ppc64le.patch, bazel/rules_rust_ppc64le.patch, bazel/v8_ppc64le.patch, envoy/ssl/private_key/private_key.h, source/common/tls/BUILD, source/common/tls/aws_lc_compat.h, source/common/tls/cert_validator/default_validator.cc, source/common/tls/context_impl.h, source/exe/BUILD, source/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator.cc
Commit Message: Build Envoy with aws_lc instead of boringssl when building for the ppc64le architecture.
Additional Description: Envoy uses boringssl as the default ssl implementation. As boringssl does not support the ppc64le architecture, a different ssl implementation is necessary to build Envoy for ppc64le.
Risk Level: High
Testing:
Docs Changes:
Release Notes:
Platform Specific Features: Boringssl no longer supports the ppc64le architecture. Here, aws_lc is used as a "drop-in" replacement for boringssl when building Envoy for ppc64le. Aws_lc is conditionally built **only** when Envoy is built for ppc64le with FIPS support.
[Optional [API …
=> Build Envoy with aws_lc on Power (ppc64le)

envoy/access_log/BUILD, envoy/access_log/access_log_config.h, source/common/access_log/access_log_impl.cc, source/common/access_log/access_log_impl.h, source/common/formatter/substitution_format_string.h, source/extensions/access_loggers/common/stream_access_log_common_impl.h, source/extensions/access_loggers/file/config.cc, source/extensions/access_loggers/file/config.h, source/extensions/access_loggers/fluentd/config.cc, source/extensions/access_loggers/fluentd/config.h, source/extensions/access_loggers/grpc/http_config.cc, source/extensions/access_loggers/grpc/http_config.h, source/extensions/access_loggers/grpc/tcp_config.cc, source/extensions/access_loggers/grpc/tcp_config.h, source/extensions/access_loggers/open_telemetry/config.cc, source/extensions/access_loggers/open_telemetry/config.h, source/extensions/access_loggers/stream/config.cc, source/extensions/access_loggers/stream/config.h, source/extensions/access_loggers/wasm/config.cc, source/extensions/access_loggers/wasm/config.h, source/extensions/filters/network/generic_proxy/file_access_log.h, test/extensions/access_loggers/file/config_test.cc, test/integration/fake_access_log.h, test/integration/typed_metadata_integration_test.cc
Commit Message: access log: new access log interface to provide custom command parsers
Part of https://github.com/envoyproxy/envoy/pull/38164. This extend the interface of access logger. Now the caller could provides some custom commands parsers to the logger directly.
By this way, the different loggers dependents (generic proxy, thrift proxy, mongo proxy, etc) could support different custom formatter command by them self and needn't to extend new formatter extension.
Testing: unit.
=> access log: new access log interface to provide custom command parsers

contrib/golang/common/go/api/api.h, contrib/golang/common/go/api/capi.go, contrib/golang/common/go/api/filter.go, contrib/golang/filters/http/source/cgo.cc, contrib/golang/filters/http/source/go/pkg/http/capi_impl.go, contrib/golang/filters/http/source/go/pkg/http/filter.go, contrib/golang/filters/http/source/go/pkg/http/type.go, contrib/golang/filters/http/source/golang_filter.cc, contrib/golang/filters/http/source/golang_filter.h, contrib/golang/filters/http/test/golang_integration_test.cc, contrib/golang/filters/http/test/test_data/BUILD, contrib/golang/filters/http/test/test_data/bufferinjectdata/BUILD, contrib/golang/filters/http/test/test_data/bufferinjectdata/config.go, contrib/golang/filters/http/test/test_data/bufferinjectdata/filter.go, contrib/golang/filters/http/test/test_data/plugins.go
Commit Message: golang: allow injecting extra data
Additional Description: This PR adds a feature that allows users to flush the data immediately when processing the data asynchronously.
Testing: Integration test
Docs Changes:
Release Notes:
=> golang: allow injecting extra data

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Commit Message: ext_proc: Add integration tests for STREAMED body immediate responses
Confirm that ext_proc body handlers may send an immediate response in STREAMED body mode, and that the downstream will see that response.
Testing: tests only
=> ext_proc: Add integration tests for STREAMED body immediate responses

mobile/library/cc/engine.cc, mobile/library/cc/engine.h, mobile/library/common/internal_engine.cc, mobile/library/common/internal_engine.h, mobile/test/common/integration/client_integration_test.cc, mobile/test/java/org/chromium/net/CronetHttp3Test.java
Envoy Mobile's network change event handling relied on the underlying operating system's network change monitor APIs to receive events of a network change. On platforms like iOS, the network change monitor callbacks get invoked on many sorts of network events, even those that don't result in an actual network change. In addition, the network monitor APIs don't always give fine granularity change events. For example, on iOS, if the device switches from one Wifi network to another, a network change event will fire but both times the type will be Wifi, so there's no way to distinguish that we actually changed networks. When Envoy Mobile detects a network change, it does some potentially costly operations, such as draining existing network connections, refreshing the DNS cache, resetting the …
=> mobile: Improvements to handling network change events

docs/root/configuration/http/http_filters/_include/aws_credentials.rst
Commit Message: docs: Fix RST formatting for AWS credentials documentation
Additional Description: Fix backtick formatting in AWS credentials documentation that was causing incorrect rendering in markdown preview. This improves readability of the SigV4A region configuration section. See https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/aws_request_signing_filter.html for the current format.
Risk Level: 
Testing:
Docs Changes:
Release Notes:
=> docs: Fix RST formatting for AWS credentials documentation

envoy/config/BUILD, envoy/config/xds_manager.h, source/common/config/xds_manager_impl.cc, source/common/config/xds_manager_impl.h, source/common/upstream/cluster_manager_impl.cc, source/common/upstream/cluster_manager_impl.h, test/mocks/config/xds_manager.h
Commit Message: xds: refactor xds-resources-delegate and move it to xds-manager
Follow up to #38242.
This PR moves the xDS-Resources-Delegate from the cluster-manager to the xds-manager.
Note that in this PR we add a getter for the xDS-Resources-Delegate, but that will be removed in the future when the rest of the xDS-related components are moved from the cluster-manager to the xds-manager.
Testing: N/A - original tests should cover functionallity.
=> xds: refactor xds-resources-delegate and move it to xds-manager

test/integration/quic_http_integration_test.cc
Risk Level: None; no functional change
Testing: CI; again, no functional change
=> Adjust comments to reflect new reality

source/common/filesystem/posix/filesystem_impl.cc
Commit Message: Make stderr and stdout not require presence of /dev/stderr and /dev/stdout
Additional Description: Not every environment has `/dev/stderr` and `/dev/stdout` - it turns out bazel sandboxes sometimes do not, which, combined with using `StdoutAccessLog`, results in a surprising behavior where the startup info logs are logged, but none of the access logs are - but if the same thing is run *not* in that sandbox, everything is logged.
Risk Level: Very small. Accessing stderr and stdout via duplicating the standard file handles should be the same behavior as the other behavior when it's not broken.
Testing: Existing `filesystem_impl_test` already tests stderr and stdout files.
=> Make stderr and stdout not require presence of /dev/stderr and /dev/stdout

contrib/tap_sinks/udp_sink/source/udp_sink_impl.cc, contrib/tap_sinks/udp_sink/test/udp_sink_test.cc
Commit Message: Support PROTO_TEXT format in UDP sink 
New request from custom, it needs raw format http2 message.
if use format JSON_BODY_AS_BYTES, then the http2  message is encoded as base64, then server side has to base64 decode to get raw http2 message.
if use format  PROTO_TEXT, then server side get raw http2 message which doesn't need run base64 decode to save CPU time
Based above reason, add format PROTO_TEXT in UDP sink to meet raw http2 message  needs.
if it set JSON_
Risk Level:low
Testing:
Docs Changes:
Release Notes:
=> http/transport tap: Support PROTO_TEXT format in UDP sink 

bazel/foreign_cc/BUILD
There is a known issue in gperftools - when linking statically profiling triggered by environment variables does not work, because linker does not see the right profiling functions used and eliminates them completely.
I'm not entirely sure why the issues has not been fixed after all this time, but it's relatively well documented (see
https://github.com/gperftools/gperftools/issues/961, https://github.com/gperftools/gperftools/issues/415, etc).
There are a few ways to address the issues:
1. Link dynamically, this way linker would not have enough information to eliminate "unused" functions, because it cannot actually tell if they are trully unused
2. Explicitly tell linker that some functions must be preserved using -Wl,--undefined=<function name>
3. Use --whole-archive to …
=> When building with gperftools always link the library

api/envoy/extensions/filters/http/jwt_authn/v3/config.proto, changelogs/current.yaml, source/extensions/filters/http/jwt_authn/jwt_cache.cc, test/extensions/filters/http/jwt_authn/jwt_cache_test.cc
Commit Message: jwt: make max token size configurable
Testing: unit tests added
Docs Changes: protobuf comment
Fixes: #32790
=> jwt: make max token size configurable

source/extensions/resource_monitors/cpu_utilization/linux_cpu_stats_reader.h
=> clang-tidy: fixes invalid case style in LinuxContainerCpuStatsReader

test/common/router/corpus_from_config_impl.sh
I'm working on addressing the issues coming up when building Envoy with clang-18 (currently used clang version is 14). One of the issues is that Envoy CI MSAN hits OOMs with clang-18 and
test/common/router/corpus_from_config_impl.sh is one of the things that hits the memory constraints.
The problem appears to be that clang-18 MSAN instrumentation is much more detailed and when running
test/common/router:config_impl_test_static MSAN itself (not the test logic) has to allocate a large amount of memory. In my tests it needed over 10GiB of memory which is a problem.
Envoy CI workers can go up to 6GiB currently, so such a large test does not fit. And for completenes, with clang-14 the same binary used around 4GiBs.
NOTE: I verified that the test itself does not have memory …
=> Shard test/common/router/corpus_from_config_impl.sh

source/common/thread_local/thread_local_impl.cc, source/common/thread_local/thread_local_impl.h
=> clang-tidy: do not call virtual method in ~SlotImpl

test/common/common/BUILD, test/common/common/assert_test.cc
It looks that assert tests were recently updated to validate that triggered asserts print a stack trace. However stacktraces that are produced depend on the compilation parameters and compiler, i.e., if compiler will decide to inline releaseAssertInAFunction it will not show up in the stack trace breaking the test, even though nothing is actually wrong.
That's exactly what I noticed when building Envoy using clang-18 as we are trying to move Envoy CI to clang-18.
This change adds an attribute to the releaseAssertInAFunction that would prevent commonly used compilers (and importantly clang specifically) from inlining the function and breaking the test.
Related to https://github.com/envoyproxy/envoy/issues/37911 and fixes one of the issues that block …
=> Stop compiler from inlining releaseAssertInAFunction in test

bazel/v8.patch
This is a workaround to help us migrate to clang-18 for Envoy CI. clang-18 detected a "use-after-free" type of issue in v8 code and that fails Envoy CI ASAN runs.
This issue was fixed upstream already (see
https://github.com/v8/v8/commit/df459f0e7eda0d1c50698284aab6f424057e076a) and updating v8 should resolve the problem. However for now I'm working around that with a patch update because:
1. Updating v8 will fix this problem, but might also introduce new issues, so I'd like to finish with clang-18 migration for now and update v8 once clang-18 migration is settled
2. v8 is a bit of special dependency, as Envoy does not use upstream v8 directly but instead relies on some kind of processed version, that's probably one of the reasons why we don't update v8 as often.
NOTE: I …
=> Update v8 patch to fix ASAN issue detected by clang-18

source/extensions/filters/http/dynamic_modules/factory.cc, test/extensions/dynamic_modules/http/factory_test.cc
Commit Message: use addStreamFilter for dynamic_modules http filter callback
Additional Description: Using addStreamDecoderFilter and addStreamEncoderFilter will cause filter to be added twice in filter manager, so that callback like onStreamComplete will be called twice for one filter. Using addStreamFilter can make sure that callback will only be called once for one filter.
=> dynamic_modules: use addStreamFilter for dynamic_modules http filter callback

test/integration/filters/test_listener_filter.h
This fixes the clang-tidy error in test_listener_filter.h as in  "use '= default' to define a trivial default constructor".
Contributes to #28566
=> clang-tidy: fix error in test_listener_filter.h

CODEOWNERS
The listed owner is no longer involved in Envoy
=> remove codeowner from rbac matchers

source/extensions/filters/http/ratelimit/config.cc, source/extensions/filters/http/ratelimit/config.h, source/extensions/filters/http/ratelimit/ratelimit.h, test/extensions/filters/http/ratelimit/ratelimit_test.cc, tools/code_format/config.yaml
Commit Message: Make http/ratelimit exception free
Testing: existing ones 
=> Make http/ratelimit exception free

docs/root/configuration/http/http_filters/admission_control_filter.rst
fix admission control document example values
Commit Message: docs: fix admission control document example values
Additional Description: the admission control documentation configuration example isn't right. the example description describe different values than the example.
=> docs: fix admission control document example values

docs/root/configuration/http/http_conn_man/headers.rst
RFC 2459 has been obsoleted (twice, as it were) and a non-obsoleted reference for SAN can be found in RFC 5280.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Update SAN RFC reference

docs/root/configuration/operations/tools/router_check.rst
Fixes the docs for the route checker tool which do not currently contain a valid test case.
The method parameter is marked as required yet the description implies it is not. From experimentation it does appear to be required, but I have not dived deep enough into the source code to fully verify this.
Testing: Ran updated configuration against latest version of the tool
Docs Changes: As described above
=> docs: correct route check docs

test/extensions/network/dns_resolver/apple/apple_dns_impl_test.cc
This is similar to #36274
./ci/mac_ci_steps.sh fails with the following error on MacOS M4
```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
test/extensions/network/dns_resolver/apple/apple_dns_impl_test.cc:176:51: error: implicit capture of 'this' with a capture default of '=' is deprecated [-Werror,-Wdeprecated-this-capture]
176 |                                    absl::StrSplit(active_dns_query_->getTraces(), ',');
|                                                   ^
test/extensions/network/dns_resolver/apple/apple_dns_impl_test.cc:123:29: note: add an explicit capture of 'this' to capture '*this' by reference
123 |                            [=](DnsResolver::ResolutionStatus status, absl::string_view,
| …
```
=> Fix Mac CI Build on M1

source/common/buffer/buffer_impl.cc, source/common/buffer/buffer_impl.h, source/common/filter/config_discovery_impl.cc, source/common/filter/config_discovery_impl.h, source/extensions/common/wasm/ext/envoy_proxy_wasm_api.h, source/extensions/filters/network/common/redis/BUILD, source/extensions/filters/network/common/redis/supported_commands.cc, source/extensions/filters/network/common/redis/supported_commands.h, source/extensions/load_balancing_policies/common/load_balancer_impl.cc, source/extensions/load_balancing_policies/common/load_balancer_impl.h, source/extensions/load_balancing_policies/subset/subset_lb.cc, source/extensions/load_balancing_policies/subset/subset_lb.h
I described the problem with coverage and possible solutions to it in https://github.com/envoyproxy/envoy/issues/37911#issuecomment-2659837724.
TL;DR: clang source-based coverage (which is what we currently use) is subtly broken when dynamic linking is involved (which is what we currently do for coverage tests).
The issue shows itself as lack of coverage of some functions defined in a header file (class members, free-standing inline functions or function temapltes), even though there are tests that cover it.
The issue is a result of a bug in LLVM/Clang/coverage tooling (it's debatable where exactly is the bug fix should be): https://github.com/llvm/llvm-project/issues/32849.
The issue symptoms are not very predictable, and can be affected by a bunch of factors starting …
=> Workaround coverage issues observed on clang-18

source/extensions/filters/http/local_ratelimit/local_ratelimit.cc, test/extensions/filters/http/local_ratelimit/filter_test.cc
Commit Message: fix: fix local ratelimit spelling
Fixed a bug where use the has_filter_enabled to check if the filter_enforced exists or not.
Testing: unit.
=> fix: fix local ratelimit spelling

source/common/network/io_socket_handle_impl.cc
Commit Message: Set saved CMSG to correct index for recvmmsg
Additional Description: This bug should be corrected, but the only usage of this is in QuicListenerFilter, where we only care about the first packet.
Testing: N/A
=> set saved CMSG to correct index for recvmmsg

api/envoy/extensions/network/socket_interface/v3/default_socket_interface.proto, changelogs/current.yaml, docs/root/configuration/other_features/_include/io_uring.yaml, docs/root/configuration/other_features/io_uring.rst, docs/root/configuration/other_features/other_features.rst, source/common/network/socket_interface_impl.cc, test/integration/socket_interface_integration_test.cc
Signed-off-by: Xie Zhihao <xzh1206@gmail.com>
Commit Message: io_uring: update API
Testing: N/A
Fix #38660
=> io_uring: update API and docs

api/envoy/config/listener/v3/listener.proto, changelogs/current.yaml, source/common/listener_manager/listener_impl.cc, source/common/listener_manager/listener_impl.h, source/common/listener_manager/listener_manager_impl.cc, test/common/listener_manager/listener_manager_impl_test.cc, test/integration/listener_lds_integration_test.cc
Commit Message: listener: fixed a bug where the addresses cannot be updated partially
To close https://github.com/envoyproxy/envoy/issues/37373. The #37373 was opened for a while and there is some related PR try to fixed it. See #37396 #38530. Thanks for the great contribution from @Shikugawa and @bbassingthwaite.
Their works is great and make sense. But I want a clean patch to fixed all LDS updating problems (not only the #37373). The exist logic and checks are pretty confusing and hard to maintain. So, I think we'd better to do complete refactring/clean up rather than only fix the #37373. So, I created this PR.
---
If we treat the addresses self and socket options as a whole entity. The rules of LDS updating of same Listener is pretty simple:
1. If the whole …
=> listener: fixed a bug where the addresses cannot be updated partially

test/common/router/header_parser_corpus/invalid_header_string, test/common/router/header_parser_fuzz_test.cc
Commit Message: disable ASSERTs in header_parser_fuzz_test
The asserts fail on the fuzz test case I add in this PR. These asserts have no effect in production, so sanitizing illegal characters in the fuzz input could hide crashes that would affect production. Therefore, we should disable these asserts in the fuzz test.
Testing: fuzz test improvement
=> disable ASSERTs in header_parser_fuzz_test

source/common/upstream/cds_api_helper.cc, source/common/upstream/cds_api_helper.h, source/common/upstream/cds_api_impl.cc, source/common/upstream/cds_api_impl.h, source/common/upstream/cluster_manager_impl.cc, source/common/upstream/od_cds_api_impl.cc, test/common/upstream/cds_api_impl_test.cc
Commit Message: Records config_reload and config_reload_time_ms statistics when cds makes a non-empty update. 
Testing: Unit tests have been updated to validate that the new stats are properly set.
Release Notes: N/A 
#38490
=> cds: set config_reload and config_reload_time_ms

test/integration/quic_http_integration_test.cc, test/integration/quic_http_integration_test.h
This should help prevent sanitized builds on CI from timing out prematurely.
=> test: Add TIMEOUT_FACTOR to relevant timeouts in QuicHttpIntegrationTest

changelogs/current.yaml, docs/root/configuration/observability/access_log/usage.rst, envoy/stream_info/stream_info.h, source/common/formatter/stream_info_formatter.cc, source/common/http/conn_manager_impl.cc, source/common/stream_info/stream_info_impl.h, test/common/access_log/access_log_impl_test.cc, test/common/formatter/substitution_formatter_test.cc, test/common/stream_info/stream_info_impl_test.cc, test/mocks/stream_info/mocks.cc, test/mocks/stream_info/mocks.h
Commit Message: stream info: custom flag support
The response flags is a great design to help debugging and observing the Envoy. And we also support to register custom response flag to indicate the custom event.
However, for the dynamic extension which doesn't be linked to the binnary initially, it's impossible to use the response flag to indicate their custom event because they cannot register their response flag.
This PR add a simple custom flag to the stream info. The envoy cannot ensure the custom flags won't be duplicated or the custom flags have stable meaning. But it's still make big sense for dynamic extensions. They now have a convenient way to record their event.
Testing: unit.
Platform Specific …
=> stream info: custom flag support

api/envoy/service/ext_proc/v3/external_processor.proto
This is the API part change of encoding some ext_proc filter configuration in the ProcessingRequest message.
Encoding such filter configurations when sending ProcessingRequest message to the ext_proc server helps the server to take right action with it, like send response immediately, or buffer the request.
=> Encoding some ext_proc filter configuration in the ProcessingRequest message

changelogs/current.yaml, source/common/conn_pool/conn_pool_base.cc, source/common/conn_pool/conn_pool_base.h, test/common/http/http2/conn_pool_test.cc, test/integration/protocol_integration_test.cc
The preconnect logic was only counting currently connecting capacity, not established connections with unused capacity, in the calculation of whether new preconnect connections are needed. This resulted in new connections anytime there wasn't an in-progress connection, resulting in far too many connections being established.
Testing: Added new tests, expanded existing tests
Docs Changes: No changes to existing documentation needed
Optional Runtime guard: This is a behavior change, but the existing behavior is so broken that I don't think anyone is using it, so I did not add a guard.
=> conn pool: fix preconnect math

changelogs/current.yaml, source/common/conn_pool/conn_pool_base.cc, source/common/conn_pool/conn_pool_base.h, test/common/http/http2/conn_pool_test.cc, test/integration/protocol_integration_test.cc
The preconnect logic was only counting currently connecting capacity, not established connections with unused capacity, in the calculation of whether new preconnect connections are needed. This resulted in new connections anytime there wasn't an in-progress connection, resulting in far too many connections being established.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> conn pool: fix preconnect math (#38708)

source/common/memory/aligned_allocator.h
std::aligned_alloc is not available for ANDROID_API<28, this change switch it to posix_memalign/free instead.
Commit Message: Use posix_memalign/free in AlignedAllocator for ANDROID_API<28.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Use posix_memalign/free in AlignedAllocator for ANDROID_API<28.

test/extensions/filters/http/common/fuzz/BUILD, test/extensions/filters/http/common/fuzz/filter_corpus/grpc_reverse_transcoding_decode_encode, test/extensions/filters/http/common/fuzz/uber_per_filter.cc
Commit Message: Add seed corpus for grpc json reverse transcoder fuzz testing.
Additional Description: This PR adds a corpus seed to fuzz test the reverse transcoder.
Risk Level: None, as this only enables fuzz testing for the reverse transcoder.
Testing: n/a as this change itself adds the test
=> Add seed corpus for the reverse transcoder

.github/workflows/codeql-daily.yml, .github/workflows/codeql-push.yml
this image is ~EOL and will start brownouting imminently
=> github/ci: Bump remaining `ubuntu-20.04` jobs

.github/config.yml
There have been several instances that changes, particularily to source/* directories, have introduced C++ features not supported by the Android NDK or iOS XCode version for Envoy Mobile.  Without triggering the mobile Android and iOS jobs on those changes, we don't catch them until after the fact.
The latest example is the std::aligned_alloc PR: https://github.com/envoyproxy/envoy/pull/38707.
Which introduced build errors on Android that CI didn't catch at the time of the PR and only in a subsequent PR that triggered mobile CI: https://github.com/envoyproxy/envoy/actions/runs/13818727995/job/38658598098.
This change causes any changes to `source/common/` to trigger Android and iOS CI.  This is a start in allowing us to catch such changes in the PR making the changes.
=> ci: Add trigger for Android and iOS CI jobs on source/common changes

ci/do_ci.sh
Failures can happen before tests actually execute, in those cases do not attempt to collect anything, otherwise we get this error:
```
./ci/do_ci.sh: line 125: pushd: bazel-testlogs: No such file or directory
```
=> ci: Only collect logs if the logs dir exist

api/envoy/service/ext_proc/v3/external_processor.proto, source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/filter_test.cc
This is the follow up PR for: https://github.com/envoyproxy/envoy/pull/38755.
It encodes the ext_proc filter protocol configuration and sends to the server.
The encoding only happens in the first gRPC message.
=> Ext_Proc: Encode filter protocol configuration and send to the server

CODEOWNERS
Thanks for letting me be the owner for Redis filter in the last couple of years, but finding it a little challenging to continue as I'm not working on the Redis filter any more in my job. Hope to re-join the community in the future!
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Remove code owner for Redis filter

contrib/kafka/filters/network/source/protocol/generator.py, contrib/kafka/filters/network/source/serialization/generator.py, contrib/kafka/filters/network/test/broker/integration_test/kafka_broker_integration_test.py, contrib/kafka/filters/network/test/mesh/integration_test/kafka_mesh_integration_test.py
Commit Message:     Autoescape protects web applications against most common cross-site-scripting (XSS) vulnerabilities.
While the output from Jinja templates in the Kafka module don't generate HTML, enabling autoescape for HTML/XML avoids tripping automatic security scanners.
Additional Description: There are more occurrences of Jinja templates that need fixing but those affect the docs generation and need a bigger CR, so I'll keep those for later.
Testing: `./ci/do_ci.sh release.test_only` -- 3 tests failed, see below
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/ …
=> kafka: set autoescape for Jinja templates

api/envoy/extensions/formatter/cel/v3/cel.proto, api/envoy/extensions/formatter/metadata/v3/metadata.proto, changelogs/current.yaml, source/extensions/formatter/cel/BUILD, source/extensions/formatter/cel/cel.cc, source/extensions/formatter/cel/cel.h, source/extensions/formatter/cel/config.cc, source/extensions/formatter/metadata/config.cc, test/extensions/access_loggers/open_telemetry/substitution_formatter_test.cc, test/extensions/formatter/cel/cel_test.cc, test/extensions/formatter/metadata/metadata_test.cc, test/integration/BUILD, test/integration/access_log_integration_test.cc, test/test_common/BUILD, test/test_common/utility.h
Commit Message: formatter: make the CEL and METADATA as built in formatter
This make the CEL and METADATA as built in formatter and could be used everywhere. Now, we needn't to configure it. After this PR, it's possible to use CEL at the header mutation which would be helpful.
Testing: unit/integration.
Docs Changes: added.
=> formatter: make the CEL and METADATA as built in formatter

source/common/http/utility.cc, source/common/http/utility.h, source/common/tls/BUILD, source/common/tls/connection_info_impl_base.cc, source/extensions/common/aws/signer_base_impl.cc, source/extensions/filters/http/grpc_json_reverse_transcoder/utils.cc, source/extensions/filters/http/oauth2/filter.cc, test/common/http/utility_test.cc
Commit Message: use PercentEncoding library instead of incomplete ad-hoc mapping
I'm pretty sure this is a no-op since pem certificates are base-64 encoded. But there's no reason to use absl::StrReplaceAll here with an incomplete, ad-hoc url-encoding character set instead of the optimized, complete percent encoding library function.
AFAICT there is nothing query parameter specific in the implementation of urlEncodeQueryParameter. Query parameters are url-encoded the same way any other data would be url-encoded.
Same as #38749
=> use PercentEncoding library instead of incomplete ad-hoc mapping

source/common/upstream/cds_api_helper.cc
Clarify the log message that counts inputs to `onConfigUpdate` to say that its numbers are derived from the CDS response.  The existing message was especially confusing for SotW because you don't indicate removed responses in SotW as you do in delta: Envoy just finds every cluster not present in the CDS response (including non-CDS clusters!) and calls them "removed", which can be confusing/alarming if you don't know what the code emitting the log message is actually doing.
And improve the log message that actually counts what changes were applied to include removals, to match what the first one is logging.
=> cds: clarify misleading/incomplete `info` logs

source/common/http/http1/settings.cc, source/common/http/utility.cc, source/common/http/utility.h
Commit Message: http: minor perf improvement for h1 ignored upgrades
Followup to #37642 - minor perf improvements when h/1 ignored upgrades are used.
Testing: N/A
=> http: minor perf improvement for h1 ignored upgrades

test/integration/BUILD
When switching to clang-18 we hit an increased rate of flakines for this test. Looking at the test under perf I could see this entry:
```
60.32%    60.30%  quic_http_integ  quic_http_integration_test  [.]
__sanitizer::StackDepotBase<__sanitizer::StackDepotNode, 1,
20>::Put(__sanitizer::StackTrace, bool*)
```
So significant time is spent inside the MSAN runtime library. What is StackDepotBase? From what I can see this is a structure used to keep track of stacktraces of places in the program that allocate and write to various memory locations (that's part of the origin tracking feature of the MSAN).
The important part is that underneath StackDepotBase has a fixed size (2^20 entries) chaining hash table. And over time, this hash table gets more and more entries and therefore …
=> Shard quic_http_integration_test to reduce flakines under msan

test/integration/quic_http_integration_test.cc
Previously, https://github.com/envoyproxy/envoy/pull/38676 updated the timeout values in `QuicHttpIntegrationTest` to use the `TIMEOUT_FACTOR`. However, the AsyncCertVerification tests still ocassionally crashed due to the TimedCertValidator's validation timer being null if the QUIC handshake timeout didn't expire before the handshake had progressed far enough to create the validation timer.
This commit fixes the issue by slightly increasing the timeout values in the AsyncCertVerification tests. Running the tests several thousand times with and without sanitized build configs generated no failures or crashes.
=> test: Adjust the Quic AsyncCertVerification test timeout values

api/envoy/extensions/filters/http/compressor/v3/compressor.proto, changelogs/current.yaml, docs/root/configuration/http/http_filters/_include/compressor-filter.yaml, docs/root/configuration/http/http_filters/compressor_filter.rst, source/extensions/filters/http/compressor/compressor_filter.cc, source/extensions/filters/http/compressor/compressor_filter.h, test/extensions/filters/http/compressor/compressor_filter_integration_test.cc, test/extensions/filters/http/compressor/compressor_filter_test.cc
Commit Message: Adding support for response codes which should not undergo compression in the Compression filter.
Additional Description: Certain response codes should cause the compression to be skipped, such as 206 Partial Content. This is because compression changes the encoding, whereas range requests, which result in 206, should refer to the encoding, so the compression cannot be applied on top of 206 response.
Risk Level: Low (small optional feature)
Testing: Unit test + Integration Test
Docs Changes: docs/root/configuration/http/http_filters/compressor_filter.rst
Release Notes: Compressor Filter now allows configuration of a list of response codes for which the compression will be skipped . Adding 206 (Partial Content) to the list prevents content-encoding change after a range of …
=> Adding support for response codes which should not undergo compression in the Compression filter.

source/common/stream_info/upstream_address.h, source/extensions/filters/common/rbac/matchers/upstream_ip_port.cc, source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc, source/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter.cc, test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_test.cc, test/extensions/filters/http/rbac/rbac_filter_test.cc, test/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter_test.cc
Commit Message: make UpstreamAddress an InstanceAccessor
Additional Description: this will allow matching on UpstreamAddress with a filter-state IP range matcher It can then be used with `matcher_tree` or within RBAC matching. In a followup PR it will also be possible to simplify the UpstreamIpPortMatcher in RBAC to use a filter state matcher directly.
For us, we can then use it to match on the route depending the the upstream IP set by dynamic_forward_proxy http filter
Testing: Yes
=> make UpstreamAddress an InstanceAccessor

bazel/envoy_build_system.bzl
The external variables - including those set by `--action_env` were not being preserved within `envoy_directory_genrule` invokations.
Setting `use_default_shell_env` makes it honor existing variables.
Example of running a test:
Before this change:
```
(cd /build/bazel_root/base/execroot/envoy && \
exec env - \
GENRULE_OUTPUT_DIR=bazel-out/k8-fastbuild/bin/test/common/router/corpus_from_config_impl.outputs \
/bin/bash -c 'mkdir -p bazel-out/k8-fastbuild/bin/test/common/router/corpus_from_config_impl.outputs && bazel-out/k8-fastbuild/bin/test/common/router/corpus_from_config_impl_sh bazel-out/k8-fastbuild/bin/test/common/router/config_impl_test_static')
...
```
After this change:
```
(cd /build/bazel_root/base/execroot/envoy && \
exec env - \
BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 \ …
```
=> build: Preserve the env in `envoy_directory_genrule`

source/common/router/config_impl.cc, source/common/router/config_impl.h
I described the problem with coverage and possible solutions to it in https://github.com/envoyproxy/envoy/issues/37911#issuecomment-2659837724.
TL;DR: clang source-based coverage (which is what we currently use) is subtly broken when dynamic linking is involved (which is what we currently do for coverage tests).
The issue shows itself as lack of coverage of some functions defined in a header file (class members, free-standing inline functions or function temapltes), even though there are tests that cover it.
The issue is a result of a bug in LLVM/Clang/coverage tooling (it's debatable where exactly is the bug fix should be): llvm/llvm-project#32849.
The issue symptoms are not very predictable, and can be affected by a bunch of factors starting from the order of linking and …
=> Workaround coverage issues observed on clang-18 (part 2)

changelogs/current.yaml, source/extensions/common/wasm/context.cc, source/extensions/common/wasm/context.h
Commit Message: wasm: fix possible crash when resetting context after vm panic
If the wasm plugin send a http call out and panic before the response. Then when the response is arrived, the clean up in the `addAfterVmCallAction` will bypassed. Then, a dirty pending request pointer will be kept in the Context object.
When the Context is destroyed because configuration update or vm reload, the the dangling pointer will crash envoy.
Testing: n/a.
=> wasm: fix possible crash when resetting context after vm panic

source/extensions/filters/http/credential_injector/config.cc, source/extensions/http/injected_credentials/common/factory.h, source/extensions/http/injected_credentials/common/factory_base.h, source/extensions/http/injected_credentials/generic/config.cc, source/extensions/http/injected_credentials/generic/config.h, source/extensions/http/injected_credentials/oauth2/config.cc, source/extensions/http/injected_credentials/oauth2/config.h, test/extensions/http/credential_injector/oauth2/config_test.cc
fix: https://github.com/envoyproxy/gateway/pull/5496#discussion_r1998304248
We should use the initManager in the DualInfo because the Credential Injector can be used for both HCM filter and upstream filter. Using the initManger from the ServerFactoryContext for HCM filter causes the secret to be added to the server initManager when it's already in the initialized state.
Change log should not be required as this fixes a bug introduced in [a RP](https://github.com/envoyproxy/envoy/pull/38398) that just merged after v1.33.0 .
@yanavlasov
=> fix: credential injector init manager

mobile/library/cc/engine.cc, mobile/library/cc/engine.h, mobile/library/common/internal_engine.cc, mobile/library/common/internal_engine.h, mobile/library/common/network/proxy_settings.cc, mobile/library/common/network/proxy_settings.h
Commit Message: Expose proxy setting API to C++ engine
Additional Description: Also updated string arguments to use the modern absl::string_view
Testing: n/a
=> [mobile]Expose proxy setting API to C++ engine

api/envoy/service/ext_proc/v3/external_processor.proto
This PR is to fix some stale ext_proc documentation issue.
There are some ext_proc documentation are only appropriate for 1x1 mode. With the MxN support added in https://github.com/envoyproxy/envoy/pull/34942, those docs need to be fixed.
=> Fix ext_proc documentation for FULL_DUPLEX_STREAMED support

source/extensions/filters/network/ext_proc/ext_proc.h
Apparently there was some bad merge around #38877 which makes the precheck failing on main branch.
https://github.com/envoyproxy/envoy/actions/runs/14137376292/job/39612219566
=> Fixes precheck failure on main

source/extensions/extensions_metadata.yaml
Commit Message: Mark `ClientSideWeightedRoundRobin` LB policy as `alpha`.
Release Notes: Mark `ClientSideWeightedRoundRobin` LB policy as `alpha`.
#34777
=> Mark `envoy.extensions.load_balancing_policies.client_side_weighted_round_robin.v3.ClientSideWeightedRoundRobin` as `alpha`

source/extensions/filters/http/oauth2/filter.cc, test/extensions/filters/http/oauth2/filter_test.cc
Introduced by #37849
It is clear that `code_verifier_cookie_settings_` is not set to the `FilterConfig`, and only the default is used.
Docs Changes:
=> oauth2: fix the code_verifier_cookie config is not set

api/envoy/config/route/v3/route_components.proto, changelogs/current.yaml, source/common/router/config_impl.cc, source/common/router/config_impl.h, test/common/router/BUILD, test/common/router/config_impl_test.cc
adding a route matcher on filter state. This will allow to match on filter state in the router.  Filter state allows for example to match on IP CIDR which is not the case for dynamic metadata and it contains information that are not available in the metadata.
This was already done for the matcher tree in the route configuration: https://github.com/envoyproxy/envoy/issues/32807 and https://github.com/envoyproxy/envoy/pull/33175
Commit Message: route match: add filter state
Testing: Test
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md) …
=> route match: add filter state

api/envoy/extensions/dynamic_modules/v3/BUILD, api/envoy/extensions/dynamic_modules/v3/dynamic_modules.proto, api/envoy/extensions/filters/http/dynamic_modules/v3/BUILD, api/envoy/extensions/filters/http/dynamic_modules/v3/dynamic_modules.proto
Commit Message: api: removes 'wip' from dynamic_modules
The dynamic modules API was introduced 6 months ago in #36448 and at the time we didn't have either an implementation or confidence on the configuration API, so it has been marked WIP just in case. 
Now that the initial implementation is done, and the documentation as well as the example repository is hosted at envoyproxy/dynamic-modules-examples, early adopters have already tried it out and we haven't heard any concern about the configuration API, so this commit removes the WIP marker towards the next release of Envoy v1.34.
Note that the extension itself is still in alpha, it follows the same caveat like any other alpha extensions.
Testing: existing tests.
Docs Changes: Already done in the …
=> api: removes 'wip' from dynamic_modules

source/extensions/filters/http/oauth2/filter.cc
it is clear that it is a dead&wrong code, and the oauth_nonce is only used in `redirectToOAuthServer`
Fixes:#38799
Testing:
Docs Changes:
Release Notes:
=> oauth2: remove OAUTH_NONCE build trail dead code

source/extensions/extensions_metadata.yaml
This extension is extremely widely used, and is covered by the security policy.
=> raw_buffer: mark as trusted security posture

mobile/library/cc/engine_builder.h, mobile/test/cc/unit/envoy_config_test.cc
From experimental analysis, a DNS query timeout of 120s and a HTTP/2 keep alive timeout of 15s is most optimal.
=> mobile: Update EngineBuilder defaults

CODEOWNERS, api/envoy/extensions/filters/http/health_check/v3/health_check.proto, test/extensions/filters/http/health_check/health_check_test.cc
The filter has always treated a missing cluster in `cluster_min_healthy_percentages` as a failure. Documenting and adding a test for this case.
Testing: added test
=> health_check: clarify docs about missing cluster and add test

source/extensions/common/aws/credential_providers/container_credentials_provider.h, source/extensions/common/aws/metadata_credentials_provider_base.h
Commit Message: chore: move expiration format for use in multiple providers
Additional Description: Minor fix to relocate a common string from inside container credential provider to metadata credential provider, and address a couple of clang18 warnings
Risk Level: Negligible
Testing: 
Docs Changes:
Release Notes:
=> chore: move expiration format for use in multiple providers

api/envoy/extensions/filters/http/jwt_authn/v3/config.proto, api/envoy/extensions/filters/http/oauth2/v3/oauth.proto, changelogs/current.yaml, source/extensions/filters/http/jwt_authn/filter_config.cc, source/extensions/filters/http/jwt_authn/filter_config.h, source/extensions/filters/http/oauth2/filter.cc, source/extensions/filters/http/oauth2/filter.h, test/extensions/filters/http/oauth2/filter_test.cc
This addresses an existing issue (oauth2) as well as one that doesn't have an associated issue, but is still useful (jwt_authn)
Commit Message: Add stat_prefix to oauth2 and jwt_authn filters
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes: #38283
=> Add stat_prefix to oauth2 and jwt_authn filters

source/common/quic/envoy_quic_utils.cc, test/common/quic/envoy_quic_utils_test.cc, test/integration/buffer_accounting_integration_test.cc
Previously, the QUICHE error `quic::QUIC_STREAM_CANCELLED` was mapped to `StreamResetReason::OverloadManager`, but that was a questionable choice because the OverloadManager has specific implications (like dealing with overload and memory management of buffers).
This commit changes two things:
1. `quic::QUIC_STREAM_CANCELLED` is mapped to either `LocalReset` or `RemoteReset`.
2. `StreamResetReason::OverloadManager` is mapped to `quic::QUIC_STREAM_EXCESSIVE_LOAD`, which seems like a more appropriate choice to convey the semantics of the overload manager behavior.
Testing: Unit/Integration
=> quic: Update the reset reason mappings for QUIC_STREAM_CANCELLED

source/common/quic/BUILD, source/common/quic/envoy_quic_server_connection.cc, source/common/quic/envoy_quic_server_connection.h, source/common/quic/quic_network_connection.h, test/common/quic/envoy_quic_dispatcher_test.cc, test/common/quic/envoy_quic_server_session_test.cc, test/integration/protocol_integration_test.cc
Commit Message: Populate counter downstream_cx_tx_bytes_total for HTTP/3.
Testing: Added DownstreamProtocolIntegrationTest.DownstreamCxStats
Docs Changes:
Release Notes:
=> quic: Populate counter downstream_cx_tx_bytes_total for HTTP/3.

source/extensions/dynamic_modules/abi.h, source/extensions/dynamic_modules/abi_version.h, source/extensions/dynamic_modules/sdk/rust/src/lib.rs, source/extensions/filters/http/dynamic_modules/BUILD, source/extensions/filters/http/dynamic_modules/abi_impl.cc, test/extensions/dynamic_modules/http/BUILD, test/extensions/dynamic_modules/http/abi_impl_test.cc, test/extensions/dynamic_modules/http/filter_test.cc, test/extensions/dynamic_modules/test_data/rust/http.rs
Commit Message: add filter state support for dynamic modules http filter
Additional Description: With filter state support, dynamic modules rust filter can get filter state from envoy
=> dynamic_modules: add filter state support for http filter

docs/root/start/sandboxes/index.rst
Commit Message: docs: link to the moved sandboxes example project
Additional Description: since the move of the sandboxes to the examples project the link to the getting started for developers has been broken.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: link to the moved sandboxes example project

source/extensions/filters/http/ext_proc/BUILD, source/extensions/filters/http/ext_proc/client_impl.cc, source/extensions/filters/http/ext_proc/client_impl.h, test/per_file_coverage.sh
In #38898 @botengyao added an exception for the ext_proc tests for coverage. That's because clang source based coverage reported missing coverage for the comments (the desirable behavior here is that comments are not counted in the coverage reports).
Digging through it, what I realized is that for only some tests report counters for the comments. And all the tests that report thos bogus counters don't actually exercise the affected code.
I still don't fully understand what triggers the issue here, but that observation suggests a workaround that this PR implements. I basically remove dependency on the grpc_client_impl.h from the tests that don't need it.
I started a thread on LLVM discussions (https://discourse.llvm.org/t/llvm-source-based-coverage-sometimes-generates-counte …
=> Fix coverage reports for ext_proc tests

source/common/quic/active_quic_listener.cc, source/common/quic/envoy_quic_server_session.cc, test/common/quic/envoy_quic_server_session_test.cc
Commit Message: Downgrade connection-ID and worker-index mismatch from assert to error when kernel_worker_routing_ is true.
Additional Description: kernel_worker_routing is not enabled atomically on the server side. If there is a QUIC client talking to server during the kernel_worker_routing setup, the cid and worker-index mismatch assertion can trigger, which is not desirable. If packet routing is not working as intended, the new error will show up in logs. 
=> Downgrade connection-ID and worker-index mismatch from assert to error.

source/common/version/BUILD, source/common/version/version.cc
Change-Id: I27552abf959a501cd592fe7fa1e5ac7d67e4ddff
Commit Message: Directly pass through boringssl's `FIPS_mode` status instead of depending on the build flag. This is useful when boringssl is forced to compile in the FIPS mode (e.g. by source code modification to set the build flag).
Additional Description: none
Risk Level: low, a release assert was already present.
Testing: yes
=> fips: prefer self-reported status over a build flag

source/extensions/filters/http/grpc_json_reverse_transcoder/filter.cc
Commit Message: Disable exceptions thrown by nlohmann's json parser
Additional Description: The current implementation uses the `accept` function to check the validity of the json string before parsing it. This PR removes the call to `accept`, disables the exceptions thrown by the `parse` function and checks if `parse` retuns a discarded json object for the validity of the json string.
Testing: No extra testing needed, the current tests are sufficient to test this change.
=> Disable exceptions thrown by the json parser

bazel/external/spdlog.BUILD, source/extensions/compression/gzip/decompressor/zlib_decompressor_impl.cc
This should have been done originally, since this is a risk on the dataplane if input to spdlog causes an exception. It is better to produce a truncated log output than crash.
Risk Level: Low, we do not rely on exceptions in spdlog
=> Disable exceptions in spdlog

api/envoy/config/core/v3/address.proto, test/common/upstream/health_checker_impl_test.cc, test/extensions/health_check/event_sinks/file/file_sink_impl_test.cc
Extends SocketAddress to allow us to specify the network namespace of the socket. This is an API-only change and it is hidden, since there is no implementation.
Addresses https://github.com/envoyproxy/envoy/issues/38947
=> socket: Add network namespace parameter to SocketAddress proto

source/extensions/filters/listener/http_inspector/config.cc, source/extensions/filters/listener/http_inspector/http_inspector.cc, source/extensions/filters/listener/http_inspector/http_inspector.h, test/extensions/filters/listener/http_inspector/http_inspector_test.cc
Backport PR #37002 to release 1.32
http_inspector dynamic buffering
Changed the buffering behavior of HttpInspector. Previously, a static buffer of 8KB was inspected, and anything larger (e.g. a GET request with >8KB of params) would fail. Now, there is a configurable initial_read_buffer_size in HttpInspector that, and if the HTTP version is not identified with that amount of request buffered, it will iteratively double up to 64KB.
Testing: Added unit tests.
=> backport to rel1.32: http_inspector dynamic buffering #37002

test/per_file_coverage.sh
Previously, the coverage percentage was 93.2, but a recent change has made CI very flakey saying that coverage for source/common/quic is at 93.1. Still haven't pinpointed which change introduced the lessening coverage, but temporarily reducing to 93.1 so CI isn't so flakey while we pinpoint the PR and address the coverage gap.
Open issue: https://github.com/envoyproxy/envoy/issues/39076
=> ci/coverage: Temporarily reduce source/common/quic coverage to 93.1

source/extensions/filters/network/redis_proxy/conn_pool_impl.cc, test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc, test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc
Commit Message: redis proxy: fix infinite loop in shardSize(), adding an upper limit and returning unique hosts
The KEYS command caused Envoy's redis_proxy to hang indefinitely
because the shardSize() function would enter an infinite loop when
chooseHost() never returned nullptr. This prevented Envoy from being
terminated with TERM or INT signals. This fix introduces an upper bound
(MaxSlot) on the loop and keeps track of unique hosts returned by
chooseHost(). Once the loop completes, shardSize() correctly returns
the number of shards instead of 0, preventing the infinite loop.
Testing: added a unit test to make sure shardSize() does not count duplicate hosts and an integration test for a simple Keys Request. Both of these tests failed prior to …
=> redis_proxy: fix infinite loop in shardSize(), adding an upper limit and returning the number of unique hosts

api/envoy/admin/v3/clusters.proto
This PR add some clarification and change the clusters doc to use proper note annotations.
**Preview Link:** https://storage.googleapis.com/envoy-pr/66be614/docs/api-v3/admin/v3/clusters.proto.html
---
**Commit Message:** docs: add some clarifications and use proper note annotations in clusters docs
**Additional Description:** Change the docs to use proper note annotations.
=> docs: add some clarifications and use proper note annotations in clusters docs

test/integration/protocol_integration_test.cc
This should hopefully fix some flakes on sanitized builds in CI, such as https://github.com/envoyproxy/envoy/actions/runs/14408964144/job/40412203326.
=> tests: Adds TIMEOUT_FACTOR to TestDownstreamResetIdleTimeout

source/extensions/clusters/eds/eds.cc
There was missing error handling when this code was changed to not use execeptions. The `info_` pointer may be nullptr if the `creation_status` is not succesful, which is dereferenced to get a stats scope.
Testing: Missing
Docs Changes:
Release Notes:
=> eds: fix crash for invalid configuration

.devcontainer/setup.sh
Commit Message: Modify devcontainer config to complete clang default
A fresh devcontainer before this change fails [for me] to compile `bazel build --announce_rc @com_envoyproxy_protoc_gen_validate//:protoc-gen-validate`.
This seems to be a bit of an ambiguous thing, in that an apparently identical container from `run_envoy_docker.sh` will build the same thing successfully, with identical bazelrc config according to the `--announce_rc` output - apparently in that container it defaults to a gcc config, while the devcontainer seemingly defaults to a weird incomplete partial clang config, which makes it try to link with `ld.lld` versus the gcc's `ld.gold` linker.
Since the clang config is already pushed by the devcontainer in a file that says "delete this if you don't …
=> Modify devcontainer config to complete clang default

api/envoy/extensions/transport_sockets/tls/v3/common.proto, changelogs/current.yaml, envoy/ssl/BUILD, envoy/ssl/context_config.h, source/common/tls/context_config_impl.cc, source/common/tls/context_config_impl.h, source/common/tls/context_impl.cc, test/common/tls/ssl_socket_test.cc, test/mocks/ssl/mocks.cc, test/mocks/ssl/mocks.h
Change-Id: Ie870267f35831663ee424dc8e4c5bc1132d19ba2
Commit Message: Add an xDS config to set BoringSSL compliance policy for FIPS. Since a given proxy is allowed to serve both FIPS and non-FIPS traffic, xDS is the appropriate configuration knob to support mixed serving.
Risk Level: low, new field
Testing: add a test to verify the policy restriction
Fixes #31746
=> fips: add compliance policy to TLS context

docs/root/start/quick-start/configuration-dynamic-control-plane.rst
fix typo in configuration-dynamic-control-plane.rst
=> docs: fix typo in configuration-dynamic-control-plane.rst

changelogs/current.yaml, source/extensions/clusters/eds/eds.cc, test/extensions/clusters/eds/eds_test.cc
There was missing error handling when this code was changed to not use execeptions. The `info_` pointer may be nullptr if the `creation_status` is not succesful, which is dereferenced to get a stats scope.
=> eds: fix crash for invalid configuration (#39083)

source/extensions/filters/http/grpc_json_reverse_transcoder/filter.cc, test/extensions/filters/http/grpc_json_reverse_transcoder/filter_test.cc
Commit Message: Map the whole 2xx HTTP range to OK gRPC response status
Additional Description: The reverse transcoder currently maps only 200 to OK status. This PR maps the whole range of 2xx status codes to the OK gRPC response status.
Testing: Added unit test to test the change
=> Map the whole 2xx range to OK gRPC response status

api/envoy/config/listener/v3/listener.proto
setting max_connections_accept_per_socket_event value will limit the cost of per event and benefit overload management without impact of the performance. 
Testing:
Docs Changes:
Release Notes:
=> listener: advise setting max_connections_accept_per_socket_event

envoy/upstream/load_balancer.h, source/common/http/filter_manager.cc, source/common/http/filter_manager.h, source/common/upstream/cluster_manager_impl.cc, source/common/upstream/host_utility.cc, source/common/upstream/host_utility.h, test/common/upstream/cluster_manager_impl_test.cc, test/common/upstream/host_utility_test.cc
Commit Message: override host: fix the potential lifetime problem and improve the code
In the previous implmentation, the setUpstreamOverrideHost method will assume the caller will maintian the lifetime of the host address string. This is true for the stateful session filter, but it's false for the lua filter.
Ths PR change the implementation of setUpstreamOverrideHost to copy and store the host address into the filter chain manager to avoid potential lifetime problem.
This PR also add more comment to the upstream override host to make it more clear.
Testing: n/a.
=> override host: fix the potential lifetime problem and improve the code

api/envoy/extensions/filters/http/grpc_json_reverse_transcoder/v3/transcoder.proto, changelogs/current.yaml, docs/root/configuration/http/http_filters/grpc_json_reverse_transcoder_filter.rst, source/extensions/filters/http/grpc_json_reverse_transcoder/filter.cc, source/extensions/filters/http/grpc_json_reverse_transcoder/filter_config.cc, source/extensions/filters/http/grpc_json_reverse_transcoder/filter_config.h, test/extensions/filters/http/grpc_json_reverse_transcoder/filter_test.cc, test/proto/bookstore.proto
Commit Message: Make json print option configurable for gRPC JSON reverse transcoder
Additional Description: The print options for transcoding from protobuf to json were initially set to a default value with no optional available for the user to configure them. This PR make those options configurable via the filter config.
Testing: Add the unit tests to test the feature.
Docs Changes: Removes the details about the restriction.
Release Notes: Added the notes about this to the changelog.
=> Configurable print options for reverse transcoder

bazel/boringssl_fips.patch, bazel/repository_locations.bzl
This PR bumps up Boring SSL from **v130.0.6723.69** to **v135.0.7049.84**
---
**Commit Message:** deps: bump up `boring_ssl` to 135.0.7049.84
**Additional Description:** Bump up Bring SSL version from **v130.0.6723.69** to **v135.0.7049.84**
=> deps: bump up boring_ssl to 135.0.7049.84

bazel/BUILD
Change-Id: I2684854733934a64a5804f8a9bc77704cc6eed86
Commit Message: Fix FIPS builds on ARM, broken by https://github.com/envoyproxy/envoy/pull/38403
=> fips: fix ARM builds

source/common/common/trie_lookup_table.h, test/common/common/trie_lookup_table_test.cc
Commit Message: Add findMatchingPrefixes to TrieLookupTable
Additional Description: This is a small step towards #38726 and/or #38986, which both want to walk up the set of "worse matches" on a subtree miss.
Risk Level: None on its own, not yet used.
Testing: Added test cases.
=> Add findMatchingPrefixes to TrieLookupTable

changelogs/current.yaml, source/extensions/filters/common/ext_authz/ext_authz.h, source/extensions/filters/common/ext_authz/ext_authz_grpc_impl.cc, source/extensions/filters/http/ext_authz/ext_authz.cc, source/extensions/filters/http/ext_authz/ext_authz.h, test/extensions/filters/common/ext_authz/ext_authz_grpc_impl_test.cc, test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc, test/extensions/filters/common/ext_authz/test_common.cc, test/extensions/filters/common/ext_authz/test_common.h, test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc, test/extensions/filters/http/ext_authz/ext_authz_test.cc, test/extensions/filters/http/ext_authz/logging_test_filter.cc, test/extensions/filters/http/ext_authz/logging_test_filter.proto
Commit Message: Add grpc status to ExtAuthzLoggingInfo in ext authz http filter
If the gRPC is used, there will be gRPC status available. Add grpc status to ExtAuthzLoggingInfo in ext authz http filter for logging purpose.
Testing: unit & integration tests
Release Notes: changelog updated
=> Add grpc status to ExtAuthzLoggingInfo in ext authz http filter

mobile/library/common/internal_engine.cc, mobile/test/common/integration/client_integration_test.cc, source/common/runtime/runtime_features.cc, source/extensions/clusters/dynamic_forward_proxy/cluster.cc, source/extensions/common/dynamic_forward_proxy/dns_cache.h, source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc, source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h, test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc, test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc, test/extensions/common/dynamic_forward_proxy/mocks.cc, test/extensions/common/dynamic_forward_proxy/mocks.h
In Mobile, whenever there is a network change, there's a check to see if there is IPv6 connectivity on the current network. If there is no IPv6 connectivity and the `dns_cache_set_ip_version_to_remove` runtime guard is true, the IPv6 addresses would get filtered out from the DNS lookup response.
This is problematic because if there is a network change and the device now has IPv6 connectivity, the DNS cache will have filtered out the IPv6 addresses already and won't be able to use them to connect to the peer.
This change fixes the issue by storing all resolved IP addresses in the DNS cache, and only filtering out the IP address families that don't have connectivity in the DFP cluster. This has the further benefit of avoiding having to re-resolve DNS host entries whenever there is a network …
=> dfp: Don't filter IP address families from the DNS cache

.bazelrc
Commit Message: fuzzing: fix a fuzzers issue to support exceptions
When trying to build and run fuzzers that may throw an exception (e.g., `bazel build //test/common/http:path_utility_fuzz_test --config=asan-fuzzer`) the following error occurs:
```
$ bazel-bin/test/common/http/path_utility_fuzz_test /tmp/corpus
INFO: found LLVMFuzzerCustomMutator (0x555ec3b27058). Disabling -len_control by default.
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3031084950
INFO: Loaded 1 modules   (2436830 inline 8-bit counters): 2436830 [0x555ecf049c40, 0x555ecf29cb1e),
INFO: Loaded 1 PC tables (2436830 PCs): 2436830 [0x555ecf29cb20,0x555ed17cb900),
INFO:        5 files found in /tmp/corpus
INFO: -max_len is not provided; libFuzzer will not generate inputs …
```
=> fuzzing: fix a fuzzers issue to support exceptions

bazel/external/boringssl_fips.genrule_cmd
There is a bad interaction between Bazel and Go file embedding. Basically, Go file embedding does not allow embedding non-regular files (like symlinks), but when building things locally with Bazel it instead of copying all the required files into the directory where the action is executed creates symbolic links instead, which breaks Go.
We worked around known cases of this issue in the BoringSSL FIPS build script by copying files that we know are embedded and therefore will break Bazel build. However, after updating BoringSSL version it seems like we now have some new cases of this issues and this PR tries to address that.
NOTE: There was a proper workaround implemented for this on Go side that would not require us to play whackamole ( …
=> Fix local FIPS builds of BoringSSL in Envoy

source/extensions/filters/http/dynamic_modules/filter.cc, source/extensions/filters/http/dynamic_modules/filter.h, test/extensions/dynamic_modules/http/integration_test.cc, test/extensions/dynamic_modules/test_data/rust/http_integration_test.rs
Commit Message: dynamic_modules: prevent reentrance on local reply
LocalReply of the stream callbacks can cause a reentrance. For example, it causes encodeHeaders to be called inline on top of the call to LocalReply. That causes a few problems e.g. multiple mutable references in Rust. In practice, modules won't need these callbacks to be called again since at the callsite of LocalReply, they already know all the details. This adds a boolean flag to prevent that and added a test that would fail otherwise. Note that this behavior matches the one of Wasm extension.
Testing: done
=> dynamic_modules: prevent reentrance on local reply

test/per_file_coverage.sh
Additional Description: lowering quic coverage threshold due to https://github.com/envoyproxy/envoy/actions/runs/14514384782/job/40720069262. The PR does not change any source code line but seems like it triggers the coverage failure. @phlax
=> lower quic coverage threshold

CODEOWNERS
I noticed this since https://github.com/envoyproxy/envoy/pull/39213 is being ready for review but no reviewers are requested
=> Add /*/ prefix to oauth2 owners

.devcontainer/setup.sh
Additional Description: After recent PR #39082 devcontainer builds are failing due to linking issue. 
Testing: none
=> Fix devcontainer link issue

api/envoy/type/matcher/v3/string.proto
This PR addresses some typos in the String Matcher docs. We have addressed the typo in the docs for `suffix` matcher where in the note it was still incorrectly pointing out that `prefix` can't be empty. It also switched the note annotation to use the newer way.
---
**Commit Message:** docs: address typos in the string matcher docs
**Additional Description:** This PR addresses some typos in the String Matcher docs.
=> docs: address typos in the string matcher docs

test/extensions/filters/http/ext_proc/ext_proc_benchmark_test.cc, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/filter_test.cc, test/extensions/filters/http/ext_proc/http_client/ext_proc_http_integration_test.cc, test/extensions/filters/http/ext_proc/mutation_utils_test.cc
WKT field should always be explicitly encoded based on the API guide: https://github.com/envoyproxy/envoy/blob/main/api/API_VERSIONING.md#backwards-compatibility
Fix ext_proc filter tests which are not encoding WKT "append" field explicitly: https://github.com/envoyproxy/envoy/blob/277a594b99a75f8b4c5bfbea54f0694bf7e9c672/api/envoy/config/core/v3/base.proto#L469
This PR is part of the efforts to force the ext_proc servers to explicitly encode "append", which will be the starting point to support "append_action".
=> ext_proc: explicitly encode append field in tests

api/envoy/extensions/load_balancing_policies/common/v3/BUILD, api/envoy/extensions/load_balancing_policies/common/v3/common.proto, docs/root/configuration/upstream/cluster_manager/cluster_runtime.rst, source/extensions/load_balancing_policies/common/load_balancer_impl.cc, source/extensions/load_balancing_policies/common/load_balancer_impl.h, test/common/upstream/load_balancer_simulation_test.cc, test/extensions/load_balancing_policies/random/random_lb_simulation_test.cc, test/extensions/load_balancing_policies/round_robin/round_robin_lb_test.cc, test/extensions/load_balancing_policies/subset/subset_test.cc
Commit Message: Add force_local_zone to zone-aware routing with min_size option and deprecate force_locality_direct_routing.
Additional Description: Follow-up to https://github.com/envoyproxy/envoy/pull/38756. Adds minimum zone size parameter as a gate to forcing LocalityDirect mode in zone-aware-routing and renames force_locality_direct_routing to force_local_zone.
Risk Level:
Testing:
Release Notes:
Fixes #38561
=> Add min_size option when forcing LocalityDirect in zone-aware-routing

test/common/orca/BUILD, test/common/orca/orca_parser_corpus/foo_bar, test/common/orca/orca_parser_corpus/invalid_json, test/common/orca/orca_parser_corpus/valid_bin, test/common/orca/orca_parser_corpus/valid_bin2, test/common/orca/orca_parser_corpus/valid_json, test/common/orca/orca_parser_corpus/valid_text, test/common/orca/orca_parser_fuzz.proto, test/common/orca/orca_parser_fuzz_test.cc
Commit Message: Add a fuzz test for ORCA parser..
See #35422 for ORCA parser implementation and #6614 for background.
Testing: Fuzz.
Tested: `bazel run //test/common/orca:orca_parser_fuzz_test  --config asan-fuzzer --linkopt=-lc++ -- test/common/orca/orca_parser_corpus`
CC @blake-snyder @adisuissa @wbpcode
=> Add a fuzz test for ORCA parser.

envoy/upstream/upstream.h, source/common/conn_pool/conn_pool_base.cc, source/common/http/conn_manager_config.h, source/common/http/conn_pool_base.cc, source/common/http/conn_pool_base.h, source/common/http/http2/conn_pool.cc, source/common/tcp/conn_pool.cc, source/common/tcp/conn_pool.h, source/common/upstream/upstream_impl.h, source/extensions/filters/network/http_connection_manager/config.h, source/extensions/filters/network/thrift_proxy/config.h, source/extensions/filters/network/thrift_proxy/conn_manager.h, source/server/admin/admin.h, test/common/http/conn_manager_impl_fuzz_test.cc, test/common/http/conn_manager_impl_test_base.cc, test/common/http/conn_manager_impl_test_base.h, test/config/utility.cc, test/config/utility.h, test/mocks/http/mocks.h, test/mocks/upstream/cluster_info.h
1. `max_requests_per_connection` is `uint32Value` in the http options and cluster configs, so no need to use `uint64_t`
2. clean up for both HTTP and TCP active clients in the connection pool to avoid `uint64_t` for any limits and the base `Envoy::ConnectionPool::ActiveClient`are all `uint32_t`.
3. correct comments and other changes for the default.
Testing:
Docs Changes:
Release Notes:
=> core: unify uint32_t in connection pool clients and max_request_per_connection

.github/workflows/_check_coverage.yml, .github/workflows/envoy-checks.yml
Currently Envoy CI uses different RBE backends for different CI targets. EngFlow is one of available backends and we want to migrate most if not all targets to EngFlow.
Other than just making the overall CI setup simpler, EngFlow appear to offer more powerful build grid machines at the moment, plus some additional nice features like automatically scaling memory when build tasks don't fit into available memory.
One specific reason why I'd like to migrate coverage targets to EngFlow is because I want to switch them to static linking to workaround a bug in Clang/LLVM source-based coverage (see llvm/llvm-project#32849).
With currently used Google RBE backend we are having issues with fuzzing coverage tests, as fuzzing tests include a lot of extensions and together with …
=> Switch coverage CI targets to EngFlow

test/extensions/resource_monitors/cpu_utilization/linux_cpu_stats_reader_test.cc
LinuxContainerCpuStatsReader that this test exercises takes two file paths (CPU allocation path and CPU times path) in constructor and both of those construcotr arguments have default values that point to some cgroup files that may or may not exist in the system where the test runs.
When you don't explicitly provide both paths in the constructor in test LinuxContainerCpuStatsReader will fallback to the default value and will try to read and parse the actual cgroup CPU times file /sys/fs/cgroup/cpu/cpuacct.usage and if the file does not exist it will fail.
That's exactly the problem with UnexpectedFormatCpuAllocatedLine test. When it creates LinuxContainerCpuStatsReader it explicitly provides a path to a test CPU allocation file, but does not provide a path to a test CPU …
=> Fix environment-dependent UnexpectedFormatCpuAllocatedLine test

api/envoy/extensions/network/dns_resolver/getaddrinfo/v3/getaddrinfo_dns_resolver.proto, changelogs/current.yaml, source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc, source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.h, test/extensions/network/dns_resolver/getaddrinfo/getaddrinfo_test.cc
Commit Message: Allow getaddrinfo to run in a thread pool. The number of worker threads can be configured.
Additional Description: There's also a minor change to std::move() callbacks for better code performance.
Testing: manual test and unit tests
=> dns: Allow getaddrinfo to run in a thread pool

source/common/common/fine_grain_logger.cc, source/common/common/fine_grain_logger.h
> **Note**:  
> - `0` means **no log print**.  
> - `1` means **log printed**.
| Benchmark                                             | Time             | CPU Time         | Iterations |
|-------------------------------------------------------|------------------|------------------|------------:|
| fineGrainLogFastPath/1024/0                           | 17,527 ns        | 17,523 ns        | 39,987      |
| fineGrainLogFastPath/1024/1                           | 15,710,231 ns    | 15,709,650 ns    | 36          |
| fineGrainLogFastPath/1024/0/process_time/threads:20   | 33,012 ns        | 391,443 ns       | 1,700       |
| fineGrainLogFastPath/1024/1/process_time/threads:20   | 440,901,766 ns   | 615,822,136 ns   | 20          |
| fineGrainLogFastPath/1024/0/process_time/threads:200  | …
=> fine-grain-logger: use memory order acquire and release

mobile/library/cc/engine_builder.cc, mobile/library/cc/engine_builder.h
Commit Message: Add envoy mobile config to set number of threads for getaddrinfo
Testing: n/a
=> [mobile]Add envoy mobile config to set number of threads for getaddrinfo

envoy/server/listener_manager.h, source/common/listener_manager/lds_api.cc, source/common/listener_manager/listener_manager_impl.cc, test/common/listener_manager/listener_manager_impl_test.cc
Commit Message: listener-manager: remove unique_ptr from the failure-state vector
Minor refactor that converts listener-manager failure-state from `vector<unique_ptr<T>>` to `vector<T>`.
Testing: N/A
=> listener-manager: remove unique_ptr from the failure-state vector

bazel/foreign_cc/BUILD, bazel/foreign_cc/icu.patch, bazel/repository_locations.bzl
This PR bumps up the version of `icu` to v77.1
---
**Commit Message:** deps: bump up icu to v77.1
**Additional Description:** Bump up the version of `icu` to v77.1
=> deps: bump up icu to v77.1

source/extensions/common/aws/cached_credentials_provider_base.h, source/extensions/common/aws/credential_providers/container_credentials_provider.cc, source/extensions/common/aws/credential_providers/container_credentials_provider.h, source/extensions/common/aws/credential_providers/instance_profile_credentials_provider.cc, source/extensions/common/aws/credential_providers/instance_profile_credentials_provider.h, source/extensions/common/aws/credential_providers/webidentity_credentials_provider.h, source/extensions/common/aws/credentials_provider.h, source/extensions/common/aws/metadata_credentials_provider_base.cc, source/extensions/common/aws/metadata_credentials_provider_base.h, test/extensions/common/aws/credential_providers/webidentity_credentials_provider_test.cc, test/extensions/common/aws/mocks.h
Commit Message: aws: (chore) remove redundant metadata inheritance
Additional Description: Metadata inherited from cached credentials provider, which is no longer required due to curl deprecation. This patch removes the unused needsrefresh calls and test cases from metadata credential providers.
Testing:
Docs Changes:
Release Notes:
=> aws: (chore) remove redundant metadata inheritance

source/extensions/filters/network/ext_proc/config.cc, test/extensions/filters/network/ext_proc/config_test.cc, tools/code_format/config.yaml
Throw in this PR, but I think a better way is to change the interface of `createFilterFactoryFromProtoTyped` to return `absl:status` to avoid throw for network filters.
Testing:
Docs Changes:
Release Notes:
=> network: add ext proc config check for processing mode and grpc services

contrib/golang/router/cluster_specifier/source/cgo.cc, contrib/golang/router/cluster_specifier/source/go/pkg/api/capi.go, contrib/golang/router/cluster_specifier/source/go/pkg/api/cluster.go, contrib/golang/router/cluster_specifier/source/go/pkg/cluster_specifier/api.h, contrib/golang/router/cluster_specifier/source/go/pkg/cluster_specifier/capi_impl.go, contrib/golang/router/cluster_specifier/source/go/pkg/cluster_specifier/type.go, contrib/golang/router/cluster_specifier/test/golang_integration_test.cc, contrib/golang/router/cluster_specifier/test/test_data/simple/plugin.go
golang extension: implement GetAllHeaders in the cluster_specifier plugin.
Fixes: #38644
- This is my first time working with Envoy and Cgo so there may be better ways to implement this. I used [copyHeaderMapToGo](https://github.com/envoyproxy/envoy/blob/61809bc1377543e3e6493157ab8fc96070867179/contrib/golang/upstreams/http/tcp/source/upstream_request.cc#L384-L414) as a reference for this implementation.
Testing: Integration testing - I would prefer to add some unit testing as well for the Go -> Cgo code, but I didn't see existing examples of this so I wasn't sure if it's common practice.
=> golang extension: implement GetAllHeaders in the cluster_specifier plugin.

source/common/conn_pool/conn_pool_base.cc, source/common/conn_pool/conn_pool_base.h
Rename `state_` to a more descriptive name and make it private. Convert some ASSERTs to ENVOY_BUGs for better detection of accounting bugs.
Testing: non-functional change; existing tests pass
=> conn pool: state variable cleanup and more ENVOY_BUGs

api/envoy/extensions/tracers/opentelemetry/samplers/v3/BUILD, api/envoy/extensions/tracers/opentelemetry/samplers/v3/parent_based_sampler.proto, api/envoy/extensions/tracers/opentelemetry/samplers/v3/trace_id_ratio_based_sampler.proto, bazel/repository_locations.bzl, source/extensions/extensions_build_config.bzl, source/extensions/extensions_metadata.yaml, source/extensions/tracers/opentelemetry/samplers/parent_based/BUILD, source/extensions/tracers/opentelemetry/samplers/parent_based/config.cc, source/extensions/tracers/opentelemetry/samplers/parent_based/config.h, source/extensions/tracers/opentelemetry/samplers/parent_based/parent_based_sampler.cc, source/extensions/tracers/opentelemetry/samplers/parent_based/parent_based_sampler.h, source/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/BUILD, source/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/config.cc, source/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/config.h, source/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/trace_id_ratio_based_sampler.cc, source/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/trace_id_ratio_based_sampler.h, test/extensions/tracers/opentelemetry/samplers/parent_based/BUILD, test/extensions/tracers/opentelemetry/samplers/parent_based/config_test.cc, test/extensions/tracers/opentelemetry/samplers/parent_based/parent_based_sampler_integration_test.cc, test/extensions/tracers/opentelemetry/samplers/parent_based/parent_based_sampler_test.cc, test/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/BUILD, test/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/config_test.cc, test/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/trace_id_ratio_based_sampler_integration_test.cc, test/extensions/tracers/opentelemetry/samplers/trace_id_ratio_based/trace_id_ratio_based_sampler_test.cc
Commit Message: implement TraceIDRatioBased and ParentBased samplers
[A previous issue](https://github.com/envoyproxy/envoy/issues/35016) existed for adding opentelemetry samplers to Envoy so I didn't create a new one. The PR at hand implements two of these samplers.
The implementation and testing strategies are inspired by the OTEL's [Go](https://github.com/open-telemetry/opentelemetry-go) and [CPP](https://github.com/open-telemetry/opentelemetry-cpp) SDKs.
Testing: The PR has unit and integration tests which I've run locally.
Docs Changes:
Release Notes:
=> opentelemetry tracer: implement TraceIDRatioBased and ParentBased samplers 

test/extensions/common/aws/credentials_provider_test.cc
I'm trying to migrate Envoy CI coverage runs from the current Google RBE backends to EngFlow (there is a long story behind that, which I will not cover here).
When we tried to do it last time we hit an issue that on EngFlow for some part of the codebase coverage fell below the threshold and caused CI failures. AWS signer/credential providers code was among those.
Looking at the diff in coverage report before and after, I figured out that coverage for CredentialsProviderChain::onCredentialUpdate was missing.
So how come this code is covered when we use Google RBE backends and not covered when we use EngFlow? While it's hard to conclusively confirm what was the issue in that particular failed EngFlow coverage run, because coverage runs don't show test logs, I believe that …
=> Add unit tests for CredentialsProviderChain::onCredentialUpdate

source/extensions/filters/http/dynamic_modules/filter_config.cc, test/extensions/dynamic_modules/http/filter_test.cc, test/extensions/dynamic_modules/test_data/rust/http.rs
Commit Message: dynamic_modules: fixes crash when config init failed
Previously, there was a bug around the handling of config initialization failure which resulted in a crash, and this commit fixes that. Note that the crash is not as serious as it seems in the sense that this is not caused by downstream inputs, but by a wrong configuration passed by Envoy control planes (or static config).
Testing: done
=> dynamic_modules: fixes crash when config init failed

ci/Dockerfile-envoy
=> build/docker: Fix permissions in distroless image

envoy/server/instance.h, source/server/config_validation/server.h, source/server/server.cc, source/server/server.h, test/mocks/server/instance.cc, test/mocks/server/instance.h
Commit Message: message visitor: use dynamic visitor after main loop started
To close [#31073](https://github.com/envoyproxy/envoy/issues/31073).
The Envoy has two different proto message visitors: static visitor for static configuration and dynamic visitor for dynamic configuration. By default, the only difference is that the static message visitor will reject unknown fields.
The ServerFactoryContext will provide dynamic visitor after the server is initialized.
And the FactoryContext and ClusterFactoryContext will provide dynamic visitor if the related listeners/clusters are added by the xDS API.
The visitor should be selected depends on the scope of xDS configuration. For example, embedded route config should use the visitor provided by the FactoryContext (The …
=> message visitor: use dynamic visitor after main loop started

mobile/library/common/internal_engine.cc, mobile/library/common/network/connectivity_manager.h, mobile/test/java/org/chromium/net/CronetHttp3Test.java, source/common/runtime/runtime_features.cc
This commit adds a FALSE runtime guard
`drain_conn_pools_on_network_change` to drain network connections on network change events when DNS refresh on network change is disabled.
The preference is to *not* refresh DNS on network change but to drain the connections only.  Right now, refreshing DNS is the only way to drain connections too, but the goal of this commit is to decouple the two operations and experiment with both.
=> mobile: Adds a runtime guard to drain connections on network change

source/common/formatter/substitution_formatter.h, source/extensions/access_loggers/open_telemetry/substitution_formatter.h
With clang 20.1.* the following code is not compiling due to a `-Wignored-qualifiers` getting promoted into an error. This was changed in [clang 20.1.0](https://releases.llvm.org/20.1.0/tools/clang/docs/ReleaseNotes.html#id242) in the commit https://github.com/llvm/llvm-project/commit/cac67d39362b23466708e464c00ce84abe16bece
See also a simplified example here https://godbolt.org/z/3eWbhsqWM
Risk Level: Pretty small, based on the LLVM commit the `const` was already ignored.
Testing: Unit
=> Fixes to support compiler clang 20.1.*

.github/workflows/_check_coverage.yml
This reverts commit 1858f70e9b0d04a04f5a3eba99449d3998a3317e. It looks like EngFlow cluster is straggling a bit and even if at the moment backlog cleared, we should hold off the Eng Flow migration for coverage for now.
Testing: n/a
+cc @phlax
=> Revert "Switch coverage CI targets to EngFlow (#39436)"

api/envoy/config/bootstrap/v3/bootstrap.proto
The deleted sentence is not correct in that you can at least use an EDS cluster that matches `cluster_manager.local_cluster_name`. We are running Envoy in such a configuration. See [this
comment](https://github.com/envoyproxy/envoy/issues/37867#issuecomment-2773064429) for details.
=> docs: remove incorrect docs about static clusters not being able to be EDS

changelogs/current.yaml, source/common/conn_pool/conn_pool_base.cc, source/common/http/mixed_conn_pool.cc, test/common/http/http2/conn_pool_test.cc, test/common/http/mixed_conn_pool_test.cc
Backport #39310 and #39349
If a connection starts draining while it has negative unused capacity
(which happens if a SETTINGS frame reduces allowed concurrency to below
the current number of requests), that connections unused capacity will
be included in total pool capacity even though it is unusable because it
is draining. This can result in not enough connections being established
for current pending requests.
This is most problematic for long-lived requests (such as streaming gRPC
requests or long-poll requests) because a connection could be in the
draining state for a long time.
Maybe fixes: #39238
Fixed an issue that could lead to too many connections when using
:ref:`AutoHttpConfig
<envoy_v3_api_msg_extensions.upstreams.http.v3.HttpProtocolOptions.AutoHttpConfig>`
if the
established …
=> 1.34: backport two connpool fixes

source/extensions/filters/http/ext_proc/ext_proc.cc, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/filter_test.cc, test/extensions/filters/http/ext_proc/ordering_test.cc
When Envoy is waiting for header response, and new client data arrives Envoy, Envoy should just buffer the data without raising watermarks. Raising watermarks is causing Envoy not sending local reply when the buffer size over the per-connection-limit.
Fixes: https://github.com/envoyproxy/envoy/issues/39365
=> ext_proc: buffered mode is not sending local reply with large request

test/common/grpc/grpc_client_integration_test_harness.h
Commit Message: test: fix test to pass if gRPC returns UNKNOWN instead of an invalid code
Additional Description: As per the [gRPC status codes doc](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md), gRPC implementations may either pass through invalid status codes or convert them to UNKNOWN.  Currently, gRPC C++ passes them through, but in the future we will instead convert them to UNKNOWN.  This change fixes Envoy's test to pass with either behavior, so that when this change happens in gRPC, it will not break Envoy.
Testing: CI
=> test: fix test to pass if gRPC returns UNKNOWN instead of an invalid code

changelogs/current.yaml, source/common/conn_pool/conn_pool_base.cc, source/common/http/mixed_conn_pool.cc, test/common/http/http2/conn_pool_test.cc, test/common/http/mixed_conn_pool_test.cc
Backport #39310 and #39349
If a connection starts draining while it has negative unused capacity (which happens if a SETTINGS frame reduces allowed concurrency to below the current number of requests), that connections unused capacity will be included in total pool capacity even though it is unusable because it is draining. This can result in not enough connections being established for current pending requests.
This is most problematic for long-lived requests (such as streaming gRPC requests or long-poll requests) because a connection could be in the draining state for a long time.
Maybe fixes: #39238
Fixed an issue that could lead to too many connections when using :ref:`AutoHttpConfig
<envoy_v3_api_msg_extensions.upstreams.http.v3.HttpProtocolOptions.AutoHttpConfig>` if the
established …
=> conn pool: fix bugs leading to incorrect conns created (#39446)

contrib/golang/filters/http/source/golang_filter.cc, contrib/golang/filters/http/test/config_test.cc, contrib/sxg/filters/http/source/config.cc, contrib/sxg/filters/http/test/config_test.cc, contrib/sxg/filters/http/test/filter_test.cc, envoy/secret/secret_manager.h, source/common/secret/sds_api.cc, source/common/secret/sds_api.h, source/common/secret/secret_manager_impl.cc, source/common/secret/secret_manager_impl.h, source/common/tls/context_config_impl.cc, source/common/tls/server_context_config_impl.cc, source/extensions/filters/http/oauth2/config.cc, source/extensions/http/injected_credentials/generic/config.cc, source/extensions/http/injected_credentials/oauth2/config.cc, source/extensions/quic/connection_id_generator/quic_lb/quic_lb.cc, test/common/secret/secret_manager_impl_test.cc, test/extensions/filters/http/oauth2/config_test.cc, test/extensions/filters/http/oauth2/filter_test.cc, test/extensions/http/credential_injector/oauth2/config_test.cc, test/extensions/quic/connection_id_generator/quic_lb/quic_lb_test.cc, test/integration/sds_generic_secret_integration_test.cc, test/mocks/secret/mocks.h
Commit Message: use server factory context as priority
Part of #26476
This PR replace `TransportSocketFactoryContext` of secret provider to `ServerFactoryContext`. After this PR, we can clean up the `getTransportSocketFactoryContext()` of FactoryContext and ServerFactoryContext and clusterManagerFactory() of ClusterManager.
Testing: n/a.
=> use server factory context as priority

changelogs/current.yaml, source/extensions/filters/http/rbac/rbac_filter.cc, test/extensions/filters/http/rbac/BUILD, test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
This PR adds the support for `FilterStateInput` in the HTTP RBAC filter.
---
Commit Message:  allowlist `FilterStateInput` for xDS matcher in HTTP RBAC filter.
Additional Description: added support for `FilterStateInput` to be allowed in the xDS matcher inside the HTTP RBAC filter.
Testing: Added Integration & Unit Tests.
=> rbac: allowlist FilterStateInput for xDS matcher in HTTP RBAC

changelogs/current.yaml, source/extensions/filters/network/rbac/rbac_filter.cc, test/extensions/filters/network/rbac/BUILD, test/extensions/filters/network/rbac/integration_test.cc
This PR adds the support for `FilterStateInput` in the Network RBAC filter.
---
Commit Message:  allowlist `FilterStateInput` for xDS matcher in Network RBAC filter.
Additional Description: added support for `FilterStateInput` to be allowed in the xDS matcher inside the Network RBAC filter.
Testing: Added Integration & Unit Tests.
=> rbac: allowlist FilterStateInput for xDS matcher in Network RBAC

api/envoy/config/core/v3/protocol.proto
This PR cleans up the protocol option docs to use the proper note annotations.
---
**Commit Message:** docs: clean up the protocol options docs
**Additional Description:** Clean up the protocol options docs.
=> docs: clean up the protocol options docs

test/integration/python/hotrestart_handoff_test.py
Commit Message: Resolve Python Datetime warnings
Additional Description: This small PR resolves the `datetime` library warnings:
```python
DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC). or datetime.datetime.utcnow()
```
Note that `.replace(tzinfo=None)` allows to keep the original behavior where the time appears as a naive UTC timestamp (i.e., without any timezone offset).
Testing:
Docs Changes:
Release Notes:
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/a …
=> Resolve Python Datetime warnings

source/common/http/conn_manager_utility.cc
constness of 'next_protocol' prevents automatic move during return
=> Perf: allow automatic move of next_protocol

source/extensions/filters/http/rbac/rbac_filter.cc, source/extensions/filters/http/rbac/rbac_filter.h
This reverts commit b2f0304f92a2476f6babf1a17be8bc2563d18eb2.
Instead of doing a fix forward, we are reverting the change which caused #39479. Will do a follow-up with the fixes included.
---
**Commit Message:** Revert "nit: remove unused imports from HTTP RBAC filter & some cleanup (#39465)"
**Additional Description:** Reverting the cleanup nits change which caused a regression in storing the metadata.
**Testing:** Existing Tests
=> Revert "nit: remove unused imports from HTTP RBAC filter & some cleanup (#39465)"

bazel/repository_locations.bzl
This just updates V8 repository leaving currently used tag the same to create baseline. V8 tag update in the followup PR.
=> Use GitHub mirror for V8 sources

envoy/common/matchers.h, source/common/common/matchers.h, source/extensions/filters/network/dubbo_proxy/router/route_matcher.h, source/extensions/string_matcher/lua/match.cc, source/extensions/string_matcher/lua/match.h, test/common/tls/cert_validator/default_validator_integration_test.cc
Commit Message: Make StringMatcher::match consistent
Additional Description: There were instances of `StringMatcher::match` that take `const absl::string_view` and instances that take `absl::string_view` (not const). Making a string_view const is about as meaningful as an argument being `const int`, in that there's little advantage, and for a virtual function significant disadvantage (in that an implementation may want to modify the value, and since it's passed by value there's no reason to not allow it), so my preferred direction of consistency is to remove the non-useful const rather than add it to the other overrides, but I'm happy to go the other way if reviewers have that preference.
My main reason to make it consistent is, the gcc build currently logs over 5000 instances of warnings …
=> Make StringMatcher::match consistent

source/common/tls/cert_validator/san_matcher.cc, source/common/tls/cert_validator/san_matcher.h
Commit Message: Make SanMatcher::match consistent
Additional Description: Function was implemented with a mix of `const GENERAL_NAME*` and `GENERAL_NAME const*`. I expect the latter was the intention, a pointer to an immutable struct, not an immutable pointer to a mutable struct. (Arguably the intention is *both* kinds of const, but there is no meaningful value in the pointer being immutable.)
The current implementation also leads to many warnings in the gcc build of the form
```
./source/common/tls/cert_validator/san_matcher.h:27:16: warning: ‘virtual bool Envoy::Ssl::SanMatcher::match(const GENERAL_NAME*, const Envoy::StreamInfo::StreamInfo&) const’ was hidden [-Woverloaded-virtual]
27 |   virtual bool match(GENERAL_NAME const* general_name, const StreamInfo::StreamInfo&) const {
``` …
=> Make SanMatcher::match consistent

test/extensions/transport_sockets/tcp_stats/tcp_stats_test.cc
Commit Message: tcp_stats: fix a flaky test fixture
Our internal system caught a tcp_stats case that assumed initialization of all the fields of the tcp_info C struct in one of the test fixtures.
This change introduces an explicit initialization of this data-member.
Testing: N/A
=> tcp_stats: fix a flaky test fixture

api/bazel/repository_locations.bzl
Commit Message: deps: update cncf/xds to 2025-05-01 version
Periodic upgrade of the xds repo.
Testing: N/A
=> deps: update cncf/xds to 2025-05-01 version

source/extensions/filters/network/rbac/rbac_filter.cc, source/extensions/filters/network/rbac/rbac_filter.h, test/extensions/filters/network/rbac/filter_test.cc, test/extensions/filters/network/rbac/integration_test.cc
This PR removes an unused import and do some other minor cleanup in the Network RBAC filter.
---
**Commit Message:** nit: remove unused imports from Network RBAC filter & some cleanup
**Additional Description:** Addressed a few minor nits in the Network RBAC filter's code
**Testing:** Existing Tests
=> nit: remove unused imports from Network RBAC filter & some cleanup

docs/root/configuration/http/http_filters/_include/dns-cache-circuit-breaker.yaml, docs/root/configuration/http/http_filters/dynamic_forward_proxy_filter.rst
This PR clarifies the documentation for circuit breakers in Dynamic Forward Proxy to address the confusion raised in #39497.
**Fixes:** #39497
https://storage.googleapis.com/envoy-pr/6d45f12/docs/configuration/http/http_filters/dynamic_forward_proxy_filter.html#circuit-breakers
---
**Commit Message:** docs: clarify Circuit Breakers docs for Dynamic Forward Proxy
**Additional Description:** Add clarification to the documentation for circuit breakers in Dynamic Forward Proxy
=> docs: clarify Circuit Breakers docs for Dynamic Forward Proxy

docs/root/configuration/observability/access_log/usage.rst
Some styling nits in HTTP Access Logs for consistency. Also removed what I could say is a typo in the `DOWNSTREAM_PEER_CHAIN_SERIALS` unless there is actually something called `wserial`.
---
**Commit Message:** docs: some styling nits in the HTTP Access Logs docs
**Additional Description:** Some styling nits in HAL docs for consistency.
=> docs: some styling nits in the HTTP Access Logs docs

envoy/upstream/load_balancer.h, source/common/router/router.cc, source/common/router/router.h, source/common/upstream/load_balancer_context_base.h, source/extensions/clusters/aggregate/lb_context.h, source/extensions/load_balancing_policies/subset/subset_lb.h, test/common/router/router_test.cc, test/common/upstream/load_balancer_context_base_test.cc, test/extensions/clusters/aggregate/cluster_test.cc, test/extensions/load_balancing_policies/subset/subset_test.cc, test/mocks/upstream/load_balancer_context.h
Commit Message: upstream lb context: add method to set headers modifier
First PR to support hash policy in upstream lb. This PR make it possible that the upstream lb could modify the response headers after the response headers is received from upstream server.
This make it's possible to support hash policy in upstream lb (for generated mode of cookie based hash policy), and this may also could be used to support session management in the upstream lb in the future.
Testing: unit.
=> upstream lb context: add method to set headers modifier

source/common/tracing/http_tracer_impl.cc
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> http trace: improve perf to avoid str copy when building response

envoy/upstream/cluster_manager.h, source/common/upstream/cluster_manager_impl.h, source/common/upstream/load_stats_reporter.cc, test/common/upstream/load_stats_reporter_test.cc, test/mocks/upstream/cluster_manager.cc, test/mocks/upstream/cluster_manager.h
Commit Message: load-stats-report: performance improvement by fetching only relevant clusters
When issuing a load-report, Envoy creates a map of clusters (active and warming) from the cluster-manager, and then looks for the relevant clusters that need their load-report emitted.
This PR changes this flow, so the intermediate map is not created, and only the relevant active clusters are fetched on-demand.
Testing: N/A
=> load-stats-report: performance improvement by fetching only relevant clusters

envoy/common/regex.h, source/common/common/matchers.h, source/common/common/regex.h, source/common/tls/cert_validator/san_matcher.h, source/extensions/string_matcher/lua/match.cc, source/extensions/string_matcher/lua/match.h, test/mocks/matcher/mocks.h
Commit Message: Don't hide virtual functions
Additional Description: gcc has a lot of warnings when `match(absl::string_view)` "hides" virtual functions `match(absl::string_view, const Context&)`. For all practical purposes this is not important because the caller always has the base/dynamic type, and the virtual function table has access to both functions, it's just the explicit base-class that has the functions "hidden". However, the thousands of repeated warnings in the gcc build output are bothersome, and it's arguably more correct to not "hide" the functions.
Risk Level: No behavior change.
Testing: Checked gcc CI output - there are now 6 instances of "hidden" in the log, vs 5180 before.
=> Don't hide virtual functions

api/envoy/extensions/filters/http/oauth2/v3/oauth.proto, changelogs/current.yaml, source/extensions/filters/http/oauth2/filter.cc, source/extensions/filters/http/oauth2/filter.h, test/extensions/filters/http/oauth2/config_test.cc, test/extensions/filters/http/oauth2/filter_test.cc, tools/spelling/spelling_dictionary.txt
Commit Message: Add support for [OpenID Connect RP-Initiated Logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) to the OAuth2 filter. This allows Relying Party(Envoy OAuth2 filter, in our case) to request that an OpenID Provider log out the End-User.
Testing: unit test, also verified manually with keycloak.
[Optional Fixes #39373]
=> OAuth2: RP initiated logout

api/envoy/extensions/load_balancing_policies/client_side_weighted_round_robin/v3/client_side_weighted_round_robin.proto
As discussed in #39382 this is something operators should be aware of when using the ORCA LB policy.
So I added a note in the proto file for the ORCA LB policy to show up in the docs.
Testing: N/A
Docs Changes: only docs
=> Adds note in the docs for ORCA Header Propagation

docs/root/intro/arch_overview/advanced/attributes.rst, source/extensions/filters/common/expr/context.cc, source/extensions/filters/common/expr/context.h, test/extensions/filters/common/expr/context_test.cc
Commit Message:expr: add xds.upstream_host_locality_metadata
Testing: done
Docs Changes: done
=> expr: add xds.upstream_host_locality_metadata

api/envoy/config/route/v3/route_components.proto, changelogs/current.yaml, docs/root/configuration/http/http_filters/router_filter.rst, envoy/http/header_map.h, envoy/router/router.h, source/common/http/conn_manager_utility.cc, source/common/http/headers.h, source/common/http/null_route_impl.h, source/common/http/utility.cc, source/common/http/utility.h, source/common/router/config_impl.cc, source/common/router/config_impl.h, source/common/router/delegating_route_impl.cc, source/common/router/delegating_route_impl.h, source/common/router/router.cc, source/common/router/upstream_request.cc, test/common/http/utility_test.cc, test/common/router/config_impl_test.cc, test/common/router/router_test.cc, test/mocks/router/mocks.cc, test/mocks/router/mocks.h
Commit Message: add x-envoy-original-host to keep original host
This PR added a x-envoy-original-host to keep original host value if the host rewriting happens.
Testing: n/a.
=> add x-envoy-original-host to keep original host

bazel/dependency_imports.bzl, bazel/emsdk.patch
Also, install before `proxy-wasm-cpp-sdk` to ensure it is used/patched
Currently its installed after, making our setup redundant
includes patch of https://github.com/emscripten-core/emsdk/pull/1531
the context for this is that its required to use a hermetic llvm toolchain (other than being generally useful)
without it, redundant hackery/patching would be required as the newer platforms way of setting up toolchains expects _something_ to be setup for various bins. Rather than adding a stub i figured add the fix. This has historically been the main blocker to adding llvm toolchains, or using the bazel platforms setup
=> deps/emscripten: Add support for dwp files in wasm builds

api/envoy/config/core/v3/address.proto
Commit Message: (chore): trivial proto format spacing fixup
https://github.com/envoyproxy/envoy/pull/39517 introduced spacing issue that is rejected by pre-commit hooks.
```
INFO: Running command line: bazel-bin/tools/code_format/check_format '--path=/workspaces/envoy' '--clang_format_path=tools/clang-format/clang-format' '--buildifier_path=external/com_github_bazelbuild_buildtools/buildifier/buildifier_/buildifier' '--buildozer_path=external/com_github_bazelbuild_buildtools/buildozer/buildozer_/buildozer' check api/envoy/config/core/v3/address.proto
ERROR: From ./api/envoy/config/core/v3/address.proto
ERROR: ./api/envoy/config/core/v3/address.proto:102: over-enthusiastic spaces
ERROR: check format failed. run 'bazel run //tools/code_format:check_format -- fix'
``` …
=> (chore): trivial proto format spacing fixup

CODEOWNERS
Commit Message: (chore) remove grpc extension from CODEOWNERS
Additional Description: Extensions no longer exists, so this codeowners path is no longer necessary
Testing:
Docs Changes:
Release Notes:
=> (chore) remove grpc extension from CODEOWNERS

source/extensions/config_subscription/grpc/new_grpc_mux_impl.cc, source/extensions/config_subscription/grpc/new_grpc_mux_impl.h
Commit Message: xds: transform recursive call by returning iterator
Minor refactor that changes a recursive call that is done after an entry is not found in the map, to changing the iterator that is returned after adding the resource.
Testing: N/A
=> xds: transform recursive call by returning iterator

api/envoy/extensions/load_balancing_policies/override_host/v3/override_host.proto, source/extensions/load_balancing_policies/override_host/load_balancer.cc, source/extensions/load_balancing_policies/override_host/load_balancer.h, source/extensions/load_balancing_policies/override_host/override_host_filter_state.h, test/extensions/load_balancing_policies/override_host/load_balancer_test.cc
Commit Message: override host: support multiple addresses parsing and cache parsing result
1. The override host lb could parse multiple hosts from single header or single metadata entry. **It's completely compatible with previous implementation.**
2. The initial parsing result will be cached.
Testing: unit.
=> override host: support multiple addresses parsing and cache parsing result

docs/root/configuration/http/http_filters/ext_proc_filter.rst
Signed-off-by: Vincenzo Vicaretti <vvicaretti@zendesk.com>
This PR only updates the documentation without modifying the metrics themselves. I'll leave it to the maintainers to provide guidance on whether renaming the metrics is more appropriate.
Updating the metric name would make it consistent with the other `streams_*` metrics. However, such a change would be more disruptive.
Risk Level:
Testing:
Docs Changes: Update the documentation to reflect the real metrics name
Release Notes:
=> docs: fix ext_proc stream_msgs_received and stream_msgs_sent metrics name

api/envoy/extensions/filters/http/dynamic_forward_proxy/v3/dynamic_forward_proxy.proto
Minor nits in the DFP docs to use the proper notes annotations.
---
**Commit Message:** docs: minor nits in DFP docs to annotate notes correctly
**Additional Description:** Minor nits to use proper notes annotations in DFP.
**Testing:** CI 
=> docs: minor nits in DFP docs to annotate notes correctly

envoy/matcher/matcher.h, source/common/listener_manager/filter_chain_manager_impl.cc, source/common/matcher/exact_map_matcher.h, source/common/matcher/field_matcher.h, source/common/matcher/list_matcher.h, source/common/matcher/map_matcher.h, source/common/matcher/matcher.h, source/common/matcher/prefix_map_matcher.h, source/common/router/config_impl.cc, source/extensions/common/matcher/trie_matcher.h, source/extensions/filters/common/rbac/engine_impl.cc, source/extensions/filters/http/custom_response/config.cc, source/extensions/filters/http/match_delegate/config.cc, source/extensions/filters/http/rate_limit_quota/filter.cc, source/extensions/filters/network/generic_proxy/route_impl.cc, source/extensions/filters/network/match_delegate/config.cc, source/extensions/filters/udp/udp_proxy/router/router_impl.cc, test/common/matcher/exact_map_matcher_test.cc, test/common/matcher/field_matcher_test.cc, test/common/matcher/list_matcher_test.cc, test/common/matcher/matcher_test.cc, test/common/matcher/prefix_map_matcher_test.cc, test/common/matcher/test_utility.h, test/common/ssl/matching/inputs_integration_test.cc, test/extensions/common/matcher/trie_matcher_test.cc, test/extensions/filters/http/proto_api_scrubber/BUILD, test/extensions/filters/http/proto_api_scrubber/filter_config_test.cc, test/extensions/matching/input_matchers/cel_matcher/cel_matcher_test.cc, test/extensions/matching/input_matchers/metadata/dyn_meta_matcher_test.cc, test/extensions/matching/network/common/inputs_integration_test.cc
Commit Message: Clean up Matcher::MatchResult's unnecessary templates
Additional Description: Since #38726 refactored Matcher impls to recurse inside the match function, there is no longer any need for MatchResults to have the capacity to return sub-match-trees, which means they also don't need to be templates. Cleaning this up makes the code much easier to follow. This may have also caught a few locations where the internal recursion wasn't fully updated correctly (minor negative, it does make one `doMatch()` implementation slightly more complicated, but the corresponding `match()` implementation is made much simpler, so still an improvement).
Risk Level: Small, existing tests should be ensuring that behaviors were unchanged.
Testing: Covered by existing tests, which are also cleaner. …
=> Clean up Matcher::MatchResult's unnecessary templates

source/common/tcp_proxy/tcp_proxy.cc, source/common/tcp_proxy/tcp_proxy.h
Commit Message: tcp_proxy: remove internal use_post bool which is redundant
The use_post boolean data-member is coupled with the value of post_path.
Refactored the code to make that coupling explicit, following ODR.
Testing: N/A
=> tcp_proxy: remove internal use_post bool which is redundant

source/extensions/common/aws/credential_providers/iam_roles_anywhere_x509_credentials_provider.cc, source/extensions/common/aws/credentials_provider.h, source/extensions/common/aws/metadata_credentials_provider_base.cc, source/extensions/common/aws/metadata_credentials_provider_base.h, test/extensions/common/aws/credential_providers/container_credentials_provider_test.cc, test/extensions/common/aws/credential_providers/instance_profile_credentials_provider_test.cc, test/extensions/common/aws/credential_providers/webidentity_credentials_provider_test.cc
Commit Message: aws: (chore) implement cache jitter
Additional Description: Adds rng based jitter on cache duration calculations, which was an outstanding TODO item.
Testing: Unit
Docs Changes:
Release Notes:
[Optional Fixes #Issue] https://github.com/envoyproxy/envoy/issues/39239
=> aws: (chore) implement cache jitter

changelogs/current.yaml, docs/root/intro/arch_overview/other_protocols/redis.rst, source/extensions/filters/network/common/redis/supported_commands.cc, source/extensions/filters/network/common/redis/supported_commands.h, source/extensions/filters/network/redis_proxy/command_splitter_impl.cc, source/extensions/filters/network/redis_proxy/command_splitter_impl.h, test/extensions/filters/network/redis_proxy/command_splitter_impl_test.cc
Commit Message: redis_proxy: add support for scan and info
Testing:unit test
Docs Changes: yes(./docs/root/intro/arch_overview/other_protocols/redis.rst, changelogs/current.yaml)
Release Notes:
=> redis_proxy: Add support for SCAN and INFO

api/envoy/extensions/clusters/aggregate/v3/BUILD, api/envoy/extensions/clusters/aggregate/v3/cluster.proto
Commit Message: xDS: add proto to get aggregate cluster config from a separate resource
Additional Description: This allows the actual list of underlying clusters to be updated dynamically from a separate resource, rather than being inlined in the CDS resource.  The idea is that instead of the CDS resource directly including the `ClusterConfig` proto, it will contain the `AggregateClusterResource` proto, which will configure the data plane to fetch the `ClusterConfig` proto via ADS.
Testing: N/A
CC @adisuissa @fuqianggao
=> xDS: add proto to get aggregate cluster config from a separate resource

source/common/tcp_proxy/tcp_proxy.h
Commit Message: tcp_proxy: minor refactor using makeOptRefFromPtr
clean up the code by using makeOptRefFromPtr to convert a pointer to opt-ref.
Testing: N/A
=> tcp_proxy: minor refactor using makeOptRefFromPtr

bazel/BUILD, bazel/external/quiche.BUILD, bazel/external/quiche.bzl, source/common/http/http3/BUILD, source/common/quic/BUILD, source/common/quic/platform/BUILD, source/common/quic/platform/mobile_impl/BUILD, source/extensions/quic/connection_debug_visitor/basic/BUILD, source/extensions/quic/connection_debug_visitor/quic_stats/BUILD, source/extensions/quic/connection_id_generator/deterministic/BUILD, source/extensions/quic/connection_id_generator/quic_lb/BUILD, source/extensions/quic/crypto_stream/BUILD, source/extensions/quic/proof_source/BUILD, source/extensions/quic/server_preferred_address/BUILD, source/extensions/udp_packet_writer/gso/BUILD, test/common/http/http3/BUILD, test/common/listener_manager/BUILD, test/common/network/BUILD, test/common/quic/BUILD, test/common/quic/platform/BUILD, test/extensions/quic/connection_debug_visitor/quic_stats/BUILD, test/extensions/quic/connection_id_generator/quic_lb/BUILD, test/extensions/quic/proof_source/BUILD, test/extensions/quic/server_preferred_address/BUILD, test/integration/BUILD, test/integration/filters/BUILD
This PR re-enables all the QUIC tests for the FIPS build as the FIPS version Envoy uses now ([fips-20220613](https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4735)) has the interface that QUIC supports.
After this, QUIC for FIPS builds are also supported.
I was able to build a FIPS binary with QUIC after this change:
**Fixes:** [#7433](https://github.com/envoyproxy/envoy/issues/7433)
---
**Commit Message:** quic: re-enable QUICHE for FIPS build and all the related tests
**Additional Description:** Re-enable QUIC for FIPS build and un-gate all the related tests
**Testing:** Existing Tests
=> quic: re-enable tests for FIPS build

contrib/golang/router/cluster_specifier/source/golang_cluster_specifier.cc, contrib/golang/router/cluster_specifier/source/golang_cluster_specifier.h, envoy/router/cluster_specifier_plugin.h, envoy/router/router.h, source/common/router/config_impl.cc, source/common/router/config_impl.h, source/extensions/router/cluster_specifiers/lua/lua_cluster_specifier.cc, source/extensions/router/cluster_specifiers/lua/lua_cluster_specifier.h, test/common/router/config_impl_integration_test.cc, test/common/router/config_impl_test.cc, test/extensions/router/cluster_specifiers/lua/lua_cluster_specifier_test.cc, test/mocks/router/mocks.cc, test/mocks/router/mocks.h
Commit Message: cluster specifier: add stream info as input parameter of cluster specifier plugin
Add stream info as input parameter to the ClusterSpecifierPlugin. This is pre PR to support https://github.com/envoyproxy/envoy/pull/39227.
Testing: n/a.
=> cluster specifier: add stream info as input parameter of cluster specifier plugin

docs/root/configuration/http/http_filters/lua_filter.rst
This PR have some cleanup in Lua docs for consistency. We are using the backticks inconsistently throughout right now.
---
**Commit Message:** docs: clean up Lua docs and make it consistent
**Additional Description:** Minor clean up for added clarity on the Lua docs.
=> docs: clean up lua docs and make it consistent

source/common/http/http3/BUILD, source/common/quic/BUILD, source/extensions/filters/network/http_connection_manager/config.cc, source/extensions/quic/connection_debug_visitor/basic/BUILD, source/extensions/quic/connection_debug_visitor/quic_stats/BUILD, source/extensions/quic/connection_id_generator/deterministic/BUILD, source/extensions/quic/connection_id_generator/quic_lb/BUILD, source/extensions/quic/crypto_stream/BUILD, source/extensions/quic/proof_source/BUILD, source/extensions/quic/server_preferred_address/BUILD, test/common/listener_manager/BUILD, test/common/network/BUILD, test/common/quic/BUILD, test/extensions/quic/connection_debug_visitor/quic_stats/BUILD, test/extensions/quic/connection_id_generator/quic_lb/BUILD, test/extensions/quic/server_preferred_address/BUILD, test/integration/BUILD, test/integration/filters/BUILD
This PR migrates everything to use the consistent `envoy_select_enable_http3` macro we have.
---
**Commit Message:** quic: make the FIPS build macros consistent
**Additional Description:** Make BUILD files consistent by using the recommended macro everywhere.
=> quic: make the FIPS build macros consistent

bazel/BUILD, bazel/external/quiche.BUILD, bazel/external/quiche.bzl, source/common/http/http3/BUILD, source/common/quic/BUILD, source/common/quic/platform/BUILD, source/common/quic/platform/mobile_impl/BUILD, source/extensions/filters/network/http_connection_manager/config.cc, source/extensions/quic/connection_debug_visitor/basic/BUILD, source/extensions/quic/connection_debug_visitor/quic_stats/BUILD, source/extensions/quic/connection_id_generator/deterministic/BUILD, source/extensions/quic/connection_id_generator/quic_lb/BUILD, source/extensions/quic/crypto_stream/BUILD, source/extensions/quic/proof_source/BUILD, source/extensions/quic/server_preferred_address/BUILD, source/extensions/udp_packet_writer/gso/BUILD, test/common/http/http3/BUILD, test/common/listener_manager/BUILD, test/common/network/BUILD, test/common/quic/BUILD, test/common/quic/platform/BUILD, test/extensions/quic/connection_debug_visitor/quic_stats/BUILD, test/extensions/quic/connection_id_generator/quic_lb/BUILD, test/extensions/quic/proof_source/BUILD, test/extensions/quic/server_preferred_address/BUILD, test/integration/BUILD, test/integration/filters/BUILD, test/per_file_coverage.sh
This PR cherry-picks the two commits we checked in the main to enable QUIC for FIPS build and parameterize the classes using QUIC.
**Fixes:** https://github.com/envoyproxy/envoy/issues/39821
--- 
**Commit Message:** quic(backport): re-enable FIPS build and related tests
**Additional Description:** Cherry-pick the two FIPS related commits in v1.34
=> quic(backport): re-enable FIPS build and related tests

changelogs/current.yaml, source/server/config_validation/server.cc, source/server/config_validation/server.h, test/config/utility.cc, test/config/utility.h, test/server/config_validation/xds_verifier_test.cc
Commit Message: fix: fix a bug where the validate mode may assert failure
This fixed the bug introduced at https://github.com/envoyproxy/envoy/pull/38740 . To close https://github.com/envoyproxy/envoy/issues/39653.
Risk Level: low, config validation code only.
Testing: unit.
=> [bp/1.34] backport: fix: fix a bug where the validate mode may assert failure (#39761)

source/common/tls/context_impl.cc
Commit Message: tls: Add support for building envoy against newer releases of BoringCrypto FIPS via override_repository
If one uses `build --override_repository=boringssl_fips=/usr/lib/boringssl-fips-static` to compile v1.31 envoy against BoringCrypto FIPS 2023042800 [#4953](https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4953) or the BoringCrypto update stream, the build will fail on an error assertion.
Remove this `#error` assertion, as it is meant to be a reminder to the developers in the development tip, but shouldn't prevent users of stable branches to build envoy against newly certified BoringCrypto FIPS or the BoringCrypto FIPS update stream.
Note the project is compiled against c++20 standard, and thus `#warning` from …
=> [1.31] tls: Add support for building envoy against newer releases of BoringCrypto FIPS via override_repository

source/common/init/target_impl.cc, source/common/init/target_impl.h, test/common/init/manager_impl_test.cc
Additional Description: in case an init target is marked ready before the init manager initialized its targets, the manager will hang forever waiting for the target, but it is already in initialized state. Fixing this by resetting the callback member. When the init manager initializes the targets, if there's no callback, it considers the target as ready.
=> init_target: dispose callback if no watcher

test/coverage.yaml
This PR bumps up the coverage numbers for some existing directories to reflect the current state.
---
**Commit Message:** coverage: adjusting coverage numbers to reflect current state
**Additional Description:** Adjusting coverage numbers for some existing directories to reflect the current state.
=> coverage: adjusting coverage numbers to reflect current state

docs/root/configuration/http/http_filters/lua_filter.rst
This PR updates the example we have for `dynamicTypedMetadata()` in LUA to be more realistic as I just back-ported it in our fork and used it for PPv2.
---
**Commit Message:** lua: update example in the LUA docs
**Additional Description:** Updates the example in docs for `dynamicTypedMetadata()`.
=> lua: update example in the LUA docs

envoy/upstream/cluster_manager.h, source/common/router/config_impl.cc, source/common/router/config_impl.h, source/common/upstream/cluster_manager_impl.h, test/mocks/upstream/cluster_manager.cc, test/mocks/upstream/cluster_manager.h
Commit Message: router: refactor the cluster validation step
Prior to this PR, for every route the cluster-manager will create a temporary map of the known clusters, and that will be used in the validation step. This will incur a temporary memory and time complexity of O(|clusters|).
This change removes the need for the temporary object, by directly querying the cluster-manager if the cluster name is known or not.
Testing: N/A
=> router: refactor the cluster validation step

source/extensions/filters/common/ext_proc/grpc_client_impl.h, source/extensions/filters/http/ext_proc/client_impl.cc, source/extensions/filters/network/ext_proc/client_impl.cc
Commit Message: ext_proc: reference the service-method to avoid copying it
ext-proc's service-method are statically defined in Envoy's code base.
Instead of copying it over to different objects, this PR now uses a string_view to reference the service-method.
Testing: N/A
=> ext_proc: reference the service-method to avoid copying it

api/envoy/service/discovery/v3/discovery.proto
This PR have some cleanup in Discovery Proto for consistency. We are using the backticks inconsistently throughout right now and there are many places where we could convert the items in a list format rather than keeping it in the form of a paragraph.
---
**Commit Message:** docs: clean up discovery docs and make it consistent
**Additional Description:** Minor clean up for added clarity on the discovery docs.
=> docs: clean up discovery docs and make it consistent

CODEOWNERS, OWNERS.md
Commit Message: update codeowner of oauth2
This PR added me and @zhaohuabing as codeowner of oauth2 filter. Thanks for great contributions from @zhaohuabing.
This PR also moved @derekargueta to emeritus code owner list because @derekargueta has no activity for a long time. Thanks for all the great contribution @derekargueta has done. Hope we can meet @derekargueta at community one day again!
Testing: n/a.
=> update codeowner of oauth2

envoy/init/manager.h, source/common/init/manager_impl.cc, source/common/init/manager_impl.h, test/common/init/manager_impl_test.cc, test/mocks/init/mocks.h
Additional Description: adding an option to update the watcher that the init manager notifies when it is done initializing. This will be used for #39141 in next PR. This is needed for cases where the original watcher is being discarded but the init targets are still initializing and are part of an initialization process. Specifically for FCDS - this is required in case an FCDS update is received while a previous listener is warming. In that case, we don't want to allow the new listener to warm up until all targets of the previous listener have also finished warming up, because the FCDS updates are incremental
=> init_manager: add option for updating watcher

docs/root/configuration/advanced/well_known_filter_state.rst, source/common/network/BUILD, source/common/network/ip_address.cc, source/common/network/ip_address.h, source/extensions/filters/common/set_filter_state/BUILD, test/extensions/filters/http/set_filter_state/integration_test.cc
The filter state factory that can be used in the `set-filter-state` HTTP filter are documented in https://www.envoyproxy.io/docs/envoy/latest/configuration/advanced/well_known_filter_state#well-known-filter-state
Unfortunately there is not factory that allows us to filter only on client-IP which means we need two case to parse an IP:
- one for IPv4 `IP:PORT`
- one for IPV6`[IP]:PORT`
This solves it by adding a factory key: `envoy.network.ip` that accept an IP where ever it is v4 or v6
Commit Message: create IP address object factory
Testing: Unit test and locally with custom build
Release Notes: …
=> set_filter_state: create IP address object factory

source/extensions/filters/http/dynamic_modules/abi_impl.cc, source/extensions/filters/http/dynamic_modules/filter.cc, source/extensions/filters/http/dynamic_modules/filter.h, test/extensions/dynamic_modules/http/abi_impl_test.cc, test/extensions/dynamic_modules/http/filter_test.cc, test/extensions/dynamic_modules/http/integration_test.cc, test/extensions/dynamic_modules/test_data/rust/http_integration_test.rs
Commit Message: dynamic_modules: enables accessing headers from generic events
Previously, the header access was done through the header maps passed to decode/encodeHeaders callbacks, and it didn't utilize the headers via decoder/encode callbacks. This changes the code slightly so that it will fallback to it. As a result, now a module can modify/access headers during generic event hook as well as the callout event hook.
Risk Level:
Testing:
Docs Changes: 
=> dynamic_modules: enables accessing headers from generic events

envoy/upstream/cluster_manager.h, source/common/upstream/cluster_manager_impl.h, source/server/admin/config_dump_handler.cc, test/mocks/upstream/cluster_manager.cc, test/mocks/upstream/cluster_manager.h, test/server/admin/config_dump_handler_test.cc
Commit Message: config-dump: refactor to use hasActiveCluster that has constant time complexity
Refactor the config-dump code to use an O(1) call (introduced `hasActiveCluster()`) instead of invoking `clusters()` that is O(n).
Note that the config-dump will later invoke `clusters()` to produce the entire info, but at the places where the code was changed the entire clusters list isn't needed.
Testing: Updated.
=> config-dump: refactor to use hasActiveCluster that has constant time complexity

contrib/golang/common/go/api/api.h, contrib/golang/common/go/api/capi.go, contrib/golang/common/go/api/filter.go, contrib/golang/common/go/api/type.go, contrib/golang/filters/http/source/cgo.cc, contrib/golang/filters/http/source/go/pkg/http/capi_impl.go, contrib/golang/filters/http/source/go/pkg/http/filter.go, contrib/golang/filters/http/source/go/pkg/http/shim.go, contrib/golang/filters/http/source/golang_filter.cc, contrib/golang/filters/http/source/golang_filter.h, contrib/golang/filters/http/source/processor_state.h, contrib/golang/filters/http/test/golang_integration_test.cc, contrib/golang/filters/http/test/test_data/basic/filter.go
Support set upstream override host  in golang filter, developer can call SetUpstreamOverrideHost in DecoderFilterCallbacks, here is the description for SetUpstreamOverrideHost: 
Sets an upstream address override for the request. When the overridden host exists in the host list of the routed cluster
and can be selected directly, the load balancer bypasses its algorithm and routes traffic directly to the specified host.
The strict flag determines whether the HTTP request must strictly use the overridden destination.
When the destination is unavailable/not-found, if strict is set to true, Envoy responds with a 503 Service Unavailable error;
if strict is set to false, Envoy will fall back to its load balancing mechanism.
Notice: host must be a valid IP address(with port).
Here is the …
=> Feature: support SetUpstreamOverrideHost in golang filter

contrib/golang/filters/http/test/golang_integration_test.cc
in the previous PR(https://github.com/envoyproxy/envoy/pull/39754), contrib/golang/filters/http/test/golang_integration_test.cc，line1225-line1228, have wrong comment, so this PR is to Fix the wrong comment .
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> Fix wrong comment in GolangIntegrationTest

api/envoy/extensions/filters/http/oauth2/v3/oauth.proto, changelogs/current.yaml, source/extensions/filters/http/oauth2/filter.cc, source/extensions/filters/http/oauth2/filter.h, test/extensions/filters/http/oauth2/filter_test.cc
Commit Message: oauth2: make CSRF and code verifier token expiration configurable
Additional Description: Currently, the OAuth2 filter hardcodes the values of the CSRF and code verifier tokens to `600s` (10 minutes) . This limits flexibility for use cases where:
- Users need shorter expiration (e.g., high-security scenarios).
- Users need longer expiration (e.g., backward-compatibility).
This PR makes both tokens configurable, adding `default_csrf_token_expires_in` and `default_code_verifier_token_expires_in` fields to the OAuth2 filter configuration. Both default to ``600s`` (10 minutes) if not specified, keeping backward compatibility.
Testing: Added tests for cases where uses sets the values of the new fields in the configuration. The default values are already tested …
=> oauth2: make CSRF and code verifier token expiration configurable

source/extensions/extensions_metadata.yaml
Commit Message: aws: mark lambda and request signing extensions as stable
Additional Description: These extensions are in heavy customer use, so alpha tag is not suitable any more.
Testing:
Docs Changes:
Release Notes:
=> aws: mark lambda and request signing extensions as stable

api/envoy/extensions/filters/http/ratelimit/v3/rate_limit.proto, changelogs/current.yaml, source/extensions/filters/http/ratelimit/ratelimit.h, test/extensions/filters/http/ratelimit/ratelimit_test.cc
Commit Message: add new `failure_mode_deny_percent` optional RuntimeFractionalPercent field to the `type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit `filter, so that if specified, its runtime value overrides the default failure_mode_deny value
Additional Description: the change does not consider deprecating the existing `failure_mode_deny` parameter
Testing: adds unit tests, and manually tested behaviour with the following Envoy config
```yaml
admin:
profile_path: /tmp/envoy.prof
access_log:
- name: envoy.access_loggers.file
typed_config:
"@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
path: /dev/null
address:
socket_address:
address: 0.0.0.0
port_value: 8001
layered_runtime:
layers:
- name: admin
admin_layer: {} …
```
=> http rate limit filter v3: add support for failure_mode_deny runtime overrides

api/envoy/config/tap/v3/common.proto, api/envoy/data/tap/v3/transport.proto, api/envoy/extensions/transport_sockets/tap/v3/tap.proto, changelogs/current.yaml, contrib/tap_sinks/udp_sink/source/udp_sink_impl.cc, contrib/tap_sinks/udp_sink/test/udp_sink_test.cc, docs/root/operations/traffic_tapping.rst, source/extensions/common/tap/tap.h, source/extensions/common/tap/tap_config_base.cc, source/extensions/common/tap/tap_config_base.h, source/extensions/transport_sockets/tap/config.cc, source/extensions/transport_sockets/tap/tap.cc, source/extensions/transport_sockets/tap/tap.h, source/extensions/transport_sockets/tap/tap_config.h, source/extensions/transport_sockets/tap/tap_config_impl.cc, source/extensions/transport_sockets/tap/tap_config_impl.h, test/extensions/common/tap/admin_test.cc, test/extensions/filters/http/tap/common.h, test/extensions/transport_sockets/tap/ssl_tap_integration_test.cc, test/extensions/transport_sockets/tap/tap_config_impl_test.cc
Commit Message: Enhance transport tap buffer trace to send tapped messages based on configured size
For buffer tracing, tapped messages are sent only on connection closure by default. This is suitable for HTTP/1 but not for HTTP/2.
Tapped messages are sent based on the configured size is needed for HTTP/2 and later.
Testing: Done the test in local.
Docs Changes:
Release Notes:
=> Tap/Transport tap Enhance buffer trace to send tapped messages based on configured size

source/common/http/filter_manager.cc, source/common/http/utility.h, source/common/upstream/upstream_impl.h, test/extensions/filters/http/header_mutation/header_mutation_integration_test.cc, test/integration/upstream_http_filter_integration_test.cc
Commit Message: Fixed upstream filter disabled by default
Fixes https://github.com/envoyproxy/envoy/issues/39587
Testing: 
Added tests in the header mutation integration tests to make sure upstream filter can be disabled and re-enabled or vice versa at all config levels.
Docs Changes:
None
Release Notes:
=> Fixed upstream filter disabled by default

source/extensions/filters/listener/tls_inspector/BUILD, source/extensions/filters/listener/tls_inspector/tls_inspector.cc
Commit Message: tls_inspector: add debug log when parseClientHello fails
Additional Description: Had to debug some TLS issues down in BoringSSL and while the metric tls_not_found is incremented, an additional debug log (which might be applicable or not) will be useful for understanding the rejection of the ClientHello
Testing: Compiled, Ran and replicated the issue:
```
tls inspector: parseClientHello failed: error:10000096:SSL routines:OPENSSL_internal:xxxx
```
=> tls_inspector: add debug log when parseClientHello fails

source/common/http/async_client_impl.cc, source/common/http/async_client_impl.h
Commit Message: http: refactor async_client_impl to remove a data-member
Minor refactor to remove the `runtime_` data member, and use the (same) one already stored by the shared-config.
Testing: N/A
=> http: refactor async_client_impl to remove a data-member

bazel/README.md
Commit Message: docs: add test_arg="--" to the build docs
Minor docs update: add test_arg="--" to the build docs
This is true since the latest upgrade of googletest (#39305)
Testing: N/A
=> docs: add test_arg="--" to the build docs

source/common/network/ip_address.cc, source/common/network/ip_address.h
Commit Message: set_fitler_state: code cleanup for IP address object factory
Followup to #39873 - minor refactor - moving the `key()` method to an internal namespace.
Testing: N/A
=> set_fitler_state: code cleanup for IP address object factory

changelogs/current.yaml, source/extensions/filters/listener/tls_inspector/tls_inspector.cc, source/extensions/filters/listener/tls_inspector/tls_inspector.h, test/extensions/filters/listener/tls_inspector/tls_inspector_test.cc, test/extensions/filters/listener/tls_inspector/tls_utility.cc, test/extensions/filters/listener/tls_inspector/tls_utility.h
Commit Message: Use max tls client hello size from boring ssl
Before this change, tls inspector is using 64kb as the max size for tls client hello message but boring ssl library allows only 16kb. Here is the [check in boring ssl library](https://github.com/google/boringssl/blob/main/ssl/tls_record.cc#L133). Because of this mismatch, for any tls client hello with size above 16kb, there are no appropriate stats/warnings reported by envoy. It becomes harder to figure out the issue.
This PR is making envoy's max size for tls client hello same as the boring ssl's max size.
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional [API …
=> tls-inspector: Use max tls client hello size from boring ssl

source/extensions/dynamic_modules/abi.h, source/extensions/dynamic_modules/abi_version.h, source/extensions/filters/http/dynamic_modules/abi_impl.cc, source/extensions/filters/http/dynamic_modules/filter.h, test/extensions/dynamic_modules/http/BUILD, test/extensions/dynamic_modules/http/abi_impl_test.cc
Commit Message: support additional attributes about ssl connection info
Additional Description: new attributes supported: 
- connection.id
- connection.tls_version
- connection.subject_local_certificate
- connection.subject_peer_certificate
- connection.dns_san_local_certificate
- connection.dns_san_peer_certificate
- connection.uri_san_local_certificate
- connection.uri_san_peer_certificate
- connection.sha256_peer_certificate_digest
Signed-off-by: Hieu Do <hieusydo@gmail.com>
=> dynamic_modules: support additional attributes about ssl connection info

source/extensions/network/dns_resolver/apple/apple_dns_impl.cc, source/extensions/network/dns_resolver/cares/dns_impl.cc, source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc, source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.h
Cherry-pick of https://github.com/envoyproxy/envoy/pull/39954
PR to fix https://github.com/envoyproxy/envoy/issues/39142 for 1.34 branch
On strict dns / logical dns resolutions if there are errors on the DNS resolution, the failure logs are getting written only when debug log level enabled and general logs are also in debug level. So, making the general/success logs in the trace level to suppress the general logs when user wants only error logs.
=> DNS Logs: Back-port -  categorising dns non-error logs to trace log levels

api/API_VERSIONING.md
I thought the original statement is kind of ambiguous "...Envoy and the larger xDS ecosystem ...is too widely used to make version bumps realistic."  could be understood as  "too widely used"  as a facilitator of version bumps (instead of a barrier to version bumps).
One could also have said "...Envoy and the larger xDS ecosystem ...is too widely used to make version bumps unrealistic." where "too widely used" is being presented as a barrier to version bumps. 
I just rewrote to make it absolutely clear
Commit Message: Update API_VERSIONING.md to remove ambiguity in a statement
Additional Description: rewrite a potentially ambiguous statement
Testing: none
=> Update API_VERSIONING.md to remove ambiguity.

mobile/library/cc/engine_builder.cc
Since the addition of reloadable_features.reject_empty_trusted_ca_file, empty certs fail validation and cause the program to terminate.
=> mobile: Don't set the trusted CA if the cert is empty

contrib/golang/router/cluster_specifier/source/BUILD, contrib/golang/router/cluster_specifier/source/golang_cluster_specifier.cc, contrib/golang/router/cluster_specifier/source/golang_cluster_specifier.h, envoy/router/cluster_specifier_plugin.h, source/common/router/config_impl.cc, source/common/router/header_cluster_specifier.cc, source/common/router/header_cluster_specifier.h, source/extensions/router/cluster_specifiers/lua/BUILD, source/extensions/router/cluster_specifiers/lua/lua_cluster_specifier.cc, source/extensions/router/cluster_specifiers/lua/lua_cluster_specifier.h, source/extensions/router/cluster_specifiers/matcher/matcher_cluster_specifier.cc, source/extensions/router/cluster_specifiers/matcher/matcher_cluster_specifier.h, test/common/router/config_impl_integration_test.cc, test/common/router/config_impl_test.cc, test/extensions/router/cluster_specifiers/lua/lua_cluster_specifier_test.cc, test/extensions/router/cluster_specifiers/matcher/matcher_cluster_specifier_test.cc, test/mocks/router/mocks.cc, test/mocks/router/mocks.h
Commit Message: router: support random value for cluster specifier plugin
Now, the cluster specifier plugin could also use the random value  to select cluster.
Testing: n/a.
=> router: support random value for cluster specifier plugin

source/common/quic/envoy_quic_stream.h, source/common/quic/quic_filter_manager_connection_impl.cc
Commit Message: add more details to integer overflow/underflow ENVOY_BUG in updateBytesBuffered() and more ENVOY_BUG in EnvoyQuicStream to ensure the stream reports write buffer changes to connection correctly.
Risk Level: low, debug logging
Testing: n/a
=> quic: more ENVOY_BUG for flow control debugging

CODEOWNERS
This PR adds a new entry in the CODEOWNERS file for the new `domain_matcher` extension.
---
**Commit Message:** owners: add an entry in CODEOWNERS for domain_matcher
**Additional Description:** Adds a new entry in the CODEOWNERS file for the new `domain_matcher` extension.
=> owners: add an entry in CODEOWNERS for domain_matcher

api/envoy/config/cluster/v3/cluster.proto, api/envoy/config/endpoint/v3/endpoint.proto, api/envoy/extensions/wasm/v3/wasm.proto
This PR have some cleanup in cluster, endpoint and WASM proto docs for consistency. We are using the new note and warning annotations and the backticks inconsistently throughout right now.
---
**Commit Message:** docs: clean up docs to make them consistent
**Additional Description:** Minor clean up for added clarity on the docs.
=> docs: clean up docs to make them consistent

envoy/config/xds_manager.h, source/common/config/xds_manager_impl.cc, source/common/config/xds_manager_impl.h, source/common/upstream/cluster_manager_impl.cc, test/common/config/xds_manager_impl_test.cc, test/mocks/config/xds_manager.h
Commit Message: xds: start the xdstp-config-source muxes after initializing them
This PR invokes the `start()` method on the xdstp-config-source based muxes at the end of the cluster-manager initialization.
Note that to make it fully compatible with the ADS the `start()` method should be invoked by a callback as described in [this TODO](https://github.com/envoyproxy/envoy/blob/e78d4a515ece03f906939d1f9052278a1b9f3c0d/source/common/upstream/cluster_manager_impl.cc#L397-L399) that was introduced in #30215. I plan to refactor this later as part of this work.
Risk Level: low - not used yet
Testing: Added unit tests
=> xds: start the xdstp-config-source muxes after initializing them

api/envoy/config/trace/v3/opentelemetry.proto, changelogs/current.yaml, source/extensions/tracers/opentelemetry/opentelemetry_tracer_impl.cc, source/extensions/tracers/opentelemetry/tracer.cc, source/extensions/tracers/opentelemetry/tracer.h, test/extensions/tracers/opentelemetry/opentelemetry_tracer_impl_test.cc
Commit Message: Avoid trace span buffer becoming too large
See https://github.com/istio/istio/issues/55439#issuecomment-2883638106 , the sidecar space-inuse flame graph shows sometimes span serialize message grow too large, maybe it's caused by sending span to remote server is too slow. We should avoid this memory growing.
Risk Level: 
Testing:
Docs Changes:
Release Notes:
=> Avoid trace span buffer becoming too large

bazel/repositories.bzl
for building external modules etc you might need the build config setup, but not the rest of envoy's dependencies
=> bazel: Make build config setup public

changelogs/current.yaml, source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc, test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
Replace c-ares with getAddrInfo DNS resolver in DFP integration tests.
It's the 1st step to address: https://github.com/envoyproxy/envoy/issues/39900
This PR also changed DFP cluster DNS resolver creating behavior to honor default DNS resolver configuration in bootstrap. Such behavior exists for strict and logical DNS clusters as here: https://github.com/envoyproxy/envoy/blob/83b36ea36575d09740cf7b1de909bdc603423212/source/common/upstream/cluster_factory_impl.cc#L106.    
The other issue is that currently: DFP sub_cluster_config feature does not support customized DNS resolver configuration as described in https://github.com/envoyproxy/envoy/issues/39694.  By honoring bootstrap default DNS resolver here, it also solved that problem.  Otherwise, when DFP sub_cluster_config is configured, …
=> Replace c-ares with getAddrInfo DNS resolver in DFP integration tests

changelogs/current.yaml, source/common/tls/connection_info_impl_base.cc, test/integration/tcp_proxy_integration_test.cc
If tls connection data was queried before it was available, and empty value was being incorrectly cached, preventing later calls from getting the correct value.
One way this could be triggered was with an access log entry being emitted before the TLS peer certificate was received during the TLS handshake, which can be configured with tcp_proxy.
Fixes #40137
Testing: New test added
=> tls: fix incorrectly cached empty peer certificate values

mobile/test/cc/unit/envoy_config_test.cc, mobile/test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
This is a follow up for https://github.com/envoyproxy/envoy/pull/40027.
=> mobile: Fix tests for not setting the trusted CA when empty

changelogs/current.yaml, source/extensions/extensions_metadata.yaml
oauth2 extension is widely used and has been stable for some time.
Testing: n/a
=> Mark oauth2 extension as stable

changelogs/current.yaml, source/common/tls/connection_info_impl_base.cc, test/integration/tcp_proxy_integration_test.cc
If tls connection data was queried before it was available, and empty value was being incorrectly cached, preventing later calls from getting the correct value.
One way this could be triggered was with an access log entry being emitted before the TLS peer certificate was received during the TLS handshake, which can be configured with tcp_proxy.
Fixes #40137
=> [1.34] tls: fix incorrectly cached empty peer certificate values (#40179)

source/common/runtime/runtime_features.cc, source/extensions/clusters/eds/eds.cc, test/extensions/clusters/eds/eds_test.cc, test/integration/BUILD, test/integration/ads_xdstp_config_sources_integration_test.cc, test/integration/xdstp_config_sources_integration_test.cc
Commit Message: xds-federation: adding EDS using on xds-TP based configs
This PR makes EDS the first xDS-resource-type to support xds-tp based configs, which enables it to be used in a federated-xDS scenario.
This feature is under a runtime flag `envoy.reloadable_features.xdstp_based_config_singleton_subscriptions` which is disabled by default. Once we get to test it end-to-end, and add a few more xDS-resource types to the support, it could be enabled by default.
Risk Level: low - disabled by default
Testing: Added both unit and integration tests.
Docs Changes: not yet
Release Notes: not yet
=> xds-federation: adding EDS using on xds-TP based configs

mobile/library/common/network/connectivity_manager.cc, mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java, mobile/library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java, mobile/library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java, mobile/library/java/org/chromium/net/impl/NativeCronvoyEngineBuilderImpl.java, mobile/library/jni/jni_impl.cc, mobile/library/kotlin/io/envoyproxy/envoymobile/AndroidEngineBuilder.kt, mobile/library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt, mobile/test/java/org/chromium/net/CronetHttp3Test.java
Commit Message: these tests failed to verify the desired behavior that existing connections are drained upon network change events. And they failed when run individually. As the code evolved over time, EM no longer drains connections immediately upon network change events if it's configured to refresh DNS at that time. But rather DNS refreshment will drain each host upon resolution completion. `networkChangeWithDrains/networkChangeNoDrains` tests have been always skipping draining connections because of this. These tests should be run with DNS refreshment disabled upon network change to test the draining behavior. To disable DNS refreshment, this PR also fixes another issue that disableDnsRefreshOnNetworkChange knob in Java engines is not plumbed into native c++ engine.
And the existing …
=> mobile: fix network change tests in CronetHttp3Test

source/extensions/tracers/opentelemetry/samplers/dynatrace/sampling_controller.cc, test/extensions/tracers/opentelemetry/samplers/dynatrace/sampling_controller_test.cc
=> [bp/1.31] dynatracesampler: avoid div by zero (#40220) 

envoy/network/address.h, source/common/network/address_impl.h, test/common/network/address_impl_test.cc, test/mocks/network/mocks.h, tools/spelling/spelling_dictionary.txt
This commit adds the following two methods to the `Ip` interface:
* `isLinkLocalAddress()`
* `isTeredoAddress()`
* `isUniqueLocalAddress()`
* `isSiteLocalAddress()`
These methods will be used by Envoy Mobile to determine IPv6 connectivity on the current network.
=> network: Adds methods to IP address to check if they are in reserved ranges

mobile/library/common/internal_engine.cc
IPv6 probing will now filter out:
* Link-local IP addresses
* Site-local IPv6 addresses
* Unique Local IPv6 addresses
* Teredo addresses
This is the same as Chromium's logic for IPv6 connectivity probing: https://source.chromium.org/chromium/chromium/src/+/main:net/dns/host_resolver_manager.cc;l=1572-1581;drc=d0260a368e65b2be56d179d21fab90976fd494b8.
Though it doesn't seem like Chromium filters out site-local addresses, local testing has shown that the IPv6 probe socket will successfully connect but the local address will be site-local on non-IPv6 networks/machines.
=> mobile: Filter reserved IP address ranges in IPv6 probing

api/envoy/extensions/filters/http/ratelimit/v3/rate_limit.proto, changelogs/current.yaml, source/extensions/filters/http/ratelimit/config.cc, source/extensions/filters/http/ratelimit/ratelimit.cc, source/extensions/filters/http/ratelimit/ratelimit.h, test/extensions/filters/http/ratelimit/ratelimit_test.cc
Commit Message: http ratelimit: Add rate_limits to filter config
This PR adds a new field `rate_limits` to the external rate limit filter which reduces the need of configuring this as part of route or vhost config. This is particularly useful when used in a service mesh (e.g. Istio) setting where users are expected to interact with mesh APIs and not Envoy APIs directly. With this change, we (service mesh providers) can limit user configurability (e.g. users now only need access to insert HTTP Filters rather than change Route or Virtual Host behaviour) to provide better support and safeguard against unintended data plane configurations. This PR is similar to what https://github.com/envoyproxy/envoy/pull/36099 does for local rate limit. I've also seen interest about …
=> http ratelimit: Add rate_limits to filter config

source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc
Commit Message: Avoid an unnecessary string copy in ProxyFilter
Additional Description: This code was changed recently to fix an issue, but it gained a string-copy that's avoidable for any addresses that are not numeric IPv6 addresses.
Risk Level: Negligible.
Testing: Existing tests cover it.
=> Avoid an unnecessary string copy in ProxyFilter

source/common/common/compiler_requirements.h
Commit Message: Bump compiler requirements for C++20
Additional Description: Compiler require C++20 to fail with a nicer error message if using an older compiler. Used https://en.cppreference.com/w/cpp/compiler_support.html#:~:text=Apple%20Clang*-,C%2B%2B20%20features,-C%2B%2B20%20core for reference
Testing: n/a
=> Bump compiler requirements for C++20

source/common/tracing/trace_context_impl.cc, source/common/tracing/trace_context_impl.h, source/extensions/tracers/datadog/dict_util.cc, source/extensions/tracers/fluentd/fluentd_tracer_impl.cc, source/extensions/tracers/opentelemetry/span_context.h, source/extensions/tracers/opentelemetry/span_context_extractor.cc, test/common/tracing/trace_context_impl_test.cc
Commit Message: tracing: support get all to avoid full interation
Added `getAll()` method to the `TraceContextHandler`. Then the opentelemtry/fluentd needn't to iterate the whole header map to find all `tracestate` headers/values.
Testing: n/a.
=> tracing: support get all to avoid full interation

source/extensions/extensions_metadata.yaml
Per notification in the envoy-announce@googlegroups.com the HTTP cache filter security posture is downgraded to unknown to match its work-in-progress status. This removes the filter from the security release process.
Testing: n/a
=> Downgrade HTTP cache filter security posture

source/extensions/filters/common/rbac/engine_impl.cc, source/extensions/filters/common/rbac/engine_impl.h
Commit Message: rbac: only allocate protobuf arena if it CEL is used
Prior to this PR, the protobuf arena would've been allocated for each RBAC configuration, even if CEL wasn't used.
Wrapped the arena and the builder around a single wrapper that will only be allocated if CEL is used.
Testing: N/A
=> rbac: only allocate protobuf arena if it CEL is used

envoy/ssl/BUILD, envoy/ssl/ssl_socket_extended_info.h, test/common/tls/cert_validator/BUILD
For `CertificateSelectionCallbackPtr` type. 
=> Add missing include to ssl_socket_extended_info_interface.h

api/envoy/extensions/filters/http/header_to_metadata/v3/header_to_metadata.proto
This PR have some nits to have proper line breaks and note annotations for the Header-To-Metadata filter docs.
**Current:**
**After This Change:**
---
**Commit Message:** docs: fix H2M filter docs to have proper spacing & breaks
**Additional Description:** Some nits to have proper line breaks and note annotations for the Header-To-Metadata filter docs.
=> docs: fix H2M filter docs to have proper spacing & breaks

changelogs/current.yaml
Minor cleanup in the change logs to apply missing back-ticks.
---
**Commit Message:** changelog: fix typos in the current change logs and clean them up
**Additional Description:** This PR fixes typos in the current change logs and cleans them up. 
=> changelog: fix typos in the current change logs and clean them up

api/envoy/config/core/v3/protocol.proto
This PR fixes a typo in the protocol docs. We misspelled range as "rage".
---
**Commit Message:** docs: fix typo in the protocol docs (rage => range)
**Additional Description:** Fixes a typo in the protocol docs. We misspelled range as "rage.
=> docs: fix typo in the protocol docs (rage => range)

test/integration/udp_tunneling_integration_test.cc
When this test was written, capsule type 0x01 was unknown to Envoy and Google QUICHE, but it had already been assigned to the connect-ip draft, later RFC 9484. RFC 9297, which defines capsules in general, defines capsule types of the form 0x29 * N + 0x17, for integer values of N, as reserved for testing behavior with unknown capsule types. Setting N=0, we can just use 0x17 instead of 0x01 and per the RFC we should never collide with a real capsule assignment again.
https://www.rfc-editor.org/rfc/rfc9484.html#section-12.4
https://www.rfc-editor.org/rfc/rfc9297.html#section-5.4-3
=> Update udp_tunneling_integration_test.cc's unknown capsule type

source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc
=> Simplify the protobuf::BytesValue::set_value call

envoy/http/BUILD, envoy/http/codec.h, envoy/http/codec_runtime_overrides.h, source/common/runtime/BUILD, source/common/runtime/runtime_features.cc, source/common/runtime/runtime_features.h
codec_interface dependency is very heavy and brings in libevent. This prevents WASM modules that need to use runtime facility from compiling with v8 runtime.
=> Remove dependency from runtime to codec

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Adding an integration test to send consecutively large request for ext_proc FULL_DUPLEX_STREAMED mode.
The test includes:
1) sending 30 consecutive HTTP requests
2) Each request contains a 2MB body
3) The request is sending to the ext_proc server.
4) After receives the complete request, the ext_proc server sends back 50 chunks, with 64KB data in each chunk back to Envoy.
=> ext_proc : adding integration test to verify request with large data

api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto, changelogs/current.yaml, source/extensions/filters/http/ext_proc/config.cc, test/extensions/filters/http/ext_proc/config_test.cc
There is a request that to have ext_proc FULL_DUPLEX_STREAMED mode support fail_open to certain stage, like before the 1st chunk of data is shipped to the ext_proc server.   This is doable. 
This PR reverts "Ext_proc: do not support fail_open+FULL_DUPLEX_STREAMED configuraton combination (#39740)", i.e, commit 4861b2057afbc67290da0ec77ae1f1af60f152d0.
A follow up PR will implement the above fail-open behavior.
=> Revert "Ext_proc: do not support fail_open+FULL_DUPLEX_STREAMED configuraton combination (#39740)"

test/coverage.yaml
This PR fixes the coverage numbers for ExtProc. Two previous PRs https://github.com/envoyproxy/envoy/pull/40503 and https://github.com/envoyproxy/envoy/pull/40568 had a race to landing made coverage to fail in CI.
---
Commit Message: coverage: adjusting coverage numbers for ExtProc
Additional Description: Fixes the coverage numbers for ExtProc.
Testing: CI
=> coverage: adjusting coverage numbers for ExtProc

changelogs/current.yaml, source/common/http/conn_pool_grid.cc, source/common/runtime/runtime_features.cc
This PR removes the deprecated reloadable flag `allow_alt_svc_for_ips` and cleans up the legacy paths.
Fix https://github.com/envoyproxy/envoy/issues/39111
---
**Commit Message:** router: deprecate flag allow_alt_svc_for_ips and remove legacy code paths
**Additional Description:** Remove the deprecated reloadable flag `allow_alt_svc_for_ips` and cleans up the legacy paths.
=> http: deprecate flag allow_alt_svc_for_ips and remove legacy code paths

source/extensions/filters/common/rbac/matchers.cc, test/extensions/filters/common/rbac/matchers_test.cc
This PR has a small fix to guard the RBAC LC-Trie based matcher against the non-IP addresses to avoid any crashes. 
---
**Commit Message:** rbac: guard LC-Trie matcher against non-IP addresses
**Additional Description:** A small fix to guard the RBAC LC-Trie based matcher against the non-IP addresses to avoid any crashes.
=> rbac: guard LC-Trie matcher against non-IP addresses

changelogs/current.yaml, docs/root/configuration/http/http_filters/lua_filter.rst, source/extensions/filters/http/lua/lua_filter.cc, source/extensions/filters/http/lua/lua_filter.h, source/extensions/filters/http/lua/wrappers.cc, source/extensions/filters/http/lua/wrappers.h, test/extensions/filters/http/lua/lua_filter_test.cc, test/extensions/filters/http/lua/lua_integration_test.cc, test/extensions/filters/http/lua/wrappers_test.cc
This PR extends the Envoy HTTP Lua filter StreamHandle API by introducing a new `route()` method. This method returns a Route object representing the matched route for the current request.
Initially, the Route object exposes a single method: `metadata()`, which retrieves route metadata scoped to a specific filter name. This enhancement allows Lua scripts to access per-filter route metadata through a dedicated Route object, improving API consistency and paving the way for future extensions.
Currently, route metadata can be accessed via `StreamHandle:metadata()`. However, with the introduction of the Route object, the preferred access pattern becomes `StreamHandle:route():metadata()`. In the long term, the goal is to migrate usage towards this new interface and deprecate the direct …
=> lua: extend StreamHandle API with route() to access matched route metadata

source/extensions/filters/network/generic_proxy/router/upstream.cc, test/extensions/filters/network/generic_proxy/integration_test.cc
Commit Message: generic proxy: ensure downstream connection callbacks removed if bound upstream is closed first
This fixes an issue in the BoundGenericUpstream where the connection callbacks added to the downstream connection can be invoked after the upstream object has been deleted. Specifically, if the client codec sends a frame with FLAG_END_STREAM, then the upstream is disconnected before the frame triggers the downstream connection to be closed, the event that fires after the downstream connection is eventually closed may attempt to invoke callbacks on the BoundGenericUpstream instance after it has already been deleted.
Risk Level: 
Testing: Added an integration test that should cover this case.
=> generic proxy: ensure downstream connection callbacks removed if bound upstream is closed first

source/common/upstream/od_cds_api_impl.cc
Commit Message: odcds: remove dead code
Removing a line of code that cannot be reached.
The `status_` data memebr is internal to the class, and can is only being set by the methods, so an invalid value cannot be set.
Risk Level: low - unused code
Testing: N/A
=> odcds: remove dead code

docs/root/intro/arch_overview/advanced/dynamic_modules.rst
Commit Message: docs: removes 'experimental' from dynamic_modules.rst
The dynamic_modules feature is no longer "experimental" after two Envoy stable releases. It has started being used in production as well, so the word "experimental" is not appropriate. Otherwise, people might think that there might be a breaking change in API, etc as opposed to the fact that it won't happen.
Testing: n/a
=> docs: removes 'experimental' from dynamic_modules.rst

api/envoy/config/core/v3/protocol.proto
Commit Message: Remove QUIC idle_network_timeout upper bound. For a non-front-line proxy, a longer value can be useful.
=> Remove QUIC idle_network_timeout upper bound.

source/common/rds/route_config_provider_manager.h
Commit Message: cleanup: const init of a variable in route_config_provider_manager
Minor cleanup after #40660 - const init of a local variable.
Testing: N/A
=> cleanup: const init of a variable in route_config_provider_manager

.github/workflows/mobile-ios_build.yml, .github/workflows/mobile-release_validation.yml
CI is currently broken, as the `Mobile/iOS` and `Mobile/Release Validation` jobs are failing while trying to start the iOS Simulator 18.1:
```
INFO: Streaming build results to: https://envoy.cluster.engflow.com/invocation/e45b583d-15a6-431a-83f9-32b8b2e73dbb
2025-08-13 21:16:13.962 INFO Creating simulator, device=iPhone 16 Pro Max, version=18.1
Invalid runtime: com.apple.CoreSimulator.SimRuntime.iOS-18-1
2025-08-13 21:16:21.214 ERROR ['/Applications/Xcode_16.1.app/Contents/Developer/usr/bin/simctl', 'create', 'TestDevice', 'iPhone 16 Pro Max', 'com.apple.CoreSimulator.SimRuntime.iOS-18-1'] exited with error code 145
```
CI is still building the iOS binary so we aren't losing too much build coverage.
=> mobile/ci: Temporarily disable running the iOS simulator

changelogs/current.yaml, source/extensions/filters/listener/tls_inspector/tls_inspector.cc, test/extensions/filters/listener/tls_inspector/tls_inspector_integration_test.cc
https://github.com/envoyproxy/envoy/pull/40544
Fix a bug where the `tls_inspector` times out when used with the `http_inspector` and it gets a large client hello.
Envoy was set up with both `http_inspector` and `tls_inspector` present. We noticed `tls_inspector` timing out when receiving a large client hello (>8 KB).
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> [bp/1.34] tls inspector time out fix

changelogs/current.yaml, source/common/runtime/runtime_features.cc, test/common/http/conn_pool_grid_test.cc, test/extensions/filters/http/dynamic_forward_proxy/BUILD, test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
Commit Message: turn off envoy.reloadable_features.http3_happy_eyeballs due to a known issue.
Additional Description: the current implementation favors TCP over QUIC when UDP doesn't work on V6 network but works on V4.
Risk Level: low, only affect mobile
Testing: changed ConnectivityGridTest which was heavily testing the H3 happy eyeball.
Release Notes: Y
=> quic: turn off HTTP/3 happy eyeball

api/envoy/config/core/v3/protocol.proto, changelogs/current.yaml, envoy/http/BUILD, envoy/http/codec.h, source/common/http/http1/BUILD, source/common/http/http1/codec_impl.cc, source/common/http/http1/settings.cc, source/common/http/http1/settings.h, source/common/http/utility.cc, source/common/http/utility.h, source/common/upstream/upstream_impl.cc, source/extensions/filters/network/http_connection_manager/config.cc, source/extensions/upstreams/http/config.cc, source/extensions/upstreams/http/config.h, test/common/http/BUILD, test/common/http/http1/BUILD, test/common/http/http1/codec_impl_test.cc, test/common/http/utility_test.cc, test/integration/integration_test.cc
Fixes https://github.com/envoyproxy/envoy/issues/36305
Add configuration to ignore HTTP/1.1 Upgrade headers . See https://datatracker.ietf.org/doc/html/rfc7230#section-6.7:
(cherry picked from commit ad400974d8114c9f2da6d96a4acf92e6601d5561)
=> [1.32] http: configurable ignore of HTTP/1.1 upgrades (#37642)

mobile/bazel/android_artifacts.bzl, mobile/bazel/test_manifest.xml, mobile/examples/java/hello_world/AndroidManifest.xml, mobile/examples/kotlin/hello_world/AndroidManifest.xml, mobile/examples/kotlin/shared/AndroidManifest.xml, mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidEngineManifest.xml, mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidNetworkMonitor.java, mobile/library/java/io/envoyproxy/envoymobile/engine/AndroidNetworkMonitorV2.java, mobile/library/java/io/envoyproxy/envoymobile/utilities/UtilitiesManifest.xml, mobile/library/java/org/chromium/net/ChromiumNetManifest.xml, mobile/library/java/org/chromium/net/impl/CronvoyManifest.xml, mobile/library/java/org/chromium/net/urlconnection/URLConnectionManifest.xml, mobile/library/kotlin/io/envoyproxy/envoymobile/EnvoyManifest.xml, mobile/test/java/io/envoyproxy/envoymobile/engine/AndroidNetworkMonitorV2Test.java, mobile/test/kotlin/apps/baseline/AndroidManifest.xml, mobile/test/kotlin/apps/experimental/AndroidManifest.xml
Commit Message: added a BroadcastReceiver callback in AndroidNetworkMonitorV2 to listen for default network changes on Android SDK versions below Oreo (API level 26).
Also lower min SDK version from 26 to 23.
Additional Description: AndroidNetworkMonitor also calls `registerDefaultNetworkCallback()` which is only supported on version 24 (N) and above. So this PR has to add version guard around the call. Unfortunately AndroidNetworkMonitor will not handle network change event on devices below version N, but we will replace it with AndroidNetworkMonitorV2 soon.
Testing: new unit test pass
=> mobile: AndroidNetworkMonitorV2 support Android API versions below 26 

ci/README.md, ci/do_ci.sh
This pr updates the documentation to inform new developers how to troubleshoot crashes when building
=> ci: support variable number of CPUs for building

test/extensions/filters/listener/tls_inspector/tls_inspector_integration_test.cc
The comments on the ContinueOnListenerTimeout doesn't make sense.
1. the max length is changed to 16K.
2. the reason is also not correct.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> tls inspector test: change the test description for ContinueOnListenerTimeout

contrib/postgres_proxy/filters/network/test/postgres_decoder_test.cc, envoy/buffer/buffer.h, envoy/http/filter.h, source/common/buffer/buffer_impl.h, source/common/buffer/watermark_buffer.cc, source/common/buffer/watermark_buffer.h, source/common/http/async_client_impl.h, source/common/http/filter_manager.cc, source/common/http/filter_manager.h, source/common/tcp_proxy/tcp_proxy.h, test/common/buffer/buffer_fuzz.cc, test/common/buffer/watermark_buffer_test.cc, test/integration/tracked_watermark_buffer.cc, test/integration/tracked_watermark_buffer.h, test/mocks/http/mocks.h
This is needed to support the new `request_body_buffer_limit` route configuration.
WatermarkBufferTest.OverflowWatermarkDisabledOnVeryHighValue had to be refactored to not used allocations as it is no longer practical with 64 bit limit and 32 bit multiplier.
=> Use uint64_t for buffer watermark values

bazel/external/quiche.BUILD, envoy/common/conn_pool.h, envoy/upstream/cluster_manager.h, mobile/library/common/internal_engine.cc, mobile/library/common/network/connectivity_manager.cc, mobile/test/common/network/connectivity_manager_test.cc, source/common/http/http3/conn_pool.h, source/common/quic/client_connection_factory_impl.cc, source/common/quic/client_connection_factory_impl.h, source/common/upstream/cluster_manager_impl.cc, source/common/upstream/cluster_manager_impl.h, test/common/http/http3/conn_pool_test.cc, test/integration/http_conn_pool_integration_test.cc, test/mocks/upstream/cluster_manager.h, tools/spelling/spelling_dictionary.txt
Commit Message: Introduces new enum value `ConnectionPool::DrainBehavior::DrainExistingNonMigratableConnections`. When this behavior is used, HTTP/3 connection pools will only drain existing connections if QUIC connection migration is not enabled. 
The mobile engine is updated to use this new drain behavior when DNS refreshing is disabled on network changes, allowing migratable QUIC connections to persist across network transitions.
Additional Description: also add QUICHE migration code into build target
Risk Level: low, the new behavior is disabled
Testing: new unit test pass
=> upstream: introduce new drain behavior DrainExistingNonMigratableConnections

api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto, changelogs/current.yaml, source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc, source/extensions/filters/common/ext_authz/ext_authz_http_impl.h, source/extensions/filters/http/ext_authz/config.cc, source/extensions/filters/http/ext_authz/ext_authz.cc, source/extensions/filters/http/ext_authz/ext_authz.h, test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc, test/extensions/filters/http/ext_authz/config_test.cc, test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc, test/extensions/filters/http/ext_authz/ext_authz_test.cc
This PR re-applies the [ext_authz commit](https://github.com/envoyproxy/envoy/commit/8c03b2aac400361f89183ab3736864087a3557cf) including the test fixes. The change was reverted due to a flaky/failing test as the PR to address the test wasn't merged on time and we had to unblock the CI.
---
Commit Message: **Reapply "ext_authz: add grpc_service field on the per-route filter"**
**Additional Description:** Reapplies the ext_authz change including the test fixes.
=> Reapply "ext_authz: add grpc_service field on the per-route filter"

test/common/upstream/BUILD, test/common/upstream/upstream_impl_test.cc
Commit Message: Use gmock mock functions for testing callbacks
Additional Description: This is a testing-the-waters PR, is this change desirable? If so I'll do the same to the rest of the file. The main hope is that a good example existing would propagate next time someone cargo-cults "how do I test this kind of thing".
(This change also slightly improves the test behavior in that now it only passes if the initialize callback is called during `initialize`, where before the test would also have passed if the initialize callback was called during `dns_callback_`. This distinction seems like it might be important based on the name of the test case and the comment `Initialized without completing DNS resolution.`.)
Risk Level: test-only
Testing: test-only …
=> Use gmock mock functions for testing callbacks

source/extensions/io_socket/user_space/io_handle.h, source/extensions/io_socket/user_space/io_handle_impl.cc, source/extensions/io_socket/user_space/io_handle_impl.h, test/extensions/io_socket/user_space/io_handle_impl_test.cc
Commit Message: userspace socket: allow providing an existing PassthroughState when creating IoHandle pair
This change is to allow extensions to provide their own implementation of PassthroughState and/or derive from the default PassthroughStateImpl when creating userspace IoHandle pairs with the IoHandleFactory. 
Risk Level: Low; changes are backwards compatible
Testing: Unit tests added
Docs Changes:
Release Notes:
=> userspace socket: allow providing an existing PassthroughState when creating IoHandle pair

bazel/dependency_imports.bzl
Commit Message: deps: upgrading GO to v1.24.6 in dependency_imports.bzl
Attempt to solve the issue that has been seen today in some PRs:
```
compilepkg: missing strict dependencies:
/mnt/engflow/worker/work/3/exec/external/org_golang_google_grpc/internal/status/status.go: import of "google.golang.org/genproto/googleapis/rpc/status"
```
([example](https://github.com/envoyproxy/envoy/actions/runs/17246350777/job/48936907349#step:17:601))
Testing: N/A
=> deps: upgrading GO to v1.24.6 in dependency_imports.bzl

source/extensions/dynamic_modules/sdk/rust/src/lib.rs, source/extensions/dynamic_modules/sdk/rust/src/lib_test.rs, test/extensions/dynamic_modules/test_data/rust/http.rs, test/extensions/dynamic_modules/test_data/rust/http_integration_test.rs, test/extensions/dynamic_modules/test_data/rust/no_op.rs
Commit Message: dynamic_modules: make sure rust's new_http_filter entrypoint matches the c abi
Additional Description: Currently, for the second argument `filter_envoy_ptr` of the `envoy_dynamic_module_on_http_filter_new` entrypoint, the Rust `new_http_filter` function expects to take a pointer to `DynamicModuleHttpFilterConfig` but should take in `DynamicModuleHttpFilter` as declared in the [C abi](https://github.com/envoyproxy/envoy/blob/55f965713e99769c729f87680c7349fd2307f6b7/source/extensions/dynamic_modules/abi.h#L571-L573).
Testing: N/A
=> dynamic_modules: make sure rust's new_http_filter entrypoint matches the c abi

api/envoy/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.proto, source/extensions/network/dns_resolver/cares/dns_impl.cc, source/extensions/network/dns_resolver/cares/dns_impl.h, test/extensions/network/dns_resolver/cares/dns_impl_test.cc
Implementation for https://github.com/envoyproxy/envoy/issues/40696
Currently dns response size is 1232 on UDP support as per c-ares lib(https://github.com/c-ares/c-ares/blob/main/src/lib/ares_private.h#L133) on EDNS0. we can provide the option via envoy filters to customise the size as per end user needs like 4096, etc.
[optional Relevant Links:]
Any extra documentation required to understand the issue.
https://datatracker.ietf.org/doc/html/rfc6891
**Sample Service Entry for testing:**
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
name: external-svc-https
spec:
hosts:
- example.com
location: MESH_EXTERNAL
ports:
- number: 443
name: https
protocol: TLS
resolution: DNS
```
**Sample Envoy filter tested with:**
```
apiVersion: networking.istio.io/v1alpha3
kind: …
```
=> dns: adding support for edns0 size customisation via envoy filters

test/extensions/filters/http/ext_authz/BUILD, test/extensions/filters/http/ext_authz/ext_authz.yaml, test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
This is a follow up of https://github.com/envoyproxy/envoy/pull/40894
It's the 3rd step to address: https://github.com/envoyproxy/envoy/issues/39900
=> Replace c-ares with getaddrinfo DNS resolver in ext_authz filter integration test

test/common/event/BUILD, test/common/event/dispatcher_impl_test.cc
Commit Message: More ReadyWatchers to MockFunction in test
Additional Description: Cleaning up more awkward ReadyWatcher constructs in favor of idiomatic MockFunction. Test-only.
=> More ReadyWatchers to MockFunction in test

test/server/api_listener_test.cc
This PR improves the test coverage for API Listener by adding more tests for the missing cases.
**Before:**
source/extensions/api_listeners/default_api_listener: 59%
**After:**
source/extensions/api_listeners/default_api_listener: 68.2%
---
**Commit Message:** api_listener: improve test coverage
**Additional Description:** Improves the test coverage for API Listener by adding more tests for the missing cases.
=> api_listener: improve test coverage

changelogs/current.yaml, source/common/config/well_known_names.cc, test/common/stats/tag_extractor_impl_test.cc
Commit Message: stats: fix a bug where the prometheus name of ssl certificate stats are wrong 
See #40891
Testing: unit.
=> stats: fix a bug where the prometheus name of ssl certificate stats are wrong (#40891)

ci/docker-compose.yml
It was silently removed after https://github.com/envoyproxy/envoy/pull/40541
While it was removed in main and in 1.35, it's still used by CI in 1.33.
=> [1.33] Restore `ENVOY_STDLIB` variable

ci/docker-compose.yml
It was silently removed after https://github.com/envoyproxy/envoy/pull/40540
While it was removed in main and in 1.35, it's still used by CI in 1.32.
=> [1.32] Restore `ENVOY_STDLIB` variable

test/extensions/transport_sockets/http_11_proxy/BUILD, test/extensions/transport_sockets/http_11_proxy/connect_integration_test.cc
This is a follow up of https://github.com/envoyproxy/envoy/pull/40896
It's the 5th step to address: https://github.com/envoyproxy/envoy/issues/39900
=> Replace c-ares with getaddrinfo DNS resolver in connect_integration_test

test/common/tls/context_impl_test.cc
Envoy has logic to reject P-224, but newer versions of BoringSSL reject it in `SSL_CTX` before Envoy's logic runs. Fix the test expectation to accept both paths.
(It was already not possible to use a P-224 TLS key in BoringSSL because we didn't recognize the P-224 NamedCurve codepoint in TLS 1.2, and there is no P-224 SignatureScheme codepoint in TLS 1.3. BoringSSL just didn't notice in SSL_CTX_use_certificate before.)
Risk Level: none, this is a test-only change
Testing: run the test changed in this test-only change
Docs Changes: no, this is a test only change
Release Notes: no, this is a test only change
Platform Specific Features: no, this is a test only change
[Optional Runtime guard:] no, this is a test only change
[Optional Fixes #Issue] no, …
=> tls: future-proof UnsupportedCurveEcdsaCert's test expectation

changelogs/current.yaml, distribution/docker/Dockerfile-envoy
=> [bp/1.32] docker/release: Fix distroless hash to use nonroot (#40956)

test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Fix https://github.com/envoyproxy/envoy/issues/36041
=> ext_proc: increasing tracing integration test timeout to be 1s to avoid flaky

changelogs/current.yaml, changelogs/summary.md, distribution/docker/Dockerfile-envoy
=> [bp/1.33] docker/release: Fix distroless hash to use nonroot (#40956)

docs/root/configuration/http/http_filters/dynamic_forward_proxy_filter.rst, docs/root/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter.rst
This PR adds docs for the SNI DFP mentioning the stats emission from DNS Cache. 
---
**Commit Message:** docs: add docs for SNI DFP mentioning the stats emission
**Additional Description:** Added docs for the SNI DFP mentioning the stats emission for DNS Cache.
=> docs: add docs for SNI DFP mentioning the stats emission

source/common/tls/utility.cc, test/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator_test.cc
Many of these APIs should be returning const pointers, but return non-const because legacy callers store them in the wrong variables. Fix some of these callers. Also in some cases exposed structs mean the compiler doesn't check const-ness, but it's still good to tag variables as const.
In doing so, this fixes a deeper bug in one of the tests: there is no guarantee that ASN1_STRINGs are NUL-terminated, yet this code was assuming they were. See CVE-2021-3712. Fortunately, this was just in test code, or Envoy would have its own instance of that CVE.
(ASN1_STRING_get0_data is the same as ASN1_STRING_data except it acts on a const pointer.)
Testing: Existing unit tests
=> Const-correct some uses of X509 API

envoy/http/async_client.h, envoy/router/router.h, source/common/http/async_client_impl.cc, source/common/http/async_client_impl.h, source/common/router/BUILD, source/common/router/config_impl.cc, source/common/router/config_impl.h, source/common/router/retry_policy_impl.cc, source/common/router/retry_policy_impl.h, test/common/http/async_client_impl_test.cc
Commit Message: async stream options: use shared pointer for pased retry policy
This PR updated the StreamOptions. The shared pointer of RetryPolicy is used rather than a reference to avoid potential lifetime problem.
This also fixed a potential bug at the `Http::AsyncStreamImpl`. At there, if the parsing of proto retry policy is field, will result in core dump.
Testing: n/a.
=> async stream options: use shared pointer for pased retry policy

test/extensions/network/dns_resolver/cares/BUILD, test/extensions/network/dns_resolver/cares/dns_impl_integration_test.cc
This is a follow up of https://github.com/envoyproxy/envoy/pull/40938
It's the 7th step to address: https://github.com/envoyproxy/envoy/issues/39900
While we are trying to remove c-ares from integration tests in different components, this PR adds back a couple c-ares integration test cases under c-ares extension to make sure c-ares DNS resolving is covered in integration test.
=> Adding c-ares DNS resolving integration test under extension specific folder

source/common/common/logger.cc, source/common/common/logger.h, test/common/common/logger_test.cc
Change-Id: I9b006e2adf96aa3c109d084ed705c3854b567766
Commit Message: dead code. Maybe some distributors use it? Not clear what the value of a thread-local log sink is.
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> logs: remove unused tls delegate

tools/repo/notify.py
Commit Message: tools: update the notifier tool calendar link
Fixing the notifier tool calendar link to point to a new Envoy maintainers rotation on-call calendar.
Also added instructions on how to repro this, if needed in the future.
Validated by executing `bazel run //tools/repo:notify -- --dry_run`, and getting the following relevant info:
```
RepoNotifier NOTICE Slack message (#envoy-maintainer-oncall):
Oncall now <@U5CALEVSL>
```
which maps to this week's oncaller
Risk Level: low - tools only
=> tools: update the notifier tool calendar link

envoy/access_log/access_log_config.h, source/common/access_log/access_log_impl.cc, source/common/access_log/access_log_impl.h, source/common/quic/envoy_quic_dispatcher.cc, source/extensions/access_loggers/common/stream_access_log_common_impl.h, source/extensions/access_loggers/file/config.cc, source/extensions/access_loggers/file/config.h, source/extensions/access_loggers/filters/cel/config.cc, source/extensions/access_loggers/filters/cel/config.h, source/extensions/access_loggers/fluentd/config.cc, source/extensions/access_loggers/fluentd/config.h, source/extensions/access_loggers/grpc/http_config.cc, source/extensions/access_loggers/grpc/http_config.h, source/extensions/access_loggers/grpc/tcp_config.cc, source/extensions/access_loggers/grpc/tcp_config.h, source/extensions/access_loggers/open_telemetry/config.cc, source/extensions/access_loggers/open_telemetry/config.h, source/extensions/access_loggers/stream/config.cc, source/extensions/access_loggers/stream/config.h, source/extensions/access_loggers/wasm/config.cc, source/extensions/access_loggers/wasm/config.h, test/common/access_log/access_log_impl_test.cc, test/extensions/filters/network/generic_proxy/fake_codec.h, test/integration/fake_access_log.h, test/integration/typed_metadata_integration_test.cc
Change-Id: Ie17a21068efdfba87dbe9375672b864c4cc52a51
Commit Message: Move access log factory to use generic context. This will allow using it in non-listener contexts (upstream logs, side request logs, application logs, ECDS logs). While at it, find and fix a bug in Quic listener not setting the listener info.
Additional Description: Also move access log filter to use generic context. In almost all cases, server context is enough for both apart from validation - the one exception is Wasm which has other issues.
Risk Level: low, no functional change.
Testing: passed
Docs Changes: none, internal change
=> access log: use generic factory context

api/envoy/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.proto
There is a small bug in `edns0_max_payload_size` docs where it skips the first two lines and only renders the docs after `Recommend Values:` due to missing `//` on the line above. This PR fixes the bug so that the docs renders correctly.
It's missing: _"Maximum EDNS0 UDP payload size in bytes. If set, c-ares will include EDNS0 in DNS queries and use this value as the maximum UDP response size."_
---
**Commit Message:** docs: fix DNS docs for edns0_max_payload_size
**Additional Description:** Fixes the bug in the `edns0_max_payload_size` docs.
=> docs: fix DNS docs for edns0_max_payload_size

api/envoy/extensions/filters/http/ext_proc/v3/BUILD, api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto, api/envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto, api/envoy/service/ext_proc/v3/external_processor.proto
Commit Message: xDS: improve documentation for ext_proc
Additional Description: Made a number of documentation changes:
- Removed lingering references to async mode, which was replaced with observability mode.
- Document that message timeouts are not supported in `FULL_DUPLEX_STREAMED` body send mode.
- Document that mode override is not supported in `FULL_DUPLEX_STREAMED` body send mode.
- Clarify that in observability mode, the body is not sent if body send mode is something other than `STREAMED`.
- Changed wording to clarify that the client may not be Envoy, since gRPC will soon be adding ext_proc support.
Testing: N/A
=> xDS: improve documentation for ext_proc

test/extensions/filters/network/redis_proxy/BUILD, test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc
This is a follow up of https://github.com/envoyproxy/envoy/pull/41097
It's the 12th step to address: https://github.com/envoyproxy/envoy/issues/39900
=> Replace c-ares library with getaddrinfo DNS library in redis_proxy network filter integration test

test/extensions/clusters/redis/BUILD, test/extensions/clusters/redis/redis_cluster_integration_test.cc
This is a follow up of https://github.com/envoyproxy/envoy/pull/41031
It's the 9th step to address: https://github.com/envoyproxy/envoy/issues/39900
=> Replace c-ares library with getaddrinfo DNS library in redis_cluster_integration_test

ci/do_ci.sh
Mimic the behavior of clang; Building first might catch build and dependencies failures earlier.
=> [bp/1.33] ci: gcc: Build before testing

api/envoy/extensions/filters/http/ext_proc/v3/BUILD, api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto, changelogs/current.yaml, envoy/http/codes.h, source/common/http/codes.cc, source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, test/extensions/filters/http/ext_proc/BUILD, test/extensions/filters/http/ext_proc/config_test.cc, test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc, test/extensions/filters/http/ext_proc/filter_test.cc
This PR adds a new `status_on_error` in ExtProc similar to what we [have for ExtAuthZ](https://arc.net/l/quote/zoibcqsy) which could be used to control the status code returned back to the user in case of failures. users can have some flow in which they expect a different status code to be returned for failures instead of the hardcoded **500 Internal Server Error**.
---
**Commit Message:** ext_proc: add status_on_error option to control the status code returned
**Additional Description:** Added a new `status_on_error` in ExtProc to control the HTTP status code returned back to the user in case of failures.
**Testing:** Added Integration Tests & Unit Tests
=> ext_proc: add status_on_error option to control the status code returned

mobile/library/common/logger/logger_delegate.cc, test/integration/alpn_integration_test.cc, test/integration/api_listener_integration_test.cc, test/integration/autonomous_upstream.cc, test/integration/base_integration_test.cc, test/integration/buffer_accounting_integration_test.cc, test/integration/fake_upstream.cc
Replace deprecated absl::MutexLock::MutexLock(Mutex*) constructor with absl::MutexLock::MutexLock(Mutex&)
=> Use mutex reference in lock constructors p2

changelogs/current.yaml, source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc, source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.h, test/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter_test.cc
Commit Message: [json_transcoder_filter] Cap grpc stream frame size
Additional Description: If the downstream sends data quickly enough, a `decodeData` buffer can contain over 4MB. The upstream grpc service by default will respond with an error if it receives such a frame, that error is surprisingly mapped to a 429 by envoy, and the upstream service won't see it because the grpc library never delivered it, which makes it very difficult to figure out what happened.
This change makes it so if the `decodeData` buffer is larger than 1MB while streaming, the buffer is broken into 1MB pieces, thereby avoiding that error (and completing an ancient TODO).
This is a behavior change, but should be largely indistinguishable from previous behavior as there are no guarantees about how many buffers the …
=> [json_transcoder_filter] Cap grpc stream frame size

changelogs/current.yaml
This PR fixes the changelog style and clean it up. There are a few issues with the styling and rendering.
---
**Commit Message:** changelog: fix typos in the current changelogs and clean them up
**Additional Description:** This PR fixes the changelog style and clean it up.
=> changelog: fix typos in the current changelogs and clean them up

.gitattributes
this causes more problems than it solves and seems to break dependabot
=> python: Remove requirements.txt entry from .gitattributes

changelogs/current.yaml, source/extensions/filters/network/rbac/rbac_filter.cc, test/extensions/filters/network/rbac/filter_test.cc
This PR enables the use of `NetworkNamespaceInput` in the RBAC filter to be able to match on the incoming network namespace and do RBAC enforcement based on that.
---
**Commit Message:** rbac: enable use of NetworkNamespaceInput in network RBAC filter
**Additional Description:** Enable `NetworkNamespaceInput` to be used in the Network RBAC filter.
=> rbac: enable use of NetworkNamespaceInput in network RBAC filter

test/extensions/filters/network/ext_proc/ext_proc_integration_test.cc
The TCP read can be partial, improve the integration tests to consider this to eliminate flaky.
Testing:
=> network ext_proc: improve the test to consider TCP fragmentation

source/common/matcher/list_matcher.h
Commit Message: list-matcher: replace push_back with emplace_back
Minor refactor that uses vector `emplace_back()` instead of `push_back()`.
Testing: N/A
=> list-matcher: replace push_back with emplace_back

docs/root/configuration/http/http_filters/ext_authz_filter.rst
This PR fixes the incorrect indentation and also also resolve some minor nits on the ExtAuthZ external docs.
---
**Commit Message:** docs: fix the incorrect indentation on ExtAuthZ external docs
**Additional Description:** Fixes the incorrect indentation and some minor nits on the ExtAuthZ external docs.
=> docs: fix the incorrect indentation on ExtAuthZ external docs

.bazelrc, bazel/external/quiche.bzl, bazel/v8.patch
Envoy is built by various platform and compiler combinations, and some of those produce warnings in quiche and v8 builds. This should not prevent those builds from succeeding.
Cherry-pick of https://github.com/envoyproxy/envoy/pull/41130
=> [bp/v1.35] build: set -Wno-error in quiche and v8 dep builds

bazel/repositories.bzl
[This PR](https://github.com/envoyproxy/envoy/pull/39728) moved the Go dependency in FIPS builds to a Bazel `http_archive`. Once that was done, Bazel's `filegroup` doesn't seem to be dealing so well with non-UTF-8 characters present in a file name in Go's test suite, causing the build to fail. 
```
#23 170.8 ERROR: /build/top/BUILD/envoy/build/bazel_root/base/external/boringssl_fips/BUILD.bazel:70:8: Executing genrule @@boringssl_fips//:build failed: error reading file '@@fips_go_linux_amd64//:test/fixedbugs/issue27836.dir/Þmain.go': /build/top/BUILD/envoy/build/bazel_root/base/external/fips_go_linux_amd64/test/fixedbugs/issue27836.dir/Þmain.go (No such file or directory)
#23 170.8 ERROR: /build/top/BUILD/envoy/build/bazel_root/base/external/boringssl_fips/BUILD.bazel:70:8: Executing …
```
=> Fix for broken FIPS builds

source/server/options_impl.cc, source/server/server.cc, test/server/options_impl_test.cc, test/server/server_test.cc, test/server/test_data/server/deprecated_runtime_key_bootstrap.yaml
Commit Message: enhance `skip_deprecated_logs` for deprecated runtime key warning 
Additional Description: Enhances the existing skip_deprecated_logs functionality to conditionally log the deprecated runtime key warning in server.cc, following the same pattern as message_validator_impl.cc.
Also extends skip_deprecated_logs support to options_impl.cc for consistent deprecated warning suppression across the codebase. 
Testing: Added unit tests for skip_deprecated_logs functionality covering both server runtime key warnings and options_impl command-line flag warnings. Tests verify both positive (warning logged) and negative (warning suppressed) scenarios. All tests pass successfully. …
=> server: enhance skip_deprecated_logs for deprecated runtime key warning

tools/base/requirements.txt
- Append the observed cryptography==46.0.1 macOS universal2 wheel sha256 to requirements.txt
- Unblocks bazel docs build on macOS without Docker (rules_python --require-hashes)
Required this to be able to build docs locally on my mac for PR https://github.com/envoyproxy/envoy/pull/41251
Testing: n/a
=> tools(base): add macOS wheel hash for cryptography to fix local docs build

api/envoy/config/endpoint/v3/load_report.proto
Change-Id: I2d861b9cba0eba35f3b6552fc319b9444d7de793
Commit Message: it turns out TCP connection is an LRS request 
Risk Level:
Testing:
Docs Changes:
Release Notes:
=> docs: clarify LRS load

source/common/router/BUILD
Commit Message: the target should expose the .h file as headers rather than resources. Otherwise its dependent targets will fail C++ layering check.
Testing: N/A
=> fix build target upstream_to_downstream_impl_base

changelogs/current.yaml, envoy/http/async_client.h, source/common/http/async_client_impl.cc, source/common/http/async_client_impl.h, test/common/http/async_client_impl_test.cc
Add `setUpstreamOverrideHost` method to `AsyncClient::StreamOptions` to enable applications to bypass load balancer selection and route requests directly to specific upstream hosts. This supports use cases like consistent hashing, sticky sessions, and stateful service routing.
Risk Level: Low ?
=> http: implement setUpstreamOverrideHost for AsyncClient

bazel/BUILD
The bazel bug that motivated it is fixed already.
Reverts f155eaac66fc23cd3e1a7bf5c4ec2309d308dbb1
=> Revert gcc detection workaround

source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc, test/extensions/filters/http/grpc_json_transcoder/grpc_json_transcoder_integration_test.cc
Commit Message: Make grpc_json_transcoder_filter correctly handle empty decodeData
Additional Description: The symptom without this fix is upstreams start flakily declaring that the client cancelled the stream, for us this was about one request in twenty, of `HttpBody` styled streaming grpcs. I think the amount it flakes depends to some extent on the behavior of the downstream, as whether a request of this form comes in as headers-with-end-stream or headers-without-end-stream-then-empty-body-with-end-stream is determined by the outcome of a race. This bug was introduced by me in #41115.
Risk Level: Negative.
Testing:
New test before fix:
```
[ RUN      ] IpVersions/GrpcJsonTranscoderIntegrationTest.EmptyMessagePost/IPv4
test/extensions/filters/http/grpc_json_transcoder/grpc_json_transcoder …
```
=> Make grpc_json_transcoder_filter correctly handle empty decodeData

changelogs/current.yaml, docs/root/configuration/other_features/reverse_tunnel.rst
This PR adds a release note for the Reverse Tunnel feature linking the architecture docs.
Fix https://github.com/envoyproxy/envoy/issues/33320
---
**Commit Message:** docs: add release note for reverse tunnels
**Additional Description:** Adds a release note for the Reverse Tunnel feature linking the architecture docs.
Release Notes: **N/A**
=> docs: add release note for reverse tunnels

changelogs/current.yaml, source/extensions/filters/http/ext_proc/ext_proc.cc, source/extensions/filters/http/ext_proc/ext_proc.h, source/extensions/filters/http/ext_proc/processing_request_modifier.h
Commit Message: Cleanup unused class ImmediateMutationChecker and destructor ProcessingRequestModifierFactory
Additional Description: This code is not invoked and is causing ext_proc coverage tests to fail. Clean-up suggested by Adi and Yanjun in https://github.com/envoyproxy/envoy/pull/41295. ImmediateMutationChecker is not needed any more after the runtime guard added in https://github.com/envoyproxy/envoy/pull/27925 is removed.
Release Notes: Ext Proc: Removed unused class ImmediateMutationChecker and unused destructor ProcessingRequestModifierFactory()
/assign @yanjunxiang-google
/assign @adisuissa
=> ExtProc: Cleanup unused class ImmediateMutationChecker and destructor ProcessingRequestModifierFactory

docs/root/intro/arch_overview/advanced/attributes.rst, source/extensions/filters/common/expr/context.cc, source/extensions/filters/common/expr/context.h, test/extensions/filters/common/expr/context_test.cc
Commit Message: add support for uint64 cel-expression upstream.num_endpoints
Additional Description: This could be very useful when extension execution depends on endpoints status, esp when backend endpoints could be dynamically wake-up by requests. 
Risk Level: LOW (no prod usage)
Docs Changes:
Release Notes:
=> add support for uint64 cel-expression upstream.num_endpoints

bazel/external/boringssl_fips.BUILD, bazel/external/boringssl_fips.genrule_cmd, bazel/external/fips_build.bzl
as the policy for these deps is "latest stable" - these validations are incorrect - removing them makes it easier to keep the deps up-to-date with latest stable
=> bazel/fips: Remove incorrect version validation

.bazelrc, .github/config.yml, .github/workflows/envoy-dependency.yml, ci/README.md, ci/docker-compose.yml, mobile/third_party/rbe_configs/config/BUILD
Using the fully qualified name avoids ambiguity and works better with other container tools such as podman.
=> Use the `docker.io/` prefix for docker images where applicable

.github/workflows/envoy-sync.yml
By removing unused branches and downstream repos.
=> Cleanup the envoy-sync GitHub workflow

test/extensions/filters/network/reverse_tunnel/integration_test.cc
This PR fixes the flaky integration test for Reverse Tunnels.
Fix https://github.com/envoyproxy/envoy/issues/41406
---
**Commit Message:** fix: fixes a flaky integration test for reverse tunnels
**Additional Description:** Fixes the flaky integration test for Reverse Tunnels.
=> fix: fixes a flaky integration test for reverse tunnels
